### ISSUE TITLE
Start without Debugging on project context menu

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#101]
_From @davkean on March 24, 2016 18:13_

UserVoice: https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/2267061-add-a-start-without-debugging-option-for-individua

_Copied from original issue: dotnet/roslyn#10073_

**Comment by davkean** [comment]
Microsofties, PR for this: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/223369?_a=overview.

**Comment by davkean** [comment]
see src\debugger\vsdebug\package\vspkg.cpp where it handles: cmdidStartNoDebug. Change StartWithoutDebugging so that it takes a bool indicating whether to choose selected project.

**Comment by kvenkatrajan** [comment]
Start without Debugging is available on the project context menu. Closing ticket.
