### ISSUE TITLE
Rename prompt should respect UI suppression for automation at the time when the operation was invoked

### ISSUE THREAD

**Issue by adrianvmsft** [dotnet/project-system#1020]
Issue #408 added support for UI suppression.
However that code gets executed async and if you want UI suppression to be scoped to that particular rename operation, there is no good way to do that.
Also, there is no good way to know when to stop the UI suppression.

Here is a repro:
- Create new Extensibility -> VSIX Project
- Add New Item -> Extensibility -> Custom Command
Insert the following code inside MenuItemCallback in Command1.cs (after the Message Box) - it renames the selected item in the solution explorer to something similar to fooNN.cs (where NN is a number)
```CSharp
var dte = this.ServiceProvider.GetService(typeof(SDTE)) as EnvDTE.DTE;
string newName = string.Format("foo{0}.cs", DateTime.Now.Second);

var extensibility = this.ServiceProvider.GetService(typeof(EnvDTE.IVsExtensibility)) as IVsExtensibility3;
extensibility.EnterAutomationFunction();
dte.SelectedItems.Item(1).ProjectItem.Name = newName;
extensibility.ExitAutomationFunction();
```
- Ctrl + F5
- Create .Net Core project
- Select Program.cs (as the extension code above renames the selected item)
- Main Menu-> Tools -> Invoke Command1 -> Program.cs will be renamed to something similar to foo24.cs
**Expected:** no rename prompt
**Actual:** you still get the rename prompt

What I think happens is by the time the rename detection logic gets executed, extension code has already exited the automation function. Ideally, that logic should maintain the context that existed at the invocation time

**Comment by tmeschter** [comment]
Blocked waiting for fixes on the CPS side. See #2852 for details.
