### ISSUE TITLE
Duplicate declaration of CSharp PropertyPageSchemas both in MPS and MSBuild

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/project-system#1028]
Exhibit A:
https://github.com/dotnet/roslyn-project-system/blob/master/src/Targets/Microsoft.CSharp.DesignTime.targets#L21-L31

Exhibit B:
https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeTasks/Microsoft.CSharp.CurrentVersion.targets#L49-L59

I'm curious if somehow the items defined by MSBuild are turned off in Roslyn Project System? Because I'm getting this from the CPS trace logger (hosting in my own host):

```
Project item <PropertyPageSchema Include="C:\Ide\bin\Debug\Rules\CSharp.BrowseObject.xaml" /> appears multiple times in the file.  Use only one item to represent a rule file and utilize a semicolon-delimited list for the Context metadata.
Project item <PropertyPageSchema Include="C:\Ide\bin\Debug\Rules\CSharp.xaml" /> appears multiple times in the file.  Use only one item to represent a rule file and utilize a semicolon-delimited list for the Context metadata.
Project item <PropertyPageSchema Include="C:\Ide\bin\Debug\Rules\CSharp.ProjectItemsSchema.xaml" /> appears multiple times in the file.  Use only one item to represent a rule file and utilize a semicolon-delimited list for the Context metadata.
Project item <PropertyPageSchema Include="C:\Ide\bin\Debug\Rules\CSharp.BrowseObject.xaml" /> appears multiple times in the file.  Use only one item to represent a rule file and utilize a semicolon-delimited list for the Context metadata.
Project item <PropertyPageSchema Include="C:\Ide\bin\Debug\Rules\CSharp.xaml" /> appears multiple times in the file.  Use only one item to represent a rule file and utilize a semicolon-delimited list for the Context metadata.
Project item <PropertyPageSchema Include="C:\Ide\bin\Debug\Rules\CSharp.ProjectItemsSchema.xaml" /> appears multiple times in the file.  Use only one item to represent a rule file and utilize a semicolon-delimited list for the Context metadata.
```

I wonder if its benign.

**Comment by davkean** [comment]
"MPS", I like.

**Comment by srivatsn** [comment]
For all the rules that come from Common.CurrentVersion.targets, there's a flag to turn them off and we set that [here](https://github.com/dotnet/roslyn-project-system/blob/master/src/Targets/Microsoft.Managed.DesignTime.targets#L12) We should make CSharp.CurrentVersion.targets respect that flag as well.

**Comment by KirillOsenkov** [comment]
Yes but from what it looks like this may require an MSBuild change because they don't seem to provide a way to turn their stuff off. That part of the file (ItemGroup) is unconditional.

/cc @RainerSigwald @AndyGerlicher

**Comment by srivatsn** [comment]
Fixed by https://github.com/dotnet/project-system/pull/1924
