### ISSUE TITLE
Visual Studio editor coloring lag

### ISSUE THREAD

**Issue by wjk** [dotnet/project-system#1057]
When I edit a .NET Core project in Visual Studio 2017 RC (version 15.0.26014.0), the syntax coloring in the editor is laggy. While screenshots might illustrate this issue better, it is rather difficult to provide them, due to the extremely small time period when it is evident. When I type code into a C# file in my .NET Core project, the syntax coloring does not update to reflect the code just entered until I stop typing and wait for a second. Furthermore, depending on where the insertion point was when I started typing, the coloring might "bleed" a bit until I pause to let VS catch up. (For example, in the text `int loopCounter`, when the word "int" is already colored as a keyword, the word "loopCounter" might also appear colored as if it was a keyword until I pause, at which time VS recolors it as an identifier. Another example would be when I type the braces in a `$""` interpolated string, the braces and the contents are still colored as a string until I pause.) This is very subtle, but just noticeable enough to be annoying.

I am quite certain that the bug lies somewhere within this repo or within Roslyn, because it does not occur when editing C# code in a project that targets .NET Framework, and uses the old C++-based project system. (A Windows Forms application is a good example of such a project.)

**Comment by davkean** [comment]
What kind of project are you writing? It is targeting multiple frameworks?

**Comment by wjk** [comment]
I am only targeting `netcoreapp1.0`. This occurs in both command-line tool and in library projects.

**Comment by davkean** [comment]
Thanks we'll investigate.

**Comment by mavasani** [comment]
I tried for a while to try and repro this in a default .Net Core console app on the latest D15Rel build, but I am unable to repro it. I am wondering if this repros only in certain context. @wjk will it be possible to provide a repro project where you are experiencing this?

**Comment by wjk** [comment]
@mavasani It has been a while since I have done any .NET Core development. My college term has just started, and I must now give priority to my classwork over my personal projects. However, I have updated Visual Studio several times since I last saw this bug; it may have been fixed since. I'll try to get back to you soon with updated information and/or a repro. Thanks!

**Comment by mavasani** [comment]
Thanks @wjk. Unfortunately, there is nothing actionable here without a trace/repro. I'll keep a close eye on this experience and reactivate this bug if I see this while dogfooding.

**Comment by wjk** [comment]
@mavasani This behavior is still occurring, even on the latest Visual Studio build. The delay before coloring is applied has decreased, but it is still noticeable. I will try to create a repro project sometime today. Could this bug be reopened? Thanks!

**Comment by wjk** [comment]
[I have created a repro](https://github.com/dotnet/roslyn-project-system/files/737787/EditorBugRepro.zip). Load it in VS2017 (I am using build 26127.0), open the `Program.cs` file, and type into the `formattedString` as instructed by the comments.

I also have one theory as to why this issue is not appearing for you: I always create my .NET Core projects by way of `dotnet new` at a command prompt; I then hand-edit them slightly if needed, and only then do I add them to the Visual Studio solution. This bug may well not occur if you create the .NET Core project using File > Add > New Project. Thanks for looking into this for me!

**Comment by mavasani** [comment]
Thanks, I'll look into it.

**Comment by mavasani** [comment]
@wjk I am still unable to repro this on 26130. As soon as I close the ending brace, the coloring for `{world}` changes to black.

Would it be possible for you to collect a perf trace and share it?

1. Download PerfView from https://www.microsoft.com/en-us/download/details.aspx?id=28567
2. Start VS
3. In PerfView, click Collect -> Collect -> Start Collection (note the location where the trace is collected)
4. Execute your scenario in VS
5. Stop Collection in PerfView
6. Share the ETL trace generated by PerfView

**Comment by mavasani** [comment]
@dotnet/project-system Anyone else has seen this on our latest dogfood builds? If so, I'd like to take a stab at your machine/grab perf traces.

**Comment by davkean** [comment]
I'm also seeing this on a very basic repro, in the following, this took > 10 seconds to color "async":

``` C#
using System;
using System.Threading.Tasks;

namespace ConsoleApp166
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");


        }

        private async Task GetFoo()
        {
            var foo = await Task.Run(
        }

        private string GetFoo2()
        {
            return null;
        }
}
```

**Comment by mavasani** [comment]
@davkean Coloring happens almost instantaneously for me for your repro on yesterday's D15Rel build. Can you please collect an ETL trace with perfview and share it?

**Comment by davkean** [comment]
I can repro this again:

![image](https://cloud.githubusercontent.com/assets/1103906/23737382/d7824d2a-04e6-11e7-979f-bf3c440cd092.png)

This is in our repro - in this case, no matter how long I wait the line isn't being colored.

**Comment by davkean** [comment]
Oh my mistake, it was after > 30 seconds.

**Comment by Pilchie** [comment]
Has anyone seen this on 15.5 or higher?  Going to close for now, as there have been a LOT of changes both here and in Roslyn since March...

**Comment by davkean** [comment]
I have not seen this.
