### ISSUE TITLE
Application properties page section relevance to .NET Core projects

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/project-system#1069]
![image](https://cloud.githubusercontent.com/assets/12449387/21652161/772dcfa2-d260-11e6-908b-8ace4487ef0f.png)

**Comment by jinujoseph** [comment]
Reported by @DamianEdwards

**Comment by davkean** [comment]
It might not be as relevant but it's still relevant, If you run on Windows and you need a win32 manifest (perhaps you want to avoid being version shimmed, or you want to be always elevated).

My question is, though, do we respect it via "dotnet exec" - probably not.

**Comment by RaulPerez1** [comment]
Moving this out of RTM - There's no reported user bad here other than they are not applicable outside of Win32. For post RTM we need to figure out the following:
- Do we want to condition this base on configurations?
- Are any of these values passed down to dotnet exec (this is potentially on the SDK side)
