### ISSUE TITLE
Debug.Assert in unit tests opens a dialog when run from the command-line

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#1077]
Our listener for replacing the Debug.Assert popup isn't working when running tests from the CLI. We need to fix this to allow us to test these conditions from the command line by doing one of two things (quoting @davkean):

1. create a "xunit framework" that wraps regular xunit but puts in a call to add the listener
2. Change xunit's runner app.config to include the listener.
    * ie copy xunit to some directory, modify the app.config. run

**Comment by davkean** [comment]
We have a debug trace listener (see src\Common\Test\App.config) that's supposed to prevent it from opening, but this only works inside VS. From the command-line, xunit.AppDomain option is turned off ("denied") which prevents xunit from seeing the App.config settings that apply to a given AppDomain. We can turn it back on but then run the risk of running into https://github.com/dotnet/roslyn/issues/6358 again.

**Comment by davkean** [comment]
This was fixed, Debug.Assert now throws an exception when run from command-line.
