### ISSUE TITLE
Should be able to copy and paste files between VS instances

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#112]
_From @davkean on March 24, 2016 16:58_

Today we don't let you copy and paste files between VS instances, we should allow that.

https://twitter.com/davkean/status/636761909614608384

File properties should flow with it.

_Copied from original issue: dotnet/roslyn#10061_

**Comment by davkean** [comment]
_From @hmemcpy on March 24, 2016 17:2_

Also, project references! Copy/pasting them between projects in the same solution would also be awesome!

**Comment by davkean** [comment]
Yep, great idea. Filed: https://github.com/dotnet/roslyn/issues/10063

**Comment by kvenkatrajan** [comment]
Older issue - Copy and paste files between VS instances works.
