### ISSUE TITLE
ProjectLockFileWatcher shouldn't start without PackageReference support

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1128]
While I cannot repro this, on Jacob's machine the ProjectLockFileWatcher class is loading for Shared Projects and crashing when it attempts to read a Intermedidate output directory.

**Comment by davkean** [comment]
Stepped through this, this isn't crashing in current builds because we started inheriting an intermediate directory from Microsoft.Common.props

**Comment by jinujoseph** [comment]
@srivatsn close this ?

**Comment by srivatsn** [comment]
Closing this. Will use #1129 to track fixing the crash if intermediate directory doesn't exist,.

**Comment by davkean** [comment]
It's not the same bug - this one represents the fact that we shouldn't be firing up this component if the project doesn't support PackageReferences.

**Comment by davkean** [comment]
I've also got a fix for this though.

**Comment by davkean** [comment]
This should be:

1. Making sure this component only shows up for PackageReferences
2. Converting to a dynamic load component, because PackageReferences is a dynamic capability

**Comment by Pilchie** [comment]
@davkean Did you do this already?

**Comment by davkean** [comment]
Yep, this is done.
