### ISSUE TITLE
DesignTimeAssemblyResolution should cache the results from VSProject.References

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1166]
DesignTimeAssemblyResolution walks VSLangProj.Refrences over and over again multiple times during certain paths, such as opening ResX. In .NET Core projects, there's >80 assemblies by default - so this cannot be cheap.

We should figure out how perf sensitive that path and others like is and consider caching the results using the reference events.

**Comment by Pilchie** [comment]
I don't think this has come up on traces yet, so deferring to 15.7.

**Comment by Pilchie** [comment]
(didn't mean to close - wrong button)

**Comment by Pilchie** [comment]
https://github.com/dotnet/project-system/issues/3387 - Wonder if this is a possible solution...

**Comment by davkean** [comment]
This hasn't shown up in other contexts, we've already got a bug #3387 tracking it showing up in AppDesigner.
