### ISSUE TITLE
Modify TFM, restore doesn't get called before build

### ISSUE THREAD

**Issue by MattGertz** [dotnet/project-system#1181]
1. Migrated a project.json project
2. Got errors about NS 1.5 and NC 1.03 being incompatible, so deleted the projected reference in the project file
3.  Pressed Build Solution
==> Build happened first, then restore, so the build failed

Workaround was to do a manual restore and build. (Presumably just another Build Solution would also work, since the restore did happen.)

**Comment by davkean** [comment]
For the repro, did you remember if you saved after 2? 

I'm wondering if the Save is occurring after after you attempted to Build Solution but too late for us to pick up the changes and "nominate a restore".

**Comment by srivatsn** [comment]
I'm wondering if this is a fall out of the change to get packagerefs from DT build. It's taking us longer to nominate a restore and increases the windows before which build could have been issued.

**Comment by jmarolf** [comment]
I can't repro this anymore.  I believe this is now fixed
