### ISSUE TITLE
"Publish..." should be renamed to "Publish for ClickOnce..."

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#119]
_From @davkean on February 14, 2016 4:21_

"Publish" is really ClickOnce publish, we should rename it as such:
![image](https://cloud.githubusercontent.com/assets/1103906/13031834/5a7680c4-d28f-11e5-98ca-5fb3340db2bc.png)

_Copied from original issue: dotnet/roslyn#8695_

**Comment by dmonroym** [comment]
@jjmew similar to #86, instead of renaming should we remove this option?

**Comment by kvenkatrajan** [comment]
@davkean  - think this one is from a while ago - ok to close this one? Publish today has publish profiles with multiple options that can be specified.
![image](https://github.com/dotnet/project-system/assets/102772054/be38753e-ae05-4529-b6fb-cdc198a918a3)

**Comment by haileymck** [comment]
@davkean bumping the previous comment!
