### ISSUE TITLE
Adding an empty Directory.builds.props, Directory.build.targets, etc. crashes VS 2017 RC

### ISSUE THREAD

**Issue by NickCraver** [dotnet/project-system#1199]
I was in this repo (it doesn't really matter): https://github.com/MiniProfiler/dotnet/tree/261d3d1bdaf4047d59f0a1eba4b3b779f26a6e84

Repro steps:
1. Open `MiniProfiler.sln` in Visual Studio 2017 RC
2. Open the `<repo>\samples\Samples.Mvc5` folder in Visual Studio Code (any editor)
3. Create an `Directory.build.props` file that is empty (VS Code will save it immediately)

Visual Studio 2017 will crash instantly, as soon as MSBuild sees the file. The exception underneath is:

> **Microsoft.Build.Exceptions.InvalidProjectFileException**: 'The project file could not be loaded. Root element is missing.'
Inner Exception:
XmlException: Root element is missing.

**Comment by srivatsn** [comment]
Tagging @lifengl @jviau @adrianvmsft. MSBuild is throwing the exception because it indeed an invalid project. We should probably handle this in CPS.

**Comment by davkean** [comment]
@lifengl What do you reckon we should do in this situation? Unload the project?

**Comment by lifengl** [comment]
We should report an error when we load it, certainly should not crash.

Sent from my phone

On Jan 16, 2017, at 2:45 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://github.com/lifengl> What do you reckon we should do in this situation? Unload the project?

-

**Comment by davkean** [comment]
The project is already loaded, so what code path is causing this to be loaded/pick up in this case?

**Comment by jviau** [comment]
Any evaluation or invalid project file errors we display as a load failure to user. If this is crashing VS then this is either bubbling out of msbuild as the wrong exception type, or it is occurring before we expect it and need to handle that.

**Comment by jeffkl** [comment]
They are imported in common props and targets. 
https://github.com/Microsoft/msbuild/pull/751

**Comment by davkean** [comment]
This has been fixed and resolved in 15.6. It should be available in Preview 2.
