### ISSUE TITLE
Publish menu items should be nested under a "Publish" menu

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#120]
_From @davkean on February 14, 2016 4:20_

We have should hide these under a sub menu:
![image](https://cloud.githubusercontent.com/assets/1103906/13031831/17769ed0-d28f-11e5-9ffb-edb48711f7a2.png)

_Copied from original issue: dotnet/roslyn#8694_

**Comment by kvenkatrajan** [comment]
Publish UI managed seperately for web tools.

**Comment by kvenkatrajan** [comment]
Closing ticket
