### ISSUE TITLE
When there's a single Debug profile, we shouldn't list the project name in the Debug button

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1203]
When we have a single Debug profile, we shouldn't show the project name in the Debug button. It's already shown in the previous combo box:

![image](https://cloud.githubusercontent.com/assets/1103906/22002412/10b5df2c-dca0-11e6-835b-6543b1e4355b.png)

Legacy project system, shows just:

![image](https://cloud.githubusercontent.com/assets/1103906/22002424/222ee9e2-dca0-11e6-8385-80a215f79dc3.png)

**Comment by BillHiebert** [comment]
I don't even see the startup projects dropdown on my builds. Is there something  I need to do to enabled it?

**Comment by srivatsn** [comment]
Some people have asked for the project name in legacy csproj after looking at this :) Not sure this is worth changing.
