### ISSUE TITLE
When Migration Fails it is Unclear How to Re-Run from Visual Studio 2017

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/project-system#1206]
**Description**
Migration failed (for whatever reason including old dotnet.exe, issue with project.json, etc.) it isn't clear how to get migration to re-run.  Reopening the solution shows all projects with "(needs migration)" following the project name.  To re-run migration requires deleting the .vs directory or right-clicking on the project and selecting Reload Project.  Reload Project is a non-obvious approach since the solution/project was just newly opened in VS.

/cc @morrisjoe @livarcocc

**Comment by srivatsn** [comment]
At this point, this is not worth fixing.
