### ISSUE TITLE
Migration Warning Text is Wrong

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#1215]
The migration warning text references VS 2010 as what the project will be compatible with. We need to find the text and update it to be correct, namely VS 2017 or newer. /cc @onovotny and @julielerman.

**Comment by davkean** [comment]
I don't think we control that text, basically need an extension point in compat dialog.

**Comment by 333fred** [comment]
@davkean, I have a thread going with the guys who do.

**Comment by srivatsn** [comment]
At this point, we are unlikely to fix migration issues.
