### ISSUE TITLE
Live Unit Testing needs a running indicator

### ISSUE THREAD

**Issue by NickCraver** [dotnet/project-system#1220]
Currently Line Unit testing isn't really clear about the current state. The user has to infer that it's running. While running, it looks like this:

<img width="411" alt="screen shot 2017-01-17 at 14 56 37" src="https://cloud.githubusercontent.com/assets/454813/22037621/eb006d4e-dcc5-11e6-9dbe-8546d88ae695.png">

I suggest changing the title from "Live Unit Testing" to "Live Unit Testing (Running)" to provide a clear indicator here.

@morrisjoe

**Comment by ManishJayaswal** [comment]
Copied it over to Live Unit Testing repo.

**Comment by davkean** [comment]
Closed this as it was moved to the Live Unit Testing (private) repo.
