### ISSUE TITLE
Inconsistent results between Live Unit Testing and Code Lens

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/project-system#1229]
I am seeing different results between Live Unit Testing and Code Lens.  This is confusing...
Image: https://www.dropbox.com/s/ad7wiw8tmdmh7gs/2017-01-17_16-03-11.png?dl=1

/cc @morrisjoe

**Comment by jinujoseph** [comment]
cc @ManishJayaswal @KevinH-MS

**Comment by ManishJayaswal** [comment]
tagging @genlu

**Comment by genlu** [comment]
@MarkMichaelis could you please share the source code with us as well (if possible)? Thanks!

**Comment by MarkMichaelis** [comment]
You are going to be disappointed:
`   public class SampleClass
    {
        internal static void DoSomething()
        {
            throw new NotImplementedException();
            Console.Write("Test");
        }
    }

    [TestClass]
    public class UnitTest1
    {


        [TestMethod]
        public void TestMethod1()
        {
            SampleClass.DoSomething();
        }
    }
`

**Comment by davkean** [comment]
@MarkMichaelis Can you continually repro this? What build are you on? Is it 26114.2? What project type?

I tried repro'ing and cannot.

**Comment by saikrishnav** [comment]
@MarkMichaelis I cannot repro this either on RC3+ builds. Can you confirm that you are on RC3.0 build? Otherwise can you tell us the build number?

**Comment by ManishJayaswal** [comment]
We saw the repro on @MarkMichaelis machine. The weird thing about it was that when @KevinH-MS hovered over the code lens test indicator glyph, it showed the error in the test. For some reason the code lens test indicator was green when it should not have been.

**Comment by MarkMichaelis** [comment]
I did demo this on site yesterday (which is when I took the screen shot) with yesterday's build of RC3.

I will try repro again later this week but given that I was able to produce this on a brand new project in 5 min. in the middle of or live testing discussion I would be surprised that you are not seeing this.

**Comment by davkean** [comment]
This code has long since changed and cannot repro. Please file a bug via Send Feedback -> Report a Problem if you are still encountering it.
