### ISSUE TITLE
Group package/project dependencies by provider type

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1255]
The dependency node shows the contents (Newtonsoft.Json) along side it's dependencies (the other things). These aren't siblings:

![image](https://cloud.githubusercontent.com/assets/1103906/22102592/1682dd18-de8c-11e6-8603-18d457b1dac5.png)

**Comment by abpiskunov** [comment]
thats how it was always in Dev14 xproj - what do you propose?

**Comment by davkean** [comment]
Not sure, either make it look like a project (ie with Dependencies node), or add a Contents folder that contains the contents. We can ship v1 with this - so moving it out.

**Comment by abpiskunov** [comment]
hm i would argue here and not only me, i guess :).. We had multiple discussions about it in Dev14 and that was the final common agreement. The idea behind a dependencies tree is: "it shows what dependencies package brings to a project" (dependencies from the binary perspective, not content files etc). This statement is exactly what we implement there: when you open package node you see that it brings following dependencies: 1. assemblies that package contains and 2. other packages under it, that also bring dependencies. We don't aim to show really a content of the package , but only data from the dependencies perspective.  

I am fine to open a new discussion though, it might not be an easy one :)...

**Comment by drewnoakes** [comment]
I like the idea of introducing a new "Content" node, alongside a "NuGet" node.

```
Dependencies
  NuGet
    Newtonsoft.Json (9.0.1)
      Content
        Newtonsoft.Json.dll
      NuGet
        Microsoft.CSharp (4.0.1)
        ....
```

Project references also show a flat list of dependencies when expanded. Grouping would help there too.

**Comment by davkean** [comment]
Yeah agreed, have a look at how some of the other project systems did it (I think JavaScript expanded SdkReferences)
