### ISSUE TITLE
Dependent properties are not immediately refreshed on package property page

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/project-system#1259]
**Repro Steps**
- Create a new  Asp .Net Core Web Application (.Net Core) project 
- Right click Properties Page -> select Packages
- Update the value of "Authors" -> Save , notice that Author is only changed. 
- Close and reopen the package page again.

**Expected**
you should see the changed value for only Author.

**Actual**
The Author and Company Tab is also changed.

![image](https://cloud.githubusercontent.com/assets/12449387/22117920/9edeca94-de2a-11e6-9a6d-fc82e965b3a9.png)

**Build:** 
26118.0.d15rel

**Comment by davkean** [comment]
Until CPS implements connection point container on the project/configuration objects - this is never going to work, unless we manually re-read the properties.

**Comment by davkean** [comment]
This has nothing to do with connection point container, but rather the way we figure out defaults for these properties. Company defaults to Author if it hasn't been set. Need a visual way of indicating taht.

**Comment by drewnoakes** [comment]
> Company defaults to Author if it hasn't been set. Need a visual way of indicating taht.

The new Project Properties UI shows what is going on here. The `Company` property is defined in terms of the `Authors` property:

![image](https://user-images.githubusercontent.com/350947/162961047-7b0d069d-99a9-4448-87ce-25ba3937db9b.png)

This relationship is defined in the SDK.

I can't see any actionable work item here for us.
