### ISSUE TITLE
Property page support for new compiler switches

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#126]
_From @jaredpar on November 20, 2015 22:53_

A number of compiler switches have come online in 1.0 - 1.2 that need to be considered for property page support:
- [x] `/deterministic` switch
- [ ] `/pathmap` option 
- [ ] `/publicsign` switch 
- [x] `/pdb:portable` switch value 

It's possible not all of these will have UI associated with them but need to make the call on them. 

_Copied from original issue: dotnet/roslyn#6945_

**Comment by davkean** [comment]
_From @Pilchie on January 22, 2016 17:32_

We think all of these can wait to have UI for these until 2.0

**Comment by davkean** [comment]
_From @tiesmaster on January 23, 2016 18:50_

:+1:

**Comment by davkean** [comment]
_From @jaredpar on January 25, 2016 17:58_

Agree.

**Comment by davkean** [comment]
_From @DustinCampbell on April 22, 2016 17:36_

Moving over to project system

**Comment by kvenkatrajan** [comment]
Closing low priority - deterministic property has been added to the UI.
