### ISSUE TITLE
Templates no longer replace spaces in namespace with underscores

### ISSUE THREAD

**Issue by jnm2** [dotnet/project-system#1271]
To repro (15.0.26014.0):

 1. Create a new console app with spaces in the name
 2. Add new class, see the following result:

```c#
using System;
using System.Collections.Generic;
using System.Text;

namespace Test namespace issue
{
    class Test
    {
    }
}
```

(There would obviously be other characters to replace besides spaces too.)

**Comment by davkean** [comment]
Did some investigation. 

For C#, we handle this correctly if the item we're adding is under a folder containing spaces. For example, adding to a folder called "Foo Bar", results in:

``` C#
namespace DefaultNamespace.Foo_Bar
{

}
```

This goes through our call to [ILanguageFeaturesProvider.MakeProperNamespace](https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/LanguageServices/CSharpLanguageFeaturesProvider.cs#L87).

The problem above is that the assumption by CPS is that the default namespace is always in the correct format, so it never calls through us. This assumptions breaks down now that we're no longer making a well-formed namespace and persisting it the project file. We should change CPS to always call through us for the default namespace.

**Comment by davkean** [comment]
Okay more info, there's two paths here:

1. When you add a class into the root of a project, the wizard infrastructure asks for "RootNamespace" property directly from the rules.

2. When you add a class into a folder of a project, the wizard infrastructure asks for "DefaultNamespace" for the parent item which in turn appends itself with the "DefaultNamespace" property (which in turn reads "RootNamespace" directly from the rules.

Make sure you test both cases when fixing this.

Two approaches to fixing this that I see:

1. Implement a data source that does a MakeProperNamespace call on "RootNamespace/DefaultNamespace" on the result before returning it.

2. Make sure the MSBuild property does the equivalent of MakePropertyNamespace on "RootNamespace".

**Comment by BillHiebert** [comment]
This is also reported on the developer community feedback  site:
https://developercommunity.visualstudio.com/content/problem/56953/namespace-contains-invalid-characters-in-new-files.html

**Comment by jnm2** [comment]
@jmarolf Since VS2019 previews seem to have fixed this, can I close?

**Comment by jmarolf** [comment]
this has been fixed
