### ISSUE TITLE
Output type is being persisted as a configuration setting

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1300]
1. File -> New Class Library (.NET Standard)
2. Change output type -> Console App:

Result:
``` XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputType>exe</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
    <OutputTypeEx>exe</OutputTypeEx>
  </PropertyGroup>
</Project>
```

**Comment by RaulPerez1** [comment]
Unless explicitly specified everything will be config specific. We do need to do a full pass on all properties and make sure that only the ones that are under config pages are saved as config specific properties, especially once we have a fix for #413

The change required is to add a data source and HasConfigurationCondition=false to the items that should not be config specific, e.g.

From: <DynamicEnumProperty Name="OutputType"/>
To:
<DynamicEnumProperty Name="OutputType">
  <DataSource Persistence="ProjectFile" HasConfigurationCondition="False"/>
</DynamicEnumProperty>

**Comment by RaulPerez1** [comment]
Should be fixed once #1709 is implemented.

**Comment by basoundr** [comment]
Fixing #1709 did not fix this issue. Reopening

**Comment by RaulPerez1** [comment]
Here's the fix I had for it:

https://github.com/dotnet/roslyn-project-system/pull/1466/commits/c628b6c25045e38221b5603abb113562b073199e

**Comment by srivatsn** [comment]
Fixed by https://github.com/dotnet/project-system/pull/2221
