### ISSUE TITLE
Turning on "Generate serialization Assembly" results in confusing build error

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1302]
1. File -> New -> Console App (.NET Core)
2. Project Properties -> Build -> Generate serialization assembly -> ON
3. Build:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		An attempt was made to load an assembly with an incorrect format: C:\Users\davkean\.nuget\packages\microsoft.win32.primitives\4.3.0\ref\netstandard1.3\Microsoft.Win32.Primitives.dll.	ConsoleApp89	c:\users\davkean\documents\visual studio 2017\Projects\ConsoleApp89\ConsoleApp89\SGEN	1	

```

**Comment by f00-beerd** [comment]
No error when specifying Platform: x64 or x86 - only for Platform: Any CPU
Still happens as of 15.3.2 update.

**Comment by Pilchie** [comment]
Is the fix here to disable that option for .NET Core projects?

**Comment by drewnoakes** [comment]
.NET Core projects now use the new Project Properties UI which does not include this option.
