### ISSUE TITLE
When you have no launch profiles, every control is disabled except launch

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1307]
Looks like Launch should probably be disabled in this:

![image](https://cloud.githubusercontent.com/assets/1103906/22192008/797786e4-e184-11e6-90b5-b108cf47612a.png)

**Comment by basoundr** [comment]
@davkean I tried to repro this issue by creating a web application and deleting the launch settings. The project is still left with the default/implicit launch profile.

![image](https://cloud.githubusercontent.com/assets/10550513/26421446/f76d338c-407a-11e7-9523-f8a0b5440ba4.png)

So, is there a different way to repro this issue? If not, please close this issue as not-repro.

**Comment by davkean** [comment]
Can you unload and reload the project and see if that still repros?

**Comment by basoundr** [comment]
I tried unload & reload and still see the implicit project launch profile.

**Comment by srivatsn** [comment]
Can't repro either.
