### ISSUE TITLE
Class Libraries show up in debug startup project list

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1308]
This list is supposed to show projects that can be launched (so the user can quickly switch start up projects), neither of these projects can be launched:

![image](https://cloud.githubusercontent.com/assets/1103906/22192072/f5bd98ce-e184-11e6-9342-320aa552c211.png)

**Comment by basoundr** [comment]
Blocked by [VSO bug 389597](https://devdiv.visualstudio.com/DevDiv/_workitems?id=389597)

**Comment by JohannZhu** [comment]
Any updates on this issue? Finding one single executable project from dozens of projects is not funny... And I know some teams have hundreds of projects...

**Comment by moginheden** [comment]
I'm not sure if this is the same bug, but I was directed here when trying to figure out why my web project is NOT in the startup list, (but, a CLI and a Windows application do.)

**Comment by mmihaly** [comment]
We're migrating to .Net Core, and this is very annoying, hopefully it gets fixed soon.

**Comment by davkean** [comment]
We need to do two things:

1) Unregister the existing debugger launch providers that we're not using via the opt out here: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/219892. This will also fix https://github.com/dotnet/project-system/issues/6140.
2) Make our debug launch provider actually provide a useful result from IsDebuggableAsync, _or_ implement it terms of another method.

**Comment by 4lexKislitsyn** [comment]
Additional information: VS2019 doesn't show .NET Framework's Class Library projects. So it excludes .NET Framework ASP.NET projects.

It's problem when you have solution with .net core and .net framework ASP.NET projects.

**Comment by jjmew** [comment]
This is a top feedback item hence giving it high priority

**Comment by davkean** [comment]
Reopen based on the revert here: https://github.com/dotnet/project-system/pull/6402.

**Comment by mmihaly** [comment]
This issue somehow got into the 16.10 versions...

**Comment by drewnoakes** [comment]
@mmihaly could you provide some more details on how to repro please?

Ping @ocallesp

**Comment by mmihaly** [comment]
Repro steps:
1. Create a blank solution
2. Add a .NET 5 C# console project to the solution
3. Add a .NET 5 C# class library to the solution

As the original post mentioned, the class library project is shown in the startup projects dropdown, when only the console app should:
![image](https://user-images.githubusercontent.com/50031464/124616902-b79ab580-de33-11eb-9cdd-26d25a0fa193.png)

It's not a big deal for small solutions, but we have a solution with more than 100 projects, only a few can be launched and it's quite annoying to find them in the dropdown.

Attached is a sample solution with the above projects. 

@ocallesp

[ConsoleApp.zip](https://github.com/dotnet/project-system/files/6770728/ConsoleApp.zip)

**Comment by drewnoakes** [comment]
@mmihaly thank you very much.

Reopening and sending back to triage.

**Comment by jjmew** [comment]
@ocalles can you please take a look?

**Comment by f-i-x-7** [comment]
Hello, any updates on this?
My solution has about 200 projects. Yesterday I updated VS from 16.9.4 to 16.10.4 and now I see all these 200 projects in startup list in toolbar. This is very painful regression bug, is there any change that it will be fixed e.g. in 16.9.5 version?

**Comment by drewnoakes** [comment]
@ocalles can you look into this asap so we can get it fixed for 16.11.

**Comment by drewnoakes** [comment]
@ocalles I believe this is fixed in #7429. Can you take a look at that PR on Monday please?
