### ISSUE TITLE
Setting CopyToOutputDirectory metadata to "Never" should remove Update

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1310]
1. File -> New Console App (.NET Core)
2. In Solution Explorer, select Program.cs
3. In Properties, change Copy to Output Directory to Always
4. In properties, change Copy to Output Directory to Never

Expected:
``` XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>
</Project>
```
Actual
``` XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Class1.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>
</Project>
```

**Comment by jviau** [comment]
This is expected behavior I believe. To remove it you need to select `<reset to default>`. Unfortunately that only shows up if you deselect and re-select the file after setting it to `Always`. We want to fix the properties window not auto-refreshing.

**Comment by dmonroym** [comment]
@davkean do you think this should be moved to CPS?

**Comment by jjmew** [comment]
Moved to Azure Devops
