### ISSUE TITLE
Changes made to the Debug property page are saved even when I save don't save changes

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1311]
Repro #1:

1. File -> New -> Console App (.NET Core)
2. Right-click on project, choose Properties
3. Click Application, change Assembly name to "Foo"
4. Click Debug, change Arguments to "FooBar"
5. Close Solution and choose No when prompted to Save
6. Reopen project

Expected: Neither changes to be saved
Actual: The assembly name change is discard (as expected). the Debug properties change is saved.

Repro #2:

1. File -> New -> Console App (.NET Core)
2. Right-click on project ,and choose Properties
3. Make any change to debug page and switch tabs for launchsettings.json to be created
4. In Explorer, mark launchsettings.json as "read-only"
5. Make any change to debug page 
6. File -> Close Solution

Get prompted with:

![image](https://cloud.githubusercontent.com/assets/1103906/22192818/5b3a92dc-e18b-11e6-9bb6-df5b30f8ae95.png)

Click Cancel cancels the closing of the solution, I **cannot** discard my changes.

**Comment by sputier** [comment]
I'll take a look a this issue this week end.

**Comment by davidwengier** [comment]
Going to dupe this against #5559 as there is a devcomm issue linking to that.
