### ISSUE TITLE
Add Service Reference support

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#132]
_From @davkean on January 14, 2016 20:59_

This is tracking adding Add Service Reference support (Service References node, menu items, opening dialog, etc)

_Copied from original issue: dotnet/roslyn#7961_

**Comment by DzonnyDZ** [comment]
Is there currently any workaround or any path (even manual) how to migrate "Service References" to "Connected Serveries"?

**Comment by kvenkatrajan** [comment]
This is available at : 
![image](https://github.com/dotnet/project-system/assets/102772054/e024fb8e-25e0-4030-bfdc-e053f114f307)
![image](https://github.com/dotnet/project-system/assets/102772054/84b21890-14a2-4c5a-9334-b9c79f8d2352)
