### ISSUE TITLE
Double clicking on imported namespace unchecks other than the selected one

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1326]
From: https://developercommunity.visualstudio.com/content/problem/7382/double-clicking-on-imported-namespace-unchecks-oth.html

1. Create a new Windows Forms App (.NET Framework)
2. Right-click on project and choose Properties
3. Click References tab
4. Double-click on System

Expected: For System to be deselected
Actual: Some other namespace is deselected (can't figure out logic).

**Comment by jrsconfitto** [comment]
I'm not sure if this is the right place to comment, but I'm seeing this behavior in the recently released VS 2017 15.5 and the Developer Community issues led me here.

Here's a gif of the problem manifesting. The issue appears at the end, when I try to click on "System" and instead "System.Data" is clicked:

![namespace checking issues](https://user-images.githubusercontent.com/238079/33630382-27d325c4-d9d5-11e7-8a33-c686de14ce7c.gif)

**Comment by natidea** [comment]
@jrsconfitto based on the report in #2872, the workaround is to Edit the `Import` itemgroup in the vbproj file

**Comment by Pilchie** [comment]
Fixed by #3095
