### ISSUE TITLE
Make it easier to manage/set multiple startup projects

### ISSUE THREAD

**Issue by hmemcpy** [dotnet/project-system#133]
Setting multiple startup projects is a bit of a pain, those settings are stored in the `.suo` file, and are easily lost.
That's why @SimonCropp made https://github.com/ParticularLabs/SetStartupProjects to manage our samples for NServiceBus, but this should be easily done in a persistent way from VS.

**Comment by davkean** [comment]
Would you like to see a way that can be persisted with the solution/project?

**Comment by kvenkatrajan** [comment]
This request has been routed to an internal team who owns this feature. The implementation is in works and will be addressed in an upcoming 17.X release.

**Comment by SimonCropp** [comment]
@kvenkatrajan can you leave this open, and only close it when that feature is released. then link to the feature
