### ISSUE TITLE
Pack from VS UI should call msbuild /t:pack instead of msbuild /p:GeneratePackageOnBuild=true

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/project-system#1339]
There are a couple of issues with the current approach:

1) Not consistent with command line : calling ```dotnet pack``` builds the project by default, but only if ```GeneratePackageOnBuild``` is not set to ```true```. However, invoking Pack from the UI always builds the project and there is no way to opt-out.

2) Confusing for user : User asked to pack the project, not build it, and therefore the entry point should be the Pack target, and not build.

CC: @rrelyea @srivatsn

**Comment by davkean** [comment]
What does GeneratePackageOnBuild have to do with whether pack builds the project or not?

**Comment by rohit21agrawal** [comment]
GeneratePackageOnBuild introduced a circular dependency between Build and Pack targets. To workaround this, we have to disable building by default when Pack is called and GeneratePackageOnBuild is set to true

**Comment by 333fred** [comment]
While it would be good call the pack target, using `GeneratePackageOnBuild` control whether pack builds the project seems rather wrong and unintuitive. I would argue that having a seemingly unrelated property control behavior here is even more confusing than having pack always run a build, because the latter is at least consistent behavior.

**Comment by 333fred** [comment]
Additionally, I would expect VS to build the project if it's not already built or out of date, not just run a pack command and fail if the project isn't built, even if `GeneratePackageOnBuild` is true.

**Comment by rohit21agrawal** [comment]
@333fred there is no other possible option here because of the circular dependency.. Also note that, ```GeneratePackageOnBuild=true``` only leads to disabling Build on Pack when the Pack target is directly invoked - which does not happen from the VS UI.

In fact, i would argue that calling Build when someone calls Pack seems wrong to me.

In the ideal situation, calling build should actually invoke the Pack target instead when ```GeneratePackageOnBuild``` is set to true.

**Comment by 333fred** [comment]
@rohit21agrawal I that's a fundamental difference between the CLI and IDE. I expect my CLI programs to do exactly what I say, no more and no less. For the IDE, I expect it to be intelligent and consistent. I can write a test method, open test explorer, and click "Run All" without having to tell the project to build at all. To be consistent, I should be able to make a change, run Pack, and have a fully updated package generated.

**Comment by rohit21agrawal** [comment]
CLI Pack does build your project by default when you pack, and I agree that VS should do it too. For the CLI scenario, user can pass the ```--no-build``` switch to explicity disable build when packing.

I expect that behavior should be the same in IDE too - and we can achieve that by calling ``` msbuild /t:pack /p:GeneratePackageOnBuild=false ``` and let user set the ```$(NoBuild)``` property in their project file (equivalent of the ```--no-build``` command line switch).

**Comment by dsplaisted** [comment]
@rohit21agrawal I'm not sure I'm fully understanding everything here, but could you resolve the circular dependency by always having Pack depend on Build, and then running the Pack target after the Build target if GeneratePackageOnBuild is specified?  Something like this:

```xml
<Target Name="PackAfterBuild" DependsOnTargets="Pack" AfterTargets="Build" Condition="'$(GeneratePackageOnBuild)' == 'true' />

<Target Name="Pack" DependsOnTargets="Build" />
```

This example doesn't account for the `--no-build` option with pack, but that can be added by having Pack's DependsOnTargets value be conditioned on a NoBuild property.

**Comment by rohit21agrawal** [comment]
@dsplaisted doing what you suggested, if someone called ```msbuild /t:pack``` with ```GeneratePackageOnBuild=true``` , they will hit the circular dependency issue.

See our current implementation here : 

[_PackAsBuildAfterTarget](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/Pack.targets#L55)

[Property Initialization](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/Pack.targets#L33-L42)

**Comment by dsplaisted** [comment]
@rohit21agrawal Can you describe what the circular dependency is?  It sounds like it may not be what I was guessing.

**Comment by rohit21agrawal** [comment]
@dsplaisted Pack depends on Build by default. Pack also happens to be an AfterTarget of Build if ```GeneratePackageOnBuild``` is set to true.

If someone calls Build with ```GeneratePackageOnBuild=true```, build completes and calls Pack, and Pack depends on Build running into a circular dependency.

If someone calls Pack with ```GeneratePackageOnBuild=true```, Pack depends on Build, so it calls Build, and Build upon completion invokes its AfterTarget, and pack is one of them, running into a circular dependency.

**Comment by dsplaisted** [comment]
@rohit21agrawal The following seems to work for me without running into circular dependency errors:

```xml
<Project>

    <Target Name="Build">
        <Message Text="Building" />
    </Target>

    <Target Name="PackAfterBuild" DependsOnTargets="CorePack" AfterTargets="Build" Condition="'$(GeneratePackageOnBuild)' == 'true' "/>

    <Target Name="Pack" DependsOnTargets="Build;CorePack"/>

    <Target Name="CorePack" DependsOnTargets="Build">
        <Message Text="CorePack" />
    </Target>

</Project>
```

The `Pack` target there would only be an entry point, all of the real packing logic would go in `CorePack`.  Would this help?

**Comment by davkean** [comment]
I'm moving to this unknown - it's unclear to me this is ready to be picked without design. Here's my concerns;

- We cannot rely on pack building the project and its dependencies. Unlike command-line, Visual Studio's build manager builds the project not MSBuild - so we need to continue to build downstream dependencies.

- It's not clear to me why someone would want to opt out of building the project if its out of date?

**Comment by davkean** [comment]
@davidwengier Is picking this up as part of another bug he is fixing, https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935258.
