### ISSUE TITLE
Project context menu is too big

### ISSUE THREAD

**Issue by svick** [dotnet/project-system#134]
Currently, the project context menu is too big, making it hard to find one of the few items from there that I use. I think the least used items should removed (e.g. does anyone actually use right click → Cut/Paste _on projects_?), some other items could be made to take less space by grouping them into a submenu.

![Screenshot of project context menu](http://i.imgur.com/b2uDgaG.png)

**Comment by svick** [comment]
Related: #94

**Comment by davkean** [comment]
Yeah, we did a pass back in VS2012 - but we should do another, and throw lots of data at it like we're doing with the editor.

**Comment by MgSam** [comment]
I cringe every time I right click in Visual Studio.

I think grouping everything into submenus and **alphabetizing** them would be a huge improvement. In the current state, every if you cut the number of items, every extension you add into VS adds items into the context menu at arbitrary places. Force all groups to be submenus and everything to alphabetize and get a huge improvement in usability. 

You shouldn't have to read every single item in the list every time you want to find something.
