### ISSUE TITLE
Broken integration test BasicErrorList_NetCore.xml

### ISSUE THREAD

**Issue by piotroko** [dotnet/project-system#1343]
This integration test is failing with the following error:

`Failed to load 1 types from Microsoft.Test.Apex.VisualStudio, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a due to loader exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.ReferenceManager.Providers, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

**Comment by jmarolf** [comment]
resolved with https://github.com/dotnet/project-system/pull/2169
