### ISSUE TITLE
Project System: Add Item menu support for Winforms and WPF

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#137]
_From @davkean on January 14, 2016 21:34_

This is tracking Add Item support including WinForms and WPF menu items:

![image](https://cloud.githubusercontent.com/assets/1103906/12338195/5f4014dc-bac3-11e5-83f7-4413d3650544.png)
![image](https://cloud.githubusercontent.com/assets/1103906/12338221/838ab144-bac3-11e5-8cd2-21fa52ace418.png)

_Copied from original issue: dotnet/roslyn#7965_

**Comment by MgSam** [comment]
In a similar vein to #134, it would be nice if there were an option in VS to disable these framework-specific context menu items. I never use them (I use the add-item dialog instead) and all they do is waste screen real-estate and make the context menu harder to parse.

**Comment by davkean** [comment]
@MgSam We're looking at two things that will make this better;

1. We're plan on improving Add Item experience via a most recently used feature: https://github.com/dotnet/roslyn-project-system/issues/104
2. We're looking to simplify Add Item, so that you don't need to open the dialog to add a class, etc: https://github.com/dotnet/roslyn-project-system/issues/136
3. We're looking at making the "existence of these menus" entirely based on whether you are using/referencing the technology.

Would that help?

**Comment by MgSam** [comment]
Yes, I think all of that helps, but it still would be nice to toggle off context menu items that I'll never use. Perhaps that's a more general-VS wide feature? Being able to add/remove context menu items in the same way you can with the toolbar?

**Comment by davkean** [comment]
@MgSam We already have this feature, and have since VS 2010. :)

1. __Tools__ -> __Customize__ -> __Commands__
2. Choose __Context menu__,  pick _Project and Solution Context Menus | Project | Add_
3. Click the command you want to remove and choose __Delete__

**Comment by MgSam** [comment]
Whoops! Thanks for the clarification!

**Comment by davkean** [comment]
We should toggle these menus based on project capabilities https://github.com/dotnet/project-system/issues/4248.

**Comment by davidwengier** [comment]
Legacy menu items are here: 
Winforms: http://index/?query=%60ECMD_ADDWEBFORM&rightProject=VisualStudio(Repo)&file=appid%5Ccmddef%5Cpkgui%5CSharedCmdDef.vsct&line=3565
WPF: http://index/?query=%60cmdidAddWPFWindow&rightProject=Microsoft.VisualStudio.WPFFlavor&file=Commands.vsct&line=91
