### ISSUE TITLE
VisualStudioWorkspace projects do not get updated if Release configuration is selected on the project

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1375]
The problem seems to be with First time publish of the project. 

If I unload the project after first publish and then try to add a model and scaffold, everything seems to work fine. 

Workaround steps:

1. Create ASP.NET Core Web Application > Web Application with Individual
2. Check the checkbox for "Create new Git repository"
3. Publish to Web App
4. Unload project
5. Add model class
6. Scaffold. 

Scaffolding uses VisualStudioWorkspace from Rolsyn to get project compilations and then gets the types available.

If I add a model class when release configuration is selected and then inspect the Project using the VisualStudioWorkspace, the included Documents does not contain the newly added model class.

Attached Screenshots
Config-Release.png :: inspecting Project in release configuration
![image](https://cloud.githubusercontent.com/assets/1103906/22415201/3d8ccac8-e719-11e6-8ff1-a2affce6c5d7.png)

Config-Debug.png :: inspecting Project in Debug configuration
![image](https://cloud.githubusercontent.com/assets/1103906/22415206/448468cc-e719-11e6-8519-b8c690c22e82.png)

Prafull Bhosalecommented 2 months ago
Tried the scenario with RC (15.0.25920.0)
It does not repro on the RC build.

Prafull Bhosalecommented 2 months ago
Update from @Vijay Ramakrishnan 
If we add a model while release configuration is selected, then model does not get displayed on the model drop down. If the configuration is changed to debug, the model shows up (repro without publish: change the configuration to release, add a model, go to the scaffolding dialog and model wont show up, change the configuration to debug and model starts showing up.)

**Comment by davkean** [comment]
This is a dup of: https://github.com/dotnet/project-system/issues/1375

**Comment by prafullbhosale** [comment]
> This is a dup of: #1375

@davkean, did you mean to dupe it to a different issue?

**Comment by srivatsn** [comment]
I think https://github.com/dotnet/project-system/issues/2262
