### ISSUE TITLE
changes made to project file during restore , don't trigger next restore after current one is complete

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#1382]
1. Create a project 
2. add some assembly reference (or project reference)
3. Restore should start - immediatelly after restore start Undo your change and save , so it happens before restore completes.

Actual result: restore complete and project assumes that initial change is still in effect, no second restore for later change happens

Expected: new restore should start after first restore completed.

**Comment by natidea** [comment]
This does not repro on 15.3 or the latest builds
