### ISSUE TITLE
Revamp Reference Paths properties page 

### ISSUE THREAD

**Issue by RaulPerez1** [dotnet/project-system#1397]
See #1071 

There's a few issues with this page:

1) It writes data to the user file so if you actually want to persist a change it will only be on that particular machine (.user files normally get excluded from source control)
2) It hardcodes paths so it's only really useful on the machine where it is edited

Need to determine if the work here is worth it or if we want to completely remove the page. Ideally this would write changes to the project file and it would encourage usage of MsBuild macros and relative paths (i.e. <ReferencePath>..\Refernces;$(MyReferencesPath);$(ReferencePath);</ReferencePath>

**Comment by kvenkatrajan** [comment]
Closed - Page removed in #1071
