### ISSUE TITLE
GeneratePackageOnBuild is persisted as "True" instead of "true"

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1417]
All other properties are persisted as "true", GeneratePackagesOnBuild is persisted as "True". 

``` XML
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

```

**Comment by davkean** [comment]
`<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>` is also in this bucket.

**Comment by basoundr** [comment]
[Fix in CPS](https://mseng.visualstudio.com/VSIDEProj/_git/VSIDEProj.CPS/pullrequest/211572)

**Comment by basoundr** [comment]
This behavior is for all Bool Property which is used via DynamicType to work with the Property pages.

**Comment by basoundr** [comment]
CPS fix is merged
