### ISSUE TITLE
Should not get offered smart tag to rename, after you've just renamed

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1422]
1. Create new Class Library (.NET Standard)
2. Rename Program.cs -> Program2.cs
3. Click Yes when prompted to rename:

**Expected:**

![image](https://cloud.githubusercontent.com/assets/1103906/22506071/9629b7c6-e8d2-11e6-8dc2-6b9436484b4c.png)

**Actual:**

![image](https://cloud.githubusercontent.com/assets/1103906/22506063/8565d03c-e8d2-11e6-80af-42229b9f0ee3.png)

The legacy project system behaves correctly in this regard.

**Comment by davkean** [comment]
@CyrusNajmabadi @dpoeschl Any idea why this is occurring? We're calling the Renamer?

**Comment by dpoeschl** [comment]
@davkean You call the Renamer to get an updated solution and then apply the new solution to the Workspace? We've talked about having a concept of "programmatic edits" that rename tracking would not respond to, but without such a mechanism rename tracking things you've legitimately just changed the text (and is therefore doing the right thing as far as it can tell).

**Comment by davkean** [comment]
How does the legacy project system handle this I wonder.

**Comment by dpoeschl** [comment]
The legacy project system working with the Roslyn language services? Probably the same strange behavior.

**Comment by dpoeschl** [comment]
And just an FYI, if you had a constructor, this wouldn't happen because two non-intersecting spans are changed in the same text edit, which rename tracking ignores. Maybe that makes the problem less frequent.

**Comment by davkean** [comment]
It doesn't have the same behavior.

**Comment by jmarolf** [comment]
This still repros after my changes @dpoeschl 	what is the correct way for a VS extension to rename files and let the rename tracker know to not show the smart tag?

**Comment by dpoeschl** [comment]
@jmarolf There isn't one as far as I know. It just listens to text buffer changes and sees that they're isolated within an identifier and thinks you've changed it. We've never created a "programmatic edit" distinguishing mechanism like mentioned above.

**Comment by jmarolf** [comment]
@dpoeschl 	alright, so I assume this will need to move to the roslyn repo? or at least have a corresponding bug?

**Comment by davkean** [comment]
This doesn't occur in legacy because it dismisses it here: https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Impl/CodeModel/AbstractCodeModelService.cs#L513.  Going to dupe this against https://github.com/dotnet/project-system/issues/5436 which is tracking unifying the logic between the two project systems.
