### ISSUE TITLE
Unloading a project doesn't cause downstream projects to get warnings

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1424]
1. File -> New Library (A)
2. File -> New Library (B)
3. Reference B from A
4. Unload B

Expected: Project to get a warning symbol and a warning to be added to error list similar to legacy
Actual: Absolutely nothing

![image](https://cloud.githubusercontent.com/assets/1103906/22506592/6f897ffe-e8d5-11e6-83ba-1ef865c04ffc.png)

**Comment by abpiskunov** [comment]
why is that expected? project A does have a project B reference which can be resolved. If B is just unloaded in the tool, does not mean it is gone.. isn't it?

**Comment by davkean** [comment]
To VS it is gone - I now get downstream missing APIs, etc.

**Comment by abpiskunov** [comment]
i see, Ok i will check what events we receive from DT build if project is unloading...

**Comment by abpiskunov** [comment]
Fixed with https://github.com/dotnet/project-system/pull/1880
