### ISSUE TITLE
Renaming a project that is referenced results in a warning in the error list complaining about old name

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1425]
1. Create a new Class Library (A)
2. Create a new Class Library (B)
3. Add a reference from A -> B
4. Rename B -> C

Expected: Reference to updated and no errors or warnings
Actual: Got a warning in the Error List about being unable to resolve the old name:

```
Warning		The referenced project '..\B\B.csproj' does not exist.	A	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1742	
```

**Comment by davkean** [comment]
This looks to be a timing thing, probably coming from design-time build.

**Comment by davkean** [comment]
Filed this: https://github.com/dotnet/roslyn-project-system/issues/1426, which is probably ultimately the underlying cause - but I do question why a design-time build was launched based on the old snapshot.

**Comment by srivatsn** [comment]
Verified that this doesn't repro anymore.
