### ISSUE TITLE
Invalid projects refs have the wrong icon in the Dependency tree

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1427]
![image](https://cloud.githubusercontent.com/assets/1103906/22507673/c33a95d4-e8da-11e6-987d-121060c9eaef.png)

**Comment by abpiskunov** [comment]
You mean that we need to have a separate "warning icon for project" instead using "warning icon for assembly" icon? If yes, its on my list for U1, i need to get icons form designers.

**Comment by davkean** [comment]
Yes.

**Comment by abpiskunov** [comment]
Fixed with https://github.com/dotnet/project-system/pull/1880
