### ISSUE TITLE
Introducing errors when editing the project file by hand is extremely jarring and confusing

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1428]
1. File -> New Console App (.NET Core)
2. File -> Edit ConsoleApp1.csproj
3. Enter some saw raw text just after `<Project>` root
4. Save

-- Get prompted with the following --
![image](https://cloud.githubusercontent.com/assets/1103906/22508074/790c7aac-e8dc-11e6-8731-464255e2584b.png)

Clicking Ignore, causes any changes you've made since you last saved to be thrown away
Clicking Reload causes the project to enter this state and for the editor to close:

![image](https://cloud.githubusercontent.com/assets/1103906/22508131/b9890032-e8dc-11e6-834e-e4465765cabc.png)

What you really want, is a chance to fix your mistake and Save again.

**Comment by davkean** [comment]
This dialog text doesn't make a lot of sense in this context either.

**Comment by srivatsn** [comment]
Tracking with https://github.com/dotnet/project-system/issues/1570

**Comment by davkean** [comment]
Disagree - this is representing the dialog that makes no sense when you have conflicts.

**Comment by srivatsn** [comment]
The dialog is now owned by CPS - can you file a CPS bug?

**Comment by srivatsn** [comment]
Filed https://devdiv.visualstudio.com/DevDiv/_workitems?id=433751&fullScreen=false&_a=edit on CPS.
