### ISSUE TITLE
We should be respecting $(ProjectAssetsFile)

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1437]
We find the assets files ourselves in the ProjectLockFileWatcher. We shouldn't be doing that, we should respecting $(ProjectAssetsFile).
See: https://github.com/NuGet/Home/issues/4463#issuecomment-276832985

**Comment by nguerrera** [comment]
Something just occurred to me. @dsplaisted  made changes so that SDK will not default ProjectAssetsFile and instead use what restore writes to generated temp props. Would this create a chicken-and-egg problem for initiating the watch when restore hasn't been done yet?

**Comment by davkean** [comment]
@nguerrera Yes, this is a chicken and egg. If we can't find $(ProjectAssetsFile) we can't tell CPS that it needs to reevaluate. We were also planning to move to a model where CPS itself monitored the file based on https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L281 but sounds like this would also be broken by that.

**Comment by nguerrera** [comment]
:(

**Comment by dsplaisted** [comment]
I don't know how feasible this is, but I think the "right" thing to do would be to monitor the `MSBuildProjectExtensionsPath`.  NuGet restore will drop .props and .targets which should be imported there, as well as the assets.json file.  So when the new .props and .targets show up there the project should be re-evaluated.  The .props file will then set the `ProjectAssetsFile` property, and you can then additionally watch for changes in that file if it's necessary.

**Comment by davkean** [comment]
We already monitor the props/targets when we reevaluate and they appear, also wouldn't play nicely with shared intermediates.

Was this change to remove logic from SDK? If so, can we add it back to NuGet targets?

**Comment by davkean** [comment]
- Assets file changed
- Reevaluate
- New props/targets are picked up

We don't monitor for props/targets existence under they appear in evaluation - there's thousand of locations they could appear.

**Comment by dzmitry-lahoda** [comment]
Not sure if right thread - but some tooling is wrong...

See the line with `ProjectAssetsFile`? If I remove it - my `csproj` fails to build. 
Why I ever need it? My task for to build from VS 2017 and VS Code and from `dotnet` command line into `.bin` and `.obj` because of Unity:(. So I did it. But when VS 2017 opens solution - it generates `obj`. So I did fix which kinda should work.  But got issues - I followed the path, and got into `C:\Program Files\dotnet\sdk\2.2.102\Sdks\Microsoft.NET.Sdk\targets\` folder and into `ProjectAssetsFile`. So here is fix:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <!-- fixing VS 2017 bug which makes it output directory which is not requested -->
  <PropertyGroup>
    <ProjectAssetsFile>$(MSBuildProjectDirectory)\.obj\project.assets.json</ProjectAssetsFile>
  </PropertyGroup>
  <PropertyGroup>
      <PreBuildEvent>
       IF EXIST "$(MSBuildProjectDirectory)\.obj\obj" (
         rmdir "$(MSBuildProjectDirectory)\.obj\obj" /s /q
       )
       IF EXIST "$(MSBuildProjectDirectory)\obj" (
         move  "$(MSBuildProjectDirectory)\obj" "$(MSBuildProjectDirectory)\.obj"
       )
      </PreBuildEvent>
      
      <PostBuildEvent>
       IF EXIST "$(MSBuildProjectDirectory)\.obj\obj" (
         rmdir "$(MSBuildProjectDirectory)\.obj\obj" /s /q
       )
       IF EXIST "$(MSBuildProjectDirectory)\obj" (
         move  "$(MSBuildProjectDirectory)\obj" "$(MSBuildProjectDirectory)\.obj"
       )
      </PostBuildEvent>      
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>.bin\Debug\</OutputPath>
    <BaseIntermediateOutputPath>.obj\Debug\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>.obj\Debug\</IntermediateOutputPath>
    <BaseOutputPath>.bin\Debug\</BaseOutputPath>
    <UseCommonOutputDirectory>true</UseCommonOutputDirectory>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>.bin\Release\</OutputPath>
    <BaseIntermediateOutputPath>.obj\Release\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>.obj\Release\</IntermediateOutputPath>
    <BaseOutputPath>.bin\Release\</BaseOutputPath>
    <UseCommonOutputDirectory>true</UseCommonOutputDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="xunit" Version="$(xUnitVersion)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(xUnitVersion)" />
  </ItemGroup>
  </ItemGroup>  
</Project>
````


There is other workaround. Very weird - depends on order of and some hacky `Import` declarations, but it breaks `xunit` runner and VS Code. Ssee lines with `Microsoft.NET.Sdk`:
```xml
<Project>
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>.bin\Debug\</OutputPath>
    <BaseIntermediateOutputPath>.obj\Debug\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>.obj\Debug\</IntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>.bin\Release\</OutputPath>
    <BaseIntermediateOutputPath>.obj\Release\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>.obj\Release\</IntermediateOutputPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <ItemGroup>
    <None Remove=".gitignore" />

    <None Remove="**/*.meta" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Buffers" Version="4.5.0" />
    <PackageReference Include="System.IO.Pipelines" Version="4.5.3" />
    <PackageReference Include="System.Memory" Version="4.5.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2" />
  </ItemGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
```
Does next relates #1438? 

I was not able to find solution on SO.

**Comment by nguerrera** [comment]
@dzmitry-lahoda I've moved your question to https://github.com/dotnet/sdk/issues/3009

It is not necessary to change ProjectAssetsFile to achieve what you want. I will discuss the options over there.
