### ISSUE TITLE
Projects implicitly get a RELEASE constants, but treated differently to DEBUG

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1439]
![image](https://cloud.githubusercontent.com/assets/1103906/22537909/ac13526e-e962-11e6-9e63-b7aff2dc1491.png)

Notice the DEBUG check box, we should have one for RELEASE or treat DEBUG the same as we treat RELEASE.

**Comment by drewnoakes** [comment]
This is unlikely to be changed in the legacy property pages. However we will consider this a feature request of the new property pages.

**Comment by drewnoakes** [comment]
The new UI doesn't treat DEBUG especially over RELEASE or any other symbol.

![image](https://user-images.githubusercontent.com/350947/162987517-b0bab178-e1bd-4f46-a6c9-ef14e8c9cdba.png)

We're unlikely to change how this works in the legacy UI.
