### ISSUE TITLE
If you customize conditional constants, and then switch targets, the "implicit" constants get baked in

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1440]
1. File -> New -> Class Library (.NET Standard)
2. Project Properties -> Build -> Add ";FOO" to conditional symbols
3. Retarget from .NET Standard 1.4 -> .NET Standard 1.6
4. Close Project Properties
5. Reopen Project Properties -> Build
6. Constants are even though I'm targeting 1.6:

```
NETSTANDARD1_4;FOO
```

Really think we need to rethink how this works - CPS has support for this with the properties, you add the constants after the project in targets, and you tell CPS to grab the browse object property before then.

**Comment by dsplaisted** [comment]
So you're saying we should add these implicit compilation constants in a target instead of evaluation.  That would be an SDK change, right?  Is there anything that would need to change in the Roslyn repo for this?

**Comment by davkean** [comment]
I'm not sure. We can certain customize when we ask for the property - ie we can tell CPS get the value of the property at the point it is defined in the project (ie don't ready targets).

**Comment by natidea** [comment]
The root cause of this is probably https://github.com/dotnet/project-system/issues/2720. Once the explicit constant is removed from the project file, retargeting the project correctly updates the constants.
