### ISSUE TITLE
Resolved references have different properties to unresolved references

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1480]
Unresolved reference:

![image](https://cloud.githubusercontent.com/assets/1103906/22678436/2f1eddd8-ed4e-11e6-9883-8297ad643b45.png)

Resolved references:

![image](https://cloud.githubusercontent.com/assets/1103906/22678488/947455be-ed4e-11e6-8cdd-3042573cc0c3.png)

These are supposed to contain the same properties.

**Comment by abpiskunov** [comment]
dupe of https://github.com/dotnet/roslyn-project-system/issues/59

**Comment by davkean** [comment]
This isn't a dupe, that bug is "make them the same as CSProj" - this is; resolved references are different from unresolved references. You can fix this one without the other. Or vice versa.

**Comment by abpiskunov** [comment]
hm yeah if you read it directly - you are right :). However for issue i mentioned, i wanted to do a complete review of all properties for all dependency types and that would include issue you reported. Anyway , let's keep it just in case.

**Comment by srivatsn** [comment]
Fixed by #2209
