### ISSUE TITLE
Improved CPS analyzer project template

### ISSUE THREAD

**Issue by jnm2** [dotnet/project-system#1481]
At some point in the future, it would be nice to have an upgrade to the current "Analyzer with Code Fix (NuGet + VSIX)" template.

The current template relies on this target in the analyzer project in order to build the VSIX project (which I only do in order to debug):

```xml
<Target Name="AfterBuild">
  <GetAssemblyIdentity AssemblyFiles="$(OutDir)\$(AssemblyName).dll">
    <Output TaskParameter="Assemblies" ItemName="AnalyzerAssemblyInfo" />
  </GetAssemblyIdentity>
  <Exec Command="&quot;$(SolutionDir)packages\NuGet.CommandLine.2.8.5\tools\NuGet.exe&quot; pack Diagnostic.nuspec -NoPackageAnalysis -Version %(AnalyzerAssemblyInfo.Version) -OutputDirectory ." WorkingDirectory="$(OutDir)" LogStandardErrorAsError="true" ConsoleToMSBuild="true">
    <Output TaskParameter="ConsoleOutput" PropertyName="OutputOfExec" />
  </Exec>
</Target>
```

This in turn means that you're stuck with NuGet v2's packages.config, and it makes upgrading packages difficult because you have to maintain the `$(SolutionDir)packages\NuGet.CommandLine.2.8.5` path in the project file.

Since the CPS csproj will support NuGet packing, will I be able to create a less hacky template? Could Microsoft maybe publish an improved template?

**Comment by srivatsn** [comment]
@jmarolf has been looking at updating the template.

**Comment by jmarolf** [comment]
see https://github.com/dotnet/roslyn-sdk

**Comment by jnm2** [comment]
@jmarolf Where are the SDK extensions published?
