### ISSUE TITLE
Support launching VSIX projects

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#1484]
VSIX projects are class libraries, but the VSSDK sets some variables to say it should launch VS in the dev hive. We should respect those flags so a launchSettings.json isn't needed to start VS.

**Comment by panopticoncentral** [comment]
This looks like we need to implement IDebugLaunchProvider after reading values from the project.

**Comment by davkean** [comment]
I suspect the existing LocalWindowsDebuggerService which we overrule will just work here.
