### ISSUE TITLE
Double-clicking an MSBuild error/warning from the current project does nothing

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1490]
1.

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <Target Name="Foo" AfterTargets="AfterBuild">
    <Error Text="This is an error" />
  </Target>
  
</Project>
```

2. Build
3. In Error List, double-click _This is an error_

**Expected:** To open the project file and navigate to the error
**Actual:** Nothing

If error/warning comes from another file then it works correctly.

**Comment by mavasani** [comment]
Not sure this works for desktop projects either - @heejaechang ?

**Comment by davkean** [comment]
It doesn't, but you can't open the project file while the project is open.

ie, Given we can open the project file now, we should be able to implement this.

We're just using the default logic of the Error List here - not using Roslyn or CPS, it must have a block here.

**Comment by davkean** [comment]
This was fixed in https://github.com/dotnet/project-system/issues/4061.
