### ISSUE TITLE
"Edit" command on project context menu should not include file name

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/project-system#1492]
Just a few thoughts on the "new" ability to edit csproj's with a simple right click.

1. Great that we can do it and its live. Love that.
2. ~The item being in the middle of the list is a bit odd. I associate it more with project properties and find my eyes often searching the list for it.~
3. I have some long project names and it feels out of place on the menu calling out the whole project name. I know which project I'm on. Just simplify it to "Edit csproj" like all the other things in the menu.
4. Keep up the good work :)

Hows that for a complement sandwich.

**Comment by davkean** [comment]
With regards to 3, I investigated. This command also shows in the Project menu, where you do want to disambiguate by including the project file. To do this, we're likely have to split the command into two; one for menu; one for context. This is similar to other commands.

**Comment by davkean** [comment]
Agree on the size aspect too:
![image](https://cloud.githubusercontent.com/assets/1103906/23406755/b6e94394-fe14-11e6-9fc9-8a5d2cf0af53.png)

It looks like cmdidProjectProperties (Project menu) and cmdidPropSheetOrProperties (context menu) are akin to what we need to here. We basically need to add a new command (and then fix up the stub hierarchy to also handle both).

**Comment by davkean** [comment]
We're going to make Edit more obvious via https://github.com/dotnet/project-system/issues/1224. I'll leave this one to track splitting the Project menu command and the context menu command into multiple commands.

**Comment by davkean** [comment]
Removing "Help wanted" on this @Pilchie. This requires mucking with context menus in core VS.

**Comment by davkean** [comment]
Have a PR out for this: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/161621?_a=overview.

**Comment by davkean** [comment]
This was fixed and merged.
