### ISSUE TITLE
Explicitly declaring TargetFrameworkVersion results in tons of errors

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/project-system#1498]
If you have a project that targets `net46;netstandard1.5` and if it mistakenly has an explicitly declared `<TargetFrameworkVersion>v4.6</TargetFrameworkVersion>` then building results in hundreds of errors such as `Predefined type 'System.Object' is not defined or imported` signaling that mscorlib wasn't passed to the compiler.

I wonder if there's something we can do to point the user to the erroneous TargetFrameworkVersion property since it's the culprit. The problem is that for customized builds this may be set in some Common.cs and only included in the project indirectly through Imports. This makes it even harder to understand what's going on.

**Comment by drewnoakes** [comment]
Can no longer repro this (with SDK 5.0.100-preview.8.20417.9). It may have been fixed for a while.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net46;netstandard1.5</TargetFrameworks>
    <TargetFrameworkVersion>v4.6</TargetFrameworkVersion>
  </PropertyGroup>

</Project>
```

Builds fine with:

```
1>------ Build started: Project: ConsoleApp251, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>ConsoleApp251 -> C:\Users\drnoakes\source\repos\ConsoleApp251\ConsoleApp251\bin\Debug\net46\ConsoleApp251.exe
1>ConsoleApp251 -> C:\Users\drnoakes\source\repos\ConsoleApp251\ConsoleApp251\bin\Debug\netstandard1.5\ConsoleApp251.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
