### ISSUE TITLE
Setting EnableDefaultCompileItems to False doesn't remove the files from solution Explorer

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/project-system#1504]
Create a ClassLibrary (.Net Core) 
Take a copy of Class1.cs and drop in the same folder
you will see of them included 
Now edit the csproj and put the below information 

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableDefaultCompileItems>False</EnableDefaultCompileItems>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
 <ItemGroup>
    <Compile Include="Class1.cs" />
 </ItemGroup>
</Project>
```
Build again , it includes only Class1.cs but the solution explorer shows all files, expected ? 

![image](https://cloud.githubusercontent.com/assets/12449387/22761664/9c18182e-ee10-11e6-8ccb-400383d403ff.png)

**Build**
26206.0.d15rel

**Comment by davkean** [comment]
This is because `<None>` picks them up. @dsplaisted

**Comment by srivatsn** [comment]
Another side effect of this reported through [VSFeedback] (https://developercommunity.visualstudio.com/content/problem/20512/when-enabledefaultcompileitemsfalse-new-compile-it.html) is that when the user goes to add a cs file to the project in this state, the None glob picks it up and so it's not passed to the compiler as a source file.

**Comment by davkean** [comment]
Ah, that's bad.

**Comment by srivatsn** [comment]
Moving this to SDK since this is caused by the None globs - @dsplaisted are they really useful? I find the None globs more annoying than useful since it picks up all files in that folder

**Comment by srivatsn** [comment]
This issue was moved to dotnet/sdk#1157

**Comment by Va9u3** [comment]
use false instead of False

**Comment by baskren** [comment]
Looks like this issue is back with Version 16.9.0

**Comment by dsplaisted** [comment]
@baskren This is an old issue, could you file a new one with details / repro steps if you're still hitting something like this?

Thanks,
Daniel

**Comment by baskren** [comment]
@dsplaisted 👍 

Done: https://github.com/dotnet/project-system/issues/7002
