### ISSUE TITLE
Utilise nameof() 

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/project-system#151]
We should be using `nameof()` over including the name in a string literal.

**Comment by davkean** [comment]
Will happily take a contribution for this.

**Comment by AdamSpeight2008** [comment]
@davkean 
Will it OK to implement this project by project ( ie a different branch), then file by file and then commit.?
So I they are accept, the merges can be do when each is ready.

**Comment by davkean** [comment]
I'll accept a single commit per project, but don't do a commit for each file as I'll just end up squashing it.

**Comment by MaximRouiller** [comment]
@davkean There's a PR for this (#357).

Is work still required for this?

**Comment by davkean** [comment]
I'm going to close this out, the PR has been abandoned. While we'll still welcome contributions and changes to make our code following our own [Coding Conventions](https://github.com/dotnet/project-system/blob/master/docs/repo/coding-conventions.md#code) - we don't need bugs to track this sort of work; if it happens, it happens.
