### ISSUE TITLE
Targets that are removed, renamed or have their dependencies changed leaves stale warnings/errors in the Error List

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1510]
Identified as part of fixing this: https://github.com/dotnet/roslyn-project-system/issues/1426.

1. Create a new project
2. Edit project
3. Add:

```
  <Target Name="Foo" AfterTargets="ResolveProjectReferences">

    <Warning Text="Foo" />
  </Target>
```

4. Save

-Notice warning appears in the Error List-

5. Rename the target
6. Save

**Expected:** Only a single warning
**Actual:** Two warnings

**Comment by davkean** [comment]
This is due to the way these are logged to the Error List (see VsErrorListLogger in CPS) - basically we associate messages with targets, and every time we see the target run we "refresh" the messages that were logged during the last run.  If we never see a target run again, we'll never remove the warnings/errors. 

We should be listening to targets changes including a change in their dependencies and maybe remove all errors associated with a particular target?

**Comment by davkean** [comment]
I suspect this, rather than the above bug is why errors/warnings stick around when retargeting. @srivatsn @mavasani

**Comment by srivatsn** [comment]
Verified that this has now been fixed.
