### ISSUE TITLE
Need to get target frameworks info from nuget instead of just operating with strings

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#1516]
Currently we only use strings specified in TargetFramework or TargetFrameworks properties and they are not "friendly" for  users in cases we need to show them and internally in the code we need to parse them everytime.

Instead we need to have a service that would access nuget IVs interop API and get framework metadata  and cache it). Then we could have a 

ITargetFramework  {
 string ShortName
 string Version
 string Moniker,
 string FriendlyName
}

similarly to what we had in Dev14

**Comment by davkean** [comment]
We decided a while back that NuGet doesn't own this concept, it's a VS concept and as such we're going to update multi-targeting service to understand this.

**Comment by panopticoncentral** [comment]
Fixed with #795
