### ISSUE TITLE
Resx files are not generated in the design time build

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#1521]
1. Create a new dotnet core Console Application
2. Add a Resource file and create a string named String1
![image](https://cloud.githubusercontent.com/assets/9797472/22807088/254c898a-eeda-11e6-998e-ba27116fe67e.png)
3. Go and use `Resource1.String1` in a code file.
![image](https://cloud.githubusercontent.com/assets/9797472/22807110/3f953238-eeda-11e6-977f-2792f564209a.png)

Expected: resx file tools are run and String1 property is generated

Actual: Project needs to be rebuilt for resx files to generate

**Comment by davkean** [comment]
This isn't design-time build, but rather the single file generator getting run.

I cannot repro this - do you have a consistent repro? If so, can you add the exactly steps (including what windows have focus)?

**Comment by jmarolf** [comment]
@davkean you see no errors at all? which build are you on?

**Comment by davkean** [comment]
Yesterdays

**Comment by jmarolf** [comment]
@davkean  http://recordit.co/5QFcOkeHAk

**Comment by jmarolf** [comment]
![image](https://cloud.githubusercontent.com/assets/9797472/22808488/02f1f2ba-eee1-11e6-9f7a-871e99d16dea.png)

**Comment by davkean** [comment]
Thanks - that's a great way to show me, upgrading to today's and trying again.

**Comment by davkean** [comment]
Okay, I can repro this now. It appears we are not running the SingleFileGenerator when we switch docs, which I thought was supposed to happen. Interestingly enough, if I open the Designer file, the generation occurs. Building also doesn't cause it to generate.

**Comment by davkean** [comment]
Looks like we don't run these when changing the default namespace either: https://github.com/dotnet/project-system/issues/1933.

**Comment by davkean** [comment]
Going to give this one to you Jon, I've got too much on my plate for 15.3.

**Comment by davkean** [comment]
We should figure out when the legacy project system runs these and run them at the same time.

**Comment by jmarolf** [comment]
NOTE: be sure to test case mentioned in #1845 when verifying this fix

**Comment by jmarolf** [comment]
Looking at our code we seem to be hooking everything up correctly for single file generators,  @lifengl is there a good way for a consumer of CPS to modify when single file generators are run?

**Comment by davkean** [comment]
Make sure you also try: https://github.com/dotnet/project-system/issues/1521.

**Comment by jamesqo** [comment]
@davkean You linked back to the same issue; I think you meant #2446.

**Comment by davkean** [comment]
@jamesqo Thanks, you would not believe how many times I do that.

**Comment by jmarolf** [comment]
Tracked in CPS with [453823](https://devdiv.visualstudio.com/DevDiv/_workitems?id=453823)

**Comment by davkean** [comment]
This isn't happening because the generator isn't running. This is happening because CPS is turning off change tracking for the generated file while it writes it to disk, causing Roslyn to not see/pick up the changes.
