### ISSUE TITLE
Copying and pasting a parent file, does not copy child's DependentUpon metadata

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1549]
1. Create a new Console App (.NET Core)
2. Add a Resources.resx
3. Copy Resources.resx 
4. Paste it in the same project

![image](https://cloud.githubusercontent.com/assets/1103906/22908458/b94cc19c-f2a2-11e6-8282-efa9c34bf18f.png)

**Comment by davkean** [comment]
Closed in lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workitems?id=397478&fullScreen=false&_a=edit.

**Comment by viktorveis** [comment]
https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workitems?id=397478&fullScreen=false&_a=edit was resolved as Won't Fixed due to lack of external feedback.

**Comment by davkean** [comment]
Using this bug to track this - there's no feedback because we haven't implemented any of the features that use DependentUpon yet, this will be part of the legacy project system bring up.

**Comment by tmeschter** [comment]
Tom's triage notes: I don't see any reason we need to do this, so I recommend closing the issue without fixing it.

**Comment by tmeschter** [comment]
We're not going to address this in the legacy project system.

**Comment by davkean** [comment]
This is CPS.

________________________________

**Comment by davkean** [comment]
This is a CPS issue, but I've played around with this and it no longer repros, even when pasting into a legacy or CPS project.
