### ISSUE TITLE
You get lots of project faults or crashes, if you introduce an error into a project that breaks evaluation

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1570]
See the linked issues that have been dup'd against this.

**Comment by davkean** [comment]
See: https://github.com/dotnet/roslyn-project-system/issues/1435 for an approach of this.

**Comment by srivatsn** [comment]
Another repro for a crash from [VSFeedback](https://developercommunity.visualstudio.com/content/problem/29176/crash-adding-empty-props-file.html) - add an empty props file and import it from the csproj, VS goes down hard.

**Comment by srivatsn** [comment]
The reload code is now in CPS and @jviau has implemented guards against crashing in error scenarios.

**Comment by davkean** [comment]
I'd like to try all the scenarios we linked this again.

**Comment by ivanbasov** [comment]
@davkean, any update on this issue since July? It is scheduled for 15.5 which is in escrow.

**Comment by Pilchie** [comment]
So, @jviau updated the reload code recently - sounds like this is about testing the related scenarios now? @jmarolf - can you take a look?

**Comment by davkean** [comment]
Yeah, we didn't really handle all sorts of errors until 15.6, which now puts a guard around missing target's files.

**Comment by Pilchie** [comment]
@richaverma1 - Can you help with some testing around this scenario?

**Comment by richaverma1** [comment]
@Pilchie, sure. I'll have all the linked issues verified. What else will need to be tested? Can you give me more context?

**Comment by Pilchie** [comment]
@jviau or @jmarolf maybe you can describe it?

**Comment by Pilchie** [comment]
Ping @jviau and @jmarolf - would be nice to get this verified and closed out.

**Comment by jviau** [comment]
The scenarios to verify are:

1) Missing import
2) Empty import
3) Invalid import

With each one, test having it be valid and then become invalid and also have it be invalid the first time it appears in the import graph.

I tested these all myself when I recently did the improvements in 15.6, but feel free to verify again.

**Comment by Pilchie** [comment]
I'm going to go ahead and close this.
