### ISSUE TITLE
Dragging/dropping multiple files in quick succession in Solution Explorer causes the application to crash

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1571]
(Opened from: https://developercommunity.visualstudio.com/content/problem/8918/draggingdropping-multiple-files-in-quick-successio.html)

* When I drag a file to a new location in the solution explorer, a pop up opens asking me to confirm if I want to update references.
* There is a slight delay to this pop up appearing.
* If I start to drag a new file around before the pop up has appeared, the system gets confused and never finishes loading. Requires me to kill it in Task Manager and then reopen it again.
* Expected Result: the pop up appears quicker, and I can't use Solution Explorer until the pop up has been dismissed.

NB: on a side note, its not clear what this pop up actually does, if anything.

**Comment by Pilchie** [comment]
Is this the new project system, or the old?  Is the dialog in question the rename dialog?  What is changing the filename here?

**Comment by Pilchie** [comment]
@tmeschter can you followup with the customer who filed the developer community item?

**Comment by davkean** [comment]
New project system. The renamer listens to workspace events and will easily get confused by multiple changes.

**Comment by davkean** [comment]
This no longer occurs in 16.5, presumbly fixed when we rewrote the rename logic.
