### ISSUE TITLE
Optimize CPS subscriptions in LangaugeServiceHost

### ISSUE THREAD

**Issue by mavasani** [dotnet/project-system#1583]
With https://github.com/dotnet/roslyn-project-system/pull/1572, our LanguageServiceHost now creates DT and evaluation subscriptions per project configurations, but never disposes them until the project is disposed. This was done to prevent duplicate subscriptions. However, Lifeng suggested we should still do some optimization to avoid holding onto the subscription related objects in memory when the configuration is removed. See https://github.com/dotnet/roslyn-project-system/pull/1572#discussion_r101657018 for Lifeng's suggestion.

**Comment by Pilchie** [comment]
@davkean is this something you'll be looking at with your current work around the language service host?

**Comment by davkean** [comment]
Yep.

**Comment by davkean** [comment]
We're rewriting this - so closing this.
