### ISSUE TITLE
[Feedback] IIS Express launch profile not used

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/project-system#1596]
Created from https://vsfeedback/comment/803555

In some cases when I create a new ASP.NET Core project and open it in VS the IIS Express launch profile doesn't get used when I hit F5.
Repro steps:
1. mkdir iisexpresslaunchprofilerepro
2. cd iisexpresslaunchprofilerepro
3. dotnet new sln
4. mkdir testproject
5. cd testproject
6. dotnet new web
7. cd ..
8. dotnet sln add testproject/testproject.csproj
9. Open iisexpresslaunchprofilerepro in VS
10. F5
Expected result:
- Runs using IIS Express
Actual result:
- The launch button shows the IIS Express launch profile, but the project runs as a console project instead
Workarounds:
- Switching the selected launch profile between the project launch profile and the IIS Express launch profile seems to resolve the issue

**Comment by BillHiebert** [comment]
This is a consequence of the 2nd item in issue https://github.com/dotnet/roslyn-project-system/issues/495. Updates tot he profiles need to be serialized.

**Comment by davkean** [comment]
@BillHiebert @srivatsn This is in 15.1 milestone, do we want to move this to 15.2 or 15.3?

**Comment by srivatsn** [comment]
This has been fixed by @BillHiebert
