### ISSUE TITLE
Create dependencies node integration tests

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/project-system#1607]
Ask @abpiskunov about what scenarios needs to be tested.

One thing we need to test is that analyzers and diagnostics show properly when multiple projects are in the same directory. We broke this in https://github.com/dotnet/roslyn/pull/18888 and fixed it in https://github.com/dotnet/roslyn/pull/19188.

**Comment by srivatsn** [comment]
@abpiskunov you are working on this - correct?

**Comment by abpiskunov** [comment]
Actually no, i am working unit tests right now and then will do corresponding changes for web package nodes. Will not have time for integration tests.. Could  you assign to some one else on your team please? I can suggest scenarios etc ..

**Comment by MattGertz** [comment]
Mondo escrow triage:  test-only, moving to 15.4 to get it off the radar,

**Comment by tmeschter** [comment]
We're in the process of re-evaluating our integration test framework. This will be addressed in 15.6 at the earliest.

**Comment by drewnoakes** [comment]
I've started writing integration tests for the dependencies node.

This required some changes to Apex, submitted in https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/169060.

That PR has been merged, but the process that pushes packages to the MyGet feed we consume broke as part of a migration to cloud build (as I understand it). @javierdlg is looking into this.

**Comment by drewnoakes** [comment]
The Apex changes are now available on myget. Draft PR #4658 includes them and will close this issue once completed.

**Comment by drewnoakes** [comment]
Closing this as #5251 was merged.
