### ISSUE TITLE
Target framework drop down behaves inconsistently

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/project-system#1611]
1. New asp.net web application
2. Edit the project file and add net452 as a 2nd framework
3. Open startup.cs. On my machine it defaults to net452 even though it is 2nd in the <TargetFrameworks> property. Change to 1.1
4. Open program.cs.  It opens as net452. 
5. Switch back to startup.cs. It flips to net452.  Change it to 1.1
6. Switch back to program.cs. It remains as net452. 
7. Close all documents. Open startup.cs - it is net452, change it to 1.1 and close it.
8. Reopen startup.cs. it is at net452.

This is completely inconsistent and varies depending on how much you play with it. Sometimes the framework appears project wide and sometimes per document.

Do the same test with Shared projects. Changing the framework changes it for all documents in the project. It is remembered after closing all documents and even closing and reopening the solution.

**Comment by mavasani** [comment]
I think these issues are likely due to the 3 issues mentioned here: https://github.com/dotnet/roslyn-project-system/issues/1013#issuecomment-282153150

**Comment by srivatsn** [comment]
Is this now fixed with your changes @mavasani ?

**Comment by srivatsn** [comment]
Verified that this is now fixed.
