### ISSUE TITLE
[Question] - Aditional debug targets

### ISSUE THREAD

**Issue by dazinator** [dotnet/project-system#1616]
Hello,
I am having an issue where, I have my own CPS based project system, and when I include csharp targets in my project file, I see a debug target generated for my project based on my project name.

However I have tried removing the "LaunchProfiles" capability by adding an msbuild item (with remove key) - so basically csharp targets includes LaunchProfiles capability and then later in my own project file, I remove that capabitlity - however, even when I do this - I am still seeing the additional / default debug target - and I can still launch the managed debugger against that target - where as I would expect removing the capability to remove this target?

If I remove csharp targets completely, then the debug target does go away - which is what I want - except that then then I lose Csharp build support!

More info here: https://github.com/Microsoft/VSProjectSystem/issues/189

Just wondering if this behaviour is the expected behaviour, or could this be a bug?

Thanks

**Comment by davkean** [comment]
As mentioned here: https://github.com/dotnet/project-system/issues/1733 you can implement IDynamicDebugTargetsGenerator to control this.

**Comment by dazinator** [comment]
@devkean I have implemented this interface, and I only return debug targets x y and z

**Comment by aienabled** [comment]
It seems [this approach](https://github.com/Microsoft/VSProjectSystem/issues/189#issuecomment-335367253) is currently the only way of ridding default debug target.
