### ISSUE TITLE
Add a reference from one projects to results in a warning icon in Dependency node

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1627]
Build: 26217.2.d15rel

1. Add a new Console App (.NET Core)
2. Add a new Library (.NET Core)
3. Add a reference from app -> library

Expected: No warning symbol on the project
Actual: Warning symbol on the project, no errors in the Error List

![image](https://cloud.githubusercontent.com/assets/1103906/23346588/85e97370-fcef-11e6-8615-77b2556d3939.png)

**Comment by davkean** [comment]
This is every project - @abpiskunov, what is this?

**Comment by davkean** [comment]
If I close the solution and reopen, the warning goes away.

**Comment by abpiskunov** [comment]
Hard to say it could be timing on our side or CPS tree update issue , we saw similar thing for Bower nodes , when we know for sure we did send update to CPS and it changed icon maybe in a minute after that ..  I will take this bug for myself since it should be affected by my pending changes.

**Comment by abpiskunov** [comment]
Fixed with https://github.com/dotnet/project-system/pull/1880
