### ISSUE TITLE
Auto restore does not work in ProjectSystem.sln

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1633]
1. Open post-Dev15 branch with the new SDK changes
2. Open ProjectSystem.sln
3. Right-click Toolsets -> Edit
4. Remove Microsoft.Net.Compilers
5. Save

Expected: Auto-restore to kick off
Actual: Auto-restore is not kicked off

I think at one point we disabled restore during build for our solution - if we did I can't find it.

**Comment by natidea** [comment]
Tried this on a few projects. I observed that restore eventually kicks in but takes a long time to start (~10 seconds). This looks like a perf issue.

**Comment by davkean** [comment]
I suspect this was due to the issue when we still opt'd in the legacy project system for the VB projects, and NuGet wouldn't restore due to the variables in the reference.
