### ISSUE TITLE
Analyzer references have a broken warning symbol in ProjectSystem.sln

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1634]
![image](https://cloud.githubusercontent.com/assets/1103906/23358109/c4a52cfe-fd34-11e6-8790-31e5b05a2c8b.png)

No errors/warnings in the ErrorList.

**Comment by abpiskunov** [comment]
Those are unresolved references (AnalyzerReference rule) , looks like DT build did not send ResolvedAnalyzerReferences updates or  something happened during tree update and it did not update. I will get this bug for now, it should be implicitly addressed by my pending changes...

**Comment by mavasani** [comment]
While debugging, I have generally noted that the CPS sends a separate DT update for analyzer references sometime after it sends the update with options/references/source files. Not sure why this is the case though, or if it happens all the time.

**Comment by abpiskunov** [comment]
Tried that just now - does not repro when existing analyzer dll is specified:

![image](https://cloud.githubusercontent.com/assets/1592091/24820740/79cd3238-1b9f-11e7-9971-a1ce003eab8c.png)

**Comment by srivatsn** [comment]
This is still broken in the project system solution.
