### ISSUE TITLE
Debug -> [Project] Properties does not show the Debug page

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1654]
1. File -> New Console App (.NET Core)
2. Menu bar -> Debug -> [Project] Properties(Not right click- Project -> Properties)

Expected: For the Debug page to be open
Actual: Application page is open

We are supposed to be handling VSHPROPID_ProjectPropertiesDebugPageArg and return the Debug property page.

**Comment by davkean** [comment]
Looks like CPS is missing the extension point for this. It's just returning a random GUID: http://index/?leftProject=Microsoft.VisualStudio.Shell.Interop.11.0&leftSymbol=jvpsskbsj3qm&rightProject=Microsoft.VisualStudio.ProjectSystem.VS.Implementation&file=PropertyPages%5CDebuggerPropertyPageGuidProvider.cs&line=16.

**Comment by basoundr** [comment]
With the current state of master, this issue does not repro. Closing this issue. Please reopen if you are still seeing it.

**Comment by davkean** [comment]
This still repros.

**Comment by basoundr** [comment]
#2108 fixed this issue
