### ISSUE TITLE
CodeLens is broken after you change the TFM

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/project-system#1656]
**Repro steps**

Create a .Net Core console application 
Change tfm to .netcoreapp1.0
Create a .Net Core class library , point to tfm .netcoreapp1.0
Add a reference from console to class library 
Add a method and call from Console application
Make sure code lens shows correctly 
Now go and change the tfm of console applciation from  .netcoreapp1.0 to .netcoreapp1.1
build , view the codelens again 

**Expected**
Code lens should show up correctly 

**Actual**
references are shown as 
     -references or 0 references 

**Note:**
close the solution and reopen fixes the issue

**Comment by davkean** [comment]
@srivatsn Can you give this to someone else?

**Comment by srivatsn** [comment]
I was able to repro this without the language service fixes and cannot repro it with it. Closing as fixed.
