### ISSUE TITLE
Changing TFM from .NET Core 1.1 -> 1.0 breaks intellisense

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1667]
1. File-> New .NET Core App 1.1
2. Right-click on project -> properties
3. Retarget from .NET Core App 1.1 -> 1.0
4. Program.cs ends up in Misc projs.

**Comment by mavasani** [comment]
We seem to be getting a successful design time build after this TF change, and also receive correct references, and in fact also get added source items for all assembly info and temporary generated files, but the primary Program.cs file is missing from the design time build for new TF. Not sure if this is related to the MSBuild DT issue or a separate CPS/SDK bug where this file is getting excluded.

**Comment by srivatsn** [comment]
Also reported here - https://developercommunity.visualstudio.com/content/problem/47859/changing-the-tfm-will-make-vs-show-false-squiggles.html

**Comment by davkean** [comment]
This was fixed by: https://github.com/dotnet/project-system/pull/2178.
