### ISSUE TITLE
Update 3rd party notice for nuget.exe

### ISSUE THREAD

**Issue by richlander** [dotnet/project-system#1675]
https://github.com/dotnet/roslyn-project-system/blob/master/build/bin/nuget.exe

Is this file needed? I thought that this need went away a long time ago, and it certainly doesn't work off of Windows.

This file is currently unattributed, so is violating our licensing policy. We could attribute it, but I'd prefer to just delete it.

/cc @davkean

**Comment by davkean** [comment]
We're still using it for pack at the moment. This repo doesn't build cross platform, so that's not a problem.

**Comment by richlander** [comment]
OK. Can you replicate the following for your repo and then close this issue?

https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/THIRD-PARTY-NOTICES

**Comment by davkean** [comment]
Yep, okay.

**Comment by tannergooding** [comment]
Is it not possible to just pull this file down from the NuGet downloads URL, like we do for our other repositories?

**Comment by davkean** [comment]
Yes, we are considering that - though might bite the bullet and move to our new pack support in csproj.

**Comment by tannergooding** [comment]
This was resolve by moving to the repo toolset (CC. @tmat)
