### ISSUE TITLE
Errors don't show up in Error List due to projects having the wrong name

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1713]
Ran into a situation in the project system where Errors aren't showing up for a particular project:

```
1>------ Build started: Project: Microsoft.VisualStudio.ProjectSystem.Managed, Configuration: Debug Any CPU ------
2>------ Build started: Project: Microsoft.VisualStudio.ProjectSystem.Managed.TestServices, Configuration: Debug Any CPU ------
3>------ Build started: Project: VisualStudioEditorsSetup, Configuration: Debug Any CPU ------
2>Microsoft.VisualStudio.ProjectSystem.Managed.TestServices -> E:\project-system\bin\Debug\Tests\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.dll
1>Microsoft.VisualStudio.ProjectSystem.Managed -> E:\project-system\bin\Debug\Microsoft.VisualStudio.ProjectSystem.Managed.dll
4>------ Build started: Project: Microsoft.VisualStudio.ProjectSystem.CSharp, Configuration: Debug Any CPU ------
5>------ Build started: Project: Microsoft.VisualStudio.ProjectSystem.Managed.VS, Configuration: Debug Any CPU ------
6>------ Build started: Project: Microsoft.VisualStudio.ProjectSystem.VisualBasic, Configuration: Debug Any CPU ------
3>VisualStudioEditorsSetup -> E:\project-system\bin\Debug\VisualStudioEditorsSetup.dll
4>Microsoft.VisualStudio.ProjectSystem.CSharp -> E:\project-system\bin\Debug\Microsoft.VisualStudio.ProjectSystem.CSharp.dll
6>Microsoft.VisualStudio.ProjectSystem.VisualBasic -> E:\project-system\bin\Debug\Microsoft.VisualStudio.ProjectSystem.VisualBasic.dll
3>VisualStudioEditorsSetup -> E:\project-system\bin\Debug\VisualStudioEditorsSetup.vsix
5>ProjectSystem\VS\Input\Commands\AbstractAddClassProjectCommand.cs(14,45,14,61): error CS0169: The field 'AbstractAddClassProjectCommand._serviceProvider' is never used
5>Done building project "v2sof1eu.tmp_proj" -- FAILED.
7>------ Build started: Project: Microsoft.VisualStudio.ProjectSystem.CSharp.VS, Configuration: Debug Any CPU ------
8>------ Build started: Project: Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS, Configuration: Debug Any CPU ------
7>Microsoft.VisualStudio.ProjectSystem.CSharp.VS -> E:\project-system\bin\Debug\Microsoft.VisualStudio.ProjectSystem.CSharp.VS.dll
8>Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS -> E:\project-system\bin\Debug\Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.dll
9>------ Build started: Project: ProjectSystemSetup, Configuration: Debug Any CPU ------
9>ProjectSystemSetup -> E:\project-system\bin\Debug\ProjectSystem.dll
9>ProjectSystemSetup -> E:\project-system\bin\Debug\ProjectSystem.vsix
10>------ Build started: Project: ProjectSystemDogfoodSetup, Configuration: Debug Any CPU ------
10>ProjectSystemDogfoodSetup -> E:\project-system\bin\Debug\ProjectSystemDogfoodSetup.dll
10>ProjectSystemDogfoodSetup -> E:\project-system\bin\Debug\ProjectSystemDogfoodSetup.vsix
========== Build: 9 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========
```

For some reason we're building with a temporary name (is this the unsaved path?) This going to cause CPS to skip over it here: http://index/?leftProject=Microsoft.Build.Framework&leftSymbol=ygyicldtigyb&rightProject=Microsoft.VisualStudio.ProjectSystem.VS.Implementation&file=Build%5CVsErrorListLogger.cs&line=179.

**Comment by davkean** [comment]
@lifengl @rainersigwald @cdmihai What's going on above here? Why is the project getting a temporary name? Is this when we ask you to build a project instance?

**Comment by davkean** [comment]
And is this supposed to be observable?

**Comment by davkean** [comment]
Okay, I'm repro'ing this pretty consistent in our ProjectSystem.sln repro - I've run into a few times now.

**Comment by cdmihai** [comment]
That probably happens when the BuildRequestData is based on a ProjectInstance which originates from in-memory data (e.g., based on a `Project` object that was created from an XmlReader, or an in-memory `ProjectRootElement`). In that situation, the ProjectInstance does not have a path, and the BuildManager assigns it a temporary name: https://github.com/Microsoft/msbuild/blob/xplat/src/Build/BackEnd/BuildManager/BuildManager.cs#L817-L833

BuildRequestData.ProjectFullPath is copied over from the ProjectInstance: https://github.com/Microsoft/msbuild/blob/xplat/src/Build/BackEnd/BuildManager/BuildRequestData.cs#L118

I don't know when VS creates an in-memory Project though.

**Comment by davkean** [comment]
@cdmihai Looks like a different path - that code you pointed to appends "Unnamed_" to the name.

**Comment by rainersigwald** [comment]
Is there a XAML project in the mix? Their build process generates a temporary project and builds it.

**Comment by davkean** [comment]
Yes there is - good catch, wondering why it's being built first before the compiler though, time to walk through the logs...

**Comment by davkean** [comment]
That would explain why we've never run into this before - I'm the first CPS project that builds XAML.

**Comment by davkean** [comment]
Microsofties, this was fixed by https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/138163?_a=overview.
