### ISSUE TITLE
You don't see top-level NuGet packages until a design-time build + restore has occured

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1714]
1. Change NuGet options to (to make it really obvious what's happening):

![image](https://cloud.githubusercontent.com/assets/1103906/23745649/13ce1b12-050d-11e7-804d-ee27492daee1.png)

2. File -> New Console App (.NET Core)

Expected: Dependencies node to show the top-level packages in the project (in this case NETCoreApp)
Actual: Dependencies node shows nothing.

**Comment by davkean** [comment]
We should be populating top-level nodes during evaluation.

**Comment by abpiskunov** [comment]
Should be fixed by my pending changes, will update when PR is complete.

**Comment by abpiskunov** [comment]
JUst tried it after https://github.com/dotnet/project-system/pull/1880 ,  removed obj and disabled nuget in Tools/Options. Everything shows up.
