### ISSUE TITLE
Unable to resolve valid project reference when using 2 netstandard class libs in one solution where one references the other

### ISSUE THREAD

**Issue by FransBouma** [dotnet/project-system#1717]
This exception requires some specific repro steps, I hope I have formulated them properly so you can reproduce them. I use a default vs2017 RTM pro installation. 

- Open vs 2017 RTM
- Add a new project -> Netstandard class library. Call it LibA
- Open LibA's properties, change its target to Netstandard1.6 (is 1.4 by default)
- Add a new project -> Netstandard class library. Call it LibB
- In LibB, add a project reference to LibA. VS will tell you it can't resolve LibA (which is obvious, as it's netstandard1.6, not 1.4 as is LibB)
- In LibB, add a nuget reference to Microsoft.EntityFrameworkCore.SqlServer. This will **fail**, and will give this error: `Package restore failed. Rolling back package changes for 'LibB'.`. 
- Change the target framework of LibB to Netstandard1.6
- Retry the nuget reference add step, it will fail again, and it will tell you again it can't resolve LibA. 

Compiling the solution works though. However adding the nuget reference keeps failing: 

```
Restoring packages for c:\Users\frans\documents\visual studio 2017\Projects\LibA\LibB\LibB.csproj...
Unable to resolve 'c:\Users\frans\documents\visual studio 2017\Projects\LibA\LibA\LibA.csproj' for '.NETStandard,Version=v1.6'.
Package restore failed. Rolling back package changes for 'LibB'.
Time Elapsed: 00:00:00.4899094
========== Finished ==========
```

Closing vs 2017 and restarting it, reloading the solution solves it. Saving the solution doesn't affect it. 

At one point I ran into the following exception when adding the nuget reference (file with stacktrace attached). 
```
=====================
9-3-2017 16:58:03
Crippling
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Could not resolve mscorlib for target framework '.NETStandard,Version=v1.6'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.
```
[VsProjectFault_f94b4a05-63f4-42f8-bbab-acf472289b41.failure.txt](https://github.com/dotnet/roslyn-project-system/files/831563/VsProjectFault_f94b4a05-63f4-42f8-bbab-acf472289b41.failure.txt)

Hopefully you can reproduce it with the steps I've provided.

**Comment by davkean** [comment]
The second issue is being tracked by https://github.com/dotnet/roslyn-project-system/issues/1322.

@natidea Can you look at the first issue?

**Comment by srivatsn** [comment]
The first part of this issue seems to be working in recent builds now. It looks like in the error case above, the project still thought that was it targeting netstandard1.4. We've made some changes between CPS\MSBuild and Projectsystem that's likely fixed that.
