### ISSUE TITLE
NuGet restore is incorrect in VS, correct on msbuild cmd line

### ISSUE THREAD

**Issue by onovotny** [dotnet/project-system#1722]
I’m getting a incorrect NuGet restore when it’s automatically run within VS 2017 RTW but a correct restore when run on the cmd line using msbuild /t:restore.

Clone https://github.com/reactive-Extensions/Rx.NET
Checkout commit e252efaab1637bb74593661248b0aacd9f7f0bbd

Open Source\Rx.NET\Source\System.Reactive.sln and wait for restore to finish.

Now go to the facades\System.Reactive.WindowsRuntime\obj directory and you’ll see that the generated props file does not contain any reference to the MSBuild.Sdk.Extras package that’s included from the Directory.build.targets two levels up (other projects in that directory work fine with them, including System.Reactive.Core).

This means the build fails because it’s not restoring the necessary targets for the uap10.0 to build (that are in that package).

If I close VS and do a git clean -xdf, then do an msbuild /t:restore System.Reactive.sln, the restore there generates the correct entries for the System.Reactive.WindowsRuntime project and the build succeeds. It will also succeed in VS afterwards too as the generated files are correct.

**Comment by davkean** [comment]
@natidea Can you figure out the underlying cause here and who's bug this is?

**Comment by davkean** [comment]
Are you hooking onto any restore targets?

**Comment by onovotny** [comment]
I don't believe so.

**Comment by onovotny** [comment]
Any updates here, at least identifying the issue?

**Comment by natidea** [comment]
Sorry for the delay. Let me dig into this using a newer build to see if it still repros

**Comment by onovotny** [comment]
I can say it still happens on 15.1, not sure about anything beyond that.

**Comment by natidea** [comment]
I was able to repro this on an RTW build, but not on a recent build from our development branch. I wonder if this is related to https://github.com/dotnet/project-system/issues/653#issuecomment-286391382 which calls out slightly different behavior between command line and VS restores. I'll make a little more effort to track down what may have changed to fix this before closing the bug

**Comment by davkean** [comment]
I asked about the restore targets above, @onovotny says he's not.

**Comment by natidea** [comment]
I'm tried again and was able to repro this on the latest 15.2 preview, but not on the latest 15.3 build. Most of the changes from our partner teams have gone into 15.3 so I expect it is fixed when that is released.
