### ISSUE TITLE
Fix and Cleanup Editors Unit Tests

### ISSUE THREAD

**Issue by basoundr** [dotnet/project-system#1724]
#1705 Added the unit tests for Editors from VSO to github. Currently, the tests are disabled from running.

[ ] Cleanup the unit test Project file. Involves removing Razzle related properties.
[ ] Fix project references/Assembly references and introduce Package references.
[ ] Remove some of the useless tests which are generated with test accessors.

**Comment by davkean** [comment]
We're never going to do this, closing this out.
