### ISSUE TITLE
[Question] - IVsProjectCfgDebugTargetSelection

### ISSUE THREAD

**Issue by dazinator** [dotnet/project-system#1733]
Any chance you could clarify where the implementation of `IVsProjectCfgDebugTargetSelection` is? It's mentioned here: 

https://github.com/dotnet/roslyn-project-system/blob/ef16880b0329cf833668657e86397e0a57e8b7fb/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Menus.vsct#L27

The reason I ask, is because I am trying to use the .vsct file above, for a VS2015 CPS extension, that implements `IDynamicDebugTargetsGenerator` to add additional debug targets to the "start" button.  I got this working in VS2017, but my vs2015 version doesn't end up having it's `IDynamicDebugTargetsGenerator` invoked at all. I am left wondering whether the same .vsct definition should work for VS2015 - or would things need to be different?

**Comment by davkean** [comment]
Sorry for the late reply, you're probably already fixed this out, but CPS has their own interface that extenders should export, called `IDynamicDebugTargetsGenerator`, our implementation is here: https://github.com/dotnet/project-system/blob/ed21d8f688d4d576bdbbdc42abd440928e5bb0bf/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/DebugProfileDebugTargetGenerator.cs.
