### ISSUE TITLE
Xamarin.Forms project targeting Microsoft.NET.Sdk fails, badly

### ISSUE THREAD

**Issue by nick42** [dotnet/project-system#1734]
Not sure if this is a known issue, but...

If you have a Xamarin.Forms PCL-type project, which is targeting netstandard (in my case, "netstandard1.4", which is the only version which will work with UWP projects currently), it fails to build after update. More specifically, it appears to fail to load the SDK at all.

Sample of [start of] build output:
1>Properties\AssemblyInfo.cs(11,12,11,25): error CS0246: The type or namespace name 'AssemblyTitleAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>Properties\AssemblyInfo.cs(11,12,11,25): error CS0246: The type or namespace name 'AssemblyTitle' could not be found (are you missing a using directive or an assembly reference?)
1>Properties\AssemblyInfo.cs(12,12,12,31): error CS0246: The type or namespace name 'AssemblyDescriptionAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>Properties\AssemblyInfo.cs(12,12,12,31): error CS0246: The type or namespace name 'AssemblyDescription' could not be found (are you missing a using directive or an assembly reference?)
1>Properties\AssemblyInfo.cs(13,12,13,33): error CS0246: The type or namespace name 'AssemblyConfigurationAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>Properties\AssemblyInfo.cs(13,12,13,33): error CS0246: The type or namespace name 'AssemblyConfiguration' could not be found (are you missing a using directive or an assembly reference?)
1>Properties\AssemblyInfo.cs(14,12,14,27): error CS0246: The type or namespace name 'AssemblyCompanyAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>Properties\AssemblyInfo.cs(14,12,14,27): error CS0246: The type or namespace name 'AssemblyCompany' could not be found (are you missing a using directive or an assembly reference?)
1>Properties\AssemblyInfo.cs(15,12,15,27): error CS0246: The type or namespace name 'AssemblyProductAttribute' could not be found (are you missing a using directive or an assembly reference?)
[...]

I have another class library targeting netstandard1.4 which is building fine after update; the only discernable differences in project files are:

- Reference to Xamarin.Forms, as:
```xml
  <PackageReference Include="Xamarin.Forms" Version="2.3.3.193" />
```

Inclusion of custom <ItemGroup> elements to work around new (broken) file detection for XAML with code-behind, eg:
```xml
  <ItemGroup>
    <None Remove="App.xaml" />
    <EmbeddedResource Include="App.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <Compile Update="App.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>App.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
```

I cannot tell what's going on, and/or how to resolve, and/or if there's something else I should be doing to make this [nominally now supported] project configuration work. Help?

Steps to repro, for reference:
- Create Xamarin.Forms PCL project
- Remove Xamarin.Forms reference from NuGet (pre-requisite to change framework to netstandard)
- Change framework to netstandard1.4
- Add Xamarin.Forms reference
- Observe CF

Additional notes:
- NuGet UI shows nothing installed in this state, and although it will allow adding references, nothing happens, and Installed pane is still blank.

**Comment by nick42** [comment]
Update:

In trying to track down this issue myself, I've discovered that the project.assets.json file in the "broken" project is, I believe, the proximate cause of the compilation issues, as it is very truncated. I still do not know why that is the case, or how to fix, but that seems to be why MSBuild is throwing up.

**Comment by nick42** [comment]
A few more comments based on my self-help efforts:

The dependency issue seems to be one with editing the .csproj file within VS2017, and a bad generation of the project.assets.json file. If I manually run 'dotnet restore' after every single project file update, I can generate a dependency file which is seemingly accurate.

The build is still failing, though, but now inside of the XamlCTask (inside Xamarin.Forms, in Xamarin.Forms.Build.Tasks.dll). Manually editing the .targets file to turn up the log verbosity just gives the searchpath adds, but no more indication of why it might be failing. Bug in Xamarin.Forms? No idea...

Broken on multiple levels at this point. =/

**Comment by nick42** [comment]
One more note, before I surrender to the opacity of the problem area:

I did try to downgrade to Xamarin.Forms 2.3.3.180 to see if that affected the issue, but it does not: still a failure with no explanation at the XamlCTask build step. I think I'm stuck as to potential workarounds as well. =/

**Comment by davkean** [comment]
@tannergooding Can you figure out all the bugs called out in this thread, and make sure we open them against the right teams?

**Comment by tannergooding** [comment]
After a bit of digging, the `XamlCTask` is failing due to the following:
```
Exception of type 'System.OutOfMemoryException' was thrown.
  + Microsoft.Cci.Pdb.MsfDirectory..ctor(Microsoft.Cci.Pdb.PdbReader, Microsoft.Cci.Pdb.PdbFileHeader, Microsoft.Cci.Pdb.BitAccess)
  + Microsoft.Cci.Pdb.PdbFile.LoadFunctions(System.IO.Stream, out Dictionary<uint, Microsoft.Cci.Pdb.PdbTokenLine>, out string, out int, out System.Guid)
  + Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
  + Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(Mono.Cecil.Cil.ImageDebugDirectory, byte[])
  + Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
  + Mono.Cecil.ModuleDefinition.ReadSymbols(Mono.Cecil.Cil.ISymbolReader)
  + Mono.Cecil.ModuleReader.ReadSymbols(Mono.Cecil.ModuleDefinition, Mono.Cecil.ReaderParameters)
  + Mono.Cecil.ModuleReader.CreateModuleFrom(Mono.Cecil.PE.Image, Mono.Cecil.ReaderParameters)
  + Mono.Cecil.ModuleDefinition.ReadModule(System.IO.Stream, Mono.Cecil.ReaderParameters)
  + Mono.Cecil.ModuleDefinition.ReadModule(string, Mono.Cecil.ReaderParameters)
  + Xamarin.Forms.Build.Tasks.XamlCTask.Compile(IList<System.Exception>)
```

**Comment by tannergooding** [comment]
Seems to be related to 'portable-pdb', as switching to a windows-pdb format causes build to succeed. Tagging @tmat

**Comment by tmat** [comment]
I believe the latest Mono.Cecil supports Portable PDBs. So it seem like the task needs to upgrade. @jbevain FYI

**Comment by srivatsn** [comment]
Closing this as external.
