### ISSUE TITLE
VS 2017 shows red squiggly on UseSqlSever when method is resolved

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/project-system#1741]
To reproduce:
1. Create new ASP.NET Core web app with all defaults.
2. Add Movie class

```
public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }
    }  
```

3.Scaffold
4. Build/run - it works fine.
5. Open _Startup.cs_ and UseSqlSever is underlined with red squiggly.  It shows the error:
'DbContextOptionsBuilder' does not contain a definition for 'UseSqlServer' and no extension method 'UseSqlServer' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by KatteKwaad** [comment]
Any idea on when a fix is coming?

**Comment by hernanbignone** [comment]
Still happend

**Comment by Rick-Anderson** [comment]
@hernanbignone  see https://github.com/aspnet/EntityFramework/issues/7891

**Comment by indiaweblab** [comment]
it worked by installing package Microsoft.EntityFrameworkCore.Sqlite.Core

**Comment by wpqs** [comment]
I need to use SQLServer, not SQLite so how do I proceed?

**Comment by shepherdnick** [comment]
Open your console and navigate to the project folder, then run this:

`dotnet add package Microsoft.EntityFrameworkCore.Sqlite`

You'll need to then add a `using Microsoft.EntityFrameworkCore.Sqlite` to the top of your class.

See here: [](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite)

**Comment by alirezaseif28** [comment]
yes.ok

**Comment by ollypapi** [comment]
You gonna need to install some nugget, create a table and do db-migration

**Comment by StuartMc77** [comment]
> Open your console and navigate to the project folder, then run this:
> 
> `dotnet add package Microsoft.EntityFrameworkCore.Sqlite`
> 
> You'll need to then add a `using Microsoft.EntityFrameworkCore.Sqlite` to the top of your class.
> 
> See here: https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite

Thank you... this worked for me after I've updated my app from core 2.1 to 3.1 it must've removed that using reference.  So easy to miss.

**Comment by TRUSTVIEWIO** [comment]
I don't get it.

 why all this..


Just add
using Microsoft.EntityFrameworkCore;

Just read the library before using it...  why nobody does that..

**Comment by jspalding70** [comment]
I am doing tutorial now which gave same issue until I added
Install-Package Microsoft.EntityFrameworkCore.InMemory

**Comment by TRUSTVIEWIO** [comment]
> I am doing tutorial now which gave same issue until I added
> Install-Package Microsoft.EntityFrameworkCore.InMemory

why do you need  Microsoft.EntityFrameworkCore.InMemory

To do UseSqlServer call

Which is static function in Microsoft.EntityFrameworkCore


  //
        // Summary:
        //     Configures the context to connect to a Microsoft SQL Server database.
        //
        // Parameters:
        //   optionsBuilder:
        //     The builder being used to configure the context.
        //
        //   connectionString:
        //     The connection string of the database to connect to.
        //
        //   sqlServerOptionsAction:
        //     An optional action to allow additional SQL Server specific configuration.
        //
        // Returns:
        //     The options builder so that further configuration can be chained.
        public static DbContextOptionsBuilder UseSqlServer([NotNullAttribute] this DbContextOptionsBuilder optionsBuilder, [NotNullAttribute] string connectionString, [CanBeNullAttribute] Action<SqlServerDbContextOptionsBuilder> sqlServerOptionsAction = null);
        //
        // Summary:
        //     Configures the context to connect to a Microsoft SQL Server database.
        //
        // Parameters:
        //   optionsBuilder:
        //     The builder being used to configure the context.
        //
        //   connection:
        //     An existing System.Data.Common.DbConnection to be used to connect to the database.
        //     If the connection is in the open state then EF will not open or close the connection.
        //     If the connection is in the closed state then EF will open and close the connection
        //     as needed.
        //
        //   sqlServerOptionsAction:
        //     An optional action to allow additional SQL Server specific configuration.
        //
        // Returns:
        //     The options builder so that further configuration can be chained.
        public static DbContextOptionsBuilder UseSqlServer([NotNullAttribute] this DbContextOptionsBuilder optionsBuilder, [NotNullAttribute] DbConnection connection, [CanBeNullAttribute] Action<SqlServerDbContextOptionsBuilder> sqlServerOptionsAction = null);

**Comment by Rick-Anderson** [comment]
@jspalding70 
>I am doing tutorial now which gave same issue until I added `Install-Package Microsoft.EntityFrameworkCore.InMemory`

That's in the tutorial.

**Comment by TRUSTVIEWIO** [comment]
> @jspalding70
> 
> > I am doing tutorial now which gave same issue until I added `Install-Package Microsoft.EntityFrameworkCore.InMemory`
> 
> That's in the tutorial.

Oka so you use SQLite

This topic its about MS SQL and EFCore..

When i work with EFCore
I use Microsoft.EntityFrameworkCore.SqlServer.dll and Microsoft.EntityFrameworkCore.Proxies.dll 
use of UseLazyLoadingProxies

Microsoft.EntityFrameworkCore.Sqlite better to use with Microsoft.EntityFrameworkCore.Proxies  then  Microsoft.EntityFrameworkCore.InMemory


CPU lower cost..

**Comment by sundardsTechMind** [comment]
Step 1: Right click your project
Step 2: Manage NuGet Package
Step 3. Browse tab
Step 4. Search ( Microsoft.EntityFrameworkCore.SqlServer )
Step 5. Install
Step 6. build 
Step 7. Success................................................................

 added package Microsoft.EntityFrameworkCore.SqlServer

**Comment by JacksReacher** [comment]
and we're supposed to use this in production? who is leading the team at Microsoft?

**Comment by JacksReacher** [comment]
I think the confusion is that people are trying this out for the first time and the little blue checkmark is confusing them into thinking the package is already installed.... not very good UI design IMHO

**Comment by marcotargino** [comment]
> Step 1: Right click your project
> Step 2: Manage NuGet Package
> Step 3. Browse tab
> Step 4. Search ( Microsoft.EntityFrameworkCore.SqlServer )
> Step 5. Install
> Step 6. build
> Step 7. Success................................................................
> 
> added package Microsoft.EntityFrameworkCore.SqlServer

Dude, u save me!!! Thanks bro! God bless ya
