### ISSUE TITLE
Rename often fails with unhelpful error

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1745]
About every 1 out of 5 renames fails with the following in the Project System repro:

```
---------------------------
Microsoft Visual Studio
---------------------------
Renaming the code element 'ProjectLockFileWatcher' failed.
---------------------------
OK   
---------------------------
```

**Comment by tannergooding** [comment]
@davkean, is this renaming of members, of files, of projects?

I've just spent about an hour trying to repro this on RTW to no avail (both with and without the debugger attached).

**Comment by davkean** [comment]
This is when you rename the type in Solution Explorer, we ask Roslyn to rename, see Renamer.cs. I've never seen this in a blank file, only our solution - it seems like a timing issue.

**Comment by tannergooding** [comment]
I was trying this with files in our solution (I ended up renaming some 200 files). If you could get a dump, that might be helpful.

**Comment by jmarolf** [comment]
This should be fixed
