### ISSUE TITLE
Add scenario to Tao ProjectFileEdit_NetCore test

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/project-system#1755]
From: mavasani
Before doing a build, can you add a scenario where you change source code to reference something from newly added PackageReference and verify error list has no diagnostics? This will verify LanguageService has picked up the new package reference.

Tao test xml = Closed/Hosting/RoslynTaoActions/IntegrationTests/ProjectFileEdit_NetCore.xml

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving to 15.4 to get it off the radar.

**Comment by davkean** [comment]
The integration tests are at a state where this bug is not useful. When we re-enabled them we'll reopen/file new bugs.
