### ISSUE TITLE
Folder names are reversed in the language service

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1760]
Moved type to new file mixed up the folder names: https://github.com/dotnet/roslyn/issues/17898#issuecomment-286904186.

I suspect we're passing the wrong folder names in the language service.

**Comment by Pilchie** [comment]
Also reported in https://developercommunity.visualstudio.com/content/problem/27347/move-type-to-own-file-from-lightbulb-will-produce.html

**Comment by Pilchie** [comment]
And https://developercommunity.visualstudio.com/content/problem/44056/incorrect-directory-for-extracted-interface-files.html

**Comment by Pilchie** [comment]
And https://developercommunity.visualstudio.com/content/problem/24157/vs-2017-rc-move-type-to-file-problem.html

**Comment by jasonmalinowski** [comment]
And https://developercommunity.visualstudio.com/content/problem/45276/create-new-class-in-file-lightbulb-creates-folder.html

**Comment by jnegron357** [comment]
This is tagged as Closed but doesn't say whether it was fixed or not, can someone elaborate?

**Comment by Pilchie** [comment]
It looks like it was fixed #1841 - Stop publishing tree just to get folder names for the language service, right @davkean?
