### ISSUE TITLE
Expose new TargetFrameworkMonikers project property

### ISSUE THREAD

**Issue by adrianvmsft** [dotnet/project-system#1764]
This property will provide the list of target framework monikers that the project supports.

E.g. perhaps a ‘;’ or '|' separated list: 
`.NETStandard,Version=v1.0;.NETCoreApp,Version=2.0;…`

Telemetry could use this property to collect information about frameworks used (internal bug 383404)

**Comment by davkean** [comment]
Tentatively putting this in 15.3 @adrianvmsft, still waiting from above if we want to take this earlier.

**Comment by srivatsn** [comment]
Pulling this into 15.2 - we really need this data.
