### ISSUE TITLE
Run localizer tool

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1794]
To save each developer running the localizer tooling everytime a string is changed, this is tracking the work to run it before the localization cut-off.

**Comment by srivatsn** [comment]
We're caught up on loc now. @dotnet/project-system, at this point, for all changes affecting loc, we should run the tool as part of the PRs themselves.

**Comment by nguerrera** [comment]
@srivatsn @davkean @dotnet/project-system That won't be necessary for long. I've finished developing build automation for this at https://github.com/dotnet/xliff-tasks and I'm rolling it out to all of the xlf-using repos starting with https://github.com/dotnet/sdk/pull/1291 I should get to project-system next week.  🎉
