### ISSUE TITLE
Console App (.NET Framework) isn't localized

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1812]
RTM:

![image](https://cloud.githubusercontent.com/assets/1103906/24134220/e9f12192-0e56-11e7-8e5a-9fd1aac53e40.png)

This might be because we missed the localization cut off?

**Comment by srivatsn** [comment]
Apparently this was just a missed localization. Supposed to be fixed now. Assigned VSO bug https://devdiv.visualstudio.com/DevDiv/_workitems?id=389309&triage=false&_a=edit to Jon for verification.
