### ISSUE TITLE
Changing a project's Platform target edits the csproj incorrectly

### ISSUE THREAD

**Issue by davidmatson** [dotnet/project-system#1820]
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
</Project>
```

Then, in project properties for all configurations, change Build -> Platform target to x86.

Expected:
RuntimeIdentifier changes to win-x86

Actual:
RuntimeIdentifier is unchanged, and conflicting platform target properties are added. Updated csproj is:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
</Project>
```

Having the full plethora of x64, AnyCPU and x86 added here is delightful :)

**Comment by davidmatson** [comment]
Per @RaulPerez1, may be partially related to #1300

**Comment by davkean** [comment]
@dsplaisted @nguerrera We don't drive PlatformTarget off RuntimeIdentifier do we? We really need to merge these concepts.

**Comment by nguerrera** [comment]
We do as a default, but if you set it we leave it alone.

**Comment by srivatsn** [comment]
When you say RuntimeIdentifier changes to x86 what is the actual effect you're seeing? 

The second part of the issue - all property per configuration instead of adding it unconditionally is tracked by https://github.com/dotnet/project-system/issues/1388

**Comment by davidmatson** [comment]
> When you say RuntimeIdentifier changes to x86 what is the actual effect you're seeing?

When I change the project's properties to target x86 (via Build -> Platform target) I would have expected it to change the RuntimeIdentifier from win-x64 to win-x86 rather than adding a conflicting PlatformTarget=x86 setting.

To be complete, if I have this project:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
</Project>
```

And change Build -> Platform target (in project properties) to x86, I would expect the updated csproj to look like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
</Project>
```

**Comment by jeremymeng** [comment]
ASP.NET .Core apps are broken (BadImageFormartException when loeading libuv) due to not updating RuntimeIdentifier when PlatformTarget is changed.  Users have to manually edit .csproj to fix it.

**Comment by davkean** [comment]
Going to dupe this against: https://github.com/dotnet/sdk/issues/1553 which is tracking the handling of these.
