### ISSUE TITLE
Have integration test machines build and deploy the project system

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#1825]
In order to test new Project System features and their integration with roslyn, we need the integration test machines to also build and deploy the project system.

**Comment by davkean** [comment]
What is this change representing? Changing our groovy script to just turn on deployment?

**Comment by davkean** [comment]
@jmarolf What does this bug represent?

**Comment by jmarolf** [comment]
@davkean have the Roslyn integration test machines deploy the project system so they can run our integration tests.

**Comment by jmarolf** [comment]
resolved with https://github.com/dotnet/project-system/pull/2169
