### ISSUE TITLE
CTRL+F5 opens a command-window when you've set Debug to launch executable

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1831]
Unlike legacy project system, CTRL+F5 opens a command-window when you set to launch an executable, such as DevEnv.exe.

**Comment by ulrichb** [comment]
Responsible code: [ConsoleDebugTargetsProvider](https://github.com/dotnet/project-system/blob/7a4ab8a6701d5ce2e8c40f33babaf112e549e0c7/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs#L111).

**Comment by ulrichb** [comment]
Would you accept a PR to get this fixed earlier than VS 16?

**Comment by srivatsn** [comment]
Yes we'll gladly accept a PR for this.
