### ISSUE TITLE
Create templates for 2.0 console apps and class libraries

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#1836]

**Comment by sbaid** [comment]
@srivatsn will there be copies of template for netcore 1.0/1.1/2.0 or there is plan for NPD level change to enable it for all templates? 
@codito

**Comment by srivatsn** [comment]
There are no NPD changes planned at this point.

**Comment by davkean** [comment]
@srivatsn We shouldn't copy the templates - is that what this is representing?

**Comment by srivatsn** [comment]
Not copies no - I don't think we'll have templates for 1.0\1.1 - Just a 2.0 template for library and console app. So really it's just changing the existing template to target 2.0

**Comment by davkean** [comment]
It will be hard to retarget down right? In which case you'll want a way to create 1.x templates.

**Comment by srivatsn** [comment]
For console and class libraries retargeting is straightforward - just change the TFM. For web apps, I believe the one asp.net dialog might offer a TFM chooser - not sure. @mlorbetske

**Comment by srivatsn** [comment]
Fixed with https://github.com/dotnet/sdk/pull/1067
