### ISSUE TITLE
Create Perf tests

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#1840]

**Comment by MattGertz** [comment]
Mondo escrow triage:  test-only, moving to 15.4 to get it off the radar.

**Comment by Pilchie** [comment]
We have the beginnings of closed source versions of these.  Work to get them running in the open will continue into 15.8 though.

**Comment by davkean** [comment]
Dup'ing against https://github.com/dotnet/project-system/issues/2702.
