### ISSUE TITLE
Code Generation for resx files fail when a project reference exists in .NET Standard project

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#1845]
Reported via [VSFeedback](https://developercommunity.visualstudio.com/content/problem/34592/code-generation-for-resx-files-fail-when-a-project.html):

Steps to reproduce: Create a new .NET Standard project (default settings) "ClassLibrary1" Create a second project "ClassLibrary2" exactly like the first one.
Add a project reference from ClassLIbrary1 to ClassLibrary2.
Try to add a resource file (.resx) to the ClassLibrary1. The .designer.cs file will not be created and sometimes an "Object Reference not set to an instance error" appears instead of the designer.
I attached a minmal working sample where all steps above are executed except for adding the resx file. 

[ResxFail.zip](https://github.com/dotnet/roslyn-project-system/files/868486/ResxFail.zip)

**Comment by aKzenT** [comment]
Just wanted you to know that it was me, who initially reported the bug on VSFeedback. I could reproduce this on several different machines using the latest update. If you need any further information to reproduce this, please let me know.

**Comment by jmarolf** [comment]
Looking into this, it appears to be the same issue as https://github.com/dotnet/project-system/issues/1521
