### ISSUE TITLE
Need API to be informed when project system has started/finished adding references

### ISSUE THREAD

**Issue by debonte** [dotnet/project-system#1846]
Explanation from Lutz Roeder in email:

> We had this discussion a few times and the gist seems that a NuGet API to detect restore won’t be enough for high-level services like designer as the project system is doing follow up work reacting to a NuGet restore. The flow is NuGet notification --> project system notifications --> clients subsystems in VS.
> 
> For a regular NuGet add/remove scenario turning a NuGet restore into assembly add/remove events might be enough?
> 
> The main scenario we are struggling with is that the .NETCore restore that happens initially on project create/open results in ~100 assembly change notifications that can happen anytime even after the project is considered “complete”. If NuGet restore and project system update hasn’t happened the designer should block on open and needs a notification when NuGet restore and project system update are complete.

@davkean responded:

> It sounds like we just need some sort of batch API; 
> 
> -	We’re about to start adding references,
> -	add references
> -	We’re done adding references
> 
> It’s really not that complicated – we (project system) know when the start of this occurs and when its done.

Probably need more discussion to flesh this out.

**Comment by davkean** [comment]
Just want to call this out, this has nothing do with NuGet restore. It's just the representation of when we about change references - NuGet causes a bunch of these, but you could hit the same thing by adding a bunch of references via ReferenceManager or by switching branches the project changing significantly underneath you (say by changing TFMs)

**Comment by debonte** [comment]
Sure, I can see that NuGet and non-NuGet reference-add scenarios may be equivalent from the project system's perspective.  Lutz would probably be able to explain this better, but the XAML designer specifically needs to know when the project system has finished responding to NuGet restore, because we need to ensure that the framework packages for the project's target platform are known/available.

**Comment by lutzroeder** [comment]
General idea is:
1) Designer should respond to project system once it updated, not to the underlying NuGet events. For updates once it is running it can react to ReferenceAdd/Removed or better groups of these.
2) Opening with no or incomplete .NET Core present, crashing or trying to guess in what state we are in, waiting for "110 .NET Core assemblies added" and the starting again is not the right experience. Waiting for the initial restore to complete seems to be more desirable. Ideally should be implemented in a way that designer can show a "waiting for initial restore to finish" progress bar.

**Comment by davkean** [comment]
@lutzroeder My point is that this can occur regardless of NuGet - change a TFM while the project is loaded in the new project system, and you'll get a bunch of removed and then added events.

With regards to the first load experience, we should track that separately - we have a similar problem with the language service, where we don't have System.Object until we've kicked off the first design-time build so you get a hundreds of errors on first load.

**Comment by davkean** [comment]
We're tracking first load experience here: https://github.com/dotnet/roslyn-project-system/issues/928.

I'll make sure whatever we do there - we can do the same for you.

**Comment by jjmew** [comment]
This doesn't meet the bar for legacy and the for the new project system you would use the Operation Progress API
