### ISSUE TITLE
Removing a package right after build does not seem to update the Language Service

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#1847]
VS Build: d15rel 26323.00.

1. Create a new "Console Application (.NET Core)" project.
2. Add the latest Newtonsoft.Json package to the project.
3. Add `using Newtonsoft.Json;` to the top of Program.cs.
4. In the body of `Main` type `JsonConvert` just to verify that the Language Service has been updated with all the references from that package.
5. Comment out `JsonConvert`.
6. Build the project--it should succeed.
7. In Solution Explorer, expand Dependencies/NuGet under the project node.
8. Right-click on the Newtonsoft.Json node and click "Remove" to remove it from the project.

At this point, note that no error squiggles appear under `using Newtonsoft.Json;` (they should) and completion lists continue to offer up types and members from the Newtonsoft.Json library, even though it should be gone.

9. Build again. You'll get an error: `error CS0246: The type or namespace name 'Newtonsoft' could not be found`.
10. Complete lists still offer up types from Newtonsoft.Json, and there still aren't any Intellisense errors associated with `using Newtonsoft.Json;`.

**Comment by srivatsn** [comment]
Cannot repro this with the language service fixes,.
