### ISSUE TITLE
Opening a project when there's an open .cd file fails to load the class designer

### ISSUE THREAD

**Issue by RaulPerez1** [dotnet/project-system#1848]
1) Open or create a new project
2) Add a class designer file to the project
3) Close the solution. Make sure the file in the second step is open so that it automatically opens next time the solution is loaded
4) Reopen the solution

Expected: File loads with no errors
Actual: There's an error coming from the designer

Debugging through the class designer code the issue is that it's requesting the code model instance from the DTE project and at that point in time it returns null. This doesn't happens if opening the file after the project is loaded (or even putting a breakpoint right before the code model call and waiting a little) so this is a race condition on code model being ready after the project is opened. 

This doesn't repros on the legacy project system or C++ projects

**Comment by davkean** [comment]
This is blocked on https://github.com/dotnet/project-system/issues/1848.

**Comment by davkean** [comment]
Sorry blocked on https://github.com/dotnet/project-system/issues/2544 which I'm going to dupe it against.
