### ISSUE TITLE
Publish nuget packages for the project system

### ISSUE THREAD

**Issue by MBulli** [dotnet/project-system#1852]
I'm the author of a visual studio extension which provides a better UI for command line editing.
While implementing support for .Net Core projects I noticed that `Microsoft.VisualStudio.ProjectSystem.Managed.ILaunchSettingsProvider` seems like the right place to start.

I couldn't find a reliable source for `Microsoft.VisualStudio.ProjectSystem.Managed.dll` to reference. On my local disk I found the dll inside `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\ujthnp1g.mnl` but the last path component is different on every computer.

What is the recommended way to reference that assembly? Or should I generally avoid referring to that assembly?

**Comment by srivatsn** [comment]
We are about to publish a NuGet package for this dll which you can use. @basoundr please update this thread once you have the package.

@MBulli - curious - what is your scenario? Is your extension providing some support for editing the launchsettings.json file?

**Comment by basoundr** [comment]
Nugets are loaded.

[Microsoft.VisualStudio.ProjectSystem.Managed.VS](https://www.nuget.org/packages/Microsoft.VisualStudio.ProjectSystem.Managed.VS/2.0.6142705)
[Microsoft.VisualStudio.ProjectSystem.Managed](https://www.nuget.org/packages/Microsoft.VisualStudio.ProjectSystem.Managed/2.0.6142705)
[Microsoft.VisualStudio.Editors](https://www.nuget.org/packages/Microsoft.VisualStudio.Editors/2.0.6142705)
[Microsoft.VisualStudio.AppDesigner](https://www.nuget.org/packages/Microsoft.VisualStudio.AppDesigner/2.0.6142705)
