### ISSUE TITLE
F# language service integration

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#1853]
This is the known work:

- [x] The command line parser is stubbed out and needs to be implemented
- [x] There's a hack for creating the WorkspaceContext. Roslyn needs to be changed to be able to create a context for F# as well.
- [X] To get the command line args, the F# SDK\Targets need to be updated to return the commandline args. [@brettfo: complete via dotnet/netcorecli-fsc#88 and Microsoft/visualfsharp#2711]

**Comment by srivatsn** [comment]
@brettfo we should fix the remaining checkbox here which is to fix https://github.com/dotnet/roslyn/blob/38afa69825db300e58aa6416dbb2c14ab340da7f/src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProjectFactory.cs#L76 

We are currently passing null for the ProjectExternalErrorReporter which likely means the error list is broken - 
https://github.com/dotnet/project-system/blob/360a009390105ad50695ae595ddb62dbd56b87b3/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/UnconfiguredProjectContextProvider.cs#L278

Easiest thing to do might be to just add a FS to [this map](https://github.com/dotnet/roslyn/blob/38afa69825db300e58aa6416dbb2c14ab340da7f/src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProjectFactory.cs#L30) and then we can call the original overload of CreateProject instead of the hacky one.

**Comment by srivatsn** [comment]
This is done.

**Comment by dsyme** [comment]
@srivatsn I should review this I think - also to familiarise with the new code - could you add links to the PRs?  Thanks

**Comment by srivatsn** [comment]
#1876, #2206 and #2244.
