### ISSUE TITLE
F# item templates don't show up

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#1855]
After creating a project, add item doesn't show any templates even though the guid provider exists. I can't even find the templates under common7\ide - so likely the regular logic doesn't work and needs to be tweaked.

In the Resources property page, if I click on the link to create the resx file, it fails saying it cannot find the resx template for F#. This is likely related as well.

**Comment by srivatsn** [comment]
The item templates show up now.

**Comment by dsyme** [comment]
Great!
