### ISSUE TITLE
Warning during MicroBuild, when indexing symbols on SymWeb

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1881]
It appears we're using an old way to index symbols on symweb. See build log for warning that describes more information.

**Comment by tannergooding** [comment]
Roslyn has the same issue. This should be a relatively simple fix. FYI. @jasonmalinowski

**Comment by Pilchie** [comment]
@tannergooding @jasonmalinowski - do you know if this got fixed yet?

**Comment by Pilchie** [comment]
I see no warnings in a recent signed build of master.

**Comment by jasonmalinowski** [comment]
I think it was fixed.
