### ISSUE TITLE
DeployTestDependencies in project system solution  is always unresolved for projects referencing it

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#1899]
DeployTestDependencies  has weird project file which does not have SDK , but imports ProducesNoOutput.Settings.targets . This results in several things:

 - DeployTestDependencies   does not receive any evaluation or designtime builds for its References,ProjectReference etc . That is expected since i don't see any Managed.DesignTime.targets imprted there (they usually brought by SDK). This is potentially a problem for the future , when we would need support projects that don't rely on core sdk.
- Other projects referencing DeployTestDependencies  receive only evaluation (which means project is unresolved for them), but no DesignTime events with resolved project path. This is i am not sure why .. even though DeployTestDependencies   does not have sdk etc , why resolution logic for other projects cannot find it? This seems like a bug we need to fix now...?

**Comment by srivatsn** [comment]
> That is expected since i don't see any Managed.DesignTime.targets imprted there (they usually brought by SDK). 

No the DesignTime.targets are brought in by CSharp.targets and not the SDK. Also ProduceNoOutput.Settings.targets internally imports the SDK. I just ran msbuild /pp on that project and it does include the sdk

**Comment by abpiskunov** [comment]
Why me? :) It is  not dependencies node - i don't receive any events as i described above, could be sdk or something else , since this project has special settings ...

**Comment by abpiskunov** [comment]
Actually, let me double check something, i will post more updates after i am done with more invcestogations

**Comment by abpiskunov** [comment]
found what was the problem and fixed it in current PR, will close this issue once PR checked in

**Comment by abpiskunov** [comment]
fixed with https://github.com/dotnet/project-system/pull/1880
