### ISSUE TITLE
Project system passing bad paths to IWorkspaceProjectContext.AddAnalyzerReference

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#1905]
The `IWorkspaceProjectContext.AddAnalyzerReference(string referencePath)` method expects `referencePath` to be the full path to an analyzer. If a relative path is provided it will throw an exception.

In the case where a project contains an item like

``` XML
<Analyzer Include="Foo.dll" />
```

and Foo.dll is not found immediately next to the project, we'll simply pass `"Foo.dll"` to `AddAnalyzerReference`. This will throw an exception, and we won't pass any more analyzers to the `IWorkspaceProjectContext`. This has two negative effects:

1. We won't tell the language service about all the analyzers, which means it obviously won't run them.
2. If we've passed along some of the analyzers but not all of their dependencies then the language service will try to load them and fail, resulting in hard-to-diagnose warnings in the Error List about type load exceptions and assemblies not being foind.

**Comment by davkean** [comment]
This is very similar to: https://github.com/dotnet/project-system/issues/1872.

**Comment by davkean** [comment]
I'll take this.

**Comment by davkean** [comment]
This was resolved in: https://github.com/dotnet/project-system/pull/2178
