### ISSUE TITLE
Project system should watch all Nuget.Config files under the solution root for changes

### ISSUE THREAD

**Issue by cdmihai** [dotnet/project-system#1910]
I had placed a Nuget.config at the solution level and expected VS to do another restore, but it didn't. Since Nuget.config files affect the restore graph, VS should probably detect changes to these files too.

And then there's all the other Nuget.config files from solution root to file system root + other Nuget.configs that Nuget looks at and I don't know about.

**Comment by davkean** [comment]
This should probably be NuGet, not the project system @emgarten

**Comment by davkean** [comment]
Going to move this to NuGet - this shouldn't be up to individual projects to do this. NuGet should watch for all projects.

**Comment by davkean** [comment]
This issue was moved to NuGet/Home#4956
