### ISSUE TITLE
Create a new rule set file when CodeAnalysisRuleSet isn't defined at all

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#1919]
Related to #88.

When targeting the full framework, the `CodeAnalysisRuleSet` property is always defined. If it isn't set in the project, then the standard project imports set it to point to a file with some default set of FxCop rules turned on. When changing the severity of a rule through the diagnostic's node in Solution Explorer we simply bail out if the property isn't defined at all.

This doesn't work well with .NET Core projects, where there seems to be no default in the standard imports (and there's no good reason there should be). In this case, we should simply create a new, empty rule set file and update the project to use that.

We already do something similar if CodeAnalysisRuleSet points to a default file. Since we shouldn't modify those (they're part of the VS install) we instead copy the file, update the project to use the copy, and then modify it.

**Comment by davkean** [comment]
How does the Full Framework project do this? We import the same set of targets.

**Comment by tmeschter** [comment]
@davkean The logic for the default value for `CodeAnalysisRuleSet` can be found in MSBuild\Microsoft\VisualStudio\v15.0\CodeAnalysis\Microsoft.CodeAnalysis.Targets in your VS install. The rules for picking a default are somewhat complex, so .NET Core projects may just be falling through the cracks.

Regardless, if `CodeAnalysisRuleSet` isn't defined when trying to change the severity of a diagnostic then it's perfectly reasonable to create an empty rule set file and use that. The default rule set files add very little value, if any.
