### ISSUE TITLE
Make VB Namespace Import List wait on Workspace_Changed event before refreshing the list

### ISSUE THREAD

**Issue by basoundr** [dotnet/project-system#1922]
[More info](https://github.com/dotnet/project-system/pull/1911) and [here](https://github.com/dotnet/project-system/pull/1911#issuecomment-291185595)

**Comment by davkean** [comment]
I don't think this is the right approach, this has nothing to do with Roslyn - we should be reading and respecting the project file.

**Comment by basoundr** [comment]
@davkean As long as we depend on the Roslyn workspace to populate the list, Roslyn will remain the source of truth for the Property pages. Whatever change we do to the Project file will eventually reach Roslyn. I have explained that [behavior here](https://github.com/dotnet/project-system/pull/1911/files#r112121502)

**Comment by Pilchie** [comment]
Fixed by #3095
