### ISSUE TITLE
The rule set file is not passed to the language service

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#1923]
That is, we never call `IWorkspaceProjectContext.SetRuleSetFile(string filePath)`. This means the language service will report diagnostics with their default severity, rather than the severity specified in the rule set file. Also, when setting the diagnostic severity through the context menu in Solution Explorer (see #88) we depend on getting the location of the rule set file from the Roslyn `Project`. If the project system hasn't passed that along, we don't know what file to update.

**Comment by mavasani** [comment]
This is supposed to work as we set ruleset via options. We also have unit tests for it.

**Comment by mavasani** [comment]
I meant "command line options"

**Comment by tmeschter** [comment]
@mavasani It sort-of works.

We pass it with the command line options, and the options-parsing code reads it content and sets the options appropriately. However, the `Project` is never told the file path to the .ruleset file. If the file contents then change on disk (such as when you edit it via the Solution Explorer or the rule set editor) the language service never picks up on this change. So we still need to call `SetRuleSetFile`.
