### ISSUE TITLE
extern alias support for NuGet package references

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/project-system#1930]
Currently, when a NuGet package reference is added, there is no way to set the alias from the project system for the new style csproj projects.

This feature is needed, because NuGet package references don't result in direct assembly references any more and only those can have an alias.

My proposal is to add the alias(es) to all assemblies referenced for the NuGet package, but not the indirectly referenced NuGet packages.

**Comment by davkean** [comment]
Great suggestion. I'll move this over to the NuGet repo, they own the syntax for PackageReference.

**Comment by davkean** [comment]
This issue was moved to NuGet/Home#4989
