### ISSUE TITLE
System.Resources.MissingManifestResourceException when Resource not placed in the default namespace

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/project-system#1933]
ResourceManager throws MissingManifestResourceException when trying to get the ResourceSet for a resource placed outside the default namespace.

### Steps to repro in VS17:

1. Create a new .NetCore Console App named MyNetCoreApp
2. Add a resource Resource1 (gets namespace MyNetCoreApp) with one entry "Foo1, Foo1Value"
3. Change the default namespace to NewNetCoreApp
4. Add a resource Resource2 (gets namespace NewNetCoreApp) with one entry "Foo2, Foo2Value"
5. Now add the following in Main:
```
Console.WriteLine("Resource2.Foo2: " + Resource2.Foo2);
Console.WriteLine("Resource1.Foo1: " + Resource1.Foo1);
```
**Expected output:**
```
Resource2.Foo2: Foo2Value
Resource1.Foo1: Foo1Value
```
**Actual output:**
```
Resource2.Foo2: Foo2Value
Unhandled Exception: System.Resources.MissingManifestResourceException: Could not find …
```
 
Note: For a .NetFramework Console App, after changing the default namespace, VS automatically updates Resource1 to be placed in the new default namespace and you'll get the expected behavior.

**Comment by danmosemsft** [comment]
@davkean I see some other bug https://github.com/dotnet/project-system/issues/1521 where the SFG is not running when it should. In this case, it's not running when the project properties are changed.

**Comment by davkean** [comment]
Yep, looks like we're not running them and going to dup it against that https://github.com/dotnet/project-system/issues/1521. I'll add this case.

**Comment by glopesdev** [comment]
@danmosemsft @davkean I'm hitting against this case and it seems there is a really long trail of issue reports leading up to these issues but then it seems like something got lost in translation.

Resx files are generated with the wrong namespace regardless of whether its design time build or not. The only workaround that really works is to force the embedded resource `LogicalName` property in the csproj to point to the correct namespace, which has to be done individually for each file.

**Comment by davkean** [comment]
@glopesdev Please open a new bug with a repro and we'll move it to the appropriate team.
