### ISSUE TITLE
Old and new csproj files don't play nicely together

### ISSUE THREAD

**Issue by alexwiese** [dotnet/project-system#1935]
While migrating from the old csproj to the new format I came across this issue. If you have a new csproj in the same folder as the old csproj then an error occurs when building the old csproj using VS2017.

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(197,5): error : Your project is not referencing the ".NETFramework,Version=v4.5.2" framework. Add a reference to ".NETFramework,Version=v4.5.2" in the "frameworks" section of your project.json, and then re-run NuGet restore.

I've narrowed it down to this target in Microsoft.NuGet.targets that runs if there is a `project.assets.json` file in the `obj` folder.

 ```
 <Target Name="ResolveNuGetPackageAssets"
          DependsOnTargets="$(ResolveNuGetPackageAssetsDependsOn)"
          Condition="'$(ResolveNuGetPackages)' == 'true' and exists('$(ProjectLockFile)')">
```

If I delete the `project.assets.json` file then the old project builds without issue. Building the new csproj creates the assets file, which causes the issue to reappear. Removing this target also allows it to build successfully.

Is there a way to detect if the project being built is using the new csproj format within the targets file to workaround this?

Repro solution is here https://github.com/alexwiese/old-vs-new-repro

**Comment by davkean** [comment]
Thanks, for the investigation. This behavior explains another issue that some contacted me internally about. I added this case to the bug about shared intermediates here: https://github.com/dotnet/project-system/issues/1935. I'm going to dup this against that bug.

**Comment by davidfowl** [comment]
@davkean you duped the bug against itself 😄

**Comment by davkean** [comment]
If I had a dollar for each time I did that, I'd be $37 dollars richer. Updated the bug.
