### ISSUE TITLE
Declaring <DefineConstants> before <TargetFramework> are not honored

### ISSUE THREAD

**Issue by shahabhijeet** [dotnet/project-system#1937]
<PropertyGroup>
<targetframeworks>net452;netstandard1.4</targetframeworks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)|$(Platform)'=='net452|AnyCPU' ">
    <DefineConstants>$(DefineConstants);FullNetFx</DefineConstants>
  </PropertyGroup>

If you reverse the order of <targetframeworks> (if you declare it after DefineConstants), DefineConstants are not honored.

Talked to David Kean and hence opening a bug about, should ordering matter in this case?
Because my mainline scenario is, I want to define <targetframeworks> in a common build.props file, and right now I cannot due to 
https://github.com/dotnet/roslyn-project-system/issues/547
So with the above bug, <DefineConstants> has to be declared after <tagetframework>.

**Comment by davkean** [comment]
@shahabhijeet Can you add the exact repro project file?

**Comment by srivatsn** [comment]
Not sure what your scenario is but #547 is resolved in latest builds.

**Comment by srivatsn** [comment]
Please reactivate if you have a repro and if #547 doesn't help you
