### ISSUE TITLE
Retargetting from netcoreapp1.1 to netcoreapp2.0 produces DT errors in VS

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#1939]
**Repro Steps:**

**Build:** vsuwpt.25404.00

Create basic netcoreapp1.1 ConsoleApp, i.e.:

```xml
		<Project Sdk="Microsoft.NET.Sdk">
		  <PropertyGroup>
		    <OutputType>Exe</OutputType>
		    <TargetFramework>netcoreapp1.1</TargetFramework>
		  </PropertyGroup>
		</Project>
```

Open in Visual Studio and open Error List. 
Edit TargetFramework to netcoreapp2.0

**Expected:** No DT Errors
**Actual:** 
Error MSB4057	The target "GenerateCompiledExpressionsTempFile" does not exist in the project.	ConsoleApp2	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets	26	

Other DT errors possible.
Solution build is successful. 
Same problem applies to netstandard class libs

**Comment by srivatsn** [comment]
@cdmihai @AndyGerlicher I think this is cause by the issue I pinged on yesterday where msbuild is reading the targets file from disk and not from the serialized projectinstance.

**Comment by davkean** [comment]
Yes agreed.

**Comment by cdmihai** [comment]
Tracking issue: https://github.com/Microsoft/msbuild/issues/1726
