### ISSUE TITLE
No F# startable projects are listed in run dropdown 

### ISSUE THREAD

**Issue by colinbull** [dotnet/project-system#1941]
![image](https://cloud.githubusercontent.com/assets/585546/24797192/07d2c344-1b88-11e7-8488-2803f3d1b604.png)

The screen clip above shows the issue. Here I would expect FSI, FSIAnyCpu to be listed, for example. This behavior has been like this for a long time, it certainly exists in VS 2012, 2013, 2015 and 2017. 

It is worth noting if you right-click on the project a `Set as start project` then this does persist and work. But it still doesn't appear in the dropdown.

**Comment by cartermp** [comment]
Note: this is an issue in the current F# project system that would be great to have fixed as we move to support here.

**Comment by davkean** [comment]
@cartermp What do you want to do with this bug? F# will automatically get this support as soon as this project system is turned on for them.

**Comment by srivatsn** [comment]
Ya this already works in the new project system. Closing this issue:

![image](https://cloud.githubusercontent.com/assets/20570/24871203/b7f335e6-1dcd-11e7-85d9-893aa4fb6bd9.png)

**Comment by cartermp** [comment]
Fantastic!
