### ISSUE TITLE
Improve presentation of dependencies tree search results

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#1942]
Currently when search happens in Solution explorer and user wants to find where dependency X or dependency with version Y comes from , we show only linear results, meaning: for each top level dependency, we show a flat list of unique dependencies from any level of hierarchy below it.  That means we would show that top level dependency depends on X or Y, but at what level? What exactly brings it there? 

We used to have search results with full hierarchy but:
- progression is super slow when dealing with deep hierarchies in search - VS hungs very often in this case
- results have multiple pages, so it becomes pretty unusable if something very common was searched.

Proposal: 
- we could request improvements in progression  to fix perf, but it is dangerous - code is very old there
- Or there were talks in CPS that they could redesign their tree logic, which would eliminate need for progression and graph nodes , and could help with search results too
- In any case we need to come up with representation that is usable when there are many results and deep hierarchies, may be create a completely separate tool window or extension for Ctrl+g search dialog.

See if there will be customer need for that when netstandard2.0 comes , maybe add telemetry - how often users search for dependenices or some polls etc ...

**Comment by drewnoakes** [comment]
The display of search results from within transitive dependencies will be reviewed as part of moving away from progression to `IAttachedCollection` APIs (currently underway as part of #3435).
