### ISSUE TITLE
OrderPrecedenceImportCollection should refresh when dynamic capabilities change

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#1944]
In dependencies nodes we have several places where we use OrderPrecedenceImportCollection and subscribe for some events for collection memebers. Then we unsubscribe later when project unloading or disposed etc. @lifengl  mentioned that OrderPrecedenceImportCollection contents can be changed and we need to react to that just in case if we don't want to miss new  events form collections memebrs (and don't leak  in case we forgot to unsubscribe).

There is a way to subscribe to capabilities changes. For more info see https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/dynamicCapabilities.md

**Comment by abpiskunov** [comment]
This is true for other places where we use OrderPrecedenceImportCollection.

**Comment by jjmew** [comment]
This is not something that meets our bar as we don't have a concrete user scenario
