### ISSUE TITLE
Context menu items on Dependencies and sub root nodes (like Nuget, Assemblies etc)

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#1945]
There was a TFS bug 288257, however better place for it here:

Now that both Bower and NuGet are nested under Dependencies, the context menus are not correct.
 
Dependencis:
![image](https://cloud.githubusercontent.com/assets/1592091/24822941/3487bd2e-1bae-11e7-9735-24f7ce8272d9.png)

I'm not sure why Add Reference is here when there are no References listed, but not sure where it belongs.
Add Service Capability seems like it belongs on the next node up, "Service Capabilities"
Manage NuGet Packages belongs on NuGet
Perhaps a Restore All Dependencies is in order.
 
Bower:
![image](https://cloud.githubusercontent.com/assets/1592091/24822944/3a5fad10-1bae-11e7-9fb9-870aa3a9d749.png)

Looks good to me
 
NuGet:

Really bad.  Manage Nuget Packages should definately be here.
A Restore NuGet Packages is in order as well.
 
Add an npm file.  Be careful to change its name form package1.json to package.json (which actually works) and add gulp.
 
NPM:
![image](https://cloud.githubusercontent.com/assets/1592091/24822948/4062a4ce-1bae-11e7-9718-0f5dcb4c6d6f.png)

Looks pretty good to me.

**Comment by tmeschter** [comment]
Note that "Manage NuGet Packages" _also_ appears on the project node.

We've also lost the "Add Analyzer" menu item.

**Comment by tmeschter** [comment]
If we move the commands down the Assemblies, NuGet, Analyzers, etc., nodes then we have a problem with multi-targeting. Since those nodes will now be under a target-specific node, is the implication that we are only adding a reference/analyzer/project reference/etc. when building under that _specific_ target? What does that even mean for NuGet packages?

**Comment by tmeschter** [comment]
Doesn't meet the bar for 15.5. Moving out to 15.6.

**Comment by davkean** [comment]
@tmeschter What context menu/group is Add Analyzer being attached to?

**Comment by drewnoakes** [comment]
There are quite a few points here, some of which have problems (i.e. we can't show 'Manage packages' only on the 'Packages' node, as it's not visible until you have a package reference) and others which apply to web projects and don't belong in this repo.

Details aside, I'm in agreement with the general idea that these context menus should be improved. I'll continue working on them over the next sprint or two and will file issues as needed.
