### ISSUE TITLE
Is it a problem to target .net core 1.1 with my library?

### ISSUE THREAD

**Issue by rykr** [dotnet/project-system#1955]
I see that .netcore1.1 includes more apis than the relevant .netstandard api.  The example I am looking at is DataTable.   From the API browser that class seems to be available in .netcore1.1 but not in .netstandard1.3.   Is it a problem if I target .netcore 1.1 instead of .netstandard1.3?

**Comment by davkean** [comment]
No, you can target .NET Core 1.1 from a library.

**Comment by srivatsn** [comment]
This is the reason VS has both a .NET Core Class library and a .NET Standard Class library. As platforms evolve, some of them will some APIs sooner than others.
