### ISSUE TITLE
A package that fails to resolve doesn't get a warning symbol

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1956]
The following package failed to resolve, but that did not cause it to get a warning symbol in dependencies node:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0-preview1-001915-00)' for '.NETCoreApp,Version=v2.0'.				

```

![image](https://cloud.githubusercontent.com/assets/1103906/24886100/aeaae2cc-1e95-11e7-8cf2-858ac741331c.png)

**Comment by srivatsn** [comment]
This was likely a bug during the initial implementation. I cannot repro this anymore. Reopen if you still see it.
