### ISSUE TITLE
Changing TFM causes the dependency node to think it's targeting multiple TFMs

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1958]
I changed TFM from netcoreapp2.0 -> net45, resulting in:
![image](https://cloud.githubusercontent.com/assets/1103906/24886642/6b7967ea-1e99-11e7-8b5b-c38257d8b3f5.png)

**Comment by srivatsn** [comment]
I believe this is fixed by https://github.com/dotnet/project-system/pull/1954 - @abpiskunov  is that right?

**Comment by abpiskunov** [comment]
yes it is in #1954
