### ISSUE TITLE
Implicit references don't get a different icon

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1959]
These are all implicit references, they are supposed to have a different icon:

![image](https://cloud.githubusercontent.com/assets/1103906/24886688/ae8bbce0-1e99-11e7-9921-a447f96b8be8.png)

**Comment by abpiskunov** [comment]
https://github.com/dotnet/sdk/issues/1107

As we discussed in another issue, reading project xml everytime we want to update dependencies coming from DT build  can be slow. Instead we could ask default sdk targets to send metadata IsImplicitlyDefined=true? If you agree please dupe it to 1107

**Comment by abpiskunov** [comment]
We can try to read xml for now, if i would be too slow we could change that later  ...
