### ISSUE TITLE
VB language service doesn't work when targeting .NET Framework

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1961]
1. Create a new .NET Core app project
2. Change target framework to net45 and Save

Expected: No errors
Actual: Errors about core assembly not being found

**Comment by davkean** [comment]
Investigated, suspect Roslyn doesn't expect /sdkpath property to change, we change it from first SetOptions call to the first design-time build.

**Comment by basoundr** [comment]
Addressed in #2071
