### ISSUE TITLE
Some packages in NuGet dependency tree can be expanded but have no contents

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1962]
This package has a chevron to expand it:
![image](https://cloud.githubusercontent.com/assets/1103906/24891583/21122676-1eba-11e7-988a-92c0b0076fd1.png)

Attempted to expand it, causes the chevron to disappear:

![image](https://cloud.githubusercontent.com/assets/1103906/24891603/445a1ab2-1eba-11e7-8e00-dbec03a8de0d.png)

**Comment by abpiskunov** [comment]
This one i am fixing now, its another issue i mentioned earlier today.

Thanks,
Anton

On Apr 10, 2017, at 8:25 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


This package has a chevron to expand it:
[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F1103906%2F24891583%2F21122676-1eba-11e7-988a-92c0b0076fd1.png&data=02%7C01%7Canton.piskunov%40microsoft.com%7C0c771f96f4ca4781e8ff08d4808a5aaf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636274779087970158&sdata=9vlBmVMe2g7Yi7DVezEOCdsDBOfRa4qGFqUY80Si%2F9w%3D&reserved=0>

Attempted to expand it, causes the chevron to disappear:

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F1103906%2F24891603%2F445a1ab2-1eba-11e7-8e00-dbec03a8de0d.png&data=02%7C01%7Canton.piskunov%40microsoft.com%7C0c771f96f4ca4781e8ff08d4808a5aaf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636274779087980166&sdata=bZsLvSnltpC96yilHsEdMz0qOaLCMmci7rccOJ1fiLo%3D&reserved=0>

**Comment by abpiskunov** [comment]
Fixed with https://github.com/dotnet/project-system/pull/1991
