### ISSUE TITLE
Attempting to View in Object Browser in certain references displays an error

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#1963]
1. Open ProjectSystem.sln
2. Right-click on the following node, and choose View In Object Browser

![image](https://cloud.githubusercontent.com/assets/1103906/24891689/c75769f6-1eba-11e7-888e-3a4cd0e6dfbf.png)

```
---------------------------
Microsoft Visual Studio
---------------------------
Value cannot be null.

Parameter name: unresolvedReference
---------------------------
OK   
---------------------------

```

**Comment by abpiskunov** [comment]
Dupe of existing issue.

Thanks,
Anton

On Apr 10, 2017, at 8:28 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  Open ProjectSystem.sln
  2.  Right-click on the following node, and choose View In Object Browser

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F1103906%2F24891689%2Fc75769f6-1eba-11e7-888e-3a4cd0e6dfbf.png&data=02%7C01%7Canton.piskunov%40microsoft.com%7C6e8a10502eca45a9048f08d4808ae2d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636274781372623476&sdata=sVpVcGROvG656G4vhb0GO7OMuAkchVsqY5Db%2FV7qzRg%3D&reserved=0>

---------------------------
Microsoft Visual Studio
---------------------------
Value cannot be null.

Parameter name: unresolvedReference
---------------------------
OK
---------------------------

**Comment by davkean** [comment]
Can you please dup it?

**Comment by abpiskunov** [comment]
this is dupe of https://github.com/dotnet/project-system/issues/403 (root cause is the same - we need our own command handler and can't rely on default on from CPS, since it is tied to their References node)

**Comment by davkean** [comment]
Going to reopen this issue - this is a really bad experience. Before, you couldn't View In Browse, noiw
