### ISSUE TITLE
nuget does not filter netstandard projects

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#1967]
1. Create new netstandard1.4 class library
2. Use nuget to install `Microsoft.Diagnostics.Tracing.TraceEvent` version 1.0.41

**Expected:** 
either nuget tells me that this package is incompatible or it install and works without error

**Actual:**
nuget package successfully installs, but none of the types it contains can be referenced

**Comment by davkean** [comment]
This issue was moved to NuGet/Home#5015
