### ISSUE TITLE
Included Compile items outside of project root directory not visible in SolutionExplorer

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/project-system#1970]
_From @Rurouni on April 11, 2017 14:41_

Hi,
I am trying to include folder one level above project root into dotnet core msbuild based project using new glob patterns:
```
<ItemGroup>
    <Compile Include="..\Shared\**\*.cs" />
</ItemGroup>
```
and whilst it work on the build level I can't find any way to make VS2017 to show those files as part of the project in SolutionExplorer. I have tried setting Visible(no difference) and Link(either links just one file or fails project loading) to no avail.  I need it as part of sharing code between .net core and .net 2.0 project.
Is it even possible or Shared projects are the only alternative?

Thank you

_Copied from original issue: Microsoft/msbuild#1965_

**Comment by rainersigwald** [comment]
Not sure if this is a problem here or in the CPS layer, but I think this is a better home for it since as you mentioned MSBuild itself is happy with the inclusions.

**Comment by davkean** [comment]
Thanks @Rurouni. We turned this off late in VS 2017 cycle as we weren't happy with the design and there was lots of bugs. We've made changes in our 15.3 milestone which fully enables this scenario,.
