### ISSUE TITLE
Memory leaks after unloading/reloading project

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#1972]
1. Open roslyn-project-system solution , wait for restore to complete
2. Press Ctrl+Shift+Alt+F12 several times to force GC
3. Take memory snapshot with perfview and keep it open
4. Unload and reload Microsoft.VisualStudio.ProjectSystem.Managed.VS 4-5 times in a row (sometimes unload it immediately after reload, some times wait for restore)
5. After last reload wait for restore and a little longer when CPU cools down.
6. Force GC again
7. Take new memory snapshot, open it and take a diff 

It would show some leaks. Sample offenders:

![image](https://cloud.githubusercontent.com/assets/1592091/24929358/83416758-1eba-11e7-951e-db47204cf6a7.png)

![image](https://cloud.githubusercontent.com/assets/1592091/24929370/8b93854e-1eba-11e7-8b55-7fc782c61734.png)

**Comment by srivatsn** [comment]
@abpiskunov you mentioned that you were looking into some memory leaks. Are you looking into this?

**Comment by abpiskunov** [comment]
I am looking now at ones related to dependencies, if see any helpful data about other stuff will comment.

Thanks,
Anton

On Apr 13, 2017, at 12:05 AM, Srivatsn Narayanan <notifications@github.com<mailto:notifications@github.com>> wrote:


@abpiskunov<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabpiskunov&data=02%7C01%7Canton.piskunov%40microsoft.com%7C671cda7b596c470c829908d4823b81d0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636276639467638903&sdata=s0bLT4Kv%2FPZo2P1hkkEHHE24ssgjruprcGM3DNZ%2BbDk%3D&reserved=0> you mentioned that you were looking into some memory leaks. Are you looking into this?

**Comment by abpiskunov** [comment]
Similar memory leaks when closing whole solution. I think it is the same issue, thats why i did not open separate bug. Here is the full object references hierarchy that holds UnconfiguredProject and essentially whole CPS in memory after project closed:

![image](https://cloud.githubusercontent.com/assets/1592091/25023810/286bd9de-2050-11e7-92c5-221c2542dc58.png)

**Comment by srivatsn** [comment]
@abpiskunov fixed leaks around the dependencies node but he had mentioned that maybe there were other leaks. Let's take a look.

**Comment by tmeschter** [comment]
Closing as I haven't turned up any obvious leaks.
