### ISSUE TITLE
File->New->ClassLibrary(.NET Standard) shows yellow warning icon in Dependencies/SDK node in Solution Explorer

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/project-system#1987]
Repro Steps:
Build: vsuwpt.26413.0
Install .NET Core x-plat workload
File->New->ClassLibrary(.NET Standard)
NuGet restore kicks-in and succeeds
But you see a yellow warning icon in Dependencies/SDK node in Solution Explorer (see image)
Closing and opening solution resolves the warning icon in Dependencies/SDK node in Solution Explorer  and goes away

![capture](https://cloud.githubusercontent.com/assets/12700391/25008664/3c63061a-2019-11e7-9851-774592a003c0.PNG)

**Comment by srivatsn** [comment]
Closing in favour of #1986 since there's more discussion there.
