### ISSUE TITLE
File->New->ClassLibrary(.NET Standard) and other .NET Core project templates result in errors if package source for myget is not added manually

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/project-system#1990]
Repro steps
Build: vsuwpt.26412.0
Install .NET Core x-plat workload
Tools/Option/NuGet - ensure there is no myGet source listed. If present remove it
Tools/Option/NuGet->ClearNuGet cache to ensure cache is clear
File->New->ClassLibrary(.NET Standard)
Expected result: Restore kicks in and no errors in Error List
Actual: See errors in Error List (image below)

Once we add back the manual step of Tools/Options, add NuGet package source of https://dotnet.myget.org/F/dotnet-core/api/v3/index.json errors go away

![capture](https://cloud.githubusercontent.com/assets/12700391/25024885/af80e550-2054-11e7-9a00-e3d7a0bc68e2.jpg)

**Comment by srivatsn** [comment]
We need to update the local feed to include the netstandard.library 2.0 version. @tannergooding can you chat with @jinujoseph on the local feed installer?

**Comment by srivatsn** [comment]
We've decided to not do this. Instead the packages will be brought by the CLI and dropped into a fallback folder on VS install.
