### ISSUE TITLE
NavigateTo shows no results for types in current solution for a certain period after open solution

### ISSUE THREAD

**Issue by mavasani** [dotnet/project-system#1992]
![image](https://cloud.githubusercontent.com/assets/10605811/25028526/f8046bd4-2069-11e7-97ac-b7e74a453b68.png)

I am hitting this quite often when working on Analyzers.sln from roslyn-analyzers repo. It doesn't show any results for few seconds to couple of minutes after opening the solution, even though the solution load has completed and I get coloring and intellisense for the type. Not sure if it is bug in the project system or Roslyn.

**Comment by mavasani** [comment]
Actually, things like find all references also doesn't work and this is reproing pretty consistently:

1. git clone github.com/dotnet/roslyn-analyzers
2. Run cibuild.cmd
3. Open src\Analyzers.sln
4. Wait for solution load to complete and open source file `\src\Microsoft.NetCore.Analyzers\Core\Microsoft.Composition.Analyzers\DoNotMixAttributesFromDifferentVersionsOfMEF.cs` - verify no squiggles
5. `Ctrl + ,` and enter DoNotMixAttributesFromDifferentVersionsOfMEFAnalyzer

Got: No results

Try Find All references and get no references found, even though it is used in unit test projects.

**Comment by davkean** [comment]
I'm not sure we could influence anything here if the project we've added the file to Roslyn.

@CyrusNajmabadi Do you understand how this search works and where we would approach this?

**Comment by CyrusNajmabadi** [comment]
Is this normal solution loading? Or are you using anything like "deferred project load"?

**Comment by CyrusNajmabadi** [comment]
When i try those instructions, i get:

```
C:\GitHub\roslyn-analyzers [master ≡]> .\cibuild.cmd
Microsoft (R) Build Engine version 4.7.2046.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

C:\GitHub\roslyn-analyzers\RoslynAnalyzers.sln.metaproj : error MSB4057: The target "Restore" does not exist in the project. [C:\GitHub\roslyn-analyzers\RoslynAnalyzers.sln]
ERROR: The process "vbcscompiler.exe" not found.
```

**Comment by Pilchie** [comment]
Not sure how this would happen in the example above.  Go To should use all the projects, and the file shown is not part of misc files, so even if it's an evaluation only project, that type should be included in it.

**Comment by Pilchie** [comment]
@mavasani have you seen this lately?

**Comment by davkean** [comment]
Project has likely "LastDesignTimeBuildSuceeeded" set to false because design-time build hasn't finished.

**Comment by Pilchie** [comment]
Sure, but I don't think that NavigateTo listens to that - only error reporting :-/

**Comment by davkean** [comment]
Going to move this to Roslyn - we don't own this experience, and are simply using a Roslyn API. Roslyn should provide a more progressive experience here.

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn#24026
