### ISSUE TITLE
random CPU spikes in idle VS

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#1993]
I was looking at VS at some moment in Task Manager and noticed that CPU started to grow to 50-60%  randomly without any action in VS (it was opened for a while already).  It was going on for sometime, then I decided to catch a trace and took etl: \\vwdbuild01\Temp\antonpis\dump\RandomCPU.etl  and it showed some code analysis going on, not sure if it is roslyn or Code Lense ..  

See if you want to investigate that…

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn#18703
