### ISSUE TITLE
"Assembly name" in "Application" tab of ASP.NET Core web project properties is empty.

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#1994]
Create an ASP.NET Core web project--> right click the project and click "Properties" --> In "Application" tab, the value of "Assembly name" is empty.
![emptyassemblynameforasp net](https://cloud.githubusercontent.com/assets/22901391/25031215/e0349e5e-20fd-11e7-9514-ff4a5b642a85.PNG)

Test on VSUWPT.26413.02.
OS: Windows 10 X64

**Comment by srivatsn** [comment]
This issue was moved to aspnet/Tooling#1029
