### ISSUE TITLE
Projects in https://github.com/balaTest/ProjectKTestProjects  are migrated failed from IDE

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#1996]
1. Clone this repo [ProjectKTestProjects ](https://github.com/balaTest/ProjectKTestProjects) to machine and extract it;
2. Double click the .sln and see one-way upgrade dialog with "UpgradeLog.htm" generated;

Expected result: migrate succeeded with no errors in migrate report;

Actual result: migrate failed with 2 errors in migrate report:	

- src\SimpleTypeScriptSample1\SimpleTypeScriptSample1.xproj: Could not read post-migration report at 'C:\Users\corbvt\AppData\Local\Temp\miw2mmiz.fta'.
- 	src\SimpleTypeScriptSample1\SimpleTypeScriptSample1.xproj: Failed to migrate XProj project SimpleTypeScriptSample1. 'dotnet migrate --skip-backup -s -x "C:\ProjectKTestProjects-master_IDE\Dev14_KRtw\KRTW-final\SimpleTypeScriptSample1\src\SimpleTypeScriptSample1\SimpleTypeScriptSample1.xproj" "C:\ProjectKTestProjects-master_IDE\Dev14_KRtw\KRTW-final\SimpleTypeScriptSample1\src\SimpleTypeScriptSample1\project.json"
 -r "C:\Users\corbvt\AppData\Local\Temp\miw2mmiz.fta" --format-report-file-json' exited with error code 1.
the similar errors for each .sln migration.
![migratefaildfromide](https://cloud.githubusercontent.com/assets/22901391/25040432/ec29fa0e-213b-11e7-95c0-8cbef33ab8f7.PNG)

Test on build: VSUWPT.26413.02
CLI: 2.0.0-preview1-005738

**Comment by tannergooding** [comment]
Closing as "no repro".

Tested on:
* 15.1 (26403.7) Release
* 15.2 (26419.0-Preview) d15rel
* 15.2 (26420.2-Preview) vsuwpt
* 15.2 (26418.1-Preview) vsuml
