### ISSUE TITLE
Continuous CPU usage of 50-75% on Roslyn Analyzers solution

### ISSUE THREAD

**Issue by mavasani** [dotnet/project-system#1998]
I left VS open overnight with the solution open, and still see the same continuous CPU usage next morning. About 80% of CPU inclusive stacks are from below, but I am not sure if it is a CPS issue or the team owning [Microsoft.VisualStudio.Language.NavigateTo.FileNameProvider.NavigateToItemProvider](http://index/?rightProject=Microsoft.VisualStudio.Language.QuickSearch.FileNameProvider&file=FileNameProvider.cs&line=300).

```
Name        Exc %	 Exc	Inc %
microsoft.visualstudio.language.quicksearch.filenameprovider!Microsoft.VisualStudio.Language.NavigateTo.FileNameProvider.NavigateToItemProvider+<>c__DisplayClass33_0.<CacheFileNames>b__0() 	  0.1	  21	 81.2
Name                                                                                                                                                    	Exc %	 Exc	Inc %
microsoft.visualstudio.shell.ui.internal.ni!Microsoft.VisualStudio.Services.TaskSchedulerService.VsUIBackgroundPriorityScheduler.<OnTaskQueued>b__6_0() 	  0.0	  16	 81.0
clr!COMToCLRWorker                                                                                                                                      	  0.3	 113	 75.5
clr!COMToCLRDispatchHelper                                                                                                                              	  0.2	  79	 75.1
microsoft.visualstudio.projectsystem.vs.ni!HResult.Invoke                                                                                               	  0.2	  71	 71.6
microsoft.visualstudio.shell.interop!dynamicClass.IL_STUB_COMtoCLR(int32,int32,int)                                                                     	  0.7	 217	 64.0
microsoft.visualstudio.projectsystem.vs.implementation!ProjectNode.HrInvoke                                                                             	  0.2	  65	 62.7
```

The ETL trace is shared at: \\mlangfs1\public\mavasani\Continuous_CPU_Usage\PerfViewData.etl.zip

**Comment by mavasani** [comment]
Note that I don't have the NavigateTo bar open, so it seems weird for the caching service to be running at all..

**Comment by davkean** [comment]
Opened https://devdiv.visualstudio.com/DevDiv/_workitems/edit/410206.

**Comment by lifengl** [comment]
This is the old solution filename provider scanning the solution in the background to build up its cache.  It is using old COM APIs in the UI thread, so it is slower for CPS projects.  It will be more efficient to move the code to use the new CPS immutable tree, but no one still actively works in that code base.

We will see whether we can make CPS more efficient there, but the priority to change the old code is low, unless it impacts UI responsiveness directly.
