### ISSUE TITLE
Debugger unexpectedly exits frequently

### ISSUE THREAD

**Issue by zuoanqh** [dotnet/project-system#2007]
I'm debugging a library built on .net standard 1.6 with unit tests. every time when i first open up the visual studio it would work properly, but after i found out the bug, change some code and rebuild everything, and if i debug the test now, it just stops after a while and say "the debugger's worker process(msvsmon.exe) unexpectedly exited. debugging will be aborted.".

**Comment by davkean** [comment]
@zuoanqh Can you please use **Help** -> **Send Feedback** -> **Report a Problem** after it next happens so that more information can be captured and routed to the right team internally?

**Comment by srivatsn** [comment]
Closing since this issue is external to this repo.
