### ISSUE TITLE
VS crashes after adding and removing the breakpoint in same place for many times

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2009]
open a .NET Core project for Visual C#, add a breakpoint;
remove the breakpoint;
add the breakpoint in the same place and VS crashed:
![vscrashesafterreaddingbreakpointinoneplace](https://cloud.githubusercontent.com/assets/22901391/25084177/b9dd3760-238d-11e7-8b60-d840eed7d9a9.PNG)

Test on build VSUWPT.26414.03;
OS: Windows 10 X64;

**Comment by davkean** [comment]
Thanks for the bug report, I can repro this - I've filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/410198.
