### ISSUE TITLE
How does the project system decide if the old (csproj.dll) must be used or the new one

### ISSUE THREAD

**Issue by RobertvanderHulst** [dotnet/project-system#2013]
If I understand it correctly, then the new project system operates side by side with the old (csproj) project system. 'Legacy' projects, such as Windows Forms and WPF are handled by csproj, where .Net Core and .Net standard apps are handled by the new project system.
I have studied the code but cannot find which mechanism is used to determine which project system is used.
I did find references to the Legacy Guid (FAE04EC0-301F-11d3-BF4B-00C04F79EFBC) and the new project system Guid (9A19103F-16F7-4668-BE54-9A1E7A4F7556), but newer project files do not seem to have a guid. Is the absense of the GUID in the newer project files the key , or is it something else ?

I am asking this because for our own language (X#, XSharp, xBase for .Net) we also have a 'legacy' project system based on MPF and we are looking at ways to switch to a CPS based project system to support .Net Core, .Net Standard etc.  

It would be really nice if we could base our new project system on the same code as the C# and VB project system, since that is what our customers are comparing our project system with as well.

Unfortunately it seems that we cannot 'use' the project-system code unchanged, since you guys have hard coded some strings that link the project system to C#, VB and F#, such as attributes as 

[AppliesTo(ProjectCapability.CSharpOrVisualBasicOrFSharp)]
and 
[AppliesTo(ProjectCapability.CSharpOrVisualBasicOrFSharpLanguageService)]

It would be really great if you could find a way to remove this kind of hard-coded language dependencies, so others can use and build on this code unchanged.

Robert

**Comment by jmarolf** [comment]
We are moving [F#](https://github.com/dotnet/project-system/tree/master/src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS) to use the new project system which also has an old project system based on MPF.  Hopefully this work will help X# when it needs to move.  @davkean can speak more to the technical ways that the project system is loaded.

**Comment by davkean** [comment]
@RobertvanderHulst I'm keen to remove the hardcoded languages on the capabilities, I wanted to replace them with `Managed` but C++/CLI uses this same capability, so we need to combine it with another or choose a different one. I'm thinking `Managed + CPS' which will exclude C++ I'll accept a PR for this if you would like, otherwise, I'll file a bug to track this.

To influence whether a project opens in the new project system or an old project system, you implement what we call a project selector. Here's an example: https://github.com/dotnet/project-system/pull/1988/files#diff-7f844133b837e70387f3e0c3c7e6149bR15.

**Comment by davkean** [comment]
I've filed: https://github.com/dotnet/project-system/issues/2017 to track the capability change.

**Comment by RobertvanderHulst** [comment]
@davkean. Thanks for the info. I have some additional questions:
- I can see the IVsProjectSelector code for F#, but not for C# or VB. Is the mechanism different for these 2 languages (and Google thinks I am looking for an  IV Product Selector ;) )
- As long as the attributes literally list the languages C#, VB and F#, what do I need to do to derive my projectsystem from the VS ProjectSystem. Is CPS really checking the contents of these strings and does that mean that my projectsystem will not work until this has changed ?
- It would be really helpful if we could see the source code on the 'other side'. I mean the CPS source code. What are the plans for this. So far only the CPS docs are on Github. Are there plans to post the CPS code on Github too ? 

Robert

**Comment by davkean** [comment]
> I can see the IVsProjectSelector code for F#, but not for C# or VB. Is the mechanism different for these 2 languages (and Google thinks I am looking for an IV Product Selector ;) )
For performance reasons, we've put the C#/VB selectors into csproj.dll and msvbprj.dll (not open source) - we don't want to unnecessarily load extra dlls for the legacy projects. The mechanism is identical to F#.

> As long as the attributes literally list the languages C#, VB and F#, what do I need to do to derive my projectsystem from the VS ProjectSystem. Is CPS really checking the contents of these strings and does that mean that my projectsystem will not work until this has changed ?
Read up on capabilities: https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/about_project_capabilities.md. These components will be used when those the capability expression applied to them evaluates to true. CPS can be used without our components, but you won't get "managed" project system behavior, such as the Properties folder, RESX support, properties pages, etc.

> It would be really helpful if we could see the source code on the 'other side'. I mean the CPS source code. What are the plans for this. So far only the CPS docs are on Github. Are there plans to post the CPS code on Github too ?
Agreed. However, there are no concrete plans on publishing their source code. // cc @lifengli

**Comment by RobertvanderHulst** [comment]
@davkean Ok, David I got it. So if I make sure that our project system exposes these capabilities then it will work. CSharp or VB is just a word here and does not require our project system to actually be C# or VB.

**Comment by srivatsn** [comment]
There's a doc about this topic now as well - https://github.com/dotnet/project-system/blob/master/docs/opening-with-cps.md

**Comment by RobertvanderHulst** [comment]
@Srivatsn Thanks for the documentation.

**Comment by Pilchie** [comment]
Got moved to https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md.
