### ISSUE TITLE
Incorrect namespace generated for new files when the project contains special characters

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2016]
_From @BattleRush on April 17, 2017 21:53_

**Version Used**: 
15.3 (master)
VisualStudio.15.Release/15.1.0+26403.7

**Steps to Reproduce**:

![image](https://cloud.githubusercontent.com/assets/11750584/25103221/fe1e8392-23bb-11e7-9088-11aa851df963.png)

1. Create a project with special characters like " ", -, +, =, (, ), !, .,
2. Add a new .cs file

**Expected Behavior**:
```
using System;
using System.Collections.Generic;
using System.Text;

namespace Debug____Test_2__.net_core________
{
    class Class1
    {
    }
}
```

**Actual Behavior**:
```
using System;
using System.Collections.Generic;
using System.Text;

namespace Debug == Test 2 (.net core) ! -+-+
{
    class Class1
    {
    }
}
```

The initial Program.cs receives the correct namespace, but all new files being added are being generated incorrectly.

Couldn't quite find the event that is creating those files.
I looked into `Microsoft.CodeAnalysis.FileTextLoader` but at that point the file was already written to disk and it's already too late. Could someone point out where I should look to find the correct entry point to debug this issue?

_Copied from original issue: dotnet/roslyn#18758_

**Comment by davkean** [comment]
_From @Pilchie on April 18, 2017 2:16_

Tagging @srivatsn @davkean looks like a `roslyn-project-system` issue?

**Comment by davkean** [comment]
_From @BattleRush on April 18, 2017 8:15_

I was able to reproduce the issue with .Net Core and .Net Standard Projects (Tested with: Console, Lib, Web projects).
.Net Framework projects worked as expected.

Other issue I found is when you add in .Net Core/Standard projects a new resource file, the *.Designer.cs file is not being generated, which has a bigger impact than just the namespace name. I assume its strongly linked with the namespace issue.

**Comment by davkean** [comment]
@BattleRush I'll move this over to the project system. The second issue is https://github.com/dotnet/project-system/issues/1521.

**Comment by davkean** [comment]
Whomever fixes this, is this supposed to be handled by: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/LanguageServices/CSharpLanguageFeaturesProvider.cs#L89.

**Comment by davkean** [comment]
Template looks correct: https://github.com/dotnet/sdk/blob/master/src/Templates/ProjectTemplates/CSharp/.NETCore/CSharpClassLibrary/Class1.cs#L3

**Comment by davkean** [comment]
Test VB also, I don't think we implement ILanguageFeaturesProvider.

**Comment by BattleRush** [comment]
Thanks @davkean for the info where to look for the issue. I was looking in the roslyn project to debug the issue (still quite new to the roslyn project) and couldn't quite figure out the entry point to debug.

If its fine I would like to give it a try when I get home at this issue.

**Comment by davkean** [comment]
@BattleRush No probs feel free to investigate if you would like, I suspect some of the code you need to debug is closed source.

**Comment by BattleRush** [comment]
@davkean Unfortunately it seems that I'm not fully able to debug this issue and couldn't make much progress. As you said a part of the source is closed, it would be best someone from the team would look at this issue. Even if I wasn't able to debug the issue, it was interesting to understand a bit more how the the roslyn projects interact.

Regarding the closed source, may I ask why its closed source or if its maybe planed to opensource that part aswell.

**Comment by AArnott** [comment]
@BattleRush The project system is based on CPS (Common Project System) which is a Visual Studio feature and closed source like most of the VS platform. It's not part of dotnet or roslyn itself.

**Comment by mlorbetske** [comment]
Another report of this https://developercommunity.visualstudio.com/content/problem/64803/problem-with-hypen-in-project-name.html

**Comment by Pilchie** [comment]
@jmarolf I believe we've seen a couple more dupes of  this too - do you know whether it lives here or in CPS?

**Comment by davkean** [comment]
I'd expect our CSharpLanguageFeaturesProvider implementation to be called back in this case.

**Comment by Pilchie** [comment]
@tmeschter @nguerrera didn't we look at this already?

**Comment by drewnoakes** [comment]
Another report in [feedback ticket 387989](https://developercommunity.visualstudio.com/content/problem/387989/visual-studio-requires-underscore-in-namespace.html), this time where the symbol starts with a digit.

**Comment by drewnoakes** [comment]
I also cannot reproduce this in 15.9.5.

**Comment by swesonga** [comment]
This issue does not reproduce in 16.7.3 either.
