### ISSUE TITLE
Pack succeeded but with no .nupkg generated for ASP.NET core web project

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/project-system#2024]
_From @MiaomiaoHuangfu on April 17, 2017 9:52_

create an ASP.NET Core web project, right click the project and click "Pack".

- Expected result: .nupkg is generated under the path bin\debug;
- Actual result: .nupkg is not generated under the path bin\debug or other path. 

![packsucceededwithnonupkggenerated](https://cloud.githubusercontent.com/assets/22901391/25085783/80591c62-2396-11e7-9bf5-04dfa4c27974.PNG)

Test on vsuwpt.26414.03
OS: windows 10 X64

_Copied from original issue: aspnet/Tooling#1030_

**Comment by srivatsn** [comment]
This issue was moved to NuGet/Home#5084

**Comment by davkean** [comment]
I was going to leave it hear because we set the global property to do this - I suspect it's got out of sync.
