### ISSUE TITLE
Adding a file causes .csproj pending changes even though it hasn't changed

### ISSUE THREAD

**Issue by jnm2** [dotnet/project-system#2031]
<sup>(Not sure on the correct repo for source control or TFS issues with the project system. If I'm not in the right place, a new issue template for this repo could point me in the right direction with new questions.)</sup>

If you add a class to a project through Visual Studio, it correctly creates it in the folder and does not add anything to the .csproj but then it goes on and causes it to show up in TFS pending changes. I'm not sure if this is because it touches the .csproj's whitespace or last modified date or something like that, or if the project system is wired to tell TFS to consider it changed.

**Comment by srivatsn** [comment]
Probably related to https://github.com/dotnet/project-system/issues/1652

**Comment by davkean** [comment]
Yeah, it's a dupe.
