### ISSUE TITLE
"ResolvePackageDependencies" task failed unexpected

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2044]
- Copy the file \\scratch2\scratch\jinuj\TestSceanrio\MultiTargetting.zip to the machine and extract it;
- double click the .sln file, auto restore completed with 4 errors:
 ![restorewitherros](https://cloud.githubusercontent.com/assets/22901391/25273319/e18461de-26bd-11e7-9d27-22b9fe73ea0f.png)

- Close the solution and reopen it, restore completed but still with 2 errors:
The "ResolvePackageDependencies" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
![restorewitherros2](https://cloud.githubusercontent.com/assets/22901391/25273393/34b375ac-26be-11e7-9325-2caa65b17c82.png)

Expected result: restore completed with no errors or warnings.

Test on d15prerel.26420.02;
OS: windows 10 X64

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#1170
