### ISSUE TITLE
Project package settings aren't persisted when specified in source

### ISSUE THREAD

**Issue by terrajobst** [dotnet/project-system#2051]
I've [helped a customer](https://github.com/Tornhoof/RoaringBitmap/pull/6) fix an issue after they migrated their `project.json` project to the new `.csproj` system.

### Actual Behavior

The result looks like this:

* The project has an old-school `AssemblyInfo.cs` with assembly level attributes.
* The project is configured to not generate the assembly info file
* When showing the package property pages, it shows these values in the UI
* Changing the value and saving *neither* persists them in the `AssemblyInfo.cs`  nor the `.csproj`
* Building a NuGet package results in having a `.nupkg` that use the default values of the MSBuild properties, *not matching* the UI which displays the values from `AssemblyInfo.cs` 

### Expected Behavior

There seems to be two locations for the configuration of certain properties: MSBuild or hand-written `AssemblyInfo.cs`. Since the property pages are primarily for the NuGet package, they should match the values that are passed to the packaging task.

This can either be achieved by reading the produced assembly manifest and initialize the properties from there or by not using the values from `AssemblyInfo.cs` at all.

**Comment by srivatsn** [comment]
We are supposed to persist changes to the assembly attributes if generateassemblyinfo is false.

**Comment by terrajobst** [comment]
> We are supposed to persist changes to the assembly attributes if generateassemblyinfo is false.

Sure, but that fix by itself doesn't address the issue that these values aren't used by `pack` to produce the NuGet package, right?

**Comment by davkean** [comment]
@terrajobst Agreed.

**Comment by srivatsn** [comment]
I confirmed that changing values in the package prop page updates assemblyinfo.cs - However as @terrajobst points out pack doesn't use those values. I forget how this was supposed to work, when this was originally discussed at https://github.com/dotnet/sdk/issues/2. I'll move the discussion to NuGet.

**Comment by srivatsn** [comment]
This issue was moved to NuGet/Home#5312
