### ISSUE TITLE
Restore failed for ASP.NET Core project (web, webpai and mvc) for "Unable to resolve 'Libuv (>= 1.10.0-preview1-22038)' for '.NETCoreApp,Version=v2.0'"

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2059]
- New project and choose " ASP.NET Core web Application (.NET Core)" template;

- In "New ASP.NET Core Web Application (.NET Core) - WebApplication" window, choose the "ASP.NET Core 2.0" in the downlist of targetframework, click the "Web Application" template, then click "OK".
  ![aspnetcorewebtemplate](https://cloud.githubusercontent.com/assets/22901391/25326520/2aae43f6-2903-11e7-9dd5-fdcf14a0e1c3.PNG)

**Expected result:** create ASP.NET Core web Application succeeded, auto restore succeeded with no errors.
**Actual result:** Create ASP.NET Core web Application  succeeded, but restore failed with error "Unable to resolve 'Libuv (>= 1.10.0-preview1-22038)' for '.NETCoreApp,Version=v2.0'.
NuGet package restore failed."
![webrestorewitherros](https://cloud.githubusercontent.com/assets/22901391/25326716/fd04b29a-2903-11e7-8d6f-4b657dfce067.png)
Note: restore failed with same error as well when creating web empty or Web API project which targeting ASP.NET Core 2.0

Test on d15prerel.26421.06
OS: windows 10 X64

**Comment by srivatsn** [comment]
This issue was moved to aspnet/Tooling#1032
