### ISSUE TITLE
VS crashes when pressing "Ctrl + t" and inputing content 

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2060]
- Open the .sln file under \\mlangfs1\public\jomorris\ConnectProductivityDemoOn.NETCore have Trainer.cs opened;
- Press "Ctrl + t" ;
- try to search "workout" and VS crashes.
  ![vscrashesafterctrt](https://cloud.githubusercontent.com/assets/22901391/25328598/069e613c-290b-11e7-91a6-4167006b335f.PNG)
Expected result: Go to feature run smoothly and can quickly navigate to any file/type/member/symbol via "Ctrl + t".

Test on d15prerel.26421.06
OS: Windows 10 X64

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn#18943
