### ISSUE TITLE
Cannot navigate to project from Find Results Window

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#2063]
1. Right-click project and choose Edit [project]
2. Edit -> File In Files
3. Change Look in to "Current Document"
4. Find a term in the project file
5. Click Find All

Expected:

Project file is opened for editing.

Actual:
```
---------------------------
Microsoft Visual Studio
---------------------------
The document 'C:\sample.csproj' is already open as a project or a solution and cannot be opened in an editor at this time.
---------------------------
OK   
---------------------------
```

**Comment by davkean** [comment]
I suspect this is caused by the same underlying issue that prevents this from working: https://github.com/dotnet/project-system/issues/1490

**Comment by davkean** [comment]
@jmarolf What's the exact repro this for this? I cannot get Find to find results in a project file due to #1490.

**Comment by davkean** [comment]
Updated the repro to more specific steps.

**Comment by davkean** [comment]
Duping this against https://github.com/dotnet/project-system/issues/4061.
