### ISSUE TITLE
Packages unsupported by a target have non-empty dependencyIDs metadata non empty, resulting in empty nodes to appear non-empty, but have no children

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2069]
After investigation i found that it is kind of old logic living in sdk task PreprocessPackageDependenciesDesignTime. We reused items for packages accross targets instead of cloning them and it caused all package items for all targets to have dependencyIDs property updated.

Fix is available in sdk.

**Comment by natidea** [comment]
Here is the full repro for completeness:

- Open the following .NET Core Console App in Visual Studio:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.0;net46</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.1.3" />
  </ItemGroup>

</Project>
```

Actual: Under .NETCoreApp 2.0 TFM there is a NuGet -> EntityFramework node with an expander, even though the project.assets.json file does not contain any dependency entries for this TFM.
