### ISSUE TITLE
Referencing netstandard assembly from default new unit test projects fails to build

### ISSUE THREAD

**Issue by olegtk** [dotnet/project-system#2078]
1.	Install latest VS2017 RTW (with .NET Core workload)
2.	Create new netstandard lib project (targets netsatndard 1.4 by default)
3.	Add unit test project to the solution (by default targets .NET 4.5.2)
4.	Add a reference to the netstandard lin project
5.	Build

**Expected**: Builds ok or provides an actionable error message (as all that's needed is to just target .NET 4.6.1 in the unit test proj).

**Actual**:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Project 'c:\users\olegtk\documents\visual studio 2017\Projects\ClassLibrary3\ClassLibrary3\ClassLibrary3.csproj' targets '.NETStandard,Version=v1.4'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.5.2'.	UnitTestProject1

**Comment by srivatsn** [comment]
The issue here is that the default framework for projcts is 4.5.2 but the netstandard default is higher. We should probably change the default framework for desktop projects to 4.6.1

**Comment by srivatsn** [comment]
The default for desktop projects has been changed to 4.6.1
