### ISSUE TITLE
VB: language version flag 15.3 not properly passed to project system

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#2088]
@jcouv commented on [Fri Apr 28 2017](https://github.com/dotnet/roslyn/issues/19075)

Repro:
- Create a VB proj and set language version to 15.3 (in the proj file)
- Type a tuple with inferred names and use the inferred names
- If you build the project, it will build properly
- But the IDE will show red squiggles (it is using language version Default)

---

@AdamSpeight2008 commented on [Fri Apr 28 2017](https://github.com/dotnet/roslyn/issues/19075#issuecomment-298045526)

Default is tied to latest major release, `15.0`.
How are you changing the language? Manually editing the actual `.vbproj` file?

---

@jcouv commented on [Fri Apr 28 2017](https://github.com/dotnet/roslyn/issues/19075#issuecomment-298054184)

From discussion with @srivatsn, only the new project system has a generic way of passing the whole command-line through. 
The old project system has to go through the un-managed API (`CVbcMSBuildHostObject::SetLanguageVersion`). That method needs to convert from language version as a string ("15.3") to an enum value (`VisualBasic15_3 = 1503` in this case).
Note: the corresponding method for Csc (`CCscMSBuildHostObject::SetLangVersion`) doesn't have that problem (it is just a pass-through).

@srivatsn It would be great if someone from your team could help with that. Thanks

FYI @jasonmalinowski 

---

@jcouv commented on [Fri Apr 28 2017](https://github.com/dotnet/roslyn/issues/19075#issuecomment-298054953)

One more thing: while making this change, let's also make sure that language version "Latest" is passed properly (`Latest = Integer.MaxValue`, but it's probably better to pass the specific version, `1503`).

---

@srivatsn commented on [Fri Apr 28 2017](https://github.com/dotnet/roslyn/issues/19075#issuecomment-298055213)

Can you file a bug in the project-system repo for this?

**Comment by jasonmalinowski** [comment]
> From discussion with @srivatsn, only the new project system has a generic way of passing the whole command-line through. The old project system has to go through the un-managed API (CVbcMSBuildHostObject::SetLanguageVersion). That method needs to convert from language version as a string ("15.3") to an enum value (VisualBasic15_3 = 1503 in this case).
Note: the corresponding method for Csc (CCscMSBuildHostObject::SetLangVersion) doesn't have that problem (it is just a pass-through).

Even in the old one you have [ICompilerOptionsHostObject](https://github.com/dotnet/roslyn/blob/81a7376b2f44a4d2a2fa66f19da492dc6db7127e/src/Compilers/Core/MSBuildTask/ICompilerOptionsHostObject.cs) you can use to shuttle stuff around the native project system.

**Comment by srivatsn** [comment]
Closing this since @jcouv is tracking a build task fix for this in https://github.com/dotnet/roslyn/issues/19075
