### ISSUE TITLE
csproj file has auto complete issues with VersionSuffix property

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2089]
Reported through [VSFeedback](https://developercommunity.visualstudio.com/content/problem/48526/csproj-file-has-auto-complete-issues-with-versions.html)

The intellisense says that the property to define a version suffix is "VersionSufix" and it is missing an "F" letter. The resulting build outputs do not have the version suffix applied as a result unless it is fixed manually and written as "VersionSuffix" with double F.

**Comment by rainersigwald** [comment]
Dup of https://github.com/Microsoft/msbuild/issues/1812, just fixed in `lab/vsuwpt`.
