### ISSUE TITLE
start button on a solution that has both a .NET Core and desktop frameworks console app does not change text when drop down is changed

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2091]
Reported by @ManishJayaswal through VSFeedback:

When I click the drop down ( highlighted in the attached image) and change the startup project, the text next to green arrow start button does not always change. Sometimes it stays as start, as sown in one of the attached image and sometimes it shows the name of the chose startup project ( as shown in other attached image) 

![capture1](https://cloud.githubusercontent.com/assets/20570/25542636/3b055e80-2c08-11e7-8e00-23db0b7a58f2.JPG)

![capture2](https://cloud.githubusercontent.com/assets/20570/25542644/412feb86-2c08-11e7-944d-68ca5683847d.JPG)

**Comment by srivatsn** [comment]
Oh actually now that I actually look the screenshots - the desktop project using the old project system just shows Start. But netcore projects using the new project system shows the project name. I originally thought the issue was showing the projectname for netcore projects was flaky but if it's consistenty just the difference between desktop and netcore projects, then I think we'll just fix this by moving desktop proejcts to CPS :) @ManishJayaswal  can you confirm that it isn't flaky within netcore projects?

**Comment by ManishJayaswal** [comment]
yes I confirm it is not flaky.

**Comment by srivatsn** [comment]
Closing this out then since it's just a new feature for .NET Core projects.
