### ISSUE TITLE
investigate flaky netcore tests

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2092]
_From @jmarolf on April 28, 2017 19:54_

_Copied from original issue: dotnet/roslyn#19090_

**Comment by srivatsn** [comment]
_From @Pilchie on April 28, 2017 21:5_

@jmarolf should this go on `dotnet/project-system`?

**Comment by srivatsn** [comment]
_From @jmarolf on April 28, 2017 21:11_

@Pilchie the tests live in this repo.  I don't know the strategy, perhaps?

**Comment by srivatsn** [comment]
_From @Pilchie on April 28, 2017 21:40_

Fair point, but there is no appropriate Area label to classify this.  @srivatsn where would you like to track it?

**Comment by srivatsn** [comment]
Let's just move to the project-system repo so that there's place to look at all project system bugs.

**Comment by jmarolf** [comment]
resolved with https://github.com/dotnet/project-system/pull/2169
