### ISSUE TITLE
Error list does not preserve filtering after builds

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2094]
When i uncheck Errors button in ErrorList to hide all errors

![image](https://cloud.githubusercontent.com/assets/1592091/25550758/b5982808-2c30-11e7-8219-1787080a489e.png)

then do build again, it appears checked again automatically and shows all errors again:

![image](https://cloud.githubusercontent.com/assets/1592091/25550760/b807909c-2c30-11e7-82f0-4478683e7529.png)

**Comment by srivatsn** [comment]
@abpiskunov this is an error list issue. Can you file a VSO bug instead?
