### ISSUE TITLE
Rename class file appears to not update proj file

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/project-system#2109]
@vsccarl commented on [Tue May 02 2017](https://github.com/dotnet/corefx/issues/19255)

In the latest d15rel build renaming a class file keeps the original file name and marks it as 'Not Found' in solution explorer.

Repros in all .NET Core project types.

![image](https://cloud.githubusercontent.com/assets/12900364/25643859/efe179f0-2f56-11e7-8442-e2eaa2ac6b4f.png)

**Comment by davkean** [comment]
This is known and the fix will be inserted today.
