### ISSUE TITLE
Changing the severity of a rule in the analyzers node doesnt take effect

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2114]
1. Create a netstandard library
2. Add Microsoft.FxCopAnalyzers nuget package.
3. Make class1 derive from Attribute - this will fire CA1018.
4. Set CA1018's severity to None from solution explorer

Expected: the diagnostic would be suppressed
Found: A ruleset file is created but looks like that ruleset doesn't become the active one - the project file doesn't change to update it as the CodeAnalysisRuleSet property either.

**Comment by tmeschter** [comment]
The .ruleset file is created and the severity of CA1018 is set to `None` within the file, but the `CodeAnalysisRuleSet` property is never set in the project file.

I suspect this has something to do with how configurations are represented. The project system extension points treat `CodeAnalysisRuleSet` as a per-configuration property, but in the new project system the project file may not define any configurations itself--they come from the imported targets/props. I wonder if this prevents the extension points from finding them.

**Comment by tmeschter** [comment]
Ah, our implementations of EnvDTE.ConfigurationManager and EnvDTE.Properties do not seem to support the "CodeAnalysisRuleSet" property. That makes it hard to set. ;-)

Indeed, they only seem to support "OutputPath".

**Comment by davkean** [comment]
We should add those properties.

**Comment by tmeschter** [comment]
This is basically another manifestation of #755.

When we ask for `Properties` we end up getting an object backed by `Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectConfigProperties`, exported under the `Microsoft.VisualStudio.ProjectSystem.ExportContractNames.VsTypes.ConfiguredProjectPropertiesAutomationObject`.

To fix this properly we would like to export our own `ConfiguredProjectPropertiesAutomationObject` that is backed by an `IRule` with all the properties we care to expose. That way if we need to add a property, we just have to update the `IRule` and it will flow through automatically.

We do need to check that this approach will also let us _set_ a property, not just _read_ it.
