### ISSUE TITLE
Incorrect font used for the Debug page on project properties

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2122]
Reported through VSFeedback by @pharring 

The "Debug" page in project properties for a .Net Core Console application appears to be using a different font from the rest of the Visual Studio UI. It appears to be using "Microsoft Sans Serif, 8.25" whereas the rest of the UI is Segoe UI 8.

**Comment by ghuntley** [comment]
Confirmed in `15.7.0 Preview 2.0` using netstandard project.

* [ ] Obtain font preferences from ????
* [ ] Update https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/WatermarkStyle.xaml
* [ ] Update https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml
