### ISSUE TITLE
Rebuild in VS2017 doesn't create package if <TargetFrameworks> tag used

### ISSUE THREAD

**Issue by DavidArno** [dotnet/project-system#2123]
I'm creating this issue here after discussing this with @davkean on twitter.

This issue is observed using `Microsoft Visual Studio Professional 2017 Version 15.1 (26403.7) Release VisualStudio.15.Release/15.1.0+26403.7` and the demo project at [DavidArno/TargetFrameworksPackBug
](https://github.com/DavidArno/TargetFrameworksPackBug)

This problem occurs for both MSBuild and for building inside Visual Studio.
* If **Build** is used, all is well and the package is created,
* If **Rebuild** is used, no package is created.

eg, If built on the command line, using:
```
dotnet restore
msbuild /p:Configuration=Release /v:minimal
```
Then all works as expected:
```
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  TargetFrameworksPackBug -> ...\TargetFrameworksPackBug\TargetFrameworksPackBug\bin\Release
  \netstandard1.1\TargetFrameworksPackBug.dll
  TargetFrameworksPackBug -> ...\TargetFrameworksPackBug\TargetFrameworksPackBug\bin\Release
  \netstandard1.4\TargetFrameworksPackBug.dll
  Successfully created package '...\TargetFrameworksPackBug\TargetFrameworksPackBug\bin\Rele
  ase\TargetFrameworksPackBug.1.0.0.nupkg'.
```

However,  if rebuild is used:
```
dotnet restore
msbuild /p:Configuration=Release /v:minimal /t:Rebuild
```
Then no package is created:
```
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  TargetFrameworksPackBug -> ...\TargetFrameworksPackBug\TargetFrameworksPackBug\bin\Release
  \netstandard1.1\TargetFrameworksPackBug.dll
  TargetFrameworksPackBug -> ...\TargetFrameworksPackBug\TargetFrameworksPackBug\bin\Release
  \netstandard1.4\TargetFrameworksPackBug.dll
```

Likewise, when loaded into Visual Studio, a build of the solution results in the package being created and a rebuild of the solution, doesn't.

**Comment by nguerrera** [comment]
@DavidArno Thanks for the report. This is a consequence of https://github.com/Microsoft/msbuild/issues/1663, which has been fixed. You should see the correct behavior starting in the upcoming preview.

**Comment by DavidArno** [comment]
@nguerrera,

Excellent news. Thanks.

**Comment by davkean** [comment]
Thanks @nguerrera and thanks for filing it @DavidArno.
