### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspacesNetCore.ProjectReference [FAIL]

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2124]
_From @dpoeschl on May 3, 2017 21:29_

https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/3638/

Seems to be failing very consistently.

_Copied from original issue: dotnet/roslyn#19223_

**Comment by srivatsn** [comment]
_From @dpoeschl on May 3, 2017 21:29_

@dotnet/roslyn-infrastructure

**Comment by srivatsn** [comment]
_From @Pilchie on May 4, 2017 16:19_

@srivatsn / @jmarolf want to move this to the project system repo?

**Comment by jmarolf** [comment]
resolved with https://github.com/dotnet/project-system/pull/2169
