### ISSUE TITLE
Remove old setup authoring files from VS

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/project-system#2153]
There are vestigial setup authoring files in VS at SetupAuthoring/vb/Registry/Microsoft.VisualStudio.Editors.*.ddr that should be removed.

**Comment by tmeschter** [comment]
Tom's triage notes: This is a basic code clean-up issue. We should do this.

**Comment by davkean** [comment]
@panopticoncentral These files don't exist and don't have ever existed based on:

```
git log --all --full-history -- "**/Microsoft.VisualStudio.Editors.*"
```

Are you referring to something else?

**Comment by panopticoncentral** [comment]
I know there was something that needed to be removed, but it's been 2.5 years now and I can't find it so, ¯\_(ツ)_/¯
