### ISSUE TITLE
Resource file editing fails for project targeting .NET Core 2.0 or .NET Standard 2.0

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/project-system#2155]
- Using VS 15.3 (preview) with .NET Core SDK (preview)
- File \ New Project \ Console App (.NET Core)
  - Also repros with Class Library (.NET Standard)
- Add \ New item \ Resources file

Note that the Value cell shows "(Value cannot be displayed)".

- Edit value and save

**EXPECTED:** Value is saved
**ACTUAL:** Visual Studio crashes

This might be related to the fact that mscorlib isn't part of .NET Core 2.0 or .NET Standard 2.0

Stack trace:

>	[Managed to Native Transition]	
 	mscorlib.dll!System.RuntimeTypeHandle.GetTypeByName(string name, bool throwOnError, bool ignoreCase, bool reflectionOnly, ref System.Threading.StackCrawlMark stackMark, System.IntPtr pPrivHostBinder, bool loadTypeFromPartialName)	Unknown
 	mscorlib.dll!System.RuntimeType.GetType(string typeName, bool throwOnError, bool ignoreCase, bool reflectionOnly, ref System.Threading.StackCrawlMark stackMark)	Unknown
 	mscorlib.dll!System.Type.GetType(string typeName, bool throwOnError, bool ignoreCase)	Unknown
 	Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.ResourceEditor.Resource.GetValueTypeHelper(string ValueTypeName, bool ThrowOnError)	Unknown
 	Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.ResourceEditor.Resource.SetValueWithoutUndo(object NewResourceValue)	Unknown
 	Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.ResourceEditor.Resource.SetPropertyValueWithoutUndo(string PropertyName, object Value)	Unknown
 	Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.ResourceEditor.ResourcePropertyDescriptor.SetValue(object Component, object Value)	Unknown
 	Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.ResourceEditor.Resource.SetValue(object NewResourceValue)	Unknown
 	Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.ResourceEditor.ResourceStringTable.OnCellValuePushed(System.Windows.Forms.DataGridViewCellValueEventArgs e)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.DataGridView.OnCellValuePushed(int columnIndex, int rowIndex, object value)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.DataGridViewCell.SetValue(int rowIndex, object value)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.DataGridView.PushFormattedValue(ref System.Windows.Forms.DataGridViewCell dataGridViewCurrentCell, object formattedValue, out System.Exception exception)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.DataGridView.CommitEdit(ref System.Windows.Forms.DataGridViewCell dataGridViewCurrentCell, System.Windows.Forms.DataGridViewDataErrorContexts context, System.Windows.Forms.DataGridView.DataGridViewValidateCellInternal validateCell, bool fireCellLeave, bool fireCellEnter, bool fireRowLeave, bool fireRowEnter, bool fireLeave)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.DataGridView.EndEdit(System.Windows.Forms.DataGridViewDataErrorContexts context, System.Windows.Forms.DataGridView.DataGridViewValidateCellInternal validateCell, bool fireCellLeave, bool fireCellEnter, bool fireRowLeave, bool fireRowEnter, bool fireLeave, bool keepFocus, bool resetCurrentCell, bool resetAnchorCell)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.DataGridView.CommitEditForOperation(int columnIndex, int rowIndex, bool forCurrentCellChange)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.DataGridView.ScrollIntoView(int columnIndex, int rowIndex, bool forCurrentCellChange)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.DataGridView.ProcessDownKeyInternal(System.Windows.Forms.Keys keyData, out bool moved)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.DataGridView.ProcessEnterKey(System.Windows.Forms.Keys keyData)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.DataGridView.ProcessDataGridViewKey(System.Windows.Forms.KeyEventArgs e)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.DataGridView.ProcessKeyPreview(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ProcessKeyPreview(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ProcessKeyMessage(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WmKeyChar(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.TextBoxBase.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.TextBox.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.ResourceEditor.ResourceStringTable.ResourceStringTextBoxEditingControl.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam)	Unknown

**Comment by srivatsn** [comment]
Both @panopticoncentral and I had tested this scenario with 2.0 before and it did work before. I can however repro this now. Not sure what's changed.

**Comment by srivatsn** [comment]
Looks like DTAR is finding mscorlib and resolving the typeforwarder to find netstandard.dll but it then tries to do a Type.GetType("System.String, netstandard.dll...") which fails because its not loaded in the VS process anywhere. 

Tagging @ericstj

**Comment by ericstj** [comment]
Why isn't the designer using the netstandard.dll that is part of the project?

The only way it got a typeforward to netstandard.dll was by loading some System.* dll that was part of the project, seems unusual that it'd do that but not do the same for netstandard.dll.

/cc @weshaggard

**Comment by ericstj** [comment]
> This might be related to the fact that mscorlib isn't part of .NET Core 2.0 or .NET Standard 2.0

That statement is incorrect.  MSCorlib is part of both .NETCoreApp2.0 and .NETStandard2.0 projects.

**Comment by srivatsn** [comment]
The designer asks the type resolution service to find the dll that has System.String and that service knows about project references and finds the right location of System.String which is in netstandard.dll. The designer then directly calls Type.GetType(typefullname) - presumably this has always worked before because the dll that string lived in always was loaded in VS or could be found by Type.GetType - not the case anymore.

**Comment by ericstj** [comment]
Do you mean AssemblyQualifiedTypeName?  In that case I'd expect them to hook up some assembly resolver that could load the assembly from the project rather than relying on stuff already loaded and/or probing paths for VS...

> right location of System.String which is in netstandard.dll

That's only true for a netstandard2.0 project.  In netcoreapp2.0 its in System.Runtime.dll.  Let's try to talk about a single scenario here.

**Comment by davkean** [comment]
@ericstj This is a runtime probe in the default appdomain, presumably netstandard.dll won't even load because it's marked with the special bit in the assembly flags. There are hardcoded assumptions throughout VS that it runs on a framework is that is greater than what the project is targeting.

**Comment by davkean** [comment]
> The only way it got a typeforward to netstandard.dll was by loading some System.* dll that was part of the project, seems unusual that it'd do that but not do the same for netstandard.dll.
There's two different probes here; one is through LMR to find effectively a "reflection-only" type - that causes us to follow the type forward. The second probe is to grab that reflection-only type and get an instance of a runtime-equivalent of it. That's what you are seeing above.  

Think of how we made Silverlight work with those "runtime loadable reference-assemblies" that ended up forwarding onto .NET Framework types.

**Comment by ericstj** [comment]
All of the facades in netcoreapp are runtime loadable, including netstandard.dll, and are in the System.Runtime type domain which should work on desktop.  NETStandard.dll in a netstandard project is the only thing that isn't runtime loadable.  If the designer needs to load that for runtime then it may need a desktop version of that on the side until netstandard.dll goes inbox on desktop.
