### ISSUE TITLE
VS 15.3 Preview 1 breaks project platforms defined in project file

### ISSUE THREAD

**Issue by AArnott** [dotnet/project-system#2157]
In VS 2017 through 15.2, this project file would be reported in VS as having an x64 platform for all configs:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net45|x64'" />
</Project>
```

But in VS 2017 15.3 Preview, the project system only reports an AnyCPU platform. This causes VS to rewrite the solution configurations such that any reference to the x64 platform is removed. So after saving the sln in VS 15.3 Preview, the build (whether in VS or at the command line) is faulty as it builds the project for AnyCPU where it should have been x64.

**Comment by AArnott** [comment]
It seems that 15.3 has a different style for expressing platforms:

```xml
<PropertyGroup>
    <Platforms>AnyCPU;x64</Platforms>
</PropertyGroup>
```

I like the new style better, but are you concerned about the breaking change in no longer supporting the old style?

**Comment by AArnott** [comment]
One more observation: 15.2 does *not* support the 15.3 style. So no single project file representation works in both. I guess I have to retain *both* representations (by hand) for this to work across versions. 👎

**Comment by srivatsn** [comment]
The break and the rationale are documented [here](https://github.com/dotnet/project-system/blob/master/docs/configurations.md) - basically telemetry suggests that a very small number of projects will run into this issue and supporting both is a bunch of extra work and builds long-term legacy. However, if this becomes a significant paint point, then yes we'll look into a hybrid system where we'd support both forms.

**Comment by AArnott** [comment]
Thanks. That makes sense. I would suggest you add to that doc a suggestion that the project author maintain *both* xml tags in their project file while their users aren't all on 15.3.
