### ISSUE TITLE
NoVariablesDefault configuration loaded into .Net Core projects

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#2159]
It is loaded when we calculate configuration dimensions to know which configuration should be loaded.  However, it becomes a fully loaded configuration, and chain all data flow blocks, so it gets reevaluated every time the project has a change, and gather schema rules, detecting glob changes. 

We want to find a way either prevent the first evaluation, or do it in a lighter way, instead of causing the entire MEF graph to be loaded.

**Comment by davkean** [comment]
@lifengl What's the proposal? Don't use a configuration to do the evaluation? Unload it after loading it? Have a better guess at what the default config is going to be?

**Comment by davkean** [comment]
Dup'ing this against https://github.com/dotnet/project-system/issues/2711.
