### ISSUE TITLE
toolSettings.json gone in 15.3 preview

### ISSUE THREAD

**Issue by stgeorge** [dotnet/project-system#2167]
After installing 2017 15.3 preview, I noticed that toolSettings.json is gone - can no longer customize the file nesting... but there is still file nesting going on, did this file move somewhere else or is something else managing the file nesting in 15.3 preview?

**Comment by srivatsn** [comment]
This was only implemented for web projects. Moving to aspnet/tooling to get an answer to this question.

**Comment by srivatsn** [comment]
This issue was moved to aspnet/Tooling#1039
