### ISSUE TITLE
Adding a new file to a cross-targeting project only adds it to the first TF

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/project-system#2168]
1. git clone https://github.com/KirillOsenkov/MSBuildStructuredLog
2. Open C:\MSBuildStructuredLog\MSBuildStructuredLog.sln in VS 2017 Update 2
3. Add a new C# file to the StructuredLogger project

Expected: the file should show up in both net46 and netstandard1.5.

Actual: the file is only added to net46 (in the NavBar left combobox), and other files which are in "netstandard1.5" don't see the type (as if it's not added to the Roslyn Workspace)

Reloading the project fixes the issue.

**Comment by davkean** [comment]
We fixed this - not sure if that fix made it into Update 2, I thought it did. @mavasani ?

**Comment by mavasani** [comment]
Nope, this will be in 15.3

**Comment by srivatsn** [comment]
This should be fixed in 15.3
