### ISSUE TITLE
Failed to "Manage NuGet Packages..." for "Provide value on 'System.Windows.StaticResourceExtension' threw an exception."

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2171]
For a project, right click the project or right click "Dependencies", click "Manage NuGet Packages...", then prompt a window "Provide value on 'System.Windows.StaticResourceExtension' threw an exception."
![failedtomanagenugetrestore](https://cloud.githubusercontent.com/assets/22901391/26047843/5fe3e4ec-3987-11e7-9410-17f643085cc1.PNG)
 close the .sln and reopen it, the issue is still repro.

Test on d15prerel.26512.05
OS: Windows 10

**Comment by davkean** [comment]
This issue was moved to NuGet/Home#5232
