### ISSUE TITLE
Single File Generator support

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#218]
1. Double-click on a resx file
2. Add a new resource

```
---------------------------
Microsoft Visual Studio
---------------------------
The method or operation is not implemented.
---------------------------
OK   
---------------------------

```

**Comment by 333fred** [comment]
I'll be taking notes here as I discover potential issues.
- The ResourceDesigner currently expects the `IVsHierarchy` to implement `IVsSingleFileGeneratorFactory`, which `ProjectNode` does not. Once we have COM Aggregation, we'll be able to directly implement this interface on the `ProjectNode` instance ourselves.

**Comment by davkean** [comment]
It looks like CPS has some support for single file generators, it looks like we need:

1) Define the "SingleFileGenerators" capability
2) Add registration to register the single file generator for all the files generators we are interested in, for example:

[$RootKey$\Generators\{8bb2217d-0f2d-49d1-97bc-3654ed321f3b}\DotNetPublicResXFileCodeGenerator]
@="DotNetPublicResXFileCodeGenerator"
"CLSID"="{3ade0602-cba7-4507-a207-c13e242b4f81}"
"GeneratesDesignTimeSource"=dword:00000001
"InputFileExtension"=".resx"

**Comment by davkean** [comment]
Above you should replace the registration with the same registration as csproj.

**Comment by davkean** [comment]
We'll also need to implement IVsSingleFileGeneratorFactory - and probably just give that to CPS.

**Comment by davkean** [comment]
I've turned this into representing all single file generator support.

**Comment by 333fred** [comment]
Ok, so the results of my investigations are this:

1. CPS will generate the pkgdefs for us. They have an article on adding SFG's here: https://github.com/Microsoft/VSProjectSystem/blob/master/doc/scenario/add_single_file_generator.md
2. An important note on this: the SFG *must* be in the same assembly as the VsPackage used to generate the pkgdefs. The resulting pkgdef will specify loading the from the assembly that the attributes were declared in. So, the C# ResX generators need to be in the ProjectSystem.CSharp.VS assembly, and similar for VB. We'll need to think about how to go about organizing our dependencies to share as much code between them as possible.
3. I'm not sure that a IVsSingleFileGeneratorFactory is necessary, other than to tell the resource designer to enable the combobox, as CPS instantiates our SFG's for us. Do we want to restructure the designer such that it doesn't need this to enable that?

**Comment by 333fred** [comment]
Pull #297 adds support for ResX, as well as creating an attribute that allows us to specify an SFG in another dll.

**Comment by 333fred** [comment]
The full list of the SFG's registered under the old project system:
- [ ] `DataServiceClientGenerator`
- [ ] `DataServicesCoreClientGenerator`
- [ ] `EntityModelCodeGenerator`
- [ ] `GlobalResourceProxyGenerator`
- [ ] `MSDataSetGenerator`
- [ ] `MSDiscoCodeGenerator`
- [ ] `MSLinqToSQLGenerator`
- [ ] `PublicResXFileCodeGenerator`
- [ ] `PublicSettingsSingleFileGenerator`
- [ ] `ResXFileCodeGenerator`
- [ ] `SettingsSingleFileGenerator`
- [ ] `TextTemplatingFileGenerator`
- [ ] `TextTemplatingFilePreprocessor`
- [ ] `WCF Proxy Generator`
- [ ] `Xaml Activity Generator`

**Comment by odalet** [comment]
+1 for SettingsSingleFileGenerator support. This would help in targetting classic Net apps  from SDK style projects!

**Comment by davkean** [comment]
Dup'ing this against https://github.com/dotnet/project-system/issues/3535 which is tracking us just picking up the legacy project system's registration.
