### ISSUE TITLE
Rename "Unit Test Project" to be better describe it

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/project-system#2183]
_From @dsplaisted on May 15, 2017 21:10_

_From @davkean on November 17, 2016 5:27_

It's confusing that there's a project called "Unit Test Project" and "xUnit Test Project" - can we rename the former to better indicate that it's MSTest based:

![image](https://cloud.githubusercontent.com/assets/1103906/20377349/ba3ee9d2-ace2-11e6-8004-73cf1bff44c5.png)

_Copied from original issue: dotnet/sdk#402_

_Copied from original issue: dotnet/templating#799_

**Comment by mlorbetske** [comment]
_From @dsplaisted on May 15, 2017 21:10_

_From @pvlakshm on November 22, 2016 9:17_

This is a convention that has been in use across various app platforms, and over multiple releases of VS. Therefore, recommend retaining it as-is.

**Comment by mlorbetske** [comment]
_From @dsplaisted on May 15, 2017 21:10_

_From @davkean on November 22, 2016 9:18_

The difference between this release and last, is that there is another unit test project with the same name barring one letter.

**Comment by mlorbetske** [comment]
_From @dsplaisted on May 15, 2017 21:10_

_From @singhsarab on November 22, 2016 9:39_

@codito Please share your thoughts ?

**Comment by mlorbetske** [comment]
_From @dsplaisted on May 15, 2017 21:10_

In VS 2017 we are renaming the templates that were "Class Library" and "Console Application" to "Class Library (.NET Framework)" and "Console Application (.NET Framework)".  So I think it makes sense to also rename the unit test templates to disambiguate them too.

**Comment by mlorbetske** [comment]
_From @dsplaisted on May 15, 2017 21:10_

_From @singhsarab on November 23, 2016 12:46_

I agree with @dsplaisted, we should make them consistent.
Regarding the other concern, I guess changing the icon for Xunit template should help. 
@bradwilson Can you please help us with icon for Xunit template.

**Comment by mlorbetske** [comment]
_From @bradwilson on May 15, 2017 21:56_

@dsplaisted  Our [media repository](https://github.com/xunit/media) contains appropriate logos in [PNG](https://github.com/xunit/media/blob/master/logo-512-transparent.png) and [SVG](https://github.com/xunit/media/blob/master/logo-transparent.svg) format.

**Comment by mlorbetske** [comment]
_From @davkean on May 15, 2017 22:23_

@dsplaisted Why was this put in templating? The templates live in project-system.

**Comment by mlorbetske** [comment]
Yep, the contents live here but the VSTemplate file that hooks it in to VS is over there. Moving the issue.

**Comment by davkean** [comment]
This was done many release ago.
