### ISSUE TITLE
Prevent 'Press any key to continue' in a .Net Core Console App

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/project-system#2184]
@spottedmahn commented on [Fri May 12 2017](https://github.com/dotnet/coreclr/issues/11576)

When I debug my console app it closes automatically.  When I run w/o debugging I get:

![image](https://cloud.githubusercontent.com/assets/14079228/26017231/8476d04c-3736-11e7-93bd-ad59e4f32934.png)

How do I prevent this?

Thanks,
Mike D.

---

@karelz commented on [Fri May 12 2017](https://github.com/dotnet/coreclr/issues/11576#issuecomment-301224984)

This is standard VS behavior for ages AFAIK. Not sure if there is any opt-out.

**Comment by danmosemsft** [comment]
Not you guys' issue but at least you may know..

**Comment by davkean** [comment]
It's our issue, we implement this. 

@spottedmahn This has been the behavior of debugging in VS for as long I can remember. We do not have an opt out.

We might be able to provide an option. This is the first complaint I've heard about it (we had plenty of the reverse complaints when we broke it!) - can you provide more information on what about the behavior bothers you?

**Comment by spottedmahn** [comment]
Ok, thanks @davkean 

I haven't used a lot of console apps in the past so it is something I never noticed.  Thanks for the heads up though!

Seems like inconsistent behavior though.  Perhaps I'll provide feedback on VS.

@danmosemsft thanks for moving the issue to the right place!

**Comment by srivatsn** [comment]
Without this behavior, unless the console app specifically adds a Console.Read, many console apps will just flash on the screen and go away without a chance for the user to see the output. While debugging that's not a problem since it'll stop somewhere. I think this was a feature all those years ago. I doubt we'll change this behavior. We could add an option but it doesn't seem worth it at this point.

**Comment by spottedmahn** [comment]
@srivatsn I see thanks!

**Comment by spottedmahn** [comment]
>can you provide more information on what about the behavior bothers you?

>This has been the behavior of debugging in VS for as long I can remember. We do not have an opt out.

Looks like VS has changed to be in sync with the running experience! 👏👏

>To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.

![image](https://user-images.githubusercontent.com/14079228/59062819-bc679680-8874-11e9-84f6-505425641765.png)

**Comment by Ekus** [comment]
When running a web app with Ctrl+F5 from VS (no debugging) the setting "Automatically close the console..." is ignored.
Sadly, this results in tons of orphaned windows after a few edit/run/test loops, see image. It's impossible to spot the one that is actually running (ignore the text in the last two miniatures, it shows which windows I have inspected manually looking for the running one)

![image](https://github.com/dotnet/project-system/assets/1641673/e7f3986c-1308-4cb1-bf35-b09b6a66454d)
