### ISSUE TITLE
Renaming the class file leads to break intellisense

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2190]
- Create a .net core console app project -- ConsoleApp1;  
- Add a new .net standard class library project -- Classlibrary1;
- Add the reference from ConsoleApp1 to Classlibrary1; 
- The intellisense works well.  
- Right-click the solution and add a second .net standard class library project -- Classlibrary2;
- Then rename "Program.cs" to "Program_Rename.cs";
- Rename Class1.cs in Classlibrary2 to Class2.cs;
- Then intellisense breaks in  Program_Rename.cs, Class1.cs and Class2.cs
 ![renameleadingtobreakintellisense](https://cloud.githubusercontent.com/assets/22901391/26099603/d16e1d72-3a5d-11e7-88b1-f86ef8026aa2.PNG)
Close solution and reopen, the intellisense will work well.

**Comment by davkean** [comment]
I assume you are running 15.3 preview?

Thanks this is a known bug.

**Comment by MiaomiaoHuangfu** [comment]
Thanks davkean. 
Test on d15prerel.26525.02.
OS: Window 10 x64.
If it's a known, I will close it.

**Comment by davkean** [comment]
This bug: https://github.com/dotnet/project-system/issues/2102
