### ISSUE TITLE
netcoreapp2.0 cannot reference netstandard2.0 in VS2017 preview

### ISSUE THREAD

**Issue by karelz** [dotnet/project-system#2192]
_From @danwalmsley on May 4, 2017 17:27_

If I build from command line it works.

But from latest vs2017 preview I get:
...project.... targets '.NETStandard,Version=v2.0'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v2.0'.

Is the a workaround for now?

_Copied from original issue: dotnet/coreclr#11391_

**Comment by karelz** [comment]
_From @watashiSHUN on May 4, 2017 18:46_

when you say you can build it on the command line, you mean you are using `dotnet cli`? ( in my case running `dotnet run`  with version `2.0.0-preview2-005905` on this project is successful)

But I also got a similar error while trying to build `.NetStandard2.0` in VS2017, please see this [stackoverflow question](http://stackoverflow.com/questions/43771446/netframework4-6-1-reference-a-classlib-targetting-netstandard2-0/43772580?noredirect=1#comment74595635_43772580)...

**Comment by karelz** [comment]
_From @danmosemsft on May 8, 2017 4:9_

@terrajobst is it expected to work in this version?

**Comment by karelz** [comment]
_From @terrajobst on May 8, 2017 18:6_

Which version of VS 2017 are you using? Help | About | Copy Info. This will work with the build we give out at Build.

**Comment by karelz** [comment]
BTW: It doesn't look like it belongs into CoreCLR repo ...

cc @weshaggard @ericstj

**Comment by karelz** [comment]
_From @NinoFloris on May 11, 2017 19:32_

It's the same for omnisharp

```
        Update project: Project
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Project '/Users/nfloris/Projects/Project/Project.csproj' targets '.NETStandard,Version=v2.0'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v2.0'.
``` 

it does compile, restore, test etc though

**Comment by karelz** [comment]
_From @ericstj on May 11, 2017 19:37_

Agree with @terrajobst, problem appears to be the VS setup.
Issues on project system should be filed in https://github.com/dotnet/project-system.

**Comment by karelz** [comment]
_From @NinoFloris on May 11, 2017 20:8_

Doesn't VS also use msbuild?

**Comment by karelz** [comment]
_From @karldodd on May 16, 2017 7:54_

Same problem for me here. I am using OmniSharp in VSCode.

I guess anyone in charge can move this issue to https://github.com/dotnet/project-system ?

**Comment by srivatsn** [comment]
This issue was moved to dotnet/sdk#1241
