### ISSUE TITLE
Closing VS now takes 10s of seconds while projects are "unloaded".

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#2211]
This seems unnecessary.  If VS is closing, why are we unloading anything?  It just adds unnecessary time while i have to wait for things to be torn down.  We should just bypass all this so that closing can be near-instant

**Comment by davkean** [comment]
Just to set expectations, while I think CPS is slower here than the legacy project system due it draining critical tasks (such as NuGet) on close, there was a change in RTM that now showed the ThreadAwait dialog on close - which makes it seem like it takes longer than it did in previous releases.

**Comment by CyrusNajmabadi** [comment]
> due it draining critical tasks (such as NuGet) on close

What "critical" tasks is it working on?    I get this even when VS has been up for minutes/hours.  So it's unclear why anything critical would not already be done by the time i want to close.

**Comment by CyrusNajmabadi** [comment]
I collected a perftrace for this: https://drive.google.com/file/d/0ByISdSEZ09PBOUhVU3Rxek5SSXc/view?usp=sharing

**Comment by davkean** [comment]
This appears to have been regressed even more by the dependency node, looks like we're blocking on Close on updating it, which we should definitely not be doing.

**Comment by davkean** [comment]
Note, we'll need to probably handle cancellation a lot better, it's not just a matter of avoiding registering the critical task for unload - we read catalog information, so if the project closes underneath us we'll be leaking ObjectDisposedException.

**Comment by MattGertz** [comment]
Mondo escrow triage: Potentially a regression, so keeping in 15.3.

**Comment by davkean** [comment]
@CyrusNajmabadi Note that CPS made a change here: https://mseng.visualstudio.com/VSIDEProj/_git/VSIDEProj.CPS/pullrequest/235754 to stop us from kicking off design-time builds that prolong the unload.

**Comment by CyrusNajmabadi** [comment]
Will that be put into 15.3?  This experience is pretty brutal.  I've taking to having to explicitly kill the msbuild instances to be able to actually close VS.

**Comment by davkean** [comment]
This was not put in 15.3, if you'd like to see it taken you'll need to ping Viktor Veis and Lifeng Lu.

**Comment by CyrusNajmabadi** [comment]
Ok.  Just pinged them.

**Comment by davkean** [comment]
Also see: https://github.com/dotnet/roslyn/issues/21429

**Comment by lifengl** [comment]
This should have been addressed (or mostly addressed) in 15.5 vsuml branch.  Can you check whether it is still a problem?

**Comment by Pilchie** [comment]
Telemetry shows that this is definitely not a widespread problem.  @CyrusNajmabadi are you still seeing it in 15.5/15.6?

**Comment by davkean** [comment]
When @CyrusNajmabadi was running into it - we were waiting for design-time builds to finish. We now cancel them/prevent them from running on unload.
