### ISSUE TITLE
VS no longer uses startup-project to prioritize project load.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#2212]
So if i load VS, and then say "ctrl-f5" to run, it says "cannot run class library".  It used to be that it would front load loading this guy first (presumably so i could get to 'debug' faster).  Now it seems to be some random order of project loads, with VisualStudioSetup.Next looking to be one of hte *last* projects that ever gets loaded.

**Comment by CyrusNajmabadi** [comment]
The whole "start vs, start debugging quickly" scenario seems to have majorly regressed.  See https://github.com/dotnet/roslyn/issues/19597 as well as an example.

**Comment by davkean** [comment]
Hmm, the startup project is stored in the solution, and we don't control the order in which we're loaded. Are you saying this regressed since Jared moved you to new project system?

**Comment by CyrusNajmabadi** [comment]
I don't know hte time it regressed unfortunately. I noticed it sometime last week and only now have filed it.  I've rolled back to/from several builds and whatnot.

**Comment by CyrusNajmabadi** [comment]
All i know is that i used to be able to open a project (from VS's quick launch bar) hit ctrl-f5 within a few seconds, and have that work 100% of the time.  Now it never works, and i need to wait minutes to be able to launch VS and attach to debug session.

**Comment by davkean** [comment]
Okay, I suspect the perf is probably the reason for this - but we'll take a look.

**Comment by CyrusNajmabadi** [comment]
Has htere been any movement on this?  it seems like VS doesn't even bother to kick off the build for many minutes.  When i look at taskman it looks like msbuild is just spinning there.  I'm guessing that the build isn't even being kicked off until all design time builds finish.  But this means having to wait many minutes after loading a project until you can even f5.

tagging @Pilchie @srivatsn

**Comment by davkean** [comment]
Okay so that's a different issue to the one that's described in the bug. What build are you on?

**Comment by CyrusNajmabadi** [comment]
i'm on 
![image](https://user-images.githubusercontent.com/4564579/28295494-c3b0ffc2-6b15-11e7-898b-b903fedaecbe.png)

**Comment by CyrusNajmabadi** [comment]
@srivatsn As per our conversation today.  Here's an example of how the new system just absolutely destroys productivity.  I used to be able to load VS and get to a debugging session is something like 30 seconds.  Now it's 3+ minutes.  I've attached a gif to show you how bad it is.  

![slowloads2](https://user-images.githubusercontent.com/4564579/28541591-6d53997e-706e-11e7-9aaa-6caf2bc69f1e.gif)

**Comment by CyrusNajmabadi** [comment]
Note that it takes VS *2 minutes* before it even starts building.

**Comment by davkean** [comment]
The perf is bad - and we need to dig into why it's taking longer.

That particular case where it takes ~2 minutes to start building under ASL is a solution bug, they wait for all projects to load before letting you F5, instead of just waiting for those startup projects and their dependencies . I raised this to @viktorveis - but there seemed to be very little interest in fixing this.

**Comment by davkean** [comment]
Note we're tracking performance elsewhere, I filed https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=489641&fullScreen=false&_a=edit to track the F5 loading all projects instead of just startup projects.
