### ISSUE TITLE
Red squiggles and missing references when working on Roslyn VB tests

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#2224]
Repro:
1. get latest Roslyn source from `master` branch
2. open `Compilers.sln`
3. open CompilationEmitTests.vb
4. see un-expected squiggles:

![image](https://cloud.githubusercontent.com/assets/12466233/26222402/ae5075e8-3bce-11e7-9760-6a1622fb633f.png)

![image](https://cloud.githubusercontent.com/assets/12466233/26222499/0db9c2aa-3bcf-11e7-8cb8-113ca3da7c39.png)

I used to have this problem about a year ago, when Roslyn was mostly using the legacy project system, but now I think those projects are using the new project system.

I'm happy to provide access to my machine if that helps the investigation.

**Comment by davkean** [comment]
@jcouv This should be fixed by https://github.com/dotnet/project-system/pull/2071.

What build are you running?

**Comment by jcouv** [comment]
Installed 15.3 and the problem is fixed. Thanks!
FYI @khyperia
