### ISSUE TITLE
Pass NuGet settings properties during nomination

### ISSUE THREAD

**Issue by emgarten** [dotnet/project-system#2225]
To allow setting fallback folders in the SDK restore nomination should send the following project properties:

* RestoreSources
* RestoreFallbackFolders
* RestorePackagesPath

More details on how restore is using these can be found here https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-settings-in-MSBuild

**Comment by natidea** [comment]
Fixed by https://github.com/dotnet/project-system/pull/2269
