### ISSUE TITLE
Determine what do with duplicate reference, analyzers and additional files

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2230]
We stopped sending duplicate references, analyzers, additional files and source files onto Roslyn to avoid crashes as a short term change. 

Instead, we should be warning/errors very similar to to what the compiler does for these situations.

**Comment by Pilchie** [comment]
Note also that we should be careful about references to the same file with different options/aliases, which might require work on the Roslyn side.

**Comment by Pilchie** [comment]
Note that we should also consider DPL/Lightweight solution load here.  See https://github.com/dotnet/roslyn/pull/19889 for a similar workaround.

**Comment by Pilchie** [comment]
For 15.7, when we change the interface with Roslyn, we should probably just let Roslyn deal with it the same way as the command line does.
