### ISSUE TITLE
NuGet restorer is running for shared projects

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2231]
NuGetRestorer should not be running in shared projects - this is causing us to hit this assert because the project has no configurations:

https://github.com/dotnet/project-system/issues/2217.

**Comment by davkean** [comment]
tag @natidea

**Comment by davkean** [comment]
This service should be marked for running with `PackageReferences` but given it's a project load service it should be made dynamic.

**Comment by srivatsn** [comment]
Why is this blocking partner - do you think this is causing the critical capabilities issue?

**Comment by davkean** [comment]
Because it's faulting the data flow.
Sent from my Windows 10 phone

**Comment by jmarolf** [comment]
This requires changes in CPS.  Moving to 15.6

**Comment by davkean** [comment]
Faulting the block only faults the consumer not the publisher, removing blocking partner.

**Comment by davkean** [comment]
The fix is in: https://github.com/dotnet/project-system/pull/3097.
