### ISSUE TITLE
Packages no longer show up under SDK node

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2233]
Build:Version 15.3.0-pre.1.0+26518.0.d15prerel

![image](https://cloud.githubusercontent.com/assets/1103906/26232268/5f75d858-3c98-11e7-854c-9695a8ea43fb.png)

**Comment by srivatsn** [comment]
Likely the same as https://github.com/dotnet/project-system/issues/2351 since the SDKs are basically packages as well and in the screenshot it's the NetCore.App package that's not expanded.

**Comment by natidea** [comment]
I don't see this builds with #2490 applied
