### ISSUE TITLE
Once you've saved a project via editor, all further changes after the first change are not sync'd

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2234]
I believe this is a regression.

1. File -> New Console App
2. Right-click -> Edit
3. In the editor, CTRL+S
4. Right-click on "Program.cs" in Solution Explorer - click Exclude

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Program.cs" />
  </ItemGroup>

</Project>

```
5. Right-click on "Program.cs" in Solution Explorer - click Include

**Expected:**

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

</Project>

```

**Actual:**

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Program.cs" />
  </ItemGroup>

</Project>
```

**Comment by srivatsn** [comment]
@jviau is this a regression from moving the editing code to CPS?

**Comment by jviau** [comment]
@srivatsn the editing code isn't in CPS yet. Just the reload code. Maybe the `CTRL-S` is getting the buffer out of sync with the file on disk. Maybe @333fred has some insight on this.

**Comment by srivatsn** [comment]
Ah yes ofcourse. Sorry about the needless ping. @tannergooding can you take a look?

**Comment by jviau** [comment]
That is alright. Something else I noticed is some weird behavior when the same project is open in multiple instances of VS and the project file is being edited in both. The editor label was rapidly switching between showing the locked icon and not showing it. Also I somehow managed to get the project to unload while it was still dirty in the msbuild project collection. Reloading the project failed until I restarted VS. No idea how I managed that and I can't repro it.

**Comment by davkean** [comment]
@jviau I've heard similar reports with regards to two VS's fighting each other, can you file a new bug describing the repo if you remember it and the behavior?

**Comment by tannergooding** [comment]
@Srivatsn, I was able to repro in the latest d15prerel build.

If you just open in edit view and don't save (no edits made), things work as expected.

If you do save (no edits made), than the subsequent include doesn't cause the editor to refresh (but the underlying csproj is updated appropriately).

A secondary save (no edits made) will cause the remove to happen again.

Excluding a different file will cause the editor to refresh and only show the remove for the new file (as expected)

**Comment by tannergooding** [comment]
@Srivatsn, this is not a regression from RTM.

**Comment by tannergooding** [comment]
@jviau, given that this only seems to happen on File Include (and excluding a separate file does cause the editor to update), I think this might be a bug with the Project Reload code.

Thoughts?

**Comment by davkean** [comment]
This no longer repros.
