### ISSUE TITLE
Current working directory for Net Core Console application is project directory

### ISSUE THREAD

**Issue by pi3k14** [dotnet/project-system#2239]
@davkean 
Regression? of [.NET Core console app default working directory is the source directory, not the bin directory](http://github.com/dotnet/project-system/issues/589)

Using Visual Studio Enterprise 2017, version 15.2 (26430.6), .NETCoreApp 1.1

Inserted
         `Directory.SetCurrentDirectory(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location));`
as first line in Main as workaround.

**Comment by davkean** [comment]
@BillHiebert Is there a reason we made working directory default to the project directory for non-web projects?

**Comment by srivatsn** [comment]
The rationale for the change was that consistency between VS and CLI for Net core projects was more important than consistency between desktop projects and netcore projects. See discussion - https://github.com/dotnet/cli/issues/4473#issuecomment-256502969

**Comment by pi3k14** [comment]
@srivatsn, what is the definition of project directory? And what is a desktop project?

**Comment by pi3k14** [comment]
@srivatsn, @davkean. I think the whole debacle is caused by a misunderstanding of this post **https://github.com/dotnet/cli/issues/4473#issuecomment-256531057**

"If RunWorkingDirectory comes back blank, VS will need to default the working directory during F5.", and this defaulting should of course be existing behavior of systems in production! Not the behavior of a beta product where there have been reported issued about this behavior.

**Comment by davkean** [comment]
I'm in agreement here - I don't think it's important to have to consistency between web and non-web, it's better to be consistent between what happens if you run with and without debugger, both inside and outside of VS.

**Comment by niwrA** [comment]
I came here to wonder about this very behavior, and agree.

**Comment by ManfredLange** [comment]
Not sure this is related: I added a postbuild event as a target to the project file to execute a command in a particular working directory. In this case the macro $(SolutionDir) is not set to the solution as I expected but set to the directory of the project which in turn is in a directory underneath the one that contains the solution file.

`<Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="dotnet &quot;$(TargetPath)&quot; /create-shared-assembly-info-file" WorkingDirectory="$(SolutionDir)"></Exec>
   </Target>`

**Comment by Pilchie** [comment]
@BillHiebert didn't we have another thread about this recently?  Do you know where to change this?

**Comment by BillHiebert** [comment]
@Pilchie - I just pushed this PR https://github.com/dotnet/project-system/pull/3073 which contains the fix for this issue.

**Comment by Pilchie** [comment]
Closing as fixed by #3073.
