### ISSUE TITLE
When referencing a desktop project from a netcoreapp project the project node appears with yellow triangle

### ISSUE THREAD

**Issue by ericstj** [dotnet/project-system#2242]
Steps to reproduce:
Create a new .NETCore 2.0 Application.
Add a .net 4.0 library to the solution.
Add a reference to the .net 4.0 library from the application.

Expect:
Reference behaves normally.

Actual:
Compile and run work fine, but the reference appears with a yellow triangle.  There is no indication in warning/error window, output, or property window of what the meaning of the yellow triangle is.  Right-clicking the reference only allows for properties.  Clicking the reference and deleting does nothing.  Only way to remove the reference is through unchecking in the add-ref dialog or editing the project file.
![image](https://cloud.githubusercontent.com/assets/8918108/26260857/cd0ae2ce-3c83-11e7-99d5-b233f36895c1.png)

**Comment by MattGertz** [comment]
Note relationship to #2257, which discusses providing text for warnings generally.  I am calling the difference as "have an erroneous warning" (15.3 for the moment) and "don't have enough info on the warning, but it's a legit warning" (which is post-15.3).  By second week of Escrow, this issue probably would not make the bar either.
