### ISSUE TITLE
.Net Core class library template actually creates .Net Standard class library

### ISSUE THREAD

**Issue by richaverma1** [dotnet/project-system#2247]
The template for .Net Core class library incorrectly creates a .Net Standard class library. This is on 15.3 internal preview

**Comment by jmarolf** [comment]
@richaverma1 what version of the SDK do you have installed?

**Comment by srivatsn** [comment]
This turned out to be an issue in the templating engine and fix is being prepared. Moving to the dotnet\templating repo

**Comment by srivatsn** [comment]
This issue was moved to dotnet/templating#856

**Comment by dmitry-pavlov** [comment]
While it is being fixed, the workaround is: 

Edit your new project and replace 
`    <TargetFramework>netstandard2.0</TargetFramework>`
with 
`    <TargetFramework>netcoreapp2.0</TargetFramework>`

**Comment by julielerman** [comment]
oh good to see this. I thought I had really missed another boat wrt differences between net standard and net core when I just created two different library projects in vs2017.3 preview to compare.
