### ISSUE TITLE
Non-informative warning icons in solution explorer

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#2257]
Something went wrong with a CPS-to-CPS p2p reference in my IDE:

![image](https://cloud.githubusercontent.com/assets/4564579/26328124/a1148538-3ef6-11e7-8167-d7dc9564fc6f.png)

However, there is no information that can be ascertained from these warning icons.  The only warnings i have are:

![image](https://cloud.githubusercontent.com/assets/4564579/26328170/c6443998-3ef6-11e7-9ca9-2e57b9de3e83.png)

**Comment by srivatsn** [comment]
@natidea mentioned that he saw a bug where the project reference was showing the error but the project wasn't. The analyzer warning issue is https://github.com/dotnet/project-system/issues/1634 and I think it's because of non-normalized paths being treated incorrectly by the dependencies node.

**Comment by srivatsn** [comment]
Try the repro from https://github.com/dotnet/project-system/issues/2261 as well.

**Comment by MattGertz** [comment]
Agreed, but post-15.6 at this point.

**Comment by davkean** [comment]
Here's another example:

Repro:

1. Clone and sync to https://github.com/rosieks/JavaScriptServices/commit/087183ea18ed563d03d35266af081a5adb24eca1
2. Open JavaScriptServices.sln
3. Expand WebPack

![image](https://cloud.githubusercontent.com/assets/1103906/26664982/97e737fe-46d9-11e7-8955-c6b46d7420ed.png)

It looks like the failed resolution of the "SDK" is affecting the NuGet node.

**Comment by abpiskunov** [comment]
@davkean  You found a separate issue actually: since sdk and packages are related, you are right that warning on Nuget group could be triggered by sdk. This is different from the original complain in current issue, when there no actual errors/warnings when any node has warning sign. I would open a separate issue to track your scenario..

**Comment by davkean** [comment]
I've filed https://github.com/dotnet/project-system/issues/2398 to track that last example.

**Comment by loop-evgeny** [comment]
It's especially confusing when the warning icon is on the Analyzers node, because that led me to believe the nodes under it represented warnings found in my code.

**Comment by drewnoakes** [comment]
This is quite a general issue, and a lot of stuff around this has been fixed recently. Without a repro to test against, I can't tell whether this is still happening.

We have some other issues to track the general case covered here. I suspect #5044 is the best fit here. Regarding the lack of information about the error itself we have #4357 and #3780. I'll close this. If someone has a repro that isn't covered by an existing issue, please file a new one.
