### ISSUE TITLE
vbcscompiler.exe should be launched at below normal priority 

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#2258]
Ported from: https://github.com/dotnet/roslyn/issues/11942

Right now when a build is invoked from VS this process is launched at normal priority and uses all the cores on the machine. This creates a lot of contention for CPU and causes noticeable slowdown in VS and other processes (chrome, for example).

I've set the process to be below-normal and have seen no serious impact on compilation speed. For Roslyn.sln speeds were within 2 seconds of normal. However, the impact on the rest of the system is enormous. VS no longer feels sluggish during build, other processes work great.

While it is great that our compiler scales up so well to the machine, i don't think it's great that it does so in a way that so greatly impacts the rest of the user experience. It's common to start a build and want to go do other things while that build happens. Setting the build to be lower priority makes that possible, with little impact to the experience, and with practically no downsides.

**Comment by CyrusNajmabadi** [comment]
@Pilchie Says i should port this bug here.  He feels like the project system is the right place to to set things up to invoke the compiler server at below normal pri.

Note: the current way we do things effectively makes my machine unusable when i build.  I cannot work with VS, nor can i use other processes well.  However, changing the pri of the compiler server does not seem to actually impact build times for me, while making my ssytem actually responsive and usable while building is happening.

Tagging @srivatsn @davkean

**Comment by davkean** [comment]
@Pilchie Not sure how why you think this belongs here? We don't launch the compiler server - it's launched by the build task. // @agocke

**Comment by davkean** [comment]
Or do you think that we should be driving this as part of design-time experience?

**Comment by srivatsn** [comment]
Closing since the discussion is continuing over at https://github.com/dotnet/roslyn/issues/11942 and the project system doesn't control this.
