### ISSUE TITLE
Start external program Browse button should browse to the path already entered.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2259]
Reported via [VS Feedback](https://developercommunity.visualstudio.com/content/problem/47289/start-external-program-browse-button-should-browse.html) 

-----

This has been an annoying quirk for many versions of VS and its mind boggling that it is something so very easy to fix.
When you are configuring the Debug options for a C# project, it would be very nice if when you click on the "Start external program:" Browse button it will browse to the path already entered rather then starting off in the installed IDE location of Visual Studio.
Currently I have to copy the path, hit the browse button, and then paste the path into the location bar first before navigating to a path relative to the current one.
If this is expected behavior, note that my current path contains relative path indicators "\..\", however it is 2017 and I think Windows should figure out how to resolve paths like this by now. Currently it always browses to the location of the IDE executable, which is fine if the path is empty, you got to start somewhere, but once a valid path is saved it should go back to this location always.
This is the standard behavior in other apps, including Microsoft apps, to browse to the path already entered, as long as its a valid path. Actually this is exactly how "Working Directory" browse button works.
I have a project that has multiple outputs generated and when debugging I often switch which location to start and debug so I do this fairly often and it woudl be excellent if this simple behavior quirk is fixed. I can't see anyone routinely setting up to run an external program from the VS IDE location constantly, and if this is the case, then have a dedicated shortcut button to go there specifcially, but otherwise Browse to the previously selected location in all cases where you have a path and a browse button presentation.

**Comment by jp2masa** [comment]
I was trying to fix this, but I have a question:
The current implementation only supports rooted paths. Supporting relative paths would mean that the stored path would be rooted, even if selecting the same file in the dialog. To fix this, it's possible to make the path relative to the project folder, but then all paths will be relative.
What is the intended behaviour for this property? Should it be a rooted or relative path?

**Comment by kajtoi** [comment]
In my case rooted path is much better. Relative might work but it would be ugly and difficult since the project and start exe are separated by several levels in my folder structure.

**Comment by adamint** [comment]
Expected behavior
