### ISSUE TITLE
Dependency node shows errors against packages/projects with zero actionable data

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2261]
1. Check out a9e5252cb89e45bc9c5202789bc7effc61b7531c.
2. Open DeployIntegrationDependencies

![image](https://cloud.githubusercontent.com/assets/1103906/26340457/c946247c-3fd1-11e7-85a1-a4bc63f56a23.png)

If I expand NuGet node, I get:

![image](https://cloud.githubusercontent.com/assets/1103906/26340495/0ae07c48-3fd2-11e7-8161-3aa84aabf616.png)

I have no idea what those warnings signs mean, I have the following:
```
Warning		Detected package downgrade: Microsoft.VisualStudio.LanguageServices from 2.3.0-beta2-61711-06 to 2.3.0-beta1-61703-10 
 Microsoft.VisualStudio.ProjectSystem.IntegrationTests (>= 1.0.0) -> Microsoft.VisualStudio.IntegrationTest.Utilities (>= 2.3.0-beta2-61711-06) -> Microsoft.VisualStudio.LanguageServices (>= 2.3.0-beta2-61711-06) 
 Microsoft.VisualStudio.ProjectSystem.IntegrationTests (>= 1.0.0) -> Microsoft.VisualStudio.LanguageServices (>= 2.3.0-beta1-61703-10)				
Warning		Detected package downgrade: Microsoft.VisualStudio.LanguageServices from 2.3.0-beta2-61711-06 to 2.3.0-beta1-61703-10 
 DeployIntegrationDependencies (>= 1.0.0) -> Microsoft.VisualStudio.IntegrationTest.Utilities (>= 2.3.0-beta2-61711-06) -> Microsoft.VisualStudio.LanguageServices (>= 2.3.0-beta2-61711-06) 
 DeployIntegrationDependencies (>= 1.0.0) -> Microsoft.VisualStudio.LanguageServices (>= 2.3.0-beta1-61703-10)				
```

Are these warnings related to the above warning symbols? No idea, there's zero mention of System.Reflection.Metadata in the downgrade warning.

**Comment by abpiskunov** [comment]
Why is it node bug? It just displays data it receives from sdk - target that reads assets json file...

Thanks,
Anton

On May 22, 2017, at 11:09 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  Check out a9e5252<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fproject-system%2Fcommit%2Fa9e5252cb89e45bc9c5202789bc7effc61b7531c&data=02%7C01%7Canton.piskunov%40microsoft.com%7Cf736f612c47b48987dfa08d4a1a247d4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636311165747939784&sdata=SnO0rvQG571foxumudUptIg9roEjZKBGUdYbxp434HI%3D&reserved=0>.
  2.  Open DeployIntegrationDependencies

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F1103906%2F26340457%2Fc946247c-3fd1-11e7-85a1-a4bc63f56a23.png&data=02%7C01%7Canton.piskunov%40microsoft.com%7Cf736f612c47b48987dfa08d4a1a247d4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636311165747949792&sdata=CsxTypZyROiCnWSwIZBpJZVhgLkgUVfy9R03%2BJEQ3vk%3D&reserved=0>

If I expand NuGet node, I get:

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F1103906%2F26340495%2F0ae07c48-3fd2-11e7-8161-3aa84aabf616.png&data=02%7C01%7Canton.piskunov%40microsoft.com%7Cf736f612c47b48987dfa08d4a1a247d4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636311165747949792&sdata=SFdLlos6u5V8usaWOk0ddzkOAqnELDtxr88lK6Ip1tc%3D&reserved=0>

I have no idea what those warnings signs mean, I have the following:

Warning         Detected package downgrade: Microsoft.VisualStudio.LanguageServices from 2.3.0-beta2-61711-06 to 2.3.0-beta1-61703-10
 Microsoft.VisualStudio.ProjectSystem.IntegrationTests (>= 1.0.0) -> Microsoft.VisualStudio.IntegrationTest.Utilities (>= 2.3.0-beta2-61711-06) -> Microsoft.VisualStudio.LanguageServices (>= 2.3.0-beta2-61711-06)
 Microsoft.VisualStudio.ProjectSystem.IntegrationTests (>= 1.0.0) -> Microsoft.VisualStudio.LanguageServices (>= 2.3.0-beta1-61703-10)
Warning         Detected package downgrade: Microsoft.VisualStudio.LanguageServices from 2.3.0-beta2-61711-06 to 2.3.0-beta1-61703-10
 DeployIntegrationDependencies (>= 1.0.0) -> Microsoft.VisualStudio.IntegrationTest.Utilities (>= 2.3.0-beta2-61711-06) -> Microsoft.VisualStudio.LanguageServices (>= 2.3.0-beta2-61711-06)
 DeployIntegrationDependencies (>= 1.0.0) -> Microsoft.VisualStudio.LanguageServices (>= 2.3.0-beta1-61703-10)


Are these warnings related to the above warning symbols? No idea, there's zero mention of System.Reflection.Metadata in the downgrade warning.

**Comment by davkean** [comment]
I have no idea how all this hooks up, I see warnings symbols all the time that come and go in the Dependency tree without an understanding of why. Regardless of where the bug lives we need to investigate, for team purposes, it's easier if we start in project system.

**Comment by davkean** [comment]
Regardless of what the underlying cause is here - we should avoid showing warning symbols without an actionable error or warning in the Error List or under the nodes themselves.

**Comment by abpiskunov** [comment]
Warning symbol logic is very straight forward, when a dependency is unresolved or has some unresolved dependencies or warnings, it is marked with warning icon. Then warning icon bubles up to dependency group and further to root dependencies node to indicate that there is some unresolved dependency if tree nodes are closed. Same logic was there for xproj in dev14.

Reason it appears and disappears, designtime builds. First build brings unresolved packages, then after assets file processed , resolved packages are sent and icons are updated. Since we still have restore happening everytime project opens this flicks happen more often.

Thanks,
Anton

On May 23, 2017, at 6:42 AM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


Regardless of what the underlying cause is here - we should avoid showing warning symbols without an actionable error or warning in the Error List or under the nodes themselves.

**Comment by srivatsn** [comment]
Tracking this with https://github.com/dotnet/project-system/issues/2257
