### ISSUE TITLE
Rename of file should listen to Language service Notification rather than workspace changes

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/project-system#228]

**Comment by tmeschter** [comment]
@jinujoseph Could you provide some background on what we should be listening to other than workspace changes? And why it matters?

**Comment by jinujoseph** [comment]
@davkean should be able to help you here, this bug was created before we wrote the language service. I believe the idea was language service will raise an event whenever the file is renamed, which you need to listen to rather than looking for workspace document change [here](https://github.com/dotnet/project-system/blob/3a2e5b710e66b3fb7df2d75aa58a66355912bb6a/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs#L41)

**Comment by davkean** [comment]
@tmeschter Right now the design of this is very different to the legacy project system and it's observable; we're listen to a rename event that CPS calls eventually on a background thread after the change has been made, then we hook up to workspace events waiting for the file to be added to the workspace, and which point then we prompt to rename. There is a noticable wait between renaming a file and getting the prompt - we need to rethink how this works so it feels much more natural at the point that you rename the file.

**Comment by tmeschter** [comment]
Blocked waiting for fixes on the CPS side. See #2852 for details.
