### ISSUE TITLE
Selecting the Application page on AppDesigner, show "PropPageDesignerRootComponent" in Properties window

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2284]
![image](https://cloud.githubusercontent.com/assets/1103906/26439339/0ee138ba-416b-11e7-95c3-d8905100d75f.png)

**Comment by tannergooding** [comment]
This repro's in 15.2.

**Comment by tannergooding** [comment]
Also repro's in 15.0

**Comment by tannergooding** [comment]
Also repro's in 14.0

**Comment by ghuntley** [comment]
Does not repro with 15.7.0 Preview 2.0

![2018-03-30_23-28-00](https://user-images.githubusercontent.com/127353/38137722-0749d9f4-3472-11e8-9bf0-68b167441384.gif)

**Comment by davkean** [comment]
Thanks! I close it out.
