### ISSUE TITLE
Not obvious that buttons are disabled in AppDesigner

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2287]
Since switching colors in the AppDesigner, there's not a lot enough contrast between enabled and disabled:

Which of these are enabled and which is disabled?
![image](https://cloud.githubusercontent.com/assets/1103906/26439492/b670e346-416b-11e7-83c1-2c3a795af035.png)

**Comment by davkean** [comment]
I really think we need to custom draw these, the Office ones do a good job of this:

Ours:
![image](https://cloud.githubusercontent.com/assets/1103906/26439546/02fe16d4-416c-11e7-99aa-49f242794fc2.png)

Office:

![image](https://cloud.githubusercontent.com/assets/1103906/26439566/2040c200-416c-11e7-8e3f-28e4c6d73acc.png)

Surely there's already someone doing this in VS.

**Comment by tannergooding** [comment]
@davkean, it doesn't look like office is custom drawing those, it just looks like they are using the 'flat' rendering style.

**Comment by davkean** [comment]
@tannergooding There is no flat rendering in Win32 and they aren't using WinForms, so I suspect they are custom drawing them.

**Comment by tannergooding** [comment]
@davkean, `Button_SetStyle` with the `BS_FLAT` value definitely works (it is only available on Vista and higher). Although I expect Office is using WPF and just setting the style property.

In either case, we are using WinForms in most cases (where flat style is available) and using WPF in the other cases (where setting flat style is trivial as well), so we should be able to do this without any custom rendering.

**Comment by davkean** [comment]
I'm going to close this - we backed out the change where the background of the pages were white.
