### ISSUE TITLE
Solution Explorer search is partially case insensitive

### ISSUE THREAD

**Issue by am11** [dotnet/project-system#2291]
Tested with VS2017 15.2.

Steps to repro:

In Library project, add a folder `Extensions` with a file `StringExtensions.cs` and define `CoreStringExtensions` class in it. In solution explorer, search for `stringextensions` (verbatim casing) to get the expected result:

![image](https://cloud.githubusercontent.com/assets/3840695/26448644/ee1aecca-4156-11e7-9488-fb0e525b17e9.png)

Then change search key to `Stringextensions` (verbatim casing; note lowercase `e`), to get "No results found":

![image](https://cloud.githubusercontent.com/assets/3840695/26448710/38849978-4157-11e7-87b1-b0106c398473.png)
 
If S and E both are upper case, it yields the result regardless of the casing of other characters.

**Comment by davkean** [comment]
We don't control the search in this repo, but I believe this behavior is behaving as designed. I was also surprised by this behavior and raised when the feature was first added.

The algorithm is like so; if the entered search string contains no uppercase characters, treat this as a case-_insensitive_ search. If it contains any uppercase characters, treat this as a case-_sensitive_ search. Hence the behavior you are seeing.

**Comment by srivatsn** [comment]
Closing this out as external.

**Comment by davkean** [comment]
@jibal Can you use **Help** -> **Send Feedback** -> **Report a Problem** and provide feedback on this? Thanks!

**Comment by Pilchie** [comment]
Inside Visual Studio, the Help menu has a Send Feedback item.

**Comment by jibal** [comment]
Not all versions.
