### ISSUE TITLE
How can I disable transitive project reference in new csproj format?

### ISSUE THREAD

**Issue by ufcpp** [dotnet/project-system#2313]
## Repro steps

Version used: Visual Studio 2017 (15.2 (26430.6)) Release

Create projects as follows:

![image](https://cloud.githubusercontent.com/assets/3760955/26540900/8c04d66e-448e-11e7-97a4-ea22a5be8254.png)

Sample Projects: [NewCsproj.zip](https://github.com/dotnet/project-system/files/1035158/NewCsproj.zip)

## Expected behavior

Successfully compiled and show `"BBBB"`.

## Actual behavior

Compilation error:

```
5>C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(94,5): error : Cannot find project info for 'c:\users\***\documents\visual studio 2017\Projects\NewCsprojWeb\ClassLibraryA\ClassLibraryA.csproj'. This can indicate a missing project reference.
```

**Comment by srivatsn** [comment]
In your ClassLibraryDependingOnA, you can add PrivateAssets=All to the ProjectReference to ClassLibraryA like this:

```xml
  <ItemGroup>
    <ProjectReference Include="..\ClassLibraryA\ClassLibraryA.csproj" PrivateAssets="All" />
  </ItemGroup>
```

This will stop the flow of ClassLibraryA further up the graph.
