### ISSUE TITLE
Consider a design for NuGetRestorer to avoid having to synclink on configured projects

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2324]
See https://github.com/dotnet/project-system/pull/2298#pullrequestreview-40441260 for a proposal from @jviau

**Comment by jviau** [comment]
This would require creating your own "buffer" block that each configuration feeds into, and then the buffer block chooses when configurations are in sync and publishes the unified values to the next block. That block then calculates the nuget restore info and sends to nuget.

Choosing when configurations are all in sync is the toughest part. @lifengl has some ideas on it.

**Comment by lifengl** [comment]
Yeah, discussed with Jacob, our idea is that you have your own dataflow block to align data from configurations (which can be done with Jacob's suggestion.), it basically holds the latest data from each configuration, and if data from all active configurations are aligned, you push to the next step.  It is kind of SyncLinkTo, but with your own implementation.

To align the data from configurations, I think you can depend on a simple logic. When you receive a newer version data from one configured project, get the latest set data from active configurations.  There, you can check each of the configurationProjectVersion with the current version of those ConfiguredProject (the live version data), if any snapshot version falls behind, you should wait, until all of them are up to date. (I guess you need do that inside a read lock, so version number won't change. or check once out side of the lock, and again inside the lock (to reduce the chance of getting lock unnecessary).

The logic behind this is that:
1, you only need restore NuGet for the latest state of the project, if the project is keeping changing, no need to do anything until things are settled down.

2, when a project is changed, it must be changed inside a write lock, and configured project version will be increased inside the same lock. If all configured project version of snapshots are up to date, they must be aligned correctly.

3, if a configured project snapshot falls behind, there must be some on-going dataflow processing and you will eventually receive up to date snapshot, so it should be safe to wait.  there might be one exception:  if some configurations are removed, you might not receive new data from it anymore, so maybe your block need refresh the state, when that happens.
