### ISSUE TITLE
MSBuild variables from launchSettings.json un-expanded in settings UI

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#2326]
I added `launchSettings.json` to `CSharpCompilerSymbolTest` project in Rolsyn:
```js
{
  "profiles":
  {
    "CSharpCompilerSymbolTest":
    {
      "commandName": "Executable",
      "executablePath": "$(XUnitPath)",
      "commandLineArgs": "$(XUnitArguments)"
    }
  }
}
```

The project settings page shows the information, and F5 seems to work:
![image](https://cloud.githubusercontent.com/assets/12466233/26603474/cecf6ef2-453b-11e7-865d-c160bd507844.png)

But the msbuild variables are un-expanded. I'm not sure if that is by-design.
The same settings in the old project system showed expanded msbuild variables:

![image](https://cloud.githubusercontent.com/assets/12466233/26603528/f7ed08ee-453b-11e7-84d3-ed09f9b22521.png)

FYI @srivatsn

**Comment by davkean** [comment]
This is somewhat intentional at the moment. We're going to revisit the whole evaluation vs unevaluated in the properties pages rewrite - we'll tackle it then.
