### ISSUE TITLE
Analyzer node shows satellite resource assemblies

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/project-system#2338]
With VS 2017 15.3 preview 1 -- 

I also noticed a UI bug with analyzers that have satellite resources:
You can see that it’s showing the resource assemblies when it shouldn’t be.
![1](https://cloud.githubusercontent.com/assets/1427284/26641161/ae3de0a8-45f7-11e7-87f2-7df2210354c3.png)

**Comment by srivatsn** [comment]
The dependencies node shows all dlls being passed to the compiler as /analyzer. Unfortunately the compiler doesn't distinguish between an analyzer and a dll that's just a dependency of an analyzer and there's no metadata to mark it as such. Solution explorer could probably only show dll that actually have rules in them - that might get rid of these and other helper dlls showing up in the node.

**Comment by tmeschter** [comment]
I see two options for fixing this, both of which involve updating the code that populates the Dependencies node.

1. When adding an analyzer node, crack the .dll ourselves and look for diagnostics using System.Reflection.Metadata or some such. If we don't find any we still create the node, but we make it invisible.
2. Implement a service on the Roslyn side that can tell consumers whether or not a DLL has any diagnostics in it, and query that.

I favor option 1 as the most straightforward.

**Comment by tmeschter** [comment]
Related to #2724. This will probably both be resolved with the same code change.

**Comment by tmeschter** [comment]
Moving out to 15.6. This no longer meets the bar for 15.5.

**Comment by drewnoakes** [comment]
Closing as this no longer repros (see #2724).
