### ISSUE TITLE
Sequence contains more than one matching element

### ISSUE THREAD

**Issue by rosieks** [dotnet/project-system#2340]
Hi,
I'm trying to open solution from this repository: https://github.com/rosieks/JavaScriptServices. Unfortunatelly I have error like in attached file
[VsProjectFault_e4637ef7-cd34-42be-b51f-b736ee4f9c10.failure.txt](https://github.com/dotnet/project-system/files/1042301/VsProjectFault_e4637ef7-cd34-42be-b51f-b736ee4f9c10.failure.txt)

I've installed VS2017.3 and .NET core 2.0 preview-1. Do you know how can I fix it?

**Comment by srivatsn** [comment]
This has been fixed. See https://github.com/dotnet/roslyn/issues/19405
