### ISSUE TITLE
View Windows Setting button in VB .NET Core app page adds an extra backslash to the project file

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2344]
Reported on [VSFeedback](https://developercommunity.visualstudio.com/content/problem/59853/could-not-find-a-part-of-the-path-cmy-projectappma.html)

I've an issue in Visual Studio 15.3 Preview, VB.net Core Console App. When I open the project properties and click "View Windows Settings" button. A default app.manifest file created and loaded for editing, as usual. The project was not rebuilt after reloading. The error was: Error BC31192 Unable to open Win32 manifest file 'C:\My Project\app.manifest' : Could not find a part of the path 'C:\My Project\app.manifest'. After a small investigation, I found that app.manifest file path is added to vbproj file with a `\` prefix. So VS is searching app.manifest file in root folder of the drive. When I deleted `\` from the vbproj, everything is back to normal. I tried these repro steps twice, and problem occured again.

**Comment by ocallesp** [comment]
Does not repro in old/new project system.
