### ISSUE TITLE
DependsOn and similar Before/After targets don't work

### ISSUE THREAD

**Issue by MikhailArkhipov** [dotnet/project-system#2348]
Target overrides don’t work in .NET Core projects. It looks like there is no place in the .NET core project file to place target overrides, i.e. there is no `<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />` line after which we could place the ‘DependsOn’… etc. 

2017 15.2.2

1. Create regular desktop class library project
2. At the end of the project file after `<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />` add
```
  <Target Name="BeforeCompile">
    <Message Importance="high" Text="Test target called"/>
  </Target>
```
3. Build
4. Observer message produced
5. Create .Net Core class library project
6. At the end of the project file add same target as above
7. Build
8. Observe message NOT produced

**Comment by srivatsn** [comment]
The form 
```xml
<Project Sdk="Microsoft.NET.Sdk">
....
</Project>
```

gets expanded to:

```xml
<Project>
   <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk">
...
   <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk">
</Project>
```
So you can your BeforeCompile target to the end if you use the long form.

**Comment by davkean** [comment]
Or even simpler, just:

``` XML
  <Target Name="DoSomethingBeforeCompile" AfterTargets="BeforeCompile">
    <Message Importance="high" Text="Test target called"/>
  </Target>
```

**Comment by MikhailArkhipov** [comment]
Thanks. I'll try this. The problem is that I can't change names of targets, they are external lab localization and signing tasks. I.e. like this

```
  <ItemGroup>
    <FilesToLocalize Include="$(OutputPath)\$(AssemblyName).dll">
      <TranslationFile>$(SourceDirectory)..\loc\lcl\{Lang}\$(AssemblyName).dll.lcl</TranslationFile>
      <SettingsFile>$(LSBuildRoot)\MCP_excludeBaml.lss</SettingsFile>
    </FilesToLocalize>
    <SignFilesDependsOn Include="GatherLocalizedOutputsForSigning">
      <InProject>false</InProject>
    </SignFilesDependsOn>
  </ItemGroup>
```

**Comment by MikhailArkhipov** [comment]
Looks like in .NET Core projects `*.nuget.targets` are not imported and hence none of the microbuild props or targets imported and that explains why MB targets are not called and project neither get signed nor localized. .NET Core sets

    <SkipImportNuGetProps>true</SkipImportNuGetProps>
    <SkipImportNuGetBuildTargets>true</SkipImportNuGetBuildTargets>

Which lead to skipping imports of *assembly*.nuget.props/targets. **Why?**. We reference build system via nuget...

I tried setting them to true but when running `Msbuild project.csproj /pp` I see that import entry is somehow commented out… Left is regular project, right is .NET Core

![image](https://user-images.githubusercontent.com/12820357/26891958-a74898dc-4b6b-11e7-8603-bf1f899bbbf3.png)

**Comment by davkean** [comment]
Where do you see those properties being set? I suspect you're actually running into: https://github.com/NuGet/Home/issues/5300

**Comment by MikhailArkhipov** [comment]
I think the problem is in how build moves and places files depending on target framework. I managed to get simple project signed with default out paths.  I am going to close this one - thanks for pointers.
