### ISSUE TITLE
If the TRACEDESIGNTIME env variable is set we should produce design time builds in the same place

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2357]
The old PS logs dt build logs in a certain place - we should respect that env var as well so that for mixed project solutions, there's one way to get the logs.

**Comment by davkean** [comment]
We run design-time builds differently to legact project system, we group targets where possible - so unlike it we wouldn't be able to include the targets in the name of the file.

**Comment by davkean** [comment]
We should consider https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools as the one place that we produce design-time build logs, and close this. //cc @panopticoncentral
