### ISSUE TITLE
Every F5 shows a project out of date prompt

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/project-system#2358]
1. New asp.net core web application
2. F5

You see this dialog.
![image](https://cloud.githubusercontent.com/assets/1553785/26692347/2d7ea286-46b5-11e7-8c7c-6a175ebc18bc.png)

I investigated and enabling support for the update to date check triggers the solution build manager to display this message. However there is a way for projects to opt out of it by implementing the following hierarchy property VSHPROPID_SuppressOutOfDateMessageOnBuild. Support for this property is already in CPS and controlled by  setting the msbuild property SuppressOutOfDateMessageOnBuild to true

**Comment by srivatsn** [comment]
Fixed by #2375
