### ISSUE TITLE
Pass project additional source/fallback folder properties during nomination

### ISSUE THREAD

**Issue by emgarten** [dotnet/project-system#2360]
Nomination should pass these additional project properties:

* RestoreAdditionalProjectSources
* RestoreAdditionalProjectFallbackFolders

These will be used to pass source and fallback folders from the SDK to restore.
https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-settings-in-MSBuild

**Comment by srivatsn** [comment]
@natidea - this is needed for fallback folders - can you please get to this soon?
