### ISSUE TITLE
Fastuptodate should check analyzers, rulesets and editorconfigs

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2374]
A build should happen after changing :

- [x] analyzers (#6015)
- [ ] ruleset files
- [x] .editorconfig files (https://github.com/dotnet/project-system/pull/4883)

**Comment by panopticoncentral** [comment]
We already do track analyzer references.

**Comment by panopticoncentral** [comment]
Rulesets also are tracked as None input items.

**Comment by panopticoncentral** [comment]
And how do editorconfig file affect the build? Don't just they affect the editor defaults? I don't see them show up anywhere in project files.

**Comment by srivatsn** [comment]
Rulesets are not none items - they are specified by a codeanalysisruleset property. @jmarolf how are editorconfigs represented in the project?

**Comment by panopticoncentral** [comment]
Never mind about the ruleset, I got confused by the test scenario I was looking at.
In terms of editorconfig, though, regardless of whether they're represented in the project, how can they affect compilation? I thought they were just editor defaults and aren't part of compilation per-se.

**Comment by srivatsn** [comment]
There's work being done (not sure of the current state - @jasonmalinowski ?) to pass editorconfig to the compiler so that editorconfig can affect commandline build

**Comment by sharwell** [comment]
The ability to pass .editorconfig files to the compiler layer is targeted to 15.6. It's well underway but not yet completed. At that point they will be similar to rule set files in their ability to change the impact of analyzers on the build.

**Comment by davkean** [comment]
Except that worse thing (looking at the last design I saw) is that .editorconfig's don't appear as items in the project. Not sure how we're supposed to be aware of them.

**Comment by panopticoncentral** [comment]
@srivatsn Is code analysis working in .NET Core projects? I see #988 about the fact that the UI doesn't work, but when I set a CodeAnalysisRuleSet and turn on code analysis, I get a build error that the platform can't be identified. Wanted to make sure I wasn't doing something wrong, as would need to test this, obviously...

**Comment by srivatsn** [comment]
FxCop doesn't work but ruleset files affect roslyn analyzers too which works for netcore.

**Comment by panopticoncentral** [comment]
Original fix cause regressions, see referenced PRs

**Comment by Pilchie** [comment]
`.editorconfig` is not in Roslyn yet, and ruleset modifications are rare enough that we can live with this for 15.6

**Comment by panopticoncentral** [comment]
@drewnoakes I don't think I'm going to get to look at this soon. Is this something you could look at?

**Comment by drewnoakes** [comment]
Sure, I'll pick it up.
