### ISSUE TITLE
[Regression] Visual Studio becomes unusable while building if you build with diagnostic results turned on

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2379]
Affected Build: Version 15.3.0-pre.1.0+26525.3003.d15prerel

Steps to reproduce:

1. Clone http://github.com/dotnet/project-system
2. Open src\ProjectSystem.sln
3. Tools -> Options -> Project and Solutions -> Build and Run -> MSBuild output verbosity -> Diagnostic
4. Open Output tool window
5. Open a source file
6. Right-click on Solution and choose Build
7. Attempt to scroll editor

Expected: Visual Studio to remain responsive
Actual: Visual Studio is unusable while it's logging. 

This was moved from: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/443365.

**Comment by davkean** [comment]
According to that internal VS bug, this is caused by two issues:

1) https://github.com/dotnet/project-system/issues/1342 (PR in review: https://github.com/dotnet/project-system/pull/2317)
2) https://github.com/dotnet/project-system/pull/2010/files#diff-2bba9bfbf3f10d84252aaf1cad7e3e1dR278

The later was introduced in 15.3.

Note, this will cause general UI blocks and is probably the cause of the non-GC UI blocks in https://github.com/dotnet/project-system/issues/2297.

**Comment by davkean** [comment]
@abpiskunov Any reason why https://github.com/dotnet/project-system/pull/2010/files#diff-2bba9bfbf3f10d84252aaf1cad7e3e1dR278 is wrapped in a sync block?

**Comment by abpiskunov** [comment]
@davkean  if you meant lock (_snapshotLock), it is needed to synchronize snapshot updates, since this event handler could be called multiple times after DT builds for any rule. This ensures snapshot is always uptodate and contains all changes across rules.

**Comment by davkean** [comment]
@abpiskunov No I mean this block:

``` C#
            CommonServices.ThreadingService.JoinableTaskFactory.Run(async () =>
            {
                projectItemSpecs = await ProjectXmlAccessor.GetProjectItems().ConfigureAwait(false);
            });
```

But I figured it out - I was confused because the method that contains it called "Async" but isn't actually an async method.

**Comment by davkean** [comment]
This one is quite tricky - as plumbing through async changes a public API.

**Comment by davkean** [comment]
I'm going to see if I rewrite that line above to use snapshot data if possible - which seems like it should be the correct fix anyway as the live project can be out-of-sync with the snapshot.

**Comment by abpiskunov** [comment]
Ah , i see, yes i was going to make it async and forgot to rename later..  sounds good, i saw your changes and discussions with Andrew and Lifeng today, thanks for investigating all those hangs! I always had impression that threading service would do right things when we wrap with synchronous Run, and cps wiki even had samples .. but this JTF stuff  turns out to be much more complex..

**Comment by davkean** [comment]
Looks like we're not sending snapshot data when our referenced projects themselves change - so need to figure something else out...

**Comment by abpiskunov** [comment]
we do, ProjectRuleHandler monitors changes in dependent projects and sends DependenciesChanged event which ends up in this method also: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs#L101

**Comment by davkean** [comment]
We're not sending "project snapshot" data, ie See this null: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs#L159.

**Comment by abpiskunov** [comment]
Ah yes CPS versions snapshot we are not. It would be hard to keep versions in sync, we were trying it with Lifeng in rtm, and without cps changes it would hard, we decided to send null for now.

Thanks,
Anton

On Jun 7, 2017, at 3:56 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


We're not sending "project snapshot" data, ie See this null: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/ProjectRuleHandler.cs#L159<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fproject-system%2Fblob%2Fmaster%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.Managed.VS%2FProjectSystem%2FVS%2FTree%2FDependencies%2FSubscriptions%2FProjectRuleHandler.cs%23L159&data=02%7C01%7Canton.piskunov%40microsoft.com%7Ced5fbbd364b2465bc1c908d4adf865bd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636324729750497287&sdata=Sx4Z80JhFgA4pcEWB7qnJS%2B%2B126wps5gB9nf7Io4HSs%3D&reserved=0>.
