### ISSUE TITLE
Warning icons shows on NuGet node even though SDK has the issue

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2398]
Repro:

1. Clone and sync to https://github.com/rosieks/JavaScriptServices/commit/087183ea18ed563d03d35266af081a5adb24eca1
2. Open JavaScriptServices.sln
3. Expand WebPack

![image](https://cloud.githubusercontent.com/assets/1103906/26664982/97e737fe-46d9-11e7-8955-c6b46d7420ed.png)

It looks like the failed resolution of the "SDK" is affecting the NuGet node.

**Comment by drewnoakes** [comment]
Does not reproduce any more:

![image](https://user-images.githubusercontent.com/350947/60181266-2fa56c80-9865-11e9-9330-dc6ad19853ae.png)

I put in a fix a while back that prohibited adding a warning icon to a parent if its unresolved children were invisible. That likely fixed this. In that case, the SDK package would have been unresolved.
