### ISSUE TITLE
Get FileNotFoundException when create App.config file in .NET Core Console App Project

### ISSUE THREAD

**Issue by JoyceLiang** [dotnet/project-system#2402]
My code call Microsoft.VisualStudio.Editors.WCF.Configuration.VSApplicationConfiguration.QueryEditConfiguration() to get/generate config file for current project. In .NET Core Console App, I expected App.config be created after that, but get a FileNotFoundException.

I also found below project types have same problem
- Class Library (.NET Core)
- Unit Test Project (.NET Core)
- xUnit Test Project (.NET Core)
- ASP .NET Core Web Application (.NET Core) with template "Empty"
- Class Library (.NET standard)
- ASP.NET Core Web Application (.NET Framework) with template "Empty"

For UWP project, the conifg file app.config can be created successfully.

My VS version is 15.3 26604.2 d15prerel.

=================================================
System.IO.FileNotFoundException: 'The system cannot find the file specified. (Exception from HRESULT: 0x80070002)'

        Microsoft.VisualStudio.ProjectSystem.Managed.VS.dll!Microsoft.VisualStudio.ProjectSystem.VS.CreateFileFromTemplateService.CreateFileAsync(string templateFile, string parentDocumentMoniker, string fileName)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()	Unknown
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()	Unknown
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()	Unknown
 	Microsoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(System.Func<System.Threading.Tasks.Task> asyncAction)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke.AnonymousMethod__0()	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.dll!Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke.AnonymousMethod__0()	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.dll!Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(System.Func<Microsoft.VisualStudio.ProjectSystem.VS.HResult> action, System.IServiceProvider vsShellServiceProvider, Microsoft.VisualStudio.ProjectSystem.IProjectFaultHandlerService projectFaultHandlerService, Microsoft.VisualStudio.ProjectSystem.UnconfiguredProject project)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke(System.Func<System.Threading.Tasks.Task> asyncAction, bool registerProjectFaultHandlerService)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.GetFile(int fileId, uint flags, out uint itemidParam, out string fileNameParam)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNodeWrapper.GetFile(int fileID, uint grfFlags, out uint pitemid, out string pbstrFilename)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Editors.WCF.dll!Microsoft.VisualStudio.Editors.WCF.Configuration.ProjectConfigurationFile.EnsureExists()	Unknown
 	Microsoft.VisualStudio.Editors.WCF.dll!Microsoft.VisualStudio.Editors.WCF.Configuration.VSApplicationConfiguration.QueryEditConfiguration()	Unknown

>	Microsoft.VisualStudio.ConnectedServices.Package2.dll!Microsoft.VisualStudio.ConnectedServices.ConfigHelpers.EditableXmlConfigImplementation.EditableXmlConfigImplementation(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy projectHierarchy) Line 35	C#

**Comment by davkean** [comment]
I suspect our AppConfigFileSpecialFileProvider implementation is pointing to a template that doesn't exist. What's the expectation for an app.config in a .NET Core app given these aren't used?

**Comment by JoyceLiang** [comment]
My feature want to write a "connection string" (a set of key-value pairs to connect to Azure Storage Service) to the app.config file. I can add a config file through Project -> add item -> visual c# items ->general -> Application Configuration File, is this the template?

**Comment by AArnott** [comment]
> I suspect our AppConfigFileSpecialFileProvider implementation is pointing to a template that doesn't exist.

@davkean Given the item template is evidently present and yet the API still fails, it looks like the problem may be something else in the project system support for this API.

> What's the expectation for an app.config in a .NET Core app given these aren't used?

@davkean are you saying that the app.config file is completely ignored by .NET Core and therefore ASP.NET Core (.NET Core) projects store connection strings somewhere else? If so, can you please provide a link to docs so we can update our Connected Service handler to add the more appropriate code to these projects?

**Comment by AArnott** [comment]
@JoyceLiang  and I confirmed that ASP.NET Core 2 (whether on .NET Framework or .NET Core) ignores web.config at runtime. But appsettings.json seems to work for connection strings for both of these cases.
So we need an API that will create such a file if it does not exist, and return some kind of a handle to it.

Should that API be `Microsoft.VisualStudio.Editors.WCF.Configuration.VSApplicationConfiguration.QueryEditConfiguration` or something else? 

On our side, once we have the API that works, we can update our Connected Service handler to insert the appropriate JSON and insert different C# code if necessary for retrieving the string at runtime.

Also curious: I think some of these config values like ConnectionStrings which may contain secrets are supposed to move into a secrets.json file or something like that. Should we be using that from our Connected Service handlers? @acangialosi do you know? I don't see any 'secrets' item template in ASP.NET Core projects today.

**Comment by davkean** [comment]
@AArnott I'm not the best person to answer questions about which files are used or what not, but will happily write a new special file handler if that's what we decide needs to happen.

**Comment by AArnott** [comment]
@BillHiebert is this your area of expertise since it's primarily ASP.NET related?

**Comment by acangialosi** [comment]
If there is an api that allows us to put this into the secrets.json for that project we should send it there.

**Comment by AArnott** [comment]
@davkean Yes for the .NET Core 2.0 console app scenario, an app.config file seems to be supported, but programmatically cannot be created. If it's a special file handler that's missing that would fix this, can you please write it?

**Comment by davkean** [comment]
We have an AppConfig special files handler - it just seems to be fail when we attempt to install the template. I'll use this bug to track that.

**Comment by katemaroney** [comment]
Along the lines of what @AArnott mentioned above, I need to be able to write connection strings to appsetting.json to be able to handle adding Azure Storage to ASP.NET Core Web Application projects with template Empty. Will this be fixed for 15.5?

**Comment by davkean** [comment]
This bug is tracking app.config. Appsettings.json should be tracked by a new bug - it's more work as we'll need to add the new special file flag.

**Comment by jjmew** [comment]
It is been 2 years and they have worked around it
