### ISSUE TITLE
Reference Manager doesn't list references on "Projects" tab

### ISSUE THREAD

**Issue by rchande** [dotnet/project-system#2405]
Create a solution with 2 .NET Framework projects. Use "Add Reference" on one of the projects in an attempt to add a P2P ref to the other one. Click on the "Projects" tab of Reference Manager.

Expected:
Projects are listed
Actual:
No projects are listed. You have to click on the "Solution" submenu to see projects

![image](https://user-images.githubusercontent.com/3751401/26937059-32165918-4c25-11e7-8dc2-79b81a0ffc98.png)

**Comment by rchande** [comment]
cc @tannergooding

**Comment by rchande** [comment]
This is on 26602.0.d15rel

**Comment by tannergooding** [comment]
Confirmed that this does not repro on 15.2

**Comment by davkean** [comment]
This looks like a regression in the dialog itself - it doesn't seem to be selecting the first category under the tab, I open a normal .NET Framework project with the legacy project system, I see:

![image](https://user-images.githubusercontent.com/1103906/26964336-5ceb0386-4d34-11e7-918a-2d2400e10481.png)

I betcha this was regressed as part of the accessibility push to give the tabs focus.

**Comment by davkean** [comment]
Opened: https://devdiv.visualstudio.com/DevDiv/_workitems?id=448286&fullScreen=false&_a=edit.
