### ISSUE TITLE
Weird behavior in "Imported namespaces" selector

### ISSUE THREAD

**Issue by rchande** [dotnet/project-system#2406]
Create a new VB console app, go to project properties -> references. Attempt to deselect some of the automatically imported namespaces.  A number of strange things can happen:
1. it takes multiple clicks on a checkbox to deselect it
2. if you repeatedly click on one checkbox, other checkboxes in the control will start deselecting (!)

This is on 26602.0.d15rel

**Comment by rchande** [comment]
cc @tannergooding

**Comment by tannergooding** [comment]
Confirmed that this does repro on 15.2

**Comment by srivatsn** [comment]
Dupe of https://github.com/dotnet/project-system/issues/1326
