### ISSUE TITLE
Add UI for WarningsNotAsErrors

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/project-system#2409]
WarningsNotAsErrors is a really useful compiler option, but isn't exposed in project UI. Would be nice to make available from UI.

Current UI:
![image](https://user-images.githubusercontent.com/2696087/26954426-c9d32fa8-4c64-11e7-9298-b81cb42fc52c.png)

csproj
```xml
<PropertyGroup>
   <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
   <WarningsNotAsErrors>$(WarningsNotAsErrors);xUnit1004;0618</WarningsNotAsErrors>
</PropertyGroup>
```

**Comment by anangaur** [comment]
This could be an option "All except <Textbox>" under "Treat warnings as errors"

**Comment by drewnoakes** [comment]
Addressed for the new property pages in https://github.com/dotnet/project-system/pull/6971. This does not meet the bar for the legacy property pages.
