### ISSUE TITLE
Re-enable CA1825 when we move to a new Dev15 build.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#241]
The rule is turned off in the ruleset because the IOperation tree is different from what the analyzer expects.

**Comment by srivatsn** [comment]
Turned off all analyzers in #2043. @mavasani let me know once you have new analyzers packages and i'll update to that and reenable.

**Comment by mavasani** [comment]
I presume you need analyzer packages built against Microsoft.CodeAnalysis 2.3.* ?

**Comment by srivatsn** [comment]
Yes so that latest 15.3 builds don't throw errors -so packages with all the breaking changes fixed.

**Comment by Pilchie** [comment]
@jmarolf @tannergooding you guys recently enabled some analyzers.  Was this one of them?  @mavasani are you tracking re-enabling analyzers here like you did with roslyn?

**Comment by mavasani** [comment]
>  @mavasani are you tracking re-enabling analyzers here like you did with roslyn

I have tracking these only for roslyn and roslyn-analyzers, but can do so for this repo as well. @jinujoseph - we probably want to wait for newer Roslyn signed build with all our latest IOperation API changes, move analyzers repo forward to consume these APIs and use this newer analyzer package in all our repos.
