### ISSUE TITLE
Broken up-to-date check with linked files that change name

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/project-system#2413]
This is in the old project system, but probably worth checking the new project system as well.

1. Create a new C# console app
2. Outside the project directory create a file called test.txt
3. Add this code to the .csproj:
```
  <ItemGroup>
    <None Include="..\test.txt">
      <Link>Subfolder\ChangedName.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

Keep rebuilding the project. It rebuilds every time with this message:
```
1>Project 'ConsoleApp5' is not up to date. Copy to output file 'C:\Users\kirillo\Documents\Visual Studio 2017\Projects\ConsoleApp5\ConsoleApp5\bin\Debug\Subfolder\test.txt' missing from output location.
```

This is because it tries to find `test.txt` in the output, and doesn't take into account that the Link metadata effectively renames the file.

**Comment by KirillOsenkov** [comment]
It would be nice if there is a known workaround because this badly breaks build incrementality for our solution.

/cc @panopticoncentral

**Comment by iskiselev** [comment]
It s broken in new project system the same way.

**Comment by panopticoncentral** [comment]
The above PR fixes this in the new project system, I opened a work item in the old project system's work item database to track fixing the old project system.
