### ISSUE TITLE
Extreme contention in OnceInitializedOnceDisposed.EnsureInitialized(bool)

### ISSUE THREAD

**Issue by sharwell** [dotnet/project-system#2421]
During a profiling pass on a solution load of Roslyn.sln last night, I observed 787126ms (over 13 minutes) of exclusive lock contention in `OnceInitializedOnceDisposed.EnsureInitialized(bool)`, 99% of occurred when called from `TargetFrameworkProvider.GetTargetFramework(string)`. This was a nearly 30 second long block of 28 threads in the thread pool. It is essential that `EnsureInitialized(bool)` be rewritten as asynchronous or otherwise modified to not block thread pool threads during this operation.

**Comment by Pilchie** [comment]
@srivatsn - can you help get this triaged.

**Comment by davkean** [comment]
@jmarolf Did you mention you were looking at this?

**Comment by jmarolf** [comment]
@davkean yeah, just sat down with @srivatsn to make sure I understood what was going on.  I'll send out a PR shortly.
