### ISSUE TITLE
Pass DotnetCliToolTargetFramework during restore nomination

### ISSUE THREAD

**Issue by emgarten** [dotnet/project-system#2427]
Restore nomination should pass ``DotnetCliToolTargetFramework``

This allows the SDK to set the target framework used to restore cli tools.

For reference, command line restores read it using nuget.targets here: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L306

**Comment by rrelyea** [comment]
Is this inserted into 15.3? If not, planned to? Which build, please?

**Comment by natidea** [comment]
This will be inserted into d15prerel today before 6pm
