### ISSUE TITLE
Hang in IVsDependencyProvider.EnumDependencies

### ISSUE THREAD

**Issue by jaredpar** [dotnet/project-system#2432]
Repro steps: 

1. Clone https://github.com/jaredpar/roslyn
1. Sync to branch repo-cps-hang
1. Run Restore.cmd
1. Open Roslyn.sln in Visual Studio

The solution will load in the time expected.  But once the solution completes loading the IDE will immediately hang.  I attached a debugger and it appears stuck in the project-system implementation of EnumDependencies.  A stack of the failure is available at the bottom of the bug report.

VS did become usable again after about 10 minutes of processing.  Using Dev15.3 Preview 2 (26606.0). 

```
Microsoft_VisualStudio_Threading_ni!Microsoft.VisualStudio.Threading.JoinableTaskFactory.WaitSynchronouslyCore
Microsoft_VisualStudio_Threading_ni!Microsoft.VisualStudio.Threading.JoinableTaskFactory.WaitSynchronously
Microsoft_VisualStudio_Threading_ni!Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread
Microsoft_VisualStudio_ProjectSystem_Implementation_ni!Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously
Microsoft_VisualStudio_ProjectSystem_VS_Implementation_ni!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.BuildDependencyProvider.Microsoft.VisualStudio.Shell.Interop.IVsDependencyProvider.EnumDependencies
Microsoft_VisualStudio_ProjectSystem_VS_Implementation_ni!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.BuildDependencyProvider+ComWrapper.Microsoft.VisualStudio.Shell.Interop.IVsDependencyProvider.EnumDependencies
Microsoft_VisualStudio_Shell_Interop!DomainNeutralILStubClass.IL_STUB_COMtoCLR
clr!COMToCLRDispatchHelper+0x28 [f:\dd\ndp\clr\src\vm\i386\asmhelpers.asm @ 1918] 
CLRStub
msenv!CDepNode::HrAddProjDeps+0x4d 
msenv!CDepGraph::HrBuildDepGraph+0x69 
msenv!CDepGraph::HrValidate+0xe 
msenv!CDepGraph::ValidateGlobalBuildOrder+0x34 
msenv!CSlnUpdate::GetBuildOrderList+0x50 
Microsoft_VisualStudio_ErrorListPkg!DomainBoundILStubClass.IL_STUB_CLRtoCOM
Microsoft_VisualStudio_ErrorListPkg!Microsoft.VisualStudio.ErrorListPkg.Shims.TaskListBase.RecalculateProjectRank
Microsoft_VisualStudio_ErrorListPkg!Microsoft.VisualStudio.ErrorListPkg.Shims.TaskListBase.OnEntriesChanged
Microsoft_VisualStudio_Platform_VSEditor_ni!Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent
Microsoft_VisualStudio_Editor_Implementation_ni!Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControl+<UpdateEntriesAsync>d__180.MoveNext
mscorlib_ni!System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext
mscorlib_ni!System.Threading.ExecutionContext.RunInternal
mscorlib_ni!System.Threading.ExecutionContext.Run
mscorlib_ni!System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run
Microsoft_VisualStudio_Threading_ni!Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector.TryExecute
Microsoft_VisualStudio_Threading_ni!Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector+<>c.<.cctor>b__20_0
mscorlib_ni!System.Threading.Tasks.Task.InnerInvoke
mscorlib_ni!System.Threading.Tasks.Task.Execute
mscorlib_ni!System.Threading.Tasks.Task.ExecutionContextCallback
mscorlib_ni!System.Threading.ExecutionContext.RunInternal
mscorlib_ni!System.Threading.ExecutionContext.Run
mscorlib_ni!System.Threading.Tasks.Task.ExecuteWithThreadLocal
mscorlib_ni!System.Threading.Tasks.Task.ExecuteEntry
mscorlib_ni!System.Threading.Tasks.TaskScheduler.TryExecuteTask
Microsoft_VisualStudio_Shell_UI_Internal_ni!Microsoft.VisualStudio.Services.TaskSchedulerService.VsUIThreadBlockableTaskScheduler.DoOneTask
Microsoft_VisualStudio_Shell_UI_Internal_ni!Microsoft.VisualStudio.Services.TaskSchedulerService.VsUIBackgroundPriorityScheduler.ProcessQueue
Microsoft_VisualStudio_Shell_UI_Internal_ni!Microsoft.VisualStudio.Services.TaskSchedulerService.VsUIBackgroundPriorityScheduler.OnTimerTick
```

**Comment by davkean** [comment]
I'll try to repro. I suspect this is the same issues we've seen with thread pool exhaustion, see: https://github.com/dotnet/project-system/issues/2297.

**Comment by jaredpar** [comment]
@davkean dug in a bit deeper last night.  It seems that the project-system / IDE isn't processing the assets files correctly here.  Hence lots of errors like System.Object can't be found (likely hundreds of thousands).  That seems to be contributing highly to the problem here.

**Comment by jaredpar** [comment]
Based on @Pilchie advice I tried the work around suggested in #2297.  

``` xml
<Project>
  <ItemGroup>
    <ProjectCapability Remove="DependenciesTree"/>
  </ItemGroup>
</Project>
```

That does seem to provide relief for Compilers.sln which is a much smaller solution.  The Roslyn.sln solution though is still unusable.

**Comment by davkean** [comment]
The contention due to the bugs I linked will increase the time it takes process the design-time data and send it onto Roslyn, which will result in System.Object missing, etc. Note that until https://github.com/dotnet/roslyn/pull/19637 is merged in, it's expected that we error about System.Object upfront until we process the data. Once you have a build with those changes, we will no longer error upfront until we've processed the data.

I'll currently looking at fully testing all my PRs today against the repros I have - I'll try to squeeze this in as part of it. Otherwise, I'll need to get to this tomorrow.

**Comment by davkean** [comment]
I'm seeing signs of ThreadPool exhaustion without my changes:

![image](https://user-images.githubusercontent.com/1103906/27112112-29db2f4e-50f8-11e7-9c65-9ee35e861d6a.png)

**Comment by davkean** [comment]
I could repo this issue with the latest build.

I then applied all the PRs pointed out by https://github.com/dotnet/project-system/issues/2297 and tried again (turning off the dependency node doesn't fix all the issues - just some). This time Roslyn.sln was significantly better, and did not block for large amounts of time.

However, it still felt sluggish, mainly due to CPU usage which was constantly pegging the CPU. I'm going to track that with: https://github.com/dotnet/project-system/issues/2388.

I'm going to close this bug in lieu of https://github.com/dotnet/project-system/issues/2297 and https://github.com/dotnet/project-system/issues/2388.

**Comment by davkean** [comment]
Oh, it also ran out of memory, which I'm tracking via: https://github.com/dotnet/project-system/issues/2438.
