### ISSUE TITLE
Property pages do not refresh when the underlying project file is updated

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#2434]
Today if you modify a project file, you need to close and re-open the property pages to see the changes.  We should automatically refresh this information when we detect a change

**Comment by davkean** [comment]
This is blocking on the connectpoint container implementation - thought we had a bug on this somewhere.

**Comment by davkean** [comment]
Weird, we don't actually have a bug on this anywhere. This is the one.

**Comment by Pilchie** [comment]
Dupe of #1259
