### ISSUE TITLE
Visual Studio is running out of memory opening Roslyn.sln

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2438]
Repro steps: 

1. Clone https://github.com/jaredpar/roslyn
1. Sync to branch repo-cps-hang
1. Run Restore.cmd
1. Open Roslyn.sln in Visual Studio
1. Open Test Window
1. Wait for 10 minutes

Expected: VS to not run out of memory
Actual: VS runs out of memory

**Comment by davkean** [comment]
I filed here, because I'm seeing lots of extra garbage being generated here.

**Comment by davkean** [comment]
After I've applied the fix for https://github.com/dotnet/project-system/issues/2445, I'm no longer running into this. I'm unsure if this the because we're still leaking but we've got more room now, or we were near the edge and the memory we were allocating in #2445 was pushing us over the edge. 

Either way, I'm pushing this out.

**Comment by Pilchie** [comment]
@sharwell This is likely the SQLite OOM?

**Comment by sharwell** [comment]
@Pilchie It depends on the machine. If it's still being observed I can look at a heap to confirm.

**Comment by Pilchie** [comment]
Closing this until/unless we get more instances to investigate.
