### ISSUE TITLE
Pinned SDK version below 1.0.4 seems broken in 15.3

### ISSUE THREAD

**Issue by onovotny** [dotnet/project-system#2450]
Here's the scenario: 

Web project that has a global.json with a pinned SDK version. 

Executing an msbuild /pp yields some interesting results for where the SDK's are imported:

If the SDK version is 1.0.0-1.0.3 is:
The import of the Web SDK is from: 
`C:\Program Files\dotnet\sdk\1.0.0\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props`

But then the .NET Sdk is from: 
`C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props`

If the SDK version is 1.0.4, both SDK's come from the `C:\Program Files\dotnet\sdk\1.0.4\Sdks\` directory.

Seems like if `1.0.4` is the min version of the SDK that will work correctly with 15.3, then if VS sees an older pinned version, it should use the upgrade wizard functionality to bump the min SDK version to 1.0.4 so things don't act strangely for users unexpectedly.

**Comment by srivatsn** [comment]
This issue was moved to dotnet/sdk#1348
