### ISSUE TITLE
Close the sln or VS and then reopen .sln, it failed to load the project.

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2457]
- Create a project (C# or VB), restore completed, build succeeded, run passed.
- Close the sln and reopen it, it failed to load the project
- Close the vs and reopen .sln, it failed to load the project as well.
   ![failedtoloadprojects](https://user-images.githubusercontent.com/22901391/27217952-a1e55354-52ae-11e7-9651-753cc887b1b2.png)
- Right click the project and click "Reload Project", all files were loaded.

Product Info:
```
Install d15prerel.26615.06
Install CLI/SDK(2.0.0-preview2-006470)
```

dotnet --info
```
.NET Command Line Tools (2.0.0-preview2-006470)

Product Information:
 Version:            2.0.0-preview2-006470
 Commit SHA-1 hash:  4ea3671bbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006470\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**Comment by natidea** [comment]
Miaomiao says this does not repro anymore.

**Comment by davkean** [comment]
This would have been that solution bug that was introduced.
