### ISSUE TITLE
Duplicate files in solution explorer after pasting

### ISSUE THREAD

**Issue by rchande** [dotnet/project-system#2459]
Was unable to come up with a minimal repro for this:

Open Roslyn.sln and navigate to the Perf.Tests project. Open any other C# project in the solution and copy a .cs file out of it. Paste it into the Perf.Tests project.

Expected:
One file entry for the pasted file.
Actual: 
Two entries for the pasted file.

This appears to happen because:
1. the Perf.Tests project has file globbing for files
2. Solution explorer file paste always adds a file include, meaning that the file is pulled in twice by msbuild

![image](https://user-images.githubusercontent.com/3751401/27243540-445ab7f4-5297-11e7-9282-0a5f0fcc1298.png)

**Comment by rchande** [comment]
cc @jmarolf

**Comment by davkean** [comment]
@rchande Can you paste the globbing? We do sniff for globbing, but we only recognize certain patterns.

**Comment by srivatsn** [comment]
[Moved to CPS](https://devdiv.visualstudio.com/DevDiv/_workitems?id=469293&fullScreen=false&_a=edit)

**Comment by jviau** [comment]
@rchande I believe `Perf.Tests` is a legacy C# project in that image. Are you able to confirm that?

* It has a `References` node, in .netcore that is `Dependencies` (or nothing if it is disabled).
* I do not believe CPS can even display duplicate items like that. The tree uses the caption as a case-insensitive key.
* Legacy project does behavior like this when there is duplicate items (and `Perf.Tests` has a `<Content Include="**" />` in it).

**Comment by rchande** [comment]
@jviau Sure, this looks like a bug in the implementation of globbing in the legacy project system. Namely, that the code that adds entries for pasted files doesn't check to see if the file it's adding is already included through globbing. Should I refile this bug somewhere else?

**Comment by jviau** [comment]
@rchande I routed the issue to the legacy C# project path. I believe this is by-design or at least a known issue they don't intend to fix/change. The legacy C# project never supported globbing. Also, the way MSBuild works, items are not distinct. There _is_ actually multiple items in the project. In CPS we see the duplicate items as well, but we "nest" them underneath a single node.

**Comment by davkean** [comment]
I closed the internal bug, we don't have intentions of fixing/changing this behavior in the legacy project system.
