### ISSUE TITLE
References added by Packages during Evaluation remain unresolved

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2460]
**Repro Steps**

Create a Console App targeting net461 and add a package reference to Drop.App.Core:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Drop.App.Core" Version="15.114.26406-rc3771152" />
  </ItemGroup>

</Project>
```

**Expected**
Assemblies node only contains framework packages, and none are unresolved

**Actual**
Two assemblies from the package are present and are unresolved:

![image](https://user-images.githubusercontent.com/7732033/27248975-60467eb6-52c0-11e7-84e7-38a52003a3cd.png)

This occurs because the package's generated `*nuget.g.targets` imports targets from the package that add a direct reference to the assembly:

```xml
    <Reference Include="Microsoft.Diagnostics.Tracing.EventSource">
      <HintPath>$(MSBuildThisFileDirectory)..\..\lib\net45\Microsoft.Diagnostics.Tracing.EventSource.dll</HintPath>
    </Reference>
```
During evaluation, this assembly is added to the Assemblies node. But following design time build, this instance is not resolved. The resolved reference appears under the package's hierarchy:

![image](https://user-images.githubusercontent.com/7732033/27249111-ad53d670-52c2-11e7-9739-deb102307fc2.png)

**Comment by drewnoakes** [comment]
The repro steps aren't working for me as I don't have a feed for package `Drop.App.Core`. The only reference I found online is in [BuildXL here](https://github.com/microsoft/BuildXL/blob/38d08ccc81623fd17fdf24b1d1cf263c0a48bb79/config.microsoftInternal.dsc#L40).
