### ISSUE TITLE
RoslynDev hive doesn't work as expected after running build.cmd

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#2463]
From discussion with @panopticoncentral, running `build.cmd` is not sufficient to properly set up project system for testing in hive.
This came up in the context of validating the ref assembly change for FUTD check. My setup was incorrect.

The [contribution guide ](
https://github.com/dotnet/project-system/blob/master/docs/repo/getting-started.md) should be updated, or `build.cmd` should be fixed:
> From the command-line, after you've run build.cmd, you can launch a Visual Studio instance with your recently built bits by running the following from a Visual Studio Command Prompt:
> `devenv /rootsuffix RoslynDev`

Relates to https://github.com/dotnet/project-system/issues/2254#issuecomment-309537869

**Comment by davkean** [comment]
@jcouv This must have been broken, let me investigate...

**Comment by davkean** [comment]
Hmm, this looks right to me, can you do the following:

1. Delete every folder in C:\Users\jcouv\AppData\Local\Microsoft\VisualStudio that ends in RoslynDev
2. Run `build.cmd`

You should now see the following folders under:

![image](https://user-images.githubusercontent.com/1103906/27308783-dba7172a-5593-11e7-9bb7-072894e88c20.png)

Also verified that we load those bits from a fresh hive:

![image](https://user-images.githubusercontent.com/1103906/27308893-7885fa0c-5594-11e7-9214-bf14651d30f0.png)

**Comment by srivatsn** [comment]
For the rules to take effect some env vars need to be set. For that - you need to F5 from VS (launchSettings.json sets them) or we need build.cmd to set them.

**Comment by davkean** [comment]
@srivatsn Ah, the rules...may be we need a launch that sets it. Having the build set it seems wrong.

**Comment by srivatsn** [comment]
We should create a batch file and update the [contribution guide ](https://github.com/dotnet/project-system/blob/master/docs/repo/getting-started.md)

**Comment by Pilchie** [comment]
Note that the current root suffix is `ProjectSystem` not `RoslynDev` too. Related to adoption of build tools?

**Comment by davkean** [comment]
I updated the contribution guide instead of adding a command-line batch. It's just a couple of environment variables.

**Comment by DominikDitoIvosevic** [comment]
@davkean what was the doc change? I have a feeling I'm missing some step to update the extensions my RoslynDev instance is using.

I'm on dev16.0 branch with my changes applied to it (some parser and lexer experiments I'm doing).
I want to try out the new compiler both in Visual studio experience and the compiler.

I cleaned my git repo. I removed the RoslynDev folder from AppData.
I run
` .\Restore.cmd; .\Build.cmd`
and then
`& "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe" /RootSuffix RoslynDev`

For some reason I'm still using a version of the compiler with SOME of the changes I did. I managed to try out my changes in this experimental instance a week ago but now I can't get the RoslynDev to use the latest version of my binaries.

Please help

**Comment by davkean** [comment]
@DominikDitoIvosevic This is the project-system, Roslyn's contribution guide is here: https://github.com/dotnet/roslyn/wiki/Contributing-Code.
