### ISSUE TITLE
legacy package reference projects need to surface warnings and errors from assets file

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2465]
_From @mishra14 on June 19, 2017 21:35_

Related cps/package ref work: https://github.com/dotnet/sdk/pull/1228

We should have feature parity for legacy package reference as well.

Also, if this is the right place for it: we should trigger a design time build for legacy package ref as well.

cc: @natidea @srivatsn 

_Copied from original issue: dotnet/sdk#1357_

**Comment by srivatsn** [comment]
The build task for legacy projects lives here - https://github.com/NuGet/NuGet.BuildTasks. I think the way we probably want to handle this is to move projects using packagereference to the new build task. Moving this issue to the project system repo.

**Comment by tmeschter** [comment]
@Pilchie How important is this? As in, do we definitely want to do it for 16.0?

**Comment by tmeschter** [comment]
Tom's triage notes: Not essential. Recommend closing the issue without addressing it.

**Comment by tmeschter** [comment]
We have decided to _not_ implement this feature request. Closing.
