### ISSUE TITLE
UI delays and continuous NuGet restores for Blazor

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2468]
Version: 26616.2.d15rel 

@danroth27 is hitting UI delays and continuous NuGet restores for https://github.com/SteveSanderson/Blazor/commit/e00a389967e9f6b31022e5a0489daacbc5c7e670.

**Comment by davkean** [comment]
This is what I see when I open the project:

![blazor](https://user-images.githubusercontent.com/1103906/27318008-5a792b40-55cd-11e7-979e-4476cf9544c6.gif)

**Comment by davkean** [comment]
After applying the fix for #2461, this is running into eternal restore issue similar to https://github.com/dotnet/project-system/issues/1457. Given that this project clearly worked at one point (solution: 15.0.26430.6), I suspect a regression, so have kept in 15.3.

@natidea Can you take a look?

**Comment by davkean** [comment]
@natidea You'll need a build without the #2461 regression. A easy workaround without needing to apply both #2461 and the ASP.NET tooling change, is to simply change LaunchSettingsProvider.GetLaunchSettingsFilePathAsync to return a random path and not ask the special file manager.

**Comment by davkean** [comment]
@srivatsn wonders if the regression might be that eternal restore is blocking UI in 15.3 whereas in previous builds it wasn't. Make note that in 15.3 we now reload the targets, and that [definitely blocks the UI for some time](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/446753).

**Comment by natidea** [comment]
I have not been able to regress this with the fix in #2461 -- solution is still hanging. Do I also need a fix from WTE? If so I'll wait until their change is in.

**Comment by natidea** [comment]
I've tracked the continuous restore here to timestamps in version suffix, specifically [version.props#L4](https://github.com/SteveSanderson/Blazor/blob/a725bdc17b25d7451bbd8bee949c727aa8558cb6/version.props#L4). This timestamp make every successful restore trigger a new nomination. 

After removing the timestamp, I no longer see UI delays. I'll take a look into the UI delays in the presence of continuous restore.

**Comment by natidea** [comment]
Closing in favor of https://github.com/NuGet/Home/issues/5500 and https://github.com/dotnet/project-system/issues/1457

**Comment by davkean** [comment]
@natidea Where's the bug tracking the UI delays?

**Comment by davkean** [comment]
@natidea Ping

**Comment by natidea** [comment]
I think the UI delays were just related to the fact that the version was updating every second, with every DT build triggering a new nomination, and this was over 3 different projects. When I repro continuous restore using previous repros, I don't see the same UI delays on the latest build.

**Comment by davkean** [comment]
None of that should be running on the UI thread.

**Comment by natidea** [comment]
Activities in the UI thread would include Restore writing to the status bar, and the dependencies node switching continuously from resolved to unresolved and back.

**Comment by davkean** [comment]
Ah, so dependency node? Okay thanks.
