### ISSUE TITLE
XAML build targets produce randomly named empty directories

### ISSUE THREAD

**Issue by tmat** [dotnet/project-system#2481]
The temporary project XAML creates has the OutDir set to a random directory name. Microsoft.Common.CurrentVersion.targets creates a directory doe such OutDir, which pollutes the output.

```xml
<MakeDir Directories="$(OutDir);$(IntermediateOutputPath);@(DocFileItem->'%(RelativeDir)');@(CreateDirectory)" ContinueOnError="True"/>
```

A workaround is to clear the OutDir in a custom .targets file:

```xml
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.tmp_proj'">
    <OutDir/>
  </PropertyGroup>
```

**Comment by davkean** [comment]
Hmm, what makes this a project system issue?

**Comment by tannergooding** [comment]
I think this is more of an issue with the XAML targets

**Comment by tmat** [comment]
Oops. I meant to file it on SDK.
