### ISSUE TITLE
Visual basic C# Login app Project

### ISSUE THREAD

**Issue by LucasAlmeida11** [dotnet/project-system#2486]
Im tryin to do my final work in school, which is an app that user log in and access info etc etc... but i cant understand what i made wrong here...  Appreciate any help!!
![capturar](https://user-images.githubusercontent.com/29627304/27432965-6cfcc1ae-574a-11e7-9f2b-0c7d6900646a.PNG)

**Comment by jprr773** [comment]
a query nao esta bem formatada (falta o caracter **'** );
string query ="Select * from tbl_login Where username = **'**" + txtuser.Text.Trim() + "**'** and passorwd = **'**" + txtBox2.Text.Trim() + "**'**";

**Comment by LucasAlmeida11** [comment]
jprr773 obrigado pela resposta.
Mas assim apenas um utilizador terá acesso?

**Comment by jprr773** [comment]
o metodo que estás a usar não é o mais robusto para efectuar o Login pois abre caminho ao SQL Injection. No entanto, para o efeito do codigo que apresentas, apenas um utilizador terá acesso.

**Comment by LucasAlmeida11** [comment]
Ok, irei pesquisar então métodos de como criar uma forma de vários utilizadores terem acesso. Se souber alguma diga! Muito obrigado.

**Comment by jprr773** [comment]
Lucas, a tua funcao permite que vários utilizadores tenham acesso, tantos quantos existirem na tabela tbl-Login.
Acontece é que a tua funcao nao é robusta para prevenir ataques do tipo SQL Injection.

**Comment by LucasAlmeida11** [comment]
Nunca estudei SQL, mas o link que você me mandou parece ser útil.

**Comment by jmarolf** [comment]
This does not have anything to do with the project system.  I would recommend asking this question on https://www.reddit.com/r/learnprogramming/ or https://www.reddit.com/r/dotnet/.  There is also an ASP.NET chatroom here: https://gitter.im/aspnet/Home that may be able to offer help.
