### ISSUE TITLE
Can't add Windows.WinMD reference to NetStandard projects

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2495]
Reported via [VSFeedback](https://developercommunity.visualstudio.com/content/problem/32171/cant-add-windowswinmd-reference-to-netstandard-pro.html)

---------------

Calling WinRT apis from both .Net and UWP is a valid scenario, and consequently you could use an old style portable library to target both that makes WinRT calls. At some point VS added the ability to change the targeting to the NetStandard type. The projects that were created that way still work fine. However, if you create a brand new NetStandard project it will not let you added the reference to the WinMD file saying it isn't supported. I undertand that referencing it creates a dependency on Windows but I don't see an alternative to creating the projects the old way.

**Comment by srivatsn** [comment]
Looks like manually editing the csproj to add a Reference to a winmd works - the compiler doesn't care that it's netstandard. The addref dialog is blocking the reference though.

**Comment by davkean** [comment]
This has been fixed.
