### ISSUE TITLE
ProjectGuids added to project files in latest Visual Studio build

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#2496]
**Version:**
![image](https://user-images.githubusercontent.com/9797472/27501144-681650ca-5820-11e7-91da-c471f5f29067.png)

Building the project system with this version of VS causes the folling XML to be added to every project file:
```XML
<PropertyGroup Label="Globals">
  <ProjectGuid>edde85b3-5ed8-4fd7-a383-013e7972c3f8</ProjectGuid>
</PropertyGroup>
```

**Comment by davkean** [comment]
I'm not seeing these. Can you debug this and see if our components are failed to load? Look in MEF error cache.

**Comment by jmarolf** [comment]
My machine was busted, false alarm
