### ISSUE TITLE
Set $(DesignTimeBuild) to true during design-time builds in the legacy project system

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2502]
This enables developers to write a set of targets that works consistently across all C#/VB projects.

I've seen asks for this from Paket, Fody and Xamarin.

**Comment by davkean** [comment]
We should do a quick pass to figure if this has compat impacts.

**Comment by onyxmaster** [comment]
Very much would like this to happen, since legacy web app projects do not have the SDK-style counterparts (at least yet).

**Comment by sharwell** [comment]
> This enables developers to write a set of targets that works consistently across all C#/VB projects.

Is this not already possible? The condition isn't as simple as checking `$(DesignTimeBuild)` alone, but I don't remember having difficulty writing compatible targets.

**Comment by onyxmaster** [comment]
It appears that `Condition="'$(DesignTimeBuild)' != 'true' AND '$(BuildingProject)' == 'true'"` (a negation of what is described at https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md) works, if applied at proper time.

**Comment by onyxmaster** [comment]
So yes, it works, but it's not as simple as checking a single property =)

**Comment by bording** [comment]
@davkean When https://github.com/Microsoft/msbuild/issues/2417 is eventually fixed, would `$(BuildingProject)` still be `true` for regular builds for SDK-style projects? When I first read about it in https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md, I was thinking it was only relevant for legacy projects, meaning it was would always be unset/false for SDK-style projects.

However, if SDK-style projects stopped setting it to true for regular builds, then @onyxmaster's suggested condition would start failing, so I suppose the outcome of https://github.com/Microsoft/msbuild/issues/2417 has to be that it would only change the value of `$(BuildingProject)` for design-time builds.

**Comment by Pilchie** [comment]
@panopticoncentral has a PR out at for the internal code for this.

**Comment by tmeschter** [comment]
Tom's triage notes: @panopticoncentral Did we address this in the csproj project system?

**Comment by tmeschter** [comment]
Confirmed with @panopticoncentral that we now set this property in the legacy project system.
