### ISSUE TITLE
Bogus warnings in dependency tree

### ISSUE THREAD

**Issue by davidfowl** [dotnet/project-system#2507]
I swore I filed this bug a while ago but it seems like it isn't fixed:

![image](https://user-images.githubusercontent.com/95136/27594141-eadddf42-5b0d-11e7-936e-0dd8fdca93b9.png)

When you use floating versions, you get a warning saying that there's a mismatch. Since we bubble this up the dependency tree, it means everything is yellow which masks real problems.

Notice the error list shows 0 warnings:

![image](https://user-images.githubusercontent.com/95136/27594260-2e129cf8-5b0e-11e7-8b3e-6f15c2344895.png)

I'm using the latest release 15.3 Preview 3:

![image](https://user-images.githubusercontent.com/95136/27594291-3e33fd2a-5b0e-11e7-88c7-777a16d5a702.png)

/cc @natidea @abpiskunov

**Comment by natidea** [comment]
@davidfowl  That warning was removed in PR https://github.com/dotnet/sdk/pull/1228 which should be in Preview 3. Do you perhaps have an older version of dotnet CLI installed?

**Comment by srivatsn** [comment]
Isnt there a similar warning that nuget still raises though?

**Comment by natidea** [comment]
I don't believe NuGet posts any warnings to the dependency node. [The text of the removed warning](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/Resources/Strings.resx#L223) matches the screenshot above.

**Comment by natidea** [comment]
Digging a little deeper, I see that the change has not flowed into master, but it is in rel/1.1.0 and release/2.0.0. I assume we are not shipping anything out of master for the SDK /cc @livarcocc

**Comment by davidfowl** [comment]
I'll check my SDK version. It might have been running preview1 bits.

**Comment by davidfowl** [comment]
Yep it's fixed
