### ISSUE TITLE
Expanded unresolved Graph Nodes remain unresolved after problem is fixed

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2509]
**Repro Steps**

Create a .NET Standard class library and add the following mismatched package references:

```xml
  <ItemGroup>
    <PackageReference Include="NuGet.Commands" Version="4.0.0" />
    <PackageReference Include="NuGet.Packaging" Version="3.5.0" />
  </ItemGroup>
```

This generates expected NU1605 package downgrade warnings for `NuGet.Packaging`. There is also a nested warning under `NuGet.Commands` which bubbles up as expected. Expand the Dependencies node to show nested warning under `NuGet.Commands`:

![image](https://user-images.githubusercontent.com/7732033/27606245-62d0e1cc-5b34-11e7-9f4e-b96a1f58266c.png)

Resolve the problem by changing the version for NuGet.Packaging to 4.0.0

**Expected**
All unresolved nodes become resolved

**Actual**
While the top 3 levels of nodes do become resolved, the lower levels which contain Graph Nodes remain unresolved. This does not occur if the nodes were not expanded prior to fixing the package downgrade issue

**Comment by drewnoakes** [comment]
This repro is blocked by #3780. 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Commands" Version="4.0.0" />
    <PackageReference Include="NuGet.Packaging" Version="3.5.0" />
  </ItemGroup>

</Project>
```

Looks like:

![image](https://user-images.githubusercontent.com/350947/52856521-87e09b00-311c-11e9-879c-e121db894f0a.png)
