### ISSUE TITLE
Idempotent Project Changes can leave Dependency Node Unresolved

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2510]
**Repro Steps**

Create a .NET Standard project and add the following package references:

```xml
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.0.2" />
  </ItemGroup>
```

Observe that the Newtonsoft.Json reference is flagged with warning NU1603 Package not found, approximate best match was resolved.

![image](https://user-images.githubusercontent.com/7732033/27607823-154e1996-5b3a-11e7-9bfc-f06beff84011.png)

Add NoWarn="NU1603" to the StyleCop.Analyzers reference (i.e. to the wrong node)

**Expected**

No changes to dependencies node.

**Actual**

StyleCop.Analyzers becomes and remains unresolved, anticipating a new resolved node. This is likely because the change did not trigger a dataflow with a "Difference".

Workaround is to make some other change that triggers a dataflow (e.g. change version to 1.0.1)

**Comment by drewnoakes** [comment]
Another way to trigger this:

- Add a package reference
- Modify metadata on the package (i.e. set `NoWarn` to `nullable`)

**Comment by drewnoakes** [comment]
#5335 has another simple way to trigger this behaviour.

**Comment by drewnoakes** [comment]
Another test case for this is moving a dependency (e.g. `PackageReference`) from the project file to `Directory.Build.props`.
