### ISSUE TITLE
Editing a resx file in a .NET Core 2.0 project crashes VS

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2512]
Repro steps:
1. Create a .NET Core 2.0 console app
2. Add a resource file
3. Open it, edit it and save.

We had the same issue for .NET Standard projects and we put in a workaround in the resx designer (https://github.com/dotnet/project-system/pull/2355) that redirects requests for System.String, netstandard.dll to System.String, mscorlib.dll

For netcoreapp 2.0 projects, however, we get a request for System.String, System.Runtime, 4.2.0.0. That version of System.Runtime isn't in the closure of VS's search paths - so same problem different form.

Maybe the hack needs to be scoped differently and we should say if the request is for a System.String then return the one that's loaded. Given String seems to be only supported type for resx files in netcore projects.

**Comment by davkean** [comment]
The problem will probably happen with Byte[] too.

**Comment by tmeschter** [comment]
@davkean Under what circumstances would we encounter a Byte[]? I haven't been able to hit any problems with that while embedding icons, images, or text files.

**Comment by davkean** [comment]
@tmeschter I don't know the code path, but byte[] is used when adding a binary file.
