### ISSUE TITLE
Remove all concepts of "target framework" and that configurations are driven from them

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2525]
LanguageServiceHost, NuGetRestorer and the dependency node all know that TFMs drive configurations, and when TFMs change we should reset them. 

They have convoluted code to wait for the TFMs to change, and then reset their state and sync that up with the configuration data. We should remove all that logic and centralize the ability to get "active" configurations, and listen to when they change. Code throughout the tree shouldn't be parsing, listening to, or understanding that TFMs drive configurations.

**Comment by drewnoakes** [comment]
From https://github.com/dotnet/project-system/issues/4886#issuecomment-497182074:

> The reason these should be removed is that dependency node shouldn't know anything about TargetFrameworks - all it should know is that there's a 3rd dimension and it's used for grouping dependencies.

**Comment by drewnoakes** [comment]
The dependencies node will soon be backed by the assets file, which requires mapping from `TargetFramework` dimension (eg. `net4.8`) to full name (e.g. `.NETFramework,Version=v4.8`). It may be possible to do this in a general way that extends to other dimensions. In such a case we'd need to update tree generation to create appropriate grouping nodes across more than just target framework.

**Comment by davkean** [comment]
TargetFrameworkMoniker is the property you should be reading to get the full moniker. The TargetFramework property could contain "foobar".

**Comment by davkean** [comment]
See: https://github.com/dotnet/project-system/blob/master/docs/repo/coding-conventions.md#guidelines

**Comment by davkean** [comment]
@drewnoakes Also play around with setting the NuGetTargetMoniker property and its impact on the assets file - NuGet it respects that too if present and we need to handle it: https://github.com/dotnet/project-system/blob/1ff236791ec03e17ceab56b008e9494496ea890e/tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/PackageRestore/Snapshots/RestoreBuilderTests.cs#L69.
