### ISSUE TITLE
Visual Studio uses CPU and hangs on opening built Fable project

### ISSUE THREAD

**Issue by xperiandri** [dotnet/project-system#2534]
## Scenario 1
1. Follow the instructions here http://fable.io/pages/getting-started.html
2. Then open that project in Visual Studio 2017 Preview 3
3. It will use CPU and UI will be unresponsive

CLI version 2.0.0.6622 Preview 2

## Scenario 2
1. `dotnet new fable` in console
2. Open project in Visual Studio
3. Open package manager
4. `yarn install`
5. `dotnet restore`
6. Hang

**Comment by tannergooding** [comment]
I am not seeing a hang in the latest preview build (15.4.P3)

**Comment by Pilchie** [comment]
@xperiandri are you seeing this with 15.5 or 15.6 Preview 1?

**Comment by Pilchie** [comment]
@Tihan - can you take a look at this?

**Comment by xperiandri** [comment]
I haven't tried
I will check and get back around 2nd of January

**Comment by davkean** [comment]
Closing this as we couldn't repro this. Please open a new issue if you are still running into this.
