### ISSUE TITLE
Reduce all file allocations

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2536]
We spend waay to much time cleaning up garbage from file manipulation due to a variety of reasons:

1) We recalculate data we already have (such as figuring out RootDirectory in a project snapshot when we already have in the snapshot in IsDocumentInProject paths)

2) We shove paths in URIs both to figure if they are rooted, and to normalize them. There are really, really expensive.

3) We allocate for already normalized paths - we should avoid that.

See PathHelper in CPS.
See ManagedPathHelper in this repo.

**Comment by davkean** [comment]
About 11% of opening ProjectSystem is just URI:
![image](https://user-images.githubusercontent.com/1103906/27728883-fd9c31b8-5dc6-11e7-81fb-80c426672f58.png)

**Comment by Pilchie** [comment]
@lifengl - do you know if anything happened to improve things in `PathHelper` in CPS for this?  Should I file an internal bug for you to investigate further?

**Comment by lifengl** [comment]
I remember @davkean fixed a few functions, and I updated a few too.  That should reduce the memory usage related to URI in some common functions like loading a project.  We do have other functions in PathHelper, which can still be expensive, but it is unclear the performance impact at this point.  I think taking a look new trace might help us to understand whether the priority of extra work in this area further.

**Comment by Pilchie** [comment]
Looking at this, I don't see much to do here in this repo.  `ManagedPathHelper.IsRooted` doesn't show up in a trace.  `ManagedPathHelper.MakeRooted` does, but it's not a HUGE amount.  

A more significant cost here comes from the language service calling `ParseCanonicalName`, which incurs a bunch of JTF overhead, and significant allocations in `PathHelper.MakeRelative`.

Hopefully, @jasonmalinowski's work will remove the requirement to call `ParseCanonicalName` while populating the language service?

@lifengl - do you want me to file a VSTS bug for potential changes to `PathHelper` in CPS?

**Comment by jasonmalinowski** [comment]
@Pilchie Long term yes I'm making `ParseCanonicalName` go away, but we might be able to make a targeted fix there.

**Comment by jasonmalinowski** [comment]
(I guess the only reason we're doing that is to fetch folder names....a better hook or at least a cheaper one would be wonderful)

**Comment by davkean** [comment]
We pass you the folder names which doesn't go through ParseCanonicalName.

**Comment by davkean** [comment]
I spent a bunch of time trying to reduce ParseCanonicalName on our side and in CPS - but stopped doing more when it stopped being the biggest thing. It could still do with a some changes - especially just to drop Uri usage.

**Comment by Pilchie** [comment]
@jasonmalinowski has a change out to fix the `ParseCanonicalName` issue in Roslyn, so closing this at this point.
