### ISSUE TITLE
Reduce general allocations

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2539]
General unneeded allocations that I saw looking at a trace for opening ProjectSystem.sln:

- [ ] ~ParseAssemblyReferences is allocating a List<T> and enumerable when it can just use an Array and branch: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/CommandLine/CSharpCommandLineParser.cs,1671. (0.1%) - https://github.com/dotnet/roslyn/pull/20666~
- [ ] ParseAnalyzers is allocation a List<T> and enumerable when it can just use an Array and branch: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/CommandLine/CSharpCommandLineParser.cs,1621 - https://github.com/dotnet/roslyn/pull/20666
- [x] IProjectTreeExtensions.FindNodeByPath is 30% of all allocations (basically searching Dependency node is really, really inefficient), there's 26 MB of just iterators - https://github.com/dotnet/project-system/pull/2562.
- [x] Roslyn is double-parsing command-line arguments  - https://github.com/dotnet/roslyn/issues/20665.-
- [ ] CoreProjectTreeProviderBase.Initialize is ~2.3% of allocations with plenty of boxed Enumerators and EnumeratorObject.
- [x] MSBuild allocating ~1.3% of invalid path/file chars (https://github.com/Microsoft/msbuild/pull/2284).
- [x] MSBuild allocating ~1.4% of char array in ComparePathsNoCompare: (https://github.com/Microsoft/msbuild/pull/2288).
- [x] ProjectTreeFlags.Contains allocating 0.2% for func/boxed enumerator: https://mseng.visualstudio.com/VSIDEProj/_git/VSIDEProj.CPS/pullrequest/236486?_a=overview.
- [x] FileMatcher is calling GetFiles/GetDirectories allocating an extra string per file that is not needed: https://github.com/Microsoft/msbuild/issues/2287.

**Comment by Pilchie** [comment]
@davkean - do you think having this open is useful anymore?

**Comment by davkean** [comment]
Nope we can resolve this one.
