### ISSUE TITLE
Cannot specify launch settings in the project file

### ISSUE THREAD

**Issue by sharwell** [dotnet/project-system#2540]
Switching to the new project system eliminated our ability to configure default launch settings in the project file, forcing us to litter the repository with more than 50 copies of the same **launchSettings.json** file.

See dotnet/roslyn#20568.

**Comment by davkean** [comment]
@sharwell Did you try linked files?

**Comment by sharwell** [comment]
I tried to use linked files, but was not successful. The IDE appeared to behave as if no file were present.

**Comment by kvenkatrajan** [comment]
Selected profile stored in : .csproj.user
