### ISSUE TITLE
Project unloads and doesn't give a good error with missing quote typo

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/project-system#2543]
Not sure if this is fixable but when I updated a project to include a package reference and forgot a quote on the version attribute. When I saved, the whole project forced a reload to tell me that it couldn't load the project. Then I had to open it by hand and figure out what went wrong. Would be nice give an error that says what went wrong so it can be fixed without needing to jump through so many hoops for a small typo.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Bifrost.Devices.Gpio" Version=0.0.1" />
  </ItemGroup>

</Project>

```

This is on VS 2017 15.3 Update 3 and .NET Core 2.0 Preview 2.

**Comment by srivatsn** [comment]
The experience with VS 2017 15.3 Preview is that making such a change and hitting save causes a dialog to pop up saying 

![image](https://user-images.githubusercontent.com/20570/28543034-4cc8140a-7073-11e7-9be3-208f3cdb911f.png)

Hitting IgnoreAll puts the file back to its original state from disk (and not from the buffer - so your edit is lost). I believe @jviau is tracking making this experience in CPS.
