### ISSUE TITLE
Adding application manifest 

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/project-system#2557]
_From @miloush on June 25, 2017 17:5_

The project properties designer asks me to add manifest to the project first before it can be selected:
![untitled](https://user-images.githubusercontent.com/10546952/27518138-8a52e322-59d0-11e7-99b8-78a31d72e1a3.png)

However, there does not seem to be a manifest template in the Add New Item list for ASP.NET Core projects.

Either add the manifest template, or let the properties designer generate it, or change the "default settings" to declare newer OS support.

_Copied from original issue: aspnet/Tooling#1048_

**Comment by mlorbetske** [comment]
This seems to be the case with all .NET Core projects, not just ASP.NET Core.

**Comment by srivatsn** [comment]
There is an item template for the app manifest. If you are not seeing it maybe that it's not installed with the core or web workload and only with the desktop workload.

**Comment by miloush** [comment]
OK I was originally looking for the ASP.NET Core project to just enable the item template for app manifest.

If this is in hands of the .NET Core projects in general, I would argue that the default manifest should declare support at least for the OS the VS is running on.

**Comment by drewnoakes** [comment]
@jmarolf is this something you'll pick up at some point or should it be moved to José's team?

**Comment by donJoseLuis** [comment]
Greetings @drewnoakes , thanks for the ping.
@phenning & @grinrag , can you please discuss on which repo this issue belongs?

**Comment by davkean** [comment]
This is a generalized problem, it's not just this template, I see a tonne of missing templates. 

Console Application:

![image](https://user-images.githubusercontent.com/1103906/78083000-1935ce00-7400-11ea-9b78-717263080109.png)

Web Application:

![image](https://user-images.githubusercontent.com/1103906/78083041-2f438e80-7400-11ea-8001-05368768422c.png)

@BillHiebert Is this because you're overriding the add item template GUID?

**Comment by phenning** [comment]
@davkean Yes, we specify
"TemplateGroupIDs(VsTemplate)"="AspNetCore"
"ShowOnlySpecifiedTemplates(VsTemplate)"=dword:00000001

All the templates which show up under the ASP.NET Core Node specify AspNetCore in the TemplateGroupID:
    <TemplateGroupID>AspNetCore</TemplateGroupID>

**Comment by phenning** [comment]
Template owners who believe that their templates will function fine on Core can just specify the template group. Most of the ones under the ASP.NET Core node are authored by our team, but there are a few which ship in other components (typescript comes to mind)

@donJoseLuis Ultimately, I think the owner of each template is the best to determine whether they should have their template be applicable to ASP .NET Core projects. I don't think either your team or my team is equipped to make that decision by either updating their templates or duplicating them separately for ASP.NET Core. We've already duplicated the most commonly used which make sense in the most common Web scenarios.

**Comment by davkean** [comment]
@phenning You can only specify Template Group IDs once per template so that's non-starter for the general purpose ones without duplication. We've deprecated use of template group ids in place of capabilities so that we don't need to duplicate templates that's how we've approached this across UWP, Portable, WinForms, WPF and Shared Projects. ASP.NET is the odd one out here.

**Comment by phenning** [comment]
@davkean do you know if having this set
`"ShowOnlySpecifiedTemplates(VsTemplate)"=dword:00000001`

would also filter out templates which had a capabilities match via Applies to, or would we need to turn this off to get those to display? I don't think we want to just display all templates which match CSharp necessarily, as they may not make sense for Web projects.

**Comment by davkean** [comment]
I'm not sure.

We've done this on a case-by-case basis; figure out technology a particular template applies to, define a capability to represent that, define that capability in project types where it makes sense so the templates show up. We've only done that where needed so far; for example, we did a pass on the WinForms/WPF ones in 16.3.

**Comment by phenning** [comment]
I just tested this by removing the TemplateGroupId from one of our templates and setting the following instead. The template still shows up even though ShowOnlySpecifiedTemplates = 1

`<AppliesTo>DotNetCoreRazor</AppliesTo>`
