### ISSUE TITLE
Provide a standalone demo to illustrate the usage of host-agnostic layer

### ISSUE THREAD

**Issue by javagg** [dotnet/project-system#2560]
Is it possible to integrate this part of work into other c# IDEs?

**Comment by srivatsn** [comment]
@KirillOsenkov weren't you working on an app using the non-VS layers?

**Comment by KirillOsenkov** [comment]
Unfortunately I have nothing that can be used as a public demo.

**Comment by davkean** [comment]
The core layer of CPS, which this project is built on top of, isn't open source, nor redistributable outside Visual Studio. Until then, there's not any benefit to doing this as this project is not reusable without it.
