### ISSUE TITLE
Build time has increased significantly

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2564]
My command-line build time used to float around 40 seconds to build and run tests. It now takes > 3 minutes with the latest in master.

**Comment by davkean** [comment]
tag @jmarolf

**Comment by davkean** [comment]
Looks like we're creating two sets of hives - why?

**Comment by jmarolf** [comment]
We are installing Roslyn vsixes now so that integration tests will work locally.  We shouldn't be installing into two separate hives though, can you post the build output where you see that @davkean?

**Comment by davkean** [comment]
Why are we installing Roslyn VSIXes? Is this their test VSIXes?

**Comment by jmarolf** [comment]
@davkean yes, and the 2.3 roslyn build as we are not running integration tests on 2.3
