### ISSUE TITLE
[regression since 15.2] net core sdk project auto restore does not pop up error list for restore errors

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2574]
_From @mishra14 on July 6, 2017 18:43_

Original bug: https://github.com/NuGet/Home/issues/5509

Moving this here since NuGet is no longer populating the error list for net core sdk projects and it seems more reasonable for the sdk target to pop up the error list.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS 

NuGet version (x.x.x.xxx): 4.3.0.4250

VS version (if appropriate): d15prerel/26627.3006

Worked before? If so, with which NuGet version: 4.2.0.2457 in VS 15.2

## Detailed repro steps so we can see the same problem

1. File New Project -> Net standard class library.

2. Change target framework to netstandard1.4.

3. Close Error list and output windows if open.

4. Edit csproj to add the following - 
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="1.1.3" />
  </ItemGroup>
```

...

### Expected 

The error list should be displayed as in 15.2 - 
![editcsprojin15 2](https://user-images.githubusercontent.com/10507120/27712654-da7edd4c-5cdc-11e7-9a1c-94f89204288c.PNG)

### Actual 

No error list is displayed - 
![editcsprojin15 3](https://user-images.githubusercontent.com/10507120/27712664-e677a34a-5cdc-11e7-844b-e1decf4dfa2a.PNG)

_Copied from original issue: dotnet/sdk#1392_

**Comment by srivatsn** [comment]
_From @mishra14 on July 6, 2017 18:43_

@natidea @srivatsn

**Comment by srivatsn** [comment]
@lifengl - when a background restore completes, we run a resolvepackagedependcies target from a designtime build and that raises some msbuild errors which we report in the error list. CPS reports those errors to the error list. Should we bring up the error list any time there's an error that is logged from design-time build. We should probably do that by respecting `Tools->Options->Projects and solutions->Always show error list if build finishes with errors`

**Comment by lifengl** [comment]
I guess we should try the user experience and may need adjust the logic based on that.  Design time build is not started by the developer directly, and we actually do lots of them in the background, so bring the error list out once a while could be very annoying too.  Maybe we should bring it when it switches from no error state to errors?

**Comment by davkean** [comment]
@srivatsn NuGet used to set the Error List to forefront during restore and it was very annoying. Agree with @lifengl, I don't think we should do anything here.

**Comment by davkean** [comment]
Make note, I don't believe the legacy project system brings the Error List forward when it logs a warning/error.

**Comment by abpiskunov** [comment]
+1 its annoying, there should have been a setting to turn this behavior on/off..

Thanks,
Anton

On Jul 6, 2017, at 1:45 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


Make note, I don't believe the legacy project system brings the Error List forward when it logs a warning/error.

**Comment by rrelyea** [comment]
@damianedwards - you were the original filer of this issue. Please take a look at this debate, and make your case, if needed.

**Comment by DamianEdwards** [comment]
When I reported the issue, the Dependencies node in Sln explorer was **not** showing the error, not even the warning icon, so the error was effectively invisible. Of the Sln explorer issue is fixed (such that it now shows the NuGet restore error) then popping the error list is not needed.

**Comment by davkean** [comment]
Okay, I'm going to close this issue. The behavior will remains as is; we'll only pop the error list if build finishes with errors and "Always show error list if build finishes with errors" is turned on.
