### ISSUE TITLE
How to trigger project load refresh? 

### ISSUE THREAD

**Issue by forki** [dotnet/project-system#2577]
If I edit the csproj file directly (like adding a package reference) VS triggers a reload and restores the package in the back. This is a really nice feature. 

Is there a way to do the same thing on a change in a different file? For paket all project references are done in paket.references. If I save that files VS should reload the project as well. Is there any MSBuild trick to make paket.references a dependency of the corresponding csproj? 

Cc @davkean @enricosada @dsplaisted

**Comment by srivatsn** [comment]
You probably need to do something like the [ProjectAssetFileWatcher](https://github.com/dotnet/project-system/blob/ed21d8f688d4d576bdbbdc42abd440928e5bb0bf/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs) which listens to changes to the assets file and [marks the project as dirty and needing an evaluation\designtime build](https://github.com/dotnet/project-system/blob/ed21d8f688d4d576bdbbdc42abd440928e5bb0bf/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs#L208). 

When the DT build for ResolvePackageReferences runs I assume you've hooked in your targets there to do a Paket restore.

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/blob/master/.paket/Paket.Restore.targets#L19 is how we hook into. Just standard MSBuild targets - no "code"

**Comment by srivatsn** [comment]
Yep, the CollectPackageReferences target will run when the project is marked dirty using the method above, which will then kick off your targets.

**Comment by forki** [comment]
So I would hook that watcher into my targets file?

**Comment by srivatsn** [comment]
No I don't think there's a msbuild way to do this. You need a vs extension that calls that API to mark the file as dirty. We [talked about](https://github.com/dotnet/project-system/issues/653#issuecomment-256781341) a feature to allow tagging msbuild items in a way to cause reevaluation but there's no such thing yet.

**Comment by forki** [comment]
Oh no. VS extension is absolutely no go for me here. But thanks for trying to help me here

**Comment by enricosada** [comment]
@srivatsn if i auto-import a .target file, who define target and set that as `BuildDependsOn` (or better `CollectPackageReferences` or what's is called), to invalidate targets based on the uptodate check of that file, can work?

**Comment by srivatsn** [comment]
I am not following the suggestion - the scenario here is that the user edits the paket.references file, we want to trigger a restore. How will the .target file change when paket.references is edited?

**Comment by davkean** [comment]
@srivatsn They kick off a target that generates a new targets file, which in turn will kick off _another_ reevaluation and build. It would be better from a perf perspective if you produced the contents of the targets file dynamically instead of statically.

I can't see a way of making this work without a VS extension.

**Comment by natemcmaster** [comment]
I came across the same issue, too. It would be nice if there were an item group or well-known property which would let us specify additional files that should be watched by the project system.

FYI - I came across this because changes to `global.json` do not automatically trigger and update. You have to close/open VS or touch each .csproj file to trigger the refresh. Perhaps this is an oversimplification of the issue, but it seems like there ought to be some way to do this via MSBuild. e.g.
```xml
    <PropertyGroup>
      <GlobalJsonFile>$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildProjectDirectory), global.json))\global.json</GlobalJsonFile>
    </PropertyGroup>
    <ItemGroup>
       <DesignTimeProjectFiles Include="$(GlobalJsonFile)" Condition="Exists('$(GlobalJsonFile)')" />
    </ItemGroup> 
```

**Comment by srivatsn** [comment]
Ya that would be an useful feature. I've logged a bug on CPS to track the request - https://devdiv.visualstudio.com/DevDiv/_workitems?id=473913&fullScreen=false&_a=edit
