### ISSUE TITLE
Constant UI hangs in VS

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#2579]
I'm on 

![image](https://user-images.githubusercontent.com/4564579/27988102-cc3213d2-63ce-11e7-828a-62c580af7027.png)

And i'm getting constant UI hangs.

ETL trace reveals teh following:

![image](https://user-images.githubusercontent.com/4564579/27988108-ea39e526-63ce-11e7-9b3b-732eed3c001b.png)

The UI thread also shows this:

![image](https://user-images.githubusercontent.com/4564579/27988114-017441fa-63cf-11e7-8160-299bf7ffb715.png)

This matches what i see in VS where i see hte message in the lower left saying it's saving the file-restore data (i.e. the copies of files that are saved in case VS crashes).

Something about VS and the project system is making such operations absolutely awful.  Nearly unusable.  Will upload ETL so that this can be investigated.

**Comment by CyrusNajmabadi** [comment]
Tagging @srivatsn @davkean

**Comment by CyrusNajmabadi** [comment]
trace is here: https://drive.google.com/file/d/0ByISdSEZ09PBdzl5RE9jb3ppTE0/view?usp=sharing

**Comment by davkean** [comment]
I had a look, I'm not really sure what's going on here - going to move it to CPS as they own the code in question.

**Comment by davkean** [comment]
Closed in lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=462430&fullScreen=false&_a=edit.
