### ISSUE TITLE
Add Existing project should default the explorer context to where the sln is

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/project-system#2580]
Im assuming this is the right repo to file this. When I right click->add->Existing project. The dialog defaults me to a random place under my user profile. I would expect people most often want to add things relative to their sln and the dialog should default to that.

**Comment by srivatsn** [comment]
This is controlled by the solution tree. Moved to https://devdiv.visualstudio.com/DevDiv/_workitems?id=469187&fullScreen=false&_a=edit
