### ISSUE TITLE
VisualStudio does not support MsBuild macros in TargetFrameworks

### ISSUE THREAD

**Issue by nothrow** [dotnet/project-system#2581]
I have following setting (reproducible example, I wanted to have the TargetFrameworks set in single file for all of the projects):

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworksForProject>netcoreapp1.1;net461</TargetFrameworksForProject>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworksForProject)</TargetFrameworks>
  </PropertyGroup>

</Project>
```

but VS cannot cope with that. Project builds, but VS reports missing references, and does not show correct framework.

![vsissue](https://user-images.githubusercontent.com/5787800/28024511-36ee4114-6591-11e7-8321-9600dfcafed8.png)

**Comment by davkean** [comment]
This has been fixed in 15.3: https://github.com/dotnet/project-system/issues/547.
