### ISSUE TITLE
Dependencies Node does not display Error icon where expected

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2582]
**Repro**

Given the following Console App project

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NuGet.Commands" Version="4.0.0" />
    <PackageReference Include="NuGet.Packaging" Version="3.5.0" />
  </ItemGroup>

</Project>
```

The resulting package downgrade diagnostics show up as errors in the Error List, but as Warnings in the Dependencies node:

![image](https://user-images.githubusercontent.com/7732033/28035840-ea12287c-656a-11e7-8d35-572a15cf6723.png)

This is despite the fact that the model attempts to distinguish between Errors and Warnings: [DiagnosticDependencyModel.cs#L38-L49](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Models/DiagnosticDependencyModel.cs#L38-L49)

**Comment by natidea** [comment]
Looks like this is just a missing rule in ResolvedPackageReference.xaml. Fixing with:

```xml
    <StringProperty Name="Severity" Visible="True" ReadOnly="True" />
```

results in:

![image](https://user-images.githubusercontent.com/7732033/28037175-68e51caa-656f-11e7-8fec-288ae9ab6d28.png)

**Comment by terrajobst** [comment]
Also odd that the aggregation doesn't work. I'd assume the spine to show error icons. Otherwise, the user is going to hunt for the errors :-)

**Comment by natidea** [comment]
Currently, the Dependencies tree only maintains resolved/unresolved state for the nodes in the spine. So those nodes are essentially being marked as unresolved, because they contain a diagnostic. I think in future work, we would need to add states for Diagnostic-Error and Diagnostic-Warning. In fact, we should probably stop using the Warning icon for "unresolved" nodes and come up with a more subtle icon. That way, warning and error icons clearly refer to diagnostics, and it would help improve the experience in https://github.com/dotnet/project-system/issues/2079

**Comment by abpiskunov** [comment]
We did have this discussion with Sri to have two or three state nodes, ended up with two state, check with him for more details ....

Thanks,
Anton

On Jul 10, 2017, at 4:25 PM, Nat Ayewah <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently, the Dependencies tree only maintains resolved/unresolved state for the nodes in the spine. So those nodes are essentially being marked as unresolved, because they contain a diagnostic. I think in future work, we would need to add states for Diagnostic-Error and Diagnostic-Warning. In fact, we should probably stop using the Warning icon for "unresolved" nodes and come up with a more subtle icon. That way, warning and error icons clearly refer to diagnostics, and it would help improve the experience in #2079<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fproject-system%2Fissues%2F2079&data=02%7C01%7Canton.piskunov%40microsoft.com%7Cd4185fcd6a2345f1aab308d4c7eae8a1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636353259116714656&sdata=XEUAoHMabwqoBkPrh92UXABvwOylkzKHxpigne6CDi4%3D&reserved=0>

**Comment by srivatsn** [comment]
If I remember right we had said that there weren't many errors that could show up in the tree. Now that NuGet has added the ability to set WarnAsError as well we should probably introduce three states.

**Comment by abpiskunov** [comment]
Sounds, good. We did have icons for error in Dev14 - who ever works in this item ping me to get them ..

**Comment by terrajobst** [comment]
What would this mean for the spine though?

**Comment by drewnoakes** [comment]
Testing this again, we now see no diagnostics at all (as per #3780):

![image](https://user-images.githubusercontent.com/350947/60575856-a4295f80-9dbf-11e9-9612-8870d9582066.png)

The relevant info is available in `project.assets.json`:

```json
  "logs": [
    {
      "code": "NU1605",
      "level": "Error",
      "message": "Detected package downgrade: NuGet.Packaging from 4.0.0 to 3.5.0. Reference the package directly from the project to select a different version. \r\n Issue2582DepNodeErrorIcons -> NuGet.Commands 4.0.0 -> NuGet.Client 4.0.0 -> NuGet.Packaging (>= 4.0.0) \r\n Issue2582DepNodeErrorIcons -> NuGet.Packaging (>= 3.5.0)",
      "libraryId": "NuGet.Packaging",
      "targetGraphs": [
        ".NETCoreApp,Version=v2.0"
      ]
    },
    {
      "code": "NU1605",
      "level": "Error",
      "message": "Detected package downgrade: NuGet.Packaging from 4.0.0 to 3.5.0. Reference the package directly from the project to select a different version. \r\n Issue2582DepNodeErrorIcons -> NuGet.Commands 4.0.0 -> NuGet.DependencyResolver.Core 4.0.0 -> NuGet.Protocol.Core.v3 4.0.0 -> NuGet.Packaging (>= 4.0.0) \r\n Issue2582DepNodeErrorIcons -> NuGet.Packaging (>= 3.5.0)",
      "libraryId": "NuGet.Packaging",
      "targetGraphs": [
        ".NETCoreApp,Version=v2.0"
      ]
    },
    {
      "code": "NU1605",
      "level": "Error",
      "message": "Detected package downgrade: NuGet.Packaging from 4.0.0 to 3.5.0. Reference the package directly from the project to select a different version. \r\n Issue2582DepNodeErrorIcons -> NuGet.Commands 4.0.0 -> NuGet.DependencyResolver.Core 4.0.0 -> NuGet.Repositories 4.0.0 -> NuGet.Packaging (>= 4.0.0) \r\n Issue2582DepNodeErrorIcons -> NuGet.Packaging (>= 3.5.0)",
      "libraryId": "NuGet.Packaging",
      "targetGraphs": [
        ".NETCoreApp,Version=v2.0"
      ]
    }
  ]
```

However no items of type `Diagnostic` are being provided by the `IProjectSubscriptionUpdate`.

Once #3780 is fixed, I will cycle around to look at this.
