### ISSUE TITLE
Conditional references in csproj files causes error when condition is false

### ISSUE THREAD

**Issue by Reza1024** [dotnet/project-system#2583]
I am trying to have a solution with two projects and reference on in the other one only in Debug builds but referencing under conditions causes compile error on Release although it compiles just fine on Debug. It is very easy to reproduce:

```
1>------ Build started: Project: DebugTools, Configuration: Release Any CPU ------
1>DebugTools -> [Address of Solution]\DebugTools\bin\Release\netstandard1.4\DebugTools.dll
2>------ Build started: Project: MainLibrary, Configuration: Release Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for '[Address of Solution]\DebugTools\DebugTools.csproj'. This can indicate a missing project reference.
2>Done building project "MainLibrary.csproj" -- FAILED.
========== Build: 1 succeeded or up-to-date, 1 failed, 0 skipped ==========
```
Here is the content of the content of the csproj files. I am using VS 15.2 (26430.14)

**DebugTools.csproj**
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard1.4</TargetFramework>
	</PropertyGroup>
</Project>
````

**MainLibrary.csproj**
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard1.4</TargetFramework>
	</PropertyGroup>
	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<ProjectReference Include="..\DebugTools\DebugTools.csproj" />
	</ItemGroup>
</Project>
```

**Comment by srivatsn** [comment]
If the solution is closed and reopened after changing the configuration to Release (such that the config is Release when the solution is loaded) then it builds fine. It looks like switching configurations doesn't change the set of project references we track for a project.

**Comment by Pilchie** [comment]
Does this work on command line builds?  @nguerrera or @lifengl - where should this be moved?

**Comment by nguerrera** [comment]
This doesn't work on the command line either. I think it's a fundamental issue with the fact that nuget restore shares assets file between configurations. I don't think SDK nor CPS can fix this either. It's more of a nuget issue.

**Comment by Pilchie** [comment]
This issue was moved to NuGet/Home#6757
