### ISSUE TITLE
Address suppressed xunit warnings

### ISSUE THREAD

**Issue by tmat** [dotnet/project-system#2584]
The RepoToolset uses the latest xunit that comes with an analyzer that currently reports quite a few warnings. For now these are suppressed.

**Comment by davkean** [comment]
@tmat Where/how are the warnings suppressed?

**Comment by tmat** [comment]
Not yet. Coming soon.

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/project-system/pull/2802
