### ISSUE TITLE
.NET core web project hangs on file system change

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2589]
From [VS Feedback](https://developercommunity.visualstudio.com/content/problem/76634/net-core-web-project-hangs-on-file-system-change.html) - ( [Internal Link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/460364) )

This may be similar to slowness reported in https://github.com/dotnet/project-system/issues/2588 or related to up-to-date checks. 

From customer:
- - - - -
We are currently porting a large web project to .NET core. We're using VS2017 15.3.0 Preview 3.0 and targeting .NET Core 2.0. I think this might be related to the "up to date" checks .NET core projects do, so I think this would have been an issue in the current version of .NET core and VS2017 had we chosen to port to .NET core 1.6 (but I haven't confirmed that).

STEPS
1) Open a large .NET core web project. Ours has about 12,600 files, plus has around 30 bower and 30 npm packages.
2) Wait for VS2017 to calm down.
3) Open Windows Explorer and navigate to a directory in the project.
4) Copy and paste a file (I've been making a copy of an Index.cshtml and pasting it in the same directory as Index-Copy.cshtml).
5) Go back to VS2017.
6) Click anywhere in Solution Explorer.
7) VS2017 will hang and say "Not Responding" for a few minutes.

I've attached a PerfView trace using the default settings while I executed these steps. If you need me to run it with different settings, please let me know.

OBSERVATIONS
- The more files that are below the root directory the longer it hangs, even if they are not part of the project.
- Using Procmon.exe to monitor file system events, I can see VS scans every directory below the project root several times while it is hung up. I tried adding directories to various exclusion lists I was aware of, but VS still scanned these directories.
- If I use VS Solution Explorer to move or delete an entire directory, I incur this per file. I can hit delete on a list of files and VS hangs. Open Windows Explorer and go to that directory. Over the course of 10 minutes you see each file disappear one at a time.
- VS2017 sits around 15% CPU, but is totally locked up.
- MSBUILD CPU usage spikes a few times while it's hanging, which is why I think it might be related to the "up to date" checks. 
- - - - -

**Comment by jasselin** [comment]
Same thing here: https://developercommunity.visualstudio.com/content/problem/73964/visual-studio-msbuild-scans-every-file-in-an-aspne.html

Related MSBuild issue: https://github.com/Microsoft/msbuild/issues/2238

**Comment by davkean** [comment]
Duping this against the MSBuild issue Microsoft/msbuild#2238
