### ISSUE TITLE
DuplicatedDependenciesSnapshotFilter.BeforeAdd is allocating 1.4% of open solution

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2596]
``` C#
       // if found node with same caption, or if there were nodes with same caption but with Alias already applied
            var shouldApplyAlias = (matchingDependency == null)
                ? topLevelBuilder.Any(
                    x => !x.Id.Equals(dependency.Id)
                         && x.ProviderType.Equals(dependency.ProviderType, StringComparison.OrdinalIgnoreCase)
                         && x.Caption.Equals(
                             string.Format(CultureInfo.CurrentCulture, "{0} ({1})", dependency.Caption, x.OriginalItemSpec), <!-- 1.4 %
                                StringComparison.OrdinalIgnoreCase))
```

![image](https://user-images.githubusercontent.com/1103906/28126340-8c0de870-676c-11e7-9406-dbce4fa47268.png)

**Comment by abpiskunov** [comment]
FYI - this logic i ported form original References code and did not see good way to avoid formatting this : dependency.Caption, x.OriginalItemSpec...

**Comment by davkean** [comment]
One way is to do string comparison without actually creating an intermediate string.

**Comment by abpiskunov** [comment]
that is the trick there - we are trying to find an element X with caption equal to "given dependency"'s Caption + element X's (itemspec). This is dynamic information, which tells you if there is an element with same caption but other item spec already and you need to change caption for given dependency also to match that pattern..  How would you cache it?

**Comment by davkean** [comment]
I didn't say cache it, I mean that instead of combining the string together and comparing that, just do a comparison that doesn't allocate via one of the [String.Compare overloads](https://msdn.microsoft.com/en-us/library/cc190416(v=vs.110).aspx) that take an offset/length. Or compare the other parts of the dependency that make up the "alias". Just don't allocate doing it.

**Comment by abpiskunov** [comment]
I see

**Comment by davkean** [comment]
This is now up to 6.6% of all allocations.

**Comment by Pilchie** [comment]
Fixed by https://github.com/dotnet/project-system/pull/2931
