### ISSUE TITLE
Wrong package factory guid in SLN file can cause build issues in VS

### ISSUE THREAD

**Issue by attilah** [dotnet/project-system#2601]
When I merged Orleans sources into a single source tree, we were using old style csproj files and new styles in vNext. Everything worked when built from commandline, but from VS the projects looked very different and was not buildable.

The thing that caused it is that TargetFramework was populated from an external props file and was not present in the csproj itself.

After some investigation help from @davkean  and @jviau it turned out that in the SLN file Orleans project had the right project factory GUID: {9A19103F-16F7-4668-BE54-9A1E7A4F7556}, while OrleansRuntime had a different value: {FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}. The later one triggered Visual Studio to use the old style project loader and not CPS.

In the old style projects that is a requirement to have the TargetFramework defined within the csproj file itself.

The legacy project system doesn’t display files that aren’t listed in the project that’s and it caused to show the project as an empty one. The legacy project system doesn’t support showing target frameworks that it doesn’t know about – that’s why properties is wrong.

The dependencies node showed warning, which maybe a different issue and needs further investigation.

![project-view](https://user-images.githubusercontent.com/230432/28152245-4d81d728-6754-11e7-9d81-0e0c5eb0cc6a.jpg)

The situation I ended up with this is that previously the solution was used in VS2015 and at some point different people from the team started to use VS2017 and also manual editing of csproj files are involved without removing and re-adding them to the solution.

What VS did is that it detected the old project factory guid and "migrated" the project but it ended in adding ToolVersion="15.0" to the root element, nothing else, the project stayed not buildable.

**Comment by srivatsn** [comment]
The behavior is that if the {9A19103F-16F7-4668-BE54-9A1E7A4F7556} is in the sln, then it will always load with new project system.

If the guid is {FAE04EC0-301F-11D3-BF4B-00C04F79EFBC} then it will look for a TargetFramework property in the csproj file (not in any imported file) and if one is present it loads with new PS else loads with old PS. https://github.com/dotnet/project-system/issues/1358 tracks the issue of needing to define TargetFramework in the csproj itself.

Given that behavior (more details - https://github.com/dotnet/project-system/blob/master/docs/opening-with-cps.md) does that explain the behavior seen here or is there anything futher to be explained\debugged\fixed?

**Comment by attilah** [comment]
I think the Developer eXperience can be enhanced, at least with the error message, as a plus a SLN guid changer function to the new one.

**Comment by davkean** [comment]
Let's make https://github.com/dotnet/project-system/issues/1358 track the experience here around accidentely opt'ing in/out of the new project system.
