### ISSUE TITLE
Operator nameof is incorrectly highlighted in red

### ISSUE THREAD

**Issue by arespr** [dotnet/project-system#2613]
**Version Used**: 
Visual Studio 14.0.25431.01 Update 3
			Visual Strudio 15.2 (26430.15)
**Steps to Reproduce**:
![obraz](https://user-images.githubusercontent.com/3482384/28208380-a18ff63a-688d-11e7-8f73-85859a83b2be.png)

**Code:**:

```csharp
enum EnumExample
{
	Value1
}
public void DoSomething(Action action)
{
}

public void NameOfOperatorError()
{
	var tmp1 = nameof(EnumExample.Value1);
	
	DoSomething(() =>
	{
		var tmp2 = nameof(EnumExample.Value1);

		int a = 3;
		int b = 3;
		
		var c =

	});
}
```

Edited by @sharwell: Fixed formatting of code block

**Comment by srivatsn** [comment]
This issue was moved to dotnet/roslyn#21071
