### ISSUE TITLE
TargetFramework fails to differentiate by NuGet profile name

### ISSUE THREAD

**Issue by sharwell** [dotnet/project-system#2617]
### Steps to reproduce:

1. Create a new SDK project
2. Set the target frameworks to `net35;net35-client` (see note below)
3. Open the project in Visual Studio

Due to limitations in the target framework inference, the following block needs to be used for step 2 above.

```xml
<PropertyGroup>
  <TargetFrameworks>net35;net35-client</TargetFrameworks>
</PropertyGroup>
<PropertyGroup Condition="'$(TargetFramework)' == 'net35-client'">
  <TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>
  <TargetFrameworkVersion>v3.5</TargetFrameworkVersion>
  <TargetFrameworkProfile>Client</TargetFrameworkProfile>
</PropertyGroup>
```

### Expected results:

Solution Explorer shows two nodes under Dependencies: one for .NETFramework 3.5, and another for .NETFramework 3.5 (Client).

### Actual results:

Solution Explorer only shows one node under Dependencies due to a caption collision in [`TargetFramework.FriendlyName`](https://github.com/dotnet/project-system/blob/fa074d228dcff6dae9e48ce43dd4a3a5aa22e8f0/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/TargetFramework.cs#L24).

**Comment by drewnoakes** [comment]
Still repros.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net35;net35-client</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net35-client'">
    <TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v3.5</TargetFrameworkVersion>
    <TargetFrameworkProfile>Client</TargetFrameworkProfile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Foo1" Version="1.0" Condition="'$(TargetFrameworkProfile)' == 'Client'" />
    <PackageReference Include="Foo2" Version="2.0" Condition="'$(TargetFrameworkProfile)' != 'Client'" />
  </ItemGroup>
</Project>
```

Gives:

![image](https://user-images.githubusercontent.com/350947/60182897-882a3900-9868-11e9-853d-d4efeb99181f.png)
