### ISSUE TITLE
During async loading, we shoudl assume the compiler version is the 'latest' not the 'default'.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#2621]
During async solution loading CPS doesn't know what version of the compiler to create.  So CPS (or Roslyn, not sure) decides to just create a compiler with the 'default' version.  This leads to unpleasant errors being shown during load like:

![image](https://user-images.githubusercontent.com/4564579/28282479-6ccb709c-6adf-11e7-947b-36e8d782bae7.png)

These errors go away once the project context is finally determined.  But this may take many minutes and the experience is poor.

instead of picking 'default' we should pick 'latest' to have the least amount of errors reported during this time.

**Comment by srivatsn** [comment]
This would be in Roslyn. The project system doesn't interpret the options - it simply sends the commandline to roslyn. Before the commandline is sent, I assume, getting a compilation would use whatever is the default LangVersion

**Comment by srivatsn** [comment]
This issue was moved to dotnet/roslyn#21070
