### ISSUE TITLE
"Add Reference" with multiple NuGet packages and references does multiple DT builds even with batch APIs

### ISSUE THREAD

**Issue by jainaashish** [dotnet/project-system#2630]
Scenario is something like when you're installing or updating multiple NuGet packages at solution level (projects with packages.config), which remove and add many assembly references as part of this single operation, then each AddReference trigger a different DT build (ResolveAssemblyReference) to create a reference dte objects. And this happens even after these AddReference calls are inside start/end batch apis (which only works to reduce triggering intellisense builds for now).

This is one of the top Visual Studio UI delay hit at watson (and top hit for NuGet) across VS versions. https://ddwatson.cloudapp.net/?q=q%3ANuGetUIDelay%20q%3ADev15.3%20&f=075ddea2-53af-34e3-4290-d84242478ab2&e=UIDelay 

I also repro'd this locally and etl logs can be found at \\scratch2\scratch\asja\AddReference Perf ETL logs

As discussed in email, we already know what the issue is and have some ideas to get this fixed.

**Comment by jainaashish** [comment]
@davkean @panopticoncentral

**Comment by davkean** [comment]
The request here is avoid kicking off a ResolveReferences design-time build every time a reference is added when StartBatchEdit has been called.

**Comment by basoundr** [comment]
@jainaashish I dont see any folder named `asja` under `\\scratch2\scratch`. There might be a typo there.

**Comment by natidea** [comment]
This has been linked to [Feedback Item](https://developercommunity.visualstudio.com/content/problem/81415/visual-studio-2017-laggy-unresponsive-slow.html) [465912](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/465912) and Bug [467044](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/467044)

**Comment by Pilchie** [comment]
Moving to 15.7 based on risk.  We have most of the API ready here, but would rather get it into 15.7 early than rush it into 15.6 late.

**Comment by Pilchie** [comment]
@tmeschter this is merged, right?

**Comment by tmeschter** [comment]
@Pilchie The project system changes are in, but I'm still trying to get the NuGet changes in. :-(

**Comment by tmeschter** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/pull/2066.
