### ISSUE TITLE
Performance degradation after converting a large solution to the new project system

### ISSUE THREAD

**Issue by aelij** [dotnet/project-system#2631]
I've recently converted a large solution (99 projects) to the new project system. I've seen performance issues similar to what's described in #2297. In addition, VS freezes a lot during build (even with verbosity set to Minimal).

I've tried both in 15.2 ([issue](https://developercommunity.visualstudio.com/content/problem/82389/performance-degradation-after-converting-a-large-s.html)) and 15.3 Preview 4 ([issue](https://developercommunity.visualstudio.com/content/problem/82391/performance-degradation-after-converting-a-large-s-1.html)). 15.3 seems to perform better, but still not as good as the previous PS.

**Comment by davkean** [comment]
@aelij Do you have have source that we can look at? If not, can you please Help -> Send Feedback -> Report a Problem -> Record the performance issues you are running into and point them from here?

**Comment by aelij** [comment]
@davkean I’m no longer actively working on this project, but I’ll see what I can do.

**Comment by Pilchie** [comment]
Closing as it doesn't look like we have more information on this specific solution.
