### ISSUE TITLE
Adding a project reference to Roslyn takes a long time

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2634]
From opening the dialog, to adding a project reference, takes a very long time in Roslyn.sln.

**Comment by Pilchie** [comment]
Going to move this to 15.7, as this isn't a core inner-loop operation.  @davkean did you ever look at a trace to see what the bottlenecks are here?  Was it evaluation time that should be improved in 15.5 and 15.6 anyway?

**Comment by kvenkatrajan** [comment]
Lower in priority - as per productivity team project reference is added very rarely and issue not noticeable
