### ISSUE TITLE
New Startup Objects do not populate Startup Object list

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2635]
RE: #763 #2238 [VSFeedback 77772](https://developercommunity.visualstudio.com/content/problem/77772/cannot-select-startup-object-for-multiple-classes.html)

**Repro:**

- Create a .NET Core Console App.
- Open Project Properties to confirm Startup Object lists default main:

![image](https://user-images.githubusercontent.com/7732033/28396090-f18d7b52-6cad-11e7-9e0b-e769cf63e34c.png)

- Add a second class with a main method:
```csharp
    class Program2
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
```

**Expected:** 
Project Properties shows additional startup object:

![image](https://user-images.githubusercontent.com/7732033/28396173-8f984f02-6cae-11e7-8e06-af36aad920d4.png)

**Actual:**
Only original is shown, even after closing and reopening properties page

**Workaround:**
Unload and reload project, or close and reopen solution.

**Comment by melytc** [comment]
This is fixed in 17.3 and later versions!
