### ISSUE TITLE
IVsProjectBuildSystem.EndBatchEdit() call locking dll post package install

### ISSUE THREAD

**Issue by mishra14** [dotnet/project-system#2643]
Original issue: https://github.com/NuGet/Home/issues/5609

## Repro steps (besides the one in the original bug)

1. File New Project -> Windows Classic Desktop -> Class Library (.NET Framework)

2. Install Newtonsoft.Json through NuGet PM UI

## Problem

After the process of installation, NuGet invokes `IVsProjectBuildSystem.EndBatchEdit()` [here](https://github.com/NuGet/NuGet.Client/blob/a87d32b15786d47809449c69b69b1f38b3c8f1a4/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/VsMSBuildProjectSystem.cs#L607). Immediately after the package dll (lib\net45\newtonsoft.json.dll) gets locked.
This causes a problem in cases when a template (as in one from the original bug's repro steps) tries to uninstall a newly installed package. The result is that the lock on the file prevents it from being deleted or overwritten by another project's installation.

## Information 

VS: d15rel 26718.0
This seems to be a regression in the End-to-End behavior since 15.2

**Comment by davkean** [comment]
Don't think this is right place to investigate - EndBatchEdit is going to do a design-time build in the VS process, and it's likely that something is the build is loading/locking the file.

**Comment by mishra14** [comment]
@davkean  what is the best place for filing this? Any pointers would be great.

**Comment by davkean** [comment]
I think you need to figure out what's stack is loading the binary and start from there.
