### ISSUE TITLE
Solution Folders are included in the loaded project count

### ISSUE THREAD

**Issue by tannergooding** [dotnet/project-system#2649]
It appears that solution folders are included in the loaded project count for some scenarios (such as displaying the project load/unload dialog).

![image](https://user-images.githubusercontent.com/10487869/28491952-9077af38-6eae-11e7-9179-76c0064817f6.png)

In the picture above, it states that it is loading 67 projects. However, my solution contains 28 projects and 39 solution folders, so this is skewing the numbers quite a bit.

**Comment by davkean** [comment]
Please file this against Project & Telemetry - we have zero influence over this.

**Comment by srivatsn** [comment]
Closing as external.

**Comment by tannergooding** [comment]
What's the area path for this?

**Comment by srivatsn** [comment]
DevDiv\VS Platform\VS IDE\Project and Telemetry
