### ISSUE TITLE
You cannot use TAB to navigate from App Designer titles onto pages

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2650]
The TAB'ing logic is broken:

1. Open AppDesigner
2. Keep pressing SHIFT+TAB until you navigate onto the page title
3. Press TAB

**Expected:** To navigate back onto the page
**Actual:** You navigate to the next tab. While you can use TAB to navigate onto the page titles, you cannot use TAB to get off it

Example of what happens:
![badtab](https://user-images.githubusercontent.com/1103906/28509033-b31453ae-7082-11e7-9a72-56670bd7121d.gif)

Example of what's expected:
![goodtab](https://user-images.githubusercontent.com/1103906/28509034-b4cbf170-7082-11e7-81ab-9146908848dd.gif)

**Comment by tannergooding** [comment]
This will need follow up with the accessibility folks. It was indicated to me that the current behavior was the expected behavior (that is, tabbing on the page selection panel should navigate between the available pages, rather than back to the active page).

**Comment by etbyrd** [comment]
This was fixed by: https://github.com/dotnet/project-system/pull/4331
