### ISSUE TITLE
UI delay when opening RoslynDev hive with Roslyn.sln open

### ISSUE THREAD

**Issue by rchande** [dotnet/project-system#2652]
Check out and build the Roslyn master branch. 
Open Roslyn.sln in the Dev15 main hive and wait for the project to finish opening.
Start a new instance of VS in the RoslynDev hive `devenv /rootsuffix RoslynDev`.
Open a C# project in the new VS instance.

For some reason, doing this causes the VS with Roslyn open to hang. It looks like opening a project in the other hive is triggering the project system to reload Roslyn.sln in the main hive. Note that I don't see this if both instances are running in the same hive.

I see lots of blocked time in:
```C#

Name
--
\|                                         + microsoft.visualstudio.projectsystem!Microsoft.VisualStudio.ProjectSystem.TaskDelayScheduler+<ThrottleAsync>d__24.MoveNext()
\|                                          + microsoft.visualstudio.projectsystem.vs.implementation!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.ProjectReloadManager.<ScheduleProjectReload>b__43_0(value class System.Threading.CancellationToken)
\|                                           + mscorlib!AsyncTaskMethodBuilder.Start
\|                                            + microsoft.visualstudio.projectsystem.vs.implementation!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.ProjectReloadManager+<<ScheduleProjectReload>b__43_0>d.MoveNext()
\|                                             + microsoft.visualstudio.projectsystem.implementation!ProjectMultiThreadedService.ExecuteSynchronously
\|                                              + microsoft.visualstudio.threading.ni!JoinableTask.CompleteOnCurrentThread
\|                                               + microsoft.visualstudio.threading.ni!JoinableTaskFactory.WaitSynchronously
\|                                               \|+ microsoft.visualstudio.threading.ni!JoinableTaskFactory.WaitSynchronouslyCore


```

**Comment by srivatsn** [comment]
Is the project being opened in the RoslynDev hive part of Roslyn.sln? The project reloader should only be called if any of the csprojs in Roslyn.sln change - if you let this happen do you see any changes to any csproj in roslyn.sln?

/cc @jviau

**Comment by rchande** [comment]
It's a totally unrelated project.

**Comment by jviau** [comment]
Is opening the unrelated project causing a change to a .targets or .props file shared by a project in Roslyn.sln?

**Comment by davkean** [comment]
@rchande I believe I understand this - this is the compiler extension generating a new targets file in AppData. We're reloading based on it, we have another bugs that are tracking the performance of this reloading but I'll move this over to Roslyn.

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn#21838
