### ISSUE TITLE
Adding TFM back after removing it doesn't work

### ISSUE THREAD

**Issue by enshuoh** [dotnet/project-system#2657]
Repro:
1.	Start with a multi-TFM solution like (\\mlangfs1\public\enhsu\MTFM)
2.	Remove a TFM (net461)
3.	Add same TFM(net461) back

![capture0](https://user-images.githubusercontent.com/2121569/28549870-fa906fd8-7091-11e7-9fa1-56ebc89b4a18.PNG)
![capture1](https://user-images.githubusercontent.com/2121569/28549871-fb822972-7091-11e7-81de-b29bcdc04611.PNG)
![capture2](https://user-images.githubusercontent.com/2121569/28549895-18269d2e-7092-11e7-9677-f64851d5d46a.PNG)
As you can see in screenshots, net461 is successfully removed but not successfully added back.

As LUT relies on the WorkspaceChanged event, I checked the workspace and event sequence. Actually, the net461 project is added back to the solution with the same project id as before but with no document in there. There will be one ProjectAdded event and multiple ProjectChanged events for the project but no DocumentAdd or DocumentChanged events for it after net461 is added back to TargetFrameworks. The current solution in workspace also has this net461 project with no document, which is consistent with the solution in the WorkspaceChanged event.

**Comment by davidwengier** [comment]
This no longer repros
