### ISSUE TITLE
Visual Studio locking .NET Standard 1.4 output dll

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2659]
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/62091/visual-studio-devenvexe-keeps-locking-my-net-stand.html) | [Ticket 441985](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/441985)

> Every now and then, devenv.exe locks my output DLL for my .NET Standard Library. Which means it can't compile it, because the 10 retry mechanism kicks in and fails. My app is not running, using SysInternal Handle.exe reveals the my current devenv.exe process if locking the file with a handle. Cleaning the .NET Standard project seems to be the workaround, but it's getting old, because it happens on about every 10th build. 

Reported on VS2017 15.2 (15.0.26430.6)

**Comment by SomeAnon42** [comment]
I wonder if there's any workaround, cause that happens all the time after migrating to the new project system. I could share my solution if needed.
![lock](https://user-images.githubusercontent.com/6377116/31861560-25353646-b738-11e7-9992-eb071f8b2f2f.PNG)

Reproducible with both 15.4.1 and 15.5 Preview 1.

**Comment by zebel** [comment]
This is too annoying! Come on MS this bug has been around too long with even previous versions of VS!

**Comment by jmarolf** [comment]
@SomeAnon42 could I get access to your solution please?

**Comment by Pilchie** [comment]
Closing as no repro for now - as we haven't been able to make progress here.
