### ISSUE TITLE
Codeanalysis property page.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#266]

**Comment by ruant** [comment]
Is this planned to be done?

**Comment by prbans** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/issues/3129

> @mavasani when researching editorconfig, I wasn't able to find how to enforce it during CI or produce build time errors across all files. I was only able to detect errors on files that were currently open in VS2017. I believe the documentation also states that editorconfig does not support static code analysis. Do you know if either of these features will eventually make it to editorconfig files?
I believe that implementing dotnet/project-system#266 may help bridge the gap until editorconfig is ready

**Comment by drewnoakes** [comment]
This was addressed in #5094.

We will port this experience to the new Project Properties UI, which is tracked in #7242.
