### ISSUE TITLE
Expose a mechanism for supporting a 'TemplateGroupID' via 'ProjectCapability'

### ISSUE THREAD

**Issue by tannergooding** [dotnet/project-system#2665]
Today there are several templates (such as the WPF templates) that are not visible by default and instead are filtered based on a 'TemplateGroupID'.

>The value of the TemplateGroupID element is used along with project system registration (HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\<version number>\Projects\) to filter templates that appear in the Add New Item dialog box.
(https://msdn.microsoft.com/en-us/library/ms171388.aspx)

We should expose a mechanism for supporting `TemplateGroupID` based on project capabilities.

**Comment by tannergooding** [comment]
FYI. @srivatsn

**Comment by davkean** [comment]
We should just move these to capabilities.

**Comment by tannergooding** [comment]
@davkean, is there existing syntax for supporting a vstemplate based on project capability?

**Comment by davkean** [comment]
Yes, AppliesTo. But when we make these changes we should factor in legacy which does not read capabilities from targets.

**Comment by davkean** [comment]
We already moved most of UWP to capabilities, WPF is pretty much the only other templategroupid that we'll support.

**Comment by davkean** [comment]
As mentioned above, we should move the templates to capabilities, projects can only have a single templategroupid, so having a mapping from capabilities -> templategroupid doesn't really make sense as only one can win.
