### ISSUE TITLE
New project system doesn't copy PDBs from packages when targeting .NET Framework

### ISSUE THREAD

**Issue by bording** [dotnet/project-system#2667]
When a NuGet package includes PDBs in its lib folder, the legacy project system copies the PDB as well as the assembly into the build output folder.

The new project system only copies the assembly.

We've recently added [source link support ](https://github.com/Particular/NServiceBus/pull/4862), and when using the new project system with a .NET Core target, everything works fine since the PDB is referenced correctly from the global NuGet package folder.

However, because the PDB isn't copied for a .NET Framework target, we don't get any of the benefit of our sourcelinked PDB.

It would be great if the new project system would behave like the legacy project system in this case, and also copy the PDB into the project's build output folder.

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#1458
