### ISSUE TITLE
Deduplicate properties in rules for item types

### ISSUE THREAD

**Issue by sharwell** [dotnet/project-system#2668]
Currently there is a large amount of duplication of properties in the rules for various item types. For example, the **Build Action** property appears in every single item type rule. These properties should be de-duplicated through inheritance/extensions after the underlying project system is updated to support such a feature.

The mechanism for this extensibility should also be documented for external developers. Users working with `ObjectExtenders` in the old project system already implemented extension properties this way. As they migrate to supporting the new project system, the lack of an equivalent feature will be a pain point.

**Comment by davkean** [comment]
Not sure what makes this blocked or VSLangProj parity, can you help me understand?

**Comment by davkean** [comment]
Ah, by blocked you mean "CPS feature" and by Vslangproj you mean as a replacement for ObjectExtenders. I would expect ObjectExtenders to work, do they not?

**Comment by sharwell** [comment]
> I would expect ObjectExtenders to work, do they not?

I was not able to get them working when trying to solve tunnelvisionlabs/LangSvcV2#85 prior to going with the approach in tunnelvisionlabs/antlr4cs#234.

**Comment by davkean** [comment]
Filed https://github.com/dotnet/project-system/issues/2671 to track that - I was under the impression that they worked because we had R# ping us about them.

**Comment by davkean** [comment]
I'm going to close this, the C#/VB project team don't have plans to do anymore work here:

1) [Object extender support](https://github.com/dotnet/project-system/issues/2671) was added in 15.8 
2) [AvailableItemName](https://github.com/dotnet/project-system/issues/113) support was added in 16.0

Both of these bring back the same experience that folks have in the legacy project system.
