### ISSUE TITLE
Building a CPS based project without changes since last build causes Visual Studio to build the project.

### ISSUE THREAD

**Issue by Portikus** [dotnet/project-system#2669]
Hi,

**Repo**
1. Create a new solution with the .netstandard template.
2. Build the project
3. Build the project again.

**Expected result**

Visual Studio should not start a build and should display:

> ========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

**Actual result**

Visual Studio does something. The Log says:
> 1>------ Build started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
1>ClassLibrary1 -> c:\users\ahuis_f\documents\visual studio 2017\Projects\ClassLibrary1\ClassLibrary1\bin\Debug\netstandard1.4\ClassLibrary1.dll
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========

If you change the output verbosity to diagnostic you will see that the compiler wont be executed but a lot of other stuff is going on there like _ResolveAssemblyReference_.

My concrete problem is that this increase the build time of my solution without a need (because nothing changed).
Furtermore we are using [SimpleStubs](https://github.com/Microsoft/SimpleStubs) which will generate its stubs each time we build the project because Visual Studio starts the build process.

**Comment by davkean** [comment]
What build of Visual Studio are you using?

**Comment by Portikus** [comment]
Version 15.2 (26430.16) Release

**Comment by davkean** [comment]
Thanks. We've added support for this in the 15.3 previews.
