### ISSUE TITLE
Add telemetry to identify the tasks that get run in a designtime build.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2674]
So that we can profile and understand what causes UI delays in VS.

**Comment by davkean** [comment]
@panopticoncentral @jmarolf Can this be resolved given recent changes?

**Comment by panopticoncentral** [comment]
I left this open because we need to port the telemetry logger from the legacy project system into CPS. We should get that into 15.4 if we can, although I'm not working on it right at this moment.

**Comment by Pilchie** [comment]
This is done now, right?

**Comment by jmarolf** [comment]
This is done

**Comment by panopticoncentral** [comment]
This isn't done because the CPS port hasn't been finished. However, there's a VSO bug on that, so I guess we can close this since there's no more work in this repo.

**Comment by jmarolf** [comment]
@panopticoncentral can you elaborate? we record the targets used in design-time builds for both the native and manages project systems correct?  What telemetry does  CPS need to add?

**Comment by panopticoncentral** [comment]
No, we only added code to the native project system. We need to add it to cps as well, but that's in their codebase.

**Comment by panopticoncentral** [comment]
Actually, we should do this in our codebase and I have a PR.

**Comment by davkean** [comment]
This is completed in 15.5.
