### ISSUE TITLE
Click/double-click seems to often be interpreted as move

### ISSUE THREAD

**Issue by ericstj** [dotnet/project-system#2679]
Using 15.3 preview 26723.0.d15rel

Create a new netstandard library project.

Click and slightly drag an item in the project hierarchy.  You'll see a popup saying
![image](https://user-images.githubusercontent.com/8918108/28834909-89f4e800-7698-11e7-9634-9dcdbea7d09b.png)

The same happens often when I'm double clicking and move the mouse ever so slightly.

This does not reproduce with dev 15 RTM.  It seems this dialog may have been added and doesn't correctly account for noise / noop moves.

**Comment by davkean** [comment]
Resolved in lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=473450&fullScreen=false&_a=edit.
