### ISSUE TITLE
Detect modification of imported projects/targets files

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/project-system#268]
The old project system doesn't detect modification of targets files that are imported into the project. The targets files are read once, and cached for the lifetime of the app (and I have a suspicion that something must be cached in the .vs folder/.suo, but not sure).

So when you modify an included targets file, you have to reload the solution for IntelliSense to "see" your changes. Reloading the project is not enough (I think).

We should think about either monitoring the import graph for changes, or during build/fast-up-to-date-check walk all imports and invalidate if they changes since the last time we "remember" them.

**Comment by davkean** [comment]
@jviau has an approach that might work on our side to handle this:

> 1) IDynamicLoadComponent that applies to HandlesOwnReload
> 2) Get a read lock on the project and collect all the Import elements
> 3) VS file watcher for them, get a write lock and call Reload on them whenever they change
> Of course some design around when to get the read lock on the project.

> I would probably hook up to a dataflow or listen to the UnconfiguredProjectAdvance.ProjectFileChanging event to get the readlock and update the list of imports to watch
> This doesn't solve imports of imports though
now that is interesting
> I guess it could though? You would be explicitly loading each import (which may be an issue)

**Comment by davkean** [comment]
@srivatsn I think this is a functional issue that we should either workaround or tackle for v1. 

This was previously a frustrating experience before but has now become a functional problem due the design of the [project].nuget.g.props/[project].nuget.g.targets that NuGet uses to auto import props and targets from packages. As your installed packages are installed/ununinstall, this file will remain stagnate in-memory while their on-disk versions are updated.

**Comment by jviau** [comment]
@davkean one thing I didn't consider with my suggestion is the lifetime of these imports in the cache after the user unloads the project, but doesn't close VS.

**Comment by srivatsn** [comment]
To be clear though, the nuget staleness issue already exists for UWP-style project.json.

**Comment by NickCraver** [comment]
FWIW, I'm hitting this all the time with `Directory.build.props`. I'm having to close/open VS on every edit to actually get any desired outcomes.

**Comment by mavasani** [comment]
+1 hitting this all the time on Roslyn-Analyzers repo.

**Comment by gulbanana** [comment]
Subscribing, this has been confusing people downstream of my  packages when they update to a prerelease version with changes in its .targets

**Comment by davkean** [comment]
Folks, good news, this change is in review internally for CPS-based project systems.

**Comment by srivatsn** [comment]
This is now implemented and the next VS preview\update should have this change.
