### ISSUE TITLE
Reference initialization optimization

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#2680]
During project load, the legacy project system cracks open dlls to read some information from metadata. This shows up in solution load traces as a significant cost. We should see what we can do here - maybe the ResolveAssemblyReferences can read this information and output that as a build variable that the project system can just read.

**Comment by davkean** [comment]
@tmeschter Can this be resolved given your recent work?

**Comment by tmeschter** [comment]
@davkean Yes, I'll resolve this.

**Comment by tmeschter** [comment]
This was addressed in 15.4 with PR https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/82260#_a=overview.
