### ISSUE TITLE
Adding resource with culture sets unnecessary ResXFileCodeGenerator metadata, pollutes error list

### ISSUE THREAD

**Issue by nguerrera** [dotnet/project-system#2681]
## Setup
* VS Version:15.3.0 Preview 7.0 [26730.0.d15rel]
* .NET Core SDK Version: 2.0.0-preview3-006908

## Repro steps
* File -> New Project -> .NET Core -> Console App
* Add Item -> ResourcesFile -> Resource1.fr.-CA.resx

## Expected result
* As with legacy project system, no ResxFileCodeGenerator metadata is set because the resource file has a specific (non-neutral) culture and therefore no corresponding .Designer.cs.
* There are no errors in my error list when I edit the newly created resx file.

## Actual result
* ResxFileCodeGenerator is set incorrectly
``` xml
    <EmbeddedResource Update="Resource1.fr-CA.resx">
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
```
* There is an error in my error list while editing the resx file

![image](https://user-images.githubusercontent.com/75470/28851338-af4ee1d0-76d6-11e7-88be-bc312c4bfd81.png)

**Comment by davkean** [comment]
Duping against the feedback item linked here: https://github.com/dotnet/project-system/issues/2681.
