### ISSUE TITLE
Incomplete design time build after saving an input to an MSBuild code generator

### ISSUE THREAD

**Issue by sharwell** [dotnet/project-system#2682]
Using Visual Studio 2017 (15.3 Preview 7).

### Steps to reproduce

1. Check out antlr/antlrcs@ca331b7109e1faa5a6aa7336bb6281ce9363e62b
2. Open **Antlr3.sln**
3. Open **ActionAnalysisLexer.g3** and **ActionAnalysisLexerHelper.cs** side-by-side (two windows split vertically)
4. In **ActionAnalysisLexer.g3**, add the following rule after the current `X_Y` rule:

    ```antlr
    X_Y2 : '$' ;
    ```

5. Save **ActionAnalysisLexer.g3**
6. Switch to the **ActionAnalysisLexerHelper.cs** window and navigate to line 55 (start of `Analyze()` method)
7. Type the following code:

    ```csharp
    int value = X_Y2;
    ```

### Expected results

IntelliSense shows `X_Y2` as valid for all target frameworks.

### Actual results

IntelliSense shows `X_Y2` as a valid completion option only for the first listed TFM (net35-client). IntelliSense only updates the other frameworks after an action like close/open the project or running a build.

**Comment by davkean** [comment]
This is just CPS not running MSBuild generators for all "active configs" It should be respecting IConfiguredProjectReadyToBuild

**Comment by Pilchie** [comment]
@davkean Is this one of the bugs you found yesterday that will be cleaned up with your changes to handle configs?

**Comment by davkean** [comment]
I closed in this lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workitems/edit/546560.
