### ISSUE TITLE
[Dependencies] Adding a project reference for netcoreapp2.0 ->netcoreapp2.0 shows yellow Project node without hierarchy

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2684]
VS d15rel 26730.0

Problem project reference node is flaky, scenario below can be repro for me every other time and is very visible. Its a regression, i did not see this flakiness before.

0. Start fresh VS instance
1. Create a new Web Coe 2.0 app and wait for restore
2. Add new project to solution Net Core Unit Tests project, wait for restore.
3. Add p2p refrenece UnitTests -> WebApp, wait for restore 

Actual Result: 

Yellow project node

Expected:

Normal project node with hierarchy.

Note: if i close and reopen solution and do repro steps they sometimes work sometimes not, however with fresh VS instance they show the problem pretty consistently)

![image](https://user-images.githubusercontent.com/1592091/28893638-17902ab4-7787-11e7-970d-9f379778492a.png)

**Comment by abpiskunov** [comment]
Note: restore was fine, no errors or warnings

**Comment by natidea** [comment]
Related VSFeedback:

- [Developer Community](https://developercommunity.visualstudio.com/content/problem/101953/dependencies-in-xunit-or-unit-test-projects-are-fl.html) 
- [Developer Community](https://developercommunity.visualstudio.com/content/problem/103849/net-core-test-project-dependencies-have-warnings-f.html) | [487074](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/487074)

**Comment by Pilchie** [comment]
I tried this a few times, but couldn't repro :(

**Comment by abpiskunov** [comment]
I will keep an eye to see if i could repro it again with latest dogfood builds.

**Comment by Pilchie** [comment]
@natidea potentially another instance of the race we just fixed?

**Comment by natidea** [comment]
It does appear to be fixed by https://github.com/dotnet/project-system/pull/3167 . Please reopen if it recurs

**Comment by isharehappycode** [comment]
I can reproduce this issue
**Environment Details**
Visual Studio Enterprise 2017
.NET Core Version: 2.0.5

**Steps**

- Create class library by running the command 
   dotnet new classlib
- Open the generated project in Visual Studio
   Add **xunit**, **xunit.runner.visualstudio** and **Microsoft.NET.Test.Sdk** from nuget package

Warning will appear as shown below!

<img width="147" alt="warningvs" src="https://user-images.githubusercontent.com/16059426/35503784-2602baea-0507-11e8-9bb3-bc60eed2b50b.PNG">

**Comment by crawshaws** [comment]
Try this one

![image](https://user-images.githubusercontent.com/9270064/42944471-9f9654b6-8b5d-11e8-8c67-d676714a319b.png)

Brand new project, not classes yet. 

Whats more annoying is there is no related textual feedback that there is an issue other than this triangle. Even if there is a problem with a reference, there is no tooltip, you need to waste time building to find the error.
