### ISSUE TITLE
Need to implement IExtenderCATIDProvider to enable extenders to extend our property pages

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2686]
_From @NickCraver on August 3, 2017 0:6_

Just found a crash for VS in the logs, stack here:

```
Unknown exception&#x000D;&#x000A;Exception:&#x000D;&#x000A;The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))&#x000D;&#x000A;StackTrace:&#x000D;&#x000A;
   at EnvDTE.ObjectExtenders.GetExtenderNames(String ExtenderCATID, Object ExtendeeObject)&#x000D;&#x000A;
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.get_ExtenderNames()&#x000D;&#x000A;
   at BuildVision.Helpers.ProjectExtensions.GetExtenderNames(Project project)&#x000D;&#x000A;Source:&#x000D;&#x000A;&#x000D;&#x000A;TargetSite:&#x000D;&#x000A;

System.Object GetExtenderNames(System.String, System.Object)&#x000D;&#x000A;BaseException:&#x000D;&#x000A;System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))&#x000D;&#x000A;
   at EnvDTE.ObjectExtenders.GetExtenderNames(String ExtenderCATID, Object ExtendeeObject)&#x000D;&#x000A;
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.get_ExtenderNames()&#x000D;&#x000A;
   at BuildVision.Helpers.ProjectExtensions.GetExtenderNames(Project project)
```

Hopefully that path makes some sense - VS 2017 Preview 7 in play. 

BuildVision Version: 1.4.1.61

_Copied from original issue: StefanKert/BuildVision#30_

**Comment by davkean** [comment]
Two bugs here that I can see;

1) we're not implementing IExtenderCATIDProvider - so the CATID that CPS is to ObjectExtenders.GetExtenderNames is very likely null.

2) CPS shouldn't be calling ObjectExtenders.GetExtenderNames if there's no IExtenderCATIDProvider.

**Comment by Pilchie** [comment]
@nickcraver - can you clarify what logs you found this in?  Looks like activitylog.xml, and it didn't actually take down VS, right?

**Comment by StefanKert** [comment]
@Pilchie if I remember right this is from actitvity.log and it didn‘t take down VS. This error occurred inside the BuildVision extension when trying to get the extendernames for a project. In buildvision this error is currently handled internally, so it does not show any errors to the user. If I remember right @NickCraver found this while looking for another error in activitylog.. 

If you need any further information on when and how this is happening let me know.

**Comment by davkean** [comment]
To implement IExtenderCATIDProvider - we need to figure out all the different CATIDs that legacy has for References, Configurations, Reference, Project, etc for C# and VB (what do we do about F#) and return them.

**Comment by davkean** [comment]
I have a PR here: https://github.com/dotnet/project-system/pull/3562 that returns CATIDs and hence implements extender support.

**Comment by davkean** [comment]
C# and VB now support extenders in the same way as legacy: https://github.com/dotnet/project-system/pull/3562. F# support is being tracked by https://github.com/dotnet/project-system/issues/3561.

**Comment by StefanKert** [comment]
@davkean Will this be  in the next 15.8 Preview? Since the exceptions that got 
 mentioned in https://github.com/StefanKert/BuildVision/issues/30 will probably be fixed and I´d love to check if it actually works or if I have to do some additional work to support this.

**Comment by davkean** [comment]
In will be in 15.8 Preview 3, not Preview 2 which is the next one.

**Comment by StefanKert** [comment]
Wow. 30 seconds to reply. That is awesome! Thanks for the heads up :). You folks doing great work. Really appreciate it!
