### ISSUE TITLE
C# file in multiple csproj files in same solution can't be switched between said csprojs in vs editor

### ISSUE THREAD

**Issue by FransBouma** [dotnet/project-system#2691]
Repro: [CSharpEditorRepro.zip](https://github.com/dotnet/project-system/files/1199694/CSharpEditorRepro.zip)

The attached repro case has two csproj files, one targeting NetFX and one targeting NetStandard2.0. The Netstandard2.0 project references the cs file from the NetFX project. While I know in theory one could use 'multi-targeting', for now I'm not using that due to tooling being in preview state and this allows me to build two artifacts without problems.

The issue is that when I open the C# file in the vs 2017 15.3 prev 7 editor, it will always pick the netstandard project in the top bar: you can't select the NetFX project version, even if you open that solution item. This is particularly problematic when there are conditional compilation directives present, like the one in the example. 

If there's more info needed, let me know. :)

**Comment by davkean** [comment]
Repro #1:

1. Open Solution
2. Open Class1.cs from ReproNetFx

Expected: For ReproNetFx to be "current context"
Actual: ReproNetStandard is "current context""

Repro #2:

1. Open Solution
2. Open Class1.cs from ReproNetStandard
3. In context drop down, choose ReproNetFx
4. Set focus to editor

Expected: For ReproNetFx to be "current context"
Actual: ReproNetStandard is "current context""

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn#21358

**Comment by davidwengier** [comment]
For the watchers: This issue has been fixed in https://github.com/dotnet/roslyn/pull/32313 and is available in the latest Visual Studio 2019 Preview.
