### ISSUE TITLE
RPS test for .NET Core projects

### ISSUE THREAD

**Issue by viktorveis** [dotnet/project-system#2702]
We need an end-to-end test to catch perf regressions in .NET Core project system.

**Comment by davkean** [comment]
@abpiskunov I believe you are working on this, yes?

**Comment by davkean** [comment]
If you're already got a bug on this, feel free to dup this one against it.

**Comment by abpiskunov** [comment]
Nope, i created an E2E test which run in our repo not RPS.

**Comment by davkean** [comment]
We need to find an owner for this.

**Comment by davkean** [comment]
This is blocked on @KevinH-MS's work to add LUT end-to-end on .NET Core which will include us.

**Comment by Pilchie** [comment]
@jmarolf is already working on this.

**Comment by Pilchie** [comment]
There are some tests authored and (finally) running nightly here, but leaving active to get a few more scenarios up and to verify that the tests are robust and reliable

**Comment by Pilchie** [comment]
I was leaving it open for:

1. Getting time to language service population tracked.
2. Ideally getting these running against PRs.

**Comment by davkean** [comment]
@jmarolf Can we close this?

**Comment by jmarolf** [comment]
@davkean 
> Getting time to language service population tracked.

This is still not done yet.  When there is an APEX API with the operation progress stuff we can fix that.

**Comment by tmeschter** [comment]
Moving to 16.2 as this is ongoing work and I expect we will continue to make progress in that milestone.

**Comment by davkean** [comment]
This has been merged and turned on.

**Comment by davkean** [comment]
Oh maybe not, @tmeschter @jmarolf Operation progress API is in, have we consumed it?

**Comment by jmarolf** [comment]
Now that nuget restore is in I will update the test to correctly wait for it

**Comment by davkean** [comment]
Closing this out - it continues to get punted and its not clear what this is tracking anymore. @dmonroym is moving RPS test to a new system which is using a different bug to track it.
