### ISSUE TITLE
Rename Fails when class is already named the target file name

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#2704]
I'm running the latest Int Preview, build 26730.0. Repro steps:

1. Create a new .net console app
2. Open Program.cs
3. Change (without refactor) Program to C1
4. Rename Program.cs to C1.cs in VS

Expected:
Program.cs is renamed to C1.cs on disk

Actual:
Program.cs remains on disk. There is a new entry in the project file of:
```  
  <ItemGroup>
    <Compile Include="C1.cs" />
  </ItemGroup>
```
Program.cs doesn't appear in the solution explorer, just C1.cs. While I haven't been able to reproduce this reliably, I've also had issues in Compilers.sln (in roslyn) where the types in the newly renamed file aren't visible in the rest of the project. I also once observed (but again can't repro reliably) that saving the project caused a new C1.cs to be written to disk, with the same contents as Program.cs.

**Comment by 333fred** [comment]
@Pilchie @davkean has anyone looked at this bug yet? I seem to hit this every few days as I fat-finger a file name.

**Comment by davkean** [comment]
@tannergooding Can you take a look? Alternatively, @333fred we take contributions. :)

**Comment by ghuntley** [comment]
Reproducible with Version 15.7.0 Preview 2.0 but observed different side effects.

* `Program.cs` is successfully updated to `P1.cs` in the csproj and on the filesystem after renaming. 
* Immediately after renaming in visual studio the Intellisense window throws a failure

`[Failure] Could not find file 'c:\users\ghuntley\source\repos\ConsoleApp3\ConsoleApp3\Program.cs'.`

![2018-03-31_0-27-56](https://user-images.githubusercontent.com/127353/38139344-c2bfaf76-347a-11e8-9e63-52b1f558b0ea.gif)

**Comment by jmarolf** [comment]
This is fixed

**Comment by ghuntley** [comment]
Lovely. Thanks Dave & Jonathon.

**Comment by davkean** [comment]
This one was all @jmarolf.

**Comment by ghuntley** [comment]
Ya but you had to listen to me bitch about it 😆
