### ISSUE TITLE
Removing Microsoft.VisualBasic import in .NETStandard Lib throws poor Error Message

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2706]
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/91802/unable-to-unselect-microsoftvisualbasic-in-project.html) | [476721](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/476721):

Steps to reproduce:
1. Create new VB .NET Standard project.
2. Go to Project Properties > References
3. Unselect Microsoft.VisualBasic in Imported namespaces list.
4. There is an error:

![image](https://user-images.githubusercontent.com/7732033/29226073-8466ffe6-7e85-11e7-94a3-7643c9f90383.png)

The error is expected, and is thrown here: https://github.com/dotnet/project-system/blob/360a009390105ad50695ae595ddb62dbd56b87b3/src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Automation/VisualBasicVSImports.cs#L122

However the error message should be cleaned up.

Additional Feedback:
- [VSFeedback](https://developercommunity.visualstudio.com/content/problem/95807/cannot-remove-imported-namespaces-from-reference-t-1.html) | [480706](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/480706)

**Comment by natidea** [comment]
Also adding a remove to the project file does not deselect the import:
```xml
  <ItemGroup>
    <Import Remove="Microsoft.VisualBasic" />
  </ItemGroup>
```

**Comment by natidea** [comment]
**Update:** the source of the implicit import of namespaces is [Microsoft.NET.Sdk.VisualBasic.targets#L21-L44](https://github.com/dotnet/sdk/blob/cd25d6bbfc2aac61cc790c511900427ac64fdaa8/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.VisualBasic.targets#L21-L44). These implicit imports can be disabled by setting the following property:
```xml
  <PropertyGroup>
    <DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
  </PropertyGroup>
```

**Comment by davkean** [comment]
Can we come with a sensible behavior here?

**Comment by ocallesp** [comment]
Does not repro in .Net Framework

**Comment by ocallesp** [comment]
If we create "Code Refactoring (.NET Standard) it does repro, but I am not sure if this is by design because we can avoid the error message if set this property.

```
<PropertyGroup>	 
   <DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
</PropertyGroup>
```

**Comment by ocallesp** [comment]
@mckennabarlow any suggestion on how to improve this error message ?

**Comment by adamint** [comment]
Expected
