### ISSUE TITLE
Perf: ProjectAssetFileWatcher.Initialize initialize directory watcher dataflow in UI thread

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#2708]
ProjectAssetFileWatcher.Initialize is called in the UI thread, and blocks to UI thread to initialize the directory tree dataflow.  Other than the query service (the first line), can we move the rest of the initialization out of the UI thread?

**Comment by davkean** [comment]
👍

**Comment by Pilchie** [comment]
Fixed by #3094.
