### ISSUE TITLE
High CPU usage when IDE is idle.

### ISSUE THREAD

**Issue by krt-** [dotnet/project-system#2713]
VS15.3 Release constantly uses 75% CPU after loading solution with Xamarin.Android project & .NET Standard 1.4 Library. I have PerfView trace file. Where should I send it?

**Comment by davkean** [comment]
Can you share it on onedrive?

**Comment by krt-** [comment]
Sent link to your email

**Comment by davkean** [comment]
We're spending 40% of our time here: 

![image](https://user-images.githubusercontent.com/1103906/29308130-f0e5fec8-81e7-11e7-998f-7452c1b484a2.png)

I suspect a bug similar to https://github.com/dotnet/project-system/pull/2526.

@krt- Can you send on what your `<TargetFrameworks>` element looks like?

**Comment by krt-** [comment]
Xamarin.Android project:
`<TargetFrameworkVersion>v7.1</TargetFrameworkVersion>`

.NET Standard Library:
`<TargetFramework>netstandard1.4</TargetFramework>`

**Comment by davkean** [comment]
Also filed https://github.com/dotnet/project-system/issues/2714 for the lock contention I saw.

Hmm, is that all that's in the solution?

**Comment by krt-** [comment]
Sorry, have also 2 Roslyn analyzers here. Both have `<TargetFramework>net4.7</TargetFramework>`

**Comment by davkean** [comment]
It would be helpful if you could share the solution privately - no worries if you can't, but it will make investigation a little quicker. :)

**Comment by krt-** [comment]
I'll try to create a small repro

**Comment by davkean** [comment]
Yeah, it's very likely the project files - I'd be surprised if the source files matter.

**Comment by krt-** [comment]
Here's a very small repro :)
[repro.zip](https://github.com/dotnet/project-system/files/1224543/repro.zip)

**Comment by davkean** [comment]
Thanks, I'll look at this tomorrow my time (Australia).

**Comment by sharwell** [comment]
💭 `net4.7` seems strange. I would have expected to see `net47`; I'm reminded of #2388.

**Comment by davkean** [comment]
Yeah this looks like another case of #2388, as a workaround, replace:

`<TargetFramework>net4.7</TargetFramework>`

with

`<TargetFramework>net47</TargetFramework>`

**Comment by krt-** [comment]
Thanks, everything is working fine now

**Comment by davkean** [comment]
This has been fixed and will be available in the next public build of 15.4.
