### ISSUE TITLE
Large amount of lock contention in dependency node

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2714]
In this bug: https://github.com/dotnet/project-system/issues/2713, I saw lots of lock contention, GetTargetFrameworkAsync has a huge amount - but that may be caused by what is the root cause of that bug of whatever cause us to continually call it. However, we should look at GetDependencyModel:

![image](https://user-images.githubusercontent.com/1103906/29308310-c3ebe72e-81e8-11e7-8fa6-47cef4d558b6.png)

**Comment by Pilchie** [comment]
Same basic issue as #2707
