### ISSUE TITLE
No package under Reference node after installing second package with Package ref format

### ISSUE THREAD

**Issue by mishra14** [dotnet/project-system#2716]
Internal issue with screenshots: 476159

## Repro steps: 
1. Check ‘Allow format selection on first package install’ in NuGet Package Manager setting dialog.
2. Restart VS and create a C# WPF (.NET Framework) project.
3. Open the ‘Manage NuGet Packages…’ for the project.
4. Go to ‘Browse’ tab, install package ‘Newtonsoft.Json’ with ‘PackageReference in project file’ format.
5. The package ‘Newtonsoft.Json’ appear under Reference node.
6. Then install package ‘NUnit’ with ‘PackageReference in project file’ format.

## Expected:
The package ‘NUnit’ also should appear under Reference node.
 
## Actual:
There is no package under Reference node as below screenshot.

## Details
NuGet Version: NuGet Client Dev-4390
VS Version: D15Rel 26808.00
OS Version: Windows 10 RS2_Release 15063.2.170323-1837

**Comment by mishra14** [comment]
@natidea @davkean  this seems like a project system issue since the assets file looks fine. 

Please let me know if there is a better place for this.

**Comment by Pilchie** [comment]
I can't repro this with 15.6 Preview 1.  I suspect this was the missing "CollectNuGetPackages" target related to DTBB.
