### ISSUE TITLE
CS8032: analyzer cannot be created after changing PackageReference 

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/project-system#2719]
When changing the version of a package reference that includes an analyzer, the project system will generate a bunch of CS8032 warnings. The warning says that the analyzer from the old version of the PackageReference cannot be created, even though this has been uninstalled.

**Repro**
1. Create a new test project that references xunit 2.3.0-beta2: https://www.nuget.org/packages/xunit/2.3.0-beta2-build3683. This has xunit.analyzers 0.1.0
2. Open in VS
3. Keeping VS open, edit the csproj file and change xunit to 2.3.0-beta4: https://www.nuget.org/packages/xunit/2.3.0-beta4-build3742. This has xunit.analyzers 0.6.0

**Result**
The Error List window displays hundreds of CS8032 warnings, all with the same message. They don't go away, even if you unload/reload the project.

```
Warning CS8032: An instance of analyzer Xunit.Analyzers.MemberDataShouldReferenceValidMember cannot be created from C:\Users\namc\.nuget\packages\xunit.analyzers\0.6.1\analyzers\dotnet\cs\xunit.analyzers.dll: Could not load type 'Xunit.Analyzers.MemberDataShouldReferenceValidMember' from assembly 'xunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..	FS.Composite.Tests(net461)		1	Active
```

![image](https://user-images.githubusercontent.com/2696087/29387731-4666757c-8296-11e7-877c-ca3ac4b46570.png)

cref https://github.com/xunit/xunit/issues/1307

**Comment by memark** [comment]
Any update on this? Will it be fixed, or just pushed forward to new milestones..?

**Comment by davkean** [comment]
This is https://github.com/xunit/xunit/issues/1704.

**Comment by Pilchie** [comment]
As @jasonmalinowski mentioned internally though, we should probably have bug on dotnet/roslyn to have a better message, and on dotnet/roslyn-analyzers to provide better guidance to analyzer authors that they should strong-name sign their analyzers.
