### ISSUE TITLE
Referencing netcoreapp in a netstandard project

### ISSUE THREAD

**Issue by aateeque** [dotnet/project-system#2721]
Hi
I am porting over a net452 & asp.net app over to netstandard & dotnet core. I have a situation where I need to refence my asp dotnet core app which is `<TargetFramework>netcoreapp2.0</TargetFramework>` in my testing project which is `<TargetFramework>netstandard2.0</TargetFramework>`. When I do a `ProjectReference` I get:

```
Project XXX is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project XXX supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
```

Is this sort of thing possible (don't see why not?)

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#1513
