### ISSUE TITLE
No squiggle in dependency in solution explorer for UWP project.json when installing a wrong version

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2722]
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/70575/no-squiggle-in-dependency-in-solution-explorer-for.html) | [453281](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/453281)

> Repro steps:
> 
> File -> New Project -> UWP Class Library, TPMinV = 10586, TPV = 14393 Edit project.json to include dependency Newtonsoft.json Version = 10.0.0 Restore solution.
> 
> There will be warnings in the console and warning window about Detected package downgrade (NU1605) but the UI doesn't reflect any indication of warning.  

We have not implemented this yet as UWP is not on the Dependencies Tree.

**Comment by davkean** [comment]
We're not going to do this - instead UWP will move over to the new project system, and hence will get the new Dependency node.
