### ISSUE TITLE
TargetFramework Filter in "Add New Project" is not honored for .NET Core projects

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2723]
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/97411/the-project-creation-wizard-doesnt-show-correct-ta-1.html) | [482122](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/482122)

The Add New Project dialog includes a Target Framework filter that affects the target framework for the desktop C# project that is created. However this filter is not honored in .NET Core and .NET Standard projects.

![image](https://user-images.githubusercontent.com/7732033/29509938-d5fd08d8-860e-11e7-8e47-941742d12539.png)

**Comment by natidea** [comment]
@panopticoncentral is this just a feature we have not implemented yet, or a bug?

**Comment by jmarolf** [comment]
@natidea I think this would need a complete re-design of the new-project dialog to fix.  .NET Framework doesn't make any sense for .NET Core of netstandard projects.

**Comment by panopticoncentral** [comment]
Yes, this is really feature-level work. I'll have to look to see if there's anything covering that, but it's a known need.

**Comment by davkean** [comment]
This is a known need - and not owned by us. This work will be done in when the new project dialog replacement is done.
