### ISSUE TITLE
Issue with Analyzers node

### ISSUE THREAD

**Issue by mavasani** [dotnet/project-system#2724]
Ported from https://github.com/dotnet/roslyn-analyzers/issues/1286

Possibly related, analyzers also display rather oddly in VS 15.3.1. (This is from a different project I'm on that also uses the analyzers and has the same errors I reported above. In this screenshot you'll notice StyleCop is also here. Removing StyleCop does not fix the issue.)

![Analyzers in VS 15.3.1](https://user-images.githubusercontent.com/1156571/29532815-d6d7d5e4-8663-11e7-9678-eeffbb1ae1b6.PNG)

**Comment by tmeschter** [comment]
What we really need is a way to filter out analyzer assemblies that don't have any actual analyzers. This would exclude all the *.resources.dll assemblies, as well as utility libraries loaded by analyzers, and libraries that just contain code fixes.

**Comment by mavasani** [comment]
@tmeschter Note that the filtering already works fine for legacy project system - we only show assemblies with at least one diagnostic analyzer.

**Comment by tmeschter** [comment]
@mavasani Yes, but that filtering is done by the language service because it owns the Solution Explorer nodes when working with the legacy project system. When the new project system is in use, it is responsible for creating those nodes. I can't (directly) re-use the same code. Though I will very likely end up copying it.

**Comment by tmeschter** [comment]
Moving out to 15.6 as this no longer meets the bar for 15.5.

**Comment by drewnoakes** [comment]
Testing this again with more recent bits.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="2.3.0-beta1">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.3.0-beta1">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Net.RoslynDiagnostics" Version="2.3.0-beta1">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta004">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

The Dependencies node appears to render correctly:

![image](https://user-images.githubusercontent.com/350947/65418878-c2dc4700-de40-11e9-8614-e9e134029449.png)

I don't see any action to take here so will close this. @tmeschter if I'm missing something please let me know.
