### ISSUE TITLE
Analyzer packages no longer added with PrivateAssets

### ISSUE THREAD

**Issue by tillig** [dotnet/project-system#2725]
Prior to VS 15.3 when you'd add a reference to a Roslyn analyzer package you'd get a reference like this:

```xml
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="2.3.0-beta1">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
```

With the `PrivateAssets` node the analyzer wouldn't be seen as a dependency when packaging your project.

As of 15.3.1, when adding a Roslyn analyzer package reference you no longer get the `PrivateAssets` node.

```xml
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="2.3.0-beta1" />
```

This ends up including the analyzer as part of the packaging process and you get an incorrect dependency.

Repro is easy - create a new project in VS 15.3.1 targeting a netstandard TFM and add a reference to Microsoft.CodeAnalysis.Analyzers. Save it and look at the .csproj.

**Comment by davkean** [comment]
This issue was moved to NuGet/Home#5816
