### ISSUE TITLE
.NET Core Class Templates do not apply code styles

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2726]
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/97435/new-net-core-application-doesnt-apply-code-styles.html) | [482102](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/482102)

**Repro Steps** 

Go to Tools/Options/TextEditor/C#/CodeStyle/Formatting/NewLines and turn off all checkboxes as to follow K&R brace style (i.e. brace opening goes on the same line).

Create a new .NET Core 2.0 application.

When a new .NET Core 2.0 application is created, the following is default file content:

```cs
    namespace TestCore2
    {
        class Program
        {
            static void Main(string[] args)
            {
                Console.WriteLine("Hello World!");
            }
        }
    }
```

Expected result would be default document properly following code styles:

```cs
    namespace TestCore2 {
        class Program {
            static void Main(string[] args) {
                Console.WriteLine("Hello World!");
            }
        }
    }
```

PS: Full .NET framework application properly follows code style on startup.
PPS: Style will be correctly applied upon pressing Ctrl+K,D.

**Comment by davkean** [comment]
@CyrusNajmabadi What's your thoughts around this? Rather than individual templates opting into this - perhaps some generalized mechanism for auto-applying styles?

**Comment by CyrusNajmabadi** [comment]
I thought we already formatted newly created template files.  Is that not the case?

**Comment by jmarolf** [comment]
This is a bug.  Newly created files should have the formatter run on them by default already.

**Comment by davkean** [comment]
Does this happen for files that aren't item templates but are part of project templates?

**Comment by jmarolf** [comment]
Yes, set K+R braces 
![image](https://user-images.githubusercontent.com/9797472/29609408-f97a7d92-87ab-11e7-8963-ff531b432905.png)

And then create 
- net core app: not formatted
- net framework app: formatted

**Comment by davkean** [comment]
Ah, this will be the new template engine.

**Comment by davkean** [comment]
@jmarolf Any idea how this actually works under the covers?

**Comment by jmarolf** [comment]
@davkean I assume the old project system would do something to let the language service know to format the document.  I'm curious if this repos with the old templates (not based on the web framework).  If not then I believe that this bug should go to the new template engine.  I

**Comment by davkean** [comment]
This issue was moved to dotnet/templating#1225
