### ISSUE TITLE
'Add Migrations' after Migrating to 2.0

### ISSUE THREAD

**Issue by QuantumHive** [dotnet/project-system#2728]
I've posted this issue on the [EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore) repo. For details see https://github.com/aspnet/EntityFrameworkCore/issues/9506  

The issue is that when adding migrations with the dotnet core 2.0 tooling, a Visual Studio UI bug occurs in the Solution Explorer.

**Comment by davkean** [comment]
@QuantumHive What build of VS are you using? Can you repro this with the released version of 15.3?

**Comment by QuantumHive** [comment]
I'm using version `15.3.2`.  
To be honest, I cannot reproduce the issue when creating a new `dotnet core 2.0` project from scratch. But you can see the issue clearly in the screenshots I've provided.

**Comment by davkean** [comment]
@QuantumHive I believe this is a [known bug](https://developercommunity.visualstudio.com/content/problem/80855/solution-shows-missing-file-icon.html) that will be fixed in 15.4 _Preview 2_ when it is released.

**Comment by araselahi** [comment]
Problem still exists in 15.5.4 so Package Manager Console can not finish the add-migration process. Machine restart required!

infoinfo: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\A.Elahi\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\A.Elahi\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Vitfw.BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection[0]
      RabbitMQ Client is trying to connect
Vitfw.BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection[0]
      RabbitMQ Client is trying to connect
Vitfw.BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection[0]
      RabbitMQ Client is trying to connect
infoinfo: Vitfw.BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection[0]
      RabbitMQ persistent connection acquired a connection desktop-f8akl87 and is subscribed to failure events
: Vitfw.BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection[0]
      RabbitMQ persistent connection acquired a connection desktop-f8akl87 and is subscribed to failure events
Vitfw.BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection[0]
      RabbitMQ persistent connection acquired a connection desktop-f8akl87 and is subscribed to failure events
