### ISSUE TITLE
NuGet reference not shown in References section for projects with PackageReference

### ISSUE THREAD

**Issue by jainaashish** [dotnet/project-system#2731]
Copied from https://github.com/NuGet/Home/issues/5803

I recently switched my project to use the PackageReference method (<RestoreProjectStyle>PackageReference</RestoreProjectStyle>) to include nuget packages and ran into a problem when I tried adding nuget reference to evopdf package.

But with the new approach, it doesn't show the nuget reference:

**Even after package restore / build, the package is not shown in the "References" section. The dlls appears in the output directory, however.**

**Comment by Pilchie** [comment]
I'm guessing this was the issue with DTBB not having the CollectNuGetPackageReferences target.  No longer repros in 15.5/15.6
