### ISSUE TITLE
No IntelliSense for ProjectReference with the same embedded COMReference

### ISSUE THREAD

**Issue by campersau** [dotnet/project-system#2735]
I have two projects with the same COMReference:
```xml
<COMReference Include="MSHTML">
    <Guid>{3050F1C5-98B5-11CF-BB82-00AA00BDCE0B}</Guid>
    <VersionMajor>4</VersionMajor>
    <VersionMinor>0</VersionMinor>
    <Lcid>0</Lcid>
    <WrapperTool>tlbimp</WrapperTool>
    <Isolated>False</Isolated>
    <EmbedInteropTypes>True</EmbedInteropTypes>
</COMReference>
```
The first project is referenced by the second one via a ProjectReference.
Building the projects does work but in the second project I don't get IntelliSense for the types of the first one.

![image](https://user-images.githubusercontent.com/4009570/29724028-3e34c4c0-89c7-11e7-96b5-d49940bd810b.png)

If I reference the output dll from the first project then IntelliSense works.

Here is a demo solution: https://github.com/campersau/dotnetcore-project-comreference

Also posted on Visual Studio Feedback: 
https://developercommunity.visualstudio.com/content/problem/101725/projectreference-to-a-net-core-project-with-comref.html

**Comment by rydergillen-compacSort** [comment]
I ran into this issue today... it appears PROJECT references can't work side/by/side with COM references, regardless if the 1st project references the same interop assembly (or any interop assembly)

1) Create .NET Standard 2.0 Class Lib
2) Reference another project in the same solution
3) Reference a COM Interop DLL
4) Observe the PROJECT reference disappears from the UI (references node)
5) Project still Builds/Runs -- NO intellisense for referenced project

**Comment by davkean** [comment]
This might be fixed by https://github.com/Microsoft/msbuild/pull/2592.

**Comment by rydergillen-compacSort** [comment]
I just manually applied the linked fix. The issue appears to be resolved.

Thanks!

**Comment by davkean** [comment]
Going to dup against: https://github.com/Microsoft/msbuild/pull/2592.

**Comment by campersau** [comment]
Yes, the fix resolved the issue for me too.

Thanks!
