### ISSUE TITLE
Changing Build Action through Properties Dialog results in Error

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2736]
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/98289/vs-changing-build-action-in-a-file-properties-is-n.html) | [482594](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/482594)

**Steps to reproduce:**
Right click on any file in solution, Properties, in "File.cs Property Pages" dialog change Build Action to any value (initially it's "C# Compiler"), Apply.

**Expected:**
changing build action!

**Actual:**
An error dialog is shown with error "Mismatched PageRule with the wrong ItemType."

![image](https://user-images.githubusercontent.com/7732033/29736902-8642fc4e-89ba-11e7-9c1f-4697f4833d29.png)

**Workaround:** 
Change build action through Properties Window (F4) after selecting file in solution explorer.

**Comment by davkean** [comment]
Two things:

- We shouldn't be showing this non-modal window anyway
- Notice that this file contains two sets of properties; File Properties and General - that's not intentional.

**Comment by davkean** [comment]
This has been fixed.
