### ISSUE TITLE
Cannot adding the Settings template due to "missing" reference

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2737]
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/97427/vs-153-settingsdesignercs-not-created.html) | [484139](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/484139)

> The designer works as expected when the old csproj format is used but fails when the new format is in use
> 
> VS2017 15.3
> Start with new solution and project (Class library, dotnet standard using NET framework 4.6)
> Right-click on the project and choose "Properties"
> Here the settings file button is NOT visible.
> 
> Rightclick on the project file and choose "new item"
> Choose settings file.
> * a new file Settings1.settings is generated marked with customer tool "SettingsSingleFileGenerator"
> 
> This is visible in the project file:
> 
> ```xml
>   <ItemGroup>
>     <None Update="Settings1.settings">
>       <Generator>SettingsSingleFileGenerator</Generator>
>     </None>
>   </ItemGroup>
> ```
> 
> Double clicking he Settings1 file opens the settings editor. I can edit the file. 
> 
> The custom tool does NOT create the expected .cs class file (settings1.designer.cs) in this case.
> 
> If I open an existing project with project settings file the editor also works but fails to regenerate the .cs class. 

Works as expected for Desktop projects. For CPS projects the Settings template is not visible in Add New Item dialog, but searching for "Settings" brings it up. After initially adding the settings file, the following error is displayed:

![image](https://user-images.githubusercontent.com/7732033/29737322-63c0963a-89c0-11e7-8a2b-67148a01aca0.png)

Dismissing this dialog proceeds to the experience described above.

**Comment by markolbert** [comment]
Is there a workaround for this? It's really annoying when basic functionality goes away because of a new csproj format. If there is no workaround, how do we get a fix expedited?

**Comment by jrgcubano** [comment]
This is happening in general with any designer.cs. The generation does not work either with x.dbml (linq to sql) to x.designer.cs

**Comment by tofutim** [comment]
I have this issue as well. In VS2017 style project, the Settings file does not generate the designer. Please help!

**Comment by alexreinking** [comment]
I am also having this issue. Any sort of workaround would be greatly appreciated.

**Comment by davkean** [comment]
@tofutim Your should be fixed in 15.6/15.7 so I'm hiding your comment as it's a separate issue.

**Comment by davkean** [comment]
The fact that the single file generator ("Custom Tool") doesn't work is being tracked by https://github.com/dotnet/project-system/issues/3535. I'll leave this issue to track the error that comes up about not being able to add "System".

**Comment by jmarolf** [comment]
This error has new been fixed in the lastest 16.3 (29108.73 master)
