### ISSUE TITLE
.Net core console application - Appsettings.{environment}.json not nesting

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2740]
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/93003/net-core-console-application-appsettingsenvironmen.html) | [479365](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/479365)

> Within VS2015 .net core console applications your appsettings.{environment}.json would nest below appsettings.json (just like they do in APIs and websites) however after upgrading to VS2017 it no longer nests them and when you have a fair few enviroments it makes the project look messy.

**Comment by davkean** [comment]
Dup'ing against: https://github.com/dotnet/project-system/issues/159
