### ISSUE TITLE
Can't remove Any CPU from Project Platforms list

### ISSUE THREAD

**Issue by davidmatson** [dotnet/project-system#2745]
I'm using VS 2017 15.3.2.

With this csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net47</TargetFramework>
  </PropertyGroup>
</Project>
```

If I add an x64 or x86 configuration (Build, Configuration Manager...), that works fine and edits the proj like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net47</TargetFramework>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>
</Project>
```

I can remove either the x64 or x86 configuration from the project, but not the Any CPU one. If I try to do so, I get the following error:
```
---------------------------
Microsoft Visual Studio
---------------------------
The operation could not be completed. The parameter is incorrect. 
---------------------------
OK   
---------------------------
```

![image](https://user-images.githubusercontent.com/3360277/29790817-c709e4d6-8bef-11e7-80db-6acf305665bc.png)

**Comment by amanbha** [comment]
Is there a timeline for the fix?

**Comment by stijnherreman** [comment]
As a workaround you can remove it by editing the csproj file by hand.

**Comment by drewnoakes** [comment]
This no longer shows an error dialog, but it also doesn't work as expected. It is removed from the UI, but not the project file. Re-open the UI and the platform is back in the dropdown list.

**Comment by ocallesp** [comment]
PR https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/228032
