### ISSUE TITLE
Design/Doc issue: PlatformTarget vs Platforms vs RuntimeIdentifier handled inconsistently

### ISSUE THREAD

**Issue by davidmatson** [dotnet/project-system#2748]
I've stumbled across a number of cases where it isn't clear if I should use PlatformTarget, Platforms or RuntimeIdentifier. The tooling seems to get confused a bit between these properties as well - sometimes one UI (project properties) will reflect one property but another UI (Configuration Manager) will reflect a different property.

Could we document when to use which property? Or, perhaps even better, could we reduce the concept count here and would that lead to fewer bugs/ambiguities/possible conflicts?

For example, what's the right way to say the project is x64?
```
<RuntimeIdentifier>win-x64</RuntimeIdentifier>
```
and/or
```
<PlatformTarget>x64</PlatformTarget>
```
and/or
```
<Platforms>x64</Platforms>
```

Is there any way to reduce the number of ways to say "I'm x64"?

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#1553
