### ISSUE TITLE
Long bin paths even for single output type

### ISSUE THREAD

**Issue by davidmatson** [dotnet/project-system#2749]
Compared to old-style .NET Framework csproj, bin output paths are more involved/nested than they used to be. For example, the default used to be just
bin\Debug
bin\Release

(folders per configuration only.)

For secondary platforms, they'd add one more level, such as:
bin\x64\Debug
bin\x86\Debug
bin\x64\Release
bin\x86\Release

With AnyCPU staying in the higher-level directory.

This organization was simple and nice.

With this csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net47</TargetFramework>
  </PropertyGroup>
</Project>
```

There's a minimum extra level of nesting:
bin\Debug\net47

And with this one:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net47</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
</Project>
```

it gets even worse:
bin\Debug\net47\win-x64

In both cases, there's just one value in use (it's a single TargetFramework, not multiple TargetFramework**s** and a single RuntimeIdentifier, not multiple RuntimeIdentifier**s**). For these cases, could the extra levels of bin subdirectory nesting be removed?

Edit: I've been getting confused between Platform & Platform**s**. It gets even worse when using that property:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net47</TargetFramework>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
</Project>
```
bin\x64\Debug\net47\win-x64
Yikes!

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#1547
