### ISSUE TITLE
Debugger launch env variable doesn't work if child process debugging tool installed

### ISSUE THREAD

**Issue by onovotny** [dotnet/project-system#2752]
If I have a launchSettings of:

```json
{
  "profiles": {
    "test.harness": {
      "commandName": "Executable",
      "executablePath": "$(VSINSTALLDIR)\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe",
      "commandLineArgs": "test.harness.dll /ListTests /testadapterpath:\"$(SolutionDir)\\src\\xunit.runner.visualstudio\\bin\\$(Configuration)\\net452\"",
      "workingDirectory": "$(SolutionDir)\\test\\test.harness\\bin\\$(Configuration)\\net452"
    }
  }
}
```

That doesn't work if the VS Child Process Debugging Extension is installed.

To repro:

- Create new project with the above launch settings
- Debug

Next to the solution file, have the following xml file called `theSolution.ChildProcessDbgSettings`
```xml
<?xml version="1.0" encoding="utf-8"?>
<ChildProcessDebuggingSettings IsEnabled="true" xmlns="http://schemas.microsoft.com/vstudio/ChildProcessDebuggingSettings/2014">
  <DefaultRule EngineFilter="[inherit]" />
</ChildProcessDebuggingSettings>
```

It launches correctly (though won't do anything without the rest of the args)

Now install https://marketplace.visualstudio.com/items?itemName=GreggMiskelly.MicrosoftChildProcessDebuggingPowerTool

Same thing fails. Even without any mixed mode debugging, just the presence of the extension seems to break things. Looks like the `$(VSINSTALLDIR)` isn't resolved.

/cc @gregg-miskelly

**Comment by Pilchie** [comment]
Also tagging @BillHiebert, but I'm not sure what project-system should do here.  @gregg-miskeylly?

**Comment by onovotny** [comment]
I haven't tested this, but shouldn't this work in 15.5 now since there's now a lauchSettings option for the native debugger?

**Comment by gregg-miskelly** [comment]
What error does the launch fail with?

**Comment by davkean** [comment]
Going to close this out, @onovotny if you are still encountering this - can you Report a Problem and I can route to the debugger tem.
