### ISSUE TITLE
Core projects in TFS keep editing project file adding TFS bindings

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2758]
We just converted our ProjectSystem.Web project to dotnet core. This project is part of the solution that has other classic csproj projects and is binded to TFS (all TFS/SCC bindings are in the solution file for all projects in solution.

Now everytime i open solution i get a dialog from TFS checking if i want to bind my ProjectSYstem.Web project:
   - if i say yes it would add this to my project

``
  <PropertyGroup Label="Globals">
    <SccProjectName>%24/DevDiv/Offcycle/WPT/WebToolsExtensions/Main/src/ProjectSystem/DotNet.Web</SccProjectName>
    <SccProvider>{4CA58AB2-18FA-4F8D-95D4-32DDF27D184C}</SccProvider>
    <SccAuxPath>http://vstfdevdiv:8080/devdiv2</SccAuxPath>
    <SccLocalPath>.</SccLocalPath>
  </PropertyGroup> ``

I don't want to have it there since sln file is the one holding this data already.

   - if i say no, next time i open solution i would see same dialog again.

Classic csproj projects did not have that. Kind of annoying...

**Comment by davkean** [comment]
Closed in lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=487274&fullScreen=false&_a=edit.

**Comment by jnm2** [comment]
@davkean Closing these in favor of internal work items is problematic for anyone who wants to know when there is an update.

**Comment by StingyJack** [comment]
@davkean what does that internal only workitem have for the latest update?

**Comment by davkean** [comment]
For folks that want to track this, please Help -> Send Feedback -> Suggest a Feature and that way you can up-vote it. This code base does not own this feature, so tracking it would mean that the team that owns it would never see it.
