### ISSUE TITLE
Error in imported project leave core projects in a state when they stop updating after targets were fixed

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2760]
- I have my project imports a targets file A, that has import for another targets file B. 
- i open targets file B and introduce some error
- project updates but is in an error state (dependencies failed to resolve or some error in error list etc)

 When I am fixing targets file - no updates happening project is still in error state. Also if i do any project file changes to my csproj, very often they are not remembered and after i reload csproj file it does not contain my recent changes (this side effect i think was reported a while back, but i did see it multiple times while was converting from classic to core csproj, so thought it is worth of mentioning).

**Comment by davkean** [comment]
Can you expand on the repro and have clear repro steps so that I can move this to CPS?

For example, I don't understand what this means:
> no updates happening project is still in error state.

What is "error" state?

**Comment by davkean** [comment]
@abpiskunov Please reopen this against CPS when you've provided more information - I don't understand the bug.
