### ISSUE TITLE
Project file opened in the editor disappears when reopening solution

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2761]
- Open core csproj file for editing in VS
- then open some cs file 
- Save All and close solution
- Open solution again 
- Project file is still opened as a Tab in the editor - Click on it

Actual result: Tab with csproj immediately disappears

Expected: Either never remember csproj opened in the editor and don't open it after solution reload, or if it is open it should be editable and not disappear everytime tab is activated.

**Comment by davkean** [comment]
Ideally we'd want this editor to reopen - I don't know the complexity of that given the temporary file solution we have at the moment, so it might be easier to opt out of that until we move to the real project file editing.

**Comment by davkean** [comment]
This has now been fixed in 15.7 as we've moved to editing the real file.
