### ISSUE TITLE
[Regression] If core project has package dependencies and version of the package changed , some times Dependencies tree has all yellow icons even though restore was OK

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2764]
- I have a core csproj and all Dependencies are having normal icons
- i change a version for some package (that lives in some imported targets file, not directly in the csproj , not sure if it could matter)

Actual result: Sometimes all Dependencies are yellow even old ones that did not change and stay this way until project is reloaded manually. 

This is a regression, and used to work in the spring for me. What is probably happening is DT build that brings resolved dependencies is lost or some miscommunication at sdk level ...

**Comment by davkean** [comment]
This is what I tried, started with:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="4.0.1" />
  </ItemGroup>

</Project>
```

Changed that to:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="5.0.1" />
  </ItemGroup>

</Project>
```

Saved project.

Dependency node showed a warning at first, but after the design-time build and we propagated it removed the warning.

Can you provide a repro or more concrete repro steps?

**Comment by abpiskunov** [comment]
:) you have a small "vanilla" app that is quick and small. You would need to try it with our project system solution. I have seen it 2 times today. $/DevDiv/Offcycle/WPT/WebToolsExtensions/Main/ProjectSystem.sln .

Sync $/DevDiv/Offcycle/WPT/WebToolsExtensions/Main/ and from DevCmd run build.cmd first. Then open solution and try to change version in $/DevDiv/Offcycle/WPT/WebToolsExtensions/Main/Extensions.Dependencies.Versions.targets..

**Comment by abpiskunov** [comment]
It might not repro everytime , and i don't have consistent steps, but i see it several times a day when actively editing targets.

**Comment by drewnoakes** [comment]
@abpiskunov do you still see this? There's not much actionable information in this bug report.

**Comment by drewnoakes** [comment]
Closing this as there's no clear action or repro.
