### ISSUE TITLE
Warning icon in nuget dependencies tree if TFM shortname is written in different style

### ISSUE THREAD

**Issue by WonyoungChoi** [dotnet/project-system#2772]
I'm using 15.3.3.

with this csproj,
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard20</TargetFramework>
  </PropertyGroup>
</Project>
```
the warning icon  appears in nuget depedencies tree. but project build succeeds without errors and warnings. 

Nuget parses various styles of shortname to produce the same Moniker. ex) netstandard2, netstandard2.0, netstandard20. Therefore it should be resolved successfully in dependencies tree.

I think this is due to the code below. The following code compares the references of two TargetFramework objects, not the Monikers of them. 

https://github.com/dotnet/project-system/blob/2791694201d05525d19edb17fa4325d4c3e8cd79/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/PackageRuleHandler.cs#L152

**Comment by Pilchie** [comment]
This is fixed by #3082.
