### ISSUE TITLE
Up-to-date check skips Pack, even after Rebuild

### ISSUE THREAD

**Issue by AArnott** [dotnet/project-system#2779]
1. Create a new .NET Standard library in VS 2017 (15.4 Preview 1)
1. Right-click the project and click Pack.
1. Pack again (this time, it skips, as appropriate).
1. Right-click the project and click Rebuild.
1. Pack again.

**Expected**

The nupkg is rebuilt

**Actual**

The Pack is skipped due to the up-to-date check. Double-checking the timestamps reveals indeed that the nupkg file is older than the rebuild .dll.

I even _deleted_ the nupkg file and clicked Pack again, and it *still* skipped packing.

**Comment by davkean** [comment]
@panopticoncentral Can you work with NuGet to make them play nicely with this?

**Comment by panopticoncentral** [comment]
This is covered by https://github.com/dotnet/project-system/issues/2923.
