### ISSUE TITLE
Renaming an item when EnableDefaultCompileItems is false causes project-system to crash

### ISSUE THREAD

**Issue by ericstj** [dotnet/project-system#2782]
To repro:
1. File > new project > .NET Core application.
2. Edit project to set EnableDefaultCompileItems to false.
3. Rename Program.cs to Program_foo.cs

Not sure if crash is the right word here, but I see
![image](https://user-images.githubusercontent.com/8918108/29988227-08d0419c-8f21-11e7-8760-899ad8952bcb.png)

File is here: [VsProjectFault_133de706-8b11-4ab0-b9a7-588b939e2c02.failure.txt](https://github.com/dotnet/project-system/files/1271555/VsProjectFault_133de706-8b11-4ab0-b9a7-588b939e2c02.failure.txt)

**Comment by davkean** [comment]
Closed in lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=489340&fullScreen=false&_a=edit.

**Comment by adrianvmsft** [comment]
@ericstj Unfortunately, I wasn't able to repro this issue. However, we think may be fixed in Update 3 or newer. Could you let me know if see it again on more recent builds?
Thanks,
Adrian
