### ISSUE TITLE
.NET Core/.NET Standard build performance

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2789]
This is an overarching issue that I'm using to track evaluation/build performance issues across all repos. This has a .NET Core/.NET Standard focus, but due to overlap, improvements such as https://github.com/Microsoft/msbuild/issues/1276, will improve all project types.

## Notes:
- Due to the behavior of projects inheriting their project references' evaluation cost during a build, evaluation is overwhelmingly the largest cost. It is also affects all scenarios inside and outside of VS. All focus should be on reducing this cost first, followed by design-time build task/target time, then full build (both VS and CLI) task/target time.
- In huge solutions, I'm seeing GC CPU time from 15% - 25%. For these, we should focus on evaluation allocations and get this to under 10%.
- In small solutions, I'm seeing evaluation time, in particular [disk walks](https://github.com/Microsoft/msbuild/issues/2392), [disk lookups](https://github.com/Microsoft/msbuild/issues/2534) and [expressions](https://github.com/dotnet/sdk/issues/1586) be problematic. Focus should be reducing number of globs, and removing unnecessary expressions especially ones that use property functions.

## Evaluation
Long evaluation times increases almost all scenarios including project load, adding/removing files, build, time-to-intellisense. Because both project systems will block the UI thread waiting for this - single project evaluation should be 20-50 ms.

### CPU Time
Breakdown: [Overhead of evaluation is too high for design-time build](https://github.com/dotnet/sdk/issues/1586)

% |Bug|Owner|Scenario|Notes
---:|---|---|:---:|---|
~30-50%~|~[For large projects with globs, MSBuild takes up to 30% - 50% of a build searching the disk](https://github.com/Microsoft/msbuild/issues/2392)~|MSBuild|All
~10-60%~|~[Avoid double evaluation of all ProjectReferences](https://github.com/Microsoft/msbuild/issues/1276)~|MSBuild|All|~In PR: https://github.com/Microsoft/msbuild/pull/2595.~
~30-50%~|~[Early evaluation of invalid DefaultCompileItems recursive itemgroup performance issue during incremental builds](https://github.com/Microsoft/msbuild/issues/2502)~|MSBuild|VS only|Affects evaluation inside VS process when project is opt'd out of globs. Just need CPS to consume new option.
~9-20%~|~[Adding .NET Standard reference assemblies is consuming lots of time in build](https://github.com/dotnet/standard/issues/442)~|.NET|All|Note, this is with globs turned off
30%|[Performance: reduce overhead of computing full path for items from globs](https://github.com/Microsoft/msbuild/issues/2645)|MSBuild|VS only
_|~[Performance inside Project.GetAllGlobs](https://github.com/Microsoft/msbuild/issues/2647)~|MSBuild|VS only|
3-20% |[IndexOfAny/ProbablyContains/InitializeProbabilisticMap is showing up on radar](https://github.com/Microsoft/msbuild/issues/2411)|MSBuild/.NET|All|Needs investigation, could be reduced once globbing speed up.
~0-13.0%~|~[Normalize include and exclude specs before file walking](https://github.com/Microsoft/msbuild/pull/2557)~|MSBuild|All
5-11%|[Builds are spending lots of time of CPU just sleeping](https://github.com/Microsoft/msbuild/issues/2391)|MSBuild|All
10%|[Optimize away separate evaluation for /restore when the restore didn't actually pull down new props/targets](https://github.com/Microsoft/msbuild/issues/2677)|CLI|
3.5%|[Importing Microsoft.CodeAnalysis.targets costs ~3.5% of evaluation time of solution-wide design-time build](https://github.com/dotnet/roslyn/issues/22111)|Roslyn|All
3%|[Projects are paying 3% of evaluation of a solution-wide design-time build importing targets they don't use](https://github.com/Microsoft/msbuild/issues/2524)|MSBuild|All
2.8%|[MSBuild throws thousands of first-chance exceptions evaluating projects with certain types of property functions](https://github.com/Microsoft/msbuild/issues/2217)|MSBuild|All|This was reduced here: https://github.com/Microsoft/msbuild/pull/2833.
2.5%|[2.5% of CPU time in build is spent evaluating unnecessary Exists() in conditions for a solution-wide design-time build](https://github.com/Microsoft/msbuild/issues/2534)|MSBuild|All
1.6%|[Calculating $(TargetPlatformSdkPath)/$(TargetPlatformDisplayName)  takes up 1.6% of evaluation of a solution-wide design-time build](https://github.com/Microsoft/msbuild/issues/2519)|MSBuild|All
~1.4%~|~[Calculating $(FrameworkPathOverride) takes up to 1.4% of evaluation of a solution-wide design-time build](https://github.com/Microsoft/msbuild/issues/2518)~|MSBuild|All|Done
~1.3%~|~[Calculating $(CodeAnalysisPath)/$(CodeAnalysisStaticAnalysisDirectory) in Microsoft.CodeAnalysis.targets takes up 1.3% of evaluation of a solution-wide design-time build](https://github.com/dotnet/roslyn/issues/22110)~|Roslyn|All|In PR.
1.2%|[Non-trivial amount of lock contention](https://github.com/Microsoft/msbuild/issues/2429)|MSBuild|All|Note this is just CPU time calling Monitor.Enter - blocked thread time will be much higher. MSBuildNameIgnoreCaseComparer portion of this was addressed.
~1.0%~|~[Resolving ToolsVersion costs 1% of a build and 2% of all allocations](https://github.com/Microsoft/msbuild/issues/2604)~|MSBuild|All
1.0%|[Calculating $(_DebugSymbolsOutputPath) takes up 1% of evaluation of a solution-wide design-time build](https://github.com/Microsoft/msbuild/issues/2520)|MSBuild|All
~0.9%~|~[MSBuild is still opt'ing into the legacy GetFullPath behavior](https://github.com/Microsoft/msbuild/issues/2338)~|MSBuild|All|We need a bug against VS to also opt in
0.7%|[Calculating $(_DirectoryBuildPropsBasePath)/$(_DirectoryBuildTargetsBasePath) takes up 0.7% of evaluation of a solution-wide design-time build](https://github.com/Microsoft/msbuild/issues/2521)|MSBuild|All
~0.5%~|~[Calculating whether a .NET Standard library ref is a facade costs 0.5% of solution-wide design time build](https://github.com/dotnet/standard/issues/494)~|.NET|All

### Memory
% |Bug|Owner|Scenario|Notes
---:|---|---|:---:|---|
11.5%|[Lookup/ItemDictionary make up a huge amount of allocations/CPU item ](https://github.com/Microsoft/msbuild/issues/2587)|MSBuild|All
4.8%|[ExpandExpressionCaptureIntoStringBuilder is spending ~4.8% of allocations resizing the string builder](https://github.com/Microsoft/msbuild/issues/2696)|MSBuild|All
5-9%|[LazyOperation.Apply can allocate 5% to 9% opening a solution](https://github.com/Microsoft/msbuild/issues/2599)|MSBuild|All
~2.6 - 5.5%~|~[ItemFragment.CreateFileMatcher allocating 2.6% of solution-wide design-time build just getting directory name](https://github.com/Microsoft/msbuild/issues/2551)~|MSBuild|All
~3.0%~|~[Reduce allocations in ExpandExpressionCaptureIntoStringBuilder](https://github.com/Microsoft/msbuild/pull/2437)~|MSBuild|All
~2.7%~|~[FileMatcher is allocating twice it needs to due to using Directory.GetFiles/GetDirectories](https://github.com/Microsoft/msbuild/issues/2287)~|.NET|All|Fixed in .NET Framework 4.7.2
~2.4%~|~[Large allocation via GetEnvironmentVariables](https://github.com/Microsoft/msbuild/issues/2402)~|MSBuild|All|This was cut in half
~2.0%~|~[Resolving ToolsVersion costs 1% of a build and 2% of all allocations](https://github.com/Microsoft/msbuild/issues/2604)~|MSBuild|All
~0.5% - 1.7%~|~[Globbing is boxing enumerators causing 0.5% of all allocations opening solution](https://github.com/Microsoft/msbuild/issues/2285)~|MSBuild|All
~2.0%~|~[ProcessItemSpec allocating 2.0% of all allocations](https://github.com/Microsoft/msbuild/pull/2589)~|MSBuild|All
~%0-2.0%~|~[Avoid iterator/list allocations when parsing projects](https://github.com/Microsoft/msbuild/pull/2577)~|MSBuild|All
~1.6%~|~[Remove short-lived List<T> allocations from SplitSemiColonSeparatedList](https://github.com/Microsoft/msbuild/pull/2586)~|MSBuild|All
~1.5%~|~[Do not allocate in TaskItem.GetHashCode](https://github.com/Microsoft/msbuild/pull/2267)~|MSBuild|All
~0.4 - 1.4%~|~[Large amount of allocations during evaluation due to boxing of KeyedObject](https://github.com/Microsoft/msbuild/issues/2561)~|MSBuild|All
~1.4%~|~[Reduce allocations in Lookup.GetItems](https://github.com/Microsoft/msbuild/pull/2624)~|MSBuild|All
~1.3%~|~[Updating conditioned properties is adding 1.3% of evaluation allocations](https://github.com/Microsoft/msbuild/issues/2575)~|MSBuild|All|We've opted out of this in CPS.
~1.2%~|~[Unnecessary List<T> instantiation](https://github.com/Microsoft/msbuild/pull/2588)~|MSBuild|All
1.0%|[Getting filename/extension metadata allocations 1% of solution-wide design-time build](https://github.com/Microsoft/msbuild/issues/2435)|MSBuild|All
1.0%|[Don't read comments when reading imports](https://github.com/Microsoft/msbuild/issues/2576)|MSBuild|All
~1.0%~|~[MSBuildNameIgnoreCaseComparer is allocating 1% of a solution-wide design-time build](https://github.com/Microsoft/msbuild/issues/2434)~|MSBuild|All
~0.8%~|~[ProjectInstance.GetItemsByItemTypeAndEvaluatedInclude allocates ~0.8% of open solution](https://github.com/Microsoft/msbuild/issues/2283)~|MSBuild|VS only
~0.7%~|~[TaskItemSpecFilenameComparer.Compare allocations 0.7% of a solution-wide design-time build](https://github.com/Microsoft/msbuild/issues/2433)~|MSBuild|All
0.6%|[MSBuild is boxing 25 MB worth of ImmutableList<T>/List<T> enumerators](https://github.com/Microsoft/msbuild/issues/2265)|MSBuild|All
~0.4%~|~[Remove unneeded allocations in ItemSpec.MatchesItem](https://github.com/Microsoft/msbuild/pull/2330)~|MSBuild|All
~0.2%~|~[Remove enumerator boxing](https://github.com/Microsoft/msbuild/pull/2438)~|MSBuild|All
~0.2%~|~[Remove boxed enumerator allocation](https://github.com/Microsoft/msbuild/pull/2622)~|MSBuild|All

## Build
Long build times increases F5, project load (legacy), editing (legacy) and time-to-intellisense. Because the legacy project system blocks the UI thread waiting for this - a single project design-time build should be 100-200ms.

### CPU Time
Breakdown (design-time build): [Overhead of SDK build targets is too high for design-time builds](https://github.com/dotnet/sdk/issues/1496)
Breakdown (normal build): [Overhead of SDK build targets is too high for a normal build](https://github.com/dotnet/sdk/issues/1534)

Term|Meaning
---|---
CLI build|Command-line build of a project or a solution
Design-time build|Design-time build of a single project
VS build|Visual Studio build of a project or a solution

% |Bug|Owner|CLI build|Design-time build|VS build|Notes
---:|---|---|:---:|:---:|:---:|---|
0-33%|[Loading NuGet/JSON.NET binaries adds ~130ms to a build](https://github.com/dotnet/sdk/issues/1483)|CLI|●|||Node reuse does not help. Hurts single project build significantly.
~25%~|~[improve NuGet.targets perf for implicit restore](https://github.com/NuGet/NuGet.Client/pull/1866)~|NuGet|●|||
~20%~|~[Use msbuild /restore instead of a separate process](https://github.com/dotnet/cli/pull/7896)~|CLI|●|||
17%|[_ComputeLockFileReferences/RunResolvePackageDependencies should be faster when projects are up-to-date](https://github.com/dotnet/sdk/issues/1116)|CLI|●|●|●|
~12%~|~[Add reference metadata to indicate that RAR can skip dependency searching](https://github.com/dotnet/sdk/pull/1725)~|MSBuild|●|●|●|
7%|[FindReferenceAssembliesForReferences accounts for 7% of a design-time build](https://github.com/Microsoft/msbuild/issues/2439)|MSBuild|●|●|●|
5.6%|[Facades with references versioned 0.0.0.0 cause lots of issues for RAR](https://github.com/dotnet/core-setup/issues/3297)|.NET|●|●|●|
~5%~|~[5% of a build is due ResolveAssemblyReferences's cache checking](https://github.com/Microsoft/msbuild/issues/2440)~|MSBuild|●|●|●|Ended up only winning ~1%
0.6%|[_GenerateCompileDependencyCache is still consuming non-trivial time in design-time build](https://github.com/Microsoft/msbuild/issues/2442)|MSBuild|●|●|●|
~0.1%~|~[GetInstalledSDKLocations runs in every project regardless of whether they even target a Windows SDK](https://github.com/Microsoft/msbuild/issues/2443)~|MSBuild|●|●|●|
_|[MSBuild has non-trivial overhead due to JIT'ing](https://github.com/Microsoft/msbuild/issues/2419)|MSBuild|●|||Node reuse does not help.
_|~[Two versions of JSON.NET are being loaded during a build](https://github.com/dotnet/sdk/issues/1484)~|CLI|●|||Node reuse does not help.
_|[Design-time builds in CPS are doing too much work because BuildingProject is set to true](https://github.com/Microsoft/msbuild/issues/2417)|MSBuild||●
_|[.NET Core-based projects are not using the RAR cache in design-time builds](https://github.com/dotnet/project-system/issues/3022)|Project||●

### Memory
% |Bug|Owner|CLI build|Design-time build|VS build|Notes
---:|---|---|:---:|:---:|:---:|---|
~20%~|~[Reduce AssemblyName allocations](https://github.com/Microsoft/msbuild/pull/2676)~|MSBuild|●|●|●|
~11%~|~[Avoid cloning AssemblyName](https://github.com/Microsoft/msbuild/pull/2658)~|MSBuild|●|●|●|
6.5%|[ResolvePackageDependencies is producing 6.5% of allocations in a build](https://github.com/dotnet/sdk/issues/1711)|CLI|●|●|●|
~3.7%~|~[FileUtilities.HasExtension allocating 3.7% of a solution build](https://github.com/Microsoft/msbuild/issues/2693)~|MSBuild|●|●|●|
3.7%|[ResolveNuGetPackageAssets allocates 3.7% of solution-wide design-time build](https://github.com/dotnet/sdk/issues/1605)|CLI|●|●|●|
3.3%|[ConflictResolver.ResolveConflict is ~3.3% of all allocations in solution-wide design-time build](https://github.com/dotnet/sdk/issues/1604)|CLI|●|●|●|
~0.3%~|~[NuGet.ProjectModel reads column/line information producing 15 MB of unneeded garbage](https://github.com/NuGet/Home/issues/6139)~|NuGet|●|●|●|

## Customer action items:

- Remove `<PackageReference/>` to NETStandard.Library.NETFramework - this has been replaced with functionality as part of .NET Core 2.0 SDK.
- Upgrade to 2.1 of .NETStandard.Library.

**Comment by DamianEdwards** [comment]
Should we like this to the issue on MSBuild for RAR perf too?

**Comment by davkean** [comment]
Targets, including RAR, are linked from [Overhead of SDK build targets is too high for a normal build](https://github.com/dotnet/sdk/issues/1534).

**Comment by DamianEdwards** [comment]
@davkean there's microsoft/msbuild#2015 too

**Comment by DamianEdwards** [comment]
There's microsoft/msbuild#2015 too

**Comment by davkean** [comment]
Hmm, need to understand why https://github.com/Microsoft/msbuild/pull/2192 hasn't moved the mile - does it only kick in on the .NET Core build?

**Comment by kiwiant** [comment]
Here is a real world example of the difference between the two web sites building on VS 2017 15.3.4 with an SSD. Full clean was performed before running each test of a full solution rebuild (including the test projects):

Solution A (.NET Framework 4.7, 2,555 .cs files, 20 projects) - rebuild time 0:31

Solution B (.NET Core 2.0, 827 .cs files, 19 projects) - rebuild time 2:13 (1:44 with ESET AV 6.5.2107.1 disabled).

**Comment by Pilchie** [comment]
Moving remaining work to 15.6.

**Comment by dasMulli** [comment]
The efforts so far have lead to a significant improvement for incremental builds!
Using https://github.com/dasMulli/cli-incremental-perf-testbed, unscientific measurements for incremental builds (macOS 10.13.1, `time dotnet build --no-restore`) are:

| run / version   | 2.0.3 | 2.1.3-preview-007232 | 2.2.0-preview1-007736 |
|-----------------|-------|----------------------|-----------------------|
| initial         | 1m17s | 56s                  | 41s                   |
| 1st inremental  | 55s   | 36s                  | 22s                   |
| 2nd incremental | 1m3s  | 37s                  | 23s                   |
| 3rd incremental | 52s   | 34s                  | 22s                   |

Thanks for the continued effort! ❤️ 🍻

**Comment by davkean** [comment]
@dasMulli Thanks! We're as you can see, we're making some pretty significant progress in 2.2 - more coming.

**Comment by 4creators** [comment]
@davkean It seems there one very good test of build infrastructure performance using dotnet coreclr repo : https://github.com/Microsoft/msbuild/issues/2843

`up-to-date` check takes 55% of clean build time. In numbers: 
- `clean build` time for managed tests only: `16:27.30`
- `up-to-date check` for managed tests only without any build action: `09:04.63`

**Comment by davkean** [comment]
@4creators At the moment we're focusing on reducing process overhead (enabling the C# compiler server and also MSBuild node reuse on .NET Core/dotnet). Afterwhich we're looking at reducing up-to-date builds. It would be interesting to see if CoreCLR's issues are due to their custom build or just merely MSBuild overhead. I suspect both are at fault.

**Comment by Pilchie** [comment]
Moving to 15.7.  We've made a lot of progress here in 15.6, and more is already underway for 15.7.  However, we also need to take stock and re-evaluate/re-profile to see what the current largest costs are.

**Comment by NinoFloris** [comment]
Thanks for all the work that landed in 2.1.0-preview1, It's highly appreciated!

I'd actually like to help with a few of these issues so new info around latest hotspots is very welcome, hard to profile on osx.

**Comment by davkean** [comment]
As a heads up, more improvements have been made in Preview 2 - https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/.

![image](https://user-images.githubusercontent.com/1103906/38791029-85ecfaac-4188-11e8-99c5-6d52548b6774.png)

**Comment by davkean** [comment]
At this point, we've spent a large effort improving performance across build, solution load, branch switching and few other areas for VS 15.5, 15.6, 15.7 and continuing to do so in 15.8. Post 15.8 it will continue to be a focus. At this point, this overarching bug has now outlived its usefulness and we're no longer using it to drive issues. Each individual issue that it pointed out has individual bugs and we'll be using those to track the issues it raised.

**Comment by kiwiant** [comment]
Agreed. Thanks for all the hard work on this. Performance is orders of magnitude better now.
