### ISSUE TITLE
Remove concept of "short name" in TargetFramework

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2795]
TargetFramework has a short name concept - this has been fraught with bugs https://github.com/dotnet/project-system/issues/2713 and https://github.com/dotnet/project-system/issues/2388 because it's really tempting to compare it. Short name is not-canonical and should never be compared, it is solely a convenience used for developers writing project files.

We should remove concept of TargetFramework.ShortName.

**Comment by drewnoakes** [comment]
Currently we use the short form in dependency ID strings. Using the long form will increase memory consumption.

Blocking this on #5051.

**Comment by drewnoakes** [comment]
#5051 has been addressed, unblocking this.

`TargetFramework.FrameworkName` was removed in dfc437c6462b115a917075eafcd5aeaf985b541a, leaving only properties `FullName` and `ShortName`. When we remove `ShortName`, we may be able to remove `TargetFramework` altogether.
