### ISSUE TITLE
ConfigurationGeneralFile.xaml should be included as Invisible

### ISSUE THREAD

**Issue by adrianvmsft** [dotnet/project-system#2809]
Currently ConfigurationGeneralFile.xaml is included using Context File in
MSBuild\Microsoft\VisualStudio\Managed\Microsoft.Managed.DesignTime.targets

Because of that, it applies to all items, and causes issues when opening the properties dialog:
# Property pages have duplicate properties
https://developercommunity.visualstudio.com/content/problem/76988/property-pages-have-duplicate-properties.html
## Repro steps
1. Create a .NET Core project (e.g. C# Console app)
2. Add a TypeScript Json Configuration File to this project
3. Right click on *.json file -> Properties
Result: There are two "General" categories in the properties dialog.

# Properties for implicitly included folders displays error message
## Repro steps
1. Create a .NET Core project(e.g. C# Console app)
2. Create a new Folder Foo
3. Add a new item - c# file under Foo (this way Foo becomes an implitly included Folder)
4. Right click on Foo, properties
5. Click on the "Configuration Properties" Category

Result: "Could not find project item with item type 'Folder' and include value 'Foo\'."
This is because the rule uses a datasource that doesn't support implicitly included folders

# Inconsistent behavior between properties dialog and properties pane
Properties dialog displays in some cases different properties comparing to the properties pane

Fix is to include the rule using "Invisible" context in
MSBuild\Microsoft\VisualStudio\Managed\Microsoft.Managed.DesignTime.targets
```xml
    <PropertyPageSchema Include="$(ManagedXamlResourcesDirectory)ConfigurationGeneralFile.xaml">
      <Context>Invisible</Context>
    </PropertyPageSchema>
```

**Comment by davkean** [comment]
@adrianvmsft Who owns the other definition here? Why would we include this rule at all if its invisible (and hence probably doing nothing?)

**Comment by adrianvmsft** [comment]
The other defintions come from item type specific rules (e.g. Compile.xaml, EmbeddedResource.xaml, None.xaml, etc). For implicitly included folders, there is Folder.xaml rule.

Removing ConfigurationGeneralFile.xaml could be another option. However, we saw that in the CPS code base we use the generated code from it quite extensively as a common way of accessing item properties - not sure if same applies in the dotnet project system, so marking it as Invisible seems better and safer than removing it.

**Comment by davkean** [comment]
If it's not used I'd prefer us to remove it to avoid having to understand why it exists in the future.
