### ISSUE TITLE
"Class Diagram" item is missing from "Add New Item" menu for .net standard projects

### ISSUE THREAD

**Issue by Andrey-iTech** [dotnet/project-system#2820]
"Class Diagram" item is missing from "Add New Item" menu for .net standard projects (e.g. `<TargetFramework>netstandard1.3</TargetFramework>`)

![image](https://user-images.githubusercontent.com/29973552/30368888-450e783c-987b-11e7-92c7-4aa7d351fb4a.png)

The issue depends on #256 because without it the diagrams don't work in .net standard projects.

VS version 15.3.4.

Workaround:
Copy existing class diagram from .net core project to .net standard project.

**Comment by davkean** [comment]
This was fixed in 15.6, but make note there are still some blocking bugs around editing class diagrams; https://github.com/dotnet/project-system/issues/3003 and https://github.com/dotnet/project-system/issues/2999. We are looking to fix these for 15.8.

**Comment by ransikerandeni** [comment]
I'm using Visual Studio 2019, and I install Class Designer through VS Installer and still it's missing the Add new Item window.
