### ISSUE TITLE
Calculating $(ManagedXamlResourcesDirectory) is taking ~2% of evaluation for a solution-wide design-time build

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2823]
From: https://github.com/dotnet/sdk/issues/1586.

Pass|File|Line #|Expression|Inc (ms)|Inc (%)|Exc (ms)|Exc (%)|#|Bug
---|---|---:|---|---:|---:|---:|---:|---:|---
Total Evaluation||||6159|100%|54|0.9%||
Properties (Pass 1)||||3312|53.8%|9|0.1%||
ItemDefinitionGroup (Pass 2)||||14|0.2%|2|0%||
Items (Pass 3)||||566|9.2%|24|0.4%||
Lazy Items (Pass 3.1)||||1826|29.6%|158|2.6%||
UsingTasks (Pass 4)||||59|1%|59|1%||
Targets (Pass 5)||||327|5.3%|208|3.4%||
Properties (Pass 1)|Microsoft.Managed.DesignTime.targets|46|`<ManagedXamlResourcesDirectory Condition="!Exists('$(ManagedXamlResourcesDirectory)')" >$(MSBuildThi...`|118|1.9%|115|1.9%|223|

https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L46

**Comment by nguerrera** [comment]
Two thoughts on this if the binder rewrite gets punted:

1. It might be sinplest if the project system just calculated the resource directory once and passed it in.

2. Does `$([MSBuild]::Add(0, $(Value)))` help bind straight to integers? I've used a variant of that once in to force an arg to string.format to be treated as an int.

**Comment by davkean** [comment]
Good ideas, still trying to mash my binder changes in without a complete rewrite - which is proving to be difficult.

**Comment by davkean** [comment]
Going to dup this against: https://github.com/Microsoft/msbuild/issues/2217, ~50% of this cost is the exceptions.
