### ISSUE TITLE
Calculating <PropertyPageSchema> takes up to 1.3% of evaluation in solution-wide design-time build

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2825]
See: https://github.com/dotnet/sdk/issues/1586

Pass|File|Line #|Expression|Inc (ms)|Inc (%)|Exc (ms)|Exc (%)|#|Bug
---|---|---:|---|---:|---:|---:|---:|---:|---
Total Evaluation||||6159|100%|54|0.9%||
Properties (Pass 1)||||3312|53.8%|9|0.1%||
ItemDefinitionGroup (Pass 2)||||14|0.2%|2|0%||
Items (Pass 3)||||566|9.2%|24|0.4%||
Lazy Items (Pass 3.1)||||1826|29.6%|158|2.6%||
UsingTasks (Pass 4)||||59|1%|59|1%||
Targets (Pass 5)||||327|5.3%|208|3.4%||
Items (Pass 3)|Microsoft.Managed.DesignTime.targets|98|`<ItemGroup Condition="'$(DefineCommonManagedItemSchemas)' == 'true'" ><PropertyPageSchema Include="$...`|81|1.3%|22|0.4%|223|

**Comment by Pilchie** [comment]
We've been working on numerous improvements to evaluation in MSBuild itself.  Let's look at this again once some of those are in.

**Comment by Pilchie** [comment]
@davkean is there more you want to do here?

**Comment by davkean** [comment]
Looking at the expression there's basically nothing for us to do here, just MSBuild/profiler overheader.
