### ISSUE TITLE
Copying configuration from Debug is broken

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/project-system#2828]
Repro with Visual Studio 15.3.4 :

1)	Create a new Console App (.NET Core) project.
2)	With the configuration manager, create a new configuration called “Test” copying from “Debug” along with the solution configuration.

Notice that “copying configuration from Debug” does not actually work (missing “Define DEBUG”, different “Optimize code” setting…).

This behavior does repro for net core and net standard apps and libraries.
This behavior does not repro for full framework apps/libraries.

**Comment by davkean** [comment]
This does repro for "full framework" because the configuration settings are stored within the project file - remove them, and you'll see the same behavior. Not really sure what we should do about that.

**Comment by davkean** [comment]
Triage: We need a design for this - please come up with one and propose to the team before you implement this.

**Comment by ocallesp** [comment]
@davkean 
This paste bin contains the first analysis of what is needed. Can you help me review this ?
https://gist.github.com/ocallesp/04825b280f858f9686a3d72c80a98999

**Comment by ocallesp** [comment]
@davkean How to read all the properties from a specific Build configuration <PropertyGroup Condition="'$(Configuration)'=='MyBuildConfiguration'">
It seems there is no API in CPS.

**Comment by ocallesp** [comment]
This require changes in CPS to handle copying from debug.

**Comment by PhilPJL** [comment]
I just hit this same issue.  I see the 'DEBUG' constant issue is mentioned here https://github.com/dotnet/project-system/issues/3674.

If I don't check the 'Define DEBUG constant' in the 'Debug' configuration, 'DEBUG' is actually defined.
If I now create a new configuration based on 'Debug' the  'Define DEBUG constant' isn't checked and 'DEBUG' isn't defined.

Similarly 'Optimize code' for 'Debug' config isn't checked, but is in the indeterminate state for the copied configuration.

If however I 

If I do define the 'DEBUG' constant and Optimize explicitly and then copy the configuration, they are copied.
So I end up with
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Configurations>Debug;Release;Debug-2</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug-2|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Optimize>false</Optimize>
  </PropertyGroup>

</Project>
```

This highlights another bug.  Creating a new configuration added this line
`<Configurations>Debug;Release;Debug-2</Configurations>`
But if I go and delete the new configuration using the configuration manager - edit solution configurations | remove.
The new configuration 'Debug-2' is still listed in <Configurations> along with all configuration specific settings.
In addition renaming the configuration doesn't work.

VS 16.10 Preview 1.0
.NET 5 console app.

**Comment by ocallesp** [comment]
Move to CPS AB#1679571
