### ISSUE TITLE
Some shortcuts are missing when creating a new Project or File

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2829]
start VS;
Create a new project, File --> New
Actual result: there is no shortcuts for Project or File under the submenu of New;
![shortcutmissing](https://user-images.githubusercontent.com/22901391/30471516-9ac4b1b8-9a2b-11e7-9f07-766b0d6027bc.PNG)

Expected result: there is shortcuts for Project or File under the submenu of New;
![shortcut](https://user-images.githubusercontent.com/22901391/30471574-d2a1c0d0-9a2b-11e7-8508-62594d3239ec.PNG)

Test on d15rel.26914.00
dotnet --info
```
.NET Command Line Tools (2.0.2-vspre-006949)

Product Information:
 Version:            2.0.2-vspre-006949
 Commit SHA-1 hash:  23fc6ec23d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2-vspre-006949\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by Pilchie** [comment]
Can you confirm what profile was selected during VS First start?

**Comment by MiaomiaoHuangfu** [comment]
Just select the "Default" setting for "additional keyboard mapping scheme".
the issue only repro on build d15rel.26914.00;
verified it not repro on the latest build d15rel.26915.01.

**Comment by davkean** [comment]
Sounds like this is resolved.

**Comment by Xiu-Li** [comment]
Test on d15rel.27117.01
• If I sign in via account "redmond\ddltd2" when first start VS, some shortcuts are missing when creating a new project or file
• If I don't sign in when first start VS, these shortcuts display correctly.
![image](https://user-images.githubusercontent.com/24784908/33007154-629f2a78-ce08-11e7-93eb-0020ceb77296.png)

**Comment by Pilchie** [comment]
It sounds like ddltd2 is configured with a different profile that uses a different keyboard shortcut scheme
