### ISSUE TITLE
output window always  displays black block 

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2830]
create a new project, restore, or build, or run the project, the output window always  displays black block and does not show anything. (neither new projects nor old projects)
![blackblock2](https://user-images.githubusercontent.com/22901391/30472308-66058e68-9a2e-11e7-948c-11cb7f3c5a0f.PNG)

Test on d15rel.26914.00
dotnet --info:
```
.NET Command Line Tools (2.0.2-vspre-006949)

Product Information:
 Version:            2.0.2-vspre-006949
 Commit SHA-1 hash:  23fc6ec23d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2-vspre-006949\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

```

**Comment by Pilchie** [comment]
@hemchander - can you take a look?

**Comment by Pilchie** [comment]
Oops, meant @hemchans.  Sorry.

**Comment by davkean** [comment]
Closed in lieu of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/499761.
