### ISSUE TITLE
Adding existing project requires VS to upgrade the project

### ISSUE THREAD

**Issue by singlis** [dotnet/project-system#2832]
When I add an existing .net project (one that is compliant with the new csproj format for VS2017), VS prompts me to  "upgrade" the project. From what I can tell -- there is nothing causing the upgrade as I have a number of other projects that are in the same format that I added fine with earlier builds of VS2017. 

This is something that I have noticed in the latest version of VS2017. 15.3.3.

Once the project upgrades and is added to the solution, I have noticed a number of things happen:
1) VS adds the project to the solution with this guid:
FAE04EC0-301F-11D3-BF4B-00C04F79EFBC
Where other projects are added with this guid:
9A19103F-16F7-4668-BE54-9A1E7A4F7556

2) It adds an "Any CPU" profile to the solution and all existing projects -- where the project I add has a Platforms tag of x64. All projects prior also only had an x64 target.

3) When loaded in VS, the project can not be "edited" normally like the other projects. I have to unload the project before editing. 

4) The project itself is converted from:
\<Project Sdk="Microsoft.NET.Sdk"/\>
to
\<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0"/\>

It also adds a few properties, such as FileUpgradeFlags,UpgradeBackupLocation and OldToolsVersion. 

Is this experience expected? 

To resolve this, I change the guid in the solution file to the "9A19103..." and revert the project header back to the Microsoft.NET.Sdk (minus the ToolsVersion). Things then work as expected and I can edit the project file without unloading.

**Comment by davkean** [comment]
@singlis Do you have a `<TargetFramework>` property in the project? That's currently [how we sniff whether to open in the new project or the old project](https://github.com/dotnet/project-system/blob/master/docs/opening-with-cps.md).

**Comment by singlis** [comment]
I have a`<TargetFrameworks>` tag since I am targeting multiple frameworks. Would that make a difference?

**Comment by davkean** [comment]
>but pulled in by a build.props file.

Yes, this is the reason.  Our sniff logic only looks in the direct project. Your workaround to change the guid ("project type") is the correct fix for now. This is a limitation that we'll be looking at fixing in a later release.

**Comment by dsplaisted** [comment]
@davkean Could we also look to see whether the `Project` element has an `Sdk` attribute?  That seems like it could be an easy fix that would address more (but not all) cases.

**Comment by davkean** [comment]
Dup'ing this against: https://github.com/dotnet/project-system/issues/2832.
