### ISSUE TITLE
When editing project file, metadata access (`->`) can get mangled

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/project-system#2834]
- Create a .NET Core project
- Edit .csproj in Visual Studio
- Add the following target:
```xml
  <Target Name="CheckForFile" BeforeTargets="_CheckForInvalidConfigurationAndPlatform">
    <ItemGroup>
      <TestItem Include="@(None-&gt;WithMetadataValue('Identity', 'output.txt'))" />
    </ItemGroup>
    <Error Text="file not found" Condition="" />
  </Target>
```
- Save

EXPECTED: Project file is saved as entered
ACTUAL: `->` in `Include` attribute is transformed into `-&gt;`.

**Comment by KirillOsenkov** [comment]
Yes, MSBuild has special magic to avoid doing that:
http://source.dot.net/#Microsoft.Build.Engine/Shared/ProjectWriter.cs,147

**Comment by davkean** [comment]
Closed in lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workitems/edit/499769.

**Comment by davkean** [comment]
CPS won't fixed this, reopening to track the issue.
