### ISSUE TITLE
Adding PackageReference to .Net core SDK based csproj with Version range shows warning until project reload

### ISSUE THREAD

**Issue by YakhontovYaroslav** [dotnet/project-system#2835]
Steps to reproduce:

1. Create empty .Net Core based csproj, optionally target net462
```
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFrameworks>net462</TargetFrameworks>
  </PropertyGroup>
  
</Project>
```
2. Add following PackageReference: 
`<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="[1.1.2,2)" />`
3. Microsoft.EntityFrameworkCore.SqlServer shows yellow triangle as unresolved until csproj reload.
![image](https://user-images.githubusercontent.com/7682768/30511050-99eda110-9ad9-11e7-848c-008547ff4f03.png)

Expected behavior:
No warning shown without project reload.

**Comment by drewnoakes** [comment]
No longer reproduces.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="[1.1.2,2)" />
  </ItemGroup>

</Project>
```

![image](https://user-images.githubusercontent.com/350947/62512619-07ddf700-b85c-11e9-8e88-5b91c157eedd.png)
