### ISSUE TITLE
Adding both Project and Package references to .Net Core SDK based project shows permanent dependency warning, when PackageReference Version range specified

### ISSUE THREAD

**Issue by YakhontovYaroslav** [dotnet/project-system#2836]
This might be somehow related to #2835

### Steps to reproduce:

1. Create project A:
```xml
<Project Sdk="Microsoft.NET.Sdk">  
  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.2.6</Version>
  </PropertyGroup>

</Project>
```
2. Create Project B:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.0.11</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ProjectA" Version="[1,2)" />
     ...
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectA\ProjectA.csproj" />
  </ItemGroup>
  
</Project>
```
3. Build packages.

### Actual behavior:

Build generates .nupkg with correct .nuspec
![image](https://user-images.githubusercontent.com/7682768/30511022-f25f8b5c-9ad8-11e7-9364-a8aee63286fe.png)
but dependencies node shows warning on NuGet
![image](https://user-images.githubusercontent.com/7682768/30511029-1f6d0caa-9ad9-11e7-84a8-ed0adf8750e3.png)

### Expected behavior:
No warning shown on NuGet dependency.

**Comment by Pilchie** [comment]
Why do you want to have both a package reference and a project reference to the same things?

**Comment by YakhontovYaroslav** [comment]
Since SDK based csproj supports setting all .nupkg related stuff inline, we decided to drop .nuspec file dependency during build\pack. This approach (setting Package and Project reference to the same thing)
allows us to not wait for CI build if some one changes both parent (project A, in case project B referencing project A) and project B code, due to fact they are tied as ProjectReferences in same solution. Setting PackageReference in form of 
`<PackageReference Include="A" Version="[1,2)" />`
sets correct version constrains in generated package B nupkg during pack. See in screenshots above R1.Common.DataAccess.Interfaces dependency, that`s our project A is this case. MsBuild analized Version="[1,2)" constraint, and resulted NuGet package of project B contains R1.Common.DataAccess.Interfaces >= 1.2.6 && < 2.0.0 constraint, where 1.2.6 is a current version of this package during build.

**Comment by emgarten** [comment]
The restore behavior is correct, you cannot have both a package and project reference.

I suggest using a condition and passing an additional property when calling pack to switch over to the view you want pack to see.

The root issue here seems to be that pack doesn't support custom version ranges for project references, that is tracked here: https://github.com/NuGet/Home/issues/5556

**Comment by YakhontovYaroslav** [comment]
@emgarten Issue You have referenced will indeed provide descent solution, once implemented, in fact i have suggested similar alternative above. 

But i`m not sure about first part of Your answer. You mentioned that i cannot have both type of references to the same thing, while sure i can. Restore\Build\Pack\etc works flawlessly both in VS, CLI (msbuild) and CI with such approaches. I`m not sure what MsBuild does in this case under the hood, but i`m suspecting it just ignores PackageReference, relying solely on ProjectReference.  The only quirk is dependencies  node in VS UI. It`s not that much of an issue, but it`s really confusing when i`m trying to figure out whether there are real issues with project dependencies or not.

Conditional references will sure fix the problem, but imho it`s just too heavy to embrace and follow for regular developer. In fact Setting PackageReference Version constraints  already forces us to edit csproj manually (adding\updating references through NuGet UI will remove any Version constrains that was set earlier).  Ideally VS should allow user to set Project and Package references version constraints through Properties window and Add Reference\NuGet package dialogs.

**Comment by tmeschter** [comment]
@drewnoakes Take a look and see if this scenario has any weird behavior in the current implementation of the Dependencies tree.

**Comment by drewnoakes** [comment]
The dependencies tree is working correctly here. There is no resolved package in this case, so it appears with a triangle.

I sympathise with the request to make it easier to substitute a project reference in the IDE with a package reference during pack. It seems like @emgarten's approach is the way to go.
