### ISSUE TITLE
Net core compilation fails with files generated during prebuild tasks

### ISSUE THREAD

**Issue by EPinci** [dotnet/project-system#2839]
Hello,

I have a .Net Core project with a prebuild task that generate a class file (.cs) needed during the actual compilation. Since this class is generated on a per build basis, it is also excluded from source control so is that is absent on repository clones.

Problem is that:
- during the first attempt the build fails not finding that class although the pre build task generated it successfully.
- Following builds run fine.
- Deleting the file, show the first build problem again.

I tried explicitly including the class file in the project but the behavior is reversed for now I get a "Duplicate 'Compile' items were included." error in the "following" builds.

**Now this breaks CI/CD scenarios**: in a case I fail on build, in the other I fail on publishing.
This behavior does not happen on full framework project that do not have default globs enabled.

Looks like the dotnet build command enumerates the files to build before the pre build task and not after. Is this a bug?
Is there a way to allow this scenario without disabling globs?

Thank you.

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#1593
