### ISSUE TITLE
In a VB ASP.NET Core Project on adding new Items C# elements are being displayed

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/project-system#2840]
Rudimentary Visual Basic ASP.NET Core projects are possible today. 
Here is a sample .NET Core VB WebAPI project which demonstrates that:

[https://github.com/KlausLoeffelmann/VBAspNetCoreWebApi](https://github.com/KlausLoeffelmann/VBAspNetCoreWebApi)

However, when you try to add new Items to such a Visual Basic project, Visual Studio displays the CSharp Item templates, so currently it is only possible to kind of "manually" add new files to such a Visual Basic project:

![image](https://user-images.githubusercontent.com/9663150/30589566-3c92f902-9d3b-11e7-8ad3-6d2a42a4a388.png)

**Comment by davkean** [comment]
I suspect web is overriding AddItemTemplatesGuid and blindly setting it to C#. We should get them to only set if it's set to the original C# one.

**Comment by Pilchie** [comment]
@BillHiebert is this something that needs to be fixed in the Web project system?

**Comment by abpiskunov** [comment]
Just tried it with 15.6 Preview 1.0 27116.3005.d15.6stg build, which is a bit outdated, but still after this issue was opened, and i can not repro it. If is change project GUID in sln and rename web csproj to vbproj, i see VB item templates.

We define IAddItemTemplatesGuidProvider only fro C# like this:

    [Export(typeof(IAddItemTemplatesGuidProvider))]
    [AppliesTo(Capabilities.DotNetCoreWeb + " & " + Capabilities.CSharp)]
    [Order(10000)]
    internal class WebCSharpAddItemTemplatesGuidProvider : IAddItemTemplatesGuidProvider
    {
        private static Guid ItemTemplateGuid = new Guid(Constants.WebCSharpAddItemTemplateGuidString);

        [ImportingConstructor]
        public WebCSharpAddItemTemplatesGuidProvider(UnconfiguredProject unconfiguredProject)
        {
            UnconfiguredProject = unconfiguredProject;
        }
        
        private UnconfiguredProject UnconfiguredProject { get; }

        public Guid AddItemTemplatesGuid 
        { 
            get 
            {
                return ItemTemplateGuid; 
            } 
        }
    }

**Comment by abpiskunov** [comment]
![image](https://user-images.githubusercontent.com/1592091/34425808-995626bc-ebe4-11e7-9a39-9b99887884b7.png)

**Comment by KlausLoeffelmann** [comment]
I checked, and this is already in production, so can I assume it is also in 15.6?
Anyway, I just tried it with 15.5.2, and it works even when I got rid of the ProjectItemTemplates property.

We can really work with this now, however, Scaffolding - of course - is still available as a menu item, but would produce pure CSharp only code. But that's OK.
