### ISSUE TITLE
Setting 'Project Dependencies' in sln cause inconsistent behavior between VS & dotnet build

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/project-system#2844]
Building our solution involves first building a tool which is used later in the build process.

In order to ensure the tooling is built first, I attempted to configure `Project Dependencies` in VS to create a dependency between a `netstandard2.0` library and a `net461` app (tool).

This works in VS and everything builds correctly, but it fails when building the solution using `dotnet build` with the error:
`C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets(87,5): error : Project 'C:\tmp\BuildOrderRepro\NetCoreApp\NetCoreApp.csproj' targets '.NETCoreApp,Version=v2.0'. It cannot be referenced by a project that targets '.NETStandard,Version=v2.0'. [C:\tmp\BuildOrderRepro\NetCoreApp\NetCoreApp.csproj]`

Repro project: 
[BuildOrderRepro.zip](https://github.com/dotnet/project-system/files/1320475/BuildOrderRepro.zip)

**Comment by davkean** [comment]
Thanks - known and a dup of https://github.com/Microsoft/msbuild/issues/2274.

**Comment by ReubenBond** [comment]
Thanks - sorry, I failed to find the original issue.

**Comment by davkean** [comment]
No probs, I don't mind duping them.
