### ISSUE TITLE
UI is blocked and it takes long time when project need to reload after changes in project file

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2847]
1. Create a Web App netcoreapp2.0
2. wait for restore
3. edit csproj and add net46 target (don't forget to change element name to TargetFrameworks)
4. Save and reload project
5. There will be dialog saying that project needs to reload - click reload button

Actual result:

UI looks like it is frozen and unloading happens about 5 seconds, then UI still frozen and project loaded, but collapsed for another 3-4 seconds, then it expands showing files and finally UI unfreezes and restore happens.

**Comment by Pilchie** [comment]
@abpiskunov do you have a trace?  Moving to 15.6 due to time constraints.

**Comment by Pilchie** [comment]
Closing - please re-open with a trace on a recent build, considering the work that has gone into evaluation improvements, etc.
