### ISSUE TITLE
Configure ProjectSystemSetup to binplace in well defined path

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2850]
ProjectSystemSetup has always dropped the extension in an anonymous path under `Common7\IDE\Extensions` which likely means that NGEN runs are not picking it up. 

This is targeted for Preview 2.

**Comment by davkean** [comment]
@natidea Not sure I follow why would stop us from being NGEN'ing?

**Comment by natidea** [comment]
This is based on feedback I've got from @tannergooding and @jmarolf about how anonymous extensions are usually handled, but we have not actually checked to see if NGEN is working or not.

**Comment by tannergooding** [comment]
So I just talked with @jmarolf. We believe there may have been a bug around this at one point, but it has since been fixed.

The only other reason to provide a well known location is so that anyone who has our binaries as a dependency and also goes through NGEN can themselves be NGEN'd.

**Comment by jviau** [comment]
Another reason for a constant install path is so ML binaries can be profiled by OptProf and later optimized. I am fairly sure only binaries with a constant path can be optimized. I am in the process of adding a solution open/close OptProf scenario, and as soon as ProjectSystemSetup installs to a constant path we can add those binaries to my scenario for training.

Right now Microsoft.VisualStudio.ProjectSystem.Managed.dll has 350ms of JIT in loading Roslyn.sln.

| Name | JitTime   msec | Num Methods | IL Size | Native Size |
|---|---|---|---|---|
| D:\Program Files   (x86)\Microsoft Visual Studio   15.0\Common7\IDE\Extensions\wknjuu1i.vzs\Microsoft.VisualStudio.ProjectSystem.Managed.dll | 355.2 | 340 | 30,790 | 63,818 |

**Comment by natidea** [comment]
I'm testing a build in a constant install path in [PR 89089](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/89089?_a=overview)

**Comment by natidea** [comment]
@jviau are you doing this optimization for 15.6? If so I'll move this bug out

**Comment by jviau** [comment]
It is being done for 15.5. Right now it is optimizing only CPS assemblies. Yours can be added in 15.6 if you want to move this out.

**Comment by Pilchie** [comment]
Are we planning on doing something here for 15.6?  Did we already and I missed it?

**Comment by natidea** [comment]
Looks like I did not complete this. I did test the scenario and everything was working as expected. I'll bring up a PR with this change.
