### ISSUE TITLE
"multiple startup projects" dont mix with "multiple target frameworks"

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/project-system#2855]
Add two console apps to a solution
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.0;net452</TargetFrameworks>
  </PropertyGroup>
</Project>
```

Set one as the startup project and u can choose the framework

![image](https://user-images.githubusercontent.com/122666/30881295-b1542e1a-a348-11e7-8894-c802915f5283.png)

set both as startup projects

![image](https://user-images.githubusercontent.com/122666/30881257-84614014-a348-11e7-90f8-05c867fc90f1.png)

you can now no longer select which framework to run 

![image](https://user-images.githubusercontent.com/122666/30881274-98a8a300-a348-11e7-8174-471b50128d39.png)

**Comment by SimonCropp** [comment]
this would seem to be a fairly significant bug. is anyone looking at it?

**Comment by Pilchie** [comment]
@BillHiebert any ideas?

**Comment by abpiskunov** [comment]
This is explicitly specified in the command logic to work only with single project : https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/StartupProjectHelper.cs#L31 . In case of multiple projects selected you would have to do more work in here https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/DebugFrameworksDynamicMenuCommand.cs to determine set of common frameworks across selected projects.

**Comment by abpiskunov** [comment]
It does not seem to be too hard, just needs to be done carefully, to cover all cases where multiple selection applies, however see if it meets your priorities for 15.6.

**Comment by Pilchie** [comment]
Moving to 15.7, as we're primarily focused on performance and reliability fixes for the remainder of 15.6.

**Comment by bording** [comment]
Having this feature is rather important for us, and we've been watching this issue to see when it might get addressed, only to see it that it keeps getting pushed back.

Is this something you'd be willing to take an external contribution on? If so, would it even be possible to get it into VS before 16.0?

**Comment by Pilchie** [comment]
We'd love to have an external contribution!  As for ship vehicle, we would likely be able to ship it in 15.9 if it comes at a reasonable time, but we're already locking down for 15.8, and it would be unlikely to meet the bar for that release.

**Comment by bording** [comment]
@Pilchie That's good news! As I start looking at this, is there a specific branch I should be targeting?

**Comment by Pilchie** [comment]
I would start with `dev15.9.x`.

**Comment by bording** [comment]
PR opened: #3787

**Comment by mauroservienti** [comment]
There is an ongoing PR, #3787, why was this closed?

**Comment by SimonCropp** [comment]
I did a blanket close of issues i not nonger needed fixed.

**Comment by DavidBoike** [comment]
@SimonCropp (or @Pilchie) would you please reopen this since @bording is actively working on it?

Also, can it be retargeted to the 15.9 milestone?

**Comment by bording** [comment]
Since #3787 was merged, should the milestone on this be changed back to 16.0 and the issue closed?
