### ISSUE TITLE
Errors in the output open files in the wrong project

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2860]
VS 15.5.0 Preview 1.0 26911.3004.d15prerel

Repro

1. I have 2 projects with identical files (having same namespaces - i just copied files form one project to another): Common and Common.CPS (dll names are different obviously).
2. Common.CPS is dotnet core project 
3. Common.CPS misses several assembly references and thus i have some build errors in the output.

Actual result: When i click on the error in the output it opens file from Common (old project) which does not have any build errors, instead of new Common.CPS project.

Expected result: Files from new project Common.CPS should be opened.

Note: when i saw it first i also did not see any errors added to Error List for Common.CPS , only in the output. I assume it is related.

![image](https://user-images.githubusercontent.com/1592091/31025489-aa7a420e-a4f7-11e7-9cce-5e2beaa093a6.png)

![image](https://user-images.githubusercontent.com/1592091/31025493-ad82ed84-a4f7-11e7-8438-a20bf0b72e46.png)

**Comment by Pilchie** [comment]
The output window just matches the first project that has a filename that matches.  There isn't anything the project system can do here.  This is one of the reasons the errorlist exists.
