### ISSUE TITLE
What is the purpose of the new project type guids?

### ISSUE THREAD

**Issue by auduchinok** [dotnet/project-system#2863]
I couldn't find anywhere in docs why adding new guids was needed and why the existing ones wouldn't work?
For existing projects: what is the point of modifying solution files by changing guids only?
/cc @cartermp

https://github.com/dotnet/project-system/blob/c51b89d4d2f5fec2b5c6d668628703027250ddc9/src/Microsoft.VisualStudio.ProjectSystem.FSharp.VS/Packaging/FSharpProjectSystemPackage.cs#L22-L23

**Comment by tannergooding** [comment]
It allows Visual Studio to determine whether the project should be loaded with the legacy or new project system.

**Comment by auduchinok** [comment]
Can I assume that these guids are always used with the new SDK and modern *proj files?

**Comment by davkean** [comment]
@auduchinok While 6EC3EE1D-3C4E-46DD-8F32-0CC8E7565705 will always cause us to opt into CPS, you can't:

1) Assume that LegacyProjectTypeGuid won't open in CPS
2) That such a project is always "modern" SDK-based format.

This new GUID is a temporary workaround, and they will be merged into a single project type in a future version of Visual Studio.

**Comment by auduchinok** [comment]
@davkean Thank you. If feasible, it would be great to reuse existing GUIDs that other tooling continue to use.

**Comment by davkean** [comment]
Yes, that's the eventual aim.
