### ISSUE TITLE
[From Test Day] Dependencies in solution explorer don't have icons

### ISSUE THREAD

**Issue by cartermp** [dotnet/project-system#2864]
Open the [SAFE Bookstore] project in a 15.5 build, and you'll see the following:

![](https://user-images.githubusercontent.com/6309070/30305340-272ba628-9727-11e7-9dbc-61d0f910e6de.PNG)

Not sure if this is a project system or F# bug, but given that it's icon-related I figured it would be better to start here.

**Comment by natidea** [comment]
This is fixed by https://github.com/dotnet/project-system/pull/2845 which went in late last week. It should be fixed in any build 26928.00 or later. What build do you have?

**Comment by cartermp** [comment]
Sounds good.!  This was in d15rel/26927.01 (from test day).
