### ISSUE TITLE
Path too long

### ISSUE THREAD

**Issue by Antaris** [dotnet/project-system#2868]
I have a couple of nested GIT submodules which bring in functionality as part of a distributed Angular app.

Recently, I've started encountering this error:

```
The item metadata "%(FullPath)" cannot be applied to the path "app\pattern-library\node_modules\material-design-icons\device\ios\ic_signal_cellular_connected_no_internet_0_bar.imageset\ic_signal_cellular_connected_no_internet_0_bar.png". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
```

I've tried excluding the `\app` folder from my project as it is only used to build output to be deployed to `\wwwroot` in an ASP.NET Core project. 

Visual Studio won't let me :-(

This is my project file items:

```
  <ItemGroup>
    <Content Include="config\**\*.*" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="wwwroot\**" CopyToPublishDirectory="PreserveNewest" />
    <EmbeddedResource Include="_Content\**\*.*" />
    <None Include="app\**" />
  </ItemGroup>
```

I would have thought `<None Include="app\**" />` would stop it, but it doesn't :-(

Visual Studio 2017 15.3.4

**Comment by Pilchie** [comment]
@livarcocc - This sounds like an SDK issue?

**Comment by livarcocc** [comment]
Yes. There are specific ways to do this exclude.

@dsplaisted can you help @Antaris? Though, as a web app, I thought wwwroot was excluded by default.

**Comment by Pilchie** [comment]
Ping @dsplaisted

**Comment by dsplaisted** [comment]
@Antaris Try this:  Remove the `<None Include="app\**" />` line, and add this to your project:

```xml
<PropertyGroup>
    <DefaultItemExcludes>app\**;$(DefaultItemExcludes)</DefaultItemExcludes>
</PropertyGroup>
```

**Comment by Pilchie** [comment]
@Antaris did that help?

**Comment by Pilchie** [comment]
Closing, since we haven't heard back in more than a week - please let us know if @dsplaisted's suggestion didn't help.

**Comment by Antaris** [comment]
@dsplaisted @Pilchie Sorry for the late reply. I had reorganised my repo to move the angular app (build assets) out of the .NET Core project. 

Justed tested this though and it worked as expected. Many thanks!
