### ISSUE TITLE
Provide a way to inject custom launch profile without needing to modify launchSettings.json file

### ISSUE THREAD

**Issue by mthalman-msft** [dotnet/project-system#2870]
For a custom VS extension to provide its own launch profile, it must implement a MEF component and modify the project's launchSettings.json file so that it will show up as a selectable profile in the VS dropdown.  The modification of the launchSettings.json file is problematic for the extension when the intention is for the profile to be always available without interference of a user's project files.  It would be better if there were a way to make a selectable profile available through an in-memory mechanism.  And only when the user actual selects that profile would it then have its settings persisted to the launchSettings.json file.

**Comment by BillHiebert** [comment]
Changes are in
