### ISSUE TITLE
Add file to a custom item group based on extension (when consuming a NuGet package/custom targets)

### ISSUE THREAD

**Issue by chwarr** [dotnet/project-system#2875]
My [NuGet package](https://microsoft.github.io/bond/manual/bond_cs.html#nuget-packages) targets file (that was automatically included in the referencing project during installation) adds [an item to `AvailableItemName`](https://github.com/Microsoft/bond/blob/ca0d1c63da2760ad5753a6a8bf29b00f8cb01585/cs/build/nuget/Common.targets#L37-L41), which--under the old project system--ended up exposing a way in Visual Studio for my package consumers to quickly add files to that item via the UI. The targets that get installed by my package use a custom item type to perform C# code generation based on the contents *.bond files, which are represented by the `BondCodegen` item. This isn't implemented yet, according to #113.

Is there a way to get the new project system to automatically add *.bond to the `BondCodegen` item like it does for .cs files today? E.g., can I include a ProjectSchemaDefinitions in some file in my package that would automatically get picked up or something?

```
<ProjectSchemaDefinitions
    xmlns="http://schemas.microsoft.com/build/2009/properties">

    <ContentType
        Name="BondIDLFile"
        DisplayName="Bond IDL file"
        ItemType="BondCodegen">
    </ContentType>

    <ItemType Name="BondFile" DisplayName="Bond codegen (gbc)"/>
    
    <FileExtension Name=".bond" ContentType="BondIDLFile"/>
</ProjectSchemaDefinitions>
```

For cross-project reference purposes, see also https://github.com/Microsoft/bond/issues/636

**Comment by danmosemsft** [comment]
@davkean do you know the answer?

**Comment by Pilchie** [comment]
@livarcocc - do you know how to do this?

**Comment by livarcocc** [comment]
I think we have a bug on an email thread on this somewhere already.

**Comment by Pilchie** [comment]
Did this get sorted out in email?

**Comment by chwarr** [comment]
I got some more details via e-mail. I haven't found time to validate whether they work or not.

An edited version of what I was e-mailed:

> The SDK does this is via a props file, which you may be able to have in your
package.
>
> See
> https://github.com/dotnet/sdk/blob/20ab910b14b2d12a0cb7b102168c3fe522b4b2ff/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.DefaultItems.props#L26
> 
> It may be as simple as just having a props file with the following in your
> nuget package.
> 
>     <ItemGroup Condition=" '$(EnableDefaultItems)' == 'true' ">
>       <BondFile Include="**/*.bond" />
>     </ItemGroup>
> 
> You may want to also add this pattern to the
> [DefaultItemExcludes](https://github.com/dotnet/sdk/blob/20ab910b14b2d12a0cb7b102168c3fe522b4b2ff/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.DefaultItems.targets#L26)
> property so that you don't get duplicate
> [None](https://github.com/dotnet/sdk/blob/20ab910b14b2d12a0cb7b102168c3fe522b4b2ff/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.DefaultItems.props#L30)
> items.
> 
>

**Comment by chwarr** [comment]
This turned out to be two separate issues rolled into one:

1. Automatically adding an item to an ItemGroup based on its extension.
    * The fix here was to add the relevant globs guarded by `Condition=" '$(EnableDefaultItems)' == 'true' "` as mentioned in my [January 8, 2018 comment][jan-comment].
1. Getting these items to appear in the Visual Studio 2017 Solution Explorer.
    * The fix here was a three-step process.
        1. Define the [custom items types][custom-item-types].
        1. [Write rules for the custom items][build-action] defining what properties to show in the UI.
            * This example [none.xaml][none-xaml] was used as the starting point for the Bond rules.
        1. [Tell Visual Studio][add-xaml-rules] about the custom items and rules.

For my project, I've started [a pull request][pr] to implement these changes.

[add-xaml-rules]: https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/adding_xaml_rules.md
[build-action]: https://github.com/Microsoft/VSProjectSystem/issues/244#issuecomment-327268174
[custom-item-types]: https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/custom_item_types.md
[none-xaml]: https://github.com/Microsoft/VSProjectSystem/blob/1c0a47aba5a22d3eb071dc097b73851bdeaf68db/samples/WindowsScript/WindowsScript/WindowsScript.ProjectType/BuildSystem/Rules/none.xaml
[jan-comment]: https://github.com/dotnet/project-system/issues/2875#issuecomment-356153052
[pr]: https://github.com/Microsoft/bond/pull/806
