### ISSUE TITLE
'Edit .csproj' using a temporary file causes UI inconsistencies

### ISSUE THREAD

**Issue by gundermanc** [dotnet/project-system#2877]
Right clicking a project and selecting _Edit .csproj_ causes the project system or some other VS component to create a temporary copy of your project file and opens it in the editor. Unfortunately, this results in a substandard editing experience in a few key ways:

- The document well tooltip doesn't show the correct path for the document in its tooltip.
![image](https://user-images.githubusercontent.com/5387680/31400677-57c74974-ada5-11e7-9bad-b3ee90bb9fa4.png)

- Invoking File.Open (e.g.: Ctrl+O) which traditionally opens the directory containing the current document now opens this temporary directory.

![image](https://user-images.githubusercontent.com/5387680/31400808-c484f336-ada5-11e7-9e25-5a99a595eeaa.png)

This looks like a work-around of some sort to prevent bad interactions between the editor when the file is saved and the project system. My question is, if I can edit the file independently in notepad and the project system can react correctly and reload it, could it similarly be loaded and edited directly in the project system? If not, are there changes that we could make to the editor that would allow this?

**Comment by jmarolf** [comment]
I agree we want a better experience here.  There were cases where directly editing the project file and making it invalid (unloadable) would crash Visual Studio.  We'll need to do work the the editor and project system to gracefully handle invalid project files in the same way we invalid code files.

**Comment by jviau** [comment]
This code is in CPS now, and we have it on our backlog to fix these UI consistencies. Unfortunately it will not make 15.5.

**Comment by Pilchie** [comment]
@jviau Does this mean we should close this and track it in CPS?

**Comment by jviau** [comment]
@Pilchie  yes you can close it here or leave it open. Up to you. We are tracking it here in CPS: [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/453750](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/453750)
