### ISSUE TITLE
Repeating the build without changing the code cause few projects to rebuild

### ISSUE THREAD

**Issue by jaydeept** [dotnet/project-system#2880]
I have almost 22 projects in my solution based on .Net Core 2. When I repeat the build without changing the code, cause 19 projects to rebuild and only 3 are recognized as up-to-date. I believe, the second build should say 22 up-to-date.
Do I need to modify anything in csproj file to fix this issue?
JFYI: I have postsharp Nuget package installed in few projects but I don't think that will be causing this issue.

**Comment by davkean** [comment]
You can turn on logging via Options -> Projects and Solutions -> .NET Core. This will tell you the reason you are out of date. Also make sure you are on 15.4.

**Comment by jaydeept** [comment]
Hello @davkean ,

Updating the Visual Studio from 15.3.3 to 15.4 has resolved the issue.
Thank you for your help.

**Comment by davkean** [comment]
No probs, glad we already fixed your issue.
