### ISSUE TITLE
Shift+Space in the managed resource editor doesn't make a space

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2881]
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/128679/shiftspace-in-the-managed-resource-editor-doesnt-m.html) | [506825](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/506825)

Repro Steps:

1. If necessary, create a new managed resource file (*.resx)
2. Open it in the managed resource editor.
3. Edit a string value.
4. Try to type something IN ALL CAPS by keeping the shift key held down as you type.

Observe that as you type while holding the shift key, spaces are ignored. This is very annoying if you're trying to type just a few words in caps.

**Comment by davkean** [comment]
Fixed by https://github.com/dotnet/project-system/pull/3786.
