### ISSUE TITLE
Changing custom tool via dialog without namespace causes dialog error (SDK projects)

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2885]
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/126857/changing-custom-tool-via-dialog-without-namespace.html) | [505817](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/505817)

> An error is raised:
> 
> ========= ==========
> An error has occurred while saving the editied properties listed below:
> 
> Custom Tool
> One or more values are invalid. An internal error occurred. Please contact Microsoft Product Support Services.
> ========= ============
> 
> the workaround is either to temporarily set the "Custom tool namespace", apply then clear it and apply again or edit the project file directly. 
> 
![image](https://user-images.githubusercontent.com/7732033/31478483-87c8c942-aec5-11e7-96d3-caa42434d6ee.png)

I believe the plan is to disable this property page in favor of the Property Grid (which is what desktop projects do) but I cannot find the backlog item on that

**Comment by dlpopescumtk** [comment]
Any updates on this? I have the same message when trying to set the custom tool to _PublicResXFileCodeGenerator_

**Comment by davkean** [comment]
This was fixed in the 15.6 timeframe.
