### ISSUE TITLE
Add/move file gestures in file tree

### ISSUE THREAD

**Issue by cartermp** [dotnet/project-system#2887]
Ref: https://github.com/Microsoft/visualfsharp/issues/3740

Add new file above or below selected item will have to be implemented to get us to feature parity for F# projects.

**Comment by forki** [comment]
This is very important for languages that have explicit file order (that one at least). We need a way to add files below or above other files and a "move file up" / down context menu

**Comment by davkean** [comment]
As a workaround right now, you'll be able to edit the project live and move things around.

**Comment by forki** [comment]
Yes that's what I already do. Thank you for making the fsproj directly
editable from vs btw

Am 13.10.2017 03:35 schrieb "David Kean" <notifications@github.com>:

**Comment by Pilchie** [comment]
Still can't assign issues to @Tihan for some reason :(

**Comment by cartermp** [comment]
Just as an update for community folks - @TIHan has made good progress on this after he sorted out the remaining file ordering issues.

**Comment by TIHan** [comment]
This has been resolved.

**Comment by Pilchie** [comment]
We have the Move, but not the Add, right?

**Comment by TIHan** [comment]
Ah, gotcha. I thought this was only for the move. Re-opening.

**Comment by forki** [comment]
Cool. So that implies ordering is resolved as well?

**Comment by jmarolf** [comment]
@forki yes ordering has been fixed.  These should all be available in the next Visual Studio Preview

**Comment by Pilchie** [comment]
Ordering should *work* in 15.5, though the UI doesn't update live if it's changed in 15.5.  That has been fixed for 15.6 as well.  Also, technically, I think this will show up in the *second* preview from now (15.6 Preview 4), since we've already forked for Preview 3.

**Comment by TIHan** [comment]
Now this is resolved. :) 

We still have more work to do with folders and paste/drop, but we will create separate issues for them.
