### ISSUE TITLE
project.OutputFilePath is null

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/project-system#2889]
@jmarolf 

We retrieve a project following the ProjectAdded workspace event.

At this time the OutputFilePath property is null

@KevinH-MS has also seen this behavior.

Is this expected behavior.

**Comment by davkean** [comment]
We currently only populate immediate output path after the first design-time build - it comes with the compiler arguments.

**Comment by KevinH-MS** [comment]
I'm seeing in the latest d15prerel bits that it often stays null even after doing an explicit full build of the solution.

**Comment by davkean** [comment]
Explicit full builds have no effect on a design-time build.

Can you turn on design-time build logging https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#visual-studio-2017 and tell me if you are seeing the CompileDesignTime target being run for the project before you query it?

**Comment by KevinH-MS** [comment]
And if this isn't a CPS project? (do the same steps to collect logs still work?)

**Comment by davkean** [comment]
In the same document has steps. If it is legacy, I wonder if it's new batched design time builds...

**Comment by KevinH-MS** [comment]
If I ```set TRACEDESIGNTIME=true```, no logs are produced in ```%temp%``` when the issue repros.  If I close and open VS a couple times, eventually the issue goes away and logs are produced.  Thoughts on what to try next?

**Comment by KevinH-MS** [comment]
If I delete the .vs folder and re-open, the issue comes back.

**Comment by davkean** [comment]
If this is a legacy project pull in a Roslyn IDE dev and SvetKere I suspect behavior difference due to batched design-time builds.

**Comment by KevinH-MS** [comment]
Thanks @davkean I've started a thread and opened a VSO bug for the VS IDE team.  Leaving this issue open, because it sounds like there may be a separate issue affecting F#/CPS.

**Comment by Pilchie** [comment]
The F# issue looks like a different issue, where Roslyn's `CPSProject` doesn't update the workspace when the output path changes (and it's initially populated with `null` based on just an evaluation.

**Comment by Pilchie** [comment]
Moved to https://github.com/dotnet/roslyn/issues/22732
