### ISSUE TITLE
Sdk style project does not use CPS project system when added to existing sln

### ISSUE THREAD

**Issue by mhutch** [dotnet/project-system#2891]
If I remove an Sdk-style project from a sln, then re-add it, it gets added to the sln with the old `FAE04EC0-301F-11D3-BF4B-00C04F79EFBC` GUID instead of the new `9A19103F-16F7-4668-BE54-9A1E7A4F7556` GUID, and uses the old project system.

**Comment by Pilchie** [comment]
@davkean  - would this be an issue for core CPS?

**Comment by Pilchie** [comment]
@lifengl - is this an issue in this repo, or VS itself?

**Comment by Pilchie** [comment]
Is this the same thing as #1821?

**Comment by mhutch** [comment]
Nope, my example was VS alone.

However, i can't repro it in 15.5.2. it seems to have been fixed.
