### ISSUE TITLE
Visual Studio/MSBuild can't find references in 4.6.2 project when netstandard libraries are used

### ISSUE THREAD

**Issue by daveaglick** [dotnet/project-system#2892]
I've noticed that with certain combinations of packages (or more specifically, references), some references can't be located by Visual Studio (15.4) and MSBuild when targeting .NET Framework 4.6.2. A repro is at https://github.com/daveaglick/RefProblemRepro.

![2017-10-13_16h03_47](https://user-images.githubusercontent.com/1020407/31564253-210dfa08-b030-11e7-9ae4-8dfbbdf1174b.png)

If I manually remove all the references to `netstandard` libraries, then the other libraries that couldn't be found earlier immediately light up as resolved.

**Comment by davkean** [comment]
In the legacy project system, this often occurs when a build target "removes" a reference that the project explicitly references. We think it's not resolved and hence show the warning. 

@dsplaisted @ericstj do you have any targets in these [.NET packages](https://github.com/daveaglick/RefProblemRepro/blob/master/RefTest/packages.config) or in the conflict handling that are doing that?

**Comment by ericstj** [comment]
@davkean see https://github.com/dotnet/sdk/issues/1499, https://github.com/dotnet/sdk/issues/1244.  This is likely a dup of one of them.

**Comment by Pilchie** [comment]
Sounds like it - resolving as a dupe.
