### ISSUE TITLE
The IConfiguratedProjectReadyToBuild method can run into NullParameterException sometime

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#2895]
I remember I saw this issue before, but @jviau hits this issue when he tries to cache design time build results.  Basically, in line 44:

              var nowActive = _configuredProject.ProjectConfiguration.EqualIgnoringTargetFramework(_activeConfiguredProjectProvider.ActiveProjectConfiguration);

ActiveProjectConfiguration can return null, and this code will throw in this state.  Please fix this issue in 15.6.

        /// <summary>
        /// Gets the project configuration that is active given the active solution configuration.
        /// </summary>
        /// <returns>An existing ProjectConfiguration defined in the project, or <c>null</c> if no active project configuration is available.</returns>
        ProjectConfiguration ActiveProjectConfiguration { get; }

**Comment by davkean** [comment]
Fixed in https://github.com/dotnet/project-system/issues/2437.
