### ISSUE TITLE
[Build] Integration test sometimes fail with "could not write state file" warning

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2898]
VS Dev15.5 Preview 2 d15rel 27016.0

Repro steps (we have automated integration test and i tried them manually too):

1. Create a new core 2.0 Web app wait for restore, save solution
2. Create a new ClassLibrary core 2.0, wait for restore
3. Add project reference web->classlib via Add Reference dialog, wait for restore
4. Build

Actual result (App1 below is web app):

![image](https://user-images.githubusercontent.com/1592091/31685823-35f1180e-b339-11e7-8436-e98efb949e5b.png)

Expected:

no errors/warnings

Note: this happens during our integration test and is not consistent. Manually i did not see it, though did not spend too much time trying. In any case it seems like a problem , test just do it quicker maybe or some other timing issue is going on.

**Comment by Pilchie** [comment]
This seems like an issue for `MSBuild` or the SDK, not the project system.

**Comment by Pilchie** [comment]
@andygerlicher @livarcocc - which repo should this be moved to?

**Comment by livarcocc** [comment]
Seems to me like it should go into the MSBuild repo. @AndyGerlicher can prove me wrong though.

**Comment by davkean** [comment]
This will be overlapped design-time time builds with real builds. This is a project system (CPS) bug.

**Comment by Pilchie** [comment]
@davkean - can you get a bug filed on CPS for this then?

**Comment by davkean** [comment]
Filed: https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workitems/edit/546566.
