### ISSUE TITLE
[Restore] When project gets multiple targets, restore starts delayed 10-15 seconds or more

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2899]
VS Dev15.5 Preview 2 d15rel 27016.0

1. Create a web app core 2.0 and wait for restore
2. Edit project file and add <TargetFrameworks>netcoreapp1.1;netcoreapp2.0;net45</TargetFrameworks>
3. reload project and wait for restore ..

Actual result: 

It just stays there with yellow dependencies and no restore happening.. than after some time it starts . Again no any visual indications that it is pending or running. However this issue track specifically delay for first auto-restore

Expected result:

Restore should start immediately after project reloaded or when solution load complete

**Comment by Pilchie** [comment]
I wasn't able to repro this - restore started about 1s after the reload.  However, I believe this depends on how long it is until we get a designtime build and nominate.

**Comment by Pilchie** [comment]
Related to #2594 and #2805.

**Comment by jmarolf** [comment]
This appears to have been fixed 
**NOTE:** You also get yellow triangles if you forget to change `TargetFramework` to `TargetFrameworks`

```XML
<TargetFramework>netcoreapp1.1;netcoreapp2.0;net45</TargetFramework>
```

```XML
<TargetFrameworks>netcoreapp1.1;netcoreapp2.0;net45</TargetFrameworks>
```
