### ISSUE TITLE
Continuous "Restoring NuGet packages" for non-fixed package version

### ISSUE THREAD

**Issue by emgarten** [dotnet/project-system#2901]
_From @hubuk on March 16, 2017 21:22_

## Details about Problem

**NuGet product used:**
Package Manager Host

**NuGet version:**
Name             : Package Manager Host
Version          : 4.0.0.2323
InstanceId       : 8c772c92-46b0-43ed-86c2-3e11d0663fb2
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : pl-PL
CurrentUICulture : en-US
PrivateData      : NuGetConsole.Host.PowerShell.Implementation.NuGetPSHost+Commander
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

**VS version:**
Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.9 D15RTWSVC

**OS version:**
win10 v1607 (14393.693)

**Worked before? If so, with which NuGet version:**
Not known

## Detailed repro steps so we can see the same problem

1. Create a new project: .NET Standard -> Class Library (.NET Standard)
2. Edit csproj file using "Edit ClassLibrary1.csproj" context menu from Solution Explorer
3. Add following line to PropertyGroup:
```XML
<VersionSuffix>t$([System.DateTime]::Now.ToString(ssff))</VersionSuffix>
```
4. Save the project.
5. Observe continuous "Restoring NuGet packages" in Package Manager Output window
```
Restoring NuGet packages...
Time Elapsed: 00:00:00.0801728
========== Finished ==========

Restoring NuGet packages...
Time Elapsed: 00:00:00.1057414
========== Finished ==========
(...)
```

### Sample Project
Opening one of the following projects in VS2017 will also trigger the problem:
[ClassLibrary1.zip](https://github.com/NuGet/Home/files/849016/ClassLibrary1.zip)
[GitHub repo](https://github.com/hubuk/ClassLibrary1)

_Copied from original issue: NuGet/Home#4830_

**Comment by emgarten** [comment]
_From @rrelyea on March 20, 2017 15:18_

@alpaix  - We likely need to work with the Roslyn-Project-System to solve this one. Can you please propose a solution after working with them?

**Comment by emgarten** [comment]
I believe this was fixed on the project system side in the latest vs.

**Comment by emgarten** [comment]
_From @hubuk on October 18, 2017 5:11_

@emgarten Still reproducible in 15.4

**Comment by emgarten** [comment]
I know this scenario has been mentioned before but I wasn't able to find the duplicate. Possibly this one is different before it uses VersionSuffix instead of Version.

**Comment by maxence51** [comment]
Put a Guid has the same effect : $([System.Guid]::NewGuid())

As a work-around, Rebuild the solution stops the infinite "Restoring NuGet packages" loop.

**Comment by davkean** [comment]
This is caused by having a project evaluation with a side-effect, re-evaluating the same project with the same global properties should result in the same behavior. We have built-in assumptions throughout VS that this is the case. You would be better off using a different versioning scheme such as the wonderful https://github.com/AArnott/Nerdbank.GitVersioning.
