### ISSUE TITLE
Updating packages with constraints through Package Manager UI removes version constraints

### ISSUE THREAD

**Issue by YakhontovYaroslav** [dotnet/project-system#2907]
Steps to reproduce:
1. Create empty .Net Core based csproj, optionally target net462
```
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFrameworks>net462</TargetFrameworks>
  </PropertyGroup>
  
  <PackageReference Include="Newtonsoft.Json" Version="[10.0.1,11)" />
</Project>
```
2. Select Manage NuGet packages on new project
3. Select Updates Tab 
4. Select Newtonsoft.Json and click Update
5. Now PackageReference to Newtonsoft.Json looks like
```
  <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
```

Expected behavior:
PackageReference version constraints persists on update:
```
  <PackageReference Include="Newtonsoft.Json" Version="[10.0.3,11)" />
```

**Comment by Pilchie** [comment]
Also for http://github.com/Nuget/Home.
