### ISSUE TITLE
Project reference in new csproj format do not obey PriveAssets? (VS2017 15.4)

### ISSUE THREAD

**Issue by philippe-lavoie** [dotnet/project-system#2909]
According to issue 2313, when adding below inside BasicModel, it should stop the reference from flowing to other projects.

```
  <ItemGroup>
    <ProjectReference Include="..\BasicModule.Contracts\BasicModule.Contracts.csproj" PrivateAssets="All">
    </ProjectReference>
  </ItemGroup>
```

However, inside my unit tests, which does a project reference to BasicModel, the project.assets file contains the following

      "BasicModule/40.0.0": {
        "type": "project",
        "framework": ".NETStandard,Version=v2.0",
        "dependencies": {
          "Module": "40.0.0"
        },
        "compile": {
          "bin/placeholder/BasicModule.dll": {}
        },
        "runtime": {
          "bin/placeholder/BasicModule.dll": {}
        }
      },
      "BasicModule.Contracts/40.0.0": {
        "type": "project",
        "framework": ".NETStandard,Version=v2.0",
        "dependencies": {
          "Contracts": "40.0.0"
        },
        "compile": {
          "bin/placeholder/BasicModule.Contracts.dll": {}
        },
        "runtime": {
          "bin/placeholder/BasicModule.Contracts.dll": {}
        }
      },

So, chaining is definitely still occurring.

**Comment by Pilchie** [comment]
@rrelyea @emgarten - should this be on NuGet?

**Comment by emgarten** [comment]
@philippe-lavoie take a look at: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

Based on your description you might be looking for `ReferenceOutputAssembly=false`

Here are some examples: 
```
// UnitTests gets BasicModule
UnitTests -(PrivateAssets=All)-> BasicModule  

// ProjectA does not see BasicModule
ProjectA -> UnitTests -(PrivateAssets=All)-> BasicModule  

// UnitTests does not see BasicModule
UnitTests -(ReferenceOutputAssembly=false)-> BasicModule
```

**Comment by philippe-lavoie** [comment]
I have the second situation you mention and ProjectA does see the nuget reference to BasicModule. You are implying it does not see it, but it does.

To be clear, the configuration is

Unit Test -> BasicModule ->  (PrivateAssets=All) BasicModuleContract

i.e. the BasicModuleContract is linked by BasicModule as a private assets

This is bad when content files are also promoted by this bug. I have a nuget that has content files and even with PrivateAssets=All, those files still get promoted and included in a project that has a PackageReference to it or any project referencing it afterwards. 

ProjectA / contentFiles / Bob.txt

ProjectB -> Project A (PrivateAssets=All)
ProjectC -> Project B (PrivateAssets = All)

when you look inside visual Studio, Bob.txt is still showing up inside ProjectC.

**Comment by emgarten** [comment]
This issue was moved to NuGet/Home#6098

**Comment by emgarten** [comment]
@philippe-lavoie let's continue debugging this at https://github.com/NuGet/Home/issues/6098  

@Pilchie this can be closed, I don't think this is related to the project system.

**Comment by Pilchie** [comment]
Thanks @emgarten closing as external.
