### ISSUE TITLE
Regression in 15.5p1: Portable0.0 is skipped

### ISSUE THREAD

**Issue by nguerrera** [dotnet/project-system#2910]
_From @onovotny on October 18, 2017 23:57_

I have an SDK project that the `MSBuild.Sdk.Extras` to build a legacy PCL target. This works in 15.4 but fails in 15.5 preview 1.

In the IDE in 15.4, I see this:

![image](https://user-images.githubusercontent.com/1427284/31748017-3c8bca6e-b43e-11e7-95a1-533476d1a1bf.png)

In 15.5 p1 I see this:

![image](https://user-images.githubusercontent.com/1427284/31748043-63688352-b43e-11e7-8354-d5b0d9068d27.png)
Note that the `Portable0.0` entry representing `portable-net4+sl5+wp8+win8+wpa81` is missing.

This is a blocker.

Building in the IDE in 15.5 p1 also yields the following error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The TargetFramework value 'portable-net4+sl5+wp8+win8+wpa81' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.	crypto	C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	96	
```
This is incorrect as the TFI and TFV is set by the MSBuild.Sdk.Extras package.

Repro is https://github.com/onovotny/bc-csharp/tree/e55eb138bf5492769ec1cf2212b49f223e377145
Open the BouncyCastle.sln

/cc @nguerrera 

_Copied from original issue: dotnet/sdk#1666_

**Comment by nguerrera** [comment]
_From @livarcocc on October 19, 2017 19:21_

@dsplaisted and @nguerrera can one of you take a look at this?

**Comment by nguerrera** [comment]
Looking

**Comment by nguerrera** [comment]
@davkean @emgarten I believe this is either a project system or nuget issue. There are no SDK changes between 15.4 and 15.5 preview 1 and things work as before on the command line. Something is  causing the project to get evaluated without the MSBuildSdkExtras targets setting TFI and TFV, but only in the IDE. Moving to project system for next look.

**Comment by Pilchie** [comment]
Not sure what could be different here, as the error only appears on build, and *does* appear in the output. Can you take a look?

**Comment by davkean** [comment]
I would look at the configurations we fire up here - I suspect Lifeng's change to reduce evaluations might have affected this.

**Comment by natidea** [comment]
On 15.5 P2, I do see the Portable0.0 node, though it is consistently coming through as unresolved:

![image](https://user-images.githubusercontent.com/7732033/31964908-6f30716a-b8ba-11e7-8722-b5bbb746af00.png)

I also get the error above when building the project. Investigating...

**Comment by natidea** [comment]
Using the build logger, the TF in the configured project is: portable-net4+sl5+wp8+win8+wpa81

But the target framework on which things are conditioned in *.nuget.g.props and *.nuget.g.targets is: portable-net40+sl5+win8+wp8+wpa81

![image](https://user-images.githubusercontent.com/7732033/31989466-310b1b52-b927-11e7-93f3-882d50ec042e.png)

Hence the import of the targets that set TFI and TFV is failing. If I modify *.nuget.g.props and *.nuget.g.targets to include the first TF, the build succeeds. Did we make any 15.5 era changes to the way this TargetFramework is computed?

**Comment by nguerrera** [comment]
Configured projects need to respect the spelling in TargetFrameworks. Is that not happening here?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davkean** [comment]
@natidea Can we make sure we're pushing the right value to NuGet? And if so, this is NuGet normalizing the value it writes to props.

**Comment by emgarten** [comment]
👍 on checking the nomination value. Restore shouldn't be normalizing the TFM string unless this has regressed in NuGet.

**Comment by natidea** [comment]
NuGet is being nominated with incorrect target framework. `ProjectConfigurationsService.GetKnownProjectConfigurationsAsync()` is returning ProjectConfigurations with this value:

![image](https://user-images.githubusercontent.com/7732033/32019057-c28561a6-b980-11e7-93f7-dd91f9bf5e0d.png)

**Comment by natidea** [comment]
Actually scratch that. The value we are sending to NuGet: `portable-net4+sl5+wp8+win8+wpa81` _is_ the value in the csproj file. But the conditions in the *.nuget.g.props and *.nuget.g.targets files are different: `portable-net40+sl5+win8+wp8+wpa81`. So this could be a bug in NuGet

**Comment by natidea** [comment]
Confirmed: if I change the targetframework in the csproj file to `portable-net40+sl5+win8+wp8+wpa81` (matching the value emitted by NuGet), then everything loads and builds properly:

![image](https://user-images.githubusercontent.com/7732033/32019994-a8d8a878-b983-11e7-8305-31f96fe4bd63.png)

So NuGet must be normalizing it somehow.

**Comment by natidea** [comment]
This issue was moved to NuGet/Home#6105
