### ISSUE TITLE
Performance in ProjectDesignerService.get_supportsProjectDesigner 

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#2911]
ProjectDesignerService.get_supportsProjectDesigner spent 151ms during loading Roslyn.sln.  It is about 1/3 of the time to build the entire project tree.  I think it might be that this code is using a COM interface, and need switch to UI thread once.

I think this code should switch to use IVsProjectDesignerPageService.IsProjectDesignerSupported, which is a project level MEF component, and that will eliminate the UI thread requirement.

**Comment by davkean** [comment]
@lifengl Who's actually switching to the UI thread?

**Comment by davkean** [comment]
This was fixed in https://github.com/dotnet/project-system/pull/2943. Still would like to know who's switching to the UI thread.

**Comment by lifengl** [comment]
The UI thread switching is in the tree property provider.  It looks like that the code is now in the VS repro.

We noticed it was a regression in this October.

Sent from my phone

On Nov 7, 2017, at 7:53 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


This was fixed in #2943<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fproject-system%2Fpull%2F2943&data=02%7C01%7Clulifeng%40hotmail.com%7Ca37a08292f6f4dc2c8e608d5265c3aed%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636457099917429030&sdata=8o27WoK6ogx3C4NuBUCvGzutKJkRBiD5TASrq1tcXKk%3D&reserved=0>. Still would like to know who's switching to the UI thread.
