### ISSUE TITLE
Create Unit Test with an error for the first creating project of the solution

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2914]
- Create a Class Library project.
- Place some sample test code into your test method
- Right click in the class and Click on "Create Unit Test"
- Run the automatically generated test

**Expected Results**: Create Unit Test with no error

**Actual Results**: Create Unit Test with an error "[Failure] Could not find file 'c:\users\v-mihuan\source\repos\CUTClassLibrary1\ClassLibrary1Tests\UnitTest1.cs'"
Note, this is only repro for the first project of the solution.
However, run generated test passed

Test on build: d15rel.27019.00
OS: Windows 10 x64 ENU

**Comment by Pilchie** [comment]
Does this error appear in the "IntelliSense" dropdown in the output window only?

If so, it is a duplicate of https://github.com/dotnet/roslyn/issues/12202

**Comment by Pilchie** [comment]
Ping @MiaomiaoHuangfu ?

**Comment by ManishJayaswal** [comment]
@richaverma1 - can you please ask @MiaomiaoHuangfu to respond to this?

**Comment by MiaomiaoHuangfu** [comment]
Yes, this error only appear in the "IntelliSense" dropdown in the output window. so we can close the issue and track dotnet/roslyn#12202.

**Comment by MiaomiaoHuangfu** [comment]
Sorry for late respond.

**Comment by Pilchie** [comment]
Duplicate of dotnet/roslyn#12202
