### ISSUE TITLE
static code coverage does not work well

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/project-system#2915]
- Create a unit test project;
- Build the project succeeded;
- Right click the solution, add a new test settings file
- While creating TestSettings file, Under Data & Diagnostics select "Code Coverage(Visual Studio 2010) option.
- Double click on above option and select the UnitTestProject1.dll and click ok
- Apply and Close the Test Settings Window
- From Menu bar select Test -> Test Settings -> Select Test Settings File -> Select the newly created test settings file.
- Rebuild the project
- Run the test
- Check the Test results folder to verify static code coverage file

**Expected Result**: CC should be created and check all CC details are available

**Actual Result**: 
       After adding TestSettings files, run the test will give the warnings:
	• Warning : A testsettings file or a runsettings with a ForcedLegacyMode set to true is not supported with the MSTest V2 Adapter.
	•  Warning: No test is available in C:\Users\v-mihuan\source\repos\UnitTestProject1\UnitTestProject1\bin\Debug\UnitTestProject1.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
	• Run test Finished: 0 run
	• No .Coverage file was generated

Test on d15rel.27019.00
OS: Windows 10 x64 ENU

**Comment by Pilchie** [comment]
@ManishJayaswal see these:

> • Warning : A testsettings file or a runsettings with a ForcedLegacyMode set to true is not supported with the MSTest V2 Adapter.
• Warning: No test is available in C:\Users\v-mihuan\source\repos\UnitTestProject1\UnitTestProject1\bin\Debug\UnitTestProject1.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Can you re-direct.  This doesn't sound like a project system issue.

**Comment by Pilchie** [comment]
This is an issue with the test platform, not the project.  Closing as external.
