### ISSUE TITLE
Add References Dialog shows referenced Shared Projects as Unselected

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#2916]
From [VSFeedback](https://developercommunity.visualstudio.com/content/problem/130875/console-net-core-2-app-still-not-showing-reference.html) | [508624](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/508624)

Repro Steps:
- Create a .NET Core Console app and a Shared Project. 
- Reference the shared project from the .NET Core console app.
- Open Add References dialog again.

Expected
Shared project is checked

Actual 
Shared project is unchecked

![image](https://user-images.githubusercontent.com/7732033/31873724-e861756c-b779-11e7-855f-8d629e633f59.png)

**Comment by Pilchie** [comment]
:link: also reported at https://developercommunity.visualstudio.com/content/problem/328798/cannot-remove-a-shared-project-reference-from-net.html

**Comment by Pilchie** [comment]
Pulling into 16.0 as there have been a couple more VSFeedback reports about this.

**Comment by etbyrd** [comment]
Probably a dupe of: https://github.com/dotnet/project-system/issues/1391

**Comment by drewnoakes** [comment]
Closing as duplicate of #1391. I moved info from here to there.

**Comment by davkean** [comment]
This was fixed in https://github.com/dotnet/project-system/pull/5805.
