### ISSUE TITLE
VS doesn't show a dialog on project open if reference assemblies are not installed

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/project-system#2919]
In contrast to the native project system, the new project system doesn't pop a dialog when you open a project and you don't have the reference assemblies installed.

**Comment by Pilchie** [comment]
However, you get an error from the build, saying that the targeting pack is not installed.  If we could hook that errorlist error up to In Product Aquisition to allow you to acquire the targeting pack, I would argue that would be a better experience.  @Cartermp  What do you think?

**Comment by cartermp** [comment]
Just so I'm clear on the term reference assemblies: this is for .NET Framework reference assemblies found in the targeting pack, yes?  If so, then I believe this is captured in the [VSTS tracking issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/506358) I created.

**Comment by Pilchie** [comment]
Yes, This is the scenario where you don't have the targeting pack installed for the TFM your project references.

**Comment by cartermp** [comment]
Sounds good!

**Comment by davkean** [comment]
Duping this against https://github.com/dotnet/project-system/issues/92.
