### ISSUE TITLE
VS Doesn't Handle PackageReference/ProjectReference Conditionals Propery

### ISSUE THREAD

**Issue by christophwille** [dotnet/project-system#2921]
Repro: https://github.com/icsharpcode/ILSpy/pull/940/files

When switching from Debug to Release (and vice versa), VS doesn't pick up that the references switched from project to package. I have to close the sln and reopen it - and then VS picks it up properly, restores package references nicely and in all does what it is supposed to do (unload project, reload also works).

Re-tested with 15.5 P2 today just to make sure. Same behavior.

**Comment by Pilchie** [comment]
@davkean do you know if this is expected?

**Comment by davkean** [comment]
From a restore perspective this works correctly, from a display perspective (dependencies node) this is still broken and being tracked by https://github.com/dotnet/project-system/issues/3642.
