### ISSUE TITLE
Unexpected DT build causes Packages to have yellow icon even though all packages are resolved

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#2924]
I was collecting some traces for evaluation and DT builds that are happening ( i dumped all events stats into a textfile) and noticed that sometimes there is unexpected second DT build event coming after the valid first DT build event:

Below is the code i added to CrossTargetRuleSubscriberBase.cs, it generates Evaluation_index.txt and DesigntimeBuild_index.txt files where index is the order in which they are coming. Sometimes for my web project i receive 3 files: Evaluation_0.txt, DesignTimeBuild_1.txt and DesignTimeBuild_2.txt. Where DesignTimeBuild_1.txt contains ResolvedPackages changes , but DesignTimeBuild_2.txt also contains package changes, which should not be happening since there is only one package and it was already received as resolved in DesignTimeBuild_1.txt, no reason for second DT build at all. 

When this happens, Nuget packages icon is yellow even though hierarchy is there and it is resolved"

![image](https://user-images.githubusercontent.com/1592091/32020268-7a745148-b984-11e7-817b-42ca0bbcc782.png)

Here is content for DesigntimeBuild_1.txt:

```
(DesignTimeBuild)
Available rules:
PackageReference, anyItems=True
AssemblyReference, anyItems=False
ResolvedAssemblyReference, anyItems=True
ResolvedAnalyzerReference, anyItems=True
ComReference, anyItems=False
SdkReference, anyItems=True
ResolvedProjectReference, anyItems=False
ResolvedPackageReference, anyItems=True
AnalyzerReference, anyItems=True
ResolvedCOMReference, anyItems=False
ProjectReference, anyItems=True
ResolvedSdkReference, anyItems=True
Changes:
ResolvedPackageReference, anyChanges=True
AssemblyReference, anyChanges=False
ResolvedProjectReference, anyChanges=False
ResolvedAnalyzerReference, anyChanges=True
PackageReference, anyChanges=True
SdkReference, anyChanges=True
ComReference, anyChanges=False
AnalyzerReference, anyChanges=True
ResolvedSdkReference, anyChanges=True
ProjectReference, anyChanges=True
ResolvedAssemblyReference, anyChanges=True
ResolvedCOMReference, anyChanges=False
```

Here is content for DesignTime_2.txt:

```
(DesignTimeBuild)
Available rules:
PackageReference, anyItems=True
AssemblyReference, anyItems=False
ResolvedAssemblyReference, anyItems=True
ResolvedAnalyzerReference, anyItems=True
ComReference, anyItems=False
SdkReference, anyItems=True
ResolvedProjectReference, anyItems=False
ResolvedPackageReference, anyItems=True
AnalyzerReference, anyItems=True
ResolvedCOMReference, anyItems=False
ProjectReference, anyItems=True
ResolvedSdkReference, anyItems=True
Changes:
ResolvedCOMReference, anyChanges=False
ComReference, anyChanges=False
ResolvedSdkReference, anyChanges=False
ResolvedAnalyzerReference, anyChanges=False
SdkReference, anyChanges=False
AssemblyReference, anyChanges=False
AnalyzerReference, anyChanges=False
ProjectReference, anyChanges=False
PackageReference, anyChanges=False
ResolvedAssemblyReference, anyChanges=False
ResolvedProjectReference, anyChanges=False
ResolvedPackageReference, anyChanges=True
```

Trace code change used to collect data (use it with basic core WebProject and try to open close solution until see yellow icon):

```c#
        private object __lock = new object();
        private int _index = 0;
        private int Index
        {
            get
            {
                lock (__lock)
                {
                    return _index++;
                }
            }
        }

        private async Task HandleAsync(
                    IProjectVersionedValue<Tuple<IProjectSubscriptionUpdate, IProjectCatalogSnapshot>> e,
                    RuleHandlerType handlerType)
        {
            var currentAggregaceContext = await _host.GetCurrentAggregateProjectContext().ConfigureAwait(false);
            if (currentAggregaceContext == null|| _currentProjectContext != currentAggregaceContext)
            {
                return;
            }

            IProjectSubscriptionUpdate update = e.Value.Item1;

            string testFileName = $"z:\\temp\\{handlerType.ToString()}_{Index}.txt";

            System.IO.File.AppendAllText(testFileName, $"({handlerType.ToString()})\r\n");
            System.IO.File.AppendAllText(testFileName, $"Available rules:\r\n");
            foreach (var ruleKvp in update.CurrentState)
            {
                System.IO.File.AppendAllText(testFileName, $"{ruleKvp.Value.RuleName}, anyItems={ruleKvp.Value.Items.Any()}\r\n");
            }

            System.IO.File.AppendAllText(testFileName, $"Changes:\r\n");
            foreach (var changeKvp in update.ProjectChanges)
            {
                System.IO.File.AppendAllText(testFileName, $"{changeKvp.Key}, anyChanges={changeKvp.Value.Difference.AnyChanges}\r\n");
            }
```

**Comment by davkean** [comment]
To rule out build issue, can you turn on design-time build logging and capture both builds (turn on verbosity enough to see the items that you are querying): https://github.com/dotnet/project-system/blob/master/docs/repo/content/DesignTimeBuildOutputPane.cmd.

**Comment by drewnoakes** [comment]
@abpiskunov @davkean is it actually invalid to have multiple DTBs in a row? I think the dependencies node code should be able to handle this scenario.

Currently the Dataflow subscriptions are suppressing version-only changes, which seems to be causing problems.

We are seeing a class of bugs related to changes in evaluation data that don't have corresponding changes in the DTB item, resulting it items reverting to 'unresolved' state.

**Comment by abpiskunov** [comment]
it is not invalid to have multiple DT builds in a row, but in my case above first and second DT builds both had ResolvedPackageReference changes, which is seemed to me "impossible" since there is only 1 package in the project and it is returned as resolved in first DT, then what should have changed if we receive a second DT with same package resolved again? I was suspecting some quirks with nuget restore .. It is likely that this flow changed now it was too long ago..

**Comment by drewnoakes** [comment]
Thanks Anton. We're doing a bunch of work around resolved statuses, and will be reworking some of the Dataflow subscriptions in coming weeks. As I can't see whether this still repros, I'm going to close this for now. Feel free to reopen if I've missed something.

Another bug I found that might explain the above: If the SDK is unresolved because its NuGet package was unresolved, then we have an invisible unresolved package that currently makes the `NuGet` tree node appear unresolved. I can't tell from your screenshot if that's what's happening here, but I've seen it in a few contexts. I've fixed this in local work and will get a PR in next week.
