### ISSUE TITLE
Content from library is not deployed to UWP app

### ISSUE THREAD

**Issue by zigzag312** [dotnet/project-system#2925]
#Hi, I am not sure if this is a bug or a proper behavior. To reproduce:

1. (in Visual Studio) create UWP project
2. create netstandard project
3. add a content file to netstandard project (mark it as 'Content' and set it to 'Copy if newer')
4. from UWP project add reference to netstandard project
5. run in debug mode (without .NET Native tool chain)

Result: Content file will be copied to bin/Debug folder on build, but it will NOT be copied/deployed to bin/Debug/AppX folder.

1. Why does content file get copied on build, but it doesn't get deployed in the end?
2. How can I properly add content to referenced project so that it will get deployed to UWP app?

I am using Visual Studio 2017 v15.4.1 on Windows 10 Fall Creators Update

**Comment by Pilchie** [comment]
This issue was moved to dotnet/sdk#1690
