### ISSUE TITLE
Project Properties does not appear

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#2929]
When creating a new project or even open an existing one, project properties doesn't appear at all.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/136246/project-properties-does-not-appear.html
VSTS ticketId: 513325_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_

Mohamed El-Sadany solved on 10/23/2017, 08:03 AM (7 days ago), 0 votes: <p><img src="https://developercommunity.visualstudio.com/storage/attachments/15197-untitled.png"></p><p>This is what I get when trying to add a new resource file in an empty project. Hopefully would make the problem clear.</p>

**Comment by Pilchie** [comment]
Also asked the user to try a repair.

**Comment by davkean** [comment]
This appears to be a setup issue, customer didn't reply so closing this bug and the VS Feedback bug.
