### ISSUE TITLE
Build in IDE makes no apparent progress

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#2935]
I open Roslyn.sln and try to run a test. The Build window becomes visible and shows some activity (see first screenshot below), then progress rapidly stops.
From discussion with @davkean, I've captured a dump file: \\\\jcouvdev\shared-dumps\devenv-build-no-progress.DMP

I've found a way to unblock it: I try to close Visual Studio, then I will get a popup saying that a build is in progress (see second screenshot), and the progress of the build will immediately resume...

```
Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.5.0 Preview 3.0 [27030.2.d15rel]
VisualStudio.15.IntPreview/15.5.0-pre.3.0+27030.2.d15rel
Microsoft .NET Framework
Version 4.7.02046
```

![image](https://user-images.githubusercontent.com/12466233/32294417-5f1cfdd0-bf03-11e7-94c4-7146b9e912fe.png)

![image](https://user-images.githubusercontent.com/12466233/32294540-b1b06c6c-bf03-11e7-8742-eacb953601b1.png)

**Comment by jcouv** [comment]
Sorry, I accidentally hard-deleted the dump file.
I'll re-open the issue once I can get a new dump file.

**Comment by jcouv** [comment]
I captured a new dump of the problem. Same path as original (above).

**Comment by Pilchie** [comment]
@jcouv do you have restore on build enabled at Tools\Options\NuGet package manager enabled?  Does this repro if you disable it?

**Comment by jcouv** [comment]
I've been toggling this nuget option on and off. Let me make sure it's off and get back to you.

**Comment by jcouv** [comment]
The issue did repro when this nuget option was off (unchecked). I captured a second dump file.

**Comment by Pilchie** [comment]
In the future, can you capture 32-bit dumps when doing it of VS?  (Use C:\Windows\SysWOW64\taskmgr.exe if using task manager). SOS.dll doesn't work for 64-bit dumps of 32-bit processes :(

**Comment by Pilchie** [comment]
We're tracking this with https://developercommunity.visualstudio.com/content/problem/137400/build-not-really-starting.html

**Comment by davkean** [comment]
I'm looking at the dump now.

**Comment by jcouv** [comment]
Sorry about that, I will capture a 32-bit dump next time.

**Comment by davkean** [comment]
@onovotny said he could repro this - can you share the dump you took?

**Comment by onovotny** [comment]
https://1drv.ms/u/s!AkdN31URmI25u7pT5_vWkbRP2Bjipg

**Comment by onovotny** [comment]
At first I couldn't immediately repro this, but then @davkean suggested it had to do with building close to solution open. That did it. If I launched the solution directly, then hit rebuild as fast as I could, then I got the hang.

**Comment by davkean** [comment]
Thanks @onovotny, I've pointed to the dump in the bug that this bug is dup'd against.
