### ISSUE TITLE
Perf: Prevent double design time build during loading solution

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#2939]
Register dataflow earlier and link rule subscriptions to DataflowBlock.NullTarget<T>().  Reduce double build can reduce overall DT build time a lot during the solution loading phase.

**Comment by Pilchie** [comment]
Is this a duplicate of #2594

cc @davkean

**Comment by Pilchie** [comment]
Closing as a dupe - let me know if it's not.
