### ISSUE TITLE
Perf: extra overhead during set project Guid

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#2940]
In a standard perf box, it wasted 500-800ms UI thread time in this code path to do nothing.

The overhead is mostly to get a read lock and switch to a thread pool to scan the project and check whether the GUID is ever persisted.  It was scanned once in CPS to retrieve the GUID during the earlier phase of loading the project.

CPS defined a new ProjectGuidStorageProvider contract to optimize that in 15.6.  Please work with the contract to eliminate this wasted time.

**Comment by davkean** [comment]
- Copy the default provider from CPS
- Consume this provider inside our in-memory properties provider instead of reading project file

**Comment by Pilchie** [comment]
Moving to 15.7 - I took a quick look at this, but it wasn't totally clear to me how to do this.

**Comment by davkean** [comment]
Just removing our usage of the rule before removing it in lieu of the IProjectGuidProvider/IProjectGuidStorageProvider; https://github.com/dotnet/project-system/pull/3303, https://github.com/dotnet/project-system/pull/3314 and https://github.com/dotnet/project-system/pull/3313.

**Comment by Pilchie** [comment]
Fixed now, right @davkean?

**Comment by Pilchie** [comment]
Fixed now, right @davkean ?

**Comment by davkean** [comment]
Ah yes.
