### ISSUE TITLE
project build fails to create nuget package

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#2941]
I create an asp.net core app 1.1 (web api template). set the output to assembly so it creates a .dll. I then use project properties under the package tab to specify my nuget information and have visual studio create the nuget file automatically on each build. Other packages from various projects are created fine, except for the one of the webapi assembly. File StateServer.dll compiles but no package is ever created. Output from log below.

To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1&gt;------ Rebuild All started: Project: StateServer.Shared, Configuration: Release Any CPU ------
2&gt;------ Rebuild All started: Project: StateServer.Abstractions.Adapter, Configuration: Release Any CPU ------
3&gt;------ Rebuild All started: Project: StateServer.Communication.StateServer, Configuration: Release Any CPU ------
1&gt;StateServer.Shared -&gt; D:\DEV\GIT\StateServer\StateServer.Shared\bin\Release\netstandard1.4\StateServer.Shared.dll
2&gt;StateServer.Abstractions.Adapter -&gt; D:\DEV\GIT\StateServer\StateServer.Abstractions.Adapter\bin\Release\net461\StateServer.Abstractions.Adapter.dll
3&gt;StateServer.Communication.StateServer -&gt; D:\DEV\GIT\StateServer\StateServer.Communication.StateServer\bin\Release\netstandard1.4\StateServer.Communication.StateServer.dll
1&gt;Successfully created package 'D:\DEV\GIT\StateServer\StateServer.Shared\bin\Release\StateServer.Shared.1.1.4.nupkg'.
2&gt;Successfully created package 'D:\DEV\GIT\StateServer\StateServer.Abstractions.Adapter\bin\Release\StateServer.Abstractions.Adapter.1.1.8.nupkg'.
3&gt;Successfully created package 'D:\DEV\GIT\StateServer\StateServer.Communication.StateServer\bin\Release\StateServer.Communication.StateServer.1.1.8.nupkg'.
4&gt;------ Rebuild All started: Project: StateServer, Configuration: Release Any CPU ------
4&gt;StateServer -&gt; D:\DEV\GIT\StateServer\StateServer\bin\Release\net461\win7-x64\StateServer.dll

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/126405/project-build-fails-to-create-nuget-package.html
VSTS ticketId: 505449_
_These are the original issue comments:_

Candy Zhang [MSFT] on 10/9/2017, 00:18 AM (29 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

Mike Lorbetske [MSFT] on 11/6/2017, 09:17 AM (28 hours ago): <p>Thank you for your feedback! Could you please try adding &lt;IsPackable&gt;true&lt;/IsPackable&gt; to a &lt;PropertyGroup&gt; in your project file? This should allow the package to be created.  We look forward to hearing from you!</p>

Leonardo Sobrado on 11/6/2017, 11:06 AM (26 hours ago): <p>modified as shown and seems to work. I created a package and deployed it to nuget, upgraded consumer project, works ok, so far. I didn't get any intellisense on the IsPackable element. But works in creating the package. I would suggest making this element something that gets inserted into the markup or at least a message that explains why the package is not generated even as I have the toggle to create it set to ON. Thanks.</p><p>&lt;PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'"&gt;<br>  &lt;OutputType&gt;Library&lt;/OutputType&gt;<br>  &lt;/PropertyGroup&gt;<br><br>  &lt;PropertyGroup&gt;<br>  &lt;TargetFramework&gt;net461&lt;/TargetFramework&gt;<br>  &lt;RuntimeIdentifier&gt;win7-x64&lt;/RuntimeIdentifier&gt;<br>  &lt;ApplicationIcon /&gt;<br>  &lt;OutputTypeEx&gt;library&lt;/OutputTypeEx&gt;<br>  &lt;StartupObject /&gt;<br>  &lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;<br>  &lt;IsPackable&gt;true&lt;/IsPackable&gt;<br>  &lt;Version&gt;1.1.27&lt;/Version&gt;<br>  &lt;AssemblyVersion&gt;1.1.27.0&lt;/AssemblyVersion&gt;<br>  &lt;FileVersion&gt;1.1.27.0&lt;/FileVersion&gt;</p>

_These are the original issue solutions:_
(no solutions)

**Comment by Pilchie** [comment]
Actually @livarcocc @nguerrera Should there be an error/warning if `GeneratePackageOnBuild` is true, but `IsPackable` is false instead of just a UI indication?

**Comment by livarcocc** [comment]
cc @rrelyea @emgarten

**Comment by Pilchie** [comment]
Ping?

**Comment by rrelyea** [comment]
Opened https://github.com/NuGet/Home/issues/6156 to track.
Should be able to close the project-system issue, I believe.

**Comment by Pilchie** [comment]
Thanks - closing in favor of the NuGet issue.
