### ISSUE TITLE
Remove <RequiredFrameworkVersion> from all non-.NET Framework templates

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2964]
There's a change in the New Project Dialog that will show the "Target Framework" dropdown below the solution name when a template has "RequiredFraemworkVersion" listed in the template. There's no way to currently list anything but .NET Framework versions in that drop down, we should prevent it from showing by removing the property from all non-.NET Framework templates.

Templates we own that will need to change:

- [ ] Console App (.NET Core)
- [ ] Class Library (.NET Standard)
- [ ] Class Library (.NET Core)
- [ ] Class Library (Portable).

This changes comes on in 15.6.

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/project-system/pull/2968
