### ISSUE TITLE
IntelliSense does not work at all while editing csproj with Windows and VS being Chinese.

### ISSUE THREAD

**Issue by Xiu-Li** [dotnet/project-system#2965]
IntelliSense in editing .csproj does not work at all in windows 10 enterprise RTM Chinese-PRC x64.
![image](https://user-images.githubusercontent.com/24784908/32869656-1d45e488-cab3-11e7-92bc-ff6d513504d2.png)

**Comment by davkean** [comment]
This issue was moved to Microsoft/msbuild#2723
