### ISSUE TITLE
Add support for native project references in interop scenarios: vcxproj, CMake, make, Xcode

### ISSUE THREAD

**Issue by 4creators** [dotnet/project-system#2970]
Cross platform library developers using interop quite often work on native and managed projects in the same solution. It would be very helpful to have a support for having native projects being referenced like any other managed project with transitive references, properties integration and orchestration of build.

If that support would start just from the level of integrating current `vcxproj` (or it's successor format) it would be a great step forward. Having xplat support for CMake, make, Xcode would be awesome.

**Comment by Pilchie** [comment]
@AndyGerlicher - I think this would start more at the MSBuild level than the project system.

@4creators What *doesn't* work today for `vcxproj`?

**Comment by Pilchie** [comment]
Closing as I don't have a clear understanding of what this request is, or where it belongs, so it isn't actionable at present.  Feel free to add more detail and reactivate.
