### ISSUE TITLE
Separate the project "loading" state from the "design time build failed" state

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/project-system#2972]
refer https://github.com/dotnet/roslyn/pull/23246

@Pilchie

**Comment by Pilchie** [comment]
We should think more about this as we change the language service init.

**Comment by davkean** [comment]
@jinujoseph @heejaechang I'm closing this bug, there's nothing actionable that we can do our side - if the feeling is that operation progress doesn't address this, please come up with a design on how this should work in Roslyn and we'll call the appropriate APIs.
