### ISSUE TITLE
Targets not imported from dependency of a package reference

### ISSUE THREAD

**Issue by bhugot** [dotnet/project-system#2973]
Hello,

If you create a package that, as a dependency, contains a target, the targets are not used by the project by referencing it.
```
Project 
 |_ NugetA
     |_ NugetB
        |_ build.targets
```
If we install NugetB on Project, the targets are applied.

How to solve this problem because I do not want to apply the targets of the dependency.

Thanks

**Comment by Pilchie** [comment]
@rrelyea @emgarten - this sounds like it should be moved to nuget/Home?

**Comment by emgarten** [comment]
This issue was moved to NuGet/Home#6206

**Comment by emgarten** [comment]
@Pilchie this can be closed, I'll work with @bhugot using the nuget issue.
