### ISSUE TITLE
Is there any online csproj converter?

### ISSUE THREAD

**Issue by kasper3** [dotnet/project-system#2974]
I 💓 the new csproj format. It worked for all the old projects that i have converted. Sometimes the hand-rolled migration gets trickier when there are custom .targets calls etc. but couldn't find "this is not possible" issue so far.

I am looking for something like a single page webapp providing a form to 'paste your cspro here' then press a button and outputs the one in new format.

If this doesn't exist, please consider building one as that will save quite a lot of time if i start converting everything manually i have.

**Comment by benaadams** [comment]
CsprojToVs2017? by @hvanbakel https://github.com/hvanbakel/CsprojToVs2017

**Comment by kasper3** [comment]
This is grand! Thanks Ben!
Having web version of tool would be great as well.

**Comment by Pilchie** [comment]
See also https://github.com/srivatsn/ProjectSimplifier
