### ISSUE TITLE
Cannot open class diagram .cd file

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/project-system#2976]
@michaelsogos commented on [Sat Nov 04 2017](https://github.com/dotnet/standard/issues/572)

Dear,

In a .net standard library project, on vs2017 15.4, we cannot open a class diagram file.

---

@jp2masa commented on [Sun Nov 05 2017](https://github.com/dotnet/standard/issues/572#issuecomment-341979005)

Related: dotnet/project-system#256 dotnet/project-system#2817

**Comment by Pilchie** [comment]
@tannergooding I'm confused about the state of the linked bugs.  Are you saying you don't think there is a change needed at all with 15.5 to open CD files, or that you need the change in #2817, but after that, reopening from the `.suo` file still doesn't work?

**Comment by tannergooding** [comment]
The latter, you need #2817, but after that, reopening from the `.suo` file doesn't work due to the language service not having been initialized yet.

My last statement was saying there doesn't appear to be any CPS side changes needed, as we originally thought.

**Comment by Pilchie** [comment]
Got it - @davkean any objections to me merging #2817 for 15.6 then?

**Comment by davkean** [comment]
Need to investigate the language service init to make sure I can fix that in 15.6 before merging.

**Comment by davkean** [comment]
I filed https://github.com/dotnet/project-system/issues/2998 which represents the bug that occurs after we merge this in.

**Comment by davkean** [comment]
This was resolved in https://github.com/dotnet/project-system/pull/2817 and will be available in 15.6.
