### ISSUE TITLE
CA1036 (Override operator methods on comparable types) violations in the repo

### ISSUE THREAD

**Issue by mavasani** [dotnet/project-system#2979]
Enabling [CA1036](https://msdn.microsoft.com/en-us/library/ms182163.aspx) caused following violations to fire:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CA1036	TargetFramework should override Equals since it implements IComparable.	Microsoft.VisualStudio.ProjectSystem.Managed.VS	c:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\Tree\Dependencies\CrossTarget\TargetFramework.cs	9	N/A
Warning	CA1036	Dependency should override Equals since it implements IComparable.	Microsoft.VisualStudio.ProjectSystem.Managed.VS	c:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\Tree\Dependencies\Snapshot\Dependency.cs	13	N/A
Warning	CA1036	TestDependency should override Equals since it implements IComparable.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests	c:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\ProjectSystem\VS\Tree\Dependencies\Snapshot\TestDependency.cs	11	N/A
```

All of these seem valid to me, and we also have a code fix. Any concerns if I send a PR to fix these and enable the rule on the repo?

**Comment by mavasani** [comment]
NOTE: The diagnostic message for CA1036 for these instances is not accurate. https://github.com/dotnet/roslyn-analyzers/issues/1396 tracks improving the message.

**Comment by Pilchie** [comment]
@davkean any objections here?

**Comment by davkean** [comment]
Why are we running these framework design rules designed for public APIs across an internal code base and tests?

**Comment by mavasani** [comment]
@davkean Are you suggesting FXCop didn't execute them for internal API surface? I can check and confirm the behavior. Regardless, I feel this is a good pattern to follow, unless we know this is causing lot of noise.

**Comment by davkean** [comment]
It is adding a bunch of noise - we're implementing a bunch of dead code: https://github.com/dotnet/project-system/pull/2995/files.

**Comment by mavasani** [comment]
Unless we add analyzer options to allow end user to explicitly specify the API surface they want to run their analyzers on, we don't know if user wants to keep his entire code base clean or just the public API surface. Until then, I agree we should probably match the FXCop behavior for existing FXCop rules. I will verify if FXCop fires for the internal types for this rule.
