### ISSUE TITLE
Target events with options AfterTargets: BeforeBuild, PreBuildEvent, PostBuildEvent, AfterBuild shouldn't be executed during publishing

### ISSUE THREAD

**Issue by stachu99** [dotnet/project-system#2982]
Tested on MS VS 2017 Community 2017, version 15.4.4, Ms .NET Fram. ver.: 4.7.02046
A part of the code in .csproj:
  `<Project Sdk="Microsoft.NET.Sdk.Web">`
  PropertyGroup
     `<TargetFramework>netcoreapp2.0</TargetFramework>`
  ItemGroup
     `<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />`

There are targets with events executed after targets: BeforeBuild, PreBuildEvent, PostBuildEvent, AfterBuild, BeforePublish, AfterPublish.
`  <Target Name="target1" AfterTargets="BeforeBuild">
    <Exec Command="echo Target: target1 executed after target: BeforeBuild" />
  </Target>`
  `<Target Name="target2" AfterTargets="PreBuildEvent">
    <Exec Command="echo Target: target2 executed after target: PreBuildEvent" />
  </Target>`
 ` <Target Name="target3" AfterTargets="PostBuildEvent">
    <Exec Command="echo Target: target3 executed after target: PostBuildEvent" />
  </Target>`
  `<Target Name="target4" AfterTargets="AfterBuild">
    <Exec Command="echo Target: target4 executed after target: AfterBuild" />
  </Target>`
  `<Target Name="target5" AfterTargets="BeforePublish">
    <Exec Command="echo Target: target5 executed after target: BeforePublish" />
  </Target>`
  `<Target Name="target6" AfterTargets="AfterPublish">
    <Exec Command="echo Target: target6 executed after target: AfterPublish" />
  </Target>`

On a publish output are targets:  target1, target2, target3, target4  executed after 'point 2 - Publish started'. That shouldn't happen.
> Restoring NuGet packages...
> To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
> 1>------ Build started: Project: TradingCore, Configuration: Release Any CPU ------
> 1>Target: target1 executed after target: BeforeBuild
> 1>Target: target2 executed after target: PreBuildEvent
> 1>TradingCore -> D:\Projects\Trading\TradingCore\bin\Release\netcoreapp2.0\TradingCore.dll
> 1>Target: target3 executed after target: PostBuildEvent
> 1>Target: target4 executed after target: AfterBuild
> 2>------ Publish started: Project: TradingCore, Configuration: Release Any CPU ------
> Connecting to D:\Projects\!Publish\Trading\Production\Release\TradingCore...
> echo Target: target5 executed after target: BeforePublish
> Target: target5 executed after target: BeforePublish
> echo Target: target1 executed after target: BeforeBuild
> Target: target1 executed after target: BeforeBuild
> echo Target: target2 executed after target: PreBuildEvent
> Target: target2 executed after target: PreBuildEvent
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:1701,1702,1705,1701,1702,2008 /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE;RELEASE;NETCOREAPP2_0 /errorendlocation /preferreduilang:en-US /reference:C:\Users\st ...... Models\IPODts.cs Program.cs Startup.cs "C:\Users\stachu99\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.cs" obj\Release\netcoreapp2.0\TradingCore.AssemblyInfo.cs /warnaserror+:NU1605
> TradingCore -> D:\Projects\Trading\TradingCore\bin\Release\netcoreapp2.0\TradingCore.dll
> echo Target: target3 executed after target: PostBuildEvent
> Target: target3 executed after target: PostBuildEvent
> echo Target: target4 executed after target: AfterBuild
> Target: target4 executed after target: AfterBuild
> "dotnet" exec --runtimeconfig "D:\Projects\Trading\TradingCore\bin\Release\netcoreapp2.0\TradingCore.runtimeconfig.json" --depsfile "D:\Projects\Trading\TradingCore\bin\Release\netcoreapp2.0\TradingCore.deps.json" "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.1\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Release\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"
> TradingCore -> D:\Projects\Trading\TradingCore\obj\Release\netcoreapp2.0\PubTmp\Out\
> echo Target: target6 executed after target: AfterPublish
> Target: target6 executed after target: AfterPublish
> Web App was published successfully file:///D:/Projects/!Publish/Trading/Production/Release/TradingCore
> 
> ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
> ========== Publish: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by Pilchie** [comment]
@livarcocc - sounds like an SDK issue?

**Comment by livarcocc** [comment]
It depends. I am not sure how VS is doing the publish. If VS is invoking a build and then a publish, then this makes sense, because from the SDK POV, publish depends on build. So, we will have one build from VS and one from the dependency from publish to build.

Does this happen when running msbuild /t:Publish from the command line?

**Comment by Pilchie** [comment]
>Does this happen when running msbuild /t:Publish from the command line? 

@stachu99 - can you answer this?

**Comment by Pilchie** [comment]
Closing since we haven't heard back yet.
