### ISSUE TITLE
Question - Move AppDesigner to CPS

### ISSUE THREAD

**Issue by jp2masa** [dotnet/project-system#2988]
I'm not sure if `AppDesigner` is meant to be a feature for managed projects only, but I think it's useful for other project systems too, so it would make more sense if it was part of the CPS. I'm working on a project system which declares the `AppDesigner` capability and everything works as expected. However, the [App Designer special file provider](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AppDesignerFolderSpecialFileProvider.cs) is internal, making it hard to get the current App Designer folder path.

**Comment by davkean** [comment]
We do plan on eventually splitting AppDesigner into a separate component. Are you having an issue with the icon not showing? I only recently fixed that in post 15.5 builds (https://github.com/dotnet/project-system/pull/2949). 

The special file provider is accessed via the COM interface IVsProjectSpecialFiles - passing `__PSFFILEID2.PSFFILEID_AppDesigner` as the `fileID` argument. There's no CPS equivalent API for accessing this.

**Comment by jp2masa** [comment]
I think that the icon was showing last time I tested the project system (using VS 15.4, didn't test on 15.5 preview). Are there any plans to expose a CPS API for AppDesigner?

**Comment by davkean** [comment]
For the AppDesigner itself or just to retrieve the AppDesigner path?

**Comment by jp2masa** [comment]
To retrieve the AppDesigner path.

**Comment by Pilchie** [comment]
> Are there any plans to expose a CPS API for AppDesigner?

@lifenglu - can you answer this?  Is it a core CPS concept, or something for this repo?

**Comment by jp2masa** [comment]
I'm guessing that the mention should be for @lifengl?

**Comment by Pilchie** [comment]
Yes - thanks @jp2masa, and sorry @lifenglu

**Comment by davkean** [comment]
The AppDesigner path can be retrieved via IVsProjectSpecialFiles - it's not an async API but in CPS it is thread-safe so you can call it on a background thread. If CPS was to provide an API here - it would be just a managed async version of IVsProjectSpecialFiles.

**Comment by Pilchie** [comment]
Closing, as this would be a CPS change.  @lifengl - is this tracked on your side?
