### ISSUE TITLE
VB: IDE crashes when trying to add reference within a .NET Standard library project.

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#2991]
_From @ericmutta on September 10, 2017 1:23_

**Version Used**: 

Visual Studio Community 2017 v15.3.3

**Steps to Reproduce**:

Create a VB library using the the .NET Standard template, then go to its Properties page under the References tab:

![vs_stdlib_addref_crash4](https://user-images.githubusercontent.com/20465797/30245334-c2e309a2-95de-11e7-9048-5f641731f31a.png)

If you press the Add button on where the label `Add...` appears, it opens the add reference dialog as expected. However if you click on the arrow on the right edge of the button, it is non-responsive and after a few seconds the IDE crashes.

**Expected Behavior**:

If the menu that usually shows when you click the arrow on the Add button is not applicable for VB .NET Standard library projects, there should be some kind of message to say so rather than crashing the IDE.

**Actual Behavior**:

As shown above: IDE crashes and you have to be careful to click on Add button's label, rather than the arrow portion.

_Copied from original issue: dotnet/roslyn#22013_

**Comment by davkean** [comment]
_From @Pilchie on September 11, 2017 15:3_

@jasonmalinowski isn't this the bug you fixed in F#'s copy of the property pages?

Cc @tannergooding

**Comment by davkean** [comment]
_From @Pilchie on September 11, 2017 15:16_

Also cc @natidea - looks like this should be moved to https://github.com/dotnet/project-system.

**Comment by Pilchie** [comment]
The problem here is that https://github.com/dotnet/project-system/blob/0c5dd7f28aff9c6897c12bfdc864d1b07753bcb2/src/Microsoft.VisualStudio.Editors/Common/Utils.vb#L1337 throws a `COMException` for disp_e_membernotfound, which we should probably treat like `NotImplementedException`.

**Comment by davkean** [comment]
Yep.

**Comment by Pilchie** [comment]
Fixed for 15.7.

**Comment by ericmutta** [comment]
@Pilchie @davkean thanks a lot for fixing this! :+1: :+1:
