### ISSUE TITLE
Stop automatically including sub folders that exist inside project folders.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/project-system#3001]
**Version Used**: 

Visual Studio Community 2017 v15.4.4 

**Current Behavior**:

For reasons I am yet to understand, recent versions of Visual Studio insist on automatically including folders into my projects and I am forced to **manually exclude them** if I don't want them.

I think this behaviour came with the 2017 editions because all versions prior (i.e 2015 all the way down to 2003) had the opposite behaviour: if you wanted a folder/file to be included, you would choose the `Show All Files` option in Solution Explorer and then right-click the item and choose `Include In Project`.

The current behaviour of automatically including sub-folders inside folders that are already part of the project is mostly harmless, but it becomes tedious when using Source Gear's Vault version control system. This tool creates a hidden folder called `_sgbak` in all folders of the project. I think that folder holds back-up copies for versioning purposes and every time it is created, Visual Studio adds it to Solution Explorer. I then have to exclude it manually, resulting in my project file looking like this:

```xml
<ItemGroup>
    <Compile Remove="Src\Async\_sgbak\**" />
    <Compile Remove="Src\Binary\_sgbak\**" />
    <Compile Remove="Src\Misc\_sgbak\**" />
    <Compile Remove="Src\Net\ADP\Session Manager\_sgbak\**" />
    <Compile Remove="Src\Net\ADP\Session Node\_sgbak\**" />
    <Compile Remove="Src\Net\ADP\_sgbak\**" />
    <Compile Remove="Src\Net\UDP2\_sgbak\**" />
    <Compile Remove="Src\Net\_sgbak\**" />
    <Compile Remove="Src\Security\_sgbak\**" />
    <Compile Remove="_sgbak\**" />
    <EmbeddedResource Remove="Src\Async\_sgbak\**" />
    <EmbeddedResource Remove="Src\Binary\_sgbak\**" />
    <EmbeddedResource Remove="Src\Misc\_sgbak\**" />
    <EmbeddedResource Remove="Src\Net\ADP\Session Manager\_sgbak\**" />
    <EmbeddedResource Remove="Src\Net\ADP\Session Node\_sgbak\**" />
    <EmbeddedResource Remove="Src\Net\ADP\_sgbak\**" />
    <EmbeddedResource Remove="Src\Net\UDP2\_sgbak\**" />
    <EmbeddedResource Remove="Src\Net\_sgbak\**" />
    <EmbeddedResource Remove="Src\Security\_sgbak\**" />
    <EmbeddedResource Remove="_sgbak\**" />
    <None Remove="Src\Async\_sgbak\**" />
    <None Remove="Src\Binary\_sgbak\**" />
    <None Remove="Src\Misc\_sgbak\**" />
    <None Remove="Src\Net\ADP\Session Manager\_sgbak\**" />
    <None Remove="Src\Net\ADP\Session Node\_sgbak\**" />
    <None Remove="Src\Net\ADP\_sgbak\**" />
    <None Remove="Src\Net\UDP2\_sgbak\**" />
    <None Remove="Src\Net\_sgbak\**" />
    <None Remove="Src\Security\_sgbak\**" />
    <None Remove="_sgbak\**" />
  </ItemGroup>
```

**Expected Behavior**:

At the very least, Visual Studio should NOT automatically include **hidden folders** that are sub-folders within existing project folders. Better yet, it would be nice to have the option to enable the previous behaviour where files/folders are included in a project only if you **explicitly include them**.

**Comment by davkean** [comment]
Are you using .NET Core/.NET Standard project types? If so, set the following to opt out:

``` XML
<PropertyGroup>
    <EnableDefaultItems>false</EnableDefaultItems>
</PropertyGroup>
```

**Comment by ericmutta** [comment]
@davkean many thanks for following up quickly! Luckily most of my projects are .NET Standard class libraries so that setting should help. Is there something equivalent for console/windows apps targeting the full .net framework?

**Comment by ericmutta** [comment]
@davkean Are you using .NET Core/.NET Standard project types? If so, set the following to opt out:

I just tried doing that on my projects: unloaded the project in solution explorer, opened the project file and pasted in the XML you gave me above, then reloaded and hit rebuild solution. **Everything breaks! It seems like ALL folders are excluded now and the projects show up empty in Solution explorer**

What to do?

**Comment by davkean** [comment]
@ericmutta Perhaps describe a little more your issue. The .NET Standard project type unlike every single project in the past automatically includes all source files under a project root. To opt out of this, you either need to opt out of folders recursively (foo\**) like above, or opt completely out of this behavior (as suggested above) and manually include all the files like previous project types.

**Comment by ericmutta** [comment]
> @davkean ... or opt completely out of this behavior (as suggested above) and **manually include all the files like previous project types**.

That last part is what I didn't do (i.e manually include the files after disabling automatic inclusion). I have now fixed the problem by manually including my `Src` folder and my code works perfectly once more 👍 👍 

Is there a similar setting for Windows/Console project types targeting the full .Net Framework? (I ask because you singled out " .NET Core/.NET Standard project types" when you showed the XML setting earlier above).

**Comment by davkean** [comment]
There's two project types in play; those that import the "Microsoft.Net.Sdk" and those that don't. The setting works for those that import the Microsoft.Net.Sdk. If you .NET Framework projects target that - then the opt out will work for them too. If they don't target the Sdk then they shouldn't be inheriting this behavior of automatically including all source files.

**Comment by ericmutta** [comment]
Very much appreciated @davkean, I think this has resolved the problem and I can close this issue.
