### ISSUE TITLE
Project system writes properties to the project file in an unfriendly way

### ISSUE THREAD

**Issue by davidfowl** [dotnet/project-system#3017]
Lets say I wanted to pick the latest version of the C# compiler. I would do the following:

![image](https://user-images.githubusercontent.com/95136/33543577-680e37f4-d88c-11e7-969c-0dd778b2dab6.png)

It would write this to the project file:

```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
```

I really want to write this:

```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
```

Anything that gets closer to this would be amazing.

**Comment by davkean** [comment]
Dup as: https://github.com/dotnet/project-system/issues/2732.
