### ISSUE TITLE
Remove RemoteCodeGeneratorAttribute

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#302]
#297 introduces the RemoteCodeGeneratorAttribute, since the CodeGeneratorAttribute requires a Type for registering SingleFileGenerators registered in other assemblies. CPS has said that they will consider adding support for specifying the class name and guid manually post Dev15, so once that's added we should remove RemoteCodeGenerator and use the standard attribute.

**Comment by davkean** [comment]
This was all removed in 15.8 when we started returning the legacy project type for compat reasons.
