### ISSUE TITLE
Clicking in "Find Results" hangs VS

### ISSUE THREAD

**Issue by mortb** [dotnet/project-system#3021]
Visual Studio 2017 (15.4.4) in a solution that uses project system:

After using "Find all" to find all files containing a text Visual Studio hangs for a long time if I click in the "Find Results" window if the result set is large. (Quite annoying).

("Find all" is one of my favorite ways of navigating the code as I can cover as an example both cs, ts and config files)
We use McAffe for antivirus, if that might be involved.

**Comment by Pilchie** [comment]
@mortb can you use the VS "Report Feedback" to record this issue?  That will capture a performance trace and upload it for the right team to look at.  (That team also doesn't track issues on GitHub).

**Comment by Pilchie** [comment]
Closing as external, since this isn't actionable without a trace.
