### ISSUE TITLE
Improve Target framework selection

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/project-system#3024]
When using _Visual Studio 2017_, I would like the ability to change the target framework of a project without restriction. Currently, _Visual Studio_ limits the framework options given to a user based on the initial project type. Since I am able to now edit a `*.csproj` and save a change to the `<TargetFramework>` node, shouldn't the GUI allow me to do that same?

When I create a new project targeting the `netstandard1.5` target framework moniker, the dropdown is limited to variants of **.NET Standard**.

#### The `.csproj` targeting `netstandard1.5`
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.5</TargetFramework>
  </PropertyGroup>
</Project>
```

![image](https://user-images.githubusercontent.com/7679720/33664675-14ce5a72-da5a-11e7-8377-fb8a2b6a09c7.png)

Likewise, if I change this in the `*.csproj` to target `net461` for example - the options are again limited to **Full .NET Framework** listings.

#### The `.csproj` targeting `net461`
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
</Project>
```

![image](https://user-images.githubusercontent.com/7679720/33664855-a9a470d2-da5a-11e7-9117-4e2cf349ce32.png)

Finally, the same is true for `netcoreapp2.0` - targeting **.NET Core**.

#### The `.csproj` targeting `netcoreapp2.0`
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
</Project>
```

![image](https://user-images.githubusercontent.com/7679720/33665036-2a46ae62-da5b-11e7-81f1-e2ea9d050fcf.png)

**Comment by Pilchie** [comment]
@davkean @natidea I suspect this might be dupe, but didn't see it?

**Comment by davkean** [comment]
I've not seen an actual bug on this - but this is a good suggestion and something we've wanted to do for a while.

**Comment by Amoenus** [comment]
Maybe also consider Ctrl+Click for multi-select. As we are also allowed to do 
```XML
<TargetFrameworks>net461;netstandard2.0</TargetFramework>
```

**Comment by davkean** [comment]
@Pilchie said:

Ideally, we'd split the concepts apart, but for 15.8, we'd be willing to just merge them into the same list:

![image](https://user-images.githubusercontent.com/312835/40336420-56d6b2ce-5d1e-11e8-9139-f1bb41b48824.png)

**Comment by tmeschter** [comment]
We don't intend to do any specific work here.
