### ISSUE TITLE
Unsupported project with an existing .NET Core csproj with VS2017 15.5

### ISSUE THREAD

**Issue by xoofx** [dotnet/project-system#3025]
Hi,
I upgraded to VS2017 15.5 and trying to compile https://github.com/lunet-io/markdig/
and I'm getting this error without more information (the log it says that I could check doesn't exist):

![markdig_error](https://user-images.githubusercontent.com/715038/33674790-d47eda3a-dab0-11e7-8de8-b25f5f38e5fe.png)

So there is likely something not supported in [this csproj](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Markdig.csproj) but I haven't tried to figure out yet what exactly is making this project no longer loaded. If you have any clue about this, let me know!

cc: @davkean @Pilchie

**Comment by Pilchie** [comment]
Took a quick glance at the project, and I don't know off the top of my head, but do you have the UWP tools workload installed?

Additonally, does the output window say anything if you right click and choose "Reload project"?

**Comment by xoofx** [comment]
> Took a quick glance at the project, and I don't know off the top of my head, but do you have the UWP tools workload installed?
> Additonally, does the output window say anything if you right click and choose "Reload project"?

I had the project compiling just fine before installing the 15.5 version. What I found strange is that I don't get any errors in the output window, only this report (like it is trying to migrate the project...)

but...

I just tried to delete the `.vs` folder and... everything is working again... so problem solved. Sorry for the trouble!

**Comment by davkean** [comment]
That is strange, trying to understand why we would hit this path - did you save the .vs folder?

**Comment by xoofx** [comment]
> did you save the .vs folder?

Oops sorry, actually tried multiple times just to make sure that it was this so I don't have even it in my recycle bin... but anyway, If it comes up again as an issue on someone else project, you will be able to ask for a full zip of the directory and try to reproduce it. But it is a fact that I have seen the .vs folder quite a few times being responsible for some weird behavior like this...

**Comment by davkean** [comment]
The VS folder contains the suo - which contains temporary data we store about projects, upgrades, etc so that we don't need to calculate it again.

**Comment by davkean** [comment]
For anyone else running into this - we're aware and we've raised a bug against the right team internally. We're unsure of the cause yet.

**Comment by davkean** [comment]
@xoofx Do you remember if Markdig.WebApp also failed to load above? The screenshot cuts that project out.

**Comment by xoofx** [comment]
> @xoofx Do you remember if Markdig.WebApp also failed to load above? The screenshot cuts that project out.
