### ISSUE TITLE
Adding a new class (scaffolding) does not pay attention to tab settings.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3038]
This worked in previous versions of VS but using Core and VS 2017 when I add a new class the file is created and it has the VS default tab settings applied not what is currently set. We have changed our tabs from 4 to 3 spaces (don't ask why - 15 year old decision) and when a new class is added there are 4 space tabs. I have to reformat the document every time to get it to change to 3 spaces. This will cause tab inconsistencies in our project long term. The scaffolding needs to format the document using the current tab settings when the file is created.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/159713/adding-a-new-class-scaffolding-does-not-pay-attent.html
VSTS ticketId: 532832_
_These are the original issue comments:_

Jeff Kelly [MSFT] on 12/7/2017, 10:26 AM (3 days ago): <p>Thank you for your feedback! </p><p><br></p><p>Is there an .editorconfig file anywhere up the directory structure under the project where you observe this problem? These config files will conflict with the tab settings you specify in Tools -&gt;Options.</p><p><br></p><p>We look forward to hearing from you!</p>

Steve Overton on 12/7/2017, 10:30 AM (3 days ago): <p>Jeff, I cannot find any.</p>

Jeff Kelly [MSFT] on 12/8/2017, 03:45 PM (2 days ago): <p>Thanks for checking. I can reproduce your issue in a .NET Core project (although .NET Framework classes work as you expect in both VS 2015 and VS 2017).</p><p><br></p><p>We'll keep this marked as under investigation to allow others to find and vote on it, and will keep this issue updated as we make progress towards a fix.</p>
_These are the original issue solutions:_
(no solutions)

**Comment by Pilchie** [comment]
Note that Roslyn formats new documents added from templates [here](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/AbstractEditorFactory.cs,229), but it doesn't look like this is supported by the new project system?

**Comment by davkean** [comment]
The new templating engine doesn't apply the ["template" bit when creating project files](https://github.com/dotnet/templating/issues/1225), I suspect individual files suffer from the same thing. I don't know what actually scaffolds though.

@mlorbetske?

**Comment by davkean** [comment]
and @phenning?

**Comment by mlorbetske** [comment]
Scaffolding is done differently than template creation (see aspnet/scaffolding)

@prafullbhosale

**Comment by mlorbetske** [comment]
In this case, I don’t believe the new template engine is in play as it’s generally not used for item templates in VS

**Comment by phenning** [comment]
Mike is correct, I just confirmed that none of the item templates other then the new razor page template invoke the new template engine.

**Comment by davkean** [comment]
This issue was moved to aspnet/Scaffolding#662
