### ISSUE TITLE
Recreating a missing folder crashes the project system

### ISSUE THREAD

**Issue by tomzorz** [dotnet/project-system#3058]
Given a **.net standard library project** where **a folder is missing from the project**
![image](https://user-images.githubusercontent.com/6363312/34083830-d199a588-e376-11e7-85ea-9f86c800e562.png)
then I **right click the project, Add > New Folder, enter the missing folder's name, hit OK** crashes the project system.

See the logs below, more than one crash inside it:

[VsProjectFault_bc79d1bf-ffdd-49b2-b4ba-510b47afa2eb.failure.txt](https://github.com/dotnet/project-system/files/1566075/VsProjectFault_bc79d1bf-ffdd-49b2-b4ba-510b47afa2eb.failure.txt)

**Comment by tomzorz** [comment]
I found the issue when pulling a project from git where a folder only had linked files in it, therefore from the file-system's perspective it was empty. (As we all know git doesn't check in empty folders.)

**Comment by davkean** [comment]
Thanks for tracking down repro. I can reproduce this - it an issue in an internal VS component and have opened a bug for it against them. 

Microsofties can see the bug here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/541104.

**Comment by tomzorz** [comment]
@davkean great, thanks for the quick follow-up! :)

This got me thinking about ways to avoid the issue I mentioned with git... maybe VS should automatically recreate the folder if it's empty but it should be there according to the .csproj? Or at least a warning when using git that the folder won't be checked in?

**Comment by davkean** [comment]
@tomzorz The old project system automatically re-created folders on open and we received feedback in the past that devs don't like this behavior. 

What if we had a way to just let you recreate it from within Visual Studio without needing to create a new folder?

**Comment by tomzorz** [comment]
Sure, that seems to be a good option. But I'd certainly add something of a warning as well, telling you that when someone does a clean pull / clone it'll be broken.
