### ISSUE TITLE
Option to disable fast-up-to-date check is not persistent

### ISSUE THREAD

**Issue by Pilchie** [dotnet/project-system#3067]
_From @jcouv on December 19, 2017 23:11_

Repro:
1. Disable the option
2. Close and re-open VS
3. The option is set again, but it should be unset

![image](https://user-images.githubusercontent.com/12466233/34183248-a9c5aa94-e4ce-11e7-85fe-752b8ca49949.png)

Tagging @AlekseyTs since he mentioned this problem, and I just observed it as well.

_Copied from original issue: dotnet/roslyn#23871_

**Comment by panopticoncentral** [comment]
@jcouv I haven't been able to reproduce this problem -- I'm seeing the settings persist correctly. My guess is that it may be a VS settings general problem. If you need help figuring out how to proceed, let me know.
