### ISSUE TITLE
Buggy namespace selection via keyboard-only

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3071]
When I try to change the selection of the namespaces I'd like to import in the references menu in the project properties, the focused row doesn't always fit to the changes which happen, when I press space to change the import status.
If I scroll through the namespaces to import by using only the arrow buttons on my keyboard and alter the import status of the selected namespace by pressing space, it can happen, that not the selected namespaces import status changes but another one. It sometimes also select and deselect each time another item, even if I don't change the row.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/164693/buggy-namespace-selection-via-keyboard-only.html
VSTS ticketId: 536186_

**Comment by drewnoakes** [comment]
@melytc assigning to you as part of the VB property pages work. This should fall out of any accessibility work we do there.

**Comment by ocallesp** [comment]
Based on the description of this bug, it seems that If we go the Property Pages | References | Imported Namespaces  and then use the keyboard keys up/down to move and select with the key Space we see it can correctly check the selected namespace. This works correctly in the old Project System.
![SelectImportedNamespaces](https://user-images.githubusercontent.com/510598/169137674-53b70218-7758-48ee-b31d-8ec5c8d77389.gif)

@melytc by quickly watching the gif, can you confirm I am testing it correctly the described behavior ?

**Comment by ocallesp** [comment]
Does not repro
