### ISSUE TITLE
Adding new C# files causes the csproj file to be changed

### ISSUE THREAD

**Issue by jamesqo** [dotnet/project-system#3076]
**VS version:** 15.5.1

Whenever I add a new C# file to a .NET Core project, I consistently get diffs in my project file like:

```csproj
  <ItemGroup>
    <Compile Update="DecafUnitTests.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
```

I have to manually remove such elements every time Visual Studio generates them. Since this does not seem to affect the build process at all, I have to ask: what's the reason for inserting these inserting these elements in the first place? I thought one of the primary benefits of the new project system was supposed to be it didn't change your csproj every time you added a file.

**Comment by natidea** [comment]
What type of project are you creating, and what steps are you using to add the C# file? C# files are implicitly included in .NET Core projects -- the entry you are seeing is an "Update" to the already included file to set the SubType to Code.

**Comment by Pilchie** [comment]
@jamesqo - can you answer @natidea's question?

**Comment by jamesqo** [comment]
@natidea I think I resolved the problem. A while ago I created a custom 'New C# Class' template because I didn't like all of the usings the default one added. Only this new template is causing that entry to be added, while the default one isn't.
