### ISSUE TITLE
NoWarn on PackageReferences seems to be broken.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#3077]
VS Build: 15.6.0 Preview 3 [27211.3005.d15.6stg]

Create a .NET Core 2.0 console app.

Add a packageref like this:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.3" NoWarn="NU1701" />
  </ItemGroup>
```

Expected: No NU1701 warnings 

Actual:  I get a NU1701 warning. 

If I change this to a NoWarn at the project level then it suppresses the warning.

**Comment by davkean** [comment]
Yep, dupe of https://github.com/NuGet/Home/issues/6340
