### ISSUE TITLE
How does project system determine if the project is ASPNET or generic C#?

### ISSUE THREAD

**Issue by am11** [dotnet/project-system#3079]
I noticed that sometimes modifying solution (add/remove project or solution item) causes my regular, *non-web* console app SDK-style projects to have `9A19103F-16F7-4668-BE54-9A1E7A4F7556` GUID in SLN, while the intended behavior is to <ins>keep</ins> the `FAE04EC0-301F-11D3-BF4B-00C04F79EFBC` GUID which was originally in sln file. This causes unintentional diffs in code checkins.

If VS is adding `FAE04EC0-301F-11D3-BF4B-00C04F79EFBC` on creating the .NET Core Console app and then changing it to `9A19103F-16F7-4668-BE54-9A1E7A4F7556` when modifying items in solution explorer, which GUID is expected and which one is incorrect? For variety, see https://github.com/dotnet/project-system/issues/2891.

Is it correct that:

* `9A19103F-16F7-4668-BE54-9A1E7A4F7556` is ASP.NET Core web application project GUID
* `FAE04EC0-301F-11D3-BF4B-00C04F79EFBC` is a generic C# project GUID, that is applicable to any csharp-y project and should be used in non-aspnet scenario?
  * If this is true and there is no benefit out of this specificity, can `9A19103F-16F7-4668-BE54-9A1E7A4F7556` be deprecated even for ASP.NET Core projects?

It seems if we have any ASP.NET Core package referenced in non-web, regular-console project, this alteration happens on modifying solution items in VS. To me it happened in a solution containing sfproj and a csproj, where csproj is SDK-style console app (targeting net462 TFM), referencing `Microsoft.AspNetCore` package. Perhaps the determination logic that deals with "Identification of ASP.NET project" needs a revisit?

**Comment by Pilchie** [comment]
See https://github.com/dotnet/project-system/blob/master/docs/opening-with-cps.md.  `9A19103F` is the "new" project system guid, and `FAE04EC0` is the "old" one.  .NET Core apps should always be the `9A19103F` guid, whether they are console apps or web.

**Comment by am11** [comment]
Thanks for the reference @Pilchie! I will use 9A19103F for new projects. 🎉

**Comment by thusithagh** [comment]
@Pilchie appreciate if you can update the link as it is broken as of now.
Thank you.

**Comment by davkean** [comment]
New location is: https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md

**Comment by JeppeSN** [comment]
A list of project types including 9A19103F and FAE04EC0 and many others, can be found at [/JamesW75/visual-studio-project-type-guid](https://github.com/JamesW75/visual-studio-project-type-guid).
