### ISSUE TITLE
Some new project need to upgrade

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/project-system#3086]
When I use Import, some new project have to upgrade, others don't have to upgrade

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Tuhu.props" />
</Project>
```
vs15.5.2

**Comment by Pilchie** [comment]
This is happening because the file sniffer is falling back to using the old project system.  In order for it to realize that it should use the new project system make sure the file directly contains either `<TargetFramework>` or `<TargetFrameworks>`.

**Comment by Pilchie** [comment]
See https://github.com/dotnet/project-system/blob/master/docs/opening-with-cps.md for some more context here.

**Comment by pengweiqhca** [comment]
@Pilchie Thanks, I change the GUID to new GUID, Thanks
