### ISSUE TITLE
No thread-safe way to iterate VisualBasicNamespaceImportsList

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3101]
There appears to be no thread-safe way to iterate VisualBasicNamespaceImportsList:

https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS/ProjectSystem/VS/Automation/VisualBasicNamespaceImportsList.cs.

While we lock when you access the indexer/count, etc, that lock is not held in the following situations:

``` C#

foreach (string import in vsProject.Imports)    // No lock taken at all
{

}
```

-or-

``` C#
for (int i = 0; i < vsProject.Imports.Count; i++)   // Lock is only held while you access `Count`
{
   var import = vsProject.Imports[i]; // Lock is only held while you read the indexer
}
```

At any time while iterating those a background thread could update the imports.

**Comment by Pilchie** [comment]
Seems like this could be fixed by changing so that:

1. Changes to the list are serialized through the UI thread.
2. Mutating operations like `VisualBasicVSImports.Remove` wait for the dataflow changes to be processed before returning.

I guess that's problematic if there was an unrelated change that also caused a dataflow change?

**Comment by Pilchie** [comment]
Presumably this issue applies to many automation objects, not just this one too?

**Comment by davkean** [comment]
No, we wrote this one - CPS wrote the others. I believe they are thread-safe.

**Comment by Pilchie** [comment]
Are there pointers to the CPS ones?  How do they implement their thread safety?

**Comment by davkean** [comment]
OAVSReferences and ReferencesHostBridge are examples.

**Comment by davkean** [comment]
> Changes to the list are serialized through the UI thread.
That's exactly what it does via the `ProjectHostBridge<TInput, TOutput, TApplied>` base class.

**Comment by Pilchie** [comment]
That still suffers from the problem that mutations that happen through that interface on the UI thread are not immediately visible, doesn't it?

**Comment by davkean** [comment]
That's what this line does:

``` C#
await this.ProjectNode.Value.ReferencesHostBridge.ReceiveLatestSnapshotAsync();
```

See OAVSReferences.AddProject.

**Comment by Pilchie** [comment]
Got it.  Seems like that's the pattern to follow here then.

**Comment by davkean** [comment]
Yeah exactly, either we copy the base class or just get CPS to make it public.

**Comment by Pilchie** [comment]
@lifengl - I took a stab at copying the code today, but there is quite a lot of it, and some of it depends on other internal parts of CPS.  Any chance we could make `UnconfiguredProjectHostBridge` and `ProjectHostBridge` public?

**Comment by Pilchie** [comment]
Moving this to 15.7, since it's not newly broken, and I'm waiting for API from CPS.

**Comment by davidwengier** [comment]
As mentioned above, this should use a ProjectHostBridge so that the collection won't change when accessed on the UI thread.
