### ISSUE TITLE
In VB .NET Core projects, "Disable all warnings" of "Compile" tab doesn't work for some warnings

### ISSUE THREAD

**Issue by ghost** [dotnet/project-system#3102]
**Steps:**
- In VS, create a  VB .net core console app project.
- Add a NuGet Package reference to "NLog" (or some other package targetting .NET Framework). 
- Open Error List (View -> Error List), it contains a warning.
- Open the project properties page, in "Compile" tab, check "Disable all warnings" and save.

**Expect Result:**
The warning is disabled.

**Actual Result:**
Error List window still  contains the warning.
![image](https://user-images.githubusercontent.com/24784908/34558870-a94bec46-f17a-11e7-94a1-a4c0801ba4a0.png)

**Note:**
For C# and F# .net core projects, in "Build" tab of project properties, can suppress the warning succeeded.

**Test Environment:**
VS build: D15.6/27302.01 (15.6 Preview 2)
Dotnet --info:
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by Pilchie** [comment]
@Xiu-Li how are you suppressing the warning for C# and F#?

I suspect that this option just passes `/nowarn` to vbc.exe, but doesn't affect other parts of the build pipeline.

**Comment by Xiu-Li** [comment]
@Pilchie 
For C# and F#, right-click project -> Properties -> Build tab -> Errors and warnings section
Add NU1701 to the list, can  suppress the warning succeeded.
![image](https://user-images.githubusercontent.com/24784908/34592722-07630630-f201-11e7-9064-5ec1c94b34eb.png)

**Comment by Xiu-Li** [comment]
If edit the .vbproj file, add `NoWarn="NU1701"` to the package reference, can suppress the warning. (For VB, C# and F#, it works fine).
The .vbproj file as below:
![image](https://user-images.githubusercontent.com/24784908/34593355-5b124bac-f205-11e7-9bba-b72d82ed12e5.png)

**Comment by tmeschter** [comment]
In the VB experience you don't get to disable specific warnings (at least, not directly), but you can disable all warnings with the checkbox. This works by setting the `WarningLevel` property to "0".

In C# you _can_ disable specific warnings (which will update the `NoWarn` property), and you can set the "Warning level" drop down to "0" to disable them all.

I imagine NuGet utilizes the `NoWarn` property but not `WarningLevel`; this makes sense as the interpretation of `WarningLevel` is very much specific to the compiler.

I'm going to move this issue to the NuGet team; the Project System team can help but ultimately they will need to decide what sort of user experience they want to have around disabling NuGet warnings.
