### ISSUE TITLE
Rename .cs -> Refactor prompt slow for .NET Core/Standard projects, but fast for .NET framework projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3103]
The title says it all really.

Create two projects (one .NET Core, and the other .NET Framework) and repeat the following steps:

1. Select Class1.cs, and press F2 (rename)
2. Rename it to whatever you like.
3. Wait for the &quot;Do you want to name the class&quot; type prompt.

In .NET Core/.NET Standard you have to wait for quite a while for the prompt, but in .NET Framework the prompt appears very quickly.

Why is there this discrepency between projects of different types?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/169697/rename-cs-refactor-prompt-slow-for-net-corestandar.html
VSTS ticketId: 541163_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by tmeschter** [comment]
I *think* we currently wait until we've seen the file renamed in the Roslyn workspace, which means we wait an arbitrary amount of time before popping up the dialog.

Ideally, the dialog would come up synchronously and immediately upon the user renaming the item in Solution Explorer. That is, if possible we don't want to wait on some asynchronous data flow before asking about the rename.

**Comment by jp2masa** [comment]
When renaming files, I think that I have the same problem (or a really similar one).

There are 2 situations that I tested:
1. If the class file is opened, after renaming the file it immediately prompts to rename the class, and if I accept it, it fails.
2. If the class file is not opened, renaming the file doesn't show the prompt (not sure if it would show after some time), but if I open the file it immediately prompts to rename the class, and it works.
