### ISSUE TITLE
Error when clicking on project in Dependencies>Projects: unresolvedReference

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3108]
Open a project whose dependencies splits into Assemblies, NuGet and Projects.
Double click on one of the projects. You'll see error box &quot;Value cannot be null. Parameter name: unresolvedReference&quot;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/177085/error-when-clicking-on-project-in-dependenciesproj.html
VSTS ticketId: 546956_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by drewnoakes** [comment]
Duplicate of #403.
