### ISSUE TITLE
Dependency node shows no child nodes for the first project created in latest bits

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3111]
Unsure if this caused by the bits in master or it repros due to our side-loaded VSIXs.

Commit: a5bbdbc28e098d9d78fea11e9219fcf073c27fdf
Build: Version 15.6.0 Preview 1.1 [27219.0.d15.6]

1.  Sync to above commit
2.  `Build.cmd`
3. `devenv /RootSuffix ProjectSystem`
4. File -> New -> C# -> Console App (.NET Core)

Expected: Dependency node to have nodes
Actual: It has zero nodes

![image](https://user-images.githubusercontent.com/1103906/34634943-6148d0bc-f2dd-11e7-84c2-9c257b97f9a2.png)

I've confirmed that NuGet restore has occurred and was successful. If you create a new project or open another project it shows successfully.

**Comment by davkean** [comment]
tag @natidea

**Comment by natidea** [comment]
I initially worried this may be related to https://github.com/dotnet/project-system/pull/3080
But the problem occurs before that PR was checked in. Comparing the oldest build I can find with this with an older builds is: https://github.com/dotnet/project-system/compare/2a5a5dc9da4e83403b2f0dbf6fe1777eff946c25...3a00e1ac65c44d76c6f1915c5173e89d4df6922c . Investigating some more...

**Comment by natidea** [comment]
I've tracked this down to a weird MEF composition error in [DependencyRulesSubscriber](https://github.com/dotnet/project-system/blob/0f59a6a6758184b0e2668c7ab1733b5d7c96f11e/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/DependencyRulesSubscriber.cs#L29). (Hopefully it is not actually MEF composition but something is changing our collection)

The Handlers collection contains all the rule handlers for processing analyzers, packages etc. In the base class, [CrossTargetRuleSubscriberBase.cs#L240](https://github.com/dotnet/project-system/blob/0f59a6a6758184b0e2668c7ab1733b5d7c96f11e/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/CrossTarget/CrossTargetRuleSubscriberBase.cs#L240), we iterate through each relevant handler calling its HandleAsync method. This typically happens first for Evaluation builds, then for DesignTime builds. 

In a debugger, I've observed several instances where the Handlers collection is correctly populated during the Evaluation pass, but then is empty during the DesignTimeBuild phase, hence no processing occurs. 

![image](https://user-images.githubusercontent.com/7732033/35064795-113d4caa-fb80-11e7-8659-6f4fdf74109d.png)

This does not occur all the time, so its flaky. I confirmed the constructor is called only once so something else is changing the collection.

**Comment by natidea** [comment]
Update: It appears MEF ImportMany is clearing and resetting the collection. But this is (probably) not the problem. The underlying collection actually has all the items required, but the CPS [OrderPrecedenceImportCollection](http://index/?leftProject=Microsoft.VisualStudio.ProjectSystem&leftSymbol=zqmmlkyegufq&file=Composition%5CCollections%5COrderPrecedenceImportCollection%7BT%2CTMetadata%7D.cs&line=310) is filtering them out unexpectedly. 

In fact this is occurring in other places as well: [DependenciesProjectTreeProvider.ViewProviders](https://github.com/dotnet/project-system/blob/0f59a6a6758184b0e2668c7ab1733b5d7c96f11e/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesProjectTreeProvider.cs#L77) is also sometimes returning an empty collection leading to an unresolved dependencies node.
