### ISSUE TITLE
(VB Console Property Page ) Implement ImportEvents in References Property page

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/project-system#312]
https://github.com/dotnet/roslyn-project-system/blob/64ed9e5b4a7c20c0bcb51af95c8136fbc23f7527/src/Microsoft.VisualStudio.Editors/PropPages/ReferencePropPage.vb#L1734

It of type http://index/#Microsoft.VisualStudio.TeamArchitect.ManagedPackageFramework/Automation/VSProject/OAVSProject.cs,2d37b422442c94b5,references

Cps just added the ability for us to implement vsproject on our side. We'll need to implement an object that implements vsprojevt and export that

**Comment by basoundr** [comment]
fixed in #1911
