### ISSUE TITLE
Dependant projects versions is not overridden when building with msbuild parameter PackageVersion

### ISSUE THREAD

**Issue by thtp** [dotnet/project-system#3120]
Solution includes some projects which depends on each other and are built as nugget packages.
Solution is build with the following command:
`dotnet msbuild ololo.sln /p:Version=3.1.431 /p:FileVersion=3.1.431 /p:PackageVersion=3.1.431`
As a result of this command dependand packages versions are not updated.
![image](https://user-images.githubusercontent.com/6025469/34723810-e374dd8e-f55c-11e7-92f5-7174d7077877.png)

**Comment by Pilchie** [comment]
@livrarcocc / @nguerrera - SDK issue?

**Comment by livarcocc** [comment]
@rohit21agrawal what is the best way to do this?

**Comment by rohit21agrawal** [comment]
this has been fixed via : https://github.com/NuGet/NuGet.Client/pull/1915

**Comment by Pilchie** [comment]
Thanks @rohit21agrawal!
