### ISSUE TITLE
LangVersion drop-down should populate list from compiler

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#3121]
Every time the compiler adds a new language version, we need to remember to add it manually to the project system (for instance, https://github.com/dotnet/project-system/pull/2334, which also discussed this problem).

The compiler supports listing supported language versions from the command-line (see below). We could add an API to expose this information in a more formal/structured way.

@davkean @jasonmalinowski @Pilchie Would you have an idea of how such an integration would work?

```
>csc /langversion:?
Supported language versions:
default
1
2
3
4
5
6
7.0 (default)
7.1
7.2 (latest)
latest
```

**Comment by jasonmalinowski** [comment]
It can't be an API in the traditional sense if you consider compiler-is-in-a-NuGet-package scenarios. There, the IDE doesn't load any compiler binaries from that package at all.

I could imagine the .targets that define CoreCompile also define a property/item group that specifies all of them, and then the project system queries that data as it would any other property/item group.

**Comment by jcouv** [comment]
@Pilchie I see that the issue is currently in Milestone=Unknown. 
What is the process to get it scheduled? 
I'd hope we could do this for 16.0.

**Comment by Pilchie** [comment]
I'm not planning that far out right now.  We're focused on perf, reliability, and scenario blocking bugs for .NET Core/.NET Standard right now.

**Comment by jcouv** [comment]
Adding a note to record the fact that this feature would have been handy to manage the "*beta*" label which we need to add for C# 8.0 (and eventually remove).

**Comment by cartermp** [comment]
This should probably be closed out given the .NET Core 3 changes around this UI
