### ISSUE TITLE
[Question] Replace Debug project designer page

### ISSUE THREAD

**Issue by jp2masa** [dotnet/project-system#3123]
If possible, I'd like to replace the `Debug` project designer page with a custom one. For the C# project system the page order is 4, for the Visual Basic one it's 2, and for the F# one it's 3. Maybe the project designer page providers could import `IDebugPageGuidProvider` and use that GUID? If there's no export for `IDebugPageGuidProvider`, then the project designer page wouldn't be displayed (currently it's conditionally displayed based on the presence of the `LaunchProfiles` capability).

**Comment by Pilchie** [comment]
@jp2masa are you wanting this only for SDK based projects, or also for classic projects?

**Comment by Pilchie** [comment]
Regardless, we won't be able to tackle this in 15.6 or 15.7 (though we might be able to slip a PR in if one appeared).

**Comment by jp2masa** [comment]
I only need it for SDK based projects. I'm not sure if this is the best way to implement it, but I can work on it if the idea is approved.

**Comment by davkean** [comment]
@jp2masa Are you using launch profiles? If not you can just remove that capability. 

> Maybe the project designer page providers could import IDebugPageGuidProvider and use that GUID? If there's no export for IDebugPageGuidProvider, then the project designer page wouldn't be displayed (currently it's conditionally displayed based on the presence of the LaunchProfiles capability).
That might work if you change it like so; import a collection of IDebugPageGuidProvider (using OrderPrecedenceImportCollection), and if the highest priority returns an empty guid, we'd skip adding it. For there to be "no exports" you'll have undefine `LaunchProfiles` - which itself will remove the page.

Alternatively, we could implement; https://github.com/dotnet/project-system/issues/2073 which enable you do this via MSBuild properties.

**Comment by jp2masa** [comment]
Actually, I found out that the current Debug page is extensible and it works for what I need, so this is no longer a problem. Thanks for the help.
