### ISSUE TITLE
Compiler in IDE uses wrong LangVersion after Reload

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#3125]
I'm working on `Compilers.sln` from Roslyn's `features/async-streams` branch. I just switched to that branch (from `dev15.6.x` branch), and VS prompted me to reload the solution.

After the solution is reloaded, I get red squiggles that relate to the LangVersion:
![image](https://user-images.githubusercontent.com/12466233/34800622-73d9e09c-f619-11e7-8231-59ba015a2e65.png)

I confirmed that the compiler in the IDE is given `default` as a LangVersion, which is incorrect:
![image](https://user-images.githubusercontent.com/12466233/34800638-82135f6c-f619-11e7-8a3f-d1a9b6b30831.png)

This is despite the project being configured to use LangVersion 7.2.
![image](https://user-images.githubusercontent.com/12466233/34800671-a42700fe-f619-11e7-948c-fa6d61249b43.png)

Building from the command-line works fine:
![image](https://user-images.githubusercontent.com/12466233/34800677-afa6ef3e-f619-11e7-8732-d2a5ed28d1cb.png)

After I closed VS and re-opened it, everything was back to normal:
![image](https://user-images.githubusercontent.com/12466233/34800895-ad8f4326-f61a-11e7-937d-87bbde090c77.png)

I'm using:
```
Version 15.6.0 Preview 2.0 [27304.0.d15.6]
VisualStudio.15.IntPreview/15.6.0-pre.2.0+27304.0.d15.6
```

**Comment by Pilchie** [comment]
Did this persist forever, or was it immediately after loading the solution?  Did the rest of the IDE work as expected?  Wondering if the project state didn't include a full design time build and only had evaluation state.

**Comment by jcouv** [comment]
This only occurred after a Reload. But it went away after closing and re-opening VS and the solution.
I did not notice any other misbehaviors in the IDE.

**Comment by Pilchie** [comment]
I just tried this with 27319.1, and I couldn't repro it.  Please let me know if you can again and I'll dig in further.
