### ISSUE TITLE
Cleaning a solution or project shows warnings on all dependencies 

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/project-system#3126]
1. Create a new ASP.NET Core Web application targeting .NET Core 2.0 (version doesn't matter, repros with 1.0 and 1.1 too)
2. Build, all dependencies should be valid
3. Clean Solution. All the dependency nodes  show the warning. Presumably this is because the asserts file has been removed? This seems like a bug to me.
4. Restore solution. Dependency nodes still show warning even though restore succeeds.
5. Build solution. Build succeeds but dependency node still shows the warnings.

This is with VS build 27309.3006.d15Stg

**Comment by BillHiebert** [comment]
I am seeing a lot of scenarios where the dependencies nodes show the warnings even though everything is fine. Sometimes just closing and re-opening a solution shows this.

**Comment by Pilchie** [comment]
@natidea does this look like another instance of the dataflow race?

**Comment by natidea** [comment]
Confirmed this no longer repros after applying race condition fix: https://github.com/dotnet/project-system/pull/3167
