### ISSUE TITLE
Create a new .net core project, can't restore automatically.

### ISSUE THREAD

**Issue by Xiu-Li** [dotnet/project-system#3127]
- Create a new .net core project, waited a long time, but there was no automatic restore.
- If right click the solution and restore nuget package manually, restore succeeded but the dependencies can't show.
![image](https://user-images.githubusercontent.com/24784908/34818924-3a7862cc-f6f7-11e7-9f98-a98776d0413e.png)

Workaround: Close the solution and reopen

Tested on VS build **D15.6stg/27310.3001 (15.6 Preview 3)**
dotnet --info:
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by davkean** [comment]
By no automatic restore do you mean the Dependencies node was empty? Or was there actually no restore? ie Did "string[]" in the signature show up as blue?

**Comment by Xiu-Li** [comment]
Waited for a long time, the Output window does not have any information to show restore finished, and the Dependencies node was empty.

**Comment by Xiu-Li** [comment]
Maybe it has been restored actually, build succeeded.

**Comment by davkean** [comment]
I do wonder if https://github.com/dotnet/project-system/issues/3111 is a dupe.

**Comment by Pilchie** [comment]
Seems likely to be a dupe.  @natidea can you take a look as soon as you get a chance?

**Comment by jp2masa** [comment]
I have the same problem I think. I need to build the project to force restore.

**Comment by Xiu-Li** [comment]
Yeah, I tried it again, the Output window does not have any information to show restore finished and the dependencies node shows a warning sign. Sometimes some codes show squiggles and error list shows the errors, but sometimes there is no.
If I build the project, the status bar will show restore completed and build succeeded, but the dependencies node was empty.

**Comment by abpiskunov** [comment]
Saw this issue too in one of the latest Stg builds.

**Comment by natidea** [comment]
I'm investigating this as part of https://github.com/dotnet/project-system/issues/3111. I'll close this report as a dupe.
