### ISSUE TITLE
Assembly neutral language not sorted

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3128]
When trying to select the neutral language for an assembly it was found that the languages are not sorted. This makes it very hard to find the appropriate language.

Additionally it would be very nice to be able to type in this field and the list of best matches be presented and options to pick. sort of like predictive text.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/180611/assembly-neutral-language-not-sorted.html
VSTS ticketId: 550178_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by sputier** [comment]
@Pilchie It seems this issue would be perfect for someone who would like to start contributing to the project, So... I'll work on it 😄

**Comment by Pilchie** [comment]
Awesome - thanks @sputier let us know if you have any questions along the way.

**Comment by sputier** [comment]
For this kind of tasks, I usually work with LINQ : 
```
Dim AllCultures As CultureInfo() = CultureInfo.GetCultures(CultureTypes.NeutralCultures Or CultureTypes.SpecificCultures Or CultureTypes.InstalledWin32Cultures).
                OrderBy(Function(language) language.DisplayName).ToArray()
```

Would this kind of code be allowed in this project context ?

**Comment by Pilchie** [comment]
I'm not worried about the overhead of linq for this - it only happens when the user explicitly drops down the list of cultures.  Not exactly a hot-path.

**Comment by sputier** [comment]
I Submitted a PR for the ordering. Should I also address the second part of the issue (change the combobox AutoCompleteMode to Suggest) ?

**Comment by Pilchie** [comment]
If you want to I'm not against it. @davkean any thoughts there?

**Comment by davkean** [comment]
Looks like we're already [Append](https://github.com/sputier/dotnet-project-system/blob/ae42003809ae0e34e587635e98c1d8f2c0a83a3a/src/Microsoft.VisualStudio.Editors/PropPages/AssemblyInfoPropPage.Designer.vb#L256), so switching to SuggestAppend sounds good.

**Comment by davkean** [comment]
We'll leave this open to address the auto-complete mode.

**Comment by sputier** [comment]
@Pilchie @davkean As the 2 PRs were merged, the issue can be closed 😄

**Comment by Pilchie** [comment]
Yes indeed.  Thanks again!
