### ISSUE TITLE
Add Property Page Validations

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/project-system#313]
**Validations**
- [ ] MaxLength validations
- [ ] Trailing slash validation on path
- [ ] Enum out of range validations

look for current validation at https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_search?type=Code&lp=git-project&text=vsprojectproperties.cpp&result=DefaultCollection%2FDevDiv%2FVS%2FGBmaster%2F%2Fsrc%2Fvsproject%2Fvsprojectprops%2FVsProjectProperties.cpp&preview=0&filters=ProjectFilters%7BDevDiv%7D&_a=contents

**Comment by kvenkatrajan** [comment]
Closing - validation present in new property pages.
