### ISSUE TITLE
Spurious warnings icons on the SDK node in the solution explorer

### ISSUE THREAD

**Issue by danroth27** [dotnet/project-system#3133]
I'm seeing warning icons on the SDK node in the solution explorer in VS when opening ASP.NET Core projects:

![image](https://user-images.githubusercontent.com/1874516/34852480-b6d471ee-f6e3-11e7-955d-d70fea7f6832.png)

For example I see this when opening one of the projects in the https://github.com/aspnet/signalr-samples repo.

There are no corresponding errors or warnings in the Errors List:

![image](https://user-images.githubusercontent.com/1874516/34852492-cd9125bc-f6e3-11e7-972c-ec596b52e636.png)

If I reload the project then the warning icons go away.

Machine setup:
- Windows 10
- VS 15.5.3

```
C:\>dotnet --info
.NET Command Line Tools (2.2.0-preview1-007925)

Product Information:
 Version:            2.2.0-preview1-007925
 Commit SHA-1 hash:  ff4299241c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.0-preview1-007925\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26110-02
  Build    : 77152705cd56e7d89f52585959ec3559d91084c4
```

**Comment by natidea** [comment]
We believe this is fixed by https://github.com/dotnet/project-system/pull/3167
