### ISSUE TITLE
C# Intellisense doesnt work with new keywords

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/project-system#3145]
when I type `in` for in parameter, then writing parameter name in method signatureintellisense doesn't suggest names anymore.

current version: 15.5.2

**Comment by Pilchie** [comment]
Hi @MkazemAkhgary - do you have the Language Version option set in project properties?

cc @jcouv.

**Comment by MkazemAkhgary** [comment]
@Pilchie It was set to latest minor version AFAIK.

**Comment by Pilchie** [comment]
This issue was moved to dotnet/roslyn#24326
