### ISSUE TITLE
Is .ruleset support broken?

### ISSUE THREAD

**Issue by taori** [dotnet/project-system#3150]
Recently i figured out that you can configure custom analyzers using ruleset files. This seemed amazing and i utilized it in a project. Oddly enough when i checked out if there are any other built in rules i could utilize they just simply would not work.

![grafik](https://user-images.githubusercontent.com/5545184/35008224-0b994c9c-fafc-11e7-8f0e-333e8ec04ff1.png)

The project is NET 4.6.2

Project.csproj contains entries for both debug+release config

`    <CodeAnalysisRuleSet>ProjectName.ruleset</CodeAnalysisRuleSet>`

ProjectName.ruleset content:

```
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="Regeln für ProjectName" Description="ProjectName.csproj." ToolsVersion="15.0">
  <Rules AnalyzerId="Microsoft.Analyzers.ManagedCodeAnalysis" RuleNamespace="Microsoft.Rules.Managed">
    <Rule Id="CA1001" Action="Error" />
    <Rule Id="CA1009" Action="Warning" />
    <Rule Id="CA1016" Action="Warning" />

  </Rules>
</RuleSet>
```
Test class to verify the rule: (I want this to be an error.)

https://msdn.microsoft.com/en-us/library/ms182172.aspx
```
public class Test
{
  private  IDisposable test =  new MemoryStream();
}
```

**Comment by Pilchie** [comment]
Tagging @mavasani - this should *probably* be moved to https://github.com/dotnet/roslyn though?

Also - what build are you on?  There was an issue with custom analyzers not working properly in 15.5.0, but it should be fixed in the most recent builds.

**Comment by taori** [comment]
@Pilchie i assume you're talking about the VS build - that would be 15.5.4. Mind you that custom analyzers did work for me but built in ones apparently do not respond to ruleset configuration.

**Comment by taori** [comment]
Apparently the VM i was testing this with originally was not on 15.5.4 - The ruleset does look different now, as well as the analyzers list.
Can't select CA 1001 anymore.
![grafik](https://user-images.githubusercontent.com/5545184/35038524-5c0d6774-fb7b-11e7-8062-52236770e512.png)

Analyzers list used to be empty - now it isn't. While that seems like an improvement it does lack analyzers i would imagine. 
![grafik](https://user-images.githubusercontent.com/5545184/35038554-744de282-fb7b-11e7-9712-599cf1226ceb.png)

Attempting to add rulesets does not seem to work. At least the previous screenshot did not get more options to select from. I guess something is broken here.

![grafik](https://user-images.githubusercontent.com/5545184/35038660-be9e1a5a-fb7b-11e7-9778-a2ed533bc64f.png)

**Comment by Pilchie** [comment]
How are you installing the custom analzyers?  That looks like the default set that VS provides?  Maybe you need a reference to the NuGet package or extension for roslyn based static analysis?

**Comment by taori** [comment]
This problem isn't about custom analyzers at all - It's about adding VS analyzers not responding to the ruleset configuration (see link of the analyzer which i referenced in my first post). And i can't seem to add them to the screen 

![grafik](https://user-images.githubusercontent.com/5545184/35038524-5c0d6774-fb7b-11e7-8062-52236770e512.png)

after interacting with the screen 

![grafik](https://user-images.githubusercontent.com/5545184/35038660-be9e1a5a-fb7b-11e7-9778-a2ed533bc64f.png)

This problem seems to be more dominant when using a .netstandard project. Ordinary .netframework projects appear to suffer from this too.

look at this minimal .net class library
![grafik](https://user-images.githubusercontent.com/5545184/35102547-84f0e8a8-fc63-11e7-953f-0ceb59e522eb.png)

According to the sample for CA1001, this project should not be compiling or am i doing something wrong here?

**Comment by Pilchie** [comment]
This issue was moved to dotnet/roslyn#24404
