### ISSUE TITLE
DynamicDependentFile capability broken in VS 15.5

### ISSUE THREAD

**Issue by aienabled** [dotnet/project-system#3155]
Hello!

I've noticed that DynamicDependentFile capability doesn't work after updating to VS 15.5.
The XAML rule which requires this capability stopped working:
`<NameValuePair Name="DependentExtensions" Value=".xaml.cs" />`

(full rule, it was fine before VS 15.5)
```XAML
    <ContentType
        Name="PageXaml"
        DisplayName="XAML Page"
        ItemType="Page">
        <ContentType.Metadata>
			<NameValuePair Name="DependentExtensions" Value=".xaml.cs" />
			<NameValuePair Name="DefaultMetadata_SubType" Value="Designer" />
			<NameValuePair Name="DefaultMetadata_Generator" Value="MSBuild:Compile" />
		</ContentType.Metadata>        
    </ContentType>
```

Regards!

**Comment by aienabled** [comment]
@adrianvmsft

**Comment by Pilchie** [comment]
@lifengl - looks like this is CoreCPS, so better to track with https://github.com/Microsoft/VSProjectSystem/issues/261?

**Comment by lifengl** [comment]
Yeah, it sounds we should take a look first. I created a bug in TFS to track it

**Comment by jviau** [comment]
The issue is that [ProjectItemsSchema.xaml](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ProjectItemsSchema.xaml#L64) does not have the metadata @aienabled listed above.

**Comment by aienabled** [comment]
@jviau, the problem is not only with the particular XAML rule from ProjectItemsSchema.xaml - we've created a custom XAML rule to use `DependentExtensions` metadata in our custom project system (as @adrianvmsft recommended). It was working fine until VS 15.5. Now `DependentExtensions` doesn't have any effect. So I've created this issue to report that `DependentExtensions` feature is broken now.

**Comment by jviau** [comment]
Also, it looks like .netcore projects don't have the `DynamicDependentFile` capability by default.

@aienabled, I'll continue to help you with your issue on the other github issue.
