### ISSUE TITLE
ResXFileCodeGenerator does not run on linked files

### ISSUE THREAD

**Issue by nguerrera** [dotnet/project-system#3156]
## Repro steps

* [repro.zip](https://github.com/dotnet/project-system/files/1641163/repro.zip)
* Open CPS\ConsoleApp29.sln
* Edit linked file Resources\Resource1.resx in designer, save

## Expected result
* Resource1.Designer.cs is updated with changes made to resx
* Note that this worked in classic project system (see Classic\ConsoleApp31.sln)

## Actual result
* No changes are applied to Resource1.Desgner.cs

**Comment by Pilchie** [comment]
@brettfo - is this what you were seeing yesterday in the F# build?

**Comment by davkean** [comment]
I suspect not related to #2687 - I suspect a CPS issue.

**Comment by ocallesp** [comment]
PR https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/CPS/pullrequest/253809
