### ISSUE TITLE
FastUpdateCheck: How to add extra input/outputs groups properly?

### ISSUE THREAD

**Issue by xen2** [dotnet/project-system#3157]
As part of a .csproj, I add some targets to compile some native code (but it could be anything that takes one input file and generate an output file, independent from C# .cs/.dll files).

Let's say for example I have `MyAssembly.csproj` with `a.c` and it will generate `a.exe`.
I can add `<ItemGroup><UpToDateCheckInput Include="a.c" /><UpToDateCheckOutput="a.exe" /></ItemGroup>` in the project, and write a target generating it (i.e. just before `CoreCompile`).

However, FastUpdateCheck will start mixing `.cs=>.dll/.pdb` with `a.c=>a.exe` in terms of timestamp, and will always fail the fast update.
For example, if I update `a.c`, `MyAssembly.dll` won't be recompiled and the check will fail.

Ideally the dependency `a.c` => `a.exe` should be kept separate from the C# ones.
* Is that possible?
* Another option is make sure after a successful build that timestamp of outputs are later than timestamp of inputs (or otherwise touch the files).

**Comment by panopticoncentral** [comment]
We just added (in the 15.6 branch) a new item called UpToDateCheckBuilt that should help here. It can have a property "Original" that will cause the item to only be compared against that original file. So:

`<UpToDateCheckBuild Include="a.exe" Original="a.c" />`

Should do what you want. I don't think this has been published in a public preview, but will be part of the 15.6 release.

**Comment by xen2** [comment]
Perfect, thanks for the explanation!
For future readers, it seems to be `UpToDateCheckBuilt` (not Build).

I hope Original can contain multiple items for a single output, will give it a try.

**Comment by xen2** [comment]
@panopticoncentral Thanks!
Quick question, can it support multiple sources, such as:
`<UpToDateCheckBuild Include="a.exe" Original="a.c;b.c" />` ?

**Comment by panopticoncentral** [comment]
I didn't add that because I didn't need it, but if you want to file an issue, we can look at it...
