### ISSUE TITLE
Build Target Stack Corruption

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#3161]
When building Roslyn.sln in recent builds of VS, I've been encountering this dialog:
![image](https://user-images.githubusercontent.com/2371880/35120758-03ddad9c-fc4e-11e7-8b0b-c58ecba5435e.png)
```
=====================
1/18/2018 12:48:29
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: '_GetProjectReferenceTargetFrameworkProperties', Actual: 'ResolveProjectReferences'.
===================
1/18/2018 12:48:30
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: '_GetProjectReferenceTargetFrameworkProperties', Actual: 'ResolveProjectReferences'.
===================
1/18/2018 12:48:31
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: 'ResolveProjectReferences', Actual: 'GetCopyToOutputDirectoryItems'.
===================
1/18/2018 12:48:32
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: 'DispatchToInnerBuilds', Actual: 'ResolveProjectReferences'.
===================
1/18/2018 12:48:33
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: 'DispatchToInnerBuilds', Actual: '_GetProjectReferenceTargetFrameworkProperties'.
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
===================
```

It seems to be relatively reproable by building Roslyn twice. The build succeeds the first time, and fails the second time with that error.
/cc @rainersigwald @olegtk @nguerrera

**Comment by Pilchie** [comment]
@lifengl @jviau Any ideas here?

**Comment by lifengl** [comment]
Andrew also reported that issue.  I am trying to reproduce it but have trouble to do.  Do you have a way to repro it?

Sent from my phone

On Jan 18, 2018, at 12:53 PM, Kevin Pilch <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flifengl&data=02%7C01%7C%7C905587904eeb416df81408d55eb59677%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636519056358480480&sdata=2v3FMiR2PZqSINTVYHJiwRQQRjEaVlY4tNBjsZC1KLU%3D&reserved=0> @jviau<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjviau&data=02%7C01%7C%7C905587904eeb416df81408d55eb59677%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636519056358480480&sdata=eg8aYrzMrkQrbwGNM4oIdmD04BEhbjhi6Z1ly5T%2BUrk%3D&reserved=0> Any ideas here?

**Comment by Pilchie** [comment]
I don't think we have a 100% repro, but several people have been seeing it regularly.

**Comment by rainersigwald** [comment]
@lifengl I'm pretty sure MSBuild with this pull request will do it for every VS build: https://github.com/Microsoft/msbuild/pull/2868.

**Comment by 333fred** [comment]
I was seeing this pretty consistently on rebuilds of Roslyn.

**Comment by lifengl** [comment]
That sounds good.  With a reasonably repeatable repro, we should find out what happened.  We will take a look tomorrow or early next week.

Sent from my phone

On Jan 18, 2018, at 1:23 PM, Fred Silberberg <notifications@github.com<mailto:notifications@github.com>> wrote:


I was seeing this pretty consistently on rebuilds of Roslyn.

**Comment by Pilchie** [comment]
@lifengl Would you prefer a VSTS bug to track this?

**Comment by lifengl** [comment]
We have a bug to track that.

Sent from my phone

On Jan 19, 2018, at 8:03 AM, Kevin Pilch <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flifengl&data=02%7C01%7C%7Cb6026394073145a57b3208d55f5630aa%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636519746144147964&sdata=F6astgbZPKIYi5mdoUlOhWQSUwZOceDCtz5lCVL%2BGrI%3D&reserved=0> Would you prefer a VSTS bug to track this?

**Comment by Pilchie** [comment]
Can you link to it please?

**Comment by lifengl** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/531370
