### ISSUE TITLE
Observed some BOM/non ASCII characters in appsettings.json in .net core web api project

### ISSUE THREAD

**Issue by shinkarmv** [dotnet/project-system#3171]
While working with appsettings transformations using python script in Docker file.
I have observed that some BOM/non ASCII characters in the starting of appsettings.json

Please find screenshot below for reference
![image](https://user-images.githubusercontent.com/31374791/35232511-a587348a-ffc1-11e7-9f82-287cded2edfe.png)

These characters came by default with project template of WEB API in Visual Studio 2017 .Net Core.

Regards,
Mukesh

**Comment by Pilchie** [comment]
Likely a UTF-8 BOM?

**Comment by Pilchie** [comment]
@BillHiebert ?

**Comment by shinkarmv** [comment]
Yes @Pilchie.  These are BOM characters.

**Comment by shinkarmv** [comment]
I have cross verified the unit test at SchemaStore repository and observed no BOM character in it.

Please see below screenshot for reference.

![image](https://user-images.githubusercontent.com/31374791/35235561-86c41afa-ffca-11e7-85c5-fca50eae9deb.png)

Regards,
Mukesh

**Comment by Pilchie** [comment]
@jmarolf @mlorbetske - do you know where this comes from?

**Comment by jmarolf** [comment]
@mlorbetske I believe these come from the WebToolsExtensions repo

**Comment by shinkarmv** [comment]
Hi @Pilchie ,

I did some analysis on the aforementioned issue and finally got the Project Template for WEB API for C# .net core app.

Repository - https://github.com/aspnet/templating

Template link - https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/WebApi-CSharp/appsettings.json

I have validated appsettings,json file and got some BOM characters at start of file.
Please find the screenshot below for reference,

![image](https://user-images.githubusercontent.com/31374791/35430494-821a07ea-029e-11e8-83bc-c470e5ec2d7a.png)
 
cc: @mlorbetske, @jmarolf

Regards,
Mukesh

**Comment by Pilchie** [comment]
This issue was moved to aspnet/templating#276

**Comment by shinkarmv** [comment]
Thank you @Pilchie for moving the issue at appropriate location.

Regards,
Mukesh

**Comment by Pilchie** [comment]
No problem!
