### ISSUE TITLE
Legacy project system - design time compiles per DLL in nuget package

### ISSUE THREAD

**Issue by maxinfet** [dotnet/project-system#3172]
I have been investigating why our main solution freezes for ~1 hour after a developer builds the first time after getting a fresh branch. Our solution is 69 C# projects with some WPF, ASP.NET and Unit Test projects, all using the legacy project system. After getting the Project System Tools extension and setting TRACEDESIGNTIME=true I was able to see we are performing 140 design time builds with compile as the only target and they take 7 seconds each for our main WPF application and altogether we are performing 2415 design time builds.

I have been trying to find what causes these design time builds and I made a small project to attempt to do that. It seems that adding some nuget packages will cause a design time build for each dll in the nuget package. I installed Newtonsoft.Json which contains 1 dll and it caused one more design time compile to be generated when building after getting a fresh version of the branch. Then I tried adding Google.Apis.Auth which adds 11 dlls all together and I see 11 design time compiles. I then wanted to see what would happen if I referenced the Newtonsoft.Json dll directly by copying the downloaded dll to another solutions root and referencing it in that solution. After referencing the dll directly I got no design time compiles.

Is this expected behavior to see this many design time builds with the compile target? When looking at the binary logs for them they are virtually the same. Some targets will take more or less each time and the order might change a little.

I created three reproduction projects for this. If you need me to upload these somewhere else I can.
[No Design Time Compiles](https://www.dropbox.com/s/9g859kahgfuzqz1/NoDesignTimeCompiles.zip?dl=0)
[1 Design Time Compile](https://www.dropbox.com/s/phbz4el5k5qy3qr/1DesignTimeCompiles.zip?dl=0)
[11 Design Time Compiles](https://www.dropbox.com/s/69jbibxkf7ynr20/11DesignTimeCompiles.zip?dl=0)

Steps to Replicate:
1.) Download one of the builds above
2.) Open the solution
3.) Open the Build Logging Window
4.) Start logging
5.) Build the solution
Result: The noted amount of design time builds with compile as the target are produced.
Expected Result: 1 Design Time Compile is performed.

To rerun the test close Visual Studio and run the cleanup.bat which sets it back to the state we get our branches in.

**Comment by Pilchie** [comment]
Tagging @panopticoncentral and @tmeschter who are both looking at related things.

**Comment by maxinfet** [comment]
I was actually wondering if this might have something to do with the Facades. I added one of our packages that contains ActiveReports dlls and did not see any additional design time builds. The only difference I can see between the packages I mentioned in my original post and this post are that the Newtonsoft and Google packages offer dlls that were targeted at a .NETStandard and a PCL.

**Comment by panopticoncentral** [comment]
It's a mix of a known bug and a new bug. What's happening is that after we build, we synchronously refresh all unresolved references. We have an open work item to make this refresh async so it doesn't block the UI. But there's an additional bug--when the references refresh, we end up doing a design-time build per reference even though they're all from the same project. So we end up doing 11 builds of the same project. We should be smarter here.

**Comment by tmeschter** [comment]
@maxinfet Are you using packages.config in your projects, or `<PackageReference>` elements? If the former, I would also expect you to see 4-5 design-time builds of the `ResolveReferences` target per assembly when adding new packages. I'm working on eliminating most of those as well.

**Comment by maxinfet** [comment]
@tmeschter We are using package.config

**Comment by maxinfet** [comment]
Just curious but how does a milestone correlate to Visual Studio releases? I was looking back at the close dates for milestones and they seem pretty frequent but didn't know how closely they correlate to when they are released to stable.

**Comment by Pilchie** [comment]
They are designed to match :)

**Comment by panopticoncentral** [comment]
This will be fixed in the next 15.6 preview.
