### ISSUE TITLE
VS 15.5.4 does not add explicitly code file created with new item command when EnableDefaultCompileItems is set to false

### ISSUE THREAD

**Issue by 4creators** [dotnet/project-system#3181]
One of the configuration options for new format project files allows to switch off default globbing patterns used for including compile items into csproj. When `EnableDefaultCompileItems` is set to false it is impossible to add new code file to project when using `Add New Item` command. Code file is created in the project directory be it Interface or Class but it is not added explicitly as `<Compile Include"Class.cs"/>` despite `EnableDefaultCompileItems` being set to false. As a result file is not compiled with project.

**Comment by davkean** [comment]
The project system behavior is currently by design based on the default globs in the SDK. It's trying to avoid double-including the file, see the following: https://github.com/dotnet/project-system/issues/2678#issuecomment-327047828. The workaround is opt also out of the None glob, or opt out of all globs.

**Comment by davkean** [comment]
@nguerrera @dsplaisted Thoughts on this? The opt outs aren't really setting the user up for success (see my comment above) - maybe None shouldn't include source files?

**Comment by nguerrera** [comment]
@davkean. Yes, I think having default none glob exclude source file irrespective of whether they are themselves globbed as source files is reasonable. I have been confused by the current behavior myself. Let me try to find the existing SDK bug to dupe this against.

**Comment by nguerrera** [comment]
https://github.com/dotnet/sdk/issues/1157

**Comment by davkean** [comment]
Dup'ing against SDK bug.
