### ISSUE TITLE
In "Application" tab of project properties page, the "Target framework" is empty, not ".NET Core 2.1".

### ISSUE THREAD

**Issue by Xiu-Li** [dotnet/project-system#3183]
## **Description:**
Create a new .net core project, open project properties page, for "Application" tab, the "Target framework" is empty,  there is no ".NET Core 2.1".
![image](https://user-images.githubusercontent.com/24784908/35368211-21be059a-01bd-11e8-8b78-d3480cafd38f.png)
## **Test Environment:**
d15svc/27130.2024 (15.5.4) + master/SDK 2.1.300-preview2-008017:
(Add dotnet-core package source: https://dotnet.myget.org/F/dotnet-core/api/v3/index.json)
dotnet --info:
```
.NET Command Line Tools (2.1.300-preview2-008017)

Product Information:
 Version:            2.1.300-preview2-008017
 Commit SHA-1 hash:  f4a0d2db0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008017\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26116-04
  Build    : eeb3a84e2142aba791fe003564b8afd048c45ff9


```

**Comment by natidea** [comment]
Some history:
- Hardcoded list was added here: https://github.com/dotnet/project-system/pull/744
- Then it was removed in favor of dynamic population in https://github.com/dotnet/project-system/pull/2097 . Dynamic population is based on `SupportedTargetFrameworks`

**Comment by natidea** [comment]
`SupportedTargetFrameworks` appears to be set in: [Microsoft.NET.SupportedTargetFrameworks.props](https://github.com/dotnet/sdk/blob/8fb4e45e2997e55ca0ef8b45cfe830ce2b85a2ca/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.SupportedTargetFrameworks.props)
/cc @livarcocc looks like this needs to be fixed in the SDK

**Comment by livarcocc** [comment]
Can you make a PR?

**Comment by natidea** [comment]
@livarcocc sure, I'll test it locally first

**Comment by Xiu-Li** [comment]
Verified on **d15.6/27408.00 (15.6 Preview 5)** + [release/2.1](https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1) **2.1.300-preview1-008117** --> **Not Repro**

**Comment by natidea** [comment]
Fixed by https://github.com/dotnet/sdk/pull/1939
