### ISSUE TITLE
Unable to find roslyntools.modifyvsixmanifest when building from VS

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/project-system#3188]
After a fresh checkout I opened ProjectSystem.sln in VS 15.5.4 and tried to build the solution. 13 projects (e.g. Microsoft.NetCore.FSharp.ProjectTemplates.Test) failed with errors like this:

> 8>The system cannot find the path specified.
> 8>C:\Users\loop-evgeny\.nuget\packages\roslyntools.repotoolset\1.0.0-beta-62512-01\tools\VisualStudio.targets(140,5): error MSB3073: The command ""C:\Users\loop-evgeny \.nuget\packages\roslyntools.modifyvsixmanifest\1.0.0-beta-62327-02\tools\ModifyVsixManifest.exe" --vsix="C:\W ork\project-system\artifacts\Debug\VSSetup\Insertion\Microsoft.NetCore.FSharp.ProjectTemplates.Test.vsix" --remove=//x:PackageManifest/x:Installation/@Experimental --add-attribute=//x:PackageManifest/x:Installation;SystemComponent;true" exited with code 3.

Indeed, the directory "C:\Users\loop-evgeny .nuget\packages\roslyntools.repotoolset" does not exist.

**Comment by loop-evgeny** [comment]
After running `build.cmd` all projects build successfully (but that has its own issue - #3187).

**Comment by Pilchie** [comment]
@tmat - any idea why the NuGet path would be missing a `\` here?

**Comment by tmat** [comment]
@loop-evgeny Could you try to open VS Developer Command Prompt and execute `build.cmd /diagnostic` from the repository root? Did it report any errors? If so, could you share files in `artifacts\Debug\log` directory?

**Comment by loop-evgeny** [comment]
The only error I got in the command prompt window was this:
```
XUnit : error : C:\Data\project-system\artifacts\Debug\TestResults\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests_net461_x86.html [net461|x86] [C:\Data\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj]
```

Here are the logs anyway: [log.zip](https://github.com/dotnet/project-system/files/1698424/log.zip)

Anyway, build.cmd worked for me the first time, it's only the VS build (before build.cmd) that failed.

**Comment by tmat** [comment]
> it's only the VS build (before build.cmd) that failed

@loop-evgeny Does it work now? Do you have automatic NuGet package restore enabled in VS? 

![image](https://user-images.githubusercontent.com/41759/35873892-f43474da-0b1f-11e8-8841-111c7446d817.png)

**Comment by loop-evgeny** [comment]
It works now, yes - even after a "git clean -d -x -f". I don't know why. Yes, I have those 2 checkboxes checked.

**Comment by tmat** [comment]
The packages are restored to your profile directory: `C:\Users\loop-evgeny.nuget\packages`
If you want to experiment you can delete that directory and see if it works. Note that after opening the solution you need to give it a bit of time to restore everything.

**Comment by drewnoakes** [comment]
I experienced this after clearing my NuGet caches and packages via `dotnet nuget locals -c all`

The build requires files under `~\.nuget\roslyntools.modifyvsixmanifest` yet building in VS does not restore this package.

As mentioned above, the fix is to run `build.cmd` from the root directory.
