### ISSUE TITLE
Packagecreation has no working UI Editor for the Version

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3199]
The packageeditor (in my example C# Project) has at the second textbox the field &quot;Packageversion&quot; which sets the XML Value (in the csproj File) of &quot;Version&quot; but the created name of the package has the &quot;PackageVersion&quot; tag, which can only be edited by editing the raw XML from the csproj

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/188197/packagecreation-has-no-working-ui-editor-for-the-v.html
VSTS ticketId: 557256_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by drewnoakes** [comment]
The new project properties UI addresses this issue.
