### ISSUE TITLE
How to copy a folder to output directory?

### ISSUE THREAD

**Issue by yhvicey** [dotnet/project-system#3203]
```xml
<ItemGroup>
  <Folder Include="$(SolutionDir)config\" CopyToOutputDirectory="Always" />
</ItemGroup>
```

It didn't work, what's the correct way to copy a folder to output/publish dir?

**Comment by Pilchie** [comment]
Sounds like a question for the Microsoft/MSBuild repo.  @andygerlicher or @rainersigwald any ideas?

**Comment by rainersigwald** [comment]
MSBuild doesn't have a built-in concept for this. There are two usual approaches:

* Copy all of the contents of the folder instead
  * This works great as long as the contents of the directory are static. If files are added to the directory during the build, you must use a target to expand the wildcard, or it will copy only the files that were present at the beginning of the build.

```xml
<ItemGroup>
  <None Include="$(SolutionDir)config\**" CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>
```

* Use a custom target with a task that is designed to copy folders. One example is the MSBuildExtensions [Robocopy Task](http://www.msbuildextensionpack.com/help/4.0.12.0/html/220731f6-6b59-0cde-26ee-d47680f51c10.htm).

**Comment by Pilchie** [comment]
Thanks @rainersigwald !

**Comment by yhvicey** [comment]
Thank you for pointing the way & answering.

**Comment by vrd** [comment]
@rainersigwald I have folder "resources" in my solution folder. This folder contains many other folder and files. I want only this content to be in my output folder (not the folder "resources" itself). I used your solution and add this lines to project file:
```
<ItemGroup>
    <None Include="$(SolutionDir)resources\**" CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>
```
But I get folder "resources" with all its content in my output folder. So all paths to files in app is broken.  How to copy only content of specific folder to output folder? 
(VS Community 2017 v 15.7.3)

**Comment by yhvicey** [comment]
@vrd https://github.com/Microsoft/msbuild/issues/2949#issuecomment-362824225 This might helps you.
