### ISSUE TITLE
Adding a NuGet package causing design time build to fail will cause reloading the project endlessly

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#3210]
This issue happens after we changed the order of targets to build and move "CompileDesignTime" before other targets (necessary steps to fix the COM reference bug).  Basically, I cannot load cps.sln on a new enlistment, because the Nugetlizer 3000 package causes the design time build to fail, when a referenced project hasn't been built (and produced the referenced assembly).

To fix this issue, CPS will add a flag to the project rule subscription flow to mark whether the evaluation successes.  When it failed, don't run NuGet restore to remove all known references.

**Comment by lifengl** [comment]
I noticed that the old similar issue was reactivated.

**Comment by natidea** [comment]
Linking to https://github.com/dotnet/project-system/issues/2867
