### ISSUE TITLE
Bogus "missing a using directive or an assembly reference" error in .Net Standard project

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#3211]
Ported from a customer reported bug (550403).

On CPS side, we have done a chance to allow rules to specify the building order of targets.  To fix this issue after taking the CPS change, you just need change the 'CompileDesignTime' rule, and set an Order number (property on the rule), to a value between 1 - 4999. (suggest to set it to 100).  A target specified in a rule with a smaller order number will be built first.  When the number is not specified or it is 0, it will be treated as 5000 (to prevent using negative numbers in other rules.)   

Steps to reproduce:
 
Create two sample .Net standard class libraries targeting to .NET standard 2.0 in VS 15.5.2. For our reference name one project as ProjectA and other one as ProjectB which will have ProjectAClass and ProjectBClass classes respectively.
Now add reference to ProjectB from ProjectA project and create an instance of ProjectBClass under ProjectAClass as below…
public class ProjectA
    {
        ProjectB.ProjectBClass obj = new ProjectB.ProjectBClass ();
    }
Everything is fine now and project builds successfully, intellisense and go-to definition feature works as expected.
Now add any COM reference from COM tab in ProjectA. For example first item under the COM tab Accessibility. Now you will see errors in the error window.

**Comment by lifengl** [comment]
Changing the order of target increases chances to run into the  [endless reloading bug](https://github.com/dotnet/project-system/issues/2867), which should be fixed first.

**Comment by lifengl** [comment]
Link to the issue #2521:
Note: CompileDesignTime is not registered later, and causes an extra DT build.  When you move the order number to move it ahead of other targets.  Our logic will think the other targets have been built earlier, so a hard reset to the DTBB service is required, which will throw away the cache for the entire solution.  In a large solution, it will cause hard reset for every project, so defining the target order without registering the target earlier enough will cause a serious performance regression.

**Comment by davkean** [comment]
A workaround is to add the following to your project file:

``` XML

  <Target Name="COMReferencesWorkaround" BeforeTargets="ResolveAssemblyReferences" DependsOnTargets="ResolveProjectReferences">
  </Target>
```

**Comment by davkean** [comment]
I'm going to dupe this against the MSBuild bug: https://github.com/Microsoft/msbuild/issues/2591. It has a pending PR for this and the correct fix is to make sure that targets have their correct dependencies listed.
