### ISSUE TITLE
Exporting a custom IDebugProfileLaunchTargetsProvider doesn't work

### ISSUE THREAD

**Issue by jp2masa** [dotnet/project-system#3219]
I tried exporting a custom `IDebugProfileLaunchTargetsProvider`, but when trying to launch the project I get an error dialog with this message (replaced the namespace with `YYY` and the class name with `XXXLaunchTargetsProvider`):

>This part (YYY.Debug.XXXLaunchTargetsProvider) cannot be instantiated.

If I understand correctly, I need to export it to the `ConfiguredProject` scope, but if I import either `ConfiguredProject` or `UnconfiguredProject`, I get the error. 
I tried using 2.5.0 packages on VS 15.5 and VS 15.6 preview, and 2.6.0 packages on VS 15.6 preview.
I believe this is a CPS bug, but as the interface is part of this project system, I'm filing the issue here.

**Comment by Pilchie** [comment]
@BillHiebert @jviau Either of you have any ideas here?

**Comment by BillHiebert** [comment]
@jp2masa - can you check the ComponentModelCache's error file? It is located in %LOCALAPPDATA%\Microsoft\VisualStudio\15.0_<instanceid>\ComponentModelCache\Microsoft.VisualStudio.Default.err. Is your part listed there?

**Comment by jp2masa** [comment]
I had already checked that, although I forgot to add that information to the issue description. The part isn't listed there.

**Comment by jviau** [comment]
`IDebugProfileLaunchTargetsProvider` is part of this project system as you mentioned. I believe this is a MEF composition issue. Can you share what your class looks like? I can help identify any composition issues.

**Comment by jp2masa** [comment]
The class looks like this:
```cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.ComponentModel.Composition;
using System.Threading.Tasks;
using Microsoft.VisualStudio.ProjectSystem;
using Microsoft.VisualStudio.ProjectSystem.Debug;
using Microsoft.VisualStudio.ProjectSystem.VS.Debug;

namespace MyProjectSystem.VS.Debug
{
    [Export(typeof(IDebugProfileLaunchTargetsProvider))]
    [AppliesTo("LaunchProfiles")]
    [Order(50)]
    internal class MyLaunchTargetsProvider : IDebugProfileLaunchTargetsProvider
    {
        private ConfiguredProject _configuredProject;

        // importing ConfiguredProject or UnconfiguredProject here fails, but, if I understood correctly, this part should be exported to the configured project scope
        public MIEngineLaunchTargetsProvider(ConfiguredProject configuredProject)
        {
            _configuredProject = configuredProject;
        }

        public Task OnAfterLaunchAsync(DebugLaunchOptions launchOptions, ILaunchProfile profile) => Task.CompletedTask;

        public async Task OnBeforeLaunchAsync(DebugLaunchOptions launchOptions, ILaunchProfile profile) => Task.CompletedTask;

        public async Task<IReadOnlyList<IDebugLaunchSettings>> QueryDebugTargetsAsync(
            DebugLaunchOptions launchOptions,
            ILaunchProfile profile)
        {
            return Array.Empty<IDebugLaunchSettings>();
        }

        public bool SupportsProfile(ILaunchProfile profile) => true;
    }
}
```

**Comment by jviau** [comment]
You need to put `[ImportingConstructor]` on your constructor. That's all you are missing!

**Comment by jp2masa** [comment]
I have no idea how I forgot to add it... Thanks for the help, it's working now.
