### ISSUE TITLE
[loc][Query]Please clarify meaning\localizability of string "Up-to-date check built artifact"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/project-system#3222]
Hi, we have a question from a translator. Could you help please?

Source:
Up-to-date check built artifact

File:
project-system/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/UpToDateCheckBuilt.xaml

Query from translators:
--
Please provide furher reference in orther to handle this string properly. Is "up-to-date" a verb?

**Comment by PDostalek** [comment]
Hi, @tmeschter could you please take a look on this vendor bug ? Thanks.

**Comment by Pilchie** [comment]
@panopticoncentral can you clarify this please?

**Comment by panopticoncentral** [comment]
I don't believe this string will ever show up in the UI. The context is: when building a project, we first check to see if the outputs are up to date in respect to the inputs of the project. If the project is up to date, then we don't need to rebuild it. When we are checking if a project is up to date, we need to identify the outputs of the project. We use an item type called UpToDateBuilt, and this string describes it. It is trying to say "This is an item that represents a build artifact (i.e. output) that we use to check whether a project is up to date." If you need more clarification, let me know!
