### ISSUE TITLE
Intellisense in ASP.NET Core .csproj file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3225]
I have a ASP.NET Core 2.0 (dotnet version 2.1.4) project. I'm editing the .csproj file to add a new ItemGroup in order to bring in DotNetCliToolReference. When I type &lt;ItemGroup I get an autocompletion window and pressing tab successfuly fires of the snippet to give me opening and closing tags for this section.

Inside of ItemGroup, when I start to type &lt;Dot there is no statement completion window or tab snippet behaviour at all for DotNetCliToolReference.

Is this behaviour normal? It seems that anything other than top level ItemGroup or PropertyGroup statements get no autocompletion or tab snippet support at when typing lines inside these tags.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/182269/intellisense-in-aspnet-core-csproj-file.html
VSTS ticketId: 551742_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Pilchie** [comment]
There are two sub-issues here:

1. Several reports of our existing, very basic support not working.
2. A desire to integrate better support, for example by bundling the [Project File Tools](https://marketplace.visualstudio.com/items?itemName=ms-madsk.ProjectFileTools) extension as part of VS.

**Comment by jmarolf** [comment]
> Several reports of our existing, very basic support not working.

I am unable to repro this

> A desire to integrate better support, for example by bundling the Project File Tools extension as part of VS.

Moving this support to 16.0

**Comment by Pilchie** [comment]
@davkean had some idea of the problem with the basic support not working - depending on what components were installed.

**Comment by jmarolf** [comment]
@davkean can you elaborate? I have tried installing just the desktop workload and just the web workload.  What set of components breaks this?

**Comment by tom-corwin** [comment]
There's an issue with projects that are restored in a solution folder, too. I believe these are related to this, possibly?

- https://developercommunity.visualstudio.com/content/problem/340537/intellisense-for-csproj-file-not-working-if-projec.html
- https://github.com/Microsoft/msbuild/issues/2787#issuecomment-428419189

**Comment by davkean** [comment]
Duplicating against: https://github.com/Microsoft/msbuild/issues/2787.
