### ISSUE TITLE
Linked Views not working in WebApplication

### ISSUE THREAD

**Issue by reaction1989** [dotnet/project-system#3232]
Hello,

i am trying to share the _Layout.cshtml over multiple projects. I created links in each project, but the application won't run.

I am getting this exception: 

```
An unhandled exception occurred while processing the request.
InvalidOperationException: The layout view '_Layout' could not be located. The following locations were searched:
/Views/Account/_Layout.de.cshtml
/Views/Account/_Layout.cshtml
/Views/Shared/_Layout.de.cshtml
/Views/Shared/_Layout.cshtml
```
While googling i found this old entry on stackoverflow
https://stackoverflow.com/questions/24075105/can-i-use-views-in-folders-linked-from-other-projects

**Comment by Pilchie** [comment]
@DamienEdwards - what's a good home for this issue?

**Comment by Pilchie** [comment]
Oops, that's @DamianEdwards...

**Comment by DamianEdwards** [comment]
It should go in aspnet/Razor

**Comment by Pilchie** [comment]
This issue was moved to aspnet/Razor#2045
