### ISSUE TITLE
Inconsistency in XML node names for nuget packages

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#3238]
[These xml tags](https://github.com/SolutionsDesign/Algorithmia/blob/master/SD.Tools.Algorithmia/SD.Tools.Algorithmia.csproj#L12) don't make sense compared to [Description](https://github.com/SolutionsDesign/BCLExtensions/blob/master/src/BCLExtensions.csproj#L3)
Why is one prefixed with `Package`  while the other isn't?
 
**NOTE:** The last line gives the warning with `long description, use summary` but there is no such thing as `<Summary></Summary>`

**Comment by FransBouma** [comment]
More clarification: 
If you build the BCLExtensions project in vs2017 15.5, you'll get: (release build)
```

1>------ Rebuild All started: Project: BCLExtensions, Configuration: Release Any CPU ------
1>C:\Program Files\dotnet\sdk\2.1.4\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(204,5): warning : Issue found with package 'SD.Tools.BCLExtensions'.
1>C:\Program Files\dotnet\sdk\2.1.4\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(204,5): warning : Issue: Consider providing Summary text.
1>C:\Program Files\dotnet\sdk\2.1.4\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(204,5): warning : Description: The Description text is long but the Summary text is empty. This means the Description text will be truncated in the 'Manage NuGet Packages' dialog.
1>C:\Program Files\dotnet\sdk\2.1.4\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(204,5): warning : Solution: Provide a brief summary of the package in the Summary field.
1>Done building project "BCLExtensions.csproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```
But it's unclear what 'Summary' is, as 'Summary' isn't a tag shown by intellisense. Adding a Summary tag below description doesn't fail but it's also not a tag that's showing up anywhere: e.g. the 'Package' tab on the csproj project properties in vs 2017 doesn't have a 'Summary' field.

**Comment by etbyrd** [comment]
This has been fixed and will be in the next release.  

An issue about the problem:
https://github.com/NuGet/Home/issues/4587

A note about the "Summary" field being deprecated: 
https://github.com/dotnet/project-system/issues/2937#issuecomment-351907557

The error message being removed:
https://github.com/NuGet/NuGet.Client/commit/41e8bde59e9a9e62e71b049ab52a379574d6f3c2

I am closing this issue, but please feel free to reopen if you believe this to be in error.
