### ISSUE TITLE
Changing Platform Target to x86 causes app to no longer start

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/project-system#3248]
VS 15.6.0 preview 4

Create a C# .NET Core Console app.
In Project Properties>Build change Platform Target to x86.
Hit F5

Expected: it works

Actual: it fails. `Unhandled Exception: System.BadImageFormatException: Could not load file or assembly '...\bin\Debug\netcoreapp2.0\ConsoleApp53.dll'. An attempt was made to load a program with an incorrect format.`

I guess it is using the dotnet.exe on the path, which is 64 bit. Should this work?

**Comment by davkean** [comment]
@Petermarcu @nguerrera What's the expectation here again?

**Comment by nguerrera** [comment]
See https://github.com/dotnet/cli/issues/7532

**Comment by davkean** [comment]
Dup'ing it against https://github.com/dotnet/cli/issues/7532. This behavior doesn't sound ideal but I'll let SDK/CLI folks figure out the right solution and if we need changes to support it.
