### ISSUE TITLE
Alternative to nuspec explicit assembly references

### ISSUE THREAD

**Issue by dmitry-a-morozov** [dotnet/project-system#3249]
To setup a context: I work on F# type provider consisting of 2 parts - run-time and design time. 
At compile time a project consuming the type provider must reference only run-time component. Design-time component [loaded in special reflection-only context](https://github.com/Microsoft/visualfsharp/issues/3303#issue-240393680) by F# compiler. If design time components gets referenced therefore loaded it [leads to problems](https://github.com/Microsoft/visualfsharp/issues/4338#issuecomment-365046415). 
Here is the ideal set-up I'm looking for when I `dotnet pack` the run-time portion of the type provider:
- invoke `dotnet pack` for run-time project which triggers compilation of design-time project
- run-time project should have _content-only_ dependency on run-time project. Kind of like described [here](https://blogs.msdn.microsoft.com/kirillosenkov/2015/04/04/how-to-have-a-project-reference-without-referencing-the-actual-binary/) .
- after run-time project build finished output folder should have: run-time assembly, design-time assembly and all dependencies including framework assemblies because eventually they must be co-located in same folder for F# compiler to find it when consuming project compiles. 
- in nuget package I must find a way to [specify referenced assemblies](https://docs.microsoft.com/en-us/nuget/reference/nuspec#specifying-explicit-assembly-references) like in nuspec. Otherwise all assemblies in package get referenced which is not nice and leads to troubles as I mentioned above. I'd love to do without nuspec file. 

Please, advise. 
Thank you.

**Comment by dsyme** [comment]
@dmitry-a-morozov I don't think this is the right place for this - I'd start with a .NET SDK or .NET CLI request that `dotnet pack` have an option to explicitly specify referenced assemblies.  

But TBH the old F# type provider package layout that puts the design-time assembly in the same directory is faulty and we only need it for legacy reasons (eventually all loading will use [this](https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1003-loading-type-provider-design-time-components.md)).  I think we might just have to live with using nuspec files for F# TP packages that want to load into legacy tooling.

**Comment by dmitry-a-morozov** [comment]
@dsyme I thought the new project system is alternative to explicit nuspec file. `dotnet  pack` has only very common parameters and unlikely to cover every little aspect of packaging process. Also it's probably better to persist it with project anyway rather than specifying it every time package is created from command like.

**Comment by dsyme** [comment]
@dmitry-a-morozov `project-system` is actually the Visual Studio bits that support new-style project files.

The project files themselves are implemented through [the .NET SDK](https://github.com/dotnet/sdk) and [the .NET CLI](https://github.com/dotnet/cli) tools.  Not sure where `dotnet pack` is installed but it will be there somehow I think
