### ISSUE TITLE
Change PublishProvider's capability string to include F#

### ISSUE THREAD

**Issue by cartermp** [dotnet/project-system#3251]
See discussion from here on downward: https://github.com/Microsoft/visualfsharp/issues/4332#issuecomment-365429446

**Comment by Pilchie** [comment]
@davkean - is this addressed for 15.7? I know https://github.com/dotnet/project-system/pull/3299 is pending, but this should be fixed without that, right?

**Comment by BillHiebert** [comment]
@vijayrkn would need to confirm

**Comment by vijayrkn** [comment]
Yes, this is fixed in 15.7 p3.
