### ISSUE TITLE
Creating .Net Core/.Net Standard project with.Net Core 2.1 Preview1 shows warning dialog

### ISSUE THREAD

**Issue by richaverma1** [dotnet/project-system#3258]
As reported by CTI
VS build used- D15.7stg/27413.3004(15.7 Preview 1) 
CLI/SDK - 2.1.300-preview1-008123 
Repro -
1. Create .Net Core or .Net Standard project, sometimes this warning shows - 
![image](https://user-images.githubusercontent.com/19596695/36220525-c65d9a04-116f-11e8-86dd-70a800fd8856.png)
and sometimes this is the warning -
![image](https://user-images.githubusercontent.com/19596695/36220547-dc2fd1bc-116f-11e8-9797-e391cc64a5f9.png)

The issue should be fixed for 15.7 Preview1 to be able to support .Net Core 2.1 Preview1

**Comment by Pilchie** [comment]
Isn't this (at least the second) the issue that @jviau fixed yesterday for 15.6?

**Comment by richaverma1** [comment]
This partially is that though that would happen in ASP.NET apps only and this seems to be any .Net Core, .Net Standard.

**Comment by Pilchie** [comment]
There was no reason why that wouldn't have happened on any .NET Core or .NET Standard project.  I'm guessing it was just luck that it didn't.

**Comment by richaverma1** [comment]
in that case porting the same fix over will suffice. I wanted to bring that up first but this scenario looked somewhat different and I filed this issue. What I need to know before .Net Core 2.1 Preview1 ships is that there are no CLI/SDK issues involved in this. Possible to port the fix today so that we can test again in tomorrow's drop and call it good?

**Comment by Pilchie** [comment]
That's a question for @jviau and the CPS team. The fix was in core VS, not this repo.

**Comment by richaverma1** [comment]
oh I see, I'll get a conversation started and I can close this bug then.

**Comment by Pilchie** [comment]
@richaverma1 - should this be closed now?
