### ISSUE TITLE
Remove check for imported targets from up to date check

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/project-system#3273]
The fast up to date check checks to see if imported targets have been modified when determining up to date-ness. Unfortunately, MSBuild does not do that, so you can end up in the situation where an updated target file causes a project to be always up to date. We should remove this check until such time as MSBuild starts to check it too.

**Comment by davkean** [comment]
Ìt does via the `<MSBuildAllProjects>` property which becomes an input for certain targets.

**Comment by panopticoncentral** [comment]
Right, I meant to say that -- we either need to remove the check (which is what the csproj project system does) or look at MSBuildAllProjects instead.
