### ISSUE TITLE
Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.dll are timing out during builds

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3279]
These tests are timing out during builds: 

https://ci.dot.net/job/dotnet_project-system/job/master/job/windows_release_prtest/885
https://ci.dot.net/job/dotnet_project-system/job/master/job/windows_debug/379

**Comment by davkean** [comment]
I suspect the new tests I added to test dataflow, or the tests that fire up a pumping thread.

**Comment by Pilchie** [comment]
Quoting @jaredpar from an email about how `roslyn` captures dumps:

>That’s correct. We essentially spawn of xunit as a process and if it doesn’t complete in ~50 minutes >then we use procdump to kill it and grab a dump.  The 50 minute timeout is roughly 4X the longest >time that xunit should take for our DLLs.
 
>Short term this is the code we use
 
>https://github.com/dotnet/roslyn/blob/master/src/Tools/Source/RunTests/Program.cs#L157

**Comment by davkean** [comment]
The tests I added to test data flow aren't hitting this, I rewrote them and it still deadlocked.

**Comment by davkean** [comment]
This appears to actually be Microsoft.VisualStudio.CSharp.VS.UnitTests.dll on my box, in particular:

```
Rename_Symbol_Should_TriggerUserConfirmationAsync
```

**Comment by davkean** [comment]
I'm wondering aloud if this correlates with increase in rename failures that I'm seeing.

**Comment by davkean** [comment]
Also seeing Microsoft.VisualStudio.Managed.VS.UnitTests hang.

**Comment by 333fred** [comment]
I believe https://ci.dot.net/job/dotnet_project-system/view/Official%20Builds/job/dev15.7.x/job/windows_release/49/ is this as well, likely in Microsoft.VisualStudio.Managed.VS.UnitTests

**Comment by davkean** [comment]
I've checked in https://github.com/dotnet/project-system/pull/3718 which seems to have removed the hangs from my box. I also added time outs to the other tests that I thought might have been the cause here so that we can get more info: https://github.com/dotnet/project-system/pull/3714.

I'll consider this bug done and open new bugs for any new failures.
