### ISSUE TITLE
Shared Projects have target framework drop down

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3300]
These projects shouldn't have this drop down.

![image](https://user-images.githubusercontent.com/1103906/36518340-254d72c6-17da-11e8-89b7-ded47b6e01ac.png)

**Comment by jmarolf** [comment]
Microsoft folk: internal PR is out to fix this: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/12493

**Comment by jmarolf** [comment]
fixed in https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/124931
