### ISSUE TITLE
Support for Class Diagram in .Net Core projects

### ISSUE THREAD

**Issue by smartcodinghub** [dotnet/project-system#3305]
This feature is useful when working with a huge codebase or domain. In orther to work with this I followed this stackoverflow:

https://stackoverflow.com/questions/47967459/how-to-generate-class-diagram-from-asp-net-core-1-1-project

But it only work until I closed the editor and never more. It didn't show the associations neither.

Is there any plan to support this?

**Comment by Pilchie** [comment]
Yes, we'd like to support it - see #1848, #2999, and #3003 .
