### ISSUE TITLE
Adding new *.cs file while having the property EnableDefaultCompileItems on false

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/project-system#3307]
@edsonaf commented on [Fri Feb 23 2018](https://github.com/dotnet/core/issues/1280)

# Creating new *.cs file while having the property EnableDefaultCompileItems on false does not automatically add this file in the project file

# General

- This is on Visual Studio 2017 Version 15.5.57
- Using the new SDK project format style
- Has `<EnableDefaultCompileItems>false</EnableDefaultCompileItems>`
- Has external files included using the `<Compile Include="" />` way
- Project was ported from the old .net framework project style to the new style as this project is now a netstandard2.0 project.

I can actually fix this issue very easily by just removing the <EnableDefaultCompileItems>false</EnableDefaultCompileItems> and removing the two files that are already included with the `<Compile Include="" />` 

However some solutions that we have, have cs files that are compiled with a Prebuild target. To use them while building, they needed  to be explicitly added in the project file and therefor the EnableDefaultCompileItems property was also used.

**Comment by davkean** [comment]
@edsonaf I believe we already have a bug on this but as a workaround, the targets that produce the cs files that generated during prebuild should be generated into the immediate directory to play nicely with globbing, build and source control in-general.

**Comment by davkean** [comment]
Yeah, we do, duping this against: https://github.com/dotnet/project-system/issues/3181.

**Comment by davkean** [comment]
Here's an example https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L22, ie:
```
<PropertyGroup>
    <MyGeneratedFile>$(IntermediateOutputPath)$(MSBuildProjectName).MyGeneratedFile.cs</MyGeneratedFile
</PropertyGroup>
```

**Comment by davkean** [comment]
One more thing, see this comment https://github.com/dotnet/project-system/issues/2678#issuecomment-327047828 which provides another workaround if you'd like to continue to opt out of globs.

**Comment by davkean** [comment]
Duping this actually against https://github.com/dotnet/sdk/issues/1157.
