### ISSUE TITLE
Inefficient usage of the immutable collections inside Dependencies code

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#3310]
I also noticed some inefficient usage of the immutable collection, like:
           var worldBuilder = ImmutableDictionary.CreateBuilder<string, IDependency>( StringComparer.OrdinalIgnoreCase);
           worldBuilder.AddRange(DependenciesWorld);
           var topLevelBuilder = ImmutableHashSet.CreateBuilder<IDependency>();
           topLevelBuilder.AddRange(TopLevelDependencies);

which should be changed to:
   var worldbuilder = DependenciesWorld.ToBuilder()
   var topLevelBuilder = TopLevelDependencies.ToBuilder()

This will allow immutable collections to build based on a base collection (shared memory), instead of creating a new dictionary every time, which is the benefit to use the data structure in the first place.  That might be other places in the code, which doesn't use the immutable structure efficiently.

**Comment by davkean** [comment]
@Pilchie Are you going to find them all? Or just fix these ones?

**Comment by Pilchie** [comment]
I was going to look for other places that call `AddRange` immediately after creating a builder.

Note that fixing `wordbuilder` breaks existing tests :(.  I suspect a casing problem, but changing the declaration of `DependenciesWorld` to specify `WithComparers(StringComparer.OrdinalIgnoreCase)` didn't immediately fix it :(

**Comment by abpiskunov** [comment]
Yes, i remember there was some thing related to casing , that's why i had do create new instance at the moment. Let me know if you don't find the reason i could look at it sometime tomorrow (OOF today)

**Comment by Pilchie** [comment]
Found it - the mocks also create a previous snapshot wrong.  PR Coming shortly.

**Comment by abpiskunov** [comment]
Ah good
