### ISSUE TITLE
Minor: unnecessary task chains + JTF in OnDependenciesSnapshotChanged

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#3319]
The code inside this method is mostly unnecessary.  BuildTreeForSnapshotAsync is not an async method (it returns immediately in all code path), so there is no need to chain a task continuation chain.  Also it is strange to wrap the code inside a JTF for the first call, but didn't do for the rest.  The JTF seems to be unnecessary here as well.

**Comment by Pilchie** [comment]
This optimization isn't valid, so closing (see #3326) for details.
