### ISSUE TITLE
Creating a SDK based project (VS2017 csproj format) project with a path containing certain characters results in dependency issues

### ISSUE THREAD

**Issue by DavidArno** [dotnet/project-system#3320]
This issue, for me at least, seems to only occur with VS15.5.n.

Create the path, `C:\Dev\(1)\`, then create a new solution below that. The only requirement to reproduce this bug is to ensure the new VS2017-style csproj format is used for at least one of the projects in the solution, eg:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>dotnet45</TargetFramework>
  </PropertyGroup>
</Project>
```
The content of `<TargetFramework/>` doesn't seem to matter.

This will then result in warnings against all dependencies:
![image](https://user-images.githubusercontent.com/196899/36757811-69a154fe-1c0a-11e8-8137-25633f6762a7.png)

Change the path to eg `C:\Dev\1\...` and the warnings will go away.

I've confirmed so far that using `(`, `)`, or `'` in the path will cause this problem, though other characters may be affected too. The issue also only manifests with SDK based projects. Projects using the old style csproj format do not appear to suffer this problem.

**Comment by Pilchie** [comment]
@jviau - can you comment on the internal bug number in CPS for this?  @DavidArno this should be fixed in 15.6 previews.

**Comment by DavidArno** [comment]
@Pilchie,

Just tried 15.6 Preview 6.0 ... and it works!

If there's one thing I like more than "we'll get right on to fixing that for you", it's "we already fixed that for you. Here you go". 😁

**Comment by Pilchie** [comment]
Well, I can't take credit in this case, as it was the core CPS team, but I'm happy to be the bearer of good news :)
