### ISSUE TITLE
Language service simplification

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3327]
- [ ] Stop passing using displayname as handshake between us and VSHPROPID_ActiveIntellisenseProjectContext

**Comment by Pilchie** [comment]
Note that we could choose to continue to use the same value, but that Roslyn never uses it as a displayname.  Instead, think of it as an immutable project moniker.

Requirements:
1. It must match what's given to `IWorkspaceContextFactory`.
2. It must be immutable over the lifetime of the project.
3. It can't be (only) the project guid or the file-path, as it needs to be unique among all the `IWorkspaceContexts`.
