### ISSUE TITLE
File.cs.cshtml cannot become EmbeddedResource

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#3336]
1. Create a new core Web app
2. in File Explorer find some cshtml page (Error.cshtml and rename it to Error.cs.cshtml.
3. In VS change type of Error.cs.cshtml to EmbeddedResource (notice it will be removed from Content in csproj)
4. Build
5. Open assembly manifest and see - no embedded resources
6. When rename file to Error.cshtml , build, assembly manifest does contain EmbeddedResource.

See this issue opened by customer originally : https://github.com/aspnet/Tooling/issues/1066#issuecomment-369131680

**Comment by davkean** [comment]
This would be a build issue, no?

**Comment by abpiskunov** [comment]
Sounds like that or even could be sdk related, Content item type might somehow interfere with EmbeddedResource.

**Comment by Pilchie** [comment]
@livarcocc @nguerrera @dsplaisted ?

**Comment by nguerrera** [comment]
Could be sdk or msbuild. Feel free to move to sdk for next look.

**Comment by dsplaisted** [comment]
I want to take a look at this, but I suspect it is CPS not understanding how to modify the project to change the item type given the default globs that the project has.

**Comment by abpiskunov** [comment]
we have a vs feedback bug associated with that 574198. Who should i assign to? Who is doing first investigation here?

**Comment by abpiskunov** [comment]
Ok i am assigning the bug to Daniel first. Please route it further if it is not yours.

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#2024
