### ISSUE TITLE
Renaming types when renaming a class doesn't update usages inside XAML, ResX, WCF, DataSource, etc

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3356]
We rename symbols directly via `Microsoft.CodeAnalysis.Renamer.RenameSymbolAsync` but not raising any of the events that legacy project system does, such as notifying IVsHierarchyRefactorNotify/IVsRefactorNotify implementations. We should extract out CodeModel's version in AbstractCodeModelService.RenameSymbol and use that, or just call through code model.

This will break usage in any projects that consume the types that are we're renaming including XAML, ResX, WCF, DataSource, etc. Note while CPS [doesn't yet implement IVsHierarchyRefactorNotify](https://github.com/dotnet/project-system/issues/3357) - legacy does and can break when it consumes types from us.

**Comment by davidwengier** [comment]
@jmarolf This should be fixed by your PR, but #3357 still needs to be done (which you don't need to do)

**Comment by jmarolf** [comment]
@davidwengier 	correct, though I may end up doing this anyways the way these changes are progressing...

**Comment by tmeschter** [comment]
@jmarolf @davidwengier Is there anything more to do here?
