### ISSUE TITLE
Implement IVsHierarchyRefactorNotify to notify XAML, ResX, etc of renames 

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3357]
CPS/we need to implement IVsHierarchyRefactorNotify to notify IVsRefactorNotify usages of renames in the project.

**Comment by davidwengier** [comment]
FileCodeModel.Rename might already do something around this. We need to figure out who uses IVsHierarchyRefactorNotify

**Comment by davidwengier** [comment]
Legacy responds to IVsHierarchyRefactorNotify and calls IVsRefactorNotify here:
http://index/?query=%60IVsHierarchyRefactorNotify&rightProject=VisualStudio(Repo)&file=venus%5Cproject%5Clangproj%5Clanghier.cpp&line=4414

Resource editor (among others) responds to those calls here:
http://index/?query=%60IVsRefactorNotify&rightProject=Microsoft.VisualStudio.Editors&file=ResourceEditor%5CResourceEditorRefactorNotify.vb&line=58

So we need the CPS project node to implement IVsHierarchyRefactorNotify and match the legacy functionality.

**Comment by davidwengier** [comment]
.resx file support is only in Web Site projects for some reason, and uses a different registry format than everything else. Should probably confirm that it works and is a going concern before worrying about it.

.xaml file support seems fine though.

**Comment by davidwengier** [comment]
Internal PR open here: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/176371?_a=overview

**Comment by davidwengier** [comment]
PR completed.

**Comment by davkean** [comment]
Was this 16.1 or 16.2?

**Comment by davidwengier** [comment]
Looks like this will just sneak in to 16.1
