### ISSUE TITLE
Null Reference when CTRL+F5 Roslyn.sln

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#3360]
Dump: `\\mlangfs1\public\frsilb\dumps\ctrlf5_nullref\devenv_ctrlf5_nullref.dmp`
Repro Steps:
1. Open Roslyn.sln
2. Select VisualStudioSetup.Next as the startup project
3. Ctrl+F5

Expected:
VS starts in dev hive
Actual:
"Object reference not set to instance of an object."

**Comment by jmarolf** [comment]
Looking at the exception

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.VisualStudio.ProductionDebug
  StackTrace:
   at Microsoft.VisualStudio.ProductionDebug.DebugProfileLaunchTargetsProvider.SupportsProfile(ILaunchProfile profile) in F:\dd\src\debugger\ProductionDebug\WebProjectExtension\NetStandard\DebugProfileLaunchTargetsProvider.cs:line 81
```

we are throwing from here:
```C#
return profile.CommandName.StartsWith(Resources.DebugExtensionTargetMenuCommand, StringComparison.OrdinalIgnoreCase);
```

It appears that `CommandName` is null:

  | Name | Value | Type
-- | -- | -- | --
◢ | profile | {Microsoft.VisualStudio.ProjectSystem.Debug.LaunchProfile} | Microsoft.VisualStudio.ProjectSystem.Debug.ILaunchProfile {Microsoft.VisualStudio.ProjectSystem.Debug.LaunchProfile}
  | CommandLineArgs | "/rootsuffix $(VSSDKTargetPlatformRegRootSuffix) /log" | string
  | CommandName | null | string
  | DoNotPersist | false | bool
  | EnvironmentVariables | null | System.Collections.Immutable.ImmutableDictionary<string, string>
  | ExecutablePath | "$(DevEnvDir)devenv.exe" | string
  | LaunchBrowser | false | bool
  | LaunchUrl | null | string
  | Name | "Visual Studio Extension" | string
  | OtherSettings | null | System.Collections.Immutable.ImmutableDictionary<string, object>
  | WorkingDirectory | null | string

**Comment by Pilchie** [comment]
@BillHiebert any ideas here? Is there something wrong with Roslyn's launch profile?

**Comment by Pilchie** [comment]
Looks like this is coming from some internal code in ProductionDebugging.  I've sent some mail to see if it's a known issue, if there is a workaround, etc.

**Comment by Pilchie** [comment]
Filled internal bug [578896](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/578896) to track.  Will keep this open for a bit in case it's actually an issue with the data the launch provider is passing down.

**Comment by Pilchie** [comment]
@BillHiebert said in email:

> We should probably skip profiles w/o a commandName with some kind of error to have the customer fix his file.

**Comment by Pilchie** [comment]
This particular instance has been fixed by the Production diagnostics team, but we should probably be better about what we pass in here.

**Comment by Pilchie** [comment]
@BillHiebert looks like we explicitly handle null/empty command [here](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs#L60).  Seems like we should keep that and just update the doc comment to indicate that it may be null?
