### ISSUE TITLE
Font used in project options

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3372]
The latest update has resulted in a small and difficult to read font on the project options page. Please change it back or let us change it somehow.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/211705/font-used-in-project-options.html
VSTS ticketId: 579826_
_These are the original issue comments:_

Andrew Cope on 3/9/2018, 06:41 AM (3 days ago): It appears to only affect .NET Core and .NET Standard projects.
_These are the original issue solutions:_
(no solutions)

**Comment by davkean** [comment]
![image](https://user-images.githubusercontent.com/1103906/37314738-daeddafc-26a9-11e8-9092-1c2fd1beb5f3.png)

**Comment by davkean** [comment]
Dup'ing against https://github.com/dotnet/project-system/issues/646.
