### ISSUE TITLE
xml schemas in projects

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/project-system#3384]
I'm creating a nuget package that will contain an xsd that will be used at build time to validate xml. I include the xsd in the package "build" folder alongside the props/targets files so I can consume it in my custom tasks. This works, no problem. However, I would like that same xsd to be used for intellisense within the Visual Studio xml editor for developers consuming my package. However, Visual Studio doesn't seem to detect the xsd. I've tried adding (linking) the xsd into the project via my targets file, hoping that would be enough for VS to detect it:

```
<ItemGroup>
<None Include="$(MSBuildThisFileDirectory)MySchema.xsd">
<Visible>False</Visible>
</None>
</ItemGroup>
```

Sadly, this doesn't work.

If I add the xsd to my packages "content" folder, it will be copied and included in the project when the package is installed. This works, and then provides intellisense, however I would prefer to keep the xsd out of the consuming project, as I don't expect the consumer to modify it (or even look at it). Additionally, the package "content" doesn't appear to be included in the new "CPS" (SDK="Microsoft.NET.Sdk") style projects, and so cannot provide intellisense for a project of that style. 

This might not  be the correct place to raise this issue. I suspect the xml editor is completely unrelated to the project system, and probably looks for physical files under the project folder, rather than using the project system to locate the schema files.

**Comment by llali** [comment]
@MarkPflug 
xml editor is unrelated to the project system but if the project has a xsd file as content. The xml editor can use that for IntelliSense.
Here's more detail: https://msdn.microsoft.com/en-us/library/ms255816.aspx
