### ISSUE TITLE
We need a temporary opt-out of out of firing up multiple TFM-based configurations

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3385]
On some solutions with large numbers of projects with multiple TFMs, we're running out of memory. For 15.7, we should add a temporary way of opt'ing out of this so that we don't load configs/roslyn projects/design-time builds for everyone of those TFMs and run out of memory.

Build, however, should continue to work.

**Comment by Pilchie** [comment]
Isn't this a dupe of https://github.com/dotnet/project-system/issues/3323?

**Comment by davkean** [comment]
Yeah missed that.
