### ISSUE TITLE
Visual studio 2017 can not stop dotnet.exe

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/project-system#3394]
@SharafiAli commented on [Wed Dec 13 2017](https://github.com/dotnet/core/issues/1159)

# Visual studio 2017 can not stop dotnet.exe

Visual studio is unable to stop dotnet.exe process. 

# General

After migration of 3 dotnet core projects from dotnet core 1 to 2.0, Visual Studio cannot stop dotnet.exe processes after stopping the debugging. The solution contains 3 dotnet core projects (Identity server, Api and Web application). 

Visual studio shows the popup window "**_Stop Debugging in Progress..._**" with the message: "**_Debugging is being stopped but is not yet complete. You can force debugging to stop immediately, but any processes being detached may be terminated instead. this window will automatically close when the debugging has completely stopped._**" but it can not stop the dotnet.exe process.

Even the "End Process" on the Processes-Tab can not terminate the dotnet.exe process, it gives an AccessDenied warning.

Even the command "taskkill /pid ProcessID /f" cannot terminate it. It returns "_**The process with PID ProcessID could not be terminated.**_" Error, with "_**This task is not running currently**_" as reason.

The only possible solution that I have at this moment is restarting my pc, which makes the development impossible.

Does anyone have any idea why this is happening?

---

@richlander commented on [Thu Dec 14 2017](https://github.com/dotnet/core/issues/1159#issuecomment-351923842)

PTAL @Andrew-MSFT 

---

@Andrew-MSFT commented on [Thu Dec 14 2017](https://github.com/dotnet/core/issues/1159#issuecomment-351924641)

Looping in @caslan 

---

@orobert91 commented on [Mon Dec 18 2017](https://github.com/dotnet/core/issues/1159#issuecomment-352541314)

I have vaguely the same problem since upgrading to Visual Studio 2017.5.2. About 1 time out of 3 I have to kill the IIS Worker Process manually. Never experienced this before.

---

@caslan commented on [Mon Dec 18 2017](https://github.com/dotnet/core/issues/1159#issuecomment-352570668)

@WardenGnaw, can you help investigate?

---

@WardenGnaw commented on [Tue Dec 19 2017](https://github.com/dotnet/core/issues/1159#issuecomment-352883262)

@SharafiAli I tried to reproduce this issue with a solution with two web apps and a dotnet console app. I can successfully start, run, and stop the debugging session. All of the dotnet and iisexpress processes are gone. 

Do you have a project that you can share that reproduces this issue?

---

@GeekyMonkey commented on [Mon Feb 19 2018](https://github.com/dotnet/core/issues/1159#issuecomment-366778393)

I'm having this problem with a dotnet core angular spa app from the template.  It happens about half the time. I have to kill the dotnet.exe process to get a compile.

---

@GeekyMonkey commented on [Tue Feb 20 2018](https://github.com/dotnet/core/issues/1159#issuecomment-366909148)

Un-checking this fixed it for me
Tools - Options - Debugging - General - "Enable JavaScript Debugging for ASP.NET (Chrome and IE)"

---

@ramvdixit commented on [Wed Mar 07 2018](https://github.com/dotnet/core/issues/1159#issuecomment-371133198)

Deleting all breakpoints and running in Debug mode fixed it. Unfortunately, nothing else did it for me. I had to again set the breakpoints that I wanted.

**Comment by Pilchie** [comment]
@greggm - any ideas here?

**Comment by WardenGnaw** [comment]
I'm currently investigating this issue. Sadly, I can't recreate the issue and I am still looking for a consistent repro.

**Comment by Pilchie** [comment]
Any updates here?

**Comment by WardenGnaw** [comment]
Still none. I can still terminate dotnet.exe from VS in .net core projects.

**Comment by WardenGnaw** [comment]
@SharafiAli @GeekyMonkey Instead of using VS to stop the process, Can you try killing the `dotnet.exe` process with another tool? You can use something like `taskkill /im dotnet.exe`. Let me know if this actually kills the process. 

Another way to help is to provide a dump for us to investigate this issue: 

You can collect a dump file with the following steps:
1. Start Visual Studio. 
2. Start another instance of VS. 
3. In the second instance click Debug | Attach to Process… 
4. In the list of processes locate msvsmon.exe. 
5. Click Select… and explicitly choose 'Native' and 'Managed(v4.6, v4.5, v4.0)' code. 
6. Click OK and OK to close Select dialog and Attach to Process dialog. 
7. Go back to the first instance of VS and repro the issue. 
8. Go to the second instance of VS and do "Debug->Break All"
9. In the second instance click Debug | Save Dump As… and save the dump. 
10. Attach the dump file to your problem report and send it

Thank you.

**Comment by GeekyMonkey** [comment]
For me the problem comes and goes. I can work half the day doing lots of bulks cycles and it works. Then once it stops working, I have to manually kill the dot net process to enable the build to complete. I set up a Windows hot key that fires a power shell script. It'll stay like this for all subsequent build cycles. If I reboot then I'm back to normal build cycles.

**Comment by Andrew-MSFT** [comment]
@SharafiAli the not stopping of IIS Express is by design.  For ASP.NET Core, no user code is hosted in the process, so stopping and restarting it slows down F5 a bit with no technical benefit (it will exit when you close Visual Studio).  Are you seeing problems associated with it still running?

**Comment by SharafiAli** [comment]
Thanks,
For the moment no.

**Comment by GeekyMonkey** [comment]
What I noticed today was everything was cool until I did an effort core migration on the command line. Then it got into the ugly state after the next build. Could be a coincidence.

**Comment by GeekyMonkey** [comment]
Effort=EF 
Dang autocorrect

**Comment by Pilchie** [comment]
@GeekyMonkey any further leads?  Did the EF correlation continue?

**Comment by Pilchie** [comment]
@livarcocc - see this comment (https://github.com/dotnet/project-system/issues/3394#issuecomment-382008270).  I can't see that being project system.  Can you take the next look?

**Comment by livarcocc** [comment]
I am somewhat confused. Is this related to F5 with debug or EF migration? Each can have their own reasons. If the first, I would loop in or move the issue to EF. If the second, I would somehow suspect the app or a debugger problem, as in that case, there is no SDK in play, VS simply runs the application and attaches the debugger.

**Comment by Pilchie** [comment]
My take is that we have determined that there isn't an issue with debugging - just confusion about the fact that IISExpress continues running, but there is a second issue that *might* be correlated with EF, but we're not sure.

**Comment by SharafiAli** [comment]
I'm having this problem again.

Not just sometimes, but every day after making a change and rebuild. my other colleagues don't have this problem, they've never experienced this problem. 

Could it be related to hardware?

**Comment by ajdotnet** [comment]
Same problem here.

I have a solution with 4 projects. After I start it, each one gets its own iisexpress/.../dotnet process, listed as process tree by "pslist /t":

```
explorer                        9544   8 116 2335 4194303  117740   58480
  devenv                        3700   8  59 2877 1332344  475920  384080
    iisexpress                 14728   8  26  497  192400   21264   11304
      conhost                  14748   8   5  118 4194303    9680    5576
      iisexpresstray           14904   8  30  589  314760   46560   31880
      VSIISExeLauncher         15276   8  12  327  187044   16868   14740
        dotnet                 14992   8  29  484 4194303   50380  100140	!!!
        conhost                15344   8   5  119 4194303    9644    5520
    iisexpress                 14976   8  27  557  194672   22432   11984
      conhost                  14776   8   5  118 4194303    9652    5544
      VSIISExeLauncher         15032   8  19  369  197112   18200   15456
        conhost                 3416   8   5  119 4194303    9648    5540
        dotnet                 15564   8  48  724 4194303  160984  341892	+++
[...]
```

Occasionally VS stops these IISExpress hosts and all child processes with them. However, sooner or later (usually sooner :-[) one of the dotnet processes gets "stranded alive":

```
Name                Pid Pri Thd  Hnd   Priv        CPU Time    Elapsed Time 
dotnet                         14992   8   1  479 4194303   50564  100116	!!!
```

When this happens, the process cannot be killed (despite being admin and having made sure that I have termination permissions).
What's more, when this happens I get a bluescreen (reference by pointer, 0x0..018) during shutdown.

I originally attributed the bluescreen to some issues with Windows 1803, therefore I just set up my laptop from scratch two days ago, i.e. the machine is as clean as can be. The issue remains though.

**Comment by pthorsley** [comment]
Just got this error late yesterday while working, trying to fix it now....so far no success. Will update as I work through trying to fix this issue.

**Comment by pthorsley** [comment]
Running VS 15.5.3 but have another dev running 15.7.1 and not getting the error yet. 
What is everyone running?

**Comment by abpiskunov** [comment]
It feels like it could be on the web side. I will create a TFS bug for us to investigate.

**Comment by SharafiAli** [comment]
I've formated my pc, installed one of the latest build of Windows 10, installed last version of visual studio proffesional 2017, installed all needed updates, get the code througg tfs and rebuild the solution, for copple of days it works fine, then it began again.

**Comment by pthorsley** [comment]
Just updated to 15.7.1 on the same machine and it is still happening....UGH...
Here is debug output:

Unhandled exception at 0x00007FFAD93F3C58 (KernelBase.dll) in dotnet.exe: 0xE0434352 (parameters: 0xFFFFFFFF8007000B, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFA8BC80000).


When it went to debug it completely failed also, here is output.
Kernelbase.pdb not loaded

Module Information
Version: 10.0.14393.1770 (rs1_release.170917-1700)
Original Location:  C:\Windows\System32\KernelBase.dll

**Comment by pthorsley** [comment]
Background on Solution:
1. Project 1: .Net Core Web API
2. Project 2: .Net Core Class Library
3. Project 3: .Net Core Class Library
     This is actually a container for nodejs react web project, the MS 2017 react template sucked big time and some libs are not even supported moving forward anymore, so we are going to nodejs instead of IIS.

We use git for our repository in vsts, works soso, so now we use the command line since VS seems to have issues at times, so not worth it.

I am running project 1 with IISExpress using the Edge browser option, have tried Chrome with same repro.

**Comment by pthorsley** [comment]
WOW.... so then I create another project just to test out VS 2017 and what do you know I am now getting:
"An error occurred trying to load the page. Object reference not set to an instance of an object" when opening the project properties for the Application, Build, and Bild Events sections only.

This is a brand new project, nothing crazy just a simple web .net core 2.0 site. 
Did anyone test just the basics??? this is really bad.
Can open sections Package, Debug, Signing, TypeScript Build, Resources

**Comment by pthorsley** [comment]
Ok, solved it myself...
Seems the .vs\config\applicationhost.config was causing issues.

**Comment by ajdotnet** [comment]
@abpiskunov: I am on the latest VS version (15.7.2) and usually update as soon as a new version becomes generally available. I've had ths issue with one (maybe two) versions before.

**Comment by SharafiAli** [comment]
I've attached some dump files created after the blue screen, may they can help you to find the cause.
[Kernel_18_b8cff6b38957c7bbd5a10cb4c673e6ac432_00000000_cab_03a03076.zip](https://github.com/dotnet/project-system/files/2057391/Kernel_18_b8cff6b38957c7bbd5a10cb4c673e6ac432_00000000_cab_03a03076.zip)

**Comment by rogerfar** [comment]
@davkean 

> We've not seen an update on this bug for a while - I'm going to close it out. If someone is still running into this issue can you please open a new bug with repro steps and actual/expected behavior?

This is still an issue, easy to reproduce.

Create an application with SignalR connected, make sure that the client keeps sending stuff to the server. When you run (debug) and then stop, IIS Express will keep running, but because it is still responding to requests from the client you can't debug your application again. This is because the DLL's in the out directory are still busy and loaded by IIS Express and cannot be overwritten. The only to continue again is to manually stop IIS Express.

```
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4366,5): warning MSB3026: Could not copy "C:\Projects\test.dll" to "bin\Debug\netcoreapp2.2\test.dll". Beginning retry 2 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.2\test.dll' because it is being used by another process. The file is locked by: ".NET Core Host (25368)"
```

**Comment by fpiazza99** [comment]
I see the same thing as @davkean in 2017-15.9.17. In my case i'm running in circles trying to figure out whether or not my latest changes are executing or if the first version of code launched is executing. The other problem is, i'm trying to debug application lifetime stops, but the web server is still running and my code never stops when I stop debugging. I can keep making api calls from the browser, and the code keeps executing. So no application stop. I think we should have an option to stop the web server if we need to. Exiting VS every time is very annoying and breaks the developer experience/continuity.

**Comment by jamesyolk** [comment]
> @davkean
> 
> > We've not seen an update on this bug for a while - I'm going to close it out. If someone is still running into this issue can you please open a new bug with repro steps and actual/expected behavior?
> 
> This is still an issue, easy to reproduce.
> 
> Create an application with SignalR connected, make sure that the client keeps sending stuff to the server. When you run (debug) and then stop, IIS Express will keep running, but because it is still responding to requests from the client you can't debug your application again. This is because the DLL's in the out directory are still busy and loaded by IIS Express and cannot be overwritten. The only way to continue again is to manually stop IIS Express.
> 
> ```
> 3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4366,5): warning MSB3026: Could not copy "C:\Projects\test.dll" to "bin\Debug\netcoreapp2.2\test.dll". Beginning retry 2 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp2.2\test.dll' because it is being used by another process. The file is locked by: ".NET Core Host (25368)"
> ```



> I see the same thing as @davkean in 2017-15.9.17. In my case i'm running in circles trying to figure out whether or not my latest changes are executing or if the first version of code launched is executing. The other problem is, i'm trying to debug application lifetime stops, but the web server is still running and my code never stops when I stop debugging. I can keep making api calls from the browser, and the code keeps executing. So no application stop. I think we should have an option to stop the web server if we need to. Exiting VS every time is very annoying and breaks the developer experience/continuity.

Our solution has SignalR related code as well, and I'm experiencing the same thing here even in the latest VS2022, not sure why killing debug can't stop the whole app.

**Comment by drewnoakes** [comment]
@jamesyolk can you please use the "Report a problem" feature in VS and include a recording of the problem occurring. Make sure you mention that you're using SignalR. We can more easily route feedback tickets across teams than GitHub issues. I believe the debugger team should look at this, and they are not on GitHub.
