### ISSUE TITLE
error on .net core projects not opening and creating

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/project-system#3398]
@umarsolehri commented on [Sat Mar 17 2018](https://github.com/dotnet/core/issues/1359)

issue comes on while opening or creating .net core project . this issue comes after latest updates
please take a look at attached files

[VsProjectFault_80e7eb42-21c5-41e8-abb9-19a13ef89c38.failure.txt](https://github.com/dotnet/core/files/1822073/VsProjectFault_80e7eb42-21c5-41e8-abb9-19a13ef89c38.failure.txt)

---

@umarsolehri commented on [Sat Mar 17 2018](https://github.com/dotnet/core/issues/1359#issuecomment-373952052)

[VsProjectFault_4bff3231-b012-4fc1-b936-76b13034f267.failure.txt](https://github.com/dotnet/core/files/1822078/VsProjectFault_4bff3231-b012-4fc1-b936-76b13034f267.failure.txt)
[VsProjectFault_8bf73e3f-2c04-4e53-bf70-6e7554b2bc83.failure.txt](https://github.com/dotnet/core/files/1822079/VsProjectFault_8bf73e3f-2c04-4e53-bf70-6e7554b2bc83.failure.txt)
[VsProjectFault_8e04af0c-8349-4ec2-b671-de05c02e6dd6.failure.txt](https://github.com/dotnet/core/files/1822080/VsProjectFault_8e04af0c-8349-4ec2-b671-de05c02e6dd6.failure.txt)
[VsProjectFault_28deb9fa-7b99-44eb-92e8-dc13222194ad.failure.txt](https://github.com/dotnet/core/files/1822081/VsProjectFault_28deb9fa-7b99-44eb-92e8-dc13222194ad.failure.txt)
[VsProjectFault_80e7eb42-21c5-41e8-abb9-19a13ef89c38.failure.txt](https://github.com/dotnet/core/files/1822082/VsProjectFault_80e7eb42-21c5-41e8-abb9-19a13ef89c38.failure.txt)
[VsProjectFault_2779d11f-0df7-431c-8457-2375f9e39b02.failure.txt](https://github.com/dotnet/core/files/1822083/VsProjectFault_2779d11f-0df7-431c-8457-2375f9e39b02.failure.txt)
[VsProjectFault_8724be7f-9f17-41f3-970c-9f606b0c3f83.failure.txt](https://github.com/dotnet/core/files/1822084/VsProjectFault_8724be7f-9f17-41f3-970c-9f606b0c3f83.failure.txt)
[VsProjectFault_8957c0ad-5189-4f14-9a06-c29e472e95d1.failure.txt](https://github.com/dotnet/core/files/1822085/VsProjectFault_8957c0ad-5189-4f14-9a06-c29e472e95d1.failure.txt)
[VsProjectFault_ab59b504-6c20-4636-ad79-608840c1c310.failure.txt](https://github.com/dotnet/core/files/1822086/VsProjectFault_ab59b504-6c20-4636-ad79-608840c1c310.failure.txt)
[VsProjectFault_afc05dff-5957-4aa6-89e0-5db14361fa56.failure.txt](https://github.com/dotnet/core/files/1822087/VsProjectFault_afc05dff-5957-4aa6-89e0-5db14361fa56.failure.txt)
[VsProjectFault_bf2bb93c-d970-4950-9a6e-4c9c42a2049b.failure.txt](https://github.com/dotnet/core/files/1822088/VsProjectFault_bf2bb93c-d970-4950-9a6e-4c9c42a2049b.failure.txt)

**Comment by umarsolehri** [comment]
so what is the solution of this isssue

**Comment by umarsolehri** [comment]
any solution ????

**Comment by Pilchie** [comment]
This appears to be a setup issue.  Tagging @Lifengl too.

@umarsolehri Can you try starting a Developer command prompt and running `devenv /updateconfiguration`?  If that doesn't work, I would suggest trying a repair operation on VS.

**Comment by umarsolehri** [comment]
@Pilchie i already repaired vs 2-3 times
tell me how to start a Developer command prompt and run devenv /updateconfiguration

**Comment by umarsolehri** [comment]
@Pilchie  already repaired visual studio and also run command as you mentioned but still error comes file attached after all these suggestions you mentioned 
[VsProjectFault_399f217c-776b-4442-8385-ba2b762c73c3.failure.txt](https://github.com/dotnet/project-system/files/1823122/VsProjectFault_399f217c-776b-4442-8385-ba2b762c73c3.failure.txt)

**Comment by davkean** [comment]
@umarsolehri Can you please:

1. Download and run http://aka.ms/vscollect
2. Help -> Send Feedback -> Report a Problem reporting the issue
3. Attach %TEMP%\vslogs.zip

Thanks. This should give us enough information to help figure this out.

**Comment by davkean** [comment]
Can you sent me a link to the feedback item you reported?

**Comment by umarsolehri** [comment]
https://developercommunity.visualstudio.com/content/problem/218144/error-while-creating-new-and-openinng-previous-pro.html?childToView=218155#comment-218155

**Comment by davkean** [comment]
Closing this lieu of the feedback item.
