### ISSUE TITLE
Implement VSHPROPID_PreferredLanguageSID

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3406]
We're currently returning DISP_E_MEMBERNOTFOUND for VSHPROPID_PreferredLanguageSID which is resulting in some extension code failing when run against CPS. We should implement this.

**Comment by davkean** [comment]
Almost all usage internally looks like they are just using to sniff project language, so we should just implement this.

**Comment by Pilchie** [comment]
See also #2876

**Comment by davkean** [comment]
Ah, forgot about this - just going to dup this against it.
