### ISSUE TITLE
"Assets file '...' doesn't have a target for '.NETCoreApp,Version=v2.0'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project." after upgrading to VS 15.6.3

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/project-system#3409]
Since updating VS 15.6.2 to 15.6.3 I started receiving the following error after modifying a source file and rebuilding the solution:

```
12>C:\Program Files\dotnet\sdk\2.1.102\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file 'C:\W ork\engine\engine\Loop54.Webserver\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project.
12>Done building project "Loop54.Webserver.csproj" -- FAILED.
12>C:\Program Files\dotnet\sdk\2.1.102\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file 'C:\W ork\engine\engine\FSharpModules\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project.
12>Done building project "FSharpModules.fsproj" -- FAILED.
```

That is, the solution initially builds successfully, but if I a change a C# source file and try to build it again the error occurs (every time). If I clean the solution it then builds successfully again.

It doesn't complain about the project I modified, but about 2 of its (indirect dependencies). I also tried modifying other projects and got the same error about some other projects that those depend on, e.g.

```
7>------ Build started: Project: CSharpSpellmasters, Configuration: Debug Any CPU ------
7>C:\Program Files\dotnet\sdk\2.1.102\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file 'C:\W ork\engine\engine\Loop54.Engine.Core\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project.
7>Done building project "Loop54.Engine.Core.csproj" -- FAILED.
```

I've verified that project.assets.json does have a target for '.NETCoreApp,Version=v2.0' and also its contents are the same as after a clean (when the build succeeds). I don't have a duplicate ProjectReference as far as I can see or anything else weird. I tried going back to an earlier revision of the code and it still happened there.

The only recent change was upgrading to 15.6.3. I re-installed VS 15.5.7 (which was a huge waste of time!) based on https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017 and the problem disappeared.

Is there a way I can upgrade to 15.6.2, at least? (15.5.7 has another problem I ran into, that was fixed in 15.6.) Can I install an "experimental" version of VS in parallel with my main (stable) one? This waste of time due to what is probably a simple bug is an AWFUL user experience. With almost any other software I'd be able to simply go back to the old version in a few minutes.

**Comment by omega1970** [comment]
Same issue after upgrading to 15.6.3. Using 'dotnet build' in package manager console solves the problem temporary, but any code change to a multi-target framework project requires me to do another dotnet build.

**Comment by loop-evgeny** [comment]
Mine isn't even multi-target, I have `<TargetFramework>netcoreapp2.0</TargetFramework>` for all projects.

**Comment by davkean** [comment]
Sorry for the late reply, see: https://github.com/dotnet/sdk/issues/2068.

**Comment by loop-evgeny** [comment]
Thanks, but is the same issue known to occur without multi-target projects (my case)?

**Comment by davkean** [comment]
It's unrelated to multi-targeting, do you have R# installed?

**Comment by loop-evgeny** [comment]
OK, good. Yes, I have R# 2017.3.3. (I hadn't tested disabling it, since I didn't think it was involved in the build.)

Can I install 2 different minor versions of VS side-by-side to test this? So when 15.6.4 is released (which presumably will fix this), can I install it without affecting my working 15.5.7 installation? If so, how?

**Comment by davkean** [comment]
The linked bug has a workaround, uninstall the SDK if you'd like to keep R# enabled. 

TBH I don't know a public way to install 15.5 and 15.6 on the same machine (we support it internally, but there's no public links for 15.5), @Pilchie is there a way?

**Comment by loop-evgeny** [comment]
Or 15.6.2 and 15.6.4?

Is there even a way to update my 15.5.7 to 15.6.2? Why does MS make it _so_ hard to install the version I want? At the very least you could keep around links to the installers for each version - I'm sure they still exist on the MS download servers, but the links are gone.

**Comment by Pilchie** [comment]
This page is the only information I know about it: https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017

**Comment by loop-evgeny** [comment]
So what am I supposed to do? Stay on 15.5.7 forever (with its own bugs) or risk wasting 5-6 hours of my time whenever there is a new release?

**Comment by Pilchie** [comment]
This issue was fixed in 15.6.4 which was released on Friday, as indicated in the primary issue.

**Comment by loop-evgeny** [comment]
Yes, I saw that, but as with any new release there is a risk it will badly break VS in some way. 15.6.3 wasn't the first version to do so and won't be the last. The options I currently see are:

* Never upgrade from a version that (more or less) works.
* Upgrade to every new release and risk wasting 5-6 hours if it breaks
* Spend some time testing a new release of VS on a dedicated machine (possibly virtual) before I upgrade my real dev machine to it

None of these are good options. Here are some better options available for most other software, but not for VS:

* Easily re-install an earlier version that was known to work in a reasonable amount of time
* Install two versions side by side
* Upgrade to a later version that is not the latest (e.g. 15.5.7->15.6.2). This would allow me to upgrade to versions that have actually been tested properly.

**Comment by davkean** [comment]
@loop-evgeny We let you install an RTM and Preview side-by-side. We don't let you install individual updates of a single version side-by-side. I'll pass your feedback on the setup team.

This particular bug was due to an extension, and they have released a complete fix: https://blog.jetbrains.com/dotnet/2018/03/23/build-failures-visual-studio-15-6-3-resharper-ultimate-2017-3-5-rescue/.

**Comment by davkean** [comment]
Someone just pointed out to me that it's possible to side-by-side updates externally by falling back to the command-line and specifying different installation folders for each install: https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples.

**Comment by loop-evgeny** [comment]
So I basically just run `vs_enterprise.exe --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017-extra"` ?

**Comment by loop-evgeny** [comment]
I tried it, seems to work so far. I have 15.5.7 and 15.6.6 installed.

**Comment by mwpowellhtx** [comment]
So... I wanted to follow up. I ended up pulling my ``C:\Program Files\dotnet\sdk`` folders aside, both ``2.1.200`` and ``2.1.201``, and the programmatic invocation succeeded. From there I should be able to verify before and after states that I expect with my custom MSBuild tasks.
