### ISSUE TITLE
How to create a .net framework class library in new .csproj formate？

### ISSUE THREAD

**Issue by Varorbc** [dotnet/project-system#3410]
How to create a .net framework class library in new .csproj formate？

**Comment by davkean** [comment]
Bear in mind that certain features (such as WPF/WinForms designer) do not currently work when using the new format/project-system.

To target .NET Framework, you can simply change TargetFramework. For example, to target .NET Framework 4.6.1:

``` XML
<Project>
    <PropertyGroup>
        <TargetFramework>net461</TargetFramework>
    </PropertyGroup>
</Project>
```

**Comment by Varorbc** [comment]
why classLibrary project template don't use new .csproj formate in vs2017?

**Comment by davkean** [comment]
The new format requires project-system changes, the new project system doesn't yet have all the features to replace the legacy project system, and the legacy project system doesn't have the features to adopt the new format.

This will be resolved in future versions.

**Comment by Varorbc** [comment]
Is there a schedule? @davkean

**Comment by davkean** [comment]
We have a roadmap: https://github.com/dotnet/project-system/blob/master/docs/repo/roadmap.md but no dates.

**Comment by Varorbc** [comment]
thank you very much
