### ISSUE TITLE
In recent builds, files are opening in Misc IntelliSense before switching to project-IntelliSense

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3414]
1. Open ProjectSystem.sln
2. Open src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\Configuration\BaseProjectConfigurationDimensionProvider.cs
3. Close the solution
4. Reopen the solution

![documents](https://user-images.githubusercontent.com/1103906/37745399-a63b2186-2dc8-11e8-9c17-dd120d08e99d.gif)

**Comment by Pilchie** [comment]
The fix in #3447 was inserted for 15.7 Preview 6.
