### ISSUE TITLE
Console apps should offer "Manage User Secrets" context menu

### ISSUE THREAD

**Issue by AndrewBrianHall** [dotnet/project-system#3420]
.NET Core console apps will load values from usersecrets.json, so we should offer the "Manage User Secrets" context menu item on the project just like ASP.NET Core projects

**Comment by davkean** [comment]
This would a web feature, no?

**Comment by Andrew-MSFT** [comment]
We already supports it, I filed this ticket in response to a customer asking why we didn't show it for Console apps because it works for console apps.  He is currently working around it, but it's reasonable to ask that it be there if it's supported

**Comment by davkean** [comment]
As in - whomever owns this feature needs to opt into our project type.

**Comment by Andrew-MSFT** [comment]
Ah, that would be @BillHiebert

**Comment by abpiskunov** [comment]
@davkean  it should be in reverse order actually: we could make feature independent on project system and be tied to capability and core project system should add capability to their targets.

**Comment by davkean** [comment]
This work is blocked on Web making this feature project-system independent. Is that work schedule for 15.8 @abpiskunov or @BillHiebert, if not let's move this out of 15.8.

**Comment by whoiskevinrich** [comment]
Any updates on this? Our team could really use this feature.

**Comment by Worthy7** [comment]
Any update guys? I just discovered this and it's a pain.

**Comment by BillHiebert** [comment]
This will light up in 16.1 by adding a package reference to Microsoft.Extensions.Configuration.UserSecrets. Note that it requires the Web workload to be installed in VS.

**Comment by davkean** [comment]
This has been done.
