### ISSUE TITLE
MetadataReferenceHandler is allocating a lot trying to root the reference 

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3432]
Large solution, UI delays due to GCs:

![image](https://user-images.githubusercontent.com/1103906/38121437-de191d44-341a-11e8-8b41-00accefc78d7.png)

**Comment by davkean** [comment]
An approach might be to grab PathHelper.IsRooted/IsPathFullyQualified and check before rooting, however, note we expect normalization of the references to avoid duplicates - so we should figure out what Roslyn does when we the same reference but not normalized to look at the same.

**Comment by davkean** [comment]
Triage: Make sure that any usage of IsRooted we use does not also allocate under the covers.

**Comment by jjmew** [comment]
@davkean is this something that we can assign to someone else? (Moving to 16.7 since it is unlikely that this will be done in 16.6)

**Comment by drewnoakes** [comment]
https://dev.azure.com/devdiv/DevDiv/_git/CPS/pullrequest/252631 reduces allocations in `PathHelper.NormalizePathSeparators`, which `MakeRooted` calls twice.

**Comment by panopticoncentral** [comment]
Closing this as CPS replaced their use of the Uri helper a while ago.
