### ISSUE TITLE
Set templates for new projects to use determinism

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#3438]
I created a new desktop project and it does not have the determinism option turned on.
In contrast, .NET Core projects have [determinism turned on](https://github.com/dotnet/roslyn/issues/372#issuecomment-377711471) by default (in the targets).

`<Deterministic>true</Deterministic>`

Tagging @davkean I wasn't sure if this is the proper repo to file this issue. Is this where templates are maintained?

**Comment by jmarolf** [comment]
The templates for the .NET Framework aren't open source (yet) but I can add the `<Deterministic>true</Deterministic>` property to them.

**Comment by jcouv** [comment]
That works. Thanks!
@gafter @jaredpar FYI, we'll turn on determinism in remaining project templates (ie. desktop one).

**Comment by jcouv** [comment]
@jmarolf Could you also check if the templates use `AssemblyVersionAttribute` with a wilcard (`*` format)? If they do, we'd need to remove them to enable determinism.

**Comment by jmarolf** [comment]
@jcouv right, I'll include you on the PR

**Comment by jmarolf** [comment]
PR is merged
