### ISSUE TITLE
PDB and PROPS file extension type have Russian language description on English-US locale setting

### ISSUE THREAD

**Issue by eriawan** [dotnet/project-system#3440]
## Current Configuration

Current machine configuration:

- Windows 10 1709 16299.309
- VS 2017: 15.6.4 Enterprise
- Language and locale settings used: English US

## Problem

When opening Windows Explorer, the file extension remark/information under "Type" column is showing Russian language for PDB and PROPS files.

Screenshot: (PDB files)

![image](https://user-images.githubusercontent.com/8773147/38186703-69a10f10-367e-11e8-9dc0-a5cd671b4a96.png)

and for PROPS files:

![image](https://user-images.githubusercontent.com/8773147/38186650-2bc7468c-367e-11e8-8722-635a47a58e05.png)
Is this a bug? Looks like there's a problem on registering file types, and it uses Russian languages instead of respecting Windows display language/locale setting, CMIIW.

cc @davkean , @jmarolf  @Pilchie

**Comment by Pilchie** [comment]
The windows shell registrations are a "last installed wins" issue, so if you installed the Russian language pack, you'll get to the Russian ones until you either:
1. Install another language pack.
2. Run a repair on VS with English selected.
