### ISSUE TITLE
Add CI leg for non ENU Windows

### ISSUE THREAD

**Issue by ghuntley** [dotnet/project-system#3441]
See https://twitter.com/jaredpar/status/980903378711490560 for full context. Currently, project-system is green when built on non-ENU windows thus this is a defensive move to prevent regressions.

Related:
* https://github.com/dotnet/corefx/issues/28729
* https://github.com/dotnet/roslyn/pull/25874

**Comment by Pilchie** [comment]
Hey @jaredpar - do you want to do this for us? 😛

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/project-system/pull/4095
