### ISSUE TITLE
Double-clicking Form in Solution Explorer doesn't open designer

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3442]
1.

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>

```

2. File -> Add New Item -> Windows Forms and click OK with default name
3. Double-click on the new Form1.cs

Expected: Designer to open
Actual: Designer does not open

**Comment by Styxxy** [comment]
The icons of forms, controls etc don't show either (compared to the legacy project format).

**Comment by davkean** [comment]
@Styxxy We've fixed the icons.

This bug requires changes to CPS.

**Comment by davkean** [comment]
Microsofties, this is being fixed by: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/134764?_a=overview.

**Comment by davkean** [comment]
This has been fixed.
