### ISSUE TITLE
FastUpdateCheck: how to add inputs implicitly added by an imported targets file 

### ISSUE THREAD

**Issue by gfraiteur** [dotnet/project-system#3444]
The result of our tool (PostSharp) depends on one or many files named `postsharp.config` and located in any parent directory of the csproj. When the user modifies any `postsharp.config`, we want VS to rebuild the project. We use `CustomAdditionalCompileInputs` to allow for incremental rebuild in MSBuild, which works when MSBuild is executed from the command line but fails to cause Visual Studio to rebuild the project.

Under the hood, we create a dependency text file, one line per input file, during the build. At the beginning of a build, during a BeforeBuild target, we load the file created during the previous build. It would be nice to be able to reuse this file.

**Comment by davkean** [comment]
`UpToDateCheckInput` item is respected by both project systems.

@panopticoncentral Are we factoring in CustomAdditionalCompileInputs?

**Comment by davkean** [comment]
Thinking about it, why do you want to have the compiler rebuild the dll when postsharp.config changes? Don't you just run on the result?

**Comment by gfraiteur** [comment]
My problem with `UpToDateCheckInput` (I did not test but I assume this works this way) is that I assume it needs to be defined declaratively, but here we should (ideally) be able to define it programmatically, by reading our dependency file. (The reason is that a `postsharp.config` could in theory have a reference to another configuration file that could not be discovered "declaratively" by naming and directory convention.)

Files like `postsharp.config` contain build-time configuration settings. For instance, when you add logging to a namespace, you can define in `postsharp.config` that you also want to measure the execution time, which then influences the MSIL code generation pattern.

**Comment by davkean** [comment]
UpToDateCheckInput is evaluation-only, we don't respect any produced during targets.  However, looks like we do run `CollectBuiltDesignTime` target in CPS to produce dynamic items that supplement the up-to-date: https://github.com/dotnet/project-system/issues/3157.

I'm doubtful this works in legacy @panopticoncentral?

Why do you affect CustomAdditionalCompileInputs? Why does changing postsharp.config cause the compiler to generate different code?

**Comment by davkean** [comment]
Here's example: http://source.roslyn.io/#MSBuildFiles/C/ProgramFiles(x86)/MicrosoftVisualStudio/2017/Enterprise/MSBuild/Microsoft/VisualStudio/Managed/Microsoft.Managed.DesignTime.targets,302.

**Comment by gfraiteur** [comment]
Thank you. I tried to "hook" into `CollectBuiltDesignTime` with `BeforeTargets` but I didn't manage to get it working. 

`postsharp.config` does not cause the compiler to produce different outputs, only the PostSharp post-compilation step is affected. I believe we define `CustomAdditionalCompileInputs` because "it worked". Looking at it today, I see it's maybe suboptimal and that we could instead add inputs to our own target, not to the compiler dependencies.

**Comment by davkean** [comment]
What project type? This will only work in .NET Core/.NET Standard projects and 15.6 - I don't think this is hooked up to legacy project system, @panopticoncentral would need to confirm.

**Comment by davkean** [comment]
And you are adding to 'UpToDateCheckBuilt'?

**Comment by gfraiteur** [comment]
I was testing with a .NET Core 2.0 project. But we need to support VS 2012 too, in theory, but it isn't too important if the experience is "degraded".

I was adding to UpToDateCheckInput and I don't see how it could work with UpToDateCheckBuilt since I understand the UpToDateCheckBuilt is for an output artefact.

**Comment by davkean** [comment]
If I understand, you mark Original metadata as the config.

**Comment by gfraiteur** [comment]
I found the reason why we add to `CustomAdditionalCompileInputs`: we must run the C# compiler again because we override its output. We would need additional build logic to re-use the last compiler output (which we save) when the compiler does not run, but currently we don't have that logic,

**Comment by panopticoncentral** [comment]
No, neither the .NET Framework or .NET Core/Standard project systems look at `CustomAdditionalCompileInputs` for the up to date check. Am I understanding correctly that you have a target that runs before compile that adds the files you want to that? You could probably repurpose `UpToDateCheckBuilt` for .NET Core/Standard, although as you note it wasn't really what it was intended for.

There isn't really something for your scenario at the moment. I assume you're looking for something that works for both .NET Framework and .NET Core/Standard?

**Comment by gfraiteur** [comment]
I haven't been successful in extending `CollectBuiltDesignTime`.

I am extending `CustomAdditionalCompileInputs` before `CoreCompile` (by extending `CoreCompileDependsOn`). However the items appended to  `CustomAdditionalCompileInputs` are read from a file generated during the previous build.

For me it would work best if the build systems supported an item named say `UpToDateCheckInputFile` that would point to a file where each line points to an input. This file would be generated by tools (including PostSharp) during the previous build.

Obviously, while it is incorrect to assume that the inputs of the previous build are equal to the inputs of the current build, it is correct that any change in the inputs of the previous build must trigger a rebuild. So the strategy of storing the dependencies of the previous build seems a both reliable and extensible.

Does it make sense to file a feature request for this?

For now I will add well-known inputs to `UpToDateCheckInput`. Thank you for your support on this matter.

**Comment by panopticoncentral** [comment]
@gfraiteur I think I've fixed this with #3486, as we now will look at `CustomAdditionalCompileInputs` for the up to date check.

**Comment by gfraiteur** [comment]
Thank you.

**Comment by drewnoakes** [comment]
@gfraiteur in #5234 we are reverting the change that caused the up-to-date check to consider `CustomAdditionalCompileInputs` as it caused the problem described in #4736. 

The correct approach is to add your custom input items to `UpToDateCheckInput`.

Note that if you need to hook into this programmatically at build time then you may override the `CollectUpToDateCheckInputDesignTime` target and add your additional items there.
