### ISSUE TITLE
Configuration vs ConfigurationName build parameter

### ISSUE THREAD

**Issue by groogiam** [dotnet/project-system#3452]
There appears to be a discrepancy between specifying the configuration from msbuild from the command line between the old and new csproj formats.

The old csproj file allowed specifying the configuration using /p:configuration="Test"

e.g. `msbuild MySln.sln /p:configuration="Test"`

This would properly set the ConfigurationName parameter for pre build events.

Note: ConfigurationName is what visual macro dialog uses as well.
![image](https://user-images.githubusercontent.com/1992395/38392710-7c4f1c40-38f6-11e8-80d0-a9deeb63dbe0.png)

This however does not happen for the new csproj format. In order to fix this I have to specify another command line argument `/p:configurationName="Test"`.

It seems like the setting configuration from msbuild should set this variable correctly no matter which csproj format is used.

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#2115
