### ISSUE TITLE
Suppress warning failed with the .csproj file opened.

### ISSUE THREAD

**Issue by Xiu-Li** [dotnet/project-system#3454]
## **Repro Steps:**
1. Using VS create a new .net core console app, build and run succeeded.
2. Add a line code " `int a = 6;` " inside the main method to produce a warning `CS0219`.
3. Open the .csproj file of the project. (Note: The key step, will effect the results.)
4. Open the project properties page, select "**Build**" tab.
5. Under "**Errors and warnings**" section, add `CS0219` to "**Suppress warning**" box and save.

**Expected Results:**
Save succeeded and the warning `CS0219` in the "Error List" disappear.
**Actual Results:**
Save failed, the warning can't disappear.

## **Test Environment:**
**VS build**: D15.7/27604.00 (15.7 Preview 3)
**dotnet --info:**
```
.NET Command Line Tools (2.1.200-preview-007517)

Product Information:
 Version:            2.1.200-preview-007517
 Commit SHA-1 hash:  dc62e50c3a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200-preview-007517\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

```

**Comment by Pilchie** [comment]
@jviau - could this be related to the new .csproj editing that doesn't use the temp file?

**Comment by jviau** [comment]
Yeah it appears there is some weird interactions between the app designer and project editor both being opened at the same time.

**Comment by Pilchie** [comment]
I created internal VSTS bug [597760](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597760) to track this.
