### ISSUE TITLE
Add package information in Visual Studio for non-SDK projects

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/project-system#3458]
On SDK projects, I can see, under Dependencies->NuGet, the referenced packages with their version and the assemblies added to the project from that package.

On non-SDK projects, I can only see the package name under References and can't see the package version and it's assemblies.

It would also be nice to see assembly information of the assemblies added by the packages.

**Comment by Pilchie** [comment]
Related (at least to the the title) to https://github.com/dotnet/project-system/issues/2129.

**Comment by tmeschter** [comment]
The most likely outcome here is that we'll add the version, but not the assemblies.

**Comment by tmeschter** [comment]
Tom's triage notes: I recommend we close this without fixing it.

**Comment by tmeschter** [comment]
We have decided to _not_ implement this feature request. Closing.
