### ISSUE TITLE
Clearer error then "The project configuration Debug|AnyCPU was not found in the project manifest."

### ISSUE THREAD

**Issue by monty241** [dotnet/project-system#3462]
Due to intermittent issues with new Visual Studio releases, this error comes and goes. Ultimately Visual Studio 2017 will probably become a reliable product, but for now it would help in analyzing and resolving issues when the following change could be made:

Original text:
The project configuration Debug|AnyCPU was not found in the project manifest.

New error text:
The project configuration Debug|AnyCPU was not found in the project manifest 'FILENAME'.

Workaround is to remove projects from the solution and then start re-adding them.

**Comment by Pilchie** [comment]
Hi @monty241 can you elaborate on what type of projects you are working with when you see this error?

**Comment by Pilchie** [comment]
@davkean - is this related to https://github.com/dotnet/project-system/blob/master/docs/configurations.md, and opening classic projects with CPS?  Sounds a lot like https://github.com/dotnet/project-system/issues/2454?

**Comment by davkean** [comment]
Yes this is a dupe of https://github.com/dotnet/project-system/issues/2454.
