### ISSUE TITLE
Pass MSBuildProjectExtensionsPath instead of BaseIntermediateOutputPath as part of NuGet restore nomination

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/project-system#3466]
Context:

- https://github.com/NuGet/NuGet.Client/pull/2131
- https://github.com/Microsoft/msbuild/issues/1603

Basically, NuGet was writing restore output to `BaseIntermediateOutputPath`, but the .props and .targets were being imported from `MSBuildProjectExtensionsPath`, so if you overrode one but not the other (commonly because you set `BaseIntermediateOutputPath` after the Microsoft common .props were evaluated), the .props written by restore wouldn't be imported.

We've now normalized this in MSBuild and NuGet to use `MSBuildProjectExtensionsPath`.  However, in some cases the path is passed to NuGet from the project system.  So those cases need to be updated to pass `MSBuildProjectExtensionsPath`.

Note that `IVsProjectRestoreInfo` has a `BaseIntermediatePath` property.  In order to avoid breaking the interface, we didn't change the name, but the project system should now set that value to the `MSBuildProjectExtensionsPath` from MSBuild.

[NuGetRestore.xaml](https://github.com/dotnet/project-system/blob/3c760034e97c2551a8ff98fe01e46830d34b4213/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml#L45-L47) may also need to be updated, I'm not sure exactly how that works.

@Pilchie I've optimistically set the milestone for this to 15.7.

**Comment by Pilchie** [comment]
Quick question here - is it safe to *always* pass `MSBuildProjectExtensionsPath`, or do we need to do some detection to know when it's okay to send it?
