### ISSUE TITLE
Project NavBar not working for Shared Projects in 15.7

### ISSUE THREAD

**Issue by amcasey** [dotnet/project-system#3467]
Create a solution containing a shared project and two class libraries that reference it.  Give each class library a distinct conditional compilation symbol and reference both in `#if`s in the shared project.  (Or open the attached repro solution.)

Expected: In the shared project, selecting a class library in the navbar activates the corresponding `#if`.
Actual: `#if` activation does not change and moving focus back to the text area causes the navbar to revert.

Note: this works correctly in 15.6.1.

Note: This works correctly with linked files - there's a branch here: https://github.com/dotnet/roslyn/blob/ef41d39c55a63d9464cc4eb5344be4d8df6408d8/src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs#L924

[SharedProject1.zip](https://github.com/dotnet/project-system/files/1916441/SharedProject1.zip)

**Comment by Pilchie** [comment]
@jasonmalinowski given @amcasey's comment that this worked in 15.6.1, could you have regressed something here with your changes to AbstractProject stuff?

**Comment by davkean** [comment]
@Pilchie Could this be https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597771?

**Comment by davkean** [comment]
@amcasey What build is this in 15.7?

**Comment by davkean** [comment]
Oh I see @jasonmalinowski has already fixed this, nevermind.

**Comment by Pilchie** [comment]
This fix was inserted for 15.7 Preview 5.
