### ISSUE TITLE
View in Object browser does not work Nuget Packages

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/project-system#3473]
_From @vsfeedback on April 12, 2018 21:56_

There are couple issues regarding dependencies brought by Nuget packages and &quot;View in Object Browser&quot; command in .Net core projects

1) I can right click on a nuget package dependency and choose View in Object browser but nothing happens. (Object browser window doesn't even come up)

2) When I expand nuget reference and right click on a reference dll, there is no object browser command.

The only way is to open object browser manually and navigate to type I want to check.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/230689/view-in-object-browser-does-not-work-nuget-package.html
VSTS ticketId: 597301_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

_Copied from original issue: NuGet/Home#6820_

**Comment by rohit21agrawal** [comment]
_From @nkolev92 on April 13, 2018 18:44_

@mishra14 This is probably more fitting for project-system.

**Comment by davkean** [comment]
Dupe of https://github.com/dotnet/project-system/issues/1256.
