### ISSUE TITLE
Move all XAML files from MSBuild folder and organize them

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#348]
- [x] Move XAML files into language specific folders (#776)
- [ ] Refactor XAML files to derive from other as appropriate.
- [x] Move remaining XAML files from MSBuild

**Comment by srivatsn** [comment]
Tagging @nguerrera - The XAML rules that we have today [here](https://github.com/dotnet/roslyn-project-system/tree/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules) need to be localized as well. The rules need to go into local-specific folders like the ones in C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin

**Comment by srivatsn** [comment]
Filed a separate issue to track the localization - #776.

**Comment by davkean** [comment]
Going to close this out, this has been mostly done with bugs tracking the rest.
