### ISSUE TITLE
Resource Editor "Add Existing File..." default path is not intuitive

### ISSUE THREAD

**Issue by Giftednewt** [dotnet/project-system#3492]
## Problem Description
When I open the Resource Editor in VS for the first time and select "Add Existing File..." the default path in the file dialog is set as per the below image:

![image](https://user-images.githubusercontent.com/7267084/39328799-5bada5ca-4994-11e8-87af-163e42b962bc.png)

I navigate to my project directory, select the files that I want and click "Open" this adds the files to my .resx as expected. If I leave the Resource Editor tab open and select "Add Existing File..." again it correctly remembers the path that I last navigated to.

![image](https://user-images.githubusercontent.com/7267084/39329829-82b6be6a-4997-11e8-85e1-dbf320d3b017.png)

If I close the Resource Editor (which I do quite frequently) and re-open it again later, selecting "Add Existing File..." the path has defaulted back to the original path, not the last one that I selected when editing that resx.

This is a pain point for me on an almost daily basis (I have a habit of closing tabs).

## Proposed Change
I think that it would be much more intuitive for the default path to be the path of the project that the resx file is part of, and if at all possible for the last path selected for that resx file to be remembered when you close and re-open the Resource Editor (at least until you unload the project/solution or close VS).

**Comment by Pilchie** [comment]
If anyone is interested in fixing this, it looks like the code to handle it is [here](https://github.com/dotnet/project-system/blob/bcab0444c672fc1a96477b627d8cd2e40b890d4a/src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb#L4184).

**Comment by Giftednewt** [comment]
I have [this](https://github.com/Giftednewt/roslyn-project-system/blob/bc4ced99e5a18461224cc0a2abbbd086e645dfb0/src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb#L4183-L4185) solution which uses the base path of the .resx file. This will mean that if the .resx is not in the root path of the project (e.g. it's a linked file to a .resx in another location or exists within a directory under the main project path), the "Add existing file" dialog will default to that path.

The default path will also get reset to the .resx path when a new instance of the designer is opened due to [this line](https://github.com/Giftednewt/roslyn-project-system/blob/bc4ced99e5a18461224cc0a2abbbd086e645dfb0/src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorView.vb#L4175). This will happen every time you close and re-open the resource editor. 

Ideally I think it should remember the last path you selected for that .resx file until you close VS. Is there a way to do this?

**Comment by Pilchie** [comment]
You'd need to store it in something that lives as long as VS, like say the [Package](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.Editors/package/VBPackage.vb)

**Comment by Giftednewt** [comment]
I have an implementation in [this branch](https://github.com/Giftednewt/roslyn-project-system/tree/resourceeditordefaultpath) that caches the path in the Package. I opted to store this using a combination of the project GUID and the VSITEMID of the .resx file, as the file could potentially be linked in multiple projects. The cache gets cleared on solution/project close and project unload.

I'm not familiar with how the VSITEMID gets generated, but if it would be sufficient on it's own for uniquely identifying the file within a project or there is a better way to achieve uniqueness I will gladly change the implementation.

I can't see any unit tests that cover this code, and my changes don't appear to have broken the tests run by Test.cmd, so is there any specific way in which I should be creating tests for this change?

**Comment by Pilchie** [comment]
You can't use itemid, since in CPS projects it can change and will change frequently.  Instead, use the path to the file, which should be enough when paired with the file.  I'm not sure how testable this code is, we basically lifted straight out of it's 15-year old home in the devdiv build where it didn't have any tests either :(

Why not take your branch and make it into a PR for people to take a look at?

**Comment by Pilchie** [comment]
Also, thanks for tackling this :)

**Comment by davkean** [comment]
Resolved with: https://github.com/dotnet/project-system/pull/3531
