### ISSUE TITLE
Add supported and non-supported project type to Readme?

### ISSUE THREAD

**Issue by conficient** [dotnet/project-system#3494]
I was discussing with @hvanbakel his project [CsprojToVs2017](https://github.com/hvanbakel/CsprojToVs2017) about a change to omit ASP.NET Framework projects from his tool, and came here to see what the definitive list of supported/unsupported project types was, but there does not seem to be one.

Could we add a note in the readme.md to explicitly state what is or is not a suitable project type, e.g.
### Supported
.NET Standard/Core libraries
.NET Core console apps
ASP.NET Core
### Not Supported
ASP.NET Web Application (Framework)
UWP? etc.

**Comment by davkean** [comment]
Thanks, this is the closest we have at the moment; https://github.com/dotnet/project-system/blob/master/docs/feature-comparison.md.

**Comment by conficient** [comment]
That's useful, thanks. Perhaps a link to that in the ReadMe? I'll close this issue now.

**Comment by davkean** [comment]
Thanks, I've linked from Readme.
