### ISSUE TITLE
nativeDebugging in launchsettings.json not working in VS 15.6.7

### ISSUE THREAD

**Issue by dlemstra** [dotnet/project-system#3495]
I should be able to enabled native debugging with `nativeDebugging: true` in `launchsettings.json` according to issue #1125. I have create a simple test project that can be used to reproduce the problem and it can be found here: https://github.com/dlemstra/NativeDebugTest. I am unable to step into the native code of the C project. I did not test this with the latest code so feel free to close this issue if my test project works with the latest version of Visual Studio.

**Comment by Pilchie** [comment]
Good catch - we don't appear to apply this when we launch the debugger for unit testing.  Maybe we don't apply the launch profile at all in that case?

@BillHiebert @ManishJayaswal @onovotny - any ideas how this gets hooked up?

**Comment by Pilchie** [comment]
As a workaround, you might be able to work around this with a launch profile that launches the test runner explicitly, the way Roslyn does [here](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/CodeAnalysisTest/Properties/launchSettings.json#L3), though updated for MSTest instead of xunit of course.

**Comment by ManishJayaswal** [comment]
It looks like Test Explorer window does not yet have support for hooking this up. We are going to open an internal bug on this.
@AbhitejJohn - FYI.

**Comment by davkean** [comment]
Link the bug and I'll dupe 

it. @dlemstra If you'd like to track status you'll need to "Report a Problem" and I'll link the internal bugs with it.

**Comment by ManishJayaswal** [comment]
Here is the VSO bug - (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/608790)
