### ISSUE TITLE
Signing, Security, and Publish tab in Project Properties don't show

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3505]
Signing, Security, and Publish tab in Project Properties don't show

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/241020/signing-security-and-publish-tab-in-project-proper.html
VSTS ticketId: 606880_
_These are the original issue comments:_

noah_son on 4/26/2018, 11:20 AM (5 days ago): <p><img src="https://developercommunity.visualstudio.com/storage/temp/28236-2.png"></p><p><img src="https://developercommunity.visualstudio.com/storage/temp/28237-3.png"></p><p>Here are the screenshots</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jmarolf** [comment]
Cannot reproduce this issue

**Comment by dad98253** [comment]
I'm having this problem, too. Is there some vs-2019 component that I don't have installed? Can someone show a screen shot of what the tab is suppose to look like?

**Comment by drewnoakes** [comment]
@dad98253 it's probably worth opening a new issue. Be sure to include the type of project you're expecting to see these property pages in.

**Comment by drewnoakes** [comment]
The original issue here was against the legacy project system.

**Comment by ft1823** [comment]
Hi everyone. Is there any thing to do when the Signing, Security, and Publish tab in Project Properties don't show?
![Capture](https://user-images.githubusercontent.com/41029429/90169721-ff70a400-dd6c-11ea-9c2e-ef74fceaf531.PNG)
