### ISSUE TITLE
Consider escaping % in Build Events

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/project-system#3506]
See feedback: https://developercommunity.visualstudio.com/content/problem/237752/prebuild-event-command-line-date-issue.html

MSBuild uses URL escaping to treat MSBuild special characters like `@`, `$`, and `%` as literals.

Unfortunately, if a user enters a Build Event that uses DOS-style environment variable expansion `%VARIABLE%` and the first two characters of the variable are valid hex digits, MSBuild will `urldecode` them into a character. This can be _very_ confusing, like the feedback case where the user was trying to say `%DATE%` but it was interpreted as `Úte%`.

It'd be nice if the project system handled escaping/unescaping such strings for users who use the VS UI to edit pre- and post-build events. I _think_ this would only be `%` characters followed by two hex digits--`urlencode`ing the whole user string would be way too much, since spaces are 100% legal and required for legibility. But scoping the round-trip could be difficult.

**Comment by davkean** [comment]
This bug is referring to the new project system, not the legacy project system.

Legacy (`echo %DATE%`):

```
1>------ Rebuild All started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
1>  Mon 07/23/2018
1>  ConsoleApp1 -> C:\Users\davkean\Source\Repos\ConsoleApp150\ConsoleApp1\bin\Debug\ConsoleApp1.exe
```

New project system (`echo %DATE%`):

```
1>------ Rebuild All started: Project: ConsoleApp150, Configuration: Debug Any CPU ------
1>ÚTE
1>ConsoleApp150 -> C:\Users\davkean\Source\Repos\ConsoleApp150\ConsoleApp150\bin\Debug\netcoreapp2.1\ConsoleApp150.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by davkean** [comment]
The fix for this would be in https://github.com/dotnet/project-system/blob/b3b6ea07cd088926ac7973e1f916ec5be9df55e6/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/AbstractBuildEventValueProvider.cs.

**Comment by davkean** [comment]
@rainersigwald Heads up that ProjectCollection.Escape/Unescape are exactly that and what we use elsewhere including other parts of this repo, CPS and legacy.

**Comment by bvamos** [comment]
I still have this issue with MSBuild 16.8.3:

Target:

        <Target Name="EncodeTest">
          <Message Text="ENCODED_TEXT: '$(ENCODED_TEXT)'" Importance="High" />
          <Exec Command="echo ENCODED_TEXT: '%ENCODED_TEXT%'" />
          <Message Text="DATE: '$(DATE)'" Importance="High" />
          <Exec Command="echo DATE: '%DATE%'" />
        </Target>

Environment variables:

        C:\Temp\upload-test>SET DATE=xxx
        C:\Temp\upload-test>set ENCODED_TEXT=a%20b

Output:

        C:\Temp\upload-test>"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" /t:EncodeTest Build.proj
        Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        Build started 5/7/2021 1:44:49 PM.
        Project "C:\Temp\upload-test\Build.proj" on node 1 (EncodeTest target(s)).
        EncodeTest:
          ENCODED_TEXT: 'a b'
          echo ENCODED_TEXT: '%ENCODED_TEXT%'
          ENCODED_TEXT: 'a%20b'
          DATE: 'xxx'
          echo DATE: 'ÚTE%'
          DATE: 'ÚTE'
        Done Building Project "C:\Temp\upload-test\Build.proj" (EncodeTest target(s)).
        
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)

Time Elapsed 00:00:00.20

It is a problem when I would like to add a property value to a URL, like this:

    <Exec Command="curl.exe http://localhost/?q=$(ENCODED_TEXT)" />

**Comment by drewnoakes** [comment]
Reopening to re-evaluate this for the new Project Properties UI.

**Comment by drewnoakes** [comment]
This issue no longer exists with the new Project Properties UI.

![image](https://user-images.githubusercontent.com/350947/131927216-c6e31dbb-99c2-46f5-8354-88db78cd9c7b.png)

![image](https://user-images.githubusercontent.com/350947/131927247-b9f7b859-0d9e-44aa-80a7-8ceb53b053ef.png)

![image](https://user-images.githubusercontent.com/350947/131927236-422a3903-c0f0-42ff-8f1f-b59311a8b925.png)
