### ISSUE TITLE
Files with type 'Resource' are invisible in VS in 'Microsoft.NET.Sdk' project

### ISSUE THREAD

**Issue by AlexeiScherbakov** [dotnet/project-system#3512]
This is compiled OK, and displays in VS normally

`
<ItemGroup>
    <EmbeddedResource Include="Resources\disabled.png" />
    <EmbeddedResource Include="Resources\enabled.png" />
</ItemGroup>
`

But this is compiled OK, but 0 of 2 files are displayed in VS

`
<ItemGroup>
    <Resource Include="Resources\disabled.png" />
    <Resource Include="Resources\enabled.png" />
</ItemGroup>
`

Also I can't change type to 'Resource'. Visual Studio 15.6.6

**Comment by etbyrd** [comment]
I can't seem to repro this issue - this is what it looks like: 

<img width="631" alt="resources" src="https://user-images.githubusercontent.com/36282608/39546712-33e97b98-4e0a-11e8-8dfd-5be42b566d5c.PNG">

Is there a different behavior that you expected?

**Comment by AlexeiScherbakov** [comment]
Steps to reproduce
1) Add images to project dir
2) Check that there are no options for resource (this is bug)
![default](https://user-images.githubusercontent.com/8665915/39547181-70f85a0e-4e5f-11e8-9a34-f058990a69d9.png)
3) Okay, switch to Embedded Resource - all ok
![default](https://user-images.githubusercontent.com/8665915/39547323-ed512fea-4e5f-11e8-886f-681952d7b712.JPG)
4) Edit project file -> change Embedded Resource to Resource, click save all -> (this is bug)
![default](https://user-images.githubusercontent.com/8665915/39547450-53c5b264-4e60-11e8-93e6-8c3bdcf51ca8.JPG)

**Comment by Pilchie** [comment]
These are showing in @etbyrd because anything that is not in another category is implicitly in `None`.  The tooling removes it from `None` in the second case though.

@davkean is this something that we just have rules for though?  Do .NET Core projects support native resources?

**Comment by davkean** [comment]
What do we do with this `<Resource/>` item? What does it end up as?

**Comment by Pilchie** [comment]
They get used for (at least) WPF resources - https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/wpf-application-resource-content-and-data-files

**Comment by davkean** [comment]
Yeah, then looks like we need a rule & register then for showing in the tree.

**Comment by davkean** [comment]
Side note, I'm also going to turn on a feature in CPS that always shows items that don't have rules to mimic legacy.

**Comment by davkean** [comment]
I looked into ShowMissingItemTypes capability which will prevent the ever growing additional of items that we need to keep adding. This will implement legacy project system-like behavior where unknown items types in the project will show up and have the same properties as `<None>` item type.

However, it's not yet ready for us to consume:

-	It won’t show items directly in the project when there is an item for that item type that comes from props/targets. I can see this resulting in confusing behavior; all your items show up in project, then you add a single common one in Directory.Build.props and then they disappear from projects.

-	It will currently shows PackageReference/ProjectReference/Reference also in the project. What’s the recommendation here? We can’t do an ItemDefinitionGroup with Visible false for these as we respect it for some of them in the Dependencies tree, such as Reference.

Reached out to CPS to see what we can do about this.

**Comment by davkean** [comment]
Going to dupe this against https://github.com/dotnet/project-system/issues/2160, we're going to turn on ShowMissingItemTypes which will mimic the legacy project system's behavior around this. These items will get the same properties as "None".
