### ISSUE TITLE
Edits to VSCT files do cause a project to get rebuilt

### ISSUE THREAD

**Issue by jaredpar** [dotnet/project-system#3513]
Editing a VSCT file is not registering as dirtying a project. Hence builds after editing my VSCT file do not trigger a rebuild but rather the project registers as being up to date. This means I must force a rebuild in order for my VSCT edits to be considered. 

Repro:

1. Clone https://github.com/jaredpar/VsVim
1. Restore from the command line (https://github.com/NuGet/Home/issues/6367)
1. Build the VsVim project
1. Edit VsVim.vsct in VsVim 
1. Build the VsVim project 

At this point I would expect the VsVim project to be rebuilt. Instead nothing is built.

**Comment by davkean** [comment]
Note I've experienced similar issues with VSIX projects that I can't find a repro of and @jviau ran into something also that he couldn't reproduce. I suspect overaggressive up-to-date because we're not aware of VSIX-related items.

**Comment by sharwell** [comment]
You need to make sure `VSCTCompile` items are listed as an input to the fast up to date check. See the following issues for more information:

* https://github.com/dotnet/roslyn-sdk/pull/99
* There was another issue where someone proposed an alternative solution but I cannot find it now

**Comment by jaredpar** [comment]
@sharwell that change adds `@(Resource)` into the up to date check list. The VSCT file in VsVim appears to be in the None ItemGroup, not Resource (based on my reading of the binary log).

**Comment by davkean** [comment]
We should make VSIX just work out of the box. @None should be included, but I'll let @panopticoncentral answer that.

**Comment by jaredpar** [comment]
Is `@None` the correct classification of VSCT files? I meant my previous comment as more of a question of whether or not I was doing something wrong in my project file.

**Comment by davkean** [comment]
No idea, ours is None.

**Comment by jasonmalinowski** [comment]
Isn't it necessary to bump the version in the ProvideMenuResourceAttribute anyways, which conveniently *would* be considered a change to the project? Not that this _isn't_ a bug, but @jaredpar's scenario might still be broken anyways?

**Comment by sharwell** [comment]
@jaredpar The item is in `VSCTCompile`:

https://github.com/jaredpar/VsVim/blob/4bf3a1906584d3697f7511110679e8ebd28b8fdf/Src/VsVim/VsVim.csproj#L108

**Comment by panopticoncentral** [comment]
I think at one point we tried putting `None` items en masse in the input list, but that ended up causing problems at the other end of the spectrum where random `None` files caused projects to rebuild even if they didn't have anything to do with compilation.

It seems to me that this is really a bug in the VSSDK, they should be marking any items that should participate in the up to date check with `UpToDateCheckInput` items. What's the right place to route this for that?

**Comment by panopticoncentral** [comment]
I moved this over to the VSSDK.

**Comment by jaredpar** [comment]
Tracking bug is https://devdiv.visualstudio.com/DevDiv/_workitems/edit/611297
