### ISSUE TITLE
GlobalProjectCollection is not checked in CPS projects

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#3516]
The workaround that we in roslyn use to get the C# and VB compilers to work on F5

https://github.com/dotnet/roslyn/blob/9bc0b873c3146ed31d382e93945399c8931c6680/src/Compilers/Extension/CompilerPackage.cs#L40

Is not respected by CPS.  It is unclear if the fix is on the project system side or if there is a workaround that can be implemented in roslyn

**Comment by davkean** [comment]
You would use CPS APIs, which is to implement; https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Build/TurnOffUseHostCompilerIfAvailableBuildPropertiesProvider.cs.

**Comment by davkean** [comment]
CPS has their own (hidden) installation of ProjectCollection.

**Comment by Pilchie** [comment]
This is by design.
