### ISSUE TITLE
New project-system is not importing .pdb symbol files from package lib folders

### ISSUE THREAD

**Issue by mungojam** [dotnet/project-system#3524]
I'm happy to put together a minimum example for this if it isn't intended behaviour.

In our internal packages we have always put the symbol files alongside the DLLs in the appropriate lib folder. With the old project system, even when using PackageReference, these symbol files would automatically get output to the bin folder.

With the new project system these symbol files are no longer being copied to the bin folders so we are no longer able to easily debug into our packages.

This is a big regression in usability for us. I am happy to implement a workaround across our projects if there is one.

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#2225
