### ISSUE TITLE
Break COM aggregation links to lessen severity of leaked IVsHierarchy objects

### ISSUE THREAD

**Issue by Pilchie** [dotnet/project-system#3530]
See :link: https://developercommunity.visualstudio.com/content/problem/246600/outofmemoryexception-crash-in-visual-studio-1580-p.html

At least one issue discovered is that the E&C manager leaks an IVsHierarchy object, which can hold a large graph.  We should be more defensive and break the link from our aggregated objects on solution close.

**Comment by davkean** [comment]
This has been fixed.
