### ISSUE TITLE
NullReferenceException in DotNetCoreProjectCompatibilityDetector.GetProjectCompatibilityAsync

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#3537]
Dump is at `"\\mlangfs1\public\frsilb\dumps\smalis\devenv.dmp"`

@smmalis37 has an internal shproj (in the same directory as the dump) that is causing a NullReferenceException on https://github.com/dotnet/project-system/blob/b3b6ea07cd088926ac7973e1f916ec5be9df55e6/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DotNetCoreProjectCompatibilityDetector.cs#L272. His shproj has no project references, which is causing a non-fatal exception and a popup. The project then "loads", but intellisense is very broken.

**Comment by smmalis37** [comment]
For context on what "broken intellisense" means I'm seeing errors like `Predefined type 'System.String' is not defined or imported` and `The type or namespace name 'IDisposable' could not be found (are you missing a using directive or an assembly reference?)` (I'm definitely not missing a using). The code still builds and runs correctly.

**Comment by Pilchie** [comment]
@BillHiebert can you take a look at this?

**Comment by BillHiebert** [comment]
@Pilchie Looks the code assumes GetUnresolvedReferences() always returns an enumerator - even if there aren't any references. Apparently that's not the case and the code needs to protect against that.

**Comment by 333fred** [comment]
@BillHiebert note that the null reference is on `PackageReferences`, not `GetUnresolvedReferencesAsync()`.

**Comment by Pilchie** [comment]
@davkean that already is limited to [ProjectCapability.CSharpOrVisualBasicOrFSharp](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/DotNetCoreProjectCompatibilityDetector.cs#L258), what more needs to happen?

**Comment by davkean** [comment]
SharedProjects have those capabilities, it should be combined with "PackageReferences".

**Comment by Pilchie** [comment]
I put a PR up, but from the code, wouldn't the .shproj have to have a TFM of `.NETFramework` to get to this code?

**Comment by smmalis37** [comment]
It's being included in a project targeting net461, would that be enough?

**Comment by davkean** [comment]
.NETFramework is the default TFM in Common.targets.
