### ISSUE TITLE
Memory allocation in DependenciesSnapshotProvider.UpdateDependenciesSnapshot.GetProjectItemSpecs

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#3548]
This method calls into IsImported(), which will get the property where the item is imported.  This property is quite expensive, and msbuild will recalculate it with some regular expression work every time.  Because the rule snapshot has already captured that data in a built-in property, there is no reason to pay that price again in the dependencies tree.  Can this code switches to use the data captured in project rule results.

This contributes 1.4% of total allocation in Roslyn.sln loading time, but also contributes to the extra CPU overhead.

Name | Inc % | Inc
-- | -- | --
Microsoft.Build.Shared.FileUtilities+ItemSpecModifiers.GetItemSpecModifier (System.String, System.String, System.String, System.String, System.String ByRef) | 1.4 | 43,575,560

**Comment by lifengl** [comment]
Yes.

Sent from my phone

On May 15, 2018, at 5:23 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh DefiningProjectFullPath?

**Comment by tmeschter** [comment]
As best I can tell the only place this information is used is in `ImplicitTopLevelDependenciesSnapshotFilter.BeforeAdd`.

**Comment by tmeschter** [comment]
@lifengl @davkean What specific type and member already captures this information?

**Comment by drewnoakes** [comment]
@lifeng I'm seeing this and would like to fix it.

On a basic .NET Core project we call `IsImported` 132 times on _every_ dependency update, of which there are many.

> Because the rule snapshot has already captured that data in a built-in property, there is no reason to pay that price again in the dependencies tree. Can this code switches to use the data captured in project rule results.

Can you please point me to the built-in property you're referring to?

The closest thing I've found after hunting around in the debugger is an `Microsoft.Build.Execution.ProjectInstance` within a `Microsoft.VisualStudio.ProjectSystem.Designers.ProjectSnapshot`. Does that sound about right?

**Comment by drewnoakes** [comment]
I'm seeing calls to `IsImported` allocating 3.8% on a large solution:

![image](https://user-images.githubusercontent.com/350947/49252621-68d74480-f41c-11e8-853f-9b165ecf09ad.png)

@lifengl made it sound like this might be straightforward to fix, and I've had a look throught the project but I'm not sure which property to use instead.

**Comment by davkean** [comment]
Can you show the allocations under that?

**Comment by drewnoakes** [comment]
Good timing. See the PR I just posted to MSBuild.

**Comment by davkean** [comment]
I understand what @lifengl is talking about, currently we're accessing the ProjectInstance to read this data - instead, we should make sure that `DefiningProjectFullPath` is part of the data in the reference rules, and read that from IProjectSubscriptionUpdate.

After you're MSBuild change, what does this path allocate?

**Comment by drewnoakes** [comment]
That should be enough for me to look at this further.

> After your MSBuild change, what does this path allocate?

Could you show me how to use a local MSBuild so I can measure, or point me at some docs?

In theory, that 3.8% should drop to 2.3%. We call `IsImported` a _lot_ so this should be good for CPU perf as well as allocation reduction.

**Comment by davkean** [comment]
@lifengl @drewnoakes did just optimize this on the MSBUild side: https://github.com/Microsoft/msbuild/pull/3969, but agreed we should pull from evaluation data.

@drewnoakes Yeah that's beyond on my knowledge, for my perf measurements, always had something outside of VS to repro it.

**Comment by drewnoakes** [comment]
To be clear, is it this value?

![image](https://user-images.githubusercontent.com/350947/49470949-75d0ab00-f803-11e8-8073-a4e10a92e436.png)

I assume our new `IsImported` logic is whether this string equals the project path. The example shown would be considered imported.

**Comment by davkean** [comment]
Yes that is the property, and yes that is correct that PackageReference is "imported" (can't be removed).

**Comment by drewnoakes** [comment]
The `DefiningProjectFullPath` property only appears to be populated for evaluations, not design time builds. Maybe we do have to explicitly subscribe for DTB too. I'll have a look tomorrow in my morning.

**Comment by davkean** [comment]
The design times rules probably don't list it. In the longer term this shouldn't matter, we should be only the top level nodes via evaluation data.

**Comment by drewnoakes** [comment]
I've been looking at adding an `IsImported` property to the dependency model directly and flowing this value through the system rather than attempting to compute it later from a set of project item specs.

The challenge is that `DefiningProjectFullPath` is not always present for that up-front comparison with the project path. I'm still investigating.

**Comment by lifengl** [comment]
@drewnoakes I remember you mentioned there are many full path to the props/targets files in the memory. could some of them come from DefiningProjectFullPath property?  We get this property for all items in the project.

**Comment by drewnoakes** [comment]
@lifengl 

> I remember you mentioned there are many full path to the props/targets files in the memory. could some of them come from DefiningProjectFullPath property? We get this property for all items in the project.

I'll keep that in mind while looking through (making progress on a tool to see roots and retention, BTW).

If this were the case I'd expect to see a lot of `csproj` paths here, no?

The top redundant strings from dumps taken on my machine tend to be:

-  `D:\Program Files %28x86%29\Microsoft Visual Studio\2019\Preview2\MSBuild\Microsoft\VisualStudio\Managed\Microsoft.Managed.DesignTime.targets` (4390 instances, ~10MB wasted)
- `C:\Program Files\dotnet\sdk\2.1.600-preview-009426\Sdks\Microsoft.NET.Sdk\targets\` (9000 instances, ~15MB wasted)

After that it's mostly full paths to `.dll` files, and dependency node IDs of the form `tfm/provider/modelid`, which I have some untested ideas about.

The numbers here are from an very large solution (`MultiProjectSystem_10`), but even on smaller solutions the top items tend to be similar.

**Comment by davkean** [comment]
@drewnoakes This is still showing up in CoreFX solution, this fix was not effective: https://github.com/Microsoft/msbuild/pull/3969.

**Comment by drewnoakes** [comment]
@davkean the MSBuild PR was an easy partial reduction in allocation. The remainder is more involved. I'll revisit this as part of changing how we use evaluation data, which I'll dive into after increasing the integration test coverage to prevent regressions.

**Comment by davkean** [comment]
I think we should tackle this before moving to evaluation data, this is a bigger win than I originally have indicated.

**Comment by drewnoakes** [comment]
The changes around use of evaluation data are aimed at improving correctness. That is, removing a class of bugs where we show unresolved-state warning icons where they shouldn't be.

I'll take another look once relocated, which pushes this into 16.2 at the earliest.

**Comment by drewnoakes** [comment]
@lifengl I picked this up as part of our bug bash and found a solution. The PR in #6781 no longer uses the project instance. Instead it uses `DefiningProjectFullPath` from evaluation data.

Thanks again for reporting this issue. I'm really satisfied with the change in that PR. It gets us closer to the design I would like to see for dependency data ingestion.
