### ISSUE TITLE
Project.Kind breaking change issues

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3552]
Issue|Proposed fix for 15.8
---|---
Analyze -> Run Code Analysis and Suppress Active Issues shows up but doesn't work (https://github.com/dotnet/roslyn/issues/27002) | Disable command inside project-system 
Analyze -> Calculate Code Metrics doesn't show up on project context until package loads | Enable command inside project-system
Analyze -> Calculate Code Metrics works for .NET Framework but not .NET Core (https://github.com/dotnet/roslyn/issues/27001) | Disable command inside project-system when not .NET Framework.
"Initialize Interactive with Project" support for projects other than .NET Framework (https://github.com/dotnet/roslyn/issues/26934) | Do nothing, command correctly lights up/down.

**Comment by davkean** [comment]
I think Roslyn might be rewriting a template file in their IVsEditorFactoryNotify callback which is causing a file to get reloaded on disk.

**Comment by Pilchie** [comment]
@davkean time to close this?

**Comment by davkean** [comment]
Closing this.
