### ISSUE TITLE
F# .net core project referencing F# .net standard project, the output window always appears a message : Rechecking code due to buffer edit!

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/project-system#3556]
1. Create a new F# .net core console app project;
2.  Add a new F# .net standard classlib project；
3. The output window always appears a message : **Rechecking code due to buffer edit!** 
    (Which affects the execution of other processes.)
![rechecking code due to buffer edit](https://user-images.githubusercontent.com/33921754/40227724-d97514fa-5ac1-11e8-9455-dc50ce690bbc.png)
4. Workaround: Close the VS and reopen, this message will disappear.

Tested on VS build D15.8/27716.01 (15.8 Preview 2)

dotnet --info

> .NET Command Line Tools (2.1.200)
> 
> Product Information:
>  Version:            2.1.200
>  Commit SHA-1 hash:  2edba8d7f1
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.16299
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.200\
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.7
>   Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
>

**Comment by YunWeiaa** [comment]
Not repro on latest d15.7/27703.2015 (15.7.2).

**Comment by Pilchie** [comment]
Didn't we have this reported somewhere else recently?  @TIHan - do you know what this is about?

**Comment by YunWeiaa** [comment]
Not repro on **d15.8/27804.00** and **d15.8/27804.01**

**Comment by Pilchie** [comment]
This is related to having CodeLens enabled.  Moving to 16.0, since CodeLens is off by default now.
