### ISSUE TITLE
F12 (go to Definition) not working between .NET Standard Class Library and WebForms Website

### ISSUE THREAD

**Issue by gkonterman** [dotnet/project-system#3558]
I am looking at porting our complete product (+150 projects) to .NET Standard but I am encountering a problem between .NET Standard libs and our big WebForms Website (so not a web application but the one without a `csproj`).

I have ported some classic Class Libraries to .NET Standard Class Libraries and it works suprisingly well except the `F12 Go to Definition` is not working between them. When I am inside my Website project and I press `F12 `on type that lives in a .NET Standard lib I will get the "metadata" version. So it is not directly jumping into my source code, which is kind of a dealbreaker because you cannot simply edit the source code. The workaround is to navigate to it yourself (`CTRL + T`) but that is not really an option imo.

![image](https://user-images.githubusercontent.com/7427231/40233547-bffe6a6c-5aa3-11e8-9598-2c5740890c5e.png)

This issue is really holding me back to port our large code base to .NET Standard so my hope is that this will be on the backlog

**Comment by Pilchie** [comment]
I believe this is the same issue as https://github.com/dotnet/project-system/issues/3010, right @BillHiebert ?

**Comment by Pilchie** [comment]
Closing as a duplicate

**Comment by davkean** [comment]
Thanks @gkonterman! That's the dupe I couldn't find. :)
