### ISSUE TITLE
Show .NET Standard in TFM list for .NET Core projects and vice versa

### ISSUE THREAD

**Issue by Pilchie** [dotnet/project-system#3563]
Ideally, we'd split the concepts apart, but for 15.8, we'd be willing to just merge them into the same list:

![image](https://user-images.githubusercontent.com/312835/40336420-56d6b2ce-5d1e-11e8-9139-f1bb41b48824.png)

**Comment by davkean** [comment]
We should show .NET Framework as well. Make note - the current drop down behavior actually prevents desktop projects from seeing .NET Core/.NET Standard and other TFMs as well, so factor that in.

**Comment by Pilchie** [comment]
The split in the picture is 16, but there was some hope to just merge the .NET Core and .NET Standard lists in 15.8 if that's easy.

**Comment by terrajobst** [comment]
> We should show .NET Framework as well

Agreed. I was thinking we'd show .NET Core, .NET Standard, and .NET Framework.

> The split in the picture is 16, but there was some hope to just merge the .NET Core and .NET Standard lists in 15.8 if that's easy.

If we do that we, we should consider listing all three frameworks in that drop down.

**Comment by Neme12** [comment]
@davkean Should I open an issue in this repo?

**Comment by davkean** [comment]
Yes.

**Comment by Neme12** [comment]
Thanks, filed #3577

**Comment by davkean** [comment]
Going to close this in lieu of https://github.com/dotnet/project-system/issues/3024, which was first.
