### ISSUE TITLE
Renaming nested files in the Solution Explorer is not possible

### ISSUE THREAD

**Issue by stijnherreman** [dotnet/project-system#3567]
According to the comments in #1529, version 15.3 made it possible to rename nested files in the Solution Explorer. I'm using version 15.7.1 and I'm not able to do so.

1. Create a new project with the ASP.NET Core Web Application template. I'm choosing *.NET Core*, *ASP.NET Core 2.0* and a *Web Application* project, but this is also reproducible with an *API* project and a *Web Application (Model-View-Controller)* project.
2. Right click the `appsettings.json` file, there is a *Rename* option. Pressing F2 also lets you rename the file.
3. Right click the `appsettings.Development.json` file, this is no *Rename* option. Pressing F2 does nothing.

Did this work at some point between 15.3 and the current release?

**Comment by Pilchie** [comment]
@abpiskunov - any idea why this might not work?

**Comment by Pilchie** [comment]
Tagging @lifengl

**Comment by davkean** [comment]
@abpiskunov That https://mseng.visualstudio.com/VSIDEProj/_git/VSIDEProj.CPS/pullrequest/189585?_a=files&path=%2Fsrc was supposed to lift that restriction.

**Comment by abpiskunov** [comment]
And did it? :) My nesting logic don't deal with explicit items, interaction is only through CPS's IDependenFileProvider , it can not affect other functionality. It still needs to be investigated in CPS.

**Comment by Pilchie** [comment]
@lifengl - based on the above, it sounds like this should be moved to CPS?  Does that sound right to you?

**Comment by davkean** [comment]
I've opened another bug against platform for this, unfortunately, this is an internal bug (Microsofties: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/635271). If you would like track it, please Help -> Send Feedback -> Report a Problem and I'll dupe the internal bug against yours.
