### ISSUE TITLE
Updated file with "copy always" does not get copied

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3568]
I have a configuration file in my .NET Core 2.0 console app's root directory. It is set to &quot;Build Action: None&quot; and &quot;Copy Always&quot;. The idea is that it will end up in the bin directory.

On first build, all is well.

Then I modify the config file and press Control+Shift+B to build the solution.

I then observe that the file in the bin directory remains out of date, despite it having changed and Copy Always being set.

Build output says that it skipped all my projects. Possibly the cause of the issue? It does not seem to consider this file changing as something that requires a build.

Behavior is same with &quot;Build Action: Content&quot;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/252209/updated-file-with-copy-always-does-not-get-copied.html
VSTS ticketId: 615693_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by MarioAtTrimble** [comment]
Why is this closed and doesn't appear to be targeted for VS 2017?

**Comment by drewnoakes** [comment]
@MarioAtTrimble this fix has not been back ported to VS2017.

**Comment by mtrtm** [comment]
Right.  I'm wondering why - most people are using 2017.  We need this to work

**Comment by davkean** [comment]
Similar to every release we've done in the past 15 years, when we've started working on a new major, our bar for servicing the downlevel product goes up, see our roadmap: https://github.com/dotnet/project-system/blob/master/docs/repo/roadmap.md, in particular:

> This release is considered done, and only impactful bugs, crashes and hangs that block major scenarios will be taken.

A workaround for this bug would be to opt out of the up-to-date check for this project via:

``` XML
<PropertyGroup>
   <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
</PropertyGroup>
```
