### ISSUE TITLE
Fix / Find correct identifiers mentioned messages.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/project-system#358]
Whilst do the work to utilise NameOf and Interpolation string. I was unable to do some to conversions as the refer to identifier does exist or isn't in scope. We should attempt fix these so that the messages are correct.

**Comment by davkean** [comment]
We have no intentions as a team of going back and fixing these identifiers. This code you are referring to is 15 years old, the traces messages are never listened to/hooked up. While I'd accept a contribution, we don't need a bug on our backlog to track this work.
