### ISSUE TITLE
New files added to projects do not respect formatting settings

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3580]
1. Create an .editorconfig with:

```
# EditorConfig is awesome:http://EditorConfig.org

# top-most EditorConfig file
root = true

# Don't use tabs for indentation.
[*]
indent_style = space
# (Please don't specify an indent_size here; that has too many unintended consequences.)

# Code files
[*.{cs,csx,vb,vbx}]
indent_size = 2
insert_final_newline = true
charset = utf-8-bom

```

2. Create a new solution with above in the root
3. Create a new Class Library (.NET Framework)
4. Create a new Class Library (.NET Standard)
5. Add a new class both both projects

**Expected:**

For each source file in projects to have 2 spaces

**Actual:**

CPS projects have 4 spaces, legacy has 2.

**Comment by Pilchie** [comment]
@davkean this should happen in the editor factory - http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/AbstractEditorFactory.cs,23c02d149880b615.

**Comment by davkean** [comment]
Ironically, this is fixed by my PR to read editor notifies via legacy location: https://devdiv.visualstudio.com/DevDiv/Default/_git/CPS/pullrequest/122410?_a=files.

Duping this against https://github.com/dotnet/project-system/issues/3535 which is tracking this work.

**Comment by davkean** [comment]
Going to repro this - as turns out this code is now causing each new file to be reloaded from disk.

**Comment by davkean** [comment]
I suspect this check is failing:

``` C#
                if (workspace.GetHierarchy(projectId) == hierarchy)
                {
                    projectIdToAddTo = projectId;
                    break;
                }
```

Roslyn is assuming the hierarchy that they get in the callback matches the hierarchy we pass to them via AbstractProject. It's not.

**Comment by davkean** [comment]
I understand the issue. This only occurs on File -> New Project and occurs because we're not blocking creation on calling the IVsEditorFactoryNotify instances.

**Comment by davkean** [comment]
This last commit fixes the issue: https://devdiv.visualstudio.com/DevDiv/_git/CPS/commit/b55cd294e47ae6fb3f452483e830a194fb6a1dcb.

**Comment by davkean** [comment]
This has been fixed.
