### ISSUE TITLE
How to specify assembly:ThemeInfo() with the new project system?

### ISSUE THREAD

**Issue by lennartb-** [dotnet/project-system#3588]
I just migrated a pre-2017 csproj to the new 2017 format. I noticed that default styles specified in `themes\generic.xaml` were not automatically applied anymore, and after comparing to the old project found out that `[assembly: ThemeInfo(ResourceDictionaryLocation.None,  ResourceDictionaryLocation.SourceAssembly)]` was omitted from the now auto-generated AssemblyInfo file. I know that you can add certain attributes, such as `InternalsVisibleTo `with an `AssemblyAttribute `in the csproj file, but [apparently only strings are supported](https://github.com/Microsoft/msbuild/issues/2281). Is it possible to somehow insert that without disabling `GenerateAssemblyInfo` (and continue using the normal AssemblyInfo)?

**Comment by davkean** [comment]
Assembly-level attributes can go in any file you want - you don't need to put them in a file called "AssemblyInfo.cs".

**Comment by psulek** [comment]
Now (VS2022) you can do this:

```xml
<AssemblyAttribute Include="System.Windows.ThemeInfoAttribute">
	<_Parameter1>System.Windows.ResourceDictionaryLocation.None</_Parameter1>
	<_Parameter1_IsLiteral>true</_Parameter1_IsLiteral>
	<_Parameter2>System.Windows.ResourceDictionaryLocation.SourceAssembly</_Parameter2>
	<_Parameter2_IsLiteral>true</_Parameter2_IsLiteral>
</AssemblyAttribute>
```

Dont forget to add **GenerateAssemblyInfo** :
```xml
<PropertyGroup>
  <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
</PropertyGroup>
```
