### ISSUE TITLE
Create a new .net core project, can't debug succeeded.

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/project-system#3593]
1. Create a new .net core console app project, first build, run succeeded
2. Place a breakpoint on the line:
           ` Console.WriteLine("Hello World!"); 
`
3. Debug failed.
4. The **terminate window** show "The tool is currently busy and not responding to messages, you can continue to wait or terminate the tool now."

![debugfailed](https://user-images.githubusercontent.com/33921754/40654912-35cc1632-6372-11e8-98f2-92accb78599d.png)
**Expected result**
     Debug succeeded

Test on **D15.8stg/27728.3000** (15.8 Preview 3)
dotnet --version:

> .NET Command Line Tools (2.1.201)
> 
> Product Information:
>  Version:            2.1.201
>  Commit SHA-1 hash:  7932dc6179
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.16299
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.201\
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.7
>   Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

**Comment by Pilchie** [comment]
Can you file a VSTS bug instead. This is more likely a debugger issue than project system.

**Comment by YunWeiaa** [comment]
Okay, I created internal VSTS bug [597760](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/623865) to track this.
