### ISSUE TITLE
latest master cannot be built from VS

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/project-system#3595]
![image](https://user-images.githubusercontent.com/1592091/40690836-d3b1a6d8-635d-11e8-9a4d-13e85f8a4c6a.png)

on my machine if i build from VS i see issue above (starting with clean nuget cache), roslyntools.modifyvsixmanifest is not getting restored.

**Comment by davkean** [comment]
@tmat This is from VS if you've not run build.cmd. I'm guessing we need to make sure these packages are in VS graph so we restore them?

**Comment by Pilchie** [comment]
@abpiskunov does running `build.cmd` from the command line at least once resolve this?

**Comment by Pilchie** [comment]
I do this regularly, so I suspect that even having them in the package cache is sufficient?

**Comment by abpiskunov** [comment]
yes commandline build worked. So the issue is for users who has fresh machine and tries to build repo from VS first time.

**Comment by tmat** [comment]
I believe this will be fixed once we move the repo to the latest RepoToolset, which is an SDK package.

**Comment by Pilchie** [comment]
@jmarolf can you take a look at updating us when you get a chance?

**Comment by davkean** [comment]
@tmat Are you saying it's already fixed or will be fixed?

**Comment by tmat** [comment]
It's not fixed in PS repo.

**Comment by davkean** [comment]
This has been resolved, you can now build directly from ProjectSystem.sln without having run build.cmd: https://github.com/dotnet/project-system/pull/5300.
