### ISSUE TITLE
ProjectItem.FileCodeModel is Null on Net Core Template Project.

### ISSUE THREAD

**Issue by junimnjw** [dotnet/project-system#3596]
Hello. My name is Jinwoo Nam.
Now, I am working on developing a vsix package. While developing, I've found one usse regarding FileCodeModel.

I created a project with .Net Core Console template project, and then added a c# file.
After that, I got the ProjectItem from the added c# file. 

the problem is... I cannot use FileCodeModel of the ProjectItem since it is always null. 

this issue does not occur if I make the project based on Net Framework.

Could you tell me why the issue occurs only in Net Core Consle Template??

**Comment by davkean** [comment]
Thanks, dupe against this https://github.com/dotnet/project-system/issues/2544. We're async so it gets updated in the background. We're fixing this for 15.8.

**Comment by junimnjw** [comment]
thank u. mr. davken.
is it avaliable to use the bug fix in 15.8 Preview??

**Comment by davkean** [comment]
No the bug is still open, it hasn't been fixed.

**Comment by junimnjw** [comment]
I have one more question. The issue was disappeared if I forcefully called the messagebox.show("message") before getting FileCodeModel. Can you tell me the reason ?

**Comment by davkean** [comment]
> We're async so it gets updated in the background.

**Comment by junimnjw** [comment]
Hello. I really hope you fix this issue in 15.8 version because my application's main feature depends on it.Untill the next release, 
Is there another work-around that I can use instead of using MessageBox.Show()???
