### ISSUE TITLE
Loading UWP xaml designer is extremely slow after building

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/project-system#3601]
##### Version:
Visual Studio 15.7.2

##### Sample project: 
https://github.com/amatukaze/ing/tree/322ef15a9a2c6bf7596e07284cd3b13c184eb635
Mixed project system

##### Steps:
Clone the repository (of course with submodules). It takes **6s** on my machine to open the solution.

Don't build, just select an UWP xaml and open(For example `Views\WinRT\Settings`). It takes **5s** to open it for first time. Following opens are immediate.

Close the solution, reopen it, then build it(in debug config).

After building, open the UWP xaml again. This time it takes **232s** to load. I even considered it fails to load. (And spent a lot of time to find what "prevents" it to load)

For comparison, WPF designer(using `MSBuild.Sdk,Extras`) always loads immediately.

**Comment by Pilchie** [comment]
I suspect this is the same issue as https://developercommunity.visualstudio.com/content/problem/251571/uwp-reference-additional-netstandard-dll-after-157.html.

Can you try upgrading the NetStandard.Library package reference to 2.0.3?

If that doesn't work, I suggest using Visual Studio's "Send Feedback" to record the problem, as that will include more information, and let the issue be routed to the right team.

**Comment by huoyaoyuan** [comment]
It's fixed after upgrading `Microsoft.NETCore.UniversalWindowsPlatform` to 6.1.5, which references `NetStandard.Library` 2.0.3.
But I'd really want UWP designer to open as fast as WPF designer.

**Comment by davkean** [comment]
@huoyaoyuan To get this on the correct team's radar, can you Help -> Send Feedback -> Report a Problem and "record" opening the UWP designer in a situation that it is slow. This will gather a bunch of data that team can dive into and find the underlying causes.
