### ISSUE TITLE
Error when setting Build Action and Copy To Output Directory

### ISSUE THREAD

**Issue by kristofferjalen** [dotnet/project-system#3607]
Microsoft Visual Studio Enterprise 2017, version 15.7.1

1. File > New > Project > Console App (.NET Core)
2. Add > New Item... > Text File > Add
3. Right click TextFile1.txt > Properties

   * Build Action: **Content**
   * Copy To Output Directory: **Copy if newer**
   * OK

Visual Studio shows an error message dialog box:

```
An error has occurred while saving the edited properties listed below:
    Build Action
One or more values are invalid. Mismatched PageRule with the wrong ItemType.
```

Workaround:

1. Right click TextFile1.txt > Properties
   * Build Action: **Content**
   * Copy To Output Directory: **Do not copy**
   * OK
2. Right click TextFile1.txt > Properties
   * Copy To Output Directory: **Copy if newer**
   * OK

**Comment by davkean** [comment]
Thanks for the great repro.

This has been fixed in 15.8 Preview 3 with this PR: https://github.com/dotnet/project-system/pull/3566.
