### ISSUE TITLE
Extenders cannot extend C# project, nor any reference

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3608]
1. Run attached VSIX, it extenders every single C#/VB object, adding a property called "Guid" that lists the name of the catid.
[VSIXProject2.zip](https://github.com/dotnet/project-system/files/2062473/VSIXProject2.zip)

For some reason extenders are not showing up on C# (both legacy & CPS) projects:
![image](https://user-images.githubusercontent.com/1103906/40838176-5f8010bc-65e0-11e8-9460-54455b1405b4.png)

While VB works:
![image](https://user-images.githubusercontent.com/1103906/40838137-38a932fc-65e0-11e8-8c48-3edbafe6bb5b.png)

Nor on any references:
![image](https://user-images.githubusercontent.com/1103906/40838202-73ea984c-65e0-11e8-8c0d-d559b543340c.png)

**Comment by Pilchie** [comment]
@davkean - Do you know if this is a regression?

**Comment by davkean** [comment]
Project used to work many years ago for flavors. However for legacy they go through an internal mechanism so I'm unsure if its a regression or not.

**Comment by thomaslevesque** [comment]
Any chance this is going to be fixed? I have a VS extension that relies on this, and it doesn't work on SDK-style projects, which is going to make it obsolete quite soon with the rapid adoption of .NET Core...

**Comment by davkean** [comment]
@thomaslevesque Which object are you extending?

**Comment by thomaslevesque** [comment]
@davkean I'm extending project items (see registration [here](https://github.com/thomaslevesque/AutoRunCustomTool/blob/d9ce090bcd116cc741ed8e57bc0854011ed96ccb/AutoRunCustomTool/AutoRunCustomToolPackage.cs#L44))

See this issue for details: https://github.com/thomaslevesque/AutoRunCustomTool/issues/18

**Comment by davkean** [comment]
Files and folders already work. I just tried using the above example project and I get the following for an SDK-based project:

![image](https://user-images.githubusercontent.com/1103906/77371623-df3d4a00-6db7-11ea-91b2-f076ea730246.png)

**Comment by davkean** [comment]
I just verified above, there's a bug in the extension - its looking up CATIDs without parsing the GUID or ignoring case. I've changed that and verified that extenders show up everywhere thats expected.

**Comment by thomaslevesque** [comment]
@davkean thanks for checking. Someone suggested that my issue might be related to this one, but I guess it's something else...
