### ISSUE TITLE
Build warnings & errors from build always get applied to the first TFM in the project 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3611]
If using multi targeting (TargetFrameworks) and one target has an error, VisualStudio seems to assign the error always to the first target, and not to the target that caused the error.

Example: 
-
 &lt;TargetFrameworks&gt;netstandard2.0;net452&lt;/TargetFrameworks&gt;
- One CS-File uses Windows.Forms (#if !NETSTANDARD2_0)
- Reference in .csproj to Windows.Forms is missing.
- Errormessage: CS0234	The type or namespace name 'Forms' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)	ocNet.Lib.Thing(netstandard2.0)

Shown ocNet.Lib.Thing(netstandard2.0), correct would be ocNet.Lib.Thing(net452)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/233599/error-output-incorrect-on-multi-trageting-targetfr.html
VSTS ticketId: 600116_
_These are the original issue comments:_

Project:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>netcoreapp2.1;net45</TargetFrameworks>
  </PropertyGroup>


  <ItemGroup>
    <Compile Condition="'$(TargetFramework)' == 'netcoreapp2.1'" Remove="Program.cs" />
  </ItemGroup>
</Project>
```

Source file:
``` C#
using System;

internal class Program
{
    private static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");
    };
}
```

**Expected:** 
```
Error	CS1597	Semicolon after method or accessor block is not valid	ConsoleApp230(net45)	1	C:\Users\davkean\Source\Repos\ConsoleApp230\ConsoleApp230	C:\Users\davkean\Source\Repos\ConsoleApp230\ConsoleApp230\Program.cs	8	6	Compiler	IntelliSense	Active	Compiler
```
**Actual:**

```
Severity	Code	Description	Project	Project Rank	Path	File	Line	Column	Category	Source	Suppression State	Tool
Error	CS1597	Semicolon after method or accessor block is not valid	ConsoleApp230(netcoreapp2.1)	1	C:\Users\davkean\Source\Repos\ConsoleApp230\ConsoleApp230	C:\Users\davkean\Source\Repos\ConsoleApp230\ConsoleApp230\Program.cs	10	10	Build	Build	Active	Compiler
Error	CS1597	Semicolon after method or accessor block is not valid	ConsoleApp230(net45)	1	C:\Users\davkean\Source\Repos\ConsoleApp230\ConsoleApp230	C:\Users\davkean\Source\Repos\ConsoleApp230\ConsoleApp230\Program.cs	8	6	Compiler	IntelliSense	Active	Compiler
```

**Comment by ghuntley** [comment]
This is super annoying.

**Comment by davkean** [comment]
Dup'ing against https://github.com/dotnet/project-system/issues/2811.
