### ISSUE TITLE
CustomTool property not working on CPS based projects

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3612]
In ASP.NET Core projects when programmatically setting the CustomTools property, the error in the screenshot below happens.

![image](https://user-images.githubusercontent.com/1103906/40893475-b635bd34-67e4-11e8-9cc8-a3f39c43aefb.png)

Also, the Property Grid doesn't show the Custom Tools property.

**Comment by Pilchie** [comment]
Does this happen to all item types, or is it specific to ones that we don't have rules registered for?

**Comment by davkean** [comment]
This was an internal bug filed by Mads, this will be on the ones that don't have CustomTool registered. I think this was a None item.

**Comment by jjmew** [comment]
We fixed this when we unified all the rules across item types

**Comment by davidwengier** [comment]
This would have been fixed by https://github.com/dotnet/project-system/pull/4016
