### ISSUE TITLE
Keyboard Navigation for the Project System Property Pages does not follow accessibility recomendations.

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3613]
The TAB'ing logic is broken:

Open AppDesigner
Keep pressing SHIFT+TAB until you navigate onto the page title
Press TAB

**Expected**: To navigate back onto the page
**Actual**: You navigate to the next tab. While you can use TAB to navigate onto the page titles, you cannot use TAB to get off it

**Comment by Pilchie** [comment]
Tag @dpoeschl any idea how this *should* work so that you can both switch through tabs and through controls on each tab?

**Comment by davkean** [comment]
Every other UI I've seen like this, lets you get into the Tabs "bar" but doesn't cycle through every tab.

**Comment by ghuntley** [comment]
Duplicate of https://github.com/dotnet/project-system/issues/2650

**Comment by davkean** [comment]
Yep,
