### ISSUE TITLE
[Feedback] RightClick->Add->Class or Shift-Alt-C defaults to Powershell

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3614]
When right clicking a folder and clicking 'Add' then 'Class', or pressing 'Shift-Alt-C' in a C# project, the default option selected is "Powershell Script", requiring manual navigation to "Visual C#" then "Class".

In a C# project, the default for Add -> New Item should be C# not Powershell, and when specifically choosing "Class" from the menu should be C# Class.

(This is tracking this repro's implementation of this, legacy and Web projects is tracked elsewhere)

**Comment by davkean** [comment]
Okay, I dug into this a bunch more today after speaking with Andrew offline.

I was under the impression, based on experimentation 6 months ago, that we didn’t have the ability to select the correct node with PowerShell tools installed. This is not correct. Turns out there’s 3 copies of effectively the same code, and I was looking at only 2 of them. ASP.NET Core have their own copy.

Conclusion:

Legacy: If we fix up the strings as called out in the bug in legacy project system, the correct node will be selected.
ASP.NET Core: ASP.NET themselves are selecting the wrong node, they are selecting Visual C# items, but should be selecting ASP.NET Core.
.NET Core: We’re selecting the right node under English but we’re not handling localized cases. Not entirely sure how we can do that – given the string lives in the legacy project system. Maybe we can rely on the fact that it will likely get localized the same as legacy?

**Comment by Pilchie** [comment]
Tagging @BillHiebert and @tmeschter who have each looked at parts of this before.  I thought @BillHiebert said that the ASP.NET Core one was fixed now?

**Comment by davkean** [comment]
One thing I forgot to write is that I've already filed a different bug for ASP.NET and left existing for legacy.

**Comment by jjmew** [comment]
@davkean @panopticoncentral  I am not able to repro this on 15.9 or 16.0. I understand that PowerShell tools need to be installed in the workflow for it to repro. Unfortunately that option is not longer available on the installer. I am resolving it as No Repro. Please let me know if we should reactivate.
