### ISSUE TITLE
Cannot compile an ASP.NET WebForms project with filenames containing special chars

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3616]
When I open a solution that contains an ASP.NET WebForms (Visual Basic), any file with special chars (e.g. &quot;ñ&quot;) is not well recognised not allowing me to compile the project. 

For instance:  &quot;RestablecerContraseña.aspx&quot; appears in Solution Explorer as:

RestablecerContraseña.aspx  (not included in project)
RestablecerContraseña.aspx.designer.vb (not included in project)
RestablecerContraseña.aspx.vb (not included in project)

And also:
RestablecerContrase?a.aspx  (included but with an exclamation icon)
RestablecerContrase?a.aspx.designer.vb (included but with an exclamation icon)
RestablecerContrase?a.aspx.vb (included but with an exclamation icon)

I tried to remove the last 3 files and include in the project the right ones. If I check the differences between the original vb.proj  and the modified one I can see the &quot;ñ&quot; chars are written as &quot;?&quot;. Other static files (.html) included in the project with &quot;ñ&quot; in the filename are written as &quot;?&quot;.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/26034/cannot-compile-an-aspnet-webforms-project-with-fil.html
VSTS ticketId: 414787_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Pilchie** [comment]
@BillHiebert any ideas here?

**Comment by Pilchie** [comment]
Also @abpiskunov

**Comment by Pilchie** [comment]
Sorry for the misdirection - as this is aspx related, we're going to use the original feedback item to track this, as it would be on a different team.
