### ISSUE TITLE
.NET Standard GenerateAssemblyInfo Add Item AssemblyInfo Error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3617]
When creating .NET Standard libraries, I manage my version numbers in a seperate AssemblyInfo.cs file under the Properties folder in that project.  This is mainly due to the fact that I like to keep things uniform to version number things across all libraries.

So I'll first edit the csproj and add &lt;GenerateAssemblyInfo&gt;false&lt;/GenerateAssemblyInfo&gt; under the &lt;Project&gt; &lt;Property&gt; tags.  No problems here.

Next I'll add a Properties folder.  No issues here either.  Visual Studio recognized this folder and changed the icon.  All good here as well.

However I then right-click the folder and choose to Add &gt; New Item...
I'll search for Assembly Information File.
I click Add

The file gets added correctly, but I believe Visual Studio also tried to add a reference here that isn't accepted.  The error reads:

The reference &quot;System&quot; could not be added to the project.  This wizard will continue to run, but the resulting project may not build properly.

The project does, in fact, build properly afterwards.  But the error should still be corrected.  Perhaps the wizard needs to have some context around the fact that I'm adding to a .NET Standard project.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/265815/net-standard-generateassemblyinfo-add-item-assembl.html
VSTS ticketId: 625582_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by davkean** [comment]
We should remove the "System.dll" requirement from this template. First check if any of the attributes come from System.

**Comment by jjmew** [comment]
We fixed this in 16.3
