### ISSUE TITLE
Multi-Target Framework project get the reference based on the first in the list.

### ISSUE THREAD

**Issue by lucasgl** [dotnet/project-system#3618]
I had a multi-target project set up like this:
`<TargetFrameworks>net45;netstandard2.0;portable-net45+win8;</TargetFrameworks>`

and when I add into a solution in the latest VS 2017 (15.7.3) it thinks is a .net framework project and don't show the files under the solution explorer.

Took me a lot of time to find a workaround:
Fixed as switching the order in the .csproj file putting the netstandard2.0 in front:
`<TargetFrameworks>netstandard2.0;net45;portable-net45+win8;</TargetFrameworks>`

**Comment by Pilchie** [comment]
The fist part of this is basically https://github.com/dotnet/project-system/issues/1162, but any project with a `<TargetFrameworks>` section should be opened by the new project system.  See https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md for more details.
