### ISSUE TITLE
In call of CSC Task sometimes the /reference parameter to project references are missing

### ISSUE THREAD

**Issue by SabotageAndi** [dotnet/project-system#3624]
This issue is happening when compiling SpecFlow on my machine and on a second one.

Source: Branch: https://github.com/techtalk/SpecFlow/commits/DotNetCore
Commit: https://github.com/techtalk/SpecFlow/commit/f4b7d24ffc615544ec4f908f9da4fbad819b4d58

This is a very strange issue, that appears random. I wasn't able yet to reproduce it.
It's not happening every time. Sometimes this error doesn't appears for some hours. Sometimes it is happening every second build.

Building in VS with "Build Solution" produces a successful build.
If I start a test in the Test Explorer, a build is triggered. This build failes with following errors:

> CodeBehindWriter.cs(4,7,4,15): error CS0246: The type or namespace name 'TechTalk' could not be found (are you missing a using directive or an assembly reference?)
> FeatureCodeBehindGenerator.cs(4,7,4,15): error CS0246: The type or namespace name 'TechTalk' could not be found (are you missing a using directive or an assembly reference?)
> FeatureCodeBehindGenerator.cs(5,7,5,15): error CS0246: The type or namespace name 'TechTalk' could not be found (are you missing a using directive or an assembly reference?)
> FeatureCodeBehindGenerator.cs(6,7,6,15): error CS0246: The type or namespace name 'TechTalk' could not be found (are you missing a using directive or an assembly reference?)
> FeatureCodeBehindGenerator.cs(7,7,7,15): error CS0246: The type or namespace name 'TechTalk' could not be found (are you missing a using directive or an assembly reference?)
> FeatureFileCodeBehindGenerator.cs(7,7,7,15): error CS0246: The type or namespace name 'TechTalk' could not be found (are you missing a using directive or an assembly reference?)
> FeatureCodeBehindGenerator.cs(55,38,55,57): error CS0246: The type or namespace name 'TestGeneratorResult' could not be found (are you missing a using directive or an assembly reference?)
> FeatureCodeBehindGenerator.cs(55,76,55,89): error CS0246: The type or namespace name 'CodeDomHelper' could not be found (are you missing a using directive or an assembly reference?)
> FeatureCodeBehindGenerator.cs(63,48,63,63): error CS0246: The type or namespace name 'ProjectSettings' could not be found (are you missing a using directive or an assembly reference?)
> FeatureCodeBehindGenerator.cs(63,17,63,30): error CS0246: The type or namespace name 'CodeDomHelper' could not be found (are you missing a using directive or an assembly reference?)
> FeatureCodeBehindGenerator.cs(13,17,13,30): error CS0246: The type or namespace name 'CodeDomHelper' could not be found (are you missing a using directive or an assembly reference?)
> FeatureCodeBehindGenerator.cs(14,17,14,32): error CS0246: The type or namespace name 'ProjectSettings' could not be found (are you missing a using directive or an assembly reference?)
> FeatureCodeBehindGenerator.cs(15,17,15,32): error CS0246: The type or namespace name 'SpecFlowProject' could not be found (are you missing a using directive or an assembly reference?)
> FeatureCodeBehindGenerator.cs(16,17,16,31): error CS0246: The type or namespace name 'ITestGenerator' could not be found (are you missing a using directive or an assembly reference?)
> Done building project "SpecFlow.Tools.MsBuild.Generation.csproj" -- FAILED.
> SpecFlow.Tools.MsBuild.Generation -> G:\Work\SpecFlow\SpecFlow.Tools.MsBuild.Generation\bin\Debug\netcoreapp2.0\SpecFlow.Tools.MsBuild.Generation.dll

After looking into the binlogs of a successful build and a failed build of SpecFlow.Tools.MsBuild.Generation, I noticed that the /reference parameters to the ProjectReferences are missing.

> /reference:G:\Work\SpecFlow\TechTalk.SpecFlow\bin\Debug\netstandard2.0\TechTalk.SpecFlow.dll 
> /reference:G:\Work\SpecFlow\TechTalk.SpecFlow.Generator\bin\Debug\netstandard2.0\TechTalk.SpecFlow.Generator.dll 
> /reference:G:\Work\SpecFlow\TechTalk.SpecFlow.Parser\bin\Debug\netstandard2.0\TechTalk.SpecFlow.Parser.dll 
> /reference:G:\Work\SpecFlow\TechTalk.SpecFlow.Utils\bin\Debug\netstandard2.0\TechTalk.SpecFlow.Utils.dll

I attached the binlogs of both runs:

Failed build:
[TechTalk.SpecFlow.Specs_Debug_AnyCPU_Build_2018-06-06T13_06_21.9553039+02_00.binlog.zip](https://github.com/dotnet/project-system/files/2075913/TechTalk.SpecFlow.Specs_Debug_AnyCPU_Build_2018-06-06T13_06_21.9553039.02_00.binlog.zip)

Successful build:
[SpecFlow.Tools.MsBuild.Generation_Debug_AnyCPU_Build_2018-06-06T13_09_04.6050029+02_00.binlog.zip](https://github.com/dotnet/project-system/files/2075914/SpecFlow.Tools.MsBuild.Generation_Debug_AnyCPU_Build_2018-06-06T13_09_04.6050029.02_00.binlog.zip)

Project file in question: https://github.com/techtalk/SpecFlow/blob/DotNetCore/SpecFlow.Tools.MsBuild.Generation/SpecFlow.Tools.MsBuild.Generation.csproj
It's based on Nate McMasters post about MSBuild Tasks in .NET Core: https://natemcmaster.com/blog/2017/07/05/msbuild-task-in-nuget/

Any ideas what this is? Is it something in my project files?

Additional information:
dotnet --info output:

> G:\Work\SpecFlow>dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.300
>  Commit:    adab45bf0c
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17134
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.300\
> 
> Host (useful for support):
>   Version: 2.1.0
>   Commit:  caa7b7e2ba
> 
> .NET Core SDKs installed:
>   1.0.0 [C:\Program Files\dotnet\sdk]
>   1.0.3 [C:\Program Files\dotnet\sdk]
>   1.0.4 [C:\Program Files\dotnet\sdk]
>   1.1.0 [C:\Program Files\dotnet\sdk]
>   2.0.0 [C:\Program Files\dotnet\sdk]
>   2.0.2 [C:\Program Files\dotnet\sdk]
>   2.0.3 [C:\Program Files\dotnet\sdk]
>   2.1.104 [C:\Program Files\dotnet\sdk]
>   2.1.105 [C:\Program Files\dotnet\sdk]
>   2.1.200-preview-007576 [C:\Program Files\dotnet\sdk]
>   2.1.200-preview-007589 [C:\Program Files\dotnet\sdk]
>   2.1.200-preview-007597 [C:\Program Files\dotnet\sdk]
>   2.1.200 [C:\Program Files\dotnet\sdk]
>   2.1.201 [C:\Program Files\dotnet\sdk]
>   2.1.300-preview2-008533 [C:\Program Files\dotnet\sdk]
>   2.1.300 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

We are using VS2017 15.7.2 and 15.8.0 Preview 2.0. It is happening in both.

**Comment by Pilchie** [comment]
@nguerrera any ideas here? 

Generally msbuild will only pass the p2p refs, if the output exists on disk.  IDE builds are a little different from command line builds, because in the IDE, VS calls MSbuild for each project, telling msbuild *not* to build P2P refs, whereas on the commandline, msbuild will build p2p references on demand.

One thought that occurs to me - is it possible that in your .sln, the currently selected configuration has those projects configured not to build at all?

**Comment by SabotageAndi** [comment]
All projects are checked in the solution configuration for building.
Something special between the 2 project is, that there is no ProjectReference, but an MSBuild task call (see https://github.com/techtalk/SpecFlow/blob/DotNetCore/Tests/TechTalk.SpecFlow.Specs/TechTalk.SpecFlow.Specs.csproj#L59)

Reason for this is, that TechTalk.SpecFlow.Specs doesn't need to reference the SpecFlow.Tools.MsBuild.Generation project, but needs the build output of it.
I used the MSBuild task, because ReferenceOutputAssembly on the ProjectReference doesn't work yet on sdk-style projects.
Could be that not all or wrong properties are past to the MSBuild task?

**Comment by Pilchie** [comment]
I suspect that that is the problem.  The IDE won't see the dependency in that case.  It's possible that using a `ProjectReference` with `<ReferenceOutputAssembly>False</ReferenceOutputAssembly>` metadata would work here instead, but IIRC there are some problems with that in .NET Core projects.  @nguerrera do you remember what they are?

**Comment by Pilchie** [comment]
Alternatively, you may be able to get this to work in VS by adding explicit dependencies between the projects by right clicking them in solution explorer (these will be stored in the .sln file).

**Comment by SabotageAndi** [comment]
I will try `<ReferenceOutputAssembly>False</ReferenceOutputAssembly>` again, but it didn't work around 15.3.
Build order in solution explorer is not a workaround for this, because the code has to be build with msbuild on the cli/VSTS agent. And AFAIK that doesn't care for the build order in the sln.

**Comment by nguerrera** [comment]
In the past, the problems arise when the thing you're ask to not be referenced is incompatible with the referencer. I believe it was fixed, but I'll have to check.

**Comment by nguerrera** [comment]
https://github.com/Microsoft/msbuild/issues/2661 is the issue. There was a fix but the fix broke things and it got reverted.

A new change was made recently that "Fixes [...] the most common cases of https://github.com/Microsoft/msbuild/issues/2661" : https://github.com/Microsoft/msbuild/pull/3315

@rainersigwald Did that make it into 15.7, or is it slated for 15.8?

**Comment by rainersigwald** [comment]
It'll be in 15.8.

**Comment by rainersigwald** [comment]
There's a workaround for solution dependencies in https://github.com/Microsoft/msbuild/issues/2661#issuecomment-338808156.

**Comment by davkean** [comment]
Should we dup this against those?

**Comment by SabotageAndi** [comment]
I was able to change on of the MSBuild task calls to a ProjectReference with ReferenceOutputAssembly=false.
https://github.com/techtalk/SpecFlow/commit/ef1dc2342404bc28b4484ba88c32841c9bbd3886

I couldn't change the second one, because then I get file lock errors. SpecFlow.Tools.MsBuild.Generation is a custom MSBuild which is executed in the build of TechTalk.SpecFlow.Specs and it loads TechTalk.SpecFlow.Specs.Generator.SpecFlowPlugin via Assembly.LoadFrom. 

But now I get a different error:
G:\Work\SpecFlow\SpecFlow.Tools.MsBuild.Generation\SpecFlow.Tools.MsBuild.Generation.csproj : error MSB4057: The target "GetTargetPath" does not exist in the project.

This happens only in Visual Studio, when I do a normal build.
Here is the binlog of the failing build: [TechTalk.SpecFlow.Specs_Debug_AnyCPU_Build_2018-06-12T09_45_00.4574298+02_00.binlog.zip](https://github.com/dotnet/project-system/files/2093040/TechTalk.SpecFlow.Specs_Debug_AnyCPU_Build_2018-06-12T09_45_00.4574298.02_00.binlog.zip)

Should I create separate issue for this new error?

**Comment by Pilchie** [comment]
`GetTargetPath` is what VS calls to determine the output path of a project when it's used as a P2P reference (instead of `Build`).  It's normally defined in common targets, but maybe your csproj file is customized to not include it?

@rainersigwald / @nguerrera If `ReferenceOutputAssembly` is `false`, should we call `GetTargetPath` at all?

**Comment by davkean** [comment]
@SabotageAndi  Sorry for the late reply, can you please open a new bug if that last issue is still occuring?
