### ISSUE TITLE
Legacy project system does not propagate codes from msbuild to error list

### ISSUE THREAD

**Issue by nguerrera** [dotnet/project-system#3633]
NOTE: This works as I would expect in CPS, but not in legacy project system.

### Repro steps

* VisualStudio.15.IntPreview/15.8.0-pre.3.0+27804.1.d15.8
* File -> New Project -> Windows Desktop -> Console App (.NET Framework)
* Right click -> Unload project ->  Edit .csproj, add target below

``` xml
 <Target Name="Test" AfterTargets="Build">
    <Warning Code="NETSDK1234" Text="This is a test"/>
  </Target>
```

* Reload project
* Build

### Expected result

The code column for the warning in the error list is populated with NETSDK1234

### Actual result

The code column is blank

cc @tmeschter As we saw earlier... I'm filing against project system since it works in CPS and therefore isn't likely an issue with the error list.

**Comment by davkean** [comment]
Yes this is known. It's using the old error list APIs which don't support setting "code".

**Comment by tmeschter** [comment]
Tom's triage notes: recommend we close this without fixing it.

**Comment by tmeschter** [comment]
We have decided not to implement this feature request.
