### ISSUE TITLE
Enable tasks running in design-time build to register files to be watched for changes

### ISSUE THREAD

**Issue by tmat** [dotnet/project-system#3636]
This is needed in order to set up file watching for .editorconfig files.

The current design is for DiscoverEditorConfigFiles task to add .editorconfig files to UpToDateCheckInput item group. When the files listed in this item group are updated on disk a design-time build should be kicked off.

Let's first implement and test this for CPS and add support to legacy project system once we validate the end-to-end scenario with .editorconfig.

**Comment by tmeschter** [comment]
The current design for .editorconfig support uses new MSBuild item intrinsic functions to find the relevant .editorconfig files during evaluation, not during a design-time build. As such this work item is no longer relevant. Closing.
