### ISSUE TITLE
Dependency node does not handle configuration switches

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3642]
1. File -> New -> Console App (.NET Core)
2. File -> New -> Class Library (.NET Standard)
3. Switch from Debug -> Release
4. Add a reference from Console App -> Class Libary

Expected: No warning icons
Actual: Warning icon on reference

**Comment by davkean** [comment]
Exactly the same issue as https://github.com/dotnet/project-system/issues/2733 except that this is the dependency node which has the same code, but duplicates it.

**Comment by davkean** [comment]
Feedback: https://developercommunity.visualstudio.com/content/problem/98738/net-core-20-project-references-always-pointing-to.html.

**Comment by davkean** [comment]
Feedback: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/236713.

**Comment by tmeschter** [comment]
@davkean Will this bug be fixed "for free" when you fix #2733 or will we need to make further changes?

**Comment by davkean** [comment]
@tmeschter I'll need to make additional work, it will basically need to copy the pattern I've used for language service. I have this work on the back of my mind.

**Comment by davkean** [comment]
@drewnoakes This will be covered in the dependency node rewrite- can you move to appropriate milestone or dup against existing bugs.

**Comment by drewnoakes** [comment]
@lifengl identified a leaked `ProjectCatalogSnapshot` after changing configurations due to this bug. When we fix this, we should verify the leak is also addressed.

**Comment by drewnoakes** [comment]
Another repro:

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    </ItemGroup>

</Project>
```

Switch between release and debug configurations and the tree will not update.
