### ISSUE TITLE
Visual Studio 2017 15.7.3 .NET Core Workload installs .NET Core SDK 2.1.201 (.NET Core 2.0) instead of 2.1.300 (.NET Core 2.1)

### ISSUE THREAD

**Issue by MBODM** [dotnet/project-system#3643]
Hey,

the guys from the .NET Core team (https://github.com/dotnet/corefx/issues/30231) said i should maybe ask here:

As title says, you can download and install .net core sdk for 2.1 (named .net core sdk 2.1.300) manually from official MS .net core homepage. All fine and so. But normally Visual Studio do this via update and installer. So i installed Visual Studio 2017 15.7.3 this way (by updating or fresh install), the .net core workload of VS installs the .net core sdk 2.1.201 (latest .net core 2.0) instead of .net core sdk 2.1.300 (.net core 2.1). Why ?

Why does the VS workload target the old 2.0 sdk instead the new 2.1 sdk ? And when will this change ?

Problem is: Even when i install the new SDK manually (and i dont know if that cause problems when VS itself will install the same later, i.e. in 15.8, via Workload) then i have still the problem where i can get the templates for VS for ASP .NET Core 2.1 ? Otherwise i have to target 2.1 and make changes in .csproj by hand, everytime i do a new project. So, installing just the SDK solves not really the problem.

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#2323
