### ISSUE TITLE
RoslynInsertionTool needs to update binding redirects for Project System assemblies

### ISSUE THREAD

**Issue by tmat** [dotnet/project-system#3646]
VSO PR [127593](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/127593) adds 

```
const string MicrosoftVisualStudioProjectSystemVersion = "2.8.0.0";
```

to `/src/ProductData/AssemblyVersions.tt` file. This version needs to be automatically updated on Project System component insertion.

It would also be good to auto-update package versions in `default.config` to avoid having old binaries in External APIs:

```xml
   <package id="Microsoft.VisualStudio.ProjectSystem.Managed" version="2.6.0-beta3-62503-02" tags="exapis" link="src\ExternalAPIs\Microsoft.VisualStudio.ProjectSystem.Managed" />
    <package id="Microsoft.VisualStudio.ProjectSystem.Managed.VS" version="2.6.0-beta3-62503-02" tags="exapis" link="src\ExternalAPIs\Microsoft.VisualStudio.ProjectSystem.Managed.VS" />
```

**Comment by jmarolf** [comment]
fixed here: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/138417
