### ISSUE TITLE
Item templates are missing

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#365]
In the latest VS builds, clicking on AddItem doesn't show most item templates. This is with the new installer and maybe some setup authoring regression.

**Comment by 333fred** [comment]
Initial comments:
It appears as though this is something specific to the .NET Core template. If I create a standard Console app and throw a breakpoint in the AbstractAddClassProjectCommand handler, it gets hit (so I know that it's invoking our project system and not old csproj) and the templates show up correctly. I need to dig more into why the templates aren't showing up for .NET Core apps.

**Comment by 333fred** [comment]
I've tracked down why this is occurring. The existing template filtering mechanism that determines what templates to show to a project doesn't understand the difference between .NET Core and .NET Framework. In the filtering process, it only looks at the TFM version *number*, not the full TFM. The TFM version number for us is 1.0, and the minimum for almost all the preexisting templates is 2.0. Therefore, the templates don't show up. I've tested artificially increasing our version number to 3.0, and that does cause all the missing templates to show up again.

**Comment by davkean** [comment]
Great work!

Sri and I talked offline, there's a few things that I see are going to need to change with the templates:

1. We should remove the '<RequiredFrameworkVersion>2.0</RequiredFrameworkVersion>' from them; it's meaningless. We don't support .NET 1.x  templates anyway.

2. They also add references in some cases - in the case of Class.cs it adds System.dll - there's no such dll in .NET Core, it's not even needed for the template in full .NET Framework. We should remove them on a case-by-case basis.

3. In some cases, we won't want them to show up at - in these cases, we should make use of capabilities - to hide them from projects without those capabilities. Make note - in some cases, we'll need to extend the old project system to return these capabilities to make that happen.

**Comment by 333fred** [comment]
It appears that the file we need to edit, at least for the standard templates such as Class, is `VS_Install_Root\Common7\IDE\ItemTemplates\Microsoft.VisualStudio.Templates.CS.ManagedCore.Resources.en-US.Item..vstman`. VS appears to ignore the RequiredVersionNumber field in the actual vstemplate file, even if the RequiredVersionNumber field is entirely absent from the vstman file.

**Comment by 333fred** [comment]
This is a list of all templates showing up when adding a new item in an old csproj:

### Code
All of these are relevant, should have references to System removed and min version removed.

- [ ] Class
- [ ] Interface
- [ ] Code File

### Data
Some of these are relevant, at least the XML and XSLT templates. What do we think about the other 3?

- [ ] DataSet
- [ ] LinqToSQLObjects_CS
- [ ] Service-based Database
- [ ] XML File
- [ ] XML Schema
- [ ] XSLT File

### General
I believe most of these are relevant. Not sure about the Debugger Visualizer (depends on `System.Windows.Forms`), Installer Class (multiple assemblies that don't exist in core), Windows Script Host, or Windows Service (depends on `System.ServiceProcess`). For the RTT template, I believe we'll also need to add the `TextTemplatingFilePreprocessor` Single-File Generator.

- [ ] Component Class
- [ ] Application Configuration File
- [ ] Application Manifest File
- [ ] Assembly Information File
- [ ] Bitmap File
- [x] Code Analysis Rule Set
- [ ] Cursor File
- [ ] Debugger Visualizer
- [ ] Icon File
- [ ] Installer Class
- [ ] Resources File
- [ ] Runtime Text Template
- [ ] Settings File
- [ ] Text File
- [ ] Text Template
- [ ] Windows Script Host
- [ ] Windows Service
- [x] Directed Graph Document (.dgml)

### Windows Forms
Irrelevant

- [ ] ~~Inherited Form~~
- [ ] ~~Inherited User Control~~
- [ ] ~~Windows Form~~
- [ ] ~~About Box~~
- [ ] ~~Custom Control~~
- [ ] ~~MDI Parent Form~~

### WPF
Irrelevant

- [ ] ~~User Control (WPF)~~

### SQL Server
I believe this is irrelevant as well?

- [ ] SQL Server Unit Test

**Comment by 333fred** [comment]
@srivatsn @davkean The ones with ❓, I'm not sure whether we want them to show up or not. Input would be appreciated.

**Comment by 333fred** [comment]
Sri and I talked a bit offline. For now, what we're going to do is remove the min version from the templates here that we'd like to have show up. That'll get us enough filtering for it to everything to appear in preview 5, and then I'll move to higher priority stories for preview 5. Once that's completed, we'll circle back around and implement the capability-based filtering.

**Comment by davkean** [comment]
@srivatsn Don't agree on the priority - well want to remove the assembly references for at least the common templates such as interface, class, etc so that you don't get an error on adding them.

**Comment by srivatsn** [comment]
Yes I'm saying we should do the work needed to get the templates we want to show up. I was saying that if we need to introduce capabilities to filter out templates that dont apply to Core (say MDI parent form) let's instead filter for now based on TFM check and do the real work later.

**Comment by 333fred** [comment]
VBProj Templates:

| Category | Template Name | Status | References | Notes |
| --- | --- | --- | --- | --- |
| Code | Module | :construction: | N/A | |
| Code | Interface | :construction: | N/A | |
| Code | Component Class | :x: | `System` | |
| Code | Code File | :construction: | N/A | |
| Code | COM Class | :x: | N/A | |
| Code | Transactional Component | :x: | N/A | |
| Data | DataSet | :x: | `System`, `System.Data`, `System.Web.Services`, `System.Xml` | |
| Data | LinqToSQLObjects_VB | :x: | `System`, `System.Data`, `System.Xml` | Located in DataDesign |
| Data | Service-based Database | :x: | `System`, `System.Data`, `System.Xml` | |
| Data | XML File | :construction: | N/A | |
| Data | XML Schema | :construction: | N/A | |
| Data | XML To Schema | :construction: | N/A | |
| Data | XSLT File | :construction: | N/A | |
| General | Application Configuration File | :x: | N/A | |
| General | Application Manifest File | :construction: | N/A | |
| General | Bitmap File | :construction: | N/A | |
| General | Code Analysis Rule Set | :heavy_check_mark: | N/A | |
| General | Cursor | :x: | N/A | |
| General | Icon File | :construction: | N/A | |
| General | Installer Class | :x: | N/A | |
| General | Resources File | :construction: | N/A | |
| General | Runtime Text Template | :x: | N/A | |
| General | Settings File | :x: | N/A | |
| General | Text File | :construction: | N/A | |
| General | Text Template | :x: | N/A | |
| General | Windows Service | :x: | N/A | |
| General | Directed Graph Document | :heavy_check_mark: | |
| WPF | User Control (WPF) | :x: | `System`, `WindowsBase`, `PresentationCore`, `PresentationFramework` | |
| SQL Server | SQL Server Unit Test | :x: | N/A | |
| Windows Forms | Windows Forms | :x: | `System`, `System.Drawing`, `System.Windows.Forms` | |
| Windows Forms | User Control | :x: | `System`, `System.Drawing`, `System.Windows.Forms` | |
| Windows Forms | About Box | :x: | `System`, `System.Drawing`, `System.Windows.Forms` | |
| Windows Forms | Custom Control | :x: | `System`, `System.Drawing`, `System.Windows.Forms` | |
| Windows Forms | Dialog | :x: | `System`, `System.Drawing`, `System.Windows.Forms` | |
| Windows Forms | Explorer Form | :x: | `System`, `System.Drawing`, `System.Windows.Forms` | |
| Windows Forms | Login Form | :x: | `System`, `System.Drawing`, `System.Windows.Forms` | |
| Windows Forms | MDI Parent Form | :x: | `System`, `System.Drawing`, `System.Windows.Forms` | |
| Windows Forms | Splash Screen | :x: | `System`, `System.Drawing`, `System.Windows.Forms` | |
| Windows Forms | Inherited Form | :x: | `System`, `System.Drawing`, `System.Windows.Forms` | |
| Windows Forms | Inherited User Control | :x: | `System`, `System.Drawing`, `System.Windows.Forms` | |

**Comment by panopticoncentral** [comment]
The VS extensibility templates are also not showing up.

**Comment by davidwengier** [comment]
WPF item templates will be in a future release of 16.1. Windows Forms templates are still in progress.

**Comment by hicks86** [comment]
Just clarifying, that this is issue is also related to unit test templates not appearing for a .NET Core Unit Test projects (Add new item)?

**Comment by davkean** [comment]
@hicks86 please file a new bug around what templates you would like to see.

**Comment by jmarolf** [comment]
Fixed with [AD#175581](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/175581)

**Comment by tmeschter** [comment]
I've done some spot checking, and many of the things that were previously missing are now showing up. I'm going to close this issue in favor of creating new issues for specific missing templates (if any) as they come up.
