### ISSUE TITLE
Regression: files missing from solution explorer with multi-targeting

### ISSUE THREAD

**Issue by onovotny** [dotnet/project-system#3652]
This is broken with 15.7.3 and 15.8.2 p2 with .NET Core 2.1 installed. It used to work. I think that setting

`<EnableDefaultCompileItems>false</EnableDefaultCompileItems>` changed the behavior where files used to be visible.

The solution explorer is missing files that are specified by the include globs.

![image](https://user-images.githubusercontent.com/1427284/41444292-2e6a2c3a-7010-11e8-85a2-ca91922f16bd.png)

[ProjectSystemRegression.zip](https://github.com/dotnet/project-system/files/2104396/ProjectSystemRegression.zip)

Note that the project builds correctly, but files aren't visible in VS.

A workaround requires adding
`<None Include="**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />` to the project file, but I don't believe that used to be necessary, thus the regression.

Here's the csproj:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;Xamarin.iOS10;MonoAndroid81;uap10.0.16299</TargetFrameworks>
    
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="MSBuild.Sdk.Extras" Version="1.5.4" PrivateAssets="All" />
    
    <Compile Include="**\*.shared.cs" />
    <Compile Include="**\*.shared.*.cs" />
  </ItemGroup>
  <ItemGroup Condition=" $(TargetFramework.StartsWith('netstandard')) ">
    <Compile Include="**\*.netstandard.cs" />
    <Compile Include="**\*.netstandard.*.cs" />
  </ItemGroup>
  <ItemGroup Condition=" $(TargetFramework.StartsWith('uap10.0')) ">
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="6.0.8" />
    <Compile Include="**\*.uwp.cs" />
    <Compile Include="**\*.uwp.*.cs" />
  </ItemGroup>
  <ItemGroup Condition=" $(TargetFramework.StartsWith('MonoAndroid')) ">
    <PackageReference Include="Xamarin.Android.Support.CustomTabs" Version="27.0.2" />
    <PackageReference Include="Xamarin.Android.Support.Core.Utils" Version="27.0.2" />
    <Compile Include="**\*.android.cs" />
    <Compile Include="**\*.android.*.cs" />
  </ItemGroup>
  <ItemGroup Condition=" $(TargetFramework.StartsWith('Xamarin.iOS')) ">
    <Compile Include="**\*.ios.cs" />
    <Compile Include="**\*.ios.*.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildSDKExtrasTargets)" Condition="Exists('$(MSBuildSDKExtrasTargets)')" />

</Project>
```

What's interesting here is that there's some dynamic evaluation happening. It's not just `*.shared.cs` that's visible, but it matches on the first conditional item group as well and shows `*.netstandard.cs`. It does not show any of the subsequent ones though.

@jamesmontemagno

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#2337
