### ISSUE TITLE
SDK style F# projects return broken FileCodeModel from ProjectItem

### ISSUE THREAD

**Issue by jcansdale** [dotnet/project-system#3664]
Old style F# projects return `null` from `ProjectItem.FileCodeModel`.

I noticed that SDK style F# projects do return a `FileCodeModel`, but when I call `FileCodeModel.CodeElementFromPoint` it throws a `NullReferenceException` from:
```
Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.CodeElementFromPosition(Int32 position, vsCMElement scope)
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.CodeElementFromPoint(TextPoint point, vsCMElement scope)
at EnvDTE.FileCodeModel.CodeElementFromPoint(TextPoint Point, vsCMElement Scope)
```

I noticed the problem when working on TestDriven.Net.

I noticed that @StefanKert's [BuildVision](https://github.com/StefanKert/BuildVision) is also have problem with this project type:

```
---------------------------
BuildVision error
---------------------------
Unknown exception

Exception:
Object reference not set to an instance of an object.
StackTrace:
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelObject.get_Language()
   at EnvDTE.CodeModel.get_Language()
   at BuildVision.Helpers.ProjectExtensions.GetLanguageName(Project project)

Source:
EnvDTE

TargetSite:
System.String get_Language()

BaseException:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelObject.get_Language()
   at EnvDTE.CodeModel.get_Language()
   at BuildVision.Helpers.ProjectExtensions.GetLanguageName(Project project)
---------------------------
OK   
---------------------------
```

**Comment by davkean** [comment]
We should return null here to be consistent with legacy. The real change should be in Roslyn - project system is simply delegating onto Roslyn - it should be aware that F# doesn't implement symbol model.

**Comment by jcansdale** [comment]
@davkean Do you know if there's a built in alternative to `FileCodeModel` that I could use in F# projects? At the moment I'm using a horrible regex to scrape just enough symbol information when targeting an F# method. Unfortunately it's limited and there are plenty of times when it's not enough.

I basically need to find a `cref` token for the method/type the caret is inside. 🤞 there's a better solution!

**Comment by davkean** [comment]
tag @TIHan to answer that.

**Comment by Pilchie** [comment]
This is also internal bug [608759](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/608759).

**Comment by davkean** [comment]
This line needs to be changed to only be turned on for C# and VB: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectContextCodeModelProvider.cs#L17.
