### ISSUE TITLE
Splash screen drop-down is not sorted

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3666]
I expected the Splash-screen drop-down on the Project Properties -&gt; Application tab to be sorted alphabetically. It's hard to find a form, when there are many.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/60441/splash-screen-drop-down-is-not-sorted.html
VSTS ticketId: 439942_
_These are the original issue comments:_

Allison Buchholtz-Au [MSFT] on 5/24/2017, 03:33 PM (390 days ago): <p>Thank you for your feedback! For us to investigate this further, could you please provide the type of project that you're working on and the coding language?  We look forward to hearing from you!</p>

Blair Wang-MSFT [MSFT] on 6/14/2018, 11:02 PM (4 days ago): Thank you for your feedback! Unfortunately, right now we don't have enough information to investigate this issue and find a solution. If this is still an issue for you, please update to our latest version. If you are still able to repro it, please provide us with more info! Thank you for helping us build a better Visual Studio!

Mikhail on 6/16/2018, 02:34 PM (2 days ago): <p>Create a Windows Forms project with a number of forms. In the project's Properties one can choose one of these forms to be a splash screen.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by davkean** [comment]
This was fixed in https://github.com/dotnet/project-system/pull/3770.
