### ISSUE TITLE
Default "Define DEBUG constant" value is not read correctly in property pages

### ISSUE THREAD

**Issue by nguerrera** [dotnet/project-system#3674]
I believe this started happening with #3579. It is related to a lot of discussions we've been having.

The framework defines were not the only ones being added in targets. The configuration define has been in targets since 15.0/1.0: https://github.com/dotnet/sdk/pull/565

From recent discussions, I know we can argue with hindsight that the SDK shouldn't have done this in targets, but moving it to props now is breaking. I'm particularly worried about case where configuration might get set to different value in body of csproj.

## Setup
Microsoft Visual Studio Enterprise 2017 Int Preview (Dogfood)
Version 15.8.0 Preview 3.0 [27820.1.d15.8]
VisualStudio.15.IntPreview/15.8.0-pre.3.0+27820.1.d15.8

## Repro steps

* File -> New Project -> .NET Core -> Console App
* Right click project -> Properties
* Double check that configuration is set to Active (Debug)
* Inspect "Define DEBUG constant"

## Expected result

"Define DEBUG constant" is checked as it is populated by default in sdk props

## Actual result

"Define DEBUG constant" is unchecked. 

Despite that, you can see that `#if DEBUG` is working as expected in code.

Checking the box yourself will add the following unnecessary code to the .csproj

``` xml
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
```

**Comment by nguerrera** [comment]
I think the best fix here is possibly to hide the checkbox altogether for projects based on a capability that SDK would set. SDK projects don't really have a "debug constant" concept, they have a more general "implicit configuration constant". Release config gets RELEASE define, SomeCustomConfg get SOMECUSTOMCONFIG define. You can disable it with DisableImplicitConfigurationDefines=true, which could have a checkbox, but I don't think there's much value in that.

**Comment by drewnoakes** [comment]
We will improve this in the new project property UI.

**Comment by drewnoakes** [comment]
More support for this issue in feedback ticket: https://developercommunity2.visualstudio.com/t/Define-DEBUG-constant-is-not-checked-for/760022

**Comment by jjmew** [comment]
We improved the experience in the new UI Project Properties. We won't fix this for legacy.

**Comment by russellfoster** [comment]
> We improved the experience in the new UI Project Properties. We won't fix this for legacy.

Could you please elaborate on what is "new" and what is "legacy". I am seeing this behavior in VS 2019 16.11.17.

**Comment by drewnoakes** [comment]
@russellfoster the new property pages first shipped in VS2022.
