### ISSUE TITLE
By default "Auto-generate binding redirects" shows up as indeterminate

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3675]
1. File -> New Project -> Console App (.NET Core)
2. Open Properties Pages

Expected:
To be checked or unchecked

Actual:
![image](https://user-images.githubusercontent.com/1103906/42014445-b74658b4-7ae5-11e8-9565-252860d92c08.png)

**Comment by Pilchie** [comment]
This was fixed because the checkbox is now hidden.
