### ISSUE TITLE
"Auto-generate binding redirects" can be turned on for .NET Core projects and incorrectly produces an app.config

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3677]
1. File -> New Console App (.NET COre)
2. Project Properties -> Check "auto-generate binding redirects"
3. Build

Expected:
Ignored?

Actual:
An app.config is generated even though this platform does not use app.configs, nor respect the bindings.

**Comment by Pilchie** [comment]
@nguerrera Do you concur that this would be an SDK change?  @wli you were looking at other binding redirect changes in the SDK, right?

**Comment by davkean** [comment]
This no longer repros in 16.5 Preview 3.

**Comment by jzabroski** [comment]
@davkean Can you confirm that AutoGenerateBindingRedirects should only work for legacy .NET Framework apps?  I thought for sure you couldn't use this feature in .NET Core (and assuming .NET 5).  I had a user/customer of FluentMigrator who to my shock shared the following csproj with me:

```c#
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netcoreapp3.1</TargetFramework>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="FluentMigrator.Runner" Version="3.2.9" />
	</ItemGroup>
</Project>
```
