### ISSUE TITLE
Setting RunCommand/StartProgram on ClassLibrary doesn't work in new project system

### ISSUE THREAD

**Issue by eerhardt** [dotnet/project-system#3684]
In the old .csproj, you could set the following properties on an `<OutputType>Library</OutputType>` project:

- StartAction = Program
- StartProgram 
- StartArguments 
- StartWorkingDirectory 

And when you F5'd in VS, it would launch the `StartProgram` as expected.

In the `Microsoft.NET.Sdk`, it translates these properties to the new `RunCommand`, `RunArguments` and `RunWorkingDirectory` properties that are used as the contract between the MSBuild project and both VS and `dotnet run` for how to execute/run the project.  
See https://github.com/dotnet/sdk/blob/0af8aa984773c32752634a62c87edcceedcb93e3/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L387-L397

However, the project-system explicitly blocks F5'ing an project with `<OutputType>Library</OutputType>`.

https://github.com/dotnet/project-system/blob/47787b324c22ee2bf03f889e07f88ce51738cbe2/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs#L228-L235

This kind of limiting shouldn't be done by the project-system. If the project returns a valid `RunCommand`, the project-system should run it, no matter what the `<OutputType>` is set to.

This is a breaking change from the old project system to the new.  Setting `StartAction` and `StartProgram` should "just work" in the new project system.

/cc @BillHiebert

**Comment by Pilchie** [comment]
@davkean just changed some of this code I thought too.

**Comment by Pilchie** [comment]
Also, pretty sure that if you specify a program in your launchSettings.json this will work, though you'd have to duplicate what you had in the .csproj.

**Comment by Pilchie** [comment]
Also, pretty sure that if you specify a program in your launchSettings.json this will work, though you'd have to duplicate what you had in the .csproj.

**Comment by eerhardt** [comment]
> if you specify a program in your launchSettings.json this will work, though you'd have to duplicate what you had in the .csproj.

The scenario I ran into this is with `dotnet/corefx` test projects. We are setting `StartAction` and `StartProgram` to allow developers to `F5` the test projects, which then invokes the `xunit` console runner.  (Yes, we want to get this integrated into Test Explorer, but we can't change everything all at once. Moving to SDK-style projects and the new project system is the first step.)

`dotnet/corefx` has on the order of 100 test .csprojs, and the MSBuild options are set in .targets files. So duplicating this information in ~100 launchSettings.json files doesn't seem realistic.

**Comment by Pilchie** [comment]
Not idea, but possible - https://github.com/dotnet/roslyn/pull/21014

**Comment by davkean** [comment]
This was fixed in https://github.com/dotnet/project-system/pull/3768, back in 16.0.
