### ISSUE TITLE
Always show project name in project references

### ISSUE THREAD

**Issue by SabotageAndi** [dotnet/project-system#3685]
Repro- project: https://github.com/SabotageAndi/WeirdProjectReferencesResult

I have to admit it's a little bit weird project setup, but I think Visual Studio should display the name of the referenced projects also in this consistent.

Project setup:
3 class libraries with different name, but same AssemblyName are referenced by a fourth class lib.

See this screenshot:
![image](https://user-images.githubusercontent.com/859801/42165497-822dffb2-7e08-11e8-9dc8-e6a8f526bf54.png)

WeirdProjectReferencesResult.ChildC is displayed with it's assembly name, WeirdProjectReferencesResult.ChildA & WeirdProjectReferencesResult.ChildB is displayed with the project name.

When you now add an additional console project, which references WeirdProjectReferencesResult and WeirdProjectReferencesResult.ChildC this is displayed:
![image](https://user-images.githubusercontent.com/859801/42165587-cbe16072-7e08-11e8-87f7-3bf5288cd99d.png)

Background why I have this references: They are only there, to get a build dependency. So WeirdProjectReferencesResult.ChildA, WeirdProjectReferencesResult.ChildB and WeirdProjectReferencesResult.ChildC are build before WeirdProjectReferencesResult.

Expected behavior of Visual Studio: Always display the project name in the references. This makes it much more clearer if you change the assembly name in a project.

**Comment by Pilchie** [comment]
@abpiskunov / @davkean thoughts on showing project name instead of assembly name?

**Comment by davkean** [comment]
Yeah, always show project name.

**Comment by abpiskunov** [comment]
Logic in VS doe snot know if it is project or assembly name, it is just receiving ItemSpec and OriginalItemSpec from DT build for project items. Then it just gets a file name out of the path that is specified there.

**Comment by davkean** [comment]
By project name, I'm referring to "original item spec".

**Comment by abpiskunov** [comment]
Ah , then it should be pretty easy change in the project dependency model, it uses ItemSpec now.

**Comment by davkean** [comment]
I think we should favor using evaluation result in "original item spec", similar to what legacy does.
