### ISSUE TITLE
When adding a project to a solution with only x86 projects the AnyCPU platform is added back to solution for every project

### ISSUE THREAD

**Issue by maxinfet** [dotnet/project-system#3695]
I am not sure if the project system is the right place to ask this question since I am not sure if .sln falls under the project system, sorry if this is not the right place.

I am trying to make a solution that only targets x86 since almost all our dependencies depend on a project which depends on an x86 COM dll. When we add any new project it will add back AnyCPU as a platform for every single project but only in the solution file. We 70+ projects in our solution and it is very tedious to remove all these lines. Is some kind of configuration I could do to prevent the AnyCPU platform from being added when a new project is added?

We are on the old project system if that has any bearing on this.

**Comment by Pilchie** [comment]
Unfortunately that configuration management isn't part of the project system.  I'm tagging @lifengl for awareness, but I'd also recommend using VS to report a feedback item.  That creates an issue that I can route to the right team.

**Comment by maxinfet** [comment]
@Pilchie Thank you, I will do that.

**Comment by StingyJack** [comment]
It should be noted that UserVoice is no longer the place to log suggestions (IMO this is a bug), and the UV item referenced in the link above (and all its votes) has not been carried over to the [new place](https://developercommunity.visualstudio.com/spaces/8/index.html). I've [requested that it be moved](https://developercommunity.visualstudio.com/content/problem/369736/please-transfer-this-uservoice-item-and-all-its-vo.html)
