### ISSUE TITLE
Multi targeting project with conditionally included files is not recompiled

### ISSUE THREAD

**Issue by MichaelRumpler** [dotnet/project-system#3717]
I have a Xamarin.Forms solution with multiple normal projects for each platform and one multi-targeting project for all platforms.

In the multi .csproj I have ItemGroups like this for each platform:

    <ItemGroup Condition=" $(TargetFramework.StartsWith('net4')) ">
        <PackageReference Include="Xamarin.Forms.Platform.WPF" Version="3.0.0.482510" />
        <Compile Include="WPF\**\*.cs" />
    </ItemGroup>

If I change something in the WPF folder and press F5 (the WPF project is the startup project), then the multi-targeting project is not automatically recompiled and the app starts at once. I have to manually rebuild the project before starting it with F5.

The same happens if the UWP project is the startup project and I change something in the UWP folder.
But I also have an "All" Folder which compiles its files for all platforms. If I change something there, then the project is recompiled automatically.

I tested this with VS versions 15.7.3 up to 15.8.0 preview 4. I already [filed this issue in VS](https://developercommunity.visualstudio.com/content/problem/268967/multi-targeting-project-with-conditionally-include.html) a month ago, but unfortunately it needed that long before someone told me that it belongs here.

**Comment by davkean** [comment]
Thanks, this is known and tracked with https://github.com/dotnet/project-system/issues/2487.
