### ISSUE TITLE
XamlAppDef not available

### ISSUE THREAD

**Issue by lokki** [dotnet/project-system#3722]
We are in a process of converting a few large-ish solutions to the SDK project format. A few of those contain Workflow Foundation workflow definitions in .xaml files. These should be using the XamlAppDef build action but it's not available in the new projects:
<img width="352" alt="new" src="https://user-images.githubusercontent.com/1587351/42652929-eb5892c8-85e1-11e8-9c86-37c715461331.png">
vs old format:
<img width="350" alt="old" src="https://user-images.githubusercontent.com/1587351/42652956-f548b8e4-85e1-11e8-9976-2494fbe51ccb.png">

Why is XamlAppDef not available? If XAML is not supported then why are Page and ApplicationDefinition available in the new format?

Thanks

**Comment by davkean** [comment]
We don't respect [AvailableItemName](https://github.com/dotnet/project-system/issues/113) yet so they need to manually added to support. What is XamlAppDef used for?

**Comment by lokki** [comment]
It is used for the Workflow Foundation workflows which are defined in .xaml files. Without it they won't compile

**Comment by lokki** [comment]
@davkean is there any chance it's a quick fix I can do myself? Or tooling/project system change needs to happen first?
Thanks

**Comment by davkean** [comment]
If you add the following experimental feature to your project, these items should show up:

``` XML
<ItemGroup>
    <ProjectCapability Include="ShowMissingItemTypes" />
</ItemGroup>
```

Note: This feature hasn't been fully tested yet, so might have bugs.

**Comment by wjk** [comment]
@davkean I wrote an initial implementation of adding this item type as XAML. [You can find it in my branch](https://github.com/wjk/dotnet-project-system/tree/XamlAppDef). It all seems to work just fine, except when I switch the item's type from "None" to "Workflow definition" in the Properties panel the XAML file disappears from the Solution Explorer! I must turn on Show All Files for the file to reappear, and right-clicking > Include in Project do nothing. I have not figured out why this is happening. The only thing I can do to make the XAML file reappear is to change its item type back to None, which of course defeats the whole point. Once we've figured out how to squash this, I can send in a PR. Thanks!

**Comment by davkean** [comment]
@wjk This occurs because you need to include the rule in https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L118

**Comment by wjk** [comment]
@davkean Oh, _that's_ what was going on! I'll have a PR in shortly. Thanks!

**Comment by davkean** [comment]
Fixed with https://github.com/dotnet/project-system/pull/3810.
