### ISSUE TITLE
"Auto-binding redirects" visible in .NET Core projects project's properties

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3735]
![image](https://user-images.githubusercontent.com/1103906/42796790-70956088-89cf-11e8-97b9-3605f4326a1a.png)

@tmeschter @Pilchie

**Comment by davkean** [comment]
This is not because it's not marked as visible=false: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml#L57.

**Comment by Pilchie** [comment]
Not sure if fixing this will meet the bar for 15.8, but we can try.

**Comment by Pilchie** [comment]
@tmeschter you fixed this, right?

**Comment by davkean** [comment]
This is not fixed in 15.8.0 Preview 5.0 [27922.0.d15.8].

**Comment by tmeschter** [comment]
@Pilchie No, what was fixed was showing the check box when opening the Application property page.

Do we still want to try and take a fix for 15.8?

**Comment by Pilchie** [comment]
Sorry - misread the bug.  I think this is fine to fix in Dev16.

**Comment by davkean** [comment]
I would have preferred this in 15.8, I've submitted for 15.9: https://github.com/dotnet/project-system/pull/3793.

**Comment by davkean** [comment]
Fixed in https://github.com/dotnet/project-system/pull/3793.
