### ISSUE TITLE
Resource items do not appear in the Solution Explorer in F#

### ISSUE THREAD

**Issue by saul** [dotnet/project-system#3740]
It looks like `<Resource>` files do not show in the Solution Explorer (but are passed to the compiler at build time) in F# projects.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Foo.xaml" />
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
```

Any idea what's causing this? EmbeddedResource items show in the Solution Explorer fine.

This project worked fine with the legacy project system.

Thanks
Saul

**Comment by Pilchie** [comment]
Possibly related to https://github.com/dotnet/project-system/issues/3620?

As @davkean notes, in the new project system right now, if there isn't a rule that mentions that item type.  We're considering changing that to show any explicitly added item by default though.

@davkean what's the workaround here?
