### ISSUE TITLE
When editing the project file, Build Selection (Shift + F6) is not available

### ISSUE THREAD

**Issue by kzu** [dotnet/project-system#3742]
While editing any file in a project, `Shit + F6` is a quick way to ensure everything is in working order by triggering a build of the containing project. This gesture is even more important when editing the project file (without unloading the project, obviously), yet it's grayed out and the shortcut obviously doesn't do anything, even though the selected node in the solution explorer is the right project:

![image](https://user-images.githubusercontent.com/169707/42835349-f214e4ae-89ce-11e8-8624-3443c46ff88a.png)

Happens in all versions of VS2017 and even vNext as of now.

**Comment by davkean** [comment]
This is caused by Issue 1 as called out in https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/124985?_a=overview:

> 1. If the project file is open and active, Monitor Service thinks Solution is the active hierarchy and not the project.

Lots of issues like this will be resolved once we've moved the owning hierarchy in the _running document table_ from the solution to the project itself.

**Comment by davkean** [comment]
Duping against https://github.com/dotnet/project-system/issues/4067 which represents the actual change to fix this.
