### ISSUE TITLE
F# - Pasting items that are outside of the project into a F# project results in a watson

### ISSUE THREAD

**Issue by TIHan** [dotnet/project-system#3752]
After some dogfooding, I noticed that pasting an item that doesn't exist in a project into a F# project will result in a watson.

**Comment by Pilchie** [comment]
@TIHan the fix for this was inserted in 15.8 and this can be closed, right?

**Comment by TIHan** [comment]
I assume so since it was merged into dev15.8.x

**Comment by davkean** [comment]
Fixed by https://github.com/dotnet/project-system/pull/3753.
