### ISSUE TITLE
Windows Forms designer doesn't understand PackageReference

### ISSUE THREAD

**Issue by wjk** [dotnet/project-system#3754]
Apologies if this is the wrong repo, but I don't know a better place to file this.

The title says it all, really. When using an old-style csproj (since the new project system doesn't support the Forms designer yet), and I add a NuGet package containing a Windows Forms control to my project, if I am using the PackageReference NuGet resolver, the item doesn't automatically appear in the Toolbox. [This the only workaround I have seen](https://docs.microsoft.com/en-us/windows/uwpcommunitytoolkit/controls/webview#add-the-webview-control-to-the-visual-studio-toolbox), and it is extremely painful.

IIRC, the deprecated packages.config-based way of doing NuGet packages populated the Toolbox automatically. If I have to hazard a guess, this is because the packages.config NuGet resolver added the `<Reference />` MSBuild items directly to the csproj, where the Forms designer looks for them. However, PackageReference-based projects add the references into an implicitly included targets file, which the Forms designer is not aware of. Would it be at all possible to get this fixed? This will become extra annoying once Forms for .NET Core 3 enters beta, as I will be adopting that technology the day is is released. Thanks!

**Comment by tmeschter** [comment]
@wjk Could you try this again? I've just tried this on VS2017 15.8.5 and I'm able to see the WinForms controls in the Toolbox right after adding the package as a `PackageReference`.

If it still doesn't work, can you point me at the package you are trying to install?

**Comment by wjk** [comment]
@tmeschter You're right, it has been fixed in the interim. I'm going to close the issue now. Thanks for looking into this!
