### ISSUE TITLE
VS build failed but using dotnet build is ok，about conditional ProjectReference

### ISSUE THREAD

**Issue by r0nn** [dotnet/project-system#3758]
Add a conditional ProjectReference to .csproj, want to add reference only when build:
`
<ProjectReference Condition="$(DesignTimeBuild) != true" Include="..\***\***.csproj" />
`

When F5 or build, the referenced project was not build, and CSC complain referenced dll not found in referenced project's output dir:
`
CSC : error CS0006: 未能找到元数据文件“D:\work\**\***\bin\Debug\netcoreapp2.1\***.dll”
`

If build the referenced project first manually, build is ok, but the referenced project dll can't be found in DependencyContext.Default.CompileLibraries, dll has copied to output dll automaticlly.

Build using dotnet build then above problem all gone.

**Comment by davkean** [comment]
What exactly are you trying to do? That won't work - Visual Studio won't see the project and does not know that it needs to build it.

**Comment by r0nn** [comment]
I want to avoid project reference in design-time, separate the abstractions and implements, use IOC container to inject implements in runtime. 

So I want to add ProjectReference only when build, the "Condition="$(DesignTimeBuild) != true" works fine using dotnet build.

**Comment by davkean** [comment]
Use solution dependencies (Right-click Solution -> Project Dependencies), or use [ReferenceOUtputAssembly](https://blogs.msdn.microsoft.com/kirillosenkov/2015/04/04/how-to-have-a-project-reference-without-referencing-the-actual-binary/). Above is going to prevent Visual Studio from seeing the reference and hence will not build it.

**Comment by r0nn** [comment]
What I mean is "Condition="$(DesignTimeBuild) != true" should work as expected, and it's correctly resolved by Intellisense,

When 
`
"Condition="$(DesignTimeBuild) != false"
`
the project reference is show up in solution explorer's dependencies tree,  $(DesignTimeBuild) will be true only set by Intellisense,  and that's why dotnet build works, VS build should have same behavior, right?

**Comment by davkean** [comment]
Command-line build builds references when it encounters them via a ProjectReference. Visual Studio builds up a graph of references and builds them in dependency order. It does this for a variety of reasons, one being history (it's done that for 15 years) and the other because it results in a better user experience inside VS. 

`DesignTimeBuild` property isn't only set for IntelliSense, we set `DesignTimeBuild` when we evaluate the project inside Visual Studio to figure out what references a project has, at that point, these references are not showing up.

**Comment by r0nn** [comment]
I just try to change the condition to:
`
<ProjectReference Condition="$(DesignTimeBuild) == true" Include="..\***\***.csproj" />
`
then dotnet build not add reference and not build the project, Condition work as expected.

**Comment by davkean** [comment]
I'm not following what you are trying to indicate.

**Comment by r0nn** [comment]
I just want to figure out that conditions on ProjectReference should work.

**Why I want this work:**
The dependency inversion principle states that your application’s abstractions should not depend on implementation details.
Says there is three projects in solution for example: App for application, Core for abstractions, Infra for 
implementations.
App should reference Core only but not reference Infra, only use Infra at runtime, using IoC to inject.
Somewhat like a plugin system, usually your may dynamic load dlls whille running, find dll in directory or whatever.
In my current project I just want to avoid reference Infra project, to prevent a developer from accessing Infra's codes from App.  Add reference while build is acceptable, and this make assembly loading, dependency resolving, IoC register much easier.
 
**What I expect:**
 - conditional ProjectReference works
 - no Infra project reference when coding in VS, IntelliSense
 - project referenced while building

donnet cli works as excepted, I have got a tricky workaround, add a dotnet build script in PreBuildEvent.

So I open this issue, thought that may be a bug.

**Comment by davkean** [comment]
Conditional references work in Visual Studio; you are just using a property that has special meaning to Visual Studio; `$(DesignTimeBuild)` is used more than just for IntelliSense.

What you are asking isn't really a "supported" scenario - but you might be able to mimic this using "ReferenceOutputAssembly" and flipping it based on DesignTimeBuild. However - we're going to give you background IntelliSense errors if you open a source file that references any types from that assembly.

**Comment by r0nn** [comment]
Ok, got it.
