### ISSUE TITLE
Convert ResourceEditor to WPF-based UI?

### ISSUE THREAD

**Issue by wjk** [dotnet/project-system#3765]
I was considering rewriting the ResourceEditor in WPF & XAML, because I personally find the old, crufty Windows Forms-based UI to be difficult to work with. I have a pretty solid idea of how I would go about doing this, but I still have a few questions.

Mainly, I want to know how I should integrate the XAML files into the build process, given we use SDK-style projects. The way I handle this in my personal projects is to use @onovotny's [excellent `MSBuild.Sdk.Extras` package](https://github.com/onovotny/MSBuildSdkExtras). Using this SDK instead of `Microsoft.NET.Sdk`, I would add literally one line of code in the csproj/vbproj file and everything would "just work." However, I don't know if it is acceptable to take this dependency. (The one "gotcha" with using this package is that you can't mix-and-match Windows Forms support and WPF support in a single project that uses it. However, seeing as the Forms designer doesn't work with an SDK-style project anyways, we lose very little due to this issue.) Note that this SDK does not have any effect at runtime in the slightest; it is purely a build-time construct.
 
Is there anything else I should know before starting work on this, or should I just dive right in? Thanks!

**Comment by davkean** [comment]
This a large non-trivial effort that will require a long back and forth between us and yourself. While it might seem cheap and easy to implement, there's many hidden things behind the scenes that make it a larger work item than it seems, including accessibility, localization, high-DPI awareness, security & performance. This one is particularly difficult, as it will be a WPF designer, hosted sometimes within a WinForms control (property pages) which it itself is hosted in WPF. There's a large risk for regressing behavior for a designer that isn't well unit tested. 

I'd like to see some smaller things bitten off first so that we understand each other's working & review style before you dive heads into this.

**Comment by wjk** [comment]
Yeah, I came to the same conclusion after looking at some of the existing code. My existing concerns/complaints with the resource editor can be summarized as such:

1. The pop-up menu that is used to select the type of resource (strings/images/icons/etc) is really poorly designed. It is actually a split-button, but the "button" part of it does absolutely nothing when clicked. You need to click on the five-pixel-wide arrow part of the control to get the menu to appear. I have no idea why it was implemented this way; I was planning on changing it to be a standard drop-down menu instead.
2. The DataGrid control used to edit strings is very clunky, which is annoying as the string editor is oftentimes the editor used the most (at least in my projects). Would it be possible to migrate this part of the resource editor to a different Windows Forms-based design? I could provide a mockup of what I have in mind once I get off work today. This might well be more practical than rewriting the entire designer.

**Comment by davkean** [comment]
The toolbar is a Visual Studio command bar, it's defined in a VSTC that isn't yet open source (Microsofties, it lives in the VS repo under src/wizard/vbdesigner/designerui/Menus.vsct). It's currently a MenuControllerLatched, I've not an expert on VS command-bar extensibility, but if there is a Win32-like drop down style (I suspect there isn't), I'll be open to making that change myself.

With regards to DataGrid, what control are you thinking about or are there examples elsewhere in VS for this sort of thing that are better? A (new) custom-drawn control is a lot of work to support high-DPI, right-to-left & accessibility. Even as we speak, accessibility changes & high DPI changes are being made to built-in WinForms & WPF controls.

**Comment by wjk** [comment]
@davkean Having consulted the VSCT docs, I don't think there is a non-split-button style available either. I don't know if the "Menu" style [described here](https://docs.microsoft.com/en-us/visualstudio/extensibility/menu-element) would be sufficient or not. I'm not near my VS dev box at the moment, so I can't test this myself. Nor do I know if a combo box control (such as the one used to change the code-generation setting) would work.

That being said, is there a way to force the drop-down menu to appear from code? If so, would it be possible to add an event handler that causes the drop-down menu to appear when the button part of the control is clicked? I just think that having to click _exactly_ on the five-pixel-wide arrow, and not on the button itself, is annoying and bad UX. Having the button be technically a separate control, but one that still shows the menu as if I clicked on the arrow, would be an acceptable compromise.

@jmarolf I was thinking of a UI created by composing several pre-existing Windows Forms controls, something like this:

* A `TableLayoutPanel` would be used to display a series of `TextBox` and `Button` controls in a spreadsheet-like format. From left to right, per row, we would have the following: Name text box, Value text box, Comment text box, Delete button. The Delete button would remove the row it is contained in (and, by extension, the back-end value from the resx file) when clicked.
* At the very bottom (below the last row of text boxes) is an Add button that would append another row of text boxes (as well as a new blank value to the resx file) when clicked.
* Everything is contained in a scrollable panel.
* Tab-navigation would move in the following order: name box, value box, comment box, delete button, next row's name box, and so on, with the add button as the last tab-visible control in the editor.

Drawing something entirely custom was never my plan, for the reasons you highlighted above. I don't know how practical this approach would be to implement. Hope this helps!

**Comment by jmarolf** [comment]
@wjk would you be willing to do a UI mockup for this?

**Comment by wjk** [comment]
I can certainly do so over my lunch break. Give me a few hours first. Thanks!

**Comment by wjk** [comment]
@jmarolf Here's my mockup:

<img width="567" alt="UI mockup" src="https://user-images.githubusercontent.com/1915951/43147447-0da6b550-8f31-11e8-9a85-a68126c6853b.png">

**Comment by wjk** [comment]
@mikedn Yeah, I agree. I now think a better use of my time would be to investigate how to make the DataGrid more usable, rather than try to replace it wholesale. I'll file/comment on issues for specific complaints instead. I'm going to close this issue if it's OK with you. Thanks for bearing with me!
