### ISSUE TITLE
Rebuild All is skipped by non-net core projects when one old project format is in sln

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/project-system#3773]
We have adopted the new project system on all of our projects, however we have one project that has reports from a vendor that uses windows forms to do reports. This project was converted to the new project system and we understood the design time limitations of this. We have tried the reports project in the older project format, but there is a problem. When we issue the rebuild all with the reports project in the new project format everything builds fine, but when we use the old project format all projects but .net core projects fail to rebuild. The message for the projects that are not .net core project shows "Skipped Rebuild All", and so most of our projects don't build. We are using the new project system on all but our reports project. What could be causing this?

Forgot to add when we do a clean the same thing happens, on all non-net core projects the clean is skipped. All of our projects are set to any cpu, as is the sln.

**Comment by dgxhubbard** [comment]
By taking our report definition out of this sln, the rebuild and clean issue goes away. The sln has .net standard library projects and .net framework projects, and every project is in the new project format, except the assembly project with report definitions.

**Comment by davkean** [comment]
"Skipped Rebuild" usually means the project is not set to build. Right-click on Solution, and choose **Configuration Manager...** and make sure the project has a checkmark next it in under the **Build** column.

**Comment by dgxhubbard** [comment]
I had moved the report def project into another sln to get around the rebuild issue. Then to look at the configuration manager I re-added it to our the sln it was in and it is checked. Then I cleaned and rebuilt and the issue has gone away. Not sure what the remove and re-add of the project did but it appears to work now.

**Comment by davkean** [comment]
The remove and add would have caused that checkbox to get checked again, as its the default.

**Comment by dgxhubbard** [comment]
thanks for the help
