### ISSUE TITLE
Add analyzers to catch incorrect usage within tree

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3777]
I see the same bugs over and over again. We should write tests or analyzers to catch them so that new devs don't run into them:

- Use IProjectAccessor over IProjectLockService. This avoids skipping:
  - Checkout from source control on write 
  - Call to ReleaseAsync to avoid blocking a thread pool thread on release of the lock

- Use/centralized usage of MSBuild construction model. This makes sure that we:
  - Escape/Unescape values
  - Implement the same behavior of walking, looking for properties, items, etc.

- Use ISafeProjectGuidService vs IProjectGuidService, IProjectGuidService2. This avoids:
  - Reading the GUID before we've been set it in the cases where the solution gives us a new one

- Use IUnconfiguredProjectTasksService.ProjectLoadInHost vs IProjectAsyncLoadDashboard.ProjectLoadInHost. This handles:
  - The situation where the project is closed before it has finished loading, instead of waiting forever.

- Use IUnconfiguredProjectTasksService.LoadedProjectAsync vs CommonProjectSystemTools.LoadedProject<T>.
  - This interface is unit testable.

- Use IProjectDynamicLoadComponent vs [ProjectAutoLoad] and [ConfiguredProjectAutoLoad]. This avoids accidently reloading the project while loading, switching branches, installing NuGet package, etc.

- Reading TargetFramework/TargetFrameworks properties. Only the configuration service should read these properties. Everyone else should be looking at "isVariantDimension" dimensions, or TargetFrameworkMoniker - and not know anything about these properties.

**Comment by Pilchie** [comment]
I can try to work on this a little bit.

**Comment by davkean** [comment]
What always prevented me from doing this, is there a way to consume this from the same solution that you build them in?

**Comment by davkean** [comment]
What might be interesting, is a way to mark an API as obsolete that you don't have access to - that way, you right the rule once and we just obsolete all the replement APIs with the new ones.

**Comment by Pilchie** [comment]
Not as P2P refs, no. You’d have to package them and refer to an LKG version.

**Comment by Pilchie** [comment]
Have some of these set up in [this branch](https://github.com/Pilchie/project-system/tree/UseBannedApiAnalyzer).  Results below.
 
Need more specifics about the MSBuild construction model, and the TargetFramework/TargetFrameworks properties.  Also need to flesh out the analyzer to allow finding members, (and the places it doesn't catch yet).

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	RS0030	The symbol 'CommonProjectSystemTools' is banned in this project	Microsoft.VisualStudio.ProjectSystem.Managed	C:\Code\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\LanguageServices\LanguageServiceHost.cs	112	Active
Warning	RS0030	The symbol 'CommonProjectSystemTools' is banned in this project	Microsoft.VisualStudio.ProjectSystem.Managed	C:\Code\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\LanguageServices\LanguageServiceHost.cs	236	Active
Warning	RS0030	The symbol 'IProjectLockService' is banned in this project	Microsoft.VisualStudio.ProjectSystem.Managed	C:\Code\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\ProjectAccessor.cs	35	Active
Warning	RS0030	The symbol 'IProjectLockService' is banned in this project	Microsoft.VisualStudio.ProjectSystem.Managed	C:\Code\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\ProjectAccessor.cs	51	Active
Warning	RS0030	The symbol 'IProjectLockService' is banned in this project	Microsoft.VisualStudio.ProjectSystem.Managed	C:\Code\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\ProjectAccessor.cs	67	Active
Warning	RS0030	The symbol 'IProjectLockService' is banned in this project	Microsoft.VisualStudio.ProjectSystem.Managed	C:\Code\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\ProjectAccessor.cs	83	Active
Warning	RS0030	The symbol 'IProjectLockService' is banned in this project	Microsoft.VisualStudio.ProjectSystem.Managed	C:\Code\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\ProjectAccessor.cs	99	Active
Warning	RS0030	The symbol 'IProjectLockService' is banned in this project	Microsoft.VisualStudio.ProjectSystem.Managed	C:\Code\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\ProjectAccessor.cs	122	Active
Warning	RS0030	The symbol 'CommonProjectSystemTools' is banned in this project	Microsoft.VisualStudio.ProjectSystem.Managed	C:\Code\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\UnconfiguredProjectTasksService.cs	52	Active
Warning	RS0030	The symbol 'CommonProjectSystemTools' is banned in this project	Microsoft.VisualStudio.ProjectSystem.Managed	C:\Code\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\UnconfiguredProjectTasksService.cs	59	Active
```

**Comment by drewnoakes** [comment]
Here's a draft of what the ban file would look like based on the above:

```text
T:Microsoft.VisualStudio.ProjectSystem.IProjectLockService; Using IProjectAccessor enables checkout from source control on write, and allows async release

T:Microsoft.VisualStudio.ProjectSystem.VS.IProjectGuidService; Using ISafeProjectGuidService avoids reading the GUID before it is safe to do so during initialisation
T:Microsoft.VisualStudio.ProjectSystem.VS.IProjectGuidService2; Using ISafeProjectGuidService avoids reading the GUID before it is safe to do so during initialisation

P:Microsoft.VisualStudio.ProjectSystem.VS.IProjectAsyncLoadDashboard.ProjectLoadedInHost; Using IUnconfiguredProjectTasksService.ProjectLoadedInHost prevents waiting indefinitely when the project is closed before it has finished loading

M:Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.LoadedProject(Microsoft.VisualStudio.ProjectSystem.IProjectAsynchronousTasksService); Using IUnconfiguredProjectTasksService.LoadedProjectAsync is unit testable

T:Microsoft.VisualStudio.ProjectSystem.ProjectAutoLoadAttribute; Using IProjectDynamicLoadComponent avoids accidently reloading the project while loading, switching branches, installing NuGet package, etc.
T:Microsoft.VisualStudio.ProjectSystem.ConfiguredProjectAutoLoadAttribute; Using IProjectDynamicLoadComponent avoids accidently reloading the project while loading, switching branches, installing NuGet package, etc.
```

**Comment by drewnoakes** [comment]
@davkean looking at this again there's one item from your list that's not covered by the current banned symbols list:

> Reading TargetFramework/TargetFrameworks properties. Only the configuration service should read these properties. Everyone else should be looking at "isVariantDimension" dimensions, or TargetFrameworkMoniker - and not know anything about these properties.

Are there specific symbols you'd like to see banned for this?

**Comment by davidwengier** [comment]
If you're looking for things to ban, ConfigureAwait() could be added to the list.

**Comment by davkean** [comment]
Good idea.

`ConfigureAwait(true)` => remove completely
`ConfigureAwait(false)` => `await TaskScheduler.Default`

**Comment by drewnoakes** [comment]
@davkean another item from your list not currently covered by the ban list is:

> Use/centralized usage of MSBuild construction model. This makes sure that we:
> - Escape/Unescape values
> - Implement the same behavior of walking, looking for properties, items, etc.

I don't know how to interpret that, nor whether there are specific symbols we can ban here.

**Comment by drewnoakes** [comment]
`ConfigureAwait` was banned in #4390.
