### ISSUE TITLE
We fail to show SDK node if you open a project with a non-existent package

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#3779]
1. While the project is open, edit the project and change it to:

``` XML

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FooBar" Version="1.0.0" />
  </ItemGroup>
</Project>


```

![image](https://user-images.githubusercontent.com/1103906/43135373-878f588e-8f88-11e8-8e1d-ebc5883bdb98.png)

2. Close project and open

Expected: To look exactly like aboev
Actual:
![image](https://user-images.githubusercontent.com/1103906/43135392-9f201f9c-8f88-11e8-83f9-d6b7f2343070.png)

**Comment by drewnoakes** [comment]
This seems to be a Heisenbug... Step through code with the debugger and everything works fine. Run freely and the node disappears. Probably timing/raciness.

Thinking I'll do some printf debugging on this tomorrow. Am open to suggestions of other techniques.

**Comment by drewnoakes** [comment]
With SDK 3.0.100-preview6-012264 (possibly in earlier previews as well) MSBuild SDKs are no longer reported as SDK nodes and there is no repro for this bug.

I intend to fix the underlying cause of this, but this particular symptom will no longer be the case from SDK 3.0.100.
