### ISSUE TITLE
F#: Editor features (intellisense etc) don't work after deleting ".vs"

### ISSUE THREAD

**Issue by 0x53A** [dotnet/project-system#3788]
![grafik](https://user-images.githubusercontent.com/4236651/43200249-3c8870b8-9015-11e8-902f-91e7c8c02112.png)

1) Create a new F# project ``Console App (.NET Core)``

2) Let VS do its thing, after a few seconds everything works. Do a build for good measure.  
![grafik](https://user-images.githubusercontent.com/4236651/43200303-69fd3308-9015-11e8-95ce-132f1d75c176.png)

3) Close VS and delete the ``.vs`` directory

4) reopen the solution: build works, but editor features don't  
![grafik](https://user-images.githubusercontent.com/4236651/43200356-9ba50ab6-9015-11e8-94c8-596e5b050883.png)

5) __Restart VS one more time, after that, everything works again__

**Comment by Pilchie** [comment]
@TIHan can you take a look at this?

**Comment by TIHan** [comment]
I know what is happening now. F#'s language service is not being initialized unless a document has been opened. This means we miss out on all the workspace events that F#'s language service needs.

**Comment by TIHan** [comment]
I have a fix for this coming. It is a bug in the F# language service.

**Comment by davkean** [comment]
This issue was moved to Microsoft/visualfsharp#5395
