### ISSUE TITLE
vs2017 new project shows wrong version of .net core 2.1.2

### ISSUE THREAD

**Issue by joshfree** [dotnet/project-system#3791]
_From @dncAdmin on July 11, 2018 11:1_

After installing .net core SDK 2.1.302 with Runtime 2.1.2 ,

vs2017 15.7.5 -> new project -> asp.net core project still shows the version of 2.1.1 and 2.1.0 in the Nuget and SDK dependence.

it should be 2.1.2

![image](https://user-images.githubusercontent.com/38060128/42567756-57f52f2c-853d-11e8-85d9-0169e173af07.png)

PC:

Win10

_Copied from original issue: dotnet/core#1772_

**Comment by joshfree** [comment]
@natemcmaster @dsplaisted

**Comment by Pilchie** [comment]
Adding @etbyrd and @nguerrera too.  What is written into the assets file in this case?

**Comment by natemcmaster** [comment]
I don't believe the issue is that the incorrect *package* version is displayed - those are the right package versions. 

The better issue to discuss is about user expectations. Package version represents what the app compiles for, but not which version is used at runtime. How can we help users understand that package version != runtime version?

One idea - don't display a package version unless RuntimeFrameworkVersion has been set.

**Comment by Pilchie** [comment]
Ah, right.

For Dev16 we want to revamp a lot of what is shown in the dependencies node to separate SDKs from packages and runtimes more clearly.

**Comment by etbyrd** [comment]
@Pilchie @natemcmaster is this still an issue? It cannot seem to get repro in dev16. It is showing the latest installed version I have from `dotnet --info`

**Comment by natemcmaster** [comment]
Yes, this is still an issue. The way to reproduce is to create a new ASP.NET Core 2.1 or 2.2 project and look at the children of   Dependencies > SDK.

![image](https://user-images.githubusercontent.com/2696087/58055422-94590300-7b12-11e9-8eba-de89453b3b6d.png)

**Comment by natemcmaster** [comment]
What I don't think was every clarified, however, is what VS should do about the problem. I suggested earlier that the UI should hide the version of the packages under the SDK node altogether, but I don't know if anyone else agrees.

**Comment by Pilchie** [comment]
Tagging @cartermp and @drewnoakes

**Comment by drewnoakes** [comment]
We've been talking for a while about removing the SDK node altogether. It doesn't provide any value as far as I can tell, and in this case is actively misleading. There's no user action to take on the SDK node or its children.

Note that we are planning on adding a new top-level node "Frameworks" for `FrameworkReference` items.

**Comment by Pilchie** [comment]
The main reason to include it is that SDK resolution logic can sometimes be confusing, especially in VS where things like the "Use Preview" option come into play. Having this do the right thing would help users understand what the result of that resolution is.  I think there is another issue about that from a twitter thread not long ago too.

**Comment by natemcmaster** [comment]
Would hiding the package version of dependencies under the SDK node be sufficient? The way I see it, the primary confusion has been in understanding the the package version of Microsoft.NETCore.App and Microsoft.AspNetCore.App is a _minumum_ version, and doesn’t represent the version that is going be used at runtime due to .NET Core rollforward policies.

**Comment by dsplaisted** [comment]
> The main reason to include it is that SDK resolution logic can sometimes be confusing, especially in VS where things like the "Use Preview" option come into play.

@Pilchie Yes, but what is shown in the "SDK" node in the solution explorer has no relation to the .NET Core SDK version that comes from the SDK resolution logic.  So we should make the resolution logic more transparent, and maybe we could show it under the SDK node, but that doesn't mean we shouldn't remove implicit package references from the SDK node.

**Comment by Pilchie** [comment]
@dsplaisted ah right.  I forgot that this was the implicit package version, not the actual SDK version.  Agree that it is less useful.

**Comment by drewnoakes** [comment]
We now have a `Frameworks` node that shows `FrameworkReference` items without a version on the node (although the version will be available in the properties panel).

An ASP.NET Core 3.0 web application looks like this, which achieves what @natemcmaster was talking about:

![image](https://user-images.githubusercontent.com/350947/60180390-49de4b00-9863-11e9-8957-243fb1476f5e.png)

The experience is unchanged when targeting ASP.NET Core 2.2.
