### ISSUE TITLE
Is "Check for arithmetic overflow/underflow" option name valid?

### ISSUE THREAD

**Issue by stjeong** [dotnet/project-system#3792]
I think, the option name has to be changed to "Check for arithmetic overflow".

Because, "underflow" means "Arithmetic_underflow", so by the definition as follows,

> http://en.wikipedia.org/wiki/Arithmetic_underflow:
> 
> The condition in a computer program that can occur when the true result of a floating point operation is smaller in magnitude (that is, closer to zero) than the smallest value representable as a normal floating point number in the target datatype.
> 

Actually, MSIL doesn't support any IL code for underflow, see documents.

OpCodes Class (https://msdn.microsoft.com/en-us/library/system.reflection.emit.opcodes(v=vs.110).aspx)

**Comment by Pilchie** [comment]
It's possible that it could be changed, but I'm not sure it's worth it - this string has remained unchanged for many years now.
