### ISSUE TITLE
Resources editor does not accept WMF files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3795]
In a Windows Forms project, it's not possible to add a WMF file resource using the GUI. 

If I click Add Resource -&gt; Existing Resource, metafiles are not listed in the file browser's list of acceptable file types, however, it does seem that the resx file can actually handle wmf file resources properly, for the most part.

The reason why I think the resx file can handle WMF, is if I hand edit the resx file with the following line:

```
<data name="TestWMF" type="System.Resources.ResXFileRef, System.Windows.Forms">
<value>..\Resources\Sample.wmf;System.Drawing.Imaging.Metafile, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</value>
</data>
```
The editor shows it in an &quot;other&quot; category, but it seems that it has accepted it as a resource, and it can be assigned to controls like ToolStripButton, etc.

Interpreting the term &quot;Image&quot; in a way that implies that it refers to System.Drawing.Image, I would expect that this category would accept both Bitmap and Metafile objects.

I considered posting this as a suggestion but I leaned toward &quot;bug&quot; on this one, sorry for the mixup if this is considered &quot;not a bug&quot;.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/199180/resources-editor-does-not-accept-wmf-files.html
VSTS ticketId: 568197_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by davkean** [comment]
@wjk Here's another Resources Editor bug if you are interested.

**Comment by wjk** [comment]
@davkean Consider me assigned. Just one question, though: Where can I get a WMF file to test with? It's an awfully old format. Thanks!

**Comment by amelvill** [comment]
@wjk  Hi William, sorry for the late reply, I was unaware that there was activity on github for this. here is my sample project from the VS feedback system containing a wmf file you can test with.

[22856-wmfimagelist.zip](https://github.com/dotnet/project-system/files/2235669/22856-wmfimagelist.zip)
