### ISSUE TITLE
FastUpToDate check is wrong after initial Rebuild in Visual Studio

### ISSUE THREAD

**Issue by smithmw** [dotnet/project-system#3826]
Steps to reproduce:
Pre-req: Options->.NET Core->Up to Date Checks: Check "Don't call MSBuild if a project appears to be up to date" (Note: I have logging level turned to Verbose)

1. Open a solution with one netStandard project.
2. Rebuild Solution (Results in "1 succeeded", and any pre/post build events are run)
3. Build Solution
Bug: 
- Results in "1 succeeded", and pre/post build events are run.
- Output: `FastUpToDate: The list of source items has changed since the last build, not up to date. (netstandardlib)`
4. Build Solution (Results in "1 up-to-date", no pre/post build events are run)
Output: `FastUpToDate: Project is up to date. (myprojectname)`

The expectation is that in Step 3 above, that the Result would be "1 up-to-date" with no pre/post build events being run (i.e. what happens in Step 4).

Notes:
- Subsequent Rebuilds/builds in the same session of Visual Studio have the expected behavior.  However, restarting Visual Studio, the bug appears again.  
- Here's a video demonstrating the issue: http://www.screencast.com/t/fCndQNvg

**Comment by smithmw** [comment]
Here's a video demonstrating the issue: 
http://www.screencast.com/t/fCndQNvg

**Comment by Pilchie** [comment]
@smithmw what version of Visual Studio are you using? @panopticoncentral didn't you fix this for 15.7?

**Comment by smithmw** [comment]
@Pilchie Visual Studio Enterprise 2017 Version 15.7.6

**Comment by panopticoncentral** [comment]
We started checking the time on the MSBuild input file cache to make sure we're counting against glob changes correctly, but we didn't address this particular scenario. Probably with the MSBuild input file cache, we can assume when we get the first list of files that the up to date check will just work, so we could probably remove the first failure. Just have to take a look at the code.

**Comment by Pilchie** [comment]
This issue was moved to dotnet/roslyn#29099

**Comment by Pilchie** [comment]
Moved the wrong issue - sorry.

**Comment by drewnoakes** [comment]
Potentially related to #4585.

**Comment by drewnoakes** [comment]
'Rebuild' doesn't call the up-to-date check, which means your second build is actually the first build from the perspective of the up-to-date check. I'm not confident it's safe for the up-to-date check to assume the files it sees on disk are up-to-date just because the outputs are newer than the inputs. It's possible, for example, that an input file was deleted.

A similar bug existed that didn't require rebuilding (#4736) which was fixed very recently.

**Comment by drewnoakes** [comment]
I am working on a fix for #6633 which may also address this.
