### ISSUE TITLE
Project rename drops aliases in ProjectReferences

### ISSUE THREAD

**Issue by tmat** [dotnet/project-system#3829]
Version:
![image](https://user-images.githubusercontent.com/41759/43670787-fe4fb39c-9744-11e8-8d53-aa120b4f7a6c.png)

Repro:
1) Create .NET Standard Library A
2) Create .NET Standard Library B and add reference to A
3) Add `Aliases="A"` to the `ProjectReference`.
4) Rename project A to C in Solution Explorer.

Expected:

`<ProjectReference Include="A.csproj" Aliases="A"/>` changes to `<ProjectReference Include="C.csproj" Aliases="A"/>`

Actual:

`<ProjectReference Include="A.csproj" Aliases="A"/>` changes to `<ProjectReference Include="C.csproj" />`

**Comment by Pilchie** [comment]
@lifengl - do you know if this is in this project, or core CPS?

**Comment by lifengl** [comment]
I think it is in the core CPS.

Sent from my phone

On Aug 6, 2018, at 8:10 AM, Kevin Pilch <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flifengl&data=02%7C01%7C%7C32345740eb7d4998860608d5fbaebc7d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636691650251586155&sdata=wSQn3OTrUlUdiagrGi3f87uwzG%2BH0VrL61drNuVYNok%3D&reserved=0> - do you know if this is in this project, or core CPS?

**Comment by Pilchie** [comment]
Filed [Bug 660382](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/660382) to track.

**Comment by davkean** [comment]
This was fixed in 16.5: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/218766.
