### ISSUE TITLE
Passing Arguments to Dockerized Console App

### ISSUE THREAD

**Issue by duncangravill** [dotnet/project-system#3851]
I'd like to pass arguments to a simple dotnet core 2.1 console app that has had docker support added.

So far I have tried adding arguments to the console app project properties debug tab without success:

`1, 2, 3`
`1; 2; 3`
`"1", "2", "3"`
`["1", "2", "3"]`

There isn't a hint in the project debug properties as to what the format of the arguments should be, also I can't find any documentation about the project properties.

I'm assuming that when the app is launched in a debug session that VS should take the arguments in the properties and pass them to the `docker run` command, but I can't find any output relating to the `docker run` command in the debug or docker output.

Or is it necessary to modify the docker-compose file with the argument to be passed in order for them to be passed? 

There also aren't any fields in the docker project properties that pertain to passing arguments.

Thanks,

EDIT: I have tried setting the output to diagnostic in Projects and Solution > Build and Run.

**Comment by jmarolf** [comment]
@duncangravill see the documentation here: https://docs.microsoft.com/en-us/dotnet/framework/docker/console

You will need to pass these arguments to the `docker run` command

**Comment by Pilchie** [comment]
@jmarolf: @duncangravill said:

> I'm assuming that when the app is launched in a debug session that VS should take the arguments in the properties and pass them to the docker run command, but I can't find any output relating to the docker run command in the debug or docker output.

> Or is it necessary to modify the docker-compose file with the argument to be passed in order for them to be passed?

It sounds like you're saying it's the latter?  Is this something we should pass along to the docker tools team?

**Comment by jmarolf** [comment]
@Pilchie yes, I think we should move this issue to the docker tools team

**Comment by duncangravill** [comment]
@Pilchie I don't know which it should be, my initial assumption was that the command line arguments for the console app should be read from the console app project properties. 

Actually I don't think the arguments should go in the docker-compose file, because this is only used to start the container, the console app isn't launched until the dev starts to debug, so VS must be sending the `docker run + arguments` command to the container via the docker tools. But since the .ps1 file is no longer added to the project it's difficult to know what is happening.

So either the arguments should be declared in the project properties or the docker project properties (there is currently no field in the docker properties for declaring arguments). It seems most logical to me to declare the arguments in the console project properties, and for the docker tools to read them from there.


@jmarolf The docs you have linked seem, at first glance, to be out of date. The .ps1 script is no longer added to the project, as it once was, so I'd be very unsure about how to add a second script to override the docker tools functionality, or if that's even possible.

**Comment by Pilchie** [comment]
Tagging @dbreshears here too.

**Comment by dbreshears** [comment]
@duncangravill ,  a couple of options 

You can pass in an argument during debugging  by creating a file docker-compose.vs.debug.yml  and place in the root of the docker-compose project.   

Then add this label appending the argument to the end of the line of the arguments we are passing in.  We will pick up you docker-compose.vs.debug.yml as the last argument to docker-compose which you can see when F5 or building your project in the build pane.    Note: I grabbed this starting point from the solution root obj\Docker\docker-compose.vs.debug.g.yml file

version: '3.4'

services:
  consoleapp3:
    labels:
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath c:\\.nuget\\packages --additionalProbingPath c:\\.nuget\\fallbackpackages  bin\\Release\\netcoreapp2.1\\ConsoleApp3.dll foobar"

Similarly you can create a docker-compose.vs.release.yml 

Alternatively, you could use an environment variable for container based configuration.  One way to do this to add a ".env" text file to the docker-compose project root and set the environment variable in it.   

VAR1=Hello World!

Then in your docker-compose.yml add a section under your service such as 

version: '3.4'

services:
  consoleapp2:
    image: ${DOCKER_REGISTRY}consoleapp2
    build:
      context: .
      dockerfile: ConsoleApp2\Dockerfile
    environment:
      VAR1: ${VAR1}

Then in your console app

  static void Main(string[] args)
        {
            Console.WriteLine(Environment.GetEnvironmentVariable("VAR1"));
        }
