### ISSUE TITLE
docker run statement is not echoed to the debug or docker output.

### ISSUE THREAD

**Issue by duncangravill** [dotnet/project-system#3852]
I've noticed that when debugging a dotnet core 2.1 console app with docker support that the docker run statement that launches the app for a debug session is not echoed to the debug or docker output.

Surely this is an important statement to echo to the output.

**Comment by Pilchie** [comment]
@gregg-miskelly is this something the debugger should do, or the project-system?

Also tagging @BillHiebert - would this be here, or in the docker tools code?

**Comment by gregg-miskelly** [comment]
I think this would need to be done from the Docker Tools code. @dbreshears

**Comment by dbreshears** [comment]
Yeah, seems like it should be.  I'll investigate and see about fixing this.

**Comment by haniamr** [comment]
@duncangravill the way Docker Tooling runs the container is by calling "docker-compose up" and not "docker run", you can find that in the build output pane, something like:
`docker-compose  -f "docker-compose.yml" -f "docker-compose.override.yml" -f "docker-compose.vs.debug.g.yml" -p dockercompose2022606616973168885 --no-ansi up -d`
