### ISSUE TITLE
SequentialTaskExecutor violates threading rule 3, causing deadlocks.

### ISSUE THREAD

**Issue by jviau** [dotnet/project-system#3853]
[SequentialTaskExecutor.cs](https://github.com/dotnet/project-system/blob/f2118e1d747f006628729de22b901b908fa0722f/src/Microsoft.VisualStudio.ProjectSystem.Managed/Threading/Tasks/SequentialTaskExecutor.cs) uses `Task.ContinueWith` to control the execution flow of multiple tasks. This is a violation of [threading rule 3](https://github.com/Microsoft/vs-threading/blob/master/doc/threading_rules.md#rule-3-if-ever-awaiting-work-that-was-started-earlier-that-work-must-be-joined), as a posted task to `ExecuteAsync` can wait on the completion of a previous, unrelated call to `ExecuteAsync`. Docker tools has encountered this hang and supplied a dump, which I investigated and found this to be the root cause.

The fix is for `SequencialTaskExecutor` to have a private `JoinableTaskFactory` and `JoinableTaskCollection`. All work supplied to `ExecuteAsync` should be ran with the `JTF.RunAsync`, and when work must be posted inside the `ContinueWith`, the collection must be joined so that the previous enqueued tasks are joined. Additionally, reconsider the usage of `ContinueWith` chains, as if `ExecuteAsync` is called a lot, it may cause memory pressure.

**Comment by Pilchie** [comment]
Also "Sequential" is spelled wrong in the type name...

**Comment by Pilchie** [comment]
Putting in 16.0 barring more data about how common this deadlock is.
