### ISSUE TITLE
UWP Target Copies Outputs Back to Intermediate Directory

### ISSUE THREAD

**Issue by Joe-Sewell-PreEmptive** [dotnet/project-system#3862]
The UWP (Universal Windows app) target `_GenerateProjectPriConfigurationFiles` can copy XBF files from the output directory (e.g., `bin\x64\Release`) to the intermediate directory (e.g., `obj\x64\Release`) where these files were originally compiled.

If a customized build step reads an XBF file from the intermediate directory and produces a modified version of the XBF file in the output directory, and then `_GenerateProjectPriConfigurationFiles` runs, the file in intermediate directory will also contain these modifications.
This can be a problem for future builds, as the customized build step will now be processing a file (in the intermediate directory) that it thinks is an "input" but is really an "output".
Additionally, the build step may run even when all files should logically be up-to-date.

For context, I am a developer on Dotfuscator, the .NET protection tool included with Visual Studio.
Our MSBuild integration works in the way described, processing XBF files from the intermediate directory and producing obfuscated XBF files elsewhere that then are copied into the output directory.

We are concerned that an output file being written back to the intermediate directory could cause bugs; e.g., Dotfuscator may process an already-obfuscated XBF file, making it out of sync with the rest of the project's markup and assemblies.
This issue also causes our integration's targets to be run every build, even if there haven't been any changes to the project since the last time it built with the integration.

### Steps to Reproduce

[XbfCopyBackRepro.zip](https://github.com/dotnet/project-system/files/2288367/XbfCopyBackRepro.zip)

The above ZIP contains a solution which reproduces the issue.
The solution has two projects:

* `XbfCopyBackRepro.csproj` is a typical UWP app, except:

    * Its `MainPage.xaml` file displays the text `MY_OLD_VALUE`.
    
    * It has two custom targets, `CreateReplacementXbfs` and `ReplaceXbfs`, which cause an edited version of `MainPage.xbf` to be copied to the output directory instead of the one originally compiled from `MainPage.xaml`. This makes the UWP app display `MY_NEW_VALUE` rather than `MY_OLD_VALUE`. See **Details**, below.

* `XbfReplacer.csproj` is a Windows console app that is called by the `CreateReplacementXbfs` target. It reads in an XBF file, then writes out a text file and a new XBF file with contents identical to the input file except the embedded string `MY_OLD_VALUE` is replaced with `MY_NEW_VALUE`.

This mimics how Dotfuscator's MSBuild integration works, which reads in the XBF files (among others) and produces obfuscated versions that then get copied to the output directory. 

To reproduce the issue, execute `run.bat`, which does the following:

1. Cleans the repository to ensure builds start from a fresh state (this also deletes any previous log files in the repository).

2. Builds `XbfReplacer.csproj` so it can be used by the build process of `XbfCopyBackRepro.csproj`.

3. Restores NuGet packages for `XbfCopyBackRepro.csproj`.

4. Builds `XbfCopyBackRepro.csproj` from a clean state.

5. Builds `XbfCopyBackRepro.csproj` again, with no intervening changes.

### Expected Behavior

Both builds of `XbfCopyBackRepro.csproj` succeed.

During the second build, the custom `CreateReplacementXbfs` target is skipped because both of its output files are up-to-date with respect to its input file.

### Actual Behavior

The second build of `XbfCopyBackRepro.csproj` fails.

During the second build, the custom `CreateReplacementXbfs` target is run because its input file is newer than one of the output files.
This target then runs the `XbfReplacer` console app, which errors because the input file does not contain the string `MY_OLD_VALUE`:

```
Didn't find MY_OLD_VALUE in 'obj\x86\Release\\MainPage.xbf'
```

It looks like this issue doesn't occur when building in Visual Studio, only from the MSBuild command line.
In the ZIP I've included log files for each interface, for two back-to-back builds.

### Details

This is the intended sequence of events when building the `XbfCopyBackRepro.csproj` project, which has custom targets, for the first time:   

1. The `MarkupCompilePass1` and `MarkupCompilePass2` targets create the file `obj\x86\Release\MainPage.xbf`, which contains an encoded string value, `MY_OLD_VALUE`.

2. The `Prep_ComputeProcessXamlFiles` target populates the items `GeneratedXamlSrc` and `GeneratedXamlDest` with `obj\x86\Release\MainPage.xbf` and `bin\x86\Release\MainPage.xbf` respectively (among other items).

3. MSBuild decides to build the custom `CreateReplacementXbfs` target, because none of its output files exist.

    * Input file: `obj\x86\Release\MainPage.xbf`
    
    * Output files: `obj\x86\Release\Replacements\Log.txt` and `obj\x86\Release\Replacements\MainPage.xbf`

4. The `CreateReplacementXbfs` target calls the `XbfReplacer` console app which:

    * Creates the file `obj\x86\Release\Replacements\Log.txt`.

    * Waits 5 seconds to ensure the previous file has an earlier timestamp than the next one.
    
    * Creates the file `obj\x86\Release\Replacements\MainPage.xbf`, a which is identical to `obj\x86\Release\MainPage.xbf` except the encoded string `MY_OLD_VALUE` has been replaced with `MY_NEW_VALUE`.

4. The custom `ReplaceXbfs` target replaces the `GeneratedXamlSrc` item `obj\x86\Release\MainPage.xbf` with `obj\x86\Release\Replacements\MainPage.xbf`. (It does this by removing the respective entries from `GeneratedXamlSrc` and `GeneratedXamlDest`, then adding new ones with the new source path.)

5. The `CopyGeneratedXaml` target copies `obj\x86\Release\Replacements\MainPage.xbf` to `bin\x86\Release\MainPage.xbf`.

However, later during this first build, the `_GenerateProjectPriConfigurationFiles` target runs and copies `bin\x86\Release\MainPage.xbf` back to `obj\x86\Release\MainPage.xbf`, overwriting the XBF file with the `MY_OLD_VALUE` string.
Thus, when we build the project again, the input file, `obj\x86\Release\MainPage.xbf` is actually the modified output file from the last build.
As a result:

* The custom `CreateReplacementXbfs` target is not skipped, because the input file `obj\x86\Release\MainPage.xbf` is newer than one of the output files, `obj\x86\Release\Replacements\Log.txt`.

* This target calls the `XbfReplacer` console app which errors, because the input file's `MY_OLD_VALUE` string has already been replaced with `MY_NEW_VALUE`. While in this scenario the custom build steps detect that what was presumed to be an input file was already modified, doing so with a real scenario could be unnecessarily difficult or expensive.

### Environment Data

`msbuild /version` output:

```
Microsoft (R) Build Engine version 15.7.180.61344 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.7.180.61344
```

OS info:

```
Microsoft Windows [Version 10.0.17134.191]
```

Visual Studio (recall that this does not reproduce the issue, only the MSBuild command line does):

```
Microsoft Visual Studio Enterprise 2017  (Enterprise)
Version 15.7.6
VisualStudio.15.Release/15.7.6+27703.2047
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise
```

**Comment by Pilchie** [comment]
@jmarolf edited the comment inline, but for notification purposes, @davkean meant to say "Unfortunately, this repo *isn't* the correct one to address the issue"...

**Comment by Joe-Sewell-PreEmptive** [comment]
OK, I've filed the issue [here](https://developercommunity.visualstudio.com/content/problem/311580/uwp-target-copies-outputs-back-to-intermediate-dir.html). (Note that I've been unable to edit the post after submission to fix the formatting, and have filed a separate issue for why I cannot edit the post).
