### ISSUE TITLE
#if preprocessor not refreshing in editor for new csproj format

### ISSUE THREAD

**Issue by AbhishekTripathi** [dotnet/project-system#3865]
I am not sure if it was working as expected before but I see that 15.8.0 update of VisualStudio is showing this issue. The `#if DEBUG` preprocessor directives does not auto-update in the editor if the csproj is of newer format starting with `<Project Sdk="Microsoft.NET.Sdk">` 

Create a new C# library project targetting full framework. Edit your csproj file and replace with following.
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <OutputPath></OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath></OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
  </ItemGroup>
</Project>
```
In your CS file try adding below and toggle Debug and Release mode from the dropdown to see if editor refreshes. Expected is that it should update correctly i.e. should be grayed out in Release mode but the observed behavior is that it has no effect and the state is same.
```csharp
namespace ClassLibrary1
{
    public class Class1
    {
#if DEBUG
        //do something
#endif
    }
```

EDIT: Cross Reference #2733

**Comment by Pilchie** [comment]
This is exactly what #2733 tracks.
