### ISSUE TITLE
Need a way to find .resx files

### ISSUE THREAD

**Issue by chborl** [dotnet/project-system#3866]
While trying to write a refactoring to extract a string to a .resx file it was discovered that there isn't a good way to find all .resx files in a project.  An API to find .resx files would be beneficial not only for us, but also for our customers.

**Comment by davkean** [comment]
For both legacy and new project system, the common API for finding ResX files would be [DTE.Project.ProjectItems](https://docs.microsoft.com/en-us/dotnet/api/envdte.project.projectitems?view=visualstudiosdk-2017) and then looking up ProjectItem.Properties for property `ItemType` where it equals `EmbeddedResource`.

For new project system only, you can use `IProjectItemProvider.GetItemsAsync("EmbeddedResource")`.

**Comment by davkean** [comment]
Going to make this as a question, feel free to ask clarifying questions if you want to dig into either of above.

**Comment by Pilchie** [comment]
Going to close this, but @chborl let us know if you run into more issues here.

**Comment by chborl** [comment]
Thanks!  I will look at David's explanation and see if I have further questions.
