### ISSUE TITLE
Is it possible to code sign files before packing it into a nuget package?

### ISSUE THREAD

**Issue by sanderobdeijn** [dotnet/project-system#3868]
I have now added my own custom target that runs after the build target. But is there also a built-in target?

**Comment by davkean** [comment]
I don't know off hand. @onovotny how are you open source projects code signing?

**Comment by onovotny** [comment]
The code signing service (https://github.com/onovotny/SignService) orchestrates all of it. It takes the nupkg, cracks it open, and recursively looks for files to sign recursively. It has to sign "inside out" for things to be done in the right order.

The service can be installed into your own Azure subscription and is the recommended approach. It uses Azure Key Vault's HSM to store the cert, so the key cannot be compromised by theft.

**Comment by Pilchie** [comment]
As for built-in targets, adding @nguerrera and @dsplaisted for that.

**Comment by sanderobdeijn** [comment]
@onovotny I have now made an target that signs my build output before running the pack target so you don't have to crack them open and after the files are packed by msbuild I sign the nuget package with a script but that could also be a target that runs after the pack target.

**Comment by onovotny** [comment]
I very strongly discourage that. It's slow and puts the certificate directly on the build box, making it easier to compromise. 

It's much faster to be able to sign things in batch. Happy to help you/your organization get the signing service set up if you'd like. The .NET Foundation, and many other organizations, are using it in production today.

**Comment by sanderobdeijn** [comment]
Would that also work with msi files containing build output?

**Comment by onovotny** [comment]
MSI files need custom packing, so the server can't do that. In that case, I'd recommend two steps: batch sign the dlls/nupkgs/anything else that's input to the MSI, then run the MSI build task, then send the MSI to the service to sign.

**Comment by Pilchie** [comment]
Discussion seems to have slowed down here, so I'm going to close this for now, but let me know if there is more to discuss.
