### ISSUE TITLE
Pinned Project Properties tab not reopened after reopening project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#3888]
When I open the Project Properties of a C-sharp project and set this tab as pinned, then when I close the project and reopen it, this tab is not reopend.

This happens only when the Project Properties tab was NOT focused when I close the project.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/315689/pinned-project-properties-tab-not-reopened-after-r.html
VSTS ticketId: 666950_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by davkean** [comment]
This has been fixed for the new project system and the project properties are remembered on reopen of the solution. We are no longer investing in .NET Framework project system, and have no plans on making improvements there to fix this.
