### ISSUE TITLE
"Build target stackw as corrupted and contain other unfinished targets"

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/project-system#3891]
Did a "build all" of my solution (Roslyn.sln), and then cancelled the build with Ctrl+Break. Got a dialog that pointed me to this log:
```
=====================
8/21/2018 10:46:56 AM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: '_GenerateCompileDependencyCache', Actual: 'BeforeCompile'.
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
===================
```

Unfortunately that's the entire log. Build is 28016.0.d15.9.

**Comment by Pilchie** [comment]
@lifengl any ideas where to look?

**Comment by Pilchie** [comment]
@jasonmalinowski Can you file internally, as this is managed by CPS?

**Comment by jasonmalinowski** [comment]
FYI: haven't hit this in awhile, so won't do an internal bug at this point.
