### ISSUE TITLE
Build should warn if packages.config present but ignored

### ISSUE THREAD

**Issue by leotsarev** [dotnet/project-system#3897]
When .csproj contains PackageReference and packages.config, packages.config will be silently ignored.
Note that PackageReference could come, for example, from some *.props with misspelled condition, and it will be hard to understand why most suddenly project doesn't restore anything.

Proposed solution: when packages.config exists on disk, but will be ignored, warn somehow.

**Comment by jmarolf** [comment]
@Pilchie this bug should be moved to whomever owns the MSBuild nuget restore task now (I don't think its https://github.com/NuGet/NuGet.BuildTasks anymore)

**Comment by Pilchie** [comment]
For projects using the old syntax, it's still that.  For SDK-style projects, that would be in https://github.com/dotnet/sdk I believe.

**Comment by Pilchie** [comment]
Actually tagging @rrelyea - it might make more sense for this to come directly from NuGet during the restore...

**Comment by Pilchie** [comment]
This issue was moved to NuGet/Home#7270
