### ISSUE TITLE
Output path only applied to first target in multi-target project

### ISSUE THREAD

**Issue by MV10** [dotnet/project-system#3898]
VS2017 15.8.1

I am working on a project that targets `netstandard2.0`, `net451` and `net461`. For local debugging purposes, in the project properties dialogs I enabled generate package on build and set Output Path to a centralized location which is also configured as a local NuGet repository.

When I build the project, only a `netstandard2.0` folder is created in the Output Path. The `net451` and `net461` builds and the NuGet package are still created in the default `bin` folder. (I assume the package just picks up the last msbuild target.)

You can reproduce this by building the dev branch of [this](https://github.com/serilog/serilog-settings-configuration) Serilog project. (You'll have to set the generate flag and output after cloning, we don't store those settings in the repo.) I'm pretty sure this is a relatively recent problem, I converted this to a multi-target project several months ago using the same centralized-package-folder setup and did not see this behavior.

**Comment by MV10** [comment]
I see the problem is that `$(TargetFramework)` is part of the condition in the csproj even though it can't be controlled through the UI. 

```xml
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
    <OutputPath>C:\Source\_dev_nuget_packages\serilog-settings-configuration\</OutputPath>
</PropertyGroup>
```

At least I can work around this. I'm aware from other issues and threads that the project properties UI is recognized as badly needing an overhaul, so I guess this is just another item to track. (I couldn't find a similar report anywhere, except a vaguely related request to provide a separate NuGet output path, which I agree would be great to have.)

**Comment by Pilchie** [comment]
Tagging @cartermp, who has been taking a bit of a look at both the property page and multi-targeting experiences to think about what we could do better here.

**Comment by cartermp** [comment]
Thanks for the report, this is definitely something to consider as you've said, @MV10. It sounds like there are two distinct things here:

1. Regardless of the project property pages UI, defaulting this to sending each binary to the specified path.
2. Designing a better way to represent this in the UI, while also accounting for multitargeting.

(2) doesn't preclude (1) - though that's without me having an understanding of what it would take to adjust the system to enable (1).

**Comment by drewnoakes** [comment]
This UI has been replaced by the new Project Properties UI which has proper support for multi-targeting.
