### ISSUE TITLE
Properties node is not showing

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#390]
![image](https://cloud.githubusercontent.com/assets/1103906/18023553/31a21e7e-6baf-11e6-8b65-a740a7a93fc1.png)

**Comment by davkean** [comment]
This looks like a result of removing AssemblyInfo.cs :( @nguerrera 

Got it back by adding `<Folder Include="Properties"/>`  but we need to figure out what we're going to do if we have nothing under Properties by default.

**Comment by nguerrera** [comment]
TBH, I saw that and thought "by design". What value does it add with no children? Anything other than double click to get property pane?

**Comment by srivatsn** [comment]
@BillHiebert will launch profiles show up in solution explorer under Properties and will there always be a launch profile?

**Comment by davkean** [comment]
Okay, after a day of using .NET Core projects this has bothered me - it makes getting into Properties just a little bit harder so I want to tackle this. 

Here's my proposal, we add an empty AssemblyInfo.cs that basically points the user to editing the project file, so that that anyone coming from traditional .NET projects get a pointer to the new way.

@srivatsn @nguerrera Any pushback on this?

**Comment by dsplaisted** [comment]
Double-clicking on the node to open properties is convenient, but I'm inclined to think it's not worth the extra clutter in the solution tree.  So my preference would be to leave it out.

**Comment by davidfowl** [comment]
@dsplaisted don't break people's muscle memory 😄

**Comment by davidfowl** [comment]
> Here's my proposal, we add an empty AssemblyInfo.cs that basically points the user to editing the project file, so that that anyone coming from traditional .NET projects get a pointer to the new way.

Make it not empty? Just leave out the version info...

**Comment by jnm2** [comment]
I would prefer to have the node, and **not** have a Properties folder or AssemblyInfo.cs. Deleting those would be the first thing I would do when creating a new project.

**Comment by nguerrera** [comment]
How about always having an empty double-clickable node regardless of project contents.

Does the folder include work if there's no properties folder on disk? Will it create the folder always or only if I add a file to it? If the latter could we put the include in our props somehow? (There's something else needed to get includes from imports isn't there?)

**Comment by srivatsn** [comment]
Yes the folder include works even if the folder doesn't exist. I remember @davkean had some reason why just adding a Folder include in the SDK targets wasn't good enough. Can't remember the reason.

**Comment by davkean** [comment]
The folder doesn't work - it appears it does, but you can't add items to it.

**Comment by davkean** [comment]
I'm going to play around with this - the experience I want, is that you can delete the folder and it disappears without adding anything to your project file.

**Comment by davkean** [comment]
Here are the requirements that I have in mind:

1. Projects start off with a Properties folder (or My Project in VB)
2. Developers can add/drag items by default into the Properties folder
3. Developers can delete the Properties folder from their project.
4. No visible elements inside the project file appear in reference to the Properties folder when they create the project
5. No visible elements inside the project file appear in reference to the Properties folder when they delete the node.

**Comment by davkean** [comment]
We've lived without this for many releases, I don't think we're going to change this.
