### ISSUE TITLE
Dependencies node is showing above Properties

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#391]
![image](https://cloud.githubusercontent.com/assets/1103906/18023595/c8fae274-6baf-11e6-90c9-9201105c8273.png)

**Comment by davkean** [comment]
tag @abpiskunov

**Comment by abpiskunov** [comment]
Its not possible now, since CPS sorts alphabetically all special folders that have BubbleUp flag. i opened this TFS bug 364549 to request a way to set order explicitly on BubbleUp folders.

**Comment by abpiskunov** [comment]
FYI: CPS bug was closed as won't fix (waiting for external customers feedback). From what i was told this is a known request sinice position of the nodes interfere with some people's routines .. please reopen  CPS bug if you feel its need to be re-activated.

**Comment by davkean** [comment]
What is the CPS bug?

**Comment by abpiskunov** [comment]
364549

**Comment by viktorveis** [comment]
This simple feature will require major changes in CPS. I think that we should wait for additional feedback to assess how critical is this order.

**Comment by davkean** [comment]
We also want to show the project file itself as he node in the tree, we don't the order of it changing based the name of the project.

To be honest, I'm unconvinced that this is complex, the tree already has 3 separate orders, BubbleUp, then Folders and then Files. The code that controls this is this simple sort here: https://mseng.visualstudio.com/VSIDEProj/_git/VSIDEProj.CPS#path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.Implementation%2FDesigners%2FProjectTreeSort.cs&version=GBmaster&_a=contents.

**Comment by jviau** [comment]
That sorter is unfortunately abstracted away underneath 2 factories (red tree and green tree). I tried once to make it extensible because we wanted to move the directory tree culture-insensitive, but it proved to be very messy.

What we could do is a very targeted change for Properties and the project file node, but that doesn't sound very attractive.

**Comment by davkean** [comment]
We've come to an agreement our approach for this: https://github.com/dotnet/roslyn-project-system/issues/391. Once we have the required CPS feature we can opt in and control the order.

**Comment by tannergooding** [comment]
@Pilchie, @davkean. This is a post 15.5 bug. The CPS team still needs to undergo a major refactoring to support setting the display order on arbitrary items in the tree (and simultaneously keeping it performant for large solutions).

**Comment by davkean** [comment]
@tannergooding Help me understand this - I thought your support added this.

**Comment by tannergooding** [comment]
@davkean, I did. But it is not useable as a general feature and is estimated to have terrible performance outside of F# (where a large project is apparently 20 files, @KevinRansom?).

For DisplayOrder to be used more generally, it requires a massive refactoring in CPS (or at least that was my understanding after the last couple meetings with them).

**Comment by Pilchie** [comment]
Is this actually a problem?

**Comment by tmeschter** [comment]
@Pilchie @davkean This bug (the Dependencies node shows above the Properties node rather than below it) has been open for two years. Do we really need to fix it? I *personally* am fine with things as they are.

**Comment by drewnoakes** [comment]
I also feel like this issue could be closed, especially now double-clicking a project opens the editor (presumably removing the need to show the project file in the tree).

There's been no community activity here, and it can always be reopened if needed.

**Comment by drewnoakes** [comment]
Closing for now.
