### ISSUE TITLE
PackageRuleHandler methods ignoring default value parameter

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#3915]
Methods `PackageRuleHandler.GetEnumMetadata` and `PackageRuleHandler.GetBoolMetadata` both have `defaultValue` parameters. Neither actually use the values when parsing fails, however.

This is not currently a problem for enums, as the default passed value always happens to be `default` (the zero-valued member), but for the `bool` case there are two callers:

- `ProjectItemMetadata.Resolved` uses `true`
- `ProjectItemMetadata.IsImplicitlyDefined` uses `false`

If parsing `Resolved` fails, the value will be `false` rather than the requested `true`.

https://github.com/dotnet/project-system/blob/d8de8cd390ab04474f8e88ec68b785757b14d350/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Subscriptions/PackageRuleHandler.cs#L354-L361

Also, the `?? "false"` bit means that `null` values parse as `false`, not `defaultValue`. This may be intentional, but probably worth reviewing at the same time.

**Comment by Pilchie** [comment]
Can you two take a look at this and see what (if anything) needs to be done?

**Comment by tmeschter** [comment]
1. Based on a brief examination I think we should update `GetEnumMetadata` and `GetBoolMetadata` to actually respect and return the `defaultValue` parameters. It looks like we're _trying_ to respect them, but the calls to `Enum.TryParse` and `bool.TryParse` will always overwrite them with the type's default value in the case they fail.
2. Consider simplifying `GetEnumMetadata` and `GetBoolMetadata` to _not_ take a default value and instead return `T?` and `bool?` respectively. Then:
  > Severity = GetEnumMetadata(ProjectItemMetadata.Severity, DiagnosticMessageSeverity.Info);

  could become

  > Severity = GetEnumMetadata(ProjectItemMetadata.Severity) ?? DiagnosticMessageSeverity.Info;

**Comment by drewnoakes** [comment]
@tmeschter makes sense to me. I'm happy to put in a PR.

**Comment by tmeschter** [comment]
@drewnoakes Nah, I'm on it.
