### ISSUE TITLE
Dependencies tree need only load the first level, and lazy creating the subtree, only when user expands it.

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#3917]
Dependencies tree is one leading reason that .Net Core project system uses excessive memory.
We need create the tree lazily, and remove the majority data from the DTBB output.

(I could not find a task to track this work.  Please resolve it as a duplicated, if you have already got one.)

**Comment by davkean** [comment]
Going to dup this against https://github.com/dotnet/project-system/issues/3435.
