### ISSUE TITLE
BuildUpToDateChecker holds lots of full paths

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#3918]
BuildUpToDateChecker computed full paths for project items, and imported files, and saves them in an internal dictionary.  It can lead into excessive memory usage for a large project. Can we prevent doing that?  Is it possible it computes a hash value of the project state, instead of maintaining a large set of state?

**Comment by davkean** [comment]
cc @drewnoakes @panopticoncentral 

We're tracking MSBuildAllProjects data with https://github.com/dotnet/project-system/issues/3744. 

It looks like this what we do currently do:

- When the project changes, we collect all inputs and outputs and store them away in fields.
- When IsUpToDateAsync is called we walk those inputs and outputs and gather write times and figure out if we're out of date. 

From my limited understanding of this, I don't see how computing hash state of the project will help us achieve this. One thing we could consider doing, is only grabbing the current state of the project via in the IsUpToDateAsync callback to avoid us needing to persist state. It will mean that it will take longer to calculate "up-to-dateness" but storing less data. The thing to note is that we'll want to make sure the design-time build has already been kicked off earlier to avoid waiting for the design-time build up-to-date check.

**Comment by drewnoakes** [comment]
#3919 proposes a change that would store the project-relative path in `BuildUpToDateChecker._items` and only produce the rooted/absolute form when performing the actual check. This results in shorter strings in memory (some saving) but I suspect the project-relative strings are retained in memory for other purposes anyway, meaning there's minimal overhead in keeping another reference to them. I hope to verify this tomorrow through profiling.

**Comment by panopticoncentral** [comment]
I think #3744 might swamp any other optimizations, I might tackle that first, I'll take a look at the optimizations you did.

**Comment by davkean** [comment]
I think #3744 will automatically be fixed in Dev16 by the MSBuild changes. We should very that, I like @drewnoakes's approach better than my suggestion, it will be interesting to look at numbers.

**Comment by drewnoakes** [comment]
The up to date checker no longer holds full paths. It holds relative paths and only computes short-lived absolute paths when needed. Closing.

**Comment by drewnoakes** [comment]
> Is it possible it computes a hash value of the project state, instead of maintaining a large set of state?

This is something I'll look at as part of #4736, so hopefully we can reduce retained memory further.
