### ISSUE TITLE
Question: Is ruleset configuration a linear process?

### ISSUE THREAD

**Issue by taori** [dotnet/project-system#3929]
I just modified a solution while being under the impression that you're able to do hierarchic ruleset configuration, where in one ruleset you're setting an analyzer to error on a solution level, that that would be applied to all projects, unless there is a ruleset on the project level, which overrides specific settings, while allowing to inherit settings from the solution level.

Am i just imagining that it used to be like that in the past?

**Comment by Pilchie** [comment]
Closing for now - let me know if you have any follow-up questions here.
