### ISSUE TITLE
Intellisense broken after opening solution and restoring packages

### ISSUE THREAD

**Issue by maxinfet** [dotnet/project-system#3930]
When we open a new branch with no packages restored the intellisense will be broken for anything that is referenced from a nuget package. Then once we restore packages it will still be broken. The odd thing is that it is marked as an error but we can still build fine.

Our solution is using the old project system and uses package.config to restore nuget packages. Also we are on Visual Studio 15.8.2 but we started experiencing this issue in 15.8.1.

Here is a project I put together to demonstrate the issue https://www.dropbox.com/sh/pvuk4m8eponihro/AABkKghoPvUIyRJ2aU91R_Kqa?dl=0

To see the issue restore packages after opening the solution and then notice that the types from log4net in Program.cs are still marked as missing. Expanding references and then clicking on the log4net reference with the properties window opened seemed to cause it to evaluate whether it knew of those files or not.

**Comment by Pilchie** [comment]
@panopticoncentral can you take a look and see if this is related to the design time build changes?

**Comment by tmeschter** [comment]
@maxinfet Does this still reproduce when using 15.8.6 or newer?

**Comment by maxinfet** [comment]
I can not confirm in this in our main project because of issue #4158. I can no longer produce it in the reproduction project I attached to the issue though.

**Comment by Pilchie** [comment]
Closing given above.
