### ISSUE TITLE
Directories leading up to hidden files should not be shown in solution explorer when using new csproj format.

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/project-system#3931]
I've created [a minimal repository](https://github.com/PathogenPlayground/HiddenFileDirectoryShows) describing and demonstrating this issue. The following is a summary if reproducing the issue without it.

# Steps to reproduce

1. Create a C# project using the new `csproj` format (EG: create a project from the .NET Standard Class Library template.)
2. Add some hidden files to the project by manually editing the `csproj` file:

```xml
<ItemGroup>
  <None Include="$(OutputPath)\$(AssemblyName).dll" Visible="false" />
  <None Include="FolderThatDoesntExist\FileThatDoesntExist.txt" Visible="false" />
</ItemGroup>
```

# Actual behavior

The directories leading up to the hidden files are shown in the solution explorer even though the hidden files aren't.

This is not consistent with the behavior from the old `csproj` format as shown in the screenshot below:

![Image showing the issue as described](https://user-images.githubusercontent.com/278957/44869055-361d8480-ac52-11e8-9f78-b0585f19d1e6.png)

# Expected behavior

The directories are not shown in the solution explorer.

**Comment by Pilchie** [comment]
@lifengl - I suspect that this is a core CPS issue, right?

**Comment by lifengl** [comment]
Yes, it is a CPS issue

Sent from my phone

On Sep 4, 2018, at 11:29 AM, Kevin Pilch <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flifengl&data=02%7C01%7C%7C393689dbbb5e466caa6908d6129452f8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636716825579932237&sdata=VxisInN%2BmX1ylcILJyPX101BsdOe7ONL0oWSbkqAIZ4%3D&reserved=0> - I suspect that this is a core CPS issue, right?

**Comment by Pilchie** [comment]
Filed [677743](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/677743) to track internally.
