### ISSUE TITLE
Project is not saved after installing NuGet package as PackageReference

### ISSUE THREAD

**Issue by jainaashish** [dotnet/project-system#3932]
With PackageReference for classic csproj, NuGet uses `VSProject4` APIs to add/remove PackageReferences but Project is not saved afterwards. So Project system needs to save the project after these operations just like it does for sdk-style projects.

**Comment by davkean** [comment]
We don't save the project in SDK-style projects after installing projects. All project manipulation has always been in-memory for all project operations, that's the save model of Visual Studio.

**Comment by jainaashish** [comment]
ohh yeah even sdk-style project doesn't auto save it. But now it's a different experience than packages.config.

**Comment by davkean** [comment]
Or you could say packages.config was different to the rest of VS...

**Comment by jainaashish** [comment]
the core of the issue is people who are currently with packages.config, see a different behavior when migrate to PackageReference. and complains that even migration succeeded but they still dont see any change in project file.

**Comment by davkean** [comment]
For migration, just explicitly call Save on every project you touched.

**Comment by Pilchie** [comment]
As @davkean mentiones, this is by design.

@rido-min to avoid the dialog, changes to the file should be made through VS, not by writing the file directly.

**Comment by rido-min** [comment]
@jainaashish how do you persist the csproj?

**Comment by jainaashish** [comment]
we don't persist the file. As David mentioned, Project system keeps all these changes in-memory which are persisted when user explicitly save the project.
