### ISSUE TITLE
Pick up the sample solution，run failed with Server Error in '/' Application.

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/project-system#3947]
### Steps to reproduce
Pick up the sample solution [Src_2479.zip
](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fsdk%2Ffiles%2F2303997%2FSrc_2479.zip&data=02%7C01%7C%7C48397e3ebd35439e24e008d61287f64d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636716772491960303&sdata=uburUEu4U7uMEgDjEAcNs1EPMo5%2F%2FvJTKlSJU1U6mT8%3D&reserved=0)
### Actual behavior
![web](https://user-images.githubusercontent.com/33921754/45076446-ef7dcd80-b11c-11e8-9fd8-b4b79b05064e.png)
Workaround: Edit the Gaia.Frondend.Web.csproj and remove the PackageReference to SqlXml
```
<PackageReference Include="SqlXml">
      <Version>4.0.0</Version>
    </PackageReference><PackageReference Include="SqlXml">
      <Version>4.0.0</Version>
    </PackageReference>

```
Build and rebuild succeed with 47 warnings.
![web1](https://user-images.githubusercontent.com/33921754/45076883-2e605300-b11e-11e8-82b3-802368d4c9a8.PNG)
Run failed with Server Error in '/' Application.
Show the following info:
[ErrorInfo.txt](https://github.com/dotnet/project-system/files/2351649/ErrorInfo.txt)
### Test Environment:
**VS-Val\d15.8\products\28031.9000.licavalc.180831.132124**
dotnet --info:

> .NET Core SDK (reflecting any global.json):
> Version: 2.1.402
> Commit: 3599f217f4
> Runtime Environment:
> OS Name: Windows
> OS Version: 10.0.17134
> OS Platform: Windows
> RID: win10-x64
> Base Path: C:\Program Files\dotnet\sdk\2.1.402\
> Host (useful for support):
> Version: 2.1.4
> Commit: 85255dde3e
> .NET Core SDKs installed:
> 1.1.10 [C:\Program Files\dotnet\sdk]
> 2.1.202 [C:\Program Files\dotnet\sdk]
> 2.1.402 [C:\Program Files\dotnet\sdk]
> .NET Core runtimes installed:
> Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
> Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> To install additional .NET Core runtimes or SDKs:
> https://aka.ms/dotnet-download

**Comment by joperezr** [comment]
As I said on the previous mail, for this one we should simply edit the .csproj and remove the reference to that package, which should fix this issue.

**Comment by Pilchie** [comment]
@dsplaisted is this expected to work now with the conflict resolver fix?

**Comment by YunWeiaa** [comment]
Thanks, there is no enough time to test today, I will verify tomorrow.

**Comment by YunWeiaa** [comment]
When editing the Gaia.Frondend.Web.csproj and remove the PackageReference to SqlXml, then that error goes away. It shows many warnings about the format and package downgrade.
[warninginfo.txt](https://github.com/dotnet/project-system/files/2360607/warninginfo.txt)

**Comment by joperezr** [comment]
That's fine I think, this was a user provided solution, so I believe it did have some problems, but the main test was to make sure that we could get it compiling, which is the fix we added to msbuild extensions. If it compiled successfully then I think that it passed the test.

**Comment by richaverma1** [comment]
There is no product issue here. Closed the issue.
