### ISSUE TITLE
PackageReference and package includes XmlSerializer file is not being added

### ISSUE THREAD

**Issue by Styxxy** [dotnet/project-system#3953]
(Sorry if I am in the wrong repo, or if it is a duplicate issue (but I didn't find one when searching).)

I noticed that the XmlSerializer dll is not being copied, while in the old packages.config style.
Having a package with following nuspec (see nupkg (remove the zip extension), 
[Styxxy.MyPackage.1.0.0.nupkg.zip](https://github.com/dotnet/project-system/files/2352697/Styxxy.MyPackage.1.0.0.nupkg.zip)):

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Styxxy.MyPackage</id>
    <version>1.0.0</version>
    <authors>Styxxy</authors>
    <owners>Styxxy</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Styxxy.MyPackage</description>
    <references>
      <reference file="Styxxy.MyPackage.dll" />
    </references>
  </metadata>
</package>
```

Package content:
* lib\net47
  * Styxxy.MyPackage.dll
  * Styxxy.MyPackage.pdb
  * Styxxy.MyPackage.xml
  * Styxxy.MyPackage.XmlSerializer.dll

My project is in SDK format and targets net47, although this problem (xmlserializer not being copied) also happens with the old project format but with PackageReference.

**Comment by Pilchie** [comment]
@livarcocc - this sounds like a NuGet MSbuild task issue.  Does this below on https://github.com/dotnet/sdk?
