### ISSUE TITLE
Add some articles to the docs

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/project-system#3958]
Would be nice to expand the docs a little bit. Here are two good articles I found:

https://mhut.ch/journal/2015/06/30/build-time-code-generation-in-msbuild
https://mhut.ch/journal/2016/04/19/msbuild-code-generation-in-vs2015

It highlights the caveats around caching compiler arguments in the .suo, and cleaning vs. git cleaning.

**Comment by Pilchie** [comment]
Care to submit a PR?
