### ISSUE TITLE
Add shortcut key to edit project file

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#3968]
There's currently no shortcut key for editing the project file.

Discussion in #1224 came up with two ideas:

- Reusing <kbd>F7</kbd> (View Code) to view XML, and <kbd>Shift</kbd>+<kbd>F7</kbd> (View Designer) to view property pages
- Adding <kbd>Shift</kbd>+<kbd>Enter</kbd> to view the project file, reflecting the current <kbd>Alt</kbd>+<kbd>Enter</kbd> that views property pages

**Comment by davidwengier** [comment]
This is quite complicated, and there are a number of issues with this right now:

* We currently have Edit .csproj File and Properties menu items to perform these tasks
* F7/Shift+F7 are globally bound to View.ViewCode and View.ViewDesigner, and can't be bound to other menu items easily
* Adding View Code as a menu item to the project context menu is possible in theory but requires changes to VS and probably CPS
* The name "View Code" doesn't necessarily make sense, plus we'd want to get rid of the "Edit .csproj" menu item, so people might think they've lost functionality
* If we rename the "View Code" menu item dynamically to "Edit Project" for a project it could work, but then the View main menu would have an Edit Project item which would be weird
* Removing Properties (and Alt+Enter) with View Designer would surely upset people, as there is a lot of muscle memory with that.

Will keep this in mind but previewing the file might be a better solution, and probably will be easier to implement once some other work is done. Discussions continue internally.

**Comment by breyed** [comment]
Since <kbd>F7</kbd> and <kbd>Shift+Enter</kbd> each have their own challenges, I'd like to propose an easy interim (or possibly alternative) solution. Simply assign a unique accelerator key to the context menu item. Currently, "Edit <project>.csproj" is the red-headed step child with on accelerator key assigned.

For example, if you picked "i", then editing the selected project would be as quick as <kbd>Menu</kbd>+<kbd>I</kbd>.

**Comment by davidwengier** [comment]
Now that #4061 has been merged, the <kbd>Enter</kbd> key works for opening the project file, which works well with <kbd>Alt</kbd>+<kbd>Enter</kbd>

**Comment by davkean** [comment]
@davidwengier https://developercommunity.visualstudio.com/content/problem/345659/shortcut-missing-for-edit-project.html was dup'd against this, but that's asking for a shortcut/key binding. ENTER isn't a traditional key binding - as you have to have the project file selected for it to work.
