### ISSUE TITLE
Right-click -> Properties on reference should open Properties window, not pages

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#397]
Right-click on reference and choosing Properties should open Properties tool window, not the property pages modal window:

![image](https://cloud.githubusercontent.com/assets/1103906/18023774/31850c64-6bb2-11e6-9716-23c84f1af55b.png)

**Comment by davkean** [comment]
Note for files - looks like we're dup'ing the categories - see the linked bugs.

**Comment by srivatsn** [comment]
Fixed by #1999
