### ISSUE TITLE
How to add resource files to netstandard project

### ISSUE THREAD

**Issue by ramsubbaraoc** [dotnet/project-system#3987]
In .NET Framework, while adding resource files,the files can be added either as an EmbeddedResource or Resource.In netstandard class library project,there is only "EmbeddedResource" property.How to add a file as "Resource" instead of "EmbeddedResource" ?

I have language specific .resources file. If i add it as "EmbeddedResource" each file will be converted to a satellite assembly which i don't want. I want all the .resources file to be embedded into same class library rather than a new library.

csc.exe command line has that option, if we use -res option all the resource files get embedded into the same class library where the source code resides. 

Is there a way to do the same for netstandard class library project as well?

**Comment by Pilchie** [comment]
@livarcocc / @nguerrera / @dsplaisted ?

**Comment by Pilchie** [comment]
Also somewhat related to https://github.com/dotnet/project-system/issues/3620...

**Comment by Pilchie** [comment]
> The handling of @(Resource) items in .NET Framework comes from Microsoft.WinFX.targets, which mainly handles Xaml, and is never imported to a .NET Standard project

@cdmihai @nguerrera @dsplaisted does changing this as part of .NET Core 3 make sense?

**Comment by ramsubbaraoc** [comment]
@Pilchie @nguerrera : Thank you.That worked.But the ResourceManager class doesn't pick the resources based on the Thread  culture. Should i be hardcoding the "basename" based on the culture?

**Comment by nguerrera** [comment]
Indeed, ResourceManager does not support finding localized resources in the main assembly. 

Changing the base name like that doesn't seem right. I looked briefly at extending ResourceManager or ResourceSet, but there doesn't seem to be a good hook. cc @tarekgh

**Comment by nguerrera** [comment]
> @cdmihai @nguerrera @dsplaisted does changing this as part of .NET Core 3 make sense?

I think it does. I'm going to look more closely at these targets.

**Comment by Pilchie** [comment]
@nguerrera Should I move this to dotnet/sdk repo?

**Comment by nguerrera** [comment]
OK. It might need to move again to msbuild, but that's ok for now.

**Comment by Pilchie** [comment]
This issue was moved to dotnet/sdk#2532
