### ISSUE TITLE
Possible bug in GroupedByTargetTreeViewProvider

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#3996]
`GroupedByTargetTreeViewProvider.CreateOrUpdateProjectItemTreeNode` computes `flags` (line 404) but then never uses it. This computation is the only usage of its arguments `additionalFlags` and `excludedFlags`.

My _guess_ is `flags` should be used in place of `viewModel.Flags` below on line 421, as happens in related method `CreateOrUpdateProjectTreeNode`. If not then some code can be removed.

https://github.com/dotnet/project-system/blob/cc4af275e0f6b0a02462f6d291b58b82e9166dee/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/GroupedByTargetTreeViewProvider.cs#L395-L431

**Comment by abpiskunov** [comment]
For ProjectItems specifically we don't add or remove flags thats why it is working fine now. However for consistency we should use it in this method too or remove additionalFlags and excludeFlags parameters from that method completely.
