### ISSUE TITLE
Possible bug in SettingsDesignerLoader

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4013]
https://github.com/dotnet/project-system/blob/c2da4607fb924d0900bfa259badecc9b83eec8db/src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsDesignerLoader.vb#L71-L77

This code looks like it needs `LoaderHost.AddService(...)` before the `End If`.

As it stands, the value of `typeDiscoveryService` is not used anywhere after being looked up. The comment suggests that is not the intention.

(I have little context for this observation. I've been taking some time each day to read different chunks of the code.)

**Comment by Pilchie** [comment]
Seems plausible, though without knowing what is actually broken, I'm not sure it's worth preemptively changing.  It would also raise the question of whether `RemoveService` should be called for that.

**Comment by Pilchie** [comment]
Totally fine with this being fixed, but I think it will require some investigation about whether there is actually a customer bug here.  The other option would just be to delete the code :)

**Comment by davkean** [comment]
This code just needs to be deleted.
