### ISSUE TITLE
Error when creating a new class in a class diagram.

### ISSUE THREAD

**Issue by dutchmartin** [dotnet/project-system#4019]
[Project zip](https://drive.google.com/file/d/1Qdf3TbLL7Vnc9pYWqopGp3-MfXHZwQk1/view?usp=sharing)

<img width="1139" alt="errorsfds" src="https://user-images.githubusercontent.com/5509155/45543765-ac56e500-b815-11e8-8090-8711d52a3397.PNG">

After creating a new .net core console app in visual studio 2017 enterprise and adding a class diagram. Adding a class from the toolbox to the diagram gives the following error:
<img width="1280" alt="errorms" src="https://user-images.githubusercontent.com/5509155/45543639-49654e00-b815-11e8-87e7-872edb51da86.PNG">
The file the editor generates is empty and does not contain any code. (see zip)

The workarount is to repeat the class generation procces by dragging a new class into the diagram and using the same class name as where you previously got an error on.

**Comment by Pilchie** [comment]
@davkean - do you know where that message comes from?  Is it because of CodeModel being async in CPS?

**Comment by jjmew** [comment]
@davkean  so this is already tracked by [this](https://developercommunity.visualstudio.com/content/problem/33831/class-diagram-not-available-in-aspnet-core-project.html)?

**Comment by drewnoakes** [comment]
I cannot repro this in 17.5, though it might be a race condition and I'm just getting lucky despite trying quite a few times. Regardless, the underlying cause is believed to be #2544, so we will track this work there.
