### ISSUE TITLE
Confusing error when you attempt to delete a reference

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#402]
In legacy csproj this doesn't prompt, in CPS it does:

![image](https://cloud.githubusercontent.com/assets/1103906/18023838/270ab3e6-6bb3-11e6-89c4-c7571e83898d.png)

This is confusing - what does it mean that is contents will be removed?

**Comment by basoundr** [comment]
Blocked by #708

**Comment by abpiskunov** [comment]
yo are not blocked - open Add Reference dialog and uncheck your reference there

**Comment by basoundr** [comment]
This scenario happens only when going through the Remove Button and not through the Add Reference dialog.

**Comment by davkean** [comment]
Also get the same error when removing a Package reference:

![image](https://cloud.githubusercontent.com/assets/1103906/22102713/84959200-de8c-11e6-8a91-ee697d3e6b12.png)

**Comment by panopticoncentral** [comment]
Removing the Parity-Legacy tag from this one because it's not really a parity issue in terms of functionality. It's just a strange behavior of the project system that it would be nice to fix in general.
