### ISSUE TITLE
Cached analyzer is applied instead of updated one

### ISSUE THREAD

**Issue by taori** [dotnet/project-system#4031]
I've got a project which references a local nuget repo analyzer.

After updating the analyzer the build process works fine and uses the updated analyzer - Visual Studio still reports diagnostics of the previous analyzer version however in the error window, as well as the code window.

I think some cache needs to be invalidated here after nuget updates.

**Comment by Pilchie** [comment]
This issue was moved to dotnet/roslyn#29939
