### ISSUE TITLE
Add support for Nullable build setting

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#4058]
This is a tracking work item related to the "nullable reference types" feature in C# 8.0 (for dev16).
We'll add design notes here as it crystallizes (is it a property or some other form of API?)
Tagging @davkean

**Comment by jcouv** [comment]
The design for turning on the nullable feature changed since our last discussion.
Previously, we would have `[NonNullTypes]` (for class- or method-level control) or `[module:NonNullTypes]` (for module/project-level).
Now, we'll have `#nullable ...` for scoped control in source, and a compiler flag for project-level control. That compiler flag is exposed via [MSBuild property](https://github.com/dotnet/roslyn/pull/30574) `NullableReferenceTypes`, as part of dev16 preview1.

Based on this, there are two scenarios of interest:
1. exposing a checkbox in Build options ("Enable Nullable Reference Types")
2. allowing a codefixer to change this project property (like UpgradeProject does for LangVersion)

@davkean I assume that those scenarios translate into three work items:
1. some common work in project-system (object model or API change)
2. IDE work to add Build option UI (or is this also owned by project-system)
3. codefixer work (IDE/myself)

@davkean @Pilchie Do you think the API work (1) could be reasonably scheduled as part of preview 2? If yes, I would do the codefixer (3) in preview 2 as well.

**Comment by etbyrd** [comment]
I could get a PR out for the checkbox in the Build property page - do we have an idea of where on the page we would want it?

**Comment by jcouv** [comment]
For adding the checkbox to the Build property page, I think putting it under "Check for arithmetic overflow/underflow" would make sense.
@davkean Does that sounds ok?

**Comment by tmeschter** [comment]
I wouldn't want to add the checkbox without adding the underlying property support to csproj/msvbprj, and that's the expensive part.

**Comment by chucker** [comment]
In my testing, it looks like the `<NullableReferenceTypes>` property only works with new-style projects. Are there plans to make it work with the old project system (e.g., for an ASP.NET project)?

**Comment by jcouv** [comment]
@chucker Yes, this property will be made to work in old project system too, before C# 8 ships as RTM, but likely after dev16.0 (where C# 8.0 language features are in beta).
The present issue tracks this remaining work.

**Comment by jcouv** [comment]
@davkean We had to modify the options to add a third one (`true`/`false` were not enough) and changed the name of the option in the process.
I assume that the change of name affects project system, but the change of values doesn't. Let me know if that's not the case, as one of the options might still change.
Sorry for the randomization.

```
Through msbuild the context could be set by supplying an argument for a "NullableContextOptions" parameter of Csc build task. Accepted values are "enable", "disable", "safeonly", or null (for the default nullable context according to the compiler). The Microsoft.CSharp.Core.targets passes value of msbuild property named "NullableContextOptions" for that parameter.
```
https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-reference-types.md#setting-project-level-nullable-context

**Comment by Tragetaschen** [comment]
Given how I spent the last thirty minutes, it might be worth going through the existing blogs and docs for C# 8 and modify the samples on how to set up that feature. That name change and the new option names took quite some time to figure out.

Some examples are https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types or https://blogs.msdn.microsoft.com/dotnet/2018/12/05/take-c-8-0-for-a-spin/

**Comment by jjmew** [comment]
This issue is tracked internally by https://dev.azure.com/devdiv/DevDiv/_workitems/edit/823504

**Comment by jcouv** [comment]
From LDM discussion today (5/1/2019) including Phillip, we concluded that "Nullable" would be a better name than either "NullableReferenceTypes" or "NullableContextOptions". It should remain a string (to accept "enable", "disable" and a couple of other values).

Relates to compiler work item https://github.com/dotnet/roslyn/issues/35432

**Comment by jnm2** [comment]
`<Nullable>enable</Nullable>` is not getting picked up by old-style csprojs. Everything works if we have to put `#nullable enable` in every file, but that's distasteful.

We can't move to SDK-style csproj until https://github.com/dotnet/project-system/issues/4938 ships in 16.4 in November.

Is there a workaround for this?

**Comment by jnm2** [comment]
It's working when I build with MSBuild Structured Log Viewer but the IDE is adamant that nothing is in a nullable context. Maybe this is an IDE bug?

**Comment by jnm2** [comment]
Full repro for 16.3.1 and 16.4p1:

```cs
public class C
{
    // CS8632 The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.;
    //                  ↓
    public void M(string? nullableParameter)
    {
    }
}
```

Brand new old-style csproj with LangVersion 8.0 and Nullable enable:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>0098472d-d4d6-4ea1-9a6b-142942f81782</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>OldStyleCsproj</RootNamespace>
    <AssemblyName>OldStyleCsproj</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System"/>
    
    <Reference Include="System.Core"/>
    <Reference Include="System.Xml.Linq"/>
    <Reference Include="System.Data.DataSetExtensions"/>
    
    
    <Reference Include="Microsoft.CSharp"/>
    
    <Reference Include="System.Data"/>
    
    <Reference Include="System.Net.Http"/>
    
    <Reference Include="System.Xml"/>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Class1.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
 </Project>
```

**Comment by jnm2** [comment]
Moved bug report to separate issue: https://github.com/dotnet/project-system/issues/5551

**Comment by jcouv** [comment]
@drewnoakes @chucker @tmeschter @davkean I noticed this old issue. I assume that we still want to expose this checkbox. What release should we aim for?

**Comment by drewnoakes** [comment]
@jcouv I took a look at this but hit a block that would require help from @davkean or someone else who knows the details of the property pages better than me.

In short, adding the UI was straightforward, however we only want to enable that UI when `LangVersion` is 8 or greater. Sniffing the current version using the APIs available in the property pages (that must work with both legacy and CPS projects) gave me some trouble.

**Comment by chucker** [comment]
@drewnoakes regarding legacy projects, I take from https://github.com/dotnet/project-system/issues/5551#issuecomment-563249987 that this is no longer planned, so the UI can focus on CPS.

(I'd love to be wrong, though.)

**Comment by drewnoakes** [comment]
PR #5807 is up to fix this.
