### ISSUE TITLE
UpToDate checker does not respect CopyBuildOutputToOutputDirectory

### ISSUE THREAD

**Issue by rojepp** [dotnet/project-system#4059]
When setting `<CopyBuildOutputToOutputDirectory>false</CopyBuildOutputToOutputDirectory>`, a project will rebuild on every build because UpToDate checker is looking for the non-existent assembly.
At least that's what I think is happening: 

> Project 'AppConfig' is not up to date. Error (0x8000FFFF). 

This project is not meant to produce an assembly, just a VSTemplate.
Found this in https://github.com/Microsoft/visualfsharp (in a C# project)

**Comment by davkean** [comment]
@drewnoakes This is in reference to the legacy project system. Can you see how the new project system handles this?

**Comment by drewnoakes** [comment]
The new project system does indeed consider a project up to date when `CopyBuildOutputToOutputDirectory` is `false`.

https://github.com/dotnet/project-system/blob/9bac1e669c67e5d0c44486be595d7ec6323461ca/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L391-L394

This causes the up to date check to consider the following inputs only:

```
obj\Debug\netstandard2.0\MyProject.dll
bin\Debug\netstandard2.0\MyProject.pdb
obj\Debug\netstandard2.0\MyProject.pdb
```

So this issue appear to only apply to legacy.

**Comment by tmeschter** [comment]
Tom's triage notes: this is a legitimate bug in the fast up-to-date check; we should fix it.

**Comment by kvenkatrajan** [comment]
@drewnoakes - is this still an issue?

**Comment by drewnoakes** [comment]
@kvenkatrajan I don't believe there's been any change here. However the issue should be tracked internally and moved to the csproj team.

**Comment by ocallesp** [comment]
Moved to csproj  AB#1679609
