### ISSUE TITLE
Stop passing RDT_ProjSlnDocument to RDT

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4066]
We need to stop passing RDT_ProjSlnDocument in CProject::HrRegister for a hierarchy where VSHPROPID_IsNonSearchable equals false. This unblocks shell document service and find from explicitly blocking these files from being open.

**Comment by davidwengier** [comment]
PR for this: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/147429

**Comment by davidwengier** [comment]
PR has been merged
