### ISSUE TITLE
Allow project to be opened in the Preview tab

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4068]
- [x] Indicate that we can be opened in tab

Whether something shows up in "preview" tab is going to be controlled by `CommonPhysicalViewAttributes` (in particular set it to `00000002`) on the ProjectFileEditorFactory registration in CPS. 

- [ ] Stop the shell from blocking us

Inside CVsUIShellOpenDocument.IsIgnorableFile there's a check that filters projects (RDT_ProjSlnDocument) and virtual documents (RDT_VirtualDocument). The former will be handled by https://github.com/dotnet/project-system/issues/4066, however, we should figure out what to do with RDT_VirtualDocument as this will continue to block project files which are marked as such.

- [x] Implement DoubleClick/Enter command to respond to provisional tab open requests

- [x]  File | Open, Error List and Find Results windows should open in text edit mode

**Comment by davidwengier** [comment]
Microsofties, PR is here: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/146935

**Comment by davidwengier** [comment]
PR has been merged
