### ISSUE TITLE
Figure out how AppDesigner and Project File editor play with each other to unblock Find when the former is opened

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4070]
If AppDesigner is open, ShellOpenDocumentService wants to activate it with a different logical view IVsMultiViewDocumentView.ActivateLogicalView when AppDesigner is open and you use **Find** set to **Project** or **Solution**. We need to figure out what that means.

**Comment by davidwengier** [comment]
PR has been merged

**Comment by davkean** [comment]
Reopening this, this still occurs:

1. Create new Console App (.NET Core)
2. Right-click and choose Properties
3. Let Program.cs be focus
4. CTRL+F and enter "TargetFramework"
5. In Find where, choose **Project** or **Solution** and click Find Next

Expected: Project file to open
Actual: 

![image](https://user-images.githubusercontent.com/1103906/48484448-4a911680-e86a-11e8-9131-f17bdb91788b.png)

**Comment by davidwengier** [comment]
I have solved this with a change in CPS and Project System. Need to check C++ and Web Applications to make sure the CPS change doesn't break anyone else.
