### ISSUE TITLE
ML should switch to use new slim version dataflow blocks in most of the code (after taking the breaking change)

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#4122]
Switch to use slim version of dataflow blocks provided by DataflowBlockSlim, especially for ActionBlock/TransformBlock usages.  The new blocks use much less memory.

This is for Dev16 only, and only after the breaking change is merged.

**Comment by jmarolf** [comment]
Done [here](https://github.com/dotnet/project-system/pull/4106)
