### ISSUE TITLE
Empty NPM package list shows warning on "npm" dependencies node

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4130]
_(Migrated from [Developer Community](https://developercommunity.visualstudio.com/content/problem/352983/npm-folder-under-dependencies-has-warning-sign.html))_

I have a teammate that added `package.json` under a Web API project. It seams to caused Visual Studio to create a "npm" folder under "Dependencies" that has a warning sign. Project appers to still build, but makes you think something is wrong. I am running latest 15.8.6.

Contents of `package.json` file:

```json
{
	"name": "@company/web.api",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"build": "dotnet publish -r linux-x64 -c Release -o dist",
		"start": "dotnet run",
		"test": "dotnet test"
	}
}
```

**Comment by jrybacek** [comment]
I have many colleagues who have also experienced this issue.  It was resolved by adding a Visual Studio extension called WebPack Task Runner.  I have no idea why that task runner extension fixes the yellow triangle on the "npm" folder under "Dependencies", but it appears to.  I hope this can help others having the same problem.

**Comment by drewnoakes** [comment]
This issue appears to be in the WebToolsExtensions project system, which is hosted internally rather than on GitHub. I'm closing this issue (and re-opening the [developer community ticket](https://developercommunity.visualstudio.com/content/problem/352983/npm-folder-under-dependencies-has-warning-sign.html)) so this can be routed properly.
