### ISSUE TITLE
FUTD false positives when using Content + PreserveNewest

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/project-system#4132]
Reported by @bradphelan at https://github.com/Microsoft/msbuild/issues/2684.

Using the reference project

https://github.com/bradphelan/msbuild-incremental-build-fail

which includes the simple project file

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Foo\TextFile1.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
```

![image](https://user-images.githubusercontent.com/17650/32212097-af8bc24a-be15-11e7-93d7-1cb189426fb5.png)

every time build is initiated it rebuilds.

My build log is

https://gist.github.com/bradphelan/c6bd0f32d62c09d7cb1e7a164b0f00af

**Comment by davkean** [comment]
@drewnoakes I think we fixed this, can you confirm?

**Comment by drewnoakes** [comment]
Cannot reproduce on `master`.

**Comment by kellyelton** [comment]
Using Resource + PreserveNewest causes this same behavior (forces a build every time).

**Comment by drewnoakes** [comment]
@kellyelton what VS version are you using? Can you turn on "info" level logging and paste the contents of the output window here?

![image](https://user-images.githubusercontent.com/350947/88011704-61b5fa80-cb5b-11ea-95ea-de9fc6749d64.png)
