### ISSUE TITLE
Possible bug in DuplicatedDependenciesSnapshotFilter

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4133]
https://github.com/dotnet/project-system/blob/85d226c52dfd6b3b5e2534f3aa108c4471914f28/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/Filters/DuplicatedDependenciesSnapshotFilter.cs#L57

Should this equality test be passing `StringComparison.OrdinalIgnoreCase` as is done above on line 40?

**Comment by Pilchie** [comment]
@abpiskunov @tmeschter any ideas?

**Comment by tmeschter** [comment]
Yes, we should be using `StringComparison.OrdinalIgnoreCase` there as well.
