### ISSUE TITLE
Build order incorrect where project targeting multiple frameworks have conditional references

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4149]
In VS2017 15.8.7 the build order is incorrectly generated in cases where a project targeting multiple frameworks contains project references with a target framework condition along side other project references without a condition.

In my scenario, I have the following projects:

Project1 targeting netcoreapp2.1 and net461
Project2 targeting netstandard2.0
Project3 targeting net461.

Project1 references Project2 unconditionally, and references Project3 with a net461 target framework condition.

Visual Studios seems to be determining the build order based on the first item in the TargetFrameworks element. A TargetFrameworks value of 'netcoreapp2.1;net461' results in a build order of: Project2, Project1, Project3. If the target frameworks are reordered to 'net461;netcoreapp2.1', however, the build order is correct and the solution builds successfully: Project3, Project2, Project1

This only occur in VS on the first build following a clean due to the out of order projects still building.

I am able to reproduce and have attached an example solution.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/360683/build-order-incorrect-where-project-targeting-mult.html
VSTS ticketId: 708155_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by Pilchie** [comment]
This is related to https://github.com/dotnet/project-system/issues/1162, but fixing it would require us to consider references from all tfms as part of reporting build ordering to the shell.

@davkean is this something feasible to do with your new config hookup stuff?

**Comment by davkean** [comment]
The new config hookup doesn't handle this, but CPS should be changed to respect the "implicitly active configs" when reporting dependencies to the build manager.

**Comment by etomm** [comment]
Still present in 15.8.9... I had a huge headache due to this. I should mention that dotnet build and msbuild from the command line works as expected.

**Comment by jjmew** [comment]
> So, you're saying that this issue should move to core CPS?

@davkean I see you added the "Need CPS Feature" label. Does that mean that were is work on both sides?

**Comment by rainersigwald** [comment]
One possible workaround is something like https://github.com/rainersigwald/examples/commit/9be10a1b47c6fc85e508f95064047857fa23be62.

**Comment by drewnoakes** [comment]
We briefly discussed this in the CPS sync meeting today. The CPS team said this is fixed in 17.3.
