### ISSUE TITLE
vs cann't load project

### ISSUE THREAD

**Issue by Varorbc** [dotnet/project-system#4153]
common.props

	<Project>
      <PropertyGroup>
        <TargetFramework>net452</TargetFramework>
      </PropertyGroup>
    </Project>
	
Test.csproj

    <Project Sdk="Microsoft.NET.Sdk">
    
      <Import Project="../../common.props" />
    
      <PropertyGroup>
        <TargetFramework>net452</TargetFramework>
      </PropertyGroup>
      
    </Project>
    
vs can load project
	
Test.csproj

    <Project Sdk="Microsoft.NET.Sdk">
    
      <Import Project="../../common.props" />
    
      
      
    </Project>
    
vs can load project
    
Test.csproj

    <Project Sdk="Microsoft.NET.Sdk">
    
      <Import Project="../../common.props" />
      
    </Project>
    
vs cann't load project

**Comment by davkean** [comment]
Known, see https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md#project-type-guids for workarounds. You need to manually update the GUIDs in the sln.

**Comment by Varorbc** [comment]
Why not vs automatically update, not manual?

**Comment by davkean** [comment]
It's a limitation due to both new and old project system having the same extension, the issue is being tracked by https://github.com/dotnet/project-system/issues/1358.

Thanks for raising an issue, I'm going to dupe this against the above bug.

**Comment by alexeyzimarev** [comment]
My solution is to add the `ToolsVersion="15.0"` to the `<Project>` tag in the `csproj` file:

```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
```

**Comment by Pilchie** [comment]
@alexeyzimarev  Note - doing that will have unexpected consequences, as it will open with the traditional C# project system, not the new one intended for the lightweight project format.  Opening may work, but most operations that modify the project file are likely to do the wrong thing.

**Comment by alexeyzimarev** [comment]
@Pilchie do you think that the migration that was performed by VS 2017 that inserted this attribute, was actually doing the wrong thing? I personally don't use VS nor Windows, and I usually manually change the project file, just tried to help colleagues that struggled after we moved the `TargetFramework` tag to the props file. However, so far we have not seen any issues. I cannot imagine that suddenly the VS will start changing the csproj file concent with the old project system. I don't observe this happening.

**Comment by Pilchie** [comment]
Yes, lacking either a `<Target Framework> / <TargetFrameworks>` element or a `ToolsVersion` attribute - VS was thinking that it was a VS 2005 or earlier project and trying to upgrade to something newer.  Perhaps you've already worked around this by setting the GUID in the sln file as @davkean described above.

**Comment by alexeyzimarev** [comment]
No, I haven't changed the guid. I worked in Rider and everything worked properly and then people started to complain that it doesn't work in the VS. So, I opened it in VS 2017 and it offered me to do the migration, the project format was kept as before, except that attribute and after adding it to all projects, we were able to load the solution in the VS.

**Comment by Pilchie** [comment]
Well, all I can say is that I'm surprised that it works, and I'm not sure *how* it does...
