### ISSUE TITLE
Provide an implementation of BuildManager to produce TempPE assembly during type resolution

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#4163]
When opening designers the type resolution service makes calls to the projects BuildManager in order to get it to compile design time files into a TempPE assembly. CPS has everything we need to be able to provide our own implementation of this.

- [x] Create DesignTimeInputsDataSource, that produces a set of design time inputs and shared inputs
- [x] Create DesignTimeInputsFileWatcher, that consumes DesignTimeInputsDataSource and watches inputs for changes
- [x] Create TempPECompilerManager that consumes DesignTimeInputsDataSource and DesignTimeInputsFileWatcher and compiles DLLs
- [x] ~Create TempPEBuildManager that consumes DesignTimeInputsDataSource and DesignTimeInputsFileWatcher and fires events~ (Removed: Too much overlap with TempPECompilerManager
- [x] Split TempPECompilerManager into two components, one to produce changes to design time inputs, and one to compile said changes into DLLs (#5231)
- [x] Create DesignTimeInputsBuildManager that consumes the changes datasource from above, and fires events (#5232)
- [x] Wire up BuildManager to call into DesignTimeInputsBuildManager

Design (subject to change):
![image](https://user-images.githubusercontent.com/754264/62267561-d3d79000-b46f-11e9-9707-033a9cf59cfe.png)

Relates to [AB#825236](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/825236)

**Comment by davidwengier** [comment]
In a project with just over 1000 `.cs` files, one of which is a design time input and one of which is a shared design time input, mutating the solution state to compile just those two files is only 5.8% of the CPU time spent, compared to 94.2% doing the actual compilation.

**Comment by davidwengier** [comment]
This is related to AB#825236

**Comment by dmonroym** [comment]
@davidwengier interestingly enough when you mention the work item in a comment it doesn't add the link in the AzDo side. This means that we have to add it either in the description (when it's a PR or issue) or on the commit message.

**Comment by davidwengier** [comment]
It did end up adding a link about 2 hours ago. Azure was just busy yesterday :)

**Comment by dmonroym** [comment]
I actually added the comment on the description, that's why it got linked 😆

**Comment by davidwengier** [comment]
Oh, thank you! GitHub must not notify about edits I guess.
