### ISSUE TITLE
Legacy project format doesn't respect conditions in Directory.Build.props and targets for PackageReference

### ISSUE THREAD

**Issue by jainaashish** [dotnet/project-system#4175]
_From @Styxxy on October 23, 2018 21:0_

# Description
When having a Directory.Build.props and/or Directory.Build.targets file, where you include a `<PackageReference />` these files are also included (by MSBuild, also Visual Studio) for legacy based project files (non-sdk format project files). This is great, except that when you set a condition on the `<PackageReference />` or it's `<ItemGroup>`, even if the condition would evaluate to `false` (and thus it should be skipped), the package is still included in the project. This doesn't happen for an SDK based project.

# Reproducable sample repository
https://github.com/Styxxy/Issue-BuildPropsTargets

# Environment details

## msbuild /version
```cmd
C:\Users\Styxxy>msbuild /version
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.8.169.51996
```

## dotnet --info
```cmd
C:\Users\Styxxy>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  ```
  
 ## Visual Studio 2017
 
Microsoft Visual Studio Community 2017 
Version 15.8.7
VisualStudio.15.Release/15.8.7+28010.2046
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

_Copied from original issue: Microsoft/msbuild#3874_

**Comment by jainaashish** [comment]
_From @Styxxy on October 23, 2018 21:19_

The package is still restored and _referenced_ in the (legacy) project. This doesn't happen for the SDK based project (= correct behaviour). In the sample repository, I referenced the FxCop analyzers, so they are executed on build (while I forced the condition to be **false**, the package shouldn't be referenced).

Screenshot from Visual Studio (to visualize it a bit):
![msbuild-issue-3874](https://user-images.githubusercontent.com/1635825/47391363-e02d0080-d719-11e8-8f17-da88f8ecaca7.png)

As you can see, in the old style project the nuget package is added (= faulty behaviour); in the sdk style project the nuget package is not added (= correct behaviour).

**Comment by Styxxy** [comment]
@rainersigwald Thanks for moving.

Bigger problem is when the (legacy) project uses still packages.config, this behaviour causes the project to switch of restore method and thus breaking the packages.config references
-> This is not included in the sample repository (but I'll add it in a few hours).

**Comment by jainaashish** [comment]
@Styxxy Can you elaborate more on `legacy projects with packages.config` scenario? what exactly is broken there?

**Comment by Styxxy** [comment]
@jainaashish Because of the described scenario, a PackageReference is added. For that, the system doesn't detect the packages.config anymore and thus doesn't restore the packages specified in the packages.config. This causes an invalid reference and building would fail. But the root cause is the PackageReference that is added where it shouldn't have done that.

**Comment by jainaashish** [comment]
You can either have `PackageReference` OR `packages.config` to manage your NuGet dependencies, not both. So onceit saw there was some `PackageReference` then it ignored `packages.config` file which is the right expectation. 

Once Project-system fixes it, then NuGet won't see any `PackageReference` and it will continue to use `packages.config` to manage NuGet dependencies.

**Comment by Styxxy** [comment]
@jainaashish Yes exactly. I just wanted to mention this, to highlight that this can be blocking (it is in my company at least, because we can't migrate for many projects to PackageReference yet, due to some internal nuget packages that need to be updated).

**Comment by rainersigwald** [comment]
@Styxxy I'm not totally sure it'll work in your case, but have you tried putting the condition on an `<Import>` that contains the `ProjectReference`s, rather than on the items/group? That can sometimes bypass "ignore conditions" style evaluations.

**Comment by Styxxy** [comment]
@rainersigwald Yes, I tried that but this doesn't fix the problem.

**Comment by Pilchie** [comment]
The old project system APIs that are used here have never respected conditions - I'm hesitant to change that here, since it's 15 years of legacy...

The normal workaround for this with `<Reference>` elements was to put them in a `<Choose>` / `<When>` block instead of putting the conditions directly on the element.  Does that work here?

**Comment by Styxxy** [comment]
@Pilchie 
Thanks for the suggestion. Seems to be working for the moment (with my repro repository), though I had to delete the ".vs", "bin" and "obj" folders. I will test this a little bit more extensively to be sure everything works.

My **Directory.Build.targets** is now:
```xml
<Project>
  <Choose>
    <!-- CustomCondition is in this case false -->
    <When Condition=" '$(CustomCondition)' == 'true' ">
      <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.6.1" />
      </ItemGroup>
    </When>
  </Choose>
</Project>
```

Maybe a suggestion to add this information on the docs (https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2017#directorybuildprops-and-directorybuildtargets)?

**Comment by jjmew** [comment]
We don' think it makes sense for us to modify the behavior since we have 15 years worth of legacy. We would like to keep the same behavior.
