### ISSUE TITLE
Unable to get updates to the lowest level package

### ISSUE THREAD

**Issue by Varorbc** [dotnet/project-system#4193]
For example, when I have three packages, A depends on,B depends on C. When C updates, project refer to package A cannot get updates to package C

**Comment by Pilchie** [comment]
Can you describe what you mean in more detail?  How are you referring to packages, what did you try and what did you observe?

**Comment by Varorbc** [comment]
for example,i have a project refer to `Newtonsoft.Json` package, `Newtonsoft.Json` package depend on `System.ComponentModel.TypeConverter` package(.NETStandard 1.0), `System.ComponentModel.TypeConverter` package depend on `System.Collections` package(.NETStandard 1.0). when `System.Collections` package updates, i Unable to get updates.I have to wait for them to update at the level before I get the lowest update

**Comment by Pilchie** [comment]
This issue was moved to NuGet/Home#7460
