### ISSUE TITLE
Unable to run exe project in debug mode

### ISSUE THREAD

**Issue by elhelmer** [dotnet/project-system#4209]
While in VS starting the project in debug mode immediately after it builds I get the below pop-up:
<img width="958" alt="debugerror" src="https://user-images.githubusercontent.com/44676174/47860325-8679a580-ddad-11e8-9aed-836593b8f0d5.PNG">

it reads: We have an active configuration that isn't one of the known configurations.

**Comment by Pilchie** [comment]
From an internal mail thread, the issue is that most projects in the solution do not correctly specify the configuration and platform to use these need to be specified as described in  https://github.com/dotnet/project-system/blob/master/docs/configurations.md
