### ISSUE TITLE
package properties tab should expose the new license property

### ISSUE THREAD

**Issue by karann-msft** [dotnet/project-system#4213]
License URL is being deprecated in favor of License.

Licenses are now going to be a part of the NuGet package - [Packaging License within the nupkg](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg)

There are now two ways to specify the package license:
1. using an SPDX identifier OR
2. including a license file within the nupkg

The package property page needs to be updated to surface these options:

![image](https://user-images.githubusercontent.com/16904420/47885964-cadc6400-ddf4-11e8-820c-e43217d4bf30.png)

If the expression is populated, the project file should be updated with:
`<PackageLicenseExpression>MIT</PackageLicenseExpression>`

If a license file is selected, it gets copied to the project root, and the project file should be updated with:
```
<PropertyGroup>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
</PropertyGroup>

<ItemGroup>
    <None Include="LICENSE.txt" Pack="true" PackagePath="$(PackageLicenseFile)" Visible="false" />
</ItemGroup>

```

**Comment by etbyrd** [comment]
Merged https://github.com/dotnet/project-system/pull/4223 - should be in Preview 5
