### ISSUE TITLE
Editing a csproj file through the integrated diffing tool is not possible

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4214]
While we now can edit the real csproj for sdk-styled projects, when diffing the csproj files before a commit, the editor still considers the files as readonly.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/238045/editing-a-csproj-file-through-the-integrated-diffi.html
VSTS ticketId: 604467_
_These are the original issue comments:_

Fannie Wang [MSFT] on 24/04/2018, 01:03 PM (191 days ago): <p>Thank you for your feedback! What's the real csproj for sdk-styled project? For us to investigate this further, could you please provide your exact repro steps?  We look forward to hearing from you!</p>

Jérôme Laban on 24/04/2018, 10:25 PM (191 days ago): <p>Thanks Fannie,</p><p>Microsoft is definitely in need for a good name for this type of project file format to avoid confusion :)</p><p>Here's how to repro:</p><ul><li>Create a .NET Standard 2.0 library project</li><li>Check the create a git repository</li><li>Commit the current changes</li><li>Add any nuget package to the project</li><li>Go the git changes, diff the modified csproj file</li><li>Try modifying the csproj file on the right pane of the diffing window, notice it is read-only and should not be.<br></li></ul><p>Thank you!</p>

David Kean [MSFT] on 25/04/2018, 08:40 AM (191 days ago): <p>Reopening this.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by davkean** [comment]
Duping against https://github.com/dotnet/project-system/issues/4215.
