### ISSUE TITLE
Show our project file editor in the right hand side of diff view

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#4215]
Currently when diffing a project file the right hand side is a plain text buffer (readonly, no colorization). We should make it use the our editor for a better experience.

Because the project file is always open this line is presumably a problem: 
http://index/?query=DocumentOpeningService&rightProject=Microsoft.VisualStudio.Editor.Implementation&file=DocumentOpeningService.cs&line=65

We need to ensure that the buffer passed to GetDocumentBuffer is the IVsTextLines returned from here:
http://index/?query=%60IVsTextBufferProvider&rightProject=Microsoft.VisualStudio.ProjectSystem.VS.Implementation&file=Editor%5CVsTextBufferProviderAggregator.cs&line=67

Also double check that legacy isn't broken because of [this](http://index/?query=%60IVsTextBufferProvider&rightProject=Microsoft.VisualStudio.AppDesigner&file=PropPageDesigner%5CPropPageDesignerDocData.vb&line=275) and that opening the diff while the app designer is open doesn't try to reuse that buffer.

**Comment by davkean** [comment]
Note this was also a feedback item: https://developercommunity.visualstudio.com/content/problem/238045/editing-a-csproj-file-through-the-integrated-diffi.html.

**Comment by davidwengier** [comment]
More feedback: https://developercommunity.visualstudio.com/idea/482797/project-files-cant-be-edited-in-diff-mode.html

**Comment by davidwengier** [comment]
Internal PR and this repos PR have been merged.
