### ISSUE TITLE
'Sign the assembly' drop down flutter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4244]
Each time I click on the 'Choose a string name key file:' drop down, 
The first click opens the drop down list, 
BUT THEN IS CLOSED
The second click works as expected

I suspect a context refresh is happening in the background, asynchronously.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/377859/sign-the-assembly-drop-down-flutter.html
VSTS ticketId: 725546_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by etbyrd** [comment]
Moved the underlying internal issue to DevDiv\NET\NET Framework\ClickOnce because that is where the page is

**Comment by OzBob** [comment]
@etbyrd if you move it to  DevDiv\NET\NET Framework\ClickOnce how can I track it?

**Comment by davkean** [comment]
Sorry about the runaround, you can use the original issue to track it: https://developercommunity.visualstudio.com/content/problem/377859/sign-the-assembly-drop-down-flutter.html. It was moved here, because the impression was that we owned this code. We do not, so we've moved it back.
