### ISSUE TITLE
Extender Provider failed when Signing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4245]
Sign an assembly
New key file
OK

&quot;The Extender Provider failed to return an Extender for this object.&quot;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/377929/extender-provider-failed-when-signing.html
VSTS ticketId: 725653_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_

Kevin Pilch [MSFT] solved on 11/8/2018, 09:04 AM (2 min ago), 0 votes: <p>We have moved this issue to a relevant GitHub project. Please comment and track it at this URL:  <a target='_blank' href="https://github.com/dotnet/project-system/issues/4244">https://github.com/dotnet/project-system/issues/4244</a> 
</p>

**Comment by etbyrd** [comment]
Moved the underlying internal issue to DevDiv\NET\NET Framework\ClickOnce because that is where the page is

**Comment by davkean** [comment]
This is very likely a project system problem, can you repro this @etbyrd?

**Comment by OzBob** [comment]
I'm happy to provide any project level information required.  It was intermittent and closing VS2017 and opening it and removing the SNK file and starting the signing process again, "worked". (except for the glitch where you have to click on the SNK drop down twice to be able to select the 'New ...' option #4244 )
