### ISSUE TITLE
Light up VB WinForms/WPF property pages

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4249]
WinForms/WPF have different property pages for VB, we should light them up based on capabilities as called out in https://github.com/dotnet/project-system/issues/4248.

**Comment by davkean** [comment]
It also does for C#: https://github.com/dotnet/project-system/issues/70.

**Comment by Pilchie** [comment]
See also #70.

**Comment by Pilchie** [comment]
Doh, same as @davkean's comment from Dec 11th.

**Comment by davidwengier** [comment]
I've started looking into this and it seems like the first thing to solve is the MyApplication property, which we don't currently support and can't be represented in a XAML rule.

**Comment by davkean** [comment]
Even when we have custom data sources applied to a rule?

**Comment by davidwengier** [comment]
Thats what I'm looking at right now. Looks like we can either define it as an EnumProperty and use a custom provider, or define a StringProperty and specify a custom persistence provider and have that do the work. Either way is a bit hacky sounding.

**Comment by davkean** [comment]
I don't know what property we're talking about, so hard to provide input.

**Comment by davidwengier** [comment]
The `MyApplication` property, part of `VBProjectProperties3`. Returned [here](http://index/?query=%60GetMyAppProperties&rightProject=VisualStudio(Repo)&file=vsproject%5Cvsprojectprops%5CVsProjectProperties.cpp&line=5246) in legacy, its an instance of our `MyApplicationManager`

**Comment by davkean** [comment]
How would an enum property help here? From a quick look, this would be a data source that returns an instance of IVsMyAppManager.

**Comment by davidwengier** [comment]
It might not, just thinking out loud :)

**Comment by melytc** [comment]
Closing as this is taken care of in the Project Properties UI.
