### ISSUE TITLE
Item templates should marked with appropriate capabilities

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4250]
We need to mark item templates with appropriate [project capabilities](https://github.com/dotnet/project-system/issues/4248) so that they light up in projects targeting WinForms/WPF. We need to do it a such a way that it continues to show up for legacy.

- [x] Mark WinForms/WPF item templates with appropriate project capabilities `<AppliesTo>` and remove _any_ TemplateGroupID
- [x] Change legacy project system to opt into "WinForms" capability (whatever is decided above)
- [x] Change WPF flavor of legacy project system to opt into "WPF" capability (whatever is decided above)

**Comment by wjk** [comment]
@davkean Question for you. I was thinking of starting work on this issue with my fork, by taking a copy of the templates from a VS2019 p2 install, and modifying them to see if I can make them work with Core. However, that being said, where in this repo should I put them? I've considered submitting a PR to the dotnet/winforms repo, but I don't _quite_ think that VS extension content really belongs in that repo/solution. I'll work on them in this repo until/unless I receive guidance otherwise. Thanks for your input!

**Comment by davkean** [comment]
We don't have current plans to open source these templates, so a contribution for them wouldn't be helpful at the moment. Once we've figured out above, we might then go and open source them.

**Comment by davidwengier** [comment]
Path to templates in VS repo: src\vsproject\Templates\Windows\CSharp\ItemTemplates (eg WPF\WPFPage\WPFPage.vstemplate)

**Comment by cartermp** [comment]
Not sure if this is applicable to this bug, but another issue to resolved for item templates:

* Need to update the project file SDK to be `Microsoft.NET.Sdk.WindowsDesktop` if not present
* Need to add `<UseWPF>true</UseWPF>` or `<UseWinforms>true</UseWinforms>` if not present

@davidwengier should I file a separate issue?

**Comment by davidwengier** [comment]
@cartermp Probably a new issue. I've logged #4718

**Comment by tmeschter** [comment]
@jmarolf Has this been addressed or is there further work to do?

**Comment by davidwengier** [comment]
I left this open because [winforms templates](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/175581?_a=overview) are still pending.

**Comment by davkean** [comment]
I also believe there's still more WPF templates that are showing up when they aren't supposed to.

**Comment by jmarolf** [comment]
Fixed with [AD#175581](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/175581)

**Comment by davkean** [comment]
Reopening this, this was added in the wrong location: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/175581?_a=files&path=%2Fsrc%2Fvsproject%2Fflavors%2FProjectFlavoring%2FMicrosoft.VisualStudio.ProjectFlavoring%2FMicrosoft%2FVisualStudio%2FProjectFlavoring%2FCapabilities%2FProjectFeaturesCapabilitiesProvider.cs. It's supposed to be added: https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvsproject%2Flangproj%2FCLangHierarchy.cpp&version=GBmaster&line=4035&lineEnd=4036&lineStartColumn=1&lineEndColumn=1&lineStyle=plain.

**Comment by davidwengier** [comment]
Also tracked by, and will be fixed with #5447 

Also tracked by https://dev.azure.com/devdiv/DevDiv/_workitems/edit/974353

**Comment by davidwengier** [comment]
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/200982

**Comment by davidwengier** [comment]
PR completed.
