### ISSUE TITLE
Publish console project fails if a netstandard library has dependencies on both netmq and messagepack nuget packages.

### ISSUE THREAD

**Issue by valeriob** [dotnet/project-system#4252]
Given the console project with a reference to a library project that contains two specific nuget packages, the publish process does not produce anything and fails silently.

If we remove one of the two packages it works. 
If we remove the library and add the two nuget packages to the console project it works.

![image](https://user-images.githubusercontent.com/1522516/48255772-ea374a80-e40d-11e8-9ff8-7a650fd4ab51.png)

[ConsoleAppPublishBroken.zip](https://github.com/dotnet/project-system/files/2577120/ConsoleAppPublishBroken.zip)

Thanks

**Comment by Pilchie** [comment]
@livarcocc - where should this go?

**Comment by valeriob** [comment]
So it looks like that visual studio is stopping the publishing process because of some nuget alert, without reporting any meaningfull error.

Solving those errors did the trick.
The package netmq is targeting netstandard1.6 and using System.ServiceModel.Primitives 4.1.0, i changed  netmq to multitarget netstandard2.0 and i upgraded System.ServiceModel.Primitives to 4.3.0.

**Comment by livarcocc** [comment]
@vijayrkn is this something that we could handle during publish in VS?

**Comment by valeriob** [comment]
Yes,
restore only fails when you publish, but not when you build :(

**Comment by vijayrkn** [comment]
I just tried the sample project you shared and it published without any errors
```

1>------ Build started: Project: ConsoleApp6, Configuration: Release Any CPU ------
1>C:\Program Files\dotnet\sdk\2.2.100-preview3-009428\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(143,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
1>ConsoleApp6 -> F:\repro\ConsoleAppPublishBroken\ConsoleApp6\bin\Release\net472\ConsoleApp6.exe
2>------ Publish started: Project: ConsoleApp6, Configuration: Release Any CPU ------
2>Restoring packages for F:\repro\ConsoleAppPublishBroken\ConsoleApp6\ConsoleApp6.csproj...
2>Generating MSBuild file F:\repro\ConsoleAppPublishBroken\ConsoleApp6\obj\publish\win7-x86\ConsoleApp6.csproj.nuget.g.props.
2>Generating MSBuild file F:\repro\ConsoleAppPublishBroken\ConsoleApp6\obj\publish\win7-x86\ConsoleApp6.csproj.nuget.g.targets.
2>Restore completed in 272.59 ms for F:\repro\ConsoleAppPublishBroken\ConsoleApp6\ConsoleApp6.csproj.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:1701,1702,1701,1702,2008 /nostdlib+ /platform:x86 /errorreport:prompt /warn:4 /define:TRACE;RELEASE;NETFRAMEWORK;NET472 /errorendlocation /preferreduilang:en-US /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Drawing.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.IO.Compression.FileSystem.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Numerics.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Runtime.Serialization.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Xml.Linq.dll" /debug- /debug:portable /filealign:512 /optimize+ /out:obj\Release\net472\win7-x86\ConsoleApp6.exe /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:exe /warnaserror- /utf8output /deterministic+ Program.cs "C:\Users\vramak\AppData\Local\Temp\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs" obj\Release\net472\win7-x86\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs obj\Release\net472\win7-x86\\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs obj\Release\net472\win7-x86\\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs obj\Release\net472\win7-x86\ConsoleApp6.AssemblyInfo.cs /warnaserror+:NU1605
2>ConsoleApp6 -> F:\repro\ConsoleAppPublishBroken\ConsoleApp6\bin\Release\net472\win7-x86\ConsoleApp6.exe
2>ConsoleApp6 -> F:\repro\ConsoleAppPublishBroken\ConsoleApp6\bin\Release\net472\publish\
2>ConsoleApp6 was published successfully to bin\Release\net472\publish\
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by vijayrkn** [comment]
This is with 15.8.5 & 2.2.100-preview3 SDK. 

There is defintely a tooling fix here where the publish should fail when restore fails but in this case if restore is successful during build, it should be successful during publish as well unless you are publishing for a different Target framework and RID.

**Comment by vijayrkn** [comment]
@valeriob can you please share the vs version and the .net sdk version?

**Comment by valeriob** [comment]
Hi,
on my machine at work i'm on vs 15.8.8 and netcore sdk 2.1.403.
On a colleague  with 15.7.3 and sdk 2.1.302 it works. I'll try to update vs later today, and check on my home pc too.
Thanks

**Comment by valeriob** [comment]
I upgraded to vs 15.8.9 and sdk 2.2.100-preview3-009430, it still does not work.

**Comment by valeriob** [comment]
I just found out i attached the wrong repro! The console app was not referencing the library, i think now you should be able to reproduce the problem, sorry for that.

**Comment by Pilchie** [comment]
@vijayrkn - any update here?

**Comment by vijayrkn** [comment]
@valeriob Thanks for the sample project. I was able to reproduce the issue. Restoring for a specific RID is what is failing. 

work-around: You can remove this line from the pubxml file under Properties\PublishProfiles\FolderProfile.pubxml
  `  <RuntimeIdentifier>win7-x86</RuntimeIdentifier>`

I can reproduce the same restore errors outside VS by running the following command 
`dotnet publish /p:RuntimeIdentifier=win7-x86`

**Comment by jjmew** [comment]
@vijayrkn Does this need to move to a different repo? It sounds like this is not a project-system issue

**Comment by jjmew** [comment]
This is issue is not related to project systems
