### ISSUE TITLE
Project file doesn't show up in Go To All searching for files

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#4257]
Using Go To All (<kbd>Ctrl</kbd>+<kbd>T</kbd>) and filtering to files with `f` doesn't list project files.

Filtering to `r` for recent files does correctly list and preview them.

**Comment by olegtk** [comment]
Hmmm, interesting case. 
Regular file name search uses IVsEnumHierarchyItemsFactory to get the full list of files in a solution, it a then filters it down to __VSHPROPID.VSHPROPID_TypeGuid == GUID_ItemType_PhysicalFile. This is where a project file is probably eliminated. I'll debug it tomorrow to confirm.
Recent Files on the other hand uses per-solution recently open file MRU, which is project system agnostic.

**Comment by davidwengier** [comment]
Thanks for commenting @olegtk, I had a quick look at this and it seems your guess is spot on! By skipping [this check](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fenv%2FQuickSearch%2FFileNameProvider%2FFiles%2FSolution%2FSolutionFileNameItemProvider.cs&version=GBmaster&line=373&lineStyle=plain&lineEnd=374&lineStartColumn=1&lineEndColumn=1) Go To All lists the project file:
![image](https://user-images.githubusercontent.com/754264/48329639-b7a38100-e69d-11e8-9d58-a61c24e4f73e.png)

Once the result is there preview works as expected.

I didn't do any exhaustive checking or debugging though, just manually moved the execution pointer a few times, so would be interested in your feedback whether the same trick Dave mentioned above (skip the check for VSITEMID_ROOT) would work here.

**Comment by davkean** [comment]
In my mind, I think it makes sense for that method to be in sync with same one that drives Find results.

**Comment by davidwengier** [comment]
PR is up for VS at https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/156741

**Comment by davidwengier** [comment]
PR completed.
