### ISSUE TITLE
Class Diagram template doesn't appear when creating new file in ASP.NET Core project

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/project-system#4258]
Hi,

When creating a new file (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd>), the _Class Diagram_ item template doesn't appear among the item templates.
This happens when I'm dealing with an ASP.NET Core app.

I tried opening a new .NET Core console app, and the issue did not occur then.

![image](https://user-images.githubusercontent.com/2716316/48326661-30c1ba80-e643-11e8-8bd4-23c92446ad9a.png)

Related:
#4019, #2976, #256

**Comment by davkean** [comment]
This code unfortunately lives inside the Visual Studio tree, and is not open source. Can you refile this via Help -> Send Feedback -> Report a Problem and link the bug. I'll make sure it gets routed to the correct team.

**Comment by weitzhandler** [comment]
[Here](https://developercommunity.visualstudio.com/content/problem/321177/cant-create-class-diagram-file.html) it is.
Thanks for your quick response!

**Comment by weitzhandler** [comment]
https://github.com/dotnet/project-system/issues/256

**Comment by weitzhandler** [comment]
It appears this issue is already [posted](https://developercommunity.visualstudio.com/content/problem/33831/class-diagram-not-available-in-aspnet-core-project.html) on the Developer Community.
Thanks for your quick response!

**Comment by davkean** [comment]
Thanks, I've found that it was already two similar feedback items around this, I've duplicated yours against this. Thanks for filing, we'll look at addressing this in a future version.

**Comment by weitzhandler** [comment]
You mean the one in the dev. community?
