### ISSUE TITLE
Cannot change file context in shared project

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/project-system#4260]
When having a shared file in either a shared project or by directly sharing a file (using Ctrl+Shift+Drag - or add existing file -> pressing the little arrow near the add button and add as link), the current project-context is locked to one of the projects without the ability to change the project context of the file.

I have a shared project between an ASP.NET Core and WPF projects.
When I open the shared file and change context, as soon as I set back the focus on the text editor, the context jumps back to the previous project-context.

I encounter the same issue when trying to change project-context using the keyboard (Ctrl+F12) as well.

Here's what I mean:
![image](https://user-images.githubusercontent.com/2716316/48326855-42f02880-e644-11e8-9772-2924e2196fca.png)

Posted [here](https://developercommunity.visualstudio.com/content/problem/163658/unable-to-change-file-context-in-shared-file-it-im.html) as well.

**Comment by Pilchie** [comment]
This is actually a Roslyn problem as far as we know - see https://github.com/dotnet/roslyn/issues/21358
