### ISSUE TITLE
Editor and Compiler doesn't handle preprocessor symbols for target frameworks with Visual Basic .Net Core/.Net Standard

### ISSUE THREAD

**Issue by jing8956** [dotnet/project-system#4263]
Create a simple multiple target frameworks .Net Standard or .Net Core project
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard1.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
</Project>
```
and put this code in the class:
```
#If NETSTANDARD1_0 Then
    Public is1_0 As Integer
#ElseIf NETSTANDARD2_0 Then
    Public is2_0 As Integer
#Else
    Public other As Integer
#End If
```
Expected(C#) and Actual(Visual Basic):
![2018-11-12](https://user-images.githubusercontent.com/20148769/48337474-fa655900-e69d-11e8-8e34-17a9c39370ec.png)
![2018-11-12 1](https://user-images.githubusercontent.com/20148769/48337493-05b88480-e69e-11e8-844a-c9b2a9ff4875.png)

These symbols are like they don't exist at all. In compilation, too.
Although I can use C #, but it makes me sad for Visual Basic.

By the way,#2733 also appears in the Visual Basic project and behaves exactly the same.

Version 15.8.9

**Comment by Pilchie** [comment]
@livarcocc - given "In compilation, too." is this something that should be on SDK?  I'm surprised there would be a language difference here?

**Comment by livarcocc** [comment]
Yes. They should be available in VS as well. I believe they are actually set in the SDK. So, I am going to move the issue there.

**Comment by livarcocc** [comment]
Issue moved to [dotnet/sdk #2671](https://github.com/dotnet/sdk/issues/2671) via [**ZenHub**](https://www.zenhub.com/)

**Comment by livarcocc** [comment]
@Pilchie can you close this issue? I don't have permissions.

**Comment by Pilchie** [comment]
Will do - I can also add you to this team, given how often we tag you on things 😉

**Comment by livarcocc** [comment]
Sounds good!

**Comment by Pilchie** [comment]
I added all of @dotnet/dotnet-cli ;)

**Comment by davkean** [comment]
@livarcocc You can also move the issue so that this one doesn't even appear in project-system via:

![image](https://user-images.githubusercontent.com/1103906/48585340-743c6180-e980-11e8-8e1d-0f18c6a88dd1.png)

**Comment by livarcocc** [comment]
I think the transfer issue button currently only shows up for maintainers.

**Comment by jmarolf** [comment]
@livarcocc 	yeah, only admins can see that
