### ISSUE TITLE
Find in Files now searches legacy projects

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4274]
I'm not sure if we regressed this or whether the new Find In Files experience did, but Find in Files now searches legacy projects and shows results from it. The project file does nothing when you attempt to open it. Either we should avoid showing the results, or alternatively give an error when you double-click on it.

1. File -> New Console App (.NET Framework)
2. Open Program.cs
3. CTRL+F
4. Enter "TargetFramework"
5. Click Find All

Expected: No results, similar to before
Actual: Results but when you double-click on it, nothing happens

Version that shows no results:  Version 16.0.0 Preview 1.0 [28312.50.d16.0]
Version that shows results: Version 16.0.0 Preview 2.0 [28312.106.d16.0stg]

**Comment by davidwengier** [comment]
This presumably would have broken when https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/124985 was merged, I forgot that lab/vscore didn't seem to go anywhere when I cherry-picked that commit and forgot to re-test it. We findmgr.cpp to use the helper method and check for the OpenProjectFile capability not just itemid, but that's easy enough.

**Comment by davidwengier** [comment]
When using the "Find Results" view you get an error when double clicking, so the experience is slightly worse.

Oddly this doesn't repro for all search terms: "Project" and "Import" get no results for example, but "PropertyGroup" does. "Target" gets no results, "TargetFramework" does.
The same odd find behaviour does not happen on our project files so it could be an issue with Find and not us, though having said that it doesn't repro in preview 1.

Compare:
![image](https://user-images.githubusercontent.com/754264/48525556-b14d1900-e8d8-11e8-854e-7c61509875c9.png)

**Comment by davidwengier** [comment]
Assuming my debugging is correct, this could be a regression in the legacy project system as [the check for IsNonSearchable](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fenv%2Fmsenv%2Fcore%2Ffindmgr.cpp&version=GBmaster&line=956&lineStyle=plain&lineEnd=957&lineStartColumn=1&lineEndColumn=1) is failing. @tmeschter assuming you're the only one working in legacy, does that make sense to you?

**Comment by davkean** [comment]
It also searches C++, and the results are buggy and misleading. We should turn this off, it was a regression in my change - the assumption is that if a hierarchy says it doesn't support this property that is it searchable.

I've sent an email out to C++, but I think the POR should be:

- C#/VB returns true for this property (they aren't searchable)
- C++ returns true for this property (they aren't searchable)

**Comment by davidwengier** [comment]
This is fixed by internal PR here: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/151990

**Comment by davidwengier** [comment]
PR has been completed.
