### ISSUE TITLE
Add msbuild property UseWindowsForms and UseWPF to telemetry

### ISSUE THREAD

**Issue by wli3** [dotnet/project-system#4279]
To get WPF and WinForm usage. Could you add msbuild property `UseWindowsForms` and `UseWPF` to telemetry collection?

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/pull/2664 SDK side for reference

**Comment by wli3** [comment]
cc @livarcocc @Pilchie

**Comment by Pilchie** [comment]
Thanks - I think for Preview 1, it *should* be sufficient to rely on reference telemetry as long as we'll be able to calculate the hashes of the path to the references.  @davkean do you know if that will work or not, given that for P1 they will be coming from NuGet and so in the user's directory?

**Comment by davkean** [comment]
We should add telemetry for capturing FrameworkReference, not individual properties from SDKs.

**Comment by wli3** [comment]
+ @dsplaisted  there is only one FrameworkReference for both WPF and Winform i remember?

**Comment by davkean** [comment]
There's two, though Kevin's right - the existing telemetry should already capture this in the references (which will also meaning existing workload tags will still tag it). Secondly, when we have capabilities tied to these, we also capture this. I don't think we need this.

**Comment by davkean** [comment]
I'm concerned the SDK is tying telemetry back to the those properties - as they cannot be compared to the existing WinForms/WPF workload rules we already have. Someone can reference WinForms without those properties.

**Comment by livarcocc** [comment]
Cool. I just wanted to be sure that we had a way to capture/differentiate between them in .NET Core. I guess we just need to reach out to Bri to make sure she knows how to update her queries.

**Comment by Pilchie** [comment]
> the existing telemetry should already capture this in the references

Did you catch my concern about the path hashing problem?  Or do we report the unresolved reference names?

**Comment by dsplaisted** [comment]
> there is only one FrameworkReference for both WPF and Winform i remember?

We expect that there will be separate FrameworkReferences, but right now there's just one which gives you both.

**Comment by Pilchie** [comment]
@davkean was going to verify the existing point.

**Comment by jjmew** [comment]
I believe I solved this back in Nov by exposing Vs.solution.project.targetframework.rawstring. This was just a change we had to do in our tool. Bri was the one that had requested it. I don't think there is further action for us.
