### ISSUE TITLE
[Regression] Edit [ProjectFile] does not show up anymore

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4299]
Version: Version 16.0.0 Preview 2.0 [28319.114.d16.0stg]

1. Create a Console App (.NET Core)
2. Right-click on project

Expected: Edit [projectfile] to show up
Actual: No longer shows up

![image](https://user-images.githubusercontent.com/1103906/48815428-a0961a80-ed92-11e8-9faa-65ea1132a912.png)

**Comment by davkean** [comment]
Probably caused CPS not registering theirs similar to: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs#L28

**Comment by davidwengier** [comment]
Fixed by https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/152550

**Comment by davidwengier** [comment]
Thanks Drew
