### ISSUE TITLE
[Regression] Dependency node shows warning that never goes away

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4300]
Version: Version 16.0.0 Preview 2.0 [28319.114.d16.0stg]

1. File -> New Console App (.NET Core)

Expected: Warning icon to go away
Actual:

![image](https://user-images.githubusercontent.com/1103906/48815521-d76c3080-ed92-11e8-99e4-9622ad161315.png)

**Comment by drewnoakes** [comment]
This was fixed in #4271 so should have been inserted. Running master in d16.0stg doesn't repro this.

How do we know which build of project-system is in 28319.114.d16.0stg?

**Comment by davkean** [comment]
https://github.com/dotnet/project-system/blob/master/docs/repo/debugging/visualstudio.md

**Comment by davkean** [comment]
That tells you the current build, not the real build, hoping @jmarolf will fill it out for a random version.

**Comment by davkean** [comment]
It was this one: #6cc37a275f9ce9f9eef6b24c8b52e8fb19ecd674

**Comment by jmarolf** [comment]
28319.114.d16.0stg would be a build of VS from 19/11/2018 based on how that number is calculated but I cannot find the drop location under the new cloudbuild stuff

**Comment by jmarolf** [comment]
installed 28320.3006.d16.0stg from [here](\\cpvsbuild\drops\VS\d16.0stg\products\28320.3006\bootstrappers\Community\vs_community.exe) and it has [this](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2217871) project system build installed (https://github.com/dotnet/project-system/commit/6cc37a275f9ce9f9eef6b24c8b52e8fb19ecd674 SHA).

**Comment by jmarolf** [comment]
This bug still repros on that build 
![image](https://user-images.githubusercontent.com/9797472/48830894-8294cf80-ed2a-11e8-94c1-e64592e99de2.png)

:(

**Comment by davkean** [comment]
Note, if you reload the project the warning goes away.

**Comment by drewnoakes** [comment]
The bug in #4271 occurred 100% of the time, even after reloading.

If I take the current master and Ctrl+F5 it in d16.0stg then I cannot get unresolved icons to appear under any circumstances.

My understanding is that Ctrl+F5 should basically run the same configuration, just with our package updated. If that's the case, why would master work yet the distribution fail?

The bug may be timing related. It's not immediately obvious to me why Ctrl+F5 (no debugger) would involve different timing however.

**Comment by drewnoakes** [comment]
> That tells you the current build, not the random build

What's the distinction here?

**Comment by drewnoakes** [comment]
Double checking the dll in a decompiler and it does look like the fix is there. I'll investigate timing issues.

**Comment by drewnoakes** [comment]
Just updated to 28321.115.d16.0stg and the problem went away.

@davkean can you confirm that you also don't see the problem any more?

![image](https://user-images.githubusercontent.com/350947/48923223-b562d300-eea4-11e8-8d52-5f282481e9f6.png)

**Comment by davkean** [comment]
Yes I've confirmed that's fixed, but I've filed: https://github.com/dotnet/project-system/issues/4313 as the contents of the package are missing.
