### ISSUE TITLE
Designer file incorrectly generated from .resx file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4301]
The designer file generated by Visual Studio at build time from .resx fails to build with the error:

> 'Type' does not contain a definition for 'Assembly'.

This happens when the project has multiple target frameworks.

Repro steps:

1. Clone solution from https://github.com/Microsoft/dotnet-apiport
2. Open `src\Microsoft.Fx.Portability\Resources\LocalizedStrings.resx` and add a new string entry.
3. Build solution.

The build will fail with the above error in the generated code in `LocalizedStrings.Designer.cs`.

The project targets are:

```xml
<PropertyGroup>
    <TargetFrameworks>net46;netstandard1.3</TargetFrameworks>
</PropertyGroup>
```

VS generates code that works for `net46` but not for `netstandard1.3`.

---

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/112762/designer-file-incorrectly-generated-from-resx-file.html
VSTS ticketId: 494399_

_These are the original issue comments:_

Candy Zhang [MSFT] on 9/13/2017, 08:07 PM (433 days ago): <p>Thank you for your feedback. We are evaluating the impact of this issue and will determine its priority from further customer impact. Thank you for helping us build a better Visual Studio.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by etbyrd** [comment]
This is issue is not reproing in 15.9
