### ISSUE TITLE
Dependency node is boxing large number of enumerators allocating 2.7% during solution load

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4308]
![image](https://user-images.githubusercontent.com/1103906/48871345-7f880500-ee38-11e8-90d7-d90b67da4933.png)

**Comment by drewnoakes** [comment]
Nice.

Where is this from? Is this with the latest code? I'll have a look tomorrow.

**Comment by davkean** [comment]
A trace from Preview 1, have the trace if you need it.

**Comment by drewnoakes** [comment]
For this code path I think it should be possible to run traces locally and verify improvement. That'll give me a before and after. Anything special about the solution?

**Comment by davkean** [comment]
Massive; 780 projects that are identical.

**Comment by drewnoakes** [comment]
Is that available somewhere?

**Comment by davkean** [comment]
That trace is probably wrong, I think I might have been looking 15.9, 16.0 looks like this, but still pretty significant:

![image](https://user-images.githubusercontent.com/1103906/48883771-779a8600-ee75-11e8-8282-4774c26c1f7d.png)
