### ISSUE TITLE
Use of PathHelper.MakeRelative consuming large amounts of memory on solution load

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4315]
On solution load for a ~500 project solution, we're allocating ~30 MB to make relative paths, only to eventually full qualify them. We need a better version that doesn't go through Uri.

![image](https://user-images.githubusercontent.com/1103906/48930670-36be7200-ef46-11e8-89e7-607c135599bd.png)

**Comment by panopticoncentral** [comment]
I think this was resolved by CPS moving off of Uri internally.
