### ISSUE TITLE
Solution load performance

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4332]
This is an overarching issue that we're using to track solution load performance issues across VS against the new project system.

Metrics | Meaning
---|---
TTE (Time to Solution Explorer) | Time it takes from first open -> showing project tree in Solution Explorer.
TTL (Time to Language Service) | Time it takes from first open -> sending design-time build results (with mscorlib) to Roslyn).
TTD (Time to Dependency node) | Time it takes from first open -> show all results in the Dependency node in Solution Explorer.
TTT (Time to Test) | Time it takes from first open -> showing every test in Test Explorer.
TTB (Time to Branch Switch) | Time it takes to switch to a branch with project & file changes

Scenario | Meaning
---|---
Double-click | Double-clicking the project in Solution Explorer.
File -> Open | Opening the solution from an already opened VS.

### CPU/Blocked/IO Time
Issues that affect the clock time of solution load due to high CPU usage, or blocked time due to IO, lock contention or awaited time.

% (Approx.) |Bug|Owner|Metric|Scenario|Notes
---:|---|-----|----|:------:|----|
~5000ms~|~[ExtensionManagerService.ShouldDeletePendingUninstalls causes ~5 second UI delay after opening empty environment](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/757468)~|Extensibility|TTL|Both
~16%~|~[Large amount of lock contention in dependency node](https://github.com/dotnet/project-system/issues/2714)~|Project|TTD|Both
15%|[Perf: DependenciesTree UpdateTree logic (BuildTreeForSnapshotAsync) is way too expensive](https://github.com/dotnet/project-system/issues/2707)|Project|TTD|Both
~2%~|~[Large amount of dictionary enumeration in dependency node](https://github.com/dotnet/project-system/pull/4365)~|Project|TTD|Both|PR #4365
~180ms~|~[Environment.DeduplicateVariables is 3% of a UI delay opening an empty environment doing an incorrect comparison](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/769811)~|AzureDevOps|TTL|Both
? |[Ensure that we only have a single design-time build on open](https://github.com/dotnet/project-system/issues/2521)|Project|TTL|Both
? |[Inefficient way to create the first version of the dependencies tree after loading a project](https://github.com/dotnet/project-system/issues/3321)|Project|TTD|Both
~?~ |~[Dependency node is doing lots of work on unload](https://github.com/dotnet/project-system/issues/2640)~|Project|TTB|Both
? |[Investigating nominating restore during evaluation as well as design-time](https://github.com/dotnet/project-system/issues/2805)|Project|TTL|Both
? |[Design-time builds in CPS are doing too much work because BuildingProject is set to true](https://github.com/Microsoft/msbuild/issues/2417)|Project|TTL|Both
? |~[Large amount of lock contention in dependency node](https://github.com/dotnet/project-system/issues/2714)~|Project|TTD|Both|PR #4364
~?~ |~[Investigate whether there is a benefit to merging dlls](https://github.com/dotnet/project-system/issues/4544)~|Project|TTE|Both

### GC Time
Issues that affect GC time from all generations and large object heap (LOH), and issues that affect the peak working set of Visual Studio.

% (Approx.)  |Bug|Owner|Metric|Scenario|Notes
---:|:---|:-----|:----|:------|----|
20%-60%|[Consume reduced data from design-time build for dependencies node](https://github.com/dotnet/project-system/issues/3435)|Project|TTL|Both|
~20%~|~[OOMFeedManager/DependencyNode.Package is responsible for 20% (233 MB) of all allocations during a large solution load](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733791)~|Setup|TTL|Both
17.5%|[PropertyChangedEventManager/WeakEventTable.Purge are responsible for 17.5% (170 MB) of allocations during solution load](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733795)|WPF|TTE|Both
~13.5%~|~[ExtractPropertyFunction allocates a huge amount of data during solution load](https://github.com/Microsoft/msbuild/issues/4085)~|MSBuild|TTE|Both
8%|[ExpandPropertiesLeaveTypedAndEscaped (incorrectly) makes the assumption that it's ReuseableStringBuilder won't be resized](https://github.com/Microsoft/msbuild/issues/4084)|MSBuild|TTE|Both|
~7%~|~[QueryStatus for "Start Debugging" allocates 7% (100 MB) of all allocations during solution load](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/734251)~|Solution|TTE|Both
  6%|[Communication between VS -> MSBuild is pushing 6% (100MB) of allocations onto the LOH](https://github.com/Microsoft/msbuild/issues/3953)|MSBuild|TTL|Both
5%|[AvatarCache.Equals is allocating a huge amount of boxed "bytes"](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/731835)|Identity|TTL|Both
5.5%|[FileWatcher indirectly creates ~42 MB of FileInfo's during solution load](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733802)|IDE|TTL|Both
~5%~|~[5% of overall allocations loading a large solution is the Project Id -> Project map in Roslyn](https://github.com/dotnet/roslyn/issues/31306)~|Roslyn|TTL|Both|PR: https://github.com/dotnet/roslyn/pull/31405/
  ~4%~|~[BuildUpToDateCheck.OnChanged allocates 4% of all data opening Roslyn.sln](https://github.com/dotnet/project-system/issues/3744)~|Project|TTE|Both|PR #4333
3.8%|[Memory allocation in GetProjectItemSpecsFromSnapshot](https://github.com/dotnet/project-system/issues/3548)|Project|TTD|Both
~3.2%~|~[OnOtherProjectDependenciesChanged allocates of 26 MB of temporary List<IDependency> during solution load](https://github.com/dotnet/project-system/issues/4311)~|Project|TTD|Both|PR #4334
~2.7%~|~[Dependency node is boxing large number of enumerators allocating 2.7% during solution load](https://github.com/dotnet/project-system/issues/4308)~|Project|TTD|Both
  2%|[Use of PathHelper.MakeRelative consuming large amounts of memory on solution load](https://github.com/dotnet/project-system/issues/4315)|Project|TTD|Both
2.1%|[InterningBinaryReader+Buffer allocates 16MB opening large solution](https://github.com/Microsoft/msbuild/issues/3954)|MSBuild|TTL|Both
~1.5%~|~[Don't allocate RegEx Match objects](https://github.com/Microsoft/msbuild/pull/3969)~|MSBuild|TTL|Both|PR Microsoft/msbuild#3969
~1.3%~|~[DependencyNodeComparer.GetHashCode is responsible for 1.3% of allocations during a large solution load](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733799)~|Setup|TTD|Both
~1%~|~[Getting filename/extension metadata allocations 1% of solution-wide design-time build](https://github.com/Microsoft/msbuild/issues/2435)~|MSBuild|TTL|Both
1%|[MetadataReferenceHandler is allocating a lot trying to root the reference ](https://github.com/dotnet/project-system/issues/3432)|Project|TTL|Both
~1%~|~[Avoid allocations mutating tree](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/152624)~|CPS|TTE|Both|PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/152624
~1%~|~[Avoid boxing IntPtr](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/152620)~|CPS|TTE|Both|PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/152620
? |[Move away from returning file paths for dependency nodes that don't need it](https://github.com/dotnet/project-system/issues/2559)|Project|TTD|Both

### Working Set
Issues that affect the stable working set (sizes of caches, data structures, etc) of Visual Studio. The higher the working set, the more likely the GC will run through all generations. Short term allocations that are affect the peak working set are tracked by GC Time

% (Approx.)  |Bug|Owner|Metric|Scenario|Milestone|Notes
---:|---|-----|----|:------:|---|----|
~7%~ | ~[Don't cache build results in BuildManager](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/946857)~ | CPS | TTE | Both
? | [Dependencies node should share identical subtrees between projects](https://github.com/dotnet/project-system/issues/3335) | Project | TTD | Both
? | [DependencyIDs create a lot of long, duplicate strings](https://github.com/dotnet/project-system/issues/5051) | Project | TTE | Both
2.7% | [VisualStudioOptionsProcessor holds on to command-line string causing heap growth](https://github.com/dotnet/roslyn/issues/37212) | Roslyn | TTE | Both
~0.6 - 2.5%~ | ~[Many duplicate strings held by `ProjectItemInstance.TaskItem._definingFileEscaped`](https://github.com/Microsoft/msbuild/issues/4151)~ | MSBuild | TTL | Both
2.4% | [Many duplicate strings held by `Microsoft.Build.Execution.ProjectMetadataInstance._escapedValue`](https://github.com/Microsoft/msbuild/issues/4172) | MSBuild | TTE | Both
2% | [CPS wastes huge amount of memory (up to 2% of heap) storing rules names and paths](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/787712) | CPS | TTE | Both
~1%~ | ~[Many duplicate strings held by `MSBuildGlob.globRoot`](https://github.com/microsoft/msbuild/issues/4511)~ | MSBuild | TTE | Both
~6%~ | ~[The dependencies tree uses quite lots of memory - TreeFlags](https://github.com/dotnet/project-system/issues/3309)~ | Project | TTE | Both | 16.0
~1%~ | ~[TaskRegistry wastes up to 1% of the heap on duplicate strings](https://github.com/Microsoft/msbuild/issues/4155)~ | MSBuild | TTE | Both | 16.1
~15%~ | ~[Metadata property storage is inefficient in VisualStudioProject](https://github.com/dotnet/roslyn/issues/37211)~ | Roslyn | TTE | Both | 16.3 P2

**Comment by Pilchie** [comment]
Tagging myself to get mentions.

**Comment by davkean** [comment]
@jasonmalinowski Just merged in https://github.com/dotnet/roslyn/issues/31306.

**Comment by jjmew** [comment]
Tagging myself to get mentions.

**Comment by cartermp** [comment]
Also joining the tagging party

**Comment by davkean** [comment]
In future, you can just use:

![image](https://user-images.githubusercontent.com/1103906/49614494-931d9900-f9fe-11e8-9b15-fd09329115a9.png)

**Comment by jmarolf** [comment]
@jmarolf 	tagging myself for updates

**Comment by jjmew** [comment]
As I am already subscribed to the whole project it doesn't help doing the subscribe since it just goes to the same place that all other notifications go :( . If you comment then you get a special notification.

**Comment by davkean** [comment]
Ah that makes sense.

**Comment by davidwengier** [comment]
I unsubscribed then resubscribed so now I'm subscribed to the thread, but the notifications still come from notifications@github.com :(

**Comment by davkean** [comment]
Look at the cc'd person, it gives you an indication of why you got a notification.

**Comment by davidwengier** [comment]
Ahh yes, it has manual@noreply.github.com as the email, which would be enough to configure a rule against.

**Comment by davkean** [comment]
The two items owned by "Setup" have been merged in.

**Comment by davkean** [comment]
@drewnoakes Merged in a fix for [Large amount of lock contention in dependency node](https://github.com/dotnet/project-system/issues/2714).

**Comment by davkean** [comment]
Extensibility folks have fixed [ExtensionManagerService.ShouldDeletePendingUninstalls causes ~5 second UI delay after opening empty environment](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/757468).

**Comment by livarcocc** [comment]
Assigning myself here for the issues with Owner: MSBuild.

**Comment by davkean** [comment]
MSBuild has fixed [TaskRegistry wastes up to 1% of the heap on duplicate strings](https://github.com/Microsoft/msbuild/issues/4155)

**Comment by drewnoakes** [comment]
The WPF item _"PropertyChangedEventManager/WeakEventTable.Purge are responsible for 17.5% (170 MB) of allocations during solution load"_ was [marked as fixed](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/676441) back in Janurary.

**Comment by davkean** [comment]
@drewnoakes It requires opt-in by VS which we haven't done.

**Comment by davkean** [comment]
"Many duplicate strings held by ProjectItemInstance.TaskItem._definingFileEscaped" has been fixed.

**Comment by panopticoncentral** [comment]
"Don't cache build results in BuildManager" was fixed a while ago

**Comment by panopticoncentral** [comment]
I'm closing this in favor of our cross-team backlog.
