### ISSUE TITLE
Up-to-date checks fail after a few time when using conditional globbing

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/project-system#4338]
Using [this solution](https://github.com/nventive/Uno/blob/1-42/src/Uno.UI.sln), when modifying any cross targeted file in the Uno.UI project (e.g. [this file](https://github.com/nventive/Uno/blob/1-42/src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs)), building the project works a few times (2 or 3) then any modification says that nothing has changed, and everything is up to date, even if a file has been modified.

This solution cross targets using msbuild extras, using `xamarinmac20;MonoAndroid80;xamarinios10;net46;netstandard2.0`.

One possible workaround is to add the following: 

```xml
	<ItemGroup>
		<UpToDateCheckInput Include="**\*.cs" Exclude="bin\**\*.cs;obj\**\*.cs;" />
	</ItemGroup>
```

So that VS picks up the changes. This used to happen regularly before VS15.9, now happens all the time.

**Comment by davkean** [comment]
I suspect this is just https://github.com/dotnet/project-system/issues/2487.

**Comment by drewnoakes** [comment]
Closing as a duplicate of #2487.

**Comment by jeromelaban** [comment]
Closing ;)
