### ISSUE TITLE
Switch to use new style ProjectLockService API

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#4342]
Please stop to use the original using style Read/Write/Upgradeable lock API, and move to the new delegator style API.  In dev 16, old style API will stay working, but we prefer people to move to the new style.  This change is to prevent dead locks, when 2nd parties is creating a non CPS JTF and calling into CPS related code.  The original API can run into dead lock under certain race conditions, and in Dev 15, we asked 2nd parties to use CPS JTF, but it is hard for them to follow, when they may not know the code eventually will call into a CPS based project system.

**Comment by davkean** [comment]
We already moved across to the new APIs: https://github.com/dotnet/project-system/blob/ddfc471669edc4b2806de3b2a731c7c10c58f2a3/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectAccessor.cs. Are you referring to an usage in particular?

**Comment by jmarolf** [comment]
This should have been done in October unless there is something I am missing? https://github.com/dotnet/project-system/pull/4108

**Comment by davkean** [comment]
Yep, just did a Find All References on the old methods and found zero usage.

**Comment by drewnoakes** [comment]
The upcoming "banned API" work covered by #3777 should prevent us from introducing usages in future, too.
