### ISSUE TITLE
Modifying the csproj not removing from the tree

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#435]
Related to #434, as I can only replicate it with folders located up levels from the project directory: when I add elements to the csproj and save with the project open, the new elements are added correctly. However, if I remove the include with the project open, the new elements do _not_ get removed. Whether or not the links appear as broken doesn't seem to factor into this.

As an example, going from this include line:

``` xml
<Compile Include="**\*.cs;..\Other\**\*.cs" Exclude="$(GlobalExclude)" />
```

to this line: 

``` xml
<Compile Include="**\*.cs" Exclude="$(GlobalExclude)" />
```

doesn't remove `..\Other\Test.cs` from the Solution Explorer.

Tagging @BillHiebert and @davkean.

**Comment by davkean** [comment]
:+1:  Good bug

**Comment by davkean** [comment]
This looks caused by https://github.com/Microsoft/msbuild/issues/1598. @cdmihai @jviau do you agree?

**Comment by cdmihai** [comment]
Looks similar, though I don't see the code path to hit it. Right now Item Provenance will report that `..\Other\Test.cs` is captured by `**\*.cs`. If this leads to the item still showing up, then yes, it's https://github.com/Microsoft/msbuild/issues/1598

**Comment by jviau** [comment]
This is an issue in CPS with our limited external items support. Most of our logic assumes external items have a `Link` metadata on it and when it doesn't we fail. Does this meet the bar for RTM? I don't see editing external globs in the project file as a common scenario and we disabled most interactions with external items in the solution explorer. We plan on working on full external item support post RTM.

**Comment by srivatsn** [comment]
We don't show files outside the project cone anymore unless they have Link metadata. So this is a non-issue now.
