### ISSUE TITLE
Does Directory.Build.props not support <AssemblyTitle>？

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/project-system#4353]
Directory.Build.props:
``` xml
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <AssemblyTitle>$(AssemblyName) ($(TargetFramework))</AssemblyTitle>
  </PropertyGroup>
```
Tuhu.AssemblyInfo.cs:
``` C#
[assembly: System.Reflection.AssemblyTitleAttribute(" (netstandard2.0)")]
```

Tuhu.csproj:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>$(AssemblyName) ($(TargetFramework))</AssemblyTitle>
  </PropertyGroup>
```
Tuhu.AssemblyInfo.cs:
``` C#
[assembly: System.Reflection.AssemblyTitleAttribute("Tuhu (netstandard2.0)")]
```

**Comment by davkean** [comment]
`msbuild /pp` will show you why this doesn't work. $(AssemblyName) is set to a value _after_ Directory.Build.props is imported. If you want to use values that project can override or have defaults, you need to use them _after_ the project body, ie in Directory.Builds.targets.

**Comment by pengweiqhca** [comment]
@davkean Thanks, I use MSBuildProjectName replace AssemblyName

**Comment by pengweiqhca** [comment]
> @davkean I tried setting this in Directory.Builds.targets but it doesn't work too. $(MSBuildProjectName) works but in many of my projects, the project name is different from AssemblyName. Do you know if I'm missing something.

You should use `Directory.Builds.targets`

**Comment by omprakashgade** [comment]
> > @davkean I tried setting this in Directory.Builds.targets but it doesn't work too. $(MSBuildProjectName) works but in many of my projects, the project name is different from AssemblyName. Do you know if I'm missing something.
> 
> You should use `Directory.Builds.targets`

Yes @pengweiqhca , I tried `Directory.Build.targets` also. They are SDK style projects and I have AssemblyName set at the project level (in individual csproj files). I'm trying to set the Output path in `Directory.Build.targets` but it is always empty.

**Comment by drewnoakes** [comment]
@omprakashgade get a binary log from a command line build (`msbuild -bl myproj.csproj`) and search for the property in the structure log viewer: https://msbuildlog.com/
