### ISSUE TITLE
Support for COM References in .NET Core project system

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/project-system#4355]
The 'Add References' operation in Visual Studio has a tab for COM References that is presently not visible for .NET Core projects. For .NET Core 3.0, support for COM References will be included. Having tooling for adding COM references is desirable.

Additional details:
 - PIA - not embedded
 - No-PIA - embedded
 - .NET Core 3.0 support only
 - Target stake holder is Office

See https://github.com/dotnet/samples/tree/master/core/extensions/ExcelDemo for the .NET Core official COM example.

Additional context: dotnet/coreclr#20497, Microsoft/MSBuild#3986

cc @jeffSchwMSFT

**Comment by jjmew** [comment]
@etbyrd Could you take a look at this on this sprint? Our partners would like this for .NET Core 3.0.

**Comment by tmeschter** [comment]
@etbyrd Is there more work to be done for this or can it be closed?

**Comment by etbyrd** [comment]
Sorry about that - the work for this was completed and merged. Closing.
