### ISSUE TITLE
Is there a way to export a project template for a solution?

### ISSUE THREAD

**Issue by taori** [dotnet/project-system#4356]
I am wondering if there is some undocumented cli command to turn a solution into a multi project template.

I've made one in the past and i noticed, that this is a task which can literally take hours to get everything right, so i thought i'd ask if there is a more convenient way to do this.

**Comment by Pilchie** [comment]
There isn't anything built in, but you might look at the http://sidewaffle.com/ extension.

**Comment by taori** [comment]
@Pilchie hm. looks like premade templates. not what i am looking for sadly. thanks for the suggestion though

**Comment by Pilchie** [comment]
No, Sidewaffle is an extension for making templates as well.  Tagging @sayedihashimi for more.

**Comment by jjmew** [comment]
Closing as the question has been answered.

**Comment by taori** [comment]
There is a way now btw... https://github.com/taori/Amusoft.VisualStudio.TemplateGenerator
