### ISSUE TITLE
Use tool tip for information about dependencies node warnings

### ISSUE THREAD

**Issue by taori** [dotnet/project-system#4357]
In the past i remember the project tree would display a warning at dependencies and tell me what exactly is wrong with references, by hovering a node. However the tooltips which used to appear, to not appear any longer so i can't really see what's wrong with my project.

![grafik](https://user-images.githubusercontent.com/5545184/49692176-75624800-fb54-11e8-9520-b54a5eee33f1.png)

You can check out the repo which points to this: https://github.com/taori/Amusoft.VisualStudio.Extensions/blob/master/templateSources/WpfApplication/Company.Desktop.Application.sln

In order to reproduce the issue.

You will need to enable support for netcore sdk to run the .application.csproj, when attempting to reproduce it with VS 2017.9.2

This is the really confusing one. It tells me i have an issue but won't show me what it is.
![grafik](https://user-images.githubusercontent.com/5545184/49692205-37b1ef00-fb55-11e8-8b81-9de052349834.png)

**Comment by davkean** [comment]
tag @drewnoakes

**Comment by drewnoakes** [comment]
@taori thanks for the report.

As I understand it, this is a difference between the old project system and this newer one. It's something that's on our radar and we are currently tracking in #2653. I agree that a tool tip seems like a good solution here. We will also consider including something in the error list.

What version of VS are you using?

**Comment by taori** [comment]
@drewnoakes 
> You will need to enable support for netcore sdk to run the .application.csproj, when attempting to reproduce it with VS 2017.9.2

I think i somewhere read that this is a temporary situation of netcore 3.0alpha being integrated in VS2017. However the idea to display those errors anyway should be thing that always works, since there appears to be some information available pointing out potential flaws.

489770dca0fc6d31ffb4d393dc2bf637cb3344a3 is the commit necessary to reproduce i think. In the meantime i've changed some project settings to make my project work and thus removed netstandard crosscompile entirely from WPF related projects.

**Comment by drewnoakes** [comment]
> We are supposed to show errors/warnings from the assets file here in the tree and Error List. I'd check the assets file to see if the issue exists in there and we're not raising it.

This is #3780.

**Comment by drewnoakes** [comment]
Closing this as we have other issues tracking the outstanding issues covered here. We're actively working on fixes now.
