### ISSUE TITLE
Starting or debugging a Windows Forms/WPF application targeting .NET Core opens the console window

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4392]
Version 16.0.0 Preview 4.0 [28528.35.d16.0stg]

1. Create a new Console App (.NET Core)
2. Right-click on project and choose Properties
3. Under Output Type, change to Windows Application
4. F5

Expected: No console window to open
Actual: Console window is opened.

**Comment by davidwengier** [comment]
This doesn't repro for me in Version 16.0.0 Preview 2.0 [28501.102.d16.0stg]

**Comment by davkean** [comment]
Still repros for me, updated steps.

**Comment by davkean** [comment]
Focus less on steps to get there and more on the resulting project.. @nguerrera Any idea how startup for these apps work? Is dotnet.exe making the decision as to whether a console should be attached? ie Is this a VS or a SDK bug?

**Comment by nguerrera** [comment]
If this is what I think it is, it is likely fixed for netcoreapp3.0.  Was this 2.x?

For < 3.0, F5 will run `dotnet app.dll` (the actual command is controlled by some properties, but that's the default) and dotnet.exe is designated as using the console subsystem. At that point, Windows is doing what it is supposed to do on behalf of dotnet.exe and creating a console window for it.

For 3.0, there will be an app.exe and F5 will be configured to use it. This app.exe should have the appropriate subsystem setting in its PE header and it should work as expected.

If I have this right, this is basically known and we will not service 2.x to fix it. WinExe isn't supported until 3.0.

**Comment by davkean** [comment]
This in on 3.0 - is app.exe only included when you use the WindowsDesktop SDK? If so, we should fix that or error/warn when turn this on.

**Comment by nguerrera** [comment]
No, it should be there unless UseAppHost was set to false to override default. What is dotnet --version?

Can you check the process command line in process explorer while the app is running.

**Comment by nguerrera** [comment]
Just confirming, SDK is 3.0 AND TFM is netcoreapp3.0?

**Comment by nguerrera** [comment]
I cannot repro this either. I put a `while (true) {}` after the hello world. No console window ever showed up.

**Comment by davkean** [comment]
I'll get SDK details after done updating.

**Comment by nguerrera** [comment]
Incidentally, hit #4519 while trying to repro this.

**Comment by davidwengier** [comment]
Using the updated repro steps this still doesn't repro for me with 3.0.0-preview-27122-01

**Comment by nguerrera** [comment]
I think @davkean had an old SDK.

**Comment by davkean** [comment]
Okay with closing this - but we need a bug to hide/error on WinExe when targeting downlevel TFMs as the reason above works is because of the apphost, right?

**Comment by nguerrera** [comment]
File away. I think the priority is low for downlevel. Who's building WinExe for .NET Core < 3.0. Slightly more interesting to consider UseAppHost=false even for 3.0. But that is not a great idea either since you lose win32 manifest customization possibility.

**Comment by davkean** [comment]
We should error for invalid states - it makes finding mistakes easier.

**Comment by nguerrera** [comment]
We could do this in the SDK: "if (winexe || user manifest) && !apphost) warning.

**Comment by nguerrera** [comment]
warning because breaking change otherwise

**Comment by nguerrera** [comment]
The semantics are well defined, but not useful: winexe and manifest go to .dll, which windows doensn't see due to launching with dotnet.exe.

**Comment by davidwengier** [comment]
Closing as no repro
