### ISSUE TITLE
Avoiding successive modal dialogs for load error

### ISSUE THREAD

**Issue by jcouv** [dotnet/project-system#4396]
Could we report this with a single dialog and outputting all the details to the output window or log file?

The screenshot is not meant to point out a specific error, but illustrate the modal dialog in general:
![image](https://user-images.githubusercontent.com/12466233/50045558-d9e84000-0049-11e9-8447-c0ba2ef3e6ea.png)

Tagging @davkean

**Comment by davkean** [comment]
This has been fixed, we now use the Info bar to report these.
