### ISSUE TITLE
Allowing out-of-proc tasks to access unsaved changes

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4406]
### Background
Design-time builds and MSBuild-based single file generators (`MSBuild::XXX`) run in the background on a project in response to a variety of user actions, such as (but not limited to) adding a source file, editing the project file, or switching away from a XAML file. At the same time these run, there might be unsaved changes to an inputs (such as a XAML files) that a target/task needs to access.

To enable the build access to unsaved changes, VS registers an in-memory service for access via the build in the form of `ITaskHost` implementation ("Host Objects"). Tasks use this object, if present, to grab unsaved Visual Studio buffers of files and always generate "up-to-date" information based on the file. This lets the user make an edit to a XAML such as dragging a button onto the designer surface, switch to the code behind and immediately have IntelliSense for the button that they just created.

For XAML files, the handshake between VS and the build is the `IVsMSBuildTaskFileManager` interface. This is used during `MarkupCompilePass1` and `MarkupCompilePass2` targets/tasks.

### Problem
The underlying assumption with usage of this interface (and ITaskHost in general), is that the build is always in-proc with Visual Studio and that MSBuild can access previously registered in-proc COM instances of these host objects. 

This presents a few challenges due to upcoming changes:

- We want to add XAML support for the new project-system, but it always uses out-of-proc builds
- The legacy project system is moving to an out-of-proc model in a future update

Out-of-proc builds break this handshake, so we would like to address this. A few requirements:

- Existing build tasks should be able to run without changes. 
   - While we have an opportunity in .NET Core timeframe to fork the WPF build tasks & targets, legacy project system will continue to run against the old version of the tasks which ship in the .NET Framework. Visual Studio 2019 will ship with a minimum requirement of .NET Framework 4.7.2, so we have no opportunity to change these tasks and targets. This makes changing the way that tasks access this host object, or breaking the API as a non-starter.

- Builds need to be able to call back into VS and access UI-thread based services (such as running document table), even if something is blocked on the UI thread on the build itself

### Proposal

This is related to [AB#825237](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/825237)

**Comment by davidwengier** [comment]
Branch for MSBuild experiment is here: https://github.com/Microsoft/msbuild/compare/exp/COM-host-object?expand=1

CPS currently calls existing RegisterHostObject in Build\BuildProject.cs. CPS needs to take a dependency on a new version of MSBuild and call the new RegisterHostObject method that takes a unique moniker name for the instance of VS, instead of the ITaskHost object.

**Comment by davidwengier** [comment]
Progress!

![unsavedwpf](https://user-images.githubusercontent.com/754264/53932632-a409a380-40ee-11e9-99d7-d31572b242e9.gif)

(You'll just have to trust me that its out-of-proc)

**Comment by davidwengier** [comment]
This is related to AB#825237

**Comment by davidwengier** [comment]
The changes to CPS for this have been inserted into VS master.
