### ISSUE TITLE
F# needs the OtherFlags build property plumbed through to property pages

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/project-system#4408]
We have an issue that for F# DotNetSdk projects the field for entering OtherFlags to the compiler is greyed out:  

- https://github.com/Microsoft/visualfsharp/issues/6024

We need the Project System to pass this through to us.

E.g.
````
  <OtherFlags>$(OtherFlags) --maxerrors:20 --extraoptimizationloops:1</OtherFlags>
````

/cc @jmarolf

**Comment by davkean** [comment]
Passed through to you how? How does the property pages read this value?

**Comment by jjmew** [comment]
@TIHan Can you figure out what needs to happen here?

**Comment by TIHan** [comment]
Yes I can.

**Comment by davkean** [comment]
@TIHan This has been open for a year and doesn't have enough data to be actionable. I'm closing for now - feel free to reopen when you have additonal data around what's needed here.
