### ISSUE TITLE
Consider adding an "allow list" of SDK resolvers that can be used inside VS

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4410]
Rogue SDK resolvers can cause [significant performance issues](https://github.com/Microsoft/msbuild/issues/4025) across the product, we should allow only a set of known "well-performing" resolvers to load inside VS to avoid VS being blamed for performance issues.

**Comment by jjmew** [comment]
The other way to think about this is to alert the user if a given SDK or SDK resolver is taking too long. We could use the traditional yellow bar.

**Comment by davkean** [comment]
@jjmew That's exactly what I turned this into: https://github.com/dotnet/project-system/issues/5732.
