### ISSUE TITLE
TargetFrameworks tag set in .props file inside a nuget package isn't loaded

### ISSUE THREAD

**Issue by sanderobdeijn** [dotnet/project-system#4414]
I don't know if this is a project-system, a nuget or a visualstudio issue.
I have created an nuget package that loads an .props file and in the props file the targetframeworks are overridden.
But this property isn't overridden.
In which order are the properties in a .props files in nuget packages and properties in a .csproj file loaded

**Comment by davidwengier** [comment]
I think in general `.props` files are imported at the start of a project, and `.targets` are imported at the end of a project, so if you want to override the TargetFrameworks you could try moving your property to a targets file. To work out exactly what is going on you can run `msbuild /pp` and it will produce a project file that is the calculated result of all of the imports, and you should be able to use that to see what order things will be processed (ie, you can see if your file is before or after the project file).

**Comment by drewnoakes** [comment]
The binary log may also help in cases such as this:

http://msbuildlog.com/

**Comment by davkean** [comment]
NuGet package cannot override TargetFrameworks; target frameworks for a project are determined _before_ NuGet restore. When NuGet restore is done via command-line, props/targets from NuGet packages are deliberately excluded. Inside VS, they will see the props/targets however, we have already determined the target frameworks & configurations at that point and the behavior will be inconsistent/likely unexpected.
