### ISSUE TITLE
Path.GetDirectoryName() isn't returning ArgumentException for empty path in .net core

### ISSUE THREAD

**Issue by jaydeept** [dotnet/project-system#4416]
I am migrating my code from .Net Framework to .Net Core and there I am seeing one regression in API called `Path.GetDirectoryName()`. Though I am passing an empty value (i.e. "") to it, it's not returning me `System.ArgumentException` but instead returning me `null `value.
This used to work fine in .Net Framework and that's how the behavior should be in .Net Core according to documentation:

> // Exceptions:
>         //   T:System.ArgumentException:
>         //     The path parameter contains invalid characters, is empty, or contains only white
>         //     spaces.

**Comment by KirillOsenkov** [comment]
I’d argue that though a breaking change, this is how it should be, it’s a good improvement and is worth keeping.

**Comment by KirillOsenkov** [comment]
I agree. This issue should be moved to CoreFx (or docs, not sure).

**Comment by davkean** [comment]
You can provide feedback to the docs here: https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getdirectoryname?view=netframework-4.7.2#feedback.
