### ISSUE TITLE
Override a transitive PackageReference with a local ProjectReference

### ISSUE THREAD

**Issue by mellinoe** [dotnet/project-system#4421]
I recently changed how a library and its dependencies are versioned in [this repository](https://github.com/mellinoe/Veldrid). I have several projects referenced by one another, and I have a "demo" application which references all of the others. Most of the libraries reference each other via ProjectReferences with relative paths. However, I switched one library to use a PackageReference so that I could lock its dependencies to a particular version. The relationship is, in a simplified view, the following:

```
Demo.csproj
  ProjectReference -> LibA.csproj
  ProjectReference -> LibB.csproj

LibB.csproj
  PackageReference -> LibA 4.5.0
```

When I build / run the "Demo" project, I want it to use the latest versions from my local repo. However, the "LibB" reference causes it to use the version 4.5.0 LibA.dll from the NuGet cache, even though Demo.csproj has a direct ProjectReference to LibA.csproj.

Is there some way to get this working?

**Comment by jmarolf** [comment]
@mellinoe 	I believe this issue is tracking this work in the SDK: https://github.com/dotnet/sdk/issues/1151
