### ISSUE TITLE
FSharp isn't picking up design time targets from experimental hive

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#4423]
Whilst the `launchSettings.json` file specifies an `FSharpDesignTimeTargetsPath` variable, it doesn't seem like there is anything that picks it up. Because of this local changes to the design time targets files are not picked up when using the experimental instance. The workaround is to directly modify the design time targets in the VS installation directory.

I assume we would want to see something like this:
https://github.com/Microsoft/msbuild/blob/d42d3504057ef2b88dd4f68c4bfc5591371bd6fe/src/Tasks/Microsoft.CSharp.CurrentVersion.targets#L323-L328

But there isn't anything like that in https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Build/Microsoft.FSharp.Targets

**Comment by jjmew** [comment]
This issue was moved to Microsoft/visualfsharp#6093
