### ISSUE TITLE
Incorrect version of referenced assembly being copied to output folder

### ISSUE THREAD

**Issue by tomrus88** [dotnet/project-system#4424]
I have following scenario:

- .NET Standard 2.0 library that references some nuget package (that package has multiple versions of assembly for different frameworks).
- That library then referenced by .NET Framework application.
- By default nuget dependency not being copied to output at all:
`System.IO.FileNotFoundException: 'Could not load file or assembly 'AssemblyNameHere, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'`
so I had to add RestoreProjectStyle tag to the project.
- After building solution, VS copies incorrect version of assembly from nuget package (it copies .NET Framework assembly instead of .NET Standard assembly) to output folder and application is unable to start with following Exception:
`System.IO.FileLoadException: 'Could not load file or assembly 'AssemblyNameHere, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'`

[NugetBugRepro.zip](https://github.com/dotnet/project-system/files/2725769/NugetBugRepro.zip)

**Comment by jmarolf** [comment]
@tomrus88 	I can reproduce this thanks. As a workaround if you change your project files to look like this same project: [NugetBugWorkaround.zip](https://github.com/dotnet/project-system/files/2725822/NugetBugWorkaround.zip) the correct reference is going to be restored.

## ConsoleApp1.csproj
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>

</Project>
```

## ClassLibrary1.csproj
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MoonSharp" Version="2.0.0" />
  </ItemGroup>

</Project>
```

@tmeschter 	this might be a bug in the native project system or a nuget bug but you would likely know where to start

**Comment by tomrus88** [comment]
@jmarolf It still coping wrong assembly from nuget package with your workaround, getting exact same exception. Tried on latest VS2017 and VS2019.
[NugetBugRepro2.zip](https://github.com/dotnet/project-system/files/2727005/NugetBugRepro2.zip)

**Comment by jmarolf** [comment]
@tomrus88 yep looks like nuget is choosing the .NET Framework version of `MoonSharp` because of the Target Framework on `ConsoleApp1`.  Unfortunately this means `ClassLibrary1` will fail to load.  The only workaround I can see for this is to change the class library to multi-target like so:

## ConsoleApp1.csproj
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>

</Project>
```

## ClassLibrary1.csproj
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MoonSharp" Version="2.0.0" />
  </ItemGroup>

</Project>
```

**Comment by jmarolf** [comment]
Based on this, I believe this is a nuget bug not a project system bug.

**Comment by davkean** [comment]
This is working exactly by-design. Packages assets are always evaluated in terms of the deployment target. 

This is a package bug, their .NET Standard version of the library is unsigned and not binding compatible with their desktop version:

```
sn -Tp ".nuget\packages\moonsharp\2.0.0\lib\net40-client\MoonSharp.Interpreter.dll"

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Public key (hash algorithm: sha1):
0024000004800000940000000602000000240000525341310004000001000100f704c50bbdc3f2
f011cc26a8c6c4797a40e0b4bc94cfb1335e9ba208326340696b686dc13099f10d3054544532f5
e3e66c26a13ff260aea2343e0410511fe56edcc2afb898aaa1bc21da33c0d0ae60824eb441d02a
0e6b7ae251cde0946bfc748209c12b062573ecdb008a3d10cc40534b314847591ce5342a3bc6aa
83ce23b8

Public key token is 921e73ce94aa17f8
```

```
sn -Tp ".nuget\packages\moonsharp\2.0.0\lib\netstandard1.6\MoonSharp.Interpreter.dll"

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

C:\Users\davkean\.nuget\packages\moonsharp\2.0.0\lib\netstandard1.6\MoonSharp.Interpreter.dll does not represent a strongly named assembly
```

The .NET Standard version of this library needs to be signed with the same key and be API compatibile as the .NET Framework version.
