### ISSUE TITLE
Inconsistent Edit csproj behavior

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#4445]
Repros on both 15.9 and 16.0.

1. Open a CPS C# project.
2. Right click -> Edit csproj
3. Add a few newlines. The star should appear immediately, however it can take anywhere from 3-10 seconds to appear.
4. Press undo until the file is back to original state. The star should go away, but it does not appear to do so, no matter how long I wait.

Additionally, the undo buffer appears to remember previous opens of the file. ie:

1. Open a C# project
2. Right click -> Edit csproj
3. Add a few newlines.
4. Close the file _without saving_.
5. Right click -> Edit csproj
6. Hit ctrl+z. Previous edits appear, even though the file should be clean.

@davidwengier. Related internal issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/761165

**Comment by davkean** [comment]
@davidwengier Take a look - this looks to be a regression probably around 15.5.

**Comment by davidwengier** [comment]
Fixed the undo buffer problem, still trying to work out why the dirty state indicator is only triggering on idle.

**Comment by Varorbc** [comment]
seems to be very similar to my issues #4454

**Comment by davidwengier** [comment]
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/160282?_a=overview

**Comment by davidwengier** [comment]
PR has been completed. Project file editing is as smooth as butter.
