### ISSUE TITLE
Symbols are not updated on-the-fly between F# projects

### ISSUE THREAD

**Issue by cmeeren** [dotnet/project-system#4452]
I have experienced a bug where symbols are not updated on-the-fly between F# projects. Let's say project A has a reference to project B. If I make changes in B, they are not visible in A until I have compiled B, even though both A and B are F# projects.

I managed to "fix" the bug by deleting the solution's `.vs` folder.

I have no reliable repro, but I just wanted to let you know that there exists such a bug, and I'm also posting here because I was requested to do so (https://github.com/Microsoft/visualfsharp/issues/5901#issuecomment-452760985).

Using VS 15.9, the F# projects are using the new .NET SDK-style.

**Comment by jmarolf** [comment]
This sounds like a situation where we are re-using cached data instead of doing a design-time build when the cache should have been invalidated.

**Comment by cmeeren** [comment]
Note that the problem even stuck around after restarting VS. Only deleting the `.vs` folder solved the problem.

**Comment by jmarolf** [comment]
Yep, and the `.vs` folder is where we keep the caches

**Comment by davkean** [comment]
Design-time builds don't cause other projects to pick up another project's changes. If there is a problem here, it will between how F# language-service monitors changes in the other project and updates it view. 

I can repro this doing the following, not sure if this the same issue:

1. Create two new .NET Core libraries, have one reference the other
2. In the referencer, change code to:

``` F#
namespace ClassLibrary2

module Say =
    let hello name =
        ClassLibrary1.Say.hello("Foo")

```
3. Go back to referencee and without saving changes, rename Say -> Say2

Expected: An error
Actual: No error

If you save changes in the referencee, then the second project picks up changes:

```
Severity	Code	Description	Project	File	Line	Category	Suppression State
Error	FS0039	The value, constructor, namespace or type 'Say' is not defined.	ClassLibrary2	C:\Users\davkean\Source\Repos\ClassLibrary45\ClassLibrary2\Library.fs	5	typecheck	Active
```

**Comment by cmeeren** [comment]
The issue I experienced occurred even though all files were saved (and, as said, even after restarting VS - only deleting the `.vs` folder helped).

**Comment by cmeeren** [comment]
Since this bug has only occurred once since upgrading to 15.9 at its release, it would likely be many months until I could be reasonably sure the problem is gone. I suggest I instead just wait until we have upgraded to 16.0 final when that is out, and I'll let you know if it occurs again.
