### ISSUE TITLE
File Ordering using IWorkspaceProjectContext.ReorderSourceFiles

### ISSUE THREAD

**Issue by TIHan** [dotnet/project-system#4469]
@davkean asked me to make an issue so we can track the work for this.

In Roslyn, we added a new method, `ReorderSourceFiles` on `IWorkspaceProjectContext`. This allows us to handle file ordering for projects that need it, such as F#. We need to integrate this into the project system.

**Comment by tmeschter** [comment]
@TIHan Is this done, no longer needed, or something we need to move out to a later milestone?

**Comment by davkean** [comment]
@TIHan This has been sitting for a year - it's unclear what this is blocking/impacting. I'm going to close it, please open if still relevant and point to what this is going to fix/resolve for you.
