### ISSUE TITLE
Return values for VSHPROPID_DesignerFunctionVisibility and VSHPROPID_DesignerVariableNaming

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4478]
To mimic legacy, we should return values for VSHPROPID_DesignerFunctionVisibility and VSHPROPID_DesignerVariableNaming which control the naming/visibility of WinForm generated controls.

VB:
```
VSHPROPID_DesignerFunctionVisibility -> VSDFV_Friend
VSHPROPID_DesignerVariableNaming -> VSDVN_VB
```
C#:
```
VSHPROPID_DesignerFunctionVisibility -> VSDFV_Private
VSHPROPID_DesignerVariableNaming -> VSDVN_Camel
```

**Comment by davkean** [comment]
We should drive this from MSBuild properties similar to other properties; https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.CSharp.DesignTime.targets#L13

**Comment by davidwengier** [comment]
Feel free to re-assign it back to me if need be.

**Comment by Varorbc** [comment]
@davkean Can you look at this [issue](https://github.com/dotnet/winforms/issues/178)?

**Comment by davkean** [comment]
@Varorbc This is slightly different, and owned by Windows Forms themselves. We don't have any control over this.
