### ISSUE TITLE
An error pops up when adding new items(Form, Winforms UserControl…) to Winforms .net core application

### ISSUE THREAD

**Issue by OliaG** [dotnet/project-system#4486]
_From @Marie-Shi on January 17, 2019 9:36_

**OS:** RS4 x64
**VS:** 16.0.0 Preview 3.0 [28516.179.d16.0stg]
**.NET SDK:** .NET Core 3.0.100-preview-010110

**More info:** This issue cannot repro on Winforms .net Framework application.

**Steps to Reproduce:**
1.	Install .NET Core 3.0 SDK available from https://github.com/dotnet/core-sdk.
2.	Create a Winforms .Net Core application by command: dotnet new winforms –o “xxx”.
3.	Open the project and right click project to choose ‘Add’, then click ‘New Item’ to choose Windows Form/Winforms User Control..

**Actual:**
An error pops up. Please see the below screenshot:
![image](https://user-images.githubusercontent.com/45864017/51308762-d2b7b600-1a7d-11e9-94b6-2e3a9e375af9.png)
Exception log:
[Add_Form_CallStack.txt](https://github.com/dotnet/winforms/files/2767970/Add_Form_CallStack.txt)

**Expected:**
A new form/User Control can be added successfully in this project.

_Copied from original issue: dotnet/winforms#331_

**Comment by jmarolf** [comment]
Item templates are authored for .NET Framework today.  In order to fix this there will need to be new .NET Core item templates.  @Pilchie 	is it on us to do that work?

**Comment by Pilchie** [comment]
Tagging @jjmew.  I thought @davkean had some ideas one what to do here.

**Comment by davkean** [comment]
We should not be duplicating templates - we'll be using capabilities, etc for lighting this up.

**Comment by jmarolf** [comment]
@davkean 	alright, we will need to update the item templates to be .NET Core aware regardless. Sounds like something I would do :)

**Comment by davidwengier** [comment]
Adding DataSets to .NET Standard libraries shows the same error (#4317)

**Comment by davidwengier** [comment]
@jmarolf This can be resolved now, right?

**Comment by jmarolf** [comment]
Yes this was fixed with a PR into CPS
