### ISSUE TITLE
New Integrated Console feature doesn't handle multiple startup projects

### ISSUE THREAD

**Issue by bording** [dotnet/project-system#4495]
After seeing the the new Integrated Console feature mentioned in https://blogs.msdn.microsoft.com/dotnet/2019/01/24/net-core-tooling-update-for-visual-studio-2019-preview-2/ and https://twitter.com/davkean/status/1088274203499847680, I decided to give it a try with a solution that has two Console Apps and have them both start at the same time by using the multiple startup projects UI.

The experience here is very poor. One of the projects gets the new console window experience, but the other one does not. That means that after running via F5, I have the results of one project visible, but the other one flashes a traditional console window before closing immediately.

That means I still have to have some sort of `Console.ReadKey` code in the projects in some cases but not others. Even worse is that if I add that code and then switch back to just running a single project, there is now unneeded code because that app would then get the new Integrated Console.

NOTE: I originally attempted to file this inside VS via Help -> Send Feedback - Report a Problem, but it hung at the final step of submitting the feedback, and I lost everything I typed in there. Since I didn't feel like going through that again, I'm filing this here instead.

**Comment by davkean** [comment]
Thanks - I've filed a bug internally to track this as this code that makes this decision in the debugger. If you file a feedback request, I can dupe it against the new one if you want to track the bug.
