### ISSUE TITLE
15.7 Preview 3 requiring code migration

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4498]
I have installed 15.7 P3 with the following parameters: &quot;--add Microsoft.Net.Component.4.6.TargetingPack --add Microsoft.VisualStudio.Component.PortableLibrary --add Microsoft.VisualStudio.Component.Static.Analysis.Tools --add Microsoft.VisualStudio.Component.Roslyn.Compiler --add Microsoft.Component.MSBuild --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.CoreIde --add Microsoft.VisualStudio.Component.Windows10SDK --add Microsoft.VisualStudio.Component.NuGet --add Microsoft.VisualStudio.Component.VC.140&quot;

When I open a solution from the corefx repo, everything opens fine. When I open a solution in corefxlab, VS requires me to do a migration.

Steps:
1. Clone the corefxlab repo.
2. Run build.cmd from the command line. Verify that the build succeeds.
3. Open corefxlab.sln in Visual Studio 2017 Preview

See GitHub issue https://github.com/dotnet/corefxlab/issues/2217 as well.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/235330/157-preview-3-requiring-code-migration.html
VSTS ticketId: 601767_
_These are the original issue comments:_

Dan Friedman on 6/2/2018, 04:30 PM (236 days ago): See also https://github.com/dotnet/corefx/issues/30094
Dan Friedman on 10/8/2018, 08:38 AM (108 days ago): It turned out that there were missing components (see  https://github.com/dotnet/corefxlab/issues/2217 ). Still, the messaging from VS was less than idea. In any case, I'm fine with this being closed.
Dan Friedman on 12/18/2018, 11:23 AM (37 days ago): We can close this. It is no longer important to me.
_These are the original issue solutions:_
(no solutions)

**Comment by jjmew** [comment]
The customer was able to figure out what was wrong in their setup.
