### ISSUE TITLE
Cannot build any project due to AL1078 failure

### ISSUE THREAD

**Issue by wjk** [dotnet/project-system#4501]
Whenever I try to build any of the product projects, I get the following output and the build fails. Because of this, I cannot work on this repo at all. This has never happened before, and I am working from a fresh clone.

```
"D:\Projects\dotnet-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj" (default target) (1:7) ->
"D:\Projects\dotnet-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj" (default target) (2:6) ->
(GenerateSatelliteAssemblies target) ->
  ALINK : error AL1078: Error signing assembly -- Access is denied. [D:\Projects\dotnet-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj]
```

[zipped binlog](https://github.com/dotnet/project-system/files/2797969/msbuild.binlog.zip)

**Comment by jjmew** [comment]
@wjk  What version of Visual Studio are you using?

**Comment by wjk** [comment]
VS 2019, 16.0.0 preview 2.

**Comment by jjmew** [comment]
Are you trying to build using the command line or visual studio? (For the first time after you cloned)

**Comment by davkean** [comment]
@wjk To rule out permissions, can you delete the artifacts directory under `D:\Projects\dotnet-project-system\`

**Comment by wjk** [comment]
I am building only with `build.cmd`; I generally build with the command-line first, before I open the solution in VS, just in case the build requires special steps that VS doesn't know how to perform. I deleted the entire artifacts directory and restarted, to no avail. AL1078 error still occurs.

**Comment by davkean** [comment]
Can you see if you are hitting this: https://stackoverflow.com/questions/4606342/signing-assembly-access-is-denied?

**Comment by wjk** [comment]
@davkean I have Full Control access to the folder listed in the SO issue, by virtue of my account being a member of the Administrators group on the local computer. Is this sufficient? Screenshot is below.

![security](https://user-images.githubusercontent.com/1915951/51952243-badd1c00-2405-11e9-9e34-ed52577a4cc6.png)

**Comment by wjk** [comment]
Note, however, that building from an elevated command prompt window **does** appear to succeed.

**Comment by davkean** [comment]
Okay, so its somesort of permissions problem. If you download Process Explorer and watch for failed reads/writes you'll see what it failing to read/write from.

**Comment by wjk** [comment]
The file causing the access-denied error is:

```
C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\1cc84112349d100690056702d00d6cd9_b8d17cd6-e641-495c-a261-e0edbe7275bc
```

No clue what this filename means, or if you'll know what it means.

**Comment by wjk** [comment]
Weirdly, this file seems to have vanished in the time between when I saw the filepath and when I went to check its security. How strange.

**Comment by davkean** [comment]
It's likely read via alink while it's trying to generate the signature. Sounds like this is a pretty common issue given we have a KB for it: https://support.microsoft.com/en-au/help/278381/default-permissions-for-the-machinekeys-folders.

**Comment by davkean** [comment]
Going to close this out as its a permissions issue, not an issue with the build itself.
