### ISSUE TITLE
Can we expose the PropertyPage targetframework control to F#

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/project-system#4505]
This would help us target desktop and netcoreapp and netstandard projects.

Thanks

**Comment by jjmew** [comment]
@KevinRansom Could you elaborate on the impact of this and the desired timeline?

**Comment by jjmew** [comment]
@KevinRansom ping?

**Comment by KevinRansom** [comment]
We want to move F# developers off of legacy project files and remove them from the product.   Stage one is to give developers a tool that doesn't require them to edit the project file XML in order to create a Net SDK project that targets the desktop framework.

What this does will allow us to add desktop framework targets to the framework selector dropdown.

Kevin

**Comment by davkean** [comment]
I'm still not sure of the actual ask. Can you share screen shots of what you want?

**Comment by KevinRansom** [comment]
I want to be able to add the target frameworks to the F# NetSDK projects drop down.

![image](https://user-images.githubusercontent.com/5175830/52822980-35de3d80-3068-11e9-9ebc-43204294f5f2.png)

We own the property page, but I don't believe we can modify the drop down for NetSDK projects.  I believe that @jmarolf has more context.  We discussed it with him and he seemed to know what needed to happen on the project-system side that would allow us to add values for desktop frameworks.

Kevin

**Comment by davkean** [comment]
This code is owned by F#: https://github.com/Microsoft/visualfsharp/blob/fead0aac540485683f694524eadad79983ec28d9/vsintegration/src/FSharp.ProjectSystem.PropertyPages/PropertyPages/TargetFrameworkMoniker.vb#L53.

**Comment by davkean** [comment]
Closing this bug @KevinRansom , please reopen if you disagree with my assessment that F# owns this code that is responsible for populating this combo.

**Comment by KevinRansom** [comment]
Makes sense, thanks for looking at this.
