### ISSUE TITLE
Remove xproj migrate

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4540]
`dotnet migrate` will be removed in the 3.0 timeframe, we should make a counter change where we prevent ourselves from calling in the xproj project factory. 

- [ ] We should have our implementation of `IVsProjectUpgradeViaFactory4.UpgradeProject_CheckOnly` in `MigrateXprojProjectFactory` return `VSPUVF_PROJECT_DEPRECATED` to indicate that these project types are not supported. 
- [ ] Delete migration code
- [ ] Remove https://github.com/dotnet/project-system/blob/master/THIRD-PARTY-NOTICES.md because we've deleted src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\Xproj\MigrationError.cs
- [ ] Doc results at https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects?view=vs-2017

**Comment by davkean** [comment]
Run this through compat owner, blocked until approval. Also should doc this here: https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects?view=vs-2017.

**Comment by drewnoakes** [comment]
PR #4895 is ready to merge once `master` is targeting 16.3.

**Comment by drewnoakes** [comment]
PR https://github.com/MicrosoftDocs/visualstudio-docs/pull/3379 is open for the documentation update.

**Comment by drewnoakes** [comment]
PR https://github.com/dotnet/docs/pull/12785 created to update documentation about migration tooling.
