### ISSUE TITLE
Property change not triggered when tabbing off File Version

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#4542]
**Visual Studio Version**: 
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.0.0 Preview 3.0 [28531.182.d16.0]

**Summary:**
When tabbing through the Package property page the FileVersion property doesn't get set when you tab off the last text box of the file version UI. The system beeps when tabbing off, presumably as it thinks its arrived at an invalid tabstop. Pressing <kbd>Tab</kbd> again, or <kbd>Shift</kbd>+<kbd>Tab</kbd>, will correctly set the property value.

Possibly a duplicate of [739224](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/739224) ([devcom](https://developercommunity.visualstudio.com/content/problem/397442/updating-assembly-file-version-does-not-work-prope-1.html)), but certainly found while investigating it.

**Steps to Reproduce**:

1. Open the App Designer at the Package page, and the project file in a tab to the side (so you can see both)
2. Click in one of the Assembly file version major text boxes
3. Change the value
4. Press <kbd>Tab</kbd> until the cursor leaves the final text box

**Expected Behavior**:
The FileVersion property in the project file changes

**Actual Behavior**:
System beeps, property doesn't change until the user presses <kbd>Tab</kbd> or <kbd>Shift</kbd>+<kbd>Tab</kbd> once more

**User Impact**:
Could potentially result in data loss if the user doesn't notice, and doesn't cause anything else to set the property

**Comment by davidwengier** [comment]
@etbyrd Could this be a regression from #4331 ?

**Comment by tmeschter** [comment]
This is in the old property pages, and we don't plan on doing any work here.
