### ISSUE TITLE
P2P Reference from .NET Core 3 to C++ WRT Component fails

### ISSUE THREAD

**Issue by devsko** [dotnet/project-system#4543]
**Visual Studio Version**:
VisualStudio.16.Preview/16.0.0-pre.2.2+28602.52
Microsoft .NET Framework Version 4.8.03707
Installed Version: Enterprise
Visual C++ 2019   00435-10000-00000-AA502
Microsoft Visual C++ 2019
.NET Core 3.0.100-preview-010184

**Summary:**
I have 3 projects
- CppLib (C++ Static Library for UWP)
- CppWrtComp (C++ WRT Component)
Referencing CppLib (without this reference it works)
- WpfApp (.NET Core)
Adding a ProjectReference to CppWrtComp.vcxproj results in `error NETSDK1007: Cannot find project info for '(..)CppLib.vcxproj'. This can indicate a missing project reference.`

Adding a assembly reference to the .winmd file instead works.
The same scenario with WpfApp (.NET Framework) works.

**Steps to Reproduce**:
1.  Create the 3 projects
2.  Add a reference from CppWrtComp to CppLib
3.  Add a reference from WpfApp to CppWrtComp

**Expected Behavior**:
Build succeeds
**Actual Behavior**:
Build fails with NETSDK1007
**User Impact**:

**Comment by devsko** [comment]
Seems to be fixed in VS 16 RC / .NET Core 3 preview 3

**Comment by davkean** [comment]
@devsko This works in VS 2019, if you have restored previously. I believe if you clean the tree this will stop working. I would head over to http://github.com/nuget/home to file a bug as they own this.

**Comment by devsko** [comment]
Are you sure? There are no NuGet packages involved at all. It's all about P2P. Anyway, my scenario works with the latest bits.

**Comment by davkean** [comment]
Ah, possibly. This must have been part of NuGet's fix which fixed restore after you've unloaded a project. Thanks for the followup!
