### ISSUE TITLE
Investigate whether there is a benefit to merging dlls

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4544]
Visual Studio load/start up time is directly related to the number of dlls that are loaded on that path. The more dlls that are loaded, the slower the load.

We should investigate whether our managed scenarios are better off by merging .CSharp/.VisualBasic/.FSharp and .VS into a single dll or whether increasing the size of the dlls regresses performance.

**Comment by drewnoakes** [comment]
From the [architecture](https://github.com/dotnet/project-system/blob/master/docs/repo/architecture.md) document:

> C# assemblies cannot depend on any F# or Visual Basic assemblies and vice versa.

If merged into a single assembly we lose an easy way to enforce this separation. An analyzer could achieve the same thing.

For example, given:

```c#
[assembly: IsolateNamespace("Microsoft.VisualStudio.ProjectSystem.LanguageServices.CSharp")]
[assembly: IsolateNamespace("Microsoft.VisualStudio.ProjectSystem.LanguageServices.FSharp")]
[assembly: IsolateNamespace("Microsoft.VisualStudio.ProjectSystem.LanguageServices.VisualBasic")]
```

An analyzer would enforce that code defined outside each of these namespaces could not reach into that namespace.

If this sounds useful I'll take a look at putting something together.

**Comment by davkean** [comment]
It sounds very useful.

**Comment by davkean** [comment]
This is done, left open to track modifying the architecture diagram.

**Comment by drewnoakes** [comment]
A first draft of the analyzer is up at https://github.com/dotnet/roslyn-analyzers/pull/2161.

**Comment by davkean** [comment]
This diagram has been updated.
