### ISSUE TITLE
Visual Studio intellisense shows errors for Core > 2.1.402 in Q# (Quantuum)

### ISSUE THREAD

**Issue by livarcocc** [dotnet/project-system#4545]
@AgentMC commented on [Wed Jan 30 2019](https://github.com/dotnet/core-sdk/issues/354)

Based on this Stackoverflow post: https://stackoverflow.com/questions/53925337/q-intellisense-errors 
I have latest 2.2.1 (2.2.103) Core, and latest updates for VS 2017.
Yet, Intellisense shows me errors in both `.qs` file and in `.cs` file. The code is as per https://docs.microsoft.com/en-us/quantum/quickstart?view=qsharp-preview&tabs=tabid-vs2017
![image](https://user-images.githubusercontent.com/11662240/51992416-e06d3280-24a4-11e9-8ee6-95037f1239a0.png)
![image](https://user-images.githubusercontent.com/11662240/51992456-efec7b80-24a4-11e9-8200-7bc8fe2e66f0.png)

---

@livarcocc commented on [Wed Feb 06 2019](https://github.com/dotnet/core-sdk/issues/354#issuecomment-461300536)

I don't believe this is the right repo for this issue. I will move it to the project system repo, however, it might be better if you file a vs feedback item through VS itself for this.

**Comment by davkean** [comment]
We also play no part in this, @AgentMC please head over to https://quantum.uservoice.com/ to provide feedback on Q# and tell them about this bug. It looks like they are using UserVoice to gather not only feature requests, but also bugs.

**Comment by AgentMC** [comment]
@davkean @livarcocc Thanks, Uservoice feedback posted.
Link for reference: https://quantum.uservoice.com/forums/906943-setup-and-visual-studio-vs-code-integration/suggestions/36793507-visual-studio-intellisense-shows-errors-for-core
