### ISSUE TITLE
[Regression] Changes to the project file no longer causes AppDesigner to pick up changes

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4549]
**Visual Studio Version**:
Version 16.0.0 Preview 4.0 [28606.63.d16.0stg]

**Summary:**

**Steps to Reproduce**:

1. Create a new Console App (.NET Core)
2. Right-click and choose Properties
3. Change Assembly Name -> 'Foo'
4. Double-click to open project file
5. Change `<AssemblyName>` to 'Bar'
6. Save
7. Switch back to AppDesigner

**Expected Behavior**:
Assembly Name to be "Bar"

**Actual Behavior**:
Assembly Name is still the old name

**User Impact**:

Project files change for a variety of reasons including branch switches, undos or manual edits. Designers are supposed to be resilient to that and always reflect the current state.

**Comment by davkean** [comment]
This was regressed in 16.0. //cc @davidwengier

**Comment by davkean** [comment]
Yep, saving sorry updated it.

**Comment by davidwengier** [comment]
@etbyrd Fix has been merged.
