### ISSUE TITLE
Changing OutputType from Exe to WinExe marks SDK as unresolved

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4550]
**Visual Studio Version**:
Version 16.0.0 Preview 4.0 [28606.63.d16.0stg]

**Summary:**
**Steps to Reproduce**:

1. File -> New Console App (.NET Core)
2. Double-click project to open editor, change `<OutputType>Exe</OutputType>` to `<OutputType>WinExe</OutputType>` and save

**Expected Behavior**:
No warnings

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1103906/52445447-492c6d00-2b7f-11e9-9c93-02fd47f24f97.png)

This is regression in 16.0.

**Comment by davkean** [comment]
// @drewnoakes

**Comment by drewnoakes** [comment]
I can't repro this in 28608.0.d16.0stg. I've tried several things and it always resolves. Was this your experimental hive?

**Comment by davkean** [comment]
Updating to that build.

**Comment by drewnoakes** [comment]
Also the "Console App (.NET Core)" template creates a netcoreapp3.0 app. Your screenshot shows 2.1.

**Comment by davkean** [comment]
If you've installed .NET SDK 3.0.

**Comment by davkean** [comment]
This is still a 100% repro for me, looks like I'm using 2.1.600-preview-009472 SDK.

**Comment by drewnoakes** [comment]
I can repro with `global.json` of:

```json
{
  "sdk": {
    "version": "2.1.600-preview-009472"
  }
}
```

Investigating.

**Comment by drewnoakes** [comment]
With SDK `3.0.100-preview-009827`, changing `<OutputType>` runs a design time build, but no project changes are received.

With SDK `2.1.600-preview-009472`, changing `<OutputType>` runs a design time build that changes the `Microsoft.NETCore.App` item's `"PrivateAssets"` property from `"All"` to `""` in evaluation data received from CPS. Evaluation data is considered 'unresolved', and so the SDK associated with that package is marked unresolved. However in the DTB data `Microsoft.NETCore.App` is completely absent from the set of packages, hence it is not returned to 'resolved' state.

At this point I can't see how changes to the dependencies node code would cause this regression and am wondering whether CPS changed to propagate the `PrivateAssets` change, or whether a newer SDK version regressed something.

It's EOD here so I'll pick this up again tomorrow.

**Comment by davkean** [comment]
This will be the whole "evalutaion considers something changed, but not design-time build because our rules are different".

**Comment by drewnoakes** [comment]
This works with the newer SDK because of this diff to `Microsoft.NET.Sdk.DefaultItems.props`:

```diff
     <PackageReference Update="Microsoft.NETCore.App"
-                      Condition="('$(OutputType)' != 'Exe') And ('$(_TargetFrameworkVersionWithoutV)' != '') And ('$(_TargetFrameworkVersionWithoutV)' >= '2.0')"
+                      Condition="('$(_TargetFrameworkVersionWithoutV)' != '') And ('$(_TargetFrameworkVersionWithoutV)' >= '2.0') And ('$(PackageType)' != 'DotnetCliTool')"
                       PrivateAssets="All"
                       Publish="true" />
```

Specifically, changing the `<OutputType>` from `WinExe` to `Exe` triggers this change in `PrivateAssets`.

However there are other scenarios that trigger this problem too.

**Comment by drewnoakes** [comment]
#2510 looks like a similar bug (difference between evaluation and dtb).

**Comment by drewnoakes** [comment]
I cannot reproduce "any edits cause node to warn" behaviour. @davkean let me know if you have other repro paths.

The case described (`OutputType` from `WinExe` to `Exe` and vice-versa) does repro, but also repros in 15.9.7. So this is not a regression.

**Comment by drewnoakes** [comment]
With SDK 3.0.100-preview6-012264 (possibly in earlier previews as well) MSBuild SDKs are not longer reported as SDK nodes and there is no repro for this bug.

I intend to fix the underlying cause of this, but this particular symptom will no longer be the case from SDK 3.0.100.

**Comment by drewnoakes** [comment]
With further testing around this I see that even if you have a newer SDK installed, if you target `netcoreapp2.1` then the SDK node is still visible. However this bug no longer repros for me so I'm leaving it closed.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
</Project>
```

**Comment by davkean** [comment]
@drewnoakes Wasn't this the whole "evalution considers something changed, but not design-time build because our rules are different". ie Just because data may have changed, doesn't mean the underlying bug has been fixed.
