### ISSUE TITLE
Add support for *glob patterns* in ASP.NET (non-Core) projects

### ISSUE THREAD

**Issue by 304NotModified** [dotnet/project-system#4557]
This is a split out of #2670

Originally posted by @davkean in https://github.com/dotnet/project-system/issues/2670#issuecomment-444840632: 
> If folks want to split out feature support into separate issues that would make ASP.NET/MVC dev easier on top of the new project system, I'm happy to take at look at each feature in isolation and maybe we can take contributions or sneak them in between our current priorities, but at the moment it's not clear in mind what exactly "ASP.NET support" means in terms of actual features without doing a deep dive into it.

Please support the glob patterns in ASP.NET non-core csproj files

Motivation from @NickCraver (https://github.com/dotnet/project-system/issues/2670#issue-246068811):

> One of the awesome features of the new .csproj system is glob patterns (and Visual Studio not replacing them on every save). This was something we really looked forward to as a real time saver and merge reducer, but in practice we can't use the new project system because a lot of functionality for ASP.NET MVC 5 apps is missing, e.g. even hitting F5 to run it.
> 
> When we migrate a large solution to ASP.NET Core, it's a stop-the-world endeavor as are most major changes. Swapping any fundamental framework piece will need to be a big swap, so you want to reduce that window and risk as much as possible. In the case of ASP.NET to ASP.NET Core, you need to swap the project file, all references, port controllers, views, etc. This is a lot to do at once, and every change since you started that path is a royal pain.
> 
> A large part of this pain is in the project file itself, since nearly every commit adding or removing files is a merge conflict. And when moving from non-glob to blog worlds, it's a huge pain to manually sync everything into that major change branch.
> 
> > But why not just stay on non-globs until after the move?
> 
> Again, merge pain. A large change like this necessitates moving files around quite a bit and that's the same merge pain between users as exists in 1 world today.

**Comment by fredericDelaporte** [comment]
The [readme](https://github.com/dotnet/project-system/blob/master/README.md) for this repository makes me wonder if this issue should be put in https://github.com/Microsoft/VSProjectSystem instead.

> This repository contains the new C#, F# and Visual Basic project system that has been rewritten on top of the [Common Project System (CPS)](https://github.com/microsoft/vsprojectsystem).

**Comment by davkean** [comment]
Trying to understand the request; is this to support globbing in existing ASP.NET projects that _are not_ based on the new project system?

**Comment by fredericDelaporte** [comment]
Yes.

**Comment by 304NotModified** [comment]
Yes indeed

**Comment by davkean** [comment]
@304NotModified Thanks for the issue and agree this would be very beneficial to folks doing full ASP.NET development. In the original thread, my intention was to find features/bugs that were preventing ASP.NET development on top on the _new project system_, not for features that we would port back to the legacy project system. 

This time last year, we spent a few weeks looking into adding globbing support in the legacy project system and found that the cost was prohibitive. Our intention is to use time we would have spent on adding this feature, and instead spend it on closing the feature ga[ as called out in this doc: https://github.com/dotnet/project-system/blob/master/docs/feature-comparison.md.
