### ISSUE TITLE
Move Microsoft.VisualStudio.Editors resources into this tree

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4561]
11 strings, a bitmap & a menu live that below to Microsoft.VisualStudio.Editors.dll live under src/wizard/vbdesigner/designerui in the VS tree.

We should move this to the open and delete the resource dll and instead use VS's ability to read resource strings from a managed dll.

- [x] Port changes to this repo: https://github.com/dotnet/project-system/pull/5069
- [x] Rename options page: https://github.com/dotnet/project-system/pull/5071
- [x] Delete the dll in the VS repo: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/192155?_a=overview

**Comment by davidwengier** [comment]
As part of this we should consider renaming the option page from ".NET Core" to ".NET SDK Projects" to better indicate its scope, and align with other sibling nodes. That change has been approved by the UX board.

**Comment by davkean** [comment]
This has been fixed.
