### ISSUE TITLE
Display different project icons for .net framework and standard projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4565]
<p>… just like asp.net projects look different from asp.net core projects...</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/445503/display-different-project-icons-for-net-framework.html
VSTS ticketId: 786142_
_These are the original issue comments:_

Fiona Niu[MSFT] on 2/7/2019, 04:26 AM (6 hours ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by drewnoakes** [comment]
SDK-style projects can target both .NET Framework and .NET Standard simultaneously. What icon should be shown in such cases?

We could show different icons based on the project system in use. But that's not quite what is being asked for.

**Comment by jjmew** [comment]
I think that showing different icons based on the project system is leaking implementation details. I am not a fan of us doing that unless it has concrete meaning to the user.

**Comment by jjmew** [comment]
With the information that we have so far I don't think we should pursuit this.
