### ISSUE TITLE
Implement the new nomination APIs for framework reference and package download 

### ISSUE THREAD

**Issue by nkolev92** [dotnet/project-system#4567]
**Visual Studio Version**: 16.1

**Summary:**

The related NuGet changes are not finalized yet. This is just a placeholder for the future work. 
I will reach out once the NuGet work has made it in. 

Related NuGet issues; 

https://github.com/NuGet/Home/issues/7719
and 
https://github.com/NuGet/Home/issues/7342

/cc @davkean @nguerrera @dsplaisted

**Comment by jjmew** [comment]
@dmonroym can you sync up with @nkolev92 and @davkean to see what we need to do this? This is something we need to do for 16.1

**Comment by davkean** [comment]
@jjmew I'll pick this up, this code is already under churn in this: https://github.com/dotnet/project-system/pull/4666.

**Comment by jjmew** [comment]
> @jjmew I'll pick this up, this code is already under churn in this: #4666.

Okay

**Comment by nkolev92** [comment]
The changes have been inserted into VS lab/d16.1stg that's currently targeting P2. 

The NuGet build number is `5.1.0-rtm.5921`. 

Relevant specs are: 

https://github.com/NuGet/Home/wiki/%5BSpec%5D-PackageDownload-support
https://github.com/NuGet/Home/wiki/%5BSpec%5D-FrameworkReference-in-NuGet

The entry points are: https://github.com/NuGet/NuGet.Client/blob/9f7a7e9a8e35d5f5db06843fbe664fee63ad50d8/src/NuGet.Clients/NuGet.SolutionRestoreManager.Interop/IVsSolutionRestoreService3.cs. 

https://github.com/NuGet/NuGet.Client/blob/9f7a7e9a8e35d5f5db06843fbe664fee63ad50d8/src/NuGet.Clients/NuGet.SolutionRestoreManager.Interop/IVsProjectRestoreInfo2.cs

https://github.com/NuGet/NuGet.Client/blob/9f7a7e9a8e35d5f5db06843fbe664fee63ad50d8/src/NuGet.Clients/NuGet.SolutionRestoreManager.Interop/IVsTargetFrameworks2.cs

https://github.com/NuGet/NuGet.Client/blob/9f7a7e9a8e35d5f5db06843fbe664fee63ad50d8/src/NuGet.Clients/NuGet.SolutionRestoreManager.Interop/IVsTargetFrameworkInfo2.cs

Note that there's a target to get the package downloads, but no target for the framework reference items at this point. 

Also important that the PackageDownload allows duplicate names. NuGet dedups based on the name and the semantic meaning of the version property.

**Comment by davkean** [comment]
> Also important that the PackageDownload allows duplicate names.

This returns IVsReferenceItems which is effectively a dictionary, ie with unique names.

> Note that there's a target to get the package downloads, but no target for the framework reference items at this point.

Why the difference?
________________________________

**Comment by nkolev92** [comment]
`IVsReferenceItems` is just an enumerable. Doesn't have to be a dictionary. 

It was just never added. I can add one if we deem it necessary.

**Comment by davkean** [comment]
@nkolev92 IVsReferenceItems isn't an enumerable, it has an indexer that takes a _index_ or a _name_ (it's Include). It's implemented as a dictionary on our side based on that. What should the indexer that takes a name return if the names are not unique?

**Comment by nkolev92** [comment]
I have created an issue for that https://github.com/NuGet/Home/issues/8005. 

I think it's ok if the indexer is positional. 

I didn't want to change the APIs too much. On NuGet side we never use the indexer.

On the commandline for example, we dedup based on the `Include` and `Version` values. 
Later on we handle the semantic duplicates, such as '[1.0.0]` and `[1.0.0, 1.0.0]`.

**Comment by nkolev92** [comment]
I'll add the CollectFrameworkReferences target in time for Preview 3.

One change that'll happen in 16.2, is that support for the PrivateAssets attribute will be added. 

https://github.com/NuGet/Home/issues/7988

Feel free to add the support for that now. 

I will update the linked specs to reflect the changes
