### ISSUE TITLE
Parent folder of items marked as Visible=False still show up in solution explorer

### ISSUE THREAD

**Issue by b-anand** [dotnet/project-system#4602]
**Visual Studio Version**: 15.9.7

**Summary:**

We have some external dlls that we need to copy to the out directory without showing them in the solution explorer. Adding them to the csproj with Visible=False will do the trick but the parent folders of the items still show up.

**Steps to Reproduce**:

Repro code: https://github.com/b-anand/MsbuildVisibilityBug

Relevant [snippet ](https://github.com/b-anand/MsbuildVisibilityBug/blob/master/MsbuildContentVisibilityBug/MsbuildContentVisibilityBug.csproj#L13) from the csproj in the above repro code:

`<None Include="../externals/**" Visible="False" CopyToOutputDirectory="PreserveNewest" />`

Bug 1: Just open the above solution in Visual studio 2017 and view the solution explorer.

Bug 2: Just open the solution in Visual studio 2017 and do rebuild followed by clean build.

**Expected Behavior**:

For bug 1: Nothing shows up in the UI

For bug 2: Empty folders are cleaned up in the out directory.

**Actual Behavior**:
For bug 1: Just the relative folder paths do show up in the UI.

![image](https://user-images.githubusercontent.com/1024622/53209372-1bb7d880-35ef-11e9-9285-d985fde8e1cd.png)

For bug 2: Empty folder are left in the out directory after doing build clean.

![image](https://user-images.githubusercontent.com/1024622/53209668-114a0e80-35f0-11e9-9e90-2f4ed4a1dd56.png)

**User Impact**:
This becomes really cumbersome when,
1. There are more resource file directories for the external binary.
2. External binaries are indirectly included in the current project when referencing an external nuget i.e. the external nuget tries to do the same thing as above using a build.props file within the nuget.

**Comment by drewnoakes** [comment]
This repros in Dev16.

@dotnet/project-system does anyone disagree that this is a CPS issue and should be routed accordingly?

**Comment by davkean** [comment]
It is a CPS issue, I believe there's an existing bug internally but I couldn't find it.

**Comment by jjmew** [comment]
@b-anand Could you open a feedback ticket in Visual Studio? if you then send us a link to that feedback I will make sure that it is routed to the right team. Here are  [Instructions](https://developercommunity.visualstudio.com/content/problem/post.html?space=8) on how to open a ticket.

**Comment by b-anand** [comment]
As requested: https://developercommunity.visualstudio.com/content/problem/495189/parent-folder-of-items-marked-as-visiblefalse-stil.html
