### ISSUE TITLE
add search keywords for .NET Core options in VS Tools -> Options

### ISSUE THREAD

**Issue by jimmylewis** [dotnet/project-system#4606]
**Visual Studio Version**: VS2019 Preview 4 (dogfood)

**Summary:**
When searching in Tools -> Options for the settings on the `Projects and Solutions -> .NET Core` page, none of the options appear based on keyword searches.

**Steps to Reproduce**:

1. Open Tools -> Options
2. Search for any of these terms related to the options on this page: msbuild, project, logging, previews, sdk, etc.

![image](https://user-images.githubusercontent.com/3976973/53273952-6a767880-36aa-11e9-86a5-5dfea2e02da9.png)

**Expected Behavior**:
Appropriate keywords should find this option page from search

**Actual Behavior**:
None of these work.  Searching for .net or core works because they match the category name, but there's no related keywords associated.

**User Impact**:
Harder to find these options, especially if the user doesn't already know about or where this specific page is in the tree view.

**Comment by etbyrd** [comment]
We don't own the search dialog, but I am investigating if there is a way for us to add keywords or something similar to make it easier to search for those options.

**Comment by Pilchie** [comment]
There is - it's an attribute on the page registration indicating a resource.  See the `keywordList` parameter [here](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.CSharp/CSharpPackage.cs,64)

**Comment by etbyrd** [comment]
Fixed in https://github.com/dotnet/project-system/pull/5054
