### ISSUE TITLE
What happened to the contributors branch?

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/project-system#4607]
The [contributing guide](https://github.com/dotnet/project-system/blob/af88cac878871119eb96debfb8bc3ae1c50d6216/CONTRIBUTING.md) states the following:

> **NOTE:** All pull requests should be submitted against the [contributors](https://github.com/dotnet/project-system/tree/contributors) branch. Other branches may have dependencies upon unreleased parts of Visual Studio and will not be debuggable per the directions below.

This branch no longer exists. Is there a new branch that external contributors should use instead?

**Comment by jmarolf** [comment]
Don't know who on the team deleted the branch. I've restored it.

**Comment by PathogenDavid** [comment]
Thanks!

**Comment by davkean** [comment]
We don't need the branch anymore - you should be able to use VS 2019 Preview 3 to build the product.

**Comment by jmarolf** [comment]
@davkean 	can you update the docs when you delete the branch please?
