### ISSUE TITLE
Editor not loading for .asp files in Sdk.Web projects

### ISSUE THREAD

**Issue by fredericDelaporte** [dotnet/project-system#4610]
**Visual Studio Version**: 15.9.7

**Summary:**
The editor stay blank when trying to open a `.asp` file (Asp Classic) inside a Sdk.Web project.

**Steps to Reproduce**:

1. Add `default.asp` file with some content into a `Sdk.Web` project, like:
```xml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <% Response.Write "ASP still lives!" %>
</body>
</html>
```

2. Try to open the file in Visual Studio from within the project in the solution explorer.

**Expected Behavior**:

The file is opened and its content shown.

**Actual Behavior**:

A tab named after the file is opened, without any content and editing capability.

**User Impact**:

The file has to be opened as as simple text file to be editable in Visual Studio, giving up any chance at having Intellisense.

**Additional notes**:

Inside a class library `Sdk` project, the trouble does not occur. The file loads correctly, and Intellisense is available.

**Comment by davidwengier** [comment]
Thanks for reporting this.

This has been logged internally against the appropriate team. If you'd like to track it you can Send Feedback -> Report a Problem, and I can link the issues together.
