### ISSUE TITLE
NullReferenceException when trying to save values in the NET Core Debug prop page

### ISSUE THREAD

**Issue by etbyrd** [dotnet/project-system#4622]
**Visual Studio Version**: d16.0stg 

**Summary:** Trying to save properties in the NET Core property pages causes a NullReferenceException 

**Steps to Reproduce**:

1. Edit Application Arguments in the Debug prop page

2. Save

**Expected Behavior**: Saves the value to the launchSettings.json

**Actual Behavior**: NullReferenceException, VS hangs and crashes

**User Impact**: Upset user 

**Cause**: 

At https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs#L599, `HandleLaunchSettingsFileChangedAsync` is returning null and the `IProjectFaultHandlerService.RegisterFaultHandler` throws a NullReferenceException

**Comment by etbyrd** [comment]
This may be a regression from https://github.com/dotnet/project-system/commit/1e0868519fcb884a259db8c358aeca7e12ea452a @drewnoakes

**Comment by davkean** [comment]
This will be a regression from my change to observe tasks that were previously unobserved.

**Comment by etbyrd** [comment]
Fix #4623 merged
