### ISSUE TITLE
Cannot manually enter a license file because the control is disabled

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4634]
In places where we let you browse for files, we let you edit/interact with the control:

![image](https://user-images.githubusercontent.com/1103906/53671564-1a636b80-3cd3-11e9-8910-4170e3b3e359.png)

In package page, it's disabled despite me selecting the radio button:

![image](https://user-images.githubusercontent.com/1103906/53671516-d07a8580-3cd2-11e9-9572-c3c0c342aa01.png)

**Comment by etbyrd** [comment]
This was by design as discussed with the Nuget team and us. The idea was to keep that to help “soft enforce” being able to only pick txt, md and no extension files. This was noted in the PR, but I think it is worth having the discussion again.

**Comment by jjmew** [comment]
I was on the fence here but I inclined  to allow you to edit the text for consistency.

**Comment by etbyrd** [comment]
Fixed in #4743
