### ISSUE TITLE
[discussion] Protect branches from direct pushes

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4643]
It (probably &mdash; hence discussion) should not be possible to directly push to any branches on this repo. Instead, all changes should come via pull request and be subject to review.

Most branches have this configured, however when the `dev16.0.x` branch was created it didn't have the same settings.

GitHub appears to support wildcard matches on rules, so we can make this behaviour apply to all branches with something like:

![](https://user-images.githubusercontent.com/350947/54042230-85281180-41c1-11e9-9927-5d85f9ad1d7e.png)

If the premise is sound, I'm happy to set this up.

**Comment by drewnoakes** [comment]
A downside of this approach (currently applied to the repo) is that while you can push up a new branch, you cannot then delete it without amending the rule.

**Comment by Pilchie** [comment]
Note that the currently applied rule also has the:

> Restrict who can push to matching branches
Specify people or teams allowed to push to matching branches. Required status checks will still prevent these people from merging if the checks fail.

Option set.  Not sure if unchecking that would be sufficient.

**Comment by Pilchie** [comment]
On deletions - presumably could also ask an admin to delete the branch without changing the rule?

**Comment by drewnoakes** [comment]
I modified the config to have identical and restrictive rules for `master` and `dev*`. This means we can create ad-hoc branches as needed, but have protection over the core ones for now and in future, so long as we adhere to the `dev` prefix pattern (which seems likely).
