### ISSUE TITLE
Classdiagramms in .net standard projects creates .vb files instead of .cs files

### ISSUE THREAD

**Issue by crone66** [dotnet/project-system#4664]
If I create a .net standard project I can't create a c# class digramm instead I get a vb class diagramm. If I create a class diagramm for Windows Forms App everything works fine.

Steps I did:

1. Disabled all third -party extensions
2. Restarted Visual Studio
3. Created a new C# .Net Standard Project
4. Added a Class Diagramm file (Visual C# Items -> General -> Class Diagramm)
5. Added a class via drag & drop from the toolbox
-> "New Class" dialog pops up where I can change the name
-> The content of Create new file is "Class1.vb"
6. Changed the extension to .cs and pressed ok
-> Got the error message "Visual studio class diagram file name extension is invalid a valid extension is .vb"

I use Visual Studio Community 2017 V.: 15.7.6
I Created a normal C# class library project as workaround.

**Comment by terrajobst** [comment]
I can't repro this issue in VS 15.9.10. Please try updating to see whether it solves your issue. However, I'm seeing #4019.

**Comment by crone66** [comment]
Sadly the update destroyed everything. I can't open projects and if I create a new project I get an empty solution without a project but with a class1.cs... And I receive many warnings that I should check the activity log. I made a backup of the activity log and started a repair procedure I hope that fixes the issue.

**Comment by davkean** [comment]
This particular issue (creating vb files) was fixed in 15.8. Please upgrade to the latest version.
