### ISSUE TITLE
"Place solution and project in the same directory" doesn't

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#4674]
**Visual Studio Version**: 16.0

**Summary:**

The "Place solution and project in the same directory" checkbox results in the project and solution being placed in different directories

**Steps to Reproduce**:

1. Create a project called ProjectName in C:\Folder

2. Tick "Place solution and project in the same directory"

3. Click Create

**Expected Behavior**:
Solution and project are placed in C:\Folder\ProjectName

**Actual Behavior**:
Solution is placed in C:\Folder, and project is placed in C:\Folder\ProjectName

**User Impact**:
Annoyance.

This doesn't happen with legacy projects. Might be CPS, or templates, I haven't looked yet.

**Comment by davkean** [comment]
@davidwengier Can we file a bug against the right team here? We don't own the template engine or the New Project dialog just so this bug doesn't sit here without an owner.

**Comment by davidwengier** [comment]
This no longer repros

**Comment by davidjcr** [comment]
IF I create a new project (X) and ask for it to be placed in a directory (D) the project is placed in D/X/X instead of D/X. Why?
