### ISSUE TITLE
First-class UWP support?

### ISSUE THREAD

**Issue by wjk** [dotnet/project-system#4704]
**Visual Studio Version**: 16.0.0

I had some thoughts on how to add first-class support for UWP projects to the CPS project system.

1. Use `IItemTypeGuidProvider` to set the project type GUID `{A5A43C5B-DE2A-4C0C-9213-0A381AF9435A}`, to enable the existing UWP-specific support (designers, deployment, etc.) in Visual Studio. We would key this GUID provider off of a new project capability.
2. Specify the above project capability, as well as default items and other boilerplate metadata, in a new MSBuild SDK (tentatively named `Microsoft.NET.Sdk.Uwp`). Note that this will require coordination with dotnet/sdk, or wherever else we want to put it.

Does this sound like a reasonable plan? If so, I'd be willing to send in a PR. Thanks!

**Comment by wjk** [comment]
It would be way cool if the MSBuild SDK could be made to have just enough cross-platform smarts to enable a project using it to load in VSMac and edit the C# code or XAML. Of course, you wouldn't be able to build it there, and the designer support would probably be nonexistent as well. If this were to happen, I could then submit PRs to monodevelop and have support for e.g. AppX manifest editing or the project property pages. I think this would go quite a ways to both make VS and VSMac more equal in terms of features, and maybe -- just maybe -- encourage more UWP app development.

All this would require from the Windows team are a copy of the winmd files, for IntelliSense purposes. (If they're not comfortable with releasing the winmd files under an open license, I'm willing to live with them being proprietary, or even copying them from a Windows PC if need be.)

**Comment by davkean** [comment]
UWP support is more than just "tricking" the designer into think we're a UWP project, there's non-trivial project system changes needed for debugging, deployment, templates, property pages, items, output groups, .NET native support, etc 

Appreciate the enthusiasm, but I would like to hold off until we've figured our strategy for replacing the legacy project system post .NET Core 3.0 support (15.3).

**Comment by wjk** [comment]
@davkean That's fine. Looking back I was just a wee bit overenthusiastic about this idea in the first place. 😄 Nevertheless, once we've fully replaced the old project system, I'd still be interested in helping. Thanks!

**Comment by weitzhandler** [comment]
Hey folks, any news on this?
