### ISSUE TITLE
Support Control Library project templates

### ISSUE THREAD

**Issue by cartermp** [dotnet/project-system#4715]
This is to bring us to experience parity with desktop for WPF on .NET Core 3.0.

This is available on desktop today:

<img width="362" alt="image" src="https://user-images.githubusercontent.com/6309070/55912698-0c3d2080-5b98-11e9-9863-03777a858dc6.png">

these should be available for .NET Core 3.0.

The project template should have the correct MSBuildisms (e.g., desktop sdk and `<UseWPF>true</UseWPF>` for WPF).

**Comment by davidwengier** [comment]
@jmarolf has a PR out for this.

**Comment by davidwengier** [comment]
Actually, I take that back, the PR is for an item template not a project template.

**Comment by jmarolf** [comment]
Moved to https://github.com/dotnet/wpf/issues/1036
