### ISSUE TITLE
Can we implement INavigateToSearchService for project file contents?

### ISSUE THREAD

**Issue by cartermp** [dotnet/project-system#4717]
This is the Roslyn API: http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/NavigateTo/INavigateToSearchService.cs,f766ad8e72e83f26,references

(Yes, that's the name for now)

As you would expect, it doesn't do anything today:

<img width="538" alt="image" src="https://user-images.githubusercontent.com/6309070/55969583-e44ecb00-5c32-11e9-8ce9-58138c967477.png">

Not that all strings should be indexed (they probably shouldn't), but there are other helpful things that could be displayed:

* Tasks/targets
* InternalsVisibleTo
* NoWarn
* etc.

Is this possible? Kicking the can down the alleyway here - spec would be later.

**Comment by jmarolf** [comment]
This cannot be done in the project system as we do not have internals-visible-to for roslyn assemblies.  We will need to implement our own progression provider

**Comment by cartermp** [comment]
> This cannot be done in the project system as we do not have internals-visible-to for roslyn assemblies. 

I know one way that can be resolved.

😈

**Comment by davidwengier** [comment]
We could make a new public API in Roslyn. Perhaps call it `INavigateToSearchService_FINAL_use_this_APRIL_2019`?

**Comment by davkean** [comment]
I think this item would naturally fall out of any language service investigation work items.

**Comment by davkean** [comment]
I'm going to close this as its not actionable by itself.
