### ISSUE TITLE
Detect CPS using Sdk attribute or TargetFramework or TargetFrameworks

### ISSUE THREAD

**Issue by aelij** [dotnet/project-system#4720]
**Visual Studio Version**: 16.0

**Summary:**
Currently Visual Studio recognizes CPS projects using either the `TargetFramework` or `TargetFrameworks` MSBuild properties, but they must be defined in the main project file.

Defining the target framework in a central place (e.g. `Directory.Build.props`) makes it easier to upgrade to a new version in large solutions.

My suggestion is to use the `Sdk` attribute (of the `Project` element) as an additional way to detect CPS. I believe it will cover most cases.

See also #3192

**Steps to Reproduce**:

1. Create a directory with a `Directory.Build.props` with `<TargetFramework>netcoreapp2.2</TargetFramework>`.
2. In the same directory, create a new .NET Core library in Visual Studio.
3. Edit the .csproj and remove the `TargetFramework` property.

**Expected Behavior**:
VS opens the project and the target framework set to netcore2.2.

**Actual Behavior**:
VS requests to reload the solution, and then asks to convert the project. If you decline, the project won't load. If you agree, the project file will be modified to something completely invalid and won't load.

**Comment by davkean** [comment]
Thanks for the bug, we agree and we're tracking this via https://github.com/dotnet/project-system/issues/4314.
