### ISSUE TITLE
Still forced to delete ".vs" folder to fix build errors or IntelliSense errors

### ISSUE THREAD

**Issue by verelpode** [dotnet/project-system#4728]
I hope I'm posting this to the right place (it's hard to know!).  In VS 2019 16.0.0, I'm still experiencing the long-standing problem where I'm forced to delete the hidden ".vs" folder in order to fix incorrect build errors or incorrect IntelliSense errors or a partially "broken" error list.  This problem has been reported by multiple people over the years.

However, although this problem still exists in VS 16.0.0, what I experienced today was much less bad than previous experiences in older VS versions.   When I experienced the bug today, the error in the error list window was actually correct this time -- the problem was that the error item was correct but broken.  For example when I double-clicked on the error to try to view the corresponding source code, nothing happened regardless of how many times I clicked.   When I deleted the ".vs" folder and reopened the solution, everything was fixed and fully functional again.

Please note that I strongly suspect that the bugs only occur when you use **multiple** VS Solutions with the same C# Projects in multiple different Solutions.   For example, today I experienced the bug when I edited various files in a ".shproj" in Solution "A", then switched to Solution "B" which contains the **same** ".shproj" plus other other projects.   I think I wouldn't be forced to delete the ".vs" folder if I only ever used a single Solution, but that's quite impractical in my case.

**Comment by jmarolf** [comment]
> I hope I'm posting this to the right place (it's hard to know!)

Thanks for filing this, don't worry about it being the correct repo just do your best, we'll move it around if need be.

> Please note that I strongly suspect that the bugs only occur when you use multiple VS Solutions with the same C# Projects in multiple different Solutions.

Would it be possible to get a solution from you that reproduces the issue? 

CC: @jasonmalinowski because of the mention of shared projects and error list

**Comment by verelpode** [comment]
> Would it be possible to get a solution from you that reproduces the issue?

I understand that it would be much easier to track down the bug if I upload a .zip file containing the complete VS Solution and all Projects in that Solution, and in particular the .zip should include a copy of the broken ".vs" folder.   The difficulty is that before I can do this, I'd have to discuss it with multiple people and get agreement, and then comes difficult questions such as _"Who are we actually sending our projects to?  Who is that guy?  Is that a Microsoft employee or some random contributor?  Should we be asking for a signed non-disclosure agreement?"_

I'll have a think about whether I can reproduce a broken ".vs" folder in merely an example VS Solution, not our actual work.  I'm unsure whether I'd have to work in VS for a number of days before the ".vs" folder is eventually broken.

**Comment by jmarolf** [comment]
If you click on the report a problem inside VS the next time it happens:
![image](https://user-images.githubusercontent.com/9797472/56379399-8850ed00-61c4-11e9-92f3-69c35b64b80f.png)

You can attach files.  Those files are considered NDA and only visible to full time Microsoft employees.  I understand you might want more than that though.  We can discuss someone from our side signing a different NDA if that is necessary.

**Comment by verelpode** [comment]
I'll discuss it, but in the meantime:

How about solving the problem by thinking outside of the box?  If it was my decision, I would make VS do the ".vs" folder in a different way.  I wouldn't store the data in the hidden ".vs" folder located in the same folder as the ".sln" file.  If you ask for my opinion, the hidden ".vs" folder is a case of asking for trouble.  It doesn't surprise me that it has been causing bugs for years.  My opinion is that the whole idea of the ".vs" folder is a troublesome idea that might never work fully reliably.

Here's an example of solving the problem by thinking outside of the box:  Firstly, observe the fact that when the .vs folder is deleted and the .sln is reopened and VS recreates the .vs folder, it doesn't take long.  In the case of the particular .sln where I deleted the .vs folder yesterday, I notice it is a total of 468 files (excluding contents of "bin" and "obj" folders), and the time taken to open the .sln plus recreate .vs was practically almost the same as opening the .sln with a preexisting .vs folder.

Therefore, the troublesome .vs folder can be entirely eliminated!  Instead store the data in a single location (with subfolders) that is used for **all** VS Solutions that the user opens, such as:
```
C:\Users\JohnSmith\AppData\Local\Microsoft\VisualStudio\Project System Cache\
```

That folder would have subfolders -- each subfolder represents a .sln that was opened in Visual Studio.  The name of each subfolder can be simply a unique random number, and inside the folder there is information to identify the corresponding .sln file:
1. A copy of the GUID that exists inside the corresponding .sln file.
2. The full file name and path of the .sln file.

Now you ask:  That may be all well and good, but how does this solve the aforementioned bug?  The answer is that this new system is better manageable because the **entire contents** of the aforementioned "Project System Cache" folder are immediately and always available to VS, unlike the current system where VS does not actually know the location of every ".vs" folder within the entire computer.  Am I explaining this clearly?  When the data for **all Solutions** is stored inside "Project System Cache", then VS has the data for all Solutions, whereas when the data is stored inside the current ".vs" folders, then VS only has the data for the **one** .sln that is currently open in VS.  See what I mean about manageability?

For example:
1. The VS user changes source code in Project "P1" (a ".csproj" project) or builds or re-builds Project P1, and VS stores info into the "Project System Cache" folder to record the fact that Project P1 was last modified at the specified date/time.  
2. Now the user closes "S1.sln" and opens a "S2.sln" that also contains the same Project P1 plus some other Projects.  
3. Now VS has enough info to know that Project P1 was modified via a different .sln, therefore the data/cache for S2.sln is known to be out-of-date, therefore _VS simply discards the entire cache for S2.sln!_  
4. As I mentioned, it's quick to rebuild the entire data, and it happens only infrequently.  The data/cache for a .sln would be entirely discarded and rebuilt whenever a .csproj is modified via a different .sln.  This happens so quickly and infrequently that the user doesn't even notice the additional time.

**Comment by verelpode** [comment]
> CC: @jasonmalinowski because of the mention of shared projects and error list

A good question is whether or not the bug only occurs when a ".shproj" is involved, and I don't know the answer in the case of VS 2019 16.0.0.   I think I only experienced it with .sln's containing .shproj BUT maybe that means nothing because nearly every .sln that I regularly open includes a .shproj, so maybe just coincidence... or not.

By the way, I find .shproj's very convenient.  Actually I love the .shproj feature, except for one thing:  Unfortunately it includes every C# class in the final compiled app, even classes that are entirely unused by a particular app.  The whole idea of a Shared Project is to use it in multiple different apps therefore it is understandable that each app uses a different subset of the classes within a large .shproj, therefore it'd make sense to exclude unused classes from the final compiled app.

**Comment by jmarolf** [comment]
@verelpode the suggestion about having a machine-wide sln cache is something you should file a feedback bug about.  Unfortunately all the code to manage that is in the VS shell which is internal.

**Comment by jmarolf** [comment]
> By the way, I find .shproj's very convenient. Actually I love the .shproj feature, except for one thing: Unfortunately it includes every C# class in the final compiled app, even classes that are entirely unused by a particular app. The whole idea of a Shared Project is to use it in multiple different apps therefore it is understandable that each app uses a different subset of the classes within a large .shproj, therefore it'd make sense to exclude unused classes from the final compiled app.

I would file this on http://github.com/dotnet/roslyn.  The compiler would be the component that would be responsible for tree-shaking in this manner

**Comment by verelpode** [comment]
The bug happened again today and this time it is very bad:  VS generated errors claiming that several classes don't exist, but that is rubbish.  They certainly do exist and these spurious errors disappeared after deleting the ".vs" folder.  The Error List pane said the following, in addition to this same error also being reported via IntelliSense or rather the popup that appears when the mouse is over the line of code experiencing the error.

```
Error	CS0246	The type or namespace name 'XXXXXX' could not be found (are you missing a using directive or an assembly reference?=
```

If any user of Visual Studio does not know how to work around this bug (by deleting ".vs" folder), then it would be **extremely frustrating** for that user because the development of their app would grind to a halt because Visual Studio makes it **impossible to compile the app** unless the user knows to delete the ".vs".  Furthermore, the ".vs" folder is a HIDDEN folder, thereby increasing the difficulty of discovering the workaround.  

Beginner programmers are even harder hit by this bug because they think it's their own fault and they must wrack their brains trying to understand and fix the errors that VS reports.

Here are the steps that led up the reoccurrence of the bug:

1. Via .sln number 1, **I renamed a .cs file** in a .shproj within that .sln.
2. I ran "Build Solution" and it completed successfully.
3. I opened .sln number 2 which contains different projects but also the same .shproj as .sln number 1.
4. I ran "Build Solution" and it produced spurious errors.  For every class that exists in the renamed .cs file, VS produced an error message (CS0246) claiming that the class could not be found.
5. I closed the .sln, deleted the .vs folder, reopened .sln, ran "Build Solution" again, and no more errors; it completed successfully.

Other people have previously reported this bug multiple times, such as [developercommunity #305572 "IntelliSense broken"](https://developercommunity.visualstudio.com/content/problem/305572/intellisense-broken-9999.html).  As you can see on that webpage, it says "Closed - Fixed" but it certainly is not fixed in VS 2019.  Unfortunately this bug appears to be a super-cockroach that never dies regardless of how many times you stomp on it.

**Comment by verelpode** [comment]
Here are some of the many reports of this bug:
* https://developercommunity.visualstudio.com/content/problem/305572/intellisense-broken-9999.html
* https://developercommunity.visualstudio.com/content/problem/341025/intellisense-broken-10000-shows-errors-but-compile.html
* https://developercommunity.visualstudio.com/content/problem/30978/vs2017-error-list-not-cleared-on-new-compile.html
* https://developercommunity.visualstudio.com/content/problem/138912/stale-intellisense-errors-in-error-list.html
* https://developercommunity.visualstudio.com/content/problem/51565/intellisense-often-reports-errors-that-are-not-tru.html
* https://developercommunity.visualstudio.com/content/problem/164720/in-vs2017-v-155-native-c-intellisense-is-broken.html
* https://developercommunity.visualstudio.com/content/problem/133593/build-succeeded-with-errors.html

**Comment by jmarolf** [comment]
@verelpode a situation like this can have many-many causes.  Almost any build task or component in VS could cause this behavior.  Thanks for the repro steps I will give those a try. Filing a new issue on developer community for us to look at would still be helpful as there are logs recorded and attached to the bug that Microsoft employees can look at.

**Comment by ScottRJones** [comment]
We are also experiencing the same problem with the latest version of Visual Studio. A reference to another project is constantly underlined in red and giving Intellisense errors but the solution builds fine. Deleting the vs folder and restarting VS and the machine has made no difference. We have been forced to revert back to using VS 2017.

Verelpode have you any other workaround other than deleting the vs folder?

Thanks, 

Scott

**Comment by verelpode** [comment]
Hi @ScottRJones

> Deleting the vs folder and restarting VS and the machine has made no difference.

Did you close Visual Studio before deleting the hidden ".vs" folder?  Or at least close the VS Solution.  Here are the exact steps that I use:
1. Click "File" menu.
2. Click "Close Solution".
3. Delete the hidden ".vs" folder located in the same folder as the ".sln" that you closed.
4. Click "File" menu.
5. Click "Recent Projects and Solutions", in order to reopen the Solution that you closed.
6. At this point (in my experience at least), the spurious errors are gone.

Also worth remembering:
1. Avoid running multiple simultaneous instances of the VS IDE program.
2. Avoid placing multiple ".sln" in the same folder.

> Intellisense errors but the solution builds fine.

hmm, your description is almost the same as mine, except for one detail:  I _thought_ that I was completely unable to build the Solution until I deleted the ".vs" folder, but I'll check this again next time it happens.  

Do the incorrect errors disappear after you build the Solution?  

> Verelpode have you any other workaround other than deleting the vs folder?

No.  In my experience, I know of only one way of fixing it:  Delete the ".vs" folder.  In my experience, deleting the ".vs" folder **always** fixes the problem, until it happens again a week or two later when I rename a file or whatever.

> We have been forced to revert back to using VS 2017.

I continue to use VS 2019.  At least in my case, it is unnecessary to revert to an older VS version because I can always fix the problem by deleting the ".vs" folder whenever the bug reoccurs (provided that I close VS or the Solution before deleting the .vs folder).

If I did revert to an older VS, then I would have to revert to something like **VS 2010** because I've been experiencing this bug for many years (in one form or another).  I don't remember exactly how many years but it could be since VS 2010 or 2012.

On one hand, it's disappointing that Microsoft hasn't fixed this problem after this many years, but on the other hand, I do understand that Microsoft engineers face substantial software engineering challenges in a complex product such as VS, and yes customers don't always provide sufficient info in bug reports.  It's also good to keep in mind that in other ways Microsoft has delivered many excellent improvements to VS.  I appreciate those improvements.

**Comment by verelpode** [comment]
@jmarolf
> Thanks for the repro steps I will give those a try.

Please let me know whether you're able to reproduce the problem using the steps I described (in particular the **renaming** of a .cs file followed by switching to a different .sln that includes the same .shproj).

Considering my experiences, I think there is a good chance that you can reproduce it using the steps I described, but if not, tell me and I'll _try_ to add more detail to the steps in order to make the reproduction successful, if possible.

**Comment by verelpode** [comment]
@jmarolf and @jasonmalinowski  
This bug occurred again today and I think you can reproduce it easily because apparently it happens whenever a .cs file is renamed or created in a .shproj, followed by switching to a different .sln that contains the same .shproj.
Here's how it happened today:  In a .shproj, I had one .cs file that contains several classes.  I decided to move one of those classes to a separate new .cs file.  
1. I created a new .cs file (in the same .shproj).
2. I used the normal cut and paste commands to cut the class from the original file and paste it into the newly created .cs file.  
3. I compiled the program (built the .sln) successfully. 
4. I closed the .sln and opened a different .sln that contains the same .shproj plus some other .csproj.
5. I opened the newly created .cs file and saw that IntelliSense was broken.  Likewise false errors appeared in the "Error List" window.
6. The false errors disappear after closing the .sln and deleting the .vs folder.

**Comment by verelpode** [comment]
Here's another way of producing a broken ".vs" folder that must be deleted:   Today (and also on other occasions), I deleted a **.xaml** file from a .csproj.  Actually I used the command "**Exclude From Project**" but I think the following bug occurs either way -- via delete or exclude.  Then I tried to build the project.  The build failed because Visual Studio produced errors saying that it couldn't find the .xaml or .xaml.cs file that I deleted!  An amazingly bad failure of Visual Studio!  I retried the build several times but the failure was permanent.  After I closed the .sln and deleted the .vs folder, the build completed successfully.

Reproducibility:  AFAIK, this bug occurs **reliably every time** I remove a .xaml file from a .csproj that was previously built at least once.   In this case, the .csproj was a WPF app.  I also work with UWP apps but don't yet know whether the same bug also occurs when a .xaml file is removed from a UWP .csproj and don't have time today to investigate further.

Although Visual Studio is overall a wonderful product and I appreciate it very much, I do find it quite surprising that users can't even do a simple common thing (remove .xaml files from a project) without triggering bugs.  Nevertheless thank you to everyone who develops Visual Studio.

**Comment by davkean** [comment]
@verelpode Understood that this is frustrating, I'm going to focus on the bugs you've raised and leave the discussion of the design of .vs folder for another time.

As Jon mentioned, Visual Studio is a large product and there's a fairly large list of this can result in incomprehensible build or IntelliSense errors. Often these are a result of a bugs due to some incomplete or broken state after reloading a project or switching branches and can be hard to chase down. Great repro steps help a lot, so does capturing the state of the solution directory that caused you to delete .vs folder. The reports of the bugs you pointed might seem like they are the same bug, but they often aren't and have very different causes and affect different project types.

For the last thing you've reported I can repro and filed: https://developercommunity.visualstudio.com/content/problem/595515/building-a-project-after-deleting-a-xaml-file-resu.html to track it. This doesn't need the .vs directory to be deleted, the very next build is successful.

I'll continue to attempt to repro the other bug you raised above around Shared Projects that are shared between solutions.

**Comment by davkean** [comment]
I've now repro'd the Shared Projects issue too and filed: https://developercommunity.visualstudio.com/content/problem/595663/files-in-a-shared-project-that-is-shared-between-s.html, this looks to be a bug in how we pass Shared Project's source files to the language service.

@ScottRJones If you have a reproducible issue, please Report a Problem and we can take a look.

I'm going to close the the bugs in lieu of the two bugs I filed, @verelpode if you feel I've missed capturing one of the issues you were running into, please Report a Problem and we can take a look. Thank-you very much for the repro steps they helped track down the issues very quickly!

**Comment by itrashpod** [comment]
VS 16.6.1 add project to solution, move file from existing project to new project, compile, undo all with github -> moved file (that via undo was restored at old location) will cause trouble: compiles, but some references therein will get red squiggly line, file in ide will not have triangle beside it (acts as if no classes contained). <- delete .vs all good again...
just for further cases where ide "loses it"

**Comment by davkean** [comment]
@itrashpod Sorry to hear that, do you mind attempting to produce a repro and file a new  with some images, I'm not following completely.

**Comment by itrashpod** [comment]
Really? Add new project to solution,  move existing file (c# class) from
old project to new project, then undo via github. After that file that was
moved (deleted in old project and then restored via undo) is in limbo.
Squiggly lines in restored file even though everything compile and one can
even step.though red squiggly lines of code. I'm sure sqlite file doesn't
realize file has been restored.
