### ISSUE TITLE
Deal with "VSTHRD003: Avoid awaiting or returning a Task representing work that was not start ed within your context as that can lead to deadlocks." violations 

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#4732]
We ignore the rule VSTHRD003 violations as we need to adopt new Microsoft.VisualStudio.Threading version. We should look into either suppressing or fixing these 18 violations instead.

- [ ] ProjectSystem\VS\Build\LanguageServiceErrorListProvider.cs(72,28): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\Build\LanguageServiceErrorListProvider.cs(79,24): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\CSharp\CSharpProjectCompatibilityProvider.cs(34,20): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\CSharp\CSharpProjectCompatibilityProvider.cs(28,20): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\Debug\ProjectDebuggerProvider.cs(71,20): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\VisualBasic\VisualBasicProjectCompatibilityProvider.cs(28,20): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\VisualBasic\VisualBasicProjectCompatibilityProvider.cs(34,20): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\VsSafeProjectGuidServiceTests.cs(41,24): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj]
- [ ] ProjectSystem\VS\VsSafeProjectGuidServiceTests.cs(92,24): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj]
- [ ] ProjectSystem\VS\Build\LanguageServiceErrorListProvider.cs(72,28): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\Build\LanguageServiceErrorListProvider.cs(79,24): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\CSharp\CSharpProjectCompatibilityProvider.cs(34,20): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\CSharp\CSharpProjectCompatibilityProvider.cs(28,20): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\Debug\ProjectDebuggerProvider.cs(71,20): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\VisualBasic\VisualBasicProjectCompatibilityProvider.cs(28,20): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\VisualBasic\VisualBasicProjectCompatibilityProvider.cs(34,20): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
- [ ] ProjectSystem\VS\VsSafeProjectGuidServiceTests.cs(41,24): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj]
- [ ] ProjectSystem\VS\VsSafeProjectGuidServiceTests.cs(92,24): error VSTHRD003: Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks. [G:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj]

**Comment by davkean** [comment]
Everyone one of these are noise - I wouldn't enable it.

**Comment by davkean** [comment]
Closing this, these are all noise.
