### ISSUE TITLE
Fast up-to-date check not working with redirected OutDir and None items

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/project-system#4737]
**Visual Studio Version**: Dev16 RTW

**Summary:**
If you have a None item with CopyToOutput PreserveNewest, and the OutDir is redirected from the default, the FUTD check doesn't work because it still expects the None item to be in the default output directory.

**Steps to Reproduce**:

1. Create a new class library SDK-style project (you can use the attached repro solution)
2. Open in VS
3. Build, then build again

[uptodate.zip](https://github.com/dotnet/project-system/files/3099475/uptodate.zip)

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutDir>bin\Debug</OutDir>
  </PropertyGroup>

  <ItemGroup>
    <None Update="1.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

**Expected Behavior**: shouldn't build the second time around

**Actual Behavior**: still builds:

```
1>FastUpToDate: Latest write timestamp on input is 4/19/2019 3:42:07 PM on 'C:\Temp\uptodate\uptodate.csproj'. (uptodate)
1>FastUpToDate: Earliest write timestamp on output is 4/19/2019 3:42:23 PM on 'C:\Temp\uptodate\obj\Debug\net472\uptodate.dll'. (uptodate)
1>FastUpToDate: Checking PreserveNewest file 'C:\Temp\uptodate\1.txt': (uptodate)
1>FastUpToDate:     Source 4/19/2019 3:40:23 PM: 'C:\Temp\uptodate\1.txt'. (uptodate)
1>FastUpToDate: Destination 'C:\Temp\uptodate\bin\Debug\net472\1.txt' does not exist, not up to date. (uptodate)
1>FastUpToDate: Project is not up to date. (uptodate)
1>------ Build started: Project: uptodate, Configuration: Debug Any CPU ------
1>uptodate -> C:\Temp\uptodate\bin\Debug\uptodate.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**User Impact**: users time wasted

**Comment by davkean** [comment]
@drewnoakes Going to give this to @ocallesp as an intro into how this stuff works.

This logic lives inside BuildUpToDateCheck and you can turn on logging via the following which will help you understand what's going on:

![image](https://user-images.githubusercontent.com/1103906/70191449-e549e500-174c-11ea-84d5-7163f71afda8.png)

**Comment by drewnoakes** [comment]
@ocallesp let me know if you want to sync up on this.

**Comment by ocallesp** [comment]
Fix
https://github.com/dotnet/project-system/pull/5773

Adding OutDir to documentation
https://github.com/MicrosoftDocs/visualstudio-docs/pull/4608
