### ISSUE TITLE
Consume NuGet /embed assets group for interop type assemblies from NuGet package

### ISSUE THREAD

**Issue by dtivel** [dotnet/project-system#4739]
@jainaashish did some work to support package authors to influence when assemblies have EmbedInteropTypes set to true in projects that reference their package.  See:

* Issue:  https://github.com/NuGet/Home/issues/2365
* Spec:  [Embed Interop Types with PackageReference](https://github.com/NuGet/Home/wiki/Embed-Interop-Types-with-PackageReference
* PR:  https://github.com/NuGet/NuGet.Client/pull/2532

The project system needs to consume the updated asset file and embed interop types appropriately.

(The corresponding .NET SDK change is tracked via https://github.com/dotnet/sdk/issues/2732.)

**Comment by davkean** [comment]
As this is defined inside the package, if the compiler is passed the appropriate switches (via https://github.com/dotnet/sdk/issues/2732) then the project-system requires no work to consume this, unless you are referring to something in particular?

**Comment by dtivel** [comment]
It was intended that this issue track the work for changes for "old" style (not SDK-style) projects that use NuGet build tasks that ship with Roslyn.

**Comment by davkean** [comment]
Those build tasks don't ship with Roslyn, they live here: https://github.com/NuGet/NuGet.BuildTasks.

**Comment by dtivel** [comment]
Moved to https://github.com/NuGet/Home/issues/8062
