### ISSUE TITLE
ApplicationPropPageVBWPF.StartupUri​, StartupObject and StartupObjectOrUri throw NotImplementedException when calling GetHashCode method

### ISSUE THREAD

**Issue by M-Lipin** [dotnet/project-system#4751]
**Visual Studio Version**: 15.9 and later with .NET 4.8

**Summary:**
Overridden GetHashCode() methods throw an exception in the following classes, which is used in VB project properties:
Microsoft.VisualStudio.Editors.PropertyPages.WPF.ApplicationPropPageVBWPF.StartupUri​
Microsoft.VisualStudio.Editors.PropertyPages.WPF.ApplicationPropPageVBWPF.StartupObject​
Microsoft.VisualStudio.Editors.PropertyPages.WPF.ApplicationPropPageVBWPF.StartupObjectOrUri

**Steps to Reproduce**:

1. Run Visual Studio, select VB language and create new WPF project.

2. Navigate to Project properties.

3. Select Application (selected by default)

**Expected Behavior**:
Application properties are displayed correctly.

**Actual Behavior**:
Application properties UI is not displayed and "An error occurred trying to load the page. The method or operation is not implemented." message is shown.

**User Impact**:
User is not able to change VB WPF project properties.

**Callstack**:
                Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.PropertyPages.WPF.ApplicationPropPageVBWPF.StartupObjectOrUri.GetHashCode() + 0x3c bytes 
               mscorlib.dll!System.Collections.Hashtable.GetHash(object key) + 0x1e bytes 
               mscorlib.dll!System.Collections.Hashtable.InitHash(object key, int hashsize, out uint seed, out uint incr) + 0xf bytes         
               mscorlib.dll!System.Collections.Hashtable.ContainsKey(object key) + 0x3b bytes            
               System.Windows.Forms.dll!System.Windows.Forms.ComboBox.ComboBoxItemAccessibleObjectCollection.this[object].get(object key) + 0x15 bytes                
               System.Windows.Forms.dll!System.Windows.Forms.ComboBox.ComboBoxUiaProvider.SetComboBoxItemSelection() + 0x26 bytes   
               System.Windows.Forms.dll!System.Windows.Forms.ComboBox.OnSelectedIndexChanged(System.EventArgs e) + 0x167 bytes          
               System.Windows.Forms.dll!System.Windows.Forms.ComboBox.SelectedIndex.set(int value) + 0xf7 bytes        
               System.Windows.Forms.dll!System.Windows.Forms.ComboBox.SelectedItem.set(object value) + 0x3f bytes    
Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.PropertyPages.WPF.ApplicationPropPageVBWPF.SetSelectedStartupObjectOrUriIntoCombobox(System.Windows.Forms.ComboBox combobox, Microsoft.VisualStudio.Editors.PropertyPages.WPF.ApplicationPropPageVBWPF.StartupObjectOrUri startupObjectOrUri) + 0x17f bytes            
Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.PropertyPages.WPF.ApplicationPropPageVBWPF.SetStartupObjectOrUriIntoUI(System.Windows.Forms.Control control, System.ComponentModel.PropertyDescriptor prop, object value) + 0x12b bytes 
               Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.PropertyPages.PropertyControlData.InitPropertyUI() + 0x153 bytes        
               Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.InitPage() + 0xcc bytes           
               Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.SetObjects(object[] objects) + 0x94a bytes        
          Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.IPropertyPageInternal_SetObjects(object[] objects) + 0x2b bytes 
               Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.PropertyPages.PropPageBase.Create(System.IntPtr hWndParent) + 0x243 bytes                
               Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.PropertyPages.PropPageBase.IPropertyPage2_Activate(System.IntPtr hWndParent, Microsoft.VisualStudio.OLE.Interop.RECT[] pRect, int bModal) + 0xaa bytes 
Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.PropPageDesigner.PropPageDesignerView.ActivatePage(Microsoft.VisualStudio.OLE.Interop.IPropertyPage PropPage) + 0x3a6 bytes           
               Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.PropPageDesigner.PropPageDesignerView.Init(EnvDTE.Project DTEProject, Microsoft.VisualStudio.OLE.Interop.IPropertyPage PropPage, Microsoft.VisualStudio.Editors.ApplicationDesigner.PropertyPageSite PropPageSite, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy Hierarchy, bool IsConfigPage) + 0x485 bytes        
               Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.ShowTab(int Index, bool ForceShow, bool ForceActivate) + 0x581 bytes            
               Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.OnInitializationComplete() + 0x46 bytes        
              Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerWindowPane.PopulateView(System.Guid guidLogicalView) + 0x418 bytes  
               Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerWindowPane.ActivateLogicalView(ref System.Guid rguidLogicalView) + 0x92 bytes 
               [Native to Managed Transition]  
               [Managed to Native Transition]  
               Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Invoke(string verb, object pvaIn, out object pvaOut) + 0x21 bytes        
               Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.VsCommand.Execute(object parameter) + 0x22 bytes 
              PresentationFramework.dll!MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource commandSource, bool userInitiated) Line 194 + 0xc bytes            C#

**Comment by davkean** [comment]
This was fixed with https://github.com/dotnet/project-system/pull/4758.,
