### ISSUE TITLE
Project files can't be edited in diff-mode

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4767]
VSF_TYPE_MARKDOWNBasically title.

The new csproj files now live as first-class citizens and it's possible to single-click-preview or double-click-open them. It's also possible to Right-Click -&gt; Source Control -&gt; Compare with unmodified, which works more or less fine, but the csproj file is opened in a read-only mode. 

csproj files should be editable in diff mode as all other first-class files are.

_This issue has been moved from https://developercommunity.visualstudio.com/idea/482797/project-files-cant-be-edited-in-diff-mode.html
VSTS ticketId: 814001_
_These are the original issue comments:_

Fiona Niu[MSFT] on 3/7/2019, 07:10 PM (52 days ago): We have converted this feedback item from problem to idea. This change was done to better reflect the feedback's nature. It will allow other developers to easily find it and engage on it.
Jane Wu [MSFT] on 3/7/2019, 08:31 PM (52 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by davidwengier** [comment]
This is being tracked by #4215. In VS2019 these files are no longer read only, and if a user has previously opened a .csproj file for editing then our editor is used as expected. We are working offline to understand what else needs to be done to bring this up to the full fidelity experience.
