### ISSUE TITLE
Specify which target framework you want to use from a dependency

### ISSUE THREAD

**Issue by JamesNK** [dotnet/project-system#477]
With project.json there is no way to specify the target framework you want to use from a dependency. It is automatically chosen for you. I would like a way to specify this manually.

For example I have MyLibrary that has netstandard1.0 and netstandard1.1 frameworks.

I want to be able to explicitly say which framework I use from MyLibrary in another project that will run unit tests. That way I can run tests against the netstandard1.0 assembly and netstandard1.1 assembly.

**Comment by davkean** [comment]
Great suggestion. @nguerrera Can we put some metadata on the reference to influence this?

**Comment by nguerrera** [comment]
Sure! With https://github.com/Microsoft/msbuild/pull/1018, we ask the dependency's project for the properties that configure it to best match. We can change this to honor SetTargetFramework metadata that you already set on the reference. So it's trivial for project-to-project refs. Do we need parity for package refs?

**Comment by benaadams** [comment]
This is a problem for async; where `net452` will currently take precedence over `netstandard2.0` reference.

So if you use the package on `net471` which has good async and is compatible with  `netstandard2.0`; it will still fallback to the `net452` package which has **extremely** allocating async

![image](https://user-images.githubusercontent.com/1142958/40398866-0cc6c07e-5e32-11e8-82cc-c06dec64e75a.png)

**Comment by benaadams** [comment]
Think I was experiencing a debug build in NuGet rather than a targeting issue

**Comment by benaadams** [comment]
This is also useful; for example currently a net452 package will always take prescience over a netstandard2.0 for net471. However may want to force the netstandard2.0 package as it uses newer apis etc

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#2280
