### ISSUE TITLE
Dealing with changed solutions was better with old-style csprojs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4771]
<p>Situation: I have a solution open in VS and I switch branches. With old-style csprojs I was given a &quot;Reload Solution&quot; dialog, I clicked on that button, and it was done.</p><p>Having switched to &quot;sdk-style&quot; csprojs the experience now is that I get an <em>error message</em> that offers me to reload all projects (not the solution!), I click that, then some error happens midway though so I get asked the same question again, and again, and again, and at this point I just kill devenv and load the solution from scratch. The old experience was better.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/391209/dealing-with-changed-solutions-was-better-with-old.html
VSTS ticketId: 735198_
_These are the original issue comments:_

Jane Wu [MSFT] on 11/26/2018, 02:33 AM (154 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  You will hear from us in about a week on our next steps.</p><p><strong></strong><u></u><sub></sub><sup></sup></p>

**Comment by cartermp** [comment]
Based on the description this sounds like a bug.

**Comment by jmarolf** [comment]
Looks like no telemetry was recorded for this [internal ticket](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/735198). I can try and psychically debug what was happening but with out more info I don't think this is actionable. @cartermp can you re-open this bug on Developer Community and ask for more info?

**Comment by cartermp** [comment]
I've asked for follow-up

**Comment by jjmew** [comment]
We reopen the ticket to get more information
