### ISSUE TITLE
Visual Studio 2017 Project System: EnvDTE.Project.ProjectItems is empty during Wizard phase

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4779]
<p>Hi All<br><br>I created in the past a Visual Studio Project Custom Type based on MPF Library (https://github.com/tunnelvisionlabs/MPFProj10 ), using custom Wizard (based on IWizard interface). This is a completed new type for Visual Studio, and it worked very well. <br><br>Now, I try to implement my custom project type with the new Visual Studio 2018 Project System.<br><br>I try to use the Project Type Extensibility Project, that create two different project<br>1. &lt;myprojectName&gt;.ProjectTemplate, where I had inserted the definition of my project template<br>2. &lt;myprojectName&gt;.ProjectType, where there is the definition of the Project Type.<br><br>In the &lt;myprojectName&gt;.ProjectTemplate there is the definition of my template, and inside the .vstemplate file I completed the &lt;WizardExtension&gt; tag with my Wizard Library Information.<br><br>When I run my project, I am able to create my new project type: during the creation the wizard run succesfully, collecting some additional information which are used to complete the project definition.<br><br>During this stage, in the ProjectFinishedGeneration method (defined in IWizard inteface) I need to access the item of the project just created due the fact that I need to change the name of one of the item based on user input collected during wizard phase.<br><br>The problem is the fact that the EnvDTE.Project.ProjectItems collection is empty. So I am not able to access of project's items and to perform changes on it.<br><br>Something is wrong in my approach?<br><br>Regards</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/438173/visual-studio-2017-project-system-envdteprojectpro.html
VSTS ticketId: 779502_
_These are the original issue comments:_

Visual Studio Feedback System on 4/29/2019, 09:38 PM (40 hours ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by davkean** [comment]
By default, the new project system loads the tree asynchronously. You can turn that off via the property on the project type registration. See https://github.com/dotnet/project-system/blob/d170def823e38db6904b08a32a89eac0f05f5980/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeRegistration.cs#L17 as an example.
