### ISSUE TITLE
Microsoft.VisualStudio.ProjectVS.NuGet.ProjectRestoreInfo uses excessive memory

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#4797]
After loading Roslyn solution, force GC, this structure uses 2.5% of the managed heap.  Almost all of them to represent TargetFrameworks.  I would expect most projects share the same target framework, and so the overall memory usage of this structure to be close to 0%.

![image](https://user-images.githubusercontent.com/11638466/57328338-03236e80-70c6-11e9-8dcd-5d8a567f0a0e.png)

**Comment by davkean** [comment]
It's a little harder than that - they don't share the same "target frameworks" as that object represents NuGet's representation of a configuration.

**Comment by davkean** [comment]
We store this information to compare it with a new version of it to avoid notifying NuGet of unneeded restores - we should hash the thing, and notify if the hash has changed.
