### ISSUE TITLE
Remove double-writes in build

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4802]
We have the following [double-writes](https://github.com/KirillOsenkov/MSBuildStructuredLog/wiki/Double-write-detection) in our build, which means that we're dependent on different binaries in the tree.

We try very hard to avoid this: 
![image](https://user-images.githubusercontent.com/1103906/57399315-d9318100-7185-11e9-9b74-2f27b84706dd.png)

**Comment by jmarolf** [comment]
@davkean how can we ensure that this fails the build when we regress this?

**Comment by drewnoakes** [comment]
> how can we ensure that this fails the build when we regress this?

Filed https://github.com/microsoft/msbuild/issues/4524.

**Comment by jmarolf** [comment]
Roslyn uses a tool called [BuildBoss](https://github.com/dotnet/roslyn/tree/master/src/Tools/BuildBoss) which reads the binlog after a build and fails if there is a double-write
