### ISSUE TITLE
VB imports in language service host

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#481]
We need to handle VB global import changes in language service host.

**Comment by basoundr** [comment]
@davkean @srivatsn We saw that the Global imports are already being passed to Roslyn through SetOptions. Currently, this task's ask is working. Is there anything else thats pending here?

**Comment by davkean** [comment]
Does the language service respect the imports like that? All other collections (references, files, etc) are passed explicitly via a AddXXX/RemoveXXX api.

**Comment by basoundr** [comment]
Yes, its works and I have verified it. It does not need the AddXXX/RemoveXXX apis
