### ISSUE TITLE
 [loc][Query][project-system] Localizability of "chkLaunchBrowserHelpText"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/project-system#4812]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Checking enables a textbox to specify an absolute or relative URl

File Name:
Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\xlf\PropertyPageResources.xlf

==========================================
Query:
Does this "checking" mean turning checkbox on? We have translated as "When turned on, textbox to specify an absolute or relative URl is enabled"

**Comment by davidwengier** [comment]
Yes, in this case "checking" means turning the checkbox on.

**Comment by PDostalek** [comment]
Thanks for reply
