### ISSUE TITLE
Project system removes <SubType>Code</SubType>

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/project-system#4814]
**Visual Studio Version**:

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.1.0 Preview 4.0 [28909.114.d16.1]
VisualStudio.16.IntPreview/16.1.0-pre.4.0+28909.114.d16.1

**Summary:**

This is the reverse of what was fixed in #4759: after that change, if you have `<SubType>Code</SubType>` it's now removed. That's "fine" in that it's harmless, but is still happening automatically.

**Steps to Reproduce**: Open Roslyn that doesn't have https://github.com/dotnet/roslyn/pull/35641 merged, and wait for awhile. Then hit Save All to save the project files.

**Expected Behavior**: nothing is changed

**Actual Behavior**: some elements are removed

**User Impact**: annoying, but ignorable

**Comment by davkean** [comment]
I think we've figured out this is just a point in time.
