### ISSUE TITLE
UseLayoutRounding and TextFormatting.Display on WPF property pages

### ISSUE THREAD

**Issue by wjk** [dotnet/project-system#4827]
**Visual Studio Version**: 16.0.4

**Summary:**

The WPF controls in this repo (`DontShowAgainMessageBox`, and the Debug and Package Properties property pages) use the default WPF theme. IMHO, this theme is extremely ugly, nor does it match the theme used by (almost all) other Visual Studio components. Unfortunately, I do not know of a good way to reference this theme. [This code is the best I can find](https://github.com/madskristensen/ExtensionPackTools/blob/master/src/ExtensionManager.Shared/Importer/VsTheme.cs), and when copied into the Managed.VS project, it seems to have no effect. Nor can I add the ResourceDictionary references it uses into the XAML statically, as these files are defined in [assemblies not part of the VS SDK](https://github.com/madskristensen/ExtensionPackTools/blob/46c20a7d247f71426ecaf3d30f606f7b0bc88ff3/src/ExtensionManager.Shared/Importer/VsTheme.cs#L52-L53), and we cannot reference them directly for this reason. Is there an alternative way we can accomplish this?

**Expected Behavior**: The VS theme should be used.  
**Actual Behavior**: The default WPF theme is used instead.  
**User Impact**: It looks bad.

**Comment by davkean** [comment]
@wjk Can you give an example of the "theme" used by other Visual Studio components?

**Comment by drewnoakes** [comment]
Some screenshots would be helpful.

**Comment by wjk** [comment]
I've taken a screenshot of the VS2019 New Project window. It seems that there are multiple "VS themes" used by various parts of VS; this one is the closest to what I am looking for.

<img width="1033" alt="Screenshot of the VS new project dialog" src="https://user-images.githubusercontent.com/1915951/59121577-7834ce80-8926-11e9-8be7-ec3e6db9a626.png">

You can also look at this screenshot, which is the result of using the class I linked to in my OP.

![screenshot](https://github.com/madskristensen/ExtensionPackTools/raw/master/art/export.png)

**Comment by mikedn** [comment]
Hmm, I think that the main problem here is that other project properties tabs use Winforms so they cannot be easily changed to use the WPF theme.

I'd be happy enough if the Debug tab would set `UseLayoutRounding` and `TextFormatting.Display` so at least the font is not blurry and consistent with the rest of the UI. But I don't have much hopes, anyway VS has a ton of such UI inconsistencies and ever version it adds more.

**Comment by wjk** [comment]
@mikedn I know the other panes use WinForms, and I am well aware of how inconsistent the VS UI is. I also agree that UseLayoutRounding and TextFormatting.Display are important steps.

However, that being said, another issue that I find is that the default WPF theme uses different backgrounds for buttons and combo-boxes. This results in a very obvious inconsistency when the two controls are placed next to each other. My main complaint with WPF as a whole is that the default themes look like they were designed by an intern on their first week on the job, five years ago, and never touched since then. Hopefully once the source for the themes are opened in WPF on Core, I'll be able to work on fixing that. (Won't help VS, of course, since it must stay on .NET Framework.)

The main reason I opened this issue is to address the font blurriness, and the combobox-versus-button issue. If we can use (some) VS theme to make the controls look more consistent, I'd really like to go that way. If we can't, I'd be satisfied if the two controls were made to look better next to each other (somehow). Thanks!

**Comment by mikedn** [comment]
> However, that being said, another issue that I find is that the default WPF theme uses different backgrounds for buttons and combo-boxes

Yes, WPF buttons and comoboxes stand out like a sore thumb. Trouble is, VS doesn't really have a better WPF theme, that make those control consistent with the Win32 ones used in other tabs. It has a WPF theme that looks completely different. And sometime even that is not used consistently or otherwise messed up (try publishing the project, you may run into a combobox that follows the VS dark theme but its item selection highlight is the default WPF one which looks weird in the dark theme).

**Comment by davkean** [comment]
@wjk We're not planning on moving the AppDesigner (prop pages) to use the WPF theme called out above, as @mikedn called out its very heavily WinForms based and not easily changed. We have intentions of replacing the pages in the distant future and we'll make it consistent as part of that.

> I'd be happy enough if the Debug tab would set UseLayoutRounding and TextFormatting.Display so at least the font is not blurry and consistent with the rest of the UI. But I don't have much hopes, anyway VS has a ton of such UI inconsistencies and ever version it adds more.

I'll treat this bug as exactly that. If there are other examples, individual bugs will help with screenshots.

**Comment by davkean** [comment]
@dmonroym I've picked this up.
