### ISSUE TITLE
Unit test templates missing from .NET Core Unit test project

### ISSUE THREAD

**Issue by hicks86** [dotnet/project-system#4828]
**Visual Studio Version**:
Visual Studio Professional 2017
Version 15.9.11

**Summary:**
Clicking on AddItem on a .NET Core 2.1 Unit Test Project does not show the Test category or any of the Unit test templates **(1)** (as opposed to a .NET Framework project **(2)** ).

**(1)**
![netcore_testtemplates](https://user-images.githubusercontent.com/11144895/57832213-02b66200-77af-11e9-83ef-9233b6a191eb.png)

**(2)**
![netframework_testtemplates](https://user-images.githubusercontent.com/11144895/57832214-02b66200-77af-11e9-8914-1ff882897dfa.png)

**Steps to Reproduce**:

1.  Right click on the unit test project go to "Add" > then select "New Item"

2. The "Add New Item" window will appear.

3. On the left hand side under Visual C# Items the "Test" category is missing, also in the central template area there are no test templates.

**Expected Behavior**:
To be able to Add a New Item to a test project using a template such as "Basic Unit Test"/"Generic Test"/"UnitTest")

**Actual Behavior**:
No test templates are found for .NET Core test project

**User Impact**:
Manual creation of a test class, via adding a plain class then adding the `[TestClass]` and `[TestMethod]` decorator attributes.

**Comment by hicks86** [comment]
Any updates on this guys?

**Comment by jmarolf** [comment]
sorry, missed the notifications for this somehow. this issue should be moved to https://github.com/microsoft/vstest

**Comment by hicks86** [comment]
No worries. Is there anything I can do to move it the the vstest repo issues? Should I repost it there?

**Comment by jmarolf** [comment]
If you can repost it there that would be great. I will leave this issue open until that can be accomplished

**Comment by hicks86** [comment]
Done - moved: https://github.com/microsoft/vstest/issues/2094
