### ISSUE TITLE
Nuget package restore error when upgrading to new project system, project type GUID issue

### ISSUE THREAD

**Issue by davidhunter22** [dotnet/project-system#4829]
Visual Studio 16.0.4 and 16.1 Preview 3

Recently we tried upgrading an existing C# solution to the new project system. All went well but we kept getting an error
"Error occurred while restoring NuGet packages: '' is not a valid version string."
After much investigation we found that we had not upgraded the project type GUID in the solution file from
FAE04EC0-301F-11D3-BF4B-00C04F79EFBC
to
9A19103F-16F7-4668-BE54-9A1E7A4F7556

The resulting error message is not really useful at all and in fact is misleading and we assumed it was a NuGet problem. If the old project type is no longer valid it would be very helpful to have a sensible error message to save others falling into the same mistake.

**Comment by drewnoakes** [comment]
@davidhunter22 are you able to share the contents of a `.csproj` that triggered this error?

Unless your project is doing something exotic, you shouldn't need to change the GUID in the `.sln` file.

**Comment by davidhunter22** [comment]
Actually I think I have got a better handle on what is going on. I tried to create a simple C# project from scratch . In our real solution we have a hundred or so project so one thing we do is to factor out some common MSBuild XML. So after creating a basic one project Hello World C# solution I created a Common.props file and imported it into the csproj file as in
    <Import Project="$(SolutionDir)\Common.props" />
In the Common.props I added
```
  <PropertyGroup>
    <TargetFrameworks>net45;net46;net47;netcoreapp2.1;netstandard2.0</TargetFrameworks>    
  </PropertyGroup>
```
and removed the <TargetFrameworks> from the csproj file. When I build I get errors like
```
Error occurred while restoring NuGet packages: '' is not a valid version string.
1>------ Build started: Project: ConsoleApp3, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\2.2.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1004: Assets file 'C:\Users\david\source\repos\NugetRestore\Project\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>C:\Program Files\dotnet\sdk\2.2.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1004: Assets file 'C:\Users\david\source\repos\NugetRestore\Project\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>C:\Program Files\dotnet\sdk\2.2.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1004: Assets file 'C:\Users\david\source\repos\NugetRestore\Project\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
Which don't go away if I do a Nuget restore.
In my original post I mentioned the project GUID in the solution file. I noticed by default this was created as  FAE04EC0-301F-11D3-BF4B-00C04F79EFBC, so I tried changing this to 9A19103F-16F7-4668-BE54-9A1E7A4F7556. After doing this the build worked so the GUID is definitely having some effect.

So my feeling is that the main issue is that the default GUID used by Visual Studio is FAE04EC0-301F-11D3-BF4B-00C04F79EFBC not 9A19103F-16F7-4668-BE54-9A1E7A4F7556.

[NugetRestore.zip](https://github.com/dotnet/project-system/files/3245294/NugetRestore.zip)

**Comment by davidwengier** [comment]
By removing the `TargetFrameworks` from the project file you're essentially running into #4314. The GUIDs are somewhat explained in https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md

**Comment by drewnoakes** [comment]
@davidhunter22 an alternative to changing project GUIDs in the solution is to use this in each project file:

```xml
<TargetFrameworks>$(TargetFrameworks)</TargetFrameworks>
```
This has no effect on how the project is evaluated, but will allow the detection to work.

It's up to you which you prefer.

**Comment by davidhunter22** [comment]
Great suggestion thanks, maybe this is why I don't get the mega bucks! I am going with the GUID approach. Note this works for the small test case. Visual Studio hangs on open for our real solution. Getting a bit late here so I will create a test case and post an issue tomorrow if needed.

**Comment by davkean** [comment]
We fixed the detection logic in https://github.com/dotnet/project-system/issues/4314 for 16.4.
