### ISSUE TITLE
Get CPS nuget packages to upload to a public feed automatically

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#4835]
CPS nuget packages are currently a completely manual process

**Comment by davkean** [comment]
@jmarolf We're blocked on consuming the new CPS package for 16.2 because they have no space on their MyGet, anyway to front load this?

**Comment by davkean** [comment]
@dmonroym Please bite this off in 16.5 and automate the publishing of NuGet packages from the CPS build. This is a large pain point.

**Comment by dmonroym** [comment]
Release was modified and we should be publishing automatically now into https://dev.azure.com/azure-public/vside/_packaging?_a=feed&feed=vs-impl%40Local
