### ISSUE TITLE
Publish CPS dependencies in nuget packages so we can re-host CPS in functional tests

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#4838]
relates to [AB#1087082](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1087082)

**Comment by jmarolf** [comment]
co-assigning to @davkean since he has the best idea of which host-agnostic assemblies we need

**Comment by davkean** [comment]
This represents putting the CPS implementation assemblies (Microsoft.VisualStudio.ProjectSystem.Implementation, Microsoft.VisualStudio.ProjectSystem.VS.Implementation) into a private NuGet package that we can consume and fire up real CPS-based projects in tests without needing to mock or fire up real VS instances.

**Comment by MiYanni** [comment]
Integration tests will be maintained internally. No need to republish packages externally.
