### ISSUE TITLE
Project system does not appear to support __VSHPROPID2.VSHPROPID_DesignerHiddenCodeGeneration property

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/project-system#4840]
I suspect that this really really needed, but the WinForms Designer is hitting an assert because `IVsHierarchy.GetProperty(...)` is returning an error for this property. Even when the property isn't provided, the designer returns `__VSDESIGNER_HIDDENCODEGENERATION.VSDHCG_InitMethods | __VSDESIGNER_HIDDENCODEGENERATION.VSDHCG_Declarations`, so I don't think it's a big deal.

**Comment by davkean** [comment]
@davidwengier Can you pick this up? 

VB returns:

```
VSDHCG_Declarations | VSDHCG_InitMethods;
```

C# returns:

```
VSDHCG_Declarations
```

It looks like the 'VSDHCG_Declarations` value is only actually used.

**Comment by davidwengier** [comment]
Internal PR for CPS support: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/183391

**Comment by davidwengier** [comment]
Internal PR is complete.
