### ISSUE TITLE
Cannot cut an open file from one project to another

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/project-system#4845]
**Visual Studio Version**: 16.2 Preview 1

**Steps to Reproduce**:

1. Open a .cs file, and make an edit in it.
2. While the file is open, cut and paste the file via solution explorer into a different _project_.

**Expected Behavior**: Ideally, the file's open file name is updated live in the unsaved buffer. Barring that, the file is saved and then moved.

**Actual Behavior**: ~The file is moved on disk~, but the open file is still pointing to the old path. Saving saves it into the *old* path, so you now have duplicate files.

**Notes:**

1. I hit this while dogfooding: added a file to the wrong layer in Roslyn. Was editing and then realized my mistake (not the right types appearing in completion). But moving the file resulted in a copy and more confusion.
2. It seems you need the combination of you having unsaved changes _and_ it being moved cross-project. If you have saved changes the file is closed from the source and cleanly removed. I suspect that's how modeled under the covers -- close the old file and then move it -- but since it can't be saved it just aborts that step.
3. This seems broken in csproj.dll too; if there's a VS limitation I get it and maybe this can't be fixed; if this is something that CPS can make better...that'd be nice!

**Comment by davkean** [comment]
Reopening for triage - cut is broken between projects when the file is already open.

**Comment by davkean** [comment]
NOTE: The file still exists in the soure location in my testing and updated Jason's repro.

**Comment by davkean** [comment]
This looks intentional, but feels like we should be able to do better than this as we own both sides of the copy/paste operation:

```
                    // Cut&Paste operations are interesting.  When used to move files within a single
                    // project, any files that are opened with unsaved changes SHOULD be preserved
                    // as open with unsaved changes intact across the move.  But when the files are
                    // pasted to a target that isn't CPS (e.g. Windows Explorer or a non-CPS project in VS)
                    // there is no opportunity to save the files before the target copies them over,
                    // so to avoid losing unsaved changes, we DO NOT remove the source items in that case.
                    // This is parity with C# behavior.
```

**Comment by davkean** [comment]
Note: Legacy prompts before doing this (see CVsProjHierarchy::OnBeforeDropNotify): 
```
---------------------------
Microsoft Visual Studio
---------------------------
One or more open documents have unsaved changes. Do you want to save uncommitted changes before proceeding?
---------------------------
Yes   No   Cancel   
---------------------------
```

**Comment by davkean** [comment]
Note: This fixes the prompt: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/225657 for drag/drop, it was already implemented but was broken due to some refactoring. After this change, the behavior is identical to legacy where drag/drop gives you an unsaved prompt, _cut/cop and paste_ still slightly copies over the old version of the file without a prompt which is not ideal and we should fix.

**Comment by davkean** [comment]
We can do much better than legacy here; see DocumentManager.RenameDocument - we can specify a new hierarchy/item id of the thing in that hierarchy as the destination which will leave the open document just send it over to the new hierarchy, we just bail in `DiskBasedDragDropItemHandler.UpdateDocumentTable`. We need to plumb it through and stop closing the doc in `ProjectNode.CleanupSelectionDataObjectAsync`.

**Comment by ocallesp** [comment]
Moving this to CPS AB#1679453
