### ISSUE TITLE
Handle project snapshot versions between evaluation and design-time

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#485]
We're not coordinating between evaluation and design-time builds so things could get out of sync, such as when a design-time build re-adds a file that was just removed.

**Comment by spottedmahn** [comment]
[VS Feedback Issue](https://developercommunity.visualstudio.com/content/problem/44059/using-statements-not-resolving.html)

**Comment by Lisaj** [comment]
[False error The type or namespace name could not be found](https://developercommunity.visualstudio.com/content/problem/48052/false-error-the-type-or-namespace-name-could-not-b.html)

**Comment by tzwlai** [comment]
[IntelliSense reports stale problems after installing a NuGet package](https://developercommunity.visualstudio.com/content/problem/49284/intellisense-reports-stale-problems-after-installi.html)

**Comment by srivatsn** [comment]
Fixed by https://github.com/dotnet/project-system/pull/2178
