### ISSUE TITLE
Project shows no files, loaded as old-style csproj, and references are all errors

### ISSUE THREAD

**Issue by cartermp** [dotnet/project-system#4857]
**Visual Studio Version**: 16.2 Preview 2 (IntPreview)

**Steps to Reproduce**:

Open `MicroBenchmarks.sln` from here: https://github.com/dotnet/performance/tree/master/src/benchmarks/micro

Observe that there are no files and the references are all warn'd out:

![image](https://user-images.githubusercontent.com/6309070/58199442-529c9980-7c85-11e9-9f6a-1e986caded32.png)

I tried modifying the project file to remove `ToolsVersion` and that doesn't appear to have any effect. The project file doesn't _seem_ bad, but perhaps it's me that's bad in all of this 🙂

**Comment by davkean** [comment]
You are running into limitations called out by: https://github.com/dotnet/project-system/issues/4314, they either need to put a TargetFramework into the project or opt into CPS via https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md until this has been fixed.
