### ISSUE TITLE
NullableContextOptions no longer works

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#4858]
VSF_TYPE_MARKDOWNIn our .csproj files, this used to enable nullable context:
&lt;NullableContextOptions&gt;enable&lt;/NullableContextOptions&gt; 

Now, after upgrading to 16.2 preview 1, it no longer works.  The compiler throws errors as if we were not in a nullable context.  Surrounding code with #nullable enable/restore still works, but it's not feasible to do it for each and every code file in our solution.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/576567/nullablecontextoptions-no-longer-works.html
VSTS ticketId: 896657_
_These are the original issue comments:_

Pierre Arnaud on 5/22/2019, 05:59 PM (16 hours ago): I've the exact same issue on all my projects.<br>
Visual Studio Feedback System on 5/22/2019, 06:02 PM (15 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Kexy Biscuit on 5/22/2019, 07:14 PM (14 hours ago): <p>Me too, this breaks nearly everything for me.</p>

richf on 5/22/2019, 10:04 PM (11 hours ago): Same problem.<br>Building from commandline does not have any issue
Anthony Trudeau on 5/23/2019, 08:20 AM (99 min ago): <p>@VisualStudio on Twitter directed me to share my comments here after some messages there.</p><p>I'm on 16.1 within a new WPF project and using the element in the project file has no affect. There are no errors, warnings, or otherwise. Using the directive in the individual code files works as expected.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by drewnoakes** [comment]
My intention was to move this to Roslyn, but I was not able to use GitHub's issue transfer feature (I got a 500 error).

Moved manually to https://github.com/dotnet/roslyn/issues/35901
