### ISSUE TITLE
Error. Who know why? I have all update

### ISSUE THREAD

**Issue by restrellasosa** [dotnet/project-system#4866]
![Capture](https://user-images.githubusercontent.com/6253560/58330826-bf3ea200-7e05-11e9-816a-6228d9327885.JPG)
**Visual Studio Version**:

**Summary:**

**Steps to Reproduce**:

1. 

2. 

3. 

**Expected Behavior**:

**Actual Behavior**:

**User Impact**:

**Comment by drewnoakes** [comment]
Does this belong in https://github.com/aspnet/EntityFrameworkCore?

**Comment by davkean** [comment]
I'm going to close this. If you are still running into issues please open a bug against https://github.com/aspnet/EntityFrameworkCore.
