### ISSUE TITLE
"View In Object Browser" does not work for COM references

### ISSUE THREAD

**Issue by kfertitta** [dotnet/project-system#4867]
**Visual Studio Version**:
Visual Studio 2019 16.1

**Summary:**
For regular, non-SDK-style projects, you can add a COM reference to a C# EXE or class library project and navigate to the Object Browser using the "View in Browser" command on the reference node for the associated interop assembly.

For SDK-style projects (.NET Core or even .NET Framework), this seems broken.  The dependencies tree includes a COM node, which is properly rendered and resolved for the COM reference (and associated Primary Interop Assembly).  However, the "View in Browser" command throws and error, or simply does nothing.

**Steps to Reproduce**:

1.  Create a .NET Core EXE application.

2.  Change the `TargetFramework` to `net45`.

3. Add a COM reference to the project for any COM component on the system that has a primary interop assembly installed in the GAC.

4. Build.  (or not, doesn't seem to matter)

5. Right-click on the COM node associated with the reference you just added and choose "View in Browser".

**Expected Behavior**:
This should open the Object Browser and navigate to the interop assembly in question.  For a regular non-SDK-style project, this works as expected.

**Actual Behavior**:
Either an error is reported or nothing happens at all.

**Comment by davkean** [comment]
See where QUICKOBJECTSEARCH is being handled in DefaultCommandSet2KHandler in CPS code.

**Comment by ocallesp** [comment]
I followed the steps in the description, but I was not able to repro the bug.

@kfertitta still having this issue ?

**Comment by davkean** [comment]
Looks like the command isn't showing up at all anymore, which is wrong too.

![image](https://user-images.githubusercontent.com/1103906/78213512-9b0c2100-74fe-11ea-8978-c715d11dba07.png)

**Comment by davkean** [comment]
@drewnoakes Was this added to the COM reference menu?

**Comment by ocallesp** [comment]
@davkean the image is from Right click on Dependencies (Solution Explorer) ? The missing command is "Add Reference" ?

![image](https://user-images.githubusercontent.com/510598/78217470-07404380-7471-11ea-8f1a-c1357e4fdb1c.png)

**Comment by davkean** [comment]
I'm not following, the missing command is "View In Object Browser". By not being able to repo, what exactly do you mean? The command doesn't show up? The command shows up but works?

**Comment by drewnoakes** [comment]
The PR that introduced these menus is https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/231736

"View in Object Browser" was not added to the context menu for COM references. To do so, add group `IDG_VS_CTXT_ITEM_OBJECTBROWSER` to menu `IDM_VS_CTXT_COMREFERENCE`.

The command was also omitted for framework references (#5643), analyzer references and package references (#1256). It's not clear to me which of these it should apply to however.

Also see #5532 which covers the menu item only working for the first target framework when multi-targeting.

On the issue of browsing COM references, https://github.com/dotnet/project-system/issues/403#issuecomment-273974199 might be useful.

**Comment by davkean** [comment]
You manually add the command to context menu/menu/toolbar via Tools -> Customize.

**Comment by ocallesp** [comment]
@davkean 
none of the categories contain the command 'View in Object Browser'
![image](https://user-images.githubusercontent.com/510598/78924798-3f3a1e80-7a4f-11ea-9322-b216e9d02ab7.png)

**Comment by ocallesp** [comment]
Moved to CPS AB#1679561

**Comment by drewnoakes** [comment]
This is not a CPS issue. We own the dependency tree.
