### ISSUE TITLE
Remove ITargetFramework and ITargetFrameworkProvider

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4886]
Review and potentially remove `ITargetFramework` and `ITargetFrameworkProvider` interfaces.

Discussed in https://github.com/dotnet/project-system/pull/4724#discussion_r288430338.

Relates to #2795.

**Comment by davkean** [comment]
The reason these should be removed is that dependency node shouldn't know anything about TargetFrameworks - all it should know is that there's a 3rd dimension and it's used for grouping dependencies.

**Comment by drewnoakes** [comment]
Closing as duplicate of #2525.
