### ISSUE TITLE
Expected 1 export(s) with contract name "IPackageRestoreConfiguredDataSource" but found 0 when opening my solution

### ISSUE THREAD

**Issue by MichaelRumpler** [dotnet/project-system#4889]
**Visual Studio Version**:
VS 16.1.1 and 16.2.0 Preview 1

**Summary**:
When I open a Xamarin.Forms solution with a multi-targeting project in VS2019, I get an error and the project doesn't build.
![image](https://user-images.githubusercontent.com/8309363/58704320-dd7b4380-83ab-11e9-9e3e-1350e5824c36.png)

The logfile for VS 16.2.0 Preview 1 shows:

	=====================
	5/31/2019 1:42:38 PM
	LimitedFunctionality
	System.AggregateException: Project system data flow 'UnwrapCollectionChainedProjectValueDataSource`2: 46556843' closed because of an exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. 
	---> Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "Microsoft.VisualStudio.ProjectSystem.VS.PackageRestore.IPackageRestoreConfiguredDataSource" but found 0 after applying applicable constraints.
	   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
	   at Microsoft.VisualStudio.Composition.DelegatingExportProvider.GetExports(ImportDefinition importDefinition)
	   at Microsoft.VisualStudio.ProjectSystem.FilteringExportProvider.GetExports(ImportDefinition importDefinition)
	   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
	   at Microsoft.VisualStudio.ProjectSystem.VS.PackageRestore.PackageRestoreUnconfiguredDataSource.GetProjectRestoreDataSource(ConfiguredProject project)
	   at Microsoft.VisualStudio.ProjectSystem.VS.PackageRestore.PackageRestoreUnconfiguredDataSource.<LinkExternalInput>b__5_2(ConfiguredProject project)
	   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	   at Microsoft.VisualStudio.ProjectSystem.UnwrapCollectionChainedProjectValueDataSource`2.CreateOrUpdateLink(IProjectVersionedValue`1 sourceData, IImmutableDictionary`2 linkVersion, ITargetBlock`1 targetBlock, IDisposable currentLink)
	   at Microsoft.VisualStudio.ProjectSystem.UnwrapChainedProjectValueDataSourceBase`2.<>c__DisplayClass12_0.<LinkExternalInput>b__1(IProjectVersionedValue`1 sourceData)
	   at Microsoft.VisualStudio.ProjectSystem.ActionBlockSlimSync`1.ProcessInputAsync(TInput input)
	   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
	   --- End of inner exception stack trace ---
	   --- End of inner exception stack trace ---

In 16.1.1 I also saw the exception in `PackageRestoreUnconfiguredDataSource` instead of `UnwrapCollectionChainedProjectValueDataSource`.

When I try to build the project, then it can't find the Xamarin TFMs:

	Error occurred while restoring NuGet packages: The operation failed as details for project MR.Gestures could not be loaded.
	1>------ Build started: Project: MR.Gestures, Configuration: Debug Any CPU ------
	1>C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(157,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
	1>C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(93,5): error NETSDK1013: The TargetFramework value 'Xamarin.iOS10' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.
	1>Done building project "MR.Gestures.csproj" -- FAILED.
	1>C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(93,5): error NETSDK1013: The TargetFramework value 'MonoAndroid81' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.
	1>Done building project "MR.Gestures.csproj" -- FAILED.
	1>C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(93,5): error NETSDK1013: The TargetFramework value 'uap10.0.16299' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.
	1>Done building project "MR.Gestures.csproj" -- FAILED.
	1>C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(233,5): error NETSDK1005: Assets file 'D:\MR.Gestures\MR.Gestures\obj\project.assets.json' doesn't have a target for '.NETStandard,Version=v2.0'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project.
	1>Done building project "MR.Gestures.csproj" -- FAILED.
	1>C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(157,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
	1>C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(157,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
	1>C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(233,5): error NETSDK1005: Assets file 'D:\MR.Gestures\MR.Gestures\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.1'. Ensure that restore has run and that you have included 'net461' in the TargetFrameworks for your project.
	1>Done building project "MR.Gestures.csproj" -- FAILED.
	1>MR.Gestures -> D:\MR.Gestures\MR.Gestures\bin\Debug\netstandard1.0\MR.Gestures.dll
	========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I can open and build the solution without problems in VS2017 15.9.12.

This seems very similar to https://github.com/dotnet/project-system/issues/4801, but I don't have a `DotNetCliToolReference` in my csproj file.

My .csproj looks like this:

	<Project Sdk="Microsoft.NET.Sdk">

	  <PropertyGroup>
		<TargetFrameworks>netstandard1.0;netstandard2.0;Xamarin.iOS10;MonoAndroid81;uap10.0.16299;net461</TargetFrameworks>
		
	

		<AssemblyName>MR.Gestures</AssemblyName>
		<RootNamespace>MR.Gestures</RootNamespace>

		<Product>$(AssemblyName) ($(TargetFramework))</Product>
		<Version>2.1.0</Version>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<AssemblyFileVersion>$(Version)</AssemblyFileVersion>
		<PackageVersion>$(Version)</PackageVersion>

		<NeutralLanguage>en</NeutralLanguage>
		<DefineConstants>$(DefineConstants);</DefineConstants>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>

		<XFDisableFrameworkVersionValidation>True</XFDisableFrameworkVersionValidation>

		<LangVersion>7.3</LangVersion>

		<Copyright>Copyright 2015-$([System.DateTime]::Now.Year)</Copyright>
	  </PropertyGroup>

	  <PropertyGroup Condition=" '$(Configuration)'=='Debug' ">
		<DebugType>full</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	  </PropertyGroup>
	  <PropertyGroup Condition=" '$(Configuration)'=='Release' ">
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<DebugType>pdbonly</DebugType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>1701;1702;1705;1591</NoWarn>
	  </PropertyGroup>

	  <ItemGroup>
		<PackageReference Include="MSBuild.Sdk.Extras" Version="1.5.4" PrivateAssets="All" />
		<PackageReference Include="Xamarin.Forms" Version="4.0.0.425677" />
		<Compile Include="All\**\*.cs" />
	  </ItemGroup>

	  <ItemGroup Condition=" $(TargetFramework.StartsWith('netstandard')) ">
	  </ItemGroup>

	  <ItemGroup Condition=" $(TargetFramework.StartsWith('uap10.0')) ">
		<PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="6.0.12" />
		<Compile Include="UWP\**\*.cs" />
	  </ItemGroup>

	  <ItemGroup Condition=" $(TargetFramework.StartsWith('MonoAndroid')) ">
		<PackageReference Include="Xamarin.Android.Support.Design" Version="28.0.0.1" />
		<PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="28.0.0.1" />
		<PackageReference Include="Xamarin.Android.Support.v4" Version="28.0.0.1" />
		<PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="28.0.0.1" />
		<PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="28.0.0.1" />
		<Compile Include="Android\**\*.cs" />
	  </ItemGroup>

	  <ItemGroup Condition=" $(TargetFramework.StartsWith('Xamarin.iOS')) ">
		<Compile Include="iOS\**\*.cs" />
	  </ItemGroup>

	  <ItemGroup Condition=" $(TargetFramework.StartsWith('Xamarin.Mac')) ">
		<Compile Include="macOS\**\*.cs" />
	  </ItemGroup>

	  <ItemGroup Condition=" $(TargetFramework.StartsWith('net4')) ">
		<PackageReference Include="Xamarin.Forms.Platform.WPF" Version="4.0.0.425677" />
		<Compile Include="WPF\**\*.cs" />
	  </ItemGroup>

	  <ItemGroup>
		<None Include="**/*" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder);$(Compile)" />
	  </ItemGroup>

	  <ItemGroup>
		<None Remove="All\Controls.tt" />
	  </ItemGroup>

	  <ItemGroup>
		<None Include="All\Controls.tt">
		  <Generator>TextTemplatingFileGenerator</Generator>
		  <LastGenOutput>Controls.cs</LastGenOutput>
		</None>
	  </ItemGroup>

	  <ItemGroup>
		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	  </ItemGroup>

	  <ItemGroup>
		<Compile Update="All\Controls.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Controls.tt</DependentUpon>
		</Compile>
	  </ItemGroup>

	  <Import Project="$(MSBuildSDKExtrasTargets)" Condition="Exists('$(MSBuildSDKExtrasTargets)')" />
	</Project>

**Expected Behavior**:
It opens and builds without errors.

**Actual Behavior**:
It doesn't.

**User Impact**:
Still have to use VS2017.

**Comment by davkean** [comment]
I cannot repro this particular bug. Can you try the following project and see if the same thing occurs:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.0;netstandard2.0;net461</TargetFrameworks>
  </PropertyGroup>
</Project>
```
For the TFMs issue please open a bug over at https://github.com/onovotny/MSBuildSdkExtras, we do not support targeting Xamarin/UWP from the project system or SDK.

**Comment by onovotny** [comment]
Can you please switch to the SDK style of reference with the latest Extras version?
https://github.com/onovotny/MSBuildSdkExtras#migrate-from-the-old-way-vs-pre-156

Using it as a package reference isn't supported anymore.

**Comment by MichaelRumpler** [comment]
When I change my csproj to that empty project from above, then I get no error when opening VS2019 (but it doesn't compile of course).

Then I put everything back in but the references to MSBuild.Sdk.Extras and the Xamarin TFMs and also got no error. So I'll close this issue and open one there.

Thanks for your help!
