### ISSUE TITLE
Copy folder in .shproj to consuming project's bin directory

### ISSUE THREAD

**Issue by td-donsartain** [dotnet/project-system#4890]
**Visual Studio Version**: 15.9.4

**Summary**:
I have a shared project that has folder structure that needs to be maintained when the contents are compiled into the consuming project's bin directory, but the folders are being excluded.

For Example: X.Y.D/XSD/AddNewRequestTimeOff.xsd is the project name, folder, and file name. 

The .prjItems is set to always copy the .xsd file:
```
<ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)XSD\AddNewRequestTimeOff.xsd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

The .csproj file imports the shared project:
`<Import Project="..\BenefitMall.HRAPI.XSD\BenefitMall.HRAPI.XSD.projitems" Label="Shared" />`

The build does push the AddNewRequestTimeOff.xsd file to the bin directory, but it does not include the XSD parent folder, which breaks requirements for other areas of the code.

**Steps to Reproduce**:

1. Add a shared project

2. Add a folder with file contents

3. Set the file contents to Copy Always or Copy Newest

4. Create a new .csproj

5. Add the shared project as a reference

6. Build the solution

**Expected Behavior**:
The folder structure should be included in the .csproj bin directory

**Actual Behavior**:
It is only the file contents that make it to the bin directory, without the folder structure.

**User Impact**:
This is causing areas of the code that look for files in specific places to not work, and we are unable to change the file locations in code at this time. This causes areas of our application to fail during runtime because it can't find the files.

**Comment by davkean** [comment]
I cannot repro this, I have the following in the shared project:

``` XML
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)NewFolder\XMLFile1.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

And it correctly gets copied to [OutputPath\NewFolder\XMLFile1.xml into the destination project.

Can you please produce a [binary log](http://msbuildlog.com/#usingbl) that produces the problem and file a bug over at http://github.com/microsoft/msbuild?
