### ISSUE TITLE
Confusing analyzer warnings in solution explorer with no way to see any details

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/project-system#4893]
**Visual Studio Version**: 16.1.1

**Summary**: The Analyzers node in Solution Explorer shows some items that seem to be warnings about the code, but there appears to be no way to see what code they refer to.

**Steps to Reproduce**:

1. Create an empty ASP.NET Core 2.2 web application.
2. Expand Dependencies, Analyzers in solution explorer.

**Expected Behavior**:

Either no warnings or I can double-click on the warning to go to the line of code where the problem occurs or there is a context menu item for this.

**Actual Behavior**:

Warnings such as "MVC1000 Use of IHtmlHelper.{0} should be avoided." and "EF1000 Possible SQL injection vulnerability." are shown:

![image](https://user-images.githubusercontent.com/34301024/58881046-9eb1fa00-86d9-11e9-944c-d971e9fee90b.png)

There are no warnings in the Error list, even if I build the solution.

In my real project there are also warning icons, like this:

![image](https://user-images.githubusercontent.com/34301024/58881304-36afe380-86da-11e9-9c77-dca9948de8cf.png)

This is what first attracted my attention to it and I thought that the warning icons referred to the text of the child nodes, but when I create a new empty project I get those child text nodes without the warning icon. There seem to be other issues about the warning icons, such as #2257 and #4716.

**User Impact**: Confusion!

**Comment by jmarolf** [comment]
@loop-evgeny 	there is the problem of https://github.com/dotnet/project-system/issues/2257 where the nodes show a warning icon on the root without explaination, however the issue you point out if by design.  These icons (which do not have color) are used to represent the severity of the analyzer result. Documentation is here: https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#analyzers-in-solution-explorer

**Comment by loop-evgeny** [comment]
OK, so that list of icons just shows the warning defined in the analyzer DLLs and not warnings detected in my solution? Makes sense now, I guess, but with the warning icon it's certainly confusing.

**Comment by secretwpn** [comment]
This is a very confusing indication indeed. Hope you find a better way of visualizing this in future.

**Comment by drewnoakes** [comment]
@secretwpn we're open to suggestions.

**Comment by jez9999** [comment]
I agree with the OP, the use of the yellow exclamation mark is profoundly confusing.  I associate that with something like "dependency failed to load".  If an analyzer loaded fine but generated a code warning, that's not something that should trigger an exclamation mark.

In addition, I have analyzers giving me a bunch of warnings in the solution explorer view (such as "Do not call 'IServiceCollection.BuildServiceProvider' in 'ConfigureServices'"), but none of them appear in the Error List.  This really needs to be done better.

**Comment by sharwell** [comment]
@jez9999 The yellow exclamation mark indicates a problem with the project. The gray exclamation is the one that is By Design. The image above shows both.

**Comment by epvanhouten** [comment]
@sharwell so how do we see the reason for the yellow triangle?

**Comment by sharwell** [comment]
@epvanhouten If I knew the answer to that question, I probably would see many fewer triangles because I would have been able to fix them by now. 😆

**Comment by epvanhouten** [comment]
@jmarolf Are we missing something here? How do we get at the information to make the IDE warnings go away?

**Comment by jmarolf** [comment]
@drewnoakes what is the best way to diagnose these?

**Comment by drewnoakes** [comment]
In the ideal case, there's a warning in the error list. However often there's not, and they're diagnosed on a case-by-case basis. It's actually currently very difficult to diagnose these due to the design of the dependencies node. We're improving the design, but it will be a while before this is improved very much. In the meantime, if you have a repro that results in such a warning icon, please open an issue and include repro steps.

**Comment by jez9999** [comment]
I'm still getting quite a few errors in the analyzers which cause a grey icon in the analyzer node, yes, but this then seems to cause parent nodes to get the yellow exclamation mark, with nothing appearing in the error list whatsoever.  This seems pretty broken at the moment, UI-wise.

![vs-analyzers](https://user-images.githubusercontent.com/793830/75361193-d89dde80-58ae-11ea-902b-1549e097d441.png)

**Comment by drewnoakes** [comment]
@jez9999 the issue with analyzers has been addressed in the latest 16.5 preview.

There are other cases that trigger the warning icon incorrectly, and we're working to fix them.

**Comment by russellg59** [comment]
Jeeeeezuz... these are annoying. Please, please, fix ASAP. To not be able to easily get an explanation is unforgivable in a product that costs $1,000s!

**Comment by xiongdashan** [comment]
These are annoying. Please, please, fix ASAP.

**Comment by davkean** [comment]
Folks, the warning symbol on the analyzer node with the full path displayed has been fixed in 16.5 Preview. If you continue to see the warning on the analyzer and you have that version installed, please open a new bug over https://github.com/dotnet/project-system/issues/new.

**Comment by lukecolbourn** [comment]
I'll miss them when they're gone.

**Comment by voroninp** [comment]
How do I find out the reason for the yellow triangle?

<img width="400" height="409" alt="Image" src="https://github.com/user-attachments/assets/f4846ca0-e19d-4eac-b0ed-892c03514af0" />
