### ISSUE TITLE
VS injecting items for EditorConfigFiles*.xaml

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4894]
I've noticed VS is creating the below diff on ~build of~ current `master`, presumably following #4883.

```diff
diff --git a/src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj b/src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
index d05e52e5a..d9cc0c8e5 100644
--- a/src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
+++ b/src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
@@ -399,4 +399,12 @@
     <AdditionalFiles Include="PublicAPI.Shipped.txt" />
     <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
   </ItemGroup>
+  <ItemGroup>
+    <None Update="ProjectSystem\Rules\Items\EditorConfigFiles.BrowseObject.xaml">
+      <Generator>MSBuild:Compile</Generator>
+    </None>
+    <None Update="ProjectSystem\Rules\Items\EditorConfigFiles.xaml">
+      <Generator>MSBuild:Compile</Generator>
+    </None>
+  </ItemGroup>
 </Project>
\ No newline at end of file
```

In https://github.com/dotnet/project-system/pull/4883#discussion_r288774773 @davidwengier points out that it's not needed, but having this generate all the time is going to be annoying.

Is there any reason not to just check it in?

//cc: @tmeschter @davidwengier

**Comment by davkean** [comment]
This is a CPS bug, and should be moved to CPS. This is incorrect generation, it thinks that the user has added a new file to project and adding a Generator (which is incorrect) to it.

**Comment by davkean** [comment]
I think you'll also find this only happens when switching between a branch with those files and without those files.

**Comment by drewnoakes** [comment]
Moved to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/905647
