### ISSUE TITLE
Custom Control templates fails if AssemblyInfo isn't present in the project

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4897]
**Steps to Reproduce**:

1.  File -> New WPF App (.NET Framework or .NET Core)
2.  If .NET Framework, remove AssembyInfo.cs
3.  Right-click Add -> New Item -> WPF -> Custom Control (WPF)

**Expected Behavior**:
Fails with an errror

**Actual Behavior**:
Succeeds

**Comment by davkean** [comment]
We should be asking for AssemblyInfo via https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivsprojectspecialfiles.getfile?view=visualstudiosdk-2017#Microsoft_VisualStudio_Shell_Interop_IVsProjectSpecialFiles_GetFile_System_Int32_System_UInt32_System_UInt32__System_String__ asking to create if it doesn't exist.

**Comment by davkean** [comment]
This is going to run into https://github.com/dotnet/project-system/issues/4898.

**Comment by jmarolf** [comment]
Closed with [AB#185705](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/185705)
