### ISSUE TITLE
Adding AssemblyInfo template causes build errors when assembly attributes are generated during build

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4898]
**Steps to Reproduce**:

1.  File -> New Console App (.NET Core) both C# and VB
2.  File -> Add -> New Item -> Assembly Info
3. Build

**Expected Behavior**:
No build errors

**Actual Behavior**:
Lots of build errors about duplicate assembly attributes

[AB#825237](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/825237)

**Comment by jmarolf** [comment]
@davkean 	This bug has existed since 15.3? If I add an assembly info file and the SDK generates the same attributes then the compilation will fail.  Won't this require changes to the SDK so they don't generate assembly attributes in the presence of and assembly info file?  

We could change the template to set `GenerateAssemblyInfo` to false in the project file, but that may not be a public contract we can depend on.

cc: @nguerrera

**Comment by nguerrera** [comment]
> Won't this require changes to the SDK so they don't generate assembly attributes in the presence of and assembly info file?

We can't do this. It is a breaking change and kind of goes against the design of the feature. Plenty of projects will have an AssemblyInfo.cs with only the things that we do not generate in it, such as `[assembly: ThemeInfo(...)]` We should not make it all generated or all in assemblyinfo.cs.

> We could change the template to set GenerateAssemblyInfo to false in the project file, but that may not be a public contract we can depend on.

That is a public contract, so you could use it, but I don't think that is the best experience. How about a capability for generation that provides a more modern assembly info template that doesn't add all the attributes, but points to how to control the generated ones in a comment, and shows how to add _other_ assembly attributes?

**Comment by jmarolf** [comment]
Talked with @nguerrera 	about this in person. Don't have an obvious answer other than:

1. Adding an AssemblyInfo.cs file to your project should not be destructive. This is a desired scenario if you want to add additional attributes other than the ones the SDK generates for you.
2. Setting `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>` in a project file is something that we should probably offer to the user, potentially as a codefix, if there are colliding attributes. Still need to think about this though

**Comment by davkean** [comment]
@jmarolf Your last sentence is exactly how I was thinking about this, we'd need a path in the template that read this property and did different things.

**Comment by jmarolf** [comment]
@davkean 	alright, I can add a wizard to detect this case or a special 'sdk-style' AssemblyInfo template that only shows when the correct capabilities are present and make the other AssemblyInfo template not show in that case

**Comment by davidwengier** [comment]
This is related to AB#825237
