### ISSUE TITLE
stop suggesting the deprecated "PackageLicenseUrl" in project file intelliSense

### ISSUE THREAD

**Issue by karann-msft** [dotnet/project-system#4903]
`PackageLicenseUrl` has been deprecated in favor of `PackageLicense` - see [4213](https://github.com/dotnet/project-system/issues/4213).

IntelliSense should not offer that option but suggest `PackageLicense`

![image](https://user-images.githubusercontent.com/16904420/59138109-f3ef4500-893f-11e9-824b-0e78c6795f19.png)

**Comment by davkean** [comment]
@karann-msft You folks own this scenario - can you please work with MSBuild to fix this?

**Comment by karann-msft** [comment]
Who owns the intellisense that shows up in the project file?

**Comment by davkean** [comment]
MSBuild.

**Comment by karann-msft** [comment]
Can you tag someone from msbuild? Or @rrelyea can you help route this?

**Comment by davkean** [comment]
http://github.com/microsoft/msbuild.

**Comment by drewnoakes** [comment]
Closing this since it's been moved to https://github.com/microsoft/msbuild/issues/4432.
