### ISSUE TITLE
Scalability performance tests should be moved to operation progress

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4909]
Our scalability performance tests should be moved to consume operation progress to better reflect our state vs just using solution load.

**Comment by davkean** [comment]
Source code: https://devdiv.visualstudio.com/DefaultCollection/InternalTools/_git/Scalability%20Measurment.

**Comment by jmarolf** [comment]
fixed by [AB#186475](https://devdiv.visualstudio.com/InternalTools/_git/Scalability%20Measurment/pullrequest/186475)
