### ISSUE TITLE
Scalability performance tests should GC before snapshotting working set

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4910]
The performance tests should run the following before snapshotting working set:

``` C#
GC.Collect();
GC.RunPendingFinalizers();
GC.Collect();
```

**Comment by davkean** [comment]
Looks like this is the code: https://devdiv.visualstudio.com/InternalTools/_git/Scalability%20Measurment?path=%2Fsrc%2FVSCMD%2FNativeMethods.cs&version=GBmaster&line=146&lineStyle=plain&lineEnd=146&lineStartColumn=44&lineEndColumn=67.

**Comment by drewnoakes** [comment]
The fix isn't that simple unfortunately. The code you linked runs in the driving console process, not devenv.exe.

**Comment by davkean** [comment]
There's actually a command called "Tools.ForceGC" that does a GC - assuming we have access to DTE out of proc in the console app, we should be able to run that command.

**Comment by jmarolf** [comment]
Forcing a GC is well understood best practice in APEX. There is support for this in APEX [here](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2FOmni%2FApex%2FHostIntegration%2FVisualStudio%2FVisualStudioHost.cs&version=GBmaster&line=537&lineStyle=plain&lineEnd=538&lineStartColumn=1&lineEndColumn=1).  It uses the DTE apis as @davkean 	describes

**Comment by jmarolf** [comment]
fixed by [AB#186458](https://devdiv.visualstudio.com/InternalTools/_git/Scalability%20Measurment/pullrequest/186458)
