### ISSUE TITLE
Shared project broken if ancestor folder contains percent-encoded character sequences

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4911]
**Visual Studio Version**: 15.9.12, 16.1.2

**Summary**:

Shared projects fail to load their contents if one of their ancestor folders contains [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding) (sometimes referred to as URL encoded) content.

**Steps to Reproduce**:

1. Create a new shared project `SharedProjectTest`, giving the same name to the solution and ensuring "Place solution and project in the same directory" is **not** checked
2. Add a class `Class1.cs` to the shared project
3. Close the solution, saving changes
4. On the file system, rename `SharedProjectTest` to `Shared%20Project%20Test`
5. Re-open the solution and notice the shared project contains no items
7. View the error list for warnings resembling:

> The file 'D:\dev\Shared Project Test\SharedProjectTest\Class1.cs' could not be added to the project.  'D:\dev\Shared Project Test\SharedProjectTest\Class1.cs' is outside the shared folder.

The warning gives an invalid path. The `%20` characters in the _actual_ path have been removed and substituted for spaces. This would apply to any percent-encoded character sequences.

Note that I found this after cloning a repo from Azure DevOps that had a space in its name.

To be clear, this is the structure before (which works):

```text
SharedProjectTest/SharedProjectTest.sln
SharedProjectTest/SharedProjectTest/SharedProjectTest.shproj
SharedProjectTest/SharedProjectTest/SharedProjectTest.projitems
SharedProjectTest/SharedProjectTest/Class1.cs
```

And after (which fails):

```text
Shared%20Project%20Test/SharedProjectTest.sln
Shared%20Project%20Test/SharedProjectTest/SharedProjectTest.shproj
Shared%20Project%20Test/SharedProjectTest/SharedProjectTest.projitems
Shared%20Project%20Test/SharedProjectTest/Class1.cs
```

This is probably due to use of `System.Uri` for paths in our implementation somewhere, potentially CPS.

**Expected Behavior**:

Shared project shows files.

**Actual Behavior**:

Shared project does not show files.

**User Impact**:

This is potentially very confusing for the end user. It's not clear what you have to do to fix this.

**Comment by davkean** [comment]
This will be CPS.

**Comment by drewnoakes** [comment]
Moved to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/917026

**Comment by jmarolf** [comment]
@drewnoakes 	can we keep the bug open and close it when CPS fixes it so external people know?

**Comment by davkean** [comment]
They aren't tied so someone has to spend time sync'ing these bugs to the VS ones. If a customer would like to track this bug, please Report a Problem and I'll link them.
