### ISSUE TITLE
Can't disable AppDesigner for the project by removing the capability

### ISSUE THREAD

**Issue by adrianvmsft** [dotnet/project-system#4924]
**Visual Studio Version**: 16.2

**Summary**:
This issue was filed a while ago #833 but was resolved as a duplicate of an issue affecting Shared Projects #1404, which was fixed meantime. However #833 still repros.

**Steps to Reproduce**:

Create new .Net Core project
Edit the project file and include the following at the end of the project (after Import Microsoft.CSharp.targets):
```xml
  <ItemGroup>
    <ProjectCapability Remove="AppDesigner" />
  </ItemGroup>
```
Reload the project
In solution explorer, select the project node, right click properties

**Expected Behavior**:
the CPS properties designer to be displayed

**Actual Behavior**:
App designer still gets displayed

Note: Other capabilities seem to be fine. For example, if you use 
```xml
<ProjectCapability Remove="OpenProjectFile" />
```
The Edit project menu item will be properly removed.

**User Impact**:
Project extenders can't use property pages defined via xaml rules

**Comment by etbyrd** [comment]
Took a quick look at this and this:

> Note: Other capabilities seem to be fine. For example, if you use 
> ```xml
> <ProjectCapability Remove="OpenProjectFile" />
> ```

Doesn't seem to be true anymore. I can't seem to remove any capability (that I don't add myself in the project file).

**Comment by davkean** [comment]
This is because AppDesigner is a fixed capability, to remove it you need to create a new project type without that capability.
