### ISSUE TITLE
Utility style project

### ISSUE THREAD

**Issue by davidhunter22** [dotnet/project-system#4926]
Is it possible to create a "Utility" style project in the new project system. By utility I mean a project that does not build anything. For instance I need a project that simply stores some files and has a Post/Pre BuildEvent that runs a script. Of course I'm not sure what Post/Pre build means in the context of a project that doesn't build anything.

**Comment by drewnoakes** [comment]
@davidhunter22 would shared projects achieve what need?

**Comment by huoyaoyuan** [comment]
What's it's difference from a `.props`/`.targets` file if those files are supported by IDE?

**Comment by davkean** [comment]
This a good suggestion, can you open a suggestion on Developer Community so that others can vote on it?

![image](https://user-images.githubusercontent.com/1103906/72575575-ffb4d800-3920-11ea-907c-d566e746e339.png)
