### ISSUE TITLE
Xamarin.Forms VS2017/19 tempate converted to paket gives "not compatible with netstandard2.0 "

### ISSUE THREAD

**Issue by generik0** [dotnet/project-system#4931]
VS2017/19

The standard Xamarin.Forms template with 1 monoandroid81 project and 1 netstandard2.0 project does not seam to work with paket.
Using standard paket convert from nuget 

e..g Errro:
- error NU1202: Package Xamarin.Android.Support.v4 27.0.2.1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Xamarin.Android.Support.v4 27.0.2.1 supports: monoandroid81 (MonoAndroid,Version=v8.1)
- Package Xamarin.Android.Support.v7.CardView 27.0.2.1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Xamarin.Android.Support.v7.CardView 27.0.2.1 supports: monoandroid81 (MonoAndroid,Version=v8.1)
- Xamarin.Forms targets have been imported multiple times. Please check your project file and remove the duplicate import(s)

**Steps to Reproduce**:

1. Create Xamarin.Forms solution from template, and build

2. Run nuget converter

3. paket install

4. Rebuild solution

**Expected Behavior**:

Should installnetstnadard nugets to app projects

**Actual Behavior**:
Does not build

**User Impact**:
Cannot use nuget, paket and / or build/rebuild without errors

Example added
[App1.zip](https://github.com/dotnet/project-system/files/3302927/App1.zip)

**Comment by davkean** [comment]
@generik0 Please start with filing an issue against https://github.com/fsprojects/Paket and if they can identify a bug in the SDK or Visual Studio that might be the cause of this, then we can look at this.

**Comment by generik0** [comment]
Omg. Sorry!!!!!
This was completely wrong of me... don’t know how I could have added this here!

Sorry...

**Comment by davkean** [comment]
No problem. I file bugs in the wrong repository all the time. :)
