### ISSUE TITLE
Remove deprecated analyzers

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4933]
In https://github.com/dotnet/roslyn-analyzers/issues/1917#issuecomment-503293520 and https://github.com/dotnet/roslyn-analyzers/issues/1918#issuecomment-503290765 @mavasani points out that `Microsoft.CodeQuality.Analyzers.Exp` is deprecated.

In 92dbbc15e63961f9159b11fdec1c7ae6bcd8fa5f I updated our usage of Roslyn Analyzers from version 2.6.3-beta1.19059.2 to version 2.9.3 and discovered the following packages were not available at that newer version:

- `Text.Analyzers`
- `Microsoft.CodeQuality.Analyzers.Exp`
- ~`Roslyn.Diagnostics.Analyzers`~

@mavasani are all three of these deprecated? Will we be losing anything by removing references to them?

**Comment by mavasani** [comment]
Below two are deprecated:

- `Text.Analyzers`
- `Microsoft.CodeQuality.Analyzers.Exp`

Roslyn.Diagnostics.Analyzers still has semi-internal analyzers for solutions used within our team (roslyn.sln, roslynanalyzers.sln, projectsystem.sln, etc.)

**Comment by drewnoakes** [comment]
@mavasani thanks for confirming.

Turns out @tmeschter is looking to remove those two in #4929.

**Comment by drewnoakes** [comment]
#5041 reverted the fix for this bug.

**Comment by drewnoakes** [comment]
@tmeschter FYI I'm assigning to you and including in this sprint. Feel free to assign it back or remove it from the sprint.

**Comment by davkean** [comment]
I can remove Text.Analyzers, I already removed Microsoft.CodeQuality.Analyzers.Exp.
