### ISSUE TITLE
The “Use Previews of the .NET Core SDK” switch is not available in the 16.3 Release channel build.

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/project-system#4934]
**Visual Studio Version**:
16.3.0 [29018.65.master]( [Release Channel](https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/VS/710819d747beda09ce59cbbbf69a82db4090fcab/258a92b4-1d34-4fee-88e3-fbb419f25336%3bchannels/internal/Release/bootstrappers/fixed/Enterprise/vs_Enterprise.exe))

**Summary**:

**Steps to Reproduce**:

1.  Install 16.3.0 [29018.65.master]( [Release Channel](https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/VS/710819d747beda09ce59cbbbf69a82db4090fcab/258a92b4-1d34-4fee-88e3-fbb419f25336%3bchannels/internal/Release/bootstrappers/fixed/Enterprise/vs_Enterprise.exe))

2. Create a new .NET Core console app project via VS

**Expected Behavior**:
1. Create a new .NET Core project, there is a message given to the user to toggle the “Use Previews of the .NET Core SDK” switch.
2. Toggle the “Use Previews of the .NET Core SDK” switch, the projects can be created successfully using the .NET Core 3.0 SDK

**Actual Behavior**:
1. Create a new .NET Core console app project, there is no message given to the user to toggle the “Use Previews of the .NET Core SDK” switch
![image](https://user-images.githubusercontent.com/33921754/59751714-9e0d8c00-92b3-11e9-96c5-37078ff0d37c.png)

2. Check the “Preview Features”, it shows: “There are no preview features available for you to try right now.”
![image](https://user-images.githubusercontent.com/33921754/59751773-b087c580-92b3-11e9-8df2-2bda79402af3.png)

**Environment data**
dotnet --info output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012323
 Commit:    46c4932822

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012323\

Host (useful for support):
  Version: 3.0.0-preview7-27809-09
  Commit:  b2a369fb53

.NET Core SDKs installed:
  3.0.100-preview7-012323 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19307.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27809-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27809-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by davkean** [comment]
tag @dmonroym

**Comment by dmonroym** [comment]
Relates to AB#897405
This was checked into lab/16.2stg so just waiting on integration into master. Will update this issue once it's checked in

**Comment by dmonroym** [comment]
It's now available in master and I've verified it's in this build: https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build/results?buildId=2789214&view=results

**Comment by YunWeiaa** [comment]
Not repro on “[[Release Channel](https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/VS/2ec8efc9df21f30b8d843c8d4b025b213f299ccf/4c37020a-8abf-8cb8-6b2b-b5fb2898982c%3bchannels/internal/Release/bootstrappers/fixed/Enterprise/vs_Enterprise.exe)]”( 16.3.0 [29021.39.master]).
