### ISSUE TITLE
Add support for SQL Server debugging

### ISSUE THREAD

**Issue by branko-d** [dotnet/project-system#4935]
**Visual Studio Version**:

2019 Professional (16.1.3)

**Summary**:

The "Enable SQL Server debugging" option is missing from the project properties for the SDK-style csproj.

It was present there with the "old-style" csproj, and enabling it would allow breakpoints set in T-SQL code to be hit when debugging C# code and stepping over `SqlCommand.ExecuteNonQuery` (or similar).

**Steps to Reproduce**:

**1.**  Connect to SQL Server (I used Developer Edition, but any should do) via SQL Server Management Studio, pick or create a database to use for testing, and create a simple stored procedure:

```sql
CREATE PROCEDURE FOO(@bar int OUT) AS
    SET @bar = 42;
```

**2.** Start Visual Studio 2019, pick "Create a new project" and create a Console App (.NET Core). 

Replace the...

```xml
<TargetFramework>netcoreapp2.2</TargetFramework>
```

...with...

```xml
<TargetFramework>net47</TargetFramework>
```

Replace the content of the generated Program.cs with (change the connection string as needed):

```c#
using System;
using System.Data;
using System.Data.SqlClient;

namespace SqlDebuggingSdkProject {

    class Program {

        static void Main(string[] args) {
            using (var conn = new SqlConnection("Data Source=.;Initial Catalog=DB1;Integrated Security=True")) {
                conn.Open();
                using (var tran = conn.BeginTransaction()) {
                    using (var cmd = new SqlCommand("FOO", conn, tran) { CommandType = CommandType.StoredProcedure }) {
                        var bar = new SqlParameter("bar", SqlDbType.Int) { Direction = ParameterDirection.Output };
                        cmd.Parameters.Add(bar);
                        cmd.ExecuteNonQuery();
                        Console.WriteLine(bar.Value);
                    }
                }
            }
        }

    }

}
```

**3.** View / SQL Server Object Explorer, browse to the stored procedure and place a break point in it.

**4.** Start debugging the console application, step over the `ExecuteNonQuery`.

**Expected Behavior**:

The breakpoint within the T-SQL stored procedure is hit.

**Actual Behavior**:

The debugger reaches the next line in C# code, without stepping into T-SQL.

**User Impact**:

Difficulty debugging any scenario where C# calls T-SQL code.

In our case, we have many automated integration tests written in C# that call into T-SQL stored procedures. These tests often prepare complex input data, interface with external systems (with APIs available from C# but not through T-SQL) and some of them are concurrent (to test for race conditions, deadlocks and such).

Being able to debug a failed test and jump straight into T-SQL was a big help for achieving the good quality of our product. Such "hybrid" C# to T-SQL debugging was available in older versions of Visual Studio and old-style csproj, but we now struggle to debug our code effectively.

Related StackOverflow question is [here](https://stackoverflow.com/q/56635940/533120).

**Comment by davkean** [comment]
Thanks for the suggestion, we'll accept a PR for this, similar example here:

PR that added native debugging support: https://github.com/dotnet/project-system/pull/2766
PR that added the checkbox for native debugging support: https://github.com/dotnet/project-system/pull/4624
