### ISSUE TITLE
Append "Windows Forms" and "WPF" suffix to file templates & menus

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4936]
Now that Windows Forms and WPF can be combined in the same project type, we should add suffix differentiators to differentiate the technologies:

![image](https://user-images.githubusercontent.com/1103906/59824384-4aaf4280-9374-11e9-8d16-3bd64029923a.png)

![image](https://user-images.githubusercontent.com/1103906/59824958-f86f2100-9375-11e9-922d-9feb0990dac3.png)

Proposal is to change the menus and template names to append the appropriate tech:

Current Template|Current Menu|New Template Name|New Menu Name
---|---|---|---
Inherited Form|N/A|Inherited Form (Windows Forms)|N/A
Inherited User Control|N/A|Inherited User Control (Windows Forms)|N/A
Window Form|Windows Form...|Form (Windows Forms)|Form (Windows Forms)...
User Control|User Control...|User Control (Windows Forms)|User Control (Windows Forms)...
About Box|N/A|About Box (Windows Forms)|N/A
Custom Control|N/A|Custom Control (Windows Forms)|N/A
MDI Parent Form|N/A|MDI Parent Form (Windows Forms)|N/A
Window (WPF)|Window...|Window (WPF)|Window (WPF)...
Page (WPF)|Page...|Page (WPF)|Page (WPF)...
User Control (WPF)|User Control...|User Control (WPF)|User Control (WPF)...
Resource Dictionary (WPF)|Resource Dictionary...|Resource Dictionary (WPF)|Resource Dictionary (WPF)...

[AB#825237](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/825237)

**Comment by jmarolf** [comment]
fixed with [AB#187828](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/187828)

**Comment by davidwengier** [comment]
This is related to AB#825237

**Comment by davkean** [comment]
@jmarolf Reopening this, this looks great with exception to WIndows Forms, it looks like Update 2 wasn't merged: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/187828?_a=files&iteration=2&base=1.

![image](https://user-images.githubusercontent.com/1103906/61107042-35848a00-a4c2-11e9-927f-a2e54d974164.png)


![image](https://user-images.githubusercontent.com/1103906/61107069-4503d300-a4c2-11e9-96b0-581599b16e65.png)

**Comment by jmarolf** [comment]
I don't know if I see the sense is writing `Windows Form (Windows Form)`. How does repeating yourself give the user more actionable information than the single `Windows Form`?

**Comment by davkean** [comment]
As per above and PR it was `Form (Windows Forms)`. Now the "Windows Forms" looks out of place with the other templates. It's not repeating, it's a `Form` from the technology `Windows Forms`, just like its a  `Window` from the technology `Windows Presentation Framework`

**Comment by davkean** [comment]
@jmarolf I see you updated C# here: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/191489?path=%2Fsrc%2Fvsproject%2Fcool%2Fcoolpkg%2Fpkgui%2Fcoolpkgui.rc&_a=files, but not VB. Was there a reason for that?

**Comment by davkean** [comment]
Oh, may be VB is okay:
![image](https://user-images.githubusercontent.com/1103906/61256439-32361a80-a7b0-11e9-8a57-728b75be45c1.png)

And only add item needed to be updated which is shared between C# and VB?

![image](https://user-images.githubusercontent.com/1103906/61256435-2ea29380-a7b0-11e9-9dae-ff13262d791c.png)

**Comment by davkean** [comment]
Although in saying that Splash Screen isn't updated, which was also called out:

![image](https://user-images.githubusercontent.com/1103906/61256524-690c3080-a7b0-11e9-8a16-d39b3ddb3596.png)

**Comment by jmarolf** [comment]
@davkean 	sorry, I somehow missed the conversation on splash screen.  Is there anything else I am missing from this table https://github.com/dotnet/project-system/issues/4936#issue-458364676? I'll send a mop-up pr shortly

**Comment by davkean** [comment]
It looks like only splash screen.

**Comment by jmarolf** [comment]
Should all be resolved with [AB#191747](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/191747)
