### ISSUE TITLE
Don't hide/remove empty TFMs

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4937]
**Visual Studio Version**: 16.2.0-pre.2.0+29006.145

**Summary**:

TFMs with no dependencies are removed from the dependencies node, which can be confusing.

**Steps to Reproduce**:

1. With SDK 3.0.100 installed open this project:

   ```xml
   <Project Sdk="Microsoft.NET.Sdk">
     <PropertyGroup>
       <OutputType>Exe</OutputType>
       <TargetFrameworks>netcoreapp2.1;netcoreapp3.0</TargetFrameworks>
     </PropertyGroup>
   </Project>
   ```

2. The Dependencies node looks like this:

   ![image](https://user-images.githubusercontent.com/350947/59825075-53a11380-9376-11e9-81f8-f3d52d249dd5.png)

3. Add:

   ```xml
   <ItemGroup>
     <PackageReference Include="MetadataExtractor" Version="2.1.0" />
   </ItemGroup>
   ```

4. The Dependencies node now looks like:

   ![image](https://user-images.githubusercontent.com/350947/59825209-c01c1280-9376-11e9-9c77-ca71076dc656.png)

**Expected Behavior**:

Don't mislead the user into thinking that a package is used in all TFMs. We should show an empty ".NETCoreApp 3.0" node in the first screenshot and dock those children under ".NETCoreApp 2.0".

**Actual Behavior**:

See screenshot.

**User Impact**:

User can be misled.

**Comment by drewnoakes** [comment]
There are things going on here.

1. We are removing TFMs when they have no dependencies, even if they're specified in the project.
2. The MSBuild SDK only appears under .NETCoreApp 3.0 when multi-targeting.

**Comment by drewnoakes** [comment]
Another way of triggering this is:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.1;netcoreapp3.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Condition="$(TargetFramework) == 'netcoreapp2.1'" Include="MetadataExtractor" Version="2.1.0" />
  </ItemGroup>
</Project>
```

This gives a tree resembling:

![image](https://user-images.githubusercontent.com/350947/59825530-9a433d80-9377-11e9-9010-0e7a35bd87ea.png)

You could therefore assume you have that package in all project configurations, which is not the case.

Now that the SDK 3.0.100 omits the MSBuild SDK item, I suspect the above bug will become more prevalent.

**Comment by davkean** [comment]
Yeah that's weird.
