### ISSUE TITLE
[Question/Proposal] API to interact with WPF ClickOnce

### ISSUE THREAD

**Issue by shaggygi** [dotnet/project-system#494]
I have not looked into the details, so this capability might already be provided.  However, a quick search didn't provide any good results.

It would be nice to have an API to work with ClickOnce and publishing for better automation scenarios.  For example...

1.) I want to be able to query all DLLs that are included in the Application Files section to see what state is currently selected (e.g. Include Auto, Include, Prerequisite, Exclude, etc.).

2.) I want the ability to change/save items in item 1 to a specific value.  This would be a good method to verify they are a certain value before deploying.  We get the "Not found in GAC" sometimes after deploying.

3.) I want the ability to automate the ClickOnce deployment outside of using the Properties GUI.

4.) In addition to item 3, it would be nice to have methods to update the Assembly and Publish versions (and parameters), compile and check analyzers before performing the publish.  Understanding this is more for Roslyn and MSBuild, but possibly good steps before performing the publish.

Thanks

**Comment by shaggygi** [comment]
Referencing... https://github.com/Microsoft/msix-packaging
Not sure if it is related and eventually replacing ClickOnce, but sounds like.

**Comment by davkean** [comment]
ClickOnce is deprecated and is not being brought forward. We do not have any public APIs for consuming this, other than what is provided via https://docs.microsoft.com/en-us/dotnet/api/vslangproj80.projectproperties3?view=visualstudiosdk-2017. Going to close this out as this will never bubble up to be a priority.
