### ISSUE TITLE
Data Source Configuration Wizard is not responding when adding new data source to an sdk-style project

### ISSUE THREAD

**Issue by cartermp** [dotnet/project-system#4941]
From here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/934160

1. Create a WPF(.NET Core) project.

2. Add new Data Source following below:

 

In Data Sources window, click 'Add New Data Source' -->Choose 'Database'->Next ->Choose 'Dataset'->Next ->click 'New Connection…'->Choose 'Microsoft SQL Server'->Continue

 

       a. Data Source: Microsoft SQL Server

       b. Server name: SERVERMACHINE

       c. Authentication: SQL Server Authentication

       d. User name: Sa

       e. Password: Password

       f. Database name: Sacket

3. Choose 'YES'->Next->Next->Chosse 'Tables'->Finish

**Expect:**

Data Source 'SacketDataSet' can be added successfully.

**Actual:**

Data Source Configuration Wizard is not responding after clicking 'Finish'.

![image](https://user-images.githubusercontent.com/6309070/59863569-cd66dc00-9339-11e9-8350-76641397538a.png)

**Comment by davidwengier** [comment]
Tried to look at this today.. blocked by this:
![image](https://user-images.githubusercontent.com/754264/61509324-4f2d5080-aa31-11e9-8945-02bb73d08c3e.png)

Hopefully I don't need to install SQL Server to repro :)

**Comment by davidwengier** [comment]
This is a JTF hang by the look of things. Will investigate when I get a volunteer to help :)

**Comment by davidwengier** [comment]
Bug in CPS, will move the internal bug.

**Comment by PharmaSoftVS** [comment]
His that bug corrected ?

**Comment by davkean** [comment]
This bug has been fixed. If you are still running into it and you are running the latest VS, please report a problem via Help -> Send Feedback -> Report a Problem.

**Comment by PharmaSoftVS** [comment]
It does not work with wpf netcore by myside
Do I miss something ?

**Comment by drewnoakes** [comment]
@PharmaSoftVS you are likely hitting a different issue. Please see https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019 for details on how to report an issue.
