### ISSUE TITLE
Project tree `DisplayOrder` commands broken in C# projects 

### ISSUE THREAD

**Issue by aodl** [dotnet/project-system#4948]
**Visual Studio Version**:

16.1.1 (VS 2019)

**Summary**:

C# projects with `SortByDisplayOrder` capability show 'Move up', 'Move down', 'Add before', and 'Add after' commands on project items, but these commands do not work. However they do work for F# projects (which I believe implicitly has `SortByDisplayOrder` capability).

**Steps to Reproduce**:

1. Create a new C# class library project

2. Add a couple of `.txt` project items

3. Edit the project file to declare the `SortByDisplayOrder` capability for the project.

4. Observe that right clicking on the project items shows 'Move up', 'Move down', 'Add before', and 'Add after' commands. Attempting to use these commands has no effect (the items are not moved, and new items do not respect the 'Add before' or 'Add after').

**Expected Behavior**:

The commands should move/insert the subject item with respect the sibling items.

**Actual Behavior**:

'Move up', 'Move down': The selected item is not moved

'Add before', 'Add after': Inserted items do not respect the before/after insert (they can appear after instead of before and vice versa)

**User Impact**:

Sad user :(

See https://github.com/dotnet/project-system/issues/1896#issuecomment-504281025

**Comment by aodl** [comment]
I've realised that the cause of this is [default 'None' items](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#default-compilation-includes-in-net-core-projects) in C# projects. If the item-includes come from an imported targets file, the reordering can't take place. I guess this makes sense. 

However it would be useful if there were some feedback to let the user know, instead of silently failing to move the item.

**Comment by aodl** [comment]
Or better yet the [CanMove](https://github.com/dotnet/project-system/blob/f28a7397ca13a57e08fb9db9e7dcbe35eb977c8b/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/MoveDownCommand.cs#L21) check (which I guess determines if the command is visible to the user) should perform [this check](https://github.com/dotnet/project-system/blob/ef109b2443b81dea285dc0e20526b46228da6059/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Input/Commands/Ordering/OrderingHelper.cs#L154) to ensure the item is declared in the .csproj file (rather than an imported targets file). Maybe there are performance consideration that I'm not taking into account here.

**Comment by davkean** [comment]
@drewnoakes Can you follow up with this based on the changes you made to this recently?

**Comment by drewnoakes** [comment]
@aodl do you want this behaviour across the whole tree or just in a root graft subtree?

Note that after #5736 you'll need to add capability `EditableDisplayOrder` in addition to `SortByDisplayOrder`.

**Comment by aodl** [comment]
Hi @drewnoakes. For my specific use case, I would only want to be able reorder nodes in a specific subtree (a custom tree of virtual nodes that sit below a file node), rather than across the whole project/workspace tree.

Thanks for the heads up about `EditableDisplayOrder`.

Can I ask about how wide reaching this edit/sort by display order feature is - will it only work for CPS based project systems, or any project system? Is it supported by Open Folder?

**Comment by drewnoakes** [comment]
If you are using a CPS root graft provider then, from 16.5 on the `ProjectTreeProviderBase` constructor has an additional `useDisplayOrdering` parameter which causes CPS to respect `IProjectTree2.DisplayOrder` just for that subtree, regardless of project capabilities.

If however you want to show custom nodes beneath a file, then I wonder if the `IAttachedCollection*` interfaces would be a better fit. It allows you to attach children to any node in the tree using `INotifyCollectionChanged` and `INotifyPropertyChanged`. Another perk of the `IAttachedCollection*` interfaces is that they're not tied to CPS so will work across all project systems. I believe they work with Open Folder too, though haven't tested it.

**Comment by aodl** [comment]
Cool, thanks for the suggestion. I came across that interface a while ago and switched away from relying on CPS. At the time though Open Folder seemed to ignore this interface, and instead has separate interfaces for extending Solution Explorer trees such as `INodeExtender`. The trouble is I can't see anything in the [base node type](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.workspace.vsintegration.ui.workspacevisualnodebase?view=visualstudiosdk-2017) that allows a display order to be specified. Would you know of a way around this or is it something I should raise with Open Folder directly?

**Comment by drewnoakes** [comment]
I'm not familiar with that base type. I think you'll need to speak with the a team on the platform side of things. A Developer Community feedback ticket is probably the best way forward, as those teams aren't on GitHub. They can advise about `IAttachedCollection*` support in the Open Folder scenario too.
