### ISSUE TITLE
All C# files get a default "(Project default editor)" that opens the WinForms designer

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#4950]
1. File -> New -. NET Core (Console App)
2. Right-click on Program.cs and choose Open With...

Expected: Similar to legacy, (Project Default Editor) doesn't show
Actual:

![image](https://user-images.githubusercontent.com/1103906/59909878-1317c780-9454-11e9-9016-0b8ad38a1719.png)

This looks like a regression when the WinForms stuff was added.

**Comment by davkean** [comment]
@lifengl Any thoughts on this?

**Comment by lifengl** [comment]
Not sure whether we did this intentionally to allow us to use the designer before the subType work is done. But I guess it is a small gap, and should be easy to fix.

Sent from my phone

On Jun 21, 2019, at 1:58 AM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flifengl&data=02%7C01%7C%7Cde885f0d0fdc44458d7908d6f626a8c3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636967043225018238&sdata=J3sRmOTxQo40J%2FhDAzWt20BtDd2brlKQrBJF%2Fa%2FK45o%3D&reserved=0> Any thoughts on this?

**Comment by davkean** [comment]
PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/213487?_a=overview

**Comment by davkean** [comment]
Fixed.
