### ISSUE TITLE
Add RuntimeIdentifierGraphPath to nomination

### ISSUE THREAD

**Issue by nkolev92** [dotnet/project-system#4951]
**Visual Studio Version**: 16.2

**Summary**:

Original ask [here](https://github.com/NuGet/Home/issues/7351). 

The SDK will provide the RuntimeIdentifierGraphPath, that NuGet will treat that as the project provided runtime identifier graph.
This will effectively replace the platforms package. 

cc @davkean 

**Steps to Reproduce**:
N/A

**Expected Behavior**:
N/A
**Actual Behavior**:
N/A
**User Impact**:
Affets .NET Core 3.0 customers.

**Comment by davkean** [comment]
This has been merged.
