### ISSUE TITLE
Shared Projects don't show in Dependencies node

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#4969]
**Visual Studio Version**:

d16.2stg

**Summary**:

This is presumably a regression, based on the screenshot in #2688, and indeed the regression could be caused by the fix for that, but Shared Projects don't show up at all in the Dependencies node. In this screenshot both console apps reference the shared project:
![image](https://user-images.githubusercontent.com/754264/60311116-2ae1d500-9999-11e9-85be-c7fb44ca0cb4.png)

**Steps to Reproduce**:

1. Create a Console App
3. Add a Shared Project to the solution
4. Reference the shared project from the console app

**Expected Behavior**:

Dependencies node should show dependencies

**Actual Behavior**:

Dependencies node is empty

**Comment by drewnoakes** [comment]
I can't repro this on 16.2.0-pre.4.0+29029.12.d16.2stg with 3.0.100-preview6 SDK installed and enabled.

![image](https://user-images.githubusercontent.com/350947/60569765-71796a00-9db3-11e9-9284-9a34d19dbce1.png)

## Console app

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <Import Project="..\SharedProject\SharedProject.projitems" Label="Shared" />

</Project>
```

## SharedProject.projitems

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <HasSharedItems>true</HasSharedItems>
    <SharedGUID>f350ab0a-9b83-4f01-9ec7-3936ccafe73c</SharedGUID>
  </PropertyGroup>
  <PropertyGroup Label="Configuration">
    <Import_RootNamespace>SharedProject</Import_RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)Class1.cs" />
  </ItemGroup>
</Project>
```

@davidwengier could you try and repro it, and if you can, send me a zip of your solution and exact versions of the bits you're using?

**Comment by davidwengier** [comment]
All of my stuff is newer than that. Running 16.2.0-pre.4.0+29101.197.d16.2stg with 3.0.100-preview7-012601 .NET Core SDK.

I suspect the SDK is the real problem here, as I don't see anything under Dependencies at all, even for just a plain console app. Maybe preview 7 is too new?

**Comment by davidwengier** [comment]
Now on 16.3.0-pre.2.0+29109.117.master and 3.0.100-preview7-012802, this no longer repros. I can finally see the Frameworks node too which is exciting, my Dependencies node has been too lonely for too long!
