### ISSUE TITLE
Shared project template should have use of MSBuildAllProjects updated

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4988]
With MSBuild 16.0+, imports no longer need to update the `MSBuildAllProjects` property (https://github.com/Microsoft/msbuild/issues/1299).

Currently a `.projitems` file contains something like:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <HasSharedItems>true</HasSharedItems>
    <SharedGUID>f350ab0a-9b83-4f01-9ec7-3936ccafe73c</SharedGUID>
  </PropertyGroup>
  <PropertyGroup Label="Configuration">
    <Import_RootNamespace>SharedProject</Import_RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)Class1.cs" />
  </ItemGroup>
</Project>
```

The construct should be updated to resemble:

```xml
    <MSBuildAllProjects Condition="'$(MSBuildVersion)' == '' Or '$(MSBuildVersion)' &lt; '16.0'">$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
```

If we can be sure that the project will only be used with MSBuild 16, the property can be removed altogether. I think it would be safer to use the above condition however.

**Comment by davkean** [comment]
Triage: We should make this change to all Shared Project templates under /src/vsproject/Templates/ in the VS tree.

**Comment by drewnoakes** [comment]
@melytc this issue is actually related in a way to the up-to-date check. Let's discuss tomorrow.

**Comment by drewnoakes** [comment]
@melytc if you haven't already, please get the VS code on your machine and run `init.cmd`. This can take a few hours, so better to start it early.

**Comment by melytc** [comment]
This is being solved in [this PR](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/224217) in AzDO.
