### ISSUE TITLE
Unresolved package prevents fixing other unresolved package

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#4992]
Having any unresolved package reference in a project prevents changes to other packages from working correctly.

### Scenario 1 &mdash; Fix an invalid package ref while another unresolved

1. Add two invalid packages:

    ```xml
    <PackageReference Include="MetadataExtractor" Version="2.1.0-badversion" />
    <PackageReference Include="System.Missing" Version="99.99.99" />
    ```
    
2. Fix one of them:

    ```xml
    <PackageReference Include="MetadataExtractor" Version="2.1.0" />
    <PackageReference Include="System.Missing" Version="99.99.99" />
    ```

3. The fixed package resolve, but doesn't.

---

### Scenario 2 &mdash; Add valid package ref while another is unresolved

1. Add one invalid package:

    ```xml
    <PackageReference Include="System.Missing" Version="99.99.99" />
    ```
    
2. Add a valid package:

    ```xml
    <PackageReference Include="MetadataExtractor" Version="2.1.0" />
    <PackageReference Include="System.Missing" Version="99.99.99" />
    ```

3. The added package should resolve, but doesn't.

---

At the end of both scenarios the Dependencies node shows:

![image](https://user-images.githubusercontent.com/350947/60631986-f0b77e00-9e45-11e9-8070-dd2b006e312d.png)

The output window shows: 

> NuGet package restore failed. Please see Error List window for detailed warnings and errors.

And the error list shows:

> NU1101 Unable to find package System.Missing.

The design time build of both fail due to NU1101:

![image](https://user-images.githubusercontent.com/350947/60632431-ddf27880-9e48-11e9-9db1-371beaa0e03d.png)

The design time build was aiming to run the following tasks, but stopped at the first error:

- CollectResolvedSDKReferencesDesignTime
- CollectPackageReferences
- ResolveComReferencesDesignTime
- ResolveProjectReferencesDesignTime
- BuiltProjectOutputGroup
- CollectFrameworkReferences
- CollectUpToDateCheckBuiltDesignTime
- CollectPackageDownloads
- ResolveAssemblyReferencesDesignTime
- CollectAnalyzersDesignTime
- CollectSDKReferencesDesignTime
- CollectUpToDateCheckInputDesignTime
- CollectUpToDateCheckOutputDesignTime
- ResolvePackageDependenciesDesignTime
- CompileDesignTime
- CollectResolvedCompilationReferencesDesignTime

**Comment by drewnoakes** [comment]
This occurs because the dependencies node considers its items as 'unresolved' until they're observed via a design time build.

The experience could be improved by adding an 'unknown' state that occurs while waiting for a design time build. In the above scenarios, both the fixed and added package references would transition to the 'unknown' state, making it clearer which package has the actual problem.

**Comment by davkean** [comment]
@drewnoakes Design-time builds are meant to be run with ContinueOnError set to true, which these targets are supposed to respect. Can you check that?

**Comment by drewnoakes** [comment]
@davkean I'll have a look. I think https://github.com/dotnet/project-system/issues/3780#issuecomment-508084332 is related.

**Comment by drewnoakes** [comment]
With https://github.com/dotnet/sdk/pull/3399 the DTB completes successfully and the above bug no longer reproduces.

**Comment by drewnoakes** [comment]
Fixed in https://github.com/dotnet/sdk/pull/3399.
