### ISSUE TITLE
csproj files do not end with a newline character

### ISSUE THREAD

**Issue by aaronfranke** [dotnet/project-system#4993]
I apologize if this is the wrong repository for this, if so please point me elsewhere.

**Summary**: I have noticed that in most C# projects, `csproj` files do not contain a newline character at the end of the file.

This is bad behavior because it does not follow the POSIX specification for text files. Lines contained in text files end with a newline character, therefore, any text at the end of the file which is not followed by a newline character is not a real part of the text file and can produce incorrect behavior. For example, using `cat` on the file will end up with the next prompt appended to the last (non-spec) line of the file.

Also, many modern tools, including GitHub, will show a warning for any files which do not have a newline at the end of the file. Other languages enforce this further - GCC is not allowed to work with such files as part of its spec ([source](http://c0x.coding-guidelines.com/5.1.1.2.html)).

Since C# is multi-platform and Windows also has WSL, it should logically try to follow POSIX specs whenever it can. My proposed solution is to make ending with a newline a part of the csproj spec, and updating all tools that work with and generate csproj files, to enforce this.

**Expected Behavior**: All csproj files are required to contain newlines.

**Actual Behavior**: csproj files are generated without newlines.

**User Impact**: Impacts most or all C# projects ever created, but users are unlikely to notice actual problems or failures, just warnings or slightly incorrect behavior with many tools.

Over a thousand votes on [this SO question](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/729795), see also [this](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file).

It should also be relatively easy to fix, it just needs to be done. This may also apply to other similar file types, such as fsproj, but I do not use F#.

**Comment by davkean** [comment]
@aaronfranke Thanks for the filing the bug.

For projects using the legacy project system by default and run primary on Windows (.NET Framework, UWP), the templates themselves are missing a newline and VS will remove any trailing new line when saving.

For projects using the new project-system (contained in this respository) and run cross platform (.NET Core), the templates end with a new line, and VS will respect it if is present and not remove it.

Starting in 16.0, we're investing all our efforts into adding features to the new project-system (https://github.com/dotnet/project-system/blob/master/docs/feature-comparison.md) and have reduced our investment in the legacy project system and hence won't be going back to fix it. The intention is that the new project-system will support all the features of the legacy project system and replace it, so over time this will become less and less of a problem.
