### ISSUE TITLE
Class item template instantiates with no namespace

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5007]
**Visual Studio Version**: 16.2.0-pre.4.0+29104.9.d16.2

**Summary**:

Class item template instantiates with no namespace.

**Steps to Reproduce**:

1. Run the project system at master (16702928b28ed5704efdaae06811c52c6496f5bc)

2. Create a new .NET Core Console App

3. Right-click project, Add, Class...

4. Click _Add_

5. Class appears with no namespace:

```c#
using System;
using System.Collections.Generic;
using System.Text;

namespace
{
    class Class1
    {
    }
}
```

**Comment by davkean** [comment]
@jmarolf Can you investigate?

**Comment by jmarolf** [comment]
@drewnoakes 	what .NET Core SDKs do you have installed?

**Comment by jmarolf** [comment]
Still looking into this but it looks like we no longer return the project system is not longer returning the default namespace

**Comment by davkean** [comment]
We probably control that in our rules, which ahve

**Comment by davkean** [comment]
This was regressed https://github.com/dotnet/project-system/pull/5000, @drewnoakes is going to revert.
