### ISSUE TITLE
Warning on .NET Core dependencies after changing to 2.1/2.2 and back

### ISSUE THREAD

**Issue by vsccarl** [dotnet/project-system#5012]
**Visual Studio Version**:
d16.3
**Summary**:
The dependencies node in Solution Explorer is not showing any dependencies dropdown for .NET Core projects. It also shows a warning symbol after changing the target framework from .NET Core 3.0 to 2.1/2.2 frameworks. After changing back to 3.0 the warning symbol remains.

**Steps to Reproduce**:

1. Create a .NET Core Console App.

2. Open the project properties page

3. Change target framework to 2.1 or 2.2 and save.

4. Observe that a warning symbol has shown up on the dependencies section of solution explorer.

5. Change back to 3.0 and observe the warning symbol has not been removed.

**Expected Behavior**:
Warning symbol is removed after changing back.

**Actual Behavior**:
Warning symbol remains.

**User Impact**:
Unnecessary warnings on project dependencies.

**Comment by etbyrd** [comment]
This doesn't seem to reliably repro in any one distinct pattern. Also, it seems like after changing the TFM several times the bug is less likely to appear.

**Comment by drewnoakes** [comment]
Changes from PRs #4928, #4980 and #4981 did not make it into 16.3p1. They have now been merged to the [`dev16.3.x`](https://github.com/dotnet/project-system/tree/dev16.3.x) branch in #5014.

Testing that branch:

- In `16.1.6+29102.190` and `16.2.0-pre.3.0+29021.104` there is no yellow triangle and the dependencies node updates correctly as you change between TFMs
- In `16.3.0-pre.1.0+29109.77.d16.3` there is no yellow triangle after changing the target framework to `netcoreapp2.1` (fixed as part of #4980), however the dependencies node becomes empty and does not recover, which I haven't observed before.

I'm investigating the issue now. Note that it's the same project-system code running in 16.2p3 and 16.3p1, yet only the latter exhibits this problem.

**Comment by drewnoakes** [comment]
Turns out we need #4985 in the `dev16.3.x` branch. I've submitted #5020 as a fix.

I also found a potential NRE in `dev16.3.x` (which has been fixed in `master`) which is fixed in #5021.

@jmarolf @jjmew

**Comment by jmarolf** [comment]
Thanks @drewnoakes 	! I've gone ahead and merged these after pulling them down and testing them

**Comment by drewnoakes** [comment]
Thanks @jmarolf! It was good to wake up to nothing being on fire.
