### ISSUE TITLE
Provide feedback that dependencies node is populating

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5045]
### Current behaviour

When the dependencies node first populates, it does not yet have enough information to show nested child items. For example, you're unable to expand a package to see its children until that package has restored and resolved.

Currently (until #5044 is solved) the yellow triangle has indicated that the dependency is unresolved. However this triangle suggests there is a problem, rather than the user just needs to wait in order to interact with the nodes.

### Proposed behaviour

When #5044 is completed (it should be completed before this issue) the only indication that a node is populated with data for interaction will be the appearance of the ▷ mark to its left, indicating its tree node can be expanded. Before then, no mark is present.

The proposed behaviour allows dependency tree items to always be expandable (always have the ▷ mark). If they are not yet ready to display their actual contents, a single child item would appear with text "Loading...". Once the backing data is ready, that child would be replaced with the relevant data.

**Comment by drewnoakes** [comment]
Another proposal is to show nodes with "(resolving)" suffix, without the ability to expand until resolution completes.

**Comment by davkean** [comment]
I like the first proposal 👍
