### ISSUE TITLE
Profile is never populated for a FrameworkReference

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5055]
Both WinForms/WPF never show anything for a "Profile".

![image](https://user-images.githubusercontent.com/1103906/61256950-3ebb7280-a7b2-11e9-945b-1350b5690eb4.png)

**Comment by davkean** [comment]
tag @drewnoakes

**Comment by drewnoakes** [comment]
This is dummy data, along with `c:\some\path`. I've been tracking this in #4762 and will be fixed when the temporary code is removed.
