### ISSUE TITLE
Improve DTEUtils.GetProjectProperty

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5060]
> From https://github.com/dotnet/project-system/pull/5057#discussion_r303747450:
>
> This method is pretty inefficient, it walks every property, when it can just use the string indexer of the Properties instance.

**Comment by davkean** [comment]
Bear in mind that the indexer (I think) will throw ArgumentException if the property doesn't exist.

**Comment by davkean** [comment]
Triage: This will never bubble up as important to fix.
