### ISSUE TITLE
Verify FrameworkReference browse object

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5070]
- [x] Remove temporary code from `ResolveFrameworkReferencesDesignTime`:
https://github.com/dotnet/project-system/blob/075e8dd0ca5bb45b6a692e8c5aaff6c582fab80e/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L386-L404
- [x] Test with updated SDK/MSBuild that data is displaying correctly
- [ ] Review properties/rules
  - [ ] Should `PrivateAssets` be set by the SDK, or should it be removed from the rule files in the project system? (PR #5230)
  - [x] Should `Profile` be populated?

**Comment by drewnoakes** [comment]
@dsplaisted @davkean the only pending item here is:

> Should `PrivateAssets` be set by the SDK, or should it be removed from the rule files in the project system?

I don't have enough context to know the answer to this. Currently we show an editable "Private Assets" property in the properties window. Though every value I try to set in it results in:

> An error has occurred while saving the edited properties listed below:
>> 	Private Assets
>
> One or more values are invalid. 
> Specified method is not supported. 

Do you have an opinion on this? Is "Private Assets" required for framework references?

**Comment by davidwengier** [comment]
In general the "Private Assets" experience in the Properties window is not good. See #4281

**Comment by drewnoakes** [comment]
Thanks. Actually I think I've found a fix. Investigating. If it works I'll see about fixing package references too.

**Comment by drewnoakes** [comment]
@dsplaisted is it even valid for an end user to specify Private Assets on a framework reference? Should this property be removed?

**Comment by davkean** [comment]
It's valid and its set by the SDK in some cases.

**Comment by dsplaisted** [comment]
It is "valid" to set PrivateAssets on a FrameworkReference, but I consider it an implementation detail and don't think there's value in showing it or allowing it to be edited in VS.

There may be scenarios where it would make sense for a user to set it, but the fact is we didn't consider or design for those scenarios when we added the support.  It's only an accident of the fact that everything is public and there's no encapsulation in MSBuild that it's possible to set it specifically.  So I don't think we should be promoting something like that to the UI in Visual Studio.

**Comment by davkean** [comment]
How do indicate a dependency on FrameworkReference without getting the APIs?

**Comment by dsplaisted** [comment]
> How do indicate a dependency on FrameworkReference without getting the APIs?

There isn't a way to do this today.  https://github.com/dotnet/designs/pull/81 proposes supported `IncludeReferences="False"` as metadata which would do this (and then you could reference individual assemblies with a `Reference` item).

PrivateAssets doesn't do this, FWIW.  `PrivateAssets="All"` won't affect your project directly, it will affect consumers of your project.

**Comment by davkean** [comment]
Ah, sorry was thinking `ExcludeAsset`, so you would use PrivateAssets to hide references from downstream consumers, right? Imagine you have a layer that can depend on WPF but don't want downstream consumers to have dependency on WPF - you can use it in that case?

**Comment by dsplaisted** [comment]
In that case, if the WPF dependency doesn't flow to the consumer, and the consumer doesn't otherwise depend on WPF, then it will get a runtime exception failing to load WPF if it tries to run any of your code that calls into WPF.  The app's runtimeconfig.json needs to refer to the WPF shared framework in order for it to load WPF assemblies at all.

Ideally you would be able to control whether the compilation references flowed to your consumers, while the fact that you depend on the framework at runtime still flows.  This is discussed a bit in the last section of the proposal ("NuGet and transitivity").

**Comment by davkean** [comment]
I would have imagined that's what `PrivateAssets="Compile"` would do - is that not the case?

**Comment by dsplaisted** [comment]
`PrivateAssets="All"` is the only thing we support on `FrameworkReference`.  `PrivateAssets="Compile"` could be a good way to express that compile assets shouldn't flow.

**Comment by davkean** [comment]
Okay, I agree, pull `PrivateAssets` until we have the full support here.

**Comment by drewnoakes** [comment]
Removed in #5230.
