### ISSUE TITLE
Changing AssemblyName prevent app from starting

### ISSUE THREAD

**Issue by nguerrera** [dotnet/project-system#5090]
_From @LokiMidgard on December 18, 2018 11:5_

I've created a project and want to rename the created Assembly.
OutputType: `WinExe`  
TargetFramework: `netcoreapp3.0`  
UseWPF: `true`

OS: `Windows 10`  
dotnet core `3.0.100-preview-009812`

After renaming it I can no longer start the exe or debug it in Visual Studio.
Following error appears when I try to start debugging:
```
Das Programm "[17104] DiceTool.exe" wurde mit Code -2147450741 (0x8000808b) beendet.
Das Programm "[17104] DiceTool.exe: Programmablaufverfolgung" wurde mit Code 0 (0x0) beendet.
```
I try to set `<AssemblyName>DiceTool.Ui</AssemblyName>` to `<AssemblyName>DiceTool</AssemblyName>`.

Reverting this change will fix the issue.

The code to reproduce this is in [this Commit](https://github.com/LokiMidgard/Dice-Tool/tree/512a397c8c09de7be3a2c1b106c9a7457fc5c305)

_Copied from original issue: dotnet/core#2163_

**Comment by etbyrd** [comment]
I can't seem to repro this on 16.1.6 with your steps. I can't think of anything else that would be different. Hm.

**Comment by drewnoakes** [comment]
No longer reproduces in Version 16.5.0 Preview 2.0 [29608.6.master]. May be related to project file editing bugs that have since been fixed.
