### ISSUE TITLE
Consider enabling project-wide properties vary per configuration

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#51]
_From @davkean on April 29, 2016 21:39_

(Filed on behalf of a customer)

Today in csproj/msvbprj, target framework, assembly name, etc are all project-wide properties - something that's not expected vary based on configuration. In the rewrite, we should making effectively all properties configuration-based

_Copied from original issue: dotnet/roslyn#10991_

**Comment by kvenkatrajan** [comment]
Closing ticket - Vary by configuration is available in sdk style projects : https://devblogs.microsoft.com/visualstudio/revamped-project-properties-ui/#conditional-configuration-improvements
