### ISSUE TITLE
Undoing a Roslyn rename prompts a rename

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5139]
**Steps to Reproduce**:

1. File -> New -> Console App (.NET Core)
2. Press F2 to rename Program -> NotProgram

-- observe that Program.cs has been renamed to NotProgram.cs --

3.  In same editor, CTRL+Z to undo rename

**Expected Behavior**:
No prompt to rename

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1103906/61709604-f217fe80-ad92-11e9-9be4-5dd2ff255a88.png)

**User Impact**:

**Comment by davkean** [comment]
/cc @jmarolf @ryzngard 

Looks like both your bits arrived in master, and the above is the result.

**Comment by jmarolf** [comment]
@davkean 	I cannot reproduce this with the repro steps provided.  Is there anything else that you did other than what you've suggested?

**Comment by davkean** [comment]
Here's a video:

![cfbce04d-3bcf-41e8-a504-084f6f04949d](https://user-images.githubusercontent.com/475144/66791109-a1063b00-eea7-11e9-974e-7b27cbb06561.gif)

**Comment by davkean** [comment]
This is going to because we conflating "renames" via dataflow with user actions.

**Comment by jmarolf** [comment]
@davkean 	I cannot reliably repo this today, can you provide consistent repro steps on a build we've release?

**Comment by davkean** [comment]
I mentioned early on in the rewrite that we shouldn't be using dataflow renames as an indication that the user renamed the type, any use of ProjectItem.Rename will result in this.

**Comment by jmarolf** [comment]
I think I see where I mis-understood @davkean 	when you saith this:

> Press F2 to rename Program -> NotProgram

I thought you mean't F2 in the solution explorer, I assume you actually meant F2 on the class definition, which I can repro

**Comment by jmarolf** [comment]
yeah, well need to re-write everything again...

**Comment by ocallesp** [comment]
@davkean  I will investigate this issue.
This issue is related to https://youtrack.jetbrains.com/issue/RSRP-476479 
e-mail thread with subject [EXTERNAL] Bogus 'You are renaming a file...`

**Comment by ocallesp** [comment]
@jmarolf  @davkean I cannot repro this issue using the steps in the description. Is there any missing step ?

**Comment by davkean** [comment]
@ocallesp The "Rename File" code fix isn't showing up for me anymore, can you see it? Regardless, this will still occur when any component (such as R#) uses APIs to rename files.

**Comment by ryzngard** [comment]
This is currently blocking us from enabling this on the Roslyn side, so it shouldn't show up for CPS projects.

**Comment by davkean** [comment]
Did you remove the code fix? It was enabled at one point.

**Comment by ryzngard** [comment]
It hasn't been enabled for a long time as far as I'm aware. The PR is here https://github.com/dotnet/roslyn/pull/39225
