### ISSUE TITLE
Upgrade RoslynToolset to latest version

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5176]
We need to update to 1.0.0-beta3-19362.3 which includes https://github.com/dotnet/roslyn-tools/pull/528. Currently blocked because I can't find a package with that version.

**Comment by jmarolf** [comment]
The version with @tmeschter's changes was built [here](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2847362)

**Comment by davkean** [comment]
Do you know how to get dotnet.myget credentials?

**Comment by jmarolf** [comment]
You should be able to log into myget with your microsoft account

this is the package with those changes: https://dotnet.myget.org/feed/roslyn-tools/package/nuget/RoslynTools.RepoToolset/1.0.0-beta3.19362.3+71a08fcf

**Comment by davkean** [comment]
Can't log in with Microsoft credentials - they have their own AD for .NET Foundation.

**Comment by davkean** [comment]
Or if you can, it's not obvious how to do that.

**Comment by jmarolf** [comment]
Does updating to `1.0.0-beta3.19362.3` not work? What do you need to see on myget?

**Comment by davkean** [comment]
I haven't tried yet - the version number was wrong, but I still want to be able to log onto myget so that I can upload other packages.

**Comment by davkean** [comment]
We're not going to do this, it's a non-trivial work item to move to the new version of it as its completely changed. Instead we just grabbed the sign.proj: https://github.com/dotnet/project-system/pull/5303.
