### ISSUE TITLE
Cannot set collapsed project icon using IProjectTreePropertiesProvider

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5183]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/597813/icon-property-in-iprojecttreepropertiesprovider-is.html). Please vote and comment there to make sure your voice is heard._

---
When setting the icon of the project tree using `IProjectTreePropertiesProvider` the `Icon` property doesn't change the icon that is showned. It's always the default C# proect.

Here's the code I'm using:

```c#
[Export(typeof(IProjectTreePropertiesProvider))]
[AppliesTo(NanoCSharpProjectUnconfigured.UniqueCapability)]
internal class ProjectTreePropertiesProvider : IProjectTreePropertiesProvider
{
    /// <summary>
    /// Calculates new property values for each node in the project tree.
    /// </summary>
    /// <param name="propertyContext">Context information that can be used for the calculation.</param>
    /// <param name="propertyValues">Values calculated so far for the current node by lower priority tree properties providers.</param>
    public void CalculatePropertyValues(
        IProjectTreeCustomizablePropertyContext propertyContext,
        IProjectTreeCustomizablePropertyValues propertyValues)
    {
        // set the icon for the root project node
        if (propertyValues.Flags.Contains(ProjectTreeFlags.Common.ProjectRoot))
        {
            propertyValues.Icon = KnownMonikers.AbstractCube.ToProjectSystemType(); ;// NanoFrameworkMonikers.NanoFrameworkProject.ToProjectSystemType();
            propertyValues.ExpandedIcon = NanoFrameworkMonikers.NanoFrameworkProject.ToProjectSystemType();
        }
    }
}
```

To rule out any issues with the icon format on my resources, I've momentarily replaced it with one of VS stock icons, as can be seen from the above. The result is the same.

The `ExpandedIcon` property does work.

Attaching screenshots of a project tree expanded and colapsed for illustration.

Worth noting that this happens in both VS2017 and VS2019.

---

#### Visual Studio Feedback System (6/10/2019, 04:18 PM)

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### José Simões (7/17/2019, 06:09 PM)

<p>Hi,</p><p>Any update on this?</p>

**Comment by drewnoakes** [comment]
Tagging @josesimoes.

**Comment by drewnoakes** [comment]
@josesimoes thank you for your feedback! If this code is pushed to nanoFramework on GitHub, can you point me at it so I can run some local tests?

In the mean time you may like to try applying an `[Order(...)]` attribute to your export and experimenting with different numbers (eg. `int.MinValue` and `int.MaxValue` to see if it has any effect).

**Comment by davkean** [comment]
This properties provider needs to be a higher priority than ours: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectRootImageProjectTreePropertiesProvider.cs#L14. By default CPS uses 0 priority, we use 10. Marking it higher than that would have it have higher priority. Make sure you do not use int.MaxValue as that would prevent others from overridding you.

**Comment by drewnoakes** [comment]
I haven't looked at the code yet but I was surprised that José's code set the expanded icon but not the collapsed one.

**Comment by davkean** [comment]
We don't set the ExpandedIcon, so it just pulls from Icon. When that code above sets ExpandedIcon it becomes the only provider to do that and wins.

**Comment by drewnoakes** [comment]
@josesimoes please let us know if `Order` attribute solves the problem.

**Comment by josesimoes** [comment]
Adding the `Order` attribute did fix it!
I've totally missed it on the initial look at the documentation that you pointed above.

Looking at it again, may I suggest that the comment there about `Order` is improved? It probably shouldn't pass the impression that one shouldn't mind about this attributer, instead has to use it in order to make sure that CPS defaults are effectively overridden.

**Comment by drewnoakes** [comment]
Glad to hear you got it working. I agree the comment is confusing. Take a look at https://github.com/microsoft/VSProjectSystem/pull/327 and see if you find it an improvement.

Thanks again for your feedback and helping to improve the project system!
