### ISSUE TITLE
Prevent NuGet assemblies from beeing copied

### ISSUE THREAD

**Issue by lukashankeln** [dotnet/project-system#5189]
**Visual Studio Version**:
16.1.16
**Summary**:
NuGet Packages get copied to OutputPath. We always separated our third party components and our own Assemblys and Resolved them via an Assembly Resolver, but if we add Nuget Packages they get copied to the OutputPath next to our own Assemblies. We would like to have a property to change the outputpath where the NuGet-Assemblies are copied, or have an option to prevent it from copying at all. When we use multiple NuGet-Packages with different Versions they get overriden.

**Steps to Reproduce**:

1.  Create a new project which uses the Sdk Projectformat

2. Change the OutputPath and add a NuGet Package

3.  Build the Project
 
**User Impact**:
We can't use NuGet packages at the moment. It would be much easier to have NuGet support for our project

**Comment by davkean** [comment]
Interesting requirement, there's quick a few ways to address this. 

There's a couple of ways to turn off deployment:

1) Turn off runtime assets per package:

``` XML
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" ExcludeAssets="runtime" />
  </ItemGroup>
```

2) Turn of runtime assets for all packages:

``` XML
  <ItemDefinitionGroup>
    <PackageReference ExcludeAssets="runtime" />
  </ItemDefinitionGroup>
```

Once you have that, you can then have a CopyNuGetDependencies project with a different output path. Make sure it reference to all NuGet packages - but without `ExcludeAssets`. It's soley responsable for copying NuGet packages to the output directly. 

You can generalize this to reduce the amount of copying of package references by:

- Put the package references (for example `<PackageReference Include="Newtonsoft.Json" Version="12.0.1`) in a [Directory.Build.props](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019) that is imported by all projects.
- Put `<ItemDefinitionGroup` in a targets file that is is imported by all projects except the Copy project.
- Profit!

That should cause all projects to stop copying to their output directly and the Copy project will copy to its special output folder.

**Comment by lukashankeln** [comment]
Thanks a lot! `ExcludeAssets` works perfectly.

**Comment by lukashankeln** [comment]
I reopen this because I just realized that on first sight it seems to work right but there is still a problem.

If I have two projects referencing FParsec version 1.0.3 and FSharp.Core version 4.6.2 and add them into one it will look like this 
```
<ItemGroup>
    <PackageReference Include="FParsec" Version="1.0.3" />
    <PackageReference Include="FSharp.Core" Version="4.6.2" />
  </ItemGroup>
```
The point is that FParsec has an dependency to FSharp.Core but its using 4.4.1 and not 4.6.2.

If I now compile this project the version of FSharp.Core on which FParsec depends will be overridden.

This seems to be no problem because FSharp.Core 4.6.2 and 4.4.1 are binary compatible but there is a breaking change which will leave us with an runtime error (Methode not Found Exception).

So I somehow have to separate the packages in a folder-structure. 

Thank's for your help.

**Comment by davkean** [comment]
@lukashankeln I don't know of a way to resolve this problem. Please ask a question over on http://github.com/dotnet/nuget/home.
