### ISSUE TITLE
Summary in AzureDevOps builds should include warnings/errors

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5194]
Our AzureDevOps builds do not include errors/warnings in the summary making it extra steps to see the actual errors/warnings from a build. We should change that: https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md.

**Comment by MiYanni** [comment]
Warnings/errors currently show up in the DevOps pipelines for most tasks. They look like:

![image](https://user-images.githubusercontent.com/17788297/160718692-a0107d2c-9872-421d-a3c2-d1553306a3ea.png)

For our actual build of the product, we have 'treat warnings as errors' so the build will fail and show them appropriately as errors in that summary of the run. If we need to do more work here, I can re-open as needed.
