### ISSUE TITLE
Pull common steps into pipelines into templates

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5195]
We duplicate a bunch of steps in our pipelines (such as the publish steps). Please then out into a template and share them to all the YML files: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops.

**Comment by jmarolf** [comment]
👍 	to this idea!

**Comment by drewnoakes** [comment]
It looks like the biggest gain will come from templating steps. This will be easier to do if we have consistent folder structures and artifacts across builds.

**Comment by davkean** [comment]
I've done this for unit-tests: https://github.com/dotnet/project-system/pull/5312. Integration tests will automatically inherit this when we merge it and unit-tests.
