### ISSUE TITLE
MSBuildThisFileDirectory evaluated incorrectly in the IDE for NuGet targets

### ISSUE THREAD

**Issue by davidmatson** [dotnet/project-system#5214]
**Visual Studio Version**:
2019 (16.2.0)

**Summary**:
A NuGet package that uses a targets file with MSBuildThisFileDirectory gets evaluated incorrectly in the IDE - things that should only be applied to files inside the NuGet package are instead applied to the customer's project tree location.

**Steps to Reproduce**:

1. Install the NuGet package below.

2. Add a new class to the project.

3. Notice the item type.

**Expected Behavior**:
Item Type is Compile.

**Actual Behavior**:
Item Type is None:

**User Impact**:
Hard to create new source files; IntelliSense crashes.

Test.nuspec:
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>Test</id>
    <version>0.1.0</version>
    <authors>Test</authors>
    <description>Test</description>
  </metadata>
  <files>
    <file src="Test.targets" target="build" />
  </files>
</package>
```

Test.targets:
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)\**" Exclude="$(MSBuildThisFileDirectory)\**\*.targets">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="MyAfterBuild" AfterTargets="Build">
    <Message Importance="high" Text="MSBuildThisFileDirectory: $(MSBuildThisFileDirectory)" />
  </Target>
</Project>
```

Note that the message displayed during build shows the correct location for MSBuildThisFileDirectory, but the IDE adds items to the user's csproj forcing the items to type = None. (Manually removing these items from the csproj gets things working again.)

(A separate bug is that IntelliSense seems to get quite confused in certain cases when this behavior occurs.)

To prove that the Include filter is evaluating incorrectly in the IDE only, try changing it Test.targets as follows:
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)\**\BadClass.cs" Exclude="$(MSBuildThisFileDirectory)\**\*.targets">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="MyAfterBuild" AfterTargets="Build">
    <Message Importance="high" Text="MSBuildThisFileDirectory: $(MSBuildThisFileDirectory)" />
  </Target>
</Project>
```

And then add a new class named Class1.cs vs BadClass.cs and note the difference. My expectation is that MSBuildThisFileDirectory should always be interpreted as the same directory as the targets file itself (similarly to how $PSScriptRoot works in PowerShell), which gives a way for a NuGet targets file to refer only to files in its own package.

**Comment by davkean** [comment]
Thanks for the great repo, the bug isn't that MSBuildThisFileDirectory isn't set to the correct directory, it's that we're asking for all the glob patterns in the project and either MSBuild or underlying thing we're building on is confused and thinks the glob pattern covers the project directory.

If you remove any references to the newly added class in the project file, ie delete these lines:

``` XML
  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Class1.cs" />
  </ItemGroup>
```

Then it works as expected. 

This logic unfortunately lives outside of our repo, so I've opened an internal bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/957725. If you would like to track it, please Send Feedback -> Report a Problem and I'll dupe mine against the one you've filed.
