### ISSUE TITLE
Build log in CI it too verbose

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#5241]
I generally just want to know if a build failed because:

0. some random infra failure
1. restore failed
2. build failed
3. tests failed

And that just tells me where to start when I open the binlog. Any build failure that is going to take more than a few seconds to solve is going to be a binlog download anyways so the old format was better for me.

**Comment by jmarolf** [comment]
related to conversation from https://github.com/dotnet/project-system/pull/5233

**Comment by davkean** [comment]
@dotnet/project-system 

Undecided on this one. Errors are put at the end of the log if you want to find them, I find the new logging to be helpful and we can quickly resolve things with forcing to look at the binlog. Thoughts?

**Comment by davkean** [comment]
The other thing to note, is that binlog is only currently published on failure too.

**Comment by drewnoakes** [comment]
I'd suggest leaving the verbose logging for a while and seeing if it turns out to be helpful or annoying in practice.

**Comment by davkean** [comment]
I don't think we're going to change this at the moment, I've lived with this for a few months and its quite nice to be able to see the log without a build log.
