### ISSUE TITLE
Language service add/removing files when their sub type metadata changes

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5259]
In https://devdiv.visualstudio.com/DevDiv/_workitems/edit/961596, we found that we're [unnecessarily adding and removing](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs#L175) files from Roslyn when the sub type metadata changes. This causes a bunch of unnecessarily analysis to occur. We should change the above check to only occur when the `Link` metadata changes.

**Comment by drewnoakes** [comment]
Chase up the Roslyn bug related that causes subtype to change when changing configurations.
