### ISSUE TITLE
Use Azure Boards github integration

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#5263]
Relates to [AB#952802](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/952802)

**Comment by davkean** [comment]
@dmonroym: Was this completed?

**Comment by dmonroym** [comment]
Followed up today. Permissions were granted on December but seems people might've left for vacation.

**Comment by MiYanni** [comment]
Reviving this since I think it would be useful. See: https://docs.microsoft.com/en-us/azure/devops/boards/github/install-github-app?view=azure-devops

**Comment by tmeschter** [comment]
Need a better understanding of how this would help us and further team discussion.

**Comment by tmeschter** [comment]
On second thought nevermind.
