### ISSUE TITLE
Improve build time by reducing the number of things we copy to our build share

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#5265]
Relates to [AB#1087080](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1087080)

**Comment by davkean** [comment]
A couple of things:

1) How does the insertion tool pick up binaries? I think it might pick them from this drop share.
2) I find the drop share to be helpful, I just had to look through 30 builds before and the signed build does not currently produce artifacts containing the binaries. Even if it did, it would be very painful to look through them all as opposed ot file share.

**Comment by jmarolf** [comment]
>How does the insertion tool pick up binaries?

1. looks for an artifact that matches the build number and then downloads the file from \\cpvsbuild
2. looks for an artifact that matches VSSetup and then downloads that

If we no longer wanted to use cpvsbuild we would need to publish an artifact with the name `VSSetup` (using [PublishPipelineArtifact](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops)).

> I find the drop share to be helpful

I think we need to have a consistent story for how you access the output of a build.  Most devs who interact with CI are trained to look in the artifacts directory on AzDO. Only older folks (like me) would think to check \\cpvsbuid (we don't even give you a direct link to the folder from the build).

**Comment by davkean** [comment]
We can reduce the number of files we copy by avoiding copying IntegrationTests/UnitTests directories, this is half the files we are copying and they contain dlls that we don't ship.

**Comment by davkean** [comment]
It looks like we're using [Copy and Publish Build Artifacts Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-and-publish-build-artifacts?view=azure-devops), this is deprecated and appears to be replaced with [Publish Build Artifacts task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops). This task has the ability to copy to a build share and you can opt into parallel copy/CPU count which should help reduce time.

**Comment by davkean** [comment]
When we do this, we have to make sure that the [insertion](https://devdiv.visualstudio.com/DevDiv/_apps/hub/ms.vss-releaseManagement-web.cd-release-progress?_a=release-pipeline-progress&releaseId=407559) can still pick it up.
