### ISSUE TITLE
Update ComponentAreaPath.csv for our components

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5267]
We own Microsoft.VisualStudio.AppDesigner but its not reflected in [ComponentAreaPath.csv](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2FProductData%2FInternal%2FComponentAreaPath.csv&version=GBmaster)

At the same time, review and make sure the rest of our bits are correct.

**Comment by davidwengier** [comment]
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/196145

Can I do AR#196145 ?

**Comment by drewnoakes** [comment]
Isn't it AB#196145 ?

**Comment by drewnoakes** [comment]
Yep.

**Comment by davidwengier** [comment]
Yeah, thats *A*zure *B*oards, I was being cheeky and seeing if *A*zure *R*epos worked, even though I was pretty sure it didn't, but its Friday so ¯\\\_(ツ)_/¯

**Comment by davidwengier** [comment]
The PR has been merged.

Pity the kanban board automation doesn't work both ways.
