### ISSUE TITLE
Delay BeginBuild in host object until its needed

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5302]
To improve the perf of the new OOP host object we want to delay the call to BeginBuild until the host object is actually needed. At the moment BeginBuild is called very early on in the build, possibly even before the build starts, but there are few builds (0.9%) that actually need to use the host object, but all builds take the perf hit of the call (and the UI thread switch).

Internally in our host object shim we can work around this by waiting until a "real" use of the host object, to call BeginBuild.

/cc @lifengl

**Comment by lifengl** [comment]
Also, we need delay HostObject.Init as well.  This is called before BeginBuild.

**Comment by davidwengier** [comment]
Init is used by the native host object to subscribe to solution events, and those events determine if `IsRealBuild` returns true. We could find another way to set that for CPS, but legacy might be a different story. We could just delay the Init and BeginBuild calls in the CPS case though I guess.

**Comment by davidwengier** [comment]
Looks like we can delay Init in the CPS case, and BeginBuild in both legacy and CPS. Preliminary internal PR up, see link below, though I will still reviewing, just putting this up because it's Friday.

https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/197490
