### ISSUE TITLE
Memory leak: entire project leaked after openning/closing solution quickly

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#5315]
Memory leak: open Roslyn.sln and close it quickly, the entire solution memory leaked through this path:

```
->  121f9988 Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Snapshot.AggregateDependenciesSnapshotProvider
            ->  121f99a4 System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.ValueTuple`2[[Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Snapshot.IDependenciesSnapshotProvider, Microsoft.VisualStudio.ProjectSystem.Managed],[System.IDisposable, mscorlib]], mscorlib]]
            ->  208c0b54 System.Collections.Generic.Dictionary`2+Entry[[System.String, mscorlib],[System.ValueTuple`2[[Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Snapshot.IDependenciesSnapshotProvider, Microsoft.VisualStudio.ProjectSystem.Managed],[System.IDisposable, mscorlib]], mscorlib]][]
            ->  24f48674 Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Subscriptions.DependenciesSnapshotProvider
            ->  1169a224 Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectCommonServices
            ->  1167dd40 Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl
```

The leak appears to be a race condition.  A DependenciesSnapshotProvider registers itself to a global table in the constructor, but the clean-up logic was registered during the initialization code.  When I open Roslyn and close it quickly, the provider never has a chance to run the initialization code, and it leaks under that condition.

**Comment by lifengl** [comment]
@drewnoakes : I guess some dependencies refactoring might lead into this?

**Comment by drewnoakes** [comment]
@lifengl thanks for the report. Digging into `AggregateDependenciesSnapshotProvider` and `DependenciesSnapshotProvider` shows there are actually a few different races here around lifecycle.

> I guess some dependencies refactoring might lead into this?

These bugs predates my work on the dependencies node. It must be hard to trigger in the product, or we've just not seen it until now.

I'll get a fix in asap.
