### ISSUE TITLE
Content files not added to project (but copied to it)

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/project-system#5316]
**Visual Studio Version**: 16.2.2

**Summary**:
Check 
[OrmTest.csrpoj](https://github.com/dotnet/project-system/files/3511749/OrmTest.txt)
project file from this [issue](https://github.com/linq2db/linq2db/issues/1865). Installing package with content files doesn't work with it properly - files are copied to project folder, but not included into project itself.

I've tried to edit project file by replacing almost everything except project guid with content of new Windows Forms project, but it didn't helped (I suspect it already broke something in solution files at this point).

**Steps to Reproduce**:

1. Open attached project

2. Reinstall linq2db.PostgreSQL nuget package

**Expected Behavior**:
Content files appeared in project under `LinqToDB.Templates` folder

**Actual Behavior**:
Content files appeared in project folder, but not in project

**User Impact**:
Confusion and anxiety

**Comment by davkean** [comment]
Moved to NuGet: https://github.com/NuGet/Home/issues/9094.
