### ISSUE TITLE
Direct and transitive reference to project causes warning error on dependencies node

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5335]
Migrated from [AB#967428](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/967428).

**Visual Studio Version**: 15.9.15 onwards (possibly earlier)

**Summary**:

If a project references another project both directly and indirectly (transitively) then the direct project reference appears with a warning icon.

**Steps to Reproduce**:

1. Create three .NET Standard class library projects
2. Make `ClassLibrary1` reference `ClassLibrary2`
3. Make `ClassLibrary2` reference `ClassLibrary3`
4. Everything looks fine
5. Add a direct reference from `ClassLibrary1` to `ClassLibrary3` and save the project
6. That new dependency appears with a warning. The project builds without error.
  ![image](https://user-images.githubusercontent.com/350947/63391409-a8ecb600-c3f5-11e9-9031-d687af575c7c.png)

**Expected Behavior**:

No warning.

**Actual Behavior**:

Warning.

**User Impact**:

Confusion. Not a very likely scenario as the bug has existed for a long time and we've only just had it reported.

**Comment by jjmew** [comment]
@drewnoakes It might be good to have @ocallesp  help with this one

**Comment by ocallesp** [comment]
@drewnoakes do you know if the warning icon in the description is using https://github.com/dotnet/project-system/blob/master/resources/Overlay_Warning_16x.png   
?

**Comment by drewnoakes** [comment]
This should fall out of work I'm doing for #3435.

**Comment by drewnoakes** [comment]
This is a duplicate of #2510.
