### ISSUE TITLE
Console Apps (.NET Core) need icon differentiation between languages

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5343]
There used to be only C# Console App for .NET Core so it did not need differentiation, now their's F# and VB and we should add the appropriate language overlay to them:

Current:
![image](https://user-images.githubusercontent.com/1103906/63511945-dd5f8f80-c525-11e9-96b0-f05f8c0147da.png)

.NET Framework:
![image](https://user-images.githubusercontent.com/1103906/63511965-e81a2480-c525-11e9-962a-9962e4be1fbd.png)

**Comment by jmarolf** [comment]
We include a custom icon [here](https://github.com/dotnet/templates/blob/d094f7421467f53e1e9f3a2e2e90267cd369bfe9/src/Templates/DotnetCore/Microsoft.NetCore.CSharp.ProjectTemplates/ConsoleApplication.vstemplate#L6) and [here](https://github.com/dotnet/templates/blob/d094f7421467f53e1e9f3a2e2e90267cd369bfe9/src/Templates/DotnetCore/Microsoft.NetCore.VB.ProjectTemplates/ConsoleApplication.vstemplate#L6).  We could use the default icon from the resource package ([C#](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvsproject%2FTemplates%2FWindows%2FCSharp%2FProjectTemplates%2FConsoleApplication%2Fcsconsoleapplication.vstemplate&version=GBmaster&line=6&lineStyle=plain&lineEnd=6&lineStartColumn=5&lineEndColumn=72) an [VB](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvsproject%2FTemplates%2FWindows%2FVisualBasic%2FProjectTemplates%2Fconsoleapplication%2Fconsoleapplication.vstemplate&version=GBmaster&line=6&lineStyle=plain&lineEnd=6&lineStartColumn=5&lineEndColumn=72) respectively) or modify our custom icon to have the language glyphs
