### ISSUE TITLE
Shared Projects have the wrong template icon

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5344]
Shared Projects are supposed to have the double-diamond overlay similar to C++:

![image](https://user-images.githubusercontent.com/1103906/63512222-9f16a000-c526-11e9-84bc-25392c56de28.png)

**Comment by davkean** [comment]
This does look like it regressed, this is currently using `hub-csharp.ico` and `hub-vb.ico` icons.

**Comment by davkean** [comment]
These are supposed to be using [CSSharedProject](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvscommon%2Fvsimages%2FXaml%2FCSSharedProject.xaml&version=GBmaster) and [VBSharedProject](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvscommon%2Fvsimages%2FXaml%2FVBSharedProject.xaml&version=GBmaster) from here: http://glyphlist.azurewebsites.net/knownmonikers/. I don't know if there's a way to use KnownMonikers in templates, so I've asked the extensibility alias. Otherwise, we need to ask http://aka.ms/dduxicon to turn those XAML files into icons.

**Comment by davidwengier** [comment]
> Actually, this isn't correct

What isn't correct? That they should be using those monikers (or icon versions of them)?

**Comment by davkean** [comment]
I don't think the monikers are the right icon at 32x32 based on looking at the XAML.

**Comment by davidwengier** [comment]
I agree. I think we should get something made that is the C# and VB equivalent of the C++ shared icon: 
![image](https://user-images.githubusercontent.com/754264/63999091-01365d00-cb46-11e9-9c05-545fb086d9c4.png)

**Comment by davkean** [comment]
Make note that only the diamond shows at 16x16.

**Comment by davidwengier** [comment]
And at 20x20 😛

**Comment by davidwengier** [comment]
Waiting for icons. https://devdiv-design.visualstudio.com/D3%20Studio/_workitems/edit/7973

**Comment by davidwengier** [comment]
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/202543

**Comment by davidwengier** [comment]
PR completed.
