### ISSUE TITLE
"Assembly Information File" shows under ".NET Core" node instead of "General"

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5346]
**Visual Studio Version**:
Version 16.3.0 Preview 3.0 [29221.207.master]

**Summary**:
An Assembly Information File appears under a ".NET Core" node. This is the only template that lives under that node, similar to .NET Framework, this template should appear under "General".

**Steps to Reproduce**:
![image](https://user-images.githubusercontent.com/1103906/63519255-f5d7a600-c535-11e9-8a5f-a64c83ac486c.png)

**Expected Behavior**:
Template to lives under General exactly like .NET Framework.

**Actual Behavior**:
Template lives under .NET Core.

**Comment by davkean** [comment]
@jmarolf Was this intentional?

**Comment by jmarolf** [comment]
nope just a copy/paste error . 

we need to change the output subpath [here](https://github.com/dotnet/templates/blob/d094f7421467f53e1e9f3a2e2e90267cd369bfe9/src/Templates/DotnetCore/Microsoft.NetCore.CSharp.ProjectTemplates.Desktop/Microsoft.NetCore.CSharp.ProjectTemplates.Desktop.csproj#L25)
