### ISSUE TITLE
.NET Core "Assembly Information File" should give a better indication of how assembly info is stored now

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5347]
The contents of the .NET Core Assembly Information File template is the following:

``` C#
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
// [assembly: AssemblyTitle("WindowsFormsApp8")]
// [assembly: AssemblyDescription("")]
// [assembly: AssemblyConfiguration("")]
// [assembly: AssemblyCompany("")]
// [assembly: AssemblyProduct("WindowsFormsApp8")]
// [assembly: AssemblyCopyright("Copyright ©  2019")]
// [assembly: AssemblyTrademark("")]
// [assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
// [assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
// [assembly: Guid("b72c1634-c91c-4f85-8224-0e3d9a8bfc83")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// [assembly: AssemblyVersion("1.0.0.0")]
// [assembly: AssemblyFileVersion("1.0.0.0")]

```

This gives the impression that you can just uncomment those attributes, but if you do so you get a very unhelpful error:

``` 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0579	Duplicate 'AssemblyTitle' attribute	WindowsFormsApp8	C:\Users\davkean\source\repos\WindowsFormsApp8\WindowsFormsApp8\AssemblyInfo5.cs	8	Active
```

The file should give a better indication that most of this data is now stored in the project, pointing to a doc that documents these.

**Comment by jmarolf** [comment]
This template lives here: https://github.com/dotnet/templates/tree/master/src/Templates/DotnetCore/Microsoft.NetCore.CSharp.ProjectTemplates.Desktop/AssemblyInfo

**Comment by davkean** [comment]
This isn't a .NET Core template, it's a "auto-generated AssemblyInfo" template, so we'll need to fact that in as soon as we start supporting legacy format in CPS. It's not enough to indicate that it always applies to CPS.

**Comment by davidwengier** [comment]
To confirm my understanding: 

Since when CPS loads the old format, the SDK and our design time targets aren't present (I assume?), then we need to add a new capability to the SDK to indicate that it generates assembly info (like it does [for the documentation file](https://github.com/dotnet/sdk/blob/4094dca1091f32f16b5756ef14e6e1f99d67bee3/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L186-L189)) and then update the template capabilities to that, and update its contents.

Possibly that capability could be conditioned on `$(GenerateAssemblyInfo)` though I'm not sure its worth it (or even if it will work, though its easy to test).

**Comment by davkean** [comment]
Our design-time targets are always present in every C#/VB/F# project loaded in VS.

We could model this via a capability or a wizard that generates a different AssemblyInfo based on the presence of the property. Given we have a special file provider that calls a [single template](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/VisualBasic/VisualBasicAssemblyInfoSpecialFileProvider.cs#L27), the latter might end up easier.

**Comment by davidwengier** [comment]
Reopening. Only half of this has been merged...

**Comment by davidwengier** [comment]
Other half has been completed.
