### ISSUE TITLE
AssemblyInfo created by Custom Control template does not match "AssemblyInfo" template and ends up in wrong location

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5348]
**Visual Studio Version**:
Version 16.3.0 Preview 3.0 [29221.207.master]

**Summary**:

**Steps to Reproduce**:

1. In WPF App (.NET Core) -> Add New Item -> Custom Control (WPF)

**Expected Behavior**:
AssemblyInfo.cs to be created under Properties\AssemblyInfo.cs and uses the same template as called by https://github.com/dotnet/project-system/issues/5347.

**Actual Behavior**:
AssemblyInfo.cs is created in root of project and contains nothing but attribute.

As per https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/185705?_a=overview, this was a behavior was temporary and was to be fixed in https://github.com/dotnet/project-system/issues/4898. However that bug is also resolved.

**Comment by davkean** [comment]
This wizard is supposed to go through IVsProjectSpecialFiles for the project, which is supposed to hit a special handler under https://github.com/dotnet/project-system/tree/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders, which creates the same template that is created in https://github.com/dotnet/project-system/issues/5347 (Note I think the template differs  between projects that have opt into auto-generation of these attributes and those that haven't). Looks like we have one for VB but not C#.

**Comment by jmarolf** [comment]
We include a custom icon [here](https://github.com/dotnet/templates/blob/d094f7421467f53e1e9f3a2e2e90267cd369bfe9/src/Templates/DotnetCore/Microsoft.NetCore.CSharp.ProjectTemplates/ConsoleApplication.vstemplate#L6) and [here](https://github.com/dotnet/templates/blob/d094f7421467f53e1e9f3a2e2e90267cd369bfe9/src/Templates/DotnetCore/Microsoft.NetCore.VB.ProjectTemplates/ConsoleApplication.vstemplate#L6).  We could use the default icon from the resource package ([C#](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvsproject%2FTemplates%2FWindows%2FCSharp%2FProjectTemplates%2FConsoleApplication%2Fcsconsoleapplication.vstemplate&version=GBmaster&line=6&lineStyle=plain&lineEnd=6&lineStartColumn=5&lineEndColumn=72) an [VB](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvsproject%2FTemplates%2FWindows%2FVisualBasic%2FProjectTemplates%2Fconsoleapplication%2Fconsoleapplication.vstemplate&version=GBmaster&line=6&lineStyle=plain&lineEnd=6&lineStartColumn=5&lineEndColumn=72) respectively) or modify our custom icon to have the language glyphs

**Comment by davidwengier** [comment]
PR open for the fix: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/200967?_a=overview

**Comment by davidwengier** [comment]
PR completed.
