### ISSUE TITLE
[Regression] View Windows Settings button throws error

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5350]
**Visual Studio Version**:

This is a regression from 15.9, and repos in 16.2/16.3 for .NET Framework projects. .NET Core works correctly.

**Summary**:

**Steps to Reproduce**:

1.  File -> New -> **_Visual Basic_** Windows Forms App (.NET Framework)

2. Double-click My Project

3. Click View Windows Settings

**Expected Behavior**:
To open app.manifest

**Actual Behavior**:

```
---------------------------
Microsoft Visual Studio
---------------------------
Exception occurred. (Exception from HRESULT: 0x80020009 (DISP_E_EXCEPTION))
---------------------------
OK   
---------------------------
```

![image](https://user-images.githubusercontent.com/1103906/63525175-959a3180-c540-11e9-80c8-00f8bf003bc1.png)

**User Impact**:

**Comment by davkean** [comment]
@dmonroym Can you take a look.

**Comment by ocallesp** [comment]
devdiv.visualstudio.com PR 209739 merged
