### ISSUE TITLE
Add option to stop projects building if their dependencies fail to build.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5352]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/355793/add-option-to-stop-projects-building-if-their-depe.html). Please vote and comment there to make sure your voice is heard._

---

I found an old UserVoice suggestion for this feature here: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/18657544-don-t-attempt-to-build-a-project-if-a-dependency-f

My issue is I have a project which builds a deployable package which takes a few minutes, but it tries to build the package even if one of the projects it depends on fails to build.

When I press 'Build Solution' I don't want MSBuild to (try to) build any projects that depend on other projects that failed to build. This would save me killing opening Process Explorer and killing MSBuild instances that are doomed to fail.

---

#### Nick Craver on 12/1/2018, 04:21 AM: 

Not only an option, this should be the default. It's actively harmful for projects to continue to build. When downstream projects try to build after a dependency has failed a lot of time is wasted.

The developer's time is wasted by the doomed build itself spending time and resources, but also by the onslaught of errors that are accumulated. Irrelevant errors. What mattered here? It could be a missing semi-colon, but in generally it's one to a few errors. But that's not what the user gets, they get dozens to hundreds of errors from a missing DLL, some new class downstream code needs that missing, or just entire missing namespaces. Whatever it is...it's all irrelevant and just adds insult to injury. Downstream projects should never keep building after we know they're going to fail. It's a waste of everything to do so.

Please, please make stopping the default behavior.

#### mtr on 2/27/2019, 06:00 AM: 

Add this:
I guarantee you... much of the frustration and anger with Visual Studio is rooted right here. Locking my development workflow beyond whats required to report an error is exactly what i don't want to deal with if i get build errors. It's a situation where odd behavior like this catalyses the frustration of breaking something yourself.

Also Nick Craver is very very right: There's nothing more useless than an error telling me that project y's build went wild, because project x's build completely bombed. I have to fix project x not project y.

#### Richard Pastrick on 6/6/2019, 02:14 PM: 

As with a lot of very simple things in Visual Studio, there is an extension which will take care of this.

https://marketplace.visualstudio.com/items?itemName=EinarEgilsson.StopOnFirstBuildError

Only drawback is that if you have parallel builds going on and one fails, they all get killed instead of letting the others complete. I'd prefer it to just kill any dependent builds instead of all builds.

#### Matthieu Penant on 6/11/2019, 01:55 PM: 

In the mean time, DevExpress CodeRush has an option that does this:

https://documentation.devexpress.com/CodeRushForRoslyn/118261/Building-Assistance#stopbuild

And this extension as well:

https://marketplace.visualstudio.com/items?itemName=EinarEgilsson.StopOnFirstBuildError

**Comment by mafshin** [comment]
Also this extension (VSColorOutput)  has the option "Stop Build on First Error" which is very handy. Still wondering why that's not a default option in VS2022.

 https://marketplace.visualstudio.com/items?itemName=MikeWard-AnnArbor.VSColorOutput

**Comment by johndog** [comment]
> Also this extension (VSColorOutput) has the option "Stop Build on First Error" which is very handy. Still wondering why that's not a default option in VS2022.

Stop Build on First Error has the effect of stopping the _whole_ build, rather than just the part of the build depending on the failed project.  I use such an extensions, but this really has to be a native option so that the build can validate as much of the graph as it can, exposing as many true errors as it can.  This would be very difficult to pull off in an extension.

**Comment by drewnoakes** [comment]
This request is not specific to .NET projects, or indeed any one kind of project system. The change will need to happen in the core of VS, where builds across potentially different types of projects are scheduled. I'm closing this here, and encourage anyone to vote on the feedback ticket rather than here:

https://developercommunity.visualstudio.com/t/Add-option-to-stop-projects-building-if/355793
