### ISSUE TITLE
You don't get prompted to rename a second time

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5358]
**Steps to Reproduce**:

1.  Create new .NET Core project
2. Rename Program.cs -> Programed.cs
3. Click Yes to the prompt
4. Rename Programed.cs -> Programming.cs

**Expected Behavior**:
Get a prompt

**Actual Behavior**:
No prompt

**User Impact**:
Sadness

**Comment by jmarolf** [comment]
Don't know how to fix this.  The roslyn workspace needs to check the running document table to know the contents of your unsaved file (this bug won't repro if you save). RDT requires the UI thread so its the one thing in the workspace layer that is not capable of being deterministically updated. @jasonmalinowski may have some ideas...

**Comment by jasonmalinowski** [comment]
We have a few ideas, but I'm not sure why the asynchrony there would matter. Unless @davkean is capable of flooding the message queue with perfect precision and never leaving any processing time, this should work just fine. Something else is up.

**Comment by jasonmalinowski** [comment]
To explain further: the unsaved file *will* still be wired up, just asynchronously. But I expect that would have happened between steps 3 and 4. The simple test: as long as you don't see "Miscellaneous Files" in the project drop down before doing 4, then there's something else going on here.

**Comment by davkean** [comment]
It's not in the Misc workspace. If I save in between it works, whatever is doing the type check appears to be working off the saved buffer, not the unsaved changes.

**Comment by jmarolf** [comment]
@jasonmalinowski 	thanks! I'll need to debug this then.  There must be some logic error in https://github.com/dotnet/project-system/blob/48a170d200278a1bfaface9e9a9f671f770ec593/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/Renamer.cs#L227
