### ISSUE TITLE
Improve incremental build scoping (avoid rebuilding downstream projects after internal changes to a C# project)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5363]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/485909/improve-incremental-build-scoping-avoid-rebuilding.html). Please vote and comment there to make sure your voice is heard._

---
<p>My team works on a large/complex UWP app comprised of a mixture of C# and C++/CX projects.</p><p>Our productivity has been hindered by incremental build performance, particularly after iterative changes to C# code. A change to the implementation of a single one of our frequently-changed C# DLLs takes ~3-5 minutes to rebuild on a high-end workstation via the F5 / Start Debugging workflow (building any 'outdated' projects in the startup project's dependency graph).</p><p>The majority of this time is spent rebuilding C# projects downstream of (dependent on) the project that changed. These rebuilds are often unnecessary. They occur even when the changes only affect the internal implementation of a single assembly, with no changes to its exported / public API surface.</p><p>In contrast, a change to the implementation of one of our frequently-changed C++ modules takes ~30-55 seconds to rebuild on the same hardware with the same workflow. In this case, there are no extraneous rebuilds of downstream projects; the incremental build is well-scoped.</p><p>The difference in incremental build behavior seems to stem from the granularity of the project outputs. A C++/CX WinRT component project outputs a DLL, plus a winmd file that's only updated if the external API surface of the component changed. Downstream projects are considered up-to-date if the winmd is unchanged (strangely, I'm not seeing this behavior in a small test app I just created, but do in our larger/older app). A C# WinRT component project outputs a winmd file that's updated regardless of the nature of the changes (it seemingly contains the implementation/code).</p><p>Our frequently-changed C# projects are Class Library projects that output a DLL. Presumably this couldn't be augmented with a winmd given its more-restrictive type system. I wonder if could be augmented with some new file reflecting the DLL's external API surface / exported types, or a hash thereof. An ILDasm dump filtered to exported methods / types comes to mind, but perhaps this could be done more efficiently using some compiler knowledge/state.</p><p>We understand that any incremental-build optimization here would be scoped to Debug builds in our scenario (builds with .NET Native compilation disabled). We're also aware of workarounds that avoid incrementally building the startup project or unit test projects (e.g. build only the changed project, copy the updated DLL to the deployed package layout, debug the installed app / test package), but these seem awkward &amp; unlikely to be discovered / adopted broadly. Ideally the simple 'F5' workflow would be better-optimized for dev inner-loop productivity. Thanks.</p>

---
#### Jane Wu [MSFT] on 3/12/2019, 01:31 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by jjmew** [comment]
This belongs to a different team. We have move the original ticket to the correct team.
