### ISSUE TITLE
Warn users they are creating .NET Core tests when they only have .NET Framework projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5364]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/573556/warn-users-they-are-creating-net-core-tests-when-t.html). Please vote and comment there to make sure your voice is heard._

---
<p>Warn users they are adding a .NET Core test project to a solution with only .NET Framework projects. This is easy to miss and can cause issues with their tests referencing the .NET Framework code.</p>

---
#### Jane Wu [MSFT] on 5/20/2019, 00:19 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by jjmew** [comment]
Thanks for the suggestion. This currently doesn't meet our bar.
