### ISSUE TITLE
Option to manage project references including NuGet packages from a .csproj context menu in Folder View

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5365]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/432343/option-to-manage-project-references-including-nuge.html). Please vote and comment there to make sure your voice is heard._

---
<p>As far as I can tell, I am unable to manage project references including NuGet package references when viewing my source code from &quot;Folder View&quot;. I would like a context menu option when right clicking a .csproj file to manage the project references including being able to manage NuGet packages.</p>

---
#### brian pickens on 1/21/2019, 10:58 AM: 

<p>I will say, there is a sort of work around in that, in the Solution Explorer menu, if you click the dropdown next to "Solutions and Folders" you can switch context to any particular project or solution in the directory context you're operating under. Still, my request would very much come in handy.</p>

#### Jane Wu [MSFT] on 1/22/2019, 02:11 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>
#### Simon Brand [MSFT] on 2/6/2019, 11:48 AM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by davkean** [comment]
Moved this back to https://developercommunity.visualstudio.com/content/idea/432343/option-to-manage-project-references-including-nuge.html, as an internal team owns this.
