### ISSUE TITLE
add a filter on the build-output to switch between detailed and normal view.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5379]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/505936/add-a-filter-on-the-build-output-to-switch-between.html). Please vote and comment there to make sure your voice is heard._

---
<p>Now the choice has to be made before you build at:</p><p>Tools-&gt;Options-&gt;Project and Solutions-&gt;Build and Run-:&gt;MSBuild project output verbosity: Normal/Detailed.</p><p>However, if you can an error message, its often useful to look at the detailed output.</p><p>My suggestion is to offer a second linked- build output tab with all the detailed logging, so if you select a line in the normal build output, then switch to the detailed build output, the same line in selected, but you see it in its full detailed context.</p><p></p>

---
#### Jane Wu [MSFT] on 3/27/2019, 00:36 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by jjmew** [comment]
Thank you for the suggestion but this doesn't meet the bar.
