### ISSUE TITLE
Incremental Build (Fast Up To Date Check) broken with build setting [Debugging Information = Embedded]. Project is always marked a 'Missing output file' *.pdb in the target directory

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5381]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/648727/incremental-build-fast-up-to-date-check-broken-wit.html). Please vote and comment there to make sure your voice is heard._

---
Visual Studio 2017 & 2019 will always initiate MSBuild when no source files have changed when the debugging symbols compiler option is set to embedded.  

Steps to reproduce:

1. Create a new .Net framework project (any application output type)
1. Set project build output setting &quot;Debugging Information&quot; to &quot;Embedded&quot;
1. Build the project twice
1. Note the second build output message :

``` 
1> Project 'ConsoleApp1' is not up to date. Missing output file '.pdb'.
1> ------ Build started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
1>   ConsoleApp1 -> \ConsoleApp1.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

Expected output from second build when no source changed:

```
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```

Issue : Output pdb file is missing from output directory with compiler option set to embedded. The symbols are generated and embedded in the assembly, however the 'FastUpToDateCheck' in visual studio seems to expect the symbol file in the output directory.

Incremental build in VS works as expected (not starting Msbuild) when any other debugging information option is set : full, none, or portable. 

See also: 

- https://docs.microsoft.com/en-us/visualstudio/ide/reference/advanced-build-settings-dialog-box-csharp
- https://blogs.msdn.microsoft.com/kirillosenkov/2014/08/04/how-to-investigate-rebuilding-in-visual-studio-when-nothing-has-changed/
- Related work https://github.com/dotnet/project-system/pull/3142

**Comment by drewnoakes** [comment]
This applies to the legacy project system. We should first determine whether it applies to SDK-style projects.

**Comment by jjmew** [comment]
We need to check if this applies to new project system or only legacy.

**Comment by drewnoakes** [comment]
This doesn't apply to the new project system.

This works as expected:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

</Project>
```

**Comment by jjmew** [comment]
@drewnoakes Thank you for checking. We will close this issue.
