### ISSUE TITLE
Project dropdown in code editor can't switch between .NET and .NET Core projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5382]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/584985/project-dropdown-in-code-editor-cant-switch-betwee.html). Please vote and comment there to make sure your voice is heard._

---
I have numerous solutions that contain .NET Framework and .NET Core projects, with common code in a Shared Project.

In _theory_ it should be possible to use the project dropdown in the upper-left of the code window to switch views of my code files between different projects. This works in VS if no .NET Core projects are involved, but if there are both .NET Framework and .NET Core projects then any change to the combobox value is reset to the old value.

1. Open a solution such as https://github.com/marimerllc/csla `source/csla.test.sn`
1. Open a code file from the `Csla.Shared` project
1. Notice that the project dropdown shows 3 .NET Framework projects and 1 .NET Core project
1. Try to switch to a different project from whatever random one (?) VS chose when opening the file
1. Click back in the code window - notice that the dropdown changes back to its previous value

The workaround I've found is to unload all projects that I don't want to see, leaving VS with no option but to show the view I want. This is tedious however, as then I need to reload all those projects to build/test, etc.

---
#### Visual Studio Feedback System on 5/28/2019, 05:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Milan Simic on 7/28/2019, 10:06 PM: 

<p>Still exists in v16.2.0</p>

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment]
This is being tracked by a bug in an internal issue tracker. You can follow this developer community issue to get updates: https://developercommunity.visualstudio.com/content/problem/606555/the-code-editor-project-selector-switches-back-to.html

**Comment by LeftTwixWand** [comment]
> This is being tracked by a bug in an internal issue tracker. You can follow this developer community issue to get updates: https://developercommunity.visualstudio.com/content/problem/606555/the-code-editor-project-selector-switches-back-to.html

Hi. In this article mentioned, that the issue was Fixed In: Visual Studio 2019 version 16.5, but today I get it in the Visual Studio 2019, version 16.9.2. And I can't reopen the issue on the developercommunity site.

**Behavior:**
My solution contained: UWP project, .NET Core 3 console app, and a .NET Standard 2.0 class library. I was trying to use ef core with UWP, and I had this dropdown problem, until I didn't install ef core tools, using the command:
`dotnet tool install --global dotnet-ef`. After that I restarted the VS, and it becomes working.
