### ISSUE TITLE
VS doesn't respect Shared project name

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5383]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/698372/vs-doesnt-respect-shared-project-name.html). Please vote and comment there to make sure your voice is heard._

---
I have a shared project which was called Scenes and I've renamed it to Shared. I just created some classes and VS has assigned 'Scenes' to the namespace instead of 'Shared'. That's not what I expect and it doesn't make sense.

---
#### Visual Studio Feedback System on 8/19/2019, 08:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by davkean** [comment]
This is controlled via the "Root Namespace" property by right-clicking on the Shared Project in Solution Explorer and choosing Properties.
