### ISSUE TITLE
Project File Preview shows on double-click

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#5385]
I have "Open SDK-Style project files with double-click or the Enter key" turned off, but in VS 29226.166.16.3 the preview window now opens when I double-click on a project node. The hierarchy still opens/closes, and turning off Preview Tabs makes the preview go away. From @davidwengier on Teams: `Yeah, sounds like they changed when the focus event fires`

**Comment by davidwengier** [comment]
Thanks for the report. Moved to solution explorer bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/973662
