### ISSUE TITLE
Issues with Inherited Form or Inherited Control templates

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5398]
Two problems: 
* At the moment when in a non-WinForms project  the Inherited Control and Inherited Form show in the Add Item dialog when they shouldn't
* The Inheritance Picker window that the templates open up doesn't work in .NET Core projects

The code for these is located here: https://devdiv.visualstudio.com/DevDiv/_git/VS.ref_archive?path=%2Fsrc%2Fcsharp%2FWizards%2FVSZ%2Fcsharpprojectitems&version=GBmaster
The Inheritance Picker window code is here: https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvsip%2FPackages%2FWin%2FInheritanceDialog.cs&version=GBmaster

These use the older "vsz" template format so don't support capabilities. We need to work out what to do with these:
* Move them to vstemplate?
* Hide them via a manaully written Add Item template filter that explicitly calls these templates out?

**Comment by davkean** [comment]
@davidwengier One option we should consider is just to drop them altogether from CPS, they went out of flavor many releases ago because the experience "inherited forms" was pretty buggy and not great.

**Comment by davkean** [comment]
Here's an example of a filter: http://index/?leftProject=Microsoft.VisualStudio.ProjectFlavoring&leftSymbol=r0ghexgesmiv&file=Microsoft%5CVisualStudio%5CProjectFlavoring%5CTemplating%5CProjectItemManager.cs&line=18. CPS might need to be involved.

**Comment by davkean** [comment]
Or maybe not, we can just export a COM service that implements IVsFilterAddProjectItemDlg.

**Comment by davidwengier** [comment]
> One option we should consider is just to drop them altogether from CPS

I was thinking this, particularly as they don't work with .NET Core anyway, the amount of work here probably outweighs the benefit.
