### ISSUE TITLE
Project System: Post Build event does not handle spaces in paths, despite being quoted

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#54]
_From @davkean on April 29, 2016 18:37_

(Posted on behalf of a customer)

using this:

```
robocopy “$(TargetDir)\” “$(SolutionDir)\Application\$(OutDir)\Modules” $(TargetName).dll $(TargetName).pdb
``

when my solution path is":

```

C:\Users\user\Documents\Visual Studio 2012\Foo\Foo Bar\Foo App

```

error message
```

Invalid Parameter #: "2012\Foo\Foo"

```
shows that it is not respecting the quotes around and split

_Copied from original issue: dotnet/roslyn#10983_
```

**Comment by alexanderkozlenko** [comment]
It seems that now it works well without any error about invalid parameter. There is an error message `error MSB3073: The command ... exited with code 1`, but it indicates only that files were copied.

**Comment by ticktickMOF** [comment]
Isn't the issue just that the slash after $(TargetDir) escapes the quote so the first argument becomes '$(TargetDir)” ' rather than '$(TargetDir)' and the second argument is unquoted.

**Comment by davkean** [comment]
@ticktickMOF Ha, yes that would would be it. Thanks!
