### ISSUE TITLE
Can't change Build Action to Page from ApplicationDefinition

### ISSUE THREAD

**Issue by onovotny** [dotnet/project-system#5404]
**Visual Studio Version**: 16.3p2

**Summary**:
In a .NET Core 3 WPF app, I cannot use the properties window to change the Build Action of App.xaml to Page from its default of ApplicationDefinition.

**Steps to Reproduce**:

1. New WPF .NET Core 3 app

2. Select App.xaml and hit properties on it

3. Change the Build Action to Page

**Expected Behavior**:
VS should add the proper remove/include's to the csproj file.

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1427284/64063918-202a0300-cbc9-11e9-96f9-bb8606aa8c3b.png)

```
An error has occurred while saving the edited properties listed below:
	Build Action
One or more values are invalid. Cannot add 'App.xaml' to the project, because the path is explicitly excluded from the project (C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.NET.Sdk.WindowsDesktop.targets (9,5)).
```

Also, that error dialog is too small and not resizeable (200% display scaling)

**User Impact**:
Have to figure out how to do it by hand.

**Comment by davidwengier** [comment]
This is a CPS bug so I've logged https://devdiv.visualstudio.com/DevDiv/_workitems/edit/976289 internally but will keep this issue updated with its status.

**Comment by davidwengier** [comment]
Unfortunately the work item linked above has been closed. I recommend using the Help | Send Feedback | Report a Problem feature in Visual Studio, and I will route it to the correct team, and they can track votes.
