### ISSUE TITLE
Analyzer dependencies showing as unresolved full paths

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5418]
Steps to reproduce:

1. Create a new .NET Core Console App
1. Add a package reference to `xunit.analyzers`
1. Build the solution
1. Close the solution
1. Re-open the solution
1. Expand the project's dependencies node
1. Notice there is no `Analyzers` node
1. Modify whitespace in the project file and save it (triggering a design-time build)
1. Notice an `Analyzers` node appears with unresolved child, which is a full path rather than the analyzer's name
   ![image](https://user-images.githubusercontent.com/350947/64308182-bd2ad880-cfdb-11e9-8670-7a0dc69bc780.png)
1. Close and reopen the solution and the analyzers appear correctly
1. Modify the project file again (stays resolved)
1. Close and re-open the solution (stays resolved)
1. Build from VS then close/re-open solution and notice `Analyzers` node is missing again

Open questions:

- Why is the `Analyzers` node not initially present? This seems to happen if the build before opening the solution happened within VS.
- Why are analyzers appearing as paths and in unresolved state?

**Comment by drewnoakes** [comment]
It seems the command line build isn't strictly necessary. Just touching the project file will trigger it to load in unresolved state.

**Comment by drewnoakes** [comment]
As part of fixing this, add coverage of analyzers to the integration tests.

**Comment by drewnoakes** [comment]
Some notes to capture findings of investigations.

- It doesn't appear to vary based on SDK version
- It reproduces in 16.2.3
- It seems related to a restored cache of DTB data

Attempting to bisect to find the first commit that introduced the bug hit a snag I haven't seen before:

```
$ git bisect bad
Bisecting: a merge base must be tested
[63e6b4124bf593f9ae5b7771c6c560c0820b828a] Merge pull request #4642 from etbyrd/revert-change
$ git bisect bad
The merge base 63e6b4124bf593f9ae5b7771c6c560c0820b828a is bad.
This means the bug has been fixed between 63e6b4124bf593f9ae5b7771c6c560c0820b828a and [144f544a69484f73bcd850c2b205801e8b24b7e0].
$ git bisect log
git bisect start
# bad: [59a17d3894ddbe76b2fd5fc3ee84aeda8285060f] Merge pull request #5426 from drewnoakes/double-subscribe
git bisect bad 59a17d3894ddbe76b2fd5fc3ee84aeda8285060f
# bad: [ba4a0a9e06dac4d0c825291f8fb7e7755be34740] Merge pull request #5395 from drewnoakes/fix-5386-up-to-date-check
git bisect bad ba4a0a9e06dac4d0c825291f8fb7e7755be34740
# bad: [97febccd933f874ed3879189951dfb4ac9a18500] Merge pull request #5280 from davkean/MoveCI_dev16.2
git bisect bad 97febccd933f874ed3879189951dfb4ac9a18500
# bad: [7c3e3c9b1644679176c6a7be5a4ac87d3946d692] Merge pull request #4859 from davkean/UWP
git bisect bad 7c3e3c9b1644679176c6a7be5a4ac87d3946d692
# good: [144f544a69484f73bcd850c2b205801e8b24b7e0] Merge dev15.9.x to dev16.0.x (#4770)
git bisect good 144f544a69484f73bcd850c2b205801e8b24b7e0
# bad: [d5843e0bf9de830e59a522e36d727fad693e92e7] Merge pull request #4646 from davkean/OperationProgress
git bisect bad d5843e0bf9de830e59a522e36d727fad693e92e7
# bad: [d5843e0bf9de830e59a522e36d727fad693e92e7] Merge pull request #4646 from davkean/OperationProgress
git bisect bad d5843e0bf9de830e59a522e36d727fad693e92e7
# bad: [63e6b4124bf593f9ae5b7771c6c560c0820b828a] Merge pull request #4642 from etbyrd/revert-change
git bisect bad 63e6b4124bf593f9ae5b7771c6c560c0820b828a
```

This means the bug was not present in 144f544a69484f73bcd850c2b205801e8b24b7e0 (Apr 30). I need to dig into why the bisect wouldn't complete.

**Comment by DamianEdwards** [comment]
FYI still repros in 16.3.1 when working with ASP.NET Core projects:
![image](https://user-images.githubusercontent.com/249088/65803444-7a1fd900-e133-11e9-926c-06ec45ea9586.png)

**Comment by drewnoakes** [comment]
This is potentially caused by metadata filtering in the DTB cache for task items. From the (internal) ProjectServices repo:

> MSBuild throws exceptions when we access path related properties on non-path items.
> We try to prevent running into such frequent exceptions by detecting some common invalid path patterns.

This filtering applies when writing the cache, which fits with the above repro steps. My current hunch is that data needed by the Analyzers node is being filtered out by the cache, but this needs further investigation.

**Comment by drewnoakes** [comment]
Paths are shown for unresolved analyzer references:

https://github.com/dotnet/roslyn/blob/ef4e36fd040f77ba5103434101138598f4c6233f/src/VisualStudio/Core/SolutionExplorerShim/AnalyzerItem/AnalyzerItem.cs#L83-L93

**Comment by drewnoakes** [comment]
This can be reproduced more easily by:

1. New ASP.NET Core Web Application (empty)
2. Close solution
3. Reopen solution

Deleting the `.dtbcache` file in the `.vs` folder between steps 2 and 3 fixes the problem, so the DTB caching in ProjectServices is looking like the culprit here.

**Comment by DamianEdwards** [comment]
@drewnoakes really appreciate the persistence on this 👍

**Comment by ttaylor29** [comment]
@drewnoakes post helped me out! Thank you!

**Comment by drewnoakes** [comment]
Getting closer. This appears to be a race condition. If the VS instance is 'warm' (has previously had a solution open) then the problem triggers. The presence of the DTB cache factors in to the sequence of events, as it's much faster to read the cache than do a DTB. It also explains why using the debugger hasn't been helpful, as that changes timing too. I'm going to add some tracing to dig deeper.

**Comment by drewnoakes** [comment]
This has been fixed and will be released in 16.5.

**Comment by AssafAuo** [comment]
could be but 16.5 is not out yet

**Comment by keserwan** [comment]
I just updated Visual studio to 16.4.4 and the issue was resolved.
The reference is fixed and no more yellow triangle.
Thanks.

> This has been fixed and will be released in 16.5.

I just updated Visual studio to 16.4.4 and the issue was resolved.
The reference is fixed and no more yellow triangle.
Thanks.

**Comment by keserwan** [comment]
> This has been fixed and will be released in 16.5.

I just updated Visual studio to 16.4.4 and the issue was resolved.
The reference is fixed and no more yellow triangle.
Thanks.

**Comment by drewnoakes** [comment]
@keserwan glad it's working for you, but the fix is not present in that build. It will be in 16.5, and most likely in a preview.

**Comment by arphox** [comment]
I fixed this error by deleting the solution's `.vs` folder along with all `bin` and `obj` folders in all subprojects. All of these of course while VS was not running.

**Comment by oboro-san** [comment]
@arphox Thanks alot. Your suggestion worked for me

**Comment by davkean** [comment]
That will work until the next reload of the solution, the fix is in 16.5.

**Comment by yunsong0922** [comment]
That's also works for me. Thanks @arphox

**Comment by walterpg** [comment]
Hi, We've found another manifestation of this issue in our project extension.

When the project loads, we see a an "empty" (but not null) project change (presumably an inconsequential DTB?). In the same update there is an evaluation change, which is the resolution of the analyzer files. Since the project change is not null, the evaluation change is not handled, and so we see the dreaded warning triangles.

We do not have a simple replication, but we do have a simple one-line fix in `DependenciesRuleHandlerBase` that "works for us". We can produce a pull request if desired.
