### ISSUE TITLE
Saving csproj file doesn't honor charset in .editorconfig

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/project-system#5424]
**Version Used**: VS 16.2

**Steps to Reproduce**:

- Create a new .NET solution (.NET Core, new SDK csproj format)
- Open it with VS 16.2
- Add .editorconfig

```
root = true

[*]
charset = utf-8
```

- Open the csproj file
- Save the file (Ctrl+S)
- Save the file (Ctrl+S) (yes, again)

**Expected Behavior**:

The csproj file has no UTF8 bom.

**Actual Behavior**:

The csproj file has a UTF8 bom.

**Comment by davidwengier** [comment]
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/200454

**Comment by davidwengier** [comment]
PR completed.

**Comment by davidwengier** [comment]
It's worth noting that in fixing this minor issue, I noticed a number of issues around general `.editorconfig` support, and have logged #5427 for further investigation and improvement.
