### ISSUE TITLE
Why does CPS save the project file twice?

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5428]
Currently when the project file is open in an editor and the user presses Ctrl+S, the project file will be save via the UnconfiguredProject, and then the SaveProjectFileEditorHandler will save it again in its Dispose method.

Need to work out if there is a reason for this, potentially it's because the first save is committing the unsaved in-memory state of the project to disk, and the second save then commits any un-saved edits from the editor. If so, we might be able to change that by updating the project from the buffer first (at SaveProjectFileEditorHandler creation maybe?), though we need to ensure the project doesn't reload at that point. It also might be hard to deal with invalid edits that cause the load to fail, without losing in-memory project changes.

**Comment by drewnoakes** [comment]
Triage: decided not to complete this.
