### ISSUE TITLE
Allow other language services to work with project file editing

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5429]
Currently https://github.com/mhutch/MonoDevelop.MSBuildEditor/ doesn't work with CPS projects because the Xml editor that we create rejects any language service other than its own. 

This might be fixed by #4215 if we can remove our editor factory entirely.

**Comment by jjmew** [comment]
@davidwengier was this fixed by #4215?

**Comment by davidwengier** [comment]
No, this is a limitation of the XML editor. I think we just close this out, if we want to do more work to provide a nicer editing experience we would use a different approach.

**Comment by mhutch** [comment]
FWIW this is the sole reason I have not shipped the MSBuild language service extension for VS.

**Comment by tmeschter** [comment]
@davidwengier So the problem here is entirely in the XML editor itself rather than in the way CPS, dotnet/project-system, or MonoDevelop.MSBuildEditor work with it?

**Comment by tmeschter** [comment]
I'm trying to get a sense of what it would take to enable MonoDevelop.MSBuildEditor.

**Comment by davidwengier** [comment]
From my vague memory the XML editor was explicitly rejecting being opened with any language service other than its own. Not sure if that situation might have changed, or if there are easier options for project file editing now (language configuration file and/or LSP server perhaps?).

**Comment by tmeschter** [comment]
@mhutch For my understanding, what features require providing a different language service as opposed to adding completion list providers, quick info providers, taggers, etc. to the existing language service? Or is the issue that the XML language service blocks those from working?

**Comment by mhutch** [comment]
@tmeschter it implements its own XML editing functionality (it's built on VS for Mac's extensible XML editor which I also wrote), so 100% of the work (parsing etc) done by the VS XML editor would be redundant and negatively impact perf for no good reason.

it'd also be very difficult to make sure the two editors wouldn't collide over things like autoformatting.

**Comment by mhutch** [comment]
> From my vague memory the XML editor was explicitly rejecting being opened with any language service other than its own. Not sure if that situation might have changed, or if there are easier options for project file editing now (language configuration file and/or LSP server perhaps?).

LSP based editor extensions would have exactly the same problems AFAIK

**Comment by mhutch** [comment]
Anyways, MonoDevelop.XmlEditor simply registers a content type for MSBuild and binds a bunch of editor extensions to that content type. As such, it works fine in the Common Language Editor.

Presumably the XML editor is forcing the content type to its own XML content type or something? But I don't want it to coexist with the XML editor, it wouldn't add anything useful to the experience and would just do a bunch of redundant work. I just want the project system to use the default editor for the file rather than forcing the XML editor by GUID.

**Comment by tmeschter** [comment]
Is this an accurate summary of what is happening?

1. MonoDevelop.MSBuildEditor registers its own language service for the MSBuild files.
2. The project system explicitly opens the files using the built-in XML editor (rather than just whatever the default is).
3. The editor factory for the built-in XML editor sees that the specified language service is not the one that is expected and fails to create the editor at all.

Is that accurate?

**Comment by davidwengier** [comment]
@tmeschter Sounds right to me.

**Comment by mhutch** [comment]
@tmeschter

1. not quite. a "language service" isn't really a concrete thing. the MSBuild extension package registers a content type and a set of file extension associations for that content type, and binds a whole bunch of editor extensions to that content type. any instance of the VS editor control that uses that content type will load the extensions. the Common Language Editor uses the associations to determine the content type to use for the file, and resulting in using the MSBuild content type and loading the MSBuild editor extensions. the MSBuild extension package doesn't need to register its own "editor" (i.e. legacy COM based factory), so it doesn't.
2. yes
3. not quite sure what you mean. pretty sure the XML editor just sets the content type to XML.

I guess one approach would be to have the project system use the Common Language Editor by GUID if the MSBuild extension package is installed.

**Comment by davidwengier** [comment]
Can we ship the extension in-box? Changing CPS based on an extension being installed feels like the path to pain, if some assumption in CPS breaks we'd only know about it when users who have the extension installed report it. Unless we get the extension installed on RPS machines 🙃

**Comment by tmeschter** [comment]
@mhutch Thanks for the info. I don't know that much about how the editor works so it's likely that at least some of my statements are non-sensical. :-)

So then the XML editor isn't using the right content types to light up the functionality from the extension?

**Comment by mhutch** [comment]
@davidwengier it would make sense to ship it in-box at some point but I don't think it's ready for that. consider it an out-of-band preview?

**Comment by mhutch** [comment]
@tmeschter there is no content type for "MSBuild files" in VS (without my extension, at least). as far as the XML editor is concerned, they are just XML files, and as for all XML files, it's able to determine an XML schema to use based on the namespace attributes and a default schema based on the file extension.

Unfortunately XML schemas are not a good way to describe MSBuild files. They are barely adequate for describing the actual attributes and elements in MSBuild, and cannot even begin to describe element/attribute values.

**Comment by tmeschter** [comment]
@mhutch OK, so you not only need to add functionality, but you need a way to turn off the existing functionality. Makes sense.

@davidwengier Instead of opening the project file with the XML editor, is there a way to open it with the "default" editor? This would of course only help if the extension could change the default editor for the project file. Would there be any downsides?

**Comment by davidwengier** [comment]
The XML editor GUID is specified in the registry (from https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeRegistration.cs) for the diff editor to pick up (and presumably anyone else who uses the OpenDocument VS API on a project file) and in CPS (https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.VS.Implementation%2FPackage%2FProjectFileDocumentManager.cs&version=GBmain&line=41&lineEnd=42&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) when it opens the project file directly. Presumably changing those to any other editor GUID would work. All of the rest of the CPS code that tracks editor windows, dirty state, asks to save on close, and reload projects etc. is all editor agnostic (in theory - obviously this is yet to be tested 🙃)

I wonder if CPS could, instead of hardcoding the XML editor GUID, just read a registry key that tells it which GUID to use. The extension could then update the 3 editor factory mapping registry entries, and whatever CPS registry entry is created, and simply change the value of that GUID.

No idea if that is something extensions are allowed to do, or how well it plays with uninstall etc. though, just a random idea.

**Comment by mhutch** [comment]
How's that different from using the default editor though? :)

FWIW those are referred to as "legacy" language services in the VS docs. AFAICT modern (including LSP based ones) are expected to extend the Common Language Editor like my extension does.

**Comment by davidwengier** [comment]
> How's that different from using the default editor though? :)

**Comment by mhutch** [comment]
Right, but I'm pretty sure the *default* editor without my extension is the XML editor? AFAICT the project system registers it as the default editor for csproj etc via those `ProvideEditorFactoryMapping` attributes.

**Comment by KirillOsenkov** [comment]
@drewnoakes @jjmew

**Comment by drewnoakes** [comment]
There's no update here. I share your desire to improve MSBuild project editing.

**Comment by tmeschter** [comment]
Fixed via https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/414261. @mhutch please reactivate or ping me if you run into further blockers in this area.
