### ISSUE TITLE
WinForms and WPF templates appear for the wrong language on legacy projects

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5447]
A C# legacy WPF app:
![image](https://user-images.githubusercontent.com/754264/64394177-3a1b8800-d098-11e9-982d-0e56897fd751.png)

A VB legacy WPF app:
![image](https://user-images.githubusercontent.com/754264/64394234-7818ac00-d098-11e9-9341-5586bfde2a78.png)

Same thing happens for legacy WinForms and Console projects.

**Comment by davkean** [comment]
This must have regressed in the move to capabilities, thought its not clear to me why - these templates should be combining the language with it `VB` or `CSharp`.

**Comment by davkean** [comment]
In the first case, is VB node selected and expanded by default? If so, we probably want to pull this into 16.3.

**Comment by davidwengier** [comment]
Good catch.

**Comment by davidwengier** [comment]
False alarm, thankfully. This regressed in https://github.com/dotnet/project-system/issues/4945 which is only in 16.4

**Comment by davkean** [comment]
This commit regressed this: https://devdiv.visualstudio.com/DevDiv/_git/VS/commit/07db0c84bcd8309abc750264bc6e56330c9788de. @jmarolf Why was that change made? There's no context in the commit.

**Comment by davkean** [comment]
I can see why this change was made, the `WindowsForms` capability was never added to legacy: https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvsproject%2Flangproj%2FCLangHierarchy.cpp&version=GBmaster&line=4035&lineEnd=4036&lineStartColumn=1&lineEndColumn=1&lineStyle=plain.

**Comment by jmarolf** [comment]
Both the WPF and Winforms teams complained that their tests on legacy broke with this change. Feel free to revert it.

**Comment by davidwengier** [comment]
Also tracked by, and will be fixed with #4250 

Also tracked by https://dev.azure.com/devdiv/DevDiv/_workitems/edit/974353

**Comment by davidwengier** [comment]
> Both the WPF and Winforms teams complained that their tests on legacy broke with this change

Does this mean there are there issues logged for this on Azure DevOps? If so, can you please send them my way.

**Comment by jmarolf** [comment]
[AB#917750](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/917750/) was the main motivator

**Comment by davidwengier** [comment]
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/200982

**Comment by davidwengier** [comment]
PR completed.
