### ISSUE TITLE
Do something with single-click .csproj preview issue

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [dotnet/project-system#5491]
I have headeak with this since first use of VS2019 and it get to the point that I now hate VS.
Looks like someone encourage people that it is a good idea to open preview on single click, but it's disaster. Every time when I navigate between projects in solution .csproj file appears and double clicking doesnt help, because even if I disable editing on double click it still catch a **click**.

I search for solution, and find a lot of complains ([exapmle 1](https://developercommunity.visualstudio.com/content/problem/450667/clicking-on-a-aspnet-core-project-in-solution-open.html), [exapmle 2](https://developercommunity.visualstudio.com/idea/439375/vs2019-preview-2-dont-open-csproj-on-project-click.html)) but MS support don't understand an issues.

Feature was added in #4061 and I'm asking for same ability to disable this behaviour in settings as it was done for double clicking or remove it completely. SOS!

**Comment by davidwengier** [comment]
Thank you for the feedback, I appreciate that this functionality is frustrating for you when it opens up unintentionally. There is a bug fix for the issue with the preview window opening when double clicking, which will be released soon.

For the option to disable previewing of project files altogether, I'm going to close this issue but ask that you please vote and/or comment on the following developer community issue instead:
https://developercommunity.visualstudio.com/content/problem/604853/disable-preview-for-csproj-files.html

By collecting all of the related feedback in a single issue it is easier for us to prioritize our work, and provides more data for the product decision makers.
