### ISSUE TITLE
Renaming configuration/platform doesn't update project file

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5502]
**Visual Studio Version**: Version 16.4.0 Preview 2.0 [29315.5.master]

**Steps to Reproduce**:

1. Create a new .NET Core console app
1. Open Configuration Manager
1. Add a new configuration (eg. `Foo`)
1. Close dialogs and open project file. Notice it now includes:
   ```xml
   <Configurations>Debug;Release;Foo</Configurations>
   ```
1. Open Configuration Manager
1. Rename that configuration (eg. to `Foo2`)
1. Close dialogs
1. Notice that project file was not updated and still mentions `Foo`

**Expected Behavior**:

Project file should reflect change.

**Comment by drewnoakes** [comment]
The same is true for platforms, as it is for configurations.

**Comment by drewnoakes** [comment]
Found while testing #5503.

**Comment by davkean** [comment]
@drewnoakes This works for me, are you renaming the _solution_ configuration as opposed to the _project_ configuration?

**Comment by davkean** [comment]
Going to close this as no-repro

**Comment by drewnoakes** [comment]
> are you renaming the solution configuration as opposed to the project configuration?

That was it. Thanks.
