### ISSUE TITLE
DependenciesSnapshotProvider is marked with [ProjectAutoLoad] with a dynamic capability

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5519]
DependenciesSnapshotProvider is marked with a dynamic capability "DependenciesTree" yet is marked as an auto-load component. These are in conflict, dynamic capabilities which can be added/removed at any time by switching branches, installing/uninstalling packages, etc must use IProjectDynamicLoadComponent, see: https://github.com/microsoft/VSProjectSystem/blob/master/doc/overview/dynamicCapabilities.md.

Remove the test workaround in the CertainExportsMustNotBeMarkedWithDynamicCapabilities test when this is fixed.

**Comment by drewnoakes** [comment]
Potentially related to #5531.

**Comment by davkean** [comment]
Why do you say that?

**Comment by drewnoakes** [comment]
Because fixing this will likely fix that issue as well.

**Comment by melytc** [comment]
Was this fixed by https://github.com/dotnet/project-system/pull/5520?

**Comment by drewnoakes** [comment]
@melytc no, this is still outstanding.
