### ISSUE TITLE
Text shown when changing from TargetFramework to TargetFrameworks should be improved

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5528]
**Visual Studio Version**:  16.4.0 Preview 2.0 [29318.173.master]

**Steps to Reproduce**:

1. Create new .NET Core Console App.

2. Edit project:

   ```diff
   -     <TargetFramework>netcoreapp3.0</TargetFramework>
   +     <TargetFrameworks>net472;netcoreapp3.0</TargetFrameworks>
   ```
3. Observe dialog:
   ![image](https://user-images.githubusercontent.com/350947/65206820-22e68c80-dad3-11e9-8f46-f6b2c8d06749.png)

**Expected Behavior**:

Project reloads automatically.

**Actual Behavior**:

Dialog appears and projects are reloaded.

**User Impact**:

Inconvenience.

**Comment by davkean** [comment]
This dialog is currently "by design", so we'd need a proposal for what the new design would look like and what to do with unsaved files, etc.

**Comment by drewnoakes** [comment]
The text "encountered an issue" sounds like there was a bug, rather than something which is by design.

Why do we need to reload the project here?

**Comment by davkean** [comment]
The text needs work, I was going to fix it at one point but forgot about it.

Going from single TFM to multi-TFM dramatically changes the configuration of a project by adding another dimension to them.

**Comment by drewnoakes** [comment]
PR https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/208768

**Comment by drewnoakes** [comment]
CPS PR merged.
