### ISSUE TITLE
Rename "Application Manifest File" to indicate its for Windows only

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5530]
The Application Manifest file shows up in Add New Item for .NET Core projects, we should indicate that its for "Win32", as the name currently sounds like a generic manifest file:

![image](https://user-images.githubusercontent.com/1103906/65211464-31887000-dae2-11e9-8554-151910595718.png)

Maybe "Application Manifest File (Win32)", or "Application Manifest File at the same time change the description to something like:

> Contains Win32 directives for assembly binding, Windows compatibility and User Access Control (UAC) for Windows applications.

**Comment by davidwengier** [comment]
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/207123?_a=overview

**Comment by davidwengier** [comment]
PR completed
