### ISSUE TITLE
ConsoleDebugTargetsProvider.QueryDebugTargetsForDebugLaunchAsync is not populating property Project with correct IVsHierarchy

### ISSUE THREAD

**Issue by srdjanjovcic** [dotnet/project-system#5545]
**Visual Studio Version**: 16.3

**Summary**:
`ConsoleDebugTargetsProvider.QueryDebugTargetsForDebugLaunchAsync` is not populating property `Project` with correct `IVsHierarchy`

**Steps to Reproduce**:
- Create a new C# .NET Core app (e.g., WPF);
- Attach a debugger to running instance of devenv.exe;
- Set a breakpoint on setter of `DebugLaunchSettings.Project` property;
- Do F5 of the app in debugged VS instance;

**Expected Behavior**:
- Breakpoint on setter is hit, with a valid `IVsHierarchy`;

**Actual Behavior**:
- Breakpoint is never hit, leaving the property null.

**User Impact**:
It mainly impacts Visual Studio telemetry, which cannot collect details of the project being debugged.

**Comment by gregg-miskelly** [comment]
NOTE: I believe this is not just the ConsoleDebugTargetsProvider.

**Comment by davkean** [comment]
This has been fixed for ConsoleDebugTargetsProvider. @gregg-miskelly If there's additional ones, do you know what they are?

**Comment by gregg-miskelly** [comment]
@srdjanjovcic was seeing this with WPF, which I am assuming is not ConsoleDebugTargetsProvider. Correct?

**Comment by srdjanjovcic** [comment]
I’ve seen it with all .NET Core projects.

**Comment by gregg-miskelly** [comment]
@davkean should we open a new issue?

**Comment by davkean** [comment]
@gregg-miskelly @srdjanjovcic ConsoleDebugTargetsProvider is named badly, it's used for all .NET Core launches, with exception to some web scenarios, If you are seeing in web scenarios, please open a bug against web tools internally.

**Comment by gregg-miskelly** [comment]
Ah. Thanks!

**Comment by gregg-miskelly** [comment]
Fix verified BTW.

**Comment by davkean** [comment]
Thanks for the followup.
