### ISSUE TITLE
For .Net Core 3.1, VS does not have 3.1 in the Target Fx dropdown of the properties pages.

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/project-system#5547]
**Visual Studio Version**: D16.4/29325.124.master(16.4.0 preview2.0)

**Steps to Reproduce**:

1.  Install .net core SDK 3.1.100-preview1-014070 against d16.4/29325.124.master

2. Create a new .net core project via VS and open property pages, for "Application" tab, the "Target framework" is empty, there is no ".NET Core 3.1".
![image](https://user-images.githubusercontent.com/33921754/65735000-1633eb00-e108-11e9-8bc6-04b7db65b4d5.png)
Note: Open the .csproj file, "netcoreapp3.1" is by default.

**Expected Behavior**:
3.1 templates should be available in Visual Studio

**Actual Behavior**:
VS does not have 3.1 in the Target Fx dropdown of the properties pages.

**Dotnet --info**:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview1-014070
 Commit:    156f17d882

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview1-014070\

Host (useful for support):
  Version: 3.1.0-preview1.19470.9
  Commit:  72b39b0473

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview1-014070 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview1.19474.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview1.19470.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview1.19470.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by nguerrera** [comment]
This should be fixed in next 3.1 build. This was tested on a VAL build that we are not going to insert.

**Comment by nguerrera** [comment]
https://github.com/dotnet/sdk/commit/11855b43a02b4d20c44c3bf3c4c70cd6191280c6 fixed it.

**Comment by RoySalisbury** [comment]
Installed release of Visual Studio 16.4 (which includes .NET Core 3.1). Unable to select 3.1 as target framework as described above.

**Comment by nguerrera** [comment]
@RoySalisbury Do you have a global.json specifying an earlier SDK then 3.1.100 by chance?

**Comment by RoySalisbury** [comment]
@nguerrera not that I can find.  Not in the project folder or any parent folders.

**Comment by RoySalisbury** [comment]
If I change the project file manually to netcoreapp3.1, then the IDE complains about it not being defined in 

`"C:\Program Files\dotnet\sdk\3.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets"`

So it looks like the IDE is still looking in the 3.0.1 directory and was not updated to look in the 3.1 directory.

**Comment by nguerrera** [comment]
Can you share `dotnet --info` run from the project directory?

**Comment by webprofusion-chrisc** [comment]
I ran into this as well, I did have a global.json which limited it, then restarted VS and can see it now. This probably needs UI in Visual Studio along the lines of 'Targets are limited to 3.0.1 by current global.json' just to avoid the head scratching (I reinstalled the 3.1 sdk, restarted VS a couple times, restarted machine, then googled it and got here).

**Comment by RoySalisbury** [comment]
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009804 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by RoySalisbury** [comment]
Seems restarting Visual Studio did not help, but rebooting the OS did.  Perhaps Visual Studio was holding a lock someplace on a file.  But now I can choose 3.1.0 as the target framework.

Very odd..

**Comment by asulwer** [comment]
i do not have a global.json located anywhere and i have this issue

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.302 [C:\Program Files (x86)\dotnet\sdk]
  2.2.402 [C:\Program Files (x86)\dotnet\sdk]
  3.0.100 [C:\Program Files (x86)\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by NiteshKoushik** [comment]
Hello, 
I am facing the same issue - VS 2019 is not showing target the framework having .NetCore 3.0 and 3.1 version. 

I have updated version of VS 2019, i.e. 16.1.3 and VS 2019 is updated on 6 May 2020.

I have tried enabling "use previews of .Net Core SDK" from tools, restarted VS and my system couple of times - but nothing works.

I have installed x64 and x86 SDK of 3.0 and 3.1 version in my machine. Initially tried with x64 and post that installed x86 SDK - but nothing works. 

Please suggest, if any one has solution for the same.

Thanks in advance.

Regards,
Nitesh

**Comment by ajelic420** [comment]
> Hello,
> I am facing the same issue - VS 2019 is not showing target the framework having .NetCore 3.0 and 3.1 version.
> 
> I have updated version of VS 2019, i.e. 16.1.3 and VS 2019 is updated on 6 May 2020.
> 
> I have tried enabling "use previews of .Net Core SDK" from tools, restarted VS and my system couple of times - but nothing works.
> 
> I have installed x64 and x86 SDK of 3.0 and 3.1 version in my machine. Initially tried with x64 and post that installed x86 SDK - but nothing works.
> 
> Please suggest, if any one has solution for the same.
> 
> Thanks in advance.
> 
> Regards,
> Nitesh

I have the same problem. I have not yet been able to come to a solution

**Comment by ushahx** [comment]
I was able to resolve the issue where I could not see Target Framework for .NET Code 3.1 (3.1.3) in the selection drop down. I could see all the SDKs under the folder C:\Program Files\dotnet\sdk but they were all missing under C:\Program Files (x86)\dotnet\sdk and even in the list when I try the "dotnet --list-sdk" in command prompt. The trick was to install the x86 version of the SDK you need. I installed the x86 version of 3.1.302 I was now able to see 3.1 in the target framework under project properties. Make sure you close VS before installing.

**Comment by observer11111** [comment]
Same/similar problem here with VS2019 16.8.2.  Only .NET Frameworks show in my "Target framework:" list.  Yet "dotnet --list-sdk" shows them all - including the one I want: "5.0.101 [C:\Program Files\dotnet\sdk]". Installing both x64 and x86 versions doesn't help. Checking Tools|Options|Preview Features|Use Previews of .NET Core SDK doesn't help.

**Comment by SteveSmith16384** [comment]
I have a solution with multiple projects, but only one of them has the option to install .Net Core 3.1; some have earlier versions of .Net Core, and some don't even have any .Net Core as an option??  I'm using VS 2019 v16.5.4.

**Comment by SteveSmith16384** [comment]
The only solution that worked for me was to create a new .Net Core 3.1 project and manually copy the source files across from the original project.  I think the difference in the project config files between .Net and .Net Core is too much for VS to automatically convert.

**Comment by observer11111** [comment]
> The only solution that worked for me was to create a new .Net Core 3.1 project and manually copy the source files across from the original project.
I had the same experience. Recreating the project was the only thing that worked for me trying to convert a project from .NET Core (or .NET Standard) to .NET Frameworks (or the other way around): I had to re-create the project with the desired target framework.  The project properties frameworks wouldn't let me change to the framework I wanted.

**Comment by drewnoakes** [comment]
The most common reason for not seeing .NET Core targets in the project property UI is that you have a legacy style `.csproj` (i.e. non SDK-style). You must upgrade your project to SDK style to target .NET Core or .NET 5 and later. You can do this by either:
1. Creating a new .NET Core or .NET 5 project and copying that project file over your previous one, or
1. Using a tool like [`try-convert`](https://github.com/dotnet/try-convert) to do the conversion, or
1. Unloading and manually converting your `csproj` file to SDK style (requires the most familiarity with MSBuild)

A less likely cause, if you're already using SDK-style projects, is that your SDK-style project is targeting .NET Framework, in which case options for .NET Core and .NET 5 and later are not displayed.
