### ISSUE TITLE
FastUpToDate check the wrong output files with customized inner build

### ISSUE THREAD

**Issue by vgriph** [dotnet/project-system#5548]
**Visual Studio Version**: 2019.2.5

**Summary**:

I have a problem with a highly customized project file that I cannot make the update check to pass as up-to-date. I'm using the multi-targeting functionality to build a project for two different major API versions of an API at the same time.

The project is configured to use separate assembly names for each api version, and also to use different BaseIntermediateOutputPath because the different APIs require different nuget packages to be restored.

When running the FastUpToDate check, it checks for an output as if there had been no multi-targeting happening.

I've tried to use `<UpToDateCheckOutput Remove=""/>` in an attempt to not check the non-existing output file, but no avail.

**Steps to Reproduce**:

1. Create a .NET SDK style project with the following content:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
    <RuntimeIdentifier>win</RuntimeIdentifier>
    <ApiVersions>1;2</ApiVersions>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>MultiBuildV$(ApiVersion)</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Exclude any files generated during builds without ApiVersion set -->
    <Compile Remove="obj\**" />
    <Compile Remove="obj\API$(ApiVersion)\**\*.cs" />
  </ItemGroup>

  <!-- Build the mock assembly for all API Versions at the same time. -->
  <Target Name="_UpdateInnerBuild" BeforeTargets="DispatchToInnerBuilds">
    <PropertyGroup>
      <!-- 
          Need to include the Restore target and set the BaseIntermediateOutputPath in the inner builds 
          since the project.assets.json files will differ per ApiVersion
      -->
      <InnerTargets>Restore;Build</InnerTargets>
    </PropertyGroup>
    <ItemGroup>
      <!-- Remove  the  default build configurations added by _ComputeTargetFrameworkItems -->
      <_InnerBuildProjects Remove="$(MSBuildProjectFile)" />

      <!-- Create configurtions for each combination of TargetFramework, ApiVersion and Platform -->
      <_ApiVersion Include="$(ApiVersions)" />
      <_TargetFramework Condition="'%(_ApiVerion.Identity)' != ''" Include="$(TargetFrameworks)" ApiVersion="%(_ApiVersion.Identity)" />
      <_InnerBuildProjects Include="$(MSBuildProjectFile)" Condition="'%(_TargetFramework.Platform)' != ''">
        <AdditionalProperties>TargetFramework=%(_TargetFramework.Identity);Platform=$(Platform);ApiVersion=%(_TargetFramework.ApiVersion);BaseIntermediateOutputPath=obj\API%(_TargetFramework.ApiVersion)\</AdditionalProperties>
      </_InnerBuildProjects>
    </ItemGroup>
  </Target>
</Project>
```

2. Build the project in Visual Studio

3. Build the project in Visual Studio again with no changes

**Expected Behavior**:

The project should be reported as up to date and not rebuilt

**Actual Behavior**:
> 1>FastUpToDate: Adding UpToDateCheckBuilt outputs: (MultiBuildTest)
> 1>FastUpToDate:     > 'C:\Users\user\source\repos\MultiBuildTest\MultiBuildTest\obj\Debug\net48\win\MultiBuildV.dll' (MultiBuildTest)
> 1>FastUpToDate: Output > 'C:\Users\user\source\repos\MultiBuildTest\MultiBuildTest\obj\Debug\net48\win\MultiBuildV.dll' does not exist, not up to date. (MultiBuildTest)
> 1>FastUpToDate: Up to date check completed in 0,3 ms (MultiBuildTest)
> 1>------ Build started: Project: MultiBuildTest, Configuration: Debug Any CPU ------
> ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**User Impact**:
Long build chains may be triggered due to changed inputs to other projects.

**Comment by drewnoakes** [comment]
> I've tried to use <UpToDateCheckOutput Remove=""/> in an attempt to not check the non-existing output file, but no avail.

Based on the log output:

> FastUpToDate: Adding UpToDateCheckBuilt outputs: (MultiBuildTest)

I would expect you'd need to remove `UpToDateCheckBuilt`, not `UpToDateCheckOutput`. Does that help?

**Comment by vgriph** [comment]
@drewnoakes I've now tried to remove the pdb file from `UpToDateCheckBuilt` but it doesn't work. I'm thinking that the remove has to happen after the `CollectUpToDateCheckBuiltDesignTime` target has been called, so I've even tried to add a target:
```xml
  <Target Name="RemoveBuiltOutput" AfterTargets="CollectUpToDateCheckBuiltDesignTime">
    <ItemGroup>
      <UpToDateCheckBuilt Remove="**\MultiBuildV.pdb"/>
    </ItemGroup>
  </Target>
```
but still no luck. Also I've tried to add messages to the target in hope that they would appear in the verbose output, but it didn't.

I've also tired to create a target to run before CollectUpToDateCheckBuiltDesignTime bout couldn't do anything with that either.

**Comment by drewnoakes** [comment]
If you haven't already, it might be useful to check the design-time build binlog using https://github.com/dotnet/project-system-tools (which you can install via https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools).

You can see the current definition of the `CollectUpToDateCheckBuiltDesignTime` target here:

https://github.com/dotnet/project-system/blob/77f6d69c2105929bcbbfe3532e851c41802ce802/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L426-L443

**Comment by vgriph** [comment]
@drewnoakes Thanks that was really useful. I think I'll be able to hack my way through it, but it won't be a good looking solution. What I've found so far:
It doesn't help to modify `UpToDateCheckBuilt` in a target called after `CollectUpToDateCheckBuiltDesignTime`. Any changes to `UpToDateCheckBuilt` done by those targets are ignored.
It is possible to modify `UpToDateCheckBuilt` and the inputs used by the default `CollectUpToDateCheckBuiltDesignTime`, so changing `IntermediateAssembly`, `_DebugSymbolsOutputPath` and `_DebugSymbolsIntermediatePath` works for those. However since my project has more than one `TargetPath`, and that's a property and not an Item group I cannot change that in the same way. Since I'm using the .NET SDK it is not easy to completely override the `CollectUpToDateCheckBuiltDesignTime` target.

For now I'll use a target before `CollectUpToDateCheckBuiltDesignTime` and knowledge of the default implementation to tweak it to check the correct files. It would have been easier if I has been able to modify `UpToDateCheckBuilt` after `CollectUpToDateCheckBuiltDesignTime`.

**Comment by drewnoakes** [comment]
> It doesn't help to modify `UpToDateCheckBuilt` in a target called after `CollectUpToDateCheckBuiltDesignTime`

Visual Studio is consuming the values produced by `Returns="@(UpToDateCheckBuilt)"` on that target, so any changes after that are ignored.

Did you try having a target that runs _before_ `CollectUpToDateCheckBuiltDesignTime` (rather than overriding it) and adds `UpToDateCheckBuilt` items?

Something like:

```xml
<Target Name="AddUpToDateCheckBuildItems" BeforeTargets="CollectUpToDateCheckBuiltDesignTime">
  <ItemGroup>
    <UpToDateCheckBuilt Include="..." />
  </ItemGroup>
</Target>
````

**Comment by vgriph** [comment]
The main problem was that I had to remove stuff from the UpToDateCheckBuilt that was added by the default target. I managed to do it by modifying the information used by the default target, and my project file ended up like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
    <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
    <Platforms>x86;x64</Platforms>
    <ApiVersions>1;2</ApiVersions>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>MultiBuildV$(ApiVersion)</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Exclude any files generated during builds without ApiVersion set -->
    <Compile Remove="obj\**" />
    <Compile Include="obj\API$(ApiVersion)\**\*.cs" />
  </ItemGroup>

  <!-- Build the assembly for all API Versions at the same time. -->
  <Target Name="_UpdateInnerBuild" BeforeTargets="DispatchToInnerBuilds">
    <PropertyGroup>
      <!-- 
          Need to include the Restore target and set the BaseIntermediateOutputPath in the inner builds 
          since the project.assets.json files will differ per ApiVersion
      -->
      <InnerTargets>Restore;Build</InnerTargets>
    </PropertyGroup>
    <ItemGroup>
      <!-- Remove  the  default build configurations added by _ComputeTargetFrameworkItems -->
      <_InnerBuildProjects Remove="$(MSBuildProjectFile)" />

      <!-- Create configurtions for each combination of TargetFramework, ApiVersion and Platform -->
      <_ApiVersion Include="$(ApiVersions)" />
      <_Platform Include="$(Platforms)" ApiVersion="%(_ApiVersion.Identity)" />
      <_TargetFramework Condition="'%(_Platform.ApiVersion)' != ''" Include="$(TargetFrameworks)" Platform="%(_Platform.Identity)" ApiVersion="%(_Platform.ApiVersion)" />
      <_InnerBuildProjects Include="$(MSBuildProjectFile)" Condition="'%(_TargetFramework.Platform)' != ''">
        <AdditionalProperties>TargetFramework=%(_TargetFramework.Identity);Platform=%(_TargetFramework.Platform);ApiVersion=%(_TargetFramework.ApiVersion);BaseIntermediateOutputPath=obj\API%(_TargetFramework.ApiVersion)\</AdditionalProperties>
      </_InnerBuildProjects>
    </ItemGroup>
  </Target>

  <Target Name="PrepareForUpToDateCheck" BeforeTargets="CollectUpToDateCheckBuiltDesignTime">
    <Message Text="@(IntermediateAssembly)"/>
    <ItemGroup>
      <_ApiVersion Include="$(ApiVersions)" />
      <_Platform Include="$(Platforms)" ApiVersion="%(_ApiVersion.Identity)" />
      <IntermediateAssembly Remove="obj\$(Platform)\$(Configuration)\$(AssemblyName).dll"/>
      <IntermediateAssembly Include="obj\API%(_Platform.ApiVersion)\%(_Platform.Identity)\$(Configuration)\MultiBuildV%(_Platform.ApiVersion).dll"/>
      <_DebugSymbolsIntermediatePath Remove="obj\$(Platform)\$(Configuration)\$(AssemblyName).pdb"/>
      <_DebugSymbolsIntermediatePath Include="obj\API%(_Platform.ApiVersion)\%(_Platform.Identity)\$(Configuration)\MultiBuildV%(_Platform.ApiVersion).pdb"/>
      <_DebugSymbolsOutputPath Remove="bin\$(Platform)\$(Configuration)\$(AssemblyName).pdb"/>
      <_DebugSymbolsOutputPath Include="obj\API%(_Platform.ApiVersion)\%(_Platform.Identity)\$(Configuration)\MultiBuildV%(_Platform.ApiVersion).pdb"/>
      <UpToDateCheckBuilt Include="bin\%(_Platform.Identity)\$(Configuration)\MultiBuildV%(_Platform.ApiVersion).dll"/>

    </ItemGroup>
    <PropertyGroup>
      <SkipCopyBuildProduct>true</SkipCopyBuildProduct>
    </PropertyGroup>
  </Target>

</Project>
```

**Comment by drewnoakes** [comment]
@vgriph I'm glad you found a way forward, and thanks for sharing your solution.
