### ISSUE TITLE
Cannot delete .editorconfig file from project, if DiscoverEditorConfigFiles is on

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5557]
**Visual Studio Version**: 16.3

**Summary**: When `DiscoverEditorConfigFiles` is on, the user can't delete `.editorconfig` files from the project

**Steps to Reproduce**:

1. Create .NET Core project
2. Ensure `DiscoverEditorConfigFiles` is on, either in the project file or some other mechanism (it might be on by default?)
3. Create a new .editorconfig file
4. Right click on the .editorconfig file and click Delete

**Expected Behavior**:
File is deleted.

**Actual Behavior**:
File is deleted, but an unintelligible error is shown:
![image](https://user-images.githubusercontent.com/754264/66097238-ec376880-e5e0-11e9-9a44-797f4a05b7a2.png)

**User Impact**:
It's annoying.

**Comment by davidwengier** [comment]
Dug into this a bit. Some notes:

The way the include is written means that MSBuild returns no provenance for the item, which CPS doesn't really handle well. See here: https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Microsoft.Managed.EditorConfig.targets#L10 and https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.Implementation%2FItems%2FSourceItemsService.cs&version=GBmaster&line=1665&lineStyle=plain&lineEnd=1666&lineStartColumn=1&lineEndColumn=1

Potential solutions:

1. We could just make CPS ignore items with no provenance - I'm not really sure when else this would happen, but it seems unlikely.
2. The targets file could be changed to have a simpler expression, which means the provenance then works, but the provenance comes back as Inconclusive which CPS also doesn't handle. One potential solution would be to treat Inconclusive as a Glob, or perhaps better expressed, treat anything that isn't a literal include the same way. This is in the same boat as handling the Resource items that have been talked about in the past, where ideally MSBuilds support of these scenarios is improved, rather than CPS having to do anything.
3. CPS could simply not call RemoveItems for anything outside of the project file, knowing it will fail, however there are potentially cases where the warning is useful to the user. When the file is physically deleted though, that may not be the case.

As an aside, the targets file should probably be updated to remove the files from `None` so there is only one item per file, though that doesn't actually help, because the None items are handled by CPS correctly (because they use globs).

/cc @lifengl

**Comment by drewnoakes** [comment]
Hit this today testing something else. The error was slightly different:

![image](https://user-images.githubusercontent.com/350947/77124714-c0794380-6a97-11ea-9fd7-ae31ee12fe41.png)

**Comment by catycaldwell** [comment]
Hi @jjmew are you all planning to get to this in 16.7? This is a blocking bug for IntelliCode.

**Comment by tmeschter** [comment]
If dotnet/project-system can intercept the delete we could special-case .editorconfig files and simply delete the file on disk without trying to touch the .targets file.

**Comment by tmeschter** [comment]
@davidwengier How do we handle globs? If you delete a .cs file that is being added by the `<Compile Include="**\*.cs" />` glob in the SDK, why don't we run into the same issue?

**Comment by davidwengier** [comment]
Briefly, CPS/MSBuild understands a glob that is a file pattern, but the .editorconfig files are included as `<EditorConfigFile Include="@(_PotentialEditorConfigFiles)" />` and the use of the item expression there essentially stops MSBuild from trying to evaluate what should be removed. Logically we know that those items came from "*.editorconfig", but MSBuild doesn't, so it can't match the file being removed to that pattern.

**Comment by davidwengier** [comment]
This was fixed by this internal PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/246088
