### ISSUE TITLE
VS 2019 16.3 Doesn't Save Dirty Project Properties Tab

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5559]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/752879/vs-2019-163-doesnt-save-dirty-project-file.html). Please vote and comment there to make sure your voice is heard._

---
VS 2019 16.3
.Net Core 3.0.100

Steps to Reproduce:

As seen in screenshot, I have my project file open (.Net Core project)

Scenario 1:

1) Change Hosting Model (or any property), project file is flagged as dirty with '*'
2) Hit F5 to debug, observe project file is NOT saved

Scenario 2:

1) Change Hosting Model (or any property), project file is flagged as dirty with '*'
2) Switch to Program.cs tab, click Save All button, observe project file is NOT saved

---
#### grosin on 29/09/2019, 10:31 AM: 

<p>Scenario 3:</p><p>1) Make project file dirty, flagged with '*'</p><p>2) Close project file, user is not prompted to save with Yes/No/Cancel, file blindly gets saved</p>

#### Visual Studio Feedback System on 29/09/2019, 00:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 29/09/2019, 03:06 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Sara Liu [MSFT] on 01/10/2019, 05:48 PM: 

<p>Thank you for your feedback and taking the time to reach out to us. We are sorry to hear about the issues you are seeing.<br>
Does this issue occurs in this specific project or any projects? I tried to test it in my side, but I cannot reproduce this issue.<br>
Could you please have a try with the following?</p>
<ol>
<li>Run VS in safe mode: “devenv /safemode”. Check whether the problem still happens.</li>
<li>Go to Tools-Import and Export Settings-Reset all settings and backup your current settings, choose ‘General’ to restore to the default setting and test it</li>
<li>Run the VS installer as administrator and Repair</li>
</ol>

#### grosin on 02/10/2019, 01:58 AM: 

<p>Hi,</p><p>It happens with all projects. Here are repro steps</p><p>1) Create New Project</p><p>2) Select Asp.net Core Web Application, click Next</p><p>3) Solution = Create New Solution, Place solution and project in same directory = Checked, click Create</p><p>4) Right click on Project and select properties</p><p>5) Go to debug tab</p><p>6) Change Hosting Model to In Process, note tab has been marked as dirty with '*'</p><p>7) Open Program.cs</p><p>8) Click Save All</p><p>9) Observe Project tab is still marked as Dirty</p>

#### Sara Liu [MSFT] on 03/10/2019, 01:47 PM: 

<p>Hi grosin, thanks for your detail steps. I tried to follow the steps, when click Program.cs file to open, VS did not popup 'Save All' button to reminder us to save the properties page. Could you please share the screenshot when you execute the step 7) with the Save All button? </p><p>The properties page auto save when it be closed or click Ctrl+S to manually save it, which different like other project files, other project files can be auto saved when we Hit F5 to debug.</p>

#### grosin on 03/10/2019, 01:54 PM: 

<p>I was referring to the Save All icon on the toolbar.</p>

#### Sara Liu [MSFT] on 03/10/2019, 03:55 PM: 

<p>Hi grosin, I suppose you means File-Save All, right? If so, I can got the same result as yours. This issue has been escalated for further investigation and if there is any process, I will inform you immediately.</p>

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment]
This happens for any configuration in the property pages that is stored in launchSettings.json

**Comment by davidwengier** [comment]
Actually that may not work without opening the launchSettings.json file in an editor... Will have to investigate

**Comment by davkean** [comment]
Removing tags for re-triage. Looks like this fell under the radar and was incorrectly marked as "legacy" when it affects the F5 properties of .NET Core projects.

**Comment by jaredpar** [comment]
FWIW: i've easily lost a several hours of my dev time to this bug recently. My mental model is that "F5 saves" and as such i've been liberally flipping my debug options around between scenarios, hitting F5, then a few minutes into debugging saying "wait, none of this makes sense". Only then do I notice that the project file tab is still dirty and hence I'm not debugging what I believe I am.

**Comment by jjmew** [comment]
We should make sure that the new property pages save the project file when F5-ing

**Comment by MiYanni** [comment]
For the new property pages, the 'dirty' mechanic doesn't exist. Properties will tell the *server* that they have new changes to make. Certain types of properties will do this instantly, like drop downs. Other properties, like string fields, need to lose focus to notify an update. In this case, pressing F5 will cause the property page to lose focus, thus those changes will always be saved. As you can see, pressing F5 switches focus to the Output pane, and thus will save the properties.

![NewPropertyPageSaving](https://user-images.githubusercontent.com/17788297/115768904-c78c1880-a35f-11eb-9c23-2ef009bc1a81.gif)

**Comment by davkean** [comment]
@MiYanni This is talking about Debug Profiles, not traditional properties.

**Comment by drewnoakes** [comment]
Agreed. However equally the launch profiles editor is now modal so the pattern described here is not possible. If we make it non-modal, it would likely become an editor, so would be backed by an actual file and subject to "save all". I think it's fine to close this as the new UI won't have this problem.
