### ISSUE TITLE
Editing proj file during PreBuildEvent causes MSBuild to always build

### ISSUE THREAD

**Issue by johnwc** [dotnet/project-system#5561]
We have a script that we call during the PreBuildEvent that updates the project file with a new version. Everytime I hit F6 it builds a new version. 

It seems that the functionality that is built-in to track if anything has changed since the last compile (Inputs.cache files), runs prior to PreBuildEvent. I would expect that functionality to run just before compile, so that you are able to make any needed modifications to your project in PreBuildEvent.

**Comment by drewnoakes** [comment]
Project files are inputs to compilation. Any time an input changes, the project is considered out-of-date. This compilation includes PreBuildEvent. There's no way to know whether the changed input modifies the behaviour of PreBuildEvent or not.

Why is your build modifying the build script? Perhaps there's some other way to achieve what you need.

**Comment by johnwc** [comment]
It's not modifying the build script, it's modifying the csproj file. We have a script that runs that updates the version in the csproj file.

I understand that a csproj file is considered inputs, but the calculation that is run to store the hash of the csproj file should run after the PreBuildEvent. That way it is calculated after any changes are applied during a PreBuildEvent. Otherwise it thinks the proj has changed because the hash doesn't match from the update.

I will give a scenario of the issue that causes the constant cycle, when just the version is edited during a PreBuildEvent 

1. Build kicks off
2. Build checks if current hash matches stored, doesn't so build runs
3. Hash is calculated and stored for project
4. PreBuildEvent is run, editing the version (causing a now diff hash)
5. Build compiles

If steps 3 and 4 were swapped, then step 2 would never continue unless something really was changed

1. Build kicks off
2. Build checks if current hash matches stored, it does so build stops
3. PreBuildEvent is run, editing the version
4. Hash is calculated and stored for project
5. Build compiles

**Comment by drewnoakes** [comment]
> the calculation that is run to store the hash of the csproj file should run after the PreBuildEvent

VS's fast up-to-date check works on file system time stamps, not hashes. The idea is to be as fast as possible. Computing a hash of every input to compilation would be too expensive. If VS considers the project not up-to-date then it calls MSBuild which performs a more rigorous series of checks. It is possible that VS tells MSBuild to build, and MSBuild concludes everything's up to date. The VS check is intended to assist perf in the general case, and mostly it works well.

However given you are actually changing the version, MSBuild would want to rebuild the project too.

> We have a script that runs that updates the version in the csproj file.

Is this computed (i.e. a function of some external state such as git hash) or incremented? If the latter, and you want it to be incremented in your build, then you'll always need to rebuild as each build is by definition unique.

**Comment by johnwc** [comment]
Yes, but the version is updated prior to the build/compile, so it really shouldn't be considered and edit on the second+ builds.

It is an increment, but a version increment should not occur if nothing has changed. It should not see that the version update made prior to the compile is a change the next time I hit F6. Example: If I edit some code and then hit F6 twice, the second F6 should not build.

**Comment by drewnoakes** [comment]
> the version is updated prior to the build/compile

In which case the input will always be newer than the output, and a build will occur.

The only way I can see around this is to compute the value at build time in such a way that it's not included in the input. For example you might include the current UTC date/time somehow in the version. Or you can use part of a git SHA-1 hash, for example.
