### ISSUE TITLE
VSSDK determine if legacy project has project capability package references

### ISSUE THREAD

**Issue by maxinfet** [dotnet/project-system#5563]
**Visual Studio Version**:
Visual Studio 2017 Professional 15.9.16

**Summary**:
When using the VSSDK to creating a `MenuItem` that has a `ProvideUIContextRule` legacy projects with `PackageReferences` will never show the `MenuItem` but SDK projects will show the `MenuItem`.

**Details**:
I found which capability I needed from this [document](https://github.com/microsoft/VSProjectSystem/blob/master/doc/overview/project_capabilities.md) but I have been unable to get this to work for the legacy project system. It seems like the project capability is not being added.

Here is the attribute I am using to setup the conditional hiding of my `MenuItem`. This works great in our SDK style projects but unfortunately in our main legacy project it never shows the item even though we are using package references.

```
   [ProvideUIContextRule(UiContextGuid,
    name: "NugetPackageUpdaterVisible",
    expression: "SolutionHasPackageReferences",
    termNames: new string[] { "SolutionHasPackageReferences" },
    termValues: new string[] { "SolutionHasProjectCapability:PackageReferences" })]
```

**Steps to Reproduce**:
1. Create a VSSDK project 
2. Follow the instructions [here](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions?view=vs-2019) for adding a menu item that uses rule-based context to hide and show the menu item.
3. Use the `ProvideUIContextRule` from the Details section above
4. Open a legacy project with a `PackageReference` and the extension loaded

**Expected Behavior**:
The legacy project would show the menu item like when `PackageReference`s are present.

**Actual Behavior**:
The legacy project does not show the menu item but the sdk project does show the menu item.

**User Impact**:
I am unable to prevent the loading of my extension in legacy projects that do not have `PackageReference`s despite the package being useless without `PackageReference`s.

**Question(s)**:
Is there a different capability I need to use for legacy projects to detect the presence of nuget packages?

**Comment by davkean** [comment]
I don't have a great answer for you, there's no way to do this currently. The legacy project system has a fixed set of capabilities that does not change for the lifetime of a project, and it current has zero awareness of whether its in packages.config or PackageReference mode - this is entirely driven by NuGet. 

Given our investment has moved almost entirely to the new project system, I cannot see this bug ever making the cut to be fixed. As a workaround until this project system replaces legacy, use the [VSLangProj.VSProject4](https://docs.microsoft.com/en-us/dotnet/api/vslangproj150.vsproject4.packagereferences?view=visualstudiosdk-2017#VSLangProj150_VSProject4_PackageReferences) interface to manually query the project system for PackageReferences in the project file in your QueryStatus to determine if the command should _really_ be enabled.
