### ISSUE TITLE
System.Resources.MissingManifestResourceException when DependentUpon not specified and .resx path not match with Control/Form namespace

### ISSUE THREAD

**Issue by ds1709** [dotnet/project-system#5566]
**Visual Studio Version**:
16.3.0

**Summary**:
.Net Core 3.0
Microsoft.NET.Sdk.WindowsDesktop
UseWindowsForms = true
System.Resources.MissingManifestResourceException when DependentUpon not specified and .resx path not match with Control/Form namespace.

**Steps to Reproduce**:
1. Create new WindowsForms project (sdk style, net472).
2. Add local resource to Form1 (e.g. BackgroundImage).
3. Change Form1 namespace or move it to another folder in project.
4. Build and run application.

**Expected Behavior**:
Application starts and Form1 shown with set background image.

**Actual Behavior**:
`System.Resources.MissingManifestResourceException` thrown when `this.BackgroundImage = (System.Drawing.Image)resources.GetObject("$this.BackgroundImage")))` called.

**Content of csproj file**:
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

</Project>
```
**Workaround**:
Add next item in csproj file:
```xml
  <ItemGroup>
    <!-- "NewFolder" is project subfolder where form has been moved. -->
    <EmbeddedResource Update="NewFolder/Form1.resx" DependentUpon="Form1.cs" />
  </ItemGroup>
```

**Comment by ds1709** [comment]
Also forget to point, what in visual studio resx files looks like dependent from it's component cs file, but in fact we need to specify DependentUpon attribute explicitly, and it's confusing.

**Comment by davidwengier** [comment]
@nguerrera is this an SDK issue?

**Comment by AdamDotNet** [comment]
I've been researching this too, lately. Try adding this property to your CSProj.
``` xml
<PropertyGroup>
 <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
</PropertyGroup>
```

Which I found via: /dotnet/sdk/pull/3533

Remove your workaround `<EmbeddedResource Update="..."` after adding the above property and you should be good to go.

Note that this flag is set to true for .Net Core 3.0+ and .Net Standard 2.1+, but needs to be opted in like this for other TFMs. This flag has worked for me on my projects using `Sdk="Microsoft.NET.Sdk.WindowsDesktop"` WinForms projects targeting `net48` where the namespace of the form did not match the folder it was in.

**Comment by nguerrera** [comment]
@AdamDotNet is exactly right. The convention was not applied by default to existing TFMs to avoid a breaking change. Opting in as shown above is the solution.

**Comment by ds1709** [comment]
Yes, it works now. Thanks.

**Comment by abrguyt** [comment]
> ```
> <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
> ```

This is a life-saver; I had a .NET 4.8 Winforms project converted to the .NET SDK project format with the Visual Studio Upgrade Assistant and for some mysterious reason for ALL forms where the class name was different from the file name, its corresponding .resx file would not be embedded correctly and lead to the infamous MissingManifestResourceException exception.

Adding this property solves it.

I got the hint for this at [https://github.com/dotnet/winforms/issues/638](url) where the phenomenon with the differing class and file names was mentioned related to this problem.

It seems a bug that the Visual Studio Upgrade Assistant does not add this property automatically.

**Comment by drewnoakes** [comment]
cc @adamint @abpiskunov for feedback on Upgrade Assistant.

**Comment by abrguyt** [comment]
@dr

> cc @adamint @abpiskunov for feedback on Upgrade Assistant.

Thanks, does that mean I don't have to do that myself?

**Comment by drewnoakes** [comment]
@abrguyt it would be great if you could file an issue at https://github.com/dotnet/upgrade-assistant

**Comment by abrguyt** [comment]
> @abrguyt it would be great if you could file an issue at https://github.com/dotnet/upgrade-assistant

Done .. thanks.
