### ISSUE TITLE
There's a missing space in ".NETFramework 4.8" in the Target framework dropdown in Project Properties; and it doesn't work

### ISSUE THREAD

**Issue by davidmatson** [dotnet/project-system#5572]
**Visual Studio Version**:
16.3.3

**Summary**:
When using a new-style csproj (Common Project System), a new item appears in the listn after a recent VS update, but it's missing a space. It shows ".NETFramework 4.8" instead of ".NET Framework 4.8"

**Steps to Reproduce**:

1. Create a new .NET Core exe project.

2. Unload the project file and change TargetFramework to something like net47.

3. Reload the project and open the properties page.

4. Look at the items in the Target framework list.

**Expected Behavior**:
An item labeled ".NET Framework 4.8" appears in the list and works.

**Actual Behavior**:
An item labeled ".NETFramework 4.8" appears in the list and does not work.

**User Impact**:
The items looks off compared to every other item in the list, all the way back to .NET Framework 2.0. And it doesn't work; it gives this error:
```
error MSB3644: The reference assemblies for .NETFramework,Version=v4.8 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
```

If it isn't going to work, it shouldn't appear in the list.

**Comment by davidmatson** [comment]
After installing .NET Framework 4.8 Targeting Pack in VS Setup, both problems go away. I suspect this bug may occur if .NET Framework 4.8 SDK installed but the Targeting Pack isn't.

**Comment by davidmatson** [comment]
@davidwengier - I think there's still a bug here - this item shouldn't show up in the list if the SDK is installed but the Targeting Pack isn't, right?

**Comment by davidwengier** [comment]
Unfortunately its not possible to filter the list of options here based on what is installed, as that would require doing a build before being able to show the project properties. The error message on build that says to install the targeting pack is the best we can do for now.

**Comment by davkean** [comment]
> Unfortunately its not possible to filter the list of options here based on what is installed, as that would require doing a build before being able to show the project properties.  

We can do that - and this is exactly what legacy does.
