### ISSUE TITLE
<ProjectGuid> ignored ?

### ISSUE THREAD

**Issue by goswinr** [dotnet/project-system#5576]
I undestand that a  `<ProjectGuid>` [is no longer needed](https://github.com/dotnet/project-system/pull/3303) [or desired](https://github.com/dotnet/project-system/issues/2940).
But it seems that even if it is present it is silently ignored. Is that intended?
Where would I look for the official documentation of this behavior? 
I need to have a Guid in my dll in order to load it as a plugin into another App.
I had to look at the IL to see that the Guid is missing.  I got it back via an  `AssemblyInfo` File.

**Comment by drewnoakes** [comment]
The [`[assembly: Guid(...)]`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.guidattribute?view=netframework-4.8) attribute determines an assembly's GUID. 

In .NET Framework, the project GUID was synchronised between `.sln`, `.csproj` and `AssemblyInfo.cs`.

In SDK-style projects, the project GUID only exists in the `.sln` file. Looking at the generated `obj\Debug\netstandard2.0\MyProject.AssemblyInfo.cs` will show there is not `[assembly: Guid]` attribute for the assembly. Each time you build your project, a different Guid will be used. If you require a specific Guid, you must add the attribute yourself.
