### ISSUE TITLE
VS2019 hangs opening solution

### ISSUE THREAD

**Issue by RobSwDev** [dotnet/project-system#5581]
**Visual Studio Version**:
16.3.5
**Summary**:
Visual Studio 2019 hangs when opening solution. (Does not hang in VS2017)
[Hanging.zip](https://github.com/dotnet/project-system/files/3731270/Hanging.zip)

Has happened a couple of times. We are (mostly successfully) converting our projects to the new sdk-style format so we can multitarget. I assume it's something to do with that.

**Steps to Reproduce**:
Unzip the attached cut-down solution, and open in VS2019.
VS hangs

**Comment by jjmew** [comment]
@RobSwDev I am able to repro the issue but the project file is invalid. It is using <TargetFrameworks> without adding the SDK tag. It should look like this: 

<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  	<TargetFrameworks>net461</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
  </ItemGroup>
</Project>

**Comment by RobSwDev** [comment]
@jjmew It is using "what" without adding the SDK tag? 

The history is that we converted all projects to the new sdk style, but then converted WinForms projects back to legacy style. 

So the project is supposed to be legacy, not new sdk style.  E.g. it has 
<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" /> 
Admittedly, that's far more obvious in my Company's project than in the stripped down version I submitted here.

**Comment by RobSwDev** [comment]
I guess adding <TargetFrameworks> to a legacy project is what causes the issue in VS2019?

**Comment by drewnoakes** [comment]
You can have both SDK and legacy projects in a single solution.

The project file you attached produces a hang. This is a bug in VS that we aim to fix. In the meantime you should ensure your project defines the necessary configuration properties. Use a new WinForms project file for reference, or diff your WinForms project files as they are now to how they were before your initial conversion.

**Comment by jjmew** [comment]
Here is an example of a valid WinForms project for .NET Framework 
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{560B4654-0FAD-4C41-9B94-4A82E41CFADC}</ProjectGuid>
    <OutputType>WinExe</OutputType>
    <RootNamespace>WindowsFormsApp1</RootNamespace>
    <AssemblyName>WindowsFormsApp1</AssemblyName>
    <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Deployment" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Form1.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Form1.Designer.cs">
      <DependentUpon>Form1.cs</DependentUpon>
    </Compile>
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>`
