### ISSUE TITLE
Dataset Designer Code Generator Fails in .NET Core 2.1

### ISSUE THREAD

**Issue by chickenfeetsd** [dotnet/project-system#5589]
**Visual Studio Version**:
VS2019 Enterprise v16.3.5
**Summary**:
Open any legacy dataset or create a new dataset (.xsd) that contains a DataTable with a Guid column. The code generator fails to generate the designer code after any change to the dataset is made.
The following errors are shown:

- Failed to generate code. Unable to convert input xml file content to a DataSet. Column requires a valid DataType. Column requires a valid DataType.	NetCore.DataSets
- Unable to convert input xml file content to a DataSet. Column requires a valid DataType.

This isn't an issue if the project is targeted **.NET 4.x** or **.NET Standard 2.0**.

Examine the .xsd file, it shows the System.Guid DataType is referring to System.Runtime version 4.2.1. 
Checking the latest version of System.Runtime 4.3.1 on [Nuget.org](https://www.nuget.org/packages/System.Runtime/), seems like System.Guid isn't a part of commonly used types included in the package. 

**Steps to Reproduce**:

1. Create a new .NET Core 2.1 Library project

2. Add a new Dataset

3. Using the Dataset tool to add a new data table

4. Add a new column to the data table and set the data type to System.Guid

5. Save the dataset

**Expected Behavior**:
The custom tool (MSDataSetGenerator) runs successfully and get a designer code for the dataset
**Actual Behavior**:
The custom tool (MSDataSetGenerator) fails with error
**User Impact**:
High

**Comment by chickenfeetsd** [comment]
@davkean: by any chance this issue was erroneously closed? I didn't see any relation between the issue that I reported and the fix IntegratedConsoleDebugging capability in #5605. I believed the issue that I reported hasn't been resolved yet.

**Comment by davkean** [comment]
@chickenfeetsd Good catch, yes you are correct. I'll reopen.

**Comment by davidwengier** [comment]
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/217284

**Comment by davidwengier** [comment]
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/223226
