### ISSUE TITLE
IntegratedConsoleDebugging project capability not respected 

### ISSUE THREAD

**Issue by aodl** [dotnet/project-system#5592]
**Visual Studio Version**:
16.2.0

**Project Type**
ASP .Net Core 2.2

**Summary**:
There is an 'IntegratedConsoleDebugging' project capability that could be detected to decide whether or not to launch inside the integrated console, but it isn't used. See [issue 3667](https://github.com/dotnet/project-system/issues/3667) (which indicates that the 'IntegratedConsoleDebugging' should be used) and the [resolution](https://github.com/dotnet/project-system/pull/4388) (which doesn't check for the project capability)

The only way to opt out of the integrated console debugging experience appears to be to select the 'Automatically close the console when debugging stops' debug option. 

**Expected Behavior**:
Check the project capabilities to see if 'IntegratedConsoleDebugging' is included. If not, expect that the app will not be launched for debugging in the integrated console.

**Actual Behavior**:
Regardless of whether or not the app has 'IntegratedConsoleDebugging' project capability specified, it ends up being launched for debugging in the integrated console.

**User Impact**:
The 'Automatically close the console when debugging stops' debug option can't be specified at the project level and isn't very flexible. Making use of the 'IntegratedConsoleDebugging' capability as a requisite for launching in the integrated console would provide flexibility for VSIX extensions to temporarily remove the capability and bypass the integrated console for special launches (temporarily) without needing to fiddle with an IDE-wide option that actually gets persisted (and therefore would cause problems if VS suddenly crashed without undoing the change to the IDE option).

-------------

Update: Similarly `DebugLaunchOptions.IntegratedConsole` isn't specified as a debug options flag, despite the launch taking place inside the integrated console

**Comment by drewnoakes** [comment]
@aodl would you like to submit a PR for this? It seems like you're clear on what's needed.

**Comment by aodl** [comment]
I'd be happy to give it a try, but I'm not currently aware of where the decision to launch inside the integrated console is made, and why it's made there. Or how to actually tell VS to run an app in the integrated console (I have a feeling it's outside of CPS). @davkean, would you be able give me some pointers?

My thoughts are that if a project has "LaunchProfiles" capability, the debug launch provider should decide whether or not to launch in the integrated console (and set `DebugLaunchOptions.IntegratedConsole` based on `ProjectCapabilities.IntegratedConsoleDebugging` and the 'Automatically close the console...' IDE option). I believe I can raise a PR with those changes, but I don't know how to get VS to respect the DebugLaunchOptions.IntegratedConsole` flag

**Comment by aodl** [comment]
I've raised the ^above PR with a minor commit that addresses this for `ConsoleDebugTargetsProvider` (hoping that the build tests pass with my latest commit).

However this won't address the issue for ASP.Net Core projects, as they appear to use [ProjectDebuggerProvider](https://github.com/dotnet/project-system/blob/138f25249f2170a9cf3c3df1b6cea419f4dc469b/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ProjectDebuggerProvider.cs) instead of `ConsoleDebugTargetsProvider`. 

I don't know where to start with `ProjectDebuggerProvider`. As my previous comment mentions, even though `DebugLaunchOptions.IntegratedConsole` isn't set by this debugger provider, VS still launches the integrated console. I don't know how to stop this from happening, or why it's happening. Strangely the integrated console seems to open before `ProjectDebuggerProvider.QueryDebugTargetsAsync` is called (from what I can tell). A point in the right direction with this would be much appreciated :)

**Comment by aodl** [comment]
@drewnoakes thanks for your response a couple of days ago. After doing what you suggested and raising a PR, I looked into this further in the case of Asp.Net Core projects, and it turns out that the magic happens when `ProjectDebuggerProvider.QueryDebugTargetsAsync` calls `IDebugProfileLaunchTargetsProvider.QueryDebugTargetsAsync`. If the active launch profile's command name is 'Project' (which causes the integrated console to show up), the `IDebugProfileLaunchTargetsProvider` implementation will typically be `Microsoft.WebTools.ProjectSystem.Debugger.ProjectDebugTargetsProvider`.

I'd love to work on this further, but this implementation appears to be **closed source**. I took a peek using dotpeek, and seems that it calls into `IWebServerDebuggingSupport.GetDebugLaunchSettingsAsync`, which is probably the next place to look - I just don't know where the implementation is :(

Do you think this is something that could get picked up by someone on the project-system team?

**Comment by davkean** [comment]
Thanks for your contribution @aodl!

**Comment by aodl** [comment]
Thanks @davkean!

However I don't think this issue should be closed just yet. The pull request fixed the `ConsoleDebugTargetsProvider`, but I don't believe Asp.Net Core projects typically use this provider - they use `ProjectDebuggerProvider` instead. Due to the more complicated nature of Asp.Net Core debug launches, I think this actually needs fixing in the `IDebugProfileLaunchTargetsProvider`s that are referred to. These appear to be closed source so there's not too much I can do myself, though I'd love to try. Please see my [above comment](https://github.com/dotnet/project-system/issues/5592#issuecomment-545118346) for more info

**Comment by davkean** [comment]
@aodl Can you file a bug via Help -> Send Feedback -> Report a Problem and I'll route to them? They don't track bugs here.
