### ISSUE TITLE
InvalidCastException when attempting to open project property pages

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#5595]
I'm not quite sure how I got into this state, but when I right-click on my project node and click properties, nothing happens. When I attach a debugger and turn on first-chance exceptions, I see an `InvalidCastException` in CPS. VS Version 16.4.0 Preview 3.0 [29420.8.master]. This _only_ repros on one of my solutions, but it repros consistently there, after restarting.

I've taken a dump and saved it here: "\\mlangfs1\public\frsilb\dumps\5595\devenv_cannot_open_properties.dmp"

**Comment by davkean** [comment]
Yes, I've just hit this - looks to be a operation progress bug and occurs when you attempt to open the property pages while we're restoring/doing design-time builds in the back.

**Comment by davkean** [comment]
Dup'ing against https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1005856.
