### ISSUE TITLE
RunAnalyzersDuringLiveAnalysis should be a per-user property

### ISSUE THREAD

**Issue by sharwell** [dotnet/project-system#5600]
**Visual Studio Version**: 16.4 Preview 2

**Summary**:

The `RunAnalyzersDuringLiveAnalysis` property should be a per-user property (stored in the .csproj.user file instead of the .csproj file).

**Steps to Reproduce**:

1. Create an SDK project
1. On the **Code Analysis** page, uncheck **Run on live analysis**
1. Save the project

**Expected Behavior**:

* No changes are made to the project file.
* A .user file next to the project file is created or updated to set the `RunAnalyzersDuringLiveAnalysis` property.

**Actual Behavior**:

The project file is updated.

**User Impact**:

One user's personal preferences for developer experience is impacting the IDE behavior for other users, who may not agree with those personal preferences.

**Comment by tmeschter** [comment]
Achieving this should be as simple as passing `ControlDataFlags.PersistedInProjectUserFile` when creating the `PropertyControlData` at [CodeAnalysisPropPage.vb line 69](https://github.com/dotnet/project-system/blob/caf15122c2b1eb08b1aa82d17e1b1f36cda8b0ad/src/Microsoft.VisualStudio.Editors/PropPages/CodeAnalysisPropPage.vb#L69). Whether or not that is actually desirable behavior I'll leave to others to decide.

@mavasani Can we migrate this issue to dotnet/roslyn or dotnet/roslyn-analyzers as you own this property page?

**Comment by mavasani** [comment]
@tmeschter Thanks for the suggestion on the implementation. However, I would want to eventually pass down this property down to the Roslyn language service, so it can be respected. I did it with https://github.com/dotnet/project-system/pull/5598/files, but I presume it would now need to implemented differently if the property is set in a user specific file. Any pointers to how I can accomplish that.

I am fine with this issue being in any repo. @jinujoseph @vatsalyaagrawal can we port this issue to Roslyn repo?

**Comment by tmeschter** [comment]
The .user file is still just an MSBuild project file, but by convention it is treated as user-specific and is not checked into source control. Whether the value is stored in the .user or .csproj file shouldn't affect how it is passed from MSBuild to the project system and then on to the language service.

That being said, the .user file may not get used all that much by SDK-style projects so you would definitely want to spend some time verifying the end-to-end functionality.

**Comment by mavasani** [comment]
Thanks @tmeschter! I have a PR out that should fix this: https://github.com/dotnet/project-system/pull/5601
