### ISSUE TITLE
We're no longer including Native.rc in Microsoft.VisualStudio.Settings.dll

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#561]
When we moved from VS -> GitHub, we broke the embedding of https://github.com/dotnet/roslyn-project-system/blob/b22cf2e196665e747a00c60d53aba0865567f329/src/Microsoft.VisualStudio.Editors/native.rc. This means that some of our icons are no longer registered - we should figure out if thsi important or not.

**Comment by jviau** [comment]
To fix this you can inject the icon into your assembly post-build and pre-signing. If you just need the icon for a default icon in windows explorer, can you get away with having the .ico delivered raw and not embedded?

**Comment by davkean** [comment]
This was removed in https://github.com/dotnet/project-system/pull/5068. The icons are actually already registered to point to msenvico.dll.
