### ISSUE TITLE
HostAgnostic project depends on Microsoft.VisualStudio.LanguageServices

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/project-system#5615]
See this NuGet reference: https://github.com/dotnet/project-system/blob/a70b016013ee5e45350661fcd3fcbc5684e41235/build/import/HostAgnostic.props#L41
This is blocking any exploration of using this host agnostic layer in non-Visual Studio scenarios.

**Comment by davkean** [comment]
This is known. We would need host-agnostic activation of Roslyn (owned by Roslyn), which will likely come due to other upcoming changes. Please reach out to me internally if you want to start the conversations around this.
