### ISSUE TITLE
Rename and FindAllReferences broken across projects in Visual Studio 2019 based on Azure Functions projects

### ISSUE THREAD

**Issue by petehauge** [dotnet/project-system#5624]
**Visual Studio Version**:  Visual Studio 2019 (16.3.6)

**Summary**:  We are working with an Azure Functions project with associated unit tests and we’ve found that find all references, rename, etc, for the existing solution (VS 2019) doesn't work across all the projects.  We followed all the troubleshooting online (ensure project-to-project references, clearing the intellisense cache, etc), but can’t get these features working across project.

**Steps to Reproduce**:

1)	Create a new Azure Functions v2 project (http trigger)
2)	Create a new unit test project (.net core)
3)	Add a project reference from the unit test project to the functions project
4)	Add a method to the function project like this:
        public static bool Test()
        {
            return true;
       }
5)	Call the method above from the unit test project
6)	Right click on “Test” and choose Find All References

**Expected Behavior**: Should find the reference in the unit test project for the method

**Actual Behavior**: No references found

**User Impact**:  Users can't use the code navigation & smart intellisense features.  We've introduced bugs in the code when doing a 'rename' because we trusted Visual Studio to do the right thing.

![findallreferences](https://user-images.githubusercontent.com/12090616/68167306-0db6a780-ff33-11e9-96d8-7c421237243b.jpg)

**Comment by davkean** [comment]
@petehauge As per an internal thread:

```
So we aren’t wiring up the project to project reference because there’s a mismatch of output paths. The project claims its output path is:

%USERPROFILE%\source\repos\FunctionApp4\bin\Debug\netcoreapp2.1\FunctionApp4.dll

but the Unit Test project is referencing it via:

%USERPROFILE%\source\repos\FunctionApp4\bin\Debug\netcoreapp2.1\bin\FunctionApp4.dll

It looks like the Azure functions build is hooking GetTargetPath which is adding the extra “bin”.
```

This an Azure functions issue.

**Comment by davkean** [comment]
As per internal, this is a build issue. Azure functions should avoid manipulating the output path.
