### ISSUE TITLE
Unable to add datasource in designer

### ISSUE THREAD

**Issue by ShemJM** [dotnet/project-system#5634]
I am trying to add a datasource to my C#, WPF, .net core 3.0 application. After choosing my data connection in the wizard I press next then get this error 

![image](https://user-images.githubusercontent.com/42591036/68426845-e402b800-01a0-11ea-9e51-36ec989866cf.png)

If I start a fresh project and try to add a datasource I get this error at the end of the wizard:

![image](https://user-images.githubusercontent.com/42591036/68427101-69866800-01a1-11ea-9f08-90ce499bc063.png)

It works fine in a .net framework application.

**Comment by davkean** [comment]
I've moved this over to us, @davidwengier please take a look. @ShemJM What version of VS are you using, 16.3?

**Comment by davidwengier** [comment]
Will have to dig in, this used to work, but looks like there were recent changes that change how the window works with .NET Core projects and might have exposed a pre-existing bug (Microsofties: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/978885/)

**Comment by ShemJM** [comment]
Thanks, yes I am using 16.3. Good luck with the fix.

**Comment by davidwengier** [comment]
This is happening because the single file generator isn't creating the `.Designer.cs` file until after the Data Source Wizard goes to look for it.

**Comment by davkean** [comment]
Ah, single file generation is probably async. I wonder if the wizard can force generation via the ProjectItem

**Comment by davkean** [comment]
Yeah they can via https://docs.microsoft.com/en-us/dotnet/api/vslangproj.vsprojectitem.runcustomtool?view=visualstudiosdk-2017.

**Comment by davidwengier** [comment]
Logged an issue internally for this at AB#1027669. I will update this issue as the status of that changes.

**Comment by ShemJM** [comment]
I have updated to the latest version of visual studio and the data sources window now seems to be broken.

![image](https://user-images.githubusercontent.com/42591036/70694066-abca2a00-1cb6-11ea-8da3-ebf46292d8ec.png)

I think this is relevant to this issue. 

Although I can now add data tables using the wizard if I use the toolbox.

**Comment by davidwengier** [comment]
The internal issue linked above was resolved.
