### ISSUE TITLE
Support "View in Object Browser" for framework references

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5643]
~The "View in Object Browser" context menu currently does nothing for framework references.~

~It should either be removed or made to work.~

The "View in Object Browser" menu item was removed from framework references in https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/231736?_a=files.

We could bring it back and make it work.

![image](https://user-images.githubusercontent.com/350947/68764403-bf11b780-066e-11ea-89f6-48f617a6bd5f.png)

**Comment by davkean** [comment]
I'm not sure I agree on this - I think this should open the Object Browser with all the assemblies in that Framework reference in the same way that you can filter the list for a given TFM.

**Comment by drewnoakes** [comment]
@davkean updated issue to keep the option of showing all open. Personally I think opening ~100 assemblies probably isn't what the user wants, and that we should allow expanding to show contained assemblies which may then be opened individually or in aggregate via multi-selection.

**Comment by davkean** [comment]
@drewnoakes If they don't want that, they can dig down to the individual assemblies. Right now we have an experience gap where you don't get the following for .NET Core:

![image](https://user-images.githubusercontent.com/1103906/68814487-16df0b80-06cd-11ea-9327-261c3b17f2c3.png)
