### ISSUE TITLE
Design-Time Target Failure Causing Loading Errors

### ISSUE THREAD

**Issue by 333fred** [dotnet/project-system#5653]
I have a branch of roslyn, https://github.com/333fred/roslyn/tree/xlf-break, that demonstrates this issue. The xlf task running during the design time build fails because the xlf files are out of date, and that causes the project to be incorrectly loaded by the project system. This causes a myriad of non-obvious downstream issues, including partial intellisense/highlighting, missing framework types, and other issues that result from missing data. The project system should be resilient to this. I saved the logs from the design-time builds and have them saved here: `\\mlangfs1\public\frsilb\logs\project-system-design-time-5653`. /cc @tmat

**Comment by 333fred** [comment]
I've also filed a separate issue on xliff-tasks about not running their tasks during the design-time build, https://github.com/dotnet/xliff-tasks/issues/233, but even if we can't do anything more than putting something in the error list to indicate the design-time failure, we need to a better job here. I only discovered about this failure after attempting to load the solution in omnisharp and seeing that complain about failing the project load because of the failing targets.

**Comment by drewnoakes** [comment]
The error here (for `src\Compilers\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.csproj`):

> C:\Users\drnoakes\.nuget\packages\xlifftasks\0.2.0-beta-63004-01\build\XliffTasks.targets(92,5): 'xlf\CSharpResources.cs.xlf' is out-of-date with 'CSharpResources.resx'. Run `msbuild /t:UpdateXlf` to update .xlf files or set UpdateXlfOnBuild=true to update them on every build, but note that it is strongly discouraged to set UpdateXlfOnBuild=true in official/CI build environments as they should not modify source code during the build.

Design-time builds run with the `ContinueOnError` property set to `ErrorAndContinue` which is intended for this kind of thing, so one fix would be to change xliff-tasks to respect that property, though it's somewhat VS specific.

Looking at the xliff-tasks README, that package supports the following option:

> `ErrorOnOutOfDateXlf` - When set to true the build will produce an error if the .xlf files are out-of-date with respect to the source files. Defaults to true.

So we could set `ErrorOnOutOfDateXlf` to `false` for design-time builds.

Should XLF targets even run during design-time builds? I haven't worked out what's triggering them.

![image](https://user-images.githubusercontent.com/350947/69200911-c23a0580-0b90-11ea-9e1d-ccc9653cd80c.png)

**Comment by davkean** [comment]
It should run for design-time builds, they need to respect it, see: https://github.com/dotnet/xliff-tasks/issues/36.

**Comment by davkean** [comment]
@333fred Did the error not show up in the Error LIst?

**Comment by 333fred** [comment]
@davkean nope. I got no errors of any kind, just the weird vs state when only partial types are available. I could go to def on things in the current file, for example, but not defined elsewhere. You can repro with the branch I linked to in my fork, browse around the CSharp compiler project. I was specifically in LanguageParser.cs when I saw the issue.

**Comment by drewnoakes** [comment]
Filed https://github.com/dotnet/xliff-tasks/pull/234 which I believe should fix this problem.

**Comment by jjmew** [comment]
@nguerrera and @tmeschter  this is an issue that should be tracked in xliff-tasks as it is not a project system problem. Unfortunately we don't have the ability to transfer the issue. Can you transfer it?

**Comment by 333fred** [comment]
@jjmew the reason I opened a bug both here and on xliff was because of the bad experience around the failure. There was literally no indication in VS that something had failed: just bad info.

**Comment by drewnoakes** [comment]
Fixed in https://github.com/dotnet/xliff-tasks/pull/297.
