### ISSUE TITLE
Changing .NET Core WPF project item from None to Resource does not embed item in output assembly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5658]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/802033/in-sdk-style-csproj-changing-build-action-between.html). Please vote and comment there to make sure your voice is heard._

---
This issue is present in VS2019 16.3.7, when targeting WPF and .NET Core 3.0 or .NET Framework 4.7.2 with the new SDK-Style .csproj format.

When changing [Build Action] for a file between [None] and [Resource] in SDK-Style .csproj, the Output dll/exe is not correctly recreated on Build (if there are no other changes triggering a recompile) - we have to do a Rebuild to get the desired effect! 

NOTE: The Build command seems to do _something_, but the size of the resulting dll/exe does not reflect the removal/addition of the built-in resource content. After a Rebuild (or after changing code etc and doing another Build) the size of the dll/exe is corrected.

Interestingly enough, the same issue does not seem to apply when switching between [None] and [EmbeddedResource].

The issue can easily be reproduced:

* Create a new WPF application (with SDK-style .csproj file).
* Drop an image file or similar with a size that's large compared to the application .dll/.exe output (just to easily spot the size difference when the image is embedded or not). 
* Initially the image file will have [Build Action = None]. Build the app and note the size of the output dll/exe. 
* Then change to [Build Action = Resource] and Build again (not Rebuild, and no code change in between). 
* The build seems to update the dll/exe, but the output size does not change.
* Now, do a Rebuild (or change a source-code file and Build). The output size will change.

The above steps can be used to repeatedly reproduce the (wrong size) issue by toggling between [None] and [Resource] - doing a build does not change the size, but doing a Rebuild correctly updates the size (of the output dll/exe).

---
#### Visual Studio Feedback System on 11/1/2019, 04:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sara Liu [MSFT] on 11/4/2019, 06:17 PM: 

<p>Thank you for your feedback, this issue has been escalated for further investigation and if there is any process, I will inform you immediately.</p>

---
### Original Solutions
(no solutions)

**Comment by drewnoakes** [comment]
I intend to transfer this to https://github.com/dotnet/wpf but no longer have permission to do so. However this may be related to a GitHub outage seen today, so will try again later before escalating.

**Comment by sharwell** [comment]
@terrajobst can you transfer this issue for us?

**Comment by dmonroym** [comment]
Closing. Will be tracking this in https://github.com/dotnet/wpf/issues/2240

**Comment by terrajobst** [comment]
@sharwell:

> To transfer an open issue to another repository, you must have write permissions on the repository the issue is in and the repository you're transferring the issue to. 

FYI: You no loner need owner/admin status for that but you're probably lacking push permissions in WPF.

**Comment by sharwell** [comment]
@terrajobst Correct. After the permissions change we aren't sure who has push access to both project-system and wpf, but I figured if anyone does it's you. 😄
