### ISSUE TITLE
Debugging program with environment variables

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5667]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/353814/debugging-program-with-environment-variables.html). Please vote and comment there to make sure your voice is heard._

---
<p>In the debugging panel of a .Net application: </p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/43600-debugging.png"> Image:43600-debugging.png</a></p><p>there should be an option to set environment variables. </p><p>Basically the same as &quot;Command line arguments&quot;. </p><p>In addition, it would be nice to call a &quot;setup.bat&quot; setting this environment variables before calling the executable. </p><p>It would then be easy to debug applications which need to run in a visual studio command line (for example).</p>

---
#### Fiona Niu[MSFT] on 10/15/2018, 02:43 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about five business days on our next steps. </p>
#### Angelos Petropoulos [MSFT] on 4/1/2019, 10:44 AM: 

<p>Here is how you deal with environment variables in ASP.NET Core: <a target="_blank"> https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.2 </a></p>

#### James Chaldecott on 4/1/2019, 01:55 PM: 

<p>This report is <strong>clearly</strong> about standalone .Net executables, not ASP.NET or ASP.NET Core. It's really unhelpful to post a link to an unrelated help page and then close the report.</p>

#### Angelos Petropoulos [MSFT] on 4/3/2019, 11:08 AM: 

<p>Really sorry about that, it was an honest mistake. I've re-opened the feedback ticket to allow other community members to also vote on it. The appropriate team will review and update the status accordingly.</p>

#### Angelos Petropoulos [MSFT] on 4/3/2019, 11:08 AM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

#### James Chaldecott on 4/4/2019, 00:48 AM: 

<p>Thanks.</p><p>For context, my use case is using the Microsoft.Extensions.Configuration system from a .Net Framework console application.</p>

**Comment by davkean** [comment]
Triage: This is the legacy project system's version of the Debug properties pages. For SDK-projects, we have a new Debug property page that lets you set environment variables. This would be the part of the same story of enabling customers to opt into CPS for legacy projects, which we are tracking via https://github.com/dotnet/project-system/issues?q=is%3Aopen+is%3Aissue+label%3AParity-Legacy-API+label%3AParity-Legacy.

@jjmew Can you deal with feedback ticket for this one?
