### ISSUE TITLE
Add support for module references for .NET projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5669]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/814199/add-support-for-module-references-for-net-projects.html). Please vote and comment there to make sure your voice is heard._

---
Additional item in References

---
#### Visual Studio Feedback System on 11/11/2019, 01:01 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by davkean** [comment]
Triage: I don't think this would ever bubble up as a priority as modules are an advanced concept that we don't have great tooling around anyway, with the move to .NET Core modules have been deemphasized. 
@jjmew Can you deal with the Feedback ticket?
