### ISSUE TITLE
GacUtil in Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5670]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/801401/gacutil-in-visual-studio.html). Please vote and comment there to make sure your voice is heard._

---
<p>Hello</p><p>The most common change we always make to a new project here at Fujitsu, is adding the newly created dll to the GAC. We do it in the Post build event command line box, like this:</p><p>&quot;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\gacutil.exe&quot; /if &quot;$(TargetPath)&quot;</p><p>Sometimes, after major updates to Windows the gacutil is located in a different location, and we need to change this in all projects.</p> <p>My suggestion is:<br>Could you create a checkbox in the Build events tab that says:<br>Add to Assembly Cache on succesful build? Yes| No</p><p>Best regards,</p><p>Axel</p>

---
#### Visual Studio Feedback System on 11/1/2019, 00:21 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by cartermp** [comment]
Even though this project system is primarily for .NET Core, I moved this here to see if we'd consider it since you can use .NET SDK-style here

**Comment by davkean** [comment]
Thanks for the suggestion. We have no plans to invest in this area. 

As a workaround, to avoid the path changing, you can refer to it using an environment variable: 

```
"%WindowsSDK_ExecutablePath_x64%\Gacutil" /if "$(TargetPath)"
```
