### ISSUE TITLE
Add a way to add <Nullable> to csproj without having to edit manually the file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5671]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/795142/add-a-way-to-add-to-csproj-without-having-to-edit.html). Please vote and comment there to make sure your voice is heard._

---
Today when we create a NET Core 3  app with C# 8 nullables are not enabled by default. Why is this, I will never understand it. THe only way to enable them is to manually editing the csproj file and add <Nullable> tag to it. Why can't we just go in VS2019 to the project properties and check a box that would enable nullables? Please add this checkbox, can't be too difficult and will save us having to manually edit the csproj file.

---
#### Visual Studio Feedback System on 10/28/2019, 01:28 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by drewnoakes** [comment]
Agree this would be a useful feature.

Duplicates #4058.
