### ISSUE TITLE
EnvDTE.ProjectItem.Value.Object as VSLangProj.VSProjectItem RunCustomTool in T4 Template freeze visual studio.

### ISSUE THREAD

**Issue by malylemire1** [dotnet/project-system#5679]
**Visual Studio Version**:
2019 Professional

**Summary**:
Was working fine with old project format.

EnvDTE.ProjectItem.Value.Object as VSLangProj.VSProjectItem RunCustomTool freeze visual studio in T4 Template with new project format.

When debugging the T4 template everything seems to run.

**Steps to Reproduce**:

1. Add a T4 template to a new class library project. (Tested for .net standard but the problem is the same for .net 4.8)

2. Add a Resx file file with custom tool set to `PublicResXFileCodeGenerator`.

3. Get all project items.
   ```c#
    foreach (EnvDTE.ProjectItem file in items)
	{
	    if (file.Object != null && file.Object is VSProjectItem)
	    {
	        var projectItem = (VSProjectItem)file.Object;
	        if (projectItem.ProjectItem.Name.EndsWith(".resx"))
	        {
	            projectItem.RunCustomTool();
	        }
	    }
	}
   ```

**Expected Behavior**:
Visual studio should not freeze.

**Actual Behavior**:
Visual studio freeze.

**Comment by davkean** [comment]
Triage: This was likely regressed in the recent changes around generators.

**Comment by davidwengier** [comment]
This doesn't repro for me.
