### ISSUE TITLE
Add retargeting support

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5691]
CPS currently implements IVsRetargetProjectAsync so we need to validate or possible expand that support, and then implement WinUI retargeting on top of it.

* Property Pages
* Template wizard
* IVsRetargetProject retargeting (retargeting entire solution to new version, prompting when prerequisite is missing)

Retargeting .NET Core projects should be considered too, and could be a way to work on this without being blocked on WinUI support.

**Comment by davkean** [comment]
Have a look at how we did this for UWP/Portable/Phone here: http://index/?leftProject=Microsoft.VisualStudio.ProjectFlavoring&file=Microsoft%5CVisualStudio%5CProjectFlavoring%5CRetargeting%5CVsRetargetProjectManager.cs. I would port this as it adds a simplified layer (separating into "Acquisition" and "Retargeting") over IVsRetargetProject

**Comment by davkean** [comment]
Although bear in mind that looks like it changed to hardcode Windows SDK platforms for some reason, which should be removed.

**Comment by davkean** [comment]
We should factor in missing SDKs, and the aquisition of SDKs.

**Comment by davkean** [comment]
Triage: This needs to be filled out with actual scenarios; MSBuild SDK, targeting packages, Xamarin SDK, etc and broken up into features.

**Comment by davidwengier** [comment]
Duping this against #6080
