### ISSUE TITLE
Project System: Changes to project file are not reflected in the Properties page tab (no * appears)

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#57]
_From @davkean on April 29, 2016 17:56_
1. Create a new project (say WPF project).
2. Right click on the project an click on properties, keep it open.
3. Right click and add reference to the project.

Actual : No \* appears next to the file name in the tab header. It appears if I close the tab and open it again via Right click -> properties on the project.

Expected : \* should appear indicating that there are unsaved changes to the project file.

_Copied from original issue: dotnet/roslyn#10980_

**Comment by Giftednewt** [comment]
@davkean I've debugged this on VS15 Preview 3 and it does update the dirty status of the tab, but there is a massive delay (~2mins on my PC) before OnAfterAttributeChange gets called.

From what I can see this is called directly from VS so is outside the control of the project system.

**Comment by davkean** [comment]
Yes but that's probably called in response to the underlying csproj.dll firing an event to tell the RDT that it's changed, which in turn will call listeners to IVsRunningDocTableEvents. What's the stack at the time of this method being called? Is csproj.dll on the stack (you'll need to turn on native debugging).

**Comment by Giftednewt** [comment]
Ok I've enabled native debugging and this is the call stack

	Microsoft.VisualStudio.AppDesigner.dll!Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.OnAfterAttributeChange(UInteger docCookie, UInteger grfAttribs) Line 1611	Basic
 	[Native to Managed Transition]	
 	msenv.dll!<lambda>(void)()	Unknown
 	msenv.dll!CCookieTable<class ATL::CComPtr<struct IVsRunningDocTableEvents>,struct DefaultCookieTraits<unsigned long,1,4294967295,0,1>,struct DefaultValueTraits<class ATL::CComPtr<struct IVsRunningDocTableEvents> > >::for_each<class <lambda_e715a5a65f3109938e0e279d252a656b> >(class <lambda_e715a5a65f3109938e0e279d252a656b>,bool)	Unknown
 	msenv.dll!CRunningDocTable::Impl::NotifyOnAfterAttributeChange(unsigned long,unsigned long,struct IVsHierarchy *,unsigned long,unsigned short const *,struct IVsHierarchy *,unsigned long,unsigned short const *)	Unknown
 	msenv.dll!CRunningDocTable::NotifyOnAfterAttributeChange(unsigned long,unsigned long,struct IVsHierarchy *,unsigned long,unsigned short const *,struct IVsHierarchy *,unsigned long,unsigned short const *)	Unknown
 	msenv.dll!CRunningDocInfo::NotifyOfAttributeChange(unsigned long)	Unknown
 	msenv.dll!CRunningDocInfo::IsDocumentDirty(void)	Unknown
 	msenv.dll!CRunningDocTable::IsDocumentDirty(unsigned long)	Unknown
 	msenv.dll!CDisasterRecoverySaveComponent::TrySaveCheckpoint(unsigned long,bool,struct IVsTask * *)	Unknown
 	msenv.dll!CDisasterRecoverySaveComponent::DoNextTask(void)	Unknown
 	msenv.dll!std::_Func_impl<class <lambda_0e4cd9124caac87ddd8ea66c8b1662d0>,class std::allocator<int>,long,struct IVsTask *,unsigned long,struct IVsTask * *,struct tagVARIANT *>::_Do_call(struct IVsTask * &&,unsigned long &&,struct IVsTask * * &&,struct tagVARIANT * &&)	Unknown
 	msenv.dll!std::_Func_class<long,struct IVsTask *,unsigned long,struct IVsTask * *,struct tagVARIANT *>::operator()(struct IVsTask *,unsigned long,struct IVsTask * *,struct tagVARIANT *)	Unknown
 	msenv.dll!`anonymous namespace'::NativeVsTaskBody::DoWork()	Unknown
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.VsTask.GetCallbackForMultipleParent.AnonymousMethod__0(System.Threading.Tasks.Task<object>[] _)	Unknown
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.VsTask.GetCallback.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<object>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task task)	Unknown
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.TaskSchedulerService.VsUIThreadBlockableTaskScheduler.DoOneTask()	Unknown
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.TaskSchedulerService.VsIdleTimeScheduler.FDoIdle(uint grfidlef)	Unknown
 	[Native to Managed Transition]	
 	msenv.dll!SCM::FDoIdleLoop(int,enum MSOIDLE,unsigned long)	Unknown
 	msenv.dll!SCM::FDoIdle(enum MSOIDLE)	Unknown
 	msenv.dll!SCM_MsoStdCompMgr::FDoIdle(enum MSOIDLE)	Unknown
 	msenv.dll!MainMessageLoop::DoIdle(struct IMsoStdComponentMgr *)	Unknown
 	msenv.dll!CMsoCMHandler::EnvironmentMsgLoop(void)	Unknown
 	msenv.dll!CMsoCMHandler::FPushMessageLoop(unsigned long)	Unknown
 	msenv.dll!SCM::FPushMessageLoop(class SCMI *,unsigned long,void *)	Unknown
 	msenv.dll!SCM_MsoCompMgr::FPushMessageLoop(unsigned long,unsigned long,void *)	Unknown
 	msenv.dll!CMsoComponent::PushMsgLoop(unsigned long)	Unknown
 	msenv.dll!VStudioMainLogged(void)	Unknown
 	msenv.dll!_VStudioMain()	Unknown
 	devenv.exe!util_CallVsMain(struct MAINPARAM *,int *)	Unknown
 	devenv.exe!CDevEnvAppId::Run(unsigned short *,int)	Unknown
 	devenv.exe!_WinMain@16()	Unknown
 	devenv.exe!operator new[](unsigned int)	Unknown
 	kernel32.dll!749762c4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	
 	ntdll.dll!77770609()	Unknown
 	ntdll.dll!777705d4()	Unknown

csproj.dll doesn't appear in there. Looks like it's firing off an idle timeout

**Comment by davkean** [comment]
This only repros in the the legacy project system. Given all of our investment is the new project system, I'm going to won't fix this.
