### ISSUE TITLE
Debug menu shows on Shared Projects

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#570]
![image](https://cloud.githubusercontent.com/assets/1103906/19208283/49df546a-8cad-11e6-955f-73f31612806f.png)

**Comment by davkean** [comment]
Punting.

**Comment by srivatsn** [comment]
Pulling this into 15.1 - we're seeing bunch of VSFeedback around this (for eg: https://developercommunity.visualstudio.com/content/problem/22367/vs-2017-rc-project-properties-window-debug-tab-con.html). There's a MSFT person on that thread who says they can repro as well. @davkean can you try reaching that person?

**Comment by davkean** [comment]
Fixed in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/226430.
