### ISSUE TITLE
Deleted folder does not appear in Recycle Bin

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5710]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/829439/deleted-folder-does-not-appear-in-recycle-bin.html). Please vote and comment there to make sure your voice is heard._

---
[regression] [worked-in:Visual Studio 2017 Professional]
Deleting a folder from a C# project does not move it to Recycle Bin. Instead, it completely removes the folder from the file system.

---
#### Visual Studio Feedback System on 11/22/2019, 08:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sara Liu [MSFT] on 11/26/2019, 08:32 PM: 

<p>Thank you for your feedback and taking the time to reach out to us.<br>
According to your description, I suppose the folder that you deleted is a Solution Folder, which directly under the Solution name and we can right click the Solution name and choose Add -&gt; New Solution Folder to create it, right?<br>
Solution Folders are an organizational tool in Solution Explorer, corresponding Windows folders are not created. After you remove this solution folder, it will not display inside the Solution Explorer, but go to the Solution root store folder, those projects or files under this solution folder should still existing.<br>
When we right click the Solution folder, it displays ‘Remove’ button and if we right click one folder under the one project, it displays ‘Delete’ button and click this button will delete tis folder to Recycle Bin folder as expected.<br>
If I made any misunderstandings, please feel free to let us know.</p>

#### Razvan Chisa on 11/27/2019, 03:06 AM: 

<p>I have already mentioned that my problem is about folders inside a C# project, not solution folders.</p><p>I just noticed that this problem reproduces only on .NET Core projects and I have attached numbered pictures with steps on how to reproduce the problem: <a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/106906-folderdelete.zip" target="_blank">FolderDelete.zip</a></p><p>Thank you</p>

#### Sara Liu [MSFT] on 11/27/2019, 01:11 PM: 

<p>Thanks for your correction and sorry for my mistake, I can reproduced this issue through your shared steps and this issue has been escalated for further investigation, if there is any process, I will inform you immediately.</p>

---
### Original Solutions
(no solutions)

**Comment by drewnoakes** [comment]
In CPS, the enum member `DeleteFromStorage` will be a good place to start looking.

**Comment by drewnoakes** [comment]
Fixed by @melytc in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/220070.

**Comment by RyanGaudion** [comment]
My xamarin solution has been deleted and is not in recycle bin. How can I get these files back?

**Comment by melytc** [comment]
Hi @RyanGaudion, sorry to hear that. I am able to repro this: folders and files are correctly moved; however, when I delete a project, it's removed from the VS Solution Explorer, but can still be found in File Explorer. 

![image](https://user-images.githubusercontent.com/8518253/74767383-9f74c700-523b-11ea-8284-dfb770a8cfc8.png)

I'll open a new issue for this. Thanks for the feedback :)

**Comment by drewnoakes** [comment]
@RyanGaudion do you mean that your entire solution is missing, or just the .sln file? How did you delete it?
