### ISSUE TITLE
Add a  reference to CPS project, it does not display in the Assemblies list

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5712]
_Copied from [AB#719762](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/719762)_

**Affected Branch:** d16.0

**Affected Build:** 28229.52

**Steps to reproduce:**

1. Copy CPS template(all zip files) from \\vspfs3\public\CPS\Templates\ProjectTemplates\Visual C#\CPS Barebone to local machine template path, such as %USERPROFILE%\Documents\Visual Studio 2019\Templates\ProjectTemplates\Visual C#
2. Restart VS

3. Search CPS in the top right of new project dialog

4. Select "CPS C# Windows console application" -> Create

5. Open add reference dialog

6. Add a reference to project, eg: “Microsoft.Build”

**Expected result:**  

The reference is added successfully, it displays under Assemblies node

![image](https://user-images.githubusercontent.com/754264/70588687-a078ef00-1c21-11ea-8200-ee0b54a0a452.png)

**Actual result:** Reference does not display under Assemblies node

 Sometimes, when clicking on the Dependencies or Assemblies node, it will display.

please refer the video: `\\vspfs3\public\v-nzicol\CPS\addReferenceError.mp4`

**Comment by drewnoakes** [comment]
For context, the repro steps given here require using CPS project templates that are not shipped anywhere.

**Comment by davkean** [comment]
Triage: This only repros in CPS barebone so we're not going to fix this unless it can be hit in a C#/VB/F# project, we don't support the dependency node outside of that. We'll happily take contributions to fix this - but we're not going to address this.
