### ISSUE TITLE
VS hangs every time when opening MessagePack.sln

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5713]
_Copied from [AB#801326](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/801326)_

**Repro steps:**
git clone https://github.com/AArnott/MessagePack-CSharp.git
cd MessagePack-CSharp
notepad sandbox\PerfNetFramework\PerfNetFramework.csproj
Add the following line to the first PropertyGroup and save the file.
    <Platforms>x86</Platforms>

Use Visual Studio 2019 to open MessagePack.sln

Hangs about halfway through synchronous solution open.
Dump file: https://microsoft-my.sharepoint.com/:u:/p/andarno/EfHFHj9yCqpPizs4OCIDJL0B6IEAG3JBAyT4pQTSp3SjNg?e=cvYVXn
Stacks and !dumpasync: see text file attached to above linked Azure DevOps issue

**Comment by davkean** [comment]
Dup'ing against https://github.com/dotnet/project-system/issues/3425. The root cause is that we don't have a way to handle configuration switches during soluton load which causes us to wait for init of the language service that will never complete. This is being tracked by the API additional.
