### ISSUE TITLE
Add telemetry points to Property Pages

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5714]
_Copied from [AB#827704](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/827704)_

Today, we lack telemetry to tell us which property pages pages are used, and which parts of a given property page are used. Because of this, we only know how many people open the property pages, which is not enough to inform which ones need work the most.

**Comment by davidwengier** [comment]
@melytc this may be already covered by https://github.com/dotnet/project-system/pull/5575 ? If so, feel free to close this.

**Comment by davkean** [comment]
Closing this for the work we did in https://github.com/dotnet/project-system/pull/5575, feel free to reopen if its not enough.
