### ISSUE TITLE
Regression in CPS load time in d16.1 on solutions with 260+ projects

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5715]
_Copied from [AB#842321](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/842321)_

Scalability measurement of CPS-ProjectSystem for d16.1 on VS (Version:[28802.258.d16.1]]). The solution load time is longer than 16.0P4. Here is the compared result as below:

![image](https://user-images.githubusercontent.com/754264/70589118-074ad800-1c23-11ea-9362-5c4d81a94d59.png)

Get the solution from: `\\vspfs3\Public\v-chzu\ProjectSystem`

**Comment by davkean** [comment]
This is a old regression that we're no longer tracking.
