### ISSUE TITLE
Regressions for CPS memory usages in 16.3 P2 master ([29131.210.master])

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5720]
_Copied from [AB#961468](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/961468)_

Scalability measurement of CPS-ProjectSystem for d16.3P2 master on VS (Version:[29131.210.master]]). Here is the compared result as below:
![image](https://user-images.githubusercontent.com/754264/70590408-bc32c400-1c26-11ea-85f2-a8a9b9fef4f9.png)

![image](https://user-images.githubusercontent.com/754264/70590414-bf2db480-1c26-11ea-928e-7aebb385df5d.png)

Get the solution from: \\vspfs3\Public\v-chzu\ProjectSystem

Get the ETL trace when VS open 1300 projects from :
\\vspfs3\Public\v-chzu\ETLTrace_CPS

**Comment by panopticoncentral** [comment]
We've gotten back to 1560 projects in 16.4 after a number of fixes.
