### ISSUE TITLE
MSBuild process constantly starting and ending

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5721]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/667419/msbuild-process-constantly-starting-and-ending.html). Please vote and comment there to make sure your voice is heard._

_Copied from [AB#961596](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/961596)_

---
The MBuild process seeems to be starting and stopping constantly. Looks like it's related to the FbCommand, FbConnection, etc. classes and the icons being shown. These classes ultimately derive from `Component` and that might be some clue.

More info [here](https://twitter.com/cincura_net/status/1156129203294810112) and [here](https://twitter.com/cincura_net/status/1156129531956273153), link to repository included.

Happens on 16.1 and 16.2.

---
#### Jiri Cincura on 30/07/2019, 08:57 PM: 

<p>It might be affecting debugging as well - making changes and hence ending with https://twitter.com/cincura_net/status/1149582471584870400.</p>

#### Visual Studio Feedback System on 31/07/2019, 05:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 06/08/2019, 07:09 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by davkean** [comment]
Closed in this lieu of the AzureDevOps bug which is assigned to Roslyn.

**Comment by davkean** [comment]
The other side of this was fixed in https://github.com/dotnet/project-system/pull/6567.
