### ISSUE TITLE
PLM: OP stuck in PackageRestoreProgressTracker - project.assets.json not getting created

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5724]
_Copied from [AB#1032715](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1032715)_

**Dump:** 
`\\scratch2\scratch\peterspa\devenv intellisense stuck.zip`

**Repro steps:**
1. Install VS from master branch: https://aka.ms/vs/16/int.master/vs_enterprise.exe
2. Open PowerShell and run `Set-ExecutionPolicy Unrestricted`
3. `cd \\vspfs3\Public\AdrianV\Tools\Operation Progress\`
4 `. .\PartialLoad-Enable.ps1`
5. Open and close VS
6. In razzle prompt:
    * `src\Xaml\Designer\Tools\setrazzle.cmd`
    * `bt`
    * `vstis <test>`

**Test Run:**
https://devdiv.visualstudio.com/DevDiv/_apps/hub/ms.vss-releaseManagement-web.cd-release-progress?_a=release-environment-extension&releaseId=525314&environmentId=2717276&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab

**Impacted tests:**
AdornerProviderTest_WpfCore
ContextMenuProviderTest_WpfCore
ValidateLegacyAttributeLoadingInCore
SurfaceIsolation_OpenMahAppsMainWindow
SurfaceIsolationExploration_WPFCore
SurfaceIsolationExploration_UAP(pathToSolution: Projects\Windows-appsample-customers-orders-database\Contoso.sln) - UAP.LatestVersion.VS
SurfaceIsolationExploration_UAP_RS2Projects(solutionPath: Projects\Windows-appsample-customers-orders-database\Contoso.sln) - UAP.LatestVersion.VS

**Comment by spadapet** [comment]
This seems to only repro on one of my machines. I can't find any way to repro this failure on another machine and not even in other folders on that same repro machine. It _only_ repros with the test project folder as created by the XAML integration test. So if you need to debug anything on my machine, I'll help.

**Comment by davkean** [comment]
@spadapet Can you repro this manually? If so, capturing design-time build logs via https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#visual-studio-2017-or-later would be extremely helpful.

**Comment by spadapet** [comment]
@davkean I finally saw your question. Yeah I installed that extension, turned on logs, opened the project that never finishes intellisense, and here's the logs:

[BuildLogs.zip](https://github.com/dotnet/project-system/files/3970573/BuildLogs.zip)

Hope that helps. I can repro any time.

**Comment by spadapet** [comment]
It's funny that I can't view the build log because the intellisense build is stuck :)

![image](https://user-images.githubusercontent.com/2523431/70950642-12807800-2016-11ea-9762-66ea06bd7955.png)

**Comment by davkean** [comment]
@spadapet This was fixed in 16.5, can you verify if your tests are still hitting this and if so, tell me?

**Comment by spadapet** [comment]
> @spadapet This was fixed in 16.5, can you verify if your tests are still hitting this and if so, tell me?

Sure thing, I'll run the tests today. If I don't comment again then they worked.

**Comment by spadapet** [comment]
Yep, the tests work. Thanks!
