### ISSUE TITLE
[Cloud] Modifying a project on the server does not cause NuGet restore to run

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5726]
_Copied from [AB#1020118](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1020118)_

**Steps to reproduce:**

1. Create a .NET Core project and load it up in a cloud server (using these instructions).
2. Connect using a client.
3. On the server, use Notepad to edit the project to add <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />

**Expected result:**

NuGet restore is run on the server. The corresponding project.assets.json file is updated. On the client, the Newtonsoft.Json package shows up under the Dependencies node.

**Actual result:**

NuGet restore does not seem to run. The assets file isn't updated, and the client does not show the package.

**Note:** the underlying bug is tracked in https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1025608. This issue tracks verification of the scenario once that bug is fixed.

**Comment by tmeschter** [comment]
I've verified that this is fixed. Editing the .csproj file causes the project.assets.json to be regenerated, the Dependencies node and its children update appropriately, and types from the package show up in Intellisense.
