### ISSUE TITLE
[Cloud] Build behavior is inconsistent in .NET Core project

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5727]
_Copied from [AB#1006986](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1006986)_

**Client build:** 29423.80.master
**Server build:** 29423.80.master
**LS:** "\\cpvsbuild\drops\cascade\vs\Insiders\master\1.0.1067\drop\Microsoft.VisualStudio.LiveShare.vsix"

**Steps to reproduce:**

1. Follow the steps in Setup and Configure a static Online Environment to set up a client/server

2. Clone https://github.com/Microsoft/TailwindTraders-Desktop at 71f74ad62650b7387a6f133c17da7c1a07d21365 on the server

3. Launch the server and open CouponReader.sln by default:

    - devenv …\CouponReader.sln /server /joinworkspace "vsls:?share=true&workspaceId=ID"

4. Connect client to the server

    - devenv /client /joinworkspace "vsls:?remoteJoin=true&workspaceId=ID"

5. Invoke "Rebuild All" over and over

**Observed:**

Inconsistent build results and output each time

**Expected:**

First build succeeds and builds succeed and do nothing (and still succeed)

**Comment by tmeschter** [comment]
1. The solution in question contains .NET Framework projects (more specifically, non-SDK-style projects). These are unsupported in VS Online at this time.
2. Even so, I was unable to reproduce any build problems.
