### ISSUE TITLE
WPF and Windows Forms nodes are showing up in Add New Item

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#573]
![image](https://cloud.githubusercontent.com/assets/1103906/19208697/862c4950-8cb2-11e6-8564-d31ec60adbf8.png)

**Comment by jjmew** [comment]
This repros in CSProj too. It doesn't sound like this is a regression.

**Comment by etbyrd** [comment]
This issue seems to have been fixed in dev16 in both project systems.
