### ISSUE TITLE
ProjectServices should dedup strings coming from MSBuild

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/project-system#5730]
Looking at memory dumps of large solutions, one source of duplicate strings is the ProjectServices's `DesignTimeBuildResultCache` object. @drewnoakes did a bunch of work to dedup strings when saving to and loading from the cache, but this situation is where the cache was empty and we ran a design-time build. We should consider whether we could dedup strings in this case at least within an individual cache (since there are likely going to be overlaps) and ideally across all of the strings in the cache?

**Comment by drewnoakes** [comment]
I remember talking to @lifengl around the time I worked on Project Services and IIRC he said that MSBuild already de-dupes strings.

When I look at this I'll verify by inspecting dumps.

**Comment by davkean** [comment]
This was moved to 16.5 - but we've already booked for that unless you pick this up Paul. I've unassigned the milestone, we'll pick this up in triage.

**Comment by drewnoakes** [comment]
@lifengl's comment was here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/603660

> MSBuild result will always reuse the same string, (especially for built in values like true/false).  But when DTBB reads from cache, it creates different strings in the memory for each value.  We can have a simple fix to prevent all the duplications.

I fixed the cache dupes a month or so back. When I get to this issue I'll look at some dumps to see if it still applies.

**Comment by panopticoncentral** [comment]
Actually, I realized this was a mistake on my part -- because the solution duplicates projects, it was creating false duplicates.

**Comment by drewnoakes** [comment]
De-duping across projects may be helpful in some cases. We should get metrics on real-world solutions rather than synthesized ones.
