### ISSUE TITLE
Accept Platform "AnyCPU" for a solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5737]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/426844/accept-platform-anycpu-for-a-solution.html). Please vote and comment there to make sure your voice is heard._

---
<p>Please change build of a solution to treat &quot;AnyCPU&quot; the same as it does &quot;Any CPU&quot;.</p><p>Trying to build either a project or solution in TFS using the same build configuration values.</p><p>The default expected value for variable Platform is &quot;Any CPU&quot; for a solution, while for a project it is &quot;AnyCPU&quot; (no space).</p>

---
#### Jane Wu [MSFT] on 1/15/2019, 00:01 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

#### Phillip Carter [MSFT] on 8/23/2019, 01:52 PM: 

<p>Hello, could you provide some more information about this discrepancy between VS and TFS for your solution? Is it that TFS expects a particular name and VS doesn’t use this name?</p>

#### Visual Studio Feedback System on 9/3/2019, 08:09 PM: 

We will close this report in 7 days because we don’t have enough information to investigate further. To keep the suggestion open, please provide the requested details.
#### jukka on 9/3/2019, 08:21 PM: 

<p>I guess this is more of an annoyance. I noticed this myself when working with Azure DevOps pipelines. If you're building with the "Visual Studio build" task, choosing a .csproj file you need to use "AnyCPU", for .sln file it's "Any CPU", and the error message isn't exactly clear what the problem is. This is MSBuild issue though, not Azure DevOps (or TFS AFAIK). It was a while ago, so I don't remember if I was trying to build sln and csproj files at the same time.</p>

#### Elliott, Joel on 9/4/2019, 07:32 AM: 

<p>We are using "Microsoft Visual Studio Team Foundation Server Version 15.117.27414.0". In my TFS build, I have task "Visual Studio Build", of the solution (.sln file). For this to work, the Platform option/parameter must be "any cpu". Now in another build, I have a task "Visual Studio Build", of the project (.csproj). For this to work, the Platform must be "anycpu" (no space). Using "any cpu" on a project will fail; using "anycpu" on a solution will fail.</p><p>The request is to change at least one of them to accept either input, so that that one value will work for both of them. In the above, I opted for the no-space "anycpu", so that means changing the build of a solution to treat "anycpu" the same as it does "any cpu".</p>

**Comment by davkean** [comment]
This is owned by the Solution Experience, and we'll use https://developercommunity.visualstudio.com/content/idea/426844/accept-platform-anycpu-for-a-solution.html to track it.

**Comment by duaneking** [comment]
Please reopen this; Its outright DUMB that Azure Devops Pipelines cant accept its own default config.

**Comment by drewnoakes** [comment]
@duaneking the fix is not in this repo, so we won't track it here. You can vote on the [feedback ticket](https://developercommunity.visualstudio.com/t/accept-platform-anycpu-for-a-solution/426844), which is open, to increase its visibility to the team that owns this area.

**Comment by duaneking** [comment]
The big issue I have is that platform has a history of being ignored when issues are provided by developers. and so as a developer I can't trust that any process involving that website will actually reach a resolution instead of simply being closed by a random person.
