### ISSUE TITLE
Add package file/contained assembly paths to browse object

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5740]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/idea/781589/cannot-see-the-path-for-a-dll-reference-via-packag.html). Please vote and comment there to make sure your voice is heard._

---
Hi,

After migrating to the `<PackageReference>` syntax, we cannot see the path of dll(s) in **Properties** tool window any more.

I know the default path of these nuget packages is `C:\Users\%UserName%\.nuget\packages`, but it would be more helpful if you can display the path in Properties tool window just as before.

Thank you!
Heku

**Comment by davkean** [comment]
Triage: We provide this functionality in the new project system but we are not investing in this area in the legacy project system.

**Comment by davkean** [comment]
Triage: This is a request to add the full path of the dll to the browse object of the graph nodes:

![image](https://user-images.githubusercontent.com/1103906/70951559-d43b9500-20b7-11ea-8d4c-e5b88a2e7e9a.png)

**Comment by drewnoakes** [comment]
I guess there are two things here:

1. Show the path to the `.nupkg` file when a package is selected
1. Show the path to the `.dll` file when a DLL is selected

**Comment by heku** [comment]
Thank you for consideration.
