### ISSUE TITLE
show a thumnail when hovering vector drawable inside resource folder

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5741]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/664173/show-a-thumnail-when-hovering-vector-drawable-insi.html). Please vote and comment there to make sure your voice is heard._

---
show a thumnail when hovering vector drawable inside resource folder
and we still need support for webP images in imageview

---
#### Jane Wu [MSFT] on 7/29/2019, 02:32 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by davkean** [comment]
I've moved to this internally to another team that provides this functionality.
