### ISSUE TITLE
Project File Editor not marked dirty when property changed

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#5744]
**Visual Studio Version**: 16.5 Preview 1

**Summary**:
When a project property is changed there is no dirty mark added to any open project file editor. If the project file editor is opened after changing the property, it does correctly have a dirty indicator.

**Steps to Reproduce**:

1. New .NET Core console app
2. Right click the project node -> Edit Project File
3. Right click the project node -> Properties
4. Change output type to Class Library

**Expected Behavior**:
Project file editor window is marked dirty

**Actual Behavior**:
Project file editor window is not marked dirty. I think I saw it flash the indicator briefly, but not 100% sure.

**User Impact**:
Confusing and incorrect

**Comment by davidwengier** [comment]
Putting this back into triage to confirm the milestone. I played with it for a minute and its super easy to introduce a regression.

**Comment by davkean** [comment]
Triage: This worked in 15.9.

**Comment by davidwengier** [comment]
Internal PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/243805

**Comment by davidwengier** [comment]
PR was completed.
