### ISSUE TITLE
Move CPS build pipeline to VS2019

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#5748]
This should work with VS2019 https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?definitionId=9020&_a=summary

**Comment by dmonroym** [comment]
This is related to CPS so internal PR is available here: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/218389?path=%2Fbuild%2Fcloud%2Fartifacts%2F_vsts.ps1&_a=overview

**Comment by drewnoakes** [comment]
@dmonroym I'm closing this as the CPS PR has been merged.

**Comment by dmonroym** [comment]
@drewnoakes This mas merged into CPS repo but [this PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/221021) is still pending for insertion into VS master, is it best to create another issue to track that?

**Comment by drewnoakes** [comment]
@dmonroym I'll reopen this and let you decide.

**Comment by davkean** [comment]
We don't usually wait until insertion before closing an issue unless it's got a possibiliy of being rejected, such as during Ask Mode.

**Comment by dmonroym** [comment]
In this case the insertion seems to be getting stuck. Just discussed with the CPS team and they kicked off another insertion again. I'll close this issue and track the insertion on #5768
