### ISSUE TITLE
Support "Edit Project File" in the Cloud Environment

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#5760]
In local scenarios the "Edit Project File" command can open project files in the XML editor. We need to update the command so that it is available and displays in the cloud environment, as well.

Notes:

- In the current implementation the command is only available if the selected project supports the "editable project file" capability. As such it is _not_ available on every project.
- To achieve the same thing in the cloud environment we either need a local cache of the project capabilities, or we need a commanding system that can effectively remote the `QueryStatus` and `Exec` calls back to the server.
- If the actual opening of the file is initiated by the server then we need to figure out how to get the editor to appear on the correct client, assuming there are multiple.

**Comment by tmeschter** [comment]
Currently blocked by https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1040697.

**Comment by tmeschter** [comment]
@davidwengier Assigning to you as you are currently working on this experience.

**Comment by davidwengier** [comment]
Initial internal PR: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/234344

**Comment by davidwengier** [comment]
Also tracked by AB#1076627

**Comment by davidwengier** [comment]
New interfaces has been added to MS.VS.RpcContracts. CPS work is merged. Live Share team notified.
