### ISSUE TITLE
[loc][Query][project-system] Localizability of 0; "OutputGroupPublishItemsDisplayName"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/project-system#5771]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Publish Items

ID:
0; "OutputGroupPublishItemsDisplayName"

File Name:
Microsoft.VisualStudio.ProjectSystem.Managed\xlf\Resources.xlf

==========================================
Query:
Is "Publish" a verb here? Or does it mean "Items in the publishing"?

**Comment by davidwengier** [comment]
@PDostalek No, "Publish" in this context is not a verb.

**Comment by jjmew** [comment]
Closing since the question has been answered

**Comment by PDostalek** [comment]
So what´s the correct meaning? @davidwengier  ?

**Comment by davidwengier** [comment]
@PDostalek "Publish items" in this case refers to the files needed when publishing a project

**Comment by PDostalek** [comment]
Thx
