### ISSUE TITLE
Debug page mnemonics

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5797]
The 'Debug' property page doesn't define any keyboard accelerators/mnemonics for text boxes, drop downs or buttons. This makes the page less accessible than it should be.

These are usually visible when holding down the <kbd>Alt</kbd> key:

![image](https://user-images.githubusercontent.com/350947/72491013-e05c7300-386c-11ea-83b4-a3444b12c59a.png)

Notice how the main menu items have underlined letters, but none of the property page labels or buttons do.

Compare this with the 'Application' property page:

![image](https://user-images.githubusercontent.com/350947/72490944-b014d480-386c-11ea-8323-705db91ed220.png)

Adding these is a matter of prepending the desired character with `_` in the resource string. We should take care to not override other mnemonics such as those used in the main menu.

**Comment by drewnoakes** [comment]
We should copy these mnemonics from legacy where that makes sense, to help people with muscle memory.

**Comment by jjmew** [comment]
Moving to 16.8 as this specific item will not meet the QB bar for for 16.7
