### ISSUE TITLE
[PerfWatson] PerfWatsonHang: microsoft.visualstudio.projectsystem.managed.vs.dll!Microsoft.VisualStudio.ProjectSystem.VS.Automation.VSBuildManager.get_DesignTimeOutputMonikers

### ISSUE THREAD

**Issue by ocallesp** [dotnet/project-system#5801]
**Summary**:

PerfWatsonHang: microsoft.visualstudio.projectsystem.managed.vs.dll!Microsoft.VisualStudio.ProjectSystem.VS.Automation.VSBuildManager.get_DesignTimeOutputMonikers

https://github.com/dotnet/project-system/blob/5a856d9fb67fccc8db12ec500359f8408addcb86/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VsBuildManager.cs#L84
**Steps to Reproduce**:

1.  Create a  .net core winforms app

2.  Add a resource file
      In the project file
     DesignTime should be True
![image](https://user-images.githubusercontent.com/510598/72563560-c5850100-3862-11ea-8fda-4b42cc9d79e1.png)

3. Open the winforms designer

**Expected Behavior**:

**Actual Behavior**:

**User Impact**:

**Comment by davkean** [comment]
@ocallesp Can you point to the PerfWatsonhang?

**Comment by davkean** [comment]
Ah: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1028094.

Heads up @davidwengier - this is apparently 7th in 16.5.

**Comment by davkean** [comment]
@ocallesp We don't need cabs for this - we should be able to figure it out.

**Comment by davkean** [comment]
Strike that - its a hang not a delay, cabs would help.

**Comment by ocallesp** [comment]
https://dev.azure.com/devdiv/DevDiv/_queries/edit/1054653/?triage=true

**Comment by davkean** [comment]
@ocallesp What's that bug representing?

**Comment by ocallesp** [comment]
is the same issue. How to relate dev.azure issues here ?

**Comment by davkean** [comment]
We should only have a single bug representing the work. Close all bugs in lieu of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1028094. We track Watons/Hang on AzureDevOps.

**Comment by davkean** [comment]
What happened to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1028094? It seems to have disappeared.

**Comment by davidwengier** [comment]
> How to relate dev.azure issues here ?

You can just write `AB#<work item number>` in here and it will auto-link after you save your comment.

**Comment by ocallesp** [comment]
AB#1054653

**Comment by ocallesp** [comment]
the output from !dumpasync is showing SynchronouslyBlockingMainThread
GetTempPEMonikersAsync() 
     waiting for AsyncLazy.GetValueAsync()
           waiting for  OnceInitializedOnceDisposedAsync
               waiting for ProjectHostBridge.InitializeCoreAsync()
                     await Task.WhenAny(    list of tasks, one of them is blocked  )

the task that is blocked is firstValuePublishedSource

**Comment by ocallesp** [comment]
@jjmew closing bug in github to track it only internally
