### ISSUE TITLE
App Designer Folder: New Icon

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5803]
We would like a new icon that is folder based.

**Comment by davkean** [comment]
We need 3 icons:

Closed
Open
Missing

**Comment by davkean** [comment]
See: AppDesignerFolderProjectImageProvider for where we would return the new image.

**Comment by davkean** [comment]
We no longer need an icon for missing based on https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/226418?_a=overview, which automatically overlays the missing icon over it:

![image](https://user-images.githubusercontent.com/1103906/73590907-54b93680-453c-11ea-9e6c-87f0a6cbb871.png)

**Comment by drewnoakes** [comment]
Some options. What do people think? If you're on high-DPI you may need to zoom in to see these properly.

![image](https://user-images.githubusercontent.com/350947/73626759-35d2b580-469e-11ea-93fb-e60dfb6686d1.png) ![image](https://user-images.githubusercontent.com/350947/73626773-4420d180-469e-11ea-99f4-bc0faaccd4a5.png)

![image](https://user-images.githubusercontent.com/350947/73626802-5f8bdc80-469e-11ea-8d35-bc685ca88002.png) ![image](https://user-images.githubusercontent.com/350947/73626791-5a2e9200-469e-11ea-9e26-ad8ac1fa250f.png)

![image](https://user-images.githubusercontent.com/350947/73627036-299b2800-469f-11ea-955d-82d8f1d846cf.png) ![image](https://user-images.githubusercontent.com/350947/73627046-2f910900-469f-11ea-889f-ec4d6e1a6401.png)

The spanner is consistent with the project context menu icon. I think I like the last pair best.

These are 16px images, which are easier to make than the XAML ones. Once we have agreement on the icon, I'll make the XAML versions.

**Comment by davidwengier** [comment]
I would definitely stick with the spanner - in VS iconography the cog means Options. Also I think it's weird having the little overlay bit move to be inside the folder when its expanded. None of the others do that from the look of the screenshots above.

But I would also just get the DD icon team to do it so we don't have to worry about all of this bikeshedding :D

**Comment by davkean** [comment]
I don't mind the last one, but like Dave I think the overlay should remain where is belongs on open.

**Comment by drewnoakes** [comment]
That gives:

![image](https://user-images.githubusercontent.com/350947/74581549-dad98080-5004-11ea-8a30-58f1a178f61c.png) ![image](https://user-images.githubusercontent.com/350947/74581547-d745f980-5004-11ea-8e03-eb4eed05f70e.png)

My original concern was that the spanner would hide the open flap and make it confusing, but in practice it seems fine.

**Comment by davkean** [comment]
Yeah that's not bad, can we try it?

**Comment by drewnoakes** [comment]
Yeah, I'll look into the XAML equivalent next.
