### ISSUE TITLE
Pressing F1 on property page opens broken link

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5815]
Pressing <kbd>F1</kbd> on the property page navigates to:

https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(cs.ProjectPropertiesBuild)&rd=true

This redirects to:

https://msdn.microsoft.com/Areas/Epx/Content/500.aspx?aspxerrorpath=/query/dev16.query

![image](https://user-images.githubusercontent.com/350947/72770509-2db45800-3c52-11ea-8eff-a522d514e153.png)

**Comment by davkean** [comment]
I cannot repro this, I get:

**Comment by davkean** [comment]
Even your link above (which is missing view=vs-2019) redirects to the same location, maybe this is a temporary error?

**Comment by drewnoakes** [comment]
Yeah I cannot repro it any more either.
