### ISSUE TITLE
Consolidate reference manager capabilities

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5829]
Currently we have capabilities such as:

- `ReferenceManagerAssemblies`
- `ReferenceManagerBrowse`
- `ReferenceManagerCOM`
- `ReferenceManagerProjects`
- `ReferenceManagerSharedProjects`
- `ReferenceManagerWinRT`

Additionally we have capabilities such as:

- `AssemblyReferences`
- `COMReferences`
- `PackageReferences`
- `ProjectReferences`
- `SharedProjectReferences`
- `WinRTReferences`

It may be possible to consolidate these.

Note that `ReferenceManagerBrowse` has no analogue, nor does `PackageReferences`.

**Comment by davkean** [comment]
Don't consolidate the reference XXXReference ones, they are needed. Some projects only support some of those.
