### ISSUE TITLE
Memory: ProjectSystem#Microsoft.VisualStudio.ProjectVS.PackageRestore.ReferenceProperties use excessive memory

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#5832]
What I found is that the code essentially make a completely new copy of dictionaries from the immutable dictionary from IProjectRuleSnapshot, and double the price for all the data structure cost we have already paid earlier. That code can easily build by shimming over the existing data. It is also using a less efficient data structure for properties. Basically, each ReferenceProperties holds both a list of properties + a dictionary<propertyName, propertyValue>.  It is also wasteful, because all similar items have the exact set of properties (defined by a rule), and majorities of values are an empty string. CPS shares the mappings of property names to index, so all properties dictionary are essential fixed length string array. (We didn’t have a way to take advantage that majority values are empty strings, and many references are the same crossing projects. Let me know if you think of a better design.)

**Comment by drewnoakes** [comment]
A challenge here is that `ReferenceProperties` has to implement `IVsReferenceProperties.Item(object index)`, yet the backing data is `IImmutableDictionary<string, string>`.

Perhaps CPS could add an interface `ISharedKeySchema` or similar which would allow lookup from index to key name. If added I assume this wouldn't be declared on the snapshot, so would it be safe to assume this interface was always implemented, or would there need to be a fall back implementation?

As for trying to improve allocation by sparse arrays, two ideas come to mind:

1. An additional layer of schema is looked up based on the pattern of non-empty values.
2. The instance maintains a bit array of non-empty values, and uses that for lookups.

The first approach avoids having to think about bit-array lengths (eg. limit to 32/64 as int/long), and reduces lookup cost, though possibly creates lots of long-lived schema objects

**Comment by davkean** [comment]
My guess that the indexer isn't actually used and the only thing NuGet uses is the enumerator.

**Comment by lifengl** [comment]
For sparse array, I lean towards the 2nd solution. It is unlikely we have any rule exceeds 64 properties.

**Comment by davkean** [comment]
@lifengl We stopped persisting these collections in https://github.com/dotnet/project-system/pull/5917. As spoken offline, there's not a great away to have this wrap the existing snapshot - we could consider sharing common values, but not sure its worth for short term allocations. Please tell if me if you disagree.
