### ISSUE TITLE
Deleted files don't appear in Recycle Bin

### ISSUE THREAD

**Issue by jmevel** [dotnet/project-system#5833]
**Visual Studio Version**:
16.4.3

**Summary**:
Files deleted from the solution explorer in Visual Studio do not appear in Recycle Bin.
I've this [this bug](https://github.com/dotnet/project-system/issues/5710) from December 2019. It seems fixed (I tested it) for folders but this issue still exists for files.

**Steps to Reproduce**:

1. Create a .NET Core 3.1 project and open it with Visual Studio

2. Delete a class like (eg: `Program.cs`)

3. Open your Recycle Bin and notice your file isn't here

**Expected Behavior**:
The deleted file is in the Recycle Bin

**Actual Behavior**:
The deleted file isn't in the Recycle Bin

**User Impact**:
Any decision to delete a file is not reversible. No second thought allowed

**Comment by davkean** [comment]
@melytc Can you verify that you fixed this for 15.5?

**Comment by davkean** [comment]
This was fixed in 16.5: https://github.com/dotnet/project-system/issues/5710, dup'ing against it.

**Comment by RyanGaudion** [comment]
How can I get my files back?

**Comment by melytc** [comment]
Files and folders deletion was fixed in 16.5; opened a new issue for project deletion in #5899. 

@RyanGaudion, you should be able to see deleted files and folders in the Recycle Bin and be able to restore it from there. What VS version were you using? And what kind of file were you deleting?

**Comment by RyanGaudion** [comment]
@melytc  I'm using 16.4.4. Is there anyway that I can get my files back. It was a Xamarin project and all the files are gone

**Comment by davkean** [comment]
@RyanGaudion This issue is about a different project type and unrelated to Xamarin.

How did you delete the project? Visual Studio doesn't delete whole projects (unless you highlight every file and folder and choose Delete), just removes them from the Soluton and leaves them on disk.
