### ISSUE TITLE
Validate dotnet/project-system loads in cloud environment

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#5838]
**Validation Steps:**

1. Create a production cloud environment targeting the dotnet/project-system repo.
2. Connect to the cloud environment.
3. In Solution Explorer find ProjectSystem.sln and double-click on it to load the solution.
4. Validate that all projects show in Solution Explorer. It should look something like this:
![image](https://user-images.githubusercontent.com/10506730/73306964-24873600-41d2-11ea-8a18-359062187bb5.png)
5. Expand several of the projects. Validate that the Dependencies node is present, and that you can expand the Analyzers, Packages, and Assemblies node under it and see relevant nodes.

**Comment by tmeschter** [comment]
This is currently working.

**Comment by ocallesp** [comment]
In #5842, the string resource is only deleted after _saving_ the resx file.
