### ISSUE TITLE
Validate project file editing in dotnet/project-system

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#5841]
**Validation Steps:**

1. Create a production cloud environment targeting the dotnet/project-system repo.
2. Connect to the cloud environment.
3. In Solution Explorer find ProjectSystem.sln and double-click on it to load the solution.
4. Right-click on Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client and selected "Edit Project File".
5. Verify that the correct project file has opened.
6. Add a new `PackageReference` item.
7. Save the project.
8. Wait a bit for package restore to run, and then verify that the newly added package appears under the Dependencies node.
9. Open build/import/HostAgnostic.props.
10. Add a different `PackageReference` item here.
11. Save the .props file.
12. Wait a bit for package restore to run, and then verify that the newly added package appears under the Dependencies node of the Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client project.

**Dependencies:**

- #5838.

**Comment by davidwengier** [comment]
@tmeschter Is there a specific reason you wanted these "validate" issues open, rather than just having an issue for the bug? This seems like a duplicate.

**Comment by davidwengier** [comment]
Going to close this out. Editing the project file works, saving the file causes a Nuget restore, and types from the new package show up in intellisense. Basic editing like undo etc. all work, though aren't using our code so out of scope anyway :)

The colourization is not working, but that is tracked separately by https://github.com/dotnet/project-system/issues/6273
