### ISSUE TITLE
Validate ResX file editing in dotnet/project-system

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#5842]
**Validation Steps:**

1. Create a production cloud environment targeting the dotnet/project-system repo.
2. Connect to the cloud environment.
3. In Solution Explorer find ProjectSystem.sln and double-click on it to load the solution.
4. Double-click on a .resx file in one of the projects to open the Resource Designer. Also open the associated .Designer.cs file.
5. Add a new string resource to the file and save. Verify that the new resource shows up in the .Designer.cs file.
6. Delete the resource from the file. Verify that the resource is removed from the .Designer.cs file _without_ first saving.

**Depends On:**

- #5838.

**Comment by ocallesp** [comment]
Add a string resource 
1) Open resx file
2) add XName, XValue, XComment
3) Save the resx file
4) Open  .Designer.cs
5) Check XName appears .... GOOD

Delete the string resource XName
1) Select the row containing XName
2) right-click and select delete
3) At this point .Designer.cs still contains XName
4) Save the resx file
5) Check XName was deleted in .Designer.cs    .... GOOD
