### ISSUE TITLE
Validate debugging dotnet/project-system

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#5843]
**Validation Steps:**

1. Create a production cloud environment targeting the dotnet/project-system repo.
2. Connect to the cloud environment.
3. In Solution Explorer find ProjectSystem.sln and double-click on it to load the solution.
4. Right-click on the ProjectSystemSetup project and select "Rebuild".
5. Make sure "ProjectSystemSetup" is selected in the startup project menu in the tool bar:
![image](https://user-images.githubusercontent.com/10506730/73311820-44235c00-41dc-11ea-9c4b-7a78b62f3615.png)
6. Click the "Start" button next to the startup project menu.
7. Verify that VS starts in the Exp hive.
8. Set a breakpoint in `CompileItemHandler.AddToContext`.
9. Add a C# file to the project (either directly if item templates are available, or indirectly by adding a .txt file and changing the extension to .cs).
10. Verify that the breakpoint in step 8 is hit.

**Depends On:**

- #5838.
- #5839.

**Comment by tmeschter** [comment]
Need to add steps describing where we should put breakpoints to validate that they work.

**Comment by tmeschter** [comment]
Added a step to set a breakpoint in `CompileItemHandler.AddToContext`.

**Comment by davkean** [comment]
Triage: Load balancing, can you do this as part of the testing Online Environment scenarios?

**Comment by melytc** [comment]
This is being tracked in the VS Online scenarios, as #5844.
