### ISSUE TITLE
Validate running and debugging unit tests in dotnet/project-system

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#5844]
**Validation Steps:**

1. Create a production cloud environment targeting the dotnet/project-system repo.
2. Connect to the cloud environment.
3. In Solution Explorer find ProjectSystem.sln and double-click on it to load the solution.
4. Under the "Test" menu, choose "Test Explorer".
5. Verify that about 4852 tests are found under four projects.
6. Drill down to a specific test, right-click on it, and select "Run".
7. Verify that the test completes successfully.
8. Click the "Run All Tests" button in the upper left corner of the Test Explorer window.
9. Verify that the tests complete successfully.
10. Double-click on a test to open the source in the editor.
11. Put a break point somewhere in the test.
12. Right-click on the unit test in Test Explorer and select "Debug".
13. Verify that the break point is hit and the Locals/Auto/Watch windows show appropriate test state.

**Depends On:**

- #5838.
- #5839.

**Comment by davkean** [comment]
Triage: Load balancing, can you do this as part of the testing Online Environment scenarios?

**Comment by melytc** [comment]
Sure, will do.

**Comment by melytc** [comment]
> 5\. Verify that about 4852 tests are found under four projects.

@tmeschter where did you get the number of tests? I can see 4,837 in offline Test Explorer, but might be missing something.

**Comment by tmeschter** [comment]
@melytc That seems close enough. The exact number of tests will vary over time as we add and remove them. So long as we're close to that number, we're fine. My concern is that we might someone miss all of the tests in a particular test project, in which case the number would be much, much lower.

**Comment by melytc** [comment]
That makes sense, thanks @tmeschter !

**Comment by melytc** [comment]
@tmeschter, as of 3/24, things seem to be working. The `Debug a unit test` scenario is the only one not working. I have opened a [bug ticket](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1087710) in AzDO. I'll keep an eye on all scenarios in my biweekly (twice-a-week) testing.

Should we keep this issue opened until we have that scenario passing?

**Comment by tmeschter** [comment]
@melytc If the scenario is tracked elsewhere then this issue can be closed.
