### ISSUE TITLE
Fast up-to-date check doesn't consider global.json

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5846]
Changes to `global.json` (such as the SDK version to use) should trigger a build.

Repro steps:

1. Create a new .NET Core Console App
1. `dotnet new globaljson`
1. Build in VS twice. Second build should show 'up to date'.
1. Change the SDK version in `global.json`
1. Build in VS again. Should **not** be considered up-to-date, but it is.

**Comment by davkean** [comment]
I think this would be pretty easy if we can mimic the global.json lookup via msbuild-isms, and just have it appear in the `<AdditionalDesignTimeBuildInput>`. CPS will automatically monitor it and reevaluate/design-time build passed on changes to it.

**Comment by davkean** [comment]
Oh my bad, this is talking about fast up-to-date, this is also a problem in design-time builds and I'll file a new bug.

**Comment by drewnoakes** [comment]
The fix to this issue should also fix #5847.

**Comment by davkean** [comment]
Once we've done #5847, the file will appear in AdditionalDependentFileTimes similar to: http://index/?leftProject=Microsoft.VisualStudio.ProjectSystem.Managed.VS&leftSymbol=ggglyaslekha&file=ProjectSystem%5CVS%5CPackageRestore%5CPackageRestoreProgressTracker.PackageRestoreProgressTrackerInstance.cs&line=103. 

Either we use that or use shove it into a property that we respect in both #5847 and this.

**Comment by davkean** [comment]
> The fix to this issue should also fix #5847.

The fix is separate fixes or are you saying that they are need to be done together?

**Comment by drewnoakes** [comment]
Separate fixes, but similar enough that doing them together makes sense, which is what's happened anyway.

**Comment by davkean** [comment]
This has been fixed.
