### ISSUE TITLE
Global.json should trigger reevaluation & design-time build

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5847]
Similar to https://github.com/dotnet/project-system/issues/5846, we should trigger reevaluation/design-time build based on a change/add/removal of global.json. 

I think this would be pretty easy if we can mimic the global.json lookup via msbuild-isms, and just have it appear in the `<AdditionalDesignTimeBuildInput>`. CPS will automatically monitor it and reevaluate/design-time build passed on changes to it. This is how we trigger reevaluation on project.assets.json. 

The lookup is here, which is starting at project/solution directory and keep walking until you hit a global.json: https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/installer/corehost/cli/fxr/sdk_resolver.cpp.

**Comment by drewnoakes** [comment]
Where would this fix live? In our DT targets?

**Comment by davkean** [comment]
Yeah in the DT targets - we should hide it behind a indicator that they are using the .NET SDK, what I don't know yet.
