### ISSUE TITLE
[Regression] Debug properties pages are blank the first time you open them

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5858]
**Visual Studio Version**:
Version 16.5.0 Preview 3.0 [29802.0.master]

**Summary**:

**Steps to Reproduce**:

1. Create a new .NET Core project
2. Choose Debug -> [Project] Properties

**Expected Behavior**:
Debug property page to show

**Actual Behavior**:
The the page opens but it is blank:
![image](https://user-images.githubusercontent.com/1103906/73605930-c35bca00-45f8-11ea-8369-24a7a77dec06.png)

I suspect this is related to PLM being enabled.

**Comment by drewnoakes** [comment]
I saw something similar on the Application page today too.

**Comment by davkean** [comment]
This page doesn't use any design-time build data and should not be opt'd into placeholder mode.

**Comment by drewnoakes** [comment]
Are there other pages that don't use design-time data too?

**Comment by davkean** [comment]
Yes, a few - it needs investigating.

**Comment by jjmew** [comment]
@melytc we are load balancing since this is a blocker for 16.5. @davidwengier  will be helping with this one.

**Comment by davkean** [comment]
This has been fixed and merged.
