### ISSUE TITLE
Folder with only Visible="False" items still appears in Solution Explorer

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5859]
Given folder structure:

```
myproj.csproj
Folder\Text.txt
```

Where `myproj.csproj` contains:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Update="Folder/Text.txt" Visible="False" />
  </ItemGroup>
</Project>
```

The folder appears in the tree with no children.

![image](https://user-images.githubusercontent.com/350947/73617210-42401980-4670-11ea-825e-4d084777f214.png)

Setting `Visible="False"` on the `Folder` item doesn't work.

---

Reported in https://github.com/microsoft/VSProjectSystem/issues/162 which pointed to https://github.com/dotnet/project-system/issues/1233, yet that is closed and seems unrelated as in the example above the hidden file is within the project cone.

**Comment by davkean** [comment]
I think this is known. Given we can implicitly determine that a folder only contains "linked" items, I'm sure we could (but haven't determined) detect a folder with only hidden items and hide it.,

**Comment by davkean** [comment]
See: https://developercommunity.visualstudio.com/content/problem/215427/unmanaged-dlls-of-a-nuget-package-show-u-in-the-ro.html.

**Comment by jjmew** [comment]
@davkean I am moving this to 16.6. Can you help us route this issue?

**Comment by davkean** [comment]
Duping this against https://developercommunity.visualstudio.com/idea/1079955/parent-folder-of-items-marked-as-visiblefalse-stil.html.

**Comment by Dean-NC** [comment]
@davkean Is this fixed in 16.6.0, or will it be in 16.7?  I'm on 16.6.0 and it's not fixed.

**Comment by TechInterMezzo** [comment]
Is it just me or did this problem return in VS 2022?

**Comment by drewnoakes** [comment]
@manojdcoder this issue does not belong to this repo. It was moved to Developer Community so that it could be assigned to another team (not on GitHub). If you're seeing an issue here, could you please open a feedback ticket with detailed steps. If you link it here, I'll ensure it's routed correctly. Thanks.

**Comment by cytoph** [comment]
@manojdcoder Did you open a ticket in the Developer Community? If so could you link it here? Because I have this problem, too, in the current version of Visual Studio and would like to know if there's something to do about it.

**Comment by manojdcoder** [comment]
@cytoph No, I did not. I don't even know what it means to open a ticket in Dev Community outside Github.
