### ISSUE TITLE
Microsoft.Build.NoTargets project expects incorrect ouput

### ISSUE THREAD

**Issue by edgarrs** [dotnet/project-system#5868]
**Visual Studio Version**: 16.4.4

**Summary**:
Having a project with Microsoft.Build.NoTargets is never up-to-date because it expects an output that is never generated.

**Steps to Reproduce**:

1. Create and SDK project.

2. Update the project to be Microsoft.Build.NoTargets. See mine:
<Project Sdk="Microsoft.Build.NoTargets">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
</Project>

I also had to add the following global.json:
{
  "msbuild-sdks": {
    "Microsoft.Build.NoTargets": "1.0.85"
  }
}

3. Build twice

**Expected Behavior**: The project should be up to date.

**Actual Behavior**: The project is not up to date because it expects the pdb file. Here is the log:
1>FastUpToDate: Adding UpToDateCheckBuilt outputs: (RepoNoTargetsBug)
1>FastUpToDate:     'C:\Users\edgarsil.000\source\repos\RepoNoTargetsBug\RepoNoTargetsBug\obj\Debug\net472\RepoNoTargetsBug.pdb' (RepoNoTargetsBug)
1>FastUpToDate: Output 'C:\Users\edgarsil.000\source\repos\RepoNoTargetsBug\RepoNoTargetsBug\obj\Debug\net472\RepoNoTargetsBug.pdb' does not exist, not up to date. (RepoNoTargetsBug)

**User Impact**:
Project is never up to date.

**Comment by davkean** [comment]
@edgarrs Thanks for the bug, I've moved it over to https://github.com/microsoft/MSBuildSdks/issues/148 as they own this, thanks.

**Comment by edgarrs** [comment]
I'm not sure why the project sample was cut when I posted the repro steps but here is the same:

<Project Sdk="Microsoft.Build.NoTargets">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
</Project>

**Comment by edgarrs** [comment]
Nice, GitHub parses the XML so I would need to escape the project content

**Comment by edgarrs** [comment]
![image](https://user-images.githubusercontent.com/4756848/73797655-82cd8f00-4765-11ea-8a30-1425800138cb.png)

**Comment by NoneGiven** [comment]
@edgarrs You can enclose inline code in backticks and code blocks in triple backticks. You can even specify the language with triple backticks.

```xml
<Project Sdk="Microsoft.Build.NoTargets">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
</Project>
```
