### ISSUE TITLE
VS crashes when I change branches

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/project-system#5869]
Filed VS feedback item here: https://developercommunity.visualstudio.com/content/problem/906254/vs-crashes-when-i-change-branches-in-roslyn.html

**Version Used**: 16.5.0 Preview 3 [29802.14.master]

**Steps to Reproduce**:

1. Open Roslyn.sln in VS
2. Go into the terminal and 'git checkout' a different branch (e.g. master to release/dev16.4)
3. Return to VS and run a build

**Expected Behavior**:

VS loads the project changes and keeps going.

**Actual Behavior**:

VS shows some diagnostics about bad restores and eventually crashes.

![image](https://user-images.githubusercontent.com/5833655/73704206-2015be00-46a7-11ea-962c-312269d227b5.png)

/cc @jmarolf

**Comment by sharwell** [comment]
@jmarolf done!

**Comment by RikkiGibson** [comment]
Filed https://developercommunity.visualstudio.com/content/problem/906254/vs-crashes-when-i-change-branches-in-roslyn.html

**Comment by davkean** [comment]
Closed to in lieu of that.
