### ISSUE TITLE
Cross targeting: Dependencies node should show dependencies for all TFMs and group them

### ISSUE THREAD

**Issue by srivatsn** [dotnet/project-system#587]
Currently we show the dependencies for the first TFM and even then PackageReferences that are conditioned on a TFM don't seem to show up.

**Comment by srivatsn** [comment]
We show packages for all TFMs now but there's no UX to distinguish between TFs yet.

**Comment by srivatsn** [comment]
One other piece of work is that currently we only show the PackageReferences for all TFMs but we should show assemblies\sdks\analyzers etc for all TFMs as well and show them grouped in some form.

**Comment by srivatsn** [comment]
Also when the same package shows up in multiple TFMs we should show both versions.

**Comment by abpiskunov** [comment]
Fixed with https://github.com/dotnet/project-system/pull/1880
