### ISSUE TITLE
Debug property page changes layouts multiple times during open

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5872]
![DebugProfiles2](https://user-images.githubusercontent.com/1103906/73892723-c3471d00-48cb-11ea-879a-51e7f74d12d7.gif)

It looks like when we're adding the extensible control, we're causing a recalculation of the layout. I'm not sure about WinForms, but you can prevent layouts while you are making significant changes, we should try and do the same.

**Comment by mikedn** [comment]
Out of curiosity - how did you get that gif, slowed down screen capture? I've never seen that page loading so slow.

But FWIW all prop pages somehow "flash" during loading, if anything the WPF based Debug one flashes less than the WinForms ones. At least with the current VS preview I have installed.

**Comment by davkean** [comment]
Yeah its a slowed down screen capture, we should probably do a pass on all pages - they aren't supposed to resize, and we have asserts to catch it.

**Comment by drewnoakes** [comment]
The new Project Properties UI does not has this issue. We are unlikely to invest in improving the rendering performance of these legacy UIs at this point in time.
