### ISSUE TITLE
Reduce edit collisions and merge conflicts on insertions by splitting default.config 

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#5879]
We're seeing too many merge conflicts with insertions causing CloudBuild and DDRITs to be executed several times, by splitting our component from default.config we'll have our own file so no collisions should be happening.

For reference: https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/4272/Splitting-default.config

Relates to [AB#1087083](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1087083)

**Comment by davidwengier** [comment]
Not that it looks difficult, but @olegtk just did this for VS-Platform, as another reference: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/227966?_a=overview

**Comment by rainersigwald** [comment]
I'm in the midst of doing this for SDK, too: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/222878. Feel free to holler if you have any questions.

**Comment by dmonroym** [comment]
Thanks @rainersigwald that'll be a huge reference. I was under the impression that we might need to make some changes to the insertion tool but seems like that's not the case

**Comment by dmonroym** [comment]
Tracked by dotnet/roslyn-tools#678

**Comment by MiYanni** [comment]
Screenshot of what a collision looks like (with LiveShare): https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1087083#3238786

**Comment by MiYanni** [comment]
PR for the fix: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/425529

**Comment by MiYanni** [comment]
Success! `default.config` is no longer used and our own `.packageconfig` files are updated appropriately. https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/429533?_a=files
