### ISSUE TITLE
Deleted project does not appear in Recycle Bin

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#5899]
**Current behavior:**
![project-delete](https://user-images.githubusercontent.com/8518253/74768541-9e449980-523d-11ea-9976-266da3ead02c.gif)

Project is deleted from the Solution Explorer, but not moved to the Recycle Bin (it's actually kept in the solution folder).

**Expected behavior:**
Project is moved to the Recycle Bin, where the user can recover the project if needed.

Reported in #5710, which fixed a similar behavior but only with files and folders.

**Comment by davkean** [comment]
This behaviour is by design the project isn't deleted, it's removed but left on disk. 

Trying to understand the expected behaviour - what exactly would we put in the recycle bin? Is the suggestion that we physically delete the project?

**Comment by drewnoakes** [comment]
The customer reported in https://github.com/dotnet/project-system/issues/5710#issuecomment-587099481:

> My xamarin solution has been deleted and is not in recycle bin. How can I get these files back?

It's not clear how they deleted the solution, not exactly what is missing. I've asked for clarification.

**Comment by jjmew** [comment]
This is by design
