### ISSUE TITLE
Project System: Properties of all dependencies nodes should display correct properties comparing to old csproj system

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#59]
_From @davkean on April 29, 2016 17:12_

Unlike csproj.

_Copied from original issue: dotnet/roslyn#10975_

**Comment by abpiskunov** [comment]
Properties are now showing up for root package dependencies, however GraphNodes for child packages are still not showing properties. There no straight forward way to show them and we need to dig into Progression API to make it work. There was a thread with progression team and they suggested potential way to show properties, which i was going to prototype later, when continue with this issue.

**Comment by abpiskunov** [comment]
All Dependencies nodes are now display some properties, however comparing to what is displayed with old csproj , there are pretty big differences in property sets. We need to review all properties and finalize property sets that we want to display for all dependency types.
