### ISSUE TITLE
Default framework assembly references cannot be removed

### ISSUE THREAD

**Issue by drieseng** [dotnet/project-system#5914]
**Visual Studio Version**: 2017 / 2019
**Summary**:
If you target a .NET Framework version (eg. 3.5 or 4.0) using an the SDK project, one cannot remove any of the default framework assembly references.

**Steps to Reproduce**:
1. Create an SDK project.
2.  Update the TargetFrameworks to include - for example - net35 and net40.

`<TargetFrameworks>net35;net40;netstandard1.3;netstandard2.0;netstandard2.1</TargetFrameworks>`

3. Right-click one of the default framework assembly references.

![image](https://user-images.githubusercontent.com/312863/75097915-67111800-55b0-11ea-85c7-1a75f3b50df9.png)

**Expected Behavior**:
1. An option is provided to remove the selected framework assembly reference.

**Actual Behavior**:
1. No option is provided to remove the selected framework assembly reference.
2. If you attempt to remove any of the default framework assembly references through **Reference Manager**, the following error is reported: 

![image](https://user-images.githubusercontent.com/312863/75098028-bf94e500-55b1-11ea-9473-72b6b38f6b75.png)

**User Impact**:
1. A developer cannot control which framework assemblies he or she wants to reference.

**Comment by jjmew** [comment]
This is not a Project System issue. We have routed it to an internal team to look at it. 

Internal Bug: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1073306

**Comment by jjmew** [comment]
AB#1073306

**Comment by jeffwilcox** [comment]
The internal ticket is identical to this, with the same screenshot.
