### ISSUE TITLE
Fast up to date check add or remove UpToDateCheckInput items between builds

### ISSUE THREAD

**Issue by felixhirt** [dotnet/project-system#5919]
**Visual Studio Version**:
16.4.5

**Summary**:
I have a target where i would like to add some external files as dependencies to the fast up to date check. This is what i have so far:

```xml
  <Target Name="_AddCustomUpToDateCheckInputs" BeforeTargets="CollectUpToDateCheckBuiltDesignTime" DependsOnTargets="_FindCustomRebuildDependencies">
    <ItemGroup>
      <UpToDateCheckInput Include="@(_CustomRebuildDependencies)"></UpToDateCheckInput>
    </ItemGroup>
  </Target>
```

The _FindCustomRebuildDependencies target finds those files and adds them to "_CustomRebuildDependencies".

The whole thing works. The files are added and if they change, the fast up to date check triggers a build.

The problem is that they are only added when i start vs. If the list of files changes later on (e.g. more files added), these changes are ignored. It seems that the "CollectUpToDateCheckBuiltDesignTime" target only runs once at start of vs?

Am i doing something wrong? is there another target i could hook onto which runs every time the fast update check runs?

**Comment by drewnoakes** [comment]
The `CollectUpToDateCheckBuiltDesignTime` target only runs during design-time builds. The fast up to date check doesn't trigger these. Such builds are quite slow, and we only run them when necessary.

Can you share your `_FindCustomRebuildDependencies` target?

Ideally you'd add your `UpToDateCheckInput` items during evaluation (i.e. not in a target) and cover them by an item include glob so that file system watchers trigger re-evaluation/build when items are added/removed on disk. It's hard to tell whether this would work for you without seeing the definition of `_FindCustomRebuildDependencies`.

**Comment by felixhirt** [comment]
Thanks for the hint, should have thought about that. Tried it now, but its seems to still not be working. Here is what i did:

```xml
  <Target Name="_AddCustomUpToDateCheckInputs" BeforeTargets="CollectUpToDateCheckBuiltDesignTime" DependsOnTargets="_FindCustomRebuildDependencies">
    <ItemGroup>
      <UpToDateCheckInput  Remove="@(UpToDateCheckInput)" />
      <UpToDateCheckInput  Include="$(ACustomFile)" />
      <UpToDateCheckInput Include="$(ACustomDirectory)\MyFile" />
      <UpToDateCheckInput Include="$(ACustomDirectory)\things\**\*.*" />
    </ItemGroup>
  </Target>
```

I added the remove line to make removing of files work (the file is gone -> build is triggered -> during build the list of files is recreated without the absent file -> fast up to date check does no longer look for it the next time). To this end i also added the target to the regular build process.

The thing is though that the list of files still seems to be create only once even with globs? addition of files does not trigger a build.

On top of this, i have the problem that i would like to modify one of those files from another msbuild target in advance (Some of the info is not readily available in file-form, so i thought i would just write it into a dummy file and use that during the up to date check). I take it there is no way to make this work?

**Comment by drewnoakes** [comment]
This is still modifying `UpToDateCheckInput` in a target. Can you do it in a top-level `ItemGroup` instead?

**Comment by felixhirt** [comment]
Im sorry, i must have forgotten how to read. If i do it the way you suggested, it works for adding and removing files. 

Unfortunately i still have the problem that i cannot hardcode the base path for the live version nor devise it from predefined msbuild properties, plus i have that additional file which i have to create from msbuild anyway. 

I understand why this is not so easy, making the fast up to date check more complicated would just turn it into a second msbuild fast up to date check.

I will just exclude all of this from the fast up to date check, and if the user changes something there, they have to do a rebuild of the solution. Thank you for the support though, i appreciate it!

(I will leave the issue open for now in case you or someone else has another idea. If you are positive there is no way to do what i would like, feel free to tell me or close the issue yourself ;-))

**Comment by drewnoakes** [comment]
@felixhirt if you're able to include potential files during evaluation using a glob, then you may have some luck.

As for the file you're generating during build, does it take another file as input? If so you can use [`UpToDateCheckInput` or `UpToDateCheckBuilt`](https://github.com/dotnet/project-system/blob/master/docs/up-to-date-check.md#customization) items (again during evaluation) to teach the fast up-to-date check about the generated file.

**Comment by felixhirt** [comment]
@drewnoakes I will start another try, maybe i can find a way to include all the files for all projects in the solution in all projects. that way, if something changes, all projects would be out of date and trigger a rebuild, which would be fine since for most of them it would only do a fast incremental build anyway.

In regards to the file generated by an msbuild target: im thinking about adding a project to the solution which has the fast up to date check disabled and does nothing else but generate this file for the other projects to use during their up to date check (something akin to:
<DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
<EnableDefaultItems>false</EnableDefaultItems>).
Is this feasible? does the up to date check run right before each project is built (after its dependencies have been built), or once in the beginning before any are built?

**Comment by drewnoakes** [comment]
Closing this for now as I can't see what change we would make to the project system. We can keep the discussion going and reopen if something comes up.

**Comment by drewnoakes** [comment]
@felixhirt apologies, I didn't see your last comment before closing this.

If a project is rebuilt, then any project that depends upon its output will be rebuilt too.

**Comment by felixhirt** [comment]
@drewnoakes no problem, i was thinking about closing it myself since i agree that there is no actual change to be done to the project system about this. I'm just abusing the issue now to get advice from you :-). But i think i have an idea now on how to proceed, thanks to you. If i fail again, i might come back and ask for further advice though ;-)
