### ISSUE TITLE
Implicit dependencies should have read-only browse objects

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5924]
Firstly, is this a correct statement?

![image](https://user-images.githubusercontent.com/350947/75425083-19245780-5996-11ea-9fd7-d60c46f9b11c.png)

Notice how `System.Xml.Linq` has a padlock on its icon, indicating it's an implicit reference (defined in an imported props/targets file), unlike `System.Windows.Forms`.

I don't think it should be possible to set "Aliases", "Copy Local", "Embed Interop Types" or "Specific Version" in the properties page. In theory, the project system could update items in the root project file, but I don't think that's currently possible.

**Comment by davkean** [comment]
I would expect this to work exactly how normal items (none, compile. etc) work, using `<ProjectReference Update />`.

**Comment by davkean** [comment]
Triage: We looked at this, this works exactly like Compile and behaves correctly:

``` XML
  <ItemGroup>
    <Reference Update="System.Numerics">
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </Reference>
  </ItemGroup>
```
