### ISSUE TITLE
"Remove" does not show up on Package References context menu

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#5926]
It shows up on References and Project References but not Package References:

![image](https://user-images.githubusercontent.com/1103906/75497506-8d074400-5a18-11ea-8abd-782f31810b23.png)

Pressing DEL works.

**Comment by davkean** [comment]
tag @drewnoakes

**Comment by drewnoakes** [comment]
What build is this?
Is that package added via an imported props/targets file?

**Comment by drewnoakes** [comment]
I cannot repro this. Reopen if you're able to.
