### ISSUE TITLE
404 for styles.css when referencing an RCL from a Blazor WASM app

### ISSUE THREAD

**Issue by danroth27** [dotnet/project-system#5936]
Repro steps:

- Install latest build of d16.6 P1 (16.6.0 Preview 1.0 [29901.0.d16.6])
  - Includes .NET Core SDK 3.1.200-preview-015002
- Install latest Blazor WASM 3.2 P2 build (3.2.0-preview2.20152.1)
- Create an ASP.NET Core hosted Blazor WASM app in VS
- Add a RCL to the solution and reference it from the client project
- Add Component1 to Index.razor and add a link to styles.css

  ```razor
  <RazorClassLibrary1.Component1 />
  ```

  ```html
  <link href="_content/RazorClassLibrary1/styles.css" rel="stylesheet" />
  ```

- Run the app

Expected result:

- Component1 renders with the correct styles

Actual result:

Styles are missing. 

![image](https://user-images.githubusercontent.com/1874516/75706439-0352b300-5c72-11ea-9df3-36cd3cc216cd.png)

Request for styles returns a 404:

![image](https://user-images.githubusercontent.com/1874516/75706475-19607380-5c72-11ea-9473-02e024385680.png)

Refreshing the browser and rebuild the app doesn't resolve the issue. Neither does closing and reopening the solution. 

Workaround:

- Close VS *completely* and then reopen the solution fixes the issue.
- Closing and reopening the solution also appears to fix the issue.

**Comment by Pilchie** [comment]
@jjmew can you take a look?

**Comment by jjmew** [comment]
@ocallesp could this be related to the other issue you are looking at?

**Comment by davkean** [comment]
This looks very much like https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1073852 which was rolled back in https://github.com/dotnet/project-system/pull/5923 and should be in master now.

**Comment by danroth27** [comment]
@davkean I'm still seeing this issue with the latest internal dogfood build (Version 16.6.0 Preview 2.0 [29903.198.master]). Is that the right build to use to verify this is fixed?

**Comment by ocallesp** [comment]
This issue doesn't repro.
