### ISSUE TITLE
Add a command and command handler to show the new App Designer UI

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#5958]
_This issue is one part of #5776, which tracks the work to create a new App Designer using the App Capabilities Designer for VS Online scenarios._

Once we have an assembly in CPS to hold client-side UI, we need to add a command and command handler to show the App Designer. Or better yet, reuse the existing "Properties" command and use a Preview Features flag to toggle which UI experience you get.

**Comment by davkean** [comment]
Please intecept this at the editor factory level (appdesigner has a specific editor factory), there's lots of entry points for it, so adding a new command would only intercept a single location.

**Comment by tmeschter** [comment]
Reassigning to @drewnoakes and @melytc as it concerns the new property page UI.

**Comment by jjmew** [comment]
The new UI should be enabled/disable with a Preview feature flag and option

**Comment by drewnoakes** [comment]
Closing in favour of #6627.
