### ISSUE TITLE
Dynamically add pages to new App Designer

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#5959]
_This issue is one part of #5776, which tracks the work to create a new App Designer using the App Capabilities Designer for VS Online scenarios._

Once we can show the new App Designer shell in VS Online scenarios we need to query the `IItemPropertiesService` to retrieve the list of pages and create them to the App Capabilities Designer. Note that this work item is just about creating the pages, not the content on the pages.

**Comment by tmeschter** [comment]
Re-assigning to @drewnoakes and @melytc as it concerns the new property page UI.

**Comment by drewnoakes** [comment]
We are not using the Application Capabilities Designer.
