### ISSUE TITLE
Dynamically generate App Designer UI components

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#5960]
_This issue is one part of #5776, which tracks the work to create a new App Designer for VS Online scenarios._

Once we have a new App Designer that can show individual blank pages we need to populate them with generated UI. This issue tracks the following:

- [ ] Calling the Project Query API to retrieve the list of properties for the page.
- [ ] Generating an appropriate UI element (text box, combo box, etc.) for the property and binding it to the data.
- [ ] ~~Tracking the dirty state of individual pages.~~
- [ ] Calling the server (`IItemPropertiesService`?) to save property changes.
- [ ] Ensuring the UI is localizable.
- [ ] Ensuring the UI is accessible.
- [ ] Ensuring the UI is themable.

**Comment by tmeschter** [comment]
@drewnoakes, @melytc: This concerns work for the new property page UI, so I'm re-assigning it to you. As you work on the feature design, feel free to adapt this issue as you see fit.

**Comment by AraHaan** [comment]
Ah nice looks promising. I however have yet to discover how I can make dotnet build support custom project formats like this one for example https://github.com/Elskom/newsmake/blob/master/test/test.newsmakeproj.

I have also yet to discover how to make it also work in VS2019 as well.

**Comment by drewnoakes** [comment]
Closing in favour of #6627.
