### ISSUE TITLE
Dependencies node should respect PrivateAssets on ProjectReference

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5973]
When a `ProjectReference` has `PrivateAssets` set to `true`, the dependencies node should not display that project's child project/package references.

#### App.csproj

```xml
<PropertyGroup>
  <TargetFramework>netcoreapp3.1</TargetFramework>
</PropertyGroup>
<ItemGroup>
  <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
</ItemGroup>
```

#### ClassLibrary1.csproj

```xml
<ItemGroup>
  <ProjectReference Include="..\ClassLibrary2\ClassLibrary2.csproj" PrivateAssets="all" />
  <PackageReference Include="MetadataExtractor" Version="2.3.0" PrivateAssets="all" />
</ItemGroup>
```

#### App's Dependencies Tree

![image](https://user-images.githubusercontent.com/350947/76479728-e895f080-6460-11ea-93cd-d5aeb3eef4ce.png)

## Expected

`ClassLibrary1` in the `App` project does not display any child nodes.

---

Note that `App`'s `project.assets.json` file does not list these dependencies:

```json
{
  "version": 3,
  "targets": {
    ".NETCoreApp,Version=v3.1": {
      "ClassLibrary1/1.0.0": {
        "type": "project",
        "framework": ".NETStandard,Version=v2.0",
        "compile": {
          "bin/placeholder/ClassLibrary1.dll": {}
        },
        "runtime": {
          "bin/placeholder/ClassLibrary1.dll": {}
        }
      }
    }
  },
  ...
}
```

**Comment by davkean** [comment]
@drewnoakes I've moved this to backlog for now, if it falls out of the new design so be it, but the reading of the assets file itself should be top of this.
