### ISSUE TITLE
Prompted to close .csproj file when reloading a project

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#5983]
**Visual Studio Version**:
16.6.0 Preview 2.0 [29909.25.master]

**Summary**:
If I have the .csproj file open while a project is unloaded and try reloading I get prompted to close the file (despite having the ability to open it once the project is loaded again)

**Steps to Reproduce**:

1. Unload project

2. Open the .csproj file for editing

3. Reload the project

**Expected Behavior**:
Project loads and .csproj file remains open

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/3288375/76655785-54dd2680-652b-11ea-993e-e41d7950c0d7.png)

**Comment by tmeschter** [comment]
This is by design, and I doubt we would change this now.
