### ISSUE TITLE
Recent change to ProjectTreeFlags breaks Roslyn's analyzers nodes

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5984]
PRs #5947 and #5961 changed a bunch of tree flags used in the dependencies node.

Roslyn currently expects `TargetNode` as a flag. After the above PRs it's now `DependencyConfigurationGroup`.

https://github.com/dotnet/roslyn/blob/331d68b8532bbb39d2d448c286b42c195d5fd357/src/VisualStudio/Core/SolutionExplorerShim/DiagnosticItem/CpsDiagnosticItemProvider.cs#L103

Either we have to update Roslyn or revert the flag change.

@davkean you wanted to remove the concept of 'target' from the name. Is changing Roslyn to match the new value the best way forward here?

**Comment by davkean** [comment]
I pushed back against TargetFramework, Target seems okay.

**Comment by davidwengier** [comment]
Isn't there a better way for Roslyn to determine the target framework here? I would have thought that `$TFM:Foo` format is an implementation detail.

**Comment by davkean** [comment]
We don't provide a good way for this.

**Comment by drewnoakes** [comment]
> Isn't there a better way for Roslyn to determine the target framework here?

I've wondered about this too as it seems a bit hacky, but that's how it's worked for years now and is essentially public API.

>  I would have thought that $TFM:Foo format is an implementation detail of the project system, and shouldn't be relied on.

The `TFM:*` flag is there solely for outside consumers. We don't use it within the Project System.
