### ISSUE TITLE
Connected Services node appears for every .NET Core project type

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/project-system#5992]
**Visual Studio Version**: IntPreview [29916.199.master]

**Summary**: In recent IntPreview builds, the Connected Services node has started appearing on every .NET Core project type. Is this an expected design change?

**Steps to Reproduce**:

1. Create .NET Core Console, WinForms, ASP.NET Core or WPF app
2. Observe the Solution Explorer

**Expected Behavior**: I'm not 100% certain, but should this only appear for ASP.NET Core projects? The node does appear on .NET Framework ASP .NET web application projects. However, it doesn't appear on .NET Framework Console, WinForms or WPF projects.

**Actual Behavior**: It appears everywhere.

![image](https://user-images.githubusercontent.com/116161/76863254-75073100-681c-11ea-85fa-01688a5ea44a.png)

![image](https://user-images.githubusercontent.com/116161/76863265-78022180-681c-11ea-9f40-9da35c822317.png)

**Comment by jmarolf** [comment]
I can also reproduce this bug on internal builds

**Comment by davkean** [comment]
I have a thread going on this.



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by davkean** [comment]
Dup'd against this https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1083875.
