### ISSUE TITLE
Add COM Reference adds invalid reference on some projects

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#5995]
1. Check out this repo
2. In VS, right click "Dependencies" of `Microsoft.VisualStudio.ProjectSystem.Managed`
3. Select "Add COM Reference..."
4. Select the first item "Accessibility" and OK

![image](https://user-images.githubusercontent.com/350947/76909299-fcc56c00-68fe-11ea-9217-ce5757c83bd4.png)

```diff
diff --git a/src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj b/src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
index 12c091e7f..d8d14ef0b 100644
--- a/src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
+++ b/src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
@@ -451,6 +451,15 @@
     <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
   </ItemGroup>
 
+  <ItemGroup>
+    <COMReference Include="{1ea4dbf0-3c3b-11cf-810c-00aa00389b71}">
+      <Guid>1ea4dbf0-3c3b-11cf-810c-00aa00389b71</Guid>
+      <VersionMajor>1</VersionMajor>
+      <VersionMinor>1</VersionMinor>
+      <WrapperTool>tlbimp</WrapperTool>
+    </COMReference>
+  </ItemGroup>
+
   <ItemGroup>
     <None Update="ProjectSystem\Rules\AdditionalDesignTimeBuildInput.xaml">
       <Generator>MSBuild:Compile</Generator>
```

Doing the same for a new .NET Core project works correctly. There's something about `Microsoft.VisualStudio.ProjectSystem.Managed` that's causing it to fail in this way.

Moved from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1083908.

**Comment by drewnoakes** [comment]
Investigation narrowed this down to this line:

https://github.com/dotnet/project-system/blob/e01e676a02f69eb809b3540f046007ef046bd00c/Directory.Build.targets#L5

Removing the RepoToolset import fixes the bug.

Sending back to triage. This is currently in 16.7, but given it's triggered by RepoToolset it seems less likely it has widespread customer impact.

**Comment by jjmew** [comment]
At this point we believe this only affects our own repo.
