### ISSUE TITLE
when Visual Studio is open for several hours, namespaces stop resolving and things build successfully that should never build

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5997]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/790971/when-visual-studio-is-open-for-several-hours-names.html). Please vote and comment there to make sure your voice is heard._

---
I've been hitting an issue where if I've had Visual Studio 2019 open for several hours, sometimes more than a day, namespaces stop resolving that were there for a long time. Additionally, I've experienced when this happens code that should never compile seemingly builds successfully. The only way I've found to resolve this is to close and re-open Visual Studio which is quite disruptive.

---
#### Kelly Kosiewicz [MSFT] on 10/23/2019, 10:50 AM: 

<p>Forgot to mention, this also happens pretty consistently when switching between branches as well.</p>

#### Visual Studio Feedback System on 10/23/2019, 07:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Veronica Giaudrone [MSFT] on 10/25/2019, 02:17 PM: 

<p>In order to investigate further, we’d need some more information, could you take a look at  <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a>, andcollect more information or record the scenario when you get in this state?. Thanks!</p>

#### Kelly Kosiewicz [MSFT] on 11/6/2019, 10:02 AM: 

Namespaces are not resolving after switching branches
#### Visual Studio Feedback System on 11/5/2019, 07:26 PM: 

We will close this report in 7 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Kelly Kosiewicz [MSFT] on 11/6/2019, 10:03 AM: 

<p>Just uploaded additional information. Thanks!</p>

#### Visual Studio Feedback System on 11/7/2019, 05:11 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Visual Studio Feedback System on 3/16/2020, 10:02 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Visual Studio Feedback System on 3/17/2020, 08:18 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dmonroym** [comment]
I can no longer repro this in 16.5. Talked with Kelly Kosiewicz who, along with her team, was seeing this constantly getting repro'd in 16.1 but no longer see it now in 16.5.

After attempting using the same solution as Kelly I can't repro it in 16.6 Preview 1 either so closing this for now.
