### ISSUE TITLE
.NET Core 3.x disappears from the target framework

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#5998]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/951005/net-core-3x-か対象のフレームワークから消える.html). Please vote and comment there to make sure your voice is heard._

---
[regression] [worked-in:16.5.0]
1. Create a .NET Core 3.1 project in one of the versions up to VS 16.4.x
2. Update to VS 16.5.0
3. When you open one project, .NET Core 3.1 disappears from the target framework.

Workaround
Install the .NET Core 3.1 VS SDK directly

---
#### tosiyuki on 3/17/2020, 00:31 AM: 

<p>再現しない環境と再現する環境がある。<br><br>再現する環境は、アップデート時に再起動が要求された。もしかすると再起動時の何かでセットアップ情報の一部がうまく更新されていない可能性があるが、詳細不明。</p>

#### Visual Studio Feedback System on 3/17/2020, 02:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ocallesp** [comment]
moved to MSBuild/CLI/SDK team since they own the setup TargetFramework
