### ISSUE TITLE
Adding an assembly reference to an SDK style project causes request for reload.

### ISSUE THREAD

**Issue by vritant24** [dotnet/project-system#6019]
I have tried adding an assembly reference to a `Project` object in two ways:
  - `ConfiguredProject.Services.AssemblyReferences.AddAsync(assemblyname, location)`
  - `VSProject.Referenfeces.Add(assemblyPath)`

Using both brings up a dialogue box saying that "The project has been modified outside the environment" and requests either saving, discarding, overwriting, or ignoring. 

Is this supposed to be the case? Using the 2nd method above doesn't cause the box to appear in non-SDK style projects. 
What's the recommended way of adding an assembly reference to a CPS project?

**Comment by vritant24** [comment]
@ManishJayaswal @AbhitejJohn This is currently blocking a smooth end-to-end fakes experience

**Comment by ManishJayaswal** [comment]
@jjmew - can we get some help in understanding how to suppress this dialog? This is a 16.6 feature so there is some urgency.
@davkean

**Comment by jjmew** [comment]
@vritant24 We belive this this is CPS not us. I would suggest you open bug against them.  cc:// @ManishJayaswal

**Comment by davidwengier** [comment]
This is being discussed offline with the appropriate folks, so going to close this. If the conclusion of the thread is a bug in this repo, feel free to repoen.
