### ISSUE TITLE
Tests take 30 seconds extra to finish

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#602]
It looks like the new DispatchThread class is causing tests to take 30 seconds extra to finish.

Test guys stated:

> On attaching to `vstest.executionengine*.exe`, I find the xunit adapter thread stuck (call stack below) on appdomain unload. If you're using another build (WPT branch for instance, please try attach to testhost*.exe).
> 
> Second observation is there are several thread stuck on Dispatcher.Run method in Microsoft.VS.ProjectSystem.DispatchThread. My hypothesis is the AppDomain Unload is stuck trying to abort these threads.

**Comment by davkean** [comment]
tag @BillHiebert

**Comment by BillHiebert** [comment]
This appears to have something to do with running in XUnit.  The call to Dispatcher.InvokeShutdown() doesn't seem to do anything. After the call neither of the flags HasShutdownStarted\HasShutdownFinished are set. I would expect at least HasShutdownStarted to be set to true. I also hooked up to the ShutdownStarted\ShutdownFinished events and these aren't called either. I am not sure what is going on here.

**Comment by davkean** [comment]
I spent a little bit of time trying to figure out cause to no avail.

We've not seen any progress on this for 7 months, so I'm going to box 30 minutes to write a different mock, if I fail, I'm going to either go through and disable all tests that use IProjectThreadingServiceMock tomorrow to avoid this path in test runs.

**Comment by davkean** [comment]
This has been fixed.
