### ISSUE TITLE
[VS Online] Project factory selector needs to be moved to CommonIDE

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#6052]
We have a project factory selector that determines whether a project gets opened in legacy or CPS. It currently lives in csproj/vbideprj.dll.

Two problems:

1) These dlls don't exist in server 64 mode , so these selectors need to be moved to a dll that exists; CommonIDE is makes the most sense.
2) There's apparently additional code in ProjectLoadJob.IsCPS that runs instead of the selector when the parallel load is enabled. This is out of sync with the selector which we changed in https://github.com/dotnet/project-system/issues/1358.

We should merge both of these (src/vsproject/vsproject/ProjectSelector.cpp  ProjectLoadJob.IsCPS) into a new class in CommmonIDE and move the selector registration to point to it. Without this, projects registered using legacy project GUID will not load in Server 64, and https://github.com/dotnet/project-system/issues/1358 will also not be fixed when running through parallel project load.

**Comment by tmeschter** [comment]
The original fix for #1358 was made in [VS PR 194553](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/194553).

**Comment by tmeschter** [comment]
A managed version of the native project selector was implemented in [VS PR 239926](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/239926).
The managed version was turned on by default in #6067.
Finally, the native project selector was removed in [VS PR 241932](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/241932).
