### ISSUE TITLE
NFE in Roslyn.Utilities.Contract.ThrowIfFalse

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#6060]
Exception type:   System.InvalidOperationException
Message:          Unexpected false
InnerException:   <none>
StackTrace (generated):
    SP       IP       Function
    28ACD368 0369AFC5 Microsoft_CodeAnalysis_Workspaces_ni!Roslyn.Utilities.Contract.Fail(System.String)+0x25
    28ACD378 63FFE82A Microsoft_CodeAnalysis_Workspaces_ni!Roslyn.Utilities.Contract.ThrowIfFalse(Boolean)+0x514f8a
    28ACD37C 2456D375 Microsoft_VisualStudio_LanguageServices_Implementation!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.EndBatch()+0x1d
    28ACD388 2456456E Microsoft_VisualStudio_ProjectSystem_Managed!Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost+WorkspaceProjectContextHostInstance+<ApplyProjectChangesUnderLockAsync>d__19.MoveNext()+0x316
    28ACE95C 73A7446B mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x67
    28ACE96C 73A70CD1 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x41
    28ACE978 653AFCC8 Microsoft_VisualStudio_Threading_ni!Microsoft.VisualStudio.Threading.ReentrantSemaphore+StackSemaphore+<>c__DisplayClass3_0+<<ExecuteAsync>b__0>d.MoveNext()+0x1a8
    28ACEB1C 73A7446B mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x67
    28ACEB2C 73A70CD1 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x41
    28ACEB38 653B0585 Microsoft_VisualStudio_Threading_ni!Microsoft.VisualStudio.Threading.AwaitExtensions+ExecuteContinuationSynchronouslyAwaiter.GetResult()+0x25
    28ACEB40 653AF254 Microsoft_VisualStudio_Threading_ni!Microsoft.VisualStudio.Threading.ReentrantSemaphore+StackSemaphore+<ExecuteAsync>d__3.MoveNext()+0x294
    28ACEC9C 73A7446B mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x67
    28ACECAC 73A70CD1 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x41
    28ACECB8 24563A51 Microsoft_VisualStudio_ProjectSystem_Managed!Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync+<ExecuteUnderLockCoreAsync>d__7.MoveNext()+0x1e1
    28ACEDAC 73A7446B mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x67
    28ACEDBC 73A70CD1 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x41
    28ACEDC8 111E2C2C Microsoft_VisualStudio_ProjectSystem!Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1+<ProcessInputQueueAsync>d__5[[System.__Canon, mscorlib]].MoveNext()+0x1fc

Also:

["Roslyn.Utilities.Contract.ThrowIfFalse(Boolean,String)","Microsoft.CodeAnalysis.ProjectDependencyGraph.WithProjectReferenceRemoved(ProjectId,ProjectId)","Microsoft.CodeAnalysis.SolutionState.RemoveProjectReference(ProjectId,ProjectReference)","Microsoft.CodeAnalysis.Solution.RemoveProjectReference(ProjectId,ProjectReference)","Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ConvertProjectReferencesToMetadataReferences_NoLock(ProjectId,String)","Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.RemoveProjectOutputPath(ProjectId,String)","Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.OnProjectRemoved(ProjectId)","Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProject.<RemoveFromWorkspace>b__112_0(Workspace)","Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyChangeToWorkspace(Action`1)","Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProject.RemoveFromWorkspace()","Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.Dispose()","Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextProvider.<ReleaseProjectContextAsync>d__7.MoveNext()","System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()","Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception)","Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()","Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()","GuardMethodClass.GuardMethod(Func`1,Func`2,Func`2)"]

**Comment by jjmew** [comment]
@ocallesp  can you take a look at this? we have set for 16.6

**Comment by davkean** [comment]
I believe the first one is addressed in https://github.com/dotnet/project-system/pull/6054, it will swap 1 fault for another, as I think an underlying exception caused it to trigger.

The second is being tracked by https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1092130.
