### ISSUE TITLE
An error occurred after changing the target version of framework project in the solution which also contain a Winforms Core project

### ISSUE THREAD

**Issue by Vino-Wang** [dotnet/project-system#6087]
**Visual Studio Version**:
Version 16.6.0 Preview 3.0 [30013.163.d16.6]

**Summary**:
The targeting framework version not be changed directly with no error, this behavior will confuse the users which using .NET Framework project and affect their existing framework project.

**More info**:
1.	Close and reopen the project properties page, this error is disappear, pages load normally and target version changed successfully.
2.	This issue is not reproducing when changing the target version in the solution that only have one .NET Framework Winforms project.
3.	This issue also can reproduce with 16.5 P3 build.
**Steps to Reproduce**:
1.	Create a .NET Core Winforms project.
2.	Add a .NET Framework Winforms project in the same solution.
3.	Right click on the NetFx project name and select Properties.
4.	Change the Target Framework version in Application property page.
5.	Click ‘Yes’ in the ‘Target Framework Change’ window.

 Or

1.	Extract the attached file and open the .sln file.
[MultiProject.zip](https://github.com/dotnet/winforms-designer/files/4454718/MultiProject.zip)
2.	Implement the above step3-5.

**Expected Behavior**:
There is no any error occurring and Project properties page load/refresh successfully.
![ChangeTargetingIssue_NotRepro_NetFx](https://user-images.githubusercontent.com/18568603/78870602-fa2ae200-7a78-11ea-9caa-075601f517be.gif)

**Actual Behavior**:
Sometimes the .csproj file of Core project is opened and go back to the Application property page, the whole properties page load failure with an error.
![ChangeTargetingIssue](https://user-images.githubusercontent.com/18568603/78870618-feef9600-7a78-11ea-9081-a94f6994b222.gif)
![Error](https://user-images.githubusercontent.com/18568603/78870776-4544f500-7a79-11ea-8fa5-06a20e6aadc5.PNG)

**User Impact**:
The targeting framework version not be changed directly with no error, this behavior will confuse the users which using .NET Framework project and affect their existing framework project.

**Comment by jjmew** [comment]
@Vino-Wang Is this 100% repro? we are not able to reproduce in Version 16.6.0 Preview 3.0 [30001.196.master]

**Comment by Vino-Wang** [comment]
@jjmew Yes, 100% repro. Now it is also reproducing with 16.6.0 Preview 4.0 [30021.205.d16.6]. 
In addition, your build Version 16.6.0 Preview 3.0 [**30001.196**.master] is old than me Version 16.6.0 Preview 3.0 [**30013.163**.d16.6]

**Comment by Zheng-Li01** [comment]
The issue also can reproduce on with below steps.
1. Create a winforms application.
2. Copy the solution to the desktop.
3. Double click the .sln to open the project.
![FeedBack6087](https://user-images.githubusercontent.com/38325459/86197928-0ced1880-bb89-11ea-807b-0ac13cbb8c8d.gif)

Result:
The page load failed, but the Form1.designer can opened successfully, and no others effect.

## More info:
1. The issue can't reproduce on .NET Core project.
2. The issue can't reproduce when opened the project in the origin created path.(such as C:\Users\v-zhgl\source\repos\FeedBackTesting)
3. The issue only can reproduce when opening the project firstly on the Desktop, after closed & re-open the project, the issue can't reproduce.
4. The issue will disappear when closed the failed page, then re-open it.

**Comment by ocallesp** [comment]
This issue still repro: Create a solution, add any NetFramework project, and any NetCore project. Right-click on NetFramework project and select Properties. Go to Application tab, and change the target framework to something different. In the dialog box select Yes.

**When the error appears, it also opens the project file from Console. This behavior is wrong.**
The documentation says that this will happen when [RegisterSharedProjectFiles ](http://index/?rightProject=Microsoft.VisualStudio.ProjectSystem.VS.Implementation&file=Package%5cSharedProjects%5cSharedProjectFileRegistrationService.cs&line=93)or [RegisterSharedMSBuildFiles](http://index/?rightProject=Microsoft.VisualStudio.ProjectSystem.VS.Implementation&file=Package%5cSharedProjects%5cSharedProjectFileManagerHierarchy.cs&line=660) but CPS is not registering any file.

![github6087](https://user-images.githubusercontent.com/510598/89734158-36625500-da0f-11ea-9882-0de1518b1d27.gif)

@davkean This seems to be an issue in CPS.
"_A document (DocData object) will be registered in the RunningDocumentTable that will block the user from  opening the file simultaneously in a text (or other) editor._"

**Comment by davkean** [comment]
> The documentation says that this will happen when RegisterSharedProjectFiles or RegisterSharedMSBuildFiles but CPS is not registering any file.

The CPS project file opening is red-herring and is because it is given focus when the project is reloaded and therefore opens in the preview window. This behavior will have nothing to do with CPS nor Shared Projects.

**Comment by ocallesp** [comment]
Not able to repro this issue.
