### ISSUE TITLE
The project-system should support undo

### ISSUE THREAD

**Issue by mikadumont** [dotnet/project-system#6089]
Have the ability to undo moving a file/folder to a project or folder and perhaps have the following warning dialogue pop up:
![image](https://user-images.githubusercontent.com/46729679/79279826-c4646f80-7e63-11ea-8222-c062b91ada87.png)

This will help us with the following scenario [37243](https://github.com/dotnet/roslyn/issues/37243)

**Comment by davkean** [comment]
Tracking this under a general purpose "project-system should opt into undo". At the moment, Roslyn already works around the lack of this by tracking its own undo transaction around project system operations, such as when it renames a file.

**Comment by mikadumont** [comment]
@davkean what is the status of this feature?

**Comment by davkean** [comment]
This work isn't scheduled.

**Comment by ocallesp** [comment]
This is part of #6869 and the UX will be implemented by the Roslyn Team.
dotnet/roslyn#37453

cc. @jjmew, @mikadumont, @ryzngard

**Comment by mikadumont** [comment]
@ocallesp why is this being closed? There currently isnt an undo/redo when moving around files in general and would be great to have that. This doesnt relate to the sync namespace feature.

**Comment by ocallesp** [comment]
This changes are in CPS.

**Comment by ocallesp** [comment]
The work item on the CPS side is AB#1290920
