### ISSUE TITLE
Keep .csproj clean when setting build action

### ISSUE THREAD

**Issue by JVimes** [dotnet/project-system#6099]
**Visual Studio Version**:  16.5.4

**Summary**: Setting a build action creates more tags than seem necessary in .csproj, and related tags aren't together.

**Steps to Reproduce**:

1. Create WPF .NET Core app
2. Add a text file and set its build action to "Resource"
3. Add a .png file and set its build action to "SplashScreen"
4. Save all

**Actual Behavior**: Three ItemGroups are created, and the None tags are separate from the build action tags.

```csproj
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
<!-- . . . -->

  <ItemGroup>
    <None Remove="SplashScreen.png" />
    <None Remove="TextFile1.txt" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="TextFile1.txt" />
  </ItemGroup>

  <ItemGroup>
    <SplashScreen Include="SplashScreen.png" />
  </ItemGroup>

</Project>
```

**Expected Behavior**: 

I would like the build action tags (Resource, SplashScreen, etc.) to imply the None tags, and be in the same ItemGroup:

```csproj
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
<!-- . . . -->

  <ItemGroup>
    <Resource Include="TextFile1.txt" />
    <SplashScreen Include="SplashScreen.png" />
  </ItemGroup>

</Project>
```

If the None tags must stay, I would like fewer ItemGroups and for None tags to be kept in pairs with their build action tags (Resource, SplashScreen, etc.).

```csproj
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
<!-- . . . -->

  <ItemGroup>
    <None Remove="TextFile1.txt" />
    <Resource Include="TextFile1.txt" />
    <None Remove="SplashScreen.png" />
    <SplashScreen Include="SplashScreen.png" />
  </ItemGroup>

</Project>
```

**User Impact**:  .csproj gets less clean with the number of build actions set.

**Comment by davidwengier** [comment]
Duping against #4534
