### ISSUE TITLE
Project System: Renaming project.json to [ProjectName].project.json should take immediate effect

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#61]
_From @davkean on April 29, 2016 17:9_

Unlike csproj, which requires a project reload.
1. Create a new project
2. Rename the project.json to ProjectName.project.json.
3. Edit the project.json to add a reference to your favorite package.
4. Rebuild.

**Expected:** the package reference is added
**Actual:** it's not

Background: once the project.json is renamed, we don't have the proper logic to update the file system watcher that is watching project.lock.json.

_Copied from original issue: dotnet/roslyn#10973_

**Comment by shederman** [comment]
Sorry, can I ask a simple question? Why are we using [ProjectName].project.json? If I want to rename a project, I must change the name of the directory **as well** as the name of the project file? Why would we want that?

Not trying to be combative, just asking to understand.

**Comment by davkean** [comment]
This isn't relevant anymore; we've moved to putting references inside the project file itself.
