### ISSUE TITLE
[.NET 5 P3.20211.8] 1 error and 1 warning occured when changing project target framework from .NET 5 to .NET Core 3.1

### ISSUE THREAD

**Issue by jjmew** [dotnet/project-system#6100]
Affected Branch: master

Affected Build: 30013.171

Affected SKU: ENT

Affected Product Language:  EN

Operation System Information:19h2

Machine: XETLAB017(10.195.201.195）

Workloads:.NET desktop development + Universal Windows Platform development

 

 

More info:

1.  .Net 5 build: \\vsufile\patches\sign\NET\CORE_BUILDS\5.0.X\5.0.0\5.0.100-preview.3.20211.8

     Feed:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json

2. It doesn't repro when you change project target framework from .NET Core 3.1 to 3.0.

3. if you close the solution and reopen it, this bug will not repro.

 

Steps to reproduce:

1. Create a WPF(.NET Core) Project.

2.  Add a WPF User Control Library(.Net Core) to the solution.

3. Set the Grid background="Red" in UserControl1.xaml.

4. Add project reference from WPF Core project to WPF User Control Library(.Net Core) and then build the solution.

5.  Open MainWindow.xaml, drag UserControl1 from toolbox to designer and save it.

6. Change these 2 projects target framework from .NET 5 to .NET Core 3.1 and save it.

7. Observe the Error List.

 

Expected: 

No errors or warnings in Error List.

 

Actual:

1 error and 1 warning occured in the error list

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | CS0103 | The name 'InitializeComponent' does not exist in the current context | WpfApp1 | C:\Users\v-wenjuz\source\repos\WpfApp1\WpfApp1\MainWindow.xaml.cs | 25 | Active
Warning | MC3074 | The tag 'UserControl1' does not exist in XML namespace 'clr-namespace:WpfControlLibrary1;assembly=WpfControlLibrary1'. Line 12 Position 10. | WpfApp1 | C:\Users\v-wenjuz\source\repos\WpfApp1\WpfApp1\MainWindow.xaml | 12 |

**Comment by davidwengier** [comment]
From AB#1104079

**Comment by davidwengier** [comment]
This appears to be a limitation/by design of CPS. What is happening is that a full build of the user control is needed, because without the DLL for it available the generation of the `MainWindow.g.i.cs` file is not successful. Unfortunately it is by design that doing a build of one project doesn't start a design time build of another.

The workaround is to kick off a design time build in some way, and reloading the project is the most straightforward way to do that.
