### ISSUE TITLE
1 errors and 1 warning occurred after Building the solution with multiple projects

### ISSUE THREAD

**Issue by Mandy1204** [dotnet/project-system#6104]
**Affected Branch**: master
**Affected Build**: 29930.122
**Affected SKU**: ENT
**Affected Product Language**:  EN
**Operation System Information**:19h2
**Machine**: XETLAB017(10.195.201.195）
**Workloads**:.NET desktop development + Universal Windows Platform development

**More Info**: 
It also reproes on Debug x64.
It also repro on d16.6(2 errors and 1 warning) and d16.5(1 error and 1 warning). 

**Steps to reproduce**:
1. Download project from [https://github.com/Guerra24/LRReader](https://github.com/Guerra24/LRReader).
2. Open the solution and set LRReader.UWP as the startup project.
3. Set Debug x86/x64 and build the solution.

**Expect**:
Build solution successfully without errors and warning.

**Actual**:
1 errors and 1 warning occurred after Building the solution.
![image](https://user-images.githubusercontent.com/29625285/79537566-18b25e00-80b5-11ea-9dab-7d82f905ea6b.png)

**Comment by ocallesp** [comment]
When AnyCPU
![image](https://user-images.githubusercontent.com/510598/79815772-5eca2480-8336-11ea-8dd9-fbe9760ac237.png)

When using x86 or x64 the https://www.nuget.org/packages/Microsoft.VCRTForwarders.140
is used. 
This issue seems not related to Project System
