### ISSUE TITLE
Review searching items within the dependencies tree by path

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6110]
Paths of items within the dependencies node are somewhat contrived.

Verify whether there is a valid scenario for this function, and if not:

1. Change `DependenciesProjectTreeProvider.FindByPath` to always return `null`
2. Remove `IDependenciesTreeViewProvider.FindByPath`

**Comment by davkean** [comment]
The one thing that we might want to think about, is that this API is called by _IVsHierarchy.ParseCanonicalName_ and _IVsProject.IsDocumentInProject_, which paired with IVsHierarchy.GetCanonicalName is supposed to return/provide a way to retrieve and query any item within a tree. These APIs don't actually have to take paths, but rather monikers that more than often are paths. For drag and drop, I want to select/expand to a project reference for the drag as reference feature- and I was thinking that combos of this these APIs combiend with Solution Explorer APIs (ExpandItem) would provide that.

One option might to not remove this implementation, but to short circuit when the provided moniker isn't actually a moniker/id that we produced.

**Comment by davkean** [comment]
Actually this bug provides more informationa and either one should be dup'd against the other: https://github.com/dotnet/project-system/issues/2559.

**Comment by drewnoakes** [comment]
Closing as duplicate of #2559.
