### ISSUE TITLE
Enabling native code debugging on a .net core 3.1 project doesn't start correctly

### ISSUE THREAD

**Issue by chrisbardon** [dotnet/project-system#6112]
**Visual Studio Version**:
Microsoft Visual Studio Enterprise 2019 Version 16.5.4
**Summary**:
I created a WPF project in .net core 3.1 that used a native component through a C++/CLI wrapper DLL. If I try to enable native debugging in the project properties, an f5 debug does not start the project correctly.  If I ctrl+f5, and then attach (manually selecting CoreCLR and Native), then it works as expected.

**Steps to Reproduce**:

1. Create a WPF .net core 3.1 project
2. Add a C++/CLI wrapper DLL to a native library
3. In the .net core app, enable native code debugging
4. Start debugging
5. Observe that nothing launches.

**Expected Behavior**:
Expecting that this would launch with both debuggers attached (similar to how the launch + attach works).

**Actual Behavior**:
Debugging doesn't work as expected.
**User Impact**:
Much more difficult to debug hybrid .net core apps.

**Comment by jjmew** [comment]
@ocallesp  can you check if it repros?

**Comment by ocallesp** [comment]
Still reproes in VS Main and Net Core 7.0

![debugging](https://user-images.githubusercontent.com/510598/200466244-740e1712-6c1d-448a-8e86-9d19cb693ed8.gif)

**Comment by ocallesp** [comment]
The message "No executable code of the debugger's target code type is associated with this line." is thrown by the VS debugger

**Comment by ocallesp** [comment]
Moved to [AB#1676893](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1676893)
