### ISSUE TITLE
Infinite cycle of DesignTimeBuilds in multi target projects referencing System.Web.UI.Page

### ISSUE THREAD

**Issue by joaorosado** [dotnet/project-system#6129]
**Visual Studio Version**:
16.5.4

**Summary**:
Multitarget project keeps making DesignTimeBuilds
Also if asked to Build it says it is always not up-to-date.

**Steps to Reproduce**:

1. Created an empty solution with just

csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <TargetFrameworks>net461;netstandard2.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup Condition=" '$(TargetFramework)'!='netstandard2.0'">
        <Reference Include="System.Web" />
    </ItemGroup>

</Project>
```

BasePage.cs:
```
#if !NETSTANDARD

using System.Web.UI;

namespace bla { 
    public class BasePage : Page {
    }
}
#endif
```

2. Just saving those 2 files causes VS to keep building in an infinite cycle
![image](https://user-images.githubusercontent.com/5313340/80249545-f34fc200-8669-11ea-8720-dab45799e848.png)

![image](https://user-images.githubusercontent.com/5313340/80249658-242ff700-866a-11ea-9945-7d8e96ea5fbb.png)

**Expected Behavior**:
That after a DesignTimeBuild it stops.
Also that subsequent Builds say that the project is up-to-date instead of
`FastUpToDate: The set of project items was changed more recently (2020-04-24 20:28:48) than the earliest output 'C:\Users\jmr\source\repos\ClassLibrary1\ClassLibrary1\obj\Debug\net461\ClassLibrary1.dll' (2020-04-24 20:28:45), not up to date. (ClassLibrary1)`

**Actual Behavior**:
DesignTimeBuilds never stop

**User Impact**:
Visual studio gets very slow and all projects depending on the affected one keeps being build over and over again.
Not sure what other classes can trigger this.

**Workaround**
Exclude the problematic file completely from the netstandard2.0 compilation
```
<ItemGroup Condition=" '$(TargetFramework)'=='netstandard2.0'">
    <Compile Remove="BasePage.cs" />
</ItemGroup>

```

**Comment by drewnoakes** [comment]
I ran some more tests on 17.1 and could not get the infinite loop of design-time builds to occur. Nor could I see the failure in the fast up-to-date check.

I'll close this. If you're able to reproduce this still, we can reopen and I will revisit it.
