### ISSUE TITLE
GetResolvedReferenceAsync doesn't work for Package References

### ISSUE THREAD

**Issue by vritant24** [dotnet/project-system#6137]
After successfully adding a package reference to a project using `IPackagereferenceService.AddAsync()`, and waiting for a restore, `IPackagereferenceService.GetResolvedReferenceAsync()` returns null. 

expected:
return a reference to verify whether the package reference was successfully restored.

**Comment by jjmew** [comment]
@vritant24 do you still need us to look at this? it is over a year old

**Comment by vritant24** [comment]
Ah we are no longer blocked by this. I'll close this issue, thanks :)
