### ISSUE TITLE
Create an Active ConfiguredProjects Subscription Service

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#614]
Similar to IActiveConfiguredProjectSubscriptionService, create a service that will allow listeners to subscribe to changes in the active projects, _and_ any changes in the set of active projects (e.g. because of changes to target framework). This should replace the patterns in #524 and #534 where we first listen to changes in the active "VS" configured project, then reset subscriptions on that project to detect changes within it.

Given the following configured projects:

```
///         Debug | AnyCPU | net45
///         Debug | AnyCPU | net46
///         Release | AnyCPU | net45
///         Release | AnyCPU | net46
```

If the active VS configuration = "Debug | AnyCPU", then active configured projects tracked by this service would be:

```
///         Debug | AnyCPU | net45
///         Debug | AnyCPU | net46
```

And an event would be fired if 
- any changes happen to either configuration, 
- if target framework changes,
- if active "VS" configuration changes

This should help limit possible races associated with resetting subscriptions

**Comment by mavasani** [comment]
@srivatsn Does this meet the RTW bar? This is just a refactoring to share code between 2 places (and probably more in future) where we have similar functionality/implementation.

**Comment by natidea** [comment]
This will be more than refactoring since @davkean wanted this to mirror the implementation in `ActiveConfiguredProjectSubscriptionService` and have *one* subscription that fires for both project changes *and* changes in the set of active projects. Right now both places use two subscriptions, resetting the second one each time the set of active projects change.

**Comment by mavasani** [comment]
Couple of points:

1. What is broken that we are trying to fix? Do we have any failing scenarios to justify this for RTW? Otherwise, I am concerned this will be rejected in the shiproom.
2. I am worried about the potential regression/race conditions being introduced from this level of refactoring. We would probably have to invest good amount of testing/bake time for this change.

**Comment by srivatsn** [comment]
Moving out to 1.1.

**Comment by davkean** [comment]
Having spent half a day debugging through all this, I have some thoughts here:

1) The ActiveConfiguredProjectsService should be responsible for telling consumers when the active configured projects have changed. Right now, consumers of this service have intimate knowledge that changes to the "TargetFrameworks" property causes this to change. They all listen to data flow, wait for the TFM to change, push to the UI thread, and then Refresh the active config (which in turns causes the active config**s** to change). This seems overly complex, when really all we should be doing is waiting until the active config (and hence active configs) change.

This will reduce the amount of knowledge that other components have that TFM dimension drives the configurations.

2) We should add a new service, ActiveConfiguredProjectsSubscriptionService, that centralizes and coordinates the dataflow for the active configured projects. A component should be able to listen to this, and never have to worry about unsubscribing/subscribing as configs change. The callback would include enough information for the language service host to fire up/close down workspace contexts, and enough info for the NuGetRestorer to push its changes to NuGet.

**Comment by Pilchie** [comment]
This is the PR you just added today, right?

**Comment by davkean** [comment]
This is now resolved, CPS added `IActiveConfigurationGroupService` that centralizes "active" configuration management, and I added `IConfiguredProjectImplicitActivationTracking` to track the activation state of an individual configuration.
