### ISSUE TITLE
IVsSolution3.GetUniqueUINameOfProject does not produce unique name for multi-targeted project

### ISSUE THREAD

**Issue by sharwell** [dotnet/project-system#6142]
**Visual Studio Version**: 16.6 Preview 3

**Summary**:

`IVsSolution3.GetUniqueUINameOfProject` does not produce a unique name for a multi-targeted project. Roslyn [delegates](https://github.com/dotnet/roslyn/blob/55ec5980375f0f72094079aeaf38fcfffad47568/src/VisualStudio/Core/Def/Implementation/Library/ObjectBrowser/Extensions.cs#L52-L64) to this implementation for **Class View** and **Object Browser** (dotnet/roslyn#43712).

**Steps to Reproduce**:

1. Create a multi-targeted project
2. Open **Class View** or **Object Browser**

**Expected Behavior**:

The multiple instances of the project have unique names. For example:

* My.Project (netstandard2.0)
* My.Project (netcoreapp3.1)

**Actual Behavior**:

The multiple instances of of the project all have the same name. For example:

* My.Project
* My.Project

**User Impact**:

Users cannot tell which target framework they are looking at in **Class View** or **Object Browser**.

**Comment by sharwell** [comment]
@davkean @drewnoakes if this is a behavior that the project system would like to change, then Roslyn would likely not need to take further action. However, if the project system is already behaving as expected, I have prepared an alternative fix for the original issue (see links). Please let me know the direction you believe is best for this.

**Comment by davkean** [comment]
GetUniqueUINameOfProject takes a IVsHierarchy. There is only one of these for a multi-targeted project. Roslyn should be using IWorkspaceProjectContext.DisplayName to populate these.

**Comment by davkean** [comment]
I'm going to resolve this, please reopen if you disagree. // cc @jasonmalinowski

**Comment by sharwell** [comment]
@davkean Thanks this simplified our code a bunch 👍
