### ISSUE TITLE
Design Time Builds failing if we have some derived properties in Implicit or leading imports

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/project-system#6143]
_From @Anipik on Monday, April 27, 2020 8:50:43 PM_

In case of multple TargetFrameworks,  DesignTimeBuild uses  msbuild ```setproperty``` function to  set the TargetFramework property.  

So this updates a property if it exists, otherwise it searches for the first unconditioned PropertyGroup in the project file to add the property to. This is always going to be after any implicit imports as well as explicitly leading imports. This appears to be the long-standing behavior of SetProperty. Contrast that to SetGlobalProperty, which will treat the property as global.

Hence any property derived from targetFramework in implicit imports and leading imports will not be evaluated correctly.

There is a detail repro here https://github.com/dotnet/runtime/issues/33427#issuecomment-597634844

cc @ericstj @ViktorHofer 

similar issue https://github.com/OmniSharp/omnisharp-roslyn/issues/1738

_Copied from original issue: microsoft/msbuild#5319_

**Comment by rainersigwald** [comment]
Please let us know if you need a new API from MSBuild to fix this, we can work together if so.

**Comment by ericstj** [comment]
@davkean please have a look.  This is the same as https://github.com/dotnet/project-system/issues/5996 which was moved to msbuild and now came back.  I believe the bug here is that project system (or some service it uses) is calling SetProperty instead of SetGlobalProperty.

**Comment by davkean** [comment]
This is a core CPS bug and not this repo. I suspect looking at the code, they've done this because they have an existing project instance and can't change global properties. @Lifengl?

**Comment by ViktorHofer** [comment]
ping @lifengl

**Comment by jjmew** [comment]
@ericstj  You will need to file a bug in Azure Dev Ops under DevDiv\VS Core\Project as this is a CPS issue

**Comment by ericstj** [comment]
@Anipik can you please open the issue as @jjmew  suggests?

**Comment by ViktorHofer** [comment]
Please 'cc me in the issue as I'm interested in a near-term solution.

**Comment by Anipik** [comment]
sure i will do that
