### ISSUE TITLE
Ordering of project references in right-click dialog

### ISSUE THREAD

**Issue by cartermp** [dotnet/project-system#6147]
In VS 16.5, right-clicking on the Dependencies node shows this:
![image](https://user-images.githubusercontent.com/6309070/80772769-a60d9d80-8b0c-11ea-9019-4047771cc009.png)

In 16.7 dogfood, it shows this:

![image](https://user-images.githubusercontent.com/6309070/80772458-b40eee80-8b0b-11ea-8890-14a98bec019c.png)

This can be useful, since you only need to click once to add a COM Reference or Shared Project reference, whereas before you need to select the appropriate item on the left-hand side of the References dialog.

However, one possible problem could be muscle memory. I found myself instinctively clicking the first item in the list since I'm almost always adding a project reference, and the 16.5 behavior gets me to what I need.

It may be worth considering reordering these based on usage (or intended usage) instead of alphabetically. But not being alphabetical can also cause other concerns, since I could imagine someone expecting the list to be alphabetical.

**Comment by cartermp** [comment]
Also, unrelated to the project system perhaps, but the "Add Connected Service" item feels like it would be less used than the "Manage NuGet Packages" item, so I'd expect that to come after "Manage NuGet Packages". But since there's already a precedent established in 16.5 that might be risky to change.

**Comment by drewnoakes** [comment]
https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/246091
