### ISSUE TITLE
Use full TargetFrameworkMoniker in NuGetRestorer

### ISSUE THREAD

**Issue by natidea** [dotnet/project-system#615]
We are temporarily using the short tfm to exchange with NuGet's Nominate Restore in #524 to workaround two issues:
- TargetFrameworkMoniker is not available until first restore. This results in default TFM NET Framework 4.0 always being sent.
- NuGet should use target framework in generated props/targets that matches the TF in the Project File. So e.g. if the Project File has TF `netcoreapp10`, we exchange canonical TFM `.NETCoreApp,Version=v1.0` that NuGet processes to `netcoreapp1.0`, which is different from what is in the file. One solution would be for NuGet to filter by canonical TFM instead of TF.

Once these are resolved, revert back to using the full TargetFrameworkMoniker.

**Comment by natidea** [comment]
Instead of reverting to full TFM, we are passing the full TFM as a property that NuGet can consume

**Comment by davkean** [comment]
NuGet should only be using the short TFM as part of the conditions - it should be using the full TFM as the canonical indication of the "target framework" is that's what is happening?

**Comment by natidea** [comment]
I believe NuGet is still using the TargetFramework.
Relevant bug is https://github.com/NuGet/Home/issues/5154

**Comment by natidea** [comment]
Confirmed we are passing the full TFM as a property that NuGet can consume
