### ISSUE TITLE
Exception occurred. (Exception from HRESULT: 0x80020009 (DISP_E_EXCEPTION))			

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6177]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1015106/exception-occurred-exception-from-hresult-0x800200.html). Please vote and comment there to make sure your voice is heard._

---
[regression] [worked-in:16.6.0 Preview 5.0]
Try to install a nuget package with the nuget manager.

Get: 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception occurred. (Exception from HRESULT: 0x80020009 (DISP_E_EXCEPTION))

---
#### Visual Studio Feedback System on 5/3/2020, 08:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by kartheekp-ms** [comment]
I was able to reproduce this error message only **once** on my local machine "Microsoft Visual Studio Enterprise 2019 Preview, Version 16.6.0 Preview 6.0" following below steps. 

- Open [`NuGet.Client`](https://github.com/NuGet/NuGet.Client) solution
- Press F5 to launch experimental instance
- Create new .NET framework project (Console App - .NET Framework - C#)
- open `Manage NuGet Packages..` window in VS
- Install any package, but I tried with `Newtonsoft.json` package
- I noticed `Exception from HRESULT: 0x80020009 (DISP_E_EXCEPTION)` exception in the `Error List` window in VS.

I have noticed from my team member @dominoFire [comment](https://github.com/NuGet/NuGet.Client/pull/3377#discussion_r419610601) that that this exception is raised almost every time. The inner-exception call stack points to the `EnvDTE` object.
```shell
System.Runtime.InteropServices.COMException (0x80020009): Exception occurred. (Exception from HRESULT: 0x80020009 (DISP_E_EXCEPTION))
   at EnvDTE.Property.get_Value()
   at NuGetVSExtension.OutputConsoleLogger.<GetMSBuildVerbosityLevelAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGetVSExtension.OutputConsoleLogger.<<Start>b__24_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run(Func`1 asyncMethod)
   at NuGetVSExtension.OutputConsoleLogger.Start()
   at NuGet.PackageManagement.UI.NuGetUI.BeginOperation()
   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass12_0.<<PerformActionImplAsync>b__0>d.MoveNext()
Time Elapsed: -10675199.02:48:05.4775808
========== Finished ==========
```

**Comment by davkean** [comment]
Closing this and moving the original to NuGet as this is NuGet code attempting to read a setting that has been moved by platform.

**Comment by div78641** [comment]
Is there a link to the work item where this was move to? I am currently seeing this issue when using the NuGet Package Manger 5.6.0 UI within Visual Studio Pro 16.6.0 freshly installed into Windows 10 Pro version 2004 (build 19041.264). I can work around this error by using the Package Manager command line but would like to track the issue and comment on it (if needed). Thanks.

**Comment by davkean** [comment]
@div78641 First link above: https://developercommunity.visualstudio.com/content/problem/1015106/exception-occurred-exception-from-hresult-0x800200.html.
