### ISSUE TITLE
 VS 2019 does not showing target framework 3.0 or 3.1

### ISSUE THREAD

**Issue by NiteshKoushik** [dotnet/project-system#6180]
Hello,
VS 2019 is not showing target the framework having .NetCore 3.0 and 3.1 version.

I have updated version of VS 2019, i.e. 16.1.3 and VS 2019 is updated on 6 May 2020.

I have tried enabling "use previews of .Net Core SDK" from tools, restarted VS and my system couple of times - but nothing works.

I have installed x64 and x86 SDK of 3.0 and 3.1 version in my machine. Initially tried with x64 and post that installed x86 SDK - but nothing works.

Please suggest, if any one has solution for the same.

Thanks in advance.

Regards,
Nitesh

**Comment by drewnoakes** [comment]
@NiteshKoushik could you provide some more information please and perhaps a screenshot? Where do you want these frameworks to show?

**Comment by drewnoakes** [comment]
Relates to #5547.

**Comment by NiteshKoushik** [comment]
![Capture](https://user-images.githubusercontent.com/39699046/81639209-ef2cee00-9438-11ea-9dc3-d8b0c8f50302.PNG)

**Comment by NiteshKoushik** [comment]
In project - properties the target framework is not appearing.

**Comment by NiteshKoushik** [comment]
Yes - this is similar to Relates to #5547. I have commented on that request too.
Also I can see all the installed version (till 3.1) from command prompt with the command "dotnet --list-sdks" but the same is not appearing in VS

**Comment by drewnoakes** [comment]
@NiteshKoushik please confirm that you don't have a `global.json` file in your project folder, or _any_ ancestor folder, all the way up to your drive root.

**Comment by NiteshKoushik** [comment]
Yes.. I dont have a global.json file

**Comment by yeyener** [comment]
Hello, I have the exact same issue. VS 2019 version : 16.5.4

**Comment by NiteshKoushik** [comment]
Thanks @yeyener  - I have created global json file in file system and this is how it looks, but still it is not appearing in VS-2019 

{
  "sdk": {
    "version": "3.1.201",
    "rollForward": "latestPatch"
  }
}

**Comment by NiteshKoushik** [comment]
I have the below sdk versions

1.1.9 [C:\Program Files\dotnet\sdk]
2.1.201 [C:\Program Files\dotnet\sdk]
2.1.700 [C:\Program Files\dotnet\sdk]
3.0.103 [C:\Program Files\dotnet\sdk]
3.1.201 [C:\Program Files\dotnet\sdk]

**Comment by drewnoakes** [comment]
@NiteshKoushik the `global.json` file does not have to appear in VS for it to have an effect on how VS behaves. You really need to check your disk. Start in the folder that contains your project then look in every ancestor folder.

Can you share the contents of the project file?

**Comment by NiteshKoushik** [comment]
@drewnoakes  the global.json file is kept in VS project root node.  Post that I am getting the below error as my MS build is not supporting. This is the issue similar to #1256

**Comment by NiteshKoushik** [comment]
![error](https://user-images.githubusercontent.com/39699046/81806234-cdfff680-9539-11ea-9256-27db9bf992e6.PNG)

**Comment by drewnoakes** [comment]
@NiteshKoushik can you share the contents of the project file that's failing to load? What version of Visual Studio 2019 are you using?

**Comment by NiteshKoushik** [comment]
Hello @drewnoakes , Im using VS 2019 16.1.3 Enterprise version. I have gone through the VS enterprise doc, 3.1 SDK supports VS 2019 16.4 and above versions. Any chance I can get it run :|.

**Comment by drewnoakes** [comment]
@NiteshKoushik can you share the contents of the project file that's failing to load?

**Comment by siroz1907** [comment]
There is no "global.json" file in my project folder.

I have a visual studio 2019 professional license. I was working on windows 10 pro operating system. Today windows operating system received updates KB5021233, KB5021087, KB5021954 and KB5021953.

In the project running before the update, "Target Framework" seems to be turned off as in this topic. Visual studio is not compiling. MSB4044 "ProcessFrameworkReferences" throws "RuntimeGraphPath" error.

I reinstalled visual studio, but the problem did not go away.

The project is opened in visual studio 2022 and the target framework option is active. But the problem is that my license is for visual studio 2019.

**Comment by drewnoakes** [comment]
@siroz1907 can you include a screenshot please? It would be helpful if you opened a new issue, as it sounds like you are having a different issue. If you could include the contents of your csproj file it would help.
