### ISSUE TITLE
Opt-in flag for VS Codespaces for c#

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/project-system#6217]
**Visual Studio Version**:

**Summary**:
Potentially 3rd party project systems will get installed on the server in the future. This work is  to require all project systems to opt-in to VS Codespaces. This is an opt-in model for the .NET Core project systems that we know support VS Codespaces. 

**Steps to Reproduce**:

Not applicable

**Expected Behavior**:

**Actual Behavior**:

**User Impact**:

**Comment by arkalyanms** [comment]
I have a commit for this that consumes the CPS packaging changes. Can I get permissions to the repo to create a PR?

**Comment by drewnoakes** [comment]
@arkalyanms you don't need permission to create a PR.

**Comment by arkalyanms** [comment]
remote: Permission to dotnet/project-system.git denied to arkalyanms.
fatal: unable to access 'https://github.com/dotnet/project-system.git/': The requested URL returned error: 403

**Comment by drewnoakes** [comment]
Yes, the workflow is different here. You have to:

- fork this repo
- push to your fork
- create a pull request from your fork to this repo

https://github.com/dotnet/project-system/blob/master/docs/repo/getting-started.md
