### ISSUE TITLE
Can not remove Analyzers from depencencies

### ISSUE THREAD

**Issue by natilivni** [dotnet/project-system#6222]
**Visual Studio Version**:
Microsoft Visual Studio Professional 2019
Version 16.6.0

**Summary**:

Can not remove unwanted analyzers from dependencies

**Steps to Reproduce**:

1. Install Microsoft.CodeAnalysis.FxCopAnalyzers 3.0.0 using nuget.
2. revert project files so that package is removed (but not through nuget)

**Expected Behavior**:

Analyzers should be removed from the dependencies

**Actual Behavior**:

Analyzers are still in dependencies and can not be removed.

**User Impact**:

Can not manage the analyzers properly and choose which ones I want to keep.

**Comment by drewnoakes** [comment]
I cannot repro this. Can you provide more details on the steps you're taking, ideally from a brand new project? What kind of project are you starting with, for example?

**Comment by natilivni** [comment]
I can not get back to my initial state to try and reproduce.  Any project I start has the extra analyzers as dependencies and they can not be removed.  How do I manually remove them?

**Comment by drewnoakes** [comment]
What project template are you instantiating that has analyzers included?

**Comment by davidwengier** [comment]
Do you have the analyzers installed as a Visual Studio extension? Do you have a `Directory.Build.props` or `Directory.Build.targets` file anywhere in any of the parent directories of where you are creating your projects?

**Comment by natilivni** [comment]
I ended up going to my last restore point and re-installing the analyzers using nuget.  can not reproduce now.
