### ISSUE TITLE
[System.Configuration.ConfigurationManager] designer cannot edit *.settings file

### ISSUE THREAD

**Issue by iulian0512** [dotnet/project-system#6249]
> An error occurred while saving values to the app.config file. The file might be corrupted or contain invalid XML.

Steps to reproduce:
1. create console .net core 3.1 app
2. add nuget `System.Configuration.ConfigurationManager` version 4.7.0
3. add a settings file
4. add an empty file named `app.config` to the project
3. add a string property in the settings file scoped to application give it an arbitrary value then save
4. close the settings editor 
5. open the settings editor -> you get the error and any changes do not propagate to `app.config` file

**Comment by davkean** [comment]
tag @davidwengier @JeremyKuhne

**Comment by JeremyKuhne** [comment]
FWIW I don't recall ever seeing this error when I was playing around with this a few months ago.

**Comment by iulian0512** [comment]
should i provide a sample zipped project demonstrating the issue ?

**Comment by davkean** [comment]
@iulian0512 Please do.
