### ISSUE TITLE
VS 2019 16.5.0 hangs when opening a project where a compatible .NET Core SDK is not available (with repro)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6256]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/954681/vs-2019-1650-hangs-when-opening-a-project-where-a-1.html). Please vote and comment there to make sure your voice is heard._

---
[regression] [worked-in:16.4.6]
I have a project that has a `global.json` file in the root indicating that version `3.1.100` of the .NET Core SDK should be used. A compatible version of that SDK comes with VS 16.4.0. After upgrading VS to 16.5.0 and attempting to open my project, the IDE hangs indefinately. After some trial and error, `dotnet --list-sdks` revealed that no compatible .NET Core SDK was installed for 3.1.1xx. After installing .NET Core SDK 3.1.101, VS 16.5.0 opened the project successfully. This is likely because my machine was using the VS specific version of that SDK and it got upgraded, which I understand.

The issue is that the IDE hangs when opening the project. It would be great if an error indicating the issue could be displayed. A bonus would be to pop the installer to install the missing SDK.

---
#### Roi Chen [MSFT] on 3/18/2020, 10:21 PM: 

<p>Thank you for taking the time to log this issue!<br>
I’ve tried to reproduce and investigate using the description, and attachments already provided. Unfortunately those aren’t enough and more information is needed in order to investigate it further.<br>
The easiest way to provide all the information is to use the Visual Studio Feedback Tool. This will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace).<br>
Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool:<br>
•	Open Visual Studio Feedback tool.<br>
•	Click the banner letting you know that you have problems requesting your attention.<br>
•	Click this problem from the list<br>
•	Click “View their request and respond” from the problem details banner<br>
•	Add a comment, in the Attachments/Record: click Start Recording<br>
•	When the Steps Recorder tool appears, perform the steps that reproduce the problem.<br>
•	When you’re done, choose the Stop Record button.<br>
•	Wait a few minutes for Visual Studio to collect and package the information that you recorded.<br>
•	Submit. You will be able to see the comment on Developer Community. For security reasons, your files come directly to us and don’t appear on Developer Community.<br>
For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a> . For information about what data is collected, see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect">https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect</a><br>
Get performance issues fixed quicker, please see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019</a>.<br>
We look forward to hearing from you!</p>

#### Craig Treasure (ANALOG) [MSFT] on 4/6/2020, 09:17 AM: 

Adding repro recording.
#### Visual Studio Feedback System on 3/31/2020, 06:28 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Visual Studio Feedback System on 4/9/2020, 02:54 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Yuanyuan Dong [MSFT] on 4/9/2020, 03:50 AM: 

<p>Dear Craig,<br>
Thank you for your information! For us to investigate this further, could you please provide a dump file?<br>
You are able to get the dump file with the following steps:<br>
1.Start the 32-bit task manager (C:\Windows\SysWOW64\Taskmgr.exe).<br>
2. Repro the issue, and wait about 10 seconds<br>
3. Right click on devenv.exe, and press “Create dump file”. Then please attach this file.<br>
We look forward to hearing from you!</p>

#### Craig Treasure (ANALOG) [MSFT] on 4/9/2020, 09:57 AM: 

I&#39;ve attached the requested dump file.
#### Visual Studio Feedback System on 4/10/2020, 04:23 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Lifeng Lu [MSFT] on 4/10/2020, 05:17 PM: 

<p>Hey, Craig, </p><p>Thanks a lot to report the issue. Because our team didn't reproduce this issue directly, it would be critical to use the dump file to find out the what happened. Unfortunately, the earlier dump file was a 64bit process dump, which doesn't work with WinDBG SOS commands.  I reviewed the instruction from Yuanyuan earlier, which is mostly correct. However, one key thing missing is that if you have task manager opened, executing the WOW version of the taskmgr will reuse the window, and still left you to use 64bit task manager. The instruction works with people don't use task manager much, but I believe it hits the problem on you.  The better way is to run WOW taskmgr once, and close the window, and rerun it to ensure you get the 32bit one.  After that, you can create dump file with the task manager. </p><p>If you can help to capture a new dump, it will be very helpful for us to find out what happened. Sorry for the gap in the original instruction.</p><p>Thanks</p>

#### Craig Treasure (ANALOG) [MSFT] on 4/28/2020, 08:42 AM: 

<p>Sure. Can we get the item back in a state where I can submit diagnostics again?</p>

#### Craig Treasure (ANALOG) [MSFT] on 5/11/2020, 09:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jjmew** [comment]
could be related to #6069

**Comment by swesonga** [comment]
This was fixed in https://github.com/dotnet/sdk/pull/12633.
