### ISSUE TITLE
[Regression] Public Assembly not found when adding a reference to project targeting .NET 3.5

### ISSUE THREAD

**Issue by vritant24** [dotnet/project-system#6263]
**Visual Studio Version**:
16.6 GA
**Summary**:

In Fakes, we add a reference to the Fakes Framework assemby (targets v3.5) that exists in the Common7\IDE\PublicAssemblies using  VSProject.References.Add("Microsoft.QualityTools.Testing.Fakes") 
This is only being used in old-style projects and used to work from .NET 3.5 -> 4.8. 
But in the latest master, adding the reference in a project targeting .NET 3.5 fails, the rest work.

**Steps to Reproduce**:

1. Create an old style project that targets .NET 3.5
2. right click on an assembly reference (eg: system.dll) and click "add Fakes Assembly"

**Expected Behavior**:
A reference to Microsoft.QualityTools.Testing.Fakes should be added, which exists in the public assemblies directory.

**Actual Behavior**:
Adding the reference fails. 
It succeeds for all framework versions > .NET 3.5

**User Impact**:
Users will not be able to generate Fakes Assemblies in projects targeting .NET 3.5

**Comment by jjmew** [comment]
This needs to be moved to AzDo

**Comment by tmeschter** [comment]
I'll move it over to AzDO.

**Comment by vritant24** [comment]
Quick update, on talking with abhitej I've learnt that to support public assemblies in .NET 3.5 projects, the assembly needs to exist in the `Common7\IDE\ReferenceAssemblies\v2.0` folder. This is something we missed and so this is a regression on our part

**Comment by drewnoakes** [comment]
@vritant24 to be clear: does that mean we can close this issue?

**Comment by vritant24** [comment]
Yes that's correct
