### ISSUE TITLE
Project Reference node doesn't reflect the name of the project in VS

### ISSUE THREAD

**Issue by vritant24** [dotnet/project-system#6266]
**Visual Studio Version**:
Int Preview 16.7.0 Preview 3.0 [30201.181.master]

**Summary**:
On renaming a project in VS, the csproj name is changed, but the Assembly name is not changed.
This is visually reflected when the project is being referenced by another project, and the assembly name is shown instead of the project name in the list of project references

In the image below, There's two projects to look at.
1. `Net472OldStyleLibrary` which is a net472 old-style project. This was renamed from `Net472OldStyle` to `Net472OldStyleLibrary`
2. `Net472SDKStyleProject` which is a net472 test project that references `Net472OldStyleLibrary`
In the list of references, the name seen is visually different.
![image](https://user-images.githubusercontent.com/13074644/83939616-38036880-a793-11ea-881a-55aa5c610aa1.png)

When retrieving the list of references from `VSProject.References`, the value of `Reference.name` is the project name `Net472OldStyleLibrary`. (which currently breaks Fakes)

Is this by design? I'm not sure how long this has existed, but I just encountered it. I find it unintuitive to see the assembly name under a "Project Reference" node

**Comment by jjmew** [comment]
We believe that showing the assembly name is reasonable.
