### ISSUE TITLE
Directly opening a solution with an open .csproj file shows error

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#6272]
**Visual Studio Version**: 16.7.0 Preview 3.0 [30209.108.master]
Also repros in VS2019 16.6.2 but not in VS 2017 15.9.24

**Summary**:
Opening a solution with a csproj file yields the following error message:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/3288375/84211877-468ea000-aa71-11ea-97be-9a1933c52c72.png)

The .csproj file was open before I closed the solution. If I try to close and reopen the file or any other csproj file afterwards it works correctly.

**Steps to Reproduce**:

1. Clone https://github.com/dotnet/NuGet.BuildTasks

2. Open Microsoft.NuGet.Build.Tasks.csproj

3. Close VS

4. Open VS again and load the solution

**Expected Behavior**:
Microsoft.NuGet.Build.Tasks.csproj opens correctly

**Actual Behavior**:
The error message appears

**FYI**:
I wasn't able to repro this using the project-system solution but it consistently happens with NuGet.BuildTasks

**Comment by MiYanni** [comment]
@dmonroym I wasn't able to repro with 16.9.0 Preview 3.0 [30802.48.main]. Could this have been fixed since 16.7?

**Comment by dmonroym** [comment]
It no longer repros for me either. Closing
