### ISSUE TITLE
Project file colourization not working in cloud environment

### ISSUE THREAD

**Issue by davidwengier** [dotnet/project-system#6273]
**Visual Studio Version**: master

**Summary**: Opening a project file in a cloud environment does not have any colourization of XML. I wonder if these registry keys aren't present, or if this DLL isn't being loaded or something: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeRegistration.cs#L53

**Steps to Reproduce**:

1. Connect to a codespace with a .NET Core project
2. Right click, Edit Project File

**Expected Behavior**:
XML should be coloured correctly

**Actual Behavior**:
XML is black and white.

**User Impact**:
Sadness and misery

**Comment by davidwengier** [comment]
I checked our ProjectSystem.vsix and the `Microsoft.VisualStudio.ProjectSystem.Managed.VS.pkgdef` file looks like it has the right registry keys, and the `ProjectSystem.clientenabledpkg` file looks like it references the pkgdef file as expected.

@melytc any idea what else we should look at here?

**Comment by davidwengier** [comment]
The XML editor isn't marked client compliant. Internal bug opened here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1141378

**Comment by jjmew** [comment]
This is fixed
