### ISSUE TITLE
NuGet diagnostics do not add icons to top-level dependencies

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6275]
**Visual Studio Version**: master (16.7)

**Summary**:

NuGet warning/error diagnostics are not visible on top-level dependency items in the tree.

**Steps to Reproduce**:

1. New .NET Core Console Application
2. Add:

   ```xml
   <ItemGroup>
     <PackageReference Include="NuGet.Commands" Version="4.0.0" />
     <PackageReference Include="NuGet.Packaging" Version="3.5.0" />
   </ItemGroup>
   ```
3. Show packages in tree

![image](https://user-images.githubusercontent.com/350947/84224436-e145b800-ab1f-11ea-99d3-a82cb70efb53.png)

**Expected Behavior**:

Warning or error icons should be visible on these top-level tree items.

**Actual Behavior**:

The icons do not show such icons. You can see these warnings in the error list and on expanding those nodes however.

**Comment by drewnoakes** [comment]
`ResolvedPackageReference` and `ResolvedProjectReference` items do not indicate NuGet error/warning status in their metadata. Currently this error state is loaded lazily, when the assets file is parsed.

The fix here will be to update the SDK targets to identify these diagnostics for projects/packages and set appropriate metadata on the returned resolved items, then use that in VS.

**Comment by vdanche** [comment]
@drewnoakes 
The issue still repro on current environment- Version 16.7.0 Preview 4.0 [30229.179.master]
![image](https://user-images.githubusercontent.com/65637796/86104658-eaa7bc00-baf0-11ea-8ba5-5226668ff047.png)
Can you check it again?Thanks!

**Comment by drewnoakes** [comment]
Will investigate.

**Comment by drewnoakes** [comment]
@vdanche the fix for this is in VS but we won't see the new behaviour until a new enough SDK is available. Specifically, we need `DiagnosticLevel` metadata to `ResolvedPackageReference` items. 

The fix has been merged to both 3.1.4xx and 5.0.1xx branches of the SDK, so both should see the correct behaviour soon.

3.1.400-preview-015178 does not have this metadata.

5.0.100-preview.6.20318.15 is even further behind in terms of the data produced for this feature.

Did you test with 5.0.100-preview.7? I do not have that installed and am not sure where to source an installer.

**Comment by vdanche** [comment]
@drewnoakes 
Yes, with SDK .net5.0.100-preview.7.20351 installed, there are still no warning icon on some nodes.
![image](https://user-images.githubusercontent.com/65637796/86436231-74939700-bd34-11ea-82b0-65e7cd0399a1.png)


Note,
You can get the .net5 preview7 from below path.
\\vsufile\patches\sign\NET\CORE_BUILDS\5.0.X\5.0.0\5.0.100-preview.7.20351.2

**Comment by drewnoakes** [comment]
@vdanche how do you install the SDK from that link? I am able to see the files under that share, but I'm not sure what to do with them.

**Comment by drewnoakes** [comment]
@vdanche we can break your screenshot into two parts:

1. The "Dependencies" and "Packages" nodes should show yellow triangles.
2. "NuGet.Commands" does not have a direct diagnostic, however one of its transitive dependencies does. Should that be surfaced all the way to the top-level dependency?

The first point is a bug (fixed in #6330).

The second point feels like a feature request. Historically we didn't show diagnostics for transitive dependencies at all. If there is interest in such a feature, it should be tracked separately. I'm not convinced it helps the user. It may be misleading. In the example you show, it's clearer to the user that the problem is with their direct reference to "NuGet.Packaging", and it's fewer clicks to get there. If we add this feature, both top-level packages will appear with warning icons.

**Comment by drewnoakes** [comment]
This has been fixed in 16.8 and we are putting the fix to the QB for 16.7.

**Comment by vdanche** [comment]
@drewnoakes This issue repro on 16.8 preview1 (Version 16.8.0 Preview 1.0 [30320.53.master] ), can you help to check it again? Thanks!

**Comment by vdanche** [comment]
Repro on below environment again
1. on Version 16.8.0 Preview 2.0 [30404.144.master] with inserted .Net5 preview7 SDK(5.0.100-preview.7.20366.6), No warning icon as below:
![image](https://user-images.githubusercontent.com/65637796/89395535-0af61680-d740-11ea-9fd6-647f828e10d7.png)
2. Version 16.8.0 Preview 2.0 [30404.144.master] + .Net5 preview8 SDK(5.0.100-preview.8.20403.18), the icon display incorrectly.
![image](https://user-images.githubusercontent.com/65637796/89395770-53adcf80-d740-11ea-8dc0-74ae973bd628.png)

Note:
the warning icon displays well with .net core 3.1 sdk
![image](https://user-images.githubusercontent.com/65637796/89395900-7f30ba00-d740-11ea-9c21-06e0491f03a5.png)

**Comment by drewnoakes** [comment]
@vdanche this didn't make preview 7. It might not make preview 8 either, as I understand it.

**Comment by frosadev** [comment]
This is happening after the update of VS.
Targeting the project to net5.0 with the preview 8 sdk.

With all dependencies, any package.

![image](https://user-images.githubusercontent.com/26621392/91309442-7fa0fb80-e7a8-11ea-96bc-4e20c8499316.png)

steps to reproduce:

1. create a new web api project targeting net5.0;
2. add any package to the project.

**Comment by vdanche** [comment]
> Repro on below environment again
> 
> 1. on Version 16.8.0 Preview 2.0 [30404.144.master] with inserted .Net5 preview7 SDK(5.0.100-preview.7.20366.6), No warning icon as below:
>    ![image](https://user-images.githubusercontent.com/65637796/89395535-0af61680-d740-11ea-9fd6-647f828e10d7.png)
> 2. Version 16.8.0 Preview 2.0 [30404.144.master] + .Net5 preview8 SDK(5.0.100-preview.8.20403.18), the icon display incorrectly.
>    ![image](https://user-images.githubusercontent.com/65637796/89395770-53adcf80-d740-11ea-8dc0-74ae973bd628.png)
> 
> Note:
> the warning icon displays well with .net core 3.1 sdk
> ![image](https://user-images.githubusercontent.com/65637796/89395900-7f30ba00-d740-11ea-9c21-06e0491f03a5.png)

@drewnoakes **Still repro on RC1: Version 16.8.0 Preview 3.0 [30426.235.main] + RC1 SDK(https://github.com/dotnet/installer)**

**Comment by drewnoakes** [comment]
@frosadev @vdanche there's an SDK PR in flight with the fix for this: https://github.com/dotnet/sdk/pull/13093

**Comment by vdanche** [comment]
Still repro on NET 5 RC1 VAL build[Version 16.8.0 Preview 3.0 [30502.218.main]]
![image](https://user-images.githubusercontent.com/65637796/92085385-5234fd00-edfb-11ea-8596-fd4113bafcc6.png)

**Comment by drewnoakes** [comment]
@vdanche I see a yellow triangle on the `NuGet.Packaging` and `Dependencies` nodes as expected using:

- .NET SDK 5.0.100-rc.1.20452.10
- Microsoft.NETCore.App 5.0.0-rc.1.20451.14
- VS 16.8.0 Preview 4.0 [30510.110.main]

Let me know if you still see a problem when testing with newer preview bits. Thanks.

**Comment by drewnoakes** [comment]
@vdanche this is a bug in the SDK. I have filed https://github.com/dotnet/sdk/issues/13518 to track it.

**Comment by vdanche** [comment]
@drewnoakes Thanks Drew, we will track [dotnet/sdk#13518](https://github.com/dotnet/sdk/issues/13518)
