### ISSUE TITLE
Condition on ProjectReference Is Not Respected in Visual Studio

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/project-system#6277]
---
**Issue moved from microsoft/msbuild#5410**
- Please respond to @aolszowka.

---

_From @aolszowka on Friday, June 5, 2020 6:51:14 PM_

### Steps to reproduce
Here is a repository that reproduces the issue: https://github.com/aolszowka/ProjectReferenceConditionalTest

The jist of it is this project will still show up and build within Visual Studio even when a condition is used in this manner:

 ```xml
<ProjectReference Include="..\A\A.csproj" Condition="'1'=='2'">
    <Project>{679190e5-cd34-4391-85de-9031f04f50a5}</Project>
    <Name>A</Name>
</ProjectReference>
```

Calling Pure MSBuild works as expected, should this be a Developer Community Bug?

### Expected behavior

Visual Studio and MSBuild should behave identically.

### Actual behavior

Visual Studio will attempt to build/reference the project, whereas MSBuild will not.

### Environment data
`msbuild /version` output:
```
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.6.0.22303
```
OS info:
Windows 10 Enterprise 1909

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Visual Studio 2019 Enterprise 16.6.1

**Comment by davkean** [comment]
This is a limitation of the legacy project system (.NET Framework), it grabs all project references and file items ignoring any conditions. We have no plans on changing this behavior in the legacy proejct system.

This limitation has been removed in the new project system (.NET Core projects) and .NET Framework projects will benefit when we move those projects to open with it in a future Visual Studio version.

**Comment by aolszowka** [comment]
FWIW just to make it clear to anyone else who stumbles across this; this hack works:

```xml
  <Choose>
    <When Condition="'1' == '2'">
      <ItemGroup>
        <ProjectReference Include="..\D\D.csproj">
          <Project>{639424b0-0982-424b-8fdf-0ed91e9e6753}</Project>
          <Name>D</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
  </Choose>
```

Not super idea; but at least it moves people forward if they're stuck.

**Comment by davkean** [comment]
Thanks! A condition on an import of a targets file that contains the references will also be respected.

**Comment by shuffle2** [comment]
I've also hit this on a C++ project (https://github.com/dolphin-emu/dolphin/blob/55c931d6248c6dda5a8a9cbd332131255d62bc3f/Source/Core/DolphinQt/DolphinQt.vcxproj#L524) curious how this:

> This limitation has been removed in the new project system (.NET Core projects) and .NET Framework projects will benefit when we move those projects to open with it in a future Visual Studio version.

applies to C++ projects.

**Comment by zuckerthoben** [comment]
> I have a similar issue, but its the inverse situtation: ProjectReference Condition is supported in Visual Studio but not in commandline `dotnet build`:
> 
> Here is a commit that works it around: [openmod/openmod@df876c8](https://github.com/openmod/openmod/commit/df876c8bc7ad714bb6a98eafcb336deed68a315c)
> 
> In short, I had to move the ProjectReferences to their own ItemGroup and apply the condition to the ItemGroups instead.
> 
> Visual Studio Version: 16.3.1 dotnet --version: 3.1.100

I have the same problem, but moving the conditions to an ItemGroup is not helping. I can build my solution locally in VS, but not with the DotNetCoreCLI or the MSBuild task in Azure DevOps. 

Also the project is already using the current project system and if I understand correctly it should not be a problem there?
