### ISSUE TITLE
Solution Items appears twice

### ISSUE THREAD

**Issue by philippemp31** [dotnet/project-system#6284]
**Visual Studio Version**: 2019 16.6.2

**Summary**:
Solution Items folder appears twice (more ?)

**Steps to Reproduce**: 

1. Just open a solution with Solution Items folder I guess

2. 

3. 

**Expected Behavior**:

**Actual Behavior**:

**User Impact**:
![image](https://user-images.githubusercontent.com/66834013/84510555-92d21e00-acc5-11ea-82f7-03e72c583ce0.png)

**Comment by drewnoakes** [comment]
Duplicate of #6283.
