### ISSUE TITLE
AvailableItemName not working on Sql Server Database projects

### ISSUE THREAD

**Issue by Mostafa-Armandi** [dotnet/project-system#6298]
VS 2019

I didn't manage to get  AvailableItemName working on SSDT projects

Created a separated .target file and  .xml file to specify a desired Item Type. Although, it works as expected on ordinary .csproj projects, I failed to make it work on Sql Server Database projects.

[MyTarget.zip](https://github.com/dotnet/project-system/files/4808932/MyTarget.zip)

**Comment by davkean** [comment]
@Mostafa-Armandi Please open a bug via Help -> Send Feedback -> Report a Problem, so that it can be routed to the correct team. This repository does not provide support for SQL Server Database projects.
