### ISSUE TITLE
Treat warnings as errors (Displaying wrong)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6307]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1057439/treat-warnings-as-errors-displaying-wrong.html). Please vote and comment there to make sure your voice is heard._

---
[regression] [worked-in:Version 16.7.0 Preview 1.0]
I have projects that are set to "Treat warnings as errors - All".  Edit project and set right but UI displays wrong.

---
#### Visual Studio Feedback System on 5/31/2020, 11:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sara Liu [MSFT] on 6/1/2020, 11:06 PM: 

<p>Thank you for your feedback and taking the time to reach out to us.<br>
I can reproduced this issue through your shared steps with the .net core project type and this issue has been escalated for further investigation, if there is any process, I will inform you immediately.</p>

#### Andrew Stanton on 6/23/2020, 06:31 AM: 

This is a frustrating and alarming problem. I can choose &quot;All configurations&quot; and set &quot;Treat warnings as errors&quot; to &quot;All&quot;, save the page, close it, and reopen it, and it does not retain that setting. <br><br>Its not just a UI problem, it does not set the appropriate project level property

---
### Original Solutions
(no solutions)

**Comment by jjmew** [comment]
It looks like this got regressed by https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/215694?path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.Implementation%2FProperties%2FProjectContextBasedReaderWriter.cs&_a=files 

The problem seems too be that we are not zeroing out WarningsAsErrors when we set TreatWarningsAsErrors.

**Comment by StingyJack** [comment]
Just as an FYI, this also affects Errors and Warnings and sometimes the "Advanced" button 

https://user-images.githubusercontent.com/15381181/107891942-bbaf5080-6eef-11eb-992d-927649e02557.mp4

**Comment by ContentsMayVary** [comment]
This is still broken in 16/9

**Comment by jjmew** [comment]
We have fix this in Dev 17 Preview 1. The fix is only for SDK Style projects. At this point we have decided not to fix it for legacy.

**Comment by StingyJack** [comment]
@jjmew any advice or tips regarding how to convince a business that each regression does not have to be fixed?

(Asking for a friend.)
