### ISSUE TITLE
Winforms SDK Project fails to compile when two resx file exists with the same name in different namespaces

### ISSUE THREAD

**Issue by elachlan** [dotnet/project-system#6312]
### Steps to reproduce
Have a winforms project using SDK project type. The project should include two forms with the same name in separate namespaces. Each form should have its icon set, so that it creates a resource file.

**See Attached zip:**
[TestApp2.zip](https://github.com/dotnet/project-system/files/4843972/TestApp2.zip)

**Error:**
 `Two output file names resolved to the same output path: "obj\Debug\net472\TestApp2.Edit.resources"`

**Comment by jjmew** [comment]
This is already being tracked in the MSBuild Repo

**Comment by elachlan** [comment]
@jjmew so its an msbuild issue? I raised the issue in msbuild first because I wasn't sure where to create the issue.

**Comment by davkean** [comment]
MSBuild controls the output of these during build, so MSBuild is the correct repository.

**Comment by elachlan** [comment]
@davkean Thank you so much for the response. I'll try and make the issue there as verbose as possible.
