### ISSUE TITLE
Copying files to a .Net Core App via the file explorer causes the "View Designer" context menu to disappear.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6313]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1077307/copying-files-to-a-net-core-app-via-the-file-explo.html). Please vote and comment there to make sure your voice is heard._

---
The View Designer context menu disappears from the code window on a cs code behind file of an xaml file in a .Net Core project if it has been copied in the file explorer (for example from another project). 

Steps to reproduce:
1. Create a .Net Core c# WPF app.
2. Create a new folder in the project.
3. Open file explorer, and copy the MainWindow.xaml and MainWindow.xaml.cs files the the new folder.
4. Return to visual studio, open the MainWindow.xaml.cs code window and right click. The View Designer menu has disappeared.

A workaround fix is to exclude the copied files from the project, then include again. Now the View Designer menu is visible.

---
#### Visual Studio Feedback System on 6/15/2020, 00:33 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Yuanyuan Dong [MSFT] on 6/16/2020, 11:57 PM: 

<p>Dear customer,<br>
Thanks for your feedback. Unfortunately I didn’t reproduce your issue in my machine. To investigate this problem further, could you please repair your VS and try again? If this issue still repro, could you please provide following information to us:<br>
1. Does this happen on all type projects or specific one?<br>
2. Provide a sample solution which can exhibit this behavior<br>
3. Can you attach a video of the issue you describe using [ScreenToGif] (<a target='_blank' href="https://www.screentogif.com/">https://www.screentogif.com/</a>) or a similar tool?<br>
We are looking forward to your reply.</p>

#### koger9 on 6/17/2020, 01:03 AM: 

<p>I repaired VS, disabled all extensions, and reset the settings. Same behavior. 
Updated instructions: </p><p>Create a .Net Core c# WPF app.
Create a new folder in the project.
Open file explorer, and copy the MainWindow.xaml and MainWindow.xaml.cs files to the new folder.
Return to visual studio, open the recently copied MainWindow.xaml.cs files and right click in the code window. The View Designer menu has disappeared.</p><p>

A workaround fix is to exclude the copied files from the project, then include again. Now the View Designer menu is visible. </p><p>This happens on a .Net core project, and a .Net Framework project, however on a .Net Framework project, the copied files are automatically excluded from the project. </p><p>I've given you everything you need to reproduce the issue. </p>

#### Yuanyuan Dong [MSFT] on 6/17/2020, 01:46 AM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/264810/cdf87233-a309-63c9-8dbe-e91dbc9c57e4.html" nodeid="264810">@koger9</a> thanks for your reply, i can reproduce your issue now. </p>

#### Visual Studio Feedback System on 6/17/2020, 01:52 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Note: for WPF roslyn should not be involved.   Internal email discussion between @davkean @jasonmalinowski and @marcoGoertz on this.

**Comment by jjmew** [comment]
This is CPS and it will be tracked internally
