### ISSUE TITLE
Use friendly display name for target nodes in dependencies tree

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6319]
For multi-targeting projects, we group dependencies by target in the Dependencies tree.

#6315 moved from showing framework "identifier + version" to "short name". For example, instead of ".NETCoreApp5.0" we show "net5.0". The original motivation for this change was to avoid showing ".NETCoreApp" in .NET 5.

@tmeschter added a [comment on that PR](https://github.com/dotnet/project-system/pull/6315#issuecomment-651417540) pointing out that friendly strings for these names are [provided by the SDK](https://github.com/dotnet/sdk/blob/e2faebad758a7d38b5965cda755a17e9e9881599/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props).

@davkean pointed out that evaluation produces `TargetFrameworkMonikerDisplayName` which contains this string when available.

Considerations:
- [ ] @dsplaisted pointed out that "Eventually we would like to be able to have arbitrary user-defined names in TargetFrameworks for arbitrary multi-targeting": https://github.com/NuGet/Home/issues/5154
- [ ] @davkean pointed out that we may need to disambiguate with the TargetFramework property if the resulting configurations have the same name.

**Comment by dsplaisted** [comment]
Per the [spec](https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#tfms-in-the-ui), I think we're supposed to use the raw value from the `TargetFramework` or `TargetFrameworks` properties in all of the UI except for the project properties Target Framework dropdown.  That's the only place I think we'd use the "friendly" name.

To support arbitrary names, ideally the project system wouldn't be specifically using the "short" name from the TargetFramework, rather it should use the value from the project file.  So today, if I have a TargetFramework of `net5` or `net5.0.0`, that's what should be displayed.

**Comment by drewnoakes** [comment]
@dsplaisted thanks for the spec. The tree shows whatever value is in the project file (since #6315), so I'll close this.

BTW if the value in TargetFramework is not the "short" name, what is?

**Comment by davkean** [comment]
Help me understand why would only friendly name would only be used project properties? What logic is that based on?

**Comment by drewnoakes** [comment]
Sounds like a question for @terrajobst.
