### ISSUE TITLE
PackageReference in csproj should identify preferred source feed

### ISSUE THREAD

**Issue by MV10** [dotnet/project-system#6320]
I am proposing that the NuGet `<PackageReference>` tags in csproj should identify the preferred package source. 

Where I work (very large enterprise) we have a large number of internal package sources dedicated to copies of public feeds, various in-house dev, testing, and release feeds, and so on. We also have _thousands_ of project-specific feeds. On occasion, some of us even activate truly-public feeds. It is not unusual to have duplicate packages in multiple feeds (or worse, someone has published a package for their own project that "hides" an official package by the same name).

The restore behavior today is essentially random unless you carefully control which feeds are active and which are inactive on a project-by-project basis. Worse, without carefully reviewing logs, you can't even tell where a package came from after the fact.

It's enough of a hassle that I tend to just pull packages down by hand and reference a local-path feed, apart from extremely well-known dependencies like `Microsoft.*` packages.

It's unclear to me if this is actually a NuGet request, but I think either way this would require project-system support.

**Comment by MV10** [comment]
This same scenario (large numbers of sources) was also the driver for something I requested many years ago -- the ability to control the search order of package sources. A fundamentally different request of course, but still badly needed. Figured it can't hurt to mention it again.

**Comment by jjmew** [comment]
This is a NuGet feature request. Please file an issue in https://github.com/NuGet/Home
