### ISSUE TITLE
Delay initializing BuildUpToDateCheck and PackageRestoreProgressTracker for inactive project configurations

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#6327]
Current, inactive project configurations can be loaded in various conditions, either because the mismatching solution configurations, or when an extension or the developer access configured level properties (like appDesigner). AutoLoadComponents, especially dynamic loaded components are triggered in those configurations, which initializes dataflows, especially DT build dataflow, which is not essential until the configuration is activated. If we can delay initialize some of the auto load components until the configuration is activated/implicitly activated, it will reduce some of those initialization/overhead.  BuildUpToDateCheck and PackageRestoreProgressTracker are two of those components inside ML project system, which can be delayed to establish dataflow subscription, until the configuration is activated.

**Comment by drewnoakes** [comment]
#6329 addresses the `BuildUpToDateCheck` half of this.

**Comment by drewnoakes** [comment]
Chatted with @davkean. Discussed that `IConfiguredProjectActivationTracking` may be a better hook for this, as it'll prevent potential DTBs right before the first project build. Also seems that `BuildUpToDateCheck` need not be an `IProjectDynamicLoadComponent` as its capabilities are fixed.

**Comment by drewnoakes** [comment]
#6334 offers a simpler alternative to #6329.

**Comment by davkean** [comment]
Restore tracker was fixed here: https://github.com/dotnet/project-system/pull/6339.
