### ISSUE TITLE
React to HelpLink API for warnings/errors

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#6335]
See: https://github.com/microsoft/msbuild/pull/5488.

We need to wait for these APIs to appear in an MSBuild package that we can consume.

**Comment by jmezach** [comment]
@davkean The MSBuild PR got merged now. Looking forward to these links showing up in Visual Studio :).

**Comment by davkean** [comment]
Microsofties PR here: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/264132.

**Comment by davkean** [comment]
This works now for SDK-based projects:

![image](https://user-images.githubusercontent.com/1103906/89139813-40093a00-d583-11ea-8f2e-4bed0e98e821.png)

**Comment by davkean** [comment]
This has been merged in, and will be available for 16.8 Preview 2.
