### ISSUE TITLE
XML Documentatition file name option does not honor macros or intermediate folder setting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6342]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/949322/xml-documentatition-file-name-option-does-not-hono.html). Please vote and comment there to make sure your voice is heard._

---
We have C# projects that we are trying to generate XML documeation for. To do this, we set the XML Documentation field of the project settings to the name we desire.  However, the process by which the xml documeation generates appears to be the following:

- The xml file gets generated intermediately to the same folder as our project folder.
- Then an extra copy steps deploys the final xml to the project output folder.

This has the undesired affect of having a file that git likes to display as "ignored" and leaves extra files in the source tree.

Shouldn't the xml documeation generation for C# projects generate the temporary xml to the intermediate folder along side other objects from the build rather than pollute the source tree??

---
#### Andrew Bushnell on 3/15/2020, 06:10 AM: 

<p>I found I could define the XML name as a fully qualified path name but that gets ugly as the field does not honor any macros etc.. </p><p>FYI, C++/CLI project do NOT have this issue, those project types just have a check box to generate xml and they auto-name it and place it and this problem does not exist..</p>

#### Visual Studio Feedback System on 3/15/2020, 08:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Saint Wesonga [MSFT] on 3/17/2020, 04:34 PM: 

<p>Could you please generate a binary log by passing /bl to MSBuild as described in the instructions at <a target='_blank' href="https://github.com/microsoft/msbuild/blob/master/documentation/wiki/Binary-Log.md">https://github.com/microsoft/msbuild/blob/master/documentation/wiki/Binary-Log.md</a></p>
<p>Please upload the .binlog file to aid our investigation of this issue.<br>
Thank you.</p>

#### Andrew Bushnell on 3/20/2020, 06:49 AM: 

Attached find the requested log.<br><br>Also, I noticed that the default for a C# project when turning on the documentation is to prepend the xml name with the output folder.. and that avoids the extra cruft.. The issue with that, so maybe an alternative fix, is that the field in question does not honor macros, making it hard to put the setting in a common target file or set all configs to the same value (i.e. something like:  $(OutputPath)$(AssemblyName).xml)
#### Visual Studio Feedback System on 5/19/2020, 09:43 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by drewnoakes** [comment]
Testing this I found a more general problem (Version 16.8.0 Preview 1.0 [30306.135.master]):

1. Create a new .NET 5 Console Application
2. Open project properties
3. Check this box:
   ![image](https://user-images.githubusercontent.com/350947/86867448-2d334f00-c116-11ea-8b0a-2ebb5f169805.png)
4. Save
5. Inspect project file

The project file contains an absolute path:

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>C:\Users\drnoakes\source\repos\ConsoleApp227\ConsoleApp227\ConsoleApp227.xml</DocumentationFile>
  </PropertyGroup>
```

I suspect this is related, however if not then we should file it separately.

**Comment by drewnoakes** [comment]
The behaviour with the full path exists in 15.9 too, so has been around for a while.

**Comment by drewnoakes** [comment]
This issue has been addressed in the new Project Properties UI and is fixed in VS2022.

![image](https://user-images.githubusercontent.com/350947/129823073-fc6955d7-5b07-4e50-8719-1e4ab3d7ef3f.png)

Checking that box produces:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
```

The path may be specified if desired, but is optional.
