### ISSUE TITLE
Visual Studio auto completion misses <Nullable> tag

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/project-system#6345]
**Version Used**: 

Visual Studio 2019 16.16.3

**Steps to Reproduce**:

1. Open a csproj file
2. Try writing <Nu...

**Expected Behavior**:

Auto completion shows Nullable

**Actual Behavior**:

Auto completion doesn't show Nullable

![image](https://user-images.githubusercontent.com/31348972/86480893-335cb080-bd4f-11ea-8fc4-552785be3ad8.png)

**Comment by rainersigwald** [comment]
Duplicate of microsoft/msbuild#4840

**Comment by rainersigwald** [comment]
This is fixed in 16.4+ by microsoft/msbuild#4840.

**Comment by Youssef1313** [comment]
@rainersigwald I'm using 16.6.3

**Comment by davkean** [comment]
This doesn't show in latest builds:

![Uploading image.png…]()

**Comment by rainersigwald** [comment]
Thanks. Closing this in favor of the MSBuild bug, for which an (internal, VS repo) PR is in flight.

**Comment by drewnoakes** [comment]
https://github.com/dotnet/msbuild/pull/5611 adds completion for the possible values (enable, disable, warnings, annotations).
