### ISSUE TITLE
after switch branch, the published file is wrong

### ISSUE THREAD

**Issue by Varorbc** [dotnet/project-system#6354]
**Visual Studio Version**:16.6.3

**Summary**:

after switch branch, the published file is wrong

[Demo](https://github.com/Varorbc/WebApplication1)

**Steps to Reproduce**:

1. publish current branch project

2. check file version after release

3. switch to branch 'test'

4. publish current branch project

5.check file version after release

**Expected Behavior**:

file version 1.0.0

**Actual Behavior**:

file version 1.0.1

**User Impact**:

**Comment by jjmew** [comment]
This is not in this Project System but in the legacy project system. The new Project System for .NET Core it is better at this. It is unlikely this would get investigated for the legacy project system. If you would like, you can open a feedback ticket https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019
