### ISSUE TITLE
FastUpToDate check fails on CopyComplete output marker, but the marker is not updated after the build

### ISSUE THREAD

**Issue by vgriph** [dotnet/project-system#6356]
**Visual Studio Version**:
16.6.2

**Summary**:
We have quite a complex solution with 134 projects, using a setup with a common output directory (`UseCommonOutputDirectory` set to `true`). We have a problem where the FastUpToDateCheck determines that it has to rebuild a large part of the solution even thou no inputs have changed. Looking at the verbose logs from the FastUpDateCheck shows that it decides that a project quite early in the dependency chain has an other CopyComplete file than its dependencies. However, building the project does not update the CopyComplete file, so it is still not up to date for the next build.

**Steps to Reproduce**:
I've tried to replicated the situation in a smaller solution, without success. I can attach a logfile from building one of our test projects when it has just been built, but have removed logs from projects that was considered uptodate, and also removed inputs that were considered up to date.

[log.txt](https://github.com/dotnet/project-system/files/4898854/log.txt)

**Expected Behavior**:
When building a project the second time it should not be built.

**Actual Behavior**:
When building the project the second time, it is rebuild along with a bunch of other projects

**User Impact**:
This severely adds to the time waiting for projects to compile.

**Comment by ocallesp** [comment]
@vgriph  if you try to build for a third time, the same projects still out of date ?

I just extracted one part of the attached log for simplification.

45>FastUpToDate: Adding input reference copy markers: (C2.Coverage)
45>FastUpToDate:     'Z:\Source\Common\Common.Datalayer\obj\Debug\Common.Datalayer.csproj.CopyComplete' (C2.Coverage)
45>FastUpToDate:     'Z:\Source\C2\Common\C2.Datalayer.Mapping.Log\obj\Debug\C2.Datalayer.Mapping.Log.csproj.CopyComplete' (C2.Coverage)
45>FastUpToDate:     'Z:\Source\Helpers\Helpers\obj\Debug\Helpers.csproj.CopyComplete' (C2.Coverage)
45>FastUpToDate:     'Z:\Source\Common\Common\obj\Debug\Common.csproj.CopyComplete' (C2.Coverage)
45>FastUpToDate:     'Z:\Source\C2\Common\C2.Datalayer.Mapping\obj\Debug\C2.Datalayer.Mapping.csproj.CopyComplete' (C2.Coverage)
45>FastUpToDate:     'Z:\Source\Common\ProxyBase\obj\Debug\ProxyBase.csproj.CopyComplete' (C2.Coverage)
45>FastUpToDate:     'Z:\Source\Common\Geofence.Contracts\obj\Debug\Geofence.Contracts.csproj.CopyComplete' (C2.Coverage)
45>FastUpToDate:     'Z:\Source\C2\Common\C2.Common\obj\Debug\C2.Common.csproj.**CopyComplete**' (C2.Coverage)
45>FastUpToDate:     'Z:\Source\C2\Common\C2.Datalayer\obj\Debug\C2.Datalayer.csproj.CopyComplete' (C2.Coverage)
45>FastUpToDate:     'Z:\Source\Common\Contracts\obj\Debug\Contracts.csproj.CopyComplete' (C2.Coverage)
45>FastUpToDate:     'Z:\Source\Sip\Sip.Contracts\obj\Debug\Sip.Contracts.csproj.CopyComplete' (C2.Coverage)
45>FastUpToDate:     'Z:\Source\Common\Diagnostics.Contracts\obj\Debug\Diagnostics.Contracts.csproj.CopyComplete' (C2.Coverage)
45>FastUpToDate: Adding output reference copy marker: (C2.Coverage)
45>FastUpToDate:     'Z:\Source\C2\Coverage\C2.Coverage\obj\Debug\C2.Coverage.csproj.CopyComplete' (C2.Coverage)
45>FastUpToDate: Latest write timestamp on input marker is **2020-06-16 13:15:46** on 'Z:\Source\C2\Common\C2.Common\obj\Debug\C2.Common.csproj.**CopyComplete**'. (C2.Coverage)
45>FastUpToDate: Write timestamp on output marker is **2020-06-15 15:10:49** on 'Z:\Source\C2\Coverage\C2.Coverage\obj\Debug\C2.Coverage.csproj.**CopyComplete**'. (C2.Coverage)
45>FastUpToDate: Input marker is newer than output marker, not up to date. (C2.Coverage)
45>FastUpToDate: Up to date check completed in 19,2 ms (C2.Coverage)
45>------ Build started: Project: C2.Coverage, Configuration: Debug Any CPU ------

**Comment by vgriph** [comment]
@ocallesp yes, there is no change when building a third or fourth time. The dates of the input markers and output markers are unchanged.

**Comment by vgriph** [comment]
@ocallesp disabling fast up to date check, or doing a full rebuild does not update the files either.

However I think I might have found the reason: We have overridden the `IncrementalClean` target, which would delete the CopyComplete files on the builds normally if no files were copied. That was done based on a suggestion in https://github.com/Microsoft/msbuild/issues/1054. I notice that that bug is now closed, so maybe we can restore the incremental clean target. I'll investigate that with our solution.

For now, I've added `<Delete Files="@(CopyUpToDateMarker)" Condition="'@(ReferencesCopiedInThisBuild)' == ''"/>` in our overridden `IncrementalClean` target, which made the up to date work correctly again. Sorry for the confusion

**Comment by ocallesp** [comment]
In case this issue appears again you can select **Diagnostic** in the **MSBuild project build output verbosity** to get a log that can help collecting information about why CopyComplete is updated/created/not touched.

![image](https://user-images.githubusercontent.com/510598/87088686-1100e200-c1ea-11ea-9426-a5ff51766476.png)
