### ISSUE TITLE
dot net framework 4.7.2 project is never up to date when using NuGet package System.IO

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6360]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1090934/dot-net-framework-472-project-is-never-up-to-date.html). Please vote and comment there to make sure your voice is heard._

---

When building dot net framework 4.7.2 projects (without any changes), we never see the following line:

```
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```

The projects always Builds. We expect the project only builds after changing anything, or after issuing a 'Clean' command.

The reason from the detailed logs is:

> 1>Project 'Project1' is not up to date. CopyLocal reference 'C:\VSTS\Project1\bin\Debug\System.IO.dll' is missing from output location.
> 1>  Encountered conflict between 'Reference:System.IO, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL' and 'Platform:System.IO.dll'. Choosing 'Platform:System.IO.dll' because AssemblyVersion '4.1.2.0' is greater than '4.1.1.0'. (TaskId:14)

It seems like the build process decides to not copy the System.IO to the output directory; because a platform System.IO.dll exists with a greater version number.

The check for any changes in the project does not recognize this situation; so it comes to the wrong conclusion (the project is not up to date).

The check for any changes in the project should recognize the situation when a NuGet dll is not copied because a platform dll exists.

This problem costs our team a lot of valuable time. Our solution includes over 75 projects; and it takes several minutes to start a debugging session; even when nothing has changed.

To reproduce the issue:
- Create a Dot Net Framework 4.7.2 class library.
- Add System.IO NuGet package.
- Build the project.
- Change nothing and Build the project again. The expected behaviour is: the project is not build because it is up to date. But the project builds anyway.

**Comment by sixeyes** [comment]
I'm using VS v16.9.1 and it's still not fixed.

**Comment by drewnoakes** [comment]
This does not reproduce for SDK-style projects.

**Comment by drewnoakes** [comment]
This applies to legacy projects that use `Packages.config`, as described in the linked feedback ticket. To workaround this issue, use `PackageReference` for package references instead.

**Comment by sixeyes** [comment]
According to this link https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

PackageReference support is limited for ASP.NET projects
