### ISSUE TITLE
Stop using NuGet's IVsFrameworkParser in Microsoft.VisualStudio.ProjectSystem.VS.TargetFrameworkProvider

### ISSUE THREAD

**Issue by zivkan** [dotnet/project-system#6369]
### Background

NuGet's `IVsFrameworkParser` API provides two APIs:

```cs
public interface IVsFrameworkParser
{
    FrameworkName ParseFrameworkName(string shortOrFullName);
    string GetShortFrameworkName(FrameworkName frameworkName);
}
```

The problem is that `System.Runtime.Versioning.FrameworkName` does not have properies that allows us to distingish `net5.0` and `net5.0-windows`. Therefore, these APIs will not work with net5.0 projects. Full net5.0 TFM spec: https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md

NuGet itself is going to be moving away from parsing the project's `TargetFramework` and will determine the project's TFM using the `TargetFrameworkIdentifier`, `TargetFrameworkVersion`, `TargetPlatformIdentifier` and `TargetFrameworkVersion`. This means that TFM aliasing is becoming increasingly close to a possibility, so it will be unsafe to assume that the project's `TargetFramework` will be parsable.

### Proposal

@tmeschter mentioned to me on Teams that this class looks like it might be used in the dependencies node in Solution Explorer. In this case, I recommend using the `TargetFramework` (either directly as the user provided, or with `ToLowerInvariant`, as [the SDK itself does](https://github.com/dotnet/sdk/blob/b8688e3db746fcd5117b78d1538936defde79e87/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets#L215)). This would allow projects to "just work" when/if [TFM aliasing gets implemented](https://github.com/dotnet/sdk/issues/1561#issuecomment-327051425).

**Comment by drewnoakes** [comment]
Currently we only use `FrameworkName.FullName` to add a `ProjectTreeFlag` to target framework nodes in the tree. This allows external code (e.g. NuGet.Client and Roslyn) can determine which target framework a given descendant node belongs to. Because external code relies on that flag, we cannot remove it or change its representation without also changing those consumers.

In all other cases we use the short name, and I believe this will correctly support aliasing.

Given that, I'm not certain what value change here would have.

**Comment by davkean** [comment]
We have to look at every usage, for example, this usage is going to fail to parse the TargetFramework: http://index/?leftProject=Microsoft.VisualStudio.ProjectSystem.Managed&leftSymbol=tl1ajfnkdtmr&file=ProjectSystem%5CTree%5CDependencies%5CCrossTarget%5CAggregateCrossTargetProjectContext.cs&line=43.

Almost all usage of the TargetFramworkProperty should be removed completely from our code base, except for the code that produces configurations.

**Comment by davkean** [comment]
Here's another usage that will be broken: http://index/?leftProject=Microsoft.VisualStudio.ProjectSystem.Managed&leftSymbol=tl1ajfnkdtmr&file=ProjectSystem%5CTree%5CDependencies%5CSubscriptions%5CDependenciesSnapshotProvider.ContextTracker.cs&line=119. We shouldn't be intepreting the value, we should be using the _TargetFrameworkMoniker_ and _TargetPlatformMoniker_ values, except for display purposes.

**Comment by jjmew** [comment]
@swesonga Could you make this a priority for 16.8 cc: @drewnoakes . Also see https://github.com/dotnet/project-system/issues/6370
