### ISSUE TITLE
The "WireUpCoreRuntime" missing required parameter "CoreRuntimeSDKLocation"

### ISSUE THREAD

**Issue by alaskanrogue** [dotnet/project-system#6391]
**Visual Studio Version**: Enterprise 2019 Preview Version 16.7.0 Preview 4.0

**Summary**: The "WireUpCoreRuntime" task was not given a value for the required parameter "CoreRuntimeSDKLocation". Related to Developer Community Problem 771203

https://developercommunity.visualstudio.com/content/problem/771203/random-error-the-wireupcoreruntime-task-was-not-gi.html?childToView=1114804#comment-1114804

**Steps to Reproduce*: Build app targeting Xamarin UWP x64 platform; switch from x32 to x64 code target.

**Expected Behavior**: Build completion

**Actual Behavior**: Error encountered preventing further compilation and debugging.

**User Impact**: Multiple applications of workaround.

[x64Build.txt](https://github.com/dotnet/project-system/files/4939211/x64Build.txt)

**Comment by davkean** [comment]
@alaskanrogue I'll need to you file this over on Developer Community. This respository contains no code that contributes to this scenario.
