### ISSUE TITLE
Bugs with imports/dependency root graft providers and GetPath

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6420]
We have two root graft tree providers, one for the "Dependencies" tree, another for the "Imports" tree.

Each has a subtle bug around `GetPath`, which manifests via CPS's `TryGetPathFromRootGrafts`.

- The dependencies tree should return `null` for any items it does not contain (test ancestry)
- The imports tree should provide an implementation that returns `FilePath` for its items

The bug can be reproduced by disabling the dependencies tree via capabilities, showing the imports tree and invoking the "Copy Path" command. You'll get the psuedo-path of form `>123` (where 123 is the item's Id).

**Comment by davkean** [comment]
This breaks in this project type: https://marketplace.visualstudio.com/items?itemName=nanoframework.nanoFramework-VS2019-Extension.
