### ISSUE TITLE
Fix race condition in LaunchSettingsValueProviderBase.OnSetPropertyValueAsync

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6430]
In the process of working on #6211 I noticed that when updating multiple settings on the debug page at the same time not all of the changes would be persisted. I believe the issue is in `LaunchSettingsValueProviderBase.OnSetPropertyValueAsync`. Currently, this method calls `IProjectThreadingService.RunAndForget` to schedule the work to happen outside of the project lock. My theory is that this allows multiple set operations to run in parallel. There is no way to atomically retrieve and update the launch settings, so even though the `LaunchSettingsProvider` serializes updates the changes can still stomp all over each other.

I think at this point we can just remove the call to `RunAndForget`; after #6343 it should no longer be necessary. Possibly, however, I have misunderstood the issue and it will be more complicated to solve.

**Comment by davkean** [comment]
RunAndForget  can overlap; it's just a Task.Run.
