### ISSUE TITLE
FastUpToDate fails because AdditionalDependentFileTimes or .CopyComplete was changed more recently than my binaries

### ISSUE THREAD

**Issue by danquirk** [dotnet/project-system#6445]
**Visual Studio Version**:
16.7.0 Preview 6.0

**Summary**:
We have an sln with ~135 projects (99% are csproj, a couple vcxproj). I frequently hit issues with incorrect FastUpToDate check results where consecutive builds still do a lot of msbuild work instead of registering every csproj as up to date. One such example here (elided project/binary names to be safe):

1> FastUpToDate: The set of AdditionalDependentFileTimes was changed more recently (7/27/2020 12:51:52 PM) than the earliest output 'E:\src\cds\bin\debug\myDLL.dll' (7/27/2020 12:39:43pm), not up to date

As one might expect from the error, this occurred on essentially every DLL and PDB causing most of the sln to get rechecked by msbuild itself (only 3 of 92 projects in this build attempt counted as up to date). Of note, it's currently ~6:45pm on 7/28 when I get the text above. This then cascades like so:

5>FastUpToDate: The set of AdditionalDependentFileTimes was changed more recently (7/27/2020 12:51:43 PM) than the earliest output 'E:\src\cds\bin\debug\myDLL.dll' (7/27/2020 12:39:46 PM), not up to date.
5>------ Build started: Project: OtherProject, Configuration: Debug Any CPU ------
3>Target GenerateTargetFrameworkMonikerAttribute:
3>  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
3>Target CoreCompile:
3>  Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
3>Target _CopyFilesMarkedCopyLocal:
3>  Touching "E:\src\cds\obj\Debug\myproj2\myproj2.csproj.CopyComplete".

touching all these CopyComplete files eventually causes these other up to date check failures:

16>FastUpToDate: No inputs are newer than earliest output 'E:\src\CDS\bin\Debug\myotherDLL.dll' (7/27/2020 7:33:52 PM). 
16>FastUpToDate: Latest write timestamp on input marker is 7/28/2020 6:46:34 PM on 'E:\src\CDS2\obj\Debug\myproj2.csproj.CopyComplete'.
16>FastUpToDate: Write timestamp on output marker is 7/28/2020 6:42:00 PM on 'E:\src\CDS2\obj\Debug\myproj3\myproj3.csproj.CopyComplete'.
16>FastUpToDate: Input marker is newer than output marker, not up to date. 

**Steps to Reproduce**:
Our code is not open source and I doubt I could easily craft a minimal repro. I'm internal to MSFT though and can share the sln internally easily enough. My alias is the same as my GitHub name. We build projects to an intermediate dir of obj\$(MSBuildProjectName) but OutputPath for everything is set to the same common dir of bin\$(Configuration)

**Expected Behavior**:
Consecutive solution builds in VS result in 100% of projects as up to date.

**Actual Behavior**:
Many projects are not considered up to date even when I build the solution immediately after a successful build.

**User Impact**:
Attempting to just run different unit tests frequently ends up failing the up to date check and causing msbuild to do multiple minutes worth of work validating targets (none of which require rebuilding) which makes for a painful dev experience. I have to wait ~2min just to begin executing another unit test after the last one even with no code changes between executions.

**Comment by ocallesp** [comment]
Fast up-to-date temporary disabled checking AdditionalDependentFileTimes until we get the correct fix.
@jjmew this should be a must-have for 16.9...

**Comment by danquirk** [comment]
@ocallesp thanks, is there a public build with the check disabled I can test?

**Comment by ocallesp** [comment]
The next public release (16.7) is on **August 05, 2020**. It will have AdditionalDependentFileTimes disabled.
