### ISSUE TITLE
ProjectLockFileWatcher.ProjectTree_ChangedAsync calculates Project Catalogs with live project data.

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#645]
It is not a high priority issue, but need consider to be fixed, because it causes project item schema/catalogs to be calculated twice for all projects during the project loading phase.

The watching service chains to the project tree dataflow, should hook project catalog dataflow through the dataflow as well, instead of calling GetCatalogsAsync directly.  The project catalog is always calculated in the dataflow once, calling the GetCatalogsAsync will force it to be recalculated with live project (instead of the project instance matching the project tree snapshot), which comes with some performance wastes (including extra computation + extra immutable dictionaries to hold results).

Recommend to be considered after RC.

**Comment by davkean** [comment]
Are you talking about this line: http://index/?query=ProjectTree_ChangedAsync%20&rightProject=Microsoft.VisualStudio.ProjectSystem.Managed.VS&file=ProjectSystem%5CVS%5CProjectLockFileWatcher.cs&line=103?

**Comment by srivatsn** [comment]
@lifengl I assume you meant that we are [calling GetConfigurationGeneralPropeties](https://github.com/dotnet/project-system/blob/e0caa72844bb2e8c532ec32425910b0b429358f5/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/ProjectAssetFileWatcher.cs#L106) which ends up calling GetCatalogsAsync and instead we should get the value of this property from the dataflow as well?
