### ISSUE TITLE
Package Properties tab should expose the new Readme property

### ISSUE THREAD

**Issue by advay26-zz** [dotnet/project-system#6457]
Similar to [#4905](https://github.com/dotnet/project-system/issues/4905), Embedded Readmes are being introduced and will be included in packages - [Embedding and displaying NuGet READMEs](https://github.com/NuGet/Home/wiki/Embedding-and-displaying-NuGet-READMEs). 

The behavior for Project Properties would be similar to Icon and License File support:

- Using a file picker, users can select a markdown file on disc (.md)

- On selection, the value updates to the file's relative path

- The project file is updated as below:

```
    <PropertyGroup>
        ...
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        ...
    </PropertyGroup>

    <ItemGroup>
        ...
        <None Include="..\assets\readme.md" Pack="true" PackagePath=""/>
        ...
    </ItemGroup>
```

The UI view:

![image](https://user-images.githubusercontent.com/51111468/89075783-f7683b80-d34c-11ea-8f39-668555f9b7bb.png)

**Comment by drewnoakes** [comment]
We will likely add support for editor metadata here that sets the FileOpenDialog default extension to `.md`, as required in the spec.

**Comment by drewnoakes** [comment]
There is some complexity here, in that the interceptor will need to create/update/remove the `None` item, in addition to the property itself.

**Comment by drewnoakes** [comment]
> There is some complexity here, in that the interceptor will need to create/update/remove the None item, in addition to the property itself.

That complexity also exists for `PackageIcon` which is not currently wired up to manage the project item. This works in the legacy pages. We need to handle this.

https://github.com/dotnet/project-system/blob/034b42b3031ab93a14697b918e52f2ee79a5c55d/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml#L94-L103

**Comment by MiYanni** [comment]
I'll be implementing this into the new property pages.
