### ISSUE TITLE
Dataset Designer Code Generator property "Hierarchical Update" is missing when using .Net Standard project

### ISSUE THREAD

**Issue by eyaldar** [dotnet/project-system#6459]
**Visual Studio Version**:  16.6.5

**Summary**:
Dataset Designer Code Generator property "Hierarchical Update" is missing when using .Net Standard project.
As a result, TableAdapterManager won't be generated.

**Steps to Reproduce**:
1.  Create a new .NET Standard 2.1 Library project
2. Add a new Dataset
3. Double click the newly created dataset xsd file
4. Open properties for the dataset.

**Expected Behavior**:
Properties should look like this (example from .Net Framework project):
![image](https://user-images.githubusercontent.com/5829836/89190121-abfe9900-d5a9-11ea-9e94-5e78a24a69ce.png)

**Actual Behavior**:
"Hierarchical Update" property is missing:
![image](https://user-images.githubusercontent.com/5829836/89190237-d5b7c000-d5a9-11ea-8ae8-7deaf1729068.png)

**User Impact**:
TableAdapterManager can't be generated

**Comment by davkean** [comment]
PR (Microsofties only): https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/265164.

**Comment by davkean** [comment]
As well as Hierarchical Update, we've also turned on ability to generate the file into another project.

**Comment by davkean** [comment]
This is fixed and will be present in 16.8 Preview 2.
