### ISSUE TITLE
New debug dialog isn't scaling correctly with High DPI

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/project-system#646]
I see the following when I open up the Debug page:

![image](https://cloud.githubusercontent.com/assets/145043/19669319/510ba144-9a13-11e6-8bb6-f559ab08c156.png)

This is on a laptop that is normally at 200% DPI but I'm logged into via Remote Desktop with 100% DPI.

**Comment by davkean** [comment]
Hmm, both cases looks like its scaling via DPI, and not Font. It should be scaling via Font, similar to what we do for WinForm's pages.

**Comment by davkean** [comment]
But the Font in both cases looks wrong.

**Comment by davkean** [comment]
Feedback item here: https://github.com/dotnet/project-system/issues/3372.

**Comment by davkean** [comment]
@dsplaisted Is this still repro'ing for you? I've tried lots of different situations, and none of them look as bad as you have above. This is me remote desktop'ing at 100% into a 200% Surface book:

![image](https://user-images.githubusercontent.com/1103906/46998100-4b506300-d16d-11e8-8278-bd22f2d9ce5a.png).

Regardless, after https://github.com/dotnet/project-system/pull/4124 the Fonts will be inherited from VS itself so will match the same size/family as the everything else.

**Comment by Pilchie** [comment]
Windows has been making changes to scaling for HDPI, so it might depend on exact Windows version and settings too...

**Comment by dsplaisted** [comment]
@davkean  I haven't seen this recently

**Comment by davkean** [comment]
@Pilchie Yes I expect this as a result of a Windows change.
