### ISSUE TITLE
Getting CA3075 XML Error from generated code. VS should be creating error free auto-generated code and doesn't conflict with the analyzer.

### ISSUE THREAD

**Issue by mavasani** [dotnet/project-system#6467]
Getting CA3075 XML Error from generated code. VS should be creating error free auto-generated code and doesn't conflict with the analyzer.

[App.Designer.zip](https://github.com/dotnet/roslyn-analyzers/files/5029473/App.Designer.zip)

Been 2 years since this issue was detected.
Please advise.

_Originally posted by @MadnessSoftware in https://github.com/dotnet/roslyn-analyzers/issues/1880#issuecomment-669270254_

**Comment by mavasani** [comment]
It seems like the generated code in `AppDesigner.vb` has [CA3075](https://docs.microsoft.com/visualstudio/code-quality/ca3075?view=vs-2019) violations for creating XmlTextReader instances. Generated code should be following the guidance from @dotpaul at https://github.com/dotnet/roslyn-analyzers/issues/1880#issuecomment-435213592.

I am not sure if this issue belongs to this repo or some other repo - please transfer as appropriate.

**Comment by MadnessSoftware** [comment]
Thanks. I saw the comments and thread regarding a workaround, however this is from user generated code from module and/or class. I'm talking about the designer code with the v3.0 FXCop is having a fit with.

**Comment by drewnoakes** [comment]
This is a strongly typed `System.Data.DataSet`. That code is not generated by the project system.

@MadnessSoftware please file an issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/61/index.html) which will create a ticket that can be routed internally to the correct team. Thanks.
