### ISSUE TITLE
After NuGet restore is done, send UpdateProjectDependentFileAsString hint message to make sure the project system will schedule a reevaluation.

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#6479]
We currently depend on file system watcher, which is not always reliable. When we miss the event, it will hang the product.

**Comment by lifengl** [comment]
+ @davkean

**Comment by davkean** [comment]
@lifengl Does this exist currently? I can't find it.

**Comment by davkean** [comment]
Nevermind, found it.
