### ISSUE TITLE
Up-to-date check incorrectly gathers items that will actually be copied to output directory

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#6508]
**Visual Studio Version**:
Version 16.8.0 Preview 3.0 [30419.156.main]

**Summary**:

Only None/Compile/EmbeddedResource/Content items are copied to the output directory, but the up-to-date check is assuming all items with the CopyToOutputDirectory metadata are copied to the output directory. Which isn't the case in this project.

**Steps to Reproduce**:

1. `git clone http://github.com/dotnet/project-system`
2. `cd project-system`
3. `git checkout 1ba317b773e43be814963bf6d5c78164826f8afe`
4. `ProjectSystem.sln`
5. Build 3 times

**Expected Behavior**:
The 3rd time everything to be up-to-date

**Actual Behavior**:
```
2>FastUpToDate: Checking PreserveNewest file 'C:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\Rules\GeneralBrowseObject.xaml': (Microsoft.VisualStudio.ProjectSystem.Managed)
2>FastUpToDate:     Source 5/20/2020 5:00:54 PM: 'C:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\Rules\GeneralBrowseObject.xaml'. (Microsoft.VisualStudio.ProjectSystem.Managed)
2>FastUpToDate: Destination 'C:\project-system\artifacts\Debug\bin\Dlls\ProjectSystem\Rules\GeneralBrowseObject.xaml' does not exist, not up to date. (Microsoft.VisualStudio.ProjectSystem.Managed)
2>FastUpToDate: Up to date check completed in 31.9 ms (Microsoft.VisualStudio.ProjectSystem.Managed)
2>------ Build started: Project: Microsoft.VisualStudio.ProjectSystem.Managed, Configuration: Debug Any CPU ------
2>Microsoft.VisualStudio.ProjectSystem.Managed -> C:\project-system\artifacts\Debug\bin\Dlls\Microsoft.VisualStudio.ProjectSystem.Managed.dll
========== Build: 1 succeeded, 0 failed, 14 up-to-date, 0 skipped ==========
```

**Comment by drewnoakes** [comment]
@davkean suggests there is a target we can call to identify the set of item types that are copied to the output.

**Comment by davkean** [comment]
There was this: https://github.com/dotnet/project-system/pull/6046/files. But bear in mind that I think this regressed performance, and is blocked on that.
