### ISSUE TITLE
Add AnalysisLevel to code analysis  property pages

### ISSUE THREAD

**Issue by jmarolf** [dotnet/project-system#6528]
Related: https://github.com/dotnet/roslyn-analyzers/issues/3823

Not that the msbuild property has been finalized and merged into the SDK we should add support for it in the.

UX is envisioned to be:

![image](https://user-images.githubusercontent.com/9797472/90820341-191e6800-e2e6-11ea-8786-2baaf3e51b26.png)

**Comment by davkean** [comment]
How does the Version drop down associated with AnalysisLevel?
