### ISSUE TITLE
Optimize solution explorer by hiding certain projects

### ISSUE THREAD

**Issue by LeoRozing** [dotnet/project-system#6535]
Dear developer,

Currently if u have a lot of projects in a solution (> 50) and the projects you work on are at the top and bottom, you have to scroll a  lot in the solution explorer to do your work. I cannot change the order or omit certain projects. If you can - temporarily can hide (or only show the relevant) projects then it is much easier to have overview of what you are doing in the current branch / PBI

TIA,

Leo Rozing

**Comment by drewnoakes** [comment]
Let us know if any of these ideas worked for you. We'll close this for now.
