### ISSUE TITLE
net 5.0 preview 8 - Warning on Dependencies VS 16.8 preview 2

### ISSUE THREAD

**Issue by frosadev** [dotnet/project-system#6553]
This is happening after the update of VS.
Targeting the project to net5.0 with the preview 8 sdk.

With all dependencies, any package.

![image](https://user-images.githubusercontent.com/26621392/91309442-7fa0fb80-e7a8-11ea-96bc-4e20c8499316.png)

steps to reproduce:

1. create a new web api project targeting net5.0;
2. add any package to the project.

_Originally posted by @frosadev in https://github.com/dotnet/project-system/issues/6275#issuecomment-680880950_

**Comment by drewnoakes** [comment]
This is due to a change in the SDK which is being fixed as part of https://github.com/dotnet/sdk/pull/13093.

**Comment by dsplaisted** [comment]
Note that this is a known issue in .NET 5.0.100 Preview 8 SDK: https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-known-issues.md#preview-8-1
