### ISSUE TITLE
ReferenceCopyLocalPaths output group has difference canonical names in .NET FX and .NET Core project system.

### ISSUE THREAD

**Issue by sujitnayak** [dotnet/project-system#6556]
**Visual Studio Version**: 16.8.0 Preview 2.0 [30414.118.master]

**Summary**:
ClickOnce enumerates through output groups of a given project configuration with IVsOutputGroup.get_CanonicalName looking for ReferenceCopyLocalPaths output group. In a .NET FX app, we see it with canonical name "ReferenceCopyLocalPaths" and in a .NET Core app, we see it with canonical name "ReferenceCopyLocalPathsOutputGroup". Expectation is to have identical names in both project systems so we don't have to check for both.

**Steps to Reproduce**:
1.  

2. 

3. 

**Expected Behavior**:

**Actual Behavior**:

**User Impact**:

**Comment by davkean** [comment]
Please open this bug internally against DevDiv\VS Core\Project\CPS, they own this piece.
