### ISSUE TITLE
Fix links when repos switch to using main instead of master

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#6557]
Part of #6857

Our documentation currently links to these six repos, Microsoft is changing default branch names from master to main so I expect these links to stop working at some point.

- [ ] https://github.com/dotnet/corefx
- [ ] https://github.com/dotnet/home
- [ ] https://github.com/dotnet/roslyn-tools
- [ ] https://github.com/dotnet/runtime
- [ ] https://github.com/Microsoft/vs-threading
- [ ] https://github.com/Microsoft/VSProjectSystem

### CONTRIBUTING.md:
  line 15: - [Visual Studio Threading Guidelines](https://github.com/Microsoft/vs-threading/blob/master/doc/index.md)
  line 17: - [Code of Conduct](https://github.com/dotnet/home/blob/master/guidance/be-nice.md)

### README.md:
  line 45:  For more information see [Contributors Code of conduct](https://github.com/dotnet/home/blob/master/guidance/be-nice.md). 

### build\proj\GenerateDependentAssemblyVersionFile.proj:
  line 7:    See: https://github.com/dotnet/roslyn-tools/tree/master/src/RoslynInsertionTool).

### docs\repo\coding-conventions.md:
  line 5: We use the same coding style conventions as outlined in [.NET Framework Coding Styles](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md), with the following additions:
  line 59: - **DO** follow the [3 threading rules](https://github.com/Microsoft/vs-threading/blob/master/doc/threading_rules.md#3-threading-rules) inside Visual Studio.
  line 62: result in random UI deadlocks for short periods of time while the code on the UI thread waits for a new thread to be spun up. See [ThreadPool Starvation](https://github.com/Microsoft/vs-threading/blob/master/doc/threadpool_starvation.md) for more information.
  line 66: We follow the [Visual Studio guidelines](https://github.com/Microsoft/vs-threading/blob/master/doc/cookbook_vs.md#should-i-await-a-task-with-configureawaitfalse) around `ConfigureAwait` usage.

### docs\repo\loading-components-with-projects.md:
  line 23: components, if we've already loaded them or the stage has passed where we should have loaded them, will cause us to automatically [reload the project](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/dynamicCapabilities.md#critical-capabilities-changes-error). We did this for compatibility mostly. We did also consider disposing autoload components if their capability disappeared, but it was very likely that their dependencies probably weren't prepared for that.

### docs\repo\debugging\async-test-hangs.md:
  line 271: You can see more information, including a WinDBG extension that dumps async callstacks, over on [Async Hang Investigations](https://github.com/Microsoft/vs-threading/blob/master/doc/async_hang.md).

### src\Microsoft.VisualStudio.ProjectSystem.Managed\Annotations.cs:
  line 3: // Copied from https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/NullableAttributes.cs

### src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\Properties\AssemblyAttributeProperties\AssemblyInfoProperties.cs:
  line 19:         // See https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets

**Comment by dmonroym** [comment]
use HEAD instead of master

**Comment by drewnoakes** [comment]
To clarify, specifying `HEAD` in the context of a remote is resolved as the commit at the tip of the default branch for that remote.

![image](https://user-images.githubusercontent.com/350947/91505705-97e15980-e913-11ea-9561-322e44dabeab.png)

![image](https://user-images.githubusercontent.com/350947/91505734-acbded00-e913-11ea-826f-9160601df93e.png)

**Comment by dmonroym** [comment]
These changes are unnecessary since they'll be redirecting correctly once those repos rename their default branch:

https://github.com/dotnet/arcade/blob/master/Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md#what-happens-to-links-to-files-in-my-repo
