### ISSUE TITLE
Produce telemetry on yellow triangles in the dependency tree

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6575]
We would like to obtain data about the prevalence of warning icons in the dependencies tree in order to monitor progress in their reduction over time.

It's not currently possible to know when a yellow triangle is displayed due to the dependency being incorrectly specified and therefore unresolvable vs. there being a product bug that results in this error state, being that the tree is the last line of defence.

However we do believe that as we reduce the number of product bugs, we should see a reduction in yellow triangles in telemetry.

---

A pragmatic approach here may be to report the number of resolve/unresolved dependencies of each type when the project is unloaded.

**Comment by davkean** [comment]
We already send telemetry when all the trees are finished, that would be a good place to do it.
