### ISSUE TITLE
Usability issue in Solution Explorer

### ISSUE THREAD

**Issue by JVimes** [dotnet/project-system#6576]
**Summary**:

Please make the default false for "open SDK-style project files with double click". Hear me out. Users expand/collapse project nodes *much* more often than they edit .csproj files. And it's confusing to double click a tree node and not have it expand; VS is the only app that does this and it doesn't do it consistently. I really believe a majority of users find the current behavior "death by a thousand paper cuts", regardless of past discussions.

![image](https://user-images.githubusercontent.com/6148201/92149321-17bb6800-eddb-11ea-8560-2de0bcd9e175.png)

**Comment by jjmew** [comment]
@JVimes  This setting that persists so there should only be a need to set it once per installation. We believe this is the right default for the long term direction as we want to treat the project file as text.

**Comment by JVimes** [comment]
Deviating from expected tree control behavior was the wrong way to do that. Expanding project nodes happens 10s or 100s of times per day. It needs a big click area. Editing the project happens on the scale of weeks or months.

Please change the default. There are better ways to coax users away from the project UI.

**Comment by drewnoakes** [comment]
Double clicking a file in the tree opens it for edit. Would you expect double clicking a source file also expands that item to show its child member nodes? The project is a file, however historically there was no good edit experience (requiring unloading of the project) so double-click fell back to expand/collapse.

There is no one clear answer here that pleases everyone. We looked at telemetry, ran a trial in preview builds and weighed up feedback before making this change. It was a measured decision.

Changing the default back again now is likely to cause more confusion.

The setting you highlight is persisted and roams with your profile. You only have to set this once.

**Comment by JVimes** [comment]
Projects are not just files, they're also folders. And they get expanded as folders much more often then they get edited as files.

I honestly believe changing the default will alleviate confusion. Users are confused now.
