### ISSUE TITLE
RFE: Allow creating new project in existing directory

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6578]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/932722/rfe-allow-creating-new-project-in-existing-directo.html). Please vote and comment there to make sure your voice is heard._

---
Repro:
- Existing C# project within a VS _Solution_ open.
- Select a _Folder_ in the _Solution Explorer_ (let's call it _Parent_) that has at least one _Folder_ inside it (let's call it _A_). Make sure both _Folder_'s refer to actual filesystem directories.
- Select _File_/_New_/_Project_
- Select a project type (tested with _Shared Project_)
- Click _Next_.
- Type _A_ for  _Project Name_.
- Select the filesystem _Location_ of _Parent_. Bonus points for having this in a location taking you considerable amount of time to locate (just to point out how this UI is).
- Switch _Solution_ drop-list from _Create new solution_ to _Add to solution_. Curse at the unwanted path-overwrite for _Location_ this operation performed. Revert it by using the non-discoverable and undocumented feature; select the _Location_ edit field and hit CTRL+Z.
- Click _Create_.

Expected:
_A.projitems_ and _A.shproj_ created inside the existing directory _A_, followed by having that shared project added to the Solution.

Actual:
Operation is prevented. You are presented with a dialog stating:
```
---------------------------
Microsoft Visual Studio
---------------------------
The project directory already exists. When a project is created, it must be placed within a new folder of the same name. Choose a different name or location for your project.
---------------------------
OK   
---------------------------
```

Recommendation:
Allow creating a project inside an _existing_ directory.

Rationale:
That directory might contain source files that are actually to be added (in the "project" sense _moved_ from the previously existing project) to the newly created project, perhaps as a first step in restructuring existing source code.

Possibly related to the following?
https://developercommunity.visualstudio.com/content/problem/584712/place-solution-and-project-in-same-directory-fails.html

---
#### Feedback Bot on 2/27/2020, 04:22 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by cartermp** [comment]
Closing as this is actually a VS issue.
