### ISSUE TITLE
Nesting partial classes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6579]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/875392/nesting-partial-classes.html). Please vote and comment there to make sure your voice is heard._

---
When I have a class split in to separate files using partial modifier, we would like to see the files nested under one single file in the solution explorer. This is more of a convenience for code organization.

Ex: Let's say we have these files in a project in the same folder.
ClassA.cs
ClassA.One.cs
ClassA.Two.cs
ClassA.Three.cs

We would like to see the files ClassA.*.cs shown nested under ClassA.cs file.
Moving ClassA.cs file to a different folder should move all files together.
Renaming the namespace or class name should affect in all the nested files too.

---
#### Feedback Bot on 1/6/2020, 00:47 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.
#### Hamdi Chahdi on 8/6/2020, 00:39 AM: 

<p>i had the same issue, we have two solution one of them nesting partiel classes working and the other no, i don't know way.<br>both of them using the same framework Net core 3.1 without any plugin or config for nesting files, also i am using VS last version Visual studio 16.7.0 Professionel in our company.</p><p>it would be better if we have this features configurable from VS </p>

**Comment by drewnoakes** [comment]
This now happens by default due to the new file nesting logic.

![image](https://user-images.githubusercontent.com/350947/92224316-fba3ed80-eee4-11ea-8ab6-cd8f4acad6fd.png)
