### ISSUE TITLE
Allow macros to be used for c# working directory

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6581]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1116196/allow-macros-to-be-used-for-c-working-directory.html). Please vote and comment there to make sure your voice is heard._

---
On the C# Project Settings/Debug page, it would be nice if the working directory box could accept macros (e.g. `$(SolutionDir)`, etc) to set a location. Really small thing, but saves reconfiguration if one was to checkout a project on a different machine with a different path.

When I try and use macros there now I get a message saying that the working directory that was entered does not exist.

**Comment by drewnoakes** [comment]
Note that we hope to improve the experience around evaluated/unevaluated property values in the new property page UI.

**Comment by cartermp** [comment]
This would be done in a property pages redesign, likely not in the existing ones.

**Comment by cartermp** [comment]
Covered under "Determine first approach to eval/uneval value handling in UI" in https://github.com/dotnet/project-system/issues/6627
