### ISSUE TITLE
C# SDK-style project makes VS operations (very) slow

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6582]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1148934/c-sdk-style-project-makes-vs-operations-very-slow.html). Please vote and comment there to make sure your voice is heard._

---
Please consider adding (or using, if already in place) one or more ways for the/any editor/IDE to interrupt Roslyn (?) doing its background processing, when the user is trying to do something interactively.

If you have an SDK-style C# project loaded in VS, it the background processing(*) performed is making VS _very_ unresponsive in a multitude of operations.

One part of this slowdown seems to be the landfill directory Roslyn calls "Cache".

Examples:

- Load a project (+) containing, say, a few hundred subdirectories (with various nesting levels) and a few thousand of files. Now, directly after loading, try using Solution Explorer to cut/paste directories in that view (emulating an actual on-disk refactoring of code). VS can hang for **minutes**.

- Do some software assisted refactoring, say renaming of a symbol used in many different files/types. VS becomes unresponsive for extended periods of time.

These are just the two I could bother to document. There are more.

While VS is shamefully slow for these operations even for VS-style C# projects, for SDK-style projects this can be... I tried to find a polite way to say "beyond pathetic", but my vocabulary is lacking.

Experience is that Roslyn (?) background processing don't have any way to cooperate with VS (or any editor/IDE for that matter) to make sure that user input takes precedence.

To spell it out: Response to user interaction should be as immediate as possible.
An operation such as cut/paste a a directory (for C# SDK-style project) boils down to a single filesystem move operation, that takes less than a millisecond if executed from a command prompt. That VS needs over a minute -- let me spell that out; over **sixty thousand times slower** -- is, like I said, beyond pathetic.

(*) The background processing is pretty much constantly pegging the CPU, at least while editing/restructuring code.

(+) Make sure it's a new project, or the hidden-away-from-user disk-consuming Roslyn "cache" is emptied beforehand. For bonus points, place this cache directory on spinning rust (via filesystem linking) - you might want to do this to save the servicable life of SSD.

---
#### Feedback Bot on 8/14/2020, 00:57 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by jjmew** [comment]
@panopticoncentral  can you take a look at this?

**Comment by panopticoncentral** [comment]
Here's the comment I left in the linked feedback item: I’m closing this suggestion as we have ongoing work to track and address performance issues with SDK-style projects, and we hope it will address the problems you are seeing. If there are specific situations where slowdowns occur, please use the Report a Problem tool to report each situation. The Report a Problem tool captures valuable information about the state of Visual Studio and can help narrow down the specific problem that you are encountering. We are sorry that you are encountering issues and are focused on improving performance.
