### ISSUE TITLE
Option to use the new Windows Terminal app when running console apps.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6583]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1044424/option-to-use-the-new-windows-terminal-app-when-ru.html). Please vote and comment there to make sure your voice is heard._

---
There should be an option to use the new Windows Terminal app (if installed) for display of console output when running/debugging console apps from Visual Studio.

---
#### Feedback Bot on 5/22/2020, 01:11 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by drewnoakes** [comment]
I believe the original ticket should be moved to the debugger team.

**Comment by cartermp** [comment]
Yep, this is being moved to them.
