### ISSUE TITLE
Add Multilingual Application Toolkit to Visual Studio and improvement in localization

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6584]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1092142/add-multilingual-application-toolkit-to-visual-stu.html). Please vote and comment there to make sure your voice is heard._

---

I wanted to ask to add the multilingual application toolkit to Visual Studio. It is a a great product, but it has been put in the support janitorial closet. Bring it in to Visual Studio. Developers use the product make our life's easier.

Last in resx files Visual Studio display a table, but that table can contain hundreds of localized strings. Please add a search, and typing in a letter and the focus is switched to the first occurrence of that letter. A panel to the left with the alphabet could also do this. The panel displays the alphabet, and when a letter is clicked switch focus to the first occurrence of that letter.  It is very tedious with page or line down being our own search options.

**Comment by cartermp** [comment]
Closing as this is actually a request on Windows dev tooling, so this was retriaged to them.
