### ISSUE TITLE
Improve the under the covers operation of NET framework Target selection in Project Properties

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6586]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/996508/improve-the-under-the-covers-operation-of-net-fram.html). Please vote and comment there to make sure your voice is heard._

---
<p>This suggestion relates to a problem I have had using Visual Studio and which I raised under incident:  120040725000301 Unresolved references when targeting NET Framework 4.6.1 </p><p></p><p>Our product has evolved over a period of 10 years but our customers, who are defence contractors, are always reluctant to upgrade their platforms because they have to retest their own products when things are changed and because such upgrades are of no benefit to them.</p><p>Consequently although we are trying to keep up with the latest version of Visual Studio in house, we have to support older versions of the NET Framework.</p><p>I had therefore hoped that I could build a project to target NET Framework 4.6.1 using VS2019 but the build was broken by References to NET 4.7.2 dependent assemblies, despite my best efforts to use 4.6.1 assemblies by applying the Net Framework 4.6.1 Developers Pack.  The outcome of the Support Incident quoted above is that my expectation to be able to simply change a project setting so as to be able to target the old framework 4.6.1 was misplaced.</p><p>My question to Udit, who dealt with the Support Incident, was in essence this:</p><p>&quot;What is the point of being able to target and re-target a Project to any one of the NET Framework versions, as provided for in the Project Properties Application dialogue facility, if the prospects of it working are not guaranteed?&quot;</p><p>I am not an inexperienced developer, so when things don't work I tend to think I must have done something wrong and look for mistakes in what I have done, rather than doubt the tools I am working with. So my line of thinking was that I had picked the NET Framework that I wanted to target, I had installed what I believed to be the right package of assemblies, otherwise what is in the NET Framework 4.6.1 Developers Pack,  but it wouldn't build, and I couldn't see References to the 4.6.1 assemblies that I needed to introduce.to fix the build. What had I done wrong? </p><p>Imagine yourself in the position, as I was, that you have a build targeting NET Framework 4.7.2, then you realise that your customer needs it to target 4.6.1 so you think OK I think I can do that by changing the Project Properties but in truth you can't because the real changes needed to complete the retargeting operation are not available to you.  Worse still, the retargeting process does not even identify the References that have been made incompatible with the newly chosen target.  </p><p>That is what is so misleading for the user.  </p><p>In my view VS is totally misleading, setting the Target NET Framework to 4.6.1 should force the issue that all References are checked and realigned to that version of NET Framework, i.e. 4.6.1 drawing on the contents of the Net 4.6.1 Developer Pack or whatever is required, and references to 4.7.2 dependencies should be removed.</p>

---
#### Feedback Bot on 4/21/2020, 00:57 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by drewnoakes** [comment]
I responded to the customer on the feedback ticket. It's possible that their project has dependencies that do not work with the earlier target framework they wish to target.

A potential improvement to the product here would be to disallow selecting target frameworks which are not supported by the project's existing dependencies, or at least showing a warning immediately upon selection to explain why the selection is problematic.

**Comment by jjmew** [comment]
We move the ticket to MSBuild
