### ISSUE TITLE
Add Reference

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6587]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/888889/add-reference.html). Please vote and comment there to make sure your voice is heard._

---
<p>Visual Studio need to use the location of the solution as basis for where to add references, not the folder from other solutions (ie, where you added from in previous solution).</p> <p>I'm working with 15+ solutions, and always have to navigate around from the previous solution to add my references.</p>

---
#### Feedback Bot on 1/18/2020, 10:29 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jjmew** [comment]
This is CPS
