### ISSUE TITLE
New Project Structure: Seperate Code and Binaries - Add "Project Output Location" option

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6588]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1159918/new-project-structure-seperate-code-and-binaries-a.html). Please vote and comment there to make sure your voice is heard._

---
So far, for the .NET projects, the /bin and /obj folders are created within the solution/project folders. 

**Disadvantages:**
1. These folders are added to the source control unless ignored explicitly in .gitignore
2. Code sharing is difficult with the binaries included in the folders and we have to clean these to include in a Zip
3. Cleaning up of disk space becomes cumbersome unless we use a tool or script to purge these folders when needed

**Change Request**
1. Allow developers to choose a "Project output location" via new locations option
2. For existing/new projects, move all /bin/** and /obj/** items to the "output location"
3. Allow us to get to this folder from solution explorer context menu option OR show _linked /bin and /obj_ folders

---
#### Feedback Bot on 8/25/2020, 01:36 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by drewnoakes** [comment]
To summarise, I see two requests here.

1. Add UI to control the location of the obj and bin folders
2. Add project context menu item(s) that opens these folder(s) in Explorer

Note that it _is_ possible to redirect the output of the projects within the solution. This repo does exactly that.

**Comment by SNathani** [comment]
Drew, 
Your understanding is correct. The project's _Build > Output_ Path is relative to project's location and we want to change this on developer's computer. If we have an "_Projects output location_" option, this will be used as base path for build outputs of all projects on developer's computer.

For example, I have "_Projects location_" set to "C:\Projects". The new option, "_Projects output location_" is set to "C:\Projects Binaries". Then the final folder structures for a project will be as below:

C:\Projects\<solution name>\<project name>\ (All code files)

C:\Projects Binaries\<solution name>\<project name>\bin
C:\Projects Binaries\<solution name>\<project name>\obj

By default, the "Projects output location" is same as the "Projects location" (this is the current situation), but developer can change it to a different location to have better control over his/her environment (change request).

**Comment by jjmew** [comment]
Changing the output is already supported by modifying the project file. We don't believe that adding UI for it is the right thing to do as it will increase the cognitive load.
