### ISSUE TITLE
No 'Find project' menu item when project is moved and solution can't load it

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6589]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/idea/1039629/no-find-project-menu-item-when-project-is-moved-an.html). Please vote and comment there to make sure your voice is heard._

---
My issue is such:

I have a Solution (.sln) file, with Projects A.csproj, B.csproj, and C.csproj.  Say everything is fine, the solution will open, and all the projects load successfully.

Now, let's suppose I close Visual Studio for whatever reason, and I go into my File Explorer and I move the B.csproj project to a different location on my file system.  I do not delete it; I simply move it and all its files and folders, wholesale, over to some new location.

Perhaps this is because I have come up with a new way of organizing my code on my computer.

Then let's say I re-open VS.  

I get the error shown in fig01.png (see attachments for this and other .png files mentioned).  

It's clear why the error is showing -- VS is loading the .sln file and the .sln file says the B.csproj file is at XXX path on my computer.  

However, this is not the case anymore, because I moved B.csproj and its files and folders to somewhere new.

So, I click to dismiss the message box.  

The solution continues loading and then I see an icon for the offending project in my Solution Explorer showing as not loaded.  this is shown in fig02.png (see attachments).

When I click Reload Solution, the IDE simply angrily beeps at me.  This is not efficient.

I know I can do the following two steps in order to restore B.csproj:

1. Remove the offending project from the solution utilizing the right-click menu in Solution Explorer; and then
2. Right-click the Solution, say Add -> Existing Project, click to find my project in the resulting file open dialog, and hit OK.

I know that I can also edit the .sln file itself (obviosuly, having to close VS to do so first).  What a pain!

Wouldn't it be spiffy if, as discussed in fig03.png, there were a 'Find Project' for the 'non-loaded icon' in VS Solution Explorer, so I can simply right click the "bad" project and, through a file open dialog, accomplish the same as above in just one menu click?

Really would be great.  Not to mention, a time saver.

---
#### Feedback Bot on 5/19/2020, 07:50 PM: 

We have converted this feedback item from problem to idea. This change was done to better reflect the feedback's nature.
#### Feedback Bot on 5/20/2020, 02:43 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by drewnoakes** [comment]
In summary: Add the ability to locate a missing project via the UI.

Currently this requires either manually editing the sln file, or removing and re-adding the project at its new location.

**Comment by cartermp** [comment]
Closing as this is actually a VS issue, re-triaged to them.
