### ISSUE TITLE
prompt for unsaved csproj changes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6590]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1118900/prompt-for-unsaved-csproj-changes.html). Please vote and comment there to make sure your voice is heard._

---
It is happening so often that changes on csproj aren't saved. Typically you can rename file in Visual Studio, compilation pass, but PR build is failing because you have forgot to save changes on csproj.

---
#### Feedback Bot on 7/20/2020, 08:00 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by cartermp** [comment]
Closing as this is actually a VS issue, re-triaged to them.
