### ISSUE TITLE
Using lower case package name does not flow

### ISSUE THREAD

**Issue by jnyrup** [dotnet/project-system#6597]
**Visual Studio Version**: 16.7.3

**Summary**:
When referencing a nuget package through `PackageReference` and using a lower cased package name instead of matching the exact casing, the nuget package does not seem to flow properly other projects.
When changing the package name to match the exact package name, the nuget flows as expected.

**Steps to Reproduce**:

1. Download [BaseLibrary.zip](https://github.com/dotnet/project-system/files/5194095/BaseLibrary.zip)

2. build in Visual Studio

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/919634/92581123-898a2a80-f28f-11ea-879a-4a54569607e6.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/919634/92581012-69f30200-f28f-11ea-91cf-2a4baca39875.png)

**User Impact**:

**Comment by drewnoakes** [comment]
This was fixed at some point in the last few releases where a bunch of dependencies tree code was rewritten.

![image](https://github.com/dotnet/project-system/assets/350947/f11d6e16-2448-4d21-a499-b29868f2cf6f)
