### ISSUE TITLE
Project System: VSHost replacement

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#66]
_From @davkean on April 11, 2016 22:56_

Currently csproj/msvbproj uses vshost.exe to "speed up" F5 debugging for desktop client apps.It is also used for immediate window evaluation without starting a debugging session. We need to figure out if we are going to bring this forward to CPS or not.

_Copied from original issue: dotnet/roslyn#10484_

**Comment by davkean** [comment]
ClickOnce partial trust support is also handled by VSHost.

**Comment by davkean** [comment]
_From @tmat on April 12, 2016 3:19_

@tmat

**Comment by davkean** [comment]
_From @KirillOsenkov on April 17, 2016 5:51_

Note that using VSHost prevents you from inspecting most optimized variables in Watch/Locals/etc. windows. I always turn it off (and enable COMPLUS_ZapDisable=1) to actually see the variables in the debugger. My understanding is that the vshost process doesn't inherit environment from devenv, so COMPLUS_ZapDisable=1 has no effect.

I've never seen any benefit from VSHost being turned on. No perceptible perf improvement at all.

**Comment by davkean** [comment]
We gathered the data, there's ~300ms win on F5 with the the hosting process, but we end up paying 3 - 10 seconds on solution load, and stop debugging.

**Comment by tmat** [comment]
It's a bit more complicated than that. There are other factors. The debugger team is working on some precise measurements to determine why exactly VS hosts helps F5 speedup in some scenarios.

**Comment by davkean** [comment]
@tmat @ManishJayaswal where did we land with this?

**Comment by ManishJayaswal** [comment]
Debugger team had an action item to identify the specific benefits of this process on various project types. I had pinged them last week and they had asked for 2 more weeks time to get back.

**Comment by davkean** [comment]
This has been removed - there's no work to do here.

**Comment by tmat** [comment]
Actually, it's still there to support DTEE for class libraries. It's only loaded when DTEE is used.

**Comment by panopticoncentral** [comment]
@davkean @tmat Can you explain a little more what work CPS would need to do in this case?

**Comment by davkean** [comment]
We fire up VSHost for the immediate window inside csproj, the work, if we supported it, would be to figure out how that works and port it.

**Comment by tmat** [comment]
I'm not sure it's worth the effort. I think there are more important things to do.

**Comment by davkean** [comment]
Agreed, I don't think this will ever bubble up as important. Closing this out.
