### ISSUE TITLE
csproj completion for new properties

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/project-system#6600]
Some new properties that are being doc'ed in https://github.com/dotnet/docs/pull/20537 will probably need to have auto completion for csproj files (also vbproj).

|Property name|Allowed value(s)|
|---------------|-----------------|
|AnalysisMode |<ul><li>Default</li><li>AllEnabledByDefault</li><li>AllDisabledByDefault</li></ul>|
|CodeAnalysisTreatWarningsAsErrors|true/false|
|EnforceCodeStyleInBuild|true/false|

**Comment by mavasani** [comment]
Thanks @Youssef1313!

**Comment by drewnoakes** [comment]
Thanks @Yousef1313. 

Autocomplete is driven by the XSD defined in MSBuild:

https://github.com/dotnet/msbuild/blob/master/src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd

Fixed in dotnet/msbuild#5728

**Comment by drewnoakes** [comment]
Note that `CodeAnalysisTreatWarningsAsErrors` was already present.
