### ISSUE TITLE
Handle retargeting to/from .NET5.0

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#6601]
As there is an effort going on for .NET5 to explicitly specify the platform and platform version in the target framework moniker in the project file, we should handle both cases of upgrading and downgrading.

For WPF and WinForms projects, when trying to retarget to .NET5.0, we should add `-windows` to the target framework moniker in the project file; i.e. from `netcoreapp3.1` to `net5.0-windows`.
- The user will get a warning from the SDK that they are using the WindowsDesktop SDK.

**Comment by jjmew** [comment]
We need a clear spec here of what we want to build. I am keeping this untriaged until we have a spec.

**Comment by jjmew** [comment]
Assigning to @cartermp for the spec

**Comment by davkean** [comment]
@cartermp I think we should ignore the UseXXX properties on upgrade and just always remove it. If we do downgrade, we need to think about if should add it back given they now support building downlevel WPF/WinForms without it on the latest SDK.

**Comment by cartermp** [comment]
Some notes from a meeting with SDK folks:

* The .NET 5 TFM that should be shown in the property pages for WPF and WinForms apps on .NET Core should be `net5.0-windows`, @melytc and @sfoslund to take a look and ensure this gets
* .NET SDK now has logic such that it will import the `WindowsDesktop` targets even if you don't specify it in the SDK attribute in your project file if it is a WinForms or WPF app. So the "downtarget from a new 5.0 winforms app to 3.1 winforms app" scenario should no longer give a full page of errors in the error list anymore.
* The SDK will requires specifying `UseWPF` or `UseWinforms` if you want access to WPF or WinForms APIs. We should still keep this when uptargeting and we should retain them when downtargeting.

**Comment by jjmew** [comment]
@melytc is this completed?

**Comment by drewnoakes** [comment]
One but we haven't addressed is;

> The .NET 5 TFM that should be shown in the property pages for WPF and WinForms apps on .NET Core should be net5.0-windows

I'm not sure whether we need this, or how we would implement it.

**Comment by melytc** [comment]
> I'm not sure whether we need this, or how we would implement it.

I think this was our first way of handling the new platform properties, but we are now explicitly declaring it. 
When creating a new WPF app, we set the TFM to include the `-windows`. For a WinForms app, `-windows7.0` is set.

cc: @KathleenDollard, @sfoslund

**Comment by sfoslund** [comment]
Agreed, the templates automatically set the `-windows` platform identifier when necessary and AFAIK this shows up correctly in the TFM drop downs, so that scenario should be covered.
