### ISSUE TITLE
Allow project types to rename sub nodes into the dependency tree

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#6604]
MSIX deployment projects want to rename Projects -> Applications. We should let custom project types customize these nodes.

The References tree does this via the same mechasim that you customize the real tree:

``` C#
        [ImportMany(ReferencesProjectTreeCustomizablePropertyValues.ContractName)]
        protected OrderPrecedenceImportCollection<IProjectTreePropertiesProvider> ProjectTreePropertiesProviders { get; private set; }
```
``` C#
    [ProjectSystemContract(
        ProjectSystemContractScope.UnconfiguredProject,
        ProjectSystemContractProvider.Extension,
        ContractName = ReferencesProjectTreeCustomizablePropertyValues.ContractName,
        ContractType = typeof(IProjectTreePropertiesProvider))]
    public class ReferencesProjectTreeCustomizablePropertyValues : IProjectTreeCustomizablePropertyValues, IProjectTreeCustomizablePropertyValues2
    {
        /// <summary>
        /// Gets or sets the value which will be used in <see cref="IProjectTree.Caption"/>.
        /// </summary>
        public string? Caption { get; set; }

```

``` C#
        private void ApplyProjectTreePropertiesCustomization(
            IProjectTreeCustomizablePropertyContext context,
            ReferencesProjectTreeCustomizablePropertyValues values)
        {
            foreach (var provider in this.ProjectTreePropertiesProviders.ExtensionValues())
            {
                provider.CalculatePropertyValues(context, values);
            }
        }
```

Dependencies node should just do the same.

**Comment by davkean** [comment]
//cc @drewnoakes

**Comment by drewnoakes** [comment]
A `IProjectTreePropertiesProvider` receives `IProjectTreeCustomizablePropertyContext` (with 2/3 versions) but that doesn't have enough information available to identify the node to rename reliably as far as I can tell. You get the parent flags, but not the flags of the node in question.

**Comment by davkean** [comment]
If we provider our version of the class, we can provide whatever information we need to enable them to distiguish it.

**Comment by jjmew** [comment]
@drewnoakes how much work is involved on doing this?

**Comment by drewnoakes** [comment]
@jjmew I estimate a day.

**Comment by drewnoakes** [comment]
There was already an attempt to use these interfaces for node customisation, but the implementation was not adequate. I'll fix it and get a PR in today.
