### ISSUE TITLE
Visual Studio incorrectly launches WinExe with console (Microsoft.NET.Sdk.Web)

### ISSUE THREAD

**Issue by andreasstolpmann** [dotnet/project-system#6613]
**Visual Studio Version**: 16.7.2

**Summary**:
If i add `<OutputType>WinExe</OutputType>` to a new ConsoleApp and run it the app gets started, the Main method is executed and the app is shut down again. (expected)
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>
</Project>
```

If i change the Sdk to `Microsoft.NET.Sdk.Web` and start the app again now a console window is opened despite still using WinExe. (I'm aware of the LauchSettings.json that is created. I just deleted it.)

It seems be a Visual Studio problem as the console window is not opened if i just double click the executable.

**Comment by davkean** [comment]
I don't think we control this, @BillHiebert you override this in the web tooling, yes?

**Comment by BillHiebert** [comment]
@davkean Yes, we will try to run the application as a web application which we host in a console window. We don't checkout the output type to see if it is a windows application since we don't expect it to be one.

**Comment by andreasstolpmann** [comment]
But why does running the app outside of Visual Studio lead to the expected behavior? I would consider this a bug.

In my actual use case i already have a WinForms window opening up that contains some debug info. So i really don't need the console window. This extra window is just annoying. Also we used .netFramework and asp.net before and everything was working as expected. 

Do you maybe know about a work around i could use?

**Comment by davkean** [comment]
@andreasstolpmann It's a bug/feature request. Unfortunately, this repository doesn't own this code that launches the app here. I can move this bug internally against @BillHiebert's team, or alternatively if you file a new issue via Help -> Send Feedback -> Report a Problem and point me to it, I can route it to the right team.

**Comment by andreasstolpmann** [comment]
@davkean Alright, thank you: https://developercommunity.visualstudio.com/content/problem/1191199/visual-studio-incorrectly-launches-winexe-with-con-1.html

**Comment by jjmew** [comment]
We will track this internally

**Comment by andreasstolpmann** [comment]
@jjmew can you please take a look at the Visual Studio Ticket i created? (https://developercommunity.visualstudio.com/content/problem/1191199/visual-studio-incorrectly-launches-winexe-with-con-1.html) 

It still is flagged as "Need More Info" despite multiple comments providing that info.

**Comment by jjmew** [comment]
@andreasstolpmann We did an investigation and determine that it was a WebTools issue. We moved the  ticket to that team.  cc: @vijayrkn
