### ISSUE TITLE
Unable to detect design-time build inside Visual Studio

### ISSUE THREAD

**Issue by joeltankam** [dotnet/project-system#6614]
**Visual Studio Version**: 16.7.3

**Summary**:
I'm applying some customization on design-time builds, and I was hoping to use `'$(DesignTimeBuild)' == 'true'` (or `'$(BuildingProject)' != 'true'`). Unfortunately, when building inside Visual Studio, which I was expecting to be a design-time build, the first property is not set and the second equals to `true`. 

**Steps to Reproduce**:
1. Build a project using Visual Studio
2. Read `$(DesignTimeBuild)` and `$(BuildingProject)`. Using a custom target for example :

```xml
  <Target Name="_CustomBeforeCoreCompile" BeforeTargets="CoreCompile" >
    <Message Text="## $(DesignTimeBuild)" Importance="High" />
    <Message Text="## $(BuildingProject)" Importance="High" />
  </Target>
```

**Expected Behavior**:
`$(DesignTimeBuild)` should be `true` and `$(BuildingProject)` empty (I'm not sure about that last one).

```
## true
##
```

**Actual Behavior**:
`$(DesignTimeBuild)` is empty and `$(BuildingProject)` is `true`.
```
##
## true
```

Am I doing something wrong here ?
Thanks.

**Comment by tmeschter** [comment]
Design-time builds and building in VS are unrelated. A build running in VS is not necessarily a design-time build, and not every design-time build will necessarily run in VS.

If you run "Build Project" or "Build Solution" or similar from within VS, that is _not_ a design-time build; that's just a regular (or "real") build that you happen to be starting from Visual Studio.

What are you trying to accomplish?

**Comment by joeltankam** [comment]
@tmeschter Thanks for your reply. 
I was trying to apply a hack from JetBrains, regarding performance using SDK-style projects : [A Story About .csproj, Large Solutions and Memory Usage](https://blog.jetbrains.com/dotnet/2020/05/11/story-csproj-large-solutions-memory-usage/)

**Comment by tmeschter** [comment]
Ah, I see.

There is no explicit trigger for design-time builds. Rather, they happen whenever VS detects a relevant change to a project or its inputs. You can, however, use the [Project System Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools) extension to see when they occur, what they are querying for (via the targets run), and capture build logs for them.

**Comment by davkean** [comment]
We also have the following which describes them: https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md.
