### ISSUE TITLE
Any differences in assembly when build .Net Framework project using old csproj and new SDK csproj

### ISSUE THREAD

**Issue by sassy224** [dotnet/project-system#6616]
**Visual Studio Version**: VS2019 16.7.3 and VS2019 Preview 16.8.0 Preview 3.0

**Summary**:
As mentioned in [roslyn-analyzers issue #4165](https://github.com/dotnet/roslyn-analyzers/issues/4165#issuecomment-693196043), I would like to know whether there will be any differences if I build my .Net Framework 4.5.2 projects using below approaches:

- Use old .Net Framework csproj.
- Use new SDK csproj that target net452

**User Impact**:
We have a huge library targets .Net Framework 4.5.2, and we are looking into using roslyn analyzers to deliver better source code. We don't want to install the new nuget FxCopAnalyzers because it creates additional dependency and it contains too many rules - the time increases in build is huge. We just want to control the rules with .editorconfig file, and enable/disable running code analyzers with setting <RunAnalyzersDuringBuild> = true or false using Directory.Build.props.
To enable that, we are advised to use new SDK style project and target net452 instead of using the old .Net Framework project. The question is whether the 2 approaches produce the same assembly files? Or are there differences, broken changes?

**Comment by davkean** [comment]
There are differences in the build environment (for example, some defaults are different and some features are turned off, such as [AssemblyFolderEx](https://github.com/dotnet/sdk/issues/994) support), so if you are switching across you should fully test your code before merging. There are also feature differences inside VS itself which you can see here: https://github.com/dotnet/project-system/blob/master/docs/feature-comparison.md. Some features, such as ASP.NET (.NET Framework) are not supported at all.

Make note that while SDK-based projects certaintly make it easier to consume the analyzers, they are not required to use this support. Legacy projects can consume .editorconfig settings to control rules. They don't have the nice `EnableNETAnalyzers` experience, but you can mimic it by just installing the packages references into the project's you want them to run (which could be based on a property set in these projects).

**Comment by sassy224** [comment]
@davkean thanks for confirming. So there are differences, switching to SDK-based projects needs a proper plan. 
I got the answer I want so close the issue for now.
