### ISSUE TITLE
ASP.NET flavor replacement spike

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#6620]
This issue tracking ASP.NET flavor replacement spike:

- [x] Setup feature branch
- [x] Resolve configuration differentence (checked in a directory.build.props that lights up SDK-based configurations)
- [ ] ~Flavor opt-in via IFlavoredProjectCompatibilityProvider~ Unneeded
- [x] Map flavor project type -> capability. 
   - 349C5851-65DF-11DA-9384-00065B846F21 -> AspNet for example.
- [ ] Web Forms Intellisense ie IVsWebProjectContext wrapper
- [ ] F5 Debugging into IIS Express
  - Maybe via in-memory Launch Profile
- [ ] Configuration system (being able to recognize configurations from conditions vs SDK-based configurations)

Bugs:

https://github.com/dotnet/project-system/issues/6668

**Comment by davkean** [comment]
tag @BillHiebert

**Comment by davkean** [comment]
Things to investigate/file:

- [ ] ASPXCodeBehind -> View Designer interaction (see WindowsFormsEditorProvider)

**Comment by slang25** [comment]
Hi @davkean, would you be able to give an update on this spike please, I know a lot of people are keen to see progress here 🙂

**Comment by jjmew** [comment]
The spike has been completed and we have gathered information that will inform us once we are ready to make a decision.
