### ISSUE TITLE
Up-to-date Check does not work properly on first solution opening

### ISSUE THREAD

**Issue by joeltankam** [dotnet/project-system#6633]
**Visual Studio Version**: 16.7.3

**Summary**:
Up-to-date check doesn't work when a solution is opened for the first time. 

**Steps to Reproduce**:

1. Create a SDK-style project and the corresponding solution

2. Build using command-line

3. Open Visual Studio and build 

**Expected Behavior**:
The project should be considered as "up-to-date" since it has already been built using command-line.

**Actual Behavior**:
MSBuild is triggered on the project :

> FastUpToDate: The up-to-date check has not yet run for this project. Not up-to-date. (SampleProject)
>------ Build started: Project: SampleProject, Configuration: Debug Any CPU ------
>SampleProject -> C:\Temp\SampleProject\bin\Debug\netcoreapp3.1\SampleProject.dll
>========== Build: 1 succeeded, 0 failed, **0 up-to-date**, 0 skipped ==========

**User Impact**:
We have huge solutions (300+ projects, mix of SDK-style C# projects and C++ projects) and our workflow requires to first build the repository using command-line. It's pretty inconvenient to recompile all the projects inside Visual Studio (even if it is not, I assume, a full recompilation) when opening the solution.

Is there anyway we could fix this behavior ? 
Thanks

**Comment by ocallesp** [comment]
@rainersigwald  do you know which data can we (FUTD) get from MSBuild so we can know if the project is out of date when the solution is first loaded  ?

**Comment by davkean** [comment]
MSBuild doesn't have a single bit that says its "up-to-date". It needs to effectively do a build to figure that out:

Try this:

1. From command-line build the project
2. From command-line build the project again

That 2nd build is exactly what we're doing within Visual Studio, afterwhich we've filled out internal VS caches. We're not doing a full-build in this case.

@cdmihai is working on a feature that will better track this up-to-date in MSBuild and would let us share the data. This will be much better after that.

**Comment by joeltankam** [comment]
What caught my attention is that, when using old-style project format, Visual Studio is somehow able to know that the projects are "up-to-date".
Feel free to close this issue if there is no way to go back to this behavior.

**Comment by joeltankam** [comment]
I also feel like **this** could be improved :

> Input 'C:\Temp\SampleProject\SampleProject.csproj' (29/09/2020 12:09:03) has been modified since the last up-to-date check **(01/01/0001 00:00:00)**, not up to date.

**Comment by drewnoakes** [comment]
@joeltankam 

> I also feel like this could be improved :
>
>> Input 'C:\Temp\SampleProject\SampleProject.csproj' (29/09/2020 12:09:03) has been modified since the last up-to-date check (01/01/0001 00:00:00), not up to date.

Agree. Improved in https://github.com/dotnet/project-system/pull/6645.

**Comment by davkean** [comment]
> What caught my attention is that, when using old-style project format, Visual Studio is somehow able to know that the projects are "up-to-date".

I wonder if legacy persists this data to implement that, or just recalculates this on load. We should figure out what it does here and see if we can do the same thing.

**Comment by drewnoakes** [comment]
From https://github.com/dotnet/project-system/issues/4585:

> <sup>Follows discussion in https://github.com/dotnet/project-system/pull/4574#issuecomment-464214971</sup>
> 
> `BuildUpToDateCheck` tracks changes to the set of project items, and when they change, the next build request is considered not up to date. The `_itemsChangedSinceLastCheck` flag used to track this defaults to `true`.
> 
> >>>> Why is the first build always out of date?
> >>>
> >>> I assume because we can't know if the set of input items changed.
> >>
> >> That was presumably true before we cached designtime build results between solution loads, but now that we do, we should be able to tell, right?
> >
> > Even without caching between loads - after the first design-time build has finished, and the project has built at least once in a previous load - why would it be considered out of date? We've gathered all inputs at that point, right?
> 
> It may be possible to optimise this further, potentially avoiding rebuilding all projects after a solution reload, for example.

**Comment by drewnoakes** [comment]
@ocallesp I'm taking this as part of incremental build perf work for 17.0.
