### ISSUE TITLE
F2 File-rename creates a temporary file

### ISSUE THREAD

**Issue by ocallesp** [dotnet/project-system#6635]
F2 (File-rename) is creating a temporary file

Steps to repro:
1) Open a csproj in codespaces
2) Select a file from the solution explorer
3) F2 to rename the file
4) Save the file after the symbolic rename
5) Check solution explorer created a new file

![File_rename_is_creating_a_tempFile](https://user-images.githubusercontent.com/510598/94619547-ef038280-0261-11eb-9902-9fb951adad22.gif)

**Comment by davkean** [comment]
This will be a Codespaces workspace bug - something needs to rename the document in the local running document. We don't own this scenario.,

**Comment by jjmew** [comment]
@ocallesp can you move this to the Liveshare team?

**Comment by ocallesp** [comment]
Moved to Liveshare

https://dev.azure.com/devdiv/DevDiv/_queries/edit/1225383
