### ISSUE TITLE
File Nesting: Should be using case-insensitive comparisons

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#6636]
Playing around the file nesting feature, I found that paths are compared using case sensitive paths, which confused me as I couldn't figure out why the rule wouldn't work.

For example, the following rule (which is in the default rule file) will group `Resource.designer.cs` under `Resource.resx` but not `Resource.Designer.cs`. On Windows, we almost always use case insensitive comparisons.

``` js
{
  "help": "https://go.microsoft.com/fwlink/?linkid=866610",
  "root": true,

  "dependentFileProviders": {
    "add": {
      "addedExtension": {},
      "pathSegment": {
        "add": {
          ".*": [
            ".designer.cs",
          ]
        }
      },
      "extensionToExtension": {
        "add": {
          ".designer.cs": [
            ".resx"
          ]
        }
      }
    }
  }
}

```

**Comment by drewnoakes** [comment]
Fixed by https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/290330
