### ISSUE TITLE
File Nesting: Remove Custom Settings bypasses source control

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#6639]
**Visual Studio Version**:
Version 16.9.0 Preview 1.0 [30529.269.main]

**Summary**:
_Remove Custom Settings_ is skipping source control APIs when deleting the file on disk. Its making the assumption that the file is always in a git-controlled environment and is never read-only on disk.

**Steps to Reproduce**:
1. Create a new Project
2. Right-click project and choose File Nesting -> Add Project Settings
2. Add project and contents to a TFS-based Team Project
3. Drop File Nesting menu, and choose Remove Custom Settings -> .filenesting.json

Note: If you want to mimic TFS, just make the file read-only on disk and the same behavior occurs.

**Expected Behavior**:
For the file to be deleted and to show up in Pending Changes

**Actual Behavior**:
Nothing

**User Impact**:

**Comment by davkean** [comment]
I suspect the same behavior with Solution-wide File Nesting settings.

**Comment by swesonga** [comment]
Fixed in CPS PR [295245](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/CPS/pullrequest/295245)
