### ISSUE TITLE
File Nesting: Settings copied from the Default by default contains a nesting cycle

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#6640]
**Steps to Reproduce**:

1. File Nesting -> Add Custom Settings
2. In Dialog, in Template choose "Default"

Expected: No warnings in the error list
Actual:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	NEST0001	The following nesting cycle was detected: '.*->.tt->.*'. Please update the file nesting settings (in this file or a file higher up in the hierarchy) to avoid cycles, as they lead to unexpected behavior.		C:\Users\davkean\AppData\Local\Microsoft\VisualStudio\NestingProfiles\Settings11.filenesting.json	102	
```

**Comment by davkean** [comment]
This will cause the project fault if this cycle is hit.

**Comment by swesonga** [comment]
Fixed in CPS PR [295253](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/295253)

**Comment by ChrisTorng** [comment]
I still see this problem in VS 16.9.4. I found a workaround. Add the following to the custom setting:

      "allExtensions": {
        "remove": "*"
      }
