### ISSUE TITLE
Form icon lost in Solution Explorer after changing the Build Action value in Properties window and most of values in Build Action are different from .NET Framework project

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/project-system#6649]
**Repro steps:**

1. Create a .NET Core WinForms application.
2. In Solution Explorer, select Form1.cs -> right click -> Properties
3. Expand and observe the dropdown list of values for Build Action property in Properties window. This list of values is different as compared to that of a .NET Framework project. Is that expected ?
4. Select another value for Build Action property and observe that Form icon gets lost on Form1.cs node

(Note that on setting Build property value back to 'C# Compiler', the Form icon comes back, which works fine.)

![87025699-4e2a9b80-c20d-11ea-9ec1-6447407e456a](https://user-images.githubusercontent.com/24871676/94959994-f9628e00-04a6-11eb-8fa7-80f4d2acaeca.gif)

**Expected Behavior:**

The values in Build Action property are same with .NET Framework project, and the Form icon should be displayed correctly on Form1.cs node after the value changed in Build Action property.

![image](https://user-images.githubusercontent.com/24871676/94960103-1d25d400-04a7-11eb-87db-8fe680b7ae44.png)

![image](https://user-images.githubusercontent.com/24871676/94960129-27e06900-04a7-11eb-835d-484b0c5abed8.png)

**Comment by davkean** [comment]
@lifengl Is there a way for us via rules to throw away SubType on item type change?

**Comment by davkean** [comment]
On wait, I misinterpreted this bug. 

@Shyam-Gupta Why is the legacy behavior expected? This behavior in the new project system seems by design and is acting as expected.

**Comment by Shyam-Gupta** [comment]
@davkean: Our CTI team found this difference in behavior during testing.
Thanks for confirming that it is by design in the new project system. Closing this bug.
