### ISSUE TITLE
Visual Studio 2019 - Breakpoint will not hit and showing source code different from entirely different project

### ISSUE THREAD

**Issue by debayanmitra002-git** [dotnet/project-system#6657]
**Visual Studio Version**: VS 2019

**Summary**: I am working on a Microservice based solution where in my same VS 2019 solution I have multiple microservice APIs, one API Gateway and two ASP.NET MVC presentation layer project. VS solution is configured to run all the projects on startup. Everything was fine, till one day one of the presentation layer project's Startup.cs (MVC Project A) debug breakpoint will not hit.

On hovering it shows, "The breakpoint will currently not hit. A copy of Startup.cs was found in <MVCProjectB.dll>, but the current source code is different from the version built into <MVCProjectB.dll>".

Now the another MVC presentation project (MVC Project B) that I have, debugging works fine in its startup. Its weird why one MVC project debugging will not work stating source code is different in another MVC project. Also no source code modifications are done.

Tried the following. Got no luck:
1. Clean entire solution, rebuild
2. Delete breakpoints, clean and rebuild and then add breakpoints and run
3. Restarted machine, clean, rebuild
4. Deleted manually all Bin folder contents and clean again and rebuild
5. Closed VS, deleted ASP.NET temporary files and then restarted VS, clean and build

I am at wit's end as to why this would happen all of a sudden. This seems like a VS 2019 bug. But any solution or workaround will help.

**Steps to Reproduce**:

1. Added 3 microservices, 1 API Gateway project and 2 MVC projects to one solution

2. All projects are configured as startup projects in sequence.

3. Run F5 on local to start debugging application

**Expected Behavior**:
Debuggers should hit on all projects

**Actual Behavior**:
One of the project breakpoint is not hit

**User Impact**:
The debugging issue is blocking me to test a critical piece,

**Comment by jjmew** [comment]
@debayanmitra002-git is this a .NET Core project or .NET Framework?

**Comment by debayanmitra002-git** [comment]
All projects are listed above in the issue are .NET Core projects
