### ISSUE TITLE
Unsupported MyApplication Properties removed from Application.Designer.VB

### ISSUE THREAD

**Issue by paul1956** [dotnet/project-system#6659]
**Visual Studio Version**:
Version 16.8.0 Preview 3.2

**Summary**:
There are properties in MyApplication like MinimumSplashScreenDisplayTime that the VS UI does not (yet) support that need to be set manually in Application.Designer.VB, this was also true in Framework.

**Steps to Reproduce**:

1. Add Me.MinimumSplashScreenDisplayTime  = 5000 to Sub New in Application.Designer.VB
2. Update something (for example IsSingleInstance) in VS UI
3. Rebuild 

**Expected Behavior**:
The line Me.MinimumSplashScreenDisplayTime  = 5000 is not modified
**Actual Behavior**:
The line Me.MinimumSplashScreenDisplayTime  = 5000 is deleted 
**User Impact**:
Application works differently under .Net then it did under Framework. MinimumSplashScreenDisplayTime was not supported in Framework UI but VS just left it alone. There are a few other properties that might me an issue for someone but this is the only one that I have seen frequently used.

**Comment by ocallesp** [comment]
@melytc For this GitHub, do we need to add a new property MinimumSplashScreenDisplayTime  into the PP Application ?

**Comment by ocallesp** [comment]
This functionality was not implemented in the old property pages and implementing this requires a lot of work in the old project system. We should invest time implementing this in the new property pages.

**Comment by melytc** [comment]
Pending work: validate that this does not happen in the new experience.

**Comment by melytc** [comment]
Update: this is still happening in the new experience. If the user manually sets a property in the Application.Designer.VB file without first saving it or rebuilding the project, the change will be lost.

One note is that this file is not supposed to be edited: it states in the header that it is auto generated, and changes should come from the Project Properties. So, to fix this bug, the correct approach should be adding the properties to the UI, so a user is not in the need to change this file.

Hence, this would be fix by the issue #8286 .
