### ISSUE TITLE
Audit TargetFramework usage for .NET 5 TFM change

### ISSUE THREAD

**Issue by sfoslund** [dotnet/project-system#6666]
With .NET 5 we are changing target framework from the netcoreappX.X style to netX.X. With this change, it appears this repo has code that could possibly break. Please check out https://github.com/dotnet/project-system/blob/master/build/import/Coverage.targets#L8 to ensure that this logic works as intended for .NET 5 TFMs, noting that $(TargetFramework.StartsWith('netcoreapp')) will no longer be true with net5.0, thanks!

**Comment by jjmew** [comment]
@dmonroym Do we need to update our infra?

**Comment by davkean** [comment]
Nope, this is dead code and will never be hit, even after this the condition still works with the new names.
