### ISSUE TITLE
Dependency node has warning icon when you reference the same reference twice

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#6668]
**Visual Studio Version**:

**Summary**:
By default File -> New -> Web Application (.NET Framework) references the same assembly twice. Both Legacy and MSBuild do not complain about this, however, CPS does:

![image](https://user-images.githubusercontent.com/1103906/95693816-07b86300-0c7a-11eb-8ee4-390a88339bbc.png)

**Steps to Reproduce**:

(Project is: https://github.com/davkean/AspNet/tree/main/src).

``` XML
    <Reference Include="Microsoft.Web.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <Private>True</Private>
      <HintPath>..\..\packages\Microsoft.Web.Infrastructure.1.0.0.0\lib\net40\Microsoft.Web.Infrastructure.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Web.Infrastructure">
      <HintPath>..\..\packages\Microsoft.Web.Infrastructure.1.0.0.0\lib\net40\Microsoft.Web.Infrastructure.dll</HintPath>
    </Reference>
```

**Expected Behavior**:
No warning

**Actual Behavior**:
Warning

**User Impact**:

**Comment by drewnoakes** [comment]
@davkean I couldn't find the above references in your repo. I also couldn't recreate this state via File -> New -> Web Application (.NET Framework). Can you help me verify whether this has been addressed with the rewrite?

**Comment by drewnoakes** [comment]
I believe this was fixed in the rewrite. I fixed a bug where differing case of dependencies led to issues. I never could get the repro given here to work, but a very similar one was fixed, so I'm closing this.
