### ISSUE TITLE
net5.0 platform not displayed in dependencies tree

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/project-system#6674]
**Visual Studio Version**: 16.9.0 Preview 1.0 [30612.141.main]

**Summary**:
When loading up a project that has a TFM of `net5.0-windows10.0.19041`, VS only shows `net5.0` in the project's dependencies list. This is confusing since there could be multiple net5.0-based TFM's.

**Steps to Reproduce**:

1. Use a TFM of `net5.0-windows10.0.19041`

2. 

3. 

**Expected Behavior**:
VS should show `net5.0-windows10.0.19041`

**Actual Behavior**:
VS shows `net5.0`

![image](https://user-images.githubusercontent.com/1427284/95908001-65c47380-0d6a-11eb-8255-13a9cb8fda9a.png)

**User Impact**:
Confusion

**Comment by drewnoakes** [comment]
This is a bug, and it's fixed by @swesonga's PR #6712.
