### ISSUE TITLE
Test new property pages for GB18030 compliance. (1)

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6705]
While we're working on the new property pages we should test them for GB18030 compliance. Here are a few scenarios to consider. Note these are examples, not an exhaustive list.

1. Check that the following all display properly when using characters covered by the standard:
    1. Page names
    2. Category names
    3. Property names
    4. Descriptions
    5. Property values
2. Check that setting a property to a value using characters covered by the standard round-trips properly: i.e., you can input it, save it properly to the backing file (project file, launchSettings.json, code, etc.) and see it displayed property later when it has been read from the backing file.
3. Check that we can search for pages, categories, properties, descriptions, etc. containing the relevant characters and get the expected filtering and highlighting.

**Comment by cartermp** [comment]
Next year's review will make this important - we won't be able to ship the new experience without passing this review.

**Comment by melytc** [comment]
Triage note: @jjmew is there a vendor already doing this kind of testing? If so, we could benefit from their experience on this one.

**Comment by jjmew** [comment]
@melytc  I believe @richaverma1 's team has done it before

**Comment by richaverma1** [comment]
@melytc, @jjmew new properties pages have been covered in the recent GB18030 pass we did. The validation steps mentioned in this bug are good and I have noted them down for the next pass in case something was missed.

**Comment by MiYanni** [comment]
The testing has been completed. Documents here:
- [DevDiv - GB18030 Test Report - 2021 - .NET Project Property Pages.docx](https://microsoft.sharepoint.com/:w:/t/VSTactics/Edl9GnLOrsxIr02EmFhiUVUBf3ECafVQ7w_N4UpbZbQGXw?e=MVPjnS&xsdata=MDN8MDF8fDJhZDE4MTZhODE0MzQ5OGY4NGRjMDI1ODljZDBjNDJhfDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDF8MHw2Mzc2MjQxMzA2MDYxOTk1OTB8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaUlpd2lRVTRpT2lJaUxDSlhWQ0k2TVRKOQ%3D%3D&sdata=bUxLbnpmWk9Jb0l1bHRmd3A4dnM3MFExOHJxbGo0c1NncWRoUkpOc0M5Yz0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cmiyanni%40microsoft.com)
- [DevDiv - GB18030 Test Report - 2021 - .NET Launch Profiles UI.docx](https://microsoft.sharepoint.com/:w:/t/VSTactics/ETx_Bdyf4t5JtHIhGTzdE-gBmD3JNXBxkFWdIFCMyrqP_g?e=2SDYPR&xsdata=MDN8MDF8fDJhZDE4MTZhODE0MzQ5OGY4NGRjMDI1ODljZDBjNDJhfDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDF8MHw2Mzc2MjQxMzA2MDYxOTk1OTB8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaUlpd2lRVTRpT2lJaUxDSlhWQ0k2TVRKOQ%3D%3D&sdata=K1cxZXJ2UTY0S1J6blhaTS9xTU9FWlVmSlkrRWQ2SFJKbmhBNnpmcklYZz0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cmiyanni%40microsoft.com)
