### ISSUE TITLE
VS should not bloat SDK project files with resx designer entries

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/project-system#6728]
Copying from winforms repo https://github.com/dotnet/winforms/issues/4144

(Copied from https://developercommunity2.visualstudio.com/myfeedback?port=1025&fsid=9bbd6d1d-30dd-4380-b94e-af5035a8459d&entry=myfeedback where I was told to report this here instead)

With the new SDK file format, my team was excited to say goodbye to bloated csproj files using the new globbing feature. For example, to include resx files we use the following glob:

```xml
<!--Configure .resx files as embedded resources with generated . Designer.cs files.-->
<ItemGroup>
  <Compile Update="**\*. Designer.cs">
    <AutoGen>True</AutoGen>
    <DesignTime>True</DesignTime>
    <DependentUpon>$([System.String]::Copy('%(FileName)'). Replace('. Designer', '.resx'))</DependentUpon>
  </Compile>
  <EmbeddedResource Update="**\*.resx">
    <Generator>ResXFileCodeGenerator</Generator>
    <LastGenOutput>$([System.String]::Copy('%(FileName)')). Designer.cs</LastGenOutput>
  </EmbeddedResource>
</ItemGroup>
```

Unfortunately, when we add new resx files to the project VS insists on still adding an entry for each designer file like:

```xml
<Compile Update="Globalization\TestResx.Designer.cs">
  <DesignTime>True</DesignTime>
  <AutoGen>True</AutoGen>
  <DependentUpon>TestResx.resx</DependentUpon>
</Compile>
```

It would be great if VS could handle this more gracefully, either by detecting that the designer file is already getting configured in the same way or by emitting a single glob entry that covers all similar designers if one is not already present (not sure how feasible the latter is if you have multiple kinds of designer files).

**Comment by jjmew** [comment]
This has been moved to an internal database #AB1255781 (https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1255781)

**Comment by Kaelum** [comment]
@jjmew what is the status of this.  I looked at the [dotnet / winforms](https://github.com/dotnet/winforms) source of the .NET 5.0 release branch, and it looks like those projects are using this feature.  However, I can't find any documentation on how to use it.

**Comment by drewnoakes** [comment]
The internal issue was triaged by the team that owns this feature and they closed it as "won't fix". If this scenario is important to you I recommend searching for an existing feedback ticker, or creating a new one, and linking it here so that others can vote on it. As it stands, the fix does not belong in this repo and so this issue will not gain any traction. A feedback ticket is more likely to attract that attention. Closing this for now.
