### ISSUE TITLE
Github checks are marked as Succeeded, but the build log has errors

### ISSUE THREAD

**Issue by ocallesp** [dotnet/project-system#6729]
**Summary**:

![image](https://user-images.githubusercontent.com/510598/97950492-dfd59000-1d4b-11eb-8110-24e792c1820b.png)

![image](https://user-images.githubusercontent.com/510598/97950709-a94c4500-1d4c-11eb-8663-5f62f1a27625.png)

![image](https://user-images.githubusercontent.com/510598/97950564-1f9c7780-1d4c-11eb-8f47-0b0792df2333.png)

**Expected Behavior**:
The build/test should be marked as Failed when there are build errors or failed unit-tests

**Actual Behavior**:
The build/test is marked as succeeded when there are build errors

This was detected in the pr https://github.com/dotnet/project-system/pull/6692

**Comment by davkean** [comment]
Can you show an example build? The latest build on that PR has zero errors.

**Comment by ocallesp** [comment]
@davkean yes, that last build had one more commit.

@dmonroym should we close this issue ?

**Comment by dmonroym** [comment]
That's an issue for AzDo but don't think it's worth looking into, I will close this
