### ISSUE TITLE
Build considers project "up-to-date" despite failed post-build event

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6733]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Build-considers-project-up-to-date-despi/1179089). Please vote and comment there to make sure your voice is heard._

---
[severity:It's more difficult to complete my work]
When a post-build task fails (nonzero exit code), Visual Studio still considers the project "up-to-date" the next time the project is built/run.
This leaves the build output in an incomplete state, since the post-build task is never completed successfully.

### Steps to reproduce:
- Create new project (for example console application)
- Add the following command line as post-build event: `exit /b 1`
- Build the project (F6) -> build fails, build error is displayed
- Build the project (F6) again -> build succeeds, project is considered "up to date"

### Expected result:
- Build should fail each time, because the post-build task fails each time

### Additional observations:
- It doesn't matter whether the failing post-build task is defined as command line in `<PostBuildEvent>` or as an `Exec` task in `<Target Name="AfterBuild">`

### Possible workarounds:
- Disable "up-to-date" check (add `<DisableFastUpToDateCheck>True</DisableFastUpToDateCheck>`)  
  -> This causes the project and all dependent projects to be rebuilt every single time, slowing down work considerably.
- Add custom retry logic for post-build task, ensuring eventual success  
  -> Only works for cases, where post-build task may fail occasionally due to temporary issues.  
  -> Doesn't work for cases where post-build task fails consistently for a given build output.
- Add custom error handling in post-build task to force next build to not be considered "up-to-date"?  
  -> I'm currently investigating this option. (Trying to trigger some sort of change to the project source when the post-build task fails, so that the project won't be considered "up-to-date").

---
#### Christian Vogel on 9/9/2020, 06:54 AM: 

<p>A quick update regarding the custom error handling workaround I mentioned.</p><p>I changed the post-build task to the following command line:</p><pre>someaction "$(TargetPath)"
if %errorlevel% neq 0 goto error

exit /b 0
:error
echo Post-build task FAILED, touching $(ProjectExt) file to trigger rebuild.
copy /b "$(ProjectPath)" +,,
exit /b 1<br></pre><p>This (undocumented) use of the `copy` command causes the project file to be "touched" (last modified time updated) if the post-build action fails (represented by `someaction`).</p><p>Definitely not happy with this kind of bulky and cumbersome workaround, but it's probably the best we can get until this issue is fixed...</p>

#### Christian Vogel on 9/9/2020, 09:38 AM: 

<p>Okay, so the workaround described in the comment above only seems to work for certain project types...</p><p>It worked for a <i>.NET Core Console App</i> project that I used for testing, but did NOT work for <em>.NET Framework Console App</em> and <i>.NET Framework WPF App</i> projects (where I actually need this to work).</p><p>I'm not quite sure what the reason is, because touching the project file outside the build process does trigger a rebuild.</p><p>I have found another solution for those project types however:</p><pre>someaction "$(TargetPath)"
if %errorlevel% neq 0 goto error

exit /b 0
:error
echo Post-build task FAILED, updating rebuild trigger file.
echo.&gt; "$(ProjectDir)rebuild.trigger"
exit /b 1<br></pre><p>For this to work, an empty `rebuild.trigger` file must be added to the project with build action "None".</p>

#### Feedback Bot on 9/9/2020, 07:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/4/2020, 02:19 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by drewnoakes** [comment]
I do not see any actionable work item here, so will close this. The system is working as designed, and a reasonable workaround exists.
