### ISSUE TITLE
Rebuilding the project system generates a CreatePkgDef error when creating the VSIX for ProjectSystem.Managed.VS

### ISSUE THREAD

**Issue by RobertvanderHulst** [dotnet/project-system#6744]
**Visual Studio Version**:
16.8

**Summary**:
Rebuilding the project system generates a CreatePkgDef error when creating the VSIX for ProjectSystem.Managed.VS

**Steps to Reproduce**:

1. Clone the repo
2. Build the repo with build.cmd. (The same problem also happens inside VS)

**Expected Behavior**:
Successfull build

**Actual Behavior**:
Error messages:
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : CreatePkgDef : error : ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the
LoaderExceptions property for more information. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.Projec
tSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) [C:\XSharp\Other\ProjectSystem\Roslyn\src\Micro
soft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 :    at System.Reflection.RuntimeModule.GetTypes() [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.Pr
ojectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 :    at System.Reflection.Assembly.GetTypes() [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.Project
System.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 :    at Microsoft.VisualStudio.Tools.CreatePkgDef.ProcessAssembly(String fileName, Hive hive, PkgDefContext context, B
oolean register, RegistrationMode mode) [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.ProjectSystem.
Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 :    at Microsoft.VisualStudio.Tools.CreatePkgDef.DoCreatePkgDef(InputArguments inputArguments) [C:\XSharp\Other\Proje
ctSystem\Roslyn\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csp
roj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 :    at Microsoft.VisualStudio.Tools.CreatePkgDef.Main(String[] arguments) [C:\XSharp\Other\ProjectSystem\Roslyn\src\M
icrosoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetLoggersAsync' in type 'Microsoft.VisualStudio.Telemetry.DesignTimeTelemetryLoggerProvider' from assembly
'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35
' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.ProjectSystem.Manag
ed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Commands.HideAddRe
ferenceCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, P
ublicKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.Vi
sualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Commands.NavigateT
oProjectCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral,
PublicKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.V
isualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatus' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Commands.ReferenceManag
erCommandHandler' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral,
 PublicKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.
VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Commands.SuppressO
bjectBrowserForPackageReferenceCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.4
2.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem
\Roslyn\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.BrowseToDependencyInE
xplorerCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, P
ublicKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.Vi
sualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.ExploreDependencyFold
erInWindowsCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutra
l, PublicKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsof
t.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.GenerateNuGetPackageP
rojectContextMenuCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=
neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Mi
crosoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.GenerateNuGetPackageT
opLevelBuildMenuCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=n
eutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Mic
rosoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.OpenProjectDesignerCo
mmand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyT
oken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudi
o.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.OpenProjectDesignerOn
DefaultActionCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neut
ral, PublicKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Micros
oft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.VS2kAddItemCommandHan
dler' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyTo
ken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio
.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.VS97AddItemCommandHan
dler' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyTo
ken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio
.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.WPFAddItemCommandHand
ler' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyTok
en=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.
ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.Ordering.AddExistingI
temAboveCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral,
PublicKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.V
isualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.Ordering.AddExistingI
temBelowCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral,
PublicKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.V
isualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.Ordering.AddExistingI
temCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, Publi
cKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.Visual
Studio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.Ordering.AddNewItemAb
oveCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, Publi
cKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.Visual
Studio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.Ordering.AddNewItemBe
lowCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, Publi
cKeyToken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.Visual
Studio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.Ordering.AddNewItemCo
mmand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyT
oken=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudi
o.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.Ordering.MoveDownComm
and' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyTok
en=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.
ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.Ordering.MoveUpComman
d' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyToken
=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.Pr
ojectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'HintedAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Input.Commands.Ordering.OrderAddItemHintReceiv
er' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyToke
n=31bf3856ad364e35' does not have an implementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.P
rojectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'UIHierarchyWindowCommandSetGroupHandler' from assembly 'Microsoft.VisualStud
io.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an im
plementation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.Visua
lStudio.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 : Method 'GetCommandStatusAsync' in type 'StandardCommandSet97GroupHandler' from assembly 'Microsoft.VisualStudio.Proj
ectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implement
ation. [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio
.ProjectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 :  [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.Pr
ojectSystem.Managed.VS.csproj]
C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\tools\vssdk\Microsoft.VsSDK.targets(1140,5): error
 :  [C:\XSharp\Other\ProjectSystem\Roslyn\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.Pr
ojectSystem.Managed.VS.csproj]

**User Impact**:
Cannot build and test the project system sourcecode

**Comment by drewnoakes** [comment]
Based on `microsoft.vssdk.buildtools\16.7.3069` it seems that package restore failed. This repo is using 16.8.1015 (bumped in #6745 to 16.9.1025).

**Comment by RobertvanderHulst** [comment]
I have now switched to the latest commit and it indeed has buildtools version 16.8.1015. 
I then did a build /rebuild but I am still seeing the same error...

**Comment by RobertvanderHulst** [comment]
I have tried it with both a VS 2019 16.8 command prompt and a 16.9 (preview 1) command prompt and they both have the same problem.

**Comment by drewnoakes** [comment]
Are you able to build inside VS?

**Comment by RobertvanderHulst** [comment]
No, inside VS I also get a CreakePkgDef error.
I see the message that several methods do not have an implementation:
```
2>C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.9.1025\tools\vssdk\Microsoft.VsSDK.targets(1149,5): error : Method 'GetLoggersAsync' in type 'Microsoft.VisualStudio.Telemetry.DesignTimeTelemetryLoggerProvider' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
2>C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.9.1025\tools\vssdk\Microsoft.VsSDK.targets(1149,5): error : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Commands.HideAddReferenceCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
2>C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.9.1025\tools\vssdk\Microsoft.VsSDK.targets(1149,5): error : Method 'GetCommandStatusAsync' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Commands.NavigateToProjectCommand' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
2>C:\Users\robert\.nuget\packages\microsoft.vssdk.buildtools\16.9.1025\tools\vssdk\Microsoft.VsSDK.targets(1149,5): error : Method 'GetCommandStatus' in type 'Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.Commands.ReferenceManagerCommandHandler' from assembly 'Microsoft.VisualStudio.ProjectSystem.Managed.VS, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.

etc.
```

**Comment by RobertvanderHulst** [comment]
Do you have any news on this ?
I moved the code to a clean virtual machine with VS 2019 and when I build the code from the command line and also inside VS I still see the same CreatePkgDef error.

**Comment by RobertvanderHulst** [comment]
I have checked out revision dev16.7.x and with a small change (I had to add a line with #nullable disable) this compiles and runs.
For now this is OK for me, but I think you will have to look into this. I am sure that I will not be the only one with this problem.

**Comment by jjmew** [comment]
@dmonroym can you sync up with @MiYanni to see what we could do to enable the better support for the community when it comes to our repo?

**Comment by MiYanni** [comment]
@RobertvanderHulst I've merged a change that restricts the version of VS used for `build.cmd` to be the minimum version of VS we actually set the DLL to build as. Meaning, the version we put in [Versions.props](https://github.com/dotnet/project-system/blob/255bc15b422bdc5e10fbe0e93d481c020ff2193a/build/import/Versions.props#L4) is now the minimum version `build.cmd` uses. Can you check to see if you still have build issues? It should no longer be able to target `16.7.3069` build tools.

**Comment by RobertvanderHulst** [comment]
Michael,
Thanks for this. I have just tried to build it from a VS 2019 (16.8.4) and VS 2019 Preview (16.9.0 preview 3) command prompt and it works in both.
