### ISSUE TITLE
Code highlighting should change depending on the active debug framework

### ISSUE THREAD

**Issue by foretold-tom** [dotnet/project-system#6755]
**Visual Studio Version**: 16.8.1

**Summary**:
When a particular target framework is chosen in the target framework selector menu, the code within an #if directive conditioned on that target framework version should be highlighted.

**Steps to Reproduce**:

1. Create a .Net project using the new SDK-style csproj file.
2. Change the `TargetFramework` property to `TargetFrameworks` and give it more than one TFM, such as `net45;net472`.
3. Write some C# code within 2 #if directive blocks (or use #elif, that is affected too), one for NET45 and one for NET472.
4. Select net472 from the target selector menu.
5. Observe that the code within the `#if NET45` block still has syntax highlighting and the code within the `#if NET472` block is still grayed out.

**Expected Behavior**:
The code within the `#if NET472` block should have syntax highlighting and the code within the `#if NET45` block should be grayed out.
**Actual Behavior**:
The code within the #if block of the first TFM in the `TargetFrameworks` property always has syntax highlighting and the code within other #if blocks is always grayed out, including that of the currently selected active debug framework.
**User Impact**:
Syntax highlighting is misleading to the developer if the currently selected target framework is not the first one in the list.

**Comment by davkean** [comment]
I see your confusion. That switcher controls the _launch target_, the syntax highlighting is based on the editor switch here:
![image](https://user-images.githubusercontent.com/1103906/99600887-68457780-2a52-11eb-9b74-2b6a3d0fc606.png)

It's a good suggestion that we keep these in sync.

**Comment by sharwell** [comment]
We've had a few other requests for this. The main problem with any expectation that these be kept in sync is it only holds for the startup project. In many cases, the requests have been giving examples where the startup project and the file open in the editor are not the same project, and may or may not have the same target frameworks available.
