### ISSUE TITLE
Redundant builds due to up-to-date check and Assembly.exe.config in SDK-style .NET Framework projects

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6758]
**Visual Studio Version**: Version 16.9.0 Preview 2.0 [30718.87.main]

**Steps to Reproduce**:

1. Create a project

   ```xml
   <Project Sdk="Microsoft.NET.Sdk">
     <PropertyGroup>
       <OutputType>Exe</OutputType>
       <TargetFramework>net48</TargetFramework>
     </PropertyGroup>
   </Project>
   ```

2. Build a few times. It should be up-to-date after the first build.
3. Modify `Program.cs`.
4. Build again twice. It should be up-to-date, but is not.

Builds are being run even though nothing has changed. The log output is:

```
Build started...
1>FastUpToDate: Adding UpToDateCheckBuilt outputs:
1>FastUpToDate:     'C:\repos\MyApp\MyApp\obj\Debug\net48\MyApp.pdb'
1>FastUpToDate:     'C:\repos\MyApp\MyApp\bin\Debug\net48\MyApp.exe'
1>FastUpToDate:     'C:\repos\MyApp\MyApp\bin\Debug\net48\MyApp.exe.config'
1>FastUpToDate:     'C:\repos\MyApp\MyApp\bin\Debug\net48\MyApp.pdb'
1>FastUpToDate:     'C:\repos\MyApp\MyApp\obj\Debug\net48\MyApp.exe'
1>FastUpToDate: Adding project file inputs:
1>FastUpToDate:     'C:\repos\MyApp\MyApp\MyApp.csproj'
1>FastUpToDate: Input 'C:\repos\MyApp\MyApp\MyApp.csproj' is newer (6/12/2021 4:40:22 PM) than earliest output 'C:\repos\MyApp\MyApp\bin\Debug\net48\MyApp.exe.config' (6/12/2021 2:21:18 PM), not up to date.
1>FastUpToDate: Up to date check completed in 1.3 ms```

The key part is:

> Input 'C:\repos\MyApp\MyApp\MyApp.csproj' is newer (6/12/2021 4:40:22 PM) than earliest output 'C:\repos\MyApp\MyApp\bin\Debug\net48\MyApp.exe.config' (6/12/2021 2:21:18 PM), not up to date.

Builds do not modify `MyApp.exe.config`. This file is considered an output due to a `BuildUpToDateCheckBuilt` item, and the Project System expects this file to change when a build occurs. Because it does not, we become stuck in a loop where the FUTD check fails.

**Comment by drewnoakes** [comment]
Note that if the projects target `netcoreapp3.1`/`netstandard2.1` then the problem does not occur. It seems specific to targeting .NET Framework with SDK style projects. The fix is likely in MSBuild or the SDK.

**Comment by drewnoakes** [comment]
The project does not have an `App.config` file, but an output file is generated all the same with content:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1" />
  </startup>
</configuration>
```

**Comment by drewnoakes** [comment]
A workaround is to add `<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>` to the project. However, disabling binding redirects may cause other problems, so this change should not be made without proper consideration.

**Comment by jerrys-msft** [comment]
I'm still seeing this issue in Visual Studio 2022 Version 17.0.0 Preview 4.1 😟

**Comment by drewnoakes** [comment]
The `UpToDateCheckBuilt` item involved here is created in:

https://github.com/dotnet/project-system/blob/735da2cd1125d49aece04d82a2eb900e0fd17da6/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L436-L441

The `AppConfig` property is empty, as shown by the `Original` property being empty too:

![image](https://user-images.githubusercontent.com/350947/144794226-d94f4916-bcfc-4028-9267-f7f1c997ab6f.png)

I think this item should be skipped when `AppConfig` is not defined.
