### ISSUE TITLE
TargetFramework combo box is empty when editing a netcore3.1 project and changing it to net472

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/project-system#6762]
If I create a netcoreapp3.1 project, and hand edit the project file to net472 the TargetFramework combo box on the project property pages is empty

![image](https://user-images.githubusercontent.com/5175830/99894602-46a6e480-2c3a-11eb-94e8-e6441491d339.png)

For the  TargetFramwork options only desktop framework options are available.

![image](https://user-images.githubusercontent.com/5175830/99894626-8241ae80-2c3a-11eb-8966-ba90a1149194.png)

This has also impacted The F# TargetFrameworkSelector.

**Comment by jjmew** [comment]
@KevinRansom what build were you using? we are not able to repro this out of main.

**Comment by KevinRansom** [comment]
Dog food 9 days ago.  Although I also just repro'd it on: 16.8.2

![image](https://user-images.githubusercontent.com/5175830/100807465-397eb800-33e7-11eb-8c28-872db27bc707.png)



Steps:
1. Create a new C# console app
2. Open project properties window
3  Select Edit Project to get the project file text editor
4.  Change project type to net48
5.  Observe selected tfm is blank
6.  Also observe target frameworks drop-down shows net 1.0 - net 5.0
7. Close project -reopen
8. Observe tfm says net4.8 and tfm drop down contains .NETFrameworks 3.5-4.8
9. Edit projectfile to target netcoreapp3.1
10.  Observe selected tfm is blank
11.  Also observe target frameworks drop-down shows net .NETFrameworks 3.5-4.8
The issue is that the tfm drop down is filtered based on the tfm for the project file, and doesn't reset until a project reload happens.

**Comment by jjmew** [comment]
We were able to reproduce it if we don't close the Properties Pages while manually changing the project file. If you close the Properties Pages then it reset to the right values. This is something that we don't plan on addressing  as we are re-writing the UI.
