### ISSUE TITLE
VSSDK003 Tool windows should support async construction - Shows up as Message in VS Error List

### ISSUE THREAD

**Issue by ericdyoon** [dotnet/project-system#6768]
**Visual Studio Version**:
16.8.0 Preview 1.0 [30314.82.master]

**Summary**:
Stretch Goal - **Low Priority**
- Will be a good feature to add eventually

The message - VSSDK003 Tool windows should support async construction,
shows up in the Error List (message severity).
Associated page for VSSDK003
https://github.com/Microsoft/VSSDK-Analyzers/blob/master/doc/VSSDK003.md

Output from the VS message:
Severity	Code	Description	Project	File	Line	Suppression State
Message	VSSDK003	Tool windows should support async construction	ProjectSystemTools	C:\Users\t-eriyoo\Git\project-system\src\ProjectSystemTools\ProjectSystemToolsPackage.cs	24	Active

**Steps to Reproduce**:

1.  Using the code from https://github.com/dotnet/project-system-tools
in src\ProjectSystemTools\ProjectSystemToolsPackage.cs on line 24
```
[ProvideToolWindow(typeof(BuildLoggingToolWindow), Style = VsDockStyle.Tabbed, Window = ToolWindowGuids.Outputwindow)]
[ProvideToolWindow(typeof(MessageListToolWindow), Style = VsDockStyle.Tabbed, Window = ToolWindowGuids.Outputwindow)]
```

2.  Line 24 tool window construction, when in the project-system repo, will have the VSSDK003 message

**Expected Behavior**:
This message does not show up in error list, and is resolved without suppressions

**Actual Behavior**:
Using suppressions right now to resolve the message, will link the number of this issue to the suppression comment in the source code.

**User Impact**:
project-system can support the new async tool window construction

**Comment by drewnoakes** [comment]
I transferred this to our repo and assigned it to myself for the bug bash. It's a simple VS startup performance win for users of Project System Tools. Any conflicts with @ericdyoon's work will be straightforward to resolve as the diff required to fix this issue is minimal.

**Comment by drewnoakes** [comment]
This was fixed in https://github.com/dotnet/project-system-tools/pull/392, specifically in https://github.com/dotnet/project-system-tools/pull/392/commits/2e3b898e10d031ac2ce8561d825782ff4c621dca.
