### ISSUE TITLE
Cannot change the Startup Form in a .NET 5 WinForms Application Framework VB App.

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/project-system#6787]
**Visual Studio Version**:
\>=16.8

**Summary**:
In a .NET 5 WinForms Application Framework App, the Startup Form cannot be change via the UI. The changes are getting written to the wrong destination file.

**Steps to Reproduce**:

1. Create a new .NET 5 Visual Basic WinForms App.
2. Add a second Form to the project.
3. Go to the Project Designer, and change the existing "Sub Main" (which is the wrong type of start-object to begin with) to "Form2"

**Expected Behavior**:
The App should start by showing Form2 through the Infrastructure of the Application Framework.

**Actual Behavior**:
The App bypasses the Application-Framework and all its settings and infrastructure. However it shows Form2 directly.

**User Impact**:
* No HighDPI-Settings get applied.
* The App is using an old version of comctl, since Visual Styles are not enabled.
* No Application-Events get invoked., which breaks most apps because critical infrastructure parts get omitted.

The reason for this is, that in VB with the application framework enabled, the `<StartObject>` tag in the vbproj _always_ needs to be `Sub Main`. Rather, when changing the start Form, Project System _only_ needs to change _Application.myapp_ for the correct start form, which is correctly does!
 
For Application Framework apps, the Start-Object List should _only_ show the available Forms.

This is in addition to #6608.

**Comment by paul1956** [comment]
This happens with Default Form (Form1) if you change away from Sub Main as your Startup Form. Also startup form is not shown.  This whole thing is very confusing, I think you are saying Sub Main should not be listed in DropDown when there are VB Forms and the selected Form should be Form1, or whatever you want the first form to be.

**Comment by KlausLoeffelmann** [comment]
@melytc: Maybe we want to talk with @KathleenDollard about tackling this, also? I for one would love to be involved in any discussions around this. :-)

**Comment by paul1956** [comment]
@melytc @KathleenDollard Me as well, there is too much hidden stuff going on and it is easy to break an application with no idea why. I don't mind the hidden stuff it is great for new developers but when things break these same developers are really frustrated.

**Comment by melytc** [comment]
@KlausLoeffelmann @KathleenDollard @paul1956 sure thing! I plan to schedule a discussion when we come back from vacations, in the meantime I'll investigate what's the current state from our side.

Btw, thanks for the great description, Klaus! Found it helpful.

**Comment by melytc** [comment]
Part of the issue has been fixed; the dropdown shows and is able to select the different valid entries:
![image](https://user-images.githubusercontent.com/8518253/164293348-27babfb8-9c09-41b8-aa2d-94cf6dbd2abc.png)
However, it seems like the correct place to store the value is in the myapp file (`<MainForm>` property) instead of the project file (`<StartupObject>` property).

**Comment by melytc** [comment]
@ocallesp I actually think this is handled by us in  MS.VS.Editors.MyApplication and it's a high impact bug that needs a fix.

**Comment by KlausLoeffelmann** [comment]
(Don't get confused by Application Framework. This is still .NET! Not .NET Framework! Application Framework is the name of the VB technology, and it's true for .NET Framework and .NET! 😄)

**Comment by KlausLoeffelmann** [comment]
@melytc, I'd suggest we close this when the migration to the WPF AppDesigner pages is done for VB.NET Application Framework projects?

**Comment by melytc** [comment]
This is being fixed in the new Project Properties UI, where the correct values are shown and they are saved in their correct destination, either the project file or the myapp file: https://github.com/dotnet/project-system/pull/8355
