### ISSUE TITLE
Project editor should allow editing of CodeAnalysisTreatWarningsAsErrors

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6793]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Project-editor-should-allow-editing-of-C/1266567)._

---
[regression] [worked-in:16.7]
VS 2019 16.8 added a new default flag to csproj files "CodeAnalysisTreatWarningsAsErrors" and defaulted it to "ON". Existing CSPROJ files did not include that flag so the default (true) was assumed by the compiler. So all Code Analysis warnings were suddenly compile errors. 
 Not a nice surprise.  Not documented. 

Also, there's nothing in Visual Studio to insert or alter that new flag.  I reported the issue in the preview and was asked questions about whether we were using FxCop analyzers or something else. My questions about how this new flag interacted with the existing TreatWarningsAsErrors flag weren't answered.  When 16.8 went live a lot of people had this problem and someone finally managed to explain what was happening. 

However I still don't see any way to edit that flag in Visual Studio 2019 16.8.2 or 16.9 preview.  The only way to "fix" this was to manually edit all CSPROJ files to add a line "<CodeAnalysisTreatWarningsAsErrors>False</CodeAnalysisTreatWarningsAsErrors>" to each build type in existing CSPROJ files. 

Can whoever made the decision to force this new rule add a way to update the CSPROJ files with the new flag, and to insert it into existing CSPROJ files that don't include it? 

Thank you

(Personally I'm all in favor of treating all warnings as errors and any project I've started in the last 25 years has included that as part of the configuration, but when you make a change like that a little information would make it easier to fix.)

---
#### Feedback Bot on 11/23/2020, 10:43 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by drewnoakes** [comment]
We were tracking this in #6720. I've added it as an explicit item under _MSBuild "warnings as errors" properties_.

**Comment by drewnoakes** [comment]
cc @mavasani who authored the original "Code Analysis" page within the legacy property pages.

**Comment by drewnoakes** [comment]
@jinujoseph there are two aspects to this issue:

1. The breaking change of defaulting `CodeAnalysisTreatWarningsAsErrors` to `true` in 16.8, meaning upgrading VS may cause projects to not build.
2. The fact that there's no UI element to control this property.

We will track point 2 in this repo. However point 1 seems like a pain point that should be addressed via warning waves, or something like that. Are you tracking that feedback, or has there been a decision made around this?

**Comment by mavasani** [comment]
> The breaking change of defaulting CodeAnalysisTreatWarningsAsErrors to true in 16.8, meaning upgrading VS may cause projects to not build.

This has already been fixed in 16.9. Note that this was not ported to 16.8 as it only affects legacy FxCop based CodeAnalysis, which has been deprecated for over a year, but customers still keep using it. This is not a breaking change for users on Roslyn based source analyzers.

> The fact that there's no UI element to control this property.

This seems like a good addition to the .NET Analyzers section within CodeAnalysis property page that @jmarolf recently added.

**Comment by mavasani** [comment]
See https://developercommunity2.visualstudio.com/t/After-168-update-getting-lot-of-code-an/1251574?preview=true#T-N1255914 for the 16.8 breaking change regression.

**Comment by drewnoakes** [comment]
Moved to #7557.
