### ISSUE TITLE
Enabling new Project Properties UI breaks properties editor for legacy projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6794]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Updated-Project-Properties-UI-not-workin/1287500). Please vote and comment there to make sure your voice is heard._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.9.0 Preview 1.0]

Creating a new project and trying to open the properties does nothing. This works just fine if Updated Project Properties UI is disabled, but as long as it's enabled, I'm unable to pull up properties for any project.

**Comment by jjmew** [comment]
@drewnoakes The complain is that when you enable the new property pages then when you try to open the properties .NET Framework projects it fails. The expectation is that everything csproj continues to work with the old property pages.

**Comment by drewnoakes** [comment]
@jjme thanks, I'll get this fixed. A workaround until then is to disable the feature flag.

**Comment by drewnoakes** [comment]
We currently use this method to determine whether to launch the new property pages or not:

https://github.com/dotnet/project-system/blob/bd03c9b40f8f4fbf2571af9ef3d7cf8d8b2f3d8d/src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerEditorFactory.vb#L228-L234

In addition to testing the feature flag, we need to detect whether the project is using the legacy project system or not.

**Comment by drewnoakes** [comment]
Testing for the `CPS` project capability seems like a good way of doing this.
