### ISSUE TITLE
Property pages client/server protocol design discussion

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6797]
In this week's Property Pages meeting, we discussed designs for how the server could notify the client of changes to property values.

Currently, we use the Project Query API to obtain property metadata and values. The Project Query API does not yet have a mechanism for transmitting value updates over time. It seems we need an additional service contract between client and server for such updates.

The current interaction model is request/response (RPC), unidirectionally from client to server. To update properties at arbitrary points in time we will need a richer model. The server needs a mechanism to invoke actions against the client. It also needs to know when the client editor is closed, so that it can stop sending updates and clean up resources.

While the client can keep using the Project Query API for some actions and use another new interface for update notifications, this splits our interaction across two systems. I am in favour of having a single channel for communication between server and client.

Benefits of a single channel as I see it:

- No race conditions when connecting between the initial snapshot and subsequent updates. With two channels, a client may either miss an update that occurs while the snapshot is in flight, or may receive an update before the initial snapshot is received. Both scenarios can leave the client out of sync.
- The API exposed to the client has a higher level of abstraction, which grants the server more flexibility for optimising the implementation. For example:
  - The server could maintain a copy of the data previously sent to the client, and use that to produce diffs over time in order to send the minimal set of updates, while guaranteeing correctness and synchronicity.
  - The server may cache resources while a session is active, and release them when the session is closed.
- The interface becomes private, meaning versioning is easier. The Project Query API model is public so evolving must only be additive. This proposed contract would exist entirely within CPS and therefore can change freely. For example:
  - We can refactor the interfaces in future to support launch profiles.
  - If it turns out we need to introduce data versions in order to address race conditions, we own the entire contract and can do that.
- We can avoid notifying the client of its own changes, as the server will know which client made the change.

Below is an initial proposal showing how that API might look. There are three interfaces.

1. `IPropertyEditorServer` which the server proffers, with a single `ConnectAsync` method.
1. `IPropertyEditorConnection` which represents the server connection from the client's perspective, allowing the client to update values via the sever, and to disconnect when no longer needed.
1. `IPropertyEditorClientSession` which the client passes to the server when it connects, and via which the server may communicate with the client.

```c#
/// <summary>
/// The server's property editor endpoint. Clients connect via this.
/// </summary>
internal interface IPropertyEditorServer
{
    /// <summary>
    /// Initiates an client editor's session with the server.
    /// </summary>
    Task<IPropertyEditorConnection> ConnectAsync(
        Guid projectGuid,
        IPropertyEditorClientSession session
        CancellationToken token);
}

/// <summary>
/// Connection object provided to a property editor client, via which a client may update properties.
/// </summary>
/// <remarks>
/// Must be disposed when the connection is no longer required.
/// </remarks>
internal interface IPropertyEditorConnection : IAsyncDisposable
{
    /// <summary>
    /// Requests a change to one or more evaluated values of one or more properties.
    /// </summary>
    /// <returns>
    /// Updated values for any modified properties.
    /// </returns>
    // TODO decide whether the server should include requested changes, or only incidental changes
    Task<ImmutableArray<PropertyUpdate>> SetEvaluatedValueAsync(
    	ImmutableArray<EvaluatedValueChangeRequest> values);
    
    /// <summary>
    /// Requests a change to one or more unevaluated values of one or more properties.
    /// </summary>
    /// <returns>
    /// Updated values for any modified properties.
    /// </returns>
    // TODO decide whether the server should include requested changes, or only incidental changes
    Task<ImmutableArray<PropertyUpdate>> SetUnevaluatedValueAsync(
    	ImmutableArray<UnevaluatedValueChangeRequest> values);
}

/// <summary>
/// Proferred by the client, for notifications from the server.
/// </summary>
internal interface IPropertyEditorClientSession
{
    /// <summary>
    /// Provides an editor client with the initial snapshot of properties, including all metadata and values.
    /// </summary>
    Task ReceivePropertiesAsync(
    	ImmutableArray<Property> properties);

    /// <summary>
    /// Notifies an editor client of a change to the values of one or more properties.
    /// </summary>
    Task ReceivePropertyUpdatesAsync(
    	ImmutableArray<PropertyUpdate> propertyUpdates);

    /// <summary>
    /// Instructs the client that the server is shutting down.
    /// </summary>
    /// <remarks>
    /// The client may update its UI to be read-only.
    /// </remarks>
    // TODO there is likely a built-in mechanism for client awareness of server availability
    Task NotifyServerShuttingDownAsync();
}
```

These interfaces reference a few data transfer objects (DTOs), most of which are already defined in the client. We would move these to be available to both the client and server, so they may exchange them.

```c#
internal sealed record Page(
    string Name,
    string DisplayName);

internal sealed record Category(
    string Name,
    string DisplayName);

internal sealed record PropertyEditor(
    string Name,
    ImmutableDictionary<string, string> Metadata);

internal sealed record PropertyMetadata(
    string Name,
    string DisplayName,
    Page Page,
    Category Category,
    string? DependsOn,
    string? Description,
    int Priority,
    PropertyEditor Editor,
    ImmutableDictionary<string, string> EditorMetadata,
    bool SupportsPerConfigurationValues,
    string? SearchTerms,
    string? HelpUrl,
    string? VisibilityCondition);

internal sealed record SupportedValue(
    string DisplayName,
    object Value);

internal sealed record PropertyValue(
    ImmutableDictionary<string, string> Configuration,
    string UnevaluatedValue,
    object EvaluatedValue,
    ImmutableArray<SupportedValue> SupportedValues);

internal sealed record Property(
    PropertyMetadata Metadata,
    ImmutableArray<PropertyValue> Values);

internal sealed record PropertyUpdate(
    string PageName,
    string PropertyName,
    ImmutableArray<PropertyValue> Values);

internal sealed record EvaluatedValueChangeRequest(
    string PageName,
    string PropertyName,
    ImmutableDictionary<string, string> Configuration,
    object EvaluatedValue);

internal sealed record UnevaluatedValueChangeRequest(
    string PageName,
    string PropertyName,
    ImmutableDictionary<string, string> Configuration,
    string UnevaluatedValue);
```

**Comment by tmeschter** [comment]
The more I think about this, the more I like it.

The Project Query API is a general purpose API, capable of expressing requests of many different shapes. But the property pages only need data in two shapes: first, a complete set of page, category, and property metadata along with the current property values; and second, a set of updated property values. So the generality of the Project Query API isn't providing any value to the new property pages UI, but our server-side implementation of the API expends a lot of code supporting that generality. For example, we have a lot of code that generates, deconstructs, and otherwise manages entity IDs--but we don't really need any of that for the property page UI.

The Codespace-compatible version of those interfaces would be a little different, but not much--notably, we probably wouldn't need `IPropertyEditorServer`; instead you would use `IServiceBroker` to request the `IPropertyEditorConnection` service, with the project GUID and `IPropertyEditorClientSession` being passed in as request options.

**Comment by drewnoakes** [comment]
I'm sure the interfaces would change a little to fit the Codespaces client/server requirements, but the general pattern here seems reasonable to me.

Adapting to this would likely take a day or two for the client-side. I can imagine there's more work on the server to support this.

I'm all for taking this approach. We should have a deeper discussion about the interactions and their semantics, and expand on the API documentation to capture these assumptions and guarantees.

**Comment by tmeschter** [comment]
Further thoughts:

I don't think we need `IPropertyEditorClientSession.NotifyServerShuttingDownAsync`; there are more general mechanisms for detecting when the server is shutting down. I think the client may just close all of its open tabs in this case anyway.

I think `IPropertyEditorConnection.SetEvaluatedValueAsync` and `IPropertyEditorConnection.SetUnevaluatedValueAsync` would only return the updated values for the requested properties, rather than all properties affected by the change. Other affected properties would end up being reported by `IPropertyEditorClientSession.ReceivePropertyUpdatesAsync` at some later time.

I think where we're going to end up with this is that the server will maintain a copy of the DTOs for each active `IPropertyEditorClientSession`. Changes made through `SetEvaluatedValueAsync` and `SetUnevaluatedValueAsync` will be applied immediately, the affected properties re-evaluated, the new property values diffed against the DTO to produce the set of `PropertyUpdate`s to return, and then the DTO updated to reflect the new state.

When we detect changes outside of `SetEvaluatedValueAsync` and `SetUnevaluatedValueAsync` we will need to re-evaluate the affected properties, diff against the current DTO snapshot to produce the set of `PropertyUpdate`s to send via `ReceivePropertyUpdatesAsync`, and update the DTO snapshot again.

**Comment by drewnoakes** [comment]
> there are more general mechanisms for detecting when the server is shutting down

Agree. I called that out in a comment on `IPropertyEditorClientSession.NotifyServerShuttingDownAsync` so that we wouldn't fail to consider the scenario.

> I think `IPropertyEditorConnection.SetEvaluatedValueAsync` and `IPropertyEditorConnection.SetUnevaluatedValueAsync` would only return the updated values for the requested properties, rather than all properties affected by the change. Other affected properties would end up being reported by `IPropertyEditorClientSession.ReceivePropertyUpdatesAsync` at some later time.

I wrote a long reply to this then realised I was wrong, and now I've written an even longer one.

The problem I was trying to solve with the return values was allowing the client to know about all changes resulting from its update request. The client needs to know this so it can unlock the property and any that depend upon it in the UI. Returning all values in the response is one way of doing that. However it introduces problems with consistency as this diagram tries to demonstrate:

![image](https://user-images.githubusercontent.com/350947/103725766-65ffa280-502b-11eb-97e1-7b8d1cbcae50.png)

Instead, I think we need to have the update methods return _no values at all_, and accept a new parameter `Guid correlationId`. Then we extend `IPropertyEditorClientSession.ReceivePropertyUpdatesAsync` to accept `Guid? correlationId`, which the client may use to identify the updates that follow its request. When changes are external (e.g. branch switch, manual project file edit, etc) then this value is `null`. I would not expect one client to see correlation IDs from another client, as each client's workspace would be handled and versioned separately.

![image](https://user-images.githubusercontent.com/350947/103725811-829bda80-502b-11eb-9307-9b623f191240.png)

The key point here is that data only flows from the server to the client via `IPropertyEditorClientSession.ReceivePropertyUpdatesAsync`. This disallows overlapping requests and reordering of responses, so long as the server ensures calls to the client are serialised, and the client only returns from `ReceivePropertyUpdatesAsync` once the updated values have been integrated.

As it stands, this pattern would fail if the client's request doesn't produce a diff. To work around this, the update request should indicate when no properties are modified in its return.

Proposed API changes:

```c#
    // On IPropertyEditorConnection

    Task<PropertyValueUpdateResult> SetEvaluatedValueAsync(
        Guid correlationId,
    	ImmutableArray<EvaluatedValueChangeRequest> values);

    Task<ImmutableArray<PropertyUpdate>> SetUnevaluatedValueAsync(
        Guid correlationId,
    	ImmutableArray<UnevaluatedValueChangeRequest> values);

    // On IPropertyEditorSession

    Task ReceivePropertyUpdatesAsync(
        Guid? correlationId,
    	ImmutableArray<PropertyUpdate> propertyUpdates);

internal enum PropertyValueUpdateResult { ValuesChanged, NoValuesChanged }
```

> I think where we're going to end up with this is that the server will maintain a copy of the DTOs for each active `IPropertyEditorClientSession`.

Agreed. I originally advocated for having the server maintain/own the client's workspace. It helps us ensure consistency and allows various optimisations, such as per-client delta computation. This approach may not scale well when a large number of clients/sessions are expected, but in our case the expected number is small.

---

The current design allows a batch of either evaluated or unevaluated values. This is useful in the case that a property has multiple different configured values and the user selects "Use a single value across configurations", whereafter we need to modify N-1 of those values. Doing this in a single call improves performance.

Do we also want to allow modifying both evaluated and unevaluated values in a single batch? We could change the API to allow this. One downside appears to be you could request modifying both the evaluated and unevaluated value of the same property, which doesn't make sense. I can't think of a use case for this now though, can you?

**Comment by tmeschter** [comment]
What if the contract was such that each call to `SetEvaluatedValueAsync` or `SetUnevaluatedValueAsync` must result in a subsequent call to `ReceivePropertyUpdatesAsync`, even if no property values change (e.g., `propertyUpdates` would be an empty array)?

That would allow us to adopt the following interface shapes:

``` csharp
/// <summary>
/// Connection object provided to a property editor client, via which a client may update properties.
/// </summary>
/// <remarks>
/// Must be disposed when the connection is no longer required.
/// </remarks>
internal interface IPropertyEditorConnection : IAsyncDisposable
{
    /// <summary>
    /// Requests a change to one or more evaluated values of one or more properties.
    /// </summary>
    /// <returns>
    /// A Task that completes when the server has received and scheduled the property update.
    /// </returns>
    /// <remarks>
    /// Guaranteed to call IPropertyEditorClientSession.ReceivePropertyUpdatesAsync with the given
    /// given correlationId at some point after the Task completes, even if the update resulted in no
    /// changes to property values.
    /// </remarks>
    Task SetEvaluatedValueAsync(
        Guid correlationId,
    	ImmutableArray<EvaluatedValueChangeRequest> values);
    
    /// <summary>
    /// Requests a change to one or more unevaluated values of one or more properties.
    /// </summary>
    /// <returns>
    /// A Task that completes when the server has received and scheduled the property update.
    /// </returns>
    /// Guaranteed to call IPropertyEditorClientSession.ReceivePropertyUpdatesAsync with the given
    /// given correlationId at some point after the Task completes, even if the update resulted in no
    /// changes to property values.
    /// </remarks>
    Task SetUnevaluatedValueAsync(
        Guid correlationId,
    	ImmutableArray<UnevaluatedValueChangeRequest> values);
}

/// <summary>
/// Proffered by the client, for notifications from the server.
/// </summary>
internal interface IPropertyEditorClientSession
{
    /// <summary>
    /// Provides an editor client with the initial snapshot of properties, including all metadata and values.
    /// </summary>
    Task ReceivePropertiesAsync(
    	ImmutableArray<Property> properties);

    /// <summary>
    /// Notifies an editor client of a change to the values of one or more properties.
    /// </summary>
    /// <returns>
    /// A Task that completes when the client has received and scheduled the property update.
    /// </returns>
    Task ReceivePropertyUpdatesAsync(
        Guid? correlationId,
    	ImmutableArray<PropertyUpdate> propertyUpdates);
}
```

This guarantees that the server and client process each other's messages in order, but neither needs to block on the actual processing of those messages. And the client always gets a notification when its changes have been applied.

The difficulty I have with `SetEvaluatedValueAsync` returning a `PropertyValueUpdateResult` is that the only way to compute that value is to apply all the updates and perform the diff--at which point we may as well return the actual `PropertyUpdate`s.

Does that seem workable?

**Comment by drewnoakes** [comment]
> Does that seem workable?

Yes, and it seems slightly tidier.

> The difficulty I have with SetEvaluatedValueAsync returning a PropertyValueUpdateResult is that the only way to compute that value is to apply all the updates and perform the diff--at which point we may as well return the actual PropertyUpdates.

Returning the updates is not an option, due to the race condition identified above.

The client is going to have to wait for the update one way or another, and the server's going to have to hold that correlation ID until the diff is completed anyway.

---

As correlation IDs are not comparable in any meaningful way (unlike versions), we need to make sure the server locks around update requests and handles them serially. I am also assuming that the channel of communication between client/server preserves message order. If that's not the case, we may end up with inconsistent state if two nearby updates have their updates received in the opposite order to which they were sent, even with locking.

**Comment by tmeschter** [comment]
To be clear to guarantee message order with my proposed interfaces the client would have to await the `Task` returned by `SetEvaluatedValuesAsync`/`SetUnevaluatedValuesAsync` before making further calls to the server, and the server would have to await the `Task` returned by `ReceivePropertiesAsync`/`ReceivePropertyUpdatesAsync`. The completion of these tasks just signifies that the client or server has received the message and scheduled it for processing (in sequential order), not that the processing is complete.

**Comment by tmeschter** [comment]
Further notes:

1. After calling SetEvaluatedValueAsync, the corresponding call to ReceivePropertyUpdatesAsync needs to include the updated values of any dependent properties in addition to the requested properties. We should also consider requerying everything and sending a total diff.

**Comment by drewnoakes** [comment]
> Highlight that ReceivePropertyUpdatesAsync may include an empty ImmutableArray

Chatting with @lifengl highlighted a scenario we need to consider:

- Client requests changing property from A -> B
  - At this point, the client has the value B stored in memory
- Server, for whatever reason, rejects the change

The client needs to be notified that the property it requested the change to now has value A. From the server's perspective, there's no delta.

One way to achieve this may be to always include the value of a changed property in the correlated update message. So long as the client is locking that editor (which it will) there's no chance for the value to flip-flop.

**Comment by drewnoakes** [comment]
We have settled on a design.
