### ISSUE TITLE
Project System: Fix Microsoft.VisualStudio.Editors package def to be auto-generated

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#68]
_From @davkean on April 1, 2016 17:25_

Currently, Microsoft.VisualStudio.Editor's pkgdef is hand-written + expected to be pre-processed. We should move it an auto-generated model.

_Copied from original issue: dotnet/roslyn#10253_

**Comment by davkean** [comment]
While this might be a lot of work to figure them all out - we should at least move the ones with versions numbers out, see: https://github.com/dotnet/roslyn-project-system/pull/9

**Comment by panopticoncentral** [comment]
I've got to hand modify the pkgdef to add a project page, which annoys me. This is too much to do for that, but I'll take it.
