### ISSUE TITLE
Design-time log file names wrong

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/project-system#6800]
https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#visual-studio-2015-or-below states:

> Under `%TEMP%`, look for `[RANDOMGUID].designtime.log` files, these will contain the results of the design-time build. If running Visual Studio 2015 Update 2 or higher, the name of the project and design-time target that is being called will also be included in the file name.

However, for Visual Studio 2019, I get `DTBB_[RANDOMGUID].log` files

**Comment by drewnoakes** [comment]
That section of the documentation is for VS2015 and earlier. For VS2017 and later we recommend using the Project System Tools to get a binlog which is much richer.

**Comment by paulomorgado** [comment]
VS2015 is still supported ([Visual Studio Product Lifecycle and Servicing](https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing)).

Or are the log files produced by VS2019 named differently from the ones produced by VS2015?

**Comment by drewnoakes** [comment]
My understanding is that our documentation is correct for both cases. I don't know if/why the names would have changed. Do you feel that the `.log` file adds anything over the `.binlog`?

**Comment by paulomorgado** [comment]
No!

But this issue is about the documentation being correct or not.

**Comment by drewnoakes** [comment]
The documentation is correct if you read the section for the version of VS you're using, as I understand it. Let me know if you disagree and how you'd fix it. Bear in mind that we point users at this documentation when diagnosing issues and we want them to produce binlogs, not text logs.
