### ISSUE TITLE
Build Events Macro for Directory Separator

### ISSUE THREAD

**Issue by larsbuch** [dotnet/project-system#6808]
**Visual Studio Version**: Community 2019 16.8.2

**Summary**:
To make build events Macros are used but there is one missing for supporting cross platform build events. Fx Developing on windows and having CI/CD on linux

**Steps to Reproduce**:

1. Make a PostBuild event for a special subfolder for plugin generation

**Expected Behavior**: Having a Directory Separator Macro or handling directory separator is a preprosessing step

**Actual Behavior**: Build fails

**User Impact**: Limiting use of Build Events

**Comment by rainersigwald** [comment]
It's a bit clunky but you can use `$([System.IO.Path]::DirectorySeparatorChar)` since [MSBuild property functions](https://docs.microsoft.com/visualstudio/msbuild/property-functions) expose static members of `Path`.

**Comment by larsbuch** [comment]
Thank you for the answer. Clunky is better that failing. I do not write it that often

**Comment by drewnoakes** [comment]
I think it would work to just use `/` in your build events, as Windows supports both `/` and `\` as directory separators afaik.

**Comment by larsbuch** [comment]
@drewnoakes Visual Studio 2019 Build fails with / separator on windows and on linux MSBuild it fails with \ separator. If Visual Studio 2019 is surposed to accept / separator there is a bug in Visual Studio 2019 making it fail. The suggestion from @rainersigwald works.

**Comment by larsbuch** [comment]
Sorry. I forgot to close issue after resolution

**Comment by drewnoakes** [comment]
> Visual Studio 2019 Build fails with / separator on windows

I didn't expect that, given `/` works on the command line.
