### ISSUE TITLE
[Loc][CSY] Properties page style is not correct

### ISSUE THREAD

**Issue by Lydia-Shi** [dotnet/project-system#6821]
**Visual Studio Version**:
Version 16.9.0 Preview 3.0 [30906.181.main]

**More info**:
This issue reproduce in CSY, not reproduce in CHT&FRA.

**Steps to Reproduce**:

1. Create a Winforms .Net Cpre application
2. In Solution explorer, focus on project, right-click on it then click Properties, then observe the Properties page

**Actual Behavior**:
Properties page style is not correct.
![image](https://user-images.githubusercontent.com/54019172/103963484-623b5f80-5194-11eb-87af-b5809bc172e7.png)

**Expected Behavior**:
The style of the Properties page should be consistent with ENU.

**Comment by jjmew** [comment]
@Lydia-Shi it looks like you accidently turned on the preview feature that enables the new property pages. Please  make sure you uncheck both preview features. 

![image](https://user-images.githubusercontent.com/14163814/104068200-5ada7d00-51b9-11eb-932b-6dbaa9e6e60e.png)

**Comment by Lydia-Shi** [comment]
@jjmew  Thanks for your reply. After disabling the two options you mentioned in https://github.com/dotnet/project-system/issues/6821#issuecomment-757016779, Properties page style displays correctly.
