### ISSUE TITLE
Add option to the project system to enable  /largaaddresaware on built assemblies (All target frameworks in C# & VB.NET).

### ISSUE THREAD

**Issue by AraHaan** [dotnet/project-system#6829]
**Visual Studio Version**: Latest Preview of Visual Studio 2019.

**Summary**: The project system on C#, and VB.NET assemblies lack the option of setting /largeaddressaware. This option then for programs that need it then requires remembering to editbin it in, however it becomes an inconvience as then it invalidates code signing using an certificate so then one cant tell if it is a legit build (by me) or anyone else who clones the git repository (since they cannot sign the assembly without my certificate file I used the powershell equivalent of makecert on).

This becomes unacceptable because what we really need is for then the option to tell the compiler to set ``/largeaddressaware`` for us.

**Steps to Reproduce**:

1. make a new console application using ``dotnet new``

2. Add some memory usage tasks that when ran would use over about 2 GB of RAM.

3. Sign the console application using a certificate (*.cer file) made using powershell at compile time.

4. run the application and wait till it throws an ``OutOfMemoryException``.

5. use editbin to make the console application not throw an ``OutOfMemoryException`` (by setting ``/largeaddressaware``).

6. Now the code signature on the console application from using the *.cer file at compile time is invalidated.

**Expected Behavior**:

For /largeaddressaware to have an option on the Project Properties pages in the Project System for Visual Studio so when we code sign it does not get invalidated when we have to set it as part of the fact the program is designed to use over 2 GB of RAM on single objects.

**Actual Behavior**:
No way to set it so when manually setting it, it then invalidates the code signing at compile time.
**User Impact**:
major

**Comment by drewnoakes** [comment]
This request goes beyond the project system and to the compiler itself. As far as I understand, the compiler does not support emitting `largeaddressaware` binaries. The standard advice is to opt into this via editbin as indicated, however this invalidates signing.

**Comment by AraHaan** [comment]
Unless it is made to where the compiler outputs the binary (prior to being signed) then if the option to make it ``/largeaddressaware`` is set then it would invoke editbin, and then the compiler signs it so that way it does not invalidate.

**Comment by tmeschter** [comment]
@AraHaan The C# compiler will already set the "large address aware" flag if you target AnyCPU and turn on the "prefer 32-bit" option. Please see https://github.com/dotnet/roslyn/issues/9209 for more details.

If you would like to see support beyond that, the compiler or SDK would to create a design for how it would work and only then can we update the property pages to support it. As such I am closing this issue as there is nothing further we (the .NET project system) can do here.

If you have further questions or comments I'd suggest directing them to https://github.com/dotnet/roslyn/issues/9209 so the compiler team can better understand your needs.

**Comment by michaelcfanning** [comment]
@AraHaan, I noticed this closed issue investigating a binary analysis issue that appears related to this problem. I see that you're pursuing getting an explicit option for this setting in the compiler. 

Can you confirm for me whether large address aware is set for you after step #2? I think your issue is that it is *not*, due to compiler behaviors. You need it set, however, due to the special way you load this assembly in a native process?

**Comment by AraHaan** [comment]
Yes, I need LAA set, but due to a native dependency that is x86 only I cannot set AnyCPU (with prefer 32 bit set) as my dev machine is amd64 so it will try to load the x86 dependency in an x64 process and crash with the LAA flag set when I do set AnyCPU.

And yes I needed the flag on the compiler to be added as an option to override the compiler default of not setting it when someone like me MUST set the program to x86 so it will run as x86 when on an 64 bit system.

In my case the native dependency is made with C++/CLR so it gets loaded directly by a plugin system (similar to MEF on Visual Studio in a way).
