### ISSUE TITLE
Add project format migration tool

### ISSUE THREAD

**Issue by Varorbc** [dotnet/project-system#6836]
**Visual Studio Version**:16.8

**Summary**:There are many legacy projects in our project, and we hope to convert them to the SDK style。Request to add project format migration tool

**Comment by drewnoakes** [comment]
@Varorbc have you tried https://github.com/dotnet/try-convert?

**Comment by Varorbc** [comment]
![image](https://user-images.githubusercontent.com/5714438/104893011-da343180-59ad-11eb-826f-2c7a68502919.png)
Thank you very much, can it be a part of vs like nuget tool

**Comment by drewnoakes** [comment]
> Thank you very much, can it be a part of vs like nuget tool

You're welcome. Let us know how you get on with it. //cc @cartermp 

From the project's README:

> This tool is not supported in any way. Nobody will be on the hook for fixing any issues with it, nor is anyone who builds this tool obliged to add any requested features.
>
> This is an open source project built by members of the .NET team in their spare time. Although we'll strive to fix issues and add features if people ask for them, the default answer to any issue filed will be, "we'll review a pull request that implements this".

**Comment by jjmew** [comment]
As of now the current plan is to do this as command line tool  ( https://github.com/dotnet/try-convert)
