### ISSUE TITLE
File Nesting: Make IDefaultNestingProfileProvider public

### ISSUE THREAD

**Issue by swesonga** [dotnet/project-system#6838]
Project systems that need to customize their file nesting implementations need to export an INestingProfilesProvider. The file nesting implementation has a concept of a default nesting profile in case there are multiple. In order to inform CPS which profile is the default profile, an implementation of IDefaultNestingProfileProvider is required. However, this interface is currently internal to CPS and needs to be publicly consumable by Web tools and other project systems.

**Comment by ocallesp** [comment]
Any changes to default profiles will impact the user experience and should be designed and discussed with PMs.

Closing this since current implementation works as per documentation https://learn.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2022
