### ISSUE TITLE
document `<ProjectCapability  />`

### ISSUE THREAD

**Issue by John0King** [dotnet/project-system#6842]
sorry to ask there, (I do not know which doc repo to ask to).

As title `<ProjectCapability />` control which feature can be use in IDE like visual studio, by default `Microsoft.Net.Sdk.Web`  add all the feature need for web project, but when we separate the project (for example :  a class library for web )  with `Microsoft.Net.Sdk`
then we lost most of features that Web project have.  
After some research I found that visual studio's  "features"  controlled by `<ProjectCapability />`,  but their many "capability name " and I do not know how much of them, and  which one control which feature ,
so I hope we can document the `ProjectCapability` that current available.

**Comment by drewnoakes** [comment]
Hi @John0King, apologies for the delay.

I see two questions here:

1. What project capabilites exist?
2. What does each capability mean?

There are several VS components that produce and consume project capabilities, so there's not really a single place to discover these. I can give a few pointers however.

Firstly, to see which capabilities are active in a given project, add this to your project file:

```xml
<ItemGroup>
  <ProjectCapability Include="DiagnoseCapabilities" />
</ItemGroup>
```

This will add a node to Solution Explorer that shows all active capabilities, which can be very helpful:

![image](https://user-images.githubusercontent.com/350947/106975242-44b8e000-67aa-11eb-9a8c-3dbbdf054472.png)

Secondly, several of the code project capabilities that CPS provides are tabulated here:

https://github.com/microsoft/VSProjectSystem/blob/master/doc/overview/project_capabilities.md

If there are capabilities missing from that table, please open an issue on that repo.

**Comment by John0King** [comment]
@drewnoakes   thanks,

and I want to point out that [project_capabilities.md](https://github.com/microsoft/VSProjectSystem/blob/master/doc/overview/project_capabilities.md)  doesn't document about the web project , eg. for a razor sdk project
```csproj
    <ProjectCapability Include="Web" />
    <ProjectCapability Include="AspNetCore" />
    <ProjectCapability Include="DotNetCoreWeb" />
```

**Comment by drewnoakes** [comment]
Please open an issue on that repo.
