### ISSUE TITLE
[Loc] Assistance with translation

### ISSUE THREAD

**Issue by crsuzukimsft** [dotnet/project-system#6848]
. | .
-- | --
MOR PM | Jan Baltus (Moravia IT)
String Resource ID | 0; "preview"
Source String | preview
Filename | Microsoft.VisualStudio.Editors\PropPages\xlf\Strings.xlf
Question | Could you please give us more context about the string? Is this related to the preview version of a service?
Additional details |  
Core Team Response |

**Comment by crsuzukimsft** [comment]
vcq 356332

**Comment by tmeschter** [comment]
@crsuzukimsft This is where the string appears:

![image](https://user-images.githubusercontent.com/10506730/105253100-a08d3300-5b33-11eb-996a-2f48ec0ab393.png)

Tagging @jmarolf for more context.

**Comment by crsuzukimsft** [comment]
@tmeschter thank you. This is good enough for context.
