### ISSUE TITLE
[Loc] Assistance with translation

### ISSUE THREAD

**Issue by crsuzukimsft** [dotnet/project-system#6849]
String Resource ID: 0; "latest"
Source String:  latest
Filename | Microsoft.VisualStudio.Editors\PropPages\xlf\Strings.xlf
Question | Where will this string appear? Without any context or information, this is almost impossible to translate accurately.

**Comment by crsuzukimsft** [comment]
vcq 359654

**Comment by tmeschter** [comment]
@crsuzukimsft This string appears on the Code Analysis property page along with the strings "none" and "preview":

![image](https://user-images.githubusercontent.com/10506730/105252894-35dbf780-5b33-11eb-9c65-3a3702d7c502.png)

@jmarolf Can you provide more context on the meaning of the string?

**Comment by crsuzukimsft** [comment]
@tmeschter thank you. T
