### ISSUE TITLE
We need to understand the plan for deprecation of BinaryFormatter

### ISSUE THREAD

**Issue by jjmew** [dotnet/project-system#6858]
We need to understand the plan for deprecation of BinaryFormatter. We use it for the Resource Designer but we need to move to a new solution as it will be deprecated.  You can see https://github.com/dotnet/runtime/issues/39292

**Comment by MiYanni** [comment]
Current plan is to replace BinaryFormatter usage. It is used for undo/redo of the old property pages and used for drag & drop/copy-paste in the resource designer. I'm currently working on a solution using System.Text.Json.
