### ISSUE TITLE
Dotnet ProjectSystem to implement the new action handler CopyAsync()

### ISSUE THREAD

**Issue by ocallesp** [dotnet/project-system#6866]
`Microsoft.VisualStudio.ProjectSystem.VS.Rename.RenamerProjectTreeActionHandler `should implement the new action handler `CopyAsync()` and handle the new prompt according to [Fix UX for namespace update](https://github.com/dotnet/project-system/issues/6867)

This work should be done after [CPS refactor : Port all code from HandleCopyPasteItemListAsync() to CopyAsync() ](https://github.com/dotnet/project-system/issues/6868)

**Comment by jjmew** [comment]
@ocallesp  can you add more details to this issue?

**Comment by ocallesp** [comment]
The UX will be implemented by the Roslyn Team.
https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

cc. @jjmew, @mikadumont, @ryzngard
