### ISSUE TITLE
Moving/renaming a file/folder the namespace should be renamed automatically

### ISSUE THREAD

**Issue by ocallesp** [dotnet/project-system#6869]
**Visual Studio Version**:

Work needed:

- CPS to implement an action handler CopyAsync to hook when the user move a file.
- CPS to refactor all the code around the new action handler CopyAsync()

- Modify dialog box in VS
![image](https://user-images.githubusercontent.com/510598/95389281-6fe8fc80-08a8-11eb-8f1f-a1cebe5e32ca.png)

- Perhaps if needed add an option to enable namespace update by default to avoid the prompt message.
![image](https://user-images.githubusercontent.com/510598/95389470-bc343c80-08a8-11eb-88b3-8edf2a86f3ae.png)

- Dotnet ProjectSystem to implement CopyAsync()

**Comment by ryzngard** [comment]
@ocallesp is there something missing from the Roslyn side on this?

**Comment by ocallesp** [comment]
The UX will be implemented by the Roslyn Team.
https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

cc. @jjmew, @mikadumont, @ryzngard
