### ISSUE TITLE
New items should not be added to the application while the application is in debug state

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/project-system#6877]
**Visual Studio Version**:
Dev16 16.9.0 Preview 3.0 [30906.181.main]

**Summary**:
Add items menu items are not disabled in the right click menu for project items.

**Steps to Reproduce**:
* Create a Winforms or WPF .Net Core app.
* Press F5 to run this app.
* Right-click this app node in Solution Explorer, and choose 'Add'.
Result: Add menu item is not disabled

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/15823268/106068655-bbbced00-60b5-11eb-9577-e220fa79d3fb.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/15823268/106068613-ac3da400-60b5-11eb-82a9-bb8ac73d92a5.png)

**User Impact**:

**Comment by davkean** [comment]
This behavior is by design. CPS will react to branch switches via the command-line by adding/removing items, there's no reason VS needs to limit this.

**Comment by drewnoakes** [comment]
@davkean should it be possible to manage NuGet packages while debugging?

**Comment by davkean** [comment]
Theoretically yes.

**Comment by jjmew** [comment]
We don't prevent you from editing files while debugging. I don't see why we would prevent you from adding files.
