### ISSUE TITLE
When copying project nodes, in SDK style projects, hierarchy of DependentUpon files is not preserved in the Solution explorer window 

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/project-system#6878]
Original issue:
This issue has been moved from [a ticket on Developer Community.](https://developercommunity2.visualstudio.com/t/User-Control-code-corrupted-by-VS2019-d/1321277)
https://github.com/dotnet/winforms-designer/issues/2823

**Visual Studio Version**:
Dev16 16.9.0 Preview 4.0 [30927.2.main]

**Summary**:
Customer copies a usercontrol  in solution explorer window, and does not see the same hierarchy among the copied files as the original files were arranged in

**Steps to Reproduce**:
1. Create a WinForms or WPF  .Net Core application
2. Add a Winforms or WPF User Control item to the project, UserControl1.cs[Designer] is opened by default, so close it
3. In Solution Explorer, copy Usercontrol1 node then paste in this project to get a UserControl1-Copy
4. Expand UserControl1 - Copy.cs solution explorer node, observe its child nodes and compare to the original sub nodes
Result: original and copied hierarchies mismatch, however files are copied on disk. The unexpected item groups are added to the project file. 

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/15823268/106072771-9fbd4980-60bd-11eb-9675-3f0e86bd3a37.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/15823268/106072742-903e0080-60bd-11eb-9df5-40d5e14dc249.png)

![image](https://user-images.githubusercontent.com/15823268/106072633-608ef880-60bd-11eb-974f-6f2870664c74.png)

**User Impact**:
User has to edit the project file to remove the added items, then solution explorer will show the expected hierarchy

**Comment by Tanya-Solyanik** [comment]
Content of the project file after the copy:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="UserControl1 - Copy.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UserControl1 - Copy.Designer.cs">
      <DependentUpon>UserControl1.Designer.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="UserControl1 - Copy.resx">
      <DependentUpon>UserControl1.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

</Project>
```
It should not contain the the compile items because they are included by default.

**Comment by drewnoakes** [comment]
I believe CPS handles copy/paste of items. Does that sound right @lifengl @davkean?

**Comment by tmeschter** [comment]
@drewnoakes Can you raise this issue at the next CPS sync up and see if we can figure out the correct owner?

**Comment by jjmew** [comment]
We have moved this to the internal database as it is a CPS issue

**Comment by Tanya-Solyanik** [comment]
Thanks! please update https://developercommunity2.visualstudio.com/t/User-Control-code-corrupted-by-VS2019-d/1321277 when you have results
