### ISSUE TITLE
Add link from new UI to old launch profile editor

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6910]
Until we have a proper launch profile editor in the new experience, we should make it easy for users to navigate from the new experience to the old one, with explanatory text.

This can be achieved by using a link action.

It may require some work in the legacy editor so that it doesn't just try and delegate to the new editor again when asked to show launch profiles.

**Comment by drewnoakes** [comment]
@jjmew I've looked into this briefly and wanted to point out that this approach will not work for Codespaces. Would you still like to go ahead with this approach? Maybe that's ok, as it's only temporary. We don't currently have a mechanism to hide UI elements in Codespaces, so dogfooding users who try to navigate to launch profiles in Codespaces will likely see errors.

**Comment by jjmew** [comment]
@drewnoakes that is fine

**Comment by drewnoakes** [comment]
We may need to add a visibility condition here to disable this linkage when running in a Codespaces client.

**Comment by drewnoakes** [comment]
Visibility condition added in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/303115

**Comment by drewnoakes** [comment]
Ability to have named command handlers for LinkAction editors added in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/303509. Before this, LinkAction editors could only launch URLs. That PR allows adding custom code to invoke the legacy editor on the debug page when the user clicks a hyperlink in the UI.

**Comment by drewnoakes** [comment]
We are going to avoid this intermediate step and work on the improved launch profile editing directly instead.

The work mentioned above to add link action extensibility is of general use, such as for #6964.
