### ISSUE TITLE
VS hang attempting to open a file

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/project-system#6913]
Collecting dump now.  Will link to it once available.

Dump at: https://microsoft.sharepoint.com/:u:/t/ManagedLanguagesIDE/EcoSe3kmJelPlUfp0Q4pLbgBF4BrErpNa1O4zaNYLmDoiw?e=FIAfFl

**Comment by drewnoakes** [comment]
@sharwel @CyrusNajmabadi this is CPS. Please file against them on AzDO rather than here on GitHub.
