### ISSUE TITLE
Add a Project Query API action to explicitly delete a property

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6920]
The new project property pages allow you to set a property value to anything you want, and those changes will be persisted into the project file as an MSBuild property. However, we have no way to remove a property from the project file entirely.

This would be used by the new property pages to provide a gesture (a button or menu item) allowing the user to reset the value of a property to a default value by deleting it from the project file. Currently the best we can do is to set the property value to the empty string, but this won't work if the default value comes from a previous imported .props file--the empty string will "shadow" the default. And even where it does work, we're left with an empty property definition; this is aesthetically displeasing and runs counter to the lean design of SDK-style projects.

**Comment by drewnoakes** [comment]
It may be possible to achieve this by passing `null` rather than requiring a new API.

**Comment by adamint** [comment]
Null indicates already for an unevaluated value that it "should be removed entirely and/or reset to a default value" - because of this, I do not think it makes sense to have a sentinel value for evaluated and not for unevaluated and think that in the context of setting an evaluated property, it should mirror the unevaluated prop.

**Comment by tmeschter** [comment]
We need to be careful about what level of the system we're talking about, as `null` means different things at different levels.

At the MSBuild level, reading a property that isn't defined will return `null` for the unevaluated value, and the empty string for the evaluated value. MSBuild will throw if you try to set the value to `null`. The MSBuild-specific implementation of IProjectProperties (the ProjectProperties type) reflects this. Note MSBuild does not make a distinction between setting evaluated vs unevaluated values.

Higher up at the `IProperty` level things get messier. `IProperty.GetValueAsync` can return `null` if the underlying data source returns `null` **or** the string value returned by the underlying data source cannot be converted to the expected type (bool, int, enum value, etc.). `IProperty.SetValueAsync` can accept a `null` value but what happens from there is undefined, and not consistent from one type of property to another. For bools and ints, `null` is effectively converted to the empty string. For strings and enum values, `null` will end up getting passed straight through for the data source to deal with. If that underlying data source is MSBuild, we'll get exceptions.

I think the current shape of the Project Query API (where we let you set the evaluated value to `null` but not the unevaluated) is a case of us exposing the semantics of the underlying layer without property thinking them through. We should do one of the following:

1. Have an explicit "delete" operation alongside "set evaluated value" and "set unevaluated value" that calls `IProperty.DeleteAsync`, and disallow `null` for either of the set operations.
2. Allow both "set" operations to accept `null`, but explicitly check for `null` and convert that case to a call to `IProperty.DeleteAsync`. Document that settings a property to `null` means you intend to delete it.

In neither case would we pass a `null` value down to a "set" operation.

**Comment by adamint** [comment]
Gotcha, that makes a lot of sense. Because null is already allowed in SetUnevaluatedValueAsync, I'd like to implement the second case

**Comment by adamint** [comment]
Addressed in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/393810
