### ISSUE TITLE
Add a UI gesture to reset a property to its default value

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6921]
This is the UX counterpart to #6920.

The new project property pages allow you to set a property value to anything you want, and those changes will be persisted into the project file as an MSBuild property. However, we have no way to reset a property to its default value. We should have a button or menu item to do so.

**Comment by adamint** [comment]
Addressed in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/393810
