### ISSUE TITLE
Transitive NuGet packages are not being shown in Solution Explorer when connect to a VS CodeSpace

### ISSUE THREAD

**Issue by donnie-msft** [dotnet/project-system#6922]
**Visual Studio Version**: **16.9.0 Preview 4.0 [31004.17.d16.9]**

**Summary**:

Transitive NuGet packages are not being shown in Solution Explorer when connect to a VS CodeSpace.

Checked `project.assets.json` and found the dependency was written as expected:
> "MicroBuild.Plugins.SwixBuild/1.0.147": {
>         "type": "package",
>         "dependencies": {
>           "MicroBuild.Core.Sentinel": "1.0.0"
>         },
>         "compile": {
>           "lib/net461/_._": {}
>         },
>         "runtime": {
>           "lib/net461/_._": {}
>         },
>         "build": {
>           "build/_._": {}
>         }
>       },
> 

**Steps to Reproduce**:

1. Connect VS to a local CodeSpace server.

2. Open a project with NuGet packages containing transitive dependencies. Eg, `Microsoft.VisualStudio.ProjectSystem.Managed`.

3. Observe that Package nodes cannot be expanded to see their transitive packages.

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/49205731/106971111-3b813200-671c-11eb-9689-c9e5992491d5.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/49205731/106971138-489e2100-671c-11eb-8655-90c5bc2b06e1.png)

**User Impact**:

**Comment by drewnoakes** [comment]
Codespaces does not support `IAttachedCollection*` APIs as of yet. 

This is the internal tracking issue https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1135451.
