### ISSUE TITLE
Some commands did not translate when right-click on a *.cs file

### ISSUE THREAD

**Issue by ocallesp** [dotnet/project-system#6925]
**Visual Studio Version**:

**Summary**:
Some commands are not translated.

**Steps to Reproduce**:

1.  Open Visual Studio
2. Change the language in Tools | Options | Environment | International Settings | Language and select Spanish.
3. Close Visual Studio and open it again
4. Create a simple Console C# application using .NET Core
5. Go to Solution Explorer and right-click on Program.cs

![image](https://user-images.githubusercontent.com/510598/107084967-a4b08600-67ac-11eb-90b8-c569d14f89b7.png)

**Comment by jjmew** [comment]
These are from ReSharper not us
