### ISSUE TITLE
Glob pattern issues for auto generated items with metadata child nodes

### ISSUE THREAD

**Issue by v-zubritsky** [dotnet/project-system#6929]
**Visual Studio Version**:
Microsoft Visual Studio Community 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.03752
Installed Version: Community

**Summary**:
Hard to say whether it's some corner case or pretty general bug in glob patterns, when item metadata represented with child nodes is involved. 

Let's say we have a bunch of `*.xsd` files used for code generation with use of `MSDataSetGenerator`. 

```
<None Remove="Schema\**\*.*" />
<Compile Remove="Schema\**\*.cs" />
<Content Include="Schema\**\*.xsd">
  <Generator>MSDataSetGenerator</Generator>
  <LastGenOutput>%(Filename).Designer.cs</LastGenOutput>
  <SubType>Designer</SubType>
</Content>
```
And we'd like to hide the autogenerated items (`*.xsc`, `*.xss`, `*.Designer.cs`) in the solution explorer under the related `*.xsd` node, while keeping our project file minimal. Here is one possible implementation of that idea

```
<XsdFiles Include="Schema\**\*.xsd" />
<None Include="@(XsdFiles -> '%(RelativeDir)%(Filename).xsc')">
   <DependentUpon>%(Filename).xsd</DependentUpon>
</None>
<None Include="@(XsdFiles -> '%(RelativeDir)%(Filename).xss')">
   <DependentUpon>%(Filename).xsd</DependentUpon>
</None>
<None Include="@(XsdFiles -> '%(RelativeDir)%(Filename).Designer.cs')">
  <DependentUpon>$([System.String]::Copy(%(Filename)).Replace('.Designer','')).xsd</DependentUpon>
  <DesignTime>True</DesignTime>
  <AutoGen>True</AutoGen>
</None>
```

I believe that item with its child nodes should be covered by the glob pattern include, but unfortunately this isn't happening for `*.Designer.cs.AutoGen` child node – node is readded to the `*.csproj` file on every Custom Tool run, even though it's present for item with glob pattern. 

This is what is added for `Items.xsd`.
```
<None Update="Schema\Items.Designer.cs">
  <DesignTime>True</DesignTime>
</None>
```
**Steps to Reproduce**:
[ClassLibrary1.zip](https://github.com/dotnet/project-system/files/5938608/ClassLibrary1.zip)

1. Open attached solution
2. Run custom tool on the `Items.xsd` file, by manually changing it and saving or through the context menu in Solution Explorer.

**Expected Behavior**:
Dependent `Items.Designer.cs` file is regenerated, while `*.csproj` file is left unchanged.

**Actual Behavior**:
File is regenerated, but `*.csproj` file is also changed

**User Impact**:
Project file is less minimalistic than it could be.

**Comment by jjmew** [comment]
This is a CPS issue. It will be tracked internally by https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1281047
