### ISSUE TITLE
Identify pages and properties missing in the VB experience

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6935]
The work here is to _identify_ which VB-specific pages and properties are missing from the new project property pages and file issues to address those.

**Comment by paul1956** [comment]
UseWindowsForms and UseWPF when you want to set both.
MinimumSplashScreenDisplayTime
Possibility UseCompatibleTextRendering
If and when Code Cleanup for VB gets integrated, separate profiles/configurations for VB and C# under Analyzer/Code CleanUp.
When configuring CodeCleanup the list of available cleanups should be by Language (especially important when names are the same).

**Comment by melytc** [comment]
Notes on our review:
- Icon is in the resources pages.
- View windows settings (creates if needed, and shows app.manifest). This is might be covered by the Manifest property > Use a custom manifest.
- `Compile` page. The warnings are shown in a different way (list vs table). How to encourage users to go to editor config for warnings. 
- How dynamic are the warning configurations lists VB has? 
- `Advanced Compiler Settings`
- `Remove integer overflows checks` is in intermediate mode.
- Compilation constants (VB) and conditional compilation symbols (C#) are different but stored in the same msbuild property.

**Comment by tmeschter** [comment]
At this point I believe I've split off all the individual work items identified here. Closing.
