### ISSUE TITLE
Identify pages and properties missing in the F# experience

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6936]
We need to identify which F#-specific pages and properties are missing from the new project property pages and file issues to address those.

**Comment by cartermp** [comment]
I can share a screenshot, but the only ones that come to mind are in the Build page (debug config):

|Property|Current UI|What it does|Context|
|--------|----------|------------|-------|
|OtherFlags|Textbox|Plops `<OtherFlags>` in the project file properties|General dumping ground for F# compiler options|
|Optimize code|Checkbox|Plops `--optimize` in `<OtherFlags>`.|On by default in release|
|Generate tail calls|Checkbox|Plops `--tailcalls` in `<OtherFlags>`|On by default in release|

**Comment by tmeschter** [comment]
@cartermp So `OtherFlags` looks like this in the project file?

``` XML
<OtherFlags>--optimize --foo --bar --tailcalls</OtherFlags>
```

**Comment by cartermp** [comment]
Yep!

**Comment by tmeschter** [comment]
@cartermp Can I close this in favor of dotnet/fsharp#11532?

**Comment by cartermp** [comment]
Yep, sounds fair.
