### ISSUE TITLE
Identify pages and properties missing in the ASP.NET Core experience

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6939]
We need to identify the ASP.NET Core-specific pages and properties missing from the new project property pages and file issues to address those.

**Comment by melytc** [comment]
The page `TypeScript build` page hosted in the web tools repo, ideally. Something similar to the `Web Server Settings` page

**Comment by melytc** [comment]
We do see `Razor Properties` page in the new experience, but maybe it's a xaml file tagged like a project properties one, but not intentional.

**Comment by melytc** [comment]
We've done the investigation and the resulting work will be done by the corresponding team.
