### ISSUE TITLE
Bugs encountered while editing SDK project in Visual Studio (lost edit history, cursor position, scrollbar position)

### ISSUE THREAD

**Issue by jrmoreno1** [dotnet/project-system#6946]
When editing a SDK project in Visual Studio 2019, I have encountered several problems.

Repo:
1. Open SDK project
2. paste `<ItemGroup ></ItemGroup>` in Project (note the space between the tag name and the closing bracket.
3. Save project file

Expected behavior:
Cursor remains in same position, vertical scroll bar position remains unchanged, edit history has new item added to it.

Actual behavior:
1) Cursor/caret is moved to the bottom of the document
2) Vertical scrollbar is moved to the top (if it is not there already)
3) Edit history is cleared (can no longer undo prior actions)

NOTE: The sequence of the above behavior may not be correct, but if you wait a second or so all 3 actions happen.

Version info:
Microsoft Visual Studio Enterprise 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.04084

**Comment by jrmoreno1** [comment]
@wli3 : yes, this would be an editor bug.  Thank you for routing it to the appropriate spot.

**Comment by drewnoakes** [comment]
@jrmoreno1 can you verify if this still occurs in 16.8.5 please? I heard a report that this behaviour went away after upgrading.

**Comment by jrmoreno1** [comment]
@drewnoakes : still happens with 16.8.5. Pasted  `<ImportGroup ></ImportGroup>` into a SDK project and hit cntrl-s, takes a second or so, but scrolls to the top, puts cursor at the bottom, and clears edit history.  Don't even have to go to a particular project, happens for all of the SDK projects I have.

**Comment by drewnoakes** [comment]
Thank you for verifying. Now I am at a computer I can reproduce the issue. Interesting that it happens for `ImportGroup` but not `PropertyGroup` or `ItemGroup`. The fact that the edit history is gone is particularly troubling.

**Comment by jjmew** [comment]
@davidwengier Do you remember if this is in CPS or not?

**Comment by jjmew** [comment]
This is owned by the CPS team and not the project system. This is being tracked internally in https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1283297

**Comment by jrmoreno1** [comment]
@jjmew : what does CPS stand for?

**Comment by jjmew** [comment]
@jrmoreno1 CPS is Common Project System. It is the underlying framework that we use to build .NET Project System.
