### ISSUE TITLE
Translation issues in new property page

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/project-system#6949]
**Visual Studio Version**:
16.9 Preview 4

**Summary**:
Some translations (in Chinese) are inappropriate. Please review it and review them in other languages too.

https://github.com/dotnet/project-system/blob/fead3ce6df4b553c2eec5c4eefce946eaab75c1c/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf#L5-L7

'unsafe' is a keyword and should not be translated. It's already mentioned in the English message.

---

https://github.com/dotnet/project-system/blob/fead3ce6df4b553c2eec5c4eefce946eaab75c1c/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf#L40-L42

Suggestion: 确定性输出 (Deterministic output)

---

https://github.com/dotnet/project-system/blob/fead3ce6df4b553c2eec5c4eefce946eaab75c1c/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf#L115-L122

`Nullable` is not suitable for property page users. They should be at least translations of "nullable types" or "nullable reference types".

---

https://github.com/dotnet/project-system/blob/fead3ce6df4b553c2eec5c4eefce946eaab75c1c/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf#L220-L222

Translating "Any CPU" is OK but not so good for me.

---

https://github.com/dotnet/project-system/blob/fead3ce6df4b553c2eec5c4eefce946eaab75c1c/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf#L285-L287

https://github.com/dotnet/project-system/blob/fead3ce6df4b553c2eec5c4eefce946eaab75c1c/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf#L295-L297

Language order specific for Chinese. `将追加子文件夹到此路径` is more natural.

---

I don't have a fork for this repo so not opening PR. Please also remind other language translators for similar issues.

**Comment by drewnoakes** [comment]
@huoyaoyuan thank you very much for the feedback on the translations 👍 

@tmeschter are you aware of a process for sending this feedback to the team that provides us with these translations?

**Comment by tmeschter** [comment]
@wli3 @cristianosuzuki77 Who can we pass this feedback along to?

**Comment by wli3** [comment]
ping  @cristianosuzuki77

**Comment by cristianosuzuki77** [comment]
Feedback incorporated.

**Comment by drewnoakes** [comment]
@cristianosuzuki77 can you explain what the number 399008 refers to?
