### ISSUE TITLE
Automatic packages restore is a hassle

### ISSUE THREAD

**Issue by v-zubritsky** [dotnet/project-system#6951]
**Visual Studio Version**:
Microsoft Visual Studio Community 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.03752
Installed Version: Community

**Summary**:
Visual studio silently restores nuget packages in background making development experience less enjoyable. Note that SDK based project files format is used.

**Steps to Reproduce**:

1. Enable [nuget restore with lock](https://devblogs.microsoft.com/nuget/enable-repeatable-package-restores-using-a-lock-file/#how-to-enable-the-lock-file);
2. Install some packages and commit changes multiple times (don't include `packages.lock.json` to simplify diff view and further rebases, if they happen);
4. Finally commit `packages.lock.json`;
4. Execute `git rebase -i HEAD~n`, where `n` is number of commits, you've created on the previous steps, choosing `edit` (`e`) for every commit in the rebase todo.

**Actual behavior**:
Visual Studio will try to restore packages in background on every rebase stop regenerating `packages.lock.json` files, so `rebase --continue` is not possible unless I execute `git checkout HEAD -- *packages.lock.json` and it heats my laptop significantly.

**Expected behavior**:
Visual Studio shouldn't be trying to restore packages unless I want it to happen (explicitly triggered restore and maybe build should be good enough).

**User Impact**:
I'd like to be able to disable such background restore, but I'm not able to find appropriate options. [Restore disable option](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#enable-and-disable-package-restore-in-visual-studio) provided in the docs seems to disable the ability to restore packages completely.

**Comment by jjmew** [comment]
This is a feature request. At this point it doesn't seem like the right path for us to take. The reason why we keep doing restores is because in the background we need to do design time builds. Those background builds allow you to have intellisense and designers. If we didn't automatically restore then your intellisense will be broken.

**Comment by v-zubritsky** [comment]
@jjmew Thanks for clarifying. 

Do I understand correctly, that there is no possibility currently to tune this behavior? So it's either this or no restore at all?
Have just switched solution to the SDK-based project format and it was somewhat noticeable behavior difference.

**Comment by drewnoakes** [comment]
@v-zubritsky a possible workaround here is to use `git rebase -i --exec "git checkout HEAD -- *packages.lock.json"`.

> Is it possible to detect that build is triggered by VS in design time? I mean does VS set any msbuild property?

Yes, the property `DesignTimeBuild` is set during design-time builds. I am not sure you'll be able to achieve what you're after with it though.

**Comment by v-zubritsky** [comment]
@drewnoakes Yeah, it seems I won't be able to improve anything with use of `DesignTimeBuild` property, as it's most likely is set to `true` even when I explicitly trigger restore from package manager. So it's not possible to disable lock file regeneration for background VS builds only.

Hoped to implement it this way
```
<RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
<RestorePackagesWithLockFile Condition="'$(DesignTimeBuild)' != 'true'">true</RestorePackagesWithLockFile>
```

Moreover nuget is unhappy, when lock is disabled, but lock file exists. Fails with `Invalid restore input where RestorePackagesWithLockFile property is set to false but a packages lock file exists`
