### ISSUE TITLE
[Question] About solution file

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/project-system#6952]
Hello, I hope it is the right corner for this question

I have ask this question before in the Roslyn repository, 
https://github.com/dotnet/msbuild/issues/545
and they let me know that i will be a good idea to ask this question in this repository

I currently working on a vscode extension for Visual Studio Soution files
(see https://github.com/TobiasSekan/SolutionExtension)

Can you help me to understand the right side of lines under `SharedMSBuildProjectFiles`

| Number | e.g. found in | stands for |
| - | - | - |
| 4 | testfx.sln | references the shared project ??? |
| 5 | roslyn.sln | ??? |
| 9 |  muxcontrol.sln | ??? |
| 13 | roslyn.sln | shared project itself ??? |

There was a similar question in https://github.com/dotnet/msbuild/issues/545, but with less information about this.

I would be pleased to receive a reply from you
With best regards

**Comment by jjmew** [comment]
@lifengl Any ideas?

**Comment by jjmew** [comment]
I have sent email to the solution team to see if they can help
