### ISSUE TITLE
Do not use BufferBlock in the import tree provider and dependencies tree

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#6977]
Please switch to use DataflowBlockSlim.CreateSimpleBufferBlock or prevent using it completely.

BufferBlock is more memory expensive & our dataflow tracking tool doesn't support it to detect potential problems.

"Show All Files" is used more often than we think, it is shown as top UI delay when we switch to it. (This issue is unrelated, but need find what blocks UI thread.)

**Comment by lifengl** [comment]
FYI: @drewnoakes

**Comment by drewnoakes** [comment]
We also use a BufferBlock in the dependencies tree, by the looks of it.

**Comment by drewnoakes** [comment]
@lifengl `DataflowBlockSlim.CreateSimpleBufferBlock` appears to be internal, unlike most other factory methods on that type. It would need to be made public for us to consume it in the .NET Project System. Is there a reason it should not be public?

**Comment by drewnoakes** [comment]
We should ban usages of these types in our repo.

**Comment by drewnoakes** [comment]
Filed https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/305607 to make the method public which will unblock this.

**Comment by drewnoakes** [comment]
Updated CPS SDK will be published [here](https://dev.azure.com/azure-public/vside/_packaging?_a=package&feed=vs-impl&package=Microsoft.VisualStudio.ProjectSystem.SDK&version=16.10.63-pre&protocolType=NuGet&view=versions).

**Comment by drewnoakes** [comment]
#6978 replaces usages of `BufferBlock` and bans future usages.
