### ISSUE TITLE
Update localization infrastructure

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#6985]
**Summary**:

Our internal localization team is updating their infrastructure, and this requires that we make some changes to our repo and our build process.

More information can be found at the [Migrating out of SimpleLoc](https://ceapex.visualstudio.com/CEINTL/_wiki/wikis/CEINTL.wiki/1481/Migrating-out-of-SimpleLoc) internal wiki page.

This work needs to be completed by Mar. 31st, 2021 or we will lose the ability to update our translations.

**Comment by tmeschter** [comment]
I believe @jonfortescue is handling related work for repos that make use of Arcade, and may be able to provide some help if we get stuck.

**Comment by drewnoakes** [comment]
This PR may be a useful reference (or may not be!) https://github.com/microsoft/vs-validation/pull/89

**Comment by jjmew** [comment]
@dmonroym and @MiYanni  this is something that is time sensitive. Can you take a look at this next week?
