### ISSUE TITLE
Support public signing in new property pages

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#6990]
The ability to sign assemblies during build was once considered a security feature, but no longer. Nowadays it's only considered useful to produce a strong identity for that assembly. That is, the assembly's identity is extended to not only include its name and version, but also a hash.

Use of the word "signing" conveys a sense of it being a security feature. We can improve this in the new Project Properties UI.

The legacy property pages show related properties under the "Signing" page:

![image](https://user-images.githubusercontent.com/350947/109252762-69045b80-7842-11eb-8c07-dd61b7ee567f.png)

The non-ClickOnce properties have been carried over to the new Project Properties UI and currently resemble:

![image](https://user-images.githubusercontent.com/350947/109253084-17100580-7843-11eb-8c64-f4949108592c.png)

I propose the following changes:

- [x] Move these properties to a new "Strong naming" category on "Build" page
- [ ] Change the property display names
  - [ ] "Sign the assembly" becomes "Use a strong name"
  - [ ] ~"Delay sign only" becomes "Public sign only"~
- [ ] Change the description of "Use a strong name" to "Give the assembly a strong name."
- [ ] Add a `HelpUrl` to the "Strong name key file" property
- [ ] Only show this property if the project targets .NET Framework in at least one target framework (maybe)

**Comment by davkean** [comment]
Public sign is not the same as delay sign, they are two different modes.

**Comment by tmeschter** [comment]
Should we consider offering "public signing" as an option alongside full signing and delay signing? That is, is public signing a supported scenario that we should encourage?

**Comment by jjmew** [comment]
@cartermp and @mckennabarlow  Can you please provide us guidance on what we should do?

**Comment by cartermp** [comment]
I think supporting public signing seems reasonable here. Since my understanding is that it's just a matter of slapping `<PublicSign>True</PublicSign>` in the project file, yes?

The main thing is that because they are mutually exclusive modes of signing, you can only enable one or the other. See the [C# compiler switch for more details](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/publicsign-compiler-option)

**Comment by drewnoakes** [comment]
We have other mutually-exclusive sets of properties. In the new UI we have introduced a new combo box property that allows explicitly changing between modes, and showing/hiding properties according to the value selected in the combo box.

We would need to decide what options such a text box would present.

**Comment by davkean** [comment]
This would just be a combo with 3 values I think; Public Sign, Delay Sign, Fully Sign;

**Comment by cartermp** [comment]
Or perhaps four?

* No signing (default)
* Publish Sign
* Delay Sign
* Fully Sign

Not sure what the best UI gesture is for this, but the default is no signing yes?

**Comment by davkean** [comment]
Ah, yes.

**Comment by drewnoakes** [comment]
The UI has been updated slightly since this issue was opened:

![image](https://user-images.githubusercontent.com/350947/114131083-3e2f1c00-9945-11eb-8742-aeb8d67a79ba.png)

We can change the check box into a drop down list with the four options @cartermp calls out. This would then remove the "Delay sign only" check box. The "Strong name key file" text box would be visible when the drop down list has any value other than "No signing". Does that sound right?

One downside of such a change would be the reduction in explanatory text shown in the UI. Each option in the drop down would not have associated descriptive text. We could describe all the options in a single paragraph above the drop down I suppose.

**Comment by MiYanni** [comment]
As per https://github.com/dotnet/project-system/issues/8649, strong name signing will be deprecated in .NET 6.0, closing ticket.
