### ISSUE TITLE
Exclude Projects from publish

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#6996]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Exclude-Projects-from-publish/1239717?preview=true). Please vote and comment there to make sure your voice is heard._

---
<p>Hello!</p> <p>I want to use the command &quot;dotnet publish *.sln&quot; on our CI but stumpled over UnitTest-Projects which got published too. After some digging i found this <a href="https://github.com/dotnet/docs/issues/13365" target=_blank>Issue</a> which suggest to use &quot;IsPublishable&quot; in a .csproj file. Having a Option in the Project settings of Visual Studio would be nice.</p> <p>Using Visual Studio 2019 16.7.7 and .NET Core 3.1</p>

---
#### Feedback Bot on 11/1/2020, 11:35 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by cartermp** [comment]
This would need UI design work, but in general the ask seems fairly clear.

An alternative would be to put an ask on the actual build (msbuild?) to recognize test projects and not publish them by default.

**Comment by tmeschter** [comment]
We can think about adding an option for this to the new property pages implementation. We'll need to make sure that the property is handled correctly within Visual Studio as well--it would be odd to have a publishing option in VS that wasn't honored when publishing from VS.

**Comment by danielchalmers** [comment]
> An alternative would be to put an ask on the actual build (msbuild?) to recognize test projects and not publish them by default.

I would be a big fan of this! wonder why it's not already the default
