### ISSUE TITLE
Handle read-only properties. (1)

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7035]
Properties in rule files may be marked as "read only".

```xml
<StringProperty
  Name="MyProperty"
  ReadOnly="True" />
```

Currently, such properties are presented to the user as writeable.

We should expose `IsReadOnly` metadata from the back end to the UI, and update the UI to allow showing properties in a read only mode.

A potential use case here is displaying the evaluated `LangVersion` value alongside the current message that explains the value is not user-editable. The Razor SDK also produces read only properties for the Razor language version and configuration name.

- [x] Add `IsReadOnly` to project model in CPS ([PR](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/319288))
- [x] Populate `IsReadOnly` in the .NET Project System (#7141)
- [x] Modify the UI to show read only properties somehow differently (either disabled, or with alternative templates, etc) ([PR](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/327180))

**Comment by drewnoakes** [comment]
This issue was discovered while exploring the Project Properties UI for ASP.NET Web Application projects. In such projects, a "Razor Properties" page is present:

![image](https://user-images.githubusercontent.com/350947/111923248-50f6c380-8af2-11eb-9343-f798a87ee9dd.png)

The properties are coming from https://github.com/dotnet/sdk/blob/main/src/RazorSdk/Targets/Rules/RazorGeneral.xaml in which they are marked as read only.

I've filed https://github.com/dotnet/sdk/issues/16458 to work with the SDK to improve or remove that page.

**Comment by drewnoakes** [comment]
Also assigning @tmeschter as this will require back end changes too.

**Comment by drewnoakes** [comment]
https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/319288 adds `UIProperty.IsReadOnly` to CPS's project model.

**Comment by tmeschter** [comment]
@drewnoakes The back-end changes were done in #7141, right? What's left is the UI side?

**Comment by drewnoakes** [comment]
@tmeschter yes, just UI stuff now. I've unassigned you. Thanks.

**Comment by drewnoakes** [comment]
https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/327180 makes read-only properties non-editable, which is the final step in this issue (for now at least).

**Comment by drewnoakes** [comment]
All parts have been merged.
