### ISSUE TITLE
Publish managed project system symbols

### ISSUE THREAD

**Issue by swesonga** [dotnet/project-system#7062]
**Visual Studio Version**: 16.9.0

**Summary**:
Attaching to the public releases of devenv.exe and loading symbols for these assemblies fails:

Microsoft.VisualStudio.ProjectSystem.Managed.dll
Microsoft.VisualStudio.ProjectSystem.Managed.VS.dll
Microsoft.VisualStudio.ProjectSystem.Managed.VS.Clientdll

We need to verify that the symbols have been correctly published and that the sources have been indexed.

**Comment by dmonroym** [comment]
@swesonga We're now doing this in the release pipeline and should be fixed. Could you check with latest main build?

**Comment by swesonga** [comment]
Verified that the symbols for 17.0 Preview 4.1 are successfully retrieved from https://msdl.microsoft.com/download/symbols
