### ISSUE TITLE
C#/WinRT Interop projects are always up-to-date regardless of their project dependencies

### ISSUE THREAD

**Issue by swesonga** [dotnet/project-system#7067]
**Visual Studio Version**: 16.9.0

**Summary**:
C#/WinRT Interop projects are considered up-to-date after changing C++/WinRT Sources

**Steps to Reproduce**:
1.	Launch Visual Studio 2019 and go to Extensions > Manage Extensions
2.	Search for “C++” then select C++/WinRT and click on “Download”
3.	Restart Visual Studio to complete the installation
4.	Create a new Windows Runtime Component (C++/WinRT) (called “CPPWinRTInteropRepro”, for example)
5.	Click OK to accept the default target and minimum platform versions (e.g. 19041 and 17763)
6.	Add a new C# Class Library (.NET Core) project called “CPPWinRTInteropReproProjection” to your solution.
7.	Delete the empty Class1.cs file from the project.
8.	Enable “Show All Files” for both projects in the solution explorer toolbar.
9.	In Solution Explorer, right click your class library project and select “Manage NuGet Packages”.
10.	Search for the “Microsoft.Windows.CsWinRT” NuGet package and install the latest version -  https://www.nuget.org/packages/Microsoft.Windows.CsWinRT
11.	In Solution Explorer, right click the class library project and select “Edit Project File”.
12.	Update the TargetFramework element to reference the Windows SDK, e.g. “net5.0-windows10.0.19041.0”
13.	Add a new PropertyGroup to the project file with 
  `<PropertyGroup>
    <CsWinRTIncludes>CPPWinRTInteropRepro</CsWinRTIncludes>
    <CsWinRTWindowsMetadata>10.0.19041.0</CsWinRTWindowsMetadata>
  </PropertyGroup>`
14.	Save and close the CPPWinRTInteropReproProjection.csproj file.

16.	In Solution Explorer, right click the “Dependencies” node under the CPPWinRTInteropReproProjection project, select “Add Project Reference”, and select the CPPWinRTInteropRepro project.
17.	Add a new C# .NET 5 console application (e.g. ConsoleApp1).
18.	In Solution Explorer, right click the console application project and select “Edit Project File”.
19.	Change the TargetFramework to “net5.0-windows10.0.19041.0” to match the projection project.
10.	Add this property to ConsoleApp1: `<PropertyGroup><CsWinRTWindowsMetadata>10.0.19041.0</CsWinRTWindowsMetadata></PropertyGroup>`
21.	Save and close the ConsoleApp1.csproj editor/window.
22.	Install the “Microsoft.Windows.CsWinRT” NuGet package into ConsoleApp1.
23.	In Solution Explorer, right click the “Dependencies” node under the ConsoleApp1project, select “Add Project Reference”, and select the CPPWinRTInteropReproProjection project.
24.	Add this code to Program.cs: `var someObject = new Class();`
25.	Add a using statement to the top of the file: `using CPPWinRTInteropRepro;`
26.	Build ConsoleApp1. This should succeed.
27.	Open Class.idl and add a new property (i.e Int32 NewProperty)
28.	Build the C++ project.
29.	Copy the generated class.h and class.cpp files into the main CPP project (copy the files from the folder Generated Files\sources to CPPWinRTInteropRepro ? and replace them ?).
30.	Remove the static asserts that cause build to fail (comment the line that contains static_assert in class.cpp and class.h)
31.	Build the C++ project, this should succeed.
32.   Build the C++ again, until the project is marked up-to-date
33.	Reference the newly added property in ConsoleApp1 (Add the statement someObject.NewProperty = 0 to Program.cs).
34.	Build ConsoleApp1.

**Expected Behavior**:
Building the console app (which depends on the interop project) should succeed.

**Actual Behavior**:
Building the console app fails.

**User Impact**:
Users need to rebuild the interops apps manually after changing the C++/WinRT sources.

**C++/WinRT Resources**:
1. https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt
2. https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/net-projection-from-cppwinrt-component

**Comment by ocallesp** [comment]
@swesonga, steps from 25 to 32 are not clear. I added some comments. Can you help check the repro steps ?
cc. @jjmew

**Comment by ocallesp** [comment]
@swesonga 
In the description you put that the actual Behavior is "Building the console app fails.", but the title of the "initial bug is project do not trigger a build on the dependent Interop"
The first one sounds like a build issue, and the second one sounds like a FUTD issue.
Which one is correct ?

**Comment by ocallesp** [comment]
It seems that I was able to repro issue following the steps provided in here.
I see that even thought we make changes to Program.cs in ConsoleApp1, the project doesn't Build because it is up-to-date.

![image](https://user-images.githubusercontent.com/510598/113781923-43daf680-96e6-11eb-997a-ac95b9002ff1.png)

**Comment by ocallesp** [comment]
@swesonga, I see two projects skipped. Are you getting the same output ?

Build started...
1>------ Skipped Build: Project: CPPWinRTInteropReproProjection ------
1> 
2>------ Skipped Build: Project: **ConsoleApp1** ------
2> 
========== Build: 0 succeeded, 0 failed, 1 up-to-date, **2 skipped** ==========

**Comment by drewnoakes** [comment]
@ocallesp are these actually legacy projects? They're showing "Dependencies" nodes in your screenshot, which implies .NET Project System.

If they're running on the .NET Project System, turn on up-to-date check logging for more information.

**Comment by ocallesp** [comment]
@swesonga 

![image](https://user-images.githubusercontent.com/510598/114458815-8db75700-9b94-11eb-913b-c00479026f4a.png)

**Comment by ocallesp** [comment]
@drewnoakes It is not legacy. Thanks for the observation.

**Comment by drewnoakes** [comment]
@ocallesp your second screenshot shows that the FU2D check has not run before, so it will build. You need to build again to see whether (and why) the FU2D check still thinks the project needs building.

**Comment by swesonga** [comment]
The root cause of the issue here is that CsWinRT uses a response file that has a .winmd input from the C++ project (e.g.
-input "C:\...\CPPWinRTInteropRepro\Debug\CPPWinRTInteropRepro\CPPWinRTInteropRepro.winmd"). However, the .NET project system does not know of the existence of this relationship. I think the fix for this issue is to determine the best way to make this relationship explicit to the .NET project system.

**Comment by swesonga** [comment]
This issue has been fixed in https://github.com/microsoft/CsWinRT/pull/813
