### ISSUE TITLE
OrchardCore build fails in insertion PR, 'TargetFrameworkMoniker' and 'NuGetTargetMoniker' are empty

### ISSUE THREAD

**Issue by MiYanni** [dotnet/project-system#7093]
Branch: main
Failure PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/315410
Failure Test: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=1001218&environmentId=5192066&_a=release-environment-extension&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&runId=20401222&paneView=debug&resultId=100005

This error (normally) occurs when switching between `TargetFramework` and `TargetFrameworks`. However, in this insertion PR, it fails when opening in Blend using the OrchardCore project. In the test link above, you can click on the individual attempts to download the ScreenCapture.wmv to see what happens.

**Comment by jjmew** [comment]
@MiYanni  are you able to repro this issue locally?

**Comment by tmeschter** [comment]
Note that we saw the same failure in Blend, but the test in question was not opening OrchardCore.

**Comment by tmeschter** [comment]
Actually this is the PR we care more about: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/315391

**Comment by MiYanni** [comment]
Fixed in: https://github.com/dotnet/project-system/pull/7096
