### ISSUE TITLE
Assembly Version test fails

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#7095]
When commit [`32968ee` (#6885)](https://github.com/dotnet/project-system/pull/6885/commits/32968eedf3a27da6f7439d900fa92c645cbf1f2e) was introduced we didn't catch assembly version failing. This test should catch it: https://github.com/dotnet/project-system/blob/main/tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Rules/ExportedRuleTests.cs#L103

Need to investigate if we're building 42.42.42.42 on CI builds or what's the underlying issue here.

**Comment by jjmew** [comment]
@tmeschter  already spent time investigating this

**Comment by MiYanni** [comment]
This was completed by Tom here: https://github.com/dotnet/project-system/pull/7097
