### ISSUE TITLE
On retargeting a WPF project, System.Xaml is added when .NET Framework 4.0

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#71]
_From @davkean on March 23, 2016 17:33_

On retargeting a WPF flavor, it adds System.Xaml if WPF is referenced if targeting .NET Framework 4.0 or higher.

_Copied from original issue: dotnet/roslyn#10013_

**Comment by ladipro** [comment]
The issue appears to have been created back when it was believed that the new project system will replace the legacy **csproj.dll**/**msvbprj.dll**. I don't believe we're tracking this as an immediate goal anymore. @davkean please reopen with more details if I misunderstood.
