### ISSUE TITLE
Duplicate root namespace in settings file with sdk-style project

### ISSUE THREAD

**Issue by tgillbe** [dotnet/project-system#7102]
**Visual Studio Version**: 16.9.3

**Summary**:
When using an SDK-style project and vb.net, the automated tool generates a duplicate root namespace for settings files.

**Steps to Reproduce**:

1. Create a new SDK-style project for vb.net:

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <StartupObject>Test.Module1</StartupObject>
    <RootNamespace>Test</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="mscorlib" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="MySettings.Designer.vb">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>MySettings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="My Project\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
    </None>
    <None Update="MySettings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>MySettings.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>
</Project>
```

2. Add a new settings file (test file is called `MySettings.settings`).
3. Inspect the generated `MySettings.Designer.vb` file.

**Expected Behavior**:

`MySettings.Designer.vb` should not wrap the code in the `RootNamespace` namespace, as that is automatically done by vb.net. This results in a duplicate namespace (i.e. `Test.Test.MySettings`).

This is what I expect the `MySettings.Designer.vb` file to look like:

![image](https://user-images.githubusercontent.com/6849866/114063232-4d07c700-9890-11eb-84a1-0467d0436dbe.png)

**Actual Behavior**:

`MySettings.Designer.vb` has duplicated namespace:

![image](https://user-images.githubusercontent.com/6849866/114062631-a3c0d100-988f-11eb-8514-23ccc1ddd7e1.png)

**User Impact**:

Having to manually remove the namespace after saving the settings file or compile errors when referring to classes with their fully qualified name.

The correct code results when the `RootNamespace` is removed from the vb.net project but then all other classes fall out of the namespace. I'm pretty sure it doesn't do this when you use the legacy project style as the problem only showed up after switching to the SDK-style project.

**Comment by ocallesp** [comment]
@tmeschter 

In C Sharp the namespace is added
![SettingsCS](https://user-images.githubusercontent.com/510598/175388573-d93acc46-fe25-4a9a-aa58-bd6e9b2147bd.png)

and the current behavior in VB is the same
![SettingsVB](https://user-images.githubusercontent.com/510598/175388781-8f6c045d-dbbf-4808-8805-ac47e5fe8ca3.png)

SettingsSingleFileGenerator adds a namespace to CS and VB.

What I see different is that when you hover your mouse over the class definition, you will see that in VB the namespace appears twice. Have any idea of why in VB this is different ?

![image](https://user-images.githubusercontent.com/510598/175391101-2abeae44-eba6-45c7-8920-a425af507f78.png)

![image](https://user-images.githubusercontent.com/510598/175390917-33521c3e-7111-4a65-8aba-01110a1a39a6.png)

**Comment by ocallesp** [comment]
1) Define the right behavior in VB
2) Investigate (and perhaps this is not us) why we see an incorrect namespace when we hover over the class definition

**Comment by kvenkatrajan** [comment]
@ocallesp 

This is in our codebase, the namespace should be removed (legacy project system does not add additional namespace)

https://github.com/dotnet/project-system/blob/b6ca713b222980af880a7d2e812957fafe55d0f5/src/Microsoft.VisualStudio.Editors/SettingsDesigner/SettingsSingleFileGeneratorBase.vb#L141-L149
