### ISSUE TITLE
Include CmdUIContextGuid to the ConfigurationGeneral rule of the NET Core project

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#7103]
CPS gets the value of this property for VSHPROPID_CmdUIGuid. It prefers to use the value in the project snapshot. Unfortunately, because this is not defined in the NET Core project rule. It won't find it, and will fall back to a backup rule and uses the live project.

When thread pool is busy, or project hasn't been evaluated, this evaluation can be blocked, and leads into UI delays.  Due to this blocks context menu, it can slowdown the user experience especially during branch switching time.

This should be a straight change to prevent this UI delay issue.

+ @davkean

**Comment by davkean** [comment]
Should we do a pass here and make sure all these hierarchy properties are defined in our rules?

**Comment by drewnoakes** [comment]
Looking at the CPS source in `ProjectNode` for usages of `GetConfigurationGeneralPropertiesAsync` related to hierarchy properties, I see:

| Hierarchy Property | MSBuild Property | Present in .NET ConfigurationGeneral.xaml |
|-|-|:-:|
| VSHPROPID_CmdUIGuid                       | CmdUIContextGuid                | ❌ |
| VSHPROPID_PreferredLanguageSID            | LanguageServiceId               | ✔️ |
| VSHPROPID_AddItemTemplatesGuid            | AddItemTemplatesGuid            | ✔️ |
| VSHPROPID_DesignerFunctionVisibility      | DesignerFunctionVisibility      | ❌ |
| VSHPROPID_DesignerVariableNaming          | DesignerVariableNaming          | ❌ |
| VSHPROPID_DesignerHiddenCodeGeneration    | DesignerHiddenCodeGeneration    | ❌ |
| VSHPROPID_SupportedMyApplicationTypes     | SupportedMyApplicationTypes     | ❌ |
| VSHPROPID_SuppressOutOfDateMessageOnBuild | SuppressOutOfDateMessageOnBuild | ✔️ |
| VSHPROPID_AppContainer                    | WindowsAppContainer             | ✔️ |
| VSHPROPID_OutputType                      | OutputType                      | ✔️ |
| VSHPROPID_SupportedOutputTypes            | SupportedOutputTypes            | ❌ |
| VSHPROPID_TargetPlatformIdentifier        | TargetPlatformIdentifier        | ✔️ |
| VSHPROPID_TargetRuntime                   | TargetRuntime                   | ✔️ |
| VSHPROPID_OneAppCapabilities              | OneAppCapabilities              | ✔️ |

Do we want to add all of these missing properties? It's straightforward to do so.

I'll get a PR together with `CmdUIContextGuid` and we can add others if necessary.

**Comment by davkean** [comment]
I think so.
