### ISSUE TITLE
Renaming a CPP Project Does Not Update in References or Dependencies Trees in WAP or C# UWP

### ISSUE THREAD

**Issue by edwardskrod** [dotnet/project-system#7111]
**Visual Studio Version**:  16.10 Preview 2

**Summary**:
A CPP project reference in both WAP or C# UWP projects does not update when renaming a CPP project.

**Steps to Reproduce**:

1.   Create a new CPP project.   Add a Windows Application Packaging Project or a C# UWP Project.

2.  Add a project reference to the WAP/C# UWP project to the CPP project.

3. Rename the CPP project.  Right click the CPP project and select Rename. 

**Expected Behavior**:

The project reference is updated in Solution Explorer with the new name AND the project reference is updated in the .wapproj or .csproj.

**Actual Behavior**:

The project reference is not updated with the new name.

![CPP_FailsToRename_WAP_and_UWP](https://user-images.githubusercontent.com/5585130/114321312-3e1b5180-9ae8-11eb-915c-f2e41dffe5dc.gif)

**User Impact**:
Users will need to manually update the .csproj/.wapproj files and reload the projects for the UI to be updated.

**Comment by drewnoakes** [comment]
That C# project has a "References" node, so is a legacy project. It's unclear if this problem is specific to WAP projects. Requires investigation.

**Comment by drewnoakes** [comment]
This appears to be an issue with UWP projects. Closing as wont-fix.

**Comment by edwardskrod** [comment]
Bug created with UWP Cpp team.
