### ISSUE TITLE
No way to specify executable in new project properties UI

### ISSUE THREAD

**Issue by dpugh** [dotnet/project-system#7114]
**Visual Studio Version**: 31212.8.main

**Summary**: I don't see a way to specify which executable to launch as part of the project properties

**Steps to Reproduce**:

1.  Create an object file project.

2. Try to configure the debug settings for that project to launch VS (or any other executable).

3. Can't do it (or, at least, I can't find the setting).

**Expected Behavior**:

**Actual Behavior**:

**User Impact**: Very difficult to debug object library projects.

**Comment by drewnoakes** [comment]
@dpugh thanks very much for taking the time to submit feedback. I really appreciate it.

Debug settings have been moved out to a new UI. It's not available in the public 16.10p2 build, but if you're on MS internal builds then you should be able to see it.

Right now you need to click on the "Debug" label in the navigation area, then click the link that appears in the property list to launch the UI.

Once https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/316814 merges, you'll be able to edit launch profiles from the Debug menu and the Start button on the tool bar.

I'll close this for now. If any of the above isn't working for you, let me know and I'll reopen this.
