### ISSUE TITLE
Bug of git comparer

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/project-system#7130]
**Visual Studio Version**:16.9.4

**Steps to Reproduce**:

1. Create a console application and add it to git.

2. Open Program.cs, make any change and save it, compare it in git, vs treat the left document as LF, and treat the right document as CRLF, so it show there're lots of changes if unchecked `Ignore trim whitespace`.
In fact, whatever the original file and modified file, the NewLine is CRLF.
Why VS allways treat the left document as LF?

![image](https://user-images.githubusercontent.com/2529999/115434751-9f0afe00-a23b-11eb-9e53-60a986cd091d.png)

https://user-images.githubusercontent.com/2529999/115434549-6703bb00-a23b-11eb-8648-b9c54c8a0c3f.mp4

**Comment by CreateAndInject** [comment]
I remember the old version(maybe a few years ago) doesn't has this bug, if this, the option `Ignore trim whitespace` is almost useless since it always show large changes and we can't find the different whitespaces we needed.

**Comment by ocallesp** [comment]
@CreateAndInject it seems that this bug is not related to Dotnet ProjectSystem.

This is more related to the Editors used in the Git Extension.

**Comment by davkean** [comment]
@CreateAndInject Please report an issue via Help -> Send Feedback -> Report a Problem. If you paste it here, I'll route it to the editor team.

**Comment by CreateAndInject** [comment]
@davkean Please route it, and then send me the link.

**Comment by davkean** [comment]
@CreateAndInject I can report this internally, but if you would like a link to track it, you need to report via Help -> Send Feedback -> Report a Problem.
