### ISSUE TITLE
Target framework property is empty if non-canonical representation used

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7136]
There are multiple ways to specify a given `TargetFramework` in a project file.

The Project Properties UI will show an empty combo box if the non-canonical form is used.

For example `net48` works, but `net4.8` does not.

Both forms will exist in the wild.

![tfm-blank](https://user-images.githubusercontent.com/350947/115551994-1fd70200-a2ef-11eb-803a-8fc2b438b3fe.gif)

**Comment by melytc** [comment]
Closing this as this is already covered. 
![targetframework-non-canonical](https://user-images.githubusercontent.com/8518253/127087872-9707c16f-ee8f-450a-bedd-68e8dece8a74.gif)
