### ISSUE TITLE
Program Icon property must copy .ico file to project (2)

### ISSUE THREAD

**Issue by sujitnayak** [dotnet/project-system#7167]
**Visual Studio Version**: 16.10 P3 Main builds (31229.188.main on my machine)

**Summary**:
Adding program icon with new Project Properties UX has a different behavior than the previous UX as described in Actual Behavior section.

**Steps to Reproduce**:

1. Create WPF or Winforms project for .NET Core/.NET FX 5.0

2. Go to Project Properties -> Application -> Resources tab and add program icon.

3. 

**Expected Behavior**:
The .ico file gets copied to the project directory and ApplicationIcon property is written to project file with just the name of the .ico file

**Actual Behavior**:
The icon file does not get copied to project folder and the ApplicationIcon property written to project file is fully qualified path to the .ico file.

**User Impact**:
ClickOnce publish fails due to this breaking change as it expects the .ico file to be in the project directory.

**Comment by melytc** [comment]
For reference, this is the previous experience looks like:
![image](https://user-images.githubusercontent.com/8518253/119036552-b5ed5f00-b965-11eb-8b64-2cd7af4bab2a.png)

And this is the new experience:
![image](https://user-images.githubusercontent.com/8518253/119036669-d61d1e00-b965-11eb-8f7a-75b61273c5aa.png)

**Comment by drewnoakes** [comment]
See also #6457 for a very similar work item on a different property. I suspect the solution to each will look similar.
