### ISSUE TITLE
Properties - Can't find Post Build Job

### ISSUE THREAD

**Issue by MissyGH** [dotnet/project-system#7178]
**Visual Studio Version**: 4.8.04084 Community 2019 Preview

**Summary**:  I could not find the Post Build Events

**Steps to Reproduce**:

1.  Open Project Properties and search for it

**Expected Behavior**:   Obvious spot for Post Build Events

**Actual Behavior**:  Missing

**User Impact**:  Cannot use the project properties page

**Comment by jjmew** [comment]
@MissyGH What is the version of Visual Studio that you are using? The one you provided is the runtime version. Also, could you paste a screenshot of the behavior that you see?

**Comment by drewnoakes** [comment]
I added support for build events in the new project properties UI quite recently. It likely didn't make the preview being used here.

**Comment by drewnoakes** [comment]
@MissyGH build events were added in this PR: https://github.com/dotnet/project-system/pull/7119

They will look like this, once available:

![](https://user-images.githubusercontent.com/350947/114558111-af583180-9cad-11eb-8c45-785f83a457c3.png)

Will this address your concern?
