### ISSUE TITLE
debug launch properties UI does not open

### ISSUE THREAD

**Issue by KenSykes** [dotnet/project-system#7179]
**Visual Studio Version**:
16.10.0 Preview 2.1

**Summary**: 
Can't open the debug properties for a .NET Core project

**Steps to Reproduce**:

1. Create .NET Core 3.1 project

2. right click on project and choose properties

3. click debug and then "Open debug launch profile UI"

**Expected Behavior**:

Debug settings appear and can be edited.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/56104430/117205316-552b2780-ada6-11eb-96e8-48cfee4856eb.png)

**User Impact**:

Have to turn off the preview project properties UI.

**Comment by drewnoakes** [comment]
@KenSykes thank you very much for the bug report. This exception is due to only one of two components making it in to preview 2. Later build will not have this problem.
