### ISSUE TITLE
New prop pages - setting environment to be a larger font messes up checkbox alignment

### ISSUE THREAD

**Issue by cartermp** [dotnet/project-system#7181]
Using latest prop pages, set the environment font to be 15 (default is 9).

![image](https://user-images.githubusercontent.com/6309070/117342223-d4c4ff00-ae57-11eb-8d71-2674024d101b.png)

Then, check out the prop pages and notice that the check boxes are off:

![image](https://user-images.githubusercontent.com/6309070/117342289-e9a19280-ae57-11eb-9620-4418b8c3a5cd.png)

These should be aligned.

**Comment by drewnoakes** [comment]
This appears to be an issue with the core VS check box control template. We should verify whether we see this elsewhere in WPF UI.

**Comment by drewnoakes** [comment]
The check box style is defined in VS within `src\env\shell\WindowManager\Themes\CommonControlsCheckBoxStyle.xaml`. I cannot see a reliable way to align this check box for such a large font. It becomes especially tricky when the label wraps and spans more than one line of text. There isn't really the concept of a text baseline to snap to.

This problem exists throughout VS:

![image](https://user-images.githubusercontent.com/350947/130722830-e0efa95b-44df-43b9-86bc-a13c2d5580a8.png)
