### ISSUE TITLE
New prop pages - consider Advanced subgrouping for the truly advanced C# features

### ISSUE THREAD

**Issue by cartermp** [dotnet/project-system#7186]
This one feels _somewhat_ like a "we're going back to what we had" thing, but the following C# properties are quite advanced and are unlikely to every be modified by people:

![image](https://user-images.githubusercontent.com/6309070/117346667-e8bf2f80-ae5c-11eb-95b4-69e8586ae02e.png)

(Note that I checked the arithmetic overflow one myself).

Maybe they should just be moved under a subtitle called "Advanced". Thoughts?

**Comment by drewnoakes** [comment]
Moving them to an "Advanced" category seems reasonable for sure.
