### ISSUE TITLE
How to show items of a custom item type in Solution Explorer?

### ISSUE THREAD

**Issue by Eilon** [dotnet/project-system#7187]
**Visual Studio Version**: VS2019

**Summary**:

I'm working on a project (CSPROJ) that has items of a custom type, such as:

```xml
  <ItemGroup>
    <RazorComponent Include="**\*.razor" />
  </ItemGroup>
```

Now, by default the `*.razor` files are actually `Content`, so my CSPROJ actually looks like this:

```xml
  <ItemGroup>
    <Content Remove="**\*.razor" />
  </ItemGroup>
  <ItemGroup>
    <RazorComponent Include="**\*.razor" />
  </ItemGroup>
```

But now that the `*.razor` files are `RazorComponent`, they no longer show up in Solution Explorer unless I click "Show All Files".

**Steps to Reproduce**:

1. Create a CSPROJ with some `.razor` files in it, using the Razor SDK (`<Project Sdk="Microsoft.NET.Sdk.Razor">`)
2. Add this so the CSPROJ:
  ```xml
    <ItemGroup>
      <Content Remove="**\*.razor" />
    </ItemGroup>
    <ItemGroup>
      <RazorComponent Include="**\*.razor" />
    </ItemGroup>
  ```
3. Look in Solution Explorer and the `.razor` files aren't there.
4. Compilation and everything else works fine - it's just that the items don't show up in Solution Explorer

I found some seemingly related issues that I thought might help, but they don't:
* https://github.com/Microsoft/VSProjectSystem/issues/162 - Content Visible=false hides the item, but not the directories in Solution Explorer
* https://github.com/dotnet/project-system/issues/1233 - Including files outside the project cone don't show up in soln explorer

**Expected Behavior**:

I expect there to be some way to make files that are of a custom item type show up in Solution Explorer. I tried setting `Visible=true` in the CSPROJ and other things I found, but nothing worked.

**Actual Behavior**:

Files of custom item types (e.g. `RazorComponent`) don't show up in Solution Explorer:

![image](https://user-images.githubusercontent.com/202643/117511540-b982ee00-af42-11eb-948a-f16dbb7e1b6a.png)

**User Impact**:

Can't have files of custom items show up in Solution Explorer.

**Comment by davkean** [comment]
https://docs.microsoft.com/en-us/visualstudio/msbuild/visual-studio-integration-msbuild?view=vs-2019#additional-build-actions is the easiest way, otherwise, https://github.com/microsoft/VSProjectSystem/blob/master/doc/overview/contentitem_types.md.

**Comment by Eilon** [comment]
Holy smokes, this worked!

```xml
<ItemGroup>
    <AvailableItemName Include="RazorComponent"/>
</ItemGroup>
```

And I've sent a small PR to the docs that might hopefully clear this up to others in the future (assuming my edit is in fact correct): https://github.com/MicrosoftDocs/visualstudio-docs/pull/6663

**Comment by Eilon** [comment]
Closing this issue because apparently this is easy to do, as long as @davkean tells you the answer 😄
