### ISSUE TITLE
[Merged Interops] Microsoft.DotNet.IBCMerge

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#7191]
We had to change the way we did `/ibc` since now we're fetching `Microsoft.DotNet.IBCMerge` from a new feed which also requires Nuget.config file.

The current solution is perhaps a better method of doing this and given our lack of optprof we weren't really using ibc so it's hard to verify. I'll need to do a deeper analysis on this and clean up the code surrounding this

**Comment by dmonroym** [comment]
We're currently getting this from `<add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />` 

When we attempt to build we get this error:
```
"C:\a\1\s\build\proj\Build.proj" (default target) (1) ->
       "C:\a\1\s\build\proj\CoreBuild.proj" (default target) (2) ->
       "C:\a\1\s\ProjectSystem.sln" (Build;Test;Pack target) (3:2) ->
       "C:\a\1\s\src\Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.vbproj" (default target) (15:10) ->
       (ApplyOptimizations target) -> 
         C:\Users\AzDevOps\.nuget\packages\roslyntools.repotoolset\1.0.0-beta-62705-01\tools\OptimizationData.targets(51,5): error MSB3073: The command ""C:\Users\AzDevOps\.nuget\packages\microsoft.dotnet.ibcmerge\5.0.7-beta.20159.1\lib\net45\ibcmerge.exe" -q -f -partialNGEN -minify -mo "C:\a\1\s\artifacts\Release\obj\Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.dll" -incremental "C:\Users\AzDevOps\.nuget\packages\RoslynDependencies.ProjectSystem.OptimizationData\2.6.0-beta1-62205-02\content\OptimizationData\Microsoft.VisualStudio.AppDesigner.pgo"" exited with code 3. [C:\a\1\s\src\Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.vbproj]
```

**Comment by tmeschter** [comment]
Note that [MicroBuild has support for OptProf](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/700/OptProf) and I strongly recommend we leverage that.

**Comment by MiYanni** [comment]
@dmonroym Just pinging ya if you want to learn some info about this. 🤓

My evaluation of this is that the IBC Merge tool was being ran manually to merge pre-existing optimization data for the `Editors` and `AppDesigner` projects. This **did not** include either `ProjectSystem` or `ProjectSystem.VS` assemblies. From my understanding, the IBC information originated from a MyGet feed and that was deprecated.

- The latest version of the IBC data was uploaded here on March 2021: https://devdiv.visualstudio.com/DevDiv/_artifacts/feed/dotnet-aggregate/NuGet/RoslynDependencies.ProjectSystem.OptimizationData/2.6.0-beta1-62205-02/overview
- The feed endpoint for this is: https://dev.azure.com/DevDiv/DevDiv/_artifacts/feed/dotnet-aggregate
- The optimization data was last generated in October 2017:
![image](https://user-images.githubusercontent.com/17788297/149650138-f8380259-2255-4d79-b2d4-548e62f3bd94.png)
- I did not see any evidence of infrastructure to generate this optimization data, unfortunately.

My current efforts to implement OptProf will only be dealing with the `ProjectSystem` and `ProjectSystem.VS` assemblies at this time, as I'm leveraging a pre-existing test that CPS was previously using. They are new using an updated test that tests their caching feature, which doesn't matter to optimize our codepaths. Whenever we want `Editors` and `AppDesigner` to be optimized, we would need to create a test to exercise those components and then include them as part of the OptProf infrastructure.
