### ISSUE TITLE
Hide platform properties when targeting lower than .NET 5.0 (2)

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#7227]
`TargetPlatform`, `TargetPlatformVersion` and `MinimumPlatformVersion` are properties that will make sense to show for projects targeting .NET 5 or higher. We should hide them if that's not the case.

Notes: the `InterceptedTargetFramework` property contains the `TargetFrameworkMoniker` (i.e. .NETCoreApp, Version=v5.0) and the `DisplayName` (i.e. .NET 5.0). I don't think that adding a conditional visibility rule into the Application file would work, we might have to think in another way to condition these properties.

**Comment by drewnoakes** [comment]
Two ideas:

1) Include non-visible `TargetFrameworkIdentifier` and `TargetFrameworkVersion` properties, and use them in a visibility condition
   - Need the ability to plumb through non-visible properties
   - Need a custom function to compare version strings e.g. `"v10.0" > "v4.0"`

2) Add a visibility condition function that does exactly what we need for this
   - Need to verify the performance of querying properties from each `ConfiguredProject` every time this is evaluated.

**Comment by drewnoakes** [comment]
Locally, I have a visibility expression that will support this. It currently looks like:

```lisp
(has-net-core-app-version-or-greater "5.0")
```

It is backed by the `TargetFrameworkMoniker` property via the `ConfigurationGeneralPage`.

Using that expression will make a property appear only in .NET 5 and later.

**Comment by drewnoakes** [comment]
See #7281 for an example of only showing properties from .NET Core 3.0 and later.
