### ISSUE TITLE
Re-create VB References property page (10)

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#7238]
We need to re-create the VB References property page in the new property page system.

For reference, this is the References property page as it currently appears for VB WinForms apps targeting .NET 5:

![image](https://user-images.githubusercontent.com/10506730/118734414-350e5600-b7f3-11eb-965e-b76181bef962.png)

I don't think this needs to be an exact copy of the existing page. For example, references can be managed via the Dependencies node, so I don't think we need to recreate that control here. However, I believe this is the only way to manage the "Reference Paths" and the "Imported namespaces".

_This work was identified as part of #6935._

**Comment by drewnoakes** [comment]
Triage note: Need to validate which parts of this experience need to be brought forward.

cc: @KathleenDollard @cartermp
