### ISSUE TITLE
Expose UseWindowsForms and UseWPF properties

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#7239]
I believe these properties are only meaningful on .NET Core 3.0/3.1, but it would still be useful to have them as they control whether or not WinForms and WPF functionality is available to the project.

The Application property page seems like a natural place for these. However, we only want them to show for projects that target .NET Core 3.0/3.1.

_This work was identified as part of #6935._

**Comment by RussKie** [comment]
Correct. This is how the SDK imports the Windows Desktop SDK and required desktop frameworks (Windows Forms and/or WPF).
