### ISSUE TITLE
Expose UseCompatibleTextRendering in the new property pages

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#7241]
This came up while investigating #6935. It only applies to VB apps, as best I can tell. Part of the work will involve understanding what it does, and how/where the underlying data is stored.

**Comment by drewnoakes** [comment]
These values are stored in a `.myapp` file.

**Comment by melytc** [comment]
After a quick sync-up with @KlausLoeffelmann, we would not want to surface this property in the UI (at least not now); it can be modified through code in the ApplicationEvents.vb: https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.applicationservices.windowsformsapplicationbase.usecompatibletextrendering?view=windowsdesktop-6.0
