### ISSUE TITLE
Support "Sign the ClickOnce manifests"

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7244]
The legacy property pages have an option to sign ClickOnce manifests:

![image](https://user-images.githubusercontent.com/350947/118753806-12d70f80-b8a9-11eb-90ed-2f701e5456eb.png)

We need to determine whether this UI is still relevant for today's projects.

Note that for SDK-style projects, even those that target .NET Framework, the UI shows:

![image](https://user-images.githubusercontent.com/350947/118753920-4a45bc00-b8a9-11eb-9da2-f4f92cef953c.png)

**Comment by MiYanni** [comment]
This is not needed. See my notes here: https://github.com/dotnet/project-system/issues/7378#issuecomment-896387764
