### ISSUE TITLE
New csproj properties page is hard to read (1)

### ISSUE THREAD

**Issue by Treit** [dotnet/project-system#7250]
**Visual Studio Verison**
Visual Studio Enterprise 2019 Preview - Version 16.10.0 Preview 4.0

**Summary**:
After upgrading to a new Visual Studio version, I see that there is a new preview Project Properties UI.

I find the design and layout of this UI to be very poor for usability. It is very hard to read as the UI makes poor use of whitespace, has oddly-sized input boxes and does not wrap descriptive text in a readable way.

**Steps to Reproduce**:

1. In Solution Explorer, right-click on the project and choose Properties.

**Expected Behavior**:
An aesthetically pleasing, easy to read properties dialog is presented.

**Actual Behavior**:
A hard-to-read, ugly properties dialog is presented.

**User Impact**:
The current design is likely to cause users to turn off the new dialog as it is much less pleasing to use than the old one.

I think the following screenshot illustrates the issue. Notice how the descriptive text running all the way to the full width of the screen clashes greatly with the small drop-down input box.

![image](https://user-images.githubusercontent.com/8271812/119051293-d8887380-b977-11eb-8d06-4fca00cff538.png)

I also find that the overall whitespace between settings seems excessive, making everything feel very spread out. The font size also seems excessively small.

Overall I just find the dialog to be hard to read and unappealing to use.

**Comment by drewnoakes** [comment]
We discussed this a little on Discord.

One clear action to take here is to limit the width of the description text, so we don't display these hard-to-read run on sentences, as shown.

**Comment by drewnoakes** [comment]
I've set a maximum width on the description text to improve readability of property descriptions when the editor is resized to be very wide.

## Before

![image](https://user-images.githubusercontent.com/350947/119799929-e6159e80-bf1f-11eb-9793-5fed91668122.png)

## After

![image](https://user-images.githubusercontent.com/350947/119799986-f2016080-bf1f-11eb-866a-24b9c3ed1ab7.png)
