### ISSUE TITLE
Plumb non-visible project properties through to the UI (1)

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7251]
It would be useful for the client to have non-visible properties available for use in visibility conditions.

- [x] Add `IsVisible` to the project model in CPS ([PR](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/325905))
- [x] Stop filtering non-visible properties in the .NET Project System ([PR](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/327511))
- [x] Filter non-visible properties from the UI ([PR](https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/327511))

**Comment by tmeschter** [comment]
@drewnoakes Do you think this is a Must Have for Dev17 GA?

**Comment by drewnoakes** [comment]
@tmeschter yes. It unblocks other must-have scenarios such as #7227.

**Comment by drewnoakes** [comment]
This has been addressed by in-flight PR and can be closed once they merge.

**Comment by drewnoakes** [comment]
All parts have been merged.
