### ISSUE TITLE
New SDK causes output path properties to show absolute paths

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7252]
VS Version 16.10.0 Preview 3.0 [31303.267.main]

![image](https://user-images.githubusercontent.com/350947/119067010-76397c80-ba24-11eb-998d-72d4a54ab4ff.png)

I believe this started after installing VS2022 internal previews, presumably with a preview of SDK 6.

These properties are now resolving as full paths. My concern here is that it may encourage users to bake an absolute path into their project files, which would not be portable.

@dsplaisted are you aware of this change and its impact on the UI?

**Comment by dsplaisted** [comment]
This is coming from the Arcade .targets files which use a common output directory.  What happens with a vanilla project outside of Arcade or other repo infrastructure?

**Comment by drewnoakes** [comment]
Thanks @dsplaisted, if this is Arcade then we can close this.

I'll verify.

**Comment by drewnoakes** [comment]
There's no action to take here.
