### ISSUE TITLE
Create fwlink URLs for all property HelpUrls (1)

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7262]
The properties shown in the new Project Properties UI and Launch Profile UI are specified in XAML rule tiles. Each property may have a `HelpUrl` associated with it. These URLs should go via the fwlink redirection service, so we can retarget them in future if they break due to changes in the location of documentation.

**Comment by tmeschter** [comment]
@MiYanni Let me know if you have any questions.

**Comment by drewnoakes** [comment]
An extra step here (thanks to @RussKie for pointing this out):

- Go through our _existing_ fwlinks and make sure they don't reference `en-us` culture.

   ```diff
   -https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props-desktop
   +https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props-desktop
   ```

   https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master#locale-codes-in-external-links
