### ISSUE TITLE
Support source generator debug launch profiles

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7289]
Roslyn source generators may be debugged using a `DebugRoslynComponent` command name.

We need to support this in the new Launch Profiles UI.

An example: https://github.com/davidwengier/Trains.NET/blob/main/src/Trains.NET.SourceGenerator/Properties/launchSettings.json

**Comment by drewnoakes** [comment]
FYI @chsienki

**Comment by tmeschter** [comment]
Ideally the UI for this command would live in the same place as the command implementation. Do we know where that is?

Or, more to the point: it probably shouldn't live here. :-)

**Comment by drewnoakes** [comment]
> Ideally the UI for this command would live in the same place as the command implementation.

Agreed.

> Do we know where that is?

It's in the Roslyn SDK:

https://github.com/dotnet/roslyn-sdk/blob/d16bce93b36d078682776b93d5435287b038783f/src/VisualStudio.Roslyn.SDK/ComponentDebugger/Constants.cs#L11

There's a [custom `ILaunchSettingsUIProvider`](https://github.com/dotnet/roslyn-sdk/blob/d16bce93b36d078682776b93d5435287b038783f/src/VisualStudio.Roslyn.SDK/ComponentDebugger/LaunchSettingsProvider.cs) too, for the legacy property pages.

I'll transfer this issue to that repo.

**Comment by drewnoakes** [comment]
I ended up filing a new issue with more context on what's required: https://github.com/dotnet/roslyn-sdk/issues/850
