### ISSUE TITLE
New Property Pages: Adjust control theme

### ISSUE THREAD

**Issue by MiYanni** [dotnet/project-system#7292]
I noticed that with the new Dev17 dark mode, it is harder to 'see' the controls for each property.
![image](https://user-images.githubusercontent.com/17788297/120537500-38c8dd80-c39a-11eb-9d15-de34a26c2718.png)

I took a look at VSCode, and realized that the dark theme for them has 'inverted' controls.
![image](https://user-images.githubusercontent.com/17788297/120537640-5f871400-c39a-11eb-8848-9340c1b71d99.png)

I think this would be a good idea to basically make the background color of each control dark grey and the text white on the dark theme. Thoughts?

**Comment by tmeschter** [comment]
The property pages are using the styles provided by VS, so like it or hate it they are consistent with the rest of VS in dark mode. :-) We would need to have a compelling reason to deviate since that places the burden on us to maintain a separate set of styles.

**Comment by drewnoakes** [comment]
This is feedback for the UX team. Any change here must be made across the whole product.

If such a change was made centrally, we would pick it up automatically.

**Comment by MiYanni** [comment]
Here, I don't want the UI changes for the entire product. It would update elements like this:
![image](https://user-images.githubusercontent.com/17788297/120569742-65491d80-c3cb-11eb-8d4d-2d2b3e7b8ee8.png)
and this:
![image](https://user-images.githubusercontent.com/17788297/120569749-6aa66800-c3cb-11eb-8f4e-043c1373f7e1.png)
which is not desired.

But I think for property pages, which is built around several screens of these controls and text descriptions, it makes sense to have the controls themselves be more obvious. It is a different use-case for these controls IMO.

**Comment by MiYanni** [comment]
Suggestion by @chryw
Could you try using a darker background color token `CommonControl.PageBackground` for the document content area, instead of using the `Environment.WindowBackground`, which is supposed to be the color of the bigger container color? This may help the input controls to pop a little bit. Here's an example of what it may look like with a `#1A1A1A` content area background.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/17788297/123355016-a12e5900-d519-11eb-86f4-cd8b3ce3c576.png)

**Comment by drewnoakes** [comment]
@MiYanni I will push an update that sets the editor background in the next day or so as part of theming changes.

**Comment by drewnoakes** [comment]
Following up here: when I looked at this there wasn't a clear theme colour that looked sensible in both light and dark themes, so I parked my investigation.

**Comment by chryw** [comment]
@drewnoakes you should set different colors for different themes. Colors will only pass accessibility requirement for text in either dark or light background.
BTW there will be new updates coming for Preview 3 release. The common controls now look more like VS Code (and Win11), where at initial state the border is not visible, the background is brighter than the environment. At focused/expanded state, the accessible border will show up.
![image](https://user-images.githubusercontent.com/7075677/128077404-3500431e-56a7-415e-a5a2-7b5f0c3eb69a.png)

**Comment by drewnoakes** [comment]
> you should set different colors for different themes. Colors will only pass accessibility requirement for text in either dark or light background

@chryw I'm not specifying any _colours_ myself. I'm looking for a brush key for the background. Ideally it would have the same background colour as the code editor. I don't know what resource key the editor uses for its background though. Do you know what it is, or&mdash;even better&mdash;how I would work this out myself?

**Comment by drewnoakes** [comment]
@MiYanni do you still feel there is something to improve here? I believe we're following the expected VS theming, and I'm not sure what action to take at this point.

**Comment by MiYanni** [comment]
The current theme and controls are looking significantly better now:
![image](https://user-images.githubusercontent.com/17788297/132763954-48f510ff-83bd-4f69-915c-e48d3be2c6bf.png)

This is looking quite similar to the VSCode screenshot I had in the original issue description. At this point, I will close this issue as it has been addressed sufficiently.
