### ISSUE TITLE
Trigger In-Product-Acquisition when opening a project targeting a TFM that is not installed

### ISSUE THREAD

**Issue by swesonga** [dotnet/project-system#7296]
**Summary**:
Visual Studio checks .NET Framework projects to determine whether the frameworks they target are installed. It then prompts the user to acquire missing targeting packs if necessary. This is a request to improve the experience for .NET Core projects so that they also trigger IPA if the TFMs they use are for SDKs not installed on the machine.

**Comment by tmeschter** [comment]
@ocallesp Is this work complete?

**Comment by ocallesp** [comment]
The IPA to detect missing runtimes is implemented in [MissingSdkRuntimeDetector](https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Runtimes/MissingSdkRuntimeDetector.cs)
