### ISSUE TITLE
Dev17: Old property pages crash VS intermittently on tab switching

### ISSUE THREAD

**Issue by MiYanni** [dotnet/project-system#7297]
### Repro Steps
1. Open VS with a project that is a csproj.dll-based (.NET framework).
2. Open the project properties.
3. Click quickly through the tabs of the property pages.
4. Observe that VS will freeze and crash.

### Details
I tested this several times, and in conjunction with the changes in https://github.com/dotnet/project-system/pull/7270. Those changes did not affect this issue. I tested this (with same solution and projects) in Dev16.10 and could not repro. This seems to be specific to Dev17.

### Repro GIF
![VSCrashOnPropPageTabSwitching](https://user-images.githubusercontent.com/17788297/120705194-5a929500-c46c-11eb-8b56-e6a94e249a17.gif)

**Comment by jjmew** [comment]
@MiYanni can you get a dump?

**Comment by MiYanni** [comment]
I may have hit it while debugging.
![image](https://user-images.githubusercontent.com/17788297/121437827-bf039780-c937-11eb-89a6-f3a65c49b528.png)

**Comment by MiYanni** [comment]
Went and set up crash dump collecting on my system. However, I can no longer cause the issue to repro. I had it happen a dozen times on whichever build of VS I was using at that time. But now when I actually go to get a dump, can't cause it to crash anymore. 🙄 I am even trying the same solution shown in the GIF.

**Comment by drewnoakes** [comment]
There was a feedback ticket about this recently. It was fixed by the WinForms team if I remember correctly.
