### ISSUE TITLE
XBAP Debugging

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#73]
_From @davkean on March 23, 2016 17:23_

Tracking the XBAP debugging support in the WPF flavor.

_Copied from original issue: dotnet/roslyn#10009_

**Comment by davidwengier** [comment]
> _Posted by @davkean in https://github.com/dotnet/project-system/issues/4248#issuecomment-439230481_
> XBAP isn't going to be supported

Based on the above, is this job needed?

**Comment by davkean** [comment]
This might be needed for legacy compat - my comment above was regards .NET Core 3.0.

**Comment by kvenkatrajan** [comment]
@ladipro  please confirm if this can be closed here and an alternate internal issue will be added and tracked

**Comment by ladipro** [comment]
The issue appears to have been created back when it was believed that the new project system will replace the legacy **csproj.dll**/**msvbprj.dll**. I don't believe we're tracking this as an immediate goal anymore. @davkean please reopen with more details if I misunderstood.
