### ISSUE TITLE
Missing "Open in explorer" in solution explorer context menu for SQL CLR project

### ISSUE THREAD

**Issue by ahdung** [dotnet/project-system#7309]
**Version Used**: 
VS2019 16.10
Sql Clr project

![微信截图_20210607113022](https://user-images.githubusercontent.com/12094247/120955562-3a244c80-c784-11eb-8044-25fb3e73212e.png)

I remember this exist until 16.9, but now missing, please put it return back. Thanks.

**Comment by davkean** [comment]
@ahdung Please use Help -> Send Feedback -> Report a Problem inside Visual Studio so that this can be routed to the correct team. The dotnet organization does not own this project type.
