### ISSUE TITLE
Show correct TargetFramework values on dropdown property

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#7310]
In #7132 we moved from consuming the rule `SupportedTargetFrameworkAlias` from the MSBuild target `GenerateSupportedTargetFrameworkAlias`, to read the items `SupportedTargetFramework` from the SDK (https://github.com/dotnet/sdk/pull/17255).

In the old properties pages, there is some logic to detect which framework is being targeted (.NET Core, .NET Framework, .NET Standard) and given that, filter the supported TargetFrameworks list.

We need to add that logic into the new Project Properties UI.

Note: the `SupportedTargetFramework` item is the combination of the 3 items: `SupportedNETCoreAppTargetFramework`, `SupportedNETStandardTargetFramework`, `SupportedNETFrameworkTargetFramework` [Microsoft.NET.SupportedTargetFrameworks.props](https://github.com/sfoslund/sdk/blob/36876246b7dd181fe6d69d7fa68ba454c916aed4/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props) . We could capture these in individual rule files to populate the dropdown after detecting which framework the user is targeting.

**Comment by jjmew** [comment]
@melytc any concerns on getting this done in 17.0?
