### ISSUE TITLE
Launch Profiles UI doesn't honor property visibility (2)

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#7318]
**Steps to Reproduce**:

1. Add the following property to ProjectDebugPropertyPage.xaml:

  ``` xml
  <StringProperty Name="MyOtherProperty"
                  Visible="False" />
  ```

2. Ctrl+F5 to run VS in the experimental hive (the updated .xaml file will be picked up).

3. Create a new C# Console App targeting .NET 5 (or any .NET Core, really)

4. Open the Launch Profiles UI

**Expected Behavior**:

"MyOtherProperty" does not show in the UI.

**Actual Behavior**:

The property does in fact show up:

![image](https://user-images.githubusercontent.com/10506730/121965185-7fff8880-cd21-11eb-81e4-ab61850dfa2d.png)

**User Impact**:

Users see properties they shouldn't.

**Comment by tmeschter** [comment]
Context: The WebTools team already extends this page to add several settings for their scenarios, but they also want to remove the "Use remote machine", "Remote machine name", and "Authentication mode" properties as these are not meaningful for their scenarios. This is supported, and can be accomplished by redefining the property with different settings (in this case, `Visible="False"`).

I've debugged through the back end and the Project Query API is returning the expected values, and in the front end I can see that `Property.IsVisible` returns "false" for these properties. I can't tell why the property still displayes.

**Comment by drewnoakes** [comment]
This not just about "permanently" non-visible properties. The bug also relates to dynamic visibility, as seen when toggling the "Use remote debugging" check box.

**Comment by drewnoakes** [comment]
Fixed in https://dev.azure.com/devdiv/DevDiv/_git/CPS/pullrequest/340758.
