### ISSUE TITLE
Hide property page when all child properties are non-visible

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7319]
Currently if a category has no visible properties, it is hidden.

The UI should also hide a page if all its children are non-visible. Otherwise we may end up with a top-level navigation section in the tree that has no corresponding items in the list.

**Comment by MiYanni** [comment]
Confirm if this is done already.

**Comment by drewnoakes** [comment]
This was fixed in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/344681.

I actually filed a dupe of this issue in #7490.
