### ISSUE TITLE
Create extension point for default launch profiles

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#7327]
Currently the `LaunchSettingsProvider.UpdateProfilesAsync` method ensures that there is always at least one launch profile associated with the project. It does this by creating a profile matching the project name and with a launch command of "Project" if the launchSettings.json file is missing or is present but contains no profiles.

Without at least one launch profile we don't know how to start the app; if you try you get cryptic error messages from the debugger. This default profile allows us to properly start console, WinForms, and WPF apps "out of the box" without forcing them to include a trivial launchSettings.json in their project template, or requiring the user to that trivial profile later.

This approach does not work so well for other project types, however. For example, the "Project" launch command is not particularly useful for .NET MAUI apps. Those generally use the "iOS" or "Android" launch commands to deploy to an emulator, and they generate a number of in-memory profiles targeting different devices to do this. The default profile is still hanging around, however, and if the user selects it and tries to run they'll get cryptic deployment errors.

The default profile could be deleted, but it would be automatically re-created the next time the project system noticed the launchSettings.json was empty or missing.

To better handle this scenario, we could create a new extension point for the `LaunchSettingsProvider` to support different default launch profiles, or even no default at all. I imagine the interface would look something like this:

``` C#
[ProjectSystemContract(ProjectSystemContractScope.UnconfiguredProject, ProjectSystemContractProvider.Extension, Cardinality = ImportCardinality.ZeroOrMore)]
public interface IDefaultLaunchProfileProvider
{
    ILaunchProfile? CreateDefaultProfile();
}
```

Implementations of this interface would be tagged with `[AppliesTo(...)]` attributes so they are only picked up by the appropriate project types, as well as `[Order(...)]` attribute to specify a priority. The `LaunchSettingsProvider` would import all applicable implementations into an `OrderPrecedenceImportCollection`. When it is unable to find a launchSettings.json, it consults the highest-priority implementation (and only that one) to see if it wishes to create a default.

The project system itself would provide an implementation of this interface with the lowest-possible priority that creates the same default as today.

**Comment by joj** [comment]
@tmeschter this is my first try at it: https://github.com/dotnet/project-system/pull/7329. It's failing tests because the project in those tests doesn't have capabilities. I need your help with that one, I'm not sure how to properly modify that test. Thanks! J
