### ISSUE TITLE
New Property Page doesn't have the WebView2 debugging option

### ISSUE THREAD

**Issue by rakatyal** [dotnet/project-system#7333]
We added the support for WebView2 debugging in .Net Core apps in VS [here](https://github.com/dotnet/project-system/pull/6779). To enable it, users had to select the option in the debug properties page:

![image](https://user-images.githubusercontent.com/12533467/122614004-aa5f8780-d03a-11eb-9b4f-01a7ca99d915.png)

However, the new properties page doesn't show the UI option anymore. This will block our customers to enable and use JavaScript debugging in WebView2.

![image](https://user-images.githubusercontent.com/12533467/122614081-d2e78180-d03a-11eb-86cb-0c67254e5a45.png)

**Comment by tmeschter** [comment]
Note that when we add this, we need to disable it for WebTools by updating the "extension" page in WebTools to hide the property.
