### ISSUE TITLE
VS17 new dark theme dim foreground in Solution Explorer

### ISSUE THREAD

**Issue by Swiftpaws** [dotnet/project-system#7335]
Compared to the old dark theme the foreground in the solution explorer window is rather dim, which strains my eyes.

(This is just personal feedback)

![image](https://user-images.githubusercontent.com/18440081/122653406-80928780-d144-11eb-901d-1ec61d86c1a7.png)

**Comment by drewnoakes** [comment]
@Swiftpaws thanks for the feedback. The new dark theme is not part of this repo (nor is it on GitHub), so it's not possible for us to track this feedback here. Could you use the "Report a problem" feature of VS to submit a ticket? That will allow it to be routed to the correct team. If you paste a link to your feedback ticket here, I will make sure it is seen by the right people.

**Comment by Swiftpaws** [comment]
@drewnoakes thanks for your reply. I have created an issue over at [devcommunity](https://developercommunity.visualstudio.com/t/VS17-new-dark-theme-dim-foreground-in-So/1455124)

**Comment by drewnoakes** [comment]
Thanks. I have followed the issue and will make sure it is triaged appropriately.
