### ISSUE TITLE
Improve Project Properties UI tab navigation

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#7350]
When editing a property and hitting tab, focus gets lost from the next property.
![tab-navigation](https://user-images.githubusercontent.com/8518253/123016768-30076e00-d380-11eb-937c-7a71ffe48372.gif)

**Impact:**
User is confused where the focus is and disrupts their productivity.

**Comment by drewnoakes** [comment]
I believe this is a duplicate of #6898.
