### ISSUE TITLE
Disable edit functionality to property's preview

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#7352]
Currently a user can tab or select a property's preview and try to edit it (the changed value is not refreshed back to the property's value itself, so at least that's good). I think we should make them read-only properties. Not sure if this was something asked from the accessibility test coverage @drewnoakes.
![preview-properties](https://user-images.githubusercontent.com/8518253/123017338-3c3ffb00-d381-11eb-9961-392d1f3125c6.gif)

**Impact:**
 User is confused why the field is editable, but has no real change.

**Comment by drewnoakes** [comment]
This is not supposed to be editable. It is supposed to be selectable and copyable.

**Comment by drewnoakes** [comment]
Fixed in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/332975

![evaluated-value-text-box-interaction](https://user-images.githubusercontent.com/350947/123028666-166b3280-d423-11eb-937b-e7e4a3c8276d.gif)

**Comment by drewnoakes** [comment]
Fix merged.
