### ISSUE TITLE
The Settings for a WinForms App cannot be created or edited from the new Project UI

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/project-system#7355]
As a developer, I want to add a settings file to my WinForms or WPF Apps or edit an existing one.
With the new Project Properties UI, I cannot do this.

Question: 
* Do we want this feature for the new Project UI?
* If yes, how would the type editors, which would need to talk to the core process to resolve the types and get the correct editors, fit into this?
* If no, what would be the alternative for WinForms and WPF to tackle this?

Also @merriemcgaw, @OliaG, @KathleenDollard, @RussKie, @Pilchie  fyi.

**Comment by drewnoakes** [comment]
@KlausLoeffelmann I've added you to an email about properties for WPF. I've previously discussed WinForms properties with @RussKie as well.

What properties would you want for WinForms?

> If yes, how would the type editors, which would need to talk to the core process to resolve the types and get the correct editors, fit into this?

Can you elaborate on this? I'm not sure what you mean by type editors. An example of such a property would help clear any confusion up here I think.

**Comment by drewnoakes** [comment]
Also I should point out that the new Project Properties UI and Launch Profiles UI are extensible, and that extensibility code should most likely not live in this repo. It would make more sense for each component to own its own properties. We will of course support setting this up, and we have docs to help here too: https://github.com/dotnet/project-system/tree/main/docs/repo/property-pages

**Comment by drewnoakes** [comment]
Ah, I mistook your use of "settings" to mean "properties". I see now you're talking about this feature:

![image](https://user-images.githubusercontent.com/350947/123195878-3d416b80-d4ec-11eb-85ff-82e104d29bd2.png)

Your question also applies to "Resources".

Neither settings nor resources fit within the new Project Properties UI. They have an arbitrary number of items, which doesn't fit our property-centric view in that experience.

For the same reason, we pulled launch profiles out to their own UI. The standalone settings/resource editors continue to work. The remaining question is about discoverability for users who previously only used these editors via the application designer.

**Comment by merriemcgaw** [comment]
Thanks @drewnoakes for the details.

**Comment by jjmew** [comment]
This will be tracked by https://github.com/dotnet/project-system/issues/7373
