### ISSUE TITLE
VS2019 visualized file order is different with the order defined in the project file

### ISSUE THREAD

**Issue by albertwoo** [dotnet/project-system#7359]
**Visual Studio Version**: 2019

**Summary**:
![image](https://user-images.githubusercontent.com/8017681/123214646-11c57d80-d4fa-11eb-8f19-9bd2b2aef2bb.png)

**Steps to Reproduce**:
Reproduce repo:
https://github.com/slaveOftime/Fun.Blazor

**Expected Behavior**:
Visualized file orders in vs should be the same as in the project file for fsharp

**Actual Behavior**:
Mess

**User Impact**:
Code file structure inconsistence.

**Comment by jjmew** [comment]
This is CPS. This will be tracked internally by https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1355397
