### ISSUE TITLE
Environment variables input

### ISSUE THREAD

**Issue by BenyErnest** [dotnet/project-system#7361]
**Visual Studio Version**:
Microsoft Visual Studio Community 2022 Preview
Version 17.0.0 Preview 1.0

**Summary**:
![image](https://user-images.githubusercontent.com/12765321/123315405-af6c7d00-d4f9-11eb-830e-dc3fc3a6eb70.png)

It is hard to read the environment variables if all are in the same text field and separated by comma, it would be nice if these could be like the ones in Windows 10 system environment variables.

**Comment by drewnoakes** [comment]
Thanks @BenyErnest, completely agree. We are tracking this in #7330 👍
