### ISSUE TITLE
Is VS2022 going to be added to the roadmap? Any info would be appreciated.

### ISSUE THREAD

**Issue by VisualMicro** [dotnet/project-system#7371]
**Visual Studio Version**: 2022

**Summary**: I am not sure if this is the correct way to ask about a version for vs2022? 

**Steps to Reproduce**:

1.  Unable to use in vs2022. Attempting to register a xaml debug flavour to launch the midebugger, 

**Expected Behavior**: Launch should work > Microsoft.VisualStudio.ProjectSystem.VS.Debug

**Actual Behavior**: Debugger fails to launch, Code is ignored > DebugLaunchProviderBase : IDebugLaunchProvider, IDebugQueryTarget

**User Impact**: Unable to debug C++ projects using GDB

**Comment by jjmew** [comment]
The best way to report this type of issue is to open a feedback ticket by using the Send Feedback button at the right top corner of Visual Studio. You can mention that this is likely to be related to CPS. That will help route the issue to the team that owns CPS
