### ISSUE TITLE
C# Hot Reload- Need to add ENABLE_XAML_DIAGNOSTICS_SOURCE_INFO=1 Need to DebugLaunchOptions

### ISSUE THREAD

**Issue by chabiss** [dotnet/project-system#7372]
**Summary**:
As part of the  ProjectLaunchTargetsProvider,  We need to include 'ENABLE_XAML_DIAGNOSTICS_SOURCE_INFO=1' as an environment to be set for Ctrl-F5 executables so that XAML Hot Reload can work well with C# Hot Reload on Ctrl-F5

**Comment by tmeschter** [comment]
@chabiss How would I test this to ensure it is working as expected?
