### ISSUE TITLE
Package Icon property needs to add item to project with metadata (3)

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7376]
When an icon is added to a package, the icon file must be shipped inside the package itself.

In order to do this, the icon must be added to the project as an item, as well as being specified as a property. That item must have metadata to include it in the package, and to specify the path within the package.

The legacy project properties handles this correctly. We should reproduce that behaviour.

**Comment by drewnoakes** [comment]
This is very similar to #6457, where the README file is included in the package. The legacy pages do not support README files in the package, but the same approach applies to both properties so the delta between fixing one versus two properties here is likely very small.

**Comment by drewnoakes** [comment]
Notes to triage team: We added this as `must-have` on the assumption that it is similar to #7167, which is also `must-have`.

**Comment by MiYanni** [comment]
Prior experience:
![image](https://user-images.githubusercontent.com/17788297/125527606-67e72ab6-47c1-4e4c-8ff4-728c13c27aa2.png)

Produces:
```xml
  <PropertyGroup>
    <PackageIcon>shell32_192.ico</PackageIcon>
    <PackageIconUrl />
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\..\Code\project-system\tests\Microsoft.VisualStudio.Editors.UnitTests\shell32_192.ico">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
```
