### ISSUE TITLE
Investigate ClickOnce properties (1+?)

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7378]
We should investigate whether we need to port any ClickOnce-related properties to the new project properties system.

See also #7244.

**Comment by MiYanni** [comment]
### Summary
This feature is not needed within the .NET project system. It is rolled into creating a publish profile and is handled by the publish profile wizard.

### Documentation
https://docs.microsoft.com/en-us/visualstudio/deployment/quickstart-deploy-using-clickonce-folder?view=vs-2019

### Repro
For ClickOnce to be available, you need to install the ClickOnce Publishing tool in the VS Installer:
![image](https://user-images.githubusercontent.com/17788297/128948178-3ea15349-3127-4139-8bd9-1956917558aa.png)
After adding it, the option to select ClickOnce publishing appears:
![image](https://user-images.githubusercontent.com/17788297/128949159-55f3d607-f7cc-4fbf-9456-7ee2a387622c.png)
Within the wizard for making a publishing profile, you can sign the ClickOnce manifest:
![image](https://user-images.githubusercontent.com/17788297/128949189-08e7f8e6-5aca-47fb-ab61-b149be9909a8.png)
