### ISSUE TITLE
Re-create VB WPF Application property page

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7379]
We need to recreate the VB Application property page for WPF projects in the new project properties system.

---

This is the WPF Application property page for a legacy project (.NET Framework):

![image](https://user-images.githubusercontent.com/350947/124107919-0d283880-daa9-11eb-9408-acb965d4e6b7.png)

Highlighted areas are features the new experience is currently missing.

---

This is the WPF Application property page for a .NET Core (SDK-style) project:

![image](https://user-images.githubusercontent.com/350947/124108307-727c2980-daa9-11eb-99e9-7da8ef59d837.png)

It has fewer features than the .NET Framework equivalent.

**Comment by tmeschter** [comment]
Really there are three WPF-specific items here:

- "Startup URI" drop down
- "Shutdown mode" drop down
- "Edit XAML" button

The last opens the Application.xaml file in the text editor (as opposed to the design mode). That's pretty straight forward.

The other two end up changing values in the Application.xaml file, which can also be done by editing the .xaml itself. In that case you will get XAML Intellisense support.

The "View Windows Settings" and "View Application Events" buttons seem to function the same as they do in WinForms apps.

We may be able to get away without this, or at least it isn't the highest priority.
