### ISSUE TITLE
Launch Profiles window should allow line breaks in command lines

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/project-system#7392]
**Visual Studio Version**: 17.0 preview2 31430.40.main

When preparing a long/complex command line for debugging a project, it hugely boosts readability to allow newlines in the command line. This allows you to put each argument on its own line, for example.

I did try just updating launchSettings.json to put `\n` in the command line but I found that it introduced args which consisted of just `\n`, for example. I believe some of the underlying handling would need to be updated for this to work.

**Comment by drewnoakes** [comment]
Legacy does not support this. It would be a nice improvement, potentially involving changes beyond just the project system.
