### ISSUE TITLE
Solution Close Perf: UpToDateCheckImplicitConfiguredInputDataSource/UpToDateCheckConfiguredInputDataSource uses sync dispose

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#7409]
Two UpToDateCheck dataflow blocks use synchronousDisposal = true, which forces them to be disposed on the UI thread. It doesn't feel they need to be.

**Comment by drewnoakes** [comment]
@lifengl in #7414 I've changed these, and also several other types in the repo.
