### ISSUE TITLE
Add a shortcut for creating interface like class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#7410]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-a-shortcut-for-creating-interface-li/1458738)._

---

Can you add an _Interface_ command alongside the _Class_ command in this menu?

![image](https://user-images.githubusercontent.com/350947/126719572-117c02a1-ddd1-4521-9c93-cd984818b19f.png)

**Comment by jjmew** [comment]
@mikadumont I believe this is owned by the VS team hence needs to be tracked on Azure DevOps
