### ISSUE TITLE
New Property Pages: Property delay on update

### ISSUE THREAD

**Issue by MiYanni** [dotnet/project-system#7421]
The information below is from testing I did related to the Package Icon property changes I did. Basically, the value gets filled in as an absolute path after initially selecting a value in the Browse dialog. Then, there is a delay between when that value is updated to be the proper relative path that is returned by the value interceptor.

> So, I'm not sure what to make of this. I never provide a fullpath to any of the value interceptors. However, it automatically fills in a fullpath. I'm assuming this is a feature of the subtype 'file' control. Then, there is a delay (on my very fast machine) of 3-6 seconds for it to update. If I run in debug, I've seen it go as long as 8-10 seconds before it shows the proper value. I'm assuming the delays would be even longer on a slower machine... or is there some kind of update timer? (GIF 1)
> 
> I tested manually putting in a path (not using Browse), making the edit field lose focus (click somewhere else), and the delay still occurs. It also makes me realize that I don't have code to validate if the path provided is valid.
> 
> Tested this on my work PC (which is slower than my home PC) and it updates faster(?) But the delay is definitely noticeable in certain situations. I explicitly show the .csproj and solution explorer in the GIF here to show them update nearly instantly, while the edit field is delayed in comparison. (GIF 2)

GIF 1:
![DelayedPropertyUpdate](https://user-images.githubusercontent.com/17788297/126710582-351fbdd9-cc70-47b3-a316-b33ed6cc740d.gif)

GIF 2:
![PackageIconUpdateDelayLess](https://user-images.githubusercontent.com/17788297/126710630-0f6519a3-bf9d-4ea9-a548-7a1692992025.gif)

**Comment by drewnoakes** [comment]
@MiYanni is this still an issue? Can we close this?

**Comment by MiYanni** [comment]
@drewnoakes Without retesting it, there is no way to know if it still an issue or not. AFAIK, there hasn't been any code change to directly address this behavior.

**Comment by drewnoakes** [comment]
Could you test again to verify?

**Comment by MiYanni** [comment]
@drewnoakes Just spent 10 minutes testing it. I couldn't reproduce this exact problem. However several times, the application (VS itself) would freeze for like 5 seconds (Window's style freeze, where you cannot interact with the app and the title bar flips theme). So, I'd say this specific issue is no longer an issue. I'll close it.

**Comment by drewnoakes** [comment]
If you can repro a freeze like that, use the "Report a problem" feature to capture a trace and file it.
