### ISSUE TITLE
[Regression] Roslyn no longer sees evaluation results until the design-time build is finished

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#7423]
**Visual Studio Version**:

**Summary**:

**Steps to Reproduce**:

1. Add a source file to the project project

``` C#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

	<UsingTask TaskName="Sleep" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v4.0.dll">
		<ParameterGroup>
			<!-- Delay in milliseconds -->
			<Delay ParameterType="System.Int32" Required="true" />
		</ParameterGroup>
		<Task>
			<Code Type="Fragment" Language="cs">
				<![CDATA[
      System.Threading.Thread.Sleep(this.Delay);
      ]]>
			</Code>
		</Task>
	</UsingTask>

	<Target Name="DelayDesignTimeBuild" AfterTargets="ResolveAssemblyReferences">
		<Sleep Delay="10000" />
	</Target>
	
</Project>

```

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/1103906/126745093-bde275ca-8cd5-41da-a842-3892f6e4475d.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1103906/126745053-1d486301-cd00-4ddd-9701-5088b4a41f82.png)

**User Impact**:
The user does not get semantic errors, intellisense or code actions that need to factor in project context (such as resolve using, etc) until the design-time build has completed. The product will feel fragile and slow (stuff won't work without an obvious reason why only to eventually work) 

The project system tries extremely hard to make changes related to source files during evaluation so that the product feels very fast and does not wait for long design-time build. This was regressed in https://github.com/dotnet/project-system/pull/7174, in particular this commit: https://github.com/dotnet/project-system/pull/7174/commits/f119b10bd3bf481886e6892d04534c580fd9521b. This says to CPS to hold off sending us evaluation results (fast) until the build (slow) results appear. 

Evaluation is guaranteed to have occurred before solution load has finished, build is not, so this will also be particularly bad after solution load.

**Comment by davkean** [comment]
This is the bug here: https://github.com/dotnet/project-system/commit/f119b10bd3bf481886e6892d04534c580fd9521b#diff-f58270d7350bab2e1ffdb27c7aa7630a3b62aaba9d9e9ed272ca2ce0e0d1f474R94-R95. The ProjectBuildRuleSource should not be combined with ProjectRuleSource.

**Comment by ocallesp** [comment]
It seems that @davidwengier fixed this.

**Comment by davkean** [comment]
@ocalles I've reopened this, this is still occurring here: https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs#L96.

**Comment by davidwengier** [comment]
Yeah, I definitely didn't fix this for evaluation, but the changes I did to not introduce it for source items should mean its a one-line change to just delete the line @davkean linked to.

I didn't do it in my PR because I figured someone should understand the issue first, so that appropriate tests can be written. The tests in my PR do not cover this issue.
