### ISSUE TITLE
Create 17.0 Preview 3 branch

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#7455]
- [x] Identify base commit for new branch
  - Base build is main 20210729.6
  - https://github.com/dotnet/project-system/commit/c5f05afefc92a2babb23be4c65c136b0e80d9fea
- [x] Create branch on GitHub
  - dev17.0-preview3
- [x] Update the YAML file to support CI/PR builds
  - Nothing to do; unit-tests.yml already covers branches matching the pattern `dev*`
- [x] Update Roslyn Tools config.xml file to flow branch changes to the latest dev branch
  - Skipping this step; the only changes we intend to take are already in `main`
- [x] Update Versions.props so ProjectSystemVersion matches the version of VS
  - https://github.com/dotnet/project-system/pull/7456
- [x] Update the signed build definition to build the new branch
  - Initial build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5055723&view=results
- [x] Clone existing release definition to insert this branch into VS
  - New release definition: https://devdiv.visualstudio.com/DevDiv/_releaseDefinition?definitionId=3053&_a=definition-pipeline
- [x] Update README.md if we need new badges
  - Skipping this step as this branch is just for Preview 3
- [x] Update Versions.props in main to reflect the version targeted by that branch
  - https://github.com/dotnet/project-system/pull/7457
- [x] Update msftbot milestone tracking
  - Skipping this step as this branch is just for Preview 3

**Comment by tmeschter** [comment]
The branch is now up and running.

**Comment by MiYanni** [comment]
@tmeschter IDEA! Do we have a GitHub template for doing this? Might be a good idea, so that we can just make an issue using that template that already has the task list on it. We can make the template only available for us, too. Templates go into the `.github` folder in the repo.

**Comment by tmeschter** [comment]
@MiYanni That's a good idea.

I found https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository, but I don't see the option to turn on templates. Maybe I lack the necessary privileges?

**Comment by MiYanni** [comment]
@tmeschter I've asked JJ to add you as a [team member](https://github.com/orgs/dotnet/teams/project-system-owners/members).

**Comment by MiYanni** [comment]
@tmeschter You should be added to the team now and able to access the template button in the settings.
