### ISSUE TITLE
Hide Hot Reload check box when Hot Reload is not supported

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#7474]
Currently we always show the Enable Hot Reload checkbox for launch profiles using the "Project" launch command:

![image](https://user-images.githubusercontent.com/10506730/128896547-bbfa0232-7cc9-4a35-9c77-7720f950f942.png)

We should only show this check box when the project supports Hot Reload; specifically, when it has the "SupportsHotReload" capability.

My current thought is to add a hidden "SupportsHotReload" bool property, and condition the visibility of the "Enable Hot Reload" property on that.

**Comment by drewnoakes** [comment]
> My current thought is to add a hidden "SupportsHotReload" bool property, and condition the visibility of the "Enable Hot Reload" property on that.

We have a visibility condition function that tests for project capabilities:

```lisp
(has-project-capability "SupportsHotReload")
```

**Comment by drewnoakes** [comment]
I had this file open today for something else so put a fix together for this.
