### ISSUE TITLE
Need to understand performance for Branch Switching

### ISSUE THREAD

**Issue by jjmew** [dotnet/project-system#7479]
Branch switching is an operation that affects a lot of files at once. In turn there is a lot of things for the Project System to update. We want to understand the performance and aid the Version Control team on coming up with ideas on how to understand what is affecting branch switch. Here are some items we need to do:

- [ ] Analyze telemetry that describes the topography of solutions (in General)
- [ ] Gather telemetry on the intersection of solution topography and branch switching operations
- [ ] Work with the Version Control team to come up with a common understanding of the problem

After this we can work in identifying concrete changes that we can make to code

**Comment by melytc** [comment]
We ended up delegating this item to the team in Prague as they have more knowledge on CSProj projects, which is taking the most time loading when branch switching upon initial investigation.
