### ISSUE TITLE
CopyLocal should be a 3-state to better indicate what it does

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#75]
_From @davkean on March 23, 2016 0:2_

On a reference, CopyLocal is a 3-state;' Use MSBuild default behavior, Don't copy local and Always Copy Local.

_Copied from original issue: dotnet/roslyn#10000_

**Comment by davkean** [comment]
This has lead to a bunch of confusion around this.

**Comment by kvenkatrajan** [comment]
Closing - lower priority - currently it doesnt render the Private tag if Copy Local is not set. If Copy Local is set, it generates the value set to the private tag
