### ISSUE TITLE
Class Name Not Updating After Renaming and Copying/Pasting File

### ISSUE THREAD

**Issue by shaggygi** [dotnet/project-system#7516]
**Version Used**:  Visual Studio 2019 16.8 Preview 1

**Steps to Reproduce**:

1. Create a new .NET Core Class Library project.
2. Click Class1.cs file in Solution Explorer and rename to Class2.cs.  Should get a prompt to say renaming file.  Click Yes and the `class Class1` gets renamed to `class Class2` in code.
4. Copy and paste Class2.cs file (I did at same level in solution).  Should have the Class2 - Copy. cs at this point.
5. Double click Class2.cs file to see code.  The Class name in code is still `class Class1`.

**Expected Behavior**:
I believe Class2 - Copy.cs should also be `class Class2` since I made a copy of it after changing the name.

**Actual Behavior**:
The copied file contains the Class name before the original file was renamed, copied and pasted.

Hope this helps.

**Comment by ocallesp** [comment]
Moving this to #AB1613812 so we can have a discussion on this with the cps team.
