### ISSUE TITLE
Can't get PlatformTarget, OutputFileName, IntermediatePath, AvailablePlatforms from EnvDTE

### ISSUE THREAD

**Issue by basoundr** [dotnet/project-system#755]
- [ ] #669 
- [ ] #668
- [ ] #667 
- [ ] #665

Clubbing all the related bugs in this issue.

fyi, @bricelam

**Comment by basoundr** [comment]
Moving to RTM since the dependent teams have already started using CPS to obtain the required properties and we don't know of other consumers who are in need of this

**Comment by berndb5** [comment]
Is there any progress regarding this issue?
This issue seems the root source of many other issues. For example the "net portability analyzer" fails to analyze projects in the new csproj format because OutputFileName is empty...

**Comment by davkean** [comment]
Going to close this in lieu of https://github.com/dotnet/project-system/issues/668 which is the only property we didn't implement yet. Others are implemented here: https://github.com/dotnet/project-system/pull/3623.
