### ISSUE TITLE
Creating a new WAP project fails with MSB4057: The target "CollectSuggestedWorkloads" does not exist in the project

### ISSUE THREAD

**Issue by swesonga** [dotnet/project-system#7561]
**Visual Studio Version**:
31631.489.main

**Steps to Reproduce**:

1. Creating a new Windows Application Packaging Project

2. Observe error in error list

**Expected Behavior**:
No errors

**Actual Behavior**:
Error MSB4057: The target "CollectSuggestedWorkloads" does not exist in the project.

**Comment by wli3** [comment]
@dsplaisted that's what you mentioned in the stand up?

**Comment by dsplaisted** [comment]
Yes, that's part of it

**Comment by swesonga** [comment]
This bug is being tracked by [VS 1393016](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1393016)
