### ISSUE TITLE
Clean up optional workload design-time tasks

### ISSUE THREAD

**Issue by swesonga** [dotnet/project-system#7563]
## Visual Studio Version
17.0 Preview 4

## Summary
https://github.com/dotnet/project-system/pull/7432 added a design-time target called CollectSuggestedWorkloads to https://github.com/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets. Unfortunately, that change did not account for the fact that this design-time targets file is used by non-SDK projects or projects using earlier SDKs. Such projects now fail with the error: The target "GetSuggestedWorkloads" does not exist in the project.

dotnet/project-system#7553 temporarily worked around this by conditioning CollectSuggestedWorkloads on SDK projects with MissingWorkloadPacks. However, that did not address bugs like https://github.com/dotnet/project-system/issues/7561 in which a project that doesn't include the design-time targets fails because the CollectSuggestedWorkloads design-time target cannot be found. To address this, https://github.com/dotnet/msbuild/pull/6813 added dummy targets to Microsoft.Common.props.

These workarounds need to be removed and replaced with a proper fix. These are the issues that need to be addressed:

1. Why wasn't the WorkloadDescriptorDataSource working with the GetSuggestedWorkloads target (i.e. is the CollectSuggestedWorkloads actually needed)?
2. If the CollectSuggestedWorkloads is indeed essential, is there a way to avoid having dummy targets (i.e. is there a way for CPS to ignore the target if it is missing without failing the design-time build)?
3. If not, what is the best way to define the dummy target in Microsoft.Common.targets without breaking the SDK optional workloads targets? Those SDK workload targets might needed to be rewritten.

**Comment by dsplaisted** [comment]
Looking at #7553 again, are we sure that didn't fix the issues with earlier SDKs and WAP projects?  I would not expect those projects to have any `MissingWorkloadPack`, items, so I don't think they should have gotten the error that the `GetSuggestedWorkloads` target wasn't defined (once #7553 went in).

**Comment by swesonga** [comment]
> Looking at #7553 again, are we sure that didn't fix the issues with earlier SDKs and WAP projects? I would not expect those projects to have any `MissingWorkloadPack`, items, so I don't think they should have gotten the error that the `GetSuggestedWorkloads` target wasn't defined (once #7553 went in).

If you get the latest VS main build, you'll have fix #7553, which fixed the issues with earlier SDKs. See Microsoft.VisualStudio.RpcContracts.sln for an example of projects pinned to .NET 5 that no longer have this issue. However, you'll still be able to repro #7561.

The WAP project imports the SDK using an Import tag then manually imports Microsoft.Common.targets. In this flow, it does not pull in Microsoft.Managed.DesignTime.targets (which is usually brought in by language specific targets). The latter target file contains the design-time target needed by the CPS SuggestedWorkload data source, hence the design-time build failure for WAP projects (in other words, notice the exact target complained about in the error message is different for #7561).
