### ISSUE TITLE
.NET Core compatability checker hasn't worked since 16.1

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7572]
We have a component (`DotNetCoreProjectCompatibilityDetector`) which attempts to warn the user when their project is using an unsupported version of .NET Core for a given version of Visual Studio.

It does this based on JSON data sourced from https://go.microsoft.com/fwlink/?linkid=866798

Currently that data is:

```json
{
  "vsVersions": {
    "15.6": {
      "recommendedVersion": "2.0",
      "nonRecommendedVersionSelectedMessage": "",
      "supportedVersion": "2.1",
      "openSupportedMessage": "",
      "unsupportedVersion": "3.0",
      "unsupportedVersionsInstalledMessage": "",
      "openUnsupportedMessage": ""
    },
    "15.8": {
      "recommendedVersion": "2.1",
      "nonRecommendedVersionSelectedMessage": "{0} requires a newer version of Visual Studio.",
      "supportedVersion": "2.2",
      "openSupportedMessage": "Visual Studio 2017 version 15.9 or newer is recommended for .NET Core 2.2 projects.",
      "unsupportedVersion": "3.0",
      "unsupportedVersionsInstalledMessage": "",
      "openUnsupportedMessage": ""
    },
    "15.9": {
      "nonRecommendedVersionSelectedMessage": "",
      "supportedVersion": "2.3",
      "openSupportedMessage": "A newer version of Visual Studio is recommended for projects targetting .NET Core projects later then 2.2.",
      "unsupportedVersion": "3.0",
      "unsupportedVersionsInstalledMessage": "",
      "openUnsupportedMessage": ""
    },
    "16.0": {
      "nonRecommendedVersionSelectedMessage": "",
      "supportedVersion": "2.3",
      "openSupportedMessage": "",
      "unsupportedVersion": "3.0",
      "unsupportedVersionsInstalledMessage": "",
      "openUnsupportedMessage": "Visual Studio 2019 16.1 Preview 3 or newer is recommended for .NET Core 3.0 projects"
    },
    "16.1": {
      "nonRecommendedVersionSelectedMessage": "",
      "supportedVersion": "2.3",
      "openSupportedMessage": "",
      "supportedPreviewVersion": "3.0",
      "openSupportedPreviewMessage": "",
      "unsupportedVersion": "3.0",
      "unsupportedVersionsInstalledMessage": "",
      "openUnsupportedMessage": "Please enable using preview .NET Core SDKs in the Visual Studio Options to open.NET Core 3.0 projects"
    }
  }
}
```

Notice how it has versions 15.6, 15.8, 15.9, 16.0 and 16.1.

`DotNetCoreProjectCompatibilityDetector` currently requires an exact match on the major and minor version, meaning that with the above data the component has not worked since version 16.2. It also wouldn't have worked in 15.7.

Possible actions:

- Change the logic so that versions roll forwards (eg. 16.1 applies to that and all later versions)
- Get updated values in the JSON data
- All of the above
- Remove the feature altogether

**Comment by drewnoakes** [comment]
cc @BillHiebert (who initially added this feature):

- Do you have any sense of whether this feature still adds value?
- Do you know who owns the above data file, so we can update it?

**Comment by davkean** [comment]
Pretty they rewrote this and to consume the updated version they needed it to move down a layer.

**Comment by BillHiebert** [comment]
Wow, I'd completely forgotten about that feature.  It was originally designed to warn if older versions of VS attempted to open projects targeting newer .net core versions where we new the developer experience was broken.  I thought the versions were minimum and maximums so it did handle ranges - or at least it used to.  As to whether it is still useful, I am not sure. 
@phenning who was using this or something similar for the templates support.

**Comment by drewnoakes** [comment]
@BillHiebert @phenning @davkean given this is not working today, yet it is doing work on solution load, I intend to remove it. We can always reinstate it in future if needed.
