### ISSUE TITLE
[Loc] New Property Pages: "When to run the post-build event" values not translated

### ISSUE THREAD

**Issue by MiYanni** [dotnet/project-system#7576]
**Related**: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1331368/

The related issue showed the information for Events not being translated. Now, they are translated... except for the values of the "When to run the post-build event" dropdown. The other dropdowns that have values like this are translated properly, so this should also have translations. For example: 
![image](https://user-images.githubusercontent.com/17788297/132781255-7472f11b-2a04-48df-a594-771454b9064a.png)

## Events page (with the missing translations on the dropdown):
![image](https://user-images.githubusercontent.com/17788297/132781063-cf4c6a06-d69a-404c-ac94-4545385e2ed4.png)

**Comment by tmeschter** [comment]
It looks like the translated text is in the .lcl files but _not_ in the .xlf files. @MiYanni who can we ping about this?

**Comment by MiYanni** [comment]
@tmeschter Interesting. I don't think that situation can normally happen. I can talk to Christiano about it. I really think some of this stuff is happening because we get multiple PRs of translations at a time. Translation changes should really be batched into a single PR.

**Comment by MiYanni** [comment]
As of https://github.com/dotnet/project-system/commit/abb6acc50b01430f9c2e130d98cd0b3c853f216c these are now appropriately translated.

![image](https://user-images.githubusercontent.com/17788297/134248322-6852e85d-8a09-44eb-8c29-ba48ca6c109a.png)
