### ISSUE TITLE
Launch Profiles editor should select the active profile at startup

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7595]
When opening the Launch Profiles UI, the selected launch profile should be the active one, where such an active profile exists.

Originally suggested via [feedback ticket 1507906](https://developercommunity.visualstudio.com/t/How-do-I-select-an-active-launch-profile/1507906).

**Comment by tmeschter** [comment]
@adamint Is this finished, or is there more to do?

**Comment by adamint** [comment]
This is finished
