### ISSUE TITLE
RenamerProjectTreeActionHandler hangs VS during project/solution closing

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#7610]
The code spin off a task waits on PublishLatestSolutionAsync(). When the project is closed quickly before operation progress finishes, this will be blocked and won't finish. This task causes Project.Close to hang.

Use the project unloading cancellation token when it waits the operation progress to prevent this deadlock.

**Comment by lifengl** [comment]
+ @drewnoakes : this is showing in PerfWatson hang dumps, and should be easy to fix.

**Comment by drewnoakes** [comment]
@lifengl please review proposed fix in https://github.com/dotnet/project-system/pull/7616.
