### ISSUE TITLE
Build inside VS may take forever due to a deadlock inside NET Core project

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#7615]
## Related Items - 
[AB#1439339](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1439339)
[AB#1439046](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1439046)

## Steps to Reproduce

1. Load a mid size solution into VS (like CPS)
2. Build the solution, works well
3. Switch solution configuration (debug -> release or reverse)
4. Build the solution immediately

## Expected Behavior
Build the solution 

## Actual Behavior
Build may hang, and will never finish.  It was reported earlier, but no clear repo.

I ran into this and captured a dump & can share if necessary.

Basically, build tasks are blocked in AppendFlushLoggersTasks

```
1f5490a7e08 <8> Microsoft.VisualStudio.ProjectSystem.Build.BuildProject+<BuildCoreAsync>d__100 @ 7fff3741d410
..1f5490a8160 <1> Microsoft.VisualStudio.ProjectSystem.Build.BuildProject+<BuildWithSolutionAsync>d__94 @ 7fff37992bb0
..1f5490a74c0 <5> Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.BuildableProjectConfig+<BuildAsync>d__63 @ 7fff7f57a580

1f549300df8 <8> Microsoft.VisualStudio.ProjectSystem.Build.BuildProject+<BuildCoreAsync>d__100 @ 7fff3741d410
..1f549301150 <1> Microsoft.VisualStudio.ProjectSystem.Build.BuildProject+<BuildWithSolutionAsync>d__94 @ 7fff37992bb0
..1f5492f69f0 <5> Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.BuildableProjectConfig+<BuildAsync>d__63 @ 7fff7f57a580

1f5491a8918 <0> Microsoft.VisualStudio.ProjectSystem.Build.BuildUtilities+<>c+<<AppendFlushLoggersTask>b__16_0>d @ 7fff388c9320
1f54930f080 <0> Microsoft.VisualStudio.ProjectSystem.Build.BuildUtilities+<>c+<<AppendFlushLoggersTask>b__16_0>d @ 7fff388c9320
```

Further tracking down, they were blocked by those tasks during error list initialization.

```
1f4b5929fe8 <0> Microsoft.VisualStudio.ProjectSystem.AbstractMultiLifetimeComponent<Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost+WorkspaceProjectContextHostInstance>+<WaitForLoadedAsync>d__3 @ 7fff367540e0
..1f4b592a248 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost+<OpenContextForWriteAsync>d__14 @ 7fff36775cc0
..1f4b592a498 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.ActiveWorkspaceProjectContextHost+<OpenContextForWriteAsync>d__5 @ 7fff36774bc0
..1f4b592a6e0 <0> Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService+<>c+<<ClearAllAsync>b__28_0>d @ 7fff7db718e0
..1f4b592bf78 <0> Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools+<ForEachAggregateExceptionsAsync>d__65<System.Lazy<Microsoft.VisualStudio.ProjectSystem.VS.Build.IVsErrorListProvider, Microsoft.VisualStudio.ProjectSystem.IOrderPrecedenceMetadataView>> @ 7fff38c05fc0
..1f4b592c1d0 <0> Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService+<ClearAllAsync>d__28 @ 7fff7db71570
..1f4b592c410 <0> Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService+<ProcessQueueAsync>d__31 @ 7fff79f87770
..1f4b592c6f8 <0> Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim<Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<Microsoft.VisualStudio.ProjectSystem.Build.ProjectBuildMessages>, System.Collections.Immutable.IImmutableDictionary<Microsoft.VisualStudio.ProjectSystem.NamedIdentity, System.IComparable>>+TransformBlockSlimAsync+<ProcessInputAsync>d__3 @ 7fff38877b20
..1f4b592c940 <0> Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim<Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<Microsoft.VisualStudio.ProjectSystem.Build.ProjectBuildMessages>>+<ProcessInputQueueAsync>d__5 @ 7fff388771d0

1f4b819d430 <0> Microsoft.VisualStudio.ProjectSystem.AbstractMultiLifetimeComponent<Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost+WorkspaceProjectContextHostInstance>+<WaitForLoadedAsync>d__3 @ 7fff367540e0
..1f4b819dbf8 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost+<OpenContextForWriteAsync>d__14 @ 7fff36775cc0
..1f4b819de48 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.ActiveWorkspaceProjectContextHost+<OpenContextForWriteAsync>d__5 @ 7fff36774bc0
..1f4b819e090 <0> Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService+<>c+<<ClearAllAsync>b__28_0>d @ 7fff7db718e0
..1f4b819e2d0 <0> Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools+<ForEachAggregateExceptionsAsync>d__65<System.Lazy<Microsoft.VisualStudio.ProjectSystem.VS.Build.IVsErrorListProvider, Microsoft.VisualStudio.ProjectSystem.IOrderPrecedenceMetadataView>> @ 7fff38c05fc0
..1f4b819e528 <0> Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService+<ClearAllAsync>d__28 @ 7fff7db71570
..1f4b819e768 <0> Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService+<ProcessQueueAsync>d__31 @ 7fff79f87770
..1f4b819ea50 <0> Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim<Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<Microsoft.VisualStudio.ProjectSystem.Build.ProjectBuildMessages>, System.Collections.Immutable.IImmutableDictionary<Microsoft.VisualStudio.ProjectSystem.NamedIdentity, System.IComparable>>+TransformBlockSlimAsync+<ProcessInputAsync>d__3 @ 7fff38877b20
..1f4b819ec98 <0> Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim<Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<Microsoft.VisualStudio.ProjectSystem.Build.ProjectBuildMessages>>+<ProcessInputQueueAsync>d__5 @ 7fff388771d0

1f4b8602d68 <0> Microsoft.VisualStudio.ProjectSystem.AbstractMultiLifetimeComponent<Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost+WorkspaceProjectContextHostInstance>+<WaitForLoadedAsync>d__3 @ 7fff367540e0
..1f4b8602fc8 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost+<OpenContextForWriteAsync>d__14 @ 7fff36775cc0
..1f4b8603218 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.ActiveWorkspaceProjectContextHost+<OpenContextForWriteAsync>d__5 @ 7fff36774bc0
..1f4b8603460 <0> Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService+<>c+<<ClearAllAsync>b__28_0>d @ 7fff7db718e0
..1f4b86036a0 <0> Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools+<ForEachAggregateExceptionsAsync>d__65<System.Lazy<Microsoft.VisualStudio.ProjectSystem.VS.Build.IVsErrorListProvider, Microsoft.VisualStudio.ProjectSystem.IOrderPrecedenceMetadataView>> @ 7fff38c05fc0
..1f4b86038f8 <0> Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService+<ClearAllAsync>d__28 @ 7fff7db71570
..1f4b8603b38 <0> Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Build.VsProjectBuildErrorListPublishService+<ProcessQueueAsync>d__31 @ 7fff79f87770
..1f4b8603e20 <0> Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim<Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<Microsoft.VisualStudio.ProjectSystem.Build.ProjectBuildMessages>, System.Collections.Immutable.IImmutableDictionary<Microsoft.VisualStudio.ProjectSystem.NamedIdentity, System.IComparable>>+TransformBlockSlimAsync+<ProcessInputAsync>d__3 @ 7fff38877b20
..1f4b8604068 <0> Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim<Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<Microsoft.VisualStudio.ProjectSystem.Build.ProjectBuildMessages>>+<ProcessInputQueueAsync>d__5 @ 7fff388771d0
```

Here we can see the code has a race condition, the ActiveWorkspaceProjectContextHost uses IActiveConfiguredValue<IWorkspaceProjectContextHost?> _activeHost to access WorkspaceProjectContext. During the configuration switching, this logic may get the old WorkspaceProjectContext, because it is deactivated, WaitForLoadedAsync will hang forever to wait it to be reinitialized. When it hangs, however, the _activeHost now gets the right configuration.  It looks like the code expects ActiveProjectConfigurationChangedException, however, in its code path, it will block waits a TaskCompletionSource inside a configured project, and nothing will stop it and throws this Exception.

```
1f4b5929fe8 <0> Microsoft.VisualStudio.ProjectSystem.AbstractMultiLifetimeComponent<Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost+WorkspaceProjectContextHostInstance>+<WaitForLoadedAsync>d__3 @ 7fff367540e0
..1f4b592a248 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost+<OpenContextForWriteAsync>d__14 @ 7fff36775cc0
..1f4b592a498 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.ActiveWorkspaceProjectContextHost+<OpenContextForWriteAsync>d__5 @ 7fff36774bc0
```

**Comment by lifengl** [comment]
@drewnoakes : it looks like this code actually adds special logic to handle this situation inside PublishAsync method, but didn't do the same thing inside two OpenContextForWriteAsync. I guess it can follow a similar fix.

**Comment by drewnoakes** [comment]
@lifengl I tried to repro this several times locally but was unable to. Based on the above I believe #7618 will prevent the hang, but I'd prefer to repro before/after to verify. Any thoughts on how I could get this to repro?

**Comment by lifengl** [comment]
Maybe I didn’t fully finish building debug before I switched the configuration to release.  Either I switched after loading the solution without building, or I started but then cancelled the earlier but then switched the configuration and started a new build.

It happened quickly so I didn’t fully remember all the details.

Sent from my phone

On Sep 19, 2021, at 10:05 PM, Drew Noakes ***@***.***> wrote:

﻿

@lifengl<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flifengl&data=04%7C01%7C%7Cb96b33c8697746671b9f08d97bf43c6c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637677111181122452%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FZLKH6Sv0d6euHV%2BhqjriQjt2wj6b%2B4Vwkut7dzs9iU%3D&reserved=0> I tried to repro this several times locally but was unable to. Based on the above I believe #7618<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fproject-system%2Fpull%2F7618&data=04%7C01%7C%7Cb96b33c8697746671b9f08d97bf43c6c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637677111181122452%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5itWyPEjqQ3c0dkUVKOgEysnDl5dUXIBoFbXUR0kWLc%3D&reserved=0> will prevent the hang, but I'd prefer to repro before/after to verify. Any thoughts on how I could get this to repro?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fproject-system%2Fissues%2F7615%23issuecomment-922639509&data=04%7C01%7C%7Cb96b33c8697746671b9f08d97bf43c6c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637677111181132447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PxVxNl5Q29akId08E954Ojcft3Lje6QDlR1r24XL8qo%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACYZNQW2HPQ5IJ2X7UAKA2DUC26IZANCNFSM5EJVR5GA&data=04%7C01%7C%7Cb96b33c8697746671b9f08d97bf43c6c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637677111181142441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LR8rzwfUrZ7d2A4Ix%2FZREfqloHISc2KT4TNokRLtHos%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cb96b33c8697746671b9f08d97bf43c6c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637677111181142441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=la8FCGR0KbafDyRhsAgzaXRG1tlGBqXUTvwWxcr0LTM%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cb96b33c8697746671b9f08d97bf43c6c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637677111181152431%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3%2FTchGKzVVqjRgGBEyOm1DxDHaj2rgeNKj8CBF7QS%2Bg%3D&reserved=0>.

**Comment by drewnoakes** [comment]
When I build, the configuration combo box on the toolbar is disabled:

![image](https://user-images.githubusercontent.com/350947/133960787-0b1fe99a-4650-41ed-a228-46f8ea0720c5.png)

There is a short window where I can change it, but then I see:

![image](https://user-images.githubusercontent.com/350947/133960757-a1c6a57e-7f4b-487a-b2c2-d215914c90d4.png)

**Comment by drewnoakes** [comment]
I managed to repro it in the end, though I don't yet have clear repro steps. Building and toggling the configuration a few times did the trick. The build seems be be ongoing, but no progress is made. It is possible to cancel the build.

I will verify that I'm unable to reproduce this state with the proposed fix.

**Comment by drewnoakes** [comment]
The change is not sufficient to address the hang. I have a local branch where I've wired through cancellation on active configuration changes, but still see the hang. The next step appears to be digging in to whether it's waiting on the new or old configuration.

**Comment by lifengl** [comment]
I read the change. I think it will still leave race conditions, so it still leads dead lock.

I think the cancellation must be aligned with the active configuration value, either when  the value is changed, it triggers it, or maybe uses a data flow. Basically, the value and cancellation must be aligned, so when it is handled, it will pick up new value for sure. If they are chained through different channels, the new value might not yet come, so not enough to fix the hang.

Sent from my phone

On Sep 20, 2021, at 7:17 PM, Drew Noakes ***@***.***> wrote:

﻿

The change is not sufficient to address the hang. I have a local branch where I've wired through cancellation on active configuration changes, but still see the hang. The next step appears to be digging in to whether it's waiting on the new or old configuration.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fproject-system%2Fissues%2F7615%23issuecomment-923534871&data=04%7C01%7C%7C91a3819fc815495fb64508d97ca5e9c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637677874308629793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MTrK8kh49%2FgTUgRyQbHsM36XH3fg7b5eh5IwGDrvqxk%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACYZNQRQVC7PSIUH6HWDTITUC7TKHANCNFSM5EJVR5GA&data=04%7C01%7C%7C91a3819fc815495fb64508d97ca5e9c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637677874308639790%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=d1oClskNRq3o06phdB5DXUaWqjhnR79qfGhfiqyNap8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C91a3819fc815495fb64508d97ca5e9c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637677874308649780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vvrsXSU4Bk5yIMkY44CgK8w%2FlifUuMscczbu%2FeQgQM4%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C91a3819fc815495fb64508d97ca5e9c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637677874308659773%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HUzz6Uz2m6PmMFfKKGBMZ08BRKXJJ3w4fsDWl%2BXQ9sY%3D&reserved=0>.

**Comment by schalling** [comment]
I encounter this hang quite often now in my solution. Cannot figure out precisely why though - yet I created a new Solution Configuration and I dont think i’ve seen the hang before that. Switching between the new Solution Configuration and Debug seems to generate the hang more frequently.. i think.

**Comment by davkean** [comment]
This is the same bug as https://developercommunity.visualstudio.com/t/VS2022-hangs-during-build/1587726.

**Comment by drewnoakes** [comment]
With #8321 I can no longer reproduce this hang.
