### ISSUE TITLE
[Loc] New Property Pages: Razor Properties are not translated

### ISSUE THREAD

**Issue by MiYanni** [dotnet/project-system#7627]
Related: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1308594/

If you create a .NET Core WebApplication, the new property pages do not have translations for Razor Properties. Here, I was testing in Korean.
![image](https://user-images.githubusercontent.com/17788297/134240677-300c2ee7-c8c0-4914-be39-0dc6ff439268.png)

Tested after this commit: https://github.com/dotnet/project-system/commit/abb6acc50b01430f9c2e130d98cd0b3c853f216c

**Comment by drewnoakes** [comment]
"Razor Properties" are shipped with the SDK and were hidden in https://github.com/dotnet/sdk/pull/16623

If they're still showing in the UI, I assume that an old SDK is in use.

**Comment by drewnoakes** [comment]
I do not see any action we can take here that doesn't involve adding some special-case logic to suppress these properties in the back end if we see them.

**Comment by captainsafia** [comment]
@drewnoakes Is there an explanation for why the values still show up even though they are removed in the current SDK version? Will it be populated if the user has an older version of the SDK that does include the properties?

**Comment by drewnoakes** [comment]
@captainsafia yes I suspect they're being shown for older SDKs. This is probably not an ideal experience.

In https://github.com/dotnet/sdk/pull/16623 we hid properties in rule "RazorExtension", though I discovered that another SDK PR is needed: https://github.com/dotnet/sdk/pull/21659.

Given this, I'll add code to the project system to exclude these well-known razor pages.

**Comment by drewnoakes** [comment]
> Given this, I'll add code to the project system to exclude these well-known razor pages.

https://github.com/dotnet/project-system/pull/7654
