### ISSUE TITLE
[Loc] New Property Pages: Some TypeScript properties are not translated

### ISSUE THREAD

**Issue by MiYanni** [dotnet/project-system#7628]
Related: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1308594/

If you create a .NET Core WebApplication, the new property pages do not have translations for some of the TypeScript properties. Here, I was testing in Korean.
![image](https://user-images.githubusercontent.com/17788297/134241140-def29bdf-bc96-445c-ad53-322100359725.png)

Tested after this commit: https://github.com/dotnet/project-system/commit/abb6acc50b01430f9c2e130d98cd0b3c853f216c

**Comment by drewnoakes** [comment]
These properties are not in this repo. The issue should be forwarded to the TypeScript team.

**Comment by tmeschter** [comment]
@MiYanni Can you close and reopen in Microsoft/TypeScript?
