### ISSUE TITLE
[Loc] bad translate

### ISSUE THREAD

**Issue by Varorbc** [dotnet/project-system#7633]
### `publish `should not be translated 

https://github.com/dotnet/project-system/blob/2146ad988ea25cfc044e9f687a22e28d38362d17/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf#L17

### The following is the wrong translation, as a Chinese, I can't understand what it means 

https://github.com/dotnet/project-system/blob/2146ad988ea25cfc044e9f687a22e28d38362d17/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf#L20-L24

https://github.com/dotnet/project-system/blob/2146ad988ea25cfc044e9f687a22e28d38362d17/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf#L70-L74

https://github.com/dotnet/project-system/blob/2146ad988ea25cfc044e9f687a22e28d38362d17/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf#L240-L244

**Comment by tmeschter** [comment]
Putting in 17.0 for the moment in hopes that we can get a translation fix for that release.

**Comment by MiYanni** [comment]
I've created 2 issues for the translation team to address these:
- https://ceapex.visualstudio.com/CEINTL/_workitems/edit/497586
- https://ceapex.visualstudio.com/CEINTL/_workitems/edit/497587

**Comment by drewnoakes** [comment]
@MiYanni this is not going to be serviced in 17.1. Can you update the milestone please?

**Comment by MiYanni** [comment]
This has been resolved.

https://github.com/dotnet/project-system/blob/1cdbf42770ff4b4c3fa5ddc8c13d55decb3356e2/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf#L17

https://github.com/dotnet/project-system/blob/1cdbf42770ff4b4c3fa5ddc8c13d55decb3356e2/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf#L20-L24

https://github.com/dotnet/project-system/blob/1cdbf42770ff4b4c3fa5ddc8c13d55decb3356e2/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/ApplicationPropertyPage.xaml.zh-Hans.xlf#L70-L74

https://github.com/dotnet/project-system/blob/1cdbf42770ff4b4c3fa5ddc8c13d55decb3356e2/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.zh-Hans.xlf#L240-L244
