### ISSUE TITLE
DependenciesSnapshotProvider.DisposeCore blocks UI thread 110ms during closing Roslyn.sln

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#7635]
most time spent to dispose dataflow subscriptions, no need to block the UI thread.

It happens because OnProjectUnloadingAsync is called on the UI thread, and also blocks the unloading process. I guess it just need spin off the task to unsubscribe dataflow.

**Comment by lifengl** [comment]
![image](https://user-images.githubusercontent.com/11638466/134579647-fa1e61af-1bd1-494b-ab8c-8022aaef46f3.png)

**Comment by drewnoakes** [comment]
We can spin off a task and not await it.

@lifengl should we consider doing no work here if we know we are shutting down? That sounds good in theory but I'm not sure how reliable it would be in practice, if for example the shutdown was aborted. It'd be nice to have a way to register work that needed to happen only if abort happened.

**Comment by drewnoakes** [comment]
Actually we don't need to handle `ProjectUnloading` at all. The UnconfiguredProject-scope MEF part will be disposed on project unload anyway, off the UI thread.
