### ISSUE TITLE
Adding/removing Content/None items can lead to overbuild

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7700]
## Visual Studio Version

main

## Summary

The fast up-to-date check tracks changes to project items. When it sees one, it remembers when it happens and uses that information in future up-to-date decision making.

This item tracking should not apply to `None` or `Content` (and possibly others). When the set of these items change, there is no observable output changes. This can lead to a state where the project continues to build (overbuild) until it is changed or rebuilt.

## Steps to Reproduce

1. Create a console app
2. Add content item `json1.json`
3. Build
4. Build again

## Expected Behavior

Up-to-date on second build.

## Actual Behavior

> 1>FastUpToDate: The set of project items was changed more recently (15/10/2021 2:29:29 PM) than the earliest output 'C:\repos\ConsoleApp341\ConsoleApp341\obj\Debug\net6.0\ConsoleApp341.pdb' (15/10/2021 2:29:11 PM), not up to date.

## User Impact

MSBuild will be called for any project in this state until the project itself is changed in a way that triggers a change in outputs, or the project is rebuilt.

Users may not be aware of this state (although we are working on improving that, in a separate effort).

**Comment by drewnoakes** [comment]
Another occurrence of this is in the OrchardCore project's .NET5/6 branches, where the creation of `None` items to be included in the project templates package causes the project to end up in an overbuild loop. That issue would be avoided if we excluded `None` items from the fast up-to-date check.

**Comment by ktaeleman** [comment]
I'm running into a similar situation where as far as I can tell, a nuget package adding None items (either through a build props/targets file or contentFiles) will cause endless compiles due to "project items changed more recently than earliest output (one of the pdbs)". Have not been able to find a workaround for this as marking them as "Content" runs into the same issue, causing every incremental compile or no-op compile to take over 2 minutes.

**Comment by drewnoakes** [comment]
@ktaeleman thanks for the scenario. Is the NuGet package you refer to public? It might help me to repro this case.

The current workaround for this bug is to rebuild the project. Not ideal, but it does break the cycle.

**Comment by ktaeleman** [comment]
Yes, both of those are on nuget.org.

Thanks for looking into this!

Feb. 11, 2022 2:52:22 p.m. Drew Noakes ***@***.***>:
