### ISSUE TITLE
ProjectReference under condition on $(TargetPlatformIdentifier) fails to build in Visual Studio

### ISSUE THREAD

**Issue by srdjanjovcic** [dotnet/project-system#7710]
### Visual Studio Issue
https://dev.azure.com/devdiv/DevDiv/_queries/edit/1371746

## Visual Studio Version
Visual Studio 2022 RC

## Summary
When project has ProjectReferences under a condition involving $(TargetPlatformIdentifier), dependent projects are not built in VS (they build fine when building on command line).

## Steps to Reproduce

1. Grab the code from https://github.com/mattleibow/ProjectsWithDepsThatDoNotBuild
2. Follow instructions in README.md

## Expected Behavior
Dependent projects are built on right click on a main project > Build.

## Actual Behavior
Dependent projects are not built, leading to build errors.

## User Impact
User cannot use Visual Studio in a normal way, or worse, they end up testing stale version of dependent libraries.

**Comment by srdjanjovcic** [comment]
@davkean Who owns multi-target framework support? Is it still project-system?

**Comment by davkean** [comment]
Its a joint effort between this repro and CPS, with CPS providing the base support to enable this, and this repro implementing the ".NET" view on top of it.

**Comment by srdjanjovcic** [comment]
I'll leave internal issue \#1371746 open and moved it to CPS area, just in case there is something needed done at that side.

**Comment by srdjanjovcic** [comment]
There is a slightly different issue which, I believe, is closely related: 

#7712

**Comment by drewnoakes** [comment]
This is being tracked by CPS in AB#1524343.

**Comment by drewnoakes** [comment]
As the fix for this issue will be in CPS and not this repo, I am closing this.
