### ISSUE TITLE
When .NET 6.0 class library targets anything besides net6.0 or net6.0-windows, "Deploy" flag in VS configuration manager is enabled.

### ISSUE THREAD

**Issue by srdjanjovcic** [dotnet/project-system#7734]
## Visual Studio Version
VS 2019 and VS 2022 Preview

## Summary
When .NET 6.0 class library has target framework net6.0-android or net6.0-ios (or anything besides net6.0 or net6.0-windows), then checkbox 'Deploy' is enabled for those projects, even if they are not deployable:

![image](https://user-images.githubusercontent.com/15749816/139712524-4de67e43-2bab-4d09-9220-7da81b96b9e4.png)

## Steps to Reproduce

1. Open attached solution [ClassLibraries.zip](https://github.com/dotnet/project-system/files/7455039/ClassLibraries.zip)
2. Go to Configuration Manager
3. See that "Deploy" checkbox is enabled for DotNet6Library. 

## Expected Behavior

- .NET 6.0 class libraries are not marked as deployable.

## Actual Behavior

- .NET 6.0 class libraries are marked as deployable if they target net6.0-android or net6.0-ios

## User Impact

- If user accidentally mark them as 'deployable', deploying the actual application from the solution would fail, because deploying the library will fail.

**Comment by jjmew** [comment]
This was moved to AB#1429382 #AB1429382

**Comment by jjmew** [comment]
This is CPS
