### ISSUE TITLE
NuGet diagnostics should be represented in the references node

### ISSUE THREAD

**Issue by davidfowl** [dotnet/project-system#774]
In xproj, we spent a considerable amount of time making sure that various types of restore errors were represented in the UI. Here's what an incompatible dependency looks like in the new csproj:

## Csproj

![image](https://cloud.githubusercontent.com/assets/95136/20427270/01c31012-ad38-11e6-9d52-0d47d98b97f4.png)

There is an error in the error list, but there's nothing showing that something is wrong if that window isn't up:

![image](https://cloud.githubusercontent.com/assets/95136/20427313/30781c72-ad38-11e6-8ffc-cd20f10c31e4.png)

## XProj

![image](https://cloud.githubusercontent.com/assets/95136/20427502/28af4438-ad39-11e6-9988-bf290f376225.png)

![image](https://cloud.githubusercontent.com/assets/95136/20427548/6d4be7f4-ad39-11e6-8a71-7b8dcb4ad39f.png)

Above shows the exact same project with an incompatible dependency. Some things to notice:

- The project.json has a squiggle under the broken dependency.
- Hovering over the squiggle gives me the nuget error directly in the editor
- The solution explorer shows an error on the dependency that is incompatible. This indicates that there's a problem even when the error list if closed.
- The warning window shows the same thing (this should arguably be an error instead of a warning).

/cc @abpiskunov @rrelyea

**Comment by srivatsn** [comment]
This needs https://github.com/dotnet/sdk/issues/26 and once that's done there's likely no work on the project system for the error to show up in solution explorer.

**Comment by davidfowl** [comment]
@srivatsn don't forget the squiggle in the project file (if it was open). It's related to https://github.com/dotnet/roslyn-project-system/issues/766

**Comment by davidfowl** [comment]
Unresolved dependencies should show up in the tree as well:

![image](https://cloud.githubusercontent.com/assets/95136/20593251/84dcee52-b1e6-11e6-9570-8d17a4d6d299.png)


Today they are completely left out.

**Comment by abpiskunov** [comment]
They do show - what is your specific repro steps? And builds ...

Thanks,
Anton

On Nov 24, 2016, at 1:37 AM, David Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:


Unresolved dependencies should show up in the tree as well:

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F95136%2F20593251%2F84dcee52-b1e6-11e6-9570-8d17a4d6d299.png&data=02%7C01%7Canton.piskunov%40microsoft.com%7C03af7def49b048d3049008d4144d8138%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636155770490013991&sdata=DLRSWRj4PX8ZNzIif7BtHMo%2FJk2Dah4noJCawp8odkU%3D&reserved=0>

Today they are completely left out.

-

**Comment by davidfowl** [comment]
@abpiskunov I removed it. I might not have hit save, or there may have been another error preventing restore from writing the lock file.

**Comment by davidfowl** [comment]
However, there does seem to be a large class of bugs where things aren't getting updated properly after a csproj edit

**Comment by davidfowl** [comment]
Related to https://github.com/dotnet/sdk/issues/26
