### ISSUE TITLE
NullReferenceException when building vcxproj

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7747]
## Visual Studio Version

Version 17.1.0 Preview 2.0 [31908.427.main]

## Summary

When building a mixed .NET / C++ solution, a `NullReferenceException` can occur.

## Steps to Reproduce

1. Open a solution having mixed C++ and .NET projects (`\\mlangfs1\public\v-masche\RealWorldSolutions\NETCoreCppCliTestWithNative.zip` is a good example)
2. Build

## Expected Behavior

No bang.

## Actual Behavior

Bang.

```
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.VisualStudio.ProjectSystem.VS.Build.Diagnostics.IncrementalBuildFailureDetector.ProjectChecker.<>c__DisplayClass7_0.<<OnProjectBuildCompleted>g__CheckAsync|1>d.MoveNext()
```

## User Impact

Yellow bar.

**Comment by drewnoakes** [comment]
Originally reported in a comment on closed issue https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1430106

**Comment by ligg** [comment]
vs version is 17.1.0 Preview 1.1
i have the same issue when i build a docker-compose project
[VsProjectFault_711c6d2b-2c54-4392-939b-0ca479dbff26.failure.txt](https://github.com/dotnet/project-system/files/7716284/VsProjectFault_711c6d2b-2c54-4392-939b-0ca479dbff26.failure.txt)
