### ISSUE TITLE
unable to open sql file 

### ISSUE THREAD

**Issue by Varorbc** [dotnet/project-system#7751]
## Visual Studio Version

Visual Studio 2022 17.0

## Summary

Open for the first time 

![image](https://user-images.githubusercontent.com/5714438/141029195-e39cfe73-4d21-4f9a-8916-00020c5a2112.png)

Open for the second time 

![image](https://user-images.githubusercontent.com/5714438/141029255-6aeffc53-5ade-47bd-af95-3fc7a9597a49.png)

**Comment by davkean** [comment]
@Varorbc Can you please report this via Help -> Send Feedback -> Report a Problem so this can be routed to the right team that owns this?

**Comment by Varorbc** [comment]
ok,thanks
