### ISSUE TITLE
Section 508 502.3.1: (devenv/button '') The Name property of a focusable element must not be null.

### ISSUE THREAD

**Issue by japarson** [dotnet/project-system#7758]
The following accessibility issue needs investigation.

**App:** devenv

**Element path:** button ''

**Issue Details:** The Name property of a focusable element must not be null. [Section 508 502.3.1](https://www.access-board.gov/ict/#502-interoperability-assistive-technology)

**How To Fix:** Provide a UI Automation Name property that concisely identifies the element.

![image](https://user-images.githubusercontent.com/59936622/141216759-3f202fe1-08cf-4497-85a2-11c3bead09e1.png)

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by japarson** [comment]
For context, I'm in the process of getting the .NET 6 Xamarin iOS and Android property pages reviewed by the C + AI Accessibility team. One of the requirements was to run the Accessibility Insights tool on the pages and this is the result.

**Comment by drewnoakes** [comment]
Fixed in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/363783
