### ISSUE TITLE
Generated Compile files causing FastUpToDateCheck to rebuild.

### ISSUE THREAD

**Issue by ktaeleman** [dotnet/project-system#7784]
## Visual Studio Version
17.0.0

## Summary
When generating code files in a project, the resulting code files are always newer than the last FastUpToDateCheck check timestamp, causing msbuild to run again although no changes were made.
There does not seem to be a way to exclude generated code from the FastUpToDateCheck compile list to prevent this behavior as the `CollectUpToDateCheckInputDesignTime` target to customize the build only allows adding items.

## Steps to Reproduce

Pseudo project file
```
<Project>
<ItemGroup>
  <Compile Include="generatedcode.cs"/>
</ItemGroup>

<ItemGroup>
    <None Include="sourcedata.data"/>
    <UpToDateCheckInput Include="sourcedata.data" />
    <DataFile Include="sourcedata.data">
       <GeneratedFile>generatedcode.cs</GeneratedFile>
    </DataFile>
</ItemGroup>
</Project>
```
## Expected Behavior

Metadata can be added or a target can be overridden that allows filtering of the compile items, allowing the generated code to be considered as 'UpToDateBuilt' item.

## Actual Behavior

Compile items can't be filtered causing the build to run multiple times as the generated code is always newer than the last FastUpToDateCheck timestamp. I was not able to find a workaround for this behavior.

## User Impact

Projects compile multiple times with cascading effects. This is very confusing in solutions with lots (500+) projects.

**Comment by davkean** [comment]
Are you generating code into the obj directory?

**Comment by ktaeleman** [comment]
Hey David, thanks for the quick reply.

_> Are you generating code into the obj directory?_
No, we have a different setup.
Our folder structure looks more or less like this:

```
Root
-- Project
----Source
------sourcedata.cs
-- Local
----Project
------GeneratedCode
--------Project
----------Source
------------generatedcode.cs
------win64-release
--------buildoutput
------Project.csproj
```

**Comment by drewnoakes** [comment]
@ktaeleman the generated code should not exist within the project's regular set of input files.

I put together a sample repository that shows one way to generate source during build such that incremental build works correctly:

https://github.com/drewnoakes/generate-code-sample

Perhaps you can use that approach in your projects.

**Comment by ktaeleman** [comment]
Thank you so much for that, I'll give that a go and get back to you!

**Comment by ktaeleman** [comment]
Moving the generator target before CoreCompile and adding the output to the Compile ItemGroup in the same target worked nicely. Thanks a lot!
