### ISSUE TITLE
VS File->Open goes to TEMP directory when project file is open for editing

### ISSUE THREAD

**Issue by AArnott** [dotnet/project-system#780]
1. Create a Console App (.NET Core) project
1. Right-click on the project in Solution Explorer and Edit it (while open)
1. While the editor is focused, click File->Open

**Expected**
The open dialog presents my project directory (because that's where the file I'm currently editing is).

**Actual**
The %TEMP% directory is presented instead.

Dev15: d15prerel 25917.2

**Comment by davkean** [comment]
Yeah, that's fallout of how we let the project file get edited in VS due to limitations in the editor, we ended up having to copy to a temporary file. 

@333fred are there plans to switch back to the approach we originally started with?

**Comment by 333fred** [comment]
That's what I'm investigating next.

**Comment by 333fred** [comment]
It's looking like the temp file approach is what we're going to stick with for now. The buffer approach is promising, but there's some niggling issues with document state that I'm not sure we're going to be able to address without some changes to the Shell/Editor that wouldn't make bar at this point. I'm going to keep looking at this post RC2, but for now we're sticking with the temp file solution.

**Comment by davkean** [comment]
This has been fixed in 15.7.
