### ISSUE TITLE
Base project capabilities to determine project Type is not enough

### ISSUE THREAD

**Issue by SFC-Sarge** [dotnet/project-system#7807]
## Project Capabilities for built in Project templates need to be enhanced. 

I am working with @madskristensen on his new Visual Studio 2022 extension https://github.com/madskristensen/HelpExplorer that Adds a Help Explorer tool window that provides contextual help and resources. Great for beginners, students, and hobby programmers alike. We found that using project capabilities is great for determining the base project type (i.e. WPF, AspNetCore etc.) but since the HelpExplorer provides URL links to navigate based on the current project type that developer has open and is currently selected in Visual Studio Solution Explorer. We found that the base project type is not enough since (i.e. for a test project that (i.e. MsTest, NUnit, or xUnit), the project capabilities for each of these project types, are the same (see attached files.) Is there a way to determine project type based on the current project template used to create the project? Note: We also found that for a WPF project that contains an EXE, User Control Library, Custom Control Library, etc. that the libraries project capabilities are also the same, need a deeper return of project types if possible. 

For example, as developers we would not want to see URL links for NUnit from offered from HelpExplorer for a MsTest project. Since these are built-in templates, we do not have the option to add custom project capabilities to them.
 
[MsTest_CSharp_CPS_Capabilities.txt](https://github.com/dotnet/project-system/files/7641814/MsTest_CSharp_CPS_Capabilities.txt)
[NUnit_CSharp_CPS_Capabilities.txt](https://github.com/dotnet/project-system/files/7641816/NUnit_CSharp_CPS_Capabilities.txt)
[XUnit_CSharp_CPS_Capabilities.txt](https://github.com/dotnet/project-system/files/7641817/XUnit_CSharp_CPS_Capabilities.txt)

[WPFUserControlLibrary_Capabilities.txt](https://github.com/dotnet/project-system/files/7641874/WPFUserControlLibrary_Capabilities.txt)
[WPFLibrary_Capabilities.txt](https://github.com/dotnet/project-system/files/7641876/WPFLibrary_Capabilities.txt)
[WPFCustomControlLibrary_Capabilities.txt](https://github.com/dotnet/project-system/files/7641877/WPFCustomControlLibrary_Capabilities.txt)

**Comment by drewnoakes** [comment]
That sounds like a great extension.

I see two possible approaches here:

1. Query the project's package references to identify what testing framework(s) it uses.
2. Have the providers of those test frameworks add an MSBuild item (such as ProjectCapability) or property in their bundled .props/.targets files.

The downside of the second approach is that it relies upon the package maintainers making a change, and then the user of the extension having a new enough version of the package.

Therefore I believe the first approach is likely the best way forward here. Note that there's nothing stopping a project using more than one unit test library at a time.

**Comment by SFC-Sarge** [comment]
@drewnoakes thanks but tested number one and it will allow you to get which test package is used this same method does not work for which project type of WPF library since the package reference do not specify that the WPF library project is a Custom user control, user control, or just a library project. Do you have any sample C# code that would help [Mads](https://github.com/madskristensen) and I determine the difference?

**Comment by drewnoakes** [comment]
Can you check the MSBuild project properties `UseWindowsForms` and `UseWPF` instead?

**Comment by SFC-Sarge** [comment]
@drewnoakes; Sorry I must not have been clear. The Project Capabilities works fine to determine if it is a Windows Forms, or WPF. What it does not provide is if it is a WPF Library (determined by the Capabilities returned not having `CrossPlatformExecutable` listed.) for WindowsForms and WPF application projects this works fine, but if the project type is WPF Library (three forms of WPF Library ships with VS 2022, Custom Control, User Control, and Library) so, if the project is a WPF Custom Control we would like to return a URL link with info on WPF Custom Controls, etc.  Currently the returned Project Capabilities for the built-in project types do not differ between the WPF Library types. 

Here is the current `projecttypes.json` that shows what we query for `capabilityExpression` in the Project Capabilities.
[projecttypes.json.txt](https://github.com/dotnet/project-system/files/7653252/projecttypes.json.txt)

**Comment by drewnoakes** [comment]
Thanks for the extra information.

Note that from the project system's perspective there's no real difference between WPF class library, WPF custom control or WPF user control projects.

The contents of the `.csproj` are identical for all three. In fact, the only difference between those three and a WPF application is the `OutputType` is set to `WinExe` on the application.

The difference between these templates is the content they generate internally. But there's nothing stopping you creating a WPF class library and putting both a user control and a custom control in it.

**Comment by drewnoakes** [comment]
As an aside, you might find the following trick handy in VS if you're not already using it. Stick this in your project file and the project's capabilities will be displayed in Solution Explorer:

```xml
  <ItemGroup>
    <ProjectCapability Include="DiagnoseCapabilities" />
  </ItemGroup>
```

![image](https://user-images.githubusercontent.com/350947/144958741-5f76ffcb-5ac2-4cd8-af43-b5fe76284c4c.png)

**Comment by SFC-Sarge** [comment]
Thanks @drewnoakes;

I will let @[madskristensen](https://github.com/madskristensen) know so he can ask the MS PM he is working with to determine how much detail the HelpExplorer should return to the deverlop.

**Comment by SFC-Sarge** [comment]
@drewnoakes; I noticed when I add:
  ```
<ItemGroup>
    <ProjectCapability Include="DiagnoseCapabilities" />
  </ItemGroup>
```
To the solution it shows: Capabilities Version: 3, but if I save the solution, close it, and reopen it, it now shows Capabilities Version: 2. No big deal, and thanks for the info.

**Comment by SFC-Sarge** [comment]
@drewnoakes; One last thing, do you have an example of how to add Project Capabilities to a project template.  I create project templates and would like to add a few to my templates [WPFAppWithDocFxLoggingAndZip2022](https://marketplace.visualstudio.com/items?itemName=DannyMcNaught.WPFAppWithDocFxLoggingAndZip2022) besides the default ones. (i.e. DocFX, MS.Extension.Logging, and Zip support), but I am not sure how to update my '.target' file to include the custom project capabilities in my project template.
