### ISSUE TITLE
Incremental build logging is not localised

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7820]
By default the fast up-to-date check does not log messages. Users can enable logging via _Tools | Options | Projects | SDK-Style_.

These log messages are currently not localised and will always appear in English.

In 17.1 we are trialling a feature that flags incremental build failures. Diagnosing these failures requires enabling this logging. That increases the urgency that this logging should be localised.

**Comment by tmeschter** [comment]
We will need to fix this for 17.1 if at all possible.
