### ISSUE TITLE
Re-invented bug #3506

### ISSUE THREAD

**Issue by A-x-S** [dotnet/project-system#7830]
## Visual Studio Version
Microsoft Visual Studio Professional 2019
Version 16.11.8

## Summary
The percent character '%' followed by valid hex characters is interpreted as url encoded character. This is a behaviour that should have been/was fix according to bug #3506. Either it wasn't fixed or is reinvented.

## Steps to Reproduce

1. Open project settings->build events.
2. enter something like:
set cfg=$(Configuration)
if "%cfg:~0,8" equ "Release-" echo is release
3. Build the project

## Expected Behavior
"%cfg:~0,8" is evaluated to the first 8 characters of the build configuration

## Actual Behavior
"%cfg:~0,8%" is evaluated to "Ïg:~0,8%"

## User Impact
Breaks existing builds.

**Comment by drewnoakes** [comment]
Thanks for taking the time to submit this feedback.

The bug you mention was closed with the view that the new Project Properties UI, introduced in VS2022, does not exhibit this problem. Are you able to validate that with your test case? I've tried and the % signs appear to be escaped correctly.

**Comment by A-x-S** [comment]
Thanks for the fast response.
This is how it looks in a c++ make-file projects configuration UI using VS2022
![image](https://user-images.githubusercontent.com/93795352/146774361-eebf6d7f-829d-4763-a461-8e33469feb5e.png)
And the build output is:
1>------ Build started: Project: BugValidation, Configuration: Release x64 ------
1>Build started 20.12.2021 14:29:13.
1>Target Build:
1>  Ïg
1>
1>Build succeeded.
1>    0 Warning(s)
1>    0 Error(s)
1>
1>Time Elapsed 00:00:00.05
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

I wouldn't call this 'escaped correctly'.
Besides, what ever might be invented in VS2022 doesn't fix bugs in VS2019. And VS2022 is very, not to say extremely, unstable (crashing all over the place) and therefor not usable yet for professional development.

**Comment by drewnoakes** [comment]
Thank you for the additional detail. This repository is for .NET projects. For C++ you would need to report the problem via the Help menu in Visual Studio so that the right team can track the issue.

If you paste the link to your feedback ticket here I can make sure it is rooted to the correct team.

**Comment by A-x-S** [comment]
Understood. Should have taken a closer look to where the search had lead me. Opened a feedback issue report [here](https://developercommunity.visualstudio.com/t/build-event-interprets-percent-character-wrong/1618730). Seams that someone is looking at it already (at least the bot forwarded it).
