### ISSUE TITLE
Visual Studio 2022 doesn't copy a resource file to the Resources folder in a Visual Basic WinForms project

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/project-system#7845]
## Have you experienced this same bug with .NET Framework?
Yes

## More info
1. This is a regression issue; **it is not reproducing on Dev16 16.11.8, it reproduced from 17.0.3 to latest build 17.1 Preview3 32022.105**
2. This issue is not reproducing on WinForms C# project
3. This issue reproduced on both .NET core and .NET framework project

## Steps to Reproduce
1. Create a WinForms .NET Core Visual Basic project.
2. Drag and drop Picture Box onto the form.
3. Find the Image property in Property Grid and run the Select Resource dialog.
4. Import any image to the project’s resources.

## Actual Behavior
Visual Studio 2022 adds a file to the project’s resources and uses the file’s path in the .resx file
![Actual](https://user-images.githubusercontent.com/62929087/149251755-0915e16b-6e2e-46f3-8e8a-beb4b6fbd44d.gif)

## Expected Behavior
Visual Studio 2022 creates the Resources folder, copies the file, and uses the file’s copy path in the .resx file
![Expected](https://user-images.githubusercontent.com/62929087/149251872-67a56311-c3a0-4f65-b641-3d0135ddaba7.gif)

**Comment by tmeschter** [comment]
@Amy-Li03 Closing this bug as we have good reason to believe this is a bug in the Designer, and that is tracked by https://github.com/dotnet/winforms-designer/issues/4012.
