### ISSUE TITLE
Browsing for embedded package license file breaks the project

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7846]
## Visual Studio Version

17.0 and later

## Summary

Using the file browser to specify an embedded package license file via the Project Properties UI results in a project that won't pack correctly.

## Steps to Reproduce

1. Create a new class library or console app project
2. Open the project properties
3. Navigate to Package | License
4. Set "Package License" to "Embedded File"
5. Click "Browse" and select a file from the local disk
6. Save
7. Right click the project node and click "Pack"

![image](https://user-images.githubusercontent.com/350947/149712366-88a93455-0761-4e65-b55d-7b5400f3f50a.png)

## Expected Behavior

Project packs correctly.

## Actual Behavior

Error:

> C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5030: The license file 'D:\repos\aspnetcore\LICENSE.txt' does not exist in the package.

## User Impact

The error here is quite misleading as it suggests the file does not exist on disk, which is not the case. It's not obvious how to self-service one's way out of this.

**Comment by drewnoakes** [comment]
The above steps currently inject this in the project file:

```xml
<PropertyGroup>
  <PackageLicenseFile>D:\repos\aspnetcore\LICENSE.txt</PackageLicenseFile>
</PropertyGroup>
```

According to the docs on this (https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5030) the following should be created instead:

```xml
<PropertyGroup>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
</PropertyGroup>

<ItemGroup>
    <None Include="licenses\LICENSE.txt" Pack="true" PackagePath="" />
</ItemGroup>
```

This means the `LICENSE.txt` file should be copied into the project cone, if not already present.

We do this today for README files and package icons. @MiYanni added the former in https://github.com/dotnet/project-system/pull/7440 so I'm tentatively assigning this to him for now.

**Comment by drewnoakes** [comment]
Originally reported via feedback ticket: https://developercommunity.visualstudio.com/t/You-give-me-an-error-License-File-doesn/1617123

**Comment by MiYanni** [comment]
Yeah. All of these pack items should use the same value provider. I made a base class for it here: https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/PackageFilePropertyValueProviderBase.cs

And here's an example of it used for the Readme file: https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/PackageReadmeFileValueProvider.cs
