### ISSUE TITLE
Avoid redundant updates to the IWorkspaceProjectContext

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7847]
During solution open, and any time a project is updated, we notify Roslyn of relevant project data via the `IWorkspaceProjectContext` interface. Each update occurs within a transaction which has the following phases:

1. Call `IWorkspaceProjectContext.BeginBatch`
2. Call whatever `IWorkspaceProjectContext` members need to be updated
3. Call `IWorkspaceProjectContext.EndBatchAsync`

While investigating #7541, I observed that we frequently perform steps 1 and 3, while skipping step 2. Such empty batches seem wasteful. I asked @jasonmalinowski about this via email and he wrote:

> Fewer batch operations should generally be helpful, yes. The main benefit would be that it produces fewer Solution snapshots that the rest of our system will start to analyze. Otherwise those “intermediate” states we’ll start parsing/producing data for, only for it to get thrown away.

There are currently three dataflow sources that can trigger us to update the `IWorkspaceProjectContext` in a batch:

1. Evaluation
2. Source items
3. Build

We are not handling version-only changes properly, and are pushing empty updates through to Roslyn.

Furthermore, source items derive directly from evaluation, so they should be bundled and treated as a single update.

When loading a new class library project, we currently fire nine updates. This should only be two: one for evaluation, and one for build.

**Comment by jasonmalinowski** [comment]
@drewnoakes Hmm, I might have misunderstood the email conversation then. I was thinking you were doing multiple batches with stuff still in them -- I didn't quite realize this was empty batches. Those should be pretty harmless other than we're flooding the underlying semaphore slim with more work that'll release it. But sounds like your PR should be reducing other work at the same time too?

**Comment by drewnoakes** [comment]
@jasonmalinowski there are two scenarios:

1. We send through empty batches (fixed in #7848)
2. We report evaluation changes twice, once for each of the `ProjectRule` and `SourceItemsRule` data sources

Our email conversation covered both of these cases. For a new console app I saw nine batches. Fixing point 1 gets this down to three batches. Fixing point 2 gets this down to two batches. So I guess it's the second case that's likely to be more impactful.

The fix for point 2 is on my local machine and I'll submit a PR once #7848 is merged in.

Do you have any thoughts on how to measure a performance delta here? If you have tooling for that and are interested, the code is on branch https://github.com/drewnoakes/project-system/tree/combine-evaluation-and-source-items.

**Comment by jasonmalinowski** [comment]
I admit I usually use a stopwatch when measuring changes here opening a large solution like Roslyn itself. Although it's not terribly scientific, there's a lot of potential ways your change _could_ help, in terms of reducing contention or meaning Roslyn has fewer changes right away to process, which means anything short of a stopwatch time might miss some benefits that aren't immediately obvious.

**Comment by drewnoakes** [comment]
When do you stop your stopwatch? Is operation progress enough?

Given we've seen issues related to thread pool starvation around locks within the language service, hopefully fewer empty batches can help with that too, until a proper fix becomes available.

**Comment by drewnoakes** [comment]
@jasonmalinowski FYI the skipping of empty batches just inserted: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/375087

The last PR in that series combines evaluation and source item updates: https://github.com/dotnet/project-system/pull/7855
