### ISSUE TITLE
How to add fast up-to-date check support to a custom project?

### ISSUE THREAD

**Issue by crusader-mike** [dotnet/project-system#7850]
[Full issue](https://stackoverflow.com/questions/70672201/how-to-create-custom-project-file-that-works-with-fast-up-to-date-and-avoids-ot) is posted on SO and I welcome help with any of 3 mentioned issues.

But main problem is: how to extend this project to support Visual Studio's fast up-to-date checks?

Project (`myproject.csproj`) is a simple custom "wrapper" around angular-cli code (but it doesn't really matter, tbh):
```
<Project ToolsVersion="Current" DefaultTargets="Build">
  <PropertyGroup>
    <ProjectGuid>{...some-guid...}</ProjectGuid>
    <!-- do not include files by default -->
    <EnableDefaultItems>false</EnableDefaultItems>
    <!-- this removes 'Publish...' menu in VS -->
    <OutputType>Library</OutputType>
    <!-- output directory name -->
    <AngularProject>MyWebFiles</AngularProject>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>bin\Debug\</OutputPath>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>
  
  <ItemGroup>
    <AngularFile Include="**" Exclude="node_modules\**" />
  </ItemGroup>

  <Target Name="Build" Inputs="@(AngularFile)" Outputs="$(OutputPath)$(AngularProject)\index.html">
    <Exec Command="ng build --no-progress --output-path $(OutputPath)$(AngularProject)\" Condition="'$(Configuration)'=='Debug'" />
    <Exec Command="ng build --no-progress --output-path $(OutputPath)$(AngularProject)\ --prod" Condition="'$(Configuration)'=='Release'" />
  </Target>
  
  <Target Name="Clean">
    <RemoveDir Directories="$(OutputPath)$(AngularProject)\" />
  </Target>
  
  <Target Name="Rebuild" DependsOnTargets="Clean;Build" />
</Project>
```

**Comment by drewnoakes** [comment]
As this project does not specify an SDK, it is most likely being loaded by the traditional csproj project system, rather than the one developed in this repository.

The [fast up-to-date check documentation](https://github.com/dotnet/project-system/blob/main/docs/up-to-date-check.md) in this repo applies to these SDK style projects. You can refer to it when this project system is in use.

If you don't want to specify an SDK, then you can force this project system to load your project by changing the project type guid in your solution:

- `FAE04EC0-301F-11D3-BF4B-00C04F79EFBC` is the traditional project system (shows a "References" node in Solution Explorer)
- `9A19103F-16F7-4668-BE54-9A1E7A4F7556` is this project system (shows a "Dependencies" node in Solution Explorer)

**Comment by crusader-mike** [comment]
@drewnoakes I've tried adding this to `myproject.csproj`:
```
  <PropertyGroup>
    <ProjectTypeGuids>{9A19103F-16F7-4668-BE54-9A1E7A4F7556}</ProjectTypeGuids>
    ...
  </PropertyGroup>
```

Alas, VS2019  (v16.11.7) fails to load it with `E_NOTIMPL`:
```
C:\...\myproject.csproj : error  : The method or operation is not implemented.
```

- Am I missing something? 
- Do I have to specify project type in `.sln` file specifically? (in this case how VS will guess it's type when project is added to another solution via `Add\Existing Project...`?)
- Maybe there is a way to feed "traditional project system" all necessary information?

**Comment by drewnoakes** [comment]
You would have to set the project type GUID in the solution, not in the project file. That GUID influences which project system will load the project. By the time the project file has been read, it is (generally) too late.

You might like to look at https://github.com/microsoft/MSBuildSdks/tree/main/src/NoTargets. Using that SDK may mean you can avoid a bunch of complexity here.

**Comment by crusader-mike** [comment]
I have tried specifying project type in `.sln` file manually -- it fails with:
```
C:\...\myproject.csproj : error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.
```

Any idea what are those critical imports? Does VS actually look for these imports or it expects certain properties to be defined?

Wrt to NoTargets SDK -- I'll try it, but it seem I have to specify `TargetFramework` which in this context looks strange (since nothing in my project has anything to do with .Net).

**Comment by crusader-mike** [comment]
@drewnoakes, thank you very much for your help. I finally figured it out, it seems:
```
<Project Sdk="Microsoft.Build.NoTargets/3.2.14">
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.NoTargets" Version="3.2.14" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Any target framework you want as long as its compatible with your referenced NuGet packages -->
    <TargetFramework>net462</TargetFramework>
    <Platforms>x64</Platforms>
    <!-- Do not add TargetFramework to OutputPath -->
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <!-- Do not expect pdb files to be generated (this is for fast up-to-date check) -->
    <DebugType>None</DebugType>
    <!-- Do not include files by default -->
    <EnableDefaultItems>false</EnableDefaultItems>
    <!-- Output subdir name -->
    <AngularProject>MyWebFiles</AngularProject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\..\Bin\Debug\</OutputPath>
    <BuildCommand>ng build --no-progress --output-path $(OutputPath)$(AngularProject)\</BuildCommand>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\..\Bin\Release\</OutputPath>
    <BuildCommand>ng build --no-progress --output-path $(OutputPath)$(AngularProject)\ --prod</BuildCommand>
  </PropertyGroup>

  <ItemGroup>
    <None Include="**" Exclude="node_modules\**;$(BaseIntermediateOutputPath)\**;$(MSBuildProjectFile)" />
    
    <!-- This deals with fast up-to-date checks -->
    <UpToDateCheckBuilt Original="package-lock.json" Include="node_modules/.build" />
    
    <UpToDateCheckInput Include="@(None);$(MSBuildProjectFile)" Set="AngularFiles" />
    <UpToDateCheckOutput Include="$(OutputPath)$(AngularProject)\index.html" Set="AngularFiles" />
  </ItemGroup>

  <Target Name="InitModules" Inputs="package-lock.json" Outputs="node_modules/.build">
    <Exec Command="npm ci --no-progress --no-color" YieldDuringToolExecution="true" />
    <Exec Command="cd . &gt; node_modules/.build" />
  </Target>

  <Target Name="BuildAngular" BeforeTargets="AfterBuild" Inputs="@(None);$(MSBuildProjectFile)" Outputs="$(OutputPath)$(AngularProject)\index.html" DependsOnTargets="InitModules">
    <Exec Command="$(BuildCommand)" YieldDuringToolExecution="true" />
  </Target>

  <Target Name="CleanAngular" BeforeTargets="AfterClean">
    <RemoveDir Directories="$(OutputPath)$(AngularProject)\" />
  </Target>
</Project>
```

I could see only one minor nuisance here -- `obj` folder gets created and is full of stuff (but it can be moved away by overriding `IntermediateOutputPath`, e.g. for out-of-source build).

If you see how this project can be improved in any way -- please, let me know...

**Comment by drewnoakes** [comment]
Regarding `Publish...` if you can add this late enough in the evaluation (in a .targets file), it might help:

```xml
  <ItemGroup>
    <ProjectCapability Remove="Publish" />
  </ItemGroup>
```

**Comment by drewnoakes** [comment]
For your interest, if you add...

```xml
    <ProjectCapability Include="DiagnoseCapabilities" />
```

...you will see a tree of capabilities appear in Solution Explorer. These `ProjectCapability` items turn certain project features on and off. This is not always supported, as we cannot test all combinations of capabilities. It might help in the case of publish though.

**Comment by crusader-mike** [comment]
Thank you, @drewnoakes. Very much appreciated

**Comment by crusader-mike** [comment]
@drewnoakes Curiously, removing `Publish` capability did absolutely nothing, in fact it didn't even remove it from the list of capabilities generated by `DiagnoseCapabilities`.

Another curiosity: adding `DiagnoseCapabilities` creates a `Capabilities Version: X` node in "Solution Explorer", where X seem to be fluctuating between 2 and 4 in completely unpredictable manner. Some times you need to reload project to get X to change (after you change project file). Weird...

What is the meaning of X? some sort of version of class that deals with these capabilities under the cover?

**Comment by drewnoakes** [comment]
> Curiously, removing `Publish` capability did absolutely nothing

Are you sure the item is removed from the final evaluation? These are added very late in design-time builds (in a `.targets` file that ships with VS) so it's possible that your attempt to remove it is happening before it has even been added.

> What is the meaning of X?

It's an internal version number for project state that will have no meaning to anyone who isn't implementing code that runs within the project system. It will increase every time the project's capabilities are changed.

**Comment by crusader-mike** [comment]
>>Curiously, removing Publish capability did absolutely nothing
>
>Are you sure the item is removed from the final evaluation? These are added very late in design-time builds (in a .targets file that ships with VS) so it's possible that your attempt to remove it is happening before it has even been added.

Likely you are correct -- `Publish` capability is added later, so I need to either figure out a condition/variable that will stop it from happening or add that magic `.targets` file that gets pulled in by VS. I am too lazy for this... None of this is worth the time I already spent on it. :)
