### ISSUE TITLE
How to use UseCommonOutputDirectory correctly?

### ISSUE THREAD

**Issue by crusader-mike** [dotnet/project-system#7852]
`UseCommonOutputDirectory` seem to be a nice feature and fits our use case (our entire solution is compiled into the same directory). But switching it on breaks the build -- because all nugets don't get deployed to output dir, nor do references that point to specific `.dll` via `HintPath`.

What is the proper way to use this feature?

**Comment by drewnoakes** [comment]
This is a feature of MSBuild, not this repo, so your question would be better asked at https://github.com/dotnet/msbuild.

We use `UseCommonOutputDirectory` in this repo, though our build is quite custom so may not map well to yours. 

The discussion on https://github.com/dotnet/roslyn/issues/8975 might be of help to you.

**Comment by crusader-mike** [comment]
Yeah, I saw that discussion already. Basically, for your typical solution (with nugets and blackjack tables) this `UseCommonOutputDirectory` is not going to work at all... :-/

**Comment by drewnoakes** [comment]
See also https://twitter.com/davkean/status/991651609443643392
