### ISSUE TITLE
Support disabling configuration by specific dimensions per property

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7873]
(Extracted from #6907)

Currently, for configurable properties., the Project Properties UI allow varying the value by all dimensions (for example: Debug/Release, AnyCPU/x64, net48/net60).

For some properties, this is not desirable.

In #6907 we noted TF for Output Path as an issue.

For MAUI projects, we may wish to disable varying by target framework for certain properties (for example, allowing an Android property to be specified for iOS doesn't make sense).

---

This is similar to #7874, but distinct. It may be a single solution exists to both issues however.

**Comment by MiYanni** [comment]
Related to: https://github.com/dotnet/project-system/issues/7052

**Comment by adamint** [comment]
PR to track this: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/389081

**Comment by adamint** [comment]
Complete thru https://dev.azure.com/devdiv/DevDiv/_git/CPS/pullrequest/389081
