### ISSUE TITLE
Support disabling configuration by specific dimensional values per property

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7874]
(Extracted from #6907)

Currently, for configurable properties., when a property in the Project Properties UI is varied by a given dimension, all values within that dimension are provided to the user.

For some properties, this is not desirable.

In #6907 we noted that "Prefer 32-bit" does not apply for platform x86.

For MAUI projects, we may wish to disable entering values for specific target frameworks for certain properties.

---

This is similar to #7873, but distinct. In that issue we propose disabling the ability to vary a property by a dimension altogether. In this issue, we allow varying, but disallow specifying a value for one or more dimension values. It may be a single solution exists to both issues however.

**Comment by drewnoakes** [comment]
Another case is when visibility is configured on another property, but that property has different values per configuration.

In this screenshot, we would ideally hide the "Debug" option for "Treat specific warnings as errors" because we are in fact treating all warnings as errors in that configuration:

![image](https://user-images.githubusercontent.com/350947/152335964-d20fce09-4a4b-4e2d-9e39-9525f1eac1a0.png)

**Comment by MiYanni** [comment]
Related to: https://github.com/dotnet/project-system/issues/7052

**Comment by adamint** [comment]
PR to track this: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/389081

**Comment by adamint** [comment]
Completed thru https://dev.azure.com/devdiv/DevDiv/_git/CPS/pullrequest/389081
