### ISSUE TITLE
Some property values not correctly simplified

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7886]
Seen in a new Blazor WebAssembly project:

![image](https://user-images.githubusercontent.com/350947/152325619-d67aeb70-d6bf-489d-8d3a-4eb08675b8ab.png)

This is how the properties appear on a new project when first loaded. These checkboxes with matching states should have been collapsed into a single value. The same for the File Alignment property.

**Comment by adamint** [comment]
This doesn't repro
