### ISSUE TITLE
Persist startup project(s) in solution (.sln) file for the sake of Blazor WebAssembly

### ISSUE THREAD

**Issue by Bellarmine-Head** [dotnet/project-system#7934]
## Summary
Storing what a solution's startup project(s) is in the hidden and non-persisted `.suo` file is crazy.  This important setting needs to be in the solution (.sln) file, and thus:-

* persisted to your version control system
* included in distributed new-solution templates.

When you create a new Blazor WebAssembly solution in Visual Studio 2022, the startup project is the "Current selection".  Since your `Server` project is selected by default (probably because it's listed first in the .sln file), then when you hit F5, all will be fine.  But - as people discover a little bit later on to their cost - if you happen to innocently select the `Client` project in the Solution Explorer, and then hit F5... things will go badly wrong.  At first you may not even notice that things have gone wrong.  And resolving the problem is not easy or obvious.

I.e. it's **very** easy to get this wrong.  A slip of the mouse and **bang!** your website isn't working and you have no idea why.

So you learn that you should always set the startup project setting to `Single startup project`, where the single project in question is the `Server` project.

After you will have no more problems until....

* you clone the solution anew from version control
* someone else clones your project from version control, and doesn't spot your dire warnings in the `Readme` to set the `Server` project as the startup
* you have to delete your hidden `.vs` folder for whatever reason (it happens).

Since the choice of startup project **is so important** for a Blazor WebAssembly solution, it seems crazy that this setting is stored in the `.suo` file.

Surely it's time to do the right thing (after years of knowing about this problem) and store the setting in the solution file instead?  (and also update the Blazor WebAssembly solution templates accordingly).

## User Impact
It's all too easy for your Blazor WebAssembly solution to basically *not work* in confusing and non-obvious ways without getting this setting absolutely right.  And sometimes it can take a fair bit of tinkering to get your solution working even if you're able to diagnose the problem.

**Comment by tmeschter** [comment]
@Bellarmine-Head This functionality is owned by a different team in Visual Studio. Could you please file a feedback ticket through "Help | Send Feedback | Report a Problem..." in Visual Studio? That way we can get it in front of the right team and you can track the progress.

I'll keep this issue open on our backlog if you would like to link to it in the Feedback ticket.

See also: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

**Comment by drewnoakes** [comment]
@Bellarmine-Head if you link your feedback ticket here I can help route it internally.

**Comment by Bellarmine-Head** [comment]
> @Bellarmine-Head if you link your feedback ticket here I can help route it internally.

Thank you!

Here is the link to my feedback ticket:-

https://developercommunity2.visualstudio.com/t/Persist-startup-projects-in-solution-/1678968?space=8&q=Persist+startup+project%28s%29+in+solution+%28.sln%29+file+for+the+sake+of+Blazor+WebAssembly

**Comment by drewnoakes** [comment]
Closing as external to this repo.
