### ISSUE TITLE
File nesting does not work in non-web projects VS 2022

### ISSUE THREAD

**Issue by drauch** [dotnet/project-system#7939]
## Visual Studio Version

Version 17.0.1

## Summary

We switched from VS 2019 to VS2022 and file nesting (we're using ..filenesting.json) in non-web-projects no longer works. It doesn't help to switch from "Standard" to "Web" in the solution explorer either.

## Steps to Reproduce

1. Add .filenesting.json like so:
```
{
  "help": "https://go.microsoft.com/fwlink/?linkid=866610",
  "root": true,

  "dependentFileProviders": {
    "add": {
      "addedExtension": {},
      "pathSegment": {
        "add": {
          ".*": [
            ".yml"
          ]
       }
    }
  }
}
```
2. Add suitable files like appsettings.yml and appsettings.Production.yml
3. They do not nest

## Expected Behavior

They should nest like in VS2019.

## Actual Behavior

They do not nest like in VS2019.

## User Impact

We have lots of configuration files which no longer nest and it is _very_ confusing to see all those files every time I open the project in solution explorer. We furthermore have cs files which have been split up in partial files and they do no longer nest either.

Please fix soon, it worked perfectly in VS2019

**Comment by csegyud** [comment]
Good news: this is added to milestone [17.2](https://github.com/dotnet/project-system/milestone/40)  
It was removed from several earlier milestones - for good reasons I know. 
I hope it will finally remain there. :)

**Comment by drewnoakes** [comment]
Enabling this for all projects by default is blocked on:

- #7161 

We need to either address the performance issue, or find a way to enable it per-project.

Until we solve that, you can workaround by adding this to your project file:

```xml
<ItemGroup>
  <ProjectCapability Include="ConfigurableFileNesting" />
  <ProjectCapability Include="ConfigurableFileNestingFeatureEnabled" />
</ItemGroup>
```

**Comment by drauch** [comment]
Thank god there is a workaround, great!

**Comment by kvenkatrajan** [comment]
This is working as per design. Please pick "Web" option in File Nesting configuration/dropdown. This applies only to sdk style projects.

**Comment by kosalanuwan** [comment]
> This is working as per design. Please pick "Web" option in File Nesting configuration/dropdown. This applies only to sdk style projects.

I just tried this by selecting the Solution.sln file and it seemed to apply for all the projects. But, where do these settings get saved? Is it user-based under Visual Studio Settings? Or limited to the Workspace? or Build.props? Or .csproj?

I checked under Tools > Options > Environment and Project and Solution, but no luck finding the flag. Version Control also not detecting any changes.

**Comment by CrispyDrone** [comment]
> Enabling this for all projects by default is blocked on:
> 
>     * [File Nesting: Investigate file nesting performance impact on non-web projects  #7161](https://github.com/dotnet/project-system/issues/7161)
> 
> 
> We need to either address the performance issue, or find a way to enable it per-project.
> 
> Until we solve that, you can workaround by adding this to your project file:
> 
> <ItemGroup>
>   <ProjectCapability Include="ConfigurableFileNesting" />
>   <ProjectCapability Include="ConfigurableFileNestingFeatureEnabled" />
> </ItemGroup>

This does not seem to work for a non-sdk style vb.net project using visual studio 17.14.21 
It thinks these are 2 files it can't find in the project directory. The `.filenesting.json` also has no effect on anything.
