### ISSUE TITLE
VS Solution Explorer does not show certain folders in a very simple custom SDK style project

### ISSUE THREAD

**Issue by MarkKharitonov** [dotnet/project-system#7941]
**Visual Studio version**
Microsoft Visual Studio Enterprise 2022 (64-bit) 
Version 17.0.4

**Description**
I have a very simple custom SDK style project here (https://github.com/MarkKharitonov/HiddenFolders):
```
C:.
│   .gitignore
│   Directory.Build.props
│   Directory.Build.targets
│   LegacyFrontEnd.sln
│
└───Approvals
    │   Approvals.csproj
    │
    ├───Content
    │       approvals_icons.png
    │
    ├───Scripts
    │       Approvals.ts
    │
    └───StaticViews
            Approvals.html
```
My problem is that VS Solution Explorer does not show the `Scripts` folder:

![image](https://user-images.githubusercontent.com/489792/155383621-ee62b0c2-dcdc-4e23-99bc-cbf71ec0eed2.png)

The build code is trivial, but it replaces the standard build targets of the SDK:

**Directory.Build.props**
```
<Project>
  <PropertyGroup>
    <EnableDefaultItems>False</EnableDefaultItems>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <TypeScriptCompile Include="Scripts\**\*.ts" />
    <Stylus Include="Stylus\**\*.styl" />
    <Content Include="Content\**\*.*" />
    <Content Include="StaticViews\**\*.*" />
  </ItemGroup>
</Project>
```

**Directory.Build.targets**
```
<Project>
  <Target Name="Build" />
  <Target Name="Clean" />
  <Target Name="Rebuild" DependsOnTargets="Clean;Build" />

  <Target Name="CompileTypeScript" BeforeTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)\_jsCompiled"/>
    <Touch Files="$(MSBuildProjectDirectory)\_jsCompiled\Approvals.js" AlwaysCreate="true" />
  </Target>
</Project>
```

**.\Approvals\Approvals.csproj**
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputPath>bin</OutputPath>
  </PropertyGroup>
</Project>
```

Very simple.

Why does VS Solution Explorer not show the **Scripts** folder?

P.S.

Also posted here - https://stackoverflow.com/questions/71164341/why-visual-studio-hides-certain-folders-in-a-codeless-c-sharp-project

**Comment by MarkKharitonov** [comment]
We have an old enterprise application. It used to have 50 Asp.Net projects, but not because these projects represented a web application each. No, they just implemented different aspects of one big web application. During the build, these "fake" web applications build the Typescript and Stylus files using ad-hoc targets that run before `Build` and copy the products to the big web application. We have downgraded these "fake" web applications to normal C# projects, but the fact that they mix C# and Typescript is problematic for us. So, we want to separate them - C# aside, legacy front end code aside. I call it legacy, because at the same time the front end is being migrated to React micro frontends. But right there is a ton of legacy front end code and it would take literally years to migrate it all (it took us about 10 years to get rid of the Silverlight completely).

So, I am trying to figure out what project format to use for the legacy front end code. Right now, the SDK style projects is the best option I can see. The project files are small and the build code is injected through Directory.Build.* files (of course, the real files are more sophisticated than in my repro). The command line build using msbuild works great. But the VS IDE experience is a problem.

I am open to suggestions, but I cannot change the paradigm where front end code from many different projects is copied to a single location during the build, which corresponds to the location of the big web application. 

If I could "tell" VS to show the **Scripts** folder that would have been the easiest.

**Comment by drewnoakes** [comment]
> If I could "tell" VS to show the Scripts folder that would have been the easiest.

MSBuild projects produce many many items of different types. It does not show all these items in Solution Explorer. It only shows certain types.

`TypeScriptCompile` items are not shown. If you want to see them in the tree, you'll have to add them as a different type. For example:

```xml
<ItemGroup>
   <None Include="@(TypeScriptCompile)" />
</ItemGroup>
```

**Comment by drewnoakes** [comment]
Actually, a simpler approach may be for you to use this instead:

```xml
<ItemGroup>
    <AvailableItemName Include="TypeScriptCompile" />
</ItemGroup>
```

I haven't tested this though.

**Comment by MarkKharitonov** [comment]
@drewnoakes - The last approach does work. Thank you very much.

**Comment by MarkKharitonov** [comment]
@drewnoakes - would you like to answer on my SO question, so that I could credit you there?

**Comment by drewnoakes** [comment]
@MarkKharitonov sure, thanks. Done. I wanted to test my first suggestion on your repro but it seems you deleted the repo. Did it not work for you?

**Comment by drewnoakes** [comment]
Also, for what you're trying to do, this might be helpful: https://github.com/microsoft/MSBuildSdks/tree/main/src/NoTargets

**Comment by MarkKharitonov** [comment]
The repo was somehow private. I changed it back to public. Sorry for that.
