### ISSUE TITLE
Design a way to get the supported Target Framework List for Net core projects

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/project-system#795]
We need to come up with a design for this, here’s a couple of things to think about:

1)	You’re not always going to have project context to get the list of TFMs – think File -> New where you have a drop down to select the version of .NET Core you want to create the project with. If it comes from the project, you need a project before you’ve created a project.
2)	You’ll want friendly names, .NETStandard, Version=v1.0 isn’t something to show the developer, it would be “.NET Standard 1.0”
3)	You’ll also want a way to get the NuGet name, as that’s the thing you need to persist.

I’m thinking that we should just reuse (and extend) the existing multi-targeting system, either by dropping a RedistList for all these frameworks, and then add a field for the nuget name. That means the existing multi-targeting service and those that use will just work. One other thing we might want to consider is adding a per-VS registration instead of the per-machine registration we have today.

Packages can bring in the list of TFMs that they target so that a dev version of a package can add a TFM for eg. Making it per-machine or per-vs wont enable that scenario.

**Comment by davkean** [comment]
When this is implemented, remove the hardcode of .NETStandard/.NETCore here: https://github.com/dotnet/roslyn-project-system/pull/1877

**Comment by davkean** [comment]
@panopticoncentral Sync with me around this - I have some ideas how we would do with this by plugging into the existing infrastructure.

**Comment by srivatsn** [comment]
Fixed with #2097
