### ISSUE TITLE
Optimize fast up-to-date check's handling of CopyAlways items

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7961]
## Summary

When an item is to be copied to the output directly, there are two options:

1. `CopyToOutputDirectory="Always"` always copies source over destination
2. `CopyToOutputDirectory="PreserveNewest"` copies the file is the timestamp of the source is newer than the destination

Today, having a single `Always` item in a project causes the fast up-to-date check to immediately flag the project as out of date, leading to a build.

It is very easy for users to select the `Always` option and unwittingly break incremental build performance.

~In practice, there does not seem to be a valid use case for `Always` beyond the behaviour of `PreserveNewest`.~

An example of when you might want the behaviour of `Always` is in https://github.com/dotnet/project-system/issues/7961#issuecomment-1063474242.

## Proposal

- ~Change the fast up-to-date check to treat `Always` as it currently treats `PreserveNewest` by default.~
- Change the fast up-to-date check to check timestamps and file sizes for `Always` items, and not fail if they are the same.
- Add an MSBuild project property that restores the old behaviour if needed.

## User Impact

`Always` items are currently responsible for:

- Around 20% of all scheduled builds in VS.
- Around 17% of all incremental build failures in VS.

With the proposed change, the failures should disappear and builds will only be scheduled when the item to be copied is actually out of date with respect to its target file.

**Comment by drewnoakes** [comment]
> In practice, there does not seem to be a valid use case for `Always` beyond the behaviour of `PreserveNewest`.

@davkean pointed out a valid use case for `Always`:

1. Build copies `Always` item `data.xml` to the output directory
2. App runs and modifies `data.xml` (making it the newest)
3. The developer desires subsequent runs to reset `data.xml` back to its default state

This is a plausible scenario, but seems much less likely than the case where `Always` was set without knowing the build performance impact. If the above scenario is needed, and we merge #7963, then the developer can set property `DisableFastUpToDateTreatsCopyAlwaysAsPreserveNewest` to true in their project to preserve the old behaviour.

**Comment by drewnoakes** [comment]
> If the above scenario is needed, and we merge https://github.com/dotnet/project-system/pull/7963, then the developer can set property `DisableFastUpToDateTreatsCopyAlwaysAsPreserveNewest` to true in their project to preserve the old behaviour.

Thinking about this some more, we can do better than the current iteration of #7963. Rather than treating CopyAlways and PreserveNewest the same, we should just loosen the rules on CopyAlways a little.

Today, PreserveNewest means "copy to the output directory if the source file is newer".

The behaviour for Always should be "copy to the output directory if newer, older, or has differing file size."

The opt-out property should also change name. Something like `DisableFastUpToDateCopyAlwaysOptimization` becomes a better fit.

**Comment by davkean** [comment]
Much better approach!

**Comment by mrlacey** [comment]
Where will this fix be experienced?
Does it affect all projects built in VS17.2 and above? Even ones targeting .NET Framework?

**Comment by drewnoakes** [comment]
It'll be for SDK style projects in 17.2 and above.
