### ISSUE TITLE
Compile items removed by targets still present in Roslyn workspace

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#7973]
## Visual Studio Version

17.2.0 Preview 3 (specifically VS main 32309.98).

## Summary

Compile items present in evaluation but removed by targets are still present in the Roslyn workspace. This has a number of downstream affects, such as:

- The Navigation Bar for the removed file shows it as still present for one or more of the project's TargetFrameworks.
- Errors from Intellisense do not match errors from builds.
- Hot Reload in MAUI scenarios is broken as the language service believes everything is a rude edit.

## Steps to Reproduce

1. Create a new Console application targeting .NET 6.
2. Add a new class to the project, in a file named "Class1.cs".
3. Update Program.cs to refer to the new class:
``` csharp
Console.WriteLine("Hello, World!");

var c = new Class(); // Add usings as needed.
```
4. Unload the project.
5. Edit the project file and replace the `TargetFramework` property with `<TargetFrameworks>net6.0;net6.0 windows</TargetFrameworks>`.
6. Add the following target to the project:
``` xml
  <Target Name="RemoveClass1" BeforeTargets="CoreCompile">

    <Message Text="Attempting to remove Class1.cs" />
    
    <ItemGroup>
      <Compile Remove="Class1.cs" />
    </ItemGroup>
    
  </Target>
```
7. Reload the project.
8. Open Class1.cs and inspect the Navigation Bar drop downs.
9. Open Program.cs and observe how Class1.cs is handled by colorization and Intellisense.
10. Build the project.

## Expected Behavior

Intellisense errors should match the build errors. Class1.cs should show as being part of the "Miscellaneous Project" in the Nav Bar.

## Actual Behavior

The build fails (as it should) but no errors come from Intellisense. The Nav Bar drop downs indicate that Class1.cs is part of the project, even though it is not.

## User Impact

This manifests in MAUI single-project apps where source files that are only present in one configuration (e.g., in Android, but not iOS or Windows) still seem to be present in all configurations in the IDE. This causes numerous downstream issues, including (we believe) that Hot Reload does not function because of the mismatch between what the Roslyn workspace thinks is in the project and what has actually been compiled into the final assembly.

**Comment by Nirmal4G** [comment]
> Compile items present in evaluation but removed by targets are still present in the Roslyn workspace.

That's the expected behavior since, project system only evaluates until targets phase or in some cases, initial targets or known targets depending on the project system needs.

The DesignTime targets (_ones that provide intelli-sense_) skips and overrides some nodes in the full `Build` target graph, and thus results from a DesignTime build might not match completely with a full Build especially with a heavily customized build environment.

More info on [DesignTime builds](/dotnet/project-system/blob/main/docs/design-time-builds.md) and how to diagnose them.

**Comment by tmeschter** [comment]
We decided to handle this by supporting additional metadata on the item in the evaluation item that will cause us to ignore it rather than pass it to the language service; see #8115 for the details.
