### ISSUE TITLE
Evaluation cache breaks project properties UI

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#7980]
## Visual Studio Version

17.2.0 Preview 3.0 [32314.166.main]

## Summary

Project properties don't populate correctly when the project is restored from the evaluation cache.

## Steps to Reproduce

1. Create a new .NET 6 console app
2. Open project properties and view Debug | Errors and warnings:
    ![image](https://user-images.githubusercontent.com/350947/158285838-bd5e2ec1-6027-4ac3-a857-bb6f8d416894.png)
3. Close and reopen solution
4. Notice project comes from cache (via star on icon, available on internal builds only):
    ![image](https://user-images.githubusercontent.com/350947/158285978-ae7f8cd0-897e-4190-8476-e9dc4ec1cfc8.png)
5. Check project properties again
    ![image](https://user-images.githubusercontent.com/350947/158285910-8acfdc6d-43fa-471f-a9fc-ee30ac6ba6e5.png)

## Expected Behavior

UI is unchanged.

## Actual Behavior

Properties appear duplicated.

This happens to many properties in the UI (not just errors/warnings).

**Comment by drewnoakes** [comment]
FYI @arkalyanms as this appears related to evaluation caching.

**Comment by arkalyanms** [comment]
Taking a look. This might be a regression from the TFS change to use the project xml and its dependent PRE for the matching, perhaps the PRE in question is knocked off memory.

**Comment by drewnoakes** [comment]
> more likely a change in the sequence of values

Can you elaborate on what you mean by this?

**Comment by arkalyanms** [comment]
The property list will not contain duplicates or unevaluated values in the cache mode. Right now, when the project property page is opened, it implicitly creates a new evaluation for the Release although the active configured projects is Debug. So the property page will compare the bookmark definitions between the two configurations and find the non-existence of unevaluated entries in the cache mode configuration. 

I guess the right fix is to break out of cache mode for the active configured project for the property pages - https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/386579

**Comment by arkalyanms** [comment]
This is in main today
