### ISSUE TITLE
Project property page "Vary by configuration" gear menu icon has null name property

### ISSUE THREAD

**Issue by japarson** [dotnet/project-system#8001]
## Visual Studio Version
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.2.0 Preview 2.0

## Summary
Project property page "Vary by configuration" gear menu icon has null name property.
- [Bug 1504593](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1504593): A11y_Visual Studio Client_Code generation and run time section_SDK version_AI4D: Section 508 502.3.1: (devenv/menu item '') The Name property of a focusable element must not be null.

![image](https://user-images.githubusercontent.com/59936622/159596813-5fbae38c-61af-4436-bb5a-082f8c5df6f2.png)

## Steps to Reproduce
1. Create new iOS project from power shell using dotnet new ios -n <project_name>.
1. Open VS 2022, select "Open a project or solution" option, and press enter.
1. Open "iOS Build" page.
1. Hover the configuration condition gear icon on the SDK Version property so that it is visible.
1. Run [Accessibility Insights for Windows](https://accessibilityinsights.io/) on this window.

## Expected Behavior
Accessibility Insights returns no errors.

## Actual Behavior
Accessibility Insights returns an error: "Provide a UI Automation Name property that concisely identifies the element".

## User Impact
This might affect the user screen reader experience.

[MAS 4.2.1 – Object Information](https://microsoft.sharepoint.com/:w:/r/sites/accessibility/CELA/Official_Microsoft_Accessibility_Standards/MAS%204.2.1%20%E2%80%93%20Object%20Information.docx?d=weee97bbd999048a08b036ea775581aa8&csf=1&web=1&e=oK4Gcr)

**Comment by melytc** [comment]
This has been fixed.
