### ISSUE TITLE
Prefer 32-bit property not displaying when it should

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8016]
## Summary

The "Build" page's "Prefer 32-bit" property should be visible in some cases, as defined here:

https://github.com/dotnet/project-system/blob/791fc3fe6d18391a5ab3b9cafbed3a9a04a3488b/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml#L109-L120

## Steps to Reproduce

1. Create this project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

</Project>
```

2. Open the Project Properties UI 
3. "Prefer 32-bit" is not visible

## Expected Behavior

Should be visible.

## Actual Behavior

Is not visible.

**Comment by adamint** [comment]
I am able to reproduce this.

**Comment by adamint** [comment]
After further look, it seems like this project defaults to x86 PlatformTarget, which means that the property will not be visible.
However, after manually changing platform target to anycpu, 
` Evaluate("(unevaluated \"Build\" \"PlatformTarget\")")`
Evaluates to "Any CPU", with the space
