### ISSUE TITLE
CreateProjectContextHandlingFaultAsync should apply its changes in a batch scope

### ISSUE THREAD

**Issue by sharwell** [dotnet/project-system#8027]
## Visual Studio Version

17.2.0 Preview 3.0 [32328.651.main]

## Summary

🔗 [AB#1511966](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1511966)

A heap dump analysis of a local UI delay shows 176 threads blocked on a semaphore attempting to synchronously set `LastDesignTimeBuildSucceeded`.

## Steps to Reproduce

I just opened dotnet/roslyn-sdk.

## Expected Behavior

`CreateProjectContextHandlingFaultAsync` should create a batch scope around setting `LastDesignTimeBuildSucceeded`, and then await the release of that scope. This will avoid thread pool starvation by yielding while awaiting the semaphore instead of blocking on it.

## Actual Behavior

`CreateProjectContextHandlingFaultAsync` blocks on the synchronous completion of `LastDesignTimeBuildSucceeded`.

## User Impact

Long UI delay while the thread pool spins up hundreds of threads to bypass the starvation.

**Comment by drewnoakes** [comment]
@jasonmalinowski I made a caller-side fix in https://github.com/dotnet/project-system/pull/8031 for this issue. Does that look reasonable to you, or did you have a different solution in mind?

**Comment by drewnoakes** [comment]
We also need to decide if we want this for 17.2 or if it can wait for 17.3.

**Comment by jasonmalinowski** [comment]
@drewnoakes: yes that's all I was going to do.

**Comment by jasonmalinowski** [comment]
(my idea of "oh, this is quick, let me just do it" was scuttled by a bunch of meetings)

**Comment by sgreenmsft** [comment]
@drewnoakes - I believe this issue causes a hang (or at least several minutes of delay) on Solution Close for a partner team (see devdiv bug 1508575) so if possible getting this change into 17.2 would be ideal (and 17.2 Preview 3 would be fantastic).
