### ISSUE TITLE
File rename fails the first time 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/project-system#803]
![image](https://cloud.githubusercontent.com/assets/12449387/20575021/470c971e-b16c-11e6-80f1-619f5908f63a.png)

Now rename the 'class1' to 'foo' manually 
try rename again (change file 'foo' to 'bar') , this time it successfully renames but still shows IntelliSense error 

![image](https://cloud.githubusercontent.com/assets/12449387/20575081/9ba9e8c6-b16c-11e6-948b-8b9a673f1bc2.png)

**Comment by jinujoseph** [comment]
The rename works fine in d15rel/15.0.26006.2 and the failure message is only displayed for the first project and  rebuilding clears the failure

**Comment by jinujoseph** [comment]
Flaky occurance

**Comment by tmeschter** [comment]
Blocked waiting for fixes on the CPS side. See #2852 for details.
