### ISSUE TITLE
Avoid horizontal scroll bar in launch profile arguments text box

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8034]
#7919 allowed newlines in launch profile arguments for executables.

If you have one very long argument then a horizontal scroll bar is introduced, making the text box harder to work with.

Anecdotally, launch arguments are often file paths, which tend to be lengthy and can end up looking this like:

![image](https://user-images.githubusercontent.com/350947/161406814-9aca97a8-f431-440e-a3e0-051fce8cb23a.png)

We should investigate wrapping text when it overflows here.

When addressing this, we should consider whether we want to control wrapping on a per-property basis. For example, we may not wish to have wrapping for build pre/post events, which tend to contain executable code. Executable code does not format well with wrapping.

**Comment by adamint** [comment]
Command line arguments has been changed to a multi line string editor, so this has been fixed.

**Comment by drewnoakes** [comment]
This was reported again on an internal DL with a screenshot almost identical to the one given above. We should revisit. Sending back to triage.

**Comment by melytc** [comment]
Let's investigate making this editor wrap text for this control.

**Comment by drewnoakes** [comment]
As discussed in today's triage meeting, we will add wrapping for "command line arguments", but not for build events.

Checklist:
- New metadata on the editor, to control wrapping.
- Specify this on both project and executable launch profile XAML files.
- Update documentation to show how to control wrapping for that editor.
