### ISSUE TITLE
Resource editor's "Add existing resource" fails in C# SDK-style projects

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8039]
1. Create an SDK-style C# project
2. Create a .resx file within the project
3. Add an existing file as a resource
   ![image](https://user-images.githubusercontent.com/350947/161647724-4c5a8656-ff36-457b-a20c-070388a444b4.png)
4. Error dialog:
   ![image](https://user-images.githubusercontent.com/350947/161647770-ddab5a71-0b54-4736-95c1-c79abaab6165.png)

> Unable to add 'C:\Users\drnoakes\Desktop\image.png' to the project.
>
> This operation is not allowed while holding an active upgradeable read or write lock from an AsyncReaderWriterLock.

An empty `Resources` folder is added to the project:

![image](https://user-images.githubusercontent.com/350947/161647640-a4fdb866-3d8a-48eb-b580-12677f4b2092.png)

**Comment by drewnoakes** [comment]
This may be one for CPS, based on the following stack, which is triggered via `OAProjectItems.AddFromFileCopy` which calls into `OAProject.Mutate`:

```
Microsoft.VisualStudio.Validation.dll!Microsoft.Verify.FailOperation(string message, object[] args)
Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.VerifyNoNonConcurrentSyncContext()
Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.PackageUtilities.CopyUrlToLocal(System.Uri uri, string local)
Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.CopyFileToLocalIfNecessary(Microsoft.VisualStudio.Shell.Interop.VSADDITEMOPERATION fileOp, string file, string newFileName, bool addItemAsFolder, bool overwrite) Line 5217
Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.AddItemWithSpecificAsync.AnonymousMethod__4(Microsoft.VisualStudio.ProjectSystem.ProjectWriteLockReleaser access) Line 5039
```

Or at least, we could benefit from some guidance on how to handle project locking correctly here.

**Comment by ocallesp** [comment]
Does not repro.
cc: @drewnoakes @melytc
