### ISSUE TITLE
Implement CPVM support

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8056]
#GitHub mirror of [AB#1302817](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1302817).

- [x] Initial feature implementation
- [x] [AB#1544117](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1544117)

**Comment by kvenkatrajan** [comment]
I have gone ahead and moved  : - [ ] [AB#1544123](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1544123) (not blocking) to 17.4 since its non-blocking
