### ISSUE TITLE
Standardize Hot Reload message Reporting

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8060]
## Summary
Mirror of : [AB#1503716](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1503716) 
Dependency : [AB#1463525](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1463525)

- [ ] [AB#1524868](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1524868)
## User Impact

Provide consistent developer experience. - Users can configure verbosity of messages in Tools > Options
- Consistent logging in hot reload window across components
- Detailed error/stack trace presented on errors
- Consistent experience on display & component branding

**Comment by adamint** [comment]
@kvenkatrajan I don't think the bug fits in here.
