### ISSUE TITLE
Infrastructure Simplification - MVP

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8062]
## Summary

Mirror of : [AB#1503714](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1503714)

- [x] #7913
- [x] #7869
- [x] #7911
- [x]  #7915 
- [x]  #7981 
- [x] #5879 
- [x] #7189 
- [x] #7070
---
- [x] #5888
- [x] #6612 
- [x] #7868 
- [x] #6453
- [x] #8074 
- [x] #8019 
- [ ] #7935
## User Impact

Improve developer efficiency

**Comment by MiYanni** [comment]
Will update this issue once PRs are created and then merged.

**Comment by MiYanni** [comment]
All required tasks are now completed.
