### ISSUE TITLE
An error dialog pops up when renaming form designer in solution explorer

### ISSUE THREAD

**Issue by Ashley-Li** [dotnet/project-system#8064]
Visual Studio Version:
The latest main VS build

Steps to Reproduce:
1. Create a Winforms .NET Core project.
2. Right click Form1.cs in Solution Explorer, rename it to "Test.cs".

Actual behavior:
An error dialog"Visual Studio project system has encountered a non-fatal error " pops up.
![image](https://user-images.githubusercontent.com/56664234/162869956-49f5ef9d-637f-4083-a50d-571edd4d9153.png)
![image](https://user-images.githubusercontent.com/56664234/162869965-f4619a42-1ca1-410b-8aa7-2e57e7aadfd9.png)
![rename_form_issue](https://user-images.githubusercontent.com/56664234/162870084-eb00b49a-19ec-47b9-bdbb-4c7b4aa26c88.gif)

Expected behavior:
No error dialog pops up.

More info:
 1. This is a regression issue ,it cannot reproduce in VS 17.1.3.
 2. This issue also reproduce in .NET WPF Application.
 3. This issue cannot reproduce in Winforms .NET Framework project.

**Comment by drewnoakes** [comment]
@Ashley-Li this is a bug in CPS. Could you please file this on Azure DevOps under area path _DevDiv\VS Core\Project\CPS_?

Also I tried to reproduce this with the latest CPS code and was unable to do so. It did repro in the latest int.main build however.

**Comment by Ashley-Li** [comment]
@drewnoakes Have filed a Azure DevOps bug to track: [1523001](https://devdiv.visualstudio.com/DevDiv/_queries/edit/1523001/)

**Comment by kvenkatrajan** [comment]
Bug filed to internal team. Closing issue

**Comment by kvenkatrajan** [comment]
Bug filed to internal team. Closing issue
