### ISSUE TITLE
Not a bug, but a question - how can I specify build outputs for FUTD heuristic in a non standard SDK style project?

### ISSUE THREAD

**Issue by MarkKharitonov** [dotnet/project-system#8073]
This question is related to https://github.com/dotnet/project-system/issues/7941

I have custom SDK style projects. A typical project looks like this:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputPath>$(xyzBaseOutputPath)</OutputPath>
  </PropertyGroup>
</Project>
```
The actual logic is injected through a series of props and targets files:
```
C:\xyz\tip\LegacyFrontEnd\_Build> dir


    Directory: C:\xyz\tip\LegacyFrontEnd\_Build


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         4/13/2022  11:13 AM            701 05_Common.props
-a----         4/11/2022   9:43 PM            135 05_Common.targets
-a----         4/11/2022   9:43 PM            613 10_TypescriptCommon.props
-a----         4/11/2022   9:43 PM           1110 20_StylusCommon.props
-a----         4/11/2022   9:43 PM           3929 AdjustTypeScriptOutDir.cs
-a----         4/11/2022   9:43 PM            207 CompileFonts.targets
-a----         4/11/2022   9:43 PM           2772 CompileStylus.targets
-a----         4/11/2022   9:43 PM           2726 CompileTypeScript.targets


C:\xyz\tip\LegacyFrontEnd\_Build>
```
Where the most important ones are 05_Common.props and 05_Common.targets:

**05_Common.props**
```
<Project>
  <PropertyGroup>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
    <IsLegacyFrontEndProject>true</IsLegacyFrontEndProject>
    <Node>$(WorkspaceRoot)Tools\Node\node.exe</Node>
    <EnableDefaultItems>False</EnableDefaultItems>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <TypeScriptCompile Include="Scripts\**\*.ts" />
    <None Include="Scripts\**\*.js*" />
    <Stylus Include="Stylus\**\*.styl" />
    <Content Include="Content\**\*.*" />
    <Content Include="StaticViews\**\*.*" />
    <AvailableItemName Include="TypeScriptCompile" />
    <AvailableItemName Include="Stylus" />
  </ItemGroup>
</Project>
```

**05_Common.targets**
```
<Project>
  <Target Name="Build" />
  <Target Name="Clean" />
  <Target Name="Rebuild" DependsOnTargets="Clean;Build" />
</Project>
```
Notice that I disable the FUTD heuristic. I am doing it because it is not working. Trying to build a project with FUTD enabled produces the following verbose messages:
```
Build started...
1>FastUpToDate: No build outputs defined. (VacationBidding)
1>FastUpToDate: Project is up-to-date. (VacationBidding)
1>FastUpToDate: Up-to-date check completed in 4.3 ms (VacationBidding)
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```
What can I do to enable FUTD?

**Comment by drewnoakes** [comment]
Does this project actually build anything? If it doesn't advertise any outputs, there is nothing to build (or so the current logic says).

If not, you might like to use https://github.com/microsoft/MSBuildSdks/tree/main/src/NoTargets

In what way does the FUTD check not work if you enable it?

**Comment by MarkKharitonov** [comment]
It builds typescript and stylus files using ad-hoc targets. But no C#. For example, this is the contents of the **CompileTypeScript.targets** file imported by each of these projects through the common **Directory.Build.props file**:
```
<Project>
  <Target Name="CompileTypeScript" BeforeTargets="Build" DependsOnTargets="BeforeCompileTypeScript;DoCompileTypeScript" />
  
  <Target Name="BeforeCompileTypeScript">
    <PropertyGroup>
      <TypeScriptItemCount>@(TypeScript->Count())</TypeScriptItemCount>
    </PropertyGroup>
  </Target>

  <Target Name="DoCompileTypeScript" Condition="'$(TypeScriptItemCount)' != 0">
    <PropertyGroup>
      <TSAuxFolder>$(TypeScriptOutDir)\.ts</TSAuxFolder>
      <TypeScriptOptions Condition="'$(TypeScriptRemoveComments)' == 'true'">$(TypeScriptOptions) --removeComments</TypeScriptOptions>
      <TypeScriptOptions Condition="'$(TypeScriptGeneratesDeclarations)' == 'true'">$(TypeScriptOptions) --declaration</TypeScriptOptions>
      <TypeScriptOptions Condition="'$(TypeScriptModuleKind)' != ''">$(TypeScriptOptions) --module $(TypeScriptModuleKind)</TypeScriptOptions>
      <TypeScriptOptions Condition="'$(ProjectName)' != 'Framework'">$(TypeScriptOptions) --outDir $(TypeScriptOutDir)</TypeScriptOptions>
      <TypeScriptOptions Condition="'$(ProjectName)' == 'Framework'">$(TypeScriptOptions) --outDir $(TypeScriptOutDir)\Framework\Scripts\Framework</TypeScriptOptions>
      <TypeScriptOptions Condition="'$(TypeScriptSourceMap)' == 'true'">$(TypeScriptOptions) --sourceMap</TypeScriptOptions>
      <TypeScriptOptions Condition="'$(TypeScriptTarget)' != ''">$(TypeScriptOptions) --target $(TypeScriptTarget)</TypeScriptOptions>
      <TypeScriptOptions Condition="'$(TypeScriptAdditionalFlags)' != ''">$(TypeScriptOptions) $(TypeScriptAdditionalFlags)</TypeScriptOptions>
      <TypeScriptOptions>$(TypeScriptOptions) --noEmitOnError --noImplicitUseStrict</TypeScriptOptions>
      <TypeScriptCommandLine>$(TypeScriptOptions);@(TypeScript->'&quot;%(FullPath)&quot;', '%0d%0a')</TypeScriptCommandLine>
      <TypeScriptArgsFile>$(TSAuxFolder)\typeScriptArgs.txt</TypeScriptArgsFile>
    </PropertyGroup>
    <MakeDir Directories="$(TSAuxFolder)"/>
    <WriteLinesToFile File="$(TypeScriptArgsFile)" Lines="$(TypeScriptCommandLine)" Overwrite="true" />
    <Exec Command="$(Node) $(WorkspaceRoot)Tools\TypeScript\tsc.js %40$(TypeScriptArgsFile)"/>
    <AdjustTypeScriptOutDir TypeScriptOutDir="$(TypeScriptOutDir)" />
  </Target>
  
  <UsingTask TaskName="AdjustTypeScriptOutDir" TaskFactory="RoslynCodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <ParameterGroup>
      <TypeScriptOutDir ParameterType="System.String" Required="true" />
    </ParameterGroup>
    <Task>
      <Code Source="$(MSBuildThisFileDirectory)\AdjustTypeScriptOutDir.cs" Language="cs" />
    </Task>
  </UsingTask>
</Project>
```

The https://github.com/microsoft/MSBuildSdks/tree/main/src/NoTargets looks very relevant. But it is not clear to me what extension would such files have. Is it plain `*.targets`? But then can they be arranged in a VS solution? Because devs must be able to open the solution consisting of such projects in VS IDE and get the intellisense for their Typescript/Javascript/CSS/HTML files as they do today.

**Comment by drewnoakes** [comment]
@MarkKharitonov can you not use one of the existing project types for JavaScript or TypeScript? I'm unclear why you need to define this project type yourself.

**Comment by drewnoakes** [comment]
I would think the `.esproj` would do what you want.

https://docs.microsoft.com/en-us/visualstudio/javascript/javascript-in-visual-studio?view=vs-2022#project-templates

Here's what the project file looks like for a new React project:

```xml
<Project Sdk="Microsoft.VisualStudio.JavaScript.Sdk/0.5.29-alpha">
  <PropertyGroup>
    <StartupCommand>set BROWSER=none&amp;&amp;npm start</StartupCommand>
    <JavaScriptTestRoot>src\</JavaScriptTestRoot>
    <JavaScriptTestFramework>Jest</JavaScriptTestFramework>
  </PropertyGroup>
</Project>
```

Note that I generated that using a pre-release version of VS so the exact template/SDK version/etc may differ in a public build.

**Comment by MarkKharitonov** [comment]
1. Most of the devs use VS 2019, not VS 2022. Will VS 2019 recognize the esproj extension or work with the JavaScript sdk?
2. Our Typescript and Stylus code is built using custom targets. Does it make sense to try the JavaScript SDK?

**Comment by drewnoakes** [comment]
I don't know about VS2019. It should be quick to check whether it works or not.

It's an MSBuild SDK so you can hook your own targets if needed.

**Comment by MarkKharitonov** [comment]
Trying to open an esproj project with VS 2019 produces the following result:
![image](https://user-images.githubusercontent.com/489792/165938727-40f4e79c-c616-41ef-b1bc-3f6080f8d372.png)

Until all the devs migrate to VS 2022 we cannot use esproj. I am not in a position to force hundreds of devs to migrate at once. Usually this process takes months.

**Comment by drewnoakes** [comment]
Understood. In the meantime you may be able to get something to load by changing the extension to `.csproj`, but some features may not work correctly.

As for this work item, I'm not sure what action we would take on the product or documentation here, so I'll close it. If I am missing something, we can re-open it. Thanks.
