### ISSUE TITLE
Remove duplicate PackageReference items

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8074]
We have a number of duplicate PackageReference items, including:

- XliffTasks
- Microsoft.VisualStudio.Composition
- Microsoft.VSSDK.BuildTools

Recently NuGet has started warning about these duplicates, and the command line build (via build.cmd) elevates them to errors.

For the moment we'll suppress the warning (NU1504) until we can fix the duplicates.

**Comment by MiYanni** [comment]
This may be fixed with the Infrastructure Simplification efforts. I've added it to that project list for review during that endeavor.
