### ISSUE TITLE
[LiveShare] Adding new item crashes LiveShare for F# project

### ISSUE THREAD

**Issue by xperiandri** [dotnet/project-system#8088]
From https://github.com/dotnet/fsharp/issues/12976

## Visual Studio Version
2022 17.1.4

## Summary
When 2 users with Visual Studio connected to Live Share in the F# project and one of them adds a new F# file via project context menu -> Add -> New Item... (or file context menu -> Add above/Add beloved -> New Item...) then some files in the F# project are being removed physically from a disc.

The most ridiculous is that files are being physically deleted from the disc and disappear!
![image](https://user-images.githubusercontent.com/2365592/162931960-fcf9644a-e3f9-4309-9a08-8ca9314dec5f.png)

## Steps to Reproduce

1. Create F# console app
2. Start Live Share
3. Connect from another Visual Studio to the Live Share session
4. Add a new F# code file to the project
5. Save All

## Expected Behavior
The file has been added and appeared in all instances connected to Live Share, all the existing files remain in their places.

## Actual Behavior
The very bottom file in the project is deleted from the disk.

## User Impact
Work done in the file is lost forever.

**Comment by xperiandri** [comment]
Also, file changes in the remaining files may not propagate into the Live Share session anymore

**Comment by tmeschter** [comment]
@xperiandri This only occurs when using Live Share, correct?

**Comment by xperiandri** [comment]
Yes, only in Live Share session

**Comment by kvenkatrajan** [comment]
I have gone ahead and moved this issue to the FSharp team : AB#1539580 for support. Thank you for your continued patience!
