### ISSUE TITLE
Changes to a custom app manifest don't trigger a rebuild

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/project-system#8092]
## Visual Studio Version
17.1.4

## Summary
Making a change to a custom app manifest, and _only_ to the manifest, doesn't rebuild the app when run from VS.

## Steps to Reproduce

1. Create a new .NET console app
2. Add a custom app manifest
3. Break the manifest (for example, add `<supportedOS Id="" />` to the `compatibility/application` section)
4. Press F5 to debug

## Expected Behavior
A launch error (This application has failed to start because the application configuration is incorrect...)

## Actual Behavior
The app continues to launch with the old manifest until a build is manually requested, or a code file is changed.

## User Impact
Confusion and wasted time figuring out why your fix isn't working.

**Comment by drewnoakes** [comment]
Thanks for the bug report. There's a fix in PR for 17.3. It's too late to get it into 17.2 now unfortunately.
