### ISSUE TITLE
ShowAllFiles in a project file is no longer respected

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/project-system#8098]
I'm not sure if this belongs here - or even if it is a bug, considering it doesn't seem to be documented - but it used to be possible to show excluded files in the VS solution explorer by adding `<ShowAllFiles>true</ShowAllFiles>` to `Directory.Build.props`. This stopped working somtime recently.

Would it be possible to restore this behaviour? It was very useful in solutions with 10s or 100s of projects.

If this was removed intentionally, please consider allowing the solution explorer UI to batch-apply this setting (selecting mutiple projects currently hides the toolbar button).

**Comment by drewnoakes** [comment]
@lorcanmooney the persistence of this setting changed a while ago. It used to be stored in the .user file, but is now inside the .suo instead. This helps with performance. The .suo file may be changed at any time, at no real cost. Changing the .user file, by comparison, triggers a full internal build of the project, which is redundant.

Re-enabling the property in the project file would be a request of the CPS team, which is internal to Microsoft. Would you mind filing a feedback ticket with the above details? If you link it here, I will route it directly to the right team. They will be able to assess the request there.

Note that "show all files" comes with a performance cost.

Could you elaborate on why you want it enabled for so many projects at the same time? Is there some feature that only works when that's enabled?

**Comment by lorcanmooney** [comment]
Thanks for the explanation @drewnoakes. I've opened a feedback issue here: https://developercommunity.visualstudio.com/t/Provide-a-way-to-bulk-set-Show-All-File/10021523

I routinely use the Exclude From Project feature to prevent broken code from causing build failures. It's much quicker than setting the Build Action through the file properties. With Show All files I can still see the file exists and the change in icon provides a visual reminder that I should re-include the file later, or just delete it permanently. Having it in the project file meant I could ensure it was always on for freshly cloned repos, new projects, and remained so even after `git clean` trashed the `.vs` directory. Without it, I've found a build-up of stale code files in the source tree that I otherwise would have dealt with.

I understand the performance concerns in the general case, but for my workflow it was a once off, set-and-forget for an entire solution.

**Comment by drewnoakes** [comment]
@lorcanmooney thanks very much, I've routed it to the correct team. They'll take it from here.

That is an interesting workflow. I suggest you copy/paste the above as a comment on your feedback ticket so that those who triage it will have the additional context. It's not a workflow I've heard of before, so it'd be good to highlight that to help the team understand where you're coming from with your request.
