### ISSUE TITLE
Renaming Properties folder should work or be disabled

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#81]
_From @davkean on March 22, 2016 23:45_

CPS allows you to rename Properties/My Project folder. Either we should disallow like csproj/msvbproj, or make sure we do the right things to update the associated project property; `<AppDesignerFolder>`

_Copied from original issue: dotnet/roslyn#9993_

**Comment by jjmew** [comment]
Look at ProjectTreeActionHandler as way to fixing this
