### ISSUE TITLE
Can't "Scope to this" on top-level reference groupings

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#811]
![image](https://cloud.githubusercontent.com/assets/1103906/20611484/69a72be2-b2ff-11e6-9030-62a40bdeb077.png)

**Comment by drewnoakes** [comment]
I fixed this recently as part of the context menu overhaul.

![image](https://user-images.githubusercontent.com/350947/77218172-a2394380-6b7c-11ea-92b9-5e0ec232dc70.png)

All grouping nodes and top-level dependencies have 'Scope to This' and 'New Solution Explorer View' menu items.
