### ISSUE TITLE
Migration of Project System  OptProf pipeline to DartLab

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8139]
# Summary
Migrate the OptProf pipeline from legacy pipeline to [DartLab](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/3894/DartLab). This is due 8/25/2022. After that date, all test pipelines that have not been  [migrated](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/26153/Migration) to DartLab will begin failing.

## User Impact
Enhanced end-to-end test run automation solution

**Comment by MiYanni** [comment]
Completed as part of https://github.com/dotnet/project-system/pull/8420.
