### ISSUE TITLE
MSBuild Language service for project files

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8140]
# Summary

Build a set of tools to simplify editing of msbuild project files. 
Details of the intial spec can be found at: https://github.com/jmarolf/msbuild-language-service/blob/spec/docs/spec.md
Here's an internal wiki :referencing some background information on the internal components:  https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/28854/MSBuild-Language-Service

- [x] Create initial solution - msbls
- [x] Define a basic VSIX project
- [x] [AB#1552520](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1552520) - Basic Infrastructure setup
- [ ] #766
- [x] #5429 

# Impact

- We expect this would fast track migration to .NET core by .NET developers, since the MSBuild files could be modified easily in their editor of choice 
- MSBuild files can be reasoned about by developers

**Comment by drewnoakes** [comment]
We already have a work item for this. I can find it when not on a phone.

**Comment by drewnoakes** [comment]
I can't find a good top-level work item for this actually. These are both components of this work:

- [ ] #766
- [ ] #5429

**Comment by mhutch** [comment]
FWIW I have [a fully functional MSBuild language service](https://github.com/mhutch/MonoDevelop.MSBuildEditor) but it's been blocked for ~3 years by a project system bug that prevents it from providing a good UX for opening files while a project is open.

**Comment by KirillOsenkov** [comment]
I think the relevant details are here:
https://github.com/dotnet/project-system/issues/5429

**Comment by tmeschter** [comment]
Closing this issue as the initial round of investigation and development is complete. New issues will be opened as we plan the next steps around this work.
