### ISSUE TITLE
Inconsistent/wrong indentation value when writing properties to project file

### ISSUE THREAD

**Issue by stmoor** [dotnet/project-system#8147]
## Visual Studio Version
Version 17.3.0 Preview 2.0 [32509.85.main]

## Summary
When writing properties to the project file, there is inconsistent and wrong indentation value. 

When the XML setting is to use spaces as indentation in VS Options, this is how the property is written to the file: 
![image](https://user-images.githubusercontent.com/77985069/167496137-3804e069-98b7-4d1c-9b10-f6acbf73ba94.png)

Notice that the PropertyGroup uses one single space as indentation, but the LaunchForBackgroundFetch used 3. That is inconsistent. 

When the XML setting is to use tabs, this is how the property is written:
![image](https://user-images.githubusercontent.com/77985069/167496529-58cc69bf-0d87-4b87-b43e-d458fa51a4df.png)

Notice how for LaunchForBackgroundFetch it is using a combination of both tabs and spaces to indent. That is incorrect, as it should be using only two tabs. 

## Steps to Reproduce

1. Open a new MAUI project with iOS listed in the TargetsFramework
2. Open the properties page, and go to Run Options page under iOS. 
3. Select "Background Fetch" as the Execution Mode. 
4. Open the project file, and notice the indentation. 

## Expected Behavior
The indentation used when writing properties to project file should be consistent with the XML settings in VS options. 

## Actual Behavior
Then indentation is inconsistent and wrong.

## User Impact
Users will be annoyed that the formatting of the property is inconsistent with the rest of the file

**Comment by drewnoakes** [comment]
@stmoor what settings do you have here:

![image](https://user-images.githubusercontent.com/350947/167540044-6f59b3e0-764f-4cff-8d34-f3e82c82f9fd.png)

If there is work to be done here, it's likely a request for CPS rather than this repo.

**Comment by stmoor** [comment]
The screenshots in the Summary used both Insert Spaces for one, and Keep tabs for the other, with Tab Size and Indent Size set to 4. Okay, do you know where I can open an issue with CPS?

**Comment by drewnoakes** [comment]
In that case, is there a bug? If the file's current style is inconsistent with the IDE's preference, I would not expect the IDE to ignore the preference and do something different.

To file a bug on CPS, go [here](https://dev.azure.com/devdiv/DevDiv/_workitems/create/bug) (MS internal) and use area path _DevDiv\VS Core\Project\CPS_.

**Comment by kvenkatrajan** [comment]
Please route to CPS team closing issue
