### ISSUE TITLE
Command line arguments in Debug Profiles UI are not correctly escaping escape sequences

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#8167]
## Visual Studio Version
Version 17.3.0 Preview 2.0 [32503.442.main]

## Summary
The command line arguments requires the user to understand the underlying format that it is used to correctly escape their own strings. This should be handled by whatever writes the file. 

I cannot figure out a workaround for this issue, other than renaming the argument to not include "\n"

## Steps to Reproduce

1.  File -> New -> Console App with program.cs that contains:

``` C#
Console.WriteLine(args[0]);
```

2.  Right-click on project and choose Properties -> Debug -> Open debug launch profiles UI
3. In command-line enter "C:\Users\davkean\AppData\Local\Temp\VsEngDropExplorer\93d5d61d38386807d9f4663c7c74839f\TestExecutionOutputs\OrchardCoreWithCache.TestSolutionOpenClose\Warmup-1-20220511-193634_dtl-qe1vpwty\NGenLogs\Framework64\ngen.log"
4. F5

## Expected Behavior
```
C:\Users\davkean\AppData\Local\Temp\VsEngDropExplorer\93d5d61d38386807d9f4663c7c74839f\TestExecutionOutputs\OrchardCoreWithCache.TestSolutionOpenClose\Warmup-1-20220511-193634_dtl-qe1vpwty\NGenLogs\Framework64\ngen.log
```

## Actual Behavior
```
C:\Users\davkean\AppData\Local\Temp\VsEngDropExplorer\93d5d61d38386807d9f4663c7c74839f\TestExecutionOutputs\OrchardCoreWithCache.TestSolutionOpenClose\Warmup-1-20220511-193634_dtl-qe1vpwty\NGenLogs\Framework64
gen.log
```

**Comment by drewnoakes** [comment]
This broke with a10b002cf82149e4440be4451c1fa2ef995c223c in #7919.

It's a regression that was introduced and shipped in 17.2.

**Comment by davkean** [comment]
This is the same as https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1540835.

**Comment by adamint** [comment]
Eek, I'll get to this ASAP

**Comment by realvizu** [comment]
The workaround for me was to replace \n with \N in file paths.
