### ISSUE TITLE
Support AppliesTo filtering for property interceptors

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8170]
The reading and writing of property values can be intercepted by exports of `IInterceptingPropertyValueProvider` as discussed in [this document](https://github.com/dotnet/project-system/blob/main/docs/repo/property-pages/property-value-interception.md).

Today we match the property name against the property definition in order to find the correct export for a given property.

This may be problematic in cases where we have properties with the same name, but in different project types.

For example, perhaps C# and VB projects have the same property, but treat them differently.

The classical way of achieving this is via `[AppliesTo("<expression>")]` metadata on the export, where `<expression>` describes the _project capabilities_ to which the export applies.

This issue is tracking the idea of allowing (or possibly even requiring) this metadata on exports in order to match them to properties.

---

The challenge with doing this today is that no current exports have `AppliesTo` metadata. The current capability filtering treats the absence of `AppliesTo` as meaning no match can happen.

There are two ways we could allow this metadata to be added:

1. Update _every_ existing export of `IInterceptingPropertyValueProvider` to have this metadata. This includes all those in this repository, JavaScript/TypeScript projects, MAUI projects, Xamarin projects and possibly others.
2. Create a new mechanism for capability filtering that treats the absence of `AppliesTo` as automatically _including_ rather than excluding the export. This seems like something that could be generally useful in future too.

**Comment by adamint** [comment]
relevant to #8387
