### ISSUE TITLE
Property gear icon is clickable when invisible

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8200]
## Visual Studio Version

Version 17.3.0 Preview 2.0 [32522.62.main]

## Summary

![invisible-property-menu-gear](https://user-images.githubusercontent.com/350947/170022154-500659c6-0657-4be2-983a-05c65a9e6a81.gif)

## Expected Behavior

Icon should be visible when it can be clicked, and not clickable when hidden.

## Actual Behavior

Icon can be hidden yet clickable.

**Comment by adamint** [comment]
PR tracked in: https://dev.azure.com/devdiv/DevDiv/_git/CPS/pullrequest/407439
