### ISSUE TITLE
Allow properties to define an expression to control when they are editable

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8204]
Today we have an expression that controls property visibility.

We could add a similar expression that controls when a property is marked as read only, conditional upon other property values.

This facility would simplify the approach taken in #8196 for example. In that PR, we add a duplicate of every property that might potentially be disabled, using mutually exclusive visibility conditions to hide the editable version and show the readonly one, based on other property values.

Here's an example of how this might work. The `EditabilityCondition` allows the UI to toggle the state of the UI element dynamically at runtime.

```xml
  <DynamicEnumProperty Name="SomeProperty"
                       ...>
    <DynamicEnumProperty.Metadata>
      <NameValuePair Name="EditabilityCondition">
        <NameValuePair.Value>
          (not (has-evaluated-value "Build" "WarningSeverity" "DisableAll"))
        </NameValuePair.Value>
      </NameValuePair>
    </DynamicEnumProperty.Metadata>
  </DynamicEnumProperty>
```

The majority of properties would not define a `EditabilityCondition`, and there would be no overhead for those properties.

**Comment by tmeschter** [comment]
I ended up duplicating ~10 properties on the VB "Compile" page in order to create read-only versions; we should go back and clean those up as part of this work.
