### ISSUE TITLE
Empty configuration values are being displayed.

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#8244]
I'm not sure why we see an empty configuration value in that property:
![image](https://user-images.githubusercontent.com/8518253/173694076-9b0fd9a4-562b-45b9-b2b6-38cd466286a9.png)

For context, this is a VB WPF application using the latest main (32614.125); I added the ProjectCapability `ProjectPropertiesEditor` in the project file to turn on the new experience and test it.

**Comment by melytc** [comment]
Typo is being fixed here: #8266. I'll edit this issue's description describe the greater bug.

**Comment by adamint** [comment]
Possibly related to #8354, I'll investigate

**Comment by adamint** [comment]
It's unrelated to #8354, this is because the properties in question have no description. I'll put in a PR to add descriptions
