### ISSUE TITLE
High Priority Accessibility Issues - Sev3 and Sev4 - 17.4

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8250]
## Summary

Address Sev3 non-blocking accessibility issues
- [x] [AB#1408079](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1408079)
- [x] [AB#1408953](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1408953)
- [x] [AB#1441093](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1441093)

## Impact
To improve accessibility experience and compliance

**Comment by drewnoakes** [comment]
@adamint this has been marked as closed, but the three original AB tickets are still open and targeting 17.4.

**Comment by adamint** [comment]
@drewnoakes oops, thank you! _Now_ it can be closed
