### ISSUE TITLE
DesignTime element added to project if .resx/.designer.cs definitions are in separate shared .props file

### ISSUE THREAD

**Issue by sgarske** [dotnet/project-system#8256]
## Visual Studio Version

>Microsoft Visual Studio Enterprise 2019
Version 16.11.5

## Summary

While converting some legacy .NET Framework projects to use the .NET sdk style, we ran into an issue with resource files where duplicate elements are being automatically added to the project.  For various reasons, our `resx` files exist outside of the project directory and multiple projects might reference different files but from similar locations.  Thus, in an effort to share some "project definition" code, I extracted the `.resx/.designer.cs` definitions into their own `.props` file.  This works and the files are included in the project.  However every time the resource generation tool runs, these elements are re-added to the project despite already being defined in the external `.props` file

```xml
  <ItemGroup>
    <Compile Update="..\ExternalResources\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
    </Compile>
  </ItemGroup>
```

## Steps to Reproduce

I just created a simple `WPF Class Library` and setup my folder structure as follows

> .\TestResources\ExternalResources
.\TestResources\ExternalResources\Resource.Designer.cs
.\TestResources\ExternalResources\Resource.resx
.\TestResources\TestResources
.\TestResources\TestResources\TestResources.csproj
.\TestResources\Resources.props
.\TestResources\TestResources.sln

In `TestResources.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Import Project="$(SolutionDir)Resources.props" />

</Project>
```

In `Resources.props`
```
<?xml version="1.0" encoding="utf-8"?>
<Project>
  <ItemGroup>
    <Compile Include="..\ExternalResources\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Include="..\ExternalResources\Resource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
```

Every time you `Run Custom Tool` (or modify the resx), the `DesignTime` element is re-added to the `.csproj` despite it already existing in the `.props`
![image](https://user-images.githubusercontent.com/7501210/174895208-b4b17fca-e70a-4e27-ae7c-68a77faef9f9.png)

## Expected Behavior

Nothing is added to my `.csproj` and it remains unmodified

## Actual Behavior

`DesignTime` element is added with an `ItemGroup` for the `.designer.cs` definition when resources are regenerated despite it already being defined in the external props file

## User Impact

The workaround as far as I can tell is to leave the generated lines in the project so it doesn't keep re-adding them or duplicate the definitions in each .csproj rather than using a common .props.

------ 

Thanks in advance to reading and considering

**Comment by tmeschter** [comment]
Fixed via https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/421299 and then https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/422035.
