### ISSUE TITLE
Intercept `UseApplicationFramework` property in `ApplicationFrameworkPropertiesValueProvider`.

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#8257]
We need to intercept the `UseApplicationFramework` property in two interceptors:
1. `ApplicationFrameworkValueProvider`, where we set the `MyType` property in the project file.
2. `ApplicationFrameworkPropertiesValueProvider`, where we set the `MySubMain` property in the Application.myapp file.

We already have case 1 in place, which was done as the initial port for the VB pages.

This property is a special case because it is used by both the WPF and WinForms projects, and because it affects a property in two files, the project file and the myapp file. That means that we need two interceptors (which I tried to in my PR #8252 but got errors since we don't support having two interceptors for one property) or we use the interceptor we already have and make it aware that changes in the myapp file need to happen too.

Related to #8252.

**Comment by drewnoakes** [comment]
@melytc could you capture any reason it wasn't included in your recent PR here, for future reference?

**Comment by melytc** [comment]
Sure, I'll add it on the description.
