### ISSUE TITLE
Create Application.myapp file when one is not found in project directory.

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#8258]
I need to validate what the correct experience should be when the `Application.myapp` does not exist in a VB WinForms project and the user tries to set the Application Framework properties: my assumption is that we need to create one.

Related #8252.

**Comment by adamint** [comment]
When I create a new vb winforms project, an application.myapp file is created. Is this issue about when the user deletes that file, when should it be recreated?

**Comment by drewnoakes** [comment]
Yes, if the file was not present on disk and the user opened the project properties to read the file, we should handle that case without exception. Also if the user attempts to modify properties that are stored in that file when it doesn't exist. In either case, we should avoid exceptions.

**Comment by adamint** [comment]
Gotcha, thanks Drew. I can handle this then to take some of the vb issues off melissa's plate, at kay's suggestion!

**Comment by definesfineout** [comment]
This is happening when I upgrade a VB class library project from .NET 6 to .NET 7. These are not WinForms projects or applications. Is this intentional?

**Comment by drewnoakes** [comment]
@definesfineout do you mean that the file is being created when you change the target framework? If so, please file a new issue and include repro steps and your VS version. Thanks.

**Comment by definesfineout** [comment]
Created https://github.com/dotnet/project-system/issues/8693

Appears to be due to creating the file on "first get". The new properties panels format tries to get properties that cause the generation to occur despite being a class library.
