### ISSUE TITLE
The FUTD Heuristic should initialize itself before the first build

### ISSUE THREAD

**Issue by MarkKharitonov** [dotnet/project-system#8272]
## Summary
Suppose one fully builds the code with msbuild on the console and then opens and builds the same solution in VS IDE. 
Even if the code is completely up to date and there are no issues, the output in VS IDE with Info verbosity for the Heuristic would be something like this:
```
Build started...
1>FastUpToDate: The up-to-date check has not yet run for this project. Not up-to-date. (CustomBuildWorkflowCode)
1>------ Build started: Project: CustomBuildWorkflowCode, Configuration: Debug Any CPU ------
2>FastUpToDate: The up-to-date check has not yet run for this project. Not up-to-date. (DeploymentEngine)
2>------ Build started: Project: DeploymentEngine, Configuration: Debug Any CPU ------
1>CustomBuildWorkflowCode -> C:\dayforce\tip2\bin.link\CustomBuildWorkflowCode.dll
2>DeploymentEngine -> C:\dayforce\tip2\bin.link\DeploymentEngine.dll
3>FastUpToDate: The up-to-date check has not yet run for this project. Not up-to-date. (ActivityPack)
3>------ Build started: Project: ActivityPack, Configuration: Debug Any CPU ------
4>FastUpToDate: The up-to-date check has not yet run for this project. Not up-to-date. (Deployer)
4>------ Build started: Project: Deployer, Configuration: Debug Any CPU ------
3>ActivityPack -> C:\dayforce\tip2\bin.link\TeamFoundation.Build.ActivityPack.dll
4>Deployer -> C:\dayforce\tip2\bin.link\_PublishedApplications\Deployer\Deployer.exe
5>FastUpToDate: The up-to-date check has not yet run for this project. Not up-to-date. (ActivityInvoker)
5>------ Build started: Project: ActivityInvoker, Configuration: Debug Any CPU ------
6>FastUpToDate: The up-to-date check has not yet run for this project. Not up-to-date. (DeployerTests)
6>------ Build started: Project: DeployerTests, Configuration: Debug Any CPU ------
5>ActivityInvoker -> C:\dayforce\tip2\bin.link\_PublishedApplications\ActivityInvoker\ActivityInvoker.exe
6>DeployerTests -> C:\dayforce\tip2\bin.link\DeployerTests.dll
========== Build: 6 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
So the Heuristic is inactive and hence every project is passed to msbuild. Which in turn does not compile any code, but burns the time checking all the projects.

## User Impact
Devs do not know that the build does not actually recompile the code, from their perspective the solution is completely rebuilt.
I think it is a regression from the legacy style projects, where the FUTD Heuristic was active from the start.

**Comment by drewnoakes** [comment]
I'd be interested to brainstorm this.

Here's a scenario to consider:

1. Build on the command line
2. Delete a source file
3. Open in VS and build again

How would VS know that the source file has been deleted? We would need to share information about the inputs that MSBuild used to produce those outputs. I don't believe that's available to us today.

When VS says _"The up-to-date check has not yet run for this project. Not up-to-date."_ that's mostly because we don't have persisted data that shows the set of items we last used.

> I think it is a regression from the legacy style projects

Legacy projects didn't use globbing, so if you deleted a source file off disk, the project would flag it as an error. With globbing, you can delete a file off disk and everything looks fine.

My feeling is that this performance hit happens infrequently (though perhaps some users use a workflow that increases the chance of seeing this).

**Comment by MarkKharitonov** [comment]
I understand what you are saying. No idea how to resolve it without msbuild leaving some trace behind for VS to pick up.

**Comment by MarkKharitonov** [comment]
Can it leverage the design time builds? At least those which have finished by the time the regular build is triggered by the developer.

**Comment by drewnoakes** [comment]
The design-time build still won't know if an input was removed from disk that would modify the last-built output. We'd need the command line build to provide this information to the project system somehow.

**Comment by drewnoakes** [comment]
I don't see any way forward here as it stands today, so will close this out. This only impacts a very specific scenario where the first build occurs on the command line, so I don't know if there's enough justification to spend time on this over other more impactful build improvements we have planned. If we come up with a design here, we can reopen and prioritise accordingly.
