### ISSUE TITLE
Property page scroll position jumps suddenly after editing an enum property

### ISSUE THREAD

**Issue by japarson** [dotnet/project-system#8279]
## Visual Studio Version
17.3 Preview 3

## Summary
In a Maui project, the iOS Bundle Signing property page jumps from one scroll position to another after choosing an option in the Signing Identity combo box. 

[Bug 1521150: [XVS][MAUI]The page will incorrectly jump, when editing the drop-down box in iOS bundle signing in properties](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1521150)

## Steps to Reproduce
1. Create .NET MAUI app.
2. Open the project properties editor.
3. Click iOS-> Bundle Signing.
4. Select any option in Scheme or the Signing identity or Provisioning profile drop-down option.
5. Observe that the page scroll position changes suddenly.

## Expected Behavior
The page scroll position does not change at all.

## Actual Behavior
The page scroll position changes suddenly.

## User Impact
Users will be annoyed or confused by the UI moving suddenly.

**Comment by adamint** [comment]
@japarson Thanks for reporting this, we'll fix this in 17.4

**Comment by adamint** [comment]
@japarson I cannot repro this on latest vs Version 17.4.0 Preview 2.0 [32809.211.main]

**Comment by adamint** [comment]
Note that this can also appear when varying property.

**Comment by adamint** [comment]
want to re-triage with team

**Comment by adamint** [comment]
PR tracked in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/424639
