### ISSUE TITLE
<Import> items from the SDK can't be removed via the new property pages

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8281]
## Visual Studio Version

VS main 32628.85

## Summary

VB `<Import>` items that come from the SDK (or any imported .props/.targets file) cannot be removed through the new VB "References" property page.

## Steps to Reproduce

1. Create a VB project targeting .NET 6.
2. In the Solution Explorer window, right click the project and select Edit Project File.
3. Add the following lines of code after the last ItemGroup:
  ```xml
  <ItemGroup>
    <ProjectCapability Include="ProjectPropertiesEditor"/>
  </ItemGroup>
  ```
4. Save and close the project file. If a gold bar appears, reload the project.
5. In the Solution Explorer window, right click the project and select Properties.
6. Go to the "References" page.
7. Uncheck "Microsoft.VisualBasic".

## Expected Behavior

The item stays unselected, and an `<Import Remove="Microsoft.VisualBasic" />` is added to the project file.

## Actual Behavior

The project file is not modified, and "Microsoft.VisualBasic" immediately becomes checked again.

## User Impact

Users can't remove imported namespaces that are provided by the SDK.

**Comment by tmeschter** [comment]
FYI @adamint.

**Comment by adamint** [comment]
Hmm, I didn't realize these imports should be removable. This should be a fairly simple fix

**Comment by adamint** [comment]
Actually, @tmeschter I think the current way of these items being readonly in the editor is sufficient. If the user _really_ wants to remove one of the SDK (or props) imported namespaces, shouldn't they do it via the project file?
![image](https://user-images.githubusercontent.com/20359921/183564995-b5636d76-2490-4d47-aa4e-e5424628072c.png)
