### ISSUE TITLE
Can't remove a shared-project reference via solution explorer

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/project-system#8305]
## Visual Studio Version
17.2.5

## Summary
It doesn't seem to be possible to remove a shared-project reference using the solution explorer.

## Steps to Reproduce

1. Select a shared-project reference in solution explorer.
2. Press the &lt;Delete&gt; key.
3. Right click the reference and select "Remove".

## Expected Behavior
The reference is removed.

## Actual Behavior
The reference remains.

## User Impact
Need to use the "Add reference" dialog or edit project XML to remove these references.

**Comment by drewnoakes** [comment]
@lorcanmooney just to be sure, are you referring to removing the shared project reference from within the "Dependencies" tree?

**Comment by lorcanmooney** [comment]
Yes, that's the one:
![remove_shared_project](https://user-images.githubusercontent.com/13181165/177191803-64c33ac8-13e7-41d5-908c-9389daa0d2dc.png)

**Comment by tmeschter** [comment]
Could be us; could be CPS.

**Comment by drewnoakes** [comment]
> Could be us; could be CPS.

It was... both!? 😆 

CPS changed how tree items were populated in 17.2, for performance reasons. This bug fell out of that change. I've worked around it with #8329, and the fix should be in 17.4.
