### ISSUE TITLE
Disable namespaces that are unable to be unselected

### ISSUE THREAD

**Issue by adamint** [dotnet/project-system#8311]
### Summary

As can be seen in the below image, namespaces that are unable to be unselected are still enabled. There should be an extension to the MultiStringSelector editor/control to allow for a list of shown but disabled strings.

 ![image](https://user-images.githubusercontent.com/20359921/177388905-127d93d8-9bb7-4426-93b7-e4f42fb86406.png)

### User impact

There is low user impact, as no functionality is actually affected.

**Comment by tmeschter** [comment]
Moving this up to 17.4 as this is a UI interaction issue that will be easy to run into.

**Comment by tmeschter** [comment]
Also note that in the legacy property pages you can still _try_ to uncheck namespaces coming from `<Import Include="...">` items outside of the project file (e.g. from a Directory.Build.props file) but you get a (marginally helpful) error dialog:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/10506730/178065767-3c774e7c-551a-4cfb-a8a3-db63aea62b12.png">

and nothing is actually changed. So the current experience isn't significantly worse than what we used to have, though knowing that the operation explicitly failed is perhaps better than it being silently ignored.
