### ISSUE TITLE
Project System Build Error

### ISSUE THREAD

**Issue by jonathanchapmanmoore** [dotnet/project-system#8319]
![Untitled12](https://user-images.githubusercontent.com/8218836/178334058-790968e8-e646-4ab1-b61a-12b9d0d5085f.png)
## Visual Studio Version

2017, 2019, 2022 Build Tools

## Summary

 I was trying to build the WinRT but I need the machine type switch and the build tools only have a devenv icon. or I would have used devenv to build the WinRT on the Project System I get one error 'unable to locate extensions directory' where should it be?

## Steps to Reproduce

1. Open 2017, 2019, or 2022 cmd prompt as admin
2. Execute build.cmd from the root of the source repo

**Comment by jonathanchapmanmoore** [comment]
Yes, I get the same error the extensions directory can't be found where should it be?

**Comment by drewnoakes** [comment]
This error is coming from the VSSDK. I don't see it locally.

Note that you must build this repo using VS2022. Earlier versions won't work.

Perhaps you could try resetting your experimental hive. There'll be an entry in your start menu for that. Something like _Reset the Visual Studio 2022 Experimental Instance_.

Does it work if you build from Visual Studio?

If none of that works, you can use `msbuild /t:Restore,Rebuild -bl` to produce a file `msbuild.binlog`. You can view that file using https://msbuildlog.com and should get a better idea of what's going wrong. If that doesn't work, and you're happy to share the log (it may contain details from your machine such as your user ID and environment variables, so please check you're happy to share it with me privately), you can email it to drnoakes at Microsoft.

**Comment by MiYanni** [comment]
@jonathanchapmanmoore Our repo currently can be built using only the VS Build Tools, but you need to specify that the VS extension should not be deployed. Also, the tests will fail when doing this, but I'm not investigating that at the moment. I'm currently changing how `build.cmd` works, so I'm not sure there is a way currently. There is a flag, `/no-deploy`, but I'm not sure that functions at the moment. I've changed a lot infrastructure-wise recently and non-deployment building wasn't something I tested. Once I have these changes in, I'll let you know how to run it for your situation.

If you don't want to wait for all that, if you install VS 2022 and run the command again, it'll work. The error about it not finding the extensions directory is the Visual Studio extensions directory. Using the VS Build Tools only, no extensions directory exists.

**Comment by MiYanni** [comment]
@jonathanchapmanmoore We decided to not support Visual Studio Build Tools as an option for building this repo. If you need a free way to build it, you can use the VS Community edition.
