### ISSUE TITLE
Fail to parse a launch profile with other settings value of type list of strings

### ISSUE THREAD

**Issue by ravipal** [dotnet/project-system#8360]
## Visual Studio Version
Version 17.4.0 Preview 1.0 [32724.67.main]
And it also reproduces in Version 17.3.0 Preview 2.0 [32509.446.main]

## Summary
1. Docker compose project produces a launch profile as shown below. Note that one of the entries of `composeProfile` is `includes` and its value is list of service names.

```
{
  "profiles": {
    "Docker Compose": {
      "commandName": "DockerCompose",
      "commandVersion": "1.0",
      "composeProfile": {
        "includes": [
          "web1"
        ]
      }
    }
  }
}
```
2. This profile results into parsing error and produces a profile "ErrorProfile" with the message "ErrorString", "Expected property name at 8:16 but got string".

![image](https://user-images.githubusercontent.com/1775825/181639784-6cc6c30d-27e6-4f45-979b-ad149d55058a.png)

## Steps to Reproduce

1. Ensure the 'Azure Development' workload is installed and [Docker Desktop for Windows](https://docs.docker.com/desktop/windows/install/) is installed
2. Create a new .NET Core project with any templates.
3. Right click the project -> "Add" -> "Container Orchestrator Support" -> "docker-compose" -> "Linux/Windows" -> "OK".
4. update docker-compose.yml file by adding a profiles:[web1] then save it. (E.g. 
services:
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    profiles: [web1]
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
5. right click on the compose project and open the "Manage Docker Compose Launch Settings" dialog, check the profile "web1", save. Now a launch profile will be created as shown below
```
{
  "profiles": {
    "Docker Compose": {
      "commandName": "DockerCompose",
      "commandVersion": "1.0",
      "composeProfile": {
        "includes": [
          "web1"
        ]
      }
    }
  }
}
```
6. Close solution and reopen. Now check debug button
![image](https://user-images.githubusercontent.com/1775825/181640478-32d89467-2e7c-430b-a2c5-7d19de0c549c.png)

## User Impact
User will not be able to use the profile that uses the docker compose profile.

Note, I believe this is caused by this commit [Don't rely on JSON.NET's object serialization · dotnet/project-system@3b523af (github.com)](https://github.com/dotnet/project-system/commit/3b523af79a4eb6a5eecaf5794407c90f1ea2168f)

**Comment by drewnoakes** [comment]
@ravipal the fix has been inserted for 17.4. We are working on getting it into 17.3 as well.
