### ISSUE TITLE
Create a LinkActionEditor command type to logically focus part of the property page

### ISSUE THREAD

**Issue by adamint** [dotnet/project-system#8382]
Currently, the only available LinkAction command types seem to be to open the launch profile window and to open a file in VS. It may be beneficial to expose a command type that will allow focus to move to a different part of the property pages, whether it be a (in the main property page window) a Property, a property category, property page), or (in the navigation pane) a property category or page.

This would allow us to, for example, redirect users to a different section of the property pages if a property's location has changed

**Comment by drewnoakes** [comment]
Great idea.

**Comment by adamint** [comment]
PR tracked in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/425720
