### ISSUE TITLE
Ensure code consistency in variable naming, in VB files.

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#8404]
This is low priority, but it would be nice to go through our VB files and ensure there's consistency on our code conventions to name variables (global, local, constants, etc.): there are places where we use a mix of camel case and pascal case, even all-caps. This effort will help our code documentation be consistent, even if we don't usually add/edit these files as frequently as others in C#.

This effort is the result of @KlausLoeffelmann's observation in https://github.com/dotnet/project-system/pull/8400#discussion_r947120998. 😄

**Comment by ocallesp** [comment]
Perhaps this is something that can be triage-approved and do during the next @melytc 's rotation.
cc: @kvenkatrajan

**Comment by paul1956** [comment]
I did this about a year ago using Roslyn's built in Analyzers there were over 6,000 violations and I fix some (~1,000) but most were rejected as too risky and too much churn by the reviewer even though all tests passed and all changes were using built in Analyzers Roslyn code fixes.

**Comment by drewnoakes** [comment]
I would be concerned by wide automated changes to the VB code in this repo. We don't have adequate test coverage, nor do we have the high level of language expertise on the team to be confident that such changes wouldn't break anything.

The inconsistency in the code is frustrating, but we work in these projects less and less over time. The risk is too high and the reward too low IMHO.

**Comment by KlausLoeffelmann** [comment]
I sadly have to agree!

**Comment by paul1956** [comment]
@drewnoakes @KlausLoeffelmann Same decision @CyrusNajmabadi made about a year ago after I agreed to do the changes. There is some that can be automated but much is manual.

**Comment by drewnoakes** [comment]
I think we'd all like to see the code be more consistent here, but there is a lot of code and even automated clean up and lead to errors. On balance I don't think we're likely to change this wholesale across the VB.NET code, however we will continue to clean up the areas we work on as we touch them.
