### ISSUE TITLE
UI for blank configuration value is not being displayed

### ISSUE THREAD

**Issue by adamint** [dotnet/project-system#8406]
[Yesterday 1:19 PM] James Parsons
I'm able to reach a state where the UI for 1 configuration is not being displayed if it has no value:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/20359921/185496997-bf1ca2a1-0dc3-4eef-ba16-c1576d848ced.png)

[Yesterday 1:20 PM] James Parsons
This is the expectation:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/20359921/185497042-18748b54-311a-43ad-a38b-4184ec7e2987.png)

Repro steps:
Go to iOS->Bundle Signing-> Custom Entitlements property.

Select Vary value by Configuration.

Type a value in the Debug text box and press tab.

**Unknown whether it's a regression, as there was a blocking separate issue which is now fixed**
reported by @japarson

**Comment by adamint** [comment]
@japarson mention when this is reproducible

**Comment by japarson** [comment]
> @japarson mention when this is reproducible

Should be in VS main as of build 32822.140

**Comment by adamint** [comment]
Cool, looks like this isn't reproducible anymore, for whatever reason. Resolving @japarson
