### ISSUE TITLE
Need pass a name to create NamedIdentity inside DebugProfileDebugTargetGenerator

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#8410]
Although it is an optional parameter, and not really used to compare two ids, but it is essential part in NFE diagnostic messages and dump analysis tools to investigate deadlocks.  Please pass in a valid name in the code. (Maybe forbid any usage without passing in a name inside NET Core code).  Using nameof(DebugProfileDebugTargetGenerator) is perfectly fine, which will help us to understand dataflow problems.

![image](https://user-images.githubusercontent.com/11638466/185983214-23eb7c54-51a9-4772-864e-5ec462d8ee8d.png)

**Comment by melytc** [comment]
@ocalles please close if issue has been addressed.
