### ISSUE TITLE
[Tracking] Consider renaming "Ramp-Up" label to "good first issue"

### ISSUE THREAD

**Issue by mairaw** [dotnet/project-system#8417]
We're trying to get a consistent experience for newcomers. See some context at https://github.com/dotnet/runtime/issues/71496

You should also consider adding the project to https://up-for-grabs.net/
See an example PR at https://github.com/up-for-grabs/up-for-grabs.net/pull/3329

/cc @danmoseley

**Comment by adamint** [comment]
Thanks for the suggestion @mairaw. We've gone ahead and done this
