### ISSUE TITLE
Incorrect document causing problems in rule system

### ISSUE THREAD

**Issue by lifengl** [dotnet/project-system#8418]
The document in https://github.com/dotnet/project-system/blob/main/docs/repo/property-pages/property-specification.md leads people to create project rules in unnamed context group. We have similar document in this repo, which is doing the right thing:

```xml
<PropertyPageSchema Include="path\to\MyPropertyPage.xaml">
  <Context>Project</Context>
</PropertyPageSchema>
```

Currently, adding a rule without specifying context would inject the rule into all valid catalogs. This will add the rule into the "project" one and make the page to work correctly as a project page.  However, the rule will also be injected into 'browseObject' which leads the bowser properties of the project to be wiped out (because only one rule is allowed to describe project's browse object.

Based on this problem, we will kill this behavior, so all rules without specifying context will only stay as a rule in the empty context catalog, and those pages will no longer be shown in the next update.

Please fix the incorrect document, and potentially work with other people who may create pages by following the incorrect document, as those pages will stop working.

**Comment by lifengl** [comment]
That is the product issue when 'context' is not specified for a project property page rule. https://developercommunity.visualstudio.com/t/Error-SynthesizedEmpty-in-VS-1726-af/10097904

**Comment by tmeschter** [comment]
This has also cropped up in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1556018 and the related bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1585601.
