### ISSUE TITLE
Add VS insertion detailed description

### ISSUE THREAD

**Issue by MiYanni** [dotnet/project-system#8423]
As per the changes in [this PR](https://github.com/dotnet/project-system/pull/8420), we moved to using MicroBuild to create our VS insertion PRs. MicroBuild does not provide detailed descriptions for their VS insertion PRs. To provide the same convince that we had prior, we'll need to add this mechanism to our repo.
- Isolate the code from [Roslyn Insertion Tool](https://github.com/dotnet/roslyn-tools/tree/main/src/RoslynInsertionTool) that created this description
- Create a small, single purpose tool in our repo that simply spits out this description string
- Assign description string to a variable in the pipeline
- Assign the variable to the `InsertionDescription` value in the MicroBuild Insertion task

**Comment by JoeRobich** [comment]
Here is the script I ran prior to migrating the code into RIT - https://gist.github.com/JoeRobich/5b02dbe9b9d60b4699df546036040888

**Comment by MiYanni** [comment]
@JoeRobich That's really useful as it uses the local repo on-disk to get the commit information. RIT does a REST call to GitHub to get this information, which is completely unnecessary in our situation. I'll be combining bits of each to make something that produces a similar result.
