### ISSUE TITLE
"Enable symbolic renaming when renaming files" options not persisted properly

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8441]
## Visual Studio Version

17.4.0 Preview 2.0 [32829.42.main]

## Summary

The options around renaming a type when the containing file is renamed are not persisted properly, which leads to types being renamed even when the user has told us not to do that.

## Steps to Reproduce

1. Open _Tools | Options | Projects and Solutions | General_ and make sure the following two options are enabled:
![image](https://user-images.githubusercontent.com/10506730/187508538-cee35a20-ab1d-45c2-9863-f2a3f3f2628e.png)
2. Click "OK" to close the Options dialog.
3. Create a new C# class library targeting .NET 6.
4. In Solution Explorer, right-click on Class1.cs, select "Rename" from the menu, and rename it to "Class2.cs".
5. When this dialog comes up:
![image](https://user-images.githubusercontent.com/10506730/187508968-3656f6e9-e280-499b-a9bd-d206030fd5bc.png)
Check "Don't show again" and click "No".
6. Verify that the type inside Class2.cs is still named "Class1".
7. Add a new class named "Class3" to the project.
8. In Solution Explorer, right-click on Class3.cs, select "Rename" from the menu, and rename it to "Class4.cs".

## Expected Behavior

- The file is renamed to Class4.cs.
- The dialog asking if you want to rename the type does _not_ appear.
- The type in the file is _not_ renamed; it is still Class3.

## Actual Behavior

The dialog asking if you want to rename the type does not appear, **but the Class3 type is automatically renamed to Class4.**

Going back to _Tools | Options | Projects and Solutions | General_, we see the settings are now:

<img width="240" alt="image" src="https://user-images.githubusercontent.com/10506730/187510046-432bddfe-eb65-4056-a347-1e937559931e.png">

Which is incorrect.

## User Impact

We will now _always_ rename types to match file names, which is the exact opposite of what the user asked for.

**Comment by ocallesp** [comment]
It seems that
if "Don't show again" is checked, then persist UNcheck "prompt for symbolic renaming when renaming files"
   if "Yes", then persist check "enable symbolic renaming when renaming files"
   if "No", then persist UNcheck "enable symbolic renaming when renaming files"

If "Don't show again" is UNchecked, do not change "enable symbolic renaming when renaming files" and "enable symbolic renaming when renaming files"
