### ISSUE TITLE
Broken integration test AnalyzersNode_NetCore.xml

### ISSUE THREAD

**Issue by mavasani** [dotnet/project-system#846]
Once we add an "Analyzers" node under Dependencies, we should fix and enable [this](https://github.com/dotnet/roslyn-internal/blob/master/Closed/Hosting/RoslynTaoActions/IntegrationTests/AnalyzersNode_NetCore.xml) integration test.

**Comment by srivatsn** [comment]
We already have an Analyzers node that will show up if there are analyzer assembly dependencies.

**Comment by johnbeisner** [comment]
Removing my assignment to this issue as I am moving to a new team.

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving to 15.4 to get it off the radar.

**Comment by MattGertz** [comment]
Mondo escrow triage: test-only, moving to 15.4 to get it off the radar.

**Comment by tmeschter** [comment]
We're in the process of re-evaluating our integration test framework. This will be addressed in 15.6 at the earliest.

**Comment by davkean** [comment]
The integration tests are at a state where this bug is not useful. When we re-enabled them we'll reopen/file new bugs.
