### ISSUE TITLE
VSShellServices never initialised

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8504]
https://github.com/dotnet/project-system/pull/8239 ported the `IVsShellServices` interface and implementation from CPS to the .NET Project System.

That PR uses `IVsShellServices.IsInServerMode` to change behavior in server mode.

In CPS, that interface's implementation also implemented the (CPS-internal) `ICriticalService` interface, which caused CPS to initialize it early in CPS's lifecycle.

However, in our code nothing ever initializes `VSShellServices`. Nothing calls this method:

https://github.com/dotnet/project-system/blob/b71ed9c06d70483a5cbfc26052e2b70dd0391730/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Shell/VSShellServices.cs#L40

The result is that currently property `IVsShellServices.IsInServerMode` is always `false`.

Currently, the only consumer of this property is:

https://github.com/dotnet/project-system/blob/47d7dede65bb5abc574cf11077238f2a0c8919a2/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UI/InfoBarService/VsInfoBarService.cs#L35-L55

In practice, this mode is seldom used and so it's unlikely this code defect would ever materialize as a visible product bug.

**Comment by davkean** [comment]
IsInServiceMode is no longer revelant and can be deleted.

**Comment by drewnoakes** [comment]
> IsInServiceMode is no longer revelant and can be deleted.

Done as part of https://github.com/dotnet/project-system/pull/8506.
