### ISSUE TITLE
.NET Project System - Refactor

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8532]
This is tracked in internal experience : [AB#1632825](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1632825)

- [x] #8577
- [x] #8576
- [x] #8575
- [X] #8573
- [x] #8574 
- [ ] ~~#8572~~
- [x] #8571 
- [x] #8570

**Comment by MiYanni** [comment]
HotReload is no longer in scope. I crossed it out. Closing the issue as completed.
