### ISSUE TITLE
Adding a conditional compilation symbol generate the symbol 'TRACETRACE'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#8536]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/t/Adding-a-conditional-compilation-symbol-/10150801). Please vote and comment there to make sure your voice is heard._

---
In a new .Net MAUI project, when the conditional compilation symbol 'MYTEST' is added the symbol 'TRACE' is changed to 'TRACETRACE'

Before adding a symbol (in Debug & Release the 'TRACE' is available):
![image.png](https://aka.ms/dc/image?name=Bdb60d7c49b3c45ab85ee4a7042a52749637990051867884368_20220917-115305-image.png&tid=db60d7c49b3c45ab85ee4a7042a52749637990051867884368)

After adding the symbol 'MYTEST' (in Debug & Release the 'TRACETRACE' is available):
![image.png](https://aka.ms/dc/image?name=B0761202f12b54e68ba3fb74f9d3a0b9f637990052190471848_20220917-115337-image.png&tid=0761202f12b54e68ba3fb74f9d3a0b9f637990052190471848)

Tested with Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.3.4

Steps to Reproduce:
1. Create a MAUI Application
2. Open the properties of the project
3. In Build=>General, add a semi-colon to separate symbol and add the conditional compilation symbol 'MYTEST'

---
#### Adam Ratzman [MSFT] solved on 9/21/2022, 09:44 AM, 0 votes: 

Hi, thanks for your report. This is in fact expected behavior. The imported value is `$(DefineConstants)TRACE`. When you modify this value, it is saved in your project file. If you save it as `$(DefineConstants)TRACE;MYTEST;` to your project file, MSBuild will evaluate this as `$(DefineConstants)TRACE;MYTEST`, where `$(DefineConstants)` is the imported value `$(DefineConstants)TRACE` leading to `$(DefineConstants)TRACE;TRACE;MYTEST`.

To resolve your issue, please remove TRACE from your property value - make it `$(DefineConstants)MYTEST`.

**Comment by adamint** [comment]
Fixed in #8662
