### ISSUE TITLE
Localization bug: Compilation constants property's description not localized.

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#8547]
## Visual Studio Version
17.4 preview 3

## Summary
![image](https://user-images.githubusercontent.com/8518253/192907473-0831d4ae-bcce-423d-baef-6906d8d59834.png)

## Steps to Reproduce

1. Modify your setup to include the Spanish language pack.
2. Launch VS.
3. Continue without code. Tools->Options->Environment->International Settings-> Select language (Spanish) ->OK -> Restart VS.
4. Create VB Console Project
5. Open project properties UI.

## Expected Behavior
Compilation constants property's description is translated to Spanish

## Actual Behavior
Compilation constants property's description is not translated

**Comment by drewnoakes** [comment]
This string is changing as part of #8521 (for VB projects at least).

**Comment by melytc** [comment]
This has been fixed, see localized file: https://github.com/dotnet/project-system/blob/c1d7d1156795498617873228e12d1940b5421b86/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.xaml.es.xlf#L440-L442
