### ISSUE TITLE
Refactor ProjectSystem/VS/Build

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8570]
Refactor the types in [ProjectSystem/VS/Build](https://github.com/dotnet/project-system/tree/main/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Build) to isolate the VS dependencies behind a new interface, and then move the implementation down to the Microsoft.VisualStudio.ProjectSystem.Managed project.

**Comment by ocallesp** [comment]
`IIncrementalBuildFailureReporter `
`IncrementalBuildFailureDetector ` implements IVsUpdateSolutionEvents2, and `IVsRunningDocTableEvents`
`IncrementalBuildFailureOutputWindowReporter` reports failures to the Output Window which is Vs specific
`IncrementalBuildFailureTelemetryReporter` imports `IVsFeatureFlags`. We can abstract this service and move it to the managed project.
`ImplicitlyTriggeredDebugBuildManager` implement `IVsUpdateSolutionEvents2`, and `IVsUpdateSolutionEvents3`
`LanguageServiceErrorListProvider` implements `IVsErrorListProvider` which is specific to Vs
`ISolutionBuildManager` makes use of `IVsUpdateSolutionEvents`
`SolutionBuildManager` makes use of `IVsSolutionBuildManager2 ` and `IVsSolutionBuildManager3`

It seems that no refactor is needed.

Any thoughts @drewnoakes ?

**Comment by drewnoakes** [comment]
This looks good to me.
