### ISSUE TITLE
Refactor ProjectSystem/VS/Debug

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8571]
Refactor the types in [ProjectSystem/VS/Debug](https://github.com/dotnet/project-system/tree/main/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug) to isolate the VS dependencies behind a new interface, and then move the implementation down to the Microsoft.VisualStudio.ProjectSystem.Managed project.

**Comment by ocallesp** [comment]
Theses classes are Vs dependent because they implement `IVsUpdateSolutionEvents2`, `IVsRunningDocTableEvents`, `IVsOutputWindow `or make use of constant values like `VSSOLNBUILDUPDATEFLAGS`

**Comment by ocallesp** [comment]
It seems that no refactor is needed.

Any thoughts @drewnoakes ?

**Comment by drewnoakes** [comment]
@ocallesp the types you mention here are related to build, not debug. Are you commenting on the right issue?

**Comment by ocallesp** [comment]
I'll delete these comments to avoid confusion.

**Comment by ocallesp** [comment]
Checking this ....

**Comment by ocallesp** [comment]
The remaining code depends on the interface `ProjectSystem.VS.Debug.IDebugLaunchSettings` from CPS which are VS dependent.
