### ISSUE TITLE
Refactor ProjectSystem/VS/PackageRestore

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8574]
Refactor the types in [ProjectSystem/VS/PackageRestore](https://github.com/dotnet/project-system/tree/main/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore) to isolate the VS dependencies behind a new interface, and then move the implementation down to the Microsoft.VisualStudio.ProjectSystem.Managed project.

**Comment by ocallesp** [comment]
checking this...
