### ISSUE TITLE
Refactor ProjectSystem/VS/Refactor

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8575]
Refactor the types in [ProjectSystem/VS/Refactor](https://github.com/dotnet/project-system/tree/main/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Refactor) to isolate the VS dependencies behind a new interface, and then move the implementation down to the Microsoft.VisualStudio.ProjectSystem.Managed project.

**Comment by ocallesp** [comment]
@tmeschter @MiYanni 

In here, `IRefactorNotifyService` already abstracted a general interface and it is already in the Managed project.

The implementation of this interface related to Vs is already in `VS/Refactor` and it all depends on `IVsHierarchy`

No work needed here.
