### ISSUE TITLE
Refactor ProjectSystem/VS/Tree

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8576]
Refactor the types in [ProjectSystem/VS/Tree](https://github.com/dotnet/project-system/tree/main/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree) to isolate the VS dependencies behind a new interface, and then move the implementation down to the Microsoft.VisualStudio.ProjectSystem.Managed project.

**Comment by ocallesp** [comment]
The remaining code are not using API that depends on VS, but the code only applies to the behavior of Solution Explorer and Commands in VS.
