### ISSUE TITLE
Refactor ProjectSystem/VS/UpToDate

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8577]
Refactor the types in [ProjectSystem/VS/UpToDate](https://github.com/dotnet/project-system/tree/main/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/UpToDate) to isolate the VS dependencies behind a new interface, and then move the implementation down to the Microsoft.VisualStudio.ProjectSystem.Managed project.

**Comment by drewnoakes** [comment]
There should be no work required here. The fast up-to-date check is already split between layers, with minimal code in the VS layer.

**Comment by ocallesp** [comment]
A quick code review is showing that classes implement `IVsUpdateSolutionEvents2`, `IVsSolutionEvents`, and is very specific for Vs property ids __VSSPROPID
