### ISSUE TITLE
Custom value highlight (IsDefinedInContext) not working for ImplicitUsings

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8578]
While investigating #8553 I noticed:

![image](https://user-images.githubusercontent.com/350947/194534278-5add7bbd-79dd-4352-a20b-958621915e33.png)

There should be a vertical bar alongside this property in the UI here to indicate that the property has been specified directly in the project file:

![image](https://user-images.githubusercontent.com/350947/194534325-d3c03d06-b9ee-46e2-bf1d-9cfb9eb64dd4.png)

**Comment by adamint** [comment]
This is weird because we appear to be returning the right values

**Comment by adamint** [comment]
it looks like we should override this function for both implicitusings and implicitusingseditor
