### ISSUE TITLE
ClickOnce Publish... command

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#86]
_From @davkean on March 22, 2016 22:23_

Tracking the work to add support for the Publish... command on the project to publish a project via ClickOnce:

![image](https://cloud.githubusercontent.com/assets/1103906/13969767/f63df6c0-f041-11e5-966f-a230552264ad.png)

_Copied from original issue: dotnet/roslyn#9985_

**Comment by hrichardlee** [comment]
Not sure if this is the right place, but I wanted to ask whether ClickOnce is supported in any capacity right now with the new project system. We just tried to upgrade and this one was the showstopper. I'm sure it's tough to comment, but if there's any guidance you can give on whether this is planned to be supported or if there's a different technology that's recommended, that would be awesome.

Thanks! Also, hey, @davkean! (This is Richard who used to be an intern on your team.)

**Comment by shaggygi** [comment]
Referencing... https://github.com/Microsoft/msix-packaging
Not sure if it is related and eventually replacing ClickOnce, but sounds like.

**Comment by eriawan** [comment]
@shaggygi 

No, it will not replace ClickOnce. MSIX is actually APPX with better integration with IT Ops.

**Comment by davkean** [comment]
The intention is that MSIX will be a replacement for ClickOnce. Other options are Squirrel or MSI itself (via WIX or some other options). Squirrel is probably the closest you have to ClickOnce.

We do indent long term to support ClickOnce in the new project system, post VS 2017.

**Comment by eriawan** [comment]
@davkean 

MSIX will replace ClickOnce? 
Afaik, Mike Harsh on MS Build said that ClickOnce will always be supported, and there's no mention about replacing ClickOnce. CMIIW, though.

**Comment by davkean** [comment]
As with most technologies that we ship, ClickOnce *will* continue to be supported as long as the OS it ships with.

**Comment by dmonroym** [comment]
@davkean @jjmew given the comments on https://github.com/dotnet/project-system/issues/494#issuecomment-581038253 should this issue be closed?

**Comment by davkean** [comment]
No, that was tracking adding something new, this is tracking bringing the existing support foward.

**Comment by tmeschter** [comment]
I tried publishing a basic WPF app targeting .NET Core 3.1 via ClickOnce and everything worked as expected, as far as I could tell. At this point I don't think there is anything further to do with this issue.
