### ISSUE TITLE
VS automatically adds <ItemGroup> with Remove="xxx" for new files

### ISSUE THREAD

**Issue by tompazourek** [dotnet/project-system#8636]
## Visual Studio Version

17.3.6

## Summary

I have a custom package that automatically adds all CSHTML files inside a project into a custom MSBuild item called `<RazorTranspilerInputRazor>` used by some tooling we have. The MSBuild code looks inside the package looks as follows:

```xml
<ItemGroup>
  <RazorTranspilerInputRazor Include="**\*.cshtml" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
</ItemGroup>
```

When I then add a new CSHTML file in Visual Studio in Solution explorer (I usually copy-paste an existing one), Visual Studio adds some custom code to explicitly remove the new file from the wildcard... Let's assume I create a copy of file `XXX.cshtml` This is what gets automatically appended to the csproj by Visual Studio:

```xml
<ItemGroup>
  <RazorTranspilerInputRazor Remove="XXX.cshtml" />
</ItemGroup>
```

How do I stop this behavior? I want the original wildcard to work and include all CSHTML files, including the new files. Yet, Visual Studio tries very hard to break this and exclude any new files from the wildcard. Every time I copy-paste a file, VS removes it, and I have to revert that removal. It's very annoying.

Is there some way to work around this?

I found some other people having similar issues, e.g.: https://stackoverflow.com/questions/69240061/how-to-stop-visual-studio-from-automatically-adding-remove-in-an-item-group-in-m But no answer yet.

**Comment by tompazourek** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/27718

**Comment by tompazourek** [comment]
I found a possible workaround for me. Since I don't need the item in design-time, making the wildcard include conditional seems to fix the issue:

```xml
<ItemGroup Condition="'$(DesignTimeBuild)' != 'true'">
  <RazorTranspilerInputRazor Include="**\*.cshtml" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
</ItemGroup>
```

Still, this is very annoying, and I'm not sure how I'd fix the issue if I needed the MSBuild items even in design-time...

**Comment by adamint** [comment]
Hi @tompazourek, can you open a feedback ticket at https://developercommunity.visualstudio.com/home and put the link here @tompazourek so we can ensure it's routed correctly? We believe this is a CPS issue.
