### ISSUE TITLE
Property description string missing in localized files.

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#8669]
`DefineConstants` property (the VB-specific one) is missing its localized description.

Here it is in its base class:
https://github.com/dotnet/project-system/blob/c3c787868756f8726bca5b0da8961e46d1b6be7d/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml#L415-L420

There is no entry found in the localization file, i.e. [Spanish version](https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.es.xlf), look for DefineConstants and we only have its `DisplayName`.

**Comment by melytc** [comment]
I might be looking at the wrong file for its localized values, @MiYanni, but I couldn't find them.

**Comment by melytc** [comment]
Note: this string is being changed in this PR: https://github.com/dotnet/project-system/pull/8521, so maybe after it's merged we'll see the correct localized values.

**Comment by melytc** [comment]
This string has changed to 
```
      <trans-unit id="StringProperty|DefineConstants|Description">
        <source>Specifies custom conditional compilation constants for your application.</source>
        <target state="new">Specifies custom conditional compilation constants for your application.</target>
```.

No localization has kicked in yet.

**Comment by MiYanni** [comment]
@melytc I went and looked and didn't find that string. I realized it is in Hailey's PR, which isn't merged yet. https://github.com/dotnet/project-system/pull/8695/files#diff-d888b306ec77ce6ea03907929484d0a7e1a372f1d7a638deb004fb31a67ca929R419

**Comment by melytc** [comment]
Oh, it was closed, I thought it was merged. (#8521) #8695 will have this string, I'll wait for it to be merged to check if it's picked up.

**Comment by adamint** [comment]
Completed thru https://github.com/dotnet/xliff-tasks/pull/716
