### ISSUE TITLE
Application.myapp file erroneously created when editing VB class library project properties

### ISSUE THREAD

**Issue by definesfineout** [dotnet/project-system#8693]
## Visual Studio Version

2022 Enterprise 17.4.1

## Summary

When viewing a VB class library project's properties using VS property panels (right-click, properties), a superfluous file is generated.

## Steps to Reproduce

1. In VS, open a VB class library project or solution containing a project targeting .NET 6
2. Edit the project properties using properties panels (right click, properties)

## Expected Behavior

No superfluous files generated.

## Actual Behavior

Superfluous Application.myapp generated.

## User Impact

User has to manually delete added file(s). Issue recurs whenever editing project properties.

**Comment by drewnoakes** [comment]
@melytc can you investigate and see whether we can get a fix in for 17.5?

**Comment by adamint** [comment]
@drewnoakes We can get this in for 17.5. The MyAppFileAccessor can be modified to only create the file on modification, not on read as current behavior in #8333 specifies. Also a good first issue

**Comment by adamint** [comment]
This doesn't actually reproduce for me on a new VB class library. @definesfineout this file is only created when a project has a WPF or Winforms capability, are you sure your project doesn't have either?

**Comment by definesfineout** [comment]
Yep, absolutely certain.

**Comment by drewnoakes** [comment]
@definesfineout we'd love to fix this, but without a repro it's hard to know what's needed. Are you able to take a project that this occurs for, strip it back, then share it with us? It's unlikely that any of your source files are related, not any `ProjectReference` items. A `PackageReference` could theoretically be involved, but you would be able to validate that.

**Comment by definesfineout** [comment]
I'll see if I can reproduce today. We don't work with WPF or Winforms at all. It was happening every time we edit any project, but I don't use the edit project panels anymore because it was such a pain. I've just edited the project directly since this started happening.

I can't provide any stripped down version which is why I reproduced with a new project before submitting.

**Comment by drewnoakes** [comment]
I tried this today as well and cannot reproduce.

If you create a brand-new VB console app for .NET 6, do you see this behaviour?

- If not, then there must be something about your project that's causing VS to create the file. This could be within a `Directory.Build.props` file, or a NuGet package that includes `.props` or `.targets` files, for example.
- If so, then could you please try repairing VS via the VS installer? Alternatively you could upgrade to one of the 17.5 previews to see whether the bug has been fixed already.

**Comment by definesfineout** [comment]
I'll try reproducing again and post my results.

**Comment by drewnoakes** [comment]
Thanks @definesfineout. I suspect that once we have a repro, this would be a straightforward fix though.

We create the `.myapp` file [here](https://github.com/dotnet/project-system/blob/3742e229b41a086d738745a5e5a7a15f535deff7/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/WindowsForms/MyAppFileAccessor.cs#L81-L84).

@melytc @adamint it seems that `TryGetMyAppFileAsync` is called from `GetStringPropertyValueAsync` and will always create the file if it doesn't exist. Perhaps we need to change what happens here when the file doesn't exist and we are trying to read a property. Today we create the file then return the default value for the property (as per `DefaultMyappFileContents`). We could change this so that we don't create an empty file and instead just return `null` for the property value. We'd need to spend some time to test this in various scenarios. I suspect it's the root cause of this issue however.

**Comment by definesfineout** [comment]
I was able to reproduce this morning; using a VB class library .NET Framework 4.8 and converting to SDK-style format. This didn't occur for C# class libraries, and only seems to occur with the newer properties panels with SDK-style projects.

1. Create new project: Class Library (.NET Framework) Visual Basic
2. Convert new project to SDK-style format, using migration tool from https://github.com/hvanbakel/CsprojToVs2017
    specific command used: `dotnet migrate-2019 wizard ClassLibrary1.vbproj` then 'Y' when asked to modernize projects
3. Open the project/solution in Visual Studio
4. Open project properties (right click > properties or alt+enter)
5. Check project folder for appearance of superfluous Application.myapp file

**Comment by definesfineout** [comment]
I was just able to reproduce this with the original information in this ticket for both .NET 6 and .NET 7 Visual Basic class library projects. No migration as they already come in CPS-based format.

1. Create new project in Visual Studio, class library Visual Basic .NET 6 or 7
2. Open project properties
3. Application.myapp appears in project directory

**Comment by drewnoakes** [comment]
I wouldn't expect any change in 17.4.4 vs 17.4.3. If you're able to install a 17.5 preview (or wait until it is released) there is a chance the problem has been addressed.

**Comment by definesfineout** [comment]
Sure, I can install and test with 17.5 preview.

Just to confirm: after repairing local install of 17.4.3, I reproduced again by creating a .NET 6 VB class library, opening project properties, and observing the file created.

**Comment by drewnoakes** [comment]
Thanks for confirming. I'm hopeful that 17.5 will fix the issue for you, given that both @adamint and I are unable to repro the problem using the straightforward steps you explain on more recent (internal) builds.

**Comment by definesfineout** [comment]
Confirmed this no longer occurs in 17.5 🚀

**Comment by drewnoakes** [comment]
Great news! Thank you for taking the time to validate this 🙏
