### ISSUE TITLE
Exception in language service when trying to get ordered data from snapshots

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8698]
## Visual Studio Version

Guessing 17.4.

## Summary

Reported [on Twitter](https://twitter.com/NickeManarin/status/1597780825042714625) by @NickeManarin:

![image](https://user-images.githubusercontent.com/350947/205031487-ef489d99-518c-494e-a1db-38dfcdd5bfb6.png)

The issue is occurring here:

https://github.com/dotnet/project-system/blob/1ab64d2a232c4a8a88e7e6e8edb6f6aa3107f157/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Workspace.cs#L430-L432

For some reason, the project change's items do not provide an ordered source. It's unclear exactly what type is failing to cast here, unfortunately.

## Steps to Reproduce

Unknown.

## Expected Behavior

No exception. 

## Actual Behavior

An exception has been reported in the wild.

## User Impact

This exception tears down the language service for that project, meaning code analysis may stop responding to changes in the project, such as new files, new references to packages or other projects.

Reloading the project might help, so long as the exception doesn't immediately reoccur.

**Comment by NickeManarin** [comment]
Hi, I was working and testing my software in debug mode, when changing to Release and re/building the project, I was greeted with a StatusBand/InfoBar telling me that the project could not be loaded and required a manual reload.

Upon reload, it worked normally.

I had recently published the software, while in debug mode using "Publish as x64.pubxml" profile (then I changed the mode to Release).

> Microsoft Visual Studio Community 2022
> Version 17.4.1
> VisualStudio.17.Release/17.4.1+33110.190
> Microsoft .NET Framework
> Version 4.8.04161
> 
> Installed Version: Community
> 
> Visual C++ 2022   00482-90000-00000-AA858
> Microsoft Visual C++ 2022
> 
> ASP.NET and Web Tools   17.4.326.54890
> ASP.NET and Web Tools
> 
> Azure App Service Tools v3.0.0   17.4.326.54890
> Azure App Service Tools v3.0.0
> 
> C# Tools   4.4.0-6.22559.4+d7e8a398ef479a908e76bded82150c39251d0c9c
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> NuGet Package Manager   6.4.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
> 
> Test Adapter for Boost.Test   1.0
> Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.
> 
> Test Adapter for Google Test   1.0
> Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.
> 
> TypeScript Tools   17.0.10921.2001
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Basic Tools   4.4.0-6.22559.4+d7e8a398ef479a908e76bded82150c39251d0c9c
> Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
> Microsoft Visual F# Tools
> 
> Visual Studio IntelliCode   2.2
> AI-assisted development for Visual Studio.

(I also have ReSharper installed)

Here's the whole log:

[VsProjectFault_d2776edc-bf24-474f-b46e-eea529c19a2a.failure.txt](https://github.com/dotnet/project-system/files/10136759/VsProjectFault_d2776edc-bf24-474f-b46e-eea529c19a2a.failure.txt)

-----------------

> Is there a repro for this? If the solution is open source I can try and repro it. 

  Yes, https://github.com/NickeManarin/ScreenToGif/tree/feature/95-layers 
  Project `Other/ScreenToGif`, mind that the other project with the same name is being replaced and it's not compiling.

> What version of VS is this?

17.4.1

> Was this just a once off, or does it happen frequently?

It happened once.

> Does reloading the project help, or does the error come straight back?

Yes, it worked normally (until now) after project reload.

**Comment by drewnoakes** [comment]
Another hit of this in AB#1680186, though in a different component. That bug is the fast up-to-date check.

https://github.com/dotnet/project-system/blob/f11b6d17601e4e0ffe20776982dcd586a3358712/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/UpToDateCheckImplicitConfiguredInput.cs#L510-L512

**Comment by drewnoakes** [comment]
Feedback tickets hitting this:

- https://developercommunity.visualstudio.com/t/Unable-to-change-Target-Framework---Proj/10243288
- https://developercommunity.visualstudio.com/t/Vs2022-NET-%E7%89%88%E6%9C%AC%E8%BD%AC%E6%8D%A2%E5%A4%B1%E8%B4%A5%E5%B9%B6%E6%8A%A5%E9%94%99%EF%BC%8C%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E8%BF%90%E8%A1%8C/10239355

**Comment by drewnoakes** [comment]
The FUTDC issues mentioned in the previous two comments were addressed in #8781.

The originally reported issue was in the Language Service, and has a different root cause. @lifengl made a fix in CPS that I believe will have addressed it.

**Comment by drewnoakes** [comment]
CPS has a fix in 17.6 that should address this, but we can't be sure as we can't reproduce it. We will monitor 17.6 NFE reports for examples of this before closing this out.

**Comment by NickeManarin** [comment]
If you want me to test it or maybe if you want to do a quick call to check, just tell me.

**Comment by drewnoakes** [comment]
@NickeManarin thanks very much. There won't be a public build of 17.6 until 17.5 GA is released. Do you have a 100% repro for this? I thought it was a once-off thing for you. If so, can you help me try and reproduce it here?

**Comment by NickeManarin** [comment]
It happened 2-3 times after the first time. 

Testing now and it didn't happen :/
But it's always when switching from debug to release. 
Possibly publishing in release when in debug mode.

**Comment by drewnoakes** [comment]
This was fixed in https://github.com/dotnet/project-system/pull/8956 for 17.6.
