### ISSUE TITLE
FUTDC should handle EmbedInteropTypes on project references correctly

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8716]
After opting CPS into Build Acceleration, we see an additional DLL in one of the output directories:

```
bin/Microsoft.VisualStudio.ProjectSystem.VS.Implementation/Debug/net472/Microsoft.VisualStudio.ProjectSystem.Interop.dll
bin/Microsoft.VisualStudio.ProjectSystem.VS.Implementation/Debug/net472/Microsoft.VisualStudio.ProjectSystem.Interop.xml
```

From the verbose build log:

```
37>FastUpToDate:     Checking copy items from project 'D:\repos\CPS\src\Microsoft.VisualStudio.ProjectSystem.Interop\Microsoft.VisualStudio.ProjectSystem.Interop.csproj'. (Microsoft.VisualStudio.ProjectSystem.VS.Implementation)
37>FastUpToDate:         Checking PreserveNewest item (Microsoft.VisualStudio.ProjectSystem.VS.Implementation)
37>FastUpToDate:             Source      2022-12-12 15:53:53.593: 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.Interop\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.dll' (Microsoft.VisualStudio.ProjectSystem.VS.Implementation)
37>FastUpToDate:             Destination 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.dll' does not exist. (Microsoft.VisualStudio.ProjectSystem.VS.Implementation)
37>FastUpToDate:         Remembering the need to copy file 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.Interop\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.dll' to 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.dll'. (Microsoft.VisualStudio.ProjectSystem.VS.Implementation)
37>FastUpToDate:         Checking PreserveNewest item (Microsoft.VisualStudio.ProjectSystem.VS.Implementation)
37>FastUpToDate:             Source      2022-12-12 15:53:52.186: 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.Interop\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.xml' (Microsoft.VisualStudio.ProjectSystem.VS.Implementation)
37>FastUpToDate:             Destination 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.xml' does not exist. (Microsoft.VisualStudio.ProjectSystem.VS.Implementation)
37>FastUpToDate:         Remembering the need to copy file 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.Interop\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.xml' to 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.xml'. (Microsoft.VisualStudio.ProjectSystem.VS.Implementation)
...
37>FastUpToDate: Copying 2 files to accelerate build: (Microsoft.VisualStudio.ProjectSystem.VS.Implementation)
37>FastUpToDate:     From 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.Interop\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.dll' to 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.dll'. (Microsoft.VisualStudio.ProjectSystem.VS.Implementation)
37>FastUpToDate:     From 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.Interop\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.xml' to 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.xml'. (Microsoft.VisualStudio.ProjectSystem.VS.Implementation)
```

Deleting the output directory and performing a new build will not produce these files. We should understand why these files are being identified as needed and fix this.

I compared outputs of all CPS projects and this was the only difference.

**Comment by KirillOsenkov** [comment]
I usually search the binlog for `copy Microsoft.VisualStudio.ProjectSystem.Interop.dll` to see why a .dll was copied (or not copied) to output. You can combine with `project(Foo)` or `under(...)` to filter through search results.

**Comment by drewnoakes** [comment]
When Build Acceleration is disabled, the FUTDC is still considering that DLL as an output and will log:

> WARNING: Potential build performance issue in 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.csproj'. The project does not appear up-to-date after a successful build: Destination 'D:\repos\CPS\bin\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\Debug\net472\Microsoft.VisualStudio.ProjectSystem.Interop.dll' does not exist, not up-to-date. See https://aka.ms/incremental-build-failure.

We need to identify why this file is considered copyable by the FUTDC but not by a real build.

**Comment by drewnoakes** [comment]
I suspect this is related to the embedding of interop types. My working assumption is that the real build embeds the referenced types directly in the output assembly (via `csc.exe -link`), meaning the interop DLL doesn't also need to be copied to the output directory.

To fix this we need to understand the mechanism at play well enough to filter these items.

https://learn.microsoft.com/dotnet/csharp/language-reference/compiler-options/inputs#embedinteroptypes

**Comment by KirillOsenkov** [comment]
I think when references are passed to the C# compiler, the significant bits are: file path (obvs!), image kind (module vs. assembly), aliases and the embed interop types flag:

https://sourceroslyn.io/#Microsoft.CodeAnalysis/MetadataReference/MetadataReferenceProperties.cs,281ff7f6581b3de3
