### ISSUE TITLE
Include PrivateAssetIndependent in the NuGet restore nomination

### ISSUE THREAD

**Issue by erdembayar** [dotnet/project-system#8723]
Needed for https://github.com/NuGet/NuGet.Client/pull/4976
I'll file the PR.

**Comment by adamint** [comment]
@erdembayar is the nuget PR still being considered?

**Comment by erdembayar** [comment]
> @erdembayar is the nuget PR still being considered?

Yes, it's I just distracted by other things. I'll come back for it.

**Comment by MiYanni** [comment]
@erdembayar Please reopen the issue when work is needed for this functionality. Thanks!
