### ISSUE TITLE
FUTDC Warnings for missing csproj.user files

### ISSUE THREAD

**Issue by andersforsgren** [dotnet/project-system#8743]
I'm having some unnecessary rebuilds/FUTDC failures, and I'm seeing this:

> Potential build performance issue in 'Example.csproj'. The project does not appear up-to-date after a successful build: Input 'C:\Src\Example\Example.csproj.user' does not exist and is required, not up-to-date. See https://aka.ms/incremental-build-failure.

Now, I'm pretty sure this won't reproduce in a minimal example, so before I try to simplify and pin it down from my massive solution, I thought I'd ask:  Is a csproj.user really a "required" input for any project or can I safely ignore this?

This is in Visual Studio v17.4.0 building a solution of SDK style projects, targeting net48.

**Comment by drewnoakes** [comment]
@andersforsgren a `.csproj.user` file is not required unless a project advertises it as being present.

My assumption is that something is adding such a file to your project somewhere along the way. It could be a `Directory.Build.props` file, for example, or perhaps a NuGet package that ships its own `.props`/`.targets` file.

It would be useful to see a `.binlog` of your project's design-time build. You can obtain one in a few ways, as described in https://github.com/dotnet/project-system-tools#project-system-tools

Opening such a log with https://msbuildlog.com will allow you to search for the `.csproj.user` file and find out where it's being added. You're welcome to share such a binlog, but beware that it may contain sensitive information from environment variables, product/company details and other personally identifiable information.

> can I safely ignore this?

Yes, but ignoring it will hurt your build performance as the project will always appear as though it needs to be built. You mention you have a huge solution, and incrementality of builds tends to be more important for such solutions.

**Comment by andersforsgren** [comment]
OK I have done some more digging.

I think there are multiple things in play here. But at least one I think is this: there was at least one stray csproj.user file in non-SDK format.  So that gotcha would be this (Could repro reliably inside my sln, but can't produce a cleaner repro outside it, but it does seem like a plausible thing that could cause problems):

Example.csproj (SDK format)
Example.csproj.user (Non-SDK, ToolsVersion="..." etc).

Build project. Works ok. Then delete .csproj.user. After this, the warning "Example.csproj.user does not exist and is required" will show up. Interestingly, there is no mention of the csproj.user anywhere in the binlogs except for where the path to it is tested by Exists(). Removing the \obj or cleaning doesn't help. It does help to change the input items properly e.g. deleting one cs file and building. After that the problem is gone. I guess this is a gotcha that can occur after switching project formats.  

I do have other issues in this solution but they seem to be variations of CopyComplete-timestamps or "Set of project items changed more recently"-issues. I'll see if I can pin those down too, perhaps they are related. If so I'll create a separate issue. Closing this issue. Thanks!
