### ISSUE TITLE
Nuget restore prevents platform specific NetStandard assemblies from building in a multitargeted csproj

### ISSUE THREAD

**Issue by StephenMLucas** [dotnet/project-system#8757]
## Visual Studio Version
17.4.3

## Summary

I'm trying to create multiple platform specific versions of a netstandard assembly by replicating the net5+ pattern and creating custom target frameworks e.g. netstandard2.1-windows. My scenario is for targeting Unity3D, which supports .NetStandard2.1 and WinRT but not CoreCLR yet, but the same pattern would apply to .NET Core 3.1 or other older runtimes that support NetStandard and native platform calls.

Using the BeforeTargetFrameworkInferenceTargets extension point allows me to successfully intercept and set TargetFrameworkIdentifier, TargetFrameworkVersion, TargetPlatformIdentifier and other platform build specific properties and creates the assembly under the custom TFM. However if try and build more than one variation in the same project file, e.g. netstandard2.1-windows and generic netstandard2.1, I get a NuGet restore error that duplicate frameworks were found; 
Error occurred while restoring NuGet packages: Invalid restore input. Duplicate frameworks found: 'netstandard2.1, netstandard2.1'

It's possible I'm approaching this completely wrong but I was hoping to leverage the platform id support present in newer frameworks to avoid having to maintain duplicated csproj files for each platform. Thanks!

## Steps to Reproduce

1. Include the following custom targets in the build via the BeforeTargetFrameworkInferenceTargets extension point;
```
 <Project>
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.1-windows' ">
    <TargetFrameworkIdentifier>.NETStandard</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>2.1</TargetFrameworkVersion>
    <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
    <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
  </PropertyGroup>
   <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1-windows'">
     <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.22621.755" />
   </ItemGroup>
</Project>
```
2.
Build a multi-targeted csproj targeting;
` <TargetFrameworks>netstandard2.1-windows;netstandard2.1</TargetFrameworks>`

## Expected Behavior
NuGet restore completes successfully 

## Actual Behavior
NuGet restore fails with; Invalid restore input. Duplicate frameworks found: 'netstandard2.1, netstandard2.1' 

This is similar to the issues described at; https://github.com/dotnet/runtime/issues/32205

## User Impact
Need to maintain per platform csproj files across the solution to allow for platform specific implementations of the foundational assemblies.

**Comment by drewnoakes** [comment]
Hi @StephenMLucas. This issue relates to NuGet rather than the project system. You can verify that by testing whether `msbuild /t:Restore` (or `dotnet restore`) on the command line produces the same error.

Unfortunately I'm unable to transfer the issue to NuGet's repo as it's in a different GitHub organisation. Could you please open it at https://github.com/nuget/home/issues instead?
