### ISSUE TITLE
Build action for additional files should be called something more than "AdditionalFiles"

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#879]
I raised this in the code review and there was push back on it, but I'm going to raise it again. I think the AdditionalFiles build action should:

1. Follow the casing of the other build actions
2. Be called some more than just AdditionalFiles. Developers who do not work on the Roslyn compiler will not know what this is. If I do a google search for "AdditionalFiles build action", Google work breaks the build action, and nothing in the results points to anything related this what this build action represents.

![image](https://cloud.githubusercontent.com/assets/1103906/20913999/55f7b16e-bbd0-11e6-9a93-3e71aa7e7d21.png)

**Comment by mavasani** [comment]
Note that desktop projects follow the same AdditionalFiles build action convention and so does all Roslyn APIs and command line compiler switches. Additionally, the MSBuild item group is also called AdditionalFiles. I agree we need more documentation for it, but I feel using a different build action name will just make it inconsistent and confusing relative to the rest of the pipeline.

**Comment by mavasani** [comment]
We can fix the casing, but I don't think 2 should be changed.

**Comment by davkean** [comment]
None of my comments have said calling something "different", just adding additional information to it; 
"C# compiler additional files" or "C# analyzer additional files" - don't see how that's more confusing than what it is currently. Searching "AdditionalFiles buildaction" brings up *zero* results related to what this is, searching for "C# analyzer additional files" brings up relevant results.

**Comment by flashfearless** [comment]
I am finding this thread hilarious as I am still trying to find documentation on WTF additionalfiles means as a build action on a console application.

**Comment by davkean** [comment]
@flashfearless How very meta. :)

**Comment by bruceburge** [comment]
Months later, still top google result, for  "visual studio build action "additionalfiles"" is this thread, and I have no idea what it does either.

**Comment by jmarolf** [comment]
@bruceburge the AdditionalFiles build action is a mechanism to pass arbitrary files to an analyzer (extension code that can be loaded by the C# and VB compilers and can report errors and warnings).  For example the public api analyzer (https://github.com/DotNetAnalyzers/PublicApiAnalyzer) looks at a `PublicAPI.Shipped.txt` file that lists all the known public apis for a project.  It will then report errors for new public apis being added. `PublicAPI.Shipped.txt` is passed to the analyzer as an additional file.

**Comment by bruceburge** [comment]
@jmarolf Thanks for the heads up, I have to agree then, that if the files are for being passed to an analyzer, perhaps a better name for them would be "AnalyzerFiles."  Regardless, thanks for your response.

**Comment by figuerres** [comment]
@mavasani 
so your comment from the inside tracks but for a user / developer who does not know the details of MS Build the label is confusing and worthless.

as a developer using VS i am thinking that "AdditionalFIles" might mean that i want the file added to my project when i build it.

i would say that any action that only has to do with  analysing  code be a seperate option form build options.

**Comment by BrainSlugs83** [comment]
+1 please do not call this additional files, it's super confusing -- I totally thought what @figuerres was stating above was the actual case -- but figured I would google it and make sure... heh.  Glad I checked. XD

**Comment by mavasani** [comment]
I have filed a documentation bug https://github.com/MicrosoftDocs/visualstudio-docs/issues/1280 for more discoverable documentation for additional files, based on the current terminology.

I will let @Pilchie @davkean make a call on whether the project system team wants to rename the build action to something else. I think it would be good if we have some way for the users to directly go from a build action in VS to the docs.microsoft.com documentation page for that build action.

**Comment by figuerres** [comment]
also if the item was in a group that was labeled as "Build Analyzer Properties" then the name would be less confusing based on the property group. i think that might be doable w/o a major chnage to the tooling  that uses the property yes ?

**Comment by Pilchie** [comment]
@KathleenDollard - can you help us come up with some good terminology here?

**Comment by misternopps** [comment]
Interest is really compiling on this thread

**Comment by davkean** [comment]
This was renamed to "C# analyzer additional file".
