### ISSUE TITLE
Bypass Host environment variables with launchSettings.json

### ISSUE THREAD

**Issue by Viaun** [dotnet/project-system#8796]
## Summary
Feature:
Extracting `env.SOME_VARIABLE` from developer host (where visual studio is running),
and pass extracted variable into running profile.
```
{
   "profiles": {
      "environmentVariables": {
        "SOME_VARIABLE": env.SOME_VARIABLE
      }
   }
}
```

## User Impact
It allows to avoid  hard-coding of sensitive information into `launchSettings.json` and it will be safe to add `launchSettings.json` into source control.
For example:
When develop apps for AWS there is access keys that should be passed for running application.
Currently you need to hard-code access key within `launchSettings.json` (when running on docker or WSL).
Instead it would be convenient to declare within `launchSettings.json` which environment variable should be bypassed in to running application (that allows to avoid hard-coded credentials).
Than `launchSettings.json` may be commited in to source control (that is not possible with hard-coded sensitive data).

**Comment by adamint** [comment]
Hi @Viaun, system environment variables should already be available there, as a standard MSBuild property. See more: https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-use-environment-variables-in-a-build?view=vs-2022#reference-environment-variables

**Comment by adamint** [comment]
Could you share more about what you see as the benefit of this feature?

**Comment by drewnoakes** [comment]
@Viaun I think you can already do what you're asking.

I set an environment variable on my machine `MY_GLOBAL_SECRET = 12345` then launch VS.

![image](https://user-images.githubusercontent.com/350947/213947979-03327a3a-b4b2-45fc-a9ea-dda87ce16095.png)

With these launch settings, I apply the value of the machine's environment variable `MY_GLOBAL_SECRET` to a local var for the debugged process `MY_LOCAL_SECRET` with this:

```json
{
  "profiles": {
    "ConsoleApp10": {
      "commandName": "Project",
      "environmentVariables": {
        "MY_LOCAL_SECRET": "$(MY_GLOBAL_SECRET)"
      }
    }
  }
}
```

Then with code:

```c
Console.WriteLine(Environment.GetEnvironmentVariable("MY_LOCAL_SECRET"));
```

I see output:

![image](https://user-images.githubusercontent.com/350947/213947838-5b65864b-ac24-43d8-abe7-7936696b49ec.png)

**Comment by Viaun** [comment]
> @Viaun I think you can already do what you're asking.
> 
> I set an environment variable on my machine `MY_GLOBAL_SECRET = 12345` then launch VS.
> 
> ![image](https://user-images.githubusercontent.com/350947/213947979-03327a3a-b4b2-45fc-a9ea-dda87ce16095.png)
> 
> With these launch settings, I apply the value of the machine's environment variable `MY_GLOBAL_SECRET` to a local var for the debugged process `MY_LOCAL_SECRET` with this:
> 
> ```json
> {
>   "profiles": {
>     "ConsoleApp10": {
>       "commandName": "Project",
>       "environmentVariables": {
>         "MY_LOCAL_SECRET": "$(MY_GLOBAL_SECRET)"
>       }
>     }
>   }
> }
> ```
> 
> Then with code:
> 
> ```c
> Console.WriteLine(Environment.GetEnvironmentVariable("MY_LOCAL_SECRET"));
> ```
> 
> I see output:
> 
> ![image](https://user-images.githubusercontent.com/350947/213947838-5b65864b-ac24-43d8-abe7-7936696b49ec.png)

I tried to do so with Docker profile command, and it just passed text value "$(MY_GLOBAL_SECRET)"

**Comment by drewnoakes** [comment]
Can you share what's in your `launchSettings.json` file please? You can change any words you don't want to share.

**Comment by adamint** [comment]
Closing as not reproducible. Please update if you have steps to reproduce.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/20359921/222550357-1e9e3550-c534-48a2-8be4-3d099edd91fb.png"><img width="246" alt="image" src="https://user-images.githubusercontent.com/20359921/222550298-d56f6216-6e6a-45d2-85cd-a481c49f30aa.png">
