### ISSUE TITLE
Project System: Analyzer dependencies in project tree

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#88]
_From @davkean on March 22, 2016 22:15_

Tracking the work to add Analyzer dependencies in the project tree:

![image](https://cloud.githubusercontent.com/assets/1103906/13969571/e6a9d0cc-f040-11e5-9b4c-8519909892a6.png)

_Copied from original issue: dotnet/roslyn#9981_

**Comment by srivatsn** [comment]
Analyzers assemblies show up in the project tree now but the remaining work is to make the individual rules show up as well.

**Comment by tmeschter** [comment]
Issue #1634 will need to be fixed before I can make much progress on this.

**Comment by srivatsn** [comment]
The analyzer nodes now show the individual diagnostics
