### ISSUE TITLE
MSBUILDDEBUGPATH does not have to exist

### ISSUE THREAD

**Issue by Forgind** [dotnet/project-system#8857]
This is extremely minor, but I happened to notice your documentation [here](https://github.com/dotnet/project-system/blob/main/docs/repo/debugging/design-time-builds.md)
says to "Make sure the MSBUILDDEBUGPATH exists on your machine." That's a bit misleading; MSBuild will make the folder for you if it doesn't exist, as long as it has write permissions to do so.

**Comment by MiYanni** [comment]
@Forgind That line was applicable based on this issue: https://github.com/dotnet/msbuild/issues/7241
It may no longer be applicable, but it is fairly harmless to keep the line there since it is only informing them to 'check' that the value is present.
