### ISSUE TITLE
Deploy Extension while building solution in Jenkins

### ISSUE THREAD

**Issue by basoundr** [dotnet/project-system#888]
Changes were made to not deploy extensions in PR #882 since RC2 images were required for #860. Once we have RC2 images in Jenkins, revert this change

**Comment by basoundr** [comment]
Fixed #882

**Comment by 333fred** [comment]
Reverted with https://github.com/dotnet/roslyn-project-system/pull/1049.

**Comment by 333fred** [comment]
Reverted because the Jenkins machines are having licensing issues currently, causing a pop-up to occur and extension deploy to time out.

**Comment by basoundr** [comment]
Re-evaluating this issue. We don't really need to deploy the extensions while building the project in Jenkins for unit tests. We will only need it when running VSI tests, which will require us to deploy the extensions. Hence I think we can close this issue. @srivatsn , your thoughts?

**Comment by srivatsn** [comment]
It'll still be good to do that so that we'll know if deploying extensions broke.

**Comment by Pilchie** [comment]
Closing, since most `dotnet` projects don't deploy during build.
