### ISSUE TITLE
Missing localization in Property Pages UI

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#8894]
I noticed there are still some bugs around the localization of the UI 😞.

![image](https://user-images.githubusercontent.com/8518253/222610975-207e18ee-c124-484f-a1bc-e0a57157c6ee.png)

![image](https://user-images.githubusercontent.com/8518253/222611201-6e2337a1-bbbe-41b2-a7b0-7d98e7f80800.png)

I'll look into them, try to fix it and look at our unit tests to ensure they are detecting this type of bugs.

**Comment by melytc** [comment]
Note: the `ApplicationPropertyPage.CSharp` and `ApplicationPropertyPage.VisualBasic` both have a category with the same id (`Resource`) but different display name and description, that might be causing a problem.

**Comment by melytc** [comment]
First screenshot fixed by #8900.

**Comment by melytc** [comment]
@adamint, the second screenshot shows the unlocalized subheadings of the `DefineConstants` property. I suspect this is something particular with the `MultiStringSelector` editor, as we don't have the actual string in our loc files.

**Comment by adamint** [comment]
I had thought this was fixed by CPS.... let's create a ticket and mention Adrian, b/c I think this was a CPS issue with their translation pipeline

**Comment by melytc** [comment]
sounds good, please add the link to the ticket here, to make sure we track the work.

**Comment by MiYanni** [comment]
Ticket: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1761539
