### ISSUE TITLE
Special file provider defaults to the project root, despite if they are created under AppDesigner folder

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#893]
Our special file provider src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\SpecialFileProviders\AbstractSpecialFileProvider.cs defaults to the project root when special file doesn't exist and asked not to create it, regardless of the file is supposed to be created under AppDesigner folder by default.

**Comment by srivatsn** [comment]
I believe that's what csproj does - not sure if there's any ramifications to doing otherwise.

**Comment by davkean** [comment]
I stepped through this and confirmed this behavior, but it looks like wrong on both sides. It looks this works by change with the current design of the settings/resources editors - it's actually [using the resulting path](https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb#L767) expecting it to be correct, it just happens to throw away the full path and just using the file name.

**Comment by davkean** [comment]
This was fixed in https://github.com/dotnet/project-system/pull/5475, we chose to deviate from legacy here.
