### ISSUE TITLE
Warning/Notice when StartArguments interfere with launchSettings.json

### ISSUE THREAD

**Issue by apilosofms** [dotnet/project-system#8937]
## Summary
It's possible for a `<project>.csproj.user` file to contain a `<StartArguments />` property which is passed as a commandline arg to the program being debugged.

Unfortunately, you can also have a `launchSettings.json` which contains some `commandLineArgs` settings, and the two will be secretly merged at debug time.

Would be great if the UI somehow communicated this, as an FYI or a warning for example.

## User Impact
I spent a bunch of time trying to figure out why my debug session was passing two arguments when I only asked for one. The UI (and solution explorer) only reveals the `launchSettings.json` settings, so it was quite confusing.
First I suspected my code, then the command line parsing lib, then ended up working through various cases in VS.
The only way I found it was by doing a file-system string search for the offending argument, which happened to reveal the `.user` file.

**Comment by tmeschter** [comment]
@apilosofms Did you mean launchSettings.json instead of localsettings.json?

**Comment by drewnoakes** [comment]
@tmeschter yes that's right. Avi reported this elsewhere and I requested he file this issue.

The pain point it:
- Change arguments in Launch Profile UI
- Run app and those arguments aren't picked up
- Be confused

We could add some kind of information/banner/warning in the launch profile UI that lets the user know that they have a `StartArguments` property defined in the project that will override whatever they have specified there, potentially with a button to remove/convert that value. Our visibility conditions and link actions should be enough to provide a better experience here for users.

**Comment by drewnoakes** [comment]
An attempt at addressing this was done in #8494. See also AB#1274456.

**Comment by drewnoakes** [comment]
A warning was added to the launch profiles UI in https://github.com/dotnet/project-system/pull/9074
