### ISSUE TITLE
Enable XP visual styles property is not working for WinForms .Net Core VB project.

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#8938]
Related to https://github.com/microsoft/winforms-designer/issues/3012.

When setting the startup object from `Sub Main` to `Form1`, the enable XP visual styles property is not correctly rendered.

## Minimal Reproduction Scenario
1. Create a WinForms .Net Core VB application with added several controls
2. Go to app's Properties ->Application page
3. Set Startup object from 'Sub main' to Form1 and ensure 'Enable XP visual styles' is checked
4. Save application, build and run

## Current behavior
 
Form1:
![image](https://user-images.githubusercontent.com/8518253/228051787-a02eb0dd-9f4a-49c8-bc91-9f0166124124.png)

Sub Main:
![image](https://user-images.githubusercontent.com/8518253/228051882-d3aa0e89-34ef-4593-a32c-88834365ffa0.png)

## Expected behavior
Form1 should be displayed as V6 mode, same as the behavior of 'Sub main'.

## Notes
This has been an issue since the legacy properties pages (the issue in the WinForms repo was created back in 2021).

**Comment by tmeschter** [comment]
Triage: Investigate in 17.7 and then re-evaluate.

**Comment by melytc** [comment]
This has been fixed in #9300 🙂
