### ISSUE TITLE
Dependencies tree refactor 

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#8940]
## Summary

This is a placeholder task to refactor the current dependency tree implementation within .NET Project System. This would be a prerequisite to [AB#1503715](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1503715) and [AB#1781382](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1781382)

## User Impact
This is an effort to make the make the dependencies tree more maintainable and reliable for supporting multi targeting and configuration switch scenarios in terms of UI display. Documentation will be added as a part of the refactor

**Comment by drewnoakes** [comment]
Issues I'm hoping to address as part of this work:

Core fixes:

- [ ] #6183
- [ ] #3642
- [ ] #8946
- [ ] #8947
- [ ] #5519
- [ ] #5045
- [ ] #5044
- [ ] #2795

Probable fixes:

- [ ] #2618
- [ ] #8949
- [ ] #6832
- [ ] #6820
- [ ] #6203
- [ ] #3321
- [ ] #2707
- [ ] #2618
- [ ] #2524

Stretch goals (even if not met, this work contributes to these):

- [ ] #6668
- [ ] #6594
- [ ] #3426
- [ ] #2617
- [ ] #2525

**Comment by drewnoakes** [comment]
PR is up for this work.

An additional PR against NuGet.Client fixes a few more issues: https://github.com/NuGet/NuGet.Client/pull/5146
