### ISSUE TITLE
Update Tools | Options pages to use Unified Settings model

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system#8969]
## Summary

Update our two Tools | Options pages to use the new Unified Settings model. This includes:

- Projects and Solutions | Performance
- Projects and Solutions | SDK-Style Projects

**Comment by drewnoakes** [comment]
Potentially relates to #8979.

**Comment by kvenkatrajan** [comment]
Reverted back by : [#9129](https://github.com/dotnet/project-system/pull/9129)
CC: @adamint 

Moving to 17.8

**Comment by kvenkatrajan** [comment]
Added back in by : [#9155](https://github.com/dotnet/project-system/pull/9155)
