### ISSUE TITLE
Remove the "Performance" settings page

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#8979]
![image](https://user-images.githubusercontent.com/350947/231905281-46eae9b9-377c-4b91-9ef7-9661f2759393.png)

This option doesn't do anything.

**Comment by drewnoakes** [comment]
This may reduce the amount of work required for #8969.

**Comment by drewnoakes** [comment]
https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/472611

**Comment by melytc** [comment]
I think this is done, but I'll let you @drewnoakes close this if so 🙂

**Comment by drewnoakes** [comment]
Oh yes, this was done. Thanks!
