### ISSUE TITLE
Include ExcludedAssetsFlow in the NuGet restore nomination

### ISSUE THREAD

**Issue by erdembayar** [dotnet/project-system#8989]
Needed for https://github.com/NuGet/NuGet.Client/pull/4976, spec is [here](https://github.com/NuGet/Home/blob/1af7f2779f52f1f22e4858bdeaa25f9623cf94c8/proposed/2022/PrivateAssetIndepdentFromExcludeAsset.md).

We're going to add new optional metadata `ExcludedAssetsFlow`, allowed values are case insensitive `true`, `false`.

For example:
Not included: `<PackageReference Include="PackageA" />`
Included set false:`<PackageReference Include="PackageA" ExcludedAssetsFlow="false"/>`
Included set true: `<PackageReference Include="PackageA" PrivateAssets="Runtime;Compile" ExcludedAssetsFlow="true" IncludeAssets = "none"/>`

Technically first 2 are same thing, but for 3rd case we do additional calculation.

**Comment by drewnoakes** [comment]
The `PackageReference` item metadata we pass to NuGet for nomination are defined in schema [`CollectedPackageReference.xaml`](https://github.com/dotnet/project-system/blob/e062b62bd0a451620ee362b677ba4a48f05d8c60/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CollectedPackageReference.xaml).

You need to add a `BoolProperty` here for your new `ExcludedAssetsFlow` property.

**Comment by drewnoakes** [comment]
@erdembayar you closed your PR #8990 for this. Do you still need this issue? It's currently in 17.8 which is approaching M2 mode, so any change here would need to happen very soon.

**Comment by erdembayar** [comment]
Not needed for now.
