### ISSUE TITLE
Access to 'launchSettings.json' Properties in MSBuild Project Files

### ISSUE THREAD

**Issue by ACGNnsj** [dotnet/project-system#9003]
## Summary
Sometimes, I need to add extra properties or targets when building a unpackaged app. Is there any way to read properties in 'launchSettings.json' like 'commandName'? If so, I don't have to manually maintain a custom property to identify the packaging strategy.

**Comment by drewnoakes** [comment]
Can you describe more about what you're trying to achieve?

Note that launch and build are separate activities. There's no visibility into the launch profile from within the build action. Indeed, a launch can occur without a build occurring if the project is up to date, even if you change the active launch profile.

**Comment by ACGNnsj** [comment]
> 
Alright, it seems impossible then.
Thanks for your detailed explanations!
