### ISSUE TITLE
Transitive dependency items not attached for all target frameworks when multi-targeting

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#9006]
When a project is multi-targeting, the code in NuGet.Client that attaches transitive dependency information to dependency nodes must determine which target each item belongs to.

This doesn't work correctly for certain target framework kinds today.

Given:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net481;netcoreapp3.1;netstandard2.1;net5.0;net6.0;net7.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MetadataExtractor" Version="2.8.0" />
  </ItemGroup>

</Project>
```

We see:

![image](https://github.com/dotnet/project-system/assets/350947/ec4cb23f-a4bf-4c3a-bf80-44fb7122bf27)

Only `net5.0`, `net6.0` and `net7.0` have children attached. The others are not expandable, indicating attachments failed.

The reason for this is inconsistent treatment of the target identifier in the `project.assets.json` file:

![image](https://github.com/dotnet/project-system/assets/350947/c2a6bd5b-eb68-445d-9770-1c84ec63bd1a)

These are two different kinds of values, which makes this mapping difficult. Perhaps we need to store both the alias and the TFM on the target node, so the NuGet code can try and find either. Or NuGet could settle on a single identifier in this file. Or something else.

The JSON file does have, under `project.restore`:

![image](https://github.com/dotnet/project-system/assets/350947/57a34c28-8f84-473f-ad79-7e212770a56c)

So perhaps it could map these back, however they appear in a different order, and I can't see any other way in the data model to do that mapping such that we have only a single kind of identifier.

**Comment by RussKie** [comment]
Is NS2.1 behaving the same as NS2.0 (in this context)?

**Comment by RussKie** [comment]
I ran in to this issue yesterday with .NET Core 3.1:
![image](https://github.com/dotnet/project-system/assets/4403806/31a48a4c-bbac-413e-9671-6e6c0924acdc)

**Comment by drewnoakes** [comment]
This was already being tracked in #6832. Moving this analysis there and closing this.
