### ISSUE TITLE
Launch profile editor should select the current profile when opened

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#9015]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/t/Very-annoying-that-changing-launch-profi/1631632). Please vote and comment there to make sure your voice is heard._

---

In Visual Studio 2022 if you want to edit the CURRENT launch profile it opens the Launch Profiles but always shows the first one in the list and not the current one. Very annoying ...

**Comment by MiYanni** [comment]
This was fixed previously in a duplicate feedback ticket.
