### ISSUE TITLE
Error "Resources.resx" is not a valid resource type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#9016]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-Resourcesresx-is-not-a-valid-re/1640078). Please vote and comment there to make sure your voice is heard._

---
According my exploration this error is displayed when resources.resx is in modified state; when the file is saved is all OK. Error occurs after clicking on Image property.

---
#### Feedback Bot on 1/18/2022, 03:15 AM: 

(private comment, text removed)
#### Peng Ge [MSFT] on 1/18/2022, 07:26 PM: 

(private comment, text removed)
#### pirkljosef on 1/18/2022, 11:43 PM: 

(private comment, text removed)
#### Peng Ge [MSFT] on 1/21/2022, 01:04 AM: 

(private comment, text removed)
#### Feedback Bot on 5/7/2022, 02:07 AM: 

(private comment, text removed)
#### pirkljosef on 5/15/2022, 10:40 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by drewnoakes** [comment]
I believe this no longer reproduces. I followed the (private) steps described by the customer and the error did not occur.

The customer also mentioned that this no longer repros for them.

**Comment by MiYanni** [comment]
No longer an issue.
