### ISSUE TITLE
Downgrading .NET Framework

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#9019]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/t/Downgrading-NET-Framework/1487038). Please vote and comment there to make sure your voice is heard._

---
_[severity:It's more difficult to complete my work] [regression] [worked-in:Visual Studio 2019 Community]_

If you create a Project with the Preview .NET 6 Framework selected (which doesnt even select you another one) and then you downgrade you .NET Framework in the Project Settings (in my Example to 4.7.2, due to the Excel Interop Library not working with the newer one), You cant compile your Project anymore, due to a error with a Nullable not being found.

### **FIX:**

Navigate to your Project-Folder, locate the .csproj-File, open it with a code/text editing software (like for example Notepad++) and delete the <Nullable> Parameter

![image](https://github.com/dotnet/project-system/assets/350947/7272e864-d836-4cc2-9b94-8e29ad0263fd)

It seems like, this is a feature that is new, and it doesnt remove itself from the file when you downgrade.

If you now restart Visual Studio you can compile and run your code no Problem

**Comment by drewnoakes** [comment]
We don't officially support targeting .NET Framework with SDK style projects. That's why you cannot do this in the UI directly.

That said, it does generally work quite well, and we use it in this repo ourselves.

I don't think there's any action we would take here, but let's discuss during triage.

**Comment by MiYanni** [comment]
Not a scenario that we support.
