### ISSUE TITLE
Properties window order change as one selects more files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#9021]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/t/Properties-window-order-change-as-one-se/1501511). Please vote and comment there to make sure your voice is heard._

---

_[severity:It bothers me. A fix would be nice]_

The order of the Properties listed changes as one selects more than one item within the Solution Explorer.
The "Custom Tool" entry swaps places with the "Custom Tool Namespace" entry, as shown in the attached PNG files.
This can be a cause of user error.

**Comment by MiYanni** [comment]
CPS issue. Reopening feedback.
