### ISSUE TITLE
Setup Debug Properties - Launch Profiles should have an "Ok" button to accept changes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#9026]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/t/Setup-Debug-Properties---Launch-Profiles/1600913). Please vote and comment there to make sure your voice is heard._

---
The Launch Profiles window doesn't have an "ok" button to accept changes.  It forces users to click the "x" at the top right corner which typically indicates that you want to undo the changes that you've made.

From a UX perspective, this is confusing.

![image](https://github.com/dotnet/project-system/assets/350947/cff4f776-b866-4048-89b5-fbdefa3f84a3)

**Comment by drewnoakes** [comment]
The design of the launch profiles UI, just like that of the Project Properties UI, is to apply changes immediately. There is no OK or Cancel.

I suspect the reason this feels wrong for launch profiles is that the UI is modal, and modal UIs tend to support aborting without committing changes.

**Comment by drewnoakes** [comment]
We have a work item to make the UI non-modal, which may help here.

**Comment by drewnoakes** [comment]
I think this is close enough in spirit to #7390 that we can close this and simplify our backlog. @edwardskrod let me know if you disagree. Thanks!

**Comment by edwardskrod** [comment]
[like]  Edward Skrod reacted to your message:
________________________________
