### ISSUE TITLE
VS 2022 (but not 2019) hangs if <TargetFrameworks> is defined in an include and overridden

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/project-system#9028]
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-but-not-2019-hangs-if--is-defi/1605322). Please vote and comment there to make sure your voice is heard._

---

_[severity:It's more difficult to complete my work]_

I encountered this by happenstance while adding a net6.0 build to a project (moving from 1 TFM to several). Since this is OSS, there's a public commit here illustrating (resolving) the issue: https://github.com/NickCraver/azure-webjobs-sdk/commit/eed88b84b05936d6438d5d57f9f958f032dd3bbe

If you pull this branch/commit, VS 2022 will be happy. However, if you pull 1 commit back (https://github.com/NickCraver/azure-webjobs-sdk/commit/2f6bf938480999430f9ec533197502a32b1ce524 - totally unrelated change), you'll see VS 2022 will load 17/17 project and stall (I'm attaching a process dump from when it happened - I can reproduce this on every machine I have).

Notes: 
- I thought this was `<TargetFrameworks>` in a base `.props` file and `<TargetFramework>` in a specific project resulting on both, but after switching everything inheriting that `.props` to `<TargetFrameworks>` the issue persisted. 
- This issue doesn't happen in VS 2019 (also confirmed by another party) and seems to be specific to VS 2022.
- Most of the attachments here are from _the running instance_ (post-fix) - I could not figure out how to attach to the hung VS in 2022, the feedback tool immediately launches the web version.

**Comment by haileymck** [comment]
fixed in https://github.com/dotnet/project-system/pull/9256
