### ISSUE TITLE
VS skip building

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/project-system#9072]
## Visual Studio Version
17.6.2

## Summary
[test1.zip](https://github.com/dotnet/project-system/files/11668821/test1.zip)
VS doesn't build this solution(Ensure the platform is Any CPU):
![image](https://github.com/dotnet/project-system/assets/2529999/26efde5d-84ef-4295-915c-6e3521d9f45e)
When I click `Configuration Manager...`, then close the opened winow, vs will chage .sln file, and then can build it:
![image](https://github.com/dotnet/project-system/assets/2529999/7514dafc-5da3-4f9e-b728-8fd8249d7d7f)

Is there any error in the original .sln file? But msbuild can build it.

**Comment by melytc** [comment]
Unfortunately, it seems like this bug is not part of this repo; could you please open a feedback ticket in our [Developer Community feedback website](https://developercommunity.visualstudio.com/home)? That way we can route it to the correct team. Thanks!
