### ISSUE TITLE
"Upgrade this project to C# version" refactoring generates unnecessary conditions in the project file

### ISSUE THREAD

**Issue by davidfowl** [dotnet/project-system#9073]
## Visual Studio Version

Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview
Version 17.7.0 Preview 2.0 [33708.523.main]

## Summary

Whenever I use this amazing feature:

![image](https://github.com/dotnet/project-system/assets/95136/f23b133f-c8b7-4d7c-a293-46d0735682e6)

## Expected Behavior

![image](https://github.com/dotnet/project-system/assets/95136/35d75079-0582-4823-9d35-1d220c86d679)

## Actual Behavior

![image](https://github.com/dotnet/project-system/assets/95136/a04ffe85-5e57-4abc-a866-0de2547992d4)

## User Impact

I need to fix up the csproj everytime.

**Comment by drewnoakes** [comment]
Notes from initial investigation.

It seems like our rule files are configured to set `LangVersion` without a configuration condition, so I wonder how Roslyn is setting this property in the project. I tested adding `HasConfigurationCondition="false"` to the build page, but it had no effect.

That codefix is defined in Roslyn and performs the update here: https://github.com/dotnet/roslyn/blob/91afe0903adf80236bb7ccffc042a16f53520877/src/Analyzers/CSharp/CodeFixes/UpgradeProject/CSharpUpgradeProjectCodeFixProvider.cs#L98

We need to understand how Roslyn is calling back into the project system to set this property. I asked Dave and he said they're likely using either `IVsBuildPropertyStorage` or DTE's configuration object, both of which will be coming through CPS.

**Comment by drewnoakes** [comment]
Looks like Roslyn might be modifying the project via this code https://github.com/dotnet/roslyn/blob/087a3170022c3d3fd6b679d4f315ba4d6f86f944/src/VisualStudio/Core/Def/Utilities/ProjectPropertyStorage.cs#L17

**Comment by drewnoakes** [comment]
Fix in https://github.com/dotnet/project-system/pull/9075

**Comment by drewnoakes** [comment]
The CPS change was merged which will address this. The fix should insert to int.main over the next few days and be in public preview soon.
