### ISSUE TITLE
UpToDateCheck ignores files marked with CopyToOutputDirectory if they are in the nuget package folder

### ISSUE THREAD

**Issue by MathieuPilotInvivoo** [dotnet/project-system#9095]
## Visual Studio Version
17.6

## Summary
We reference some nuget packages that contain files we want to copy to the output directory of our project.
To this end we added those files manually in the csproj with CopyToOutputDirectory and PreserveNewest.

When rebuilding, everything works fine and the files are copied to the output.
But if the input or output files are modified and we launch a build, the project is considered up to date, project is not built. Therefore the ouptut files are outdated.

This is a regression as it worked as expected with Visual Studio 2019 V16.11
Also note that there is no issue for files that are not inside the nuget packages' folder.

I attached the sample that can be used with VS 17.6 or VS16.11

## Steps to Reproduce

1. Create a new visual studio project and add a reference to nuget package System.Text.Json
2. Add the file Readme.txt from System.Text.Json to the output of the project by adding those lines to the csproj file
The csproj should be:
	<Project Sdk="Microsoft.NET.Sdk">
		<PropertyGroup>
			<OutputType>Exe</OutputType>
			<TargetFramework>net5.0</TargetFramework>
		</PropertyGroup>

		<ItemGroup>
			<PackageReference Include="System.Text.Json" Version="7.0.3" GeneratePathProperty="True" />
		</ItemGroup>

		<ItemGroup>
			<None Include="$(Pkgsystem_text_json)\LICENSE.TXT">
				<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			</None>
		</ItemGroup>
	</Project>

4. Build the project. LICENSE.TXT is copied correctly to the output directory
5. Manually delete the file LICENSE.TXT from the output directory
6. Build the project.
7. Project is considered up to date even though the file LICENSE.TXT is NOT in the output.
UpToDate Log:
1>FastUpToDate: Project is up-to-date. (UpToDateCheckForNugetFiles)
1>FastUpToDate: Up-to-date check completed in 1,0 ms (UpToDateCheckForNugetFiles)
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

## Expected Behavior

Files that are marked explicitely as CopyToOutputDirectory should always be copied to the output directory even if they are inside the nuget packages' folder.

## Actual Behavior

Build is skipped and the output is not up to date.

## User Impact

All developpers are forced to use rebuild instead of build by fear some of the files expected in the output might be missing or be outdated. Since the full rebuild takes about 8 minutes and incremental build only a few seconds, it's quite a big loss of time at the end of the day.
[UpToDateCheckForNugetFiles.zip](https://github.com/dotnet/project-system/files/11772939/UpToDateCheckForNugetFiles.zip)

**Comment by drewnoakes** [comment]
Thanks for clear and thorough issue.

The fast up-to-date check intentionally ignores files from certain paths for performance reasons. It's generally assumed that items in `Program Files`, the NuGet cache, and other similar locations do not change over time.

It seems like items with `CopyToOutputDirectory` metadata should not be excluded.

**Comment by drewnoakes** [comment]
> It seems like items with `CopyToOutputDirectory` metadata should not be excluded.

Thinking about this some more, I don't think this statement (of mine) really applies.

In your scenario you're modifying files that are generally not intended to be modified. For that reason, VS doesn't check them for changes on every build of every project, and that saves a lot of time.

The NuGet cache is supposed to be immutable and unchanging over time. It sounds like you're explicitly modifying its contents and expecting VS to react to those changes.

Can you elaborate on your scenario? My best guess is that you're manually overwriting package contents during build somehow. Maybe there's a better way to do what you're after.

**Comment by MathieuPilotInvivoo** [comment]
That's a good point. We are not modifying any package content during the build.
I believe this was causing an issue for us because of my other case #9096. What probably happened is that we do this:
1) Update nuget packages in csproj manually
2) Do not save the csproj and launch the build directly
3) Build is using wrong version of packages
4) Building again, the project is up to date and build does nothing. The files from the new nuget package are different from the ones in the output but it's because of step 3)

I'll close this case then as I don't have any realistic scenario for it.
