### ISSUE TITLE
Create Dataflow documentation

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#9099]
Dataflow is one of the most daunting areas for contributors to the project system. We have various bits of documentation spread across several repositories but most of it is fairly advanced or provided without enough context to know whether it's relevant to what you're trying to do. We should have a single document that walks the reader through all the relevant concepts, building things up in a thought-out fashion, that is both readable top-to-bottom and as a reference for specific topics.

Here's an initial proposal for such a document's table of contents.

- Dataflow basics
  - What a Dataflow graph is
  - Snapshots
  - Threading and asynchrony
  - Block types
    - Source blocks
    - Target blocks
    - Action blocks
    - Transform blocks
    - TransformMany blocks
    - Broadcast blocks
    - Buffer blocks
  - Linking blocks
  - Completing and faulting blocks
  - Stateful / stateless blocks

- Dataflow in CPS
  - Slim blocks
  - Versions and versioned values
  - SyncLink
  - Project data subscriptions (IProjectSubscriptionService), snapshots and deltas, common sources
  - Exporting and composing data sources via MEF
  - ProjectValueDataSource blocks (as original data sources)
  - Chained ProjectValueDataSource blocks (as derived data sources)
  - UnwrapChainedProjectValueDataSource
  - ConfiguredProjectDataSourceJoinBlock
  - Working with slices
  - Avoiding hangs (JoinUpstreamDataSources)
  - Dataflow source registries
  - GetLatestVersionAsync / GetSpecificVersionAsync
  - Mixing dataflow and live project data
  - Registering blocks for fault handling
  - Skipping intermediate input/output data
  - Operation progress and Dataflow
  - Diagnosing issues / `!dumpdf`

This content should likely be hosted in the VSProjectSystem repo rather than here. It's not specific to the .NET Project System. Though those documents would likely cite this repo for real world examples.

**Comment by drewnoakes** [comment]
Gathering some existing resources:

- https://learn.microsoft.com/en-us/dotnet/standard/parallel-programming/dataflow-task-parallel-library
- https://github.com/microsoft/VSProjectSystem/blob/master/doc/automation/subscribe_to_project_data.md
- https://github.com/microsoft/VSProjectSystem/blob/master/doc/extensibility/dataflow_sources.md
- https://github.com/microsoft/VSProjectSystem/blob/master/doc/extensibility/dataflow_example.md
- https://github.com/microsoft/VSProjectSystem/blob/master/doc/extensibility/dataflow_best_practices.md
- https://github.com/microsoft/VSProjectSystem/blob/master/doc/overview/dataflow_in_CPS.md
- https://github.com/dotnet/project-system/blob/main/docs/repo/coding-conventions.md#data
- https://github.com/dotnet/project-system/blob/main/docs/repo/joy-of-dataflow.md

@lifengl produced an internal video/deck on the topic with loads of great content. We should make sure that's all covered in the doc.

**Comment by tmeschter** [comment]
I think completion, faulting, and completion propagation _within_ CPS could get its own section.

**Comment by tmeschter** [comment]
Maybe also a section on proper handling of all the `IDisposable`s. Though I could also see that information spread out through all the other sections.

**Comment by tmeschter** [comment]
Possibly also a section on capturing (or _not_ capturing) the execution context in dataflow blocks.

**Comment by drewnoakes** [comment]
> Possibly also a section on capturing (or _not_ capturing) the execution context in dataflow blocks.

We discussed this in today's sync meeting and concluded that 1) there's a lot of very technical information to write about this and 2) the majority of code would not need to do this.

**Comment by drewnoakes** [comment]
Draft PR with some initial docs is available at https://github.com/microsoft/VSProjectSystem/pull/367.

**Comment by drewnoakes** [comment]
That PR is now up for review.

**Comment by drewnoakes** [comment]
Documentation merged: https://github.com/microsoft/VSProjectSystem/blob/master/doc/overview/dataflow.md
