### ISSUE TITLE
NuGet Package Status Indicators

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/project-system#9105]
## Summary

**Background**

Goal of this feature: Contribute to the security and reliability of the NuGet ecosystem by having a way to provide discoverable, timely, and actionable notifications to users regarding the health of their NuGet packages.

Initial Spec: https://github.com/NuGet/Home/pull/11838 

**Experience Requirements**

- Notification: icons which will surface on package nodes in the solution explorer to indicate various issues with the package (deprecated package, vulnerability, update needed)
- Details/Information: 
   1. Actionable warning notification
   2. Info tip or Inline error message text under the node in question

- Action: There must be a way to interact with the warning to take you to manage package details. Right-click to open view of package in question in NuGet Package Manager
- Opt-out: A way for users to opt out of the feature at an IDE level

More information at: [AB#1503715](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1503715)

## User Impact
By surfacing vulnerability information to the Solution Explorer we are making it super easy for users to notice and fix issues with their packages.

**Comment by drewnoakes** [comment]
The .NET Project System team's work on this is complete. The NuGet team is looking at adding diagnostics on the top-level items (in their MSBuild targets), but otherwise this work is done.
