### ISSUE TITLE
Option to always disable C# NRTs

### ISSUE THREAD

**Issue by MV10** [dotnet/project-system#9120]
Similar to the way we can permanently disable top-level statements, I would like to see a simple checkbox that always sets csproj `<nullable>` to `disable`. 

I know it's a long-shot request (I participated in the NRT holy-wars in the csharplang discussion, and I'm not interested in or trying to rehash any of that here), but I don't personally know a single professional dev who likes NRTs, and I know plenty who agree an "off switch" would be a nice-to-have feature when I mention the idea.

Ideally I'd like to see it presented the same way the top-level statement switch is shown, but even buried somewhere in the Options dialog would be appreciated, I'll only set it once.

**Comment by drewnoakes** [comment]
It sounds like you want this on the template wizard. I don't think this is a project system request.

Could you file a feedback ticket so we can route this to the correct team internally? If there's an existing ticket you can vote on it to increase the chance it gets addressed.

**Comment by MV10** [comment]
Yeah, I'll give that a shot, thanks. (Sadly that's "where bug reports and ideas go to die" but I understand your position.) Thanks.
