### ISSUE TITLE
View Code button missing on Solution Explorer toolbar for WinForms and WPF apps

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/project-system#9128]
## Minimal Reproduction Scenario

1. Create a Winforms .Net Core application.
2. In solution Explorer, focus on Form1.cs node, then observe the toolbar items at the top of solution explorer window.

## Current Behavior
Missing "View Code" button in Solution Explorer
![Actual](https://github.com/dotnet/project-system/assets/45864985/3cd83107-eff7-40d8-be95-19f848000b4e)

## Expected Behavior
View Code button is there, like the result of focusing on .Net framework form
![Expected](https://github.com/dotnet/project-system/assets/45864985/c73cca90-6453-487d-afcd-f8ff4961f997)

## Test Environment
17.7.0 Preview 3.0 [33824.57.main]

## Have you experienced this same issue with .NET Framework designer?
No

## Have you experienced this same issue with previous previews of VisualStudio?
Yes, 17.3.6 have this issue

## More Info

1. .NET Framework project does not repro this issue.
2. This issue occurs in the .NET Core WPF project too.

**Comment by drewnoakes** [comment]
This issue was created in response to https://developercommunity.visualstudio.com/t/View-Code-button-missing-for-Net60-For/10224825

**Comment by drewnoakes** [comment]
Previously discussed in https://github.com/dotnet/project-system/issues/7765

This issue does not belong in this repo. It should be moved to CPS. I'll close this, reopen the feedback ticket and move it over to that team.
