### ISSUE TITLE
Build more complete support to install/uninstall nuget packages by right clicking on nodes in the solution explorer.

### ISSUE THREAD

**Issue by rrelyea** [dotnet/project-system#914]
Internal bug [AB#283541](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/283541) covers this request.

Repro Steps:

1. create asp.net core app 
2. when we uninstall any nuget package, we can't uninstall another as because the 'Uninstall Package' option is not present

![image](https://user-images.githubusercontent.com/350947/75496103-57605c00-5a14-11ea-9e7e-3360c40bc48c.png)

**Comment by davkean** [comment]
This would be xproj parity, right?

**Comment by ranjan-ranjan** [comment]
opened because of : https://connect.microsoft.com/VisualStudio/feedback/details/3109337/uninstall-package-option-not-present

**Comment by Nirmal4G** [comment]
What's the status of this feature?

I'm only seeing `remove` in the NuGet packages node. Can't remove Analyzers or Ignore/Suppress individually. I also propose similar support for `Analyzers`, `Frameworks` and `SDKs` node.

**Comment by drewnoakes** [comment]
@Nirmal4G we're working to overhaul the context menus on the dependencies tree at the moment. Please see #5798, #5845, #5922.

**Comment by drewnoakes** [comment]
The original issue here appears to be with the legacy project system. I'm sending back to triage as I think this can be closed. We have the ability to remove package references in the dependencies tree.
