### ISSUE TITLE
Modifying launchSettings.json and launching without saving won't pick up changes

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#9169]
## Visual Studio Version

Version 17.8.0 Preview 1.0 [33908.42.main]

## Summary

It's possible for unsaved changes to `launchSettings.json` to be ignored when launching the debugger, even though launching the debugger saves the file. It seems we have a race condition.

## Steps to Reproduce

1. Create a project with launch settings. Perhaps have that project print out its command line arguments to the console.
2. Built it so it's up to date.
3. Open `launchSettings.json` in the JSON editor and modify the command line args.
4. Hit Ctrl+F5 to launch the app

## Expected Behavior

The updated command line arguments are displayed.

## Actual Behavior

The file is changed, but the previous command line arguments are used.

## User Impact

Confusion.

## Analysis

It's possible to work around this by saving the file manually, then waiting a few moments before launching the debugger so that the updated file can be processed.

The problem does not occur when using the Launch Profiles UI, as that updates the file immediately.

**Comment by tmeschter** [comment]
An explanation for the issue and an outline of the fix are in #8293.

**Comment by drewnoakes** [comment]
Closing as a duplicate of #8293.
