### ISSUE TITLE
Additional information for how-to-add-a-new-project-property-page.md needed?

### ISSUE THREAD

**Issue by 0x6d61726b** [dotnet/project-system#9216]
## Visual Studio Version
Microsoft Visual Studio Professional 2019
Version 16.6.4

## Summary
I was following information provided in [how-to-add-a-new-project-property-page.md](https://github.com/dotnet/project-system/blob/main/docs/repo/property-pages/how-to-add-a-new-project-property-page.md) to get a custom project property page for Visual Studio C# projects. For that purpose I created a very simple demo project to verify operation. Unfortunately, I was not able to get the provided example working. Maybe I am missing something important? I even read #7140 and related issues, but did not find a hint either.

## Steps to Reproduce

1. Create a new C# Console Application (.NET Core/Framework does not matter).
2. Follow steps in [how-to-add-a-new-project-property-page.md / Option 1: XAML file on disk](https://github.com/dotnet/project-system/blob/main/docs/repo/property-pages/how-to-add-a-new-project-property-page.md#option-1-xaml-file-on-disk) section.
3. Optional: Instead of loading the .targets file, include the "PropertyPageSchema" code directly into the demo .csproj file.

The resulting demo application can be found here:
[NewProjectPropertyPageDemo.zip](https://github.com/dotnet/project-system/files/12266821/NewProjectPropertyPageDemo.zip)

## Expected Behavior
When right-clicking on C# project and selecting "Properties", the "My Properties" page is shown in the left column of the project properties.

## Actual Behavior
When right-clicking on C# project and selecting "Properties", the "My Properties" page is NOT shown in the left column of the project properties, see:
![screenshot](https://github.com/dotnet/project-system/assets/25281946/71ff4a03-424a-49b4-8d0f-9854b487612c)

## User Impact
Desired functionality for manipulation of custom project properties cannot be implemented.

**Comment by drewnoakes** [comment]
Hi @0x6d61726b,

The new Project Properties UI was introduced in VS2022 and does not exist in VS2019. You won't be able to add project property pages for VS2019. I will update the docs to ensure that's made more clear.

If you experience issues doing this in VS2022, this is the right place for issues so feel free to get in touch here.

Thanks.
