### ISSUE TITLE
Changing target framework can leave unresolved analyzer nodes in dependencies tree

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#9230]
## Visual Studio Version

Version 17.8.0 Preview 2.0 [34014.421.main]

## Steps to Reproduce

1. Create a new .NET 8 console app
2. Edit the project file and change `<TargetFramework>` to `net48`
3. Notice the Analyzers node leaves two unresolved items behind:
   ![image](https://github.com/dotnet/project-system/assets/350947/a48e137e-84c4-43e1-9a0a-8b8ad4a4ddd4)
4. Reloading the project makes these nodes go away:
   ![image](https://github.com/dotnet/project-system/assets/350947/d29546d4-7979-46b4-bea1-ba7468cb223e)

Either the analyzer nodes step three should not be present, or they should be present in step 4. I suspect the former.

**Comment by soumya-ranjan-pratap** [comment]
I'm new to open source and I want to contribute to this issue, Can you please assign this issue to me ? Please.

**Comment by tmeschter** [comment]
@soumya-ranjan-pratap Apologies; on further review is not a good first issue.
