### ISSUE TITLE
For a simple multiple frameworks project visual studio fails to show files that included by TargetFramework.

### ISSUE THREAD

**Issue by deryaza** [dotnet/project-system#9233]
## Visual Studio Version

Version 17.8.0 Preview 1.0

## Summary

For a simple multiple frameworks project visual studio fails to show files that included by TargetFramework.

## Steps to Reproduce

```csproj
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0;net7.0</TargetFrameworks>
		<EnableDefaultItems>false</EnableDefaultItems>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<Compile Include="A.cs" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
		<Compile Include="B.cs" />
	</ItemGroup>
</Project>
```

## Expected Behavior

![image](https://github.com/dotnet/project-system/assets/46353085/64808d9e-ca94-4979-9fbb-e871b05de1a9)

## Actual Behavior

![image](https://github.com/dotnet/project-system/assets/46353085/5da1cb45-8b70-4bc7-bfcf-ce4825d23e93)

**Comment by haileymck** [comment]
I have opened an internal issue to track this with the respective team, and I am closing this here. Thank you!
