### ISSUE TITLE
Allow selection of .NETCore/.NETStandard version during project create.

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#925]
_From @eyalsk on December 1, 2016 0:4_

_Disclaimer: Sorry if this is the wrong place to write it but I've reported this before on uservoice and other places such as msft blogs and nothing was done with it._

This is relevant to all versions of Visual Studio but maybe it can be changed for Visual Studio 15 RTM.

So when we create a new project today in Visual Studio and open the New Project dialog the .NET framework version dropdown appears at the top regardless to the selected template!

Even if I select a C++  project I still see this dropdown, I'm using Visual Studio for many, many years to me it's an annoyance but to new comers it can be totally confusing.

I feel like from a user experience perspective this dropdown needs to be shown only when you select a .NET project template, when you select a .NET Core project I feel it should list all the relevant versions for .NET Core as opposed to all the versions of the full .NET framework that has nothing to do with it.

_Copied from original issue: dotnet/roslyn#15621_

**Comment by davkean** [comment]
_From @Pilchie on December 12, 2016 21:17_

@srivatsn @davkean This is definitely something we should think about after VS 2017.  Should we track it on the project system repo?

**Comment by Pilchie** [comment]
@jmarolf - this is done now, right?

**Comment by Pilchie** [comment]
Also, we want to show the .NET Core version there instead I think.

**Comment by Pilchie** [comment]
Internal bug at [634492](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/634492).

**Comment by davkean** [comment]
Dup'ing this against https://github.com/dotnet/project-system/issues/3577.
