### ISSUE TITLE
StartupObject is saved in project file instead of myapp file.

### ISSUE THREAD

**Issue by melytc** [dotnet/project-system#9262]
Seems like we regressed at some point the storage logic for VB WinForms projects.

The expected behavior is that if we have the Application Framework property enabled, the `StartupObject` property is saved in the myapp file; at this point, the project file has a `StartupObject` value of `WinFormsAppX.My.MyApplication`. Only when it is disabled, we save the actual value on the project file. Here's an example:

![image](https://github.com/dotnet/project-system/assets/8518253/8027ee59-9bad-4ec3-a0fd-ae55d3501d81)

Instead, we are seeing:

![image](https://github.com/dotnet/project-system/assets/8518253/d74b95a2-b192-4ad6-95fc-e16eda8d62ba)

Not sure when this was introduced, but thanks @KlausLoeffelmann for letting us know!

**Comment by melytc** [comment]
From a quick glance, I know why our `StartupObjectValueProvider` is not being picked up: there's a mismatch on the intercepted property and the name of the property on the rule file! The provider expects `StartupObjectVB` but we only have a `StartupObject` property 🙃

**Comment by adamint** [comment]
@melytc do you have any idea the scope of affected users?

cc @kvenkatrajan for priority

**Comment by melytc** [comment]
> @melytc do you have any idea the scope of affected users?
Only affects VB WinForms users, but we haven't received any user reports. Fix will come shortly with unit tests to ensure this doesn't regress.
