### ISSUE TITLE
Show path to package for graph nodes

### ISSUE THREAD

**Issue by davidfowl** [dotnet/project-system#927]
That's the one piece of information I want when I use the property grid:

![image](https://cloud.githubusercontent.com/assets/95136/21123780/9faabaf4-c08f-11e6-876e-a99d06e71145.png)

**Comment by davkean** [comment]
👍

**Comment by abpiskunov** [comment]
For top level packages , it is easy, just define new property in xaml rules and make sure sdk sends metadata.
For GraphNodes (lower levels) i added in-band extensibility point to provide any browsable properties: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/51770?view=content&path=%2Fsrc%2FVMP%2FPlatform%2FGraphModel%2FSource%2FIGraphNodeBrowsablePropertiesProvider.cs  . To Use it we need to update Microsoft.VisualStudio.GraphModel.dll in the package that is referenced by project system solution.

Not sure if i would have time to do it, so just in case adding this solution for next owner.

**Comment by MattGertz** [comment]
Moving to 15.6.  Agreed on usefulness, but the bar has moved up.

**Comment by tmeschter** [comment]
@abpiskunov How would I go about implementing `IGraphNodeBrowsablePropertiesProvider`? Should I just return it from the `DependenciesGraphProvider` implementation of `IGraphProvider.GetExtension<T>(...)`?

**Comment by abpiskunov** [comment]
Yes, that was the plan (in the index you can find how such extensions are used in other places)

**Comment by tmeschter** [comment]
Showing the path for top-level packages is a simple fix so I'll try to get that in for 15.5. Graphs nodes are more complicated and will need to wait.

**Comment by tmeschter** [comment]
Moving the rest of the work out to 15.6.
