### ISSUE TITLE
Run multiple "start new instance" as script

### ISSUE THREAD

**Issue by btbenjamin** [dotnet/project-system#9275]
Hello is it possible to Run multiple "start new instance" as script ?

On my exemple i want to run the project 1, 2, 3, 4 but i always should use the `right click / debug / start new instance` on each project.

Do you know a way to do with script or shortcut ?

![image](https://github.com/dotnet/project-system/assets/98338059/0190ed1b-3dea-41b5-bd7d-ac487ba09247)

In my case the multiple startup project on solution setting is not the best way, because I change project startups very often for debugging purposes.

![image](https://github.com/dotnet/project-system/assets/98338059/3cf9b256-3e40-48d7-a01f-730fee149865)

If you have any advice I'm listening 🥇 

Have nice day

**Comment by tmeschter** [comment]
@btbenjamin What kind of projects are you starting (web applications, desktop applications, etc.)?

**Comment by btbenjamin** [comment]
@tmeschter they are just API project (micro-services)

**Comment by drewnoakes** [comment]
@btbenjamin thanks for the feature request. It's not something that's owned by this repo. Could you please open a feedback ticket (in VS: Help | Send Feedback | Suggest a feature) so that it can be routed to the correct team. Thank you!
