### ISSUE TITLE
Visual Studio 2022 17.7.4 adds migration "designer" files to project with wrong filename case.

### ISSUE THREAD

**Issue by cabal95** [dotnet/project-system#9276]
## Visual Studio Version

17.7.4

## Summary

Basically, we are having the exact same problem as reported in #5956. The only difference, I think, is that we are using EF6 and .NET Framework projects still. When running the `Add-Migration` command from the package manager console, the file that is created is `SomeMigration.Designer.cs`, but it is added to the project file as `SomeMigration.designer.cs`. This causes the build to break on case sensitive file systems used by Linux.

We are trying to build on Linux as part of our migration process to .NET Core / EF Core. The first step of that is going through all our csproj and resx files and fixing all the incorrect filename casing issues. Many of them are our fault (such as creating the file initially with the wrong casing and then fixing it in Explorer but not the csproj file). However, all these migration files seem to be coming from VS2022 rather than us renaming things.

## Steps to Reproduce

1. Clone https://github.com/SparkDevNetwork/Rock
2. Open Rock.sln in VS2022
3. Depending on when you pull, you might need to open Rock.Migrations/Migrations/RockCSharpMigrationsCodeGenerator.cs and set the `IsFrozen` property to `false`.
4. Open the Package Manager Console
5. Run `Add-Migration -Name TestMigration -Project Rock.Migrations`
6. Save All
7. See that the file on disk is created as `xxxxx_TestMigration.Designer.cs` but in the csproj it is referenced as `xxxxx_TestMigration.designer.cs`

No related VS extensions are installed that I can think of that would have this affect. I checked the csproj file in question for any `Remove **` type lines mentioned in the other issue but did not find any.

I know the repo is huge, sorry about that. Please let me know if I can provide further details.

## Expected Behavior

The filename reference in the csproj should match the filename created on disk.

## Actual Behavior

The filename is partially down-cased.

## User Impact

Build works on Windows but then fails on Linux due to "file not found" errors.

**Comment by drewnoakes** [comment]
Thank you for a great bug report. The project in this case is, as you say, a traditional project, which is not opened by the code in this repo.

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Migrations/Rock.Migrations.csproj

The code that opens such projects is internal, and not in GitHub. Could you please create a feedback ticket (Help | Feedback | Report a problem) and include the above detail? If you share the link here, I'll make sure it is routed to the correct team.

**Comment by cabal95** [comment]
@drewnoakes I was afraid that might be the case :), but since the readme mentioned it is built on NET Framework I was hopeful it might be the same library. And the original issue was the only one I found in google that seemed similar to my problem. I have reported via VS feedback and linked to this issue for reference.

Here is the link to to the VS feedback issue: https://developercommunity.visualstudio.com/t/Visual-Studio-2022-1774-adds-migration/10484240?port=1025&fsid=7cb800eb-08b1-4399-9d8c-63064646267c

Feel free to close this unless you want to keep it open for your own tracking purposes, thank you!

**Comment by drewnoakes** [comment]
Thanks @cabal95, I've routed it to the correct team internally.

This repo builds using .NET Framework as Visual Studio's `devenv.exe` is a .NET Framework process. However, this repo only loads SDK-style projects. In your case the project is a traditional `.csproj` file, which is loaded into VS by some internal C++ code, not the code in this repo.

Thanks for taking the time to submit feedback to improve Visual Studio. It's really appreciated.
