### ISSUE TITLE
Stop referencing Microsoft.VisualStudio.Sdk.EmbedInteropTypes

### ISSUE THREAD

**Issue by AArnott** [dotnet/project-system#9286]
Your `Microsoft.VisualStudio.ProjectSystem.Managed` nuget package publicly depends on Microsoft.VisualStudio.Sdk.EmbedInteropTypes, which is deprecated and is an anti-pattern now.
In particular, it's causing problems for partner teams that reference your nuget package by causing their build to attempt to embed assemblies that can no longer be embedded.

![image](https://github.com/dotnet/project-system/assets/3548/9871f8ef-8852-4988-b2f9-5fe504cf66c4)

Please remove these lines:

https://github.com/dotnet/project-system/blob/72e29cfa31292ea959aab1f067fca280aa0d332f/eng/imports/HostAgnostic.props#L62
https://github.com/dotnet/project-system/blob/72e29cfa31292ea959aab1f067fca280aa0d332f/Directory.Packages.props#L52

**Comment by drewnoakes** [comment]
Thanks @AArnott.

Is there a reference about this anti-pattern? I'm wondering if we should also remove this:

https://github.com/dotnet/project-system/blob/72e29cfa31292ea959aab1f067fca280aa0d332f/eng/imports/HostAgnostic.props#L84-L129

**Comment by AArnott** [comment]
Nothing publicly documented, no. We realized as we shared more code with VS for Mac that embedding types in assemblies only works on .NET Framework and .NET *on Windows*. Mono, and .NET on mac/linux, do _not_ support it. This broke sharing code between the two IDEs. So when 64-bit VS came around, we took advantage of the opportunity to reverse our guidance and our SDK to _not_ embed anything at all.

**Comment by drewnoakes** [comment]
Thank you for the context. It seems like nothing will be calling `LinkVSSDKEmbeddableAssemblies` anyway, so I'll push an update to https://github.com/dotnet/project-system/pull/9289 that removes this target.

Is this urgent for 17.8 or is 17.9 fine?

**Comment by japarson** [comment]
> Thank you for the context. It seems like nothing will be calling `LinkVSSDKEmbeddableAssemblies` anyway, so I'll push an update to #9289 that removes this target.
> 
> Is this urgent for 17.8 or is 17.9 fine?

Hi Drew, not urgent for my use case; 17.9 is fine.

**Comment by drewnoakes** [comment]
Thanks @japarson!

**Comment by AArnott** [comment]
No urgent need that I know of either.
