### ISSUE TITLE
Improvement of the disassembly window

### ISSUE THREAD

**Issue by Yoticc** [dotnet/project-system#9293]
Here are a few ideas for innovation in the disassembly window.

When using VS Debugger for native applications, discomfort occurs in these situations:
1. When you disassembly function code and debugging at the same time.
Step into one line in debugger (not in opened function) and the disassembly view address point switches to current debugger point and you have to look again for the function that you had disassembly.
I suggest to add an option to the settings in Tools>Options>Debugging so that you can unlink the debugger and the disassembly window from each other, or add this option to Disassembly>View Options, what will be better if you add a second feature.

2. When you need to open the native code of several functions. 
![image](https://github.com/dotnet/project-system/assets/55879406/bfad55c2-6938-40b4-b55f-87b8f180776e)
VS makes it possible to open memory for several addresses, but doesn't disassembly for many functions.
![image](https://github.com/dotnet/project-system/assets/55879406/3542f735-705b-4748-9150-b30870eb26b1)
I suggest to add simillar listbox for dissasembly

**Comment by drewnoakes** [comment]
@Yoticc thank you for your suggestion. This repository does not own the disassembly view. For that component, please use the following guidance to provide your suggestion.

https://learn.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2022
