### ISSUE TITLE
Improvement of memory and disassembly windows

### ISSUE THREAD

**Issue by Yoticc** [dotnet/project-system#9294]
Here are a few ideas for innovation in the disassembly window.

1. In the current version memory window looks so:
![image](https://github.com/dotnet/project-system/assets/55879406/9b17a253-3d9d-4a2e-99b9-2a27891792b5)
I suggest removing 0x at the beginning of addresses (It already made in disassembly window):
![image](https://github.com/dotnet/project-system/assets/55879406/b699c2fc-819d-4359-a6f2-c4e4d7751b4e)
Also I suggest automatically calculate the maximum memory size of system and remove 100% zeros in addresses. But it would be worth addings a setting for this:
![image](https://github.com/dotnet/project-system/assets/55879406/b0e8833f-a71b-4b5e-a831-5568b7020938)

2. Add a better address parser to the disassembly address textbox
![image](https://github.com/dotnet/project-system/assets/55879406/5a863b59-3096-404c-a228-533599a99a65)
![image](https://github.com/dotnet/project-system/assets/55879406/2fa42a86-aa70-4f43-a662-46e7a9dca351)
Memory can parse "0000000000FFFFFF" and "0x0000000000FFFFFF", but can't parse "FFFFFF"
Disassembly can parse only "0x0000000000FFFFFF", but can't "0000000000FFFFFF" or "FFFFFF"

**Comment by drewnoakes** [comment]
@Yoticc thank you for your suggestion. This repository does not own the disassembly view. For that component, please use the following guidance to provide your suggestion.

https://learn.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2022
