### ISSUE TITLE
[NETSDKE2E][VS64]Error MSB4057 "The target "CollectBuildAccelerationIncompatiblePackageDesignTime" does not exist in the project." displays after creating Windows Application Packaging Project in VS 17.8 preview 6.

### ISSUE THREAD

**Issue by vdanche** [dotnet/project-system#9299]
**Affected Branch:** D17.8 branch
Version 17.8.0 Preview 6.0 [34224.125.d17.8]: [34224.125 S](https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build/results?buildId=8586641&view=results)
Below workload are installed.
.NET desktop development
ASP.NET and web development
Desktop Development with C++
Universal Windows Platform development and C++ (v143) Universal Windows Platform Tools
Visual Studio extension development
.NET Multi-platform App UI development

Repro steps
1.In VS, File->New ->Project->select "Windows Application Packaging Project" to create
2. Check error list after creation is done.

**Expected Result:**
No errors display in error list
**Actual Result:**
Error MSB4057 "The target "CollectBuildAccelerationIncompatiblePackageDesignTime" does not exist in the project." displays
![image](https://github.com/dotnet/project-system/assets/65637796/17645a22-afdf-43ea-a953-70d05e541b27)
dotnet --info
.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.25398
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\

.NET workloads installed:
 [maui-windows]
   Installation Source: VS 17.8.34224.125
   Manifest Version:    8.0.0-rc.2.9373/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34224.125
   Manifest Version:    16.4.8968-net8-rc2/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maccatalyst\16.4.8968-net8-rc2\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34224.125
   Manifest Version:    16.4.8968-net8-rc2/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.ios\16.4.8968-net8-rc2\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.8.34224.125
   Manifest Version:    34.0.0-rc.2.468/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.android\34.0.0-rc.2.468\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: x64
  Commit:       0b25e38ad3

.NET SDKs installed:
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by vdanche** [comment]
Create this bug in dotnet/project-system per the bug's([Bug 1884891](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1884891): [NetSDKE2E][VS64]Error "the target "CollectCopyToOutputDirectoryItemDesignTime" does not exist..."  after opening NPE project on VS 17.8 preview 3.) comment.

**Comment by WenJunJi01** [comment]
This issue also reproduced on Windows ARM64.

**Comment by vdanche** [comment]
in VS17.9 preview 1, the error MSB4057 not displays for Windows Application Packaging Project
![image](https://github.com/dotnet/project-system/assets/65637796/29e25beb-ff2d-47e1-9457-dce9eb5ab4ff)

**Comment by vdanche** [comment]
@drewnoakes Thanks, but want to known which repo it belongs to? Currently it is in "DevDiv\VS Core\Project\CPS" [Bug 1884891](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1884891): [NetSDKE2E][VS64]Error "the target "CollectCopyToOutputDirectoryItemDesignTime" does not exist..." after opening NPE project on VS 17.8 preview 3.)

**Comment by drewnoakes** [comment]
I think the area path contains WAPProj, but I'm in my phone so can't check right now. If you file the bug and link it here, I'll make sure it's routed correctly. Thanks!

**Comment by vdanche** [comment]
This issue not repro on 17.8 preview 6 sign-off build. Thanks
![image](https://github.com/dotnet/project-system/assets/65637796/6a9d090f-abb1-4f5c-8a9d-22e69a471c06)
