### ISSUE TITLE
Dependencies node sometimes doesn't show up

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#939]
1. File -> New Console App (.NET Core)
2. Unload project
3. reload project
4. Repeat until the node is missing (1 out ever 5 or so for me)

Looks like a race.

**Comment by srivatsn** [comment]
Wow are the targets file not getting included somehow? Can you see what msbuild /pp says?

**Comment by davkean** [comment]
Actually, this has nothing to do with the comment - it just happened when I was changing the comment. Looks like there's a race here - if I unload/reload a project over and over, the dependencies node is missing 1 out of ever 5 or 6 reloads.

**Comment by abpiskunov** [comment]
Just tried it with d15rel RC.2 - does not repro. There were no changes in Dependencies tree in RC3 yet. What VS build you have? Van it be related to latest sdk changes?

**Comment by davkean** [comment]
This consistently occurs on any recent build (I installed yesterdays).  I don't have an RC2 build to check.

The resulting project once in this state has a language service, builds and F5s, so I'm guessing it's a race of some kind.

**Comment by davkean** [comment]
Here's an example: 
![image](https://cloud.githubusercontent.com/assets/1103906/21409395/1ec43946-c82e-11e6-8a13-8cd5630d1f03.png)

**Comment by davkean** [comment]
I tried it a few times, by "consistent" I actually mean "inconsistent". It took me 3 reloads to get above, but took me another 10 to get it repro again.

**Comment by davkean** [comment]
Note, if you rename the project in this state, the node comes back.

**Comment by abpiskunov** [comment]
recent build from d15prerel?

**Comment by davkean** [comment]
Yeah.

**Comment by abpiskunov** [comment]
Opened TFS bug 364539 for CPS

I tried repro thisissue and was able to get into that state. Then i attached debugger and renamed project, my break point in the tree provider was hit and i saw that dependency node did exist (it was sent to me by 
SubmitTreeUpdateAsync parameter) and all my sub tree providers nodes existed (Nuget, Projects etc) they were not displayed in the tree though. 

 

It seems like some kind of timing issue during project load - when i attached debugger form the very beginning and tried to repro, i could not repro it again , tried maybe 50 times to unload/reload with debugger attached (project loads much slower in this case and i can even see a label saying that This project is still loading etc)

**Comment by davkean** [comment]
Just to be clear, because there was questions as to whether this was still occuring. I'm still hitting this on today's build:

![image](https://cloud.githubusercontent.com/assets/1103906/22496797/ecbe6604-e8a0-11e6-98b9-810a00c9f34d.png)

**Comment by lifengl** [comment]
@abpiskunov  when you reproduce this bug, can you capture a 32bits heap dump and share with us?  I spent several hours to introduce delays in CPS code, but could not repro.  It is not actionable on our side until we have a solid repro or a dump.

**Comment by davkean** [comment]
I can repro it pretty consistently- I'll add a dump. Give where we are, we're going to punt this to 1.1.

**Comment by davkean** [comment]
I'm repro'ing this pretty consistently with this project: https://github.com/Ponant/ResBugV2.

**Comment by lifengl** [comment]
I will give a try today

Sent from my phone

On Feb 14, 2017, at 1:00 AM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm repro'ing this pretty consistently with this project: https://github.com/Ponant/ResBugV2.

**Comment by Ponant** [comment]
@lifengl , unfortunately this happens; did you try all resx? It will occur at some point.

**Comment by davkean** [comment]
@Ponant Lifeng is referring to the bug around the dependency node not showing up. We've repro'd all your RESX issues and we got bugs tracking them.

**Comment by davkean** [comment]
We've not hit this issue for a long time, going to close it out.
