### ISSUE TITLE
Flaky: New json files in project directories aren't shown in the Solution Explorer consistently

### ISSUE THREAD

**Issue by nkolev92** [dotnet/project-system#9395]
Originally filed: https://github.com/NuGet/Home/issues/9933

1. Create a solution with two projects [e.g. C# Class Library (.NET Core 5.0)] called “CL1” and “CL2” in VS.
1. Make the project graph structure: CL1 -> CL2 and close the solution/VS.
1. Open “Developer Command Prompt”, cd to CL1 project path and input command “dotnet restore -f --use-lock-file”.
1. Open the solution and check the Solution Explorer.

This would create 2 files on the commandline, for each project, packages.lock.json. 

Despite the files *existing* on the disk, they're not consistently shown in the solution explorer. 
This is a flaky behavior.

**Comment by drewnoakes** [comment]
@nkolev92 this request needs to be routed to CPS. I wonder if it's related to their evaluation caching checks. Please file an internal bug under CPS's area path, thanks.
