### ISSUE TITLE
Unexplained warnings while trying to add System.Web reference 

### ISSUE THREAD

**Issue by bbbturan** [dotnet/project-system#9399]
## Visual Studio Version
2022 - Version 17.8.6

## Summary
Hello team, 

I'm experiencing unexplained warning signs in my .NET 8 application, created with Visual Studio 2022, after adding the System.Web library as a COM reference. Additionally, when checking the tree, I observe an ID being displayed instead of the expected package name. 

![image](https://github.com/dotnet/project-system/assets/40633380/6b02779e-e854-41f1-afbc-1dd28d6304ba)

## Steps to Reproduce

1. Create a .NET 8 application using Visual Studio 2022.
2. Add System.Web library as a COM reference.
3. Observe unexplained warning signs.
4. Inspect the tree to find an ID instead of the package name.

**Comment by drewnoakes** [comment]
Are you able to build the project without any errors?

Looking on my machine, I don't see a `System.Web` COM reference:

![image](https://github.com/dotnet/project-system/assets/350947/06facf04-c877-409a-a52f-56a3d486d7b4)

But the following steps do seem to reproduce the issue you're seeing for me:

1. Create a new .NET Console App
2. Right-click the Dependencies node and choose Add COM Reference
3. Search for "System" and select "System.Drawing" (any version)
4. Observe the solution explorer and project file:
   ![image](https://github.com/dotnet/project-system/assets/350947/f65e8071-bcda-4796-b5f4-7df7e43512ec)

The XML added to the project doesn't include a name. 

Building the project produces an error though:

> MSB3290: Failed to create the wrapper assembly for type library "{d37e2a3e-8545-3a39-9f4f-31827c9124ab}". Type library 'System_Drawing' was exported from a CLR assembly and cannot be re-imported as a CLR assembly.

So it seems that this particular COM reference is not supported.

Adding other COM references produces a human-readable name in the `Include` attribute, and no yellow triangle.

**Comment by adamint** [comment]
@bbbturan

**Comment by drewnoakes** [comment]
Closing this site to inactivity. We can reopen if @bbbturan replies.
