### ISSUE TITLE
Hierarchy needs to implement __VSHPROPID5.VSHPROPID_SupportedOutputTypes

### ISSUE THREAD

**Issue by RaulPerez1** [dotnet/project-system#940]
The property is not implemented so the property pages are defaulting to showing Console App/Windows App/Class Library instead of letting the project decide what to show.

**Comment by davkean** [comment]
Yeah, we should drive this from msbuild properties - as it will likely change per TFM/platform.

**Comment by RaulPerez1** [comment]
This needs CPS changes - Currently the handler on CPS does nothing on this case. Two possible options:

1) Have CPS check for a new MsBuild property there so existing users wouldn't be affected.
2) Add a new extensibility point to allow consumers to override properties.

The first option is cheap and low risk while the second one allows for more flexibility for other cases (as far as I know this is the only property that we would need to override).

**Comment by davkean** [comment]
CPS at the time pushed back pretty heavily on the second option, however, I'm not opposed to it. It's exactly what I did when I wrote the portable/phone/uwp flavors: http://index/?leftProject=Microsoft.VisualStudio.ProjectFlavoring&leftSymbol=pilgyyuue3yb&file=Microsoft%5CVisualStudio%5CProjectFlavoring%5CConfiguration%5CIPropertyProvider.cs.
