### ISSUE TITLE
Properties page is blank after close and reopen solution while current tab is not Properties page

### ISSUE THREAD

**Issue by Eudora-Li01** [dotnet/project-system#9405]
## Visual Studio Version

17.10.0 Preview 2.0 [34619.48.main]

## Summary

Properties page is blank after close and reopen solution while current tab is not Properties page.

## Steps to Reproduce

1. Create Winforms .NET Framework project.
2. Right click the project node in Solution Explore and select Properties.
3. Switch to form designer.
4. Close and reopen solution.
5. Open and observe Properties Tab.

https://github.com/dotnet/project-system/assets/130345015/dfc394d4-0717-41f9-a29c-de762efd2874

## Expected Behavior

Properties Page can be opened successfully.

## Actual Behavior

Properties page is blank page.

## More info:
1. In VS 17.10.0 Preview 2.0, it reproduces on ENU, DE and FR languages.
2. In VS 17.10.0 Preview 1.0 and 17.9.0, it reproduces on DE and FR languages, doesn't reproduce on ENU languages.
3. It doesn't reproduce on Winforms .NET Core project., it reproduce on WPF and console Framework projects.

**Comment by Eudora-Li01** [comment]
Verified on VS 17.10.0 Preview 2.0[34626.195.mian], ENU machine and VS, this issue still reproduces. Here is call stack I got:
[Callstacks.txt](https://github.com/dotnet/project-system/files/14413782/Callstacks.txt)

**Comment by haileymck** [comment]
Thank you for filing this issue! Because the project is .NET framework and not .NET core, another team is working a fix. This issue is open on their end, so I am going to close this, and here is the [page](https://developercommunity.visualstudio.com/t/WinForms-NET-Framework:-project-propert/10585969) where they are currently discussing it.
