### ISSUE TITLE
Update Build Acceleration documentation around opt-in/out

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/project-system#9426]
The docs at https://github.com/dotnet/project-system/blob/main/docs/build-acceleration.md explain the feature is currently opt-in, yet we have it on by default in several cases. The docs need to be updated.

**Comment by baramartin** [comment]
![image](https://github.com/user-attachments/assets/3f6b316c-4081-4bb1-95e7-9e89794389db)
We had the same issue 🤦‍♂️

**Comment by drewnoakes** [comment]
Thanks for the ping. Addressed in #9521.
