### ISSUE TITLE
Bubble-up Known Vulnerability Indicators in Solution Explorer for Transitive Packages

### ISSUE THREAD

**Issue by JonDouglas** [dotnet/project-system#9494]
## Summary

NuGet launched a vulnerability auditing feature last year and would like to enhance the experience further with project system help!

Today a user must directly navigate to a transitive package to see a warning produced when `NuGetAuditMode = all`

![image](https://github.com/dotnet/project-system/assets/1288848/fe143c36-4fcd-4c66-9731-1953b7f887d6)

Ideally these warnings would bubble up the entire packages tree similar to what you see with a top-level dependency:

![image](https://github.com/dotnet/project-system/assets/1288848/6a899b95-5142-4634-be5b-e65f2c311122)

At the end of the day, if there is a transitive dependency vulnerability warning, it should show in the `Dependencies` node so the user knows how to spelunk to find the culprit. This will also complement CLI work we did in a command called [`dotnet nuget why`](https://github.com/NuGet/Home/blob/e83e772d7372288fc4475ba8b511dca97768a006/accepted/2022/dotnet-nuget-why-proposal.md) which allows you to do similar.

## User Impact

Many users use the solution explorer to view their dependency tree alongside the newly released [transitive dependencies in visual studio](https://devblogs.microsoft.com/nuget/introducing-transitive-dependencies-in-visual-studio/) functionality that only works for project-level today.

In developer surveys, we found that the solution explorer is one of the most desired places for people to view vulnerability information about their dependencies.

More user impact/motivation can be found in an older proposal that is related more-so to the [iconography of these indicators](https://github.com/NuGet/Home/blob/package-status-indicators/proposed/2022/package-status-indicators.md#motivation)

**Comment by zivkan** [comment]
Turns out the relevant code is in NuGet.Client repo.  Closing this in favour of https://github.com/NuGet/Home/issues/13636
