### ISSUE TITLE
C# Dev Kit popup message is written in an inconsistent and extremely casual style

### ISSUE THREAD

**Issue by jnm2** [dotnet/project-system#9495]
## Visual Studio Version

C# Dev Kit v1.7.27 in Visual Studio Code

## Summary

This message is written in an unexpectedly casual style for software:
![image](https://github.com/dotnet/project-system/assets/8040367/bd89c661-467a-4fb2-982d-834b3d4211fe)

1. It's breaking an English grammar rule by joining two independent clauses with a comma without a conjunction. Shorter sentences can be easier to read, so I would recommend splitting into two sentences.
 
1. It's missing a period. <https://learn.microsoft.com/en-us/windows/win32/uxguide/text-ui#punctuation>:
   > #### Periods
   >
   > - Don't place at the end of control labels, main instructions, or Help links.
   > - Place at the end of supplemental instructions, supplemental explanations, or any other static text that forms a complete sentence.

1. It's an odd choice to capitalize 'Solution' and also an odd choice not to use the branding capitalization for 'intellisense' since that's a proper noun/brand name. <https://learn.microsoft.com/en-us/windows/win32/uxguide/text-ui#capitalization>:
   > - **For feature and technology names, be conservative in capitalizing.** Typically, only major components should be capitalized (using title-style capitalization).
   >
   >   **Correct:**
   >
   >   Analysis Services, cubes, dimensions
   >
   >   Analysis Services is a major component of SQL Server, so title-style capitalization is appropriate; cubes and dimensions are common elements of database analysis software, so it is unnecessary to capitalize them.
   
   See also <https://learn.microsoft.com/en-us/style-guide/grammar/nouns-pronouns#capitalization-and-proper-nouns>, for instance, for why it would be 'solution' and not 'Solution':
   > If there's more than one of a thing, it's a common noun. For example, there are lots of chief operating officers, so _chief operating officer_ is a common noun. There's only one _Chief Operating Officer Latasha Sharp_, so that's a proper noun.
   >
   > Don't capitalize common nouns unless they begin a sentence or the situation calls for title-style capitalization. Most technology concepts, product categories, devices, and features are common nouns, not proper nouns. Examples of common nouns include _cloud computing_, _smartphone_, _e-commerce_, and _open source_.

**Comment by CyrusNajmabadi** [comment]
@tmeschter @dibarbet Is project-system the right location for this?  I couldn't find this in Roslyn.  Thanks!

**Comment by smitpatel** [comment]
Probably CPS side. cc: @lifengl

**Comment by drewnoakes** [comment]
@smitpatel the string comes from the vs-green repo. Does that change your assessment of ownership? https://dev.azure.com/devdiv/DevDiv/_git/vs-green?path=/loc/cs/loc/xliff/enu/csdevkit.xlf.lcl&_a=contents&version=GBmain

**Comment by smitpatel** [comment]
No it doesn't change my assessment. https://dev.azure.com/devdiv/DevDiv/_git/vs-green/commit/5a6514f1ee7689e92eee20f0adcca57df57585a5?refName=refs%2Fheads%2Fmain&path=%2Fsrc%2Fstrings.ts&_a=contents

**Comment by haileymck** [comment]
Created an [internal item](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2221111) to assign to CPS
