### ISSUE TITLE
The console and class library are missing connected services

### ISSUE THREAD

**Issue by Varorbc** [dotnet/project-system#9497]
## Visual Studio Version

17.10

## Summary

The console and class library are missing connected services

![image](https://github.com/dotnet/project-system/assets/5714438/c8cb23af-3ec3-4a3b-86d9-2bee48baa945)

## Expected Behavior

add connected services

## Actual Behavior

missing connected services

**Comment by melytc** [comment]
Hi @Varorbc, please open a feedback ticket at https://developercommunity.visualstudio.com/home or through Visual Studio with "Help | Send Feedback | Report a Problem...". Here's a link with more info: https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022. Thanks!
