### ISSUE TITLE
Project System: We should support setting "ReferenceOutputAssembly" via Properties

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#95]
_From @davkean on March 29, 2016 21:40_

VSIX's allow you to specify ReferenceOutputAssembly via the Properties window, we should do something similar and make it a first-class citizen.

![image](https://cloud.githubusercontent.com/assets/1103906/14124745/1586e576-f5bc-11e5-931d-eecd531b02b5.png)

_Copied from original issue: dotnet/roslyn#10185_

**Comment by rainersigwald** [comment]
I found this especially confusing because when this is set on the project manually, it's displayed correctly:

![image](https://user-images.githubusercontent.com/3347530/27918730-710cf908-6235-11e7-8bf4-77ae92fe625c.png)

And the UI worked to change it _back_, producing

```diff
diff --git a/ReferenceOutputAssemblyFalse/ReferenceOutputAssemblyFalse.csproj b/ReferenceOutputAssemblyFalse/ReferenceOutputAssemblyFalse.csproj
index 388f94e..91ecc91 100644
--- a/ReferenceOutputAssemblyFalse/ReferenceOutputAssemblyFalse.csproj
+++ b/ReferenceOutputAssemblyFalse/ReferenceOutputAssemblyFalse.csproj
@@ -6,7 +6,7 @@
   </PropertyGroup>
 
   <ItemGroup>
-    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" ReferenceOutputAssembly="false" />
+    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" ReferenceOutputAssembly="true" />
   </ItemGroup>
 
 </Project>
```
![image](https://user-images.githubusercontent.com/3347530/27918884-e5fcde90-6235-11e7-9ef8-cc1244e682ab.png)


But then changing it again fails:

![image](https://user-images.githubusercontent.com/3347530/27918913-fe7e0cd2-6235-11e7-9ef7-326589e14d12.png)

```
An error has occurred while saving the edited properties listed below:
	Reference Output Assembly
One or more values are invalid. Specified method is not supported.
```

**Comment by cmclernon-fvs** [comment]
What is the purpose of the "Reference Output Assembly"?  My understanding is that it provides an "implicit" reference to a project but hides the project types from the "main" project (the project doing the referencing).  If this is true then I would expect the referenced project's output to be included in the main projects build output folder. (Including all nuget references)

If I'm correct in my above thinking, has anyone any ideas if/when this might be fixed?  Do I need to raise a new bug/issue?

**Comment by davkean** [comment]
@cmclernon-fvs This is referring to the VS UI experience, that question would be better asked over on http://github.com/microsoft/msbuild.

**Comment by cmclernon-fvs** [comment]
> @cmclernon-fvs This is referring to the VS UI experience, that question would be better asked over on [http://github.com/microsoft/msbuild](https://github.com/microsoft/msbuild).

Thanks @davkean.  I will do that.

Cheers,

Colm

**Comment by davkean** [comment]
This already is exposed and works as expected. @rainersigwald I cannot repro your particular situation.
