### ISSUE TITLE
Searching for NuGet packages in solution explorer no longer works

### ISSUE THREAD

**Issue by zivkan** [dotnet/project-system#9505]
## Visual Studio Version

I tested 17.10 GA, 17.11 public preview, and internal preview channels. None worked for me today.

## Summary

Previously, after enabling "search external files" in Solution Exolorer's search options, it was possible to search for a NuGet package name and it would show any results under the Dependencies node. That's how the screenshots in https://github.com/dotnet/project-system/issues/9494 were taken.

## Steps to Reproduce

1. Create any SDK style project
2. Add a package reference to a package that has dependencies. For example, NuGet.Commands
3. Enable "Search external files" in Solution Explorer's search options
4. Expand the Dependencies node, and find a dependency of that package you installed. For example, Newtonsoft.Json
5. Enter that transitive package ID in the Solution Explorer search

## Expected Behavior

It shows results, as can be seen in https://github.com/dotnet/project-system/issues/9494

## Actual Behavior

No results found.

## User Impact

The NuGet team is documenting this as a way that customers can find why a transitive package is being used by their project.

**Comment by drewnoakes** [comment]
@zivkan isn't this a dupe of https://github.com/NuGet/Home/issues/13619? If so, it was fixed recently.

**Comment by zivkan** [comment]
Oops, in my stress of trying to meet a few deadlines, I forgot that issue/PR exists!  Looks like there was a delay in getting it inserted into VS, which is why Int Preview doesn't have the fix yet.
