### ISSUE TITLE
Cannot add PNG image as WinForms Bitmap, can only add as Icon or WPF byte[]

### ISSUE THREAD

**Issue by mckennabarlow** [dotnet/project-system#9519]
User feedback from Survey Monkey:

"I cannot add a PNG image as WinForms Bitmap. I can only add it as Icon or WPF byte[]. This is what I need: <data name="example" type="System.Resources.ResXFileRef, System.Windows.Forms">
<value>..\Resources\example.png;System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</value></data>"

**Comment by melytc** [comment]
Moved to https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2188244!
