### ISSUE TITLE
Project file is included in `EvaluatedIncludeAsFullPath`, giving an invalid path

### ISSUE THREAD

**Issue by thmskv** [dotnet/project-system#9556]
## Visual Studio Version
17.11.5

## Summary
I am using the project system within a VSIX and recently `IProjectItem.EvaluatedIncludeAsFullPath` has started returning an invalid path. It seems to be  combined with the path for the actual csproj file instead of its parent directory, giving paths like: `c:\code\MyProject\MyProject.csproj\Path\To\File.cs` instead of `c:\code\MyProject\Path\To\File.cs`.

The issue can also be seen when subscribing to changes via `UnconfiguredProject.Services.ActiveConfiguredProjectSubscription.SourceItemsRuleSource.SourceBlock.LinkTo()` and inspecting the `FullPath` key in each item's associated dictionary.

## Steps to Reproduce
1. Get a source item from a configured project instance: `configuredProject.Services.SourceItems.FindItemByNameAsync(@"Path\To\File.cs")`
2. Inspect `EvaluatedIncludeAsFullPath`

## Expected Behavior
Should return the correct full path of the item:
`Path.Combine(Path.GetDirectoryName(configuredProject.UnconfiguredProject.FullPath), projectItem.EvaluatedIncludeAsRelativePath)`

## Actual Behavior
Returns a path including that of the project file:
`Path.Combine(configuredProject.UnconfiguredProject.FullPath, projectItem.EvaluatedIncludeAsRelativePath)`

## User Impact
Requires having to update code with fixes like the expected one above.

**Comment by drewnoakes** [comment]
@thmskv this should be routed to the CPS team, who are not on GitHub.

If you report the problem on Developer Community then link the ticket here, I'll make sure it gets sent to the right people.

https://developercommunity.visualstudio.com/VisualStudio/report

Thanks.

**Comment by drewnoakes** [comment]
Thanks very much. I've routed it to CPS.
