### ISSUE TITLE
Has the build event order changed?

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/project-system#9572]
## Visual Studio Version
VS 2022 17.11.5

## Summary
at some time in the past, the order of these events were (correctly, if you ask me) this:
1. OnBuildBegin
2. ProjectBuildStarted
3. ProjectBuildDone
4. OnBuildDone
but now it is this:
1. ProjectBuildStarted
2. OnBuildBegin
3. ProjectBuildDone
4. OnBuildDone

where OnBuildBegin and OnBuildDone refer to DTE.Events.BuildEvents
where ProjectBuildStarted and ProjectBuildDone refer to VS.Events.BuildEvents (from the VS community toolkit)

This makes my extension stop working properly.

## Expected Behavior
Event order is this:
1. OnBuildBegin
2. ProjectBuildStarted
3. ProjectBuildDone
4. OnBuildDone

## Actual Behavior
Event order is this:
1. ProjectBuildStarted
2. OnBuildBegin
3. ProjectBuildDone
4. OnBuildDone

## User Impact
Context: In my extension, i need to be notified before the msbuild processes have started doing their things, because i modify the .csproj. 
the change of event invocation order broke that.

**Comment by drewnoakes** [comment]
Hi @AdmiralSnyder,

This question needs to be directed to a different team, as build is handled at a higher level than this particular project system (all project systems can participate in build).

Please create a feedback ticket with the above information.

https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

If you link the ticket here I'll make sure it's routed to the correct team internally.

Thanks!

**Comment by AdmiralSnyder** [comment]
@drewnoakes thanks, i created the ticket, but developercommunity doesn't show the created ticket, even after almost 2 hours - is there an issue there, maybe?

**Comment by AdmiralSnyder** [comment]
@drewnoakes i created a new issue: here it is. thanks for your time :-)
https://developercommunity.visualstudio.com/t/extensibility:-did-the-build-event-order/10778723?port=1025&fsid=d7d07e1b-16eb-4d50-9fd8-5ea98878270b

**Comment by drewnoakes** [comment]
Thanks @AdmiralSnyder, I've routed it to the correct team internally.
