### ISSUE TITLE
Visual Studio BUILD Copies DLL from a Referenced Project containing the DLL even when that DLL is Not Consumed in that Referenced Project

### ISSUE THREAD

**Issue by garevaul** [dotnet/project-system#9574]
Hi @rainersigwald 

This may be a Bug in Visual Studio BUILD.

Visual Studio IDE Build Copies DLL from a Referenced Project containing the DLL even when that DLL is Not Consumed in that Referenced Project. **But Powershell DotNet Command Does Not Do That and works fine.**

Because it is a slightly complicated issue, I have created an 8-minute Video Explaining the Issue (attached here).

I have also attached a Sample Visual Studio Project Solution that is explained in the Video.

[MSBuild_Issue_For_Rainer.zip](https://github.com/user-attachments/files/17343981/MSBuild_Issue_For_Rainer.zip)

Video...
https://1drv.ms/f/s!AjNAB3KpbqsErxfCNpurDPIj9iGA?e=LEbbqT

Regards
Bikramjeeth Garevaul

**Comment by drewnoakes** [comment]
Hi @garevaul, thanks for taking the time to research and report this issue so clearly. After some investigation I've created #9575 to track the difference in behaviour here. It'll be a tricky one to fix, so please comment there with more information on your use case to help us understand the impact of the bug.

In the meantime, if this is breaking any important scenarios for you then I recommend adding `<AccelerateBuildsInVisualStudio>false</AccelerateBuildsInVisualStudio>` in any project that you don't want the unreferenced DLL to be copied to.

I'll close this issue and we can continue the discussion in #9575.

Thanks again.
