### ISSUE TITLE
Renaming a file only by case results in a error

### ISSUE THREAD

**Issue by davkean** [dotnet/project-system#958]
1. File -> New Console App (.NET Core)
2. Rename Program.cs -> program.cs 
3. Click Yes when prompted to rename

Expected: For `class Program` -> `class program`
Actual:

Sometimes an error about not being able to rename, other times, nothing happens.

**Comment by jinujoseph** [comment]
Can you check if the behaviour  was #803

**Comment by davkean** [comment]
Why did you close #803?

**Comment by davkean** [comment]
Either way, the error is probably 803, but even after the error future renames don't work.

**Comment by jinujoseph** [comment]
it did not repro in next couple of builds , so was closed as no repro.
but further renames did work. Did you get prompted for rename in future renames ?

**Comment by davkean** [comment]
> Sometimes an error about not being able to rename, other times, nothing happens.

**Comment by srivatsn** [comment]
Is this fixed by your latest PR?

**Comment by jinujoseph** [comment]
no, this is still pending

**Comment by tmeschter** [comment]
Blocked waiting for fixes on the CPS side. See #2852 for details.
