### ISSUE TITLE
Ignore Strong Names

### ISSUE THREAD

**Issue by TactiTac0z** [dotnet/project-system#9599]
I originally posted a question similar to this in the official C# discord channel but sadly never got a response so I will post  something here.
If here isn't an appropriate place to post it please let me know.

Long story short, if an assembly in a nuget package is strong signed (Using \<PackageReference /\>), msbuild will automatically add the packaged assembly as strong named
Is there anyway to disable the strong name enforcement?

My project is referencing an assembly that reference newtonsoft.json (no strong name, which I don't have control over) 
My project reference the Newtonsoft.Json's package on nuget which is strongly named so it will fail to compile even though they are perfectly compatible otherwise.
Some packages on nuget offer strong and non-strong named versions separately but newtonsoft.json does not.

I could edit Newtonsoft.json.dll manually to get rid of the strong name and then manually reupload it somewhere else or stop using nuget but that would be quite clucky for something I feel like I should be able to opt out of.

Surely this can't be an uncommon problem?

**Comment by drewnoakes** [comment]
Not sure this is the right repo. What error message do you get exactly? That might help identify where it belongs.

**Comment by drewnoakes** [comment]
This explains the process:

https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022
