### ISSUE TITLE
Can't add project reference in vs code against my DLL file for microsoft nav , (I'm Creating control addin for nav, can not add the perticular DLL)

### ISSUE THREAD

**Issue by aravinddnivara** [dotnet/project-system#9604]
The dll i need to use there is Microsoft.Dynamics.Framework.UI.Extensibility.dll. I'm unable to take this. It's showing to add a project first. I get it. But how do i add DLL as a project, Or is there any other way

**Comment by drewnoakes** [comment]
Please open an issue in https://github.com/microsoft/vscode-dotnettools/issues

Thank you.
