### ISSUE TITLE
Enable code analysis

### ISSUE THREAD

**Issue by jnm2** [dotnet/project-system#988]
In build 15.0.26014.0:

- _Analyze > Run Code Analysis > On Solution_
  - does nothing
- _Analyze > Configure Code Analysis > For Solution_
  - shows "There are currently no analyzable projects loaded."

**Comment by davkean** [comment]
Thanks - by Code Analysis here, you're looking to use FxCop and not C#/VB's automatic analysis?

**Comment by jnm2** [comment]
Yes, FxCop on a library targeting net20 and netstandard1.3.

**Comment by ulrichb** [comment]
Really milestone 16.0? We need FxCop mainly for CA2000 which has no replacement (I'm aware of). See https://github.com/dotnet/roslyn-analyzers/issues/476.

**Comment by Thieum** [comment]
If you are using custom rules, and custom analyzers as Visual Studio extensions, you need to edit the csproj file and add 

`<CodeAnalysisRuleSet>..\MyCompanyCodeAnalysisRules.ruleset</CodeAnalysisRuleSet>`

in the `PropertyGroup`

to match the behavior of the .net Framework projects. (from https://stackoverflow.com/a/44726528/444469)

Would be nice to be able to edit this property in the project properties, as the analyzers will default to their own configuration without the correct value.

**Comment by drewnoakes** [comment]
Let's review this together in the next triage session.

Running _Analyze > Run Code Analysis > On Solution_ shows that analysis is running in the status bar, but no results are produced. This occurs in both project systems, so I cannot see what action is needed here. I may misunderstand the feature though.

Running _Analyze > Configure Code Analysis > For Solution_ shows:

![image](https://user-images.githubusercontent.com/350947/91779298-7bf1f680-ec38-11ea-8069-6900366b2b37.png)

> NOTE: This property page has been deprecated and will be removed in a future product release. Learn more at https://docs.microsoft.com/visualstudio/code-quality/analyzers-faq#code-analysis-solution-property-page

**Comment by mavasani** [comment]
@drewnoakes That command now runs installed analyzers. Can you try to install an analyzer package to the project and retry?

**Comment by davkean** [comment]
I think we can close this; the FxCop and other source-based analyzers have replaced binary analysis that this used to perform, see: https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-legacy-analysis-to-fxcop-analyzers?view=vs-2019.

**Comment by jnm2** [comment]
Yes, the FxCopAnalyzers package has totally replaced my need for this.
